/* ==========================================================================
   abdomen.ts — fígado e vias biliares, pâncreas, baço, tubo digestivo,
   mesentério e retroperitônio, rim e adrenal. Os císticos do pâncreas só
   pelo revestimento: seroso = cuboide claro glicogênico; NCM = mucinoso com
   estroma ovariano, sem comunicação ductal; IPMN = mucinoso papilífero no
   ducto; linfoepitelial = escamoso queratinizante com manto linfoide;
   escamoide = escamoide sem manto; pseudocisto = nada. Nota: D2-40 marca
   mesotélio e endotélio linfático, não separa linfangioma de cisto
   mesotelial; o par que resolve é CD31 e ERG vs calretinina e WT1.
   Conferido em 2026-09-12.
   ========================================================================== */

import type { Cyst } from '../types'

export const abdomen: Cyst[] = [
  {
    id: 'cisto-biliar-simples',
    frequency: 3,
    name: 'Cisto biliar simples (cisto hepático solitário)',
    aka: ['cisto hepático simples', 'simple hepatic cyst'],
    sites: ['figado'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    lining: 'Epitélio biliar simples, cuboide a colunar baixo, em camada única, com frequência achatado ou desnudado pela distensão.',
    wall: 'Fina camada de colágeno; sem estroma ovariano, sem músculo liso organizado, sem atipia.',
    contents: 'Líquido seroso claro amarelo-citrino; hemorrágico ou turvo se complicado.',
    where: 'Parênquima, mais no lobo direito; unilocular, sem comunicação biliar; mulher adulta, achado incidental.',
    clues: ['Unilocular, parede lisa, sem septos.', 'Ausência absoluta de estroma ovariano subepitelial.'],
    mimics: ['Neoplasia cística mucinosa do fígado: epitélio mucinoso mais estroma ovariano (ER, PR, inibina).', 'Cisto hidático: membrana laminada PAS positiva.', 'Doença policística: múltiplos e hereditária.'],
    sources: ['https://www.pathologyoutlines.com/topic/liversolitarycyst.html'],
  },
  {
    id: 'doenca-policistica-hepatica',
    name: 'Doença policística hepática',
    aka: ['fígado policístico', 'polycystic liver disease'],
    sites: ['figado'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    lining: 'Epitélio biliar cuboide a achatado em camada única, igual ao do cisto simples (malformação da placa ductal).',
    wall: 'Estroma fibroso escasso; complexos de von Meyenburg e fibrose portal associados; sem estroma ovariano.',
    contents: 'Líquido seroso claro.',
    where: 'Múltiplos cistos em ambos os lobos; isolada (PRKCSH, SEC63) ou com rim policístico autossômico dominante; mulheres, crescimento estrogênio-dependente.',
    clues: ['Muitos cistos (mais de 10 a 20) com história familiar ou rins policísticos.'],
    mimics: ['Cistos simples múltiplos: número e contexto genético.', 'Doença de Caroli: comunica com a árvore biliar, contém bile.'],
    sources: ['https://www.pathologyoutlines.com/topic/liverpolycysticliverdisease.html'],
  },
  {
    id: 'cisto-hepatico-ciliado-intestino-anterior',
    frequency: 1,
    name: 'Cisto hepático ciliado do intestino anterior',
    aka: ['ciliated hepatic foregut cyst', 'cisto broncogênico intra-hepático'],
    sites: ['figado'],
    linings: ['respiratorio-ciliado'],
    features: ['cilios', 'celulas-caliciformes', 'musculo-liso', 'metaplasia-escamosa'],
    lining: 'Colunar pseudoestratificado ciliado com caliciformes esparsas; metaplasia escamosa possível. TTF-1 pode ser positivo.',
    wall: 'Quatro camadas: epitélio ciliado, conjuntivo frouxo subepitelial, feixes de músculo liso e cápsula fibrosa externa.',
    contents: 'Material mucoide espesso a seroso.',
    where: 'Subcapsular no segmento IV, unilocular, em geral menor que 4 cm; risco raro de carcinoma escamoso.',
    clues: ['Segmento IV mais epitélio ciliado com músculo liso na parede.'],
    mimics: ['Cisto biliar simples: cuboide sem cílios nem músculo.', 'Cisto broncogênico: extra-hepático, cartilagem.', 'Neoplasia cística mucinosa: estroma ovariano.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4486693/', 'https://www.pathologyoutlines.com/topic/liverforegutcyst.html'],
  },
  {
    id: 'neoplasia-cistica-mucinosa-do-figado',
    frequency: 1,
    name: 'Neoplasia cística mucinosa do fígado',
    aka: ['antigo cistadenoma biliar', 'mucinous cystic neoplasm of the liver'],
    sites: ['figado'],
    linings: ['colunar-mucinoso', 'cuboidal-simples'],
    features: ['estroma-ovariano', 'muco'],
    lining: 'Colunar mucinoso tipo biliar ou foveolar em camada única, podendo ser cuboide ou achatado; papilas e displasia variável.',
    wall: 'Estroma tipo ovariano subepitelial, denso e celular, ER e PR positivos, inibina e calretinina nas células luteinizadas; critério obrigatório da OMS.',
    contents: 'Muco claro a gelatinoso; CA19-9 alto no líquido.',
    where: 'Intra-hepática (lobo esquerdo em mais de 80%), multilocular, sem comunicação com ductos; mulher em torno dos 45 anos.',
    clues: ['Estroma ovariano é o único critério definidor.'],
    mimics: ['Cisto biliar simples: sem mucina nem estroma ovariano.', 'Neoplasia papilar intraductal biliar: comunica com o ducto, sem estroma ovariano.', 'Cisto hidático: membrana laminada.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC13194582/', 'https://www.pathologyoutlines.com/topic/livertumorMCN.html'],
  },
  {
    id: 'cisto-de-coledoco',
    name: 'Cisto de colédoco (malformação cística biliar)',
    aka: ['classificação de Todani I a V', 'doença de Caroli (tipo V)', 'choledochal cyst'],
    sites: ['figado'],
    linings: ['cuboidal-simples', 'colunar-mucinoso'],
    features: ['musculo-liso', 'inflamacao'],
    lining: 'Epitélio biliar colunar simples, muitas vezes desnudado ou ulcerado em crianças maiores e adultos; íntegro e achatado em lactentes.',
    wall: 'Parede fibromuscular espessa com inflamação crônica; metaplasia intestinal ou pilórica e hiperplasia no adulto; sem estroma ovariano.',
    contents: 'Bile.',
    where: 'Via biliar extra-hepática (tipo I, o mais comum) ou intra-hepática (Caroli), em continuidade com a luz biliar; junção pancreatobiliar anômala; risco de colangiocarcinoma.',
    clues: ['Comunicação direta com a árvore biliar: conteúdo de bile.'],
    mimics: ['Cisto biliar simples: não comunica, sem bile.', 'Pseudocisto pancreático da cabeça: sem epitélio.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK557762/'],
  },
  {
    id: 'cistos-peribiliares',
    name: 'Cistos peribiliares',
    aka: ['cistos das glândulas peribiliares', 'peribiliary cysts'],
    sites: ['figado'],
    linings: ['cuboidal-simples'],
    lining: 'Cuboide a colunar baixo de tipo biliar, camada única, originado das glândulas peribiliares.',
    wall: 'Estroma fibroso periductal escasso com glândulas peribiliares residuais e inflamação crônica.',
    contents: 'Líquido seroso claro ou mucinoso.',
    where: 'Hilo e ao longo dos grandes ductos e ramos portais, sem comunicar com a luz biliar; cirrose, hipertensão portal ou doença policística; distribuição em colar de contas.',
    clues: ['Periportal e hilar, comprimem sem comunicar com a via biliar.'],
    mimics: ['Doença de Caroli: comunica, contém bile.', 'Complexos de von Meyenburg: periféricos.', 'Dilatação biliar obstrutiva: contínua com o ducto.'],
    sources: ['https://www.sciencedirect.com/science/article/pii/S2211568415003162'],
  },
  {
    id: 'complexo-de-von-meyenburg',
    frequency: 3,
    name: 'Complexo de von Meyenburg (hamartoma de ductos biliares)',
    aka: ['biliary hamartoma', 'von Meyenburg complex'],
    sites: ['figado'],
    linings: ['cuboidal-simples'],
    features: ['material-eosinofilico'],
    lining: 'Biliar cuboide baixo, brando, revestindo ductos dilatados de contorno anguloso e ramificado.',
    wall: 'Estroma fibroso hialinizado abundante englobando os ductos; sem músculo liso, sem estroma ovariano.',
    contents: 'Bile inspissada ou material eosinofílico.',
    where: 'Múltiplos nódulos menores que 5 a 10 mm, periportais; achado incidental; doença policística e fibrose hepática congênita.',
    clues: ['Nódulos minúsculos periportais em estroma fibroso.'],
    mimics: ['Colangiocarcinoma bem diferenciado: atipia, desmoplasia, infiltração.', 'Adenoma de ductos biliares: sólido, túbulos pequenos sem dilatação.'],
    sources: ['https://www.pathologyoutlines.com/topic/livermeyenburgcomplex.html'],
  },
  {
    id: 'abscesso-hepatico',
    name: 'Abscesso hepático piogênico (simulador de cisto)',
    aka: ['pyogenic liver abscess'],
    sites: ['figado'],
    linings: ['sem-revestimento'],
    features: ['inflamacao'],
    pseudocyst: true,
    lining: 'Nenhum epitélio: cavidade delimitada por granulação e debris necróticos.',
    wall: 'Centro supurativo com neutrófilos, inflamação em organização, fibrose densa, fibroblastos reativos bizarros, hepatócitos reativos na periferia.',
    contents: 'Pus espesso e material necrótico; Klebsiella, E. coli, S. anginosus, anaeróbios.',
    where: 'Lobo direito, único ou múltiplo; via portal, biliar, arterial ou por contiguidade; febre, leucocitose e dor.',
    clues: ['Nenhum epitélio e nenhuma membrana laminada; cultura positiva.'],
    mimics: ['Cisto hidático: membrana laminada, eosinófilos.', 'Abscesso amebiano: pasta de anchova, trofozoítos PAS positivos.', 'Cisto simples infectado: resquícios de epitélio biliar.'],
    sources: ['https://www.pathologyoutlines.com/topic/liverpyogenicabscess.html'],
  },
  {
    id: 'pseudocisto-pancreatico',
    frequency: 3,
    name: 'Pseudocisto pancreático',
    aka: ['pancreatic pseudocyst'],
    sites: ['pancreas', 'mesenterio'],
    linings: ['sem-revestimento'],
    features: ['inflamacao', 'hemossiderina', 'colesterol', 'calcificacao'],
    pseudocyst: true,
    lining: 'Nenhum epitélio, por definição: granulação, histiócitos, células gigantes e fibrina.',
    wall: 'Fibrose madura, granulação, hemossiderina, colesterol, calcificação, necrose gordurosa e saponificação na periferia.',
    contents: 'Líquido turvo, marrom-acinzentado, necrótico-hemorrágico, rico em enzimas; amilase e lipase muito altas, CEA baixo.',
    where: 'Peripancreático (transcavidade dos epíplons) ou intrapancreático, muitas vezes comunicando com o ducto; após pancreatite ou trauma.',
    clues: ['Ausência de epitélio em toda a extensão amostrada.', 'Amilase altíssima e CEA baixo no líquido.'],
    mimics: ['Neoplasia cística mucinosa desnudada: procurar epitélio residual e estroma ovariano; CEA alto.', 'Cisto de retenção: epitélio ductal.', 'IPMN roto: mucina, CEA elevado.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK557594/', 'https://www.pathologyoutlines.com/topic/pancreaspseudocyst.html'],
  },
  {
    id: 'cistadenoma-seroso-do-pancreas',
    frequency: 3,
    name: 'Cistadenoma seroso do pâncreas',
    aka: ['neoplasia cística serosa', 'adenoma microcístico', 'serous cystadenoma'],
    sites: ['pancreas'],
    linings: ['glicogenio-rico', 'cuboidal-simples'],
    features: ['calcificacao'],
    lining: 'Cuboide a achatado em camada única, citoplasma claro rico em glicogênio (PAS positivo, diastase lábil), núcleos redondos uniformes; sem mucina, sem atipia. Inibina, GLUT1, MUC6 e PAX8 positivos; VHL.',
    wall: 'Septos fibrosos finos ricamente capilarizados; cicatriz estrelada central, às vezes calcificada; sem estroma ovariano, sem tecido linfoide.',
    contents: 'Líquido seroso claro, aquoso; CEA e amilase baixos.',
    where: 'Corpo e cauda com leve preferência; microcístico em favo de mel com cicatriz central, ou oligocístico; esporádico ou na síndrome de von Hippel-Lindau.',
    clues: ['Glicogênio intracitoplasmático com mucicarmim negativo separa dos mucinosos.'],
    mimics: ['NCM: colunar mucinoso mais estroma ovariano.', 'IPMN: mucinoso, comunica com o ducto, MUC5AC.', 'Carcinoma renal de células claras metastático: PAX8 nos dois; inibina positiva e CAIX negativa no seroso.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK557432/', 'https://www.pathologyoutlines.com/topic/pancreasserous.html'],
  },
  {
    id: 'neoplasia-cistica-mucinosa-do-pancreas',
    frequency: 3,
    name: 'Neoplasia cística mucinosa do pâncreas',
    aka: ['antigo cistadenoma mucinoso', 'mucinous cystic neoplasm'],
    sites: ['pancreas'],
    linings: ['colunar-mucinoso', 'achatado-inespecifico'],
    features: ['estroma-ovariano', 'muco', 'calcificacao'],
    lining: 'Colunar mucinoso alto tipo gástrico-foveolar em camada única, núcleos basais; cuboide, achatado ou denudado em áreas; displasia de baixo a alto grau.',
    wall: 'Estroma tipo ovariano subepitelial, denso e fusocelular, ER e PR positivos, inibina e calretinina nas células luteinizadas; obrigatório. Cápsula fibrosa espessa, às vezes com calcificação em casca de ovo.',
    contents: 'Muco espesso e viscoso; CEA alto, amilase baixa.',
    where: 'Corpo e cauda em mais de 95%; única, multilocular, sem comunicação com o ducto; mulher de 40 a 50 anos.',
    clues: ['Mulher, corpo e cauda, estroma ovariano, sem comunicação ductal.'],
    mimics: ['IPMN de ramo: comunica com o ducto, sem estroma ovariano.', 'Cistadenoma seroso: claro glicogênico, mucicarmim negativo.', 'Pseudocisto: sem epitélio, amilase alta.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC8885835/'],
  },
  {
    id: 'ipmn',
    frequency: 3,
    name: 'Neoplasia mucinosa papilar intraductal (IPMN)',
    aka: ['tumor produtor de mucina intraductal', 'intraductal papillary mucinous neoplasm'],
    sites: ['pancreas'],
    linings: ['colunar-mucinoso'],
    features: ['muco', 'celulas-caliciformes'],
    lining: 'Colunar mucinoso papilífero, subtipado: gástrico (foveolar, mucina apical, MUC5AC e MUC6), intestinal (papilas vilosas com caliciformes, MUC2 e CDX2) ou pancreatobiliar (papilas complexas, células cuboides com nucléolo, MUC1).',
    wall: 'Parede do próprio ducto com pancreatite obstrutiva e atrofia acinar; nunca estroma ovariano.',
    contents: 'Mucina abundante saindo pela papila (boca de peixe); CEA e amilase altos.',
    where: 'Ducto principal, ramos secundários (cabeça e uncinado) ou misto; por definição comunica com o sistema ductal; KRAS e GNAS (GNAS quase exclusivo de IPMN).',
    clues: ['Comunicação com o ducto e mucina pela papila.', 'Ducto principal acima de 5 mm.'],
    mimics: ['NCM: não comunica, estroma ovariano, corpo e cauda.', 'Cisto de retenção: epitélio plano sem papilas nem displasia.', 'Neoplasia papilar intraductal oncocítica: citoplasma oncocítico com nucléolo, luzes intraepiteliais, fusões PRKACA.'],
    sources: ['https://www.nature.com/articles/modpathol201693', 'https://www.pathologyoutlines.com/topic/pancreasipmn.html'],
  },
  {
    id: 'neoplasia-papilar-intraductal-oncocitica',
    frequency: 1,
    name: 'Neoplasia papilar intraductal oncocítica (IOPN)',
    aka: ['antigo IPMN oncocítico', 'intraductal oncocytic papillary neoplasm'],
    sites: ['pancreas'],
    linings: ['oncocitico'],
    features: ['muco'],
    lining: 'Oncocítico: células colunares ou poligonais com citoplasma eosinofílico granular abundante, nucléolo único proeminente, em papilas arborescentes com luzes intraepiteliais. MUC6, MUC5AC, Hep Par-1 e CD117 positivos; fusões PRKACA ou PRKACB.',
    wall: 'Parede ductal fibrosa; sem estroma ovariano; displasia em geral de alto grau.',
    contents: 'Mucina escassa a moderada.',
    where: 'Intraductal, ducto principal e ramos, mais na cabeça; entidade própria na OMS desde 2019.',
    clues: ['Nucléolo proeminente, citoplasma oncocítico e luzes intraepiteliais.'],
    mimics: ['IPMN pancreatobiliar: sem oncocitose, MUC1.', 'Neoplasia tubulopapilar intraductal: túbulos sólidos sem mucina.', 'TNE oncocítico: cromogranina e sinaptofisina.'],
    sources: ['https://www.pathologyoutlines.com/topic/pancreasiopn.html'],
  },
  {
    id: 'cisto-linfoepitelial-do-pancreas',
    frequency: 1,
    name: 'Cisto linfoepitelial do pâncreas',
    aka: ['lymphoepithelial cyst of the pancreas'],
    sites: ['pancreas'],
    linings: ['linfoepitelial', 'escamoso-queratinizado'],
    features: ['estroma-linfoide', 'queratina-lamelar'],
    lining: 'Escamoso estratificado maduro queratinizante, sem atipia; focos cuboides ou transicionais e, raramente, sebáceas ou células mucinosas.',
    wall: 'Faixa de tecido linfoide denso subepitelial com centros germinativos; trabéculas fibrosas.',
    contents: 'Material queratinoso caseoso, cremoso a granular; CA19-9 pode subir no líquido.',
    where: 'Exofítico, peripancreático, projetando-se da superfície; homens de meia-idade (4:1); totalmente benigno.',
    clues: ['Escamoso queratinizante com manto linfoide e centros germinativos em homem.'],
    mimics: ['Cisto epidermoide em baço acessório intrapancreático: polpa esplênica na parede, CD8 nos sinusoides.', 'Cisto dermoide: anexos cutâneos, sem manto linfoide.', 'Carcinoma escamoso cístico: atipia, desmoplasia.'],
    sources: ['https://www.nature.com/articles/3880553', 'https://www.pathologyoutlines.com/topic/pancreaslymphoepithelial.html'],
  },
  {
    id: 'cisto-escamoide-dos-ductos-pancreaticos',
    frequency: 1,
    name: 'Cisto escamoide dos ductos pancreáticos',
    aka: ['squamoid cyst of pancreatic ducts'],
    sites: ['pancreas'],
    linings: ['escamoso-nao-queratinizado', 'urotelial', 'achatado-inespecifico'],
    features: ['material-eosinofilico'],
    lining: 'Escamoide: de células achatadas a transicional e escamoso estratificado não queratinizante; sem granulosa, sem paraqueratose, sem células mucinosas altas nem acinares. MUC6 e p63 positivos.',
    wall: 'Fibrose delgada; sem agregados linfoides, sem tecido esplênico, sem estroma ovariano, sem anexos.',
    contents: 'Secreções acinares acidófilas formando concreções laminadas características.',
    where: 'Intrapancreático, unilocular, em média 1,5 cm; dilatação cística de ducto nativo.',
    clues: ['Concreções acidófilas na luz e ausência dos quatro elementos negativos.'],
    mimics: ['Cisto linfoepitelial: queratinização mais manto linfoide.', 'Cisto dermoide: anexos.', 'Cisto epidermoide em baço acessório: parênquima esplênico.'],
    sources: ['https://www.pathologyoutlines.com/topic/pancreassquamoidcyst.html', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4323429/'],
  },
  {
    id: 'cisto-de-retencao-pancreatico',
    name: 'Cisto de retenção pancreático',
    aka: ['cisto simples do pâncreas', 'retention cyst'],
    sites: ['pancreas'],
    linings: ['cuboidal-simples'],
    lining: 'Epitélio ductal nativo, cuboide a colunar baixo, às vezes achatado, sem displasia e sem papilas.',
    wall: 'Estroma fibroso periductal com pancreatite obstrutiva e atrofia acinar; sem estroma ovariano, sem tecido linfoide.',
    contents: 'Secreção pancreática clara ou levemente mucoide.',
    where: 'A montante de obstrução ductal (cálculo, estenose, mucina, tumor): um segmento de ducto dilatado.',
    clues: ['Continuidade com o ducto obstruído; epitélio plano e monótono.', 'Obriga a excluir tumor obstrutivo a montante.'],
    mimics: ['IPMN de ramo: mucinoso papilífero, GNAS e KRAS.', 'Pseudocisto: sem epitélio.'],
    sources: ['https://meridian.allenpress.com/aplm/article/133/3/423/460742/Pancreatic-Cysts-Pathologic-Classification'],
  },
  {
    id: 'tumor-neuroendocrino-cistico-do-pancreas',
    frequency: 1,
    name: 'Tumor neuroendócrino cístico do pâncreas',
    aka: ['cystic pancreatic neuroendocrine tumour'],
    sites: ['pancreas'],
    linings: ['sem-revestimento'],
    features: ['celulas-neuroendocrinas'],
    lining: 'Não é epitélio de revestimento: faixa periférica de células neuroendócrinas neoplásicas monomórficas, cromatina em sal e pimenta, em trabéculas ou ninhos. Cromogranina e sinaptofisina positivas.',
    wall: 'Cápsula fibrosa delgada por dentro da qual está a faixa tumoral; hemorragia e hialinização.',
    contents: 'Líquido claro a amarelo-pálido, não mucinoso; CEA baixo.',
    where: 'Qualquer segmento, leve predomínio em corpo e cauda; realce hipervascular arterial; NEM1 quando múltiplos.',
    clues: ['Cromogranina e sinaptofisina na faixa que reveste o cisto.'],
    mimics: ['NCM: mucinoso com estroma ovariano.', 'Pseudocisto: sem revestimento celular algum.', 'Neoplasia sólida pseudopapilar: beta-catenina nuclear, E-caderina perdida, cromogranina negativa.'],
    sources: ['https://www.pathologyoutlines.com/topic/pancreascysticendocrine.html'],
  },
  {
    id: 'neoplasia-solida-pseudopapilar',
    name: 'Neoplasia sólida pseudopapilar do pâncreas (cística)',
    aka: ['tumor de Frantz', 'solid pseudopapillary neoplasm'],
    sites: ['pancreas'],
    linings: ['sem-revestimento'],
    features: ['sangue', 'colesterol', 'calcificacao'],
    pseudocyst: true,
    lining: 'Sem revestimento epitelial: os espaços resultam de degeneração; as pseudopapilas são eixos fibrovasculares com várias camadas de células discoesas monótonas, sulcos nucleares, citoplasma vacuolado e glóbulos hialinos PAS positivos.',
    wall: 'Cápsula fibrosa espessa com hemorragia, colesterol, macrófagos xantomatosos e calcificação; estroma mixoide ou hialino nos eixos.',
    contents: 'Material hemorrágico e necrótico semiliquefeito.',
    where: 'Corpo e cauda com leve predomínio; mulher jovem (2ª e 3ª décadas).',
    clues: ['Beta-catenina nuclear difusa com perda de E-caderina de membrana (CTNNB1); CD10, CD56 e RP positivos, cromogranina negativa.'],
    mimics: ['TNE cístico: cromogranina positiva, beta-catenina de membrana.', 'Pancreatoblastoma: corpúsculos escamoides, criança.', 'NCM: mucinoso com estroma ovariano.'],
    sources: ['https://www.pathologyoutlines.com/topic/pancreassolidpseudo.html'],
  },
  {
    id: 'cisto-epidermoide-do-baco',
    frequency: 1,
    name: 'Cisto epidermoide do baço (cisto epitelial esplênico)',
    aka: ['cisto esplênico primário verdadeiro', 'splenic epidermoid cyst'],
    sites: ['baco'],
    linings: ['escamoso-nao-queratinizado', 'escamoso-queratinizado', 'mesotelial', 'cuboidal-simples'],
    features: ['colesterol'],
    lining: 'Escamoso estratificado, com frequência não queratinizante; pode ser cuboide, achatado tipo mesotelial ou raramente mucossecretor; origem mesotelial com metaplasia escamosa.',
    wall: 'Parede fibrosa com trabeculações e bandas espessas recobertas por epitélio; sem manto linfoide organizado.',
    contents: 'Líquido proteináceo amarelado, às vezes com queratina e colesterol.',
    where: 'Parênquima, unilocular e volumoso; adolescentes e adultos jovens; CA19-9 e CEA podem subir sem malignidade.',
    clues: ['Revestimento celular presente (cisto verdadeiro) e face interna trabeculada.'],
    mimics: ['Pseudocisto esplênico: nenhum revestimento, parede calcificada, trauma.', 'Cisto hidático: membrana laminada.', 'Linfangioma esplênico: endotélio CD31 positivo, calretinina negativa.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC10938603/'],
  },
  {
    id: 'pseudocisto-esplenico',
    name: 'Pseudocisto esplênico',
    aka: ['cisto esplênico secundário', 'cisto pós-traumático', 'splenic pseudocyst'],
    sites: ['baco'],
    linings: ['sem-revestimento'],
    features: ['calcificacao', 'hemossiderina', 'colesterol'],
    pseudocyst: true,
    lining: 'Nenhum revestimento epitelial ou endotelial em toda a extensão amostrada (amostrar amplamente antes de afirmar).',
    wall: 'Fibrose densa espessa com calcificação distrófica, hemossiderina, colesterol e inflamação crônica.',
    contents: 'Líquido seroso, hemorrágico antigo ou achocolatado; debris.',
    where: 'Cerca de 75 a 80% dos cistos esplênicos não parasitários; trauma, infarto, malária, tuberculose ou mononucleose; parede espessa e calcificada na TC.',
    clues: ['Ausência de revestimento é o critério.'],
    mimics: ['Cisto epidermoide do baço: revestimento escamoso, parede trabeculada.', 'Cisto hidático: membrana laminada e protoescólices.', 'Hematoma organizado: ruptura recente.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC9950349/'],
  },
  {
    id: 'cisto-de-duplicacao-gastrointestinal',
    name: 'Cisto de duplicação gastrointestinal',
    aka: ['duplicação entérica', 'duplicação gástrica, ileal, colônica', 'enteric duplication cyst'],
    sites: ['tubo-digestivo', 'mesenterio', 'esofago'],
    linings: ['colunar-mucinoso', 'respiratorio-ciliado', 'escamoso-nao-queratinizado'],
    features: ['musculo-liso', 'celulas-caliciformes'],
    lining: 'Mucosa gastrointestinal: foveolar gástrica (a mais comum, mesmo fora do estômago), intestinal delgada ou colônica; focos ciliados ou escamosos possíveis.',
    wall: 'Camadas de músculo liso próprias e organizadas com plexo mioentérico; submucosa e serosa; pâncreas heterotópico possível.',
    contents: 'Muco; secreção ácida com ulceração e sangramento se há mucosa gástrica.',
    where: 'Íleo distal na borda mesentérica e estômago na grande curvatura; intramural ou justaposto, compartilhando parede e vasos; no mesentério pode estar isolado com pedículo próprio.',
    clues: ['Mucosa digestiva mais músculo liso organizado mais adesão ao tubo.', 'Assinatura de alça de cinco camadas na ultrassonografia.'],
    mimics: ['Linfangioma mesentérico: endotélio, sem músculo liso organizado.', 'Cisto broncogênico abdominal: ciliado com cartilagem.', 'Pâncreas heterotópico cístico: ácinos e ilhotas.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC4145475/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6221613/'],
  },
  {
    id: 'pancreas-heterotopico-cistico',
    name: 'Pâncreas heterotópico com alteração cística',
    aka: ['pâncreas ectópico com cisto de retenção', 'heterotopic pancreas'],
    sites: ['tubo-digestivo'],
    linings: ['cuboidal-simples', 'sem-revestimento'],
    features: ['musculo-liso', 'inflamacao'],
    lining: 'Epitélio ductal pancreático cuboide a colunar revestindo ductos dilatados (cisto de retenção); os pseudocistos associados não têm revestimento.',
    wall: 'Ácinos, ductos e, conforme o tipo de Heinrich, ilhotas; fibrose, inflamação e hipertrofia de músculo liso.',
    contents: 'Secreção pancreática ou mucoide; debris no pseudocisto.',
    where: 'Submucosa e muscular do antro (grande curvatura), duodeno e jejuno proximal; lesão subepitelial com umbilicação central.',
    clues: ['Ácinos ou ilhotas na parede do cisto.'],
    mimics: ['Cisto de duplicação gástrica: mucosa e músculo organizado, sem ácinos.', 'Gastrite cística profunda: glândulas foveolares deslocadas após cirurgia.', 'GIST cístico: DOG1 e CD117.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC7503788/'],
  },
  {
    id: 'colite-cistica-profunda',
    name: 'Colite cística profunda',
    aka: ['gastrite e enterite cística profunda (análogos)', 'colitis cystica profunda'],
    sites: ['tubo-digestivo', 'retrorretal'],
    linings: ['colunar-mucinoso', 'achatado-inespecifico'],
    features: ['muco', 'hemossiderina', 'celulas-caliciformes'],
    lining: 'Epitélio colônico benigno mucinoso, colunar a achatado, camada única, sem atipia; lagos de mucina sem revestimento onde rompe.',
    wall: 'Lâmina própria acompanhando as glândulas deslocadas (o achado chave), fibrose, hemossiderina; hiperplasia fibromuscular da lâmina própria na úlcera retal solitária.',
    contents: 'Mucina inspissada.',
    where: 'Reto e sigmoide, cistos abaixo da muscular da mucosa, na submucosa; prolapso retal e esforço evacuatório, radioterapia ou cirurgia.',
    clues: ['Glândulas deslocadas cercadas por lâmina própria e hemossiderina, sem desmoplasia.'],
    mimics: ['Adenocarcinoma mucinoso: atipia, desmoplasia, glândulas infiltrativas sem lâmina própria.', 'Endometriose retal: estroma endometrial CD10.'],
    sources: ['https://www.pathologyoutlines.com/topic/coloncystitiscystica.html'],
  },
  {
    id: 'cisto-de-glandula-anal',
    frequency: 1,
    name: 'Cisto de glândula anal',
    aka: ['cisto do ducto anal', 'anal gland cyst'],
    sites: ['retrorretal', 'tubo-digestivo'],
    linings: ['colunar-nao-ciliado', 'urotelial', 'colunar-mucinoso', 'escamoso-nao-queratinizado'],
    features: ['muco'],
    lining: 'Tipo ducto anal: colunar pseudoestratificado ou transicional com células mucossecretoras; pode ser cuboide, achatado ou focalmente escamoso.',
    wall: 'Estroma fibroso delgado com glândulas anais residuais e inflamação crônica; sem músculo liso em camadas, sem estroma ovariano.',
    contents: 'Muco.',
    where: 'Parede do canal anal, espaço interesfincteriano e perianal; nasce das glândulas que drenam nas criptas da linha denteada.',
    clues: ['Interesfincteriano com mucina mucicarmim positiva; comunicação com o ducto anal fecha o diagnóstico.'],
    mimics: ['Cisto do intestino caudal: multilocular, epitélios múltiplos, músculo desorganizado, retrorretal.', 'Adenocarcinoma de glândula anal: atipia, infiltração.', 'Cisto epidermoide perianal: escamoso com granulosa.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC13485457/'],
  },
  {
    id: 'cisto-do-intestino-caudal',
    frequency: 1,
    name: 'Cisto do intestino caudal (hamartoma cístico retrorretal)',
    aka: ['tailgut cyst', 'retrorectal cystic hamartoma'],
    sites: ['retrorretal'],
    linings: ['escamoso-nao-queratinizado', 'escamoso-queratinizado', 'urotelial', 'colunar-mucinoso', 'respiratorio-ciliado', 'cuboidal-simples'],
    features: ['musculo-liso', 'muco', 'cilios'],
    lining: 'Vários epitélios na mesma lesão: escamoso (queratinizado ou não), transicional, colunar simples, colunar mucossecretor e pseudoestratificado ciliado.',
    wall: 'Feixes desorganizados de músculo liso, sem muscular própria verdadeira e sem plexo mioentérico; tecido fibroso e adiposo; sem cartilagem.',
    contents: 'Material mucoide espesso, às vezes queratinoso; pus se infectado.',
    where: 'Espaço retrorretal pré-sacral, multilocular; mulheres de meia-idade (3 a 4:1); até um quarto desenvolve neoplasia (adenocarcinoma, TNE, carcinoma escamoso).',
    clues: ['Epitélios heterogêneos mais músculo liso desorganizado sem plexo.'],
    mimics: ['Duplicação retal: muscular própria completa com plexo, mucosa colorretal única.', 'Cisto epidermoide ou dermoide: só escamoso, com ou sem anexos.', 'Teratoma sacrococcígeo: três folhetos.'],
    sources: ['https://www.pathologyoutlines.com/topic/anustailgutcyst.html', 'https://onlinelibrary.wiley.com/doi/10.1111/his.14769'],
  },
  {
    id: 'duplicacao-retal',
    frequency: 1,
    name: 'Cisto de duplicação retal',
    aka: ['rectal duplication cyst'],
    sites: ['retrorretal', 'tubo-digestivo'],
    linings: ['colunar-mucinoso', 'escamoso-nao-queratinizado', 'urotelial'],
    features: ['musculo-liso', 'celulas-caliciformes'],
    lining: 'Mucosa colorretal (colunar com criptas e caliciformes); mucosa gástrica heterotópica ou epitélio escamoso ou transicional na transição anal.',
    wall: 'Todas as camadas da parede do intestino grosso, com muscular própria em duas camadas e plexo mioentérico.',
    contents: 'Muco; secreção ácida se há mucosa gástrica.',
    where: 'Retrorretal pré-sacral, aderido à parede retal e compartilhando músculo e vasos; unilocular; lactentes e crianças.',
    clues: ['Unilocular com muscular própria completa e plexo.'],
    mimics: ['Cisto do intestino caudal: multilocular, epitélios múltiplos, músculo desorganizado.', 'Meningocele anterior: defeito sacral, meningotelial EMA positivo.'],
    sources: ['https://onlinelibrary.wiley.com/doi/10.1111/his.14769'],
  },
  {
    id: 'cisto-mulleriano-retroperitoneal',
    frequency: 1,
    name: 'Cisto mülleriano retroperitoneal',
    aka: ['cisto ciliado de diferenciação mülleriana', 'Müllerian cyst'],
    sites: ['mesenterio', 'mediastino'],
    linings: ['ciliado-mulleriano'],
    features: ['cilios', 'estroma-endometrial'],
    lining: 'Tipo tubário: colunar ciliado alternando com secretoras e intercalares, camada única; PAX8, ER, PR e WT1 positivos.',
    wall: 'Estroma fibroso delgado, às vezes com estroma endometrial ou músculo liso escasso; sem cartilagem, sem glândulas seromucosas.',
    contents: 'Líquido seroso claro.',
    where: 'Retroperitônio (também mediastino posterior); unilocular, mulheres na perimenopausa.',
    clues: ['Ciliado tubário com PAX8, ER e PR positivos (PAX8 negativo no broncogênico).'],
    mimics: ['Cisto broncogênico retroperitoneal: ciliado com cartilagem ou glândulas seromucosas, PAX8 negativo.', 'Cisto mesotelial: calretinina e WT1, PAX8 negativo, não ciliado.', 'Cisto hepático ciliado do intestino anterior: intra-hepático, músculo liso em camada.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC4215971/'],
  },
  {
    id: 'cisto-renal-simples',
    frequency: 3,
    name: 'Cisto renal simples',
    aka: ['cisto cortical simples', 'Bosniak I', 'simple renal cyst'],
    sites: ['rim'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['calcificacao'],
    lining: 'Epitélio tubular simples, cuboide baixo a achatado, camada única, sem atipia, sem estratificação, sem papilas.',
    wall: 'Parede fibrosa fina, às vezes hialinizada ou calcificada; parênquima comprimido; sem estroma ovariano.',
    contents: 'Líquido seroso claro cor de palha.',
    where: 'Córtex, unilocular, solitário ou em pequeno número; prevalência cresce com a idade.',
    clues: ['Unilocular, sem septos nem nódulos; revestimento monótono sem células claras.'],
    mimics: ['Neoplasia renal cística multilocular de baixo potencial de malignidade: multilocular com células claras de baixo grau.', 'Doença cística adquirida: diálise, cristais de oxalato.', 'Rim policístico: múltiplos e bilaterais.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK499900/'],
  },
  {
    id: 'doenca-renal-policistica-autossomica-dominante',
    frequency: 3,
    name: 'Doença renal policística autossômica dominante',
    aka: ['rim policístico do adulto', 'PKD1 e PKD2', 'ADPKD'],
    sites: ['rim'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['inflamacao', 'sangue'],
    lining: 'Epitélio tubular variável com o segmento de origem, de achatado a cuboide ou cilíndrico, camada única; hiperplasia focal e micropólipos sem atipia franca.',
    wall: 'Membrana basal tubular espessada, fibrose intersticial e inflamação crônica entre os cistos; parênquima comprimido.',
    contents: 'Líquido claro; hemorrágico ou turvo se complicado.',
    where: 'Ambos os rins, muito aumentados e difusamente substituídos; cistos hepáticos e pancreáticos, aneurismas intracranianos; história familiar.',
    clues: ['Bilateral, difuso e maciço com cistos hepáticos.'],
    mimics: ['Doença cística adquirida: rins pequenos, oxalato, diálise.', 'Rim displásico multicístico: unilateral, ductos primitivos com colar fibromuscular.', 'Esclerose tuberosa e VHL: angiomiolipomas, carcinoma de células claras.'],
    sources: ['https://www.pathologyoutlines.com/topic/kidneytumoradultpkd.html'],
  },
  {
    id: 'doenca-cistica-adquirida-do-rim',
    name: 'Doença cística adquirida do rim',
    aka: ['doença cística da diálise', 'acquired cystic kidney disease'],
    sites: ['rim'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['sangue', 'calcificacao'],
    lining: 'Cuboide baixo a achatado, com hiperplasia, pseudopapilas, aumento nuclear e perda de polaridade; borda em escova em alguns cistos.',
    wall: 'Fibrose com inflamação crônica; cristais de oxalato de cálcio birrefringentes intratubulares e intracísticos, muito característicos.',
    contents: 'Líquido claro; hemorrágico com frequência.',
    where: 'Ambos os rins, pequenos e atróficos, em doença renal terminal e diálise prolongada (cerca de 90% após 8 anos); risco de carcinoma associado à doença cística adquirida.',
    clues: ['Cristais de oxalato mais contexto de diálise.'],
    mimics: ['Rim policístico: rins enormes, história familiar.', 'Carcinoma de células renais associado à doença cística adquirida: massa sólida, cribriforme, oxalato no tumor.'],
    sources: ['https://www.pathologyoutlines.com/topic/kidneytumoracquiredcyst.html'],
  },
  {
    id: 'nefroma-cistico',
    frequency: 1,
    name: 'Nefroma cístico',
    aka: ['nefroma cístico multilocular', 'família dos tumores mistos epiteliais e estromais', 'cystic nephroma'],
    sites: ['rim'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['estroma-ovariano'],
    lining: 'Camada única achatada, cuboide ou em tachinha, com células eosinofílicas protruindo na luz, sem atipia; CK7 e PAX8 positivos.',
    wall: 'Septos fibrosos com estroma tipo ovariano, fusocelular e celular, ER e PR positivos; sem blastema, sem nódulos sólidos expansivos.',
    contents: 'Líquido seroso claro.',
    where: 'Massa multilocular bem delimitada com pseudocápsula, podendo herniar na pelve; mulheres na perimenopausa e crianças menores de 2 anos (forma pediátrica com DICER1).',
    clues: ['Estroma ovariano nos septos e nenhum blastema.'],
    mimics: ['Nefroblastoma cístico parcialmente diferenciado: blastema nos septos, o único critério que os separa.', 'Neoplasia cística multilocular de baixo potencial de malignidade: revestimento de células claras, septos sem estroma ovariano.', 'Tumor misto epitelial e estromal: componente sólido mais proeminente.'],
    sources: ['https://www.pathologyoutlines.com/topic/kidneytumorcysticnephroma.html'],
  },
  {
    id: 'nefroblastoma-cistico-parcialmente-diferenciado',
    frequency: 1,
    name: 'Nefroblastoma cístico parcialmente diferenciado',
    aka: ['tumor de Wilms cístico parcialmente diferenciado', 'cystic partially differentiated nephroblastoma'],
    sites: ['rim'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    lining: 'Camada única achatada, cuboide ou em tachinha, indistinguível do nefroma cístico: o revestimento não os separa.',
    wall: 'Septos com blastema em qualquer quantidade, com ou sem túbulos primitivos e mesênquima; WT1 no blastema; sem nódulos sólidos expansivos.',
    contents: 'Líquido seroso claro.',
    where: 'Massa multicística composta inteiramente por cistos e septos; menores de 2 anos, leve predomínio masculino; nefrectomia costuma curar.',
    clues: ['Blastema nos septos: exige amostragem extensa.'],
    mimics: ['Nefroma cístico: sem blastema, estroma ovariano.', 'Tumor de Wilms cístico: nódulos sólidos expansivos.', 'Rim displásico multicístico: ductos primitivos com colar fibromuscular, cartilagem.'],
    sources: ['https://www.pathologyoutlines.com/topic/kidneytumorcysticnephroblastoma.html'],
  },
  {
    id: 'rim-displasico-multicistico',
    name: 'Rim displásico multicístico',
    aka: ['displasia renal multicística', 'multicystic dysplastic kidney'],
    sites: ['rim'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['cartilagem', 'musculo-liso'],
    lining: 'Cuboide baixo a achatado em camada única nos cistos; ductos primitivos com epitélio colunar a cuboide indiferenciado.',
    wall: 'Ductos primitivos cercados por colar fibromuscular concêntrico (o achado definidor), cartilagem metaplásica, nervos e vasos dismórficos, hematopoese; sem arquitetura nefronal normal.',
    contents: 'Líquido seroso claro.',
    where: 'Em geral unilateral, todo o rim em cacho de uvas sem pelve funcionante; atresia ureteral; a causa mais frequente de massa abdominal no recém-nascido; involui na maioria.',
    clues: ['Colar fibromuscular ao redor de ductos primitivos, com ou sem cartilagem.'],
    mimics: ['Rim policístico: bilateral, arquitetura preservada.', 'Nefroma cístico: massa localizada com estroma ovariano.', 'Hidronefrose grave: cistos comunicam e convergem para a pelve.'],
    sources: ['https://meridian.allenpress.com/aplm/article/139/4/547/194076/Renal-Dysplasia'],
  },
  {
    id: 'nefronoftise-doenca-cistica-medular',
    frequency: 1,
    name: 'Nefronoftise e doença cística medular',
    aka: ['NPHP', 'doença renal túbulo-intersticial autossômica dominante (ADTKD)', 'nephronophthisis'],
    sites: ['rim'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['inflamacao'],
    lining: 'Epitélio tubular simples, cuboide baixo a achatado, sem atipia: túbulos distais e coletores dilatados.',
    wall: 'Membrana basal tubular espessada, desdobrada e reduplicada; atrofia tubular com fibrose intersticial; infiltrado crônico esparso.',
    contents: 'Líquido seroso claro.',
    where: 'Cistos pequenos na junção corticomedular e medula, rins normais ou pequenos com córtex afinado; ciliopatia recessiva da infância (poliúria, anemia) ou ADTKD dominante do adulto (MUC1, UMOD).',
    clues: ['Cistos corticomedulares com membrana basal tubular espessada e desdobrada.'],
    mimics: ['Doença cística adquirida: diálise, oxalato.', 'Rim em esponja medular: ductos coletores dilatados sem fibrose difusa.', 'Rim policístico: rins aumentados, cistos corticais grandes.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2770134/'],
  },
  {
    id: 'neoplasia-renal-cistica-multilocular-baixo-potencial',
    frequency: 1,
    name: 'Neoplasia renal cística multilocular de baixo potencial de malignidade',
    aka: ['antigo carcinoma de células renais cístico multilocular', 'MCRNLMP'],
    sites: ['rim'],
    linings: ['glicogenio-rico', 'cuboidal-simples'],
    lining: 'Camada única (às vezes poucas) de células claras de baixo grau (OMS/ISUP 1 a 2) revestindo todos os cistos, iguais às do carcinoma de células claras de baixo grau; CA9 em caixa, CD10 e PAX8 positivos.',
    wall: 'Septos fibrosos com pequenos ninhos de células claras sem formar nódulo expansivo; sem necrose, sem invasão vascular.',
    contents: 'Líquido seroso claro a serossanguinolento.',
    where: 'Massa multilocular com pseudocápsula, Bosniak III; espectro dos tumores de células claras na OMS 2022; prognóstico excelente.',
    clues: ['Ausência absoluta de nódulo sólido expansivo é o critério; com nódulo, é carcinoma de células claras cístico.'],
    mimics: ['Carcinoma de células claras com degeneração cística: nódulo expansivo, grau maior.', 'Tumor renal de células claras papilar: CK7 difuso, CA9 em taça, CD10 negativo.', 'Nefroma cístico: revestimento eosinofílico em tachinha, estroma ovariano.'],
    sources: ['https://www.pathologyoutlines.com/topic/kidneytumormcrnlow.html'],
  },
  {
    id: 'carcinoma-de-celulas-renais-cistico',
    name: 'Carcinoma de células renais cístico',
    aka: ['carcinoma de células claras com degeneração cística', 'cystic clear cell RCC'],
    sites: ['rim'],
    linings: ['glicogenio-rico', 'cuboidal-simples'],
    features: ['sangue', 'hemossiderina'],
    lining: 'Células neoplásicas claras com atipia em uma ou mais camadas, com nódulos sólidos expansivos na parede e septos; graus OMS/ISUP 2 a 4. CA9, CD10, PAX8 e vimentina positivos; VHL e 3p.',
    wall: 'Septos com nódulos sólidos, vasculatura em arame de galinheiro, necrose, hemorragia, hemossiderina; invasão vascular possível.',
    contents: 'Líquido seroso, hemorrágico ou necrótico.',
    where: 'Rim, uni ou multilocular, Bosniak III a IV.',
    clues: ['Nódulo sólido expansivo ou grau nuclear alto.'],
    mimics: ['Neoplasia cística multilocular de baixo potencial: sem nódulo expansivo, grau baixo.', 'Carcinoma tubulocístico: revestimento eosinofílico em tachinha, aspecto de bolha de sabão.', 'Cisto simples com atipia degenerativa: revestimento monótono, sem massa.'],
    sources: ['https://www.nature.com/articles/modpathol201078'],
  },
  {
    id: 'pseudocisto-adrenal',
    name: 'Pseudocisto adrenal',
    aka: ['cisto hemorrágico da suprarrenal', 'adrenal pseudocyst'],
    sites: ['adrenal'],
    linings: ['sem-revestimento'],
    features: ['hemossiderina', 'colesterol', 'calcificacao', 'sangue'],
    pseudocyst: true,
    lining: 'Nenhum revestimento epitelial, mesotelial ou endotelial identificável; superfície de fibrose e granulação.',
    wall: 'Parede fibrosa espessa e vascularizada com hemorragia antiga e recente, hemossiderina, colesterol, calcificação e córtex adrenal comprimido na periferia.',
    contents: 'Material hemorrágico antigo, achocolatado, com coágulos organizados.',
    where: 'Suprarrenal, unilateral; cerca de 39% dos cistos adrenais; sequela de hemorragia por trauma, sepse, anticoagulação ou estresse neonatal.',
    clues: ['Hemossiderina, córtex aprisionado na parede e ausência de revestimento com amostragem ampla.', 'Fazer CD31 e ERG antes de rotular: o cisto endotelial é fácil de confundir.'],
    mimics: ['Cisto endotelial adrenal: CD31 e D2-40 positivos.', 'Feocromocitoma cístico: cromogranina, células cromafins na parede.', 'Carcinoma adrenocortical cístico: atipia, necrose, Ki-67 alto.'],
    sources: ['https://academic.oup.com/ajcp/article/157/4/531/6378852', 'https://www.pathologyoutlines.com/topic/adrenalcysts.html'],
  },
  {
    id: 'cisto-endotelial-adrenal',
    frequency: 1,
    name: 'Cisto endotelial (linfangiomatoso) da adrenal',
    aka: ['cisto angiomatoso adrenal', 'adrenal endothelial cyst'],
    sites: ['adrenal'],
    linings: ['endotelial'],
    features: ['estroma-linfoide', 'calcificacao'],
    lining: 'Endotélio achatado em camada única, brando; CD31, CD34 e ERG positivos, D2-40 no subtipo linfangiomatoso (o mais comum); citoqueratina e calretinina negativas.',
    wall: 'Estroma fibroso delgado com músculo liso esparso, agregados linfoides, calcificação e córtex residual.',
    contents: 'Líquido seroso claro, às vezes quiloso ou hemorrágico.',
    where: 'Suprarrenal, uni ou multilocular; o cisto adrenal verdadeiro mais comum (cerca de 45%); achado incidental.',
    clues: ['CD31 e ERG positivos com citoqueratina negativa.'],
    mimics: ['Pseudocisto adrenal: nenhum revestimento; sem imuno há risco real de erro.', 'Cisto mesotelial adrenal: calretinina, CK e EMA positivos, CD31 negativo.', 'Cisto hidático adrenal: membrana laminada.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC8479637/'],
  },
  {
    id: 'cisto-epitelial-mesotelial-adrenal',
    frequency: 1,
    name: 'Cisto epitelial (mesotelial) da adrenal',
    aka: ['inclusão mesotelial adrenal', 'adrenal epithelial cyst'],
    sites: ['adrenal'],
    linings: ['mesotelial', 'cuboidal-simples'],
    lining: 'Camada única de células cuboides a achatadas de tipo mesotelial ou epitelial; citoqueratina, EMA, calretinina e CA-125 positivos; microvilosidades longas à microscopia eletrônica.',
    wall: 'Estroma fibroso delgado com córtex residual; sem hemossiderina abundante, sem membrana laminada.',
    contents: 'Líquido seroso claro.',
    where: 'Suprarrenal; o tipo mais raro (cerca de 9%), unilocular e pequeno; variantes com diferenciação mülleriana (PAX8, ER) ou folicular tireoidiana descritas.',
    clues: ['Citoqueratina, EMA e calretinina positivos com CD31 negativo.'],
    mimics: ['Cisto endotelial adrenal: CD31 e ERG positivos, citoqueratina negativa.', 'Pseudocisto: sem revestimento, hemossiderina, parede espessa.', 'Cisto broncogênico justa-adrenal: ciliado com cartilagem ou glândulas seromucosas.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC10895221/'],
  },
]
