/* ==========================================================================
   cns.ts — encéfalo e ventrículos, região selar, coluna e raízes, olho e
   órbita. As três perguntas mais cobradas: epidermoide vs dermoide (anexos),
   neurentérico vs ependimário (CK, EMA e CEA com caliciformes e membrana
   basal vs GFAP com EMA negativo) e Rathke vs craniofaringioma (ciliado em
   camada única com beta-catenina nuclear negativa vs queratina úmida e
   calcificação). Conferido em 2026-09-12.
   ========================================================================== */

import type { Cyst } from '../types'

export const cns: Cyst[] = [
  {
    id: 'cisto-coloide-terceiro-ventriculo',
    name: 'Cisto coloide do terceiro ventrículo',
    aka: ['cisto neuroepitelial do III ventrículo', 'colloid cyst'],
    sites: ['encefalo'],
    linings: ['respiratorio-ciliado', 'colunar-mucinoso', 'cuboidal-simples'],
    features: ['celulas-caliciformes', 'cilios', 'material-eosinofilico'],
    lining: 'Simples a pseudoestratificado, cuboide a colunar, com cílios esparsos e caliciformes produtoras de muco, sobre membrana basal delgada e cápsula fibrosa fina; sem metaplasia escamosa. CK7, EMA e às vezes CEA positivos; GFAP negativo.',
    wall: 'Cápsula fibroconjuntiva fina e paucicelular, sem anexos, sem gliose significativa.',
    contents: 'Material amorfo espesso, eosinofílico, PAS positivo, com debris e macrófagos; hiperdenso na TC.',
    where: 'Teto anterior do terceiro ventrículo, junto ao forame de Monro; adulto jovem com cefaleia posicional e hidrocefalia aguda.',
    clues: ['Localização exata no teto do terceiro ventrículo.', 'Conteúdo PAS positivo hiperdenso.'],
    mimics: ['Cisto neurentérico: histologia e imunofenótipo idênticos, separa a topografia (ventral à medula).', 'Cisto ependimário: GFAP positivo, EMA negativo, sem caliciformes.', 'Cisto de Rathke: região selar.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC8360874/'],
  },
  {
    id: 'cisto-fenda-rathke',
    name: 'Cisto da fenda de Rathke',
    aka: ['cisto de Rathke', 'Rathke cleft cyst'],
    sites: ['sela'],
    linings: ['respiratorio-ciliado', 'cuboidal-simples'],
    features: ['celulas-caliciformes', 'cilios', 'metaplasia-escamosa', 'muco'],
    lining: 'Camada única (simples ou pseudoestratificada) de epitélio cuboide a colunar, muitas vezes ciliado, tipo respiratório, com caliciformes esparsas; metaplasia escamosa em 25 a 40%. CK8 e CK20 frequentemente positivos; beta-catenina nuclear negativa e sem BRAF V600E.',
    wall: 'Parede fibrosa fina, sem anexos, sem queratina úmida, sem retículo estrelado, calcificação rara; inflamação crônica e nódulos de mucina possíveis.',
    contents: 'Muco espesso ou fluido seroso; nódulo intracístico de mucina na RM.',
    where: 'Sela, entre adeno e neuro-hipófise (pars intermedia), com extensão supra-selar em um terço; mulher adulta com cefaleia, hipopituitarismo ou diabetes insípido.',
    clues: ['Epitélio ciliado em camada única com caliciformes, sem calcificação.', 'Beta-catenina nuclear negativa, CK20 positivo.'],
    mimics: ['Craniofaringioma adamantinomatoso: queratina úmida, retículo estrelado, calcificação, beta-catenina nuclear positiva, CK20 negativo.', 'Craniofaringioma papilífero: escamoso não queratinizante em papilas, BRAF V600E positivo.', 'Cisto epidermoide selar: escamoso queratinizante com granulosa, sem cílios.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC11920404/', 'https://meridian.allenpress.com/aplm/article/126/10/1174/453236/Differential-Expression-of-Cytokeratins-8-and-20'],
  },
  {
    id: 'cisto-aracnoide',
    name: 'Cisto aracnóideo',
    aka: ['cisto leptomeníngeo primário', 'arachnoid cyst'],
    sites: ['encefalo', 'coluna'],
    linings: ['meningotelial'],
    lining: 'Camada única de células meningoteliais achatadas, sem cílios, sem caliciformes, sem membrana basal verdadeira; EMA positivo, GFAP, CK e S100 negativos.',
    wall: 'Colágeno delicado, avascular, rico em reticulina, indistinguível de aracnoide normal; sem gliose, sem anexos.',
    contents: 'Líquido cefalorraquidiano.',
    where: 'Fossa média (o mais comum), fossa posterior, supra-selar, convexidade, ângulo ponto-cerebelar e canal vertebral.',
    clues: ['Segue o sinal do liquor em todas as sequências, sem restrição à difusão.', 'O patologista recebe só fragmentos de membrana: EMA positivo, GFAP negativo.'],
    mimics: ['Cisto epidermoide: restringe na difusão, escamoso queratinizante.', 'Cisto glioependimário: EMA negativo, GFAP positivo.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC10718336/'],
  },
  {
    id: 'cisto-epidermoide-snc',
    name: 'Cisto epidermoide intracraniano e espinhal',
    aka: ['tumor pérola', 'colesteatoma primário', 'epidermoid cyst'],
    sites: ['encefalo', 'sela', 'coluna', 'orbita'],
    linings: ['escamoso-queratinizado'],
    features: ['queratina-lamelar', 'colesterol'],
    lining: 'Escamoso estratificado queratinizante maduro com camada granulosa bem formada, sem anexos cutâneos.',
    wall: 'Cápsula fibrosa fina; se rompido, granuloma de corpo estranho a queratina com células gigantes e colesterol.',
    contents: 'Queratina lamelar seca em flocos, cristais de colesterol, aspecto nacarado; sem pelos nem sebo.',
    where: 'Ângulo ponto-cerebelar (o mais comum), parasselar, fossa média, quarto ventrículo, intradiploico; paramediano. Na órbita, superolateral nas suturas.',
    clues: ['Restrição marcante na difusão e sinal sujo no FLAIR.', 'Granulosa presente e ausência total de anexos.'],
    mimics: ['Cisto dermoide: anexos, pelos e sebo, linha média, gordura na TC.', 'Cisto aracnóideo: meningotelial, sem restrição.', 'Cisto neurentérico com metaplasia escamosa: procure cílios e caliciformes, CK7 e EMA.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC11930405/', 'https://www.pathologyoutlines.com/topic/eyeorbitdermoid.html'],
  },
  {
    id: 'cisto-dermoide-snc',
    name: 'Cisto dermoide intracraniano e espinhal',
    aka: ['dermoide', 'dermoid cyst'],
    sites: ['encefalo', 'sela', 'coluna'],
    linings: ['escamoso-queratinizado'],
    features: ['anexos-cutaneos', 'sebo-pelos', 'queratina-lamelar'],
    lining: 'Escamoso estratificado queratinizante com camada granulosa, sobre derme com anexos: folículos pilosos, glândulas sebáceas e sudoríparas.',
    wall: 'Derme fibrosa com anexos, gordura, músculo liso perifolicular; se rompido, meningite química com granulomas lipofágicos e colesterol.',
    contents: 'Queratina, sebo oleoso e pelos; gordura na TC e hipersinal em T1.',
    where: 'Linha média: fossa posterior e vérmis, selar e parasselar, fossa média anterior; seio dérmico occipital ou nasal; criança e adulto jovem.',
    clues: ['Pelos e glândulas sebáceas no espécime.', 'Gotículas de gordura nos sulcos e ventrículos após ruptura.'],
    mimics: ['Cisto epidermoide: mesmo epitélio sem anexos nem gordura, paramediano.', 'Teratoma maduro: três folhetos.', 'Lipoma intracraniano: sem epitélio.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC11941323/'],
  },
  {
    id: 'cisto-neurenterico',
    name: 'Cisto neurentérico (enterogênico, endodérmico)',
    aka: ['cisto endodérmico', 'cisto enterogênico', 'classificação de Wilkins e Odom A, B, C', 'neurenteric cyst'],
    sites: ['coluna', 'encefalo', 'mediastino'],
    linings: ['respiratorio-ciliado', 'colunar-mucinoso', 'cuboidal-simples'],
    features: ['celulas-caliciformes', 'cilios', 'musculo-liso', 'glandulas-seromucosas', 'cartilagem', 'tecido-glial', 'metaplasia-escamosa'],
    lining: 'Cuboide a colunar, simples ou pseudoestratificado, ciliado ou não, com caliciformes, tipo respiratório ou digestivo, sobre membrana basal; metaplasia escamosa comum. CK, CK7, EMA e CEA positivos, CK20 em parte; GFAP negativo.',
    wall: 'Tipo A: só epitélio e conjuntivo. Tipo B: glândulas mucosas ou serosas, músculo liso ou estriado, gordura, cartilagem, osso, tecido linfoide, nervos e gânglios. Tipo C: além disso, glia e epêndima.',
    contents: 'Muco claro a espesso, gelatinoso, PAS e mucicarmim positivos; ruptura dá meningite química.',
    where: 'Intradural extramedular ventral à medula cervical baixa e torácica alta; intracraniano pré-medular e ângulo ponto-cerebelar; mediastino posterior paravertebral com extensão intraespinhal. Anomalias de fusão vertebral em cerca de 40%.',
    clues: ['Caliciformes com membrana basal e CK, EMA, CEA positivos.', 'Lesão ventral à medula com vértebra em borboleta, hemivértebra ou espinha bífida.'],
    mimics: ['Cisto glioependimário: GFAP positivo, EMA negativo, sem caliciformes, sem membrana basal.', 'Cisto coloide: histologia idêntica, separa a topografia no terceiro ventrículo.', 'Cisto aracnóideo: meningotelial, CK e CEA negativos.', 'Cisto broncogênico: mediastino médio, cartilagem, sem anomalia vertebral.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC6263491/', 'https://pathologyoutlines.com/topic/cnstumorenterogenouscyst.html'],
  },
  {
    id: 'cisto-glioependimario',
    name: 'Cisto glioependimário (ependimário, neuroglial)',
    aka: ['cisto neuroglial', 'cisto neuroepitelial', 'glioependymal cyst'],
    sites: ['encefalo', 'coluna'],
    linings: ['glioependimario'],
    features: ['cilios', 'tecido-glial'],
    lining: 'Camada única de células cuboides a colunares tipo ependimário, muitas vezes ciliadas, sem caliciformes e sem membrana basal, sobre tecido glial. GFAP e S100 positivos; EMA, CK e CEA negativos.',
    wall: 'Tecido neuroglial GFAP positivo com gliose variável, sem cápsula fibrosa verdadeira, sem anexos, sem meningotélio.',
    contents: 'Líquido claro semelhante ao liquor, às vezes xantocrômico.',
    where: 'Substância branca frontal (o mais comum), periventricular, tronco, cerebelo e canal vertebral; criança ou adulto jovem.',
    clues: ['Epitélio ciliado sem caliciformes assentado em neurópilo GFAP positivo.'],
    mimics: ['Cisto aracnóideo: EMA positivo, GFAP negativo.', 'Cisto neurentérico: caliciformes, membrana basal, CK7, EMA e CEA positivos.', 'Cisto porencefálico: sem revestimento celular.'],
    sources: ['https://academic.oup.com/jnen/article/84/7/617/8108138'],
  },
  {
    id: 'cisto-plexo-coroide',
    name: 'Cisto do plexo coroide (e xantogranuloma)',
    aka: ['cisto coroideo', 'xantogranuloma do plexo coroide', 'choroid plexus cyst'],
    sites: ['encefalo'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['colesterol', 'hemossiderina', 'calcificacao'],
    lining: 'Camada única de epitélio do plexo coroide, cuboide a achatado, sobre o estroma coroideo; no xantogranuloma o epitélio está ausente ou só focal. CK, transtirretina e S100 positivos.',
    wall: 'Estroma fibrovascular coroideo; no xantogranuloma, macrófagos espumosos, colesterol, hemossiderina, células gigantes, inflamação e calcificação.',
    contents: 'Líquido claro com debris epiteliais; material amarelado rico em colesterol no xantogranuloma.',
    where: 'Glômus do plexo dos ventrículos laterais, bilateral em metade; achado fetal do segundo trimestre que regride; xantogranuloma incidental no adulto.',
    clues: ['Ultrassom fetal com regressão até 26 semanas.', 'Macrófagos espumosos com colesterol no glômus do adulto.'],
    mimics: ['Cisto epidermoide intraventricular: escamoso queratinizante.', 'Papiloma do plexo coroide cístico: proliferação papilar verdadeira.', 'Cisto coloide: forame de Monro, epitélio mucossecretor.'],
    sources: ['https://www.medlink.com/articles/ependymal-and-choroid-plexus-cysts'],
  },
  {
    id: 'cisto-pineal',
    name: 'Cisto da pineal',
    aka: ['cisto glial da pineal', 'pineal cyst'],
    sites: ['encefalo'],
    linings: ['glioependimario', 'sem-revestimento'],
    features: ['tecido-glial', 'hemossiderina', 'calcificacao'],
    lining: 'Sem epitélio nem epêndima verdadeiros: superfície interna de gliose piloide paucicelular (revestimento glial), com células ependimárias só focais e inconstantes.',
    wall: 'Três camadas: gliose piloide com fibras de Rosenthal, corpos granulares e hemossiderina; parênquima pineal comprimido com lobulação e areia cerebral; leptomeninge fibrosa externa. GFAP na camada glial, sinaptofisina no parênquima pineal.',
    contents: 'Fluido proteináceo claro a xantocrômico, às vezes hemorrágico (apoplexia pineal).',
    where: 'Glândula pineal; achado incidental em mulher jovem, menor que 1 cm, realce em anel fino.',
    clues: ['Gliose com Rosenthal, parênquima pineal e leptomeninge na mesma parede.'],
    mimics: ['Astrocitoma pilocítico: biópsia pequena só com a camada gliótica; identificar o parênquima pineal com sinaptofisina.', 'Pineocitoma cístico: rosetas pineocitomatosas.', 'Cisto aracnóideo da cisterna quadrigeminal: meningotelial.'],
    sources: ['https://www.pathologyoutlines.com/topic/cnstumorpinealcyst.html'],
  },
  {
    id: 'cisto-tarlov',
    name: 'Cisto de Tarlov (perineural)',
    aka: ['divertículo da raiz nervosa', 'cisto meníngeo tipo II de Nabors', 'Tarlov cyst'],
    sites: ['coluna'],
    linings: ['meningotelial'],
    features: ['tecido-glial'],
    lining: 'Sem epitélio: células aracnoides e perineurais achatadas, com fibras nervosas e células ganglionares na parede ou dentro da luz. EMA positivo; S100 e neurofilamento nas fibras.',
    wall: 'Perineuro fibroso vascularizado com axônios mielinizados e gânglio da raiz dorsal incorporados; hemossiderina ocasional.',
    contents: 'Líquido cefalorraquidiano.',
    where: 'Raízes sacrais, entre perineuro e endoneuro, no nível do gânglio da raiz dorsal em S2-S3; mulher de meia-idade com dor perineal ou radiculopatia sacral.',
    clues: ['Fibras nervosas ou células ganglionares na parede: é o achado definidor.'],
    mimics: ['Cisto meníngeo extradural tipo I de Nabors: sem fibras nervosas na parede.', 'Cisto aracnóideo intradural: sem raiz incorporada.', 'Meningocele sacral anterior: defeito ósseo.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK582154/'],
  },
  {
    id: 'cisto-meningeo-espinhal',
    name: 'Cisto meníngeo espinhal (extradural e intradural)',
    aka: ['cisto aracnóideo espinhal', 'divertículo meníngeo', 'Nabors tipo I e III', 'spinal meningeal cyst'],
    sites: ['coluna'],
    linings: ['meningotelial'],
    lining: 'Camada única de células meningoteliais achatadas sobre colágeno; sem epitélio, sem cílios; o tipo I não contém fibras nervosas. EMA positivo; GFAP, CK e CEA negativos.',
    wall: 'Colágeno denso tipo dural ou aracnóideo, hipocelular; hemossiderina e inflamação leve; pedículo de comunicação com o espaço subaracnóideo.',
    contents: 'Líquido cefalorraquidiano.',
    where: 'Tipo IA extradural dorsal torácico (o mais comum), IB sacral, III intradural dorsal torácico; mielo-TC mostra a comunicação.',
    clues: ['Membrana translúcida fina EMA positiva sem fibras nervosas.'],
    mimics: ['Cisto de Tarlov: fibras nervosas ou gânglio na parede.', 'Cisto sinovial da faceta: sinoviócitos, contínuo com a articulação.', 'Cisto neurentérico: colunar com caliciformes, CK e CEA positivos.'],
    sources: ['https://pubmed.ncbi.nlm.nih.gov/3343608/'],
  },
  {
    id: 'cisto-porencefalico',
    name: 'Cisto porencefálico',
    aka: ['porencefalia', 'encefalomalacia cística', 'porencephalic cyst'],
    sites: ['encefalo'],
    linings: ['sem-revestimento'],
    features: ['tecido-glial', 'hemossiderina', 'calcificacao'],
    pseudocyst: true,
    lining: 'Nenhum revestimento epitelial ou meningotelial: cavidade delimitada por substância branca gliótica; epêndima residual só na porção que comunica com o ventrículo.',
    wall: 'Gliose fibrilar densa, macrófagos com hemossiderina, calcificação distrófica, mineralização neuronal, vasos hialinizados. GFAP na gliose; EMA e CK negativos.',
    contents: 'Líquido cefalorraquidiano.',
    where: 'Hemisfério cerebral em território arterial (cerebral média), comunicando com o ventrículo lateral; criança com hemiparesia ou epilepsia; insulto pré ou perinatal, COL4A1 na forma familiar.',
    clues: ['Cavidade que comunica com o ventrículo e segue território vascular.'],
    mimics: ['Cisto aracnóideo: extra-axial, meningotelial EMA positivo.', 'Esquizencefalia: fenda revestida por córtex polimicrogírico.', 'Cisto glioependimário: revestimento ependimário ciliado.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC8745398/'],
  },
  {
    id: 'craniofaringioma-adamantinomatoso-cistico',
    name: 'Craniofaringioma adamantinomatoso (cístico)',
    aka: ['craniofaringioma', 'adamantinomatous craniopharyngioma'],
    sites: ['sela'],
    linings: ['escamoso-nao-queratinizado'],
    features: ['palicada-basal', 'calcificacao', 'colesterol', 'tecido-glial', 'queratina-compacta'],
    lining: 'Escamoso estratificado com paliçada nuclear periférica (tipo ameloblástico), retículo estrelado frouxo e nódulos de queratina úmida anucleada; não é ciliado nem de camada única. Beta-catenina nuclear em ninhos (CTNNB1); CK20 e BRAF V600E negativos.',
    wall: 'Calcificação frequente, colesterol, macrófagos espumosos, células gigantes, hemossiderina, inflamação; cérebro adjacente com gliose piloide intensa e fibras de Rosenthal, armadilha em biópsia periférica.',
    contents: 'Líquido espesso amarelo-acastanhado tipo óleo de motor, com cristais de colesterol.',
    where: 'Selar e supra-selar, haste e hipotálamo; pico bimodal (5 a 15 e 45 a 60 anos).',
    clues: ['Queratina úmida ao microscópio; massa cística e calcificada em criança.', 'Beta-catenina nuclear positiva.'],
    mimics: ['Cisto de Rathke: ciliado de camada única com caliciformes, sem queratina úmida, beta-catenina nuclear negativa, CK20 positivo.', 'Craniofaringioma papilífero: adulto, escamoso não queratinizante em papilas, sem calcificação, BRAF V600E positivo.', 'Cisto epidermoide: granulosa, sem paliçada nem retículo estrelado.'],
    sources: ['https://www.pathologyoutlines.com/topic/cnstumoradamcraniopharyngioma.html', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11364980/'],
  },
  {
    id: 'neurocisticercose',
    name: 'Cisticercose (Taenia solium)',
    aka: ['neurocisticercose', 'Cysticercus cellulosae', 'forma racemosa', 'cysticercosis'],
    sites: ['encefalo', 'coluna', 'pele', 'partes-moles', 'orbita'],
    linings: ['parasitario'],
    features: ['inflamacao', 'calcificacao'],
    lining: 'Parede do parasita, não do hospedeiro: cuticular externa ondulada com microtríquias, celular intermediária e reticular interna com canalículos e calcificações; escólex invaginado com 4 ventosas e rostelo de ganchos birrefringentes.',
    wall: 'Reação do hospedeiro: cápsula fibrosa, linfoplasmócitos e eosinófilos, granulomas com células gigantes, gliose e calcificação na involução.',
    contents: 'Líquido claro (vesicular) que fica turvo, gelatinoso e por fim caseoso e calcificado.',
    where: 'Junção córtico-subcortical (o mais comum), cisternas basais (racemosa), ventrículos, medula; também subcutâneo e músculo. Brasil e áreas endêmicas; epilepsia de início tardio.',
    clues: ['Ponto excêntrico (escólex) na RM ou calcificação puntiforme.', 'Ganchos birrefringentes à luz polarizada.'],
    mimics: ['Cisto hidático: membrana laminada acelular PAS positiva espessa, sem microtríquias, protoescólices múltiplos.', 'Tuberculoma ou abscesso: sem estruturas parasitárias.', 'Cisto aracnóideo na forma racemosa: sem membrana parasitária.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC10510602/'],
  },
  {
    id: 'cisto-leptomeningeo-pos-traumatico',
    name: 'Cisto leptomeníngeo pós-traumático (fratura em crescimento)',
    aka: ['fratura craniana evolutiva', 'growing skull fracture'],
    sites: ['encefalo', 'osso'],
    linings: ['meningotelial'],
    features: ['tecido-glial', 'hemossiderina'],
    lining: 'Sem epitélio: aracnoide herniada pela laceração dural, às vezes com parênquima cerebral gliótico; a rigor uma hérnia leptomeníngea, não um cisto.',
    wall: 'Leptomeninge fibrosada aderida às bordas ósseas erodidas, cérebro com gliose e hemossiderina, cicatriz dural.',
    contents: 'Líquido cefalorraquidiano, às vezes xantocrômico.',
    where: 'Calota, sobretudo parietal, em menores de 3 anos com fratura diastática que alarga nas radiografias seriadas.',
    clues: ['Fratura que alarga semanas a meses após o trauma; laceração dural na cirurgia.'],
    mimics: ['Cisto aracnóideo primário com remodelamento ósseo: sem fratura.', 'Dermoide ou epidermoide intradiploico: epitélio escamoso.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK589642/'],
  },
  {
    id: 'cisto-inclusao-conjuntival',
    name: 'Cisto de inclusão epitelial da conjuntiva',
    aka: ['cisto epitelial conjuntival', 'conjunctival inclusion cyst'],
    sites: ['orbita'],
    linings: ['escamoso-nao-queratinizado'],
    features: ['celulas-caliciformes', 'muco'],
    lining: 'Escamoso estratificado não queratinizado de poucas camadas, com células caliciformes (a ausência delas não exclui a origem conjuntival). CK7 e MUC5AC nas caliciformes.',
    wall: 'Substância própria conjuntival fina com discreto infiltrado linfocitário; sem anexos, sem queratina.',
    contents: 'Líquido claro, mucina e debris celulares.',
    where: 'Conjuntiva bulbar (mais comum), fórnice e tarsal; intraorbitário após enucleação ou cirurgia de estrabismo (implantação).',
    clues: ['Lesão translúcida móvel sobre a esclera, após trauma ou cirurgia.', 'Caliciformes em epitélio escamoso não queratinizado.'],
    mimics: ['Epidermoide ou dermoide: queratinizado, com ou sem anexos.', 'Linfangioma conjuntival: endotélio D2-40 positivo.', 'Cisto ductal lacrimal (dacriops): cuboide a colunar em dupla camada.'],
    sources: ['https://eyewiki.org/Conjunctival_Inclusion_Cyst'],
  },
  {
    id: 'cisto-epitelio-pigmentar-iris',
    name: 'Cisto do epitélio pigmentar da íris',
    aka: ['cisto neuroepitelial da íris', 'cisto iridociliar', 'iris pigment epithelial cyst'],
    sites: ['orbita'],
    linings: ['cuboidal-simples'],
    lining: 'Duas camadas de células cuboides a colunares intensamente pigmentadas (neuroepitélio), unidas por desmossomos; não é escamoso, não há queratina.',
    wall: 'Só as duas camadas neuroepiteliais com membrana basal; sem estroma inflamatório.',
    contents: 'Líquido claro.',
    where: 'Face posterior da íris, periférico ou iridociliar (72%), midzonal ou pupilar; pode soltar-se e flutuar na câmara anterior ou vítreo; adulto assintomático.',
    clues: ['Não transilumina; parede fina e luz anecoica à biomicroscopia ultrassônica, que fecha o diagnóstico.'],
    mimics: ['Melanoma de íris ou corpo ciliar: sólido, ecogenicidade interna, vascularização.', 'Cisto estromal da íris: anterior, escamoso não queratinizado, criança.'],
    sources: ['https://eyewiki.org/Iris_Cysts', 'https://www.ncbi.nlm.nih.gov/books/NBK574573/'],
  },
  {
    id: 'cisto-estromal-iris',
    name: 'Cisto estromal da íris',
    aka: ['cisto epitelial do estroma iriano', 'iris stromal cyst'],
    sites: ['orbita'],
    linings: ['escamoso-nao-queratinizado', 'cuboidal-simples'],
    features: ['celulas-caliciformes'],
    lining: 'Escamoso estratificado não queratinizado (semelhante ao conjuntival), às vezes cuboide, podendo conter caliciformes: epitélio aprisionado no estroma durante o desenvolvimento. CK positiva, melan-A negativa.',
    wall: 'Estroma iriano fibrovascular com melanócitos; sem anexos, sem queratina lamelar.',
    contents: 'Líquido claro ou turvo, mucoide.',
    where: 'Estroma anterior da íris, protruindo na câmara anterior; congênito em lactentes e crianças, ou adquirido; transilumina e tende a crescer, causando glaucoma ou uveíte.',
    clues: ['Criança com cisto translúcido anterior que transilumina.'],
    mimics: ['Cisto do epitélio pigmentar: pigmentado, posterior, não transilumina.', 'Cisto de implantação pós-cirúrgico: idêntico, separa a história.', 'Melanoma amelanótico cístico: massa sólida com atipia.'],
    sources: ['https://eyewiki.org/Iris_Cysts', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7086092/'],
  },
  {
    id: 'mucocele-fronto-etmoidal',
    name: 'Mucocele fronto-etmoidal (com invasão orbitária)',
    aka: ['mucocele de seio paranasal', 'mucopiocele', 'frontoethmoidal mucocele'],
    sites: ['nariz', 'orbita'],
    linings: ['respiratorio-ciliado'],
    features: ['cilios', 'celulas-caliciformes', 'glandulas-seromucosas', 'muco', 'inflamacao'],
    lining: 'Respiratório: colunar pseudoestratificado ciliado com caliciformes (mucosa sinusal) sobre membrana basal; metaplasia escamosa focal em lesões antigas.',
    wall: 'Estroma fibroso com linfócitos e plasmócitos, glândulas seromucosas, osso remodelado e adelgaçado por pressão; colesterol e piócitos na mucopiocele.',
    contents: 'Muco espesso inspissado; mucopurulento se infectado.',
    where: 'Seio frontal e etmoidal expandindo para o teto e parede medial da órbita, deslocando o globo para baixo e lateralmente; sinusite crônica, trauma ou cirurgia prévia.',
    clues: ['Proptose inferolateral lenta com continuidade radiológica com o seio opacificado.'],
    mimics: ['Cisto dermoide da órbita: queratina e anexos, sem continuidade com o seio.', 'Cisto neurentérico ou broncogênico ectópico: epitélio idêntico, separa a topografia.', 'Encefalocele fronto-etmoidal: tecido cerebral GFAP positivo.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4298581/'],
  },
  {
    id: 'cisto-colobomatoso-orbitario',
    name: 'Cisto colobomatoso da órbita (microftalmia com cisto)',
    aka: ['microftalmia com cisto orbitário', 'colobomatous cyst'],
    sites: ['orbita'],
    linings: ['sem-revestimento', 'glioependimario'],
    features: ['tecido-glial', 'calcificacao'],
    lining: 'Sem epitélio verdadeiro: tecido neural gliótico e retina imatura ou displásica com rosetas, às vezes epitélio pigmentar da retina na interface. GFAP e S100 positivos; CK e EMA negativos.',
    wall: 'Glia proliferada, retina displásica sem laminação, epitélio pigmentar com metaplasia óssea, calcificações, fibrose e inflamação.',
    contents: 'Líquido proteináceo claro a xantocrômico.',
    where: 'Órbita inferior, contíguo ao globo microftálmico pela falha de fechamento da fissura óptica; recém-nascido com massa cística azulada na pálpebra inferior.',
    clues: ['Continuidade do cisto com o globo pela fissura na RM.'],
    mimics: ['Cisto dermoide congênito: epitélio queratinizado com anexos.', 'Teratoma orbitário: três folhetos.', 'Retinoblastoma com componente cístico: células pequenas azuis malignas com rosetas de Flexner-Wintersteiner.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC6939411/'],
  },
]
