/* ==========================================================================
   headneck.ts — maxilares e boca (odontogênicos e não odontogênicos),
   glândulas salivares, pescoço, tireoide e paratireoides, orelha.
   Terminologia da OMS de cabeça e pescoço, 5ª edição (2022): o ceratocisto
   e o cisto odontogênico calcificante voltaram a ser cistos; o cisto
   cirúrgico ciliado é entrada nova. Revestimentos conferidos em 2026-09-12.
   ========================================================================== */

import type { Cyst } from '../types'

export const headneck: Cyst[] = [
  {
    id: 'cisto-radicular',
    name: 'Cisto radicular (periapical)',
    aka: ['cisto apical', 'cisto inflamatório periapical', 'radicular cyst'],
    sites: ['maxilares'],
    linings: ['escamoso-nao-queratinizado'],
    features: ['dente', 'inflamacao', 'colesterol', 'corpos-rushton', 'hemossiderina'],
    lining: 'Escamoso estratificado não queratinizado, de espessura irregular, com hiperplasia em arcos e espongiose por inflamação; corpos hialinos de Rushton dentro do epitélio em cerca de 10%.',
    wall: 'Conjuntivo fibroso com infiltrado linfoplasmocitário denso, fendas de colesterol com células gigantes, hemossiderina e calcificações distróficas.',
    contents: 'Líquido amarelado ou acastanhado, turvo, com cristais de colesterol.',
    where: 'Ápice (raramente lateral, junto a canal acessório) de um dente com necrose pulpar; maxila anterior é o local mais frequente.',
    clues: ['Dente desvitalizado, teste de vitalidade negativo.', 'Radiolucidez periapical contínua com o espaço do ligamento periodontal.'],
    mimics: ['Granuloma periapical: sem cavidade revestida por epitélio.', 'Cisto dentígero inflamado: envolve a coroa de um dente não irrompido.', 'Ceratocisto: paraceratina corrugada e basal em paliçada.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC4378819/', 'https://www.sciencedirect.com/science/article/pii/S1607551X17307659'],
  },
  {
    id: 'cisto-residual',
    name: 'Cisto residual',
    aka: ['cisto radicular residual', 'residual cyst'],
    sites: ['maxilares'],
    linings: ['escamoso-nao-queratinizado'],
    features: ['colesterol', 'hemossiderina'],
    lining: 'Escamoso estratificado não queratinizado, mais fino, regular e atrófico que o do cisto radicular, porque a inflamação regride depois da exodontia.',
    wall: 'Conjuntivo fibroso denso, inflamação escassa, fendas de colesterol e hemossiderina.',
    contents: 'Fluido amarelado com colesterol.',
    where: 'Rebordo alveolar edêntulo, no lugar de um dente extraído.',
    clues: ['Histologia de cisto radicular "apagada", em área sem dente.', 'História de exodontia no local.'],
    mimics: ['Cisto radicular: o dente necrosado ainda está lá.', 'Cisto ósseo simples: sem revestimento epitelial.'],
    sources: ['https://www.pathologyoutlines.com/topic/mandiblemaxillaresidualcyst.html', 'https://www.ncbi.nlm.nih.gov/books/NBK574529/'],
  },
  {
    id: 'cisto-dentigero',
    name: 'Cisto dentígero',
    aka: ['cisto folicular', 'dentigerous cyst'],
    sites: ['maxilares'],
    linings: ['epitelio-reduzido-esmalte', 'escamoso-nao-queratinizado'],
    features: ['dente', 'celulas-mucosas'],
    lining: 'Escamoso fino, não queratinizado, uniforme, com 2 a 4 camadas (até cerca de 10), plano, derivado do epitélio reduzido do esmalte; fica hiperplásico com cristas quando inflama.',
    wall: 'Conjuntivo frouxo ou mixoide (folicular) com restos odontogênicos inativos; células mucosas, ciliadas ou sebáceas ocasionais.',
    contents: 'Líquido claro a citrino, às vezes com colesterol.',
    where: 'Envolve a coroa de um dente incluso e prende-se ao colo, na junção amelocementária; terceiro molar inferior e canino superior são os mais comuns.',
    clues: ['Radiolucidez unilocular pericoronária bem corticalizada inserida no colo do dente.', 'Espaço folicular maior que 3 a 4 mm sugere cisto.'],
    mimics: ['Folículo pericoronário hiperplásico: menor, sem cavidade definida.', 'Ceratocisto pericoronário: paraceratina corrugada, basal em paliçada.', 'Ameloblastoma unicístico: paliçada com polarização nuclear invertida.'],
    sources: ['https://www.pathologyoutlines.com/topic/mandiblemaxilladentigerous.html', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4181138/'],
  },
  {
    id: 'cisto-de-erupcao',
    name: 'Cisto de erupção',
    aka: ['hematoma de erupção', 'eruption cyst'],
    sites: ['boca', 'maxilares'],
    linings: ['epitelio-reduzido-esmalte'],
    features: ['dente', 'sangue'],
    lining: 'Escamoso fino não queratinizado de 2 a 3 camadas, vindo do epitélio reduzido do esmalte (igual ao dentígero); a mucosa oral queratinizada cobre a superfície externa.',
    wall: 'Conjuntivo frouxo com inflamação crônica variável e hemorragia frequente.',
    contents: 'Líquido claro ou sangue, daí o aspecto azul-arroxeado.',
    where: 'Tecido mole do rebordo alveolar sobre a coroa de um dente em erupção, já fora do osso; crianças, incisivos e primeiros molares.',
    clues: ['Tumefação flutuante azulada sobre dente prestes a irromper.', 'Lesão em tecido mole, não intraóssea; costuma resolver sozinha.'],
    mimics: ['Cisto dentígero: intraósseo.', 'Mucocele ou hematoma: sem revestimento epitelial.'],
    sources: ['https://www.pathologyoutlines.com/topic/mandiblemaxillaeruptioncyst.html'],
  },
  {
    id: 'ceratocisto-odontogenico',
    name: 'Ceratocisto odontogênico',
    aka: ['ceratocisto', '"tumor odontogênico ceratocístico" (termo de 2005, abandonado)', 'odontogenic keratocyst'],
    sites: ['maxilares'],
    linings: ['paraqueratinizado-corrugado'],
    features: ['palicada-basal', 'queratina-compacta'],
    lining: 'Escamoso estratificado paraceratinizado, fino e uniforme (5 a 8 camadas), superfície corrugada, sem cristas epiteliais, camada basal colunar ou cuboide alta em paliçada com núcleos hipercromáticos polarizados.',
    wall: 'Cápsula fibrosa fina e frouxa, em geral sem inflamação; cistos satélites e ilhotas odontogênicas na parede (sobretudo na síndrome); o epitélio descola facilmente do conjuntivo.',
    contents: 'Material ceratínico cremoso ou caseoso, esbranquiçado.',
    where: 'Mandíbula posterior e ramo (60 a 80%), crescendo no sentido ântero-posterior pela medular com pouca expansão; pode ser pericoronário. Múltiplos na síndrome de Gorlin-Goltz (PTCH1).',
    clues: ['Paraceratina corrugada mais basal em paliçada: é o par que define.', 'Radiolucidez multilocular no ramo com pouca expansão e alta recidiva.'],
    mimics: ['Cisto odontogênico ortoceratinizado: ortoceratina, camada granulosa, basal achatada, comportamento indolente.', 'Cisto dentígero: epitélio fino sem paraceratina corrugada.', 'Ameloblastoma: paliçada com polarização invertida e retículo estrelado.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC8794566/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9004408/'],
  },
  {
    id: 'cisto-odontogenico-ortoceratinizado',
    name: 'Cisto odontogênico ortoceratinizado',
    aka: ['COO', 'orthokeratinized odontogenic cyst', 'antiga "variante ortoceratinizada do ceratocisto"'],
    sites: ['maxilares'],
    linings: ['escamoso-queratinizado'],
    features: ['queratina-lamelar', 'dente'],
    lining: 'Escamoso estratificado ortoceratinizado de 5 a 8 camadas, com camada granulosa proeminente sob ortoceratina lamelar, superfície não corrugada e camada basal cuboide baixa ou achatada, sem paliçada.',
    wall: 'Conjuntivo fibroso com inflamação crônica discreta; sem cistos satélites.',
    contents: 'Ceratina lamelar densa, amarelada.',
    where: 'Mandíbula posterior e ramo, muitas vezes junto a um dente incluso; adultos jovens e de meia-idade, mais homens.',
    clues: ['Ortoceratina mais granulosa mais basal achatada.', 'Recidiva rara (cerca de 2%) e sem relação com a síndrome de Gorlin.'],
    mimics: ['Ceratocisto odontogênico: paraceratina corrugada, basal em paliçada, recidivante.', 'Cisto dermoide: anexos cutâneos na parede.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC10112694/'],
  },
  {
    id: 'cisto-periodontal-lateral',
    name: 'Cisto periodontal lateral',
    aka: ['lateral periodontal cyst'],
    sites: ['maxilares'],
    linings: ['escamoso-nao-queratinizado', 'cuboidal-simples'],
    features: ['dente'],
    lining: 'Epitélio fino não queratinizado, cuboide a escamoso, de 1 a 5 camadas, com placas ou espessamentos nodulares focais de células claras fusiformes ricas em glicogênio (restos da lâmina dentária).',
    wall: 'Conjuntivo fibroso maduro, pouco ou nada inflamado; ilhotas odontogênicas possíveis.',
    contents: 'Fluido seroso claro.',
    where: 'Lateral à raiz de um dente vital e irrompido, entre as raízes; pré-molares e caninos inferiores em cerca de 70%, maxila anterior depois.',
    clues: ['Radiolucidez em gota, menor que 1 cm, lateral à raiz de dente vital.', 'Placas epiteliais de células claras glicogenadas.'],
    mimics: ['Cisto radicular lateral: dente não vital, inflamação intensa.', 'Cisto gengival do adulto: mesma histologia, mas em tecido mole.', 'Ceratocisto: paraceratina corrugada.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC6644300/', 'https://www.pathologyoutlines.com/topic/mandiblemaxillalateralperiodontalcyst.html'],
  },
  {
    id: 'cisto-odontogenico-botrioide',
    name: 'Cisto odontogênico botrioide',
    aka: ['cisto periodontal lateral policístico', 'botryoid odontogenic cyst'],
    sites: ['maxilares'],
    linings: ['escamoso-nao-queratinizado', 'cuboidal-simples'],
    features: ['dente'],
    lining: 'Igual ao do cisto periodontal lateral (epitélio fino com placas de células claras glicogenadas), distribuído em múltiplos lóculos, como cacho de uvas.',
    wall: 'Septos fibrosos entre os lóculos; inflamação em geral ausente.',
    contents: 'Fluido claro em várias cavidades.',
    where: 'Mesma topografia do periodontal lateral (lateral a raízes de dentes vitais, pré-molares e caninos inferiores), porém maior e às vezes cruzando a linha média.',
    clues: ['Radiolucidez multilocular lateral às raízes.', 'Recidiva em até 30%, ao contrário do periodontal lateral unilocular.'],
    mimics: ['Cisto periodontal lateral: unilocular, não recidiva.', 'Cisto odontogênico glandular: células em taça, microcistos, células em hobnail.', 'Ameloblastoma multicístico.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2930647/'],
  },
  {
    id: 'cisto-odontogenico-glandular',
    name: 'Cisto odontogênico glandular',
    aka: ['cisto sialo-odontogênico', 'glandular odontogenic cyst'],
    sites: ['maxilares'],
    linings: ['escamoso-nao-queratinizado'],
    features: ['celulas-mucosas', 'cilios', 'muco'],
    lining: 'Escamoso estratificado não queratinizado com interface plana, células cuboides eosinofílicas em hobnail na superfície, células mucosas e lagos de muco intraepiteliais, microcistos e estruturas ductais dentro do epitélio, espessamentos em placa com redemoinhos, cílios focais; espessura variável.',
    wall: 'Conjuntivo fibroso com inflamação escassa; ilhotas odontogênicas possíveis.',
    contents: 'Material mucoide claro a espesso.',
    where: 'Mandíbula anterior, muitas vezes cruzando a linha média; adultos de meia-idade.',
    clues: ['Exige vários critérios juntos: hobnail, microcistos, mucócitos e placas.', 'Sem rearranjo de MAML2 (presente no carcinoma mucoepidermoide).'],
    mimics: ['Carcinoma mucoepidermoide central de baixo grau: MAML2 rearranjado, sólido e infiltrativo.', 'Cisto botrioide: sem mucócitos nem hobnail.', 'Cisto dentígero com metaplasia mucosa: sem placas nem microcistos.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC11829727/', 'https://pubmed.ncbi.nlm.nih.gov/21915706/'],
  },
  {
    id: 'cisto-odontogenico-calcificante',
    name: 'Cisto odontogênico calcificante',
    aka: ['cisto de Gorlin', 'cisto odontogênico de células fantasmas', 'calcifying odontogenic cyst'],
    sites: ['maxilares', 'boca'],
    linings: ['celulas-fantasma'],
    features: ['palicada-basal', 'calcificacao', 'dente'],
    lining: 'Epitélio odontogênico com camada basal colunar tipo ameloblasto (núcleos polarizados em paliçada) coberta por camada frouxa semelhante ao retículo estrelado, com células fantasmas eosinofílicas anucleadas que calcificam.',
    wall: 'Conjuntivo fibroso com massas de células fantasmas, calcificações, material dentinoide junto ao epitélio, reação de corpo estranho; odontoma associado em cerca de um terço.',
    contents: 'Material granular ceratínico e calcificado.',
    where: 'Maxila ou mandíbula anterior, região de caninos (cerca de 65%); variante periférica gengival existe.',
    clues: ['Células fantasmas mais dentinoide.', 'Radiolucidez unilocular com calcificações internas em sal e pimenta.'],
    mimics: ['Ameloblastoma: paliçada sem células fantasmas.', 'Tumor odontogênico adenomatoide: rosetas e calcificações, sem células fantasmas.', 'Tumor dentinogênico de células fantasmas: sólido e infiltrativo.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC8358629/', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3335591/'],
  },
  {
    id: 'cisto-gengival-do-recem-nascido',
    name: 'Cisto gengival do recém-nascido',
    aka: ['cistos da lâmina dentária', 'nódulos de Bohn', 'pérolas de Epstein (rafe palatino)', 'gingival cyst of the newborn'],
    sites: ['boca'],
    linings: ['escamoso-nao-queratinizado', 'escamoso-queratinizado'],
    features: ['queratina-lamelar'],
    lining: 'Escamoso estratificado fino, de 2 a 3 camadas, não queratinizado ou paraceratinizado, plano, sem cristas, com ceratina descamando para a luz.',
    wall: 'Conjuntivo fibroso delicado, sem inflamação.',
    contents: 'Ceratina lamelar.',
    where: 'Crista do rebordo alveolar (lâmina dentária), vertente vestibular ou lingual e palato lateral (Bohn), rafe palatino mediano (Epstein), em 60 a 85% dos recém-nascidos.',
    clues: ['Múltiplas pápulas branco-amareladas de 1 a 3 mm em recém-nascido.', 'Involuem em semanas; o diagnóstico é clínico.'],
    mimics: ['Dente natal: estrutura dentária.', 'Cisto gengival do adulto: idade e placas de células claras.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK493177/'],
  },
  {
    id: 'cisto-gengival-do-adulto',
    name: 'Cisto gengival do adulto',
    aka: ['gingival cyst of the adult', 'equivalente em tecido mole do cisto periodontal lateral'],
    sites: ['boca'],
    linings: ['escamoso-nao-queratinizado', 'cuboidal-simples'],
    lining: 'Epitélio fino de 1 a 5 camadas, cuboide a escamoso não queratinizado, com espessamentos nodulares focais de células claras ricas em glicogênio.',
    wall: 'Conjuntivo fibroso, inflamação ausente ou mínima.',
    contents: 'Fluido claro.',
    where: 'Gengiva inserida ou papila vestibular de caninos e pré-molares inferiores (cerca de 75%), 5ª e 6ª décadas; extraósseo, no máximo com erosão em taça.',
    clues: ['Nódulo gengival azulado ou translúcido menor que 1 cm em pré-molar inferior de adulto.', 'Histologia do periodontal lateral, mas fora do osso.'],
    mimics: ['Cisto periodontal lateral: intraósseo.', 'Mucocele: sem epitélio, com mucífagos.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10688211/'],
  },
  {
    id: 'cisto-da-bifurcacao-vestibular',
    name: 'Cisto da bifurcação vestibular (paradentário)',
    aka: ['cisto colateral inflamatório', 'buccal bifurcation cyst', 'paradental cyst'],
    sites: ['maxilares'],
    linings: ['escamoso-nao-queratinizado'],
    features: ['dente', 'inflamacao'],
    lining: 'Escamoso estratificado não queratinizado, hiperplásico, com cristas alongadas e intensa exocitose e espongiose.',
    wall: 'Conjuntivo vascularizado com infiltrado misto (neutrófilos, plasmócitos, linfócitos, eosinófilos) e tecido de granulação.',
    contents: 'Material seroso ou purulento.',
    where: 'Face vestibular da bifurcação do primeiro ou segundo molar inferior recém-irrompido, dente vital; crianças de 6 a 11 anos, muitas vezes bilateral.',
    clues: ['Molar inferior vital inclinado para vestibular, com sondagem profunda vestibular.', 'Raiz deslocada para lingual na incidência oclusal.'],
    mimics: ['Cisto radicular: dente não vital.', 'Cisto dentígero: envolve a coroa de dente não irrompido.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC6159116/'],
  },
  {
    id: 'cisto-do-ducto-nasopalatino',
    name: 'Cisto do ducto nasopalatino',
    aka: ['cisto do canal incisivo', 'nasopalatine duct cyst'],
    sites: ['maxilares', 'boca'],
    linings: ['escamoso-nao-queratinizado', 'respiratorio-ciliado', 'cuboidal-simples'],
    features: ['nervo-vaso', 'glandulas-seromucosas', 'cartilagem', 'cilios'],
    lining: 'Misto e variável com a altura no canal: escamoso estratificado (porção oral) e ou respiratório pseudoestratificado ciliado com caliciformes (porção nasal), além de colunar simples ou cuboide.',
    wall: 'Conjuntivo com feixes nervosos e vasos de calibre médio (nervo e artéria nasopalatinos), glândulas mucosas menores, inflamação crônica variável, às vezes cartilagem hialina.',
    contents: 'Líquido seroso ou mucoide.',
    where: 'Linha média do palato anterior, dentro do canal incisivo, entre as raízes dos incisivos centrais superiores, que ficam vitais; variante em tecido mole é o cisto da papila incisiva.',
    clues: ['Feixes neurovasculares calibrosos na parede: é o achado decisivo.', 'Radiolucidez em coração entre os incisivos centrais, com dentes vitais.'],
    mimics: ['Forame incisivo amplo: norma anatômica, menor que 6 mm e assintomático.', 'Cisto radicular de incisivo: dente não vital, sem nervos na parede.'],
    sources: ['https://www.pathologyoutlines.com/topic/mandiblemaxillanasopalatine.html', 'https://pubmed.ncbi.nlm.nih.gov/39670133/'],
  },
  {
    id: 'cisto-nasolabial',
    name: 'Cisto nasolabial',
    aka: ['cisto nasoalveolar', 'cisto de Klestadt', 'nasolabial cyst'],
    sites: ['boca', 'nariz', 'pele'],
    linings: ['colunar-nao-ciliado', 'escamoso-nao-queratinizado'],
    features: ['celulas-caliciformes', 'muco'],
    lining: 'Colunar pseudoestratificado não ciliado com células caliciformes (em até metade dos casos); menos vezes colunar ou cuboide misto ou escamoso estratificado.',
    wall: 'Conjuntivo fibroso hipocelular, em geral sem inflamação significativa.',
    contents: 'Material mucinoso viscoso, amarelado.',
    where: 'Tecido mole do sulco nasolabial, profundo ao lábio superior e à asa do nariz, acima do processo alveolar; extraósseo, mulheres adultas, cerca de 10% bilaterais.',
    clues: ['Abaulamento que eleva a asa nasal e apaga o sulco nasolabial.', 'Sem alteração óssea significativa e dentes vitais.'],
    mimics: ['Abscesso odontogênico vestibular: dente não vital, sinais flogísticos.', 'Cisto do ducto nasopalatino: linha média, intraósseo, com nervos.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC3642254/'],
  },
  {
    id: 'cisto-cirurgico-ciliado',
    name: 'Cisto cirúrgico ciliado',
    aka: ['cisto pós-operatório maxilar', 'surgical ciliated cyst (entrada nova na OMS 2022)'],
    sites: ['maxilares', 'nariz'],
    linings: ['respiratorio-ciliado'],
    features: ['cilios', 'celulas-caliciformes', 'glandulas-seromucosas', 'metaplasia-escamosa'],
    lining: 'Respiratório: colunar pseudoestratificado ciliado com caliciformes; metaplasia escamosa ou cuboidização focal possível.',
    wall: 'Conjuntivo fibroso com inflamação crônica, às vezes glândulas seromucosas e granulação.',
    contents: 'Material mucoide ou seroso, às vezes purulento.',
    where: 'Maxila posterior ou parede do seio maxilar, no lugar de cirurgia prévia (Caldwell-Luc, Le Fort I, enxerto sinusal), com latência de 10 a 20 anos; raro na mandíbula em sítio de enxerto.',
    clues: ['História de cirurgia maxilar ou sinusal anos antes.', 'Radiolucidez bem delimitada separada do seio.'],
    mimics: ['Mucocele do seio maxilar: expande o próprio seio.', 'Cisto radicular com metaplasia ciliada: dente não vital.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC11126345/'],
  },
  {
    id: 'defeito-de-stafne',
    name: 'Defeito de Stafne',
    aka: ['cavidade óssea de Stafne', 'defeito ósseo lingual mandibular', 'Stafne bone cavity'],
    sites: ['maxilares'],
    linings: ['sem-revestimento'],
    pseudocyst: true,
    lining: 'Não é cisto: nenhum revestimento epitelial e nenhum conteúdo cístico; a concavidade contém tecido normal.',
    wall: 'Glândula salivar normal (submandibular na forma posterior, sublingual na anterior), gordura, conjuntivo e vasos.',
    contents: 'Sem líquido: glândula salivar herniada.',
    where: 'Depressão na cortical lingual da mandíbula, abaixo do canal mandibular, entre o primeiro molar e o ângulo; variante anterior lingual aos pré-molares.',
    clues: ['Radiolucidez ovalada bem corticalizada abaixo do canal mandibular, incidental e assintomática.', 'TC ou RM mostram a continuidade com a glândula submandibular; dispensa biópsia.'],
    mimics: ['Cisto ósseo simples: acima do canal, cavidade vazia.', 'Cisto residual ou radicular: relação com dente.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC5091005/'],
  },
  {
    id: 'mucocele-e-ranula',
    name: 'Mucocele (extravasamento mucoso) e rânula',
    aka: ['fenômeno de extravasamento mucoso', 'rânula mergulhante', 'mucocele', 'ranula'],
    sites: ['boca', 'salivares', 'pescoco'],
    linings: ['sem-revestimento'],
    features: ['muco', 'inflamacao'],
    pseudocyst: true,
    lining: 'Nenhum: pseudocisto delimitado por tecido de granulação e conjuntivo comprimido.',
    wall: 'Granulação com fibroblastos, vasos, inflamação mista e mucífagos (macrófagos espumosos com mucina, em mais da metade dos casos); ducto rompido e glândula adjacente com sialadenite.',
    contents: 'Mucina pálida com neutrófilos e mucífagos.',
    where: 'Lábio inferior (mais de 60%, glândulas menores), mucosa jugal, ventre da língua; a rânula é a mucocele do assoalho bucal (glândula sublingual) e mergulha para o pescoço quando atravessa o milo-hióideo.',
    clues: ['Nódulo flutuante azulado no lábio inferior de jovem, com trauma e recidiva.', 'Ausência de epitélio mais mucífagos.'],
    mimics: ['Cisto do ducto salivar: tem revestimento epitelial, a diferença central.', 'Cisto linfoepitelial oral: escamoso mais linfoide.'],
    sources: ['https://www.pathologyoutlines.com/topic/salivaryglandsmucocele.html', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2894742/'],
  },
  {
    id: 'cisto-do-ducto-salivar',
    name: 'Cisto do ducto salivar (retenção mucosa)',
    aka: ['cisto de retenção mucosa', 'sialocisto', 'salivary duct cyst'],
    sites: ['salivares', 'boca'],
    linings: ['cuboidal-simples', 'oncocitico', 'colunar-mucinoso', 'escamoso-nao-queratinizado', 'respiratorio-ciliado'],
    features: ['muco'],
    lining: 'Epitélio ductal verdadeiro: 1 a 2 camadas de células cuboides a colunares na maioria; metaplasia oncocítica (cerca de metade), mucosa, escamosa, ciliada ou apócrina são frequentes.',
    wall: 'Conjuntivo fibroso com linfócitos esparsos; parênquima adjacente com atrofia acinar e sialadenite obstrutiva.',
    contents: 'Muco espesso, às vezes com sialólito.',
    where: 'Parótida e, na boca, mucosa jugal, assoalho e lábio; adultos mais velhos que os da mucocele.',
    clues: ['Revestimento epitelial contínuo: é o que separa da mucocele.', 'Procure sialólito obstrutivo.'],
    mimics: ['Mucocele: sem epitélio, com mucífagos.', 'Cisto linfoepitelial: manto linfoide com centros germinativos.', 'Tumor de Warthin: oncocítico bilaminar papilar com estroma linfoide.'],
    sources: ['https://pubmed.ncbi.nlm.nih.gov/28349371/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3716020/'],
  },
  {
    id: 'cisto-linfoepitelial',
    name: 'Cisto linfoepitelial (inclusive o do HIV)',
    aka: ['cisto branquial intraparotídeo', 'lesão linfoepitelial cística do HIV', 'cisto linfoepitelial oral', 'lymphoepithelial cyst'],
    sites: ['salivares', 'boca', 'pescoco'],
    linings: ['linfoepitelial', 'escamoso-nao-queratinizado'],
    features: ['estroma-linfoide', 'queratina-lamelar'],
    lining: 'Escamoso estratificado não queratinizado (às vezes com ceratina na luz), podendo ser cuboide, colunar ou ciliado em focos; emite cordões para o tecido linfoide.',
    wall: 'Tecido linfoide denso com folículos e centros germinativos (irregulares no HIV), histiócitos multinucleados subepiteliais, ductos infiltrados por linfócitos.',
    contents: 'Material ceratínico ou caseoso branco-amarelado, ou fluido claro.',
    where: 'Parótida (múltiplo e bilateral no HIV) e, na boca, assoalho, ventre e borda da língua e palato mole (nódulo amarelado submucoso).',
    clues: ['Parótida cística bilateral em jovem: pesquisar HIV.', 'Centros germinativos abraçando o epitélio.'],
    mimics: ['Cisto branquial: mesma histologia, decide a localização cervical lateral.', 'Tumor de Warthin: oncocítico bilaminar.', 'Metástase cística de carcinoma escamoso ou papilífero: atipia, p16 ou tireoglobulina.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC4291916/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4866143/'],
  },
  {
    id: 'tumor-de-warthin-cistico',
    name: 'Tumor de Warthin (quando cístico)',
    aka: ['cistadenolinfoma papilífero', 'adenolinfoma', 'Warthin tumour'],
    sites: ['salivares'],
    linings: ['oncocitico'],
    features: ['estroma-linfoide'],
    lining: 'Oncocítico bilaminar: camada interna de células colunares altas com citoplasma granular eosinofílico e núcleos em paliçada sobre camada externa de células basais, em arranjo papilar; focos de células mucosas, ciliadas, sebáceas ou escamosas.',
    wall: 'Estroma linfoide denso com folículos e centros germinativos, muitas vezes com arquitetura nodal; infarto e metaplasia escamosa após punção.',
    contents: 'Líquido castanho espesso, tipo óleo de motor, com debris e oncócitos.',
    where: 'Cauda da parótida e linfonodos periparotídeos; homens fumantes acima de 50 anos; bilateral ou multifocal com frequência.',
    clues: ['Dupla camada oncocítica mais linfoide: patognomônico.', 'Cauda da parótida em fumante.'],
    mimics: ['Cisto linfoepitelial: escamoso, não oncocítico.', 'Oncocitoma: sem estroma linfoide.', 'Carcinoma mucoepidermoide, sobretudo em Warthin infartado: células mucosas e intermediárias, MAML2.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK557640/'],
  },
  {
    id: 'cisto-do-ducto-tireoglosso',
    name: 'Cisto do ducto tireoglosso',
    aka: ['cisto tireoglosso', 'thyroglossal duct cyst'],
    sites: ['pescoco', 'tireoide', 'boca'],
    linings: ['respiratorio-ciliado', 'escamoso-nao-queratinizado'],
    features: ['foliculos-tireoidianos', 'estroma-linfoide', 'cilios', 'inflamacao'],
    lining: 'Colunar pseudoestratificado ciliado (respiratório) e ou escamoso estratificado, muitas vezes misto; o segmento lingual tende ao escamoso e o baixo ao respiratório; desnudado quando infectado.',
    wall: 'Conjuntivo com folículos tireoidianos ectópicos (o achado decisivo, presente em parte dos casos), glândulas mucosas, agregados linfoides, inflamação crônica e fibrose; hioide na peça de Sistrunk.',
    contents: 'Material mucoide claro a espesso; pus se infectado.',
    where: 'Linha média cervical, do forame cego ao lobo piramidal, cerca de 65% infra-hióideos em íntima relação com o corpo do hioide; sobe com a protrusão da língua.',
    clues: ['Folículos tireoidianos na parede.', 'Massa mediana que se eleva com a protrusão da língua; operação de Sistrunk.'],
    mimics: ['Cisto dermoide da linha média: anexos cutâneos, não sobe com a língua.', 'Tireoide ectópica: tecido sólido, cintilografia antes de ressecar.', 'Cisto tímico cervical: corpúsculos de Hassall, lateral.'],
    sources: ['https://insightsimaging.springeropen.com/articles/10.1186/s13244-019-0694-x', 'https://link.springer.com/article/10.1007/s12022-015-9354-y'],
  },
  {
    id: 'cisto-branquial-primeira-fenda',
    name: 'Cisto branquial da primeira fenda',
    aka: ['anomalia da primeira fenda branquial tipo I e II de Work', 'first branchial cleft cyst'],
    sites: ['orelha', 'salivares', 'pescoco'],
    linings: ['escamoso-queratinizado'],
    features: ['anexos-cutaneos', 'cartilagem', 'estroma-linfoide'],
    lining: 'Tipo I: só epitélio escamoso queratinizado, sem anexos nem cartilagem (duplicação do conduto auditivo externo). Tipo II: escamoso queratinizado com anexos cutâneos e cartilagem na parede.',
    wall: 'Infiltrado linfocitário focal; no tipo II, cartilagem hialina, anexos e às vezes parênquima parotídeo.',
    contents: 'Ceratina ou material caseoso; secreção pela fístula no conduto ou no pescoço.',
    where: 'Periauricular e parotídeo; tipo I paralelo ao conduto auditivo, tipo II no ângulo da mandíbula com trajeto junto ao nervo facial até o conduto; cerca de 85% dentro ou junto da parótida.',
    clues: ['Otorreia recorrente com tímpano normal, ou abscesso periauricular de repetição na infância.', 'Cartilagem e anexos definem o tipo II.'],
    mimics: ['Cisto branquial da segunda fenda: mais baixo, pré-esternocleidomastóideo, com manto linfoide.', 'Cisto dermoide: sem trajeto ao conduto auditivo.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC3146662/'],
  },
  {
    id: 'cisto-branquial-segunda-fenda',
    name: 'Cisto branquial da segunda fenda',
    aka: ['cisto cervical lateral', 'cisto branquiogênico', 'second branchial cleft cyst'],
    sites: ['pescoco'],
    linings: ['linfoepitelial', 'escamoso-nao-queratinizado', 'respiratorio-ciliado'],
    features: ['estroma-linfoide', 'colesterol', 'queratina-lamelar'],
    lining: 'Escamoso estratificado, em geral não queratinizado (a maioria); numa minoria colunar ciliado respiratório, ou misto.',
    wall: 'Manto de tecido linfoide subepitelial com folículos e centros germinativos, sem arquitetura nodal verdadeira; fibrose e inflamação quando infectado.',
    contents: 'Líquido turvo com ceratina e colesterol; pus se infectado.',
    where: 'Terço superior e médio do pescoço, ao longo da borda anterior do esternocleidomastóideo, lateral à carótida e posterior à submandibular; cerca de 95% das anomalias branquiais.',
    clues: ['Massa cervical lateral flutuante em adolescente ou adulto jovem que cresce após infecção de vias aéreas.', 'Epitélio mais manto linfoide com centros germinativos.'],
    mimics: ['Metástase cística de carcinoma papilífero da tireoide ou de carcinoma escamoso HPV positivo: sempre excluir acima dos 40 anos com p16, TTF-1 e tireoglobulina.', 'Linfonodo necrótico ou tuberculoso.', 'Cisto linfoepitelial parotídeo.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK482467/', 'https://dermnetnz.org/topics/branchial-cleft-cyst-pathology'],
  },
  {
    id: 'cisto-branquial-terceira-e-quarta-fendas',
    name: 'Anomalias branquiais da terceira e quarta fendas',
    aka: ['fístula do seio piriforme', 'third and fourth branchial cleft anomaly'],
    sites: ['pescoco', 'tireoide'],
    linings: ['escamoso-nao-queratinizado', 'respiratorio-ciliado'],
    features: ['inflamacao', 'estroma-linfoide', 'cilios'],
    lining: 'Escamoso estratificado e ou colunar ciliado respiratório, com alterações inflamatórias e fibrose; o trajeto da quarta bolsa costuma ser ciliado.',
    wall: 'Tecido linfoide variável, inflamação crônica, fibrose densa; tireoidite supurativa no parênquima adjacente na forma de quarta bolsa.',
    contents: 'Material mucoide ou purulento; a apresentação típica é abscesso.',
    where: 'Terceira: triângulo posterior, trajeto até a membrana tíreo-hióidea. Quarta: do ápice do seio piriforme ao lobo tireoidiano e mediastino; 93 a 97% à esquerda.',
    clues: ['Tireoidite supurativa ou abscesso cervical recorrente à esquerda em criança.', 'Gás junto ao polo superior da tireoide na imagem; orifício no seio piriforme à laringoscopia.'],
    mimics: ['Tireoidite supurativa primária: procurar o trajeto.', 'Cisto de segunda fenda: anterior ao esternocleidomastóideo, lado indiferente.'],
    sources: ['https://www.ajnr.org/content/31/4/755'],
  },
  {
    id: 'cisto-timico-cervical',
    name: 'Cisto tímico cervical',
    aka: ['cisto do ducto timofaríngeo', 'cervical thymic cyst'],
    sites: ['pescoco', 'mediastino'],
    linings: ['achatado-inespecifico', 'escamoso-nao-queratinizado', 'cuboidal-simples', 'respiratorio-ciliado'],
    features: ['tecido-timico', 'colesterol'],
    lining: 'Variável: cuboide a escamoso estratificado, muitas vezes achatado ou comprimido; colunar ciliado em focos; áreas denudadas com fibrose.',
    wall: 'Tecido tímico com corpúsculos de Hassall (obrigatório para o diagnóstico) e linfócitos; fendas de colesterol com células gigantes; às vezes paratireoide.',
    contents: 'Líquido claro a acastanhado, com colesterol.',
    where: 'Pescoço lateral (mais à esquerda), no trajeto de descida do timo, profundo ao esternocleidomastóideo e junto à carótida; pode alcançar o mediastino; crianças e adultos jovens.',
    clues: ['Corpúsculos de Hassall na parede fecham o diagnóstico.', 'Avaliar extensão mediastinal e timo ortotópico antes de ressecar.'],
    mimics: ['Cisto branquial de segunda fenda: linfoide com centros germinativos, sem Hassall.', 'Higroma cístico: espaços endoteliais D2-40 positivos.', 'Cisto broncogênico: cartilagem e músculo liso.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC3109961/'],
  },
  {
    id: 'higroma-cistico-linfangioma',
    name: 'Linfangioma cístico (higroma cístico, malformação linfática)',
    aka: ['malformação linfática macrocística', 'cystic hygroma', 'lymphangioma'],
    sites: ['pescoco', 'boca', 'mediastino', 'mesenterio', 'pele', 'adrenal', 'baco'],
    linings: ['endotelial'],
    features: ['estroma-linfoide', 'musculo-liso'],
    lining: 'Endotélio achatado e atenuado, sem atipia, D2-40 e CD31 positivos; não é epitélio.',
    wall: 'Septos finos de conjuntivo com agregados linfoides e feixes irregulares de músculo liso; sem cápsula, insinua-se entre as estruturas.',
    contents: 'Linfa: material eosinofílico amorfo com linfócitos, às vezes quilosa ou hemorrágica.',
    where: 'Triângulo posterior e região supraclavicular (clássico), axila, assoalho bucal e língua, mediastino, mesentério; mais de 90% até os 2 anos. Mutação de PIK3CA.',
    clues: ['Massa mole, compressível e transiluminável em lactente.', 'Agregados linfoides na parede mais endotélio D2-40 positivo.'],
    mimics: ['Hemangioma: hemácias na luz, D2-40 negativo, GLUT1 no infantil.', 'Cisto pericárdico ou de inclusão mesotelial: calretinina e WT1 positivos.', 'Teratoma cervical: três folhetos.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC4273562/', 'https://www.pathologyoutlines.com/topic/mediastinumlymphangioma.html'],
  },
  {
    id: 'cisto-paratireoidiano',
    name: 'Cisto de paratireoide',
    aka: ['cisto paratireoidiano funcionante ou não', 'parathyroid cyst'],
    sites: ['tireoide', 'mediastino'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    lining: 'Camada única de epitélio cuboide a colunar baixo, às vezes ciliado, achatado pela pressão.',
    wall: 'Cápsula fibrosa fina com ninhos de células principais da paratireoide (o achado diagnóstico), células oxífilas e gordura; GATA3 e PTH positivos.',
    contents: 'Líquido cristalino, água de rocha, com PTH altíssimo no aspirado; acastanhado nos funcionantes.',
    where: 'Pescoço inferior, junto ao polo inferior da tireoide; pode ser intratireoidiano, mediastinal ou intratímico.',
    clues: ['Punção que devolve líquido cristalino: dosar PTH no aspirado.', 'Citologia quase acelular.'],
    mimics: ['Nódulo tireoidiano cístico: líquido castanho com coloide e hemossiderina.', 'Cisto do ducto tireoglosso: linha média, folículos tireoidianos.', 'Cisto tímico: corpúsculos de Hassall.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC8721403/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11282920/'],
  },
  {
    id: 'nodulo-tireoidiano-cistico',
    name: 'Nódulo tireoidiano cístico (cisto coloide)',
    aka: ['nódulo coloide com degeneração cística', 'doença nodular folicular', 'cystic thyroid nodule'],
    sites: ['tireoide'],
    linings: ['folicular-tireoidiano', 'achatado-inespecifico'],
    features: ['coloide', 'hemossiderina', 'sangue', 'calcificacao'],
    lining: 'Epitélio folicular achatado ou atenuado, às vezes hiperplásico, muitas vezes descontínuo ou perdido: é um folículo dilatado e degenerado, não um cisto de revestimento próprio.',
    wall: 'Hemorragia recente e antiga, macrófagos espumosos e com hemossiderina, fibrose, calcificação, metaplasia óssea e reação granulomatosa a folículo roto.',
    contents: 'Coloide espesso ou degenerado misturado a sangue antigo (líquido achocolatado).',
    where: 'Qualquer lobo ou istmo; 15 a 25% dos nódulos tireoidianos são císticos.',
    clues: ['Punção com líquido castanho, coloide e macrófagos com hemossiderina (Bethesda II).', 'Nódulo que colapsa após aspiração.'],
    mimics: ['Carcinoma papilífero cístico: núcleos em vidro fosco, fendas e pseudoinclusões nas paredes; repuncionar o componente sólido.', 'Cisto paratireoidiano: líquido cristalino com PTH.'],
    sources: ['https://www.pathologyoutlines.com/topic/thyroidnodular.html', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2678825/'],
  },
  {
    id: 'colesteatoma',
    name: 'Colesteatoma',
    aka: ['cisto epidermoide da orelha média', 'queratoma', 'cholesteatoma'],
    sites: ['orelha'],
    linings: ['escamoso-queratinizado'],
    features: ['queratina-lamelar', 'inflamacao', 'colesterol'],
    lining: 'Matriz: escamoso estratificado queratinizado citologicamente banal, com as quatro camadas da epiderme e índice proliferativo alto, sem atipia.',
    wall: 'Perimatriz: conjuntivo subepitelial ou granulação com inflamação produtora de citocinas osteolíticas; osso adjacente em reabsorção.',
    contents: 'Lamelas de ceratina em camadas concêntricas (bulbo de cebola), branco-peroladas, com colesterol e debris, muitas vezes infectadas.',
    where: 'Orelha média e mastoide: ático e espaço de Prussak, a partir de bolsa de retração da pars flaccida; congênito atrás de tímpano íntegro no quadrante ântero-superior.',
    clues: ['Otorreia fétida com massa branca perolada retrotimpânica e perda condutiva.', 'Três critérios: epitélio escamoso queratinizado, conjuntivo ou granulação e debris de ceratina.'],
    mimics: ['Granuloma de colesterol: cristais e hemossiderina sem epitélio escamoso.', 'Otite média crônica com metaplasia escamosa: sem massa de ceratina em crescimento.', 'Carcinoma escamoso do osso temporal: atipia e invasão.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9445956/'],
  },
]
