/* ==========================================================================
   pelvis.ts — trato genital feminino (ovário, tuba e ligamento largo,
   útero e colo, vagina e vulva), trato genital masculino (próstata e
   vesículas seminais, testículo e epidídimo, pênis), bexiga e úraco.
   As três perguntas que mais aparecem: tubário ciliado (mülleriano) vs
   mesonéfrico (não ciliado, sem mucina, secreção eosinofílica, GATA3) vs
   mucinoso; e quem tem espermatozoide na luz. Conferido em 2026-09-12.
   ========================================================================== */

import type { Cyst } from '../types'

export const pelvis: Cyst[] = [
  {
    id: 'cisto-folicular',
    name: 'Cisto folicular do ovário',
    aka: ['follicular cyst'],
    sites: ['ovario'],
    linings: ['celulas-granulosas'],
    lining: 'Camada interna de células da granulosa (muitas vezes atrófica ou desnudada pela pressão) sobre camada externa de teca interna; sem cílios, sem mucina.',
    wall: 'Granulosa e teca, que podem estar luteinizadas; fibrose se antigo.',
    contents: 'Líquido claro a seroso, às vezes hemorrágico.',
    where: 'Córtex ovariano na menacme, unilateral e único, maior que 3 cm (abaixo disso é folículo cístico); regride sozinho.',
    clues: ['Duas camadas distintas: granulosa por dentro, teca por fora.'],
    mimics: ['Cisto de corpo lúteo: parede convoluta e luteinizada em toda a extensão.', 'Cistadenoma seroso: epitélio tubário ciliado, não granulosa.'],
    sources: ['https://www.pathologyoutlines.com/topic/ovarynontumorfollicularcysts.html', 'https://www.ncbi.nlm.nih.gov/books/NBK560541/'],
  },
  {
    id: 'cisto-corpo-luteo',
    name: 'Cisto de corpo lúteo',
    aka: ['cisto lúteo', 'cisto hemorrágico do corpo lúteo', 'corpus luteum cyst'],
    sites: ['ovario'],
    linings: ['celulas-granulosas'],
    features: ['sangue', 'hemossiderina'],
    lining: 'Camada interna festonada de células da granulosa luteinizadas (poligonais, citoplasma eosinofílico abundante) com camada externa de teca luteinizada menor.',
    wall: 'Granulosa e teca luteinizadas, fibrina, hemorragia central, fibrose e hemossiderina na involução.',
    contents: 'Líquido hemorrágico, coágulo central.',
    where: 'Ovário, unilateral, maior que 3 cm, com contorno interno pregueado amarelo; gestação ou fase lútea.',
    clues: ['Parede convoluta amarela com células luteinizadas.'],
    mimics: ['Cisto folicular: parede lisa, granulosa não luteinizada.', 'Endometrioma: estroma endometrial e hemossiderófagos, sem células luteínicas.'],
    sources: ['https://www.pathologyoutlines.com/topic/ovarynontumorcorpuslutcyst.html'],
  },
  {
    id: 'cisto-teca-luteinico',
    name: 'Cisto tecaluteínico',
    aka: ['hiperreactio luteinalis (múltiplos e bilaterais)', 'theca lutein cyst'],
    sites: ['ovario'],
    linings: ['celulas-granulosas'],
    lining: 'Teca interna hipertrofiada e luteinizada; a granulosa pode estar presente, luteinizada ou ausente.',
    wall: 'Teca luteinizada espessa, edema estromal.',
    contents: 'Líquido claro a hemorrágico.',
    where: 'Ambos os ovários, múltiplos e aumentados; hCG elevado: mola, coriocarcinoma, gestação múltipla, indução de ovulação.',
    clues: ['Bilateralidade e multiplicidade são a chave.', 'Contexto de hCG alto.'],
    mimics: ['Cisto folicular: unilateral e único.', 'Ovário policístico: folículos subcorticais pequenos com estroma denso.'],
    sources: ['https://webpath.med.utah.edu/FEMHTML/FEM122.html'],
  },
  {
    id: 'endometrioma',
    name: 'Cisto endometriótico (endometrioma)',
    aka: ['cisto de chocolate', 'endometriotic cyst'],
    sites: ['ovario', 'mesenterio', 'pele', 'vulva', 'retrorretal', 'tuba'],
    linings: ['endometrioide', 'sem-revestimento'],
    features: ['estroma-endometrial', 'hemossiderina', 'sangue'],
    lining: 'Epitélio endometrial colunar ou cuboide, muitas vezes atenuado; em cerca de 40% da superfície não há epitélio, substituído por fibrose e macrófagos.',
    wall: 'Estroma endometrial, macrófagos com hemossiderina, fibrose, células pseudoxantomatosas; formas antigas só com fibrose e pseudoxantoma.',
    contents: 'Material espesso achocolatado (sangue degradado).',
    where: 'Ovário (bilateral em até metade), aderido, com endometriose peritoneal; também cicatrizes cutâneas, canal de Nuck, septo retovaginal.',
    clues: ['Dois de quatro: epitélio endometrial, glândulas, estroma, hemossiderófagos.', 'Dismenorreia e infertilidade.'],
    mimics: ['Cisto hemorrágico do corpo lúteo: células luteínicas, sem estroma endometrial.', 'Carcinoma de células claras ou endometrioide sobre endometrioma: atipia e papilas.', 'Cisto de inclusão com metaplasia: sem estroma endometrial.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK567777/'],
  },
  {
    id: 'cistadenoma-seroso',
    name: 'Cistadenoma seroso do ovário',
    aka: ['serous cystadenoma'],
    sites: ['ovario'],
    linings: ['ciliado-mulleriano'],
    features: ['cilios', 'estroma-ovariano'],
    lining: 'Epitélio tubário: camada única de células cúbicas a colunares ciliadas e secretoras, sem estratificação nem atipia.',
    wall: 'Estroma ovariano fibroso; papilas em menos de 10% da superfície (mais que isso é cistadenofibroma ou borderline).',
    contents: 'Líquido seroso claro.',
    where: 'Ovário, uni ou bilateral, maior que 1 cm (por convenção; menor é cisto de inclusão).',
    clues: ['Cílios visíveis; parede fina e lisa.'],
    mimics: ['Cisto de inclusão cortical: 1 cm ou menos.', 'Cisto paratubário: fora do ovário.', 'Tumor seroso borderline: estratificação, tufos, atipia.'],
    sources: ['https://www.pathologyoutlines.com/topic/ovarytumorserousbenign.html'],
  },
  {
    id: 'cistadenoma-mucinoso',
    name: 'Cistadenoma mucinoso do ovário',
    aka: ['mucinous cystadenoma'],
    sites: ['ovario'],
    linings: ['colunar-mucinoso'],
    features: ['celulas-caliciformes', 'muco', 'estroma-ovariano'],
    lining: 'Colunar mucinoso de tipo gastrointestinal, com caliciformes, mucina apical e núcleos basais sem atipia; a OMS 2020 admite também o tipo mülleriano.',
    wall: 'Estroma ovariano; focos de teratoma ou Brenner associados.',
    contents: 'Mucina espessa, gelatinosa.',
    where: 'Ovário, quase sempre unilateral, volumoso e multilocular, com loculações de tamanhos diferentes.',
    clues: ['Caliciformes confirmam o tipo intestinal.', 'Amostrar amplamente para excluir borderline.'],
    mimics: ['Metástase mucinosa (apêndice, pâncreas): bilateral, nodular, pseudomixoma.', 'Cistadenoma seromucinoso: mucinoso endocervical mais ciliadas.', 'Borderline mucinoso: estratificação acima de 3 camadas, atipia.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11697686/'],
  },
  {
    id: 'cistadenoma-seromucinoso',
    name: 'Cistadenoma seromucinoso do ovário',
    aka: ['antigo mucinoso de tipo endocervical', 'seromucinous cystadenoma'],
    sites: ['ovario'],
    linings: ['colunar-mucinoso', 'ciliado-mulleriano'],
    features: ['cilios', 'muco', 'estroma-endometrial'],
    lining: 'Mistura de colunar mucinoso endocervical (mucina apical, sem caliciformes) com células serosas ciliadas; podem coexistir células endometrioides e escamosas.',
    wall: 'Estroma ovariano, muitas vezes com endometriose adjacente.',
    contents: 'Líquido mucinoso claro a espesso.',
    where: 'Ovário, com frequência associado a endometriose.',
    clues: ['Ciliadas e mucinosas endocervicais no mesmo revestimento, sem caliciformes.'],
    mimics: ['Cistadenoma mucinoso intestinal: caliciformes.', 'Cistadenoma seroso: só tubário.'],
    sources: ['https://www.pathologyoutlines.com/topic/ovaryseromucinouscystadenoma.html'],
  },
  {
    id: 'teratoma-cistico-maduro',
    name: 'Teratoma cístico maduro (cisto dermoide)',
    aka: ['dermoid cyst', 'mature cystic teratoma'],
    sites: ['ovario', 'mediastino', 'testiculo', 'retrorretal', 'mesenterio'],
    linings: ['escamoso-queratinizado', 'respiratorio-ciliado', 'colunar-mucinoso'],
    features: ['anexos-cutaneos', 'sebo-pelos', 'cartilagem', 'tecido-glial', 'foliculos-tireoidianos', 'calcificacao', 'tecido-timico'],
    lining: 'Escamoso estratificado queratinizado com camada granulosa e anexos na parede; outros lóculos com epitélio respiratório ciliado ou intestinal e gástrico.',
    wall: 'Derivados dos três folhetos: pele com anexos, cartilagem, osso, dente, gordura, glia, tireoide, epitélio respiratório e digestivo; no mediastino, tecido pancreático e timo residual; protuberância de Rokitansky no ovário.',
    contents: 'Material sebáceo e queratina, pelos; sólido e gorduroso à temperatura ambiente.',
    where: 'Ovário na idade reprodutiva (bilateral em 10 a 15%); mediastino anterior (o tumor germinativo extragonadal mais comum); sacrococcígeo no recém-nascido.',
    clues: ['Anexos cutâneos na parede (o epidermoide não os tem).', 'Gordura e calcificação ou dente na TC; tecido pancreático é típico do mediastinal.'],
    mimics: ['Cisto epidermoide: só epitélio escamoso, sem anexos nem outros folhetos.', 'Struma ovarii: tireoide em mais de 50%.', 'Teratoma imaturo: neuroepitélio imaturo.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC10093990/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3794101/'],
  },
  {
    id: 'struma-ovarii-cistico',
    name: 'Struma ovarii com alteração cística',
    aka: ['bócio ovariano', 'cystic struma ovarii'],
    sites: ['ovario'],
    linings: ['folicular-tireoidiano', 'achatado-inespecifico'],
    features: ['coloide', 'foliculos-tireoidianos'],
    lining: 'Epitélio folicular tireoidiano cúbico a achatado revestindo folículos dilatados; nos cistos grandes fica achatado e atrófico.',
    wall: 'Tecido tireoidiano maduro com folículos de vários tamanhos; outros componentes teratomatosos possíveis.',
    contents: 'Coloide eosinofílico, às vezes líquido acastanhado espesso.',
    where: 'Ovário, unilateral; teratoma monodérmico.',
    clues: ['Coloide mais TTF-1 e tireoglobulina positivos.'],
    mimics: ['Teratoma cístico maduro com foco tireoidiano: menos de 50% do tumor.', 'Carcinoma folicular em struma: invasão capsular ou vascular.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166242/'],
  },
  {
    id: 'cisto-rete-ovarii',
    name: 'Cisto da rete ovarii',
    aka: ['cisto do hilo ovariano', 'rete ovarii cyst'],
    sites: ['ovario'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['musculo-liso'],
    lining: 'Achatado, cúbico ou colunar, em geral não ciliado e sem mucina, com fendas e criptas irregulares na superfície interna.',
    wall: 'Parede fibromuscular; células hilares (de Leydig) e feixes de músculo liso no estroma adjacente.',
    contents: 'Líquido seroso claro.',
    where: 'Hilo do ovário, obrigatoriamente; unilateral, pós-menopausa.',
    clues: ['Localização hilar é o critério decisivo.', 'Fendas na face interna do cisto.'],
    mimics: ['Cistadenoma seroso: intraparenquimatoso, ciliado.', 'Cisto mesonéfrico do ligamento largo: extraovariano, secreção eosinofílica.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC9676129/'],
  },
  {
    id: 'cisto-inclusao-epitelial-superficie',
    name: 'Cisto de inclusão epitelial de superfície do ovário',
    aka: ['cisto de inclusão cortical', 'cortical inclusion cyst'],
    sites: ['ovario'],
    linings: ['mesotelial', 'ciliado-mulleriano'],
    features: ['calcificacao'],
    lining: 'Dois tipos: achatado ou cúbico de tipo mesotelial, vindo do epitélio de superfície (calretinina positivo), ou tubário ciliado cúbico a colunar (PAX8 positivo), este só depois da menarca.',
    wall: 'Estroma cortical, às vezes com corpos psamomatosos.',
    contents: 'Líquido seroso escasso, muitas vezes colapsado.',
    where: 'Córtex superficial, múltiplos, 1 cm ou menos (acima disso é cistadenoma); achado incidental.',
    clues: ['Distinguir os dois imunofenótipos: calretinina versus PAX8.'],
    mimics: ['Cistadenoma seroso: maior que 1 cm.', 'Endossalpingiose: glândulas tubárias fora do ovário.', 'Cisto folicular: granulosa e teca.'],
    sources: ['https://www.pathologyoutlines.com/topic/ovarynontumorinclusioncyst.html', 'https://pubmed.ncbi.nlm.nih.gov/25473746/'],
  },
  {
    id: 'cisto-paratubario',
    name: 'Cisto paratubário (paraovariano)',
    aka: ['cisto do mesossalpinge', 'paratubal cyst'],
    sites: ['tuba'],
    linings: ['ciliado-mulleriano', 'achatado-inespecifico'],
    features: ['cilios'],
    lining: 'Na maioria paramesonéfrico: epitélio tubário de camada única com células ciliadas, secretoras e intercalares, às vezes achatado pela pressão. Existem variantes mesonéfrica e mesotelial.',
    wall: 'Parede fibrosa fina com escassas fibras musculares lisas; sem estroma ovariano.',
    contents: 'Líquido seroso claro.',
    where: 'Mesossalpinge e mesovário, entre tuba e ovário, fora do ovário; unilateral.',
    clues: ['Ovário e tuba íntegros e separados do cisto.', 'Parede fina translúcida.'],
    mimics: ['Cistadenoma seroso: dentro do ovário.', 'Hidrossalpinge: luz tubária com pregas rombas.', 'Cisto mesonéfrico: cúbico não ciliado, secreção eosinofílica.'],
    sources: ['https://www.pathologyoutlines.com/topic/fallopiantubesparatubalcyst.html'],
  },
  {
    id: 'hidatide-de-morgagni',
    name: 'Hidátide de Morgagni',
    aka: ['apêndice vesicular', 'cisto paratubário fimbriado', 'hydatid of Morgagni'],
    sites: ['tuba'],
    linings: ['ciliado-mulleriano'],
    features: ['cilios'],
    lining: 'Epitélio tubário ciliado em camada única, muitas vezes com pregas papilíferas.',
    wall: 'Eixo fibrovascular frouxo e pedículo delgado; sem músculo liso significativo.',
    contents: 'Líquido seroso claro.',
    where: 'Pediculado na extremidade fimbriada da tuba; achado incidental muito comum; pode torcer.',
    clues: ['Pendurado na fímbria por um pedículo fino.'],
    mimics: ['Cisto paratubário do mesossalpinge: não pediculado na fímbria.', 'Tumor adenomatoide: sólido, mesotelial.'],
    sources: ['https://www.pathologyoutlines.com/topic/fallopiantubesdevelopmentalcysts.html'],
  },
  {
    id: 'cisto-mesonefrico-ligamento-largo',
    name: 'Cisto mesonéfrico (de Wolff) do ligamento largo',
    aka: ['cisto do epoóforo', 'cisto do paroóforo', 'Wolffian cyst'],
    sites: ['tuba'],
    linings: ['colunar-nao-ciliado', 'cuboidal-simples'],
    features: ['musculo-liso', 'material-eosinofilico'],
    lining: 'Colunar baixo a cúbico, não ciliado e sem mucina, às vezes pseudoestratificado, com material eosinofílico hialino na luz; GATA3 positivo.',
    wall: 'Feixes de músculo liso bem formados, parede mais espessa que a do cisto paratubário mülleriano.',
    contents: 'Líquido claro, às vezes com secreção eosinofílica densa.',
    where: 'Entre os folhetos do ligamento largo: epoóforo (entre tuba e ovário) e paroóforo (abaixo do ovário).',
    clues: ['Sem cílios, secreção luminal eosinofílica, GATA3 e CD10 luminal.', 'Túbulos residuais enfileirados no ligamento largo.'],
    mimics: ['Cisto paratubário mülleriano: ciliado, PAX8 positivo.', 'Tumor de Wolff: sólido, em peneira.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5154314/'],
  },
  {
    id: 'ninho-de-walthard',
    name: 'Ninho de Walthard (cístico)',
    aka: ['restos de Walthard', 'metaplasia transicional', 'Walthard cell nest'],
    sites: ['tuba', 'ovario', 'testiculo'],
    linings: ['urotelial', 'colunar-mucinoso'],
    features: ['material-eosinofilico'],
    lining: 'Transicional (urotelial-símile) metaplásico, com núcleos ovais e sulco longitudinal em grão de café; quando cístico pode sofrer metaplasia mucinosa. GATA3 positivo.',
    wall: 'Conjuntivo subseroso; nódulo ou placa sólida que cavita.',
    contents: 'Material eosinofílico ou mucinoso escasso.',
    where: 'Subserosa da tuba (o mais comum), mesossalpinge, mesovário e hilo; também no cordão espermático. Nódulos brancacentos de 2 mm ou menos.',
    clues: ['Núcleos em grão de café.'],
    mimics: ['STIC ou metástase: atipia, p53, Ki-67.', 'Tumor de Brenner: mesma linhagem, massa ovariana com estroma fibroso.', 'Cisto paratubário: ciliado.'],
    sources: ['https://www.pathologyoutlines.com/topic/fallopiantubeswalthard.html'],
  },
  {
    id: 'hidrossalpinge',
    name: 'Hidrossalpinge',
    aka: ['hydrosalpinx'],
    sites: ['tuba'],
    linings: ['ciliado-mulleriano', 'achatado-inespecifico'],
    features: ['musculo-liso', 'inflamacao'],
    lining: 'Epitélio tubário atenuado com perda parcial de cílios; pregas rombas, fusionadas e aderentes.',
    wall: 'Parede tubária com músculo liso próprio, fibrose, inflamação crônica e aderências.',
    contents: 'Líquido seroso claro (pus na piossalpinge, sangue na hematossalpinge).',
    where: 'A própria tuba dilatada, distal (ampola e infundíbulo obstruídos); antecedente de doença inflamatória pélvica.',
    clues: ['Forma de retorta com pregas incompletas (roda dentada).', 'Não é cisto anexial, é a tuba.'],
    mimics: ['Cisto paratubário: fora da luz, parede fina sem músculo.', 'Cisto de inclusão peritoneal: mesotélio, sem parede própria.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10183881/'],
  },
  {
    id: 'cisto-inclusao-peritoneal',
    name: 'Cisto de inclusão mesotelial (peritoneal, pleural, pericárdico)',
    aka: ['pseudocisto peritoneal', 'mesotelioma cístico multilocular benigno', 'ovário aprisionado', 'peritoneal inclusion cyst'],
    sites: ['mesenterio', 'tuba', 'ovario', 'pulmao', 'coracao', 'testiculo'],
    linings: ['mesotelial'],
    features: ['inflamacao'],
    pseudocyst: true,
    lining: 'Mesotélio achatado a cúbico, camada única, sem atipia nem mitoses, às vezes em tachinha; calretinina, WT1, CK5/6 e citoqueratina positivos; CD31 e CD34 negativos.',
    wall: 'Septos fibromixoides com inflamação crônica e hiperplasia mesotelial reativa; sem parede própria verdadeira, formado por aderências.',
    contents: 'Líquido seroso claro.',
    where: 'Pelve feminina abraçando o ovário e as superfícies peritoneais, mesentério e omento; raro na pleura, pericárdio e túnica vaginal; após cirurgia, DIP ou endometriose.',
    clues: ['Molda-se aos contornos pélvicos e aprisiona o ovário.', 'Calretinina e WT1 positivos com CD31 negativo separam do linfangioma; D2-40 marca os dois e não serve.'],
    mimics: ['Linfangioma: CD31 e ERG positivos, calretinina negativa, conteúdo quiloso, folículos linfoides.', 'Mesotelioma maligno: atipia, invasão, perda de BAP1.', 'Cistadenoma seroso: ciliado, PAX8 positivo.'],
    sources: ['https://www.pathologyoutlines.com/topic/pleuraperitmulticysticmeso.html', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11465409/'],
  },
  {
    id: 'cisto-de-naboth',
    name: 'Cisto de Naboth',
    aka: ['ovulo nabothi', 'cisto de retenção endocervical', 'nabothian cyst'],
    sites: ['utero'],
    linings: ['colunar-mucinoso'],
    features: ['muco', 'metaplasia-escamosa'],
    lining: 'Colunar mucinoso endocervical em camada única, achatado pela pressão do muco; metaplasia escamosa na abertura obstruída.',
    wall: 'Estroma fibromuscular cervical, sem reação estromal nem atipia.',
    contents: 'Muco espesso claro a amarelado.',
    where: 'Zona de transformação e endocérvice superficial; achado banal.',
    clues: ['Cripta obstruída por epitélio escamoso metaplásico.'],
    mimics: ['Tunnel clusters: agregados lobulares de glândulas dilatadas.', 'Hiperplasia endocervical lobular (LEGH): epitélio gástrico ou pilórico, HIK1083 positivo.', 'Adenocarcinoma de desvio mínimo: glândulas irregulares profundas com desmoplasia.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC11833274/'],
  },
  {
    id: 'tunnel-clusters',
    name: 'Tunnel clusters (agrupamentos em túnel)',
    aka: ['tipo A não cístico e tipo B cístico', 'cystic endocervical tunnel clusters'],
    sites: ['utero'],
    linings: ['colunar-mucinoso', 'achatado-inespecifico'],
    features: ['muco'],
    lining: 'Colunar mucinoso endocervical, achatado ou cúbico nas cavidades do tipo B, sem atipia nem mitoses.',
    wall: 'Estroma cervical normal, sem desmoplasia; arquitetura lobular com limite inferior nítido.',
    contents: 'Muco eosinofílico inspissado.',
    where: 'Endocérvice superficial de multíparas de meia-idade.',
    clues: ['Agregado lobular de glândulas dilatadas confinado à metade superficial da parede, contorno arredondado.'],
    mimics: ['LEGH: epitélio gástrico, MUC6 positivo, precursor potencial.', 'Adenocarcinoma de desvio mínimo: infiltração profunda, desmoplasia.', 'Cistos de Naboth múltiplos: não lobulados.'],
    sources: ['https://www.pathologyoutlines.com/topic/cervixtunnelclusters.html'],
  },
  {
    id: 'remanescente-mesonefrico-cervical',
    name: 'Cisto de remanescente mesonéfrico do colo',
    aka: ['restos de Wolff cervicais', 'mesonephric remnants'],
    sites: ['utero'],
    linings: ['colunar-nao-ciliado', 'cuboidal-simples'],
    features: ['material-eosinofilico'],
    lining: 'Cúbico a colunar baixo, não ciliado e sem mucina, às vezes pseudoestratificado, com material eosinofílico hialino denso na luz; GATA3 ou TTF-1 positivos, CD10 luminal.',
    wall: 'Estroma cervical fibromuscular; ducto central maior com túbulos satélites em lóbulos.',
    contents: 'Secreção eosinofílica hialina, PAS positiva, não mucinosa.',
    where: 'Parede lateral profunda do colo, não superficial.',
    clues: ['Profundo e lateral, secreção eosinofílica, mucicarmim negativo.'],
    mimics: ['Naboth e tunnel clusters: mucina endocervical, superficiais.', 'Carcinoma mesonéfrico: massa, atipia, mitoses.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC11833274/'],
  },
  {
    id: 'adenomiose-cistica',
    name: 'Adenomiose cística',
    aka: ['adenomioma cístico', 'cystic adenomyosis'],
    sites: ['utero'],
    linings: ['endometrioide'],
    features: ['estroma-endometrial', 'hemossiderina', 'sangue', 'musculo-liso'],
    lining: 'Epitélio endometrial (muitas vezes inativo ou desnudado pela hemorragia) com estroma endometrial subjacente, obrigatório.',
    wall: 'Estroma endometrial cercado por miométrio hipertrofiado; hemossiderófagos.',
    contents: 'Sangue antigo achocolatado.',
    where: 'Intramural, sem comunicação com a cavidade; variante juvenil na parede anterior.',
    clues: ['Cavidade maior que 1 cm dentro do miométrio com glândulas e estroma endometriais.'],
    mimics: ['Corno rudimentar: miométrio próprio organizado e endométrio funcionante.', 'Leiomioma com degeneração cística: sem epitélio.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC7943350/'],
  },
  {
    id: 'cisto-ducto-de-gartner',
    name: 'Cisto do ducto de Gartner',
    aka: ['cisto mesonéfrico vaginal', 'Gartner duct cyst'],
    sites: ['vulva'],
    linings: ['colunar-nao-ciliado', 'cuboidal-simples'],
    lining: 'Cúbico ou colunar baixo, não mucinoso e não ciliado, em camada única; GATA3 positivo, mucicarmim negativo.',
    wall: 'Tecido fibromuscular fino da parede vaginal.',
    contents: 'Líquido claro seroso, não mucoide.',
    where: 'Parede ântero-lateral da vagina, quase sempre lateral; pode alcançar o colo; anomalias renais ipsilaterais associadas.',
    clues: ['Posição lateral alta, epitélio sem mucina e sem cílios.'],
    mimics: ['Cisto mülleriano da vagina: mucinoso endocervical, mucicarmim positivo.', 'Cisto de inclusão epidérmica: escamoso queratinizado.', 'Ureter ectópico ou uretrocele.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7580392/'],
  },
  {
    id: 'cisto-mulleriano-vagina',
    name: 'Cisto mülleriano da vagina',
    aka: ['cisto paramesonéfrico vaginal', 'Müllerian cyst'],
    sites: ['vulva'],
    linings: ['colunar-mucinoso', 'ciliado-mulleriano', 'endometrioide'],
    features: ['muco', 'cilios'],
    lining: 'Colunar mucinoso endocervical; pode ser tubário ciliado ou endometrioide, muitas vezes misto.',
    wall: 'Estroma fibroso da parede vaginal, sem músculo liso organizado.',
    contents: 'Muco claro a espesso.',
    where: 'Qualquer segmento da vagina; o cisto vaginal embrionário mais comum.',
    clues: ['Mucina intraluminal com epitélio mucinoso, sem restrição à parede lateral.'],
    mimics: ['Cisto de Gartner: cúbico não mucinoso, lateral.', 'Cisto de Bartholin: vestibular, transicional.'],
    sources: ['https://www.pathologyoutlines.com/topic/vaginacysts.html'],
  },
  {
    id: 'cisto-inclusao-epidermica-genital',
    name: 'Cisto de inclusão epidérmica da vulva e da vagina',
    aka: ['cisto epidermoide vulvar', 'cisto pós-episiotomia', 'squamous inclusion cyst'],
    sites: ['vulva'],
    linings: ['escamoso-queratinizado'],
    features: ['queratina-lamelar'],
    lining: 'Escamoso estratificado com camada granulosa preservada e queratina lamelar, sem hastes pilosas.',
    wall: 'Derme ou estroma fibroso; granuloma de corpo estranho se rompido.',
    contents: 'Queratina lamelar, material caseoso branco-amarelado.',
    where: 'Lábios maiores e clitóris (o cisto vulvar mais frequente); na vagina, terço inferior e parede posterior, em laceração, episiotomia ou cirurgia prévia.',
    clues: ['Camada granulosa presente.', 'Antecedente de trauma obstétrico ou cirúrgico na vagina.'],
    mimics: ['Cisto de Bartholin: posterior, transicional.', 'Esteatocistoma: cutícula ondulada, sebáceas na parede, sem granulosa.', 'Cisto mülleriano: mucinoso.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK532310/', 'https://www.pathologyoutlines.com/topic/vaginacysts.html'],
  },
  {
    id: 'cisto-ducto-bartholin',
    name: 'Cisto do ducto de Bartholin',
    aka: ['cisto da glândula vestibular maior', 'Bartholin duct cyst'],
    sites: ['vulva'],
    linings: ['urotelial', 'escamoso-nao-queratinizado', 'colunar-mucinoso'],
    features: ['muco', 'inflamacao'],
    lining: 'Predominantemente transicional (o revestimento normal do ducto); escamoso perto do óstio e colunar mucinoso nos ácinos residuais; os três coexistem.',
    wall: 'Ácinos mucinosos residuais da glândula na parede, o que confirma a origem; inflamação crônica se infectado.',
    contents: 'Muco claro; pus se abscesso.',
    where: 'Terço posterior do lábio maior e vestíbulo, às 4 e 8 horas; unilateral; idade reprodutiva.',
    clues: ['Posição 4 ou 8 horas mais ácinos mucinosos residuais na parede.'],
    mimics: ['Cisto mucoso do vestíbulo: só colunar mucinoso, sem ácinos de Bartholin, mais anterior.', 'Cisto de inclusão epidérmica: escamoso queratinizado.', 'Carcinoma de Bartholin: massa sólida acima dos 40 anos.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK557803/'],
  },
  {
    id: 'cisto-ducto-de-skene',
    name: 'Cisto do ducto de Skene',
    aka: ['cisto parauretral', 'Skene duct cyst'],
    sites: ['vulva'],
    linings: ['colunar-nao-ciliado', 'urotelial', 'escamoso-nao-queratinizado'],
    lining: 'Colunar pseudoestratificado, transicional ou escamoso estratificado (derivado do seio urogenital); os três padrões descritos.',
    wall: 'Estroma fibroso com inflamação crônica e siderófagos; glândulas parauretrais residuais.',
    contents: 'Líquido claro a mucoide; pus se infectado.',
    where: 'Ao lado do meato uretral, na parede vaginal anterior distal; desloca o meato.',
    clues: ['Imediatamente lateral ao meato uretral; epitélio transicional aponta origem urinária.'],
    mimics: ['Divertículo uretral: comunica com a uretra, expele urina à compressão.', 'Cisto de Gartner: mais lateral e alto.'],
    sources: ['https://librepathology.org/wiki/Paraurethral_cyst', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10183249/'],
  },
  {
    id: 'cisto-canal-de-nuck',
    name: 'Cisto do canal de Nuck',
    aka: ['hidrocele feminina', 'cisto do processo vaginal persistente', 'canal of Nuck cyst'],
    sites: ['vulva', 'pele'],
    linings: ['mesotelial'],
    lining: 'Mesotélio: camada única de células achatadas a cúbicas, calretinina e WT1 positivos; não é epitélio colunar.',
    wall: 'Parede fibrosa com vasos e fibras musculares lisas do ligamento redondo; focos de endometriose possíveis.',
    contents: 'Líquido seroso claro.',
    where: 'Região inguinal e porção superior do lábio maior, ao longo do ligamento redondo; aumenta com Valsalva.',
    clues: ['Equivalente feminino da hidrocele; revestimento mesotelial.'],
    mimics: ['Hérnia inguinal: conteúdo intestinal ou omento.', 'Cisto de Bartholin: vestibular, transicional.', 'Endometriose do canal de Nuck: glândulas e estroma endometriais.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC11755061/'],
  },
  {
    id: 'cisto-mucoso-vestibulo-vulvar',
    name: 'Cisto mucoso do vestíbulo vulvar',
    aka: ['cisto das glândulas vestibulares menores', 'mucous cyst of the vestibule'],
    sites: ['vulva'],
    linings: ['colunar-mucinoso'],
    features: ['muco'],
    lining: 'Camada única de colunar alto produtor de mucina, núcleos basais, sem cílios; mucicarmim e PAS positivos.',
    wall: 'Estroma fibroso delgado; sem ácinos de Bartholin.',
    contents: 'Muco claro.',
    where: 'Vestíbulo e face medial dos pequenos lábios; unilocular, menor que 2 cm.',
    clues: ['Glândula mucosa derivada do seio urogenital.'],
    mimics: ['Cisto de Bartholin: posterior, transicional, ácinos residuais.', 'Cisto mülleriano vaginal: mais alto na vagina.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC12509424/'],
  },
  {
    id: 'cisto-utriculo-prostatico',
    name: 'Cisto do utrículo prostático',
    aka: ['dilatação cística do utrículo', 'prostatic utricle cyst'],
    sites: ['prostata'],
    linings: ['cuboidal-simples', 'colunar-nao-ciliado', 'urotelial'],
    features: ['espermatozoides', 'celulas-neuroendocrinas'],
    lining: 'Colunar estratificado ou cúbico igual ao do utrículo, PSA positivo; células neuroendócrinas possíveis; focos de urotélio ou escamoso quando dilatado.',
    wall: 'Estroma fibromuscular prostático.',
    contents: 'Líquido claro; pode conter espermatozoides, porque comunica com a uretra prostática.',
    where: 'Linha média a partir do verumontano, sem ultrapassar a base da próstata; criança ou adolescente com hipospádia, DDS ou agenesia renal.',
    clues: ['Comunica com a uretra prostática (opacifica à uretrografia).'],
    mimics: ['Cisto do ducto mülleriano: não comunica, ultrapassa a base, nunca tem espermatozoides.', 'Cisto do ducto ejaculatório: paramediano.', 'Cisto de vesícula seminal: lateral.'],
    sources: ['https://pubmed.ncbi.nlm.nih.gov/11743291/', 'https://www.urology-textbook.com/prostatic-cysts.html'],
  },
  {
    id: 'cisto-ducto-mulleriano-masculino',
    name: 'Cisto do ducto mülleriano (masculino)',
    aka: ['cisto do remanescente mülleriano', 'Müllerian duct cyst'],
    sites: ['prostata'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    lining: 'Cúbico a colunar, às vezes pseudoestratificado, muitas vezes atenuado ou desnudado; indistinguível do revestimento do utrículo, e parte da literatura propõe unificar os dois termos.',
    wall: 'Parede fibrosa fina, sem músculo liso bem formado.',
    contents: 'Líquido claro ou achocolatado; nunca espermatozoides.',
    where: 'Linha média, retrovesical, em lágrima com o ápice apontando ao verumontano, ultrapassando a base da próstata; homens de 20 a 40 anos.',
    clues: ['Mediano, acima da base prostática, sem espermatozoides.'],
    mimics: ['Cisto do utrículo: comunica com a uretra, não ultrapassa a base.', 'Cisto de vesícula seminal: lateral, espermatozoides e lipofuscina.'],
    sources: ['https://pubmed.ncbi.nlm.nih.gov/15948745/', 'https://ajronline.org/doi/10.2214/AJR.06.0759'],
  },
  {
    id: 'cisto-vesicula-seminal',
    name: 'Cisto da vesícula seminal',
    aka: ['síndrome de Zinner (com agenesia renal ipsilateral)', 'seminal vesicle cyst'],
    sites: ['prostata'],
    linings: ['colunar-nao-ciliado', 'cuboidal-simples'],
    features: ['espermatozoides', 'musculo-liso'],
    lining: 'Colunar pseudoestratificado com células secretoras cúbicas e colunares, citoplasma com grânulos de lipofuscina castanho-dourada; atipia degenerativa com núcleos bizarros é normal.',
    wall: 'Camada muscular lisa bem formada e espessa.',
    contents: 'Líquido espesso acastanhado, com espermatozoides.',
    where: 'Lateral à linha média, retrovesical, unilateral; agenesia renal ipsilateral na síndrome de Zinner.',
    clues: ['Lipofuscina mais atipia degenerativa sem mitoses.', 'Lateralidade.'],
    mimics: ['Cistos medianos (utrículo, mülleriano): sem lipofuscina.', 'Adenocarcinoma prostático invadindo a vesícula: mitoses, PSA e NKX3.1.'],
    sources: ['https://www.pathologyoutlines.com/topic/prostateseminalves.html'],
  },
  {
    id: 'cisto-ducto-ejaculatorio',
    name: 'Cisto do ducto ejaculatório',
    aka: ['cisto paramediano prostático', 'ejaculatory duct cyst'],
    sites: ['prostata'],
    linings: ['cuboidal-simples', 'colunar-nao-ciliado'],
    features: ['espermatozoides'],
    lining: 'Cúbico a colunar como o do ducto ejaculatório e da vesícula seminal, podendo ter lipofuscina; se é ciliado, não está confirmado.',
    wall: 'Estroma fibromuscular prostático delgado, sem a camada muscular espessa da vesícula.',
    contents: 'Líquido com espermatozoides; cálculos possíveis.',
    where: 'Paramediano, no trajeto do ducto, junto ao verumontano; hipospermia, azoospermia obstrutiva e hematospermia.',
    clues: ['Paramediano, com espermatozoides no aspirado.'],
    mimics: ['Cisto utricular: mediano, comunica com a uretra.', 'Cisto de vesícula seminal: lateral, maior, parede muscular espessa.', 'Cisto de retenção prostático: sem espermatozoides.'],
    sources: ['https://pubs.rsna.org/doi/abs/10.1148/rg.334125129'],
  },
  {
    id: 'cisto-retencao-prostatico',
    name: 'Cisto de retenção prostático',
    aka: ['cisto acinar de retenção', 'prostatic retention cyst'],
    sites: ['prostata'],
    linings: ['cuboidal-simples'],
    features: ['material-eosinofilico'],
    lining: 'Duas camadas prostáticas preservadas: secretoras colunares a cúbicas achatadas pela distensão sobre camada basal contínua (p63, CK34βE12).',
    wall: 'Estroma fibromuscular prostático.',
    contents: 'Líquido claro; corpora amylacea, às vezes calcificação; sem espermatozoides.',
    where: 'Intraprostático, lateral ou periférico; homens de 50 a 60 anos.',
    clues: ['Camada basal preservada e corpora amylacea.'],
    mimics: ['HPB cística: múltiplas glândulas dilatadas num nódulo, não cisto único.', 'Cisto do ducto ejaculatório: espermatozoides.', 'Cistadenoma prostático: massa multiloculada volumosa.'],
    sources: ['https://www.urology-textbook.com/prostatic-cysts.html'],
  },
  {
    id: 'cisto-epididimario',
    name: 'Cisto do epidídimo',
    aka: ['epididymal cyst'],
    sites: ['testiculo'],
    linings: ['cuboidal-simples', 'ciliado-mulleriano', 'achatado-inespecifico'],
    features: ['musculo-liso'],
    lining: 'Cúbico, colunar, ciliado ou achatado de tipo ductal; não é mesotélio.',
    wall: 'Tecido fibroso com músculo liso e fibras elásticas variáveis.',
    contents: 'Líquido claro sem espermatozoides.',
    where: 'Cabeça do epidídimo (o mais comum), corpo e cauda; transilumina; exposição intrauterina a DES.',
    clues: ['Ausência de espermatozoides na luz é o que o separa da espermatocele.'],
    mimics: ['Espermatocele: espermatozoides na luz.', 'Hidrocele: mesotélio, envolve o testículo.', 'Cisto da túnica albugínea: na superfície do testículo.'],
    sources: ['https://www.pathologyoutlines.com/topic/testiscysts.html'],
  },
  {
    id: 'espermatocele',
    name: 'Espermatocele',
    aka: ['cisto espermático', 'spermatocele'],
    sites: ['testiculo'],
    linings: ['ciliado-mulleriano', 'cuboidal-simples'],
    features: ['espermatozoides', 'cilios'],
    lining: 'Simples cúbico a colunar ciliado, às vezes achatado pela distensão, em camada única.',
    wall: 'Parede fibrosa com músculo liso; macrófagos com espermatozoides fagocitados.',
    contents: 'Líquido leitoso ou turvo com espermatozoides intactos e degenerados: patognomônico.',
    where: 'Cabeça do epidídimo e ductos eferentes, junto ao polo superior do testículo, separado dele.',
    clues: ['Espermatozoides na luz.'],
    mimics: ['Cisto do epidídimo: sem espermatozoides.', 'Hidrocele: mesotélio, circunda o testículo.', 'Granuloma espermático: sólido e inflamatório.'],
    sources: ['https://www.pathologyoutlines.com/topic/testisspermatocele.html'],
  },
  {
    id: 'cisto-tunica-albuginea',
    name: 'Cisto da túnica albugínea',
    aka: ['cyst of the tunica albuginea'],
    sites: ['testiculo'],
    linings: ['mesotelial', 'achatado-inespecifico', 'cuboidal-simples'],
    lining: 'Camada única de células achatadas a cúbicas, sem diferenciação escamosa; origem provável em restos mesoteliais aprisionados.',
    wall: 'Parede fibrosa densa da própria albugínea, com inclusões glandulares.',
    contents: 'Líquido seroso claro, escasso (em geral menor que 1 cm).',
    where: 'Face anterior e lateral da túnica albugínea, com conexão ampla a ela; homens de 40 a 60 anos; parênquima normal.',
    clues: ['Nódulo firme palpável na superfície do testículo, uni ou multilocular.'],
    mimics: ['Hidrocele localizada: entre os folhetos da vaginal.', 'Cisto epidermoide: intratesticular, queratina.', 'Mesotelioma papilar bem diferenciado: papilas complexas.'],
    sources: ['https://www.pathologyoutlines.com/topic/testiscysts.html'],
  },
  {
    id: 'cisto-epidermoide-testicular',
    name: 'Cisto epidermoide do testículo',
    aka: ['cisto epidérmico intratesticular', 'testicular epidermoid cyst'],
    sites: ['testiculo'],
    linings: ['escamoso-queratinizado'],
    features: ['queratina-lamelar'],
    lining: 'Escamoso estratificado queratinizado sem anexos cutâneos e sem outros folhetos germinativos.',
    wall: 'Cápsula fibrosa; parênquima adjacente sem neoplasia de células germinativas in situ.',
    contents: 'Queratina lamelar concêntrica.',
    where: 'Intratesticular, homens de 20 a 40 anos; aspecto em casca de cebola ou alvo na ultrassonografia; marcadores normais.',
    clues: ['Ausência de anexos e de GCNIS exclui teratoma.'],
    mimics: ['Teratoma pós-puberal: outros tecidos, anexos, GCNIS adjacente.', 'Cisto dermoide testicular: anexos cutâneos.', 'Cisto da albugínea: extraparenquimatoso, cúbico.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC4955498/'],
  },
  {
    id: 'displasia-cistica-rete-testis',
    name: 'Displasia cística da rete testis',
    aka: ['cystic dysplasia of the rete testis'],
    sites: ['testiculo'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    lining: 'Cúbico a achatado, camada única, revestindo espaços císticos irregulares e anastomosados, em favo.',
    wall: 'Septos fibrosos finos; túbulos seminíferos adjacentes comprimidos e atróficos.',
    contents: 'Líquido seroso claro; sem espermatozoides.',
    where: 'Mediastino testicular com extensão ao parênquima; lactentes e crianças, unilateral; agenesia ou displasia renal ipsilateral.',
    clues: ['Criança com massa testicular multicística no mediastino e anomalia renal ipsilateral.'],
    mimics: ['Ectasia tubular da rete testis: adulto, obstrução ou espermatocele.', 'Linfangioma: endotélio D2-40 positivo.'],
    sources: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9158335/'],
  },
  {
    id: 'hidrocele',
    name: 'Hidrocele',
    aka: ['hidrocele da túnica vaginal', 'hydrocele'],
    sites: ['testiculo'],
    linings: ['mesotelial'],
    features: ['inflamacao', 'calcificacao'],
    lining: 'Mesotélio: camada única de células achatadas a cúbicas, com hiperplasia reativa e atipia focal possíveis; calretinina, WT1 e EMA positivos.',
    wall: 'Conjuntivo subjacente; nos crônicos, fibrina, inflamação crônica, fibrose, aderências e calcificação.',
    contents: 'Líquido seroso claro (hematocele se sangue, piocele se pus).',
    where: 'Entre os folhetos visceral e parietal da túnica vaginal, em ferradura ao redor do testículo; hidrocele do cordão quando o processo vaginal persiste.',
    clues: ['Transilumina; circunda o testículo.', 'Revestimento mesotelial, não epitelial.'],
    mimics: ['Espermatocele: epitélio ciliado, espermatozoides.', 'Mesotelioma da vaginal: papilas complexas, atipia, invasão; o cuidado numa hidrocele recorrente.'],
    sources: ['https://www.pathologyoutlines.com/topic/testishydrocele.html'],
  },
  {
    id: 'cisto-da-rafe-mediana',
    name: 'Cisto da rafe mediana',
    aka: ['cisto parameatal', 'cisto genitoperineal da rafe', 'median raphe cyst'],
    sites: ['penis', 'pele'],
    linings: ['colunar-nao-ciliado', 'colunar-mucinoso', 'urotelial', 'escamoso-nao-queratinizado'],
    lining: 'Colunar pseudoestratificado de tipo uretral (CK7, CK13) na maioria, às vezes com mucina apical; variantes mucinosa, transicional, escamosa ou mista; cílios só em relatos isolados.',
    wall: 'Derme fibrosa fina, sem anexos cutâneos, sem músculo liso organizado, sem tecido linfoide.',
    contents: 'Líquido claro a mucoide.',
    where: 'Linha média ventral, da glande ao ânus; mais na face ventral do corpo do pênis e parameatal; homens jovens, solitário, cerca de 1 cm.',
    clues: ['Estritamente na linha média ventral; epitélio pseudoestratificado sem anexos.'],
    mimics: ['Cisto epidermoide: escamoso com granulosa e queratina.', 'Cisto dermoide: anexos cutâneos.', 'Hidrocistoma apócrino: decapitação e mioepitélio.'],
    sources: ['https://dermnetnz.org/topics/median-raphe-cyst-pathology', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6626626/'],
  },
  {
    id: 'cisto-uracal',
    name: 'Cisto do úraco',
    aka: ['cisto do ligamento umbilical mediano', 'urachal cyst'],
    sites: ['bexiga', 'mesenterio'],
    linings: ['urotelial', 'cuboidal-simples', 'colunar-mucinoso'],
    features: ['musculo-liso', 'inflamacao', 'metaplasia-escamosa'],
    lining: 'Urotélio em cerca de 70% e colunar ou cúbico em 30%, às vezes achatado; metaplasia escamosa, colônica ou intestinal em até um quarto.',
    wall: 'Conjuntivo fibroso com feixes de músculo liso; inflamação intensa se infectado.',
    contents: 'Líquido seroso ou mucoide; pus se infectado.',
    where: 'Linha média extraperitoneal entre a cúpula vesical e o umbigo (espaço de Retzius), mais no terço inferior; adulto jovem com dor infraumbilical; drena pelo umbigo se fistuliza.',
    clues: ['Mediano, entre umbigo e bexiga, fora do peritônio.'],
    mimics: ['Divertículo vesical da cúpula: comunica com a bexiga.', 'Neoplasia mucinosa cística do úraco: epitélio mucinoso com atipia, mucina extracelular.', 'Cisto do ducto onfalomesentérico: epitélio intestinal, junto ao umbigo.'],
    sources: ['https://dermnetnz.org/topics/urachal-cyst-pathology', 'https://www.pathologyoutlines.com/topic/bladderurachus.html'],
  },
  {
    id: 'cistite-cistica-glandular',
    name: 'Cistite cística e glandular',
    aka: ['ninhos de von Brunn císticos', 'cystitis cystica et glandularis'],
    sites: ['bexiga'],
    linings: ['urotelial', 'colunar-mucinoso'],
    features: ['celulas-caliciformes', 'inflamacao'],
    lining: 'Cística: urotélio atenuado revestindo ninhos de von Brunn dilatados. Glandular: metaplasia para cúbico ou colunar mucinoso, com variante intestinal de caliciformes.',
    wall: 'Lâmina própria com inflamação crônica; sem desmoplasia nem invasão muscular.',
    contents: 'Líquido eosinofílico claro (cística) ou mucina (glandular).',
    where: 'Trígono e colo vesical; também ureter e pelve renal; achado banal em grande parte das bexigas.',
    clues: ['Origem em ninhos de von Brunn, arquitetura lobular com limite inferior linear.'],
    mimics: ['Adenocarcinoma vesical: infiltrativo, atipia, desmoplasia.', 'Adenoma nefrogênico: túbulos em hobnail, PAX8 positivo.', 'Adenocarcinoma uracal: cúpula, massa.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK582125/', 'https://www.pathologyoutlines.com/topic/bladdercystitiscystica.html'],
  },
]
