/* ==========================================================================
   skin.ts — pele e subcutâneo, partes moles, articulações, bursas e osso.
   Revestimentos conferidos em 2026-09-12 contra as fontes citadas em cada
   verbete (DermNet, StatPearls, PMC, PathologyOutlines via busca).
   ========================================================================== */

import type { Cyst } from '../types'

export const skin: Cyst[] = [
  {
    id: 'cisto-epidermoide',
    frequency: 3,
    name: 'Cisto epidermoide (infundibular)',
    aka: ['cisto epidérmico', 'cisto de inclusão epidérmica', '"cisto sebáceo" (nome errado)', 'epidermoid cyst'],
    sites: ['pele', 'boca', 'orbita', 'testiculo', 'partes-moles'],
    linings: ['escamoso-queratinizado'],
    features: ['queratina-lamelar', 'colesterol'],
    lining: 'Escamoso estratificado com camada granulosa evidente, sem cristas, igual à epiderme (queratinização infundibular).',
    wall: 'Estroma fibroso fino, sem anexos. Quando rompe, reação de corpo estranho com células gigantes e neutrófilos ao redor da queratina.',
    contents: 'Ortoqueratina lamelar frouxa, em cesto, acelular.',
    where: 'Face, pescoço, tronco, couro cabeludo e escroto, em qualquer pele com folículo; poro central na clínica. Também no assoalho da boca (linha média, sem anexos, ao contrário do dermoide), na órbita e, por implantação após ferimento penetrante, na polpa digital, palma e planta (cisto de inclusão epidérmica pós-traumático).',
    clues: ['Camada granulosa presente e queratina lamelar: é o par que define o cisto.', 'Ruptura com granuloma de corpo estranho é o achado mais comum na peça.', 'No dedo, pergunte por trauma penetrante: é o mesmo cisto, implantado.'],
    mimics: ['Cisto triquilemal: sem camada granulosa e com queratina compacta.', 'Cisto dermoide: anexos (pelos, sebáceas) na parede.', 'Esteatocistoma: cutícula eosinofílica crenulada e glândula sebácea na parede.'],
    sources: ['https://dermnetnz.org/topics/epidermoid-cyst-pathology', 'https://www.ncbi.nlm.nih.gov/books/NBK499974/'],
  },
  {
    id: 'cisto-triquilemal',
    frequency: 3,
    name: 'Cisto triquilemal (pilar)',
    aka: ['cisto pilar', 'cisto do istmo-catágeno', 'trichilemmal cyst'],
    sites: ['pele'],
    linings: ['triquilemal'],
    features: ['queratina-compacta', 'palicada-basal', 'calcificacao', 'colesterol'],
    lining: 'Escamoso estratificado sem camada granulosa; as células mais internas ficam grandes, pálidas e tumefeitas e passam abruptamente a queratina compacta (queratinização triquilemal).',
    wall: 'Paliçada periférica de células basaloides; parede fibrosa; calcificação frequente; sem glândulas sebáceas.',
    contents: 'Queratina compacta, homogênea e eosinofílica, não lamelar, com fendas de colesterol e cálcio.',
    where: 'Couro cabeludo em cerca de 90% dos casos, mulheres adultas, muitas vezes múltiplos e familiares (autossômico dominante); o nódulo "descola" inteiro na cirurgia.',
    clues: ['Ausência de granulosa e queratinização abrupta.', 'Calcificação na queratina.'],
    mimics: ['Cisto epidermoide: tem granulosa e queratina lamelar.', 'Tumor triquilemal proliferante: proliferação lobular sólida para dentro da luz.'],
    sources: ['https://dermnetnz.org/topics/trichilemmal-cyst-pathology', 'https://pubmed.ncbi.nlm.nih.gov/23641374/'],
  },
  {
    id: 'tumor-triquilemal-proliferante',
    frequency: 1,
    name: 'Tumor triquilemal proliferante',
    aka: ['cisto pilar proliferante', 'tumor pilar', 'proliferating trichilemmal tumour'],
    sites: ['pele'],
    linings: ['triquilemal'],
    features: ['queratina-compacta', 'palicada-basal', 'calcificacao'],
    lining: 'Epitélio escamoso com queratinização triquilemal (sem granulosa) que prolifera em lóbulos sólidos para dentro da luz, com células claras glicogenadas.',
    wall: 'Lóbulos escamosos compactos com paliçada periférica, atipia leve possível, calcificação e corpos hialinos. Necrose, atipia acentuada e infiltração sugerem transformação maligna.',
    contents: 'Queratina triquilemal compacta em cavidades residuais.',
    where: 'Couro cabeludo (mais de 90%) de mulheres idosas; lesão lobulada de 1 a 10 cm, pode ulcerar; muitas vezes surge de um cisto pilar prévio.',
    clues: ['Queratinização triquilemal preservada dentro de uma proliferação sólida.', 'Idosa, couro cabeludo, lesão exofítica maior que 2 cm.'],
    mimics: ['Cisto triquilemal simples: sem proliferação lobular.', 'Carcinoma espinocelular: atipia acentuada, necrose, invasão infiltrativa e nenhuma queratinização triquilemal.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC10589485/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4318032/'],
  },
  {
    id: 'esteatocistoma',
    name: 'Esteatocistoma (simples ou múltiplo)',
    aka: ['cisto sebáceo verdadeiro', 'steatocystoma multiplex'],
    sites: ['pele'],
    linings: ['triquilemal'],
    features: ['anexos-cutaneos', 'sebo-pelos'],
    lining: 'Escamoso estratificado sem camada granulosa, coberto por uma cutícula córnea eosinofílica espessa e ondulada (crenulada) que se projeta para a luz.',
    wall: 'Lóbulos sebáceos achatados dentro ou junto da parede, o achado que define a lesão; às vezes folículos velos rudimentares.',
    contents: 'Sebo oleoso, dissolvido no processamento (o cisto chega colapsado); alguns pelos velos.',
    where: 'Tórax anterior, axilas, raiz dos membros, escroto e virilha; múltiplos na forma familiar (mutação de KRT17, ligada à paquioníquia congênita).',
    clues: ['Cutícula eosinofílica crenulada sem granulosa mais glândula sebácea na parede.', 'Jovem com múltiplos nódulos no tronco.'],
    mimics: ['Cisto viloso eruptivo: tem camada granulosa e muitos pelos velos; as duas lesões podem coexistir.', 'Cisto dermoide: anexos completos, nas linhas de fusão.', 'Cisto epidermoide: granulosa e queratina lamelar.'],
    sources: ['https://www.pathologyoutlines.com/topic/skintumornonmelanocyticsteatocystoma.html', 'https://www.ncbi.nlm.nih.gov/books/NBK613288/'],
  },
  {
    id: 'cisto-viloso-eruptivo',
    frequency: 1,
    name: 'Cisto viloso eruptivo',
    aka: ['cisto eruptivo de pelos velos', 'eruptive vellus hair cyst'],
    sites: ['pele'],
    linings: ['escamoso-queratinizado'],
    features: ['queratina-lamelar', 'sebo-pelos'],
    lining: 'Escamoso estratificado fino com camada granulosa (nasce no infundíbulo ou istmo do folículo velo).',
    wall: 'Parede fina; pode ter um folículo velo rudimentar aderido; glândulas sebáceas em geral ausentes.',
    contents: 'Queratina lamelar com número variável de hastes de pelo velo cortadas transversalmente, o achado que define a lesão.',
    where: 'Tórax anterior, abdome e membros; múltiplas pápulas de 1 a 4 mm em crianças e adultos jovens, na derme média.',
    clues: ['Pelos velos dentro da luz.', 'Múltiplas pápulas no tórax de um jovem.'],
    mimics: ['Esteatocistoma múltiplo: sem granulosa, cutícula crenulada, sebáceas na parede.', 'Cisto epidermoide pequeno: sem pelos velos.'],
    sources: ['https://dermnetnz.org/topics/eruptive-vellus-hair-cysts', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5396452/'],
  },
  {
    id: 'milio',
    frequency: 3,
    name: 'Mílio',
    aka: ['milium', 'milia'],
    sites: ['pele', 'orbita'],
    linings: ['escamoso-queratinizado'],
    features: ['queratina-lamelar'],
    lining: 'Escamoso estratificado com camada granulosa: um cisto epidermoide em miniatura, nascido do infundíbulo do folículo velo.',
    wall: 'Poucas camadas; pode manter conexão com o folículo velo ou com um ducto sudoríparo (mílio secundário).',
    contents: 'Pequena quantidade de queratina lamelar compacta.',
    where: 'Pálpebras, bochechas e nariz, na derme superficial; primário ou secundário a bolha, queimadura, trauma ou dermabrasão.',
    clues: ['Pápula branca de 1 a 2 mm; cisto minúsculo na derme papilar com granulosa.', 'Contexto de bolha ou trauma prévio no mílio secundário.'],
    mimics: ['Cisto epidermoide: mesma histologia, maior e mais profundo.', 'Hidrocistoma: revestimento glandular, não escamoso.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK560481/', 'https://www.ncbi.nlm.nih.gov/books/NBK603737/'],
  },
  {
    id: 'cisto-dermoide-cutaneo',
    name: 'Cisto dermoide (subcutâneo e periorbitário)',
    aka: ['cisto dermoide da cauda da sobrancelha', 'dermoid cyst'],
    sites: ['pele', 'orbita', 'nariz', 'boca', 'pescoco'],
    linings: ['escamoso-queratinizado'],
    features: ['anexos-cutaneos', 'queratina-lamelar', 'sebo-pelos'],
    lining: 'Escamoso estratificado queratinizado com camada granulosa.',
    wall: 'Anexos maduros na parede: unidades pilossebáceas com pelos, glândulas sebáceas, glândulas écrinas e às vezes apócrinas e músculo eretor.',
    contents: 'Queratina lamelar, sebo e hastes de pelo livres; reação de corpo estranho se rompido.',
    where: 'Linhas de fusão embrionária: terço lateral da sobrancelha e órbita superolateral (o mais comum), glabela e dorso nasal, occipital, sacrococcígea, assoalho da boca; presente ao nascimento ou na infância. Pode erodir o osso subjacente.',
    clues: ['Anexos na parede com pelos na luz.', 'Criança, sobrancelha lateral, sutura frontozigomática.'],
    mimics: ['Cisto epidermoide: sem anexos na parede.', 'Teratoma: tecidos das três camadas germinativas.', 'Dermoide nasal com trato intracraniano: exige imagem antes da excisão.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK560573/', 'https://pubmed.ncbi.nlm.nih.gov/25191150/'],
  },
  {
    id: 'hidrocistoma-apocrino',
    name: 'Hidrocistoma apócrino',
    aka: ['cistadenoma apócrino', 'cisto de Moll', 'apocrine hidrocystoma'],
    sites: ['pele', 'orbita'],
    linings: ['apocrino'],
    lining: 'Uma a duas camadas de células cuboides a colunares altas com secreção por decapitação (protrusões apicais), muitas vezes formando projeções papilares para a luz.',
    wall: 'Camada externa de células mioepiteliais fusiformes paralelas à parede; estroma fibroso; sem cartilagem nem anexos.',
    contents: 'Líquido seroso claro a acastanhado ou azulado; pode conter lipofuscina.',
    where: 'Pálpebra (canto interno e margem, glândulas de Moll), face, orelha e axila; adulto de meia-idade; nódulo translúcido azulado, solitário, que não varia com o calor.',
    clues: ['Decapitação apical mais camada mioepitelial.', 'Lesão única na pálpebra.'],
    mimics: ['Hidrocistoma écrino: sem decapitação, sem papilas, epitélio cuboide atenuado, mioepitélio pouco evidente.', 'Hidradenoma papilífero: região anogenital, arquitetura papilar complexa.', 'Cisto ciliado cutâneo: cílios verdadeiros.'],
    sources: ['https://dermnetnz.org/topics/apocrine-hidrocystoma-pathology', 'https://www.ncbi.nlm.nih.gov/books/NBK448109/'],
  },
  {
    id: 'hidrocistoma-ecrino',
    name: 'Hidrocistoma écrino',
    aka: ['cisto de retenção sudoral', 'hidrocistoma de Robinson', 'eccrine hidrocystoma'],
    sites: ['pele', 'orbita'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    lining: 'Duas camadas de células cuboides, com frequência atenuadas pela pressão, sem secreção por decapitação.',
    wall: 'Parede fibrosa fina; componente mioepitelial pouco proeminente ou ausente; sem papilas.',
    contents: 'Líquido seroso claro.',
    where: 'Face, sobretudo periorbitária e malar, de mulheres adultas; com frequência múltiplos; pioram no calor e regridem no inverno.',
    clues: ['Múltiplas pápulas translúcidas e sazonais na face.', 'Epitélio cuboide bilaminado atenuado, sem decapitação.'],
    mimics: ['Hidrocistoma apócrino: decapitação, papilas, mioepitélio, em geral solitário.', 'Mílio: revestimento escamoso com queratina.'],
    sources: ['https://acta-apa.org/journals/acta-dermatovenerol-apa/papers/10.15570/actaapa.2021.13/actaapa.2021.13.pdf'],
  },
  {
    id: 'cisto-ciliado-cutaneo',
    frequency: 1,
    name: 'Cisto ciliado cutâneo',
    aka: ['cisto mülleriano cutâneo', 'cutaneous ciliated cyst'],
    sites: ['pele'],
    linings: ['ciliado-mulleriano'],
    features: ['cilios', 'metaplasia-escamosa'],
    lining: 'Cuboide a colunar ciliado, simples a pseudoestratificado, igual ao da tuba uterina; metaplasia escamosa focal ocasional. ER, PR, PAX8 e WT1 positivos.',
    wall: 'Parede fibrosa, muitas vezes com projeções papilares; sem músculo liso organizado, sem cartilagem, sem anexos.',
    contents: 'Líquido seroso claro a âmbar.',
    where: 'Membros inferiores (coxa, perna, poplítea, pé) de meninas e mulheres de 15 a 30 anos, no subcutâneo ou derme profunda; raro em outros locais e no homem.',
    clues: ['Mulher jovem, perna, epitélio ciliado tipo tubário.', 'PAX8 e ER positivos confirmam a origem mülleriana.'],
    mimics: ['Cisto broncogênico cutâneo: músculo liso, glândulas seromucosas e cartilagem; TTF-1 positivo, PAX8 negativo; linha média torácica alta.', 'Hidrocistoma écrino: cuboide sem cílios.', 'Endometriose cutânea: glândulas com estroma endometrial e hemossiderina.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC5192324/', 'https://www.sciencedirect.com/science/article/pii/S2667396723000083'],
  },
  {
    id: 'cisto-broncogenico-cutaneo',
    frequency: 1,
    name: 'Cisto broncogênico cutâneo',
    aka: ['cisto broncogênico subcutâneo', 'cutaneous bronchogenic cyst'],
    sites: ['pele', 'pescoco'],
    linings: ['respiratorio-ciliado'],
    features: ['cilios', 'celulas-caliciformes', 'musculo-liso', 'glandulas-seromucosas', 'cartilagem', 'metaplasia-escamosa'],
    lining: 'Colunar pseudoestratificado ciliado, tipo respiratório, com células caliciformes; metaplasia escamosa focal possível. TTF-1 positivo.',
    wall: 'Músculo liso e glândulas seromucosas (a regra); cartilagem hialina em parte dos casos; folículos linfoides ocasionais.',
    contents: 'Material mucoide claro; pode drenar por um seio cutâneo.',
    where: 'Incisura supraesternal e manúbrio (clássico), pescoço, pré-esternal, escápula e ombro; ao nascimento ou na infância, mais em meninos.',
    clues: ['Lactente ou criança com nódulo ou fístula na fúrcula esternal.', 'Epitélio respiratório mais músculo liso, com ou sem cartilagem.'],
    mimics: ['Cisto ciliado cutâneo: sem músculo liso nem cartilagem, PAX8 e ER positivos, perna de mulher jovem.', 'Cisto tímico cervical: corpúsculos de Hassall.', 'Cisto branquial: tecido linfoide com centros germinativos.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC3162276/', 'https://bmcmedimaging.biomedcentral.com/articles/10.1186/s12880-022-00853-y'],
  },
  {
    id: 'cisto-pilonidal',
    frequency: 3,
    name: 'Seio pilonidal (pseudocisto pilonidal)',
    aka: ['cisto pilonidal', 'doença pilonidal', 'pilonidal sinus'],
    sites: ['pele', 'retrorretal'],
    linings: ['sem-revestimento', 'escamoso-queratinizado'],
    features: ['inflamacao', 'sebo-pelos', 'colesterol'],
    pseudocyst: true,
    lining: 'Sem revestimento epitelial verdadeiro na quase totalidade: cavidade forrada por tecido de granulação. Só o trajeto próximo ao óstio cutâneo pode ter epitélio escamoso.',
    wall: 'Tecido de granulação com neutrófilos, linfócitos e plasmócitos, fibrose, abscessos e células gigantes de corpo estranho abraçando hastes de pelo.',
    contents: 'Tufos de hastes de pelo livres, queratina e pus.',
    where: 'Prega interglútea sacrococcígea de homens jovens e hirsutos (15 a 30 anos); variantes ocupacionais nos espaços interdigitais do barbeiro, umbigo, axila e mama.',
    clues: ['Pelos livres com reação de corpo estranho e nenhum epitélio ou anexo na parede.', 'Óstios na linha média da prega interglútea.'],
    mimics: ['Cisto epidermoide roto: sobra epitélio com granulosa em algum ponto.', 'Hidradenite supurativa: localização apócrina, trajetos epitelizados.', 'Fístula perianal: relação com o canal anal.'],
    sources: ['https://dermnetnz.org/topics/pilonidal-sinus-pathology', 'https://www.ncbi.nlm.nih.gov/books/NBK557770/'],
  },
  {
    id: 'pseudocisto-mixoide-digital',
    frequency: 3,
    name: 'Pseudocisto mixoide digital',
    aka: ['cisto mucoso digital', 'cisto mixoide', 'gânglio periungueal', 'digital mucous cyst'],
    sites: ['pele', 'articulacao'],
    linings: ['sem-revestimento'],
    features: ['muco'],
    pseudocyst: true,
    lining: 'Sem revestimento epitelial. Na variante ganglionar pode haver células sinoviais achatadas junto ao pedículo articular.',
    wall: 'Tecido conjuntivo denso colagenizado com fibroblastos esparsos e epiderme adelgaçada por cima; o tipo mixomatoso mostra mucina dérmica em estroma frouxo.',
    contents: 'Mucina viscosa e gelatinosa (ácido hialurônico), azul de Alcian e ferro coloidal positivos.',
    where: 'Dorso do dedo sobre a interfalângica distal ou na prega ungueal proximal; mulheres acima de 50 anos com osteoartrose da IFD e osteófitos; sulco longitudinal na unha.',
    clues: ['Mucina e colágeno denso sem nenhum epitélio.', 'Idosa, IFD, osteófitos na radiografia.'],
    mimics: ['Gânglio do punho: mesma natureza, localização periarticular profunda.', 'Mixoma superficial: nódulo mixoide com vasos delicados, sem relação articular.', 'Cisto epidermoide de inclusão: epitélio escamoso com queratina.'],
    sources: ['https://dermnetnz.org/topics/digital-myxoid-pseudocyst-pathology', 'https://www.ncbi.nlm.nih.gov/books/NBK559092/'],
  },
  {
    id: 'cisto-ganglionar',
    frequency: 3,
    name: 'Cisto ganglionar (gânglio)',
    aka: ['ganglion cyst'],
    sites: ['articulacao', 'pele', 'partes-moles'],
    linings: ['sem-revestimento'],
    features: ['muco'],
    pseudocyst: true,
    lining: 'Sem revestimento celular diferenciado: nem sinóvia nem epitélio, só parede fibrosa ou mixoide.',
    wall: 'Tecido fibroso denso com fibroblastos frouxos e estroma mixoide, inflamação crônica discreta; pode haver pedículo até a cápsula articular ou bainha tendínea.',
    contents: 'Líquido mucinoso claro e viscoso, rico em ácido hialurônico; multiloculado ao corte.',
    where: 'Dorso do punho (escafossemilunar, o mais comum), face volar do punho, bainhas tendíneas dos dedos, pé, tornozelo e joelho; adultos jovens, mais mulheres.',
    clues: ['Nódulo dorsal do punho que transilumina.', 'Parede fibrosa com conteúdo mucoide e nenhum revestimento.'],
    mimics: ['Cisto sinovial verdadeiro: revestimento sinovial e comunicação com a articulação.', 'Tumor de células gigantes da bainha tendínea: sólido, histiócitos, hemossiderina, células gigantes.', 'Mixoma intramuscular: massa sólida mixoide, sem cavidade.'],
    sources: ['https://www.pathologyoutlines.com/topic/jointsganglion.html'],
  },
  {
    id: 'cisto-de-baker',
    frequency: 3,
    name: 'Cisto de Baker (poplíteo)',
    aka: ['bursa gastrocnêmio-semimembranácea distendida', 'popliteal cyst'],
    sites: ['articulacao'],
    linings: ['sinovial'],
    features: ['hemossiderina', 'inflamacao'],
    lining: 'Sinoviócitos achatados a hiperplásicos, com graus variáveis de substituição fibrosa ou desnudamento.',
    wall: 'Parede sinovial fibrosada com inflamação crônica inespecífica, hiperplasia vilosa, fibrina, corpos de arroz, hemossiderina e cristais nas artropatias.',
    contents: 'Líquido sinovial claro a turvo, às vezes hemorrágico.',
    where: 'Fossa poplítea medial, entre o semimembranáceo e a cabeça medial do gastrocnêmio; adultos com osteoartrose ou artrite reumatoide; comunica com o joelho por mecanismo valvular.',
    clues: ['Sinoviócitos revestindo a cavidade.', 'Massa poplítea medial com derrame ou lesão meniscal.'],
    mimics: ['Gânglio poplíteo: sem sinóvia, conteúdo mucoide.', 'Aneurisma poplíteo: parede vascular.', 'Sarcoma sinovial: tumor sólido, atipia, fusão SS18.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK430774/'],
  },
  {
    id: 'cisto-sinovial',
    name: 'Cisto sinovial (incluindo o justafacetário)',
    aka: ['cisto justafacetário', 'cisto facetário lombar', 'synovial cyst'],
    sites: ['articulacao', 'coluna'],
    linings: ['sinovial'],
    features: ['hemossiderina', 'calcificacao'],
    lining: 'Camada de sinoviócitos cuboides a achatados em continuidade com a articulação de origem.',
    wall: 'Tecido fibroso ou fibrocartilaginoso com hiperplasia sinovial, inflamação crônica, calcificação, hemossiderina e às vezes hemorragia recente.',
    contents: 'Líquido sinovial claro ou espesso, às vezes gelatinoso ou hemorrágico.',
    where: 'Junto a articulações sinoviais: facetas lombares L4-L5 (o mais comum), joelho, ombro e quadril; adultos acima de 50 anos com degeneração articular ou espondilolistese.',
    clues: ['Sinoviócitos no revestimento: é a definição.', 'Comunicação com a faceta degenerada na RM.'],
    mimics: ['Gânglio justafacetário: sem sinóvia e sem comunicação articular; mesmo tratamento.', 'Cisto do ligamento amarelo: degeneração mixoide do ligamento, sem revestimento.', 'Cisto de Tarlov: raiz sacral, revestido por perineuro e aracnoide.'],
    sources: ['https://pubmed.ncbi.nlm.nih.gov/29314220/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10966938/'],
  },
  {
    id: 'cisto-bursal',
    frequency: 3,
    name: 'Cisto bursal (bursite crônica)',
    aka: ['higroma', 'bursite olecraniana', 'bursite pré-patelar', 'bursal cyst'],
    sites: ['articulacao'],
    linings: ['sinovial'],
    features: ['inflamacao'],
    lining: 'Sinoviócitos com hiperplasia, muitas vezes desnudados e substituídos por fibrina nas bursites crônicas.',
    wall: 'Parede fibrosa espessada com hiperplasia sinovial vilosa, aderências e inflamação crônica; fibrina, nódulos reumatoides, tofos de urato ou neutrófilos na séptica.',
    contents: 'Líquido seroso, serossanguinolento ou purulento, rico em fibrina; corpos de arroz.',
    where: 'Bolsas superficiais: olécrano, pré-patelar, retrocalcânea, trocantérica, isquiática e subacromial; trauma repetitivo, gota ou artrite reumatoide.',
    clues: ['Exatamente sobre uma bolsa anatômica conhecida.', 'Sinóvia hiperplásica com fibrina; cristais de urato birrefringentes na gota.'],
    mimics: ['Gânglio: sem sinóvia, conteúdo mucoide.', 'Nódulo reumatoide: necrose fibrinoide em paliçada, sólido.', 'Abscesso: sem revestimento, neutrófilos e necrose.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK470291/'],
  },
  {
    id: 'cisto-meniscal',
    name: 'Cisto meniscal (parameniscal)',
    aka: ['menisco cístico', 'meniscal cyst'],
    sites: ['articulacao'],
    linings: ['sem-revestimento'],
    features: ['muco'],
    pseudocyst: true,
    lining: 'Sem revestimento epitelial ou sinovial: cavidade delimitada por fibrocartilagem e tecido fibroso.',
    wall: 'Fibrocartilagem com degeneração mixoide, tecido fibroso e células gigantes de corpo estranho ocasionais, sem sinoviócitos.',
    contents: 'Material mucoide gelatinoso extravasado do menisco.',
    where: 'Periferia do menisco, muito mais o lateral (corno médio e anterior); adultos jovens e de meia-idade com rotura horizontal do menisco.',
    clues: ['Tumefação na interlinha lateral que some com a flexão.', 'Rotura horizontal contígua ao cisto na RM.'],
    mimics: ['Gânglio periarticular: sem continuidade com o menisco.', 'Cisto sinovial: revestimento sinovial.', 'Cisto de Baker: poplíteo e medial, revestido por sinóvia.'],
    sources: ['https://www.pathologyoutlines.com/topic/jointscysticmeniscus.html', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4334430/'],
  },
  {
    id: 'cisto-epidermoide-intraosseo',
    frequency: 1,
    name: 'Cisto epidermoide intraósseo',
    aka: ['intraosseous epidermoid cyst'],
    sites: ['osso'],
    linings: ['escamoso-queratinizado'],
    features: ['queratina-lamelar', 'colesterol'],
    lining: 'Escamoso estratificado queratinizante com camada granulosa preservada.',
    wall: 'Cápsula fibrosa fina junto ao osso, com esclerose reativa; sem anexos; células gigantes de corpo estranho se rompido.',
    contents: 'Massas de queratina lamelar; pode haver colesterol.',
    where: 'Falange distal dos dedos (o mais comum, em geral após trauma) e calota craniana (díploe, em geral congênito); adultos de 20 a 50 anos.',
    clues: ['Lesão lítica bem delimitada com halo esclerótico na falange distal e antecedente de trauma.', 'Epitélio escamoso com granulosa dentro do osso.'],
    mimics: ['Encondroma: cartilagem hialina lobular, o principal diferencial radiológico na falange.', 'Cisto ósseo simples: sem epitélio, material fibrinoide.', 'Tumor glômico: lesão dolorosa subungueal, células glômicas.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC10387594/', 'https://journals.lww.com/prsgo/fulltext/2023/04000/distal_phalanx_intraosseous_epidermoid_cyst.11.aspx'],
  },
  {
    id: 'cisto-osseo-simples',
    name: 'Cisto ósseo simples (unicameral)',
    aka: ['cisto ósseo solitário', 'cisto ósseo juvenil', 'simple bone cyst'],
    sites: ['osso', 'maxilares'],
    linings: ['sem-revestimento'],
    features: ['colesterol', 'hemossiderina', 'material-eosinofilico'],
    pseudocyst: true,
    lining: 'Sem revestimento epitelial: membrana fibrosa ou fibrovascular fina, muitas vezes incompleta ou ausente na amostra.',
    wall: 'Estroma fibrovascular delgado com células gigantes tipo osteoclasto, macrófagos espumosos, hemossiderina, fendas de colesterol, granulação, osso reativo e um material eosinofílico amorfo tipo fibrina que mineraliza em matriz cementiforme, achado bastante característico.',
    contents: 'Líquido seroso ou serossanguinolento claro.',
    where: 'Metáfise do úmero e fêmur proximais em menores de 20 anos; calcâneo e ilíaco em adultos; central, medular. Nos maxilares, corpo da mandíbula de adolescentes.',
    clues: ['Criança com fratura patológica do úmero proximal e sinal do fragmento caído.', 'Material fibrinoide cementiforme na parede fina, sem septos celulares.'],
    mimics: ['Cisto ósseo aneurismático: espaços hemorrágicos com septos celulares ricos em células gigantes e osteoide, USP6 rearranjado.', 'Fibroma não ossificante: padrão estoriforme, sem cavidade.', 'Displasia fibrosa: trabéculas em letras chinesas.'],
    sources: ['https://www.pathologyoutlines.com/topic/bonesolitarybonecyst.html', 'https://www.ncbi.nlm.nih.gov/books/NBK470587/'],
  },
  {
    id: 'cisto-osseo-aneurismatico',
    name: 'Cisto ósseo aneurismático',
    aka: ['COA', 'aneurysmal bone cyst'],
    sites: ['osso', 'maxilares'],
    linings: ['sem-revestimento'],
    features: ['sangue', 'hemossiderina', 'calcificacao'],
    pseudocyst: true,
    lining: 'Sem revestimento endotelial nem epitelial: espaços cheios de sangue delimitados só por septos fibrosos.',
    wall: 'Septos com fibroblastos e miofibroblastos sem atipia, células gigantes tipo osteoclasto, hemossiderina e osteoide ou osso imaturo com rebordo osteoblástico ("osso azul"); rearranjo de USP6 na forma primária.',
    contents: 'Sangue não coagulado; níveis líquido-líquido na RM.',
    where: 'Metáfise de ossos longos, elementos posteriores da coluna e pelve nas duas primeiras décadas; excêntrico, expansivo, com casca periosteal fina.',
    clues: ['Adolescente com lesão lítica expansiva e níveis líquido-líquido.', 'Espaços hemorrágicos sem endotélio com septos ricos em células gigantes; FISH para USP6.'],
    mimics: ['Cisto ósseo simples: parede fina, sem septos celulares, material cementiforme, sem USP6.', 'Osteossarcoma telangiectásico: atipia acentuada e mitoses atípicas nos septos, o diagnóstico que não pode escapar.', 'Tumor de células gigantes com alteração cística secundária.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK546654/', 'https://www.jpatholtm.org/journal/view.php?number=17061'],
  },
  {
    id: 'cisto-osseo-subcondral',
    frequency: 3,
    name: 'Cisto ósseo subcondral (geodo)',
    aka: ['geodo degenerativo', 'cisto subarticular', 'subchondral cyst'],
    sites: ['osso'],
    linings: ['sem-revestimento'],
    features: ['hemossiderina', 'muco'],
    pseudocyst: true,
    lining: 'Sem revestimento epitelial ou sinovial: cavidade delimitada por tecido fibroso ou fibrocartilagem.',
    wall: 'Tecido fibroso com osteoblastos, adipócitos, fragmentos de osso necrótico, hemossiderina, macrófagos espumosos e osso esclerótico reativo ao redor.',
    contents: 'Líquido sinovial intruso, material mixoide ou detrito necrótico.',
    where: 'Osso subcondral logo abaixo de cartilagem articular danificada: quadril, joelho, ombro e mão de adultos com osteoartrose, artrite reumatoide, necrose avascular ou artropatia por cristais.',
    clues: ['Sempre subarticular, com perda de cartilagem, esclerose e osteófitos.', 'Comunica com a articulação por um defeito condral.'],
    mimics: ['Gânglio intraósseo: cartilagem preservada, sem artropatia, conteúdo mucoide bem delimitado.', 'Necrose avascular: infarto ósseo com linha serpiginosa de demarcação.', 'Tumor de células gigantes: proliferação celular sólida.'],
    sources: ['https://radsource.us/common-intraosseous-cysts/', 'https://ajronline.org/doi/full/10.2214/AJR.07.2098'],
  },
  {
    id: 'ganglio-intraosseo',
    frequency: 1,
    name: 'Gânglio intraósseo',
    aka: ['cisto ganglionar intraósseo', 'intraosseous ganglion'],
    sites: ['osso'],
    linings: ['sem-revestimento'],
    features: ['muco'],
    pseudocyst: true,
    lining: 'Sem revestimento epitelial nem sinovial.',
    wall: 'Tecido fibroso periférico com fibroblastos e colágeno, substância mixoide e macrófagos espumosos ocasionais; borda esclerótica no osso adjacente.',
    contents: 'Material gelatinoso e mucoide, igual ao do gânglio de partes moles.',
    where: 'Epífise subcondral: maléolo medial e pilão tibial, carpo (semilunar, escafoide), cabeça femoral e joelho; adultos de 30 a 60 anos com cartilagem articular preservada.',
    clues: ['Lesão lítica epifisária bem definida com halo esclerótico e articulação sem osteoartrose.', 'Conteúdo mucoide com parede fibrosa e nenhum revestimento.'],
    mimics: ['Geodo subcondral: há artropatia degenerativa e defeito da cartilagem.', 'Condroblastoma: epífise de jovem, células condroblásticas, calcificação em tela de galinheiro, H3F3B.', 'Abscesso de Brodie: neutrófilos, sequestro, clínica infecciosa.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC5878280/', 'https://pubmed.ncbi.nlm.nih.gov/7102899/'],
  },
  {
    id: 'pseudocisto-da-orelha',
    frequency: 1,
    name: 'Pseudocisto da orelha',
    aka: ['seroma auricular', 'condromalácia cística idiopática', 'pseudocyst of the auricle'],
    sites: ['orelha'],
    linings: ['sem-revestimento'],
    features: ['cartilagem'],
    pseudocyst: true,
    lining: 'Sem revestimento epitelial: cavidade dentro da própria cartilagem, delimitada só por cartilagem degenerada.',
    wall: 'Cartilagem adelgaçada com degeneração hialina eosinofílica na borda interna, fibrose intracartilaginosa e granulação; infiltrado linfocitário perivascular na derme; epiderme e derme normais.',
    contents: 'Líquido viscoso, estéril, cor de palha, rico em albumina.',
    where: 'Face anterior da orelha, fossa escafoide e fossa triangular; homens de 30 a 50 anos, unilateral, indolor.',
    clues: ['Cavidade dentro da cartilagem sem nenhum revestimento.', 'Aspirado amarelo-claro numa tumefação indolor da fossa escafoide.'],
    mimics: ['Otohematoma e pericondrite: trauma, sangue e inflamação aguda.', 'Condrodermatite nodular da hélice: lesão dolorosa na hélice com colágeno degenerado e úlcera.', 'Cisto epidermoide da orelha: revestimento escamoso com queratina.'],
    sources: ['https://dermnetnz.org/topics/auricle-pseudocyst-pathology', 'https://www.pathologyoutlines.com/topic/skintumornonmelanocyticauricularpseudocyst.html'],
  },
]
