/* ==========================================================================
   thorax.ts — mediastino e timo, esôfago, pulmão e pleura, coração e
   pericárdio, mama. O trio broncogênico / duplicação esofágica /
   neurentérico (este em cns.ts) é a pergunta mais frequente daqui.
   Revestimentos conferidos em 2026-09-12.
   ========================================================================== */

import type { Cyst } from '../types'

export const thorax: Cyst[] = [
  {
    id: 'cisto-broncogenico',
    name: 'Cisto broncogênico',
    aka: ['cisto de duplicação do intestino anterior de tipo respiratório', 'bronchogenic cyst'],
    sites: ['mediastino', 'pulmao', 'mesenterio', 'pescoco'],
    linings: ['respiratorio-ciliado'],
    features: ['cilios', 'celulas-caliciformes', 'cartilagem', 'glandulas-seromucosas', 'musculo-liso', 'metaplasia-escamosa'],
    lining: 'Respiratório pseudoestratificado colunar ciliado com caliciformes; cuboide ciliado ou com metaplasia escamosa quando infectado.',
    wall: 'Cartilagem hialina, glândulas seromucosas brônquicas, feixes desorganizados de músculo liso, fibras elásticas; sem duas camadas musculares organizadas. TTF-1 pode ser positivo.',
    contents: 'Muco espesso, leitoso ou gelatinoso; hemorrágico ou purulento se complicado.',
    where: 'Mediastino médio, subcarinal ou paratraqueal direito (o mais comum); intrapulmonar em lobos inferiores (15 a 20%); raro no retroperitônio justa-adrenal esquerdo e no pescoço. Densidade alta na TC apesar de cístico.',
    clues: ['Cartilagem na parede fecha o diagnóstico.', 'No pulmão, ao contrário da bolha, tem epitélio; costuma não comunicar com o brônquio.'],
    mimics: ['Cisto de duplicação esofágica: duas camadas musculares com plexo, sem cartilagem.', 'Cisto neurentérico: posterior, com anomalia vertebral.', 'Cisto tímico: corpúsculos de Hassall, anterior.', 'Cisto mülleriano retroperitoneal: também ciliado, mas PAX8 e ER positivos, sem cartilagem.'],
    sources: ['https://www.pathologyoutlines.com/topic/mediastinumbronchogenic.html', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10758913/'],
  },
  {
    id: 'cisto-duplicacao-esofagica',
    name: 'Cisto de duplicação esofágica',
    aka: ['duplicação esofágica', 'esophageal duplication cyst'],
    sites: ['esofago', 'mediastino'],
    linings: ['escamoso-nao-queratinizado', 'respiratorio-ciliado', 'colunar-mucinoso'],
    features: ['musculo-liso', 'cilios'],
    lining: 'Escamoso estratificado esofágico ou colunar ciliado respiratório; mucosa gástrica ectópica em 20 a 30% ou intestinal.',
    wall: 'Duas camadas de músculo liso (circular interna e longitudinal externa) com plexo mioentérico entre elas; sem cartilagem.',
    contents: 'Material mucoide ou seroso; hemorrágico quando a mucosa gástrica ulcera.',
    where: 'Mediastino posterior, aderido ou intramural à parede esofágica, terço distal e à direita.',
    clues: ['Contiguidade com o esôfago, revestimento digestivo ou respiratório e duas camadas de músculo liso.', 'Ausência de cartilagem.'],
    mimics: ['Cisto broncogênico: cartilagem, músculo desorganizado.', 'Cisto neurentérico: anomalia vertebral e conexão intraespinhal.', 'Cisto de retenção esofágico: simples, sem muscular própria.'],
    sources: ['https://www.pathologyoutlines.com/topic/esophaguscysts.html'],
  },
  {
    id: 'cisto-pericardico',
    name: 'Cisto pericárdico',
    aka: ['cisto celômico', 'cisto de água de fonte', 'pericardial cyst'],
    sites: ['coracao', 'mediastino'],
    linings: ['mesotelial'],
    lining: 'Camada única de mesotélio achatado a cuboide, sem cílios; calretinina e WT1 positivos.',
    wall: 'Conjuntivo frouxo fino com poucos vasos e escassa inflamação; sem músculo liso, sem cartilagem.',
    contents: 'Líquido seroso claro como água, estéril.',
    where: 'Ângulo cardiofrênico, mais à direita, no mediastino anterior inferior; contíguo ao pericárdio sem comunicar com a cavidade; achado incidental.',
    clues: ['Parede finíssima que descola com facilidade.', 'Ângulo cardiofrênico direito na radiografia.'],
    mimics: ['Cisto broncogênico: epitélio ciliado e cartilagem.', 'Linfangioma: endotélio CD31 e ERG positivos, calretinina negativa.', 'Cisto tímico: corpúsculos de Hassall.'],
    sources: ['https://librepathology.org/wiki/Pericardial_cyst', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10863696/'],
  },
  {
    id: 'cisto-timico-unilocular',
    name: 'Cisto tímico unilocular (congênito)',
    aka: ['cisto do ducto timofaríngeo', 'unilocular thymic cyst'],
    sites: ['mediastino', 'pescoco'],
    linings: ['escamoso-nao-queratinizado', 'cuboidal-simples', 'respiratorio-ciliado'],
    features: ['tecido-timico'],
    lining: 'Escamoso, cuboide ou colunar (às vezes ciliado), em camada única e regular.',
    wall: 'Parede fina com tecido tímico residual e corpúsculos de Hassall; sem fibrose significativa nem inflamação relevante.',
    contents: 'Líquido seroso claro ou levemente turvo.',
    where: 'Mediastino anterossuperior, no timo ou ao longo do ducto timofaríngeo (pode ser cervical); criança ou adulto jovem.',
    clues: ['Uniloculado, parede fina, Hassall na parede.'],
    mimics: ['Cisto tímico multilocular: multiloculado, com fibrose e inflamação intensas.', 'Cisto broncogênico: cartilagem.', 'Cisto pericárdico: só mesotélio, sem timo.'],
    sources: ['https://www.pathologyoutlines.com/topic/mediastinumthymiccyst.html', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9792833/'],
  },
  {
    id: 'cisto-timico-multilocular',
    name: 'Cisto tímico multilocular',
    aka: ['cisto tímico adquirido', 'multilocular thymic cyst'],
    sites: ['mediastino'],
    linings: ['escamoso-nao-queratinizado', 'cuboidal-simples', 'respiratorio-ciliado'],
    features: ['tecido-timico', 'inflamacao', 'colesterol', 'estroma-linfoide', 'calcificacao', 'hemossiderina'],
    lining: 'Escamoso na maioria dos lóculos, podendo ser cuboide, colunar ou ciliado; áreas desnudas e hiperplasia pseudoepiteliomatosa frequentes.',
    wall: 'Fibrose densa, inflamação aguda e crônica intensa, hiperplasia linfoide com centros germinativos, granulomas de colesterol, hemorragia, necrose e calcificação; tecido tímico com Hassall.',
    contents: 'Líquido turvo, hemorrágico ou material necrótico e colesterínico.',
    where: 'Mediastino anterior, dentro do timo; reativo, associado a Sjögren, HIV, artrite reumatoide e radioterapia.',
    clues: ['Multiloculado com parede espessa e fibrose (o unilocular é fino).', 'Amostrar toda a parede: até metade dos Hodgkin esclerose nodular e seminomas do mediastino têm alteração cística idêntica.'],
    mimics: ['Timoma cístico: ninhos de epitélio tímico neoplásico com timócitos TdT positivos.', 'Cisto tímico em linfoma de Hodgkin ou seminoma: células de Reed-Sternberg CD30 e CD15 positivas, ou células claras OCT4 e SALL4 positivas na parede.', 'Cisto tímico unilocular: fino, sem inflamação.'],
    sources: ['https://pubmed.ncbi.nlm.nih.gov/2006719/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5215007/'],
  },
  {
    id: 'timoma-cistico',
    name: 'Timoma cístico',
    aka: ['timoma com degeneração cística', 'cystic thymoma'],
    sites: ['mediastino'],
    linings: ['escamoso-nao-queratinizado', 'cuboidal-simples', 'achatado-inespecifico'],
    features: ['tecido-timico', 'hemossiderina'],
    lining: 'Lóculos revestidos por epitélio escamoso, cuboide ou colunar, ou desnudos; o revestimento é degenerativo e não é o achado diagnóstico.',
    wall: 'Timoma na parede: ninhos e lençóis de células epiteliais tímicas neoplásicas (CK19, p63, PAX8) com timócitos imaturos TdT, CD1a e CD99 positivos; septos fibrosos, infarto e hemorragia.',
    contents: 'Líquido seroso, turvo ou hemorrágico.',
    where: 'Mediastino anterior; associação com miastenia gravis.',
    clues: ['Componente sólido mural na imagem.', 'Timócitos TdT positivos junto ao epitélio neoplásico.'],
    mimics: ['Cisto tímico multilocular: sem proliferação epitelial neoplásica, exige amostragem ampla.', 'Linfoma linfoblástico T: TdT difuso sem rede epitelial.'],
    sources: ['https://www.pathologyoutlines.com/topic/mediastinumthymiccyst.html', 'https://pubmed.ncbi.nlm.nih.gov/23026930/'],
  },
  {
    id: 'meningocele-lateral-toracica',
    name: 'Meningocele lateral torácica',
    aka: ['meningocele intratorácica', 'lateral thoracic meningocele'],
    sites: ['mediastino', 'coluna'],
    linings: ['meningotelial'],
    lining: 'Sem epitélio: parede de meninges (aracnoide e dura), com células meningoteliais achatadas EMA positivas.',
    wall: 'Dura fibrosa densa e aracnoide displásicas; tecido neural ou radicular aprisionado; sem músculo, cartilagem ou glândulas.',
    contents: 'Líquido cefalorraquidiano.',
    where: 'Mediastino posterior, paravertebral, herniando pelo forame intervertebral alargado; neurofibromatose tipo 1 em cerca de dois terços; cifoescoliose.',
    clues: ['Segue o sinal do liquor em todas as sequências e continua com o espaço subaracnóideo.', 'Neurofibromatose 1.'],
    mimics: ['Cisto neurentérico: epitélio entérico, anomalia de fusão vertebral.', 'Schwannoma cístico: S100 e SOX10.', 'Cisto broncogênico posterior: epitélio ciliado.'],
    sources: ['https://www.sciencedirect.com/science/article/pii/S2214751922001384'],
  },
  {
    id: 'mafp-cpam',
    name: 'Malformação congênita das vias aéreas pulmonares (MAFP, CPAM)',
    aka: ['malformação adenomatoide cística', 'CCAM', 'congenital pulmonary airway malformation'],
    sites: ['pulmao'],
    linings: ['respiratorio-ciliado', 'cuboidal-simples'],
    features: ['musculo-liso', 'celulas-mucosas', 'cilios'],
    lining: 'Tipo 1: cistos grandes (mais de 2 cm) com epitélio pseudoestratificado ciliado e focos de células mucinosas em cerca de um terço. Tipo 2: cistos menores tipo bronquíolo com epitélio cuboide a colunar simples, sem células mucinosas. Tipo 3: microcistos com epitélio cuboide a colunar ciliado. Tipo 0: traqueobrônquico com células mucosas.',
    wall: 'Parede fibromuscular fina com músculo liso, sem cartilagem (exceto tipo 0); tipo 2 pode ter músculo estriado; sem glândulas brônquicas organizadas.',
    contents: 'Ar, muco ou líquido; comunica com a via aérea.',
    where: 'Um lobo, qualquer um; lesão congênita. Tipo 1 é o mais comum; tipo 2 associa-se a sequestro; tipo 3 toma o lobo inteiro no recém-nascido com hidropisia.',
    clues: ['Tipo 1 é o único com células mucinosas: podem ter KRAS mutado e preceder adenocarcinoma mucinoso.', 'Múltiplos cistos comunicantes sem cartilagem em placa.'],
    mimics: ['Cisto broncogênico intrapulmonar: solitário, cartilagem e glândulas, sem comunicação.', 'Blastoma pleuropulmonar tipo I: camada cambial de células primitivas sob o epitélio, DICER1.', 'Enfisema lobar congênito: alvéolos distendidos sem cistos revestidos.'],
    sources: ['https://www.pathologyoutlines.com/topic/lungnontumorcysticadenomatoid.html'],
  },
  {
    id: 'bolha-enfisematosa',
    name: 'Bolha enfisematosa e bleb subpleural',
    aka: ['bulha', 'emphysematous bulla', 'subpleural bleb'],
    sites: ['pulmao'],
    linings: ['sem-revestimento'],
    pseudocyst: true,
    lining: 'Nenhum revestimento epitelial: a superfície interna é tecido fibroso e paredes alveolares destruídas; o bleb é delimitado por fora pela pleura visceral.',
    wall: 'Septos alveolares rotos e fibrosados, fibras elásticas fragmentadas, antracose, pleura espessada; hiperplasia pneumocitária reativa focal, nunca epitélio contínuo.',
    contents: 'Ar.',
    where: 'Ápices e região subpleural (bleb) ou parênquima (bolha, maior que 1 cm); bolha gigante ocupa ao menos um terço do hemitórax. Tabagista ou jovem longilíneo com pneumotórax.',
    clues: ['Ausência de epitélio é o que separa bolha de cisto verdadeiro.'],
    mimics: ['Cisto broncogênico e MAFP: têm epitélio.', 'Pneumatocele pós-infecciosa: também sem epitélio, mas com pneumonia prévia e resolução espontânea.'],
    sources: ['https://pmc.ncbi.nlm.nih.gov/articles/PMC9727579/'],
  },
  {
    id: 'blastoma-pleuropulmonar-tipo-i',
    name: 'Blastoma pleuropulmonar tipo I',
    aka: ['PPB tipo I', 'pleuropulmonary blastoma type I'],
    sites: ['pulmao'],
    linings: ['respiratorio-ciliado'],
    features: ['cartilagem'],
    lining: 'Epitélio respiratório ciliado não neoplásico, enganosamente banal.',
    wall: 'Septos finos com, logo abaixo do epitélio, uma camada cambial contínua ou descontínua de células mesenquimais primitivas pequenas com diferenciação rabdomioblástica (desmina, miogenina, MyoD1) e às vezes nódulos de cartilagem imatura.',
    contents: 'Ar; cistos multiloculados.',
    where: 'Pulmão periférico ou pleura de criança em geral menor de 2 anos; pneumotórax em lactente; mutação germinativa de DICER1 com rastreio familiar.',
    clues: ['A camada cambial subepitelial de células primitivas define: pesquisar em toda a parede.', 'DICER1.'],
    mimics: ['MAFP tipo 1 e 4: septos sem camada cambial; amostragem exaustiva e DICER1 resolvem.', 'Cisto broncogênico: cartilagem madura, sem células primitivas.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK534211/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7443180/'],
  },
  {
    id: 'cisto-hidatico',
    name: 'Cisto hidático (equinococose)',
    aka: ['hidatidose', 'Echinococcus granulosus', 'hydatid cyst'],
    sites: ['figado', 'pulmao', 'encefalo', 'baco', 'rim', 'osso', 'mesenterio', 'adrenal'],
    linings: ['parasitario'],
    features: ['inflamacao', 'calcificacao'],
    lining: 'Nenhum epitélio do hospedeiro: por dentro, a membrana germinativa nucleada e delgada do parasita, sob a membrana laminada acelular, eosinofílica, PAS positiva, com estriação concêntrica.',
    wall: 'Pericisto fibroso do hospedeiro com eosinófilos, linfócitos, células epitelioides e gigantes, muitas vezes calcificado.',
    contents: 'Líquido claro, água de rocha, com areia hidática (protoescólices e ganchos birrefringentes); cistos-filhos.',
    where: 'Fígado (lobo direito em dois terços), pulmão (lobos inferiores), e mais raramente cérebro, baço, rim, osso e peritônio; áreas rurais com criação de ovinos e contato com cães.',
    clues: ['Membrana laminada acelular PAS positiva em lamelas: patognomônica.', 'Ganchos refringentes; sinal do nenúfar no pulmão.'],
    mimics: ['Abscesso ou cisto broncogênico infectado: têm epitélio ou granulação, sem membrana laminada.', 'Cisticercose: escólex com ventosas e parede com microtríquias.', 'Cisto biliar simples: epitélio biliar presente.'],
    sources: ['https://www.pathologyoutlines.com/topic/liverechinococcal.html', 'https://publications.ersnet.org/content/erj/21/6/1069'],
  },
  {
    id: 'cisto-sanguineo-valva-cardiaca',
    name: 'Cisto sanguíneo de valva cardíaca',
    aka: ['cisto hemático valvar congênito', 'blood cyst of the cardiac valve'],
    sites: ['coracao'],
    linings: ['endotelial'],
    features: ['sangue'],
    lining: 'Endotélio achatado contínuo com o endocárdio; não é epitélio.',
    wall: 'Escasso tecido fibroso do estroma valvar; comunica com a luz ventricular por canais endotelizados.',
    contents: 'Sangue.',
    where: 'Face atrial das valvas atrioventriculares e aparelho subvalvar em recém-nascidos e lactentes; regride em poucos meses, raro no adulto.',
    clues: ['Nódulo vermelho-escuro de poucos milímetros na face atrial da valva de neonato.'],
    mimics: ['Fibroelastoma papilífero: frondes avasculares de tecido elástico.', 'Vegetação de endocardite: fibrina, neutrófilos, germes.', 'Mixoma: células estreladas em matriz mixoide.'],
    sources: ['https://pubmed.ncbi.nlm.nih.gov/6873935/'],
  },
  {
    id: 'cisto-mamario-simples',
    name: 'Cisto mamário simples',
    aka: ['cisto da alteração fibrocística', 'simple breast cyst'],
    sites: ['mama'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['calcificacao'],
    lining: 'Cuboide a colunar achatado e atenuado, muitas vezes em camada única e desnudo pela pressão; camada mioepitelial preservada na periferia (p63, calponina).',
    wall: 'Estroma fibroso hialinizado, inflamação crônica leve, macrófagos espumosos e calcificações; adenose e fibrose adjacentes.',
    contents: 'Líquido claro, turvo ou esverdeado (cisto azul em cúpula a fresco).',
    where: 'Unidade ducto-lobular terminal, quadrante superolateral; mulheres de 35 a 55 anos; anecoico com reforço posterior (BI-RADS 2).',
    clues: ['Revestimento achatado com mioepitélio presente.'],
    mimics: ['Cisto com metaplasia apócrina: citoplasma eosinofílico granular e decapitação.', 'Galactocele: lactação, conteúdo lácteo.', 'Ectasia ductal: ducto subareolar com fibrose e inflamação periductal.'],
    sources: ['https://www.pathologyoutlines.com/topic/breastfcc.html'],
  },
  {
    id: 'cisto-mamario-metaplasia-apocrina',
    name: 'Cisto mamário com metaplasia apócrina',
    aka: ['metaplasia apócrina cística', 'apocrine metaplasia'],
    sites: ['mama'],
    linings: ['apocrino'],
    features: ['calcificacao'],
    lining: 'Cuboide a colunar com citoplasma abundante eosinofílico granular, núcleo redondo com nucléolo proeminente e secreção por decapitação; em camada única, tufos ou papilas com eixo delicado. GCDFP-15 e receptor de andrógeno positivos, RE e RP negativos.',
    wall: 'Estroma fibroso; mioepitélio contínuo na periferia; adenose, fibrose e microcalcificações.',
    contents: 'Líquido seroso a espesso, eosinofílico, com microcalcificações.',
    where: 'Unidade ducto-lobular terminal, cistos agrupados; lesão não proliferativa, sem aumento de risco.',
    clues: ['Decapitação com nucléolo proeminente.'],
    mimics: ['Cisto simples: revestimento achatado sem granularidade.', 'Carcinoma apócrino ou CDIS apócrino: atipia marcada, perda de mioepitélio, necrose.', 'Papiloma intraductal: eixos fibrovasculares arborizantes com dupla camada.'],
    sources: ['https://www.pathologyoutlines.com/topic/breastapocrinemetaplasia.html'],
  },
  {
    id: 'galactocele',
    name: 'Galactocele',
    aka: ['cisto lácteo', 'galactocele'],
    sites: ['mama'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['inflamacao'],
    lining: 'Cuboide achatado com alteração secretora (vacúolos, núcleo hipercromático protruindo na luz) e mioepitélio preservado; muitas vezes atenuado ou desnudo.',
    wall: 'Alteração secretora lobular adjacente, reação fibroinflamatória, macrófagos espumosos, reação xantogranulomatosa se extravasar.',
    contents: 'Leite ou material lácteo espesso, cremoso a caseoso; nível gordura-líquido na mamografia.',
    where: 'Região central e subareolar de lactante ou nos meses após o desmame; raro em lactentes e homens.',
    clues: ['Lactação ou desmame recente; aspiração devolve leite.', 'Nível gordura-líquido é praticamente diagnóstico.'],
    mimics: ['Cisto simples: conteúdo aquoso, sem alteração secretora.', 'Adenoma lactacional: sólido com ácinos secretores.', 'Necrose gordurosa: sem epitélio, macrófagos e calcificação em casca de ovo.'],
    sources: ['https://www.pathologyoutlines.com/topic/breastgalactocele.html', 'https://www.ncbi.nlm.nih.gov/books/NBK578180/'],
  },
  {
    id: 'cisto-ectasia-ductal',
    name: 'Ectasia ductal (cisto de ectasia)',
    aka: ['mastite periductal', 'comedomastite', 'duct ectasia'],
    sites: ['mama'],
    linings: ['achatado-inespecifico', 'cuboidal-simples'],
    features: ['inflamacao', 'calcificacao', 'hemossiderina'],
    lining: 'Epitélio ductal atenuado, atrófico ou totalmente desnudo, com mioepitélio na periferia; sem metaplasia apócrina proeminente.',
    wall: 'Fibrose periductal densa e concêntrica, linfócitos e plasmócitos, histiócitos espumosos dentro e ao redor do epitélio, células gigantes, macrófagos com pigmento e calcificações lineares ramificadas.',
    contents: 'Material espesso e cremoso, amarelo-esverdeado ou acastanhado, com histiócitos espumosos.',
    where: 'Ductos coletores subareolares de mulheres peri e pós-menopausa; tabagismo; descarga papilar espessa e retração do mamilo.',
    clues: ['Histiócitos espumosos na luz.', 'Calcificações lineares periductais que imitam CDIS na mamografia.'],
    mimics: ['CDIS comedônico: proliferação atípica com necrose intraductal.', 'Abscesso subareolar: metaplasia escamosa queratinizante do ducto lactífero.'],
    sources: ['https://www.pathologyoutlines.com/topic/breastductectasia.html'],
  },
  {
    id: 'hiperplasia-hipersecretora-cistica',
    name: 'Hiperplasia hipersecretora cística',
    aka: ['lesão hipersecretora cística', 'cystic hypersecretory hyperplasia'],
    sites: ['mama'],
    linings: ['cuboidal-simples', 'achatado-inespecifico'],
    features: ['material-eosinofilico', 'coloide'],
    lining: 'Camada única e ordenada de epitélio achatado, cuboide ou colunar sem atipia; pseudoestratificado ou micropapilar discreto; mioepitélio preservado.',
    wall: 'Estroma fibroso; ductos cisticamente dilatados agrupados.',
    contents: 'Secreção homogênea eosinofílica e acelular, semelhante a coloide tireoidiano, retraída da parede com margem festonada e fendas lineares.',
    where: 'Massa multicística palpável em mulher adulta.',
    clues: ['Coloide tireoide-símile com retração festonada é a marca.', 'A ausência de atipia é o que a mantém benigna.'],
    mimics: ['Carcinoma hipersecretor cístico: mesma secreção, com atipia e micropapilas complexas.', 'Cistos simples com secreção espessa: sem retração festonada.'],
    sources: ['https://www.pathologyoutlines.com/topic/breastcystichypersecretoryhyperplasia.html'],
  },
  {
    id: 'papiloma-intraductal-cistico',
    name: 'Papiloma intraductal com alteração cística',
    aka: ['papiloma intracístico', 'intraductal papilloma'],
    sites: ['mama'],
    linings: ['cuboidal-simples'],
    features: ['sangue', 'hemossiderina'],
    lining: 'Epitélio luminal cuboide a colunar sem atipia sobre camada mioepitelial contínua, revestindo eixos fibrovasculares arborizantes; a parede do cisto tem epitélio ductal atenuado.',
    wall: 'Ducto dilatado com esclerose e eixos fibrovasculares largos; hiperplasia usual, metaplasia apócrina, infarto, metaplasia escamosa, esferulose colagenosa e hemossiderina.',
    contents: 'Líquido seroso ou hemorrágico, por torção ou infarto do papiloma.',
    where: 'Ducto central subareolar (papiloma solitário) ou unidades terminais periféricas (múltiplos); descarga papilar sanguinolenta uniductal.',
    clues: ['Mioepitélio contínuo nos eixos (p63, SMMHC) define a benignidade.'],
    mimics: ['Carcinoma papilífero encapsulado: sem mioepitélio nos eixos e na periferia.', 'Papiloma com CDIS: população monótona CK5/6 negativa em área de 3 mm ou mais.', 'Metaplasia apócrina papilar: sem eixos fibrovasculares verdadeiros.'],
    sources: ['https://www.pathologyoutlines.com/topic/breastpapilloma.html'],
  },
  {
    id: 'lesao-mucocele-like-mamaria',
    name: 'Lesão mucocele-símile da mama',
    aka: ['tumor mucocele-like', 'mucocele-like lesion'],
    sites: ['mama'],
    linings: ['cuboidal-simples', 'colunar-mucinoso'],
    features: ['muco', 'calcificacao'],
    lining: 'Achatado, cuboide baixo ou colunar, uniforme e sem atipia; mioepitélio preservado.',
    wall: 'Mucina extravasada dissecando o estroma, com macrófagos, inflamação e microcalcificações; podem coexistir lesões de células colunares, HDA ou CDIS.',
    contents: 'Mucina abundante intraluminal e extravasada.',
    where: 'Unidade ducto-lobular terminal, mulheres em torno dos 40 anos; microcalcificações agrupadas na mamografia.',
    clues: ['Mucina extravasada com tiras de epitélio flutuando.', 'Em core biopsy indica exérese, pelo risco de CDIS ou carcinoma mucinoso associado.'],
    mimics: ['Carcinoma mucinoso: ninhos de células neoplásicas flutuando nos lagos de mucina.', 'Cisto simples com secreção espessa: sem extravasamento.'],
    sources: ['https://www.pathologyoutlines.com/topic/breastmucocele.html', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10198240/'],
  },
]
