# -*- coding: utf-8 -*-
"""Catálogo de bichos — verbetes. Cada foto: (título no Commons, legenda, coloração opcional)."""

HEADER = """/* ==========================================================================
   bugs.ts — Catálogo de bichos: fungos, parasitas, bactérias, vírus e
   artrópodes que aparecem na lâmina. Os verbetes entram aqui, em código; as
   facetas são o vocabulário dos filtros e crescem conforme os verbetes pedem.
   Fotos: Wikimedia Commons / CDC PHIL, licença livre, crédito em cada uma.
   ========================================================================== */"""

FACETS = {
    "traits": [
        ("esporo", "Faz esporo / conídio"),
        ("hifa-verdadeira", "Hifa verdadeira"),
        ("pseudo-hifa", "Pseudo-hifa"),
        ("hifa-septada", "Hifa septada"),
        ("hifa-nao-septada", "Hifa não septada (cenocítica)"),
        ("brotamento", "Brotamento"),
        ("brotamento-base-estreita", "Brotamento de base estreita"),
        ("brotamento-base-larga", "Brotamento de base larga"),
        ("brotamento-multiplo", "Brotamento múltiplo (roda de leme)"),
        ("capsula", "Cápsula"),
        ("esferula", "Esférula / esporângio"),
        ("espicula", "Tem espícula"),
        ("intracelular", "Intracelular"),
        ("pigmentado", "Pigmentado (demáceo)"),
        ("ovo", "Ovo"),
        ("larva", "Larva"),
        ("verme", "Verme em corte"),
        ("cisto", "Cisto"),
        ("trofozoito", "Trofozoíto"),
        ("artropode", "Artrópode (ácaro, inseto, carrapato)"),
        ("bacilo", "Bacilo"),
        ("filamentoso", "Bactéria filamentosa"),
        ("espiroqueta", "Espiroqueta"),
        ("grao", "Grão / grânulo de enxofre"),
        ("splendore", "Fenômeno de Splendore-Hoeppli"),
        ("membrana-laminada", "Membrana laminada"),
        ("inclusao-nuclear", "Inclusão intranuclear"),
        ("inclusao-citoplasmatica", "Inclusão citoplasmática"),
        ("multinucleacao", "Células multinucleadas"),
        ("coilocito", "Coilócito"),
        ("granuloma", "Forma granuloma"),
        ("baar", "BAAR (Ziehl / Fite positivo)"),
        ("grocott", "Grocott (GMS) positivo"),
        ("pas", "PAS positivo"),
        ("giemsa", "Giemsa positivo"),
        ("warthin-starry", "Warthin-Starry positivo"),
        ("mucicarmina", "Mucicarmina positivo"),
        ("ihq", "Imuno-histoquímica específica"),
        ("citologia", "Visto em citologia / esfregaço"),
    ],
    "sites": [
        ("pele", "Pele e anexos"),
        ("partes-moles", "Subcutâneo e partes moles"),
        ("mucosa-oral", "Mucosa oral"),
        ("nasofaringe", "Nariz e nasofaringe"),
        ("seios-paranasais", "Seios paranasais"),
        ("esofago", "Esôfago"),
        ("estomago", "Estômago"),
        ("intestino", "Intestino"),
        ("apendice", "Apêndice"),
        ("anus", "Ânus e canal anal"),
        ("figado", "Fígado"),
        ("pulmao", "Pulmão"),
        ("pleura", "Pleura"),
        ("coracao", "Coração"),
        ("snc", "Sistema nervoso central"),
        ("nervo", "Nervo periférico"),
        ("linfonodo", "Linfonodo"),
        ("medula", "Medula óssea"),
        ("colo-uterino", "Colo uterino e vagina"),
        ("genital", "Genitália externa e uretra"),
        ("placenta", "Placenta"),
        ("trato-urinario", "Trato urinário"),
        ("rim", "Rim"),
        ("osso", "Osso e articulação"),
        ("musculo", "Músculo esquelético"),
        ("olho", "Olho"),
        ("sangue", "Sangue"),
    ],
    "clinical": [
        ("imunossuprimido", "Imunossuprimido"),
        ("hiv", "HIV / aids"),
        ("transplante", "Transplantado"),
        ("corticoide", "Corticoide / imunobiológico"),
        ("neutropenia", "Neutropenia"),
        ("diabetes", "Diabetes"),
        ("imunocompetente", "Imunocompetente"),
        ("crianca", "Criança"),
        ("zona-rural", "Zona rural / contato com solo"),
        ("viagem", "Viagem a área endêmica"),
        ("animais", "Contato com animais"),
        ("agua", "Água contaminada / saneamento"),
        ("alimento", "Carne ou peixe malcozidos"),
        ("areia", "Praia / solo arenoso, pés descalços"),
        ("trauma", "Trauma / inoculação"),
        ("ist", "IST / contato sexual"),
        ("diu", "Uso de DIU"),
        ("cronico", "Curso crônico"),
        ("agudo", "Curso agudo"),
        ("contaminante", "Contaminante da lâmina / ambiente"),
    ],
}

ENTRIES = [
    {
        "id": "histoplasma",
        "name": "Histoplasma capsulatum",
        "aka": ["Histoplasmose"],
        "summary": "Leveduras pequenas (2–4 µm), intracelulares em macrófagos, com brotamento de base estreita; o halo claro no HE é artefato de retração.",
        "description": "## Morfologia\n- Leveduras ovais de **2 a 4 µm**, uniformes, dentro do citoplasma de macrófagos e histiócitos — em grupos, como \"sacos de bolinhas\".\n- **Brotamento único de base estreita.**\n- No HE quase não se vê: um ponto basofílico cercado por um halo claro (retração do citoplasma, não cápsula).\n- **Grocott (GMS)** e **PAS** mostram as leveduras com clareza; a mucicarmina é negativa (diferencia de Cryptococcus).\n\n## Diferenciais\n- Leishmania: mesmo tamanho e também intracelular, mas tem cinetoplasto e é **negativa no Grocott**.\n- Cryptococcus: maior e variável (4–15 µm), cápsula mucicarmina-positiva.\n- Candida glabrata: extracelular, sem brotamento de base estreita organizado em macrófagos.\n- Pneumocystis: cistos em \"bola amassada\", sem brotamento.\n\n## Contexto\n- Inalação de conídios em solo com fezes de aves e morcegos; grutas, galinheiros, obras.\n- Granulomas necrosantes ou não; no imunossuprimido (HIV, transplante) a forma disseminada tem macrófagos repletos de leveduras e pouco granuloma.",
        "traits": ["brotamento", "brotamento-base-estreita", "intracelular", "granuloma", "grocott", "pas", "citologia"],
        "sites": ["pulmao", "linfonodo", "medula", "figado", "mucosa-oral", "intestino", "pele"],
        "clinical": ["imunossuprimido", "hiv", "transplante", "zona-rural", "imunocompetente"],
        "photos": [
            ("File:Histopathology of Histoplasma capsulatum, GMS stain.jpg", "Granuloma de intestino delgado: leveduras com brotamento de base estreita", "Grocott (GMS)"),
            ("File:Histopathology of histoplasma, HE stain.png", "HE do mesmo granuloma: leveduras dentro de histiócitos, cada uma com halo claro de retração (legendas do autor)", "HE"),
            ("File:Histoplasma pas-d.jpg", "Biópsia de fígado: grupos de leveduras pequenas coradas em vermelho", "PAS-D"),
            ("File:Histoplasmosis - GMS stain Case 159 (5441201037).jpg", "Numerosas leveduras pequenas em brotamento, quase invisíveis no HE do mesmo caso", "Grocott (GMS)"),
            ("File:Histoplasmosis (5414173501).jpg", "Linfonodo, esfregaço: macrófagos carregados de leveduras", "Diff-Quik"),
        ],
    },
    {
        "id": "paracoccidioides",
        "name": "Paracoccidioides brasiliensis",
        "aka": ["Paracoccidioidomicose", "PCM", "Blastomicose sul-americana", "Lutz"],
        "summary": "Levedura grande de parede espessa com brotamentos múltiplos ao redor da célula-mãe: a \"roda de leme\" (ou orelhas do Mickey, quando são só dois).",
        "description": "## Morfologia\n- Leveduras redondas de tamanho muito variável, **5 a 30 µm** (algumas até 60 µm), parede espessa e birrefringente.\n- **Brotamentos múltiplos, de base estreita**, distribuídos pela circunferência da célula-mãe: a **roda de leme** é patognomônica. Com dois brotos, a imagem do \"Mickey Mouse\".\n- Grocott (GMS) e PAS destacam a parede; no HE aparecem como corpos refringentes de parede dupla.\n- Cadeias de leveduras pequenas brotando em sequência também ocorrem.\n\n## Diferenciais\n- Blastomyces: brotamento **único** de base larga.\n- Cryptococcus: cápsula mucicarmina-positiva, brotamento único.\n- Histoplasma: muito menor, intracelular.\n- Procure a roda de leme antes de fechar: leveduras isoladas de P. brasiliensis imitam qualquer um dos três.\n\n## Contexto\n- Micose sistêmica endêmica da América Latina, sobretudo Brasil; trabalhador rural, homem adulto, tabagista.\n- **Forma crônica do adulto**: pulmão, mucosa oral e laríngea (estomatite moriforme), pele, adrenal. **Forma aguda/juvenil**: linfonodos, fígado e baço, medula.\n- Granulomas com células gigantes e microabscessos; hiperplasia pseudoepiteliomatosa na mucosa e na pele.",
        "traits": ["brotamento", "brotamento-multiplo", "brotamento-base-estreita", "granuloma", "grocott", "pas"],
        "sites": ["pulmao", "mucosa-oral", "pele", "linfonodo", "figado", "medula"],
        "clinical": ["zona-rural", "imunocompetente", "cronico", "imunossuprimido"],
        "photos": [
            ("File:Paracoccidioides brasiliensis 01.jpg", "Célula-mãe com brotamentos múltiplos em roda de leme", "Prata metenamina (GMS)"),
            ("File:Histopathology of paracoccidioidomycosis.jpg", "Leveduras de parede espessa, algumas com brotos", "Prata metenamina (GMS)"),
            ("File:Paracoccidioidomycosis.jpg", "Leveduras grandes de parede espessa; à direita, brotos múltiplos em torno da célula-mãe"),
        ],
    },
    {
        "id": "candida",
        "name": "Candida",
        "aka": ["Candidíase", "Monilíase", "Candida albicans"],
        "summary": "Leveduras de 3–5 µm com brotamento, pseudo-hifas e hifas verdadeiras, na superfície de mucosas; a mais comum das micoses.",
        "description": "## Morfologia\n- Leveduras ovais de **3 a 5 µm** com brotamento, **pseudo-hifas** (cadeias de leveduras alongadas com constrições) e, em C. albicans, **hifas verdadeiras** septadas.\n- Fica na **superfície**: entre as escamas da mucosa esofágica ou oral, na camada córnea da pele, com neutrófilos.\n- PAS e Grocott mostram tudo; no HE as pseudo-hifas são discretas e basofílicas.\n- C. glabrata não forma pseudo-hifas: só leveduras pequenas.\n\n## Diferenciais\n- Aspergillus: hifas septadas uniformes com ramificação em 45°, sem leveduras.\n- Malassezia: leveduras com hifas curtas só na camada córnea, sem invasão.\n- Restos de queratina e fibrina imitam pseudo-hifas no HE — confirme com PAS.\n\n## Contexto\n- Esofagite em imunossuprimido, diabético, usuário de corticoide inalatório ou antibiótico; vaginite; intertrigo; onicomicose.\n- Invasão profunda (hifas no tecido, vasos) indica candidíase invasiva, quase sempre em neutropênico ou em terapia intensiva.",
        "traits": ["brotamento", "pseudo-hifa", "hifa-verdadeira", "hifa-septada", "pas", "grocott", "citologia"],
        "sites": ["esofago", "mucosa-oral", "colo-uterino", "pele", "estomago", "sangue"],
        "clinical": ["imunossuprimido", "diabetes", "hiv", "neutropenia", "corticoide", "imunocompetente", "agudo"],
        "photos": [
            ("File:Esophageal candidiasis (1) PAS stain.jpg", "Esôfago: pseudo-hifas e leveduras na camada superficial do epitélio", "PAS"),
            ("File:Candidiasis esophagus very high mag.jpg", "Leveduras e pseudo-hifas entre células escamosas descamadas, com neutrófilos", "PAS"),
            ("File:Candidiasis (5494228352).jpg", "Colônia de Candida dentro de um abscesso", "HE"),
        ],
    },
    {
        "id": "aspergillus",
        "name": "Aspergillus",
        "aka": ["Aspergilose", "Bola fúngica", "Aspergiloma"],
        "summary": "Hifas septadas, finas e de calibre uniforme, com ramificação dicotômica em ângulo agudo (45°); cabeças conidiais só onde há ar.",
        "description": "## Morfologia\n- Hifas **septadas**, de **3 a 6 µm**, calibre regular, com **ramificação dicotômica em ângulo agudo** (~45°), muitas vezes paralelas e orientadas na mesma direção.\n- **Cabeças conidiais** (vesícula com fiálides e conídios) aparecem quando o fungo cresce em cavidade aerada: bola fúngica, seio, brônquio. Não ocorrem no tecido invadido.\n- Invasão vascular com infarto e necrose na forma invasiva; hifas em cabelo de anjo dentro da parede do vaso.\n- Cristais de oxalato de cálcio (birrefringentes) acompanham A. niger.\n\n## Diferenciais\n- Mucorales: hifas largas, irregulares, quase sem septos, ramificação em ângulo reto.\n- Fusarium e Scedosporium: idênticos no tecido — só a cultura separa. Laude como \"hifas septadas compatíveis com Aspergillus\".\n- Candida: tem leveduras e pseudo-hifas.\n\n## Contexto\n- **Invasiva**: neutropenia prolongada, transplante, corticoide.\n- **Aspergiloma**: cavidade prévia (tuberculose, bronquiectasia).\n- **Alérgica (ABPA, sinusite alérgica)**: muco eosinofílico com poucas hifas e cristais de Charcot-Leyden.",
        "traits": ["hifa-verdadeira", "hifa-septada", "esporo", "grocott", "pas"],
        "sites": ["pulmao", "seios-paranasais", "pele", "snc", "olho"],
        "clinical": ["neutropenia", "transplante", "corticoide", "imunossuprimido", "cronico", "imunocompetente"],
        "photos": [
            ("File:Histopathology of pulmonary aspergillosis.jpg", "Aspergilose pulmonar invasiva: hifas densas e paralelas com necrose", "HE"),
            ("File:Aspergillus - very high mag.jpg", "Cabeças conidiais (frutificação), vistas quando o fungo cresce em cavidade com ar", "HE"),
            ("File:Aspergillus micrograph intermediary magnification.jpg", "Bola fúngica: hifas em arranjo radiado", "HE"),
            ("File:Aspergillus niger infection.jpg", "Seio paranasal: cabeça conidial de A. niger com conídios pigmentados e cristais de oxalato de cálcio", "HE"),
        ],
    },
    {
        "id": "mucorales",
        "name": "Mucorales (Rhizopus, Mucor, Lichtheimia)",
        "aka": ["Mucormicose", "Zigomicose"],
        "summary": "Hifas largas (5–20 µm), em fita, de calibre irregular, quase sem septos, com ramificação em ângulo reto; invadem vasos e causam infarto.",
        "description": "## Morfologia\n- Hifas **largas, de 5 a 20 µm**, parede fina, **calibre irregular** (dobram e colapsam como fitas), **raros septos** (cenocíticas).\n- **Ramificação em ângulo reto**, não dicotômica.\n- **Angioinvasão** com trombose e infarto: tecido necrótico onde as hifas são mais fáceis de achar na parede dos vasos.\n- Coram mal pelo Grocott (parede fina) — o HE muitas vezes mostra melhor. PAS ajuda.\n\n## Diferenciais\n- Aspergillus: hifas finas, uniformes, septadas, ângulo agudo.\n- Cortes tangenciais de hifas de Aspergillus parecem largos: procure septos e a regularidade do calibre.\n\n## Contexto\n- **Cetoacidose diabética** (forma rino-orbito-cerebral), neutropenia, transplante, ferro/deferoxamina, trauma com solo.\n- Emergência: o diagnóstico na congelação ou no esfregaço muda a conduta cirúrgica.",
        "traits": ["hifa-verdadeira", "hifa-nao-septada", "grocott", "pas"],
        "sites": ["seios-paranasais", "pulmao", "pele", "intestino", "snc"],
        "clinical": ["diabetes", "neutropenia", "transplante", "imunossuprimido", "trauma", "agudo"],
        "photos": [
            ("File:Zygomycosis.jpg", "Pulmão: hifas largas, de calibre irregular, com ramificação em ângulo reto", "HE"),
        ],
    },
    {
        "id": "cryptococcus",
        "name": "Cryptococcus neoformans / gattii",
        "aka": ["Criptococose", "Torulose"],
        "summary": "Levedura de tamanho variável (4–15 µm) com cápsula mucoide espessa, mucicarmina-positiva, e brotamento único de base estreita.",
        "description": "## Morfologia\n- Leveduras redondas de **4 a 15 µm**, tamanho **variável** na mesma lâmina, com **cápsula** que aparece como halo claro no HE.\n- **Brotamento único, de base estreita.**\n- **Mucicarmina** cora a cápsula em vermelho; Alcian blue também. **Fontana-Masson** marca a parede (melanina) — útil nas formas com cápsula deficiente.\n- Reação varia de quase nada (lesão \"em bolha de sabão\" no imunossuprimido) a granuloma.\n\n## Diferenciais\n- Histoplasma: menor, uniforme, sem cápsula, mucicarmina negativa.\n- Blastomyces: base larga, parede espessa, sem cápsula.\n- Cryptococcus capsulodeficiente parece Histoplasma ou Candida glabrata: Fontana-Masson resolve.\n\n## Contexto\n- Meningite e pneumonia no paciente com HIV/aids ou transplantado; C. gattii acomete imunocompetentes.\n- Fezes de pombo, eucaliptos (gattii).",
        "traits": ["brotamento", "brotamento-base-estreita", "capsula", "mucicarmina", "grocott", "pas", "granuloma", "citologia"],
        "sites": ["pulmao", "snc", "pele", "linfonodo", "medula", "figado"],
        "clinical": ["hiv", "transplante", "imunossuprimido", "corticoide", "imunocompetente"],
        "photos": [
            ("File:Cryptococcosis of lung in patient with AIDS. Mucicarmine stain 962 lores.jpg", "Pulmão em paciente com aids: leveduras com cápsula corada em vermelho", "Mucicarmina"),
            ("File:Cryptococcosis of lung in patient with AIDS Methenamine silver stain 963 lores.jpg", "Leveduras de tamanhos variados dentro de um alvéolo", "Prata metenamina (GMS)"),
            ("File:Cryptococcosis - Mucicarmine stain (5280759612).jpg", "A cápsula cora em vermelho — o que separa Cryptococcus das outras leveduras", "Mucicarmina"),
            ("File:Pulmonary cryptococcosis (2) Alcian blue-PAS.jpg", "Criptococose pulmonar em imunossuprimido", "Alcian blue-PAS"),
        ],
    },
    {
        "id": "pneumocystis",
        "name": "Pneumocystis jirovecii",
        "aka": ["Pneumocistose", "PCP", "Pneumocystis carinii"],
        "summary": "Exsudato alveolar espumoso e eosinofílico no HE; no Grocott, cistos de 4–6 µm em taça ou bola de pingue-pongue amassada, sem brotamento.",
        "description": "## Morfologia\n- No HE, alvéolos cheios de um **exsudato espumoso, eosinofílico, acelular** — o organismo não se vê.\n- No **Grocott**, cistos redondos ou em **taça / bola amassada**, de **4 a 6 µm**, muitas vezes com um ponto central mais escuro; **não brotam** (cistos justapostos imitam brotamento).\n- Pneumonite intersticial leve; formas granulomatosas e cavitárias existem e têm poucos organismos.\n- Imuno-histoquímica e Giemsa (trofozoítos) são alternativas.\n\n## Diferenciais\n- Histoplasma: brotamento verdadeiro, intracelular em macrófagos.\n- Candida glabrata: leveduras com brotamento, sem o exsudato espumoso.\n- Proteinose alveolar: material granular PAS-positivo, sem cistos no Grocott.\n\n## Contexto\n- HIV com CD4 < 200, transplante, corticoide prolongado, quimioterapia.\n- Diagnóstico frequente em lavado broncoalveolar e escarro induzido.",
        "traits": ["cisto", "grocott", "citologia"],
        "sites": ["pulmao"],
        "clinical": ["hiv", "transplante", "imunossuprimido", "corticoide", "agudo"],
        "photos": [
            ("File:Pneumocystis (carinii) jiroveci (3679907066).jpg", "Cistos em taça e bola amassada; cistos justapostos podem imitar brotamento", "Grocott (GMS)"),
            ("File:PCP high mag.jpg", "Exsudato alveolar espumoso e eosinofílico — o aspecto no HE", "HE"),
            ("File:Pneumocystis pneumonia with minimal findings - GMS Case 212 (7165923732).jpg", "Biópsia transbrônquica com poucos moldes alveolares espumosos, mas cistos típicos na prata", "Grocott (GMS)"),
        ],
    },
    {
        "id": "blastomyces",
        "name": "Blastomyces dermatitidis",
        "aka": ["Blastomicose norte-americana"],
        "summary": "Levedura grande (8–15 µm) de parede espessa e refringente, com brotamento único de base larga.",
        "description": "## Morfologia\n- Leveduras redondas de **8 a 15 µm**, parede **espessa, de duplo contorno**, refringente.\n- **Brotamento único de base larga** — a base do broto é quase tão larga quanto a levedura.\n- Núcleos múltiplos visíveis no HE; frequentemente dentro de células gigantes.\n- Reação **piogranulomatosa**: neutrófilos no centro de granulomas, hiperplasia pseudoepiteliomatosa na pele.\n\n## Diferenciais\n- Paracoccidioides: brotos múltiplos, de base estreita, em roda de leme.\n- Cryptococcus: cápsula mucicarmina-positiva, base estreita.\n- Coccidioides: esférula com endósporos, sem brotamento.\n\n## Contexto\n- Endêmico no vale do Mississippi e Grandes Lagos, na América do Norte; raro no Brasil, pense em viagem.\n- Pulmão, pele, osso e próstata; imunocompetentes.",
        "traits": ["brotamento", "brotamento-base-larga", "granuloma", "grocott", "pas", "multinucleacao"],
        "sites": ["pulmao", "pele", "osso", "trato-urinario", "snc"],
        "clinical": ["imunocompetente", "viagem", "zona-rural", "cronico"],
        "photos": [
            ("File:North American blastomycosis (5280139630).jpg", "Levedura com brotamento de base larga e parede de duplo contorno dentro de célula gigante", "HE"),
            ("File:North American blastomycosis (5279534691).jpg", "Célula gigante multinucleada com levedura em brotamento no citoplasma", "HE"),
        ],
    },
    {
        "id": "coccidioides",
        "name": "Coccidioides immitis / posadasii",
        "aka": ["Coccidioidomicose", "Febre do vale"],
        "summary": "Esférulas grandes (20–80 µm) de parede espessa, cheias de endósporos de 2–5 µm que se libertam quando a esférula rompe; sem brotamento.",
        "description": "## Morfologia\n- **Esférulas** redondas de **20 a 80 µm**, parede espessa e refringente, com **endósporos** de 2 a 5 µm no interior.\n- Esférula rompida libera endósporos que parecem leveduras pequenas sem brotamento.\n- Hifas e artroconídios só em cavidades ou em cultura — não confundir com Aspergillus.\n- Granulomas necrosantes, eosinófilos abundantes.\n\n## Diferenciais\n- Rhinosporidium: esporângio muito maior (até 300 µm), mucosa nasal/ocular.\n- Blastomyces e Paracoccidioides: brotamento.\n- Endósporos soltos vs. Histoplasma: procure a esférula-mãe.\n\n## Contexto\n- Solo árido: sudoeste dos EUA, norte do México, Argentina e, no Brasil, o **semiárido nordestino** (caçadores de tatu).\n- Pneumonia autolimitada na maioria; disseminação em imunossuprimidos.",
        "traits": ["esferula", "esporo", "granuloma", "grocott", "pas"],
        "sites": ["pulmao", "pele", "osso", "snc", "linfonodo"],
        "clinical": ["viagem", "zona-rural", "imunocompetente", "imunossuprimido"],
        "photos": [
            ("File:Spherule and endospore forms of Coccidioides immitis 01ee057 lores.jpg", "Esférulas e endósporos liberados no pulmão", "Prata metenamina (GMS)"),
            ("File:Mature spherule with endospores of Coccidioides immitis PHIL 480 lores.jpg", "Esférula madura cheia de endósporos, com neutrófilos ao redor", "HE"),
            ("File:Coccidioidomycosis Spherule.jpg", "Esférula corada pelo PAS", "PAS"),
        ],
    },
    {
        "id": "trypanosoma-cruzi",
        "name": "Trypanosoma cruzi",
        "aka": ["Doença de Chagas", "Ninhos de amastigotas"],
        "summary": "Ninhos (pseudocistos) de amastigotas de 2–4 µm dentro de fibras musculares cardíacas, cada uma com núcleo e cinetoplasto em barra.",
        "description": "## Morfologia\n- **Amastigotas** de 2 a 4 µm, redondas, com núcleo e um **cinetoplasto** em barra, agrupadas num **pseudocisto** intracelular — fibra miocárdica, músculo liso do esôfago e do cólon, glia.\n- Miocardite linfo-histiocitária difusa com fibrose; na fase crônica os ninhos são raros e o achado é a inflamação e a fibrose.\n- Na reativação (HIV, transplante) os ninhos são abundantes, inclusive no cérebro e na pele.\n\n## Diferenciais\n- Toxoplasma: cistos sem cinetoplasto, bradizoítos menores e em forma de banana.\n- Leishmania: também tem cinetoplasto, mas fica em macrófagos, não em fibras musculares.\n- Sarcocystis: cistos muito maiores, com bradizoítos alongados, em músculo.\n\n## Contexto\n- Endêmica na América Latina; transmissão vetorial (barbeiro), oral (açaí, caldo de cana), congênita, transfusional.\n- Megaesôfago e megacólon: destruição do plexo mioentérico.",
        "traits": ["intracelular", "cisto", "giemsa", "ihq"],
        "sites": ["coracao", "esofago", "intestino", "snc", "pele"],
        "clinical": ["zona-rural", "hiv", "transplante", "cronico", "agudo"],
        "photos": [
            ("File:Trypanosoma cruzi heart.jpg", "Ninho de amastigotas dentro de fibra miocárdica (coração de macaco, acervo do CDC)", "HE"),
        ],
    },
    {
        "id": "toxoplasma",
        "name": "Toxoplasma gondii",
        "aka": ["Toxoplasmose"],
        "summary": "Cistos teciduais redondos cheios de bradizoítos e taquizoítos livres em forma de meia-lua; sem cinetoplasto.",
        "description": "## Morfologia\n- **Cistos** redondos de **20 a 100 µm**, parede fina, repletos de **bradizoítos** pequenos (PAS-positivos); sem inflamação ao redor quando latentes.\n- **Taquizoítos** livres, de 2 a 6 µm, em meia-lua, nas lesões ativas — difíceis no HE; a **imuno-histoquímica** os marca.\n- Encefalite necrosante com vasculite no imunossuprimido.\n- **Linfadenite toxoplásmica** (Piringer-Kuchinka): hiperplasia folicular, agregados de histiócitos epitelioides e hiperplasia de células B monocitoides — quase nunca se vê o parasita.\n\n## Diferenciais\n- Trypanosoma cruzi: amastigotas com cinetoplasto, em músculo.\n- Histoplasma: leveduras em macrófagos, Grocott positivo (Toxoplasma é negativo).\n\n## Contexto\n- Carne malcozida e fezes de gato; infecção congênita (coriorretinite, calcificações cerebrais).\n- Encefalite e miocardite em HIV/aids e transplantados; a maioria é reativação.",
        "traits": ["cisto", "intracelular", "ihq", "pas"],
        "sites": ["snc", "linfonodo", "placenta", "olho", "coracao", "pulmao"],
        "clinical": ["hiv", "transplante", "imunossuprimido", "imunocompetente", "animais", "alimento"],
        "photos": [
            ("File:Toxoplasma gondii tissue cyst in mouse brain.jpg", "Cisto tecidual com bradizoítos em cérebro de camundongo (imagem experimental do CDC/USDA)"),
            ("File:Toxoplasmosis immuno.jpg", "Biópsia cerebral em paciente com HIV: parasitas marcados pela imuno-histoquímica", "IHQ anti-Toxoplasma"),
            ("File:Toxoplasmosis - ihc - high mag.jpg", "Encefalite toxoplásmica: organismos em marrom na imuno-histoquímica", "IHQ anti-Toxoplasma"),
        ],
    },
    {
        "id": "schistosoma",
        "name": "Schistosoma mansoni (e outros esquistossomos)",
        "aka": ["Esquistossomose", "Ovos de Schistosoma", "Barriga d'água"],
        "summary": "Ovos de 100–180 µm com casca refringente e espícula (lateral em S. mansoni, terminal em S. haematobium), cercados por granuloma com eosinófilos.",
        "description": "## Morfologia\n- **Ovos** ovais de **100 a 180 µm**, casca refringente e acidófila, muitas vezes calcificados ou vazios; **espícula lateral** em S. mansoni, **terminal** em S. haematobium, rudimentar em S. japonicum.\n- **Granuloma** epitelioide com **eosinófilos** ao redor de cada ovo; fibrose concêntrica nas lesões antigas; pigmento esquistossomótico (hemozoína) em macrófagos.\n- Vermes adultos nos vasos mesentéricos raramente aparecem no corte.\n\n## Diferenciais\n- Outros ovos de helmintos em tecido (Ascaris, Enterobius): tamanho, casca e ausência de espícula.\n- Corpo estranho calcificado: procure a casca e a espícula, gire o foco.\n\n## Contexto\n- Endêmica no Nordeste e em Minas Gerais; contato com água doce com caramujos.\n- Fibrose periportal de Symmers, hipertensão portal; pólipos e ovos no reto e no cólon; S. haematobium na bexiga (carcinoma escamoso).",
        "traits": ["ovo", "espicula", "granuloma", "pigmentado"],
        "sites": ["intestino", "figado", "trato-urinario", "colo-uterino", "apendice", "pulmao"],
        "clinical": ["zona-rural", "agua", "cronico", "imunocompetente", "viagem"],
        "photos": [
            ("File:Schistosoma - very high mag.jpg", "Ovos calcificados na mucosa do cólon", "HE"),
            ("File:Schistosoma - high mag.jpg", "Ovos na mucosa colônica, com reação inflamatória ao redor", "HE"),
            ("File:Schistosoma bladder histopathology.jpeg", "Bexiga: ovos de S. haematobium com infiltrado rico em eosinófilos", "HE"),
        ],
    },
    {
        "id": "strongyloides",
        "name": "Strongyloides stercoralis",
        "aka": ["Estrongiloidíase", "Hiperinfecção", "Larva rabditoide"],
        "summary": "Larvas e vermes adultos dentro das criptas duodenais; na hiperinfecção, larvas filarioides em pulmão, parede intestinal e outros órgãos.",
        "description": "## Morfologia\n- **Fêmeas partenogenéticas e ovos embrionados** nas criptas do duodeno e jejuno, com **larvas rabditoides** eclodindo na mucosa.\n- Eosinofilia tecidual, edema e atrofia vilositária variáveis; pode ser mínima.\n- Na **hiperinfecção**, larvas **filarioides** atravessam a parede intestinal, os vasos e chegam ao pulmão (hemorragia alveolar), fígado, SNC — com bactérias entéricas a reboque.\n\n## Diferenciais\n- Outros nematódeos em corte (Enterobius, Ascaris): localização (luz vs. criptas) e cutícula.\n- Corte tangencial de cripta ou de vaso.\n\n## Contexto\n- Autoinfecção mantém a parasitose por décadas; **corticoide**, HTLV-1, transplante e quimioterapia disparam a hiperinfecção.\n- Rastreie antes de imunossuprimir; eosinofilia periférica pode faltar.",
        "traits": ["larva", "verme", "ovo"],
        "sites": ["intestino", "estomago", "pulmao", "pele"],
        "clinical": ["corticoide", "transplante", "imunossuprimido", "zona-rural", "cronico"],
        "photos": [
            ("File:Strongyloides - high mag.jpg", "Larvas e vermes nas criptas duodenais", "HE"),
            ("File:Strongyloides - very high mag.jpg", "Corte de larva dentro da cripta", "HE"),
            ("File:Duodenum Strongyloides 40x3.JPG", "Duodeno: larva na cripta, 40×", "HE"),
        ],
    },
    {
        "id": "enterobius",
        "name": "Enterobius vermicularis",
        "aka": ["Oxiúro", "Oxiuríase", "Pinworm"],
        "summary": "Verme fino na luz do apêndice, reconhecido em corte pelas duas alas laterais (asas) da cutícula; os ovos são achatados de um lado.",
        "description": "## Morfologia\n- Verme de **2 a 13 mm**, na **luz** do apêndice ou do cólon, sem invadir a mucosa.\n- No corte transversal, cutícula com **duas alas laterais** (asas) características e intestino central; fêmeas com útero cheio de **ovos** assimétricos, achatados de um lado (50 × 25 µm).\n- Reação inflamatória ausente ou mínima; ocasionalmente eosinófilos ou granuloma quando o verme morre na parede.\n\n## Diferenciais\n- Strongyloides: nas criptas, muito menor.\n- Trichuris, Ascaris: sem alas laterais, tamanhos diferentes.\n\n## Contexto\n- Achado incidental em apendicectomias, sobretudo em crianças; prurido anal.\n- Migração para vagina, endométrio e peritônio produz granulomas com ovos.",
        "traits": ["verme", "ovo"],
        "sites": ["apendice", "intestino", "anus", "genital", "colo-uterino"],
        "clinical": ["crianca", "imunocompetente", "agudo"],
        "photos": [
            ("File:Enterobius - high mag.jpg", "Verme na luz do apêndice: as alas laterais são a assinatura", "HE"),
            ("File:Enterobius - very high mag.jpg", "Detalhe do corte transversal do verme", "HE"),
            ("File:Oxyuriasis of the appendix vermiformis, HE 02.jpg", "Corte de oxiúro na luz apendicular", "HE"),
            ("File:Enterobius in the lumen of appendix.jpg", "Apêndice em pequeno aumento com o verme na luz", "HE"),
        ],
    },
    {
        "id": "echinococcus",
        "name": "Echinococcus granulosus",
        "aka": ["Cisto hidático", "Hidatidose", "Equinococose"],
        "summary": "Cisto com membrana laminada acelular em camadas, camada germinativa interna e protoescólices com ganchos; pericisto fibroso do hospedeiro.",
        "description": "## Morfologia\n- **Membrana laminada**: acelular, eosinofílica, em camadas concêntricas, **PAS-positiva** — o achado mais constante, mesmo em cistos mortos e calcificados.\n- **Camada germinativa** fina por dentro, com **cápsulas prolígeras** e **protoescólices** (com ganchos refringentes, birrefringentes).\n- **Pericisto**: fibrose e inflamação do hospedeiro, com eosinófilos e células gigantes.\n- Areia hidática no líquido: ganchos e protoescólices.\n\n## Diferenciais\n- Cisto simples ou abscesso: sem membrana laminada.\n- Cisticerco: parede celular fina, escólex único, sem membrana laminada.\n\n## Contexto\n- Cão–ovino; endêmico no Rio Grande do Sul, Uruguai, Argentina.\n- Fígado e pulmão; ruptura causa anafilaxia e disseminação.",
        "traits": ["membrana-laminada", "cisto", "pas", "granuloma"],
        "sites": ["figado", "pulmao", "osso", "snc", "pleura"],
        "clinical": ["animais", "zona-rural", "cronico", "viagem"],
        "photos": [
            ("File:Echinococcus (hydatid) cyst - Laminated membrane Case 193 (5998594417).jpg", "Membrana laminada acelular, em camadas, de cisto hidático de pulmão", "HE"),
            ("File:Histopathology of Echinococcus granulosus hydatid cyst in a sheep 09G0016 lores.jpg", "Pericisto fibroso, ectocisto hialino e cápsulas prolígeras com protoescólices (cisto em ovino, CDC)", "HE"),
            ("File:Echinococcus (hydatid) cyst Case 193 (5998594589).jpg", "Panorâmica: parede do cisto à esquerda, conteúdo à direita", "HE"),
        ],
    },
    {
        "id": "trichinella",
        "name": "Trichinella spiralis",
        "aka": ["Triquinose", "Triquinelose"],
        "summary": "Larva enrolada dentro de uma fibra muscular esquelética transformada em célula-nutridora, com cápsula e infiltrado eosinofílico.",
        "description": "## Morfologia\n- **Larva** de ~1 mm **enrolada em espiral** dentro da fibra muscular, que perde as estrias e vira **célula-nutridora** com núcleos vesiculosos.\n- Cápsula hialina ao redor; infiltrado de eosinófilos e linfócitos; calcificação nas lesões antigas.\n- Músculos mais ativos: diafragma, língua, masseter, intercostais.\n\n## Diferenciais\n- Cisticerco: muito maior, com escólex.\n- Sarcocystis: bradizoítos numerosos e pequenos, sem larva.\n\n## Contexto\n- Carne de porco ou de caça malcozida; febre, mialgia, edema periorbitário, eosinofilia.\n- Rara no Brasil; surtos ligados a carne de javali e de caça.",
        "traits": ["larva", "verme", "cisto"],
        "sites": ["musculo"],
        "clinical": ["alimento", "agudo", "imunocompetente"],
        "photos": [
            ("File:Trichinella spiralis in muscle tissue (265 16) In skeletal (striated) muscle tissue.jpg", "Larva enrolada dentro da fibra muscular esquelética", "HE"),
            ("File:Trichinella spiralis.jpg", "Complexo célula-nutridora–larva", "HE"),
        ],
    },
    {
        "id": "helicobacter",
        "name": "Helicobacter pylori",
        "aka": ["H. pylori", "Gastrite por Helicobacter"],
        "summary": "Bacilos curvos ou em S, de 3 µm, no muco sobre o epitélio foveolar e dentro das fovéolas; gastrite crônica ativa com plasmócitos e neutrófilos.",
        "description": "## Morfologia\n- Bacilos **curvos, em S ou em gaivota**, de **2 a 4 µm**, no **muco da superfície** e no interior das fovéolas, sem invadir; aderidos ao epitélio.\n- Gastrite **crônica ativa**: plasmócitos na lâmina própria, neutrófilos no epitélio; folículos linfoides; metaplasia intestinal e atrofia com o tempo.\n- HE mostra quando são muitos; **Giemsa modificado**, **Warthin-Starry** e **imuno-histoquímica** para os casos duvidosos ou pós-tratamento.\n- H. heilmannii: espiralado, mais longo (5–10 µm), mais raro.\n\n## Diferenciais\n- Restos de muco e debris: a bactéria tem forma definida e fica sempre no muco, não solta no lúmen.\n- Após inibidor de bomba, migra para o corpo e para dentro das glândulas.\n\n## Contexto\n- Úlcera péptica, adenocarcinoma gástrico e linfoma MALT.",
        "traits": ["bacilo", "giemsa", "warthin-starry", "ihq"],
        "sites": ["estomago", "esofago", "intestino"],
        "clinical": ["cronico", "imunocompetente"],
        "photos": [
            ("File:Helicobacter pylori, Gastric Biopsy, Giemsa Stain (5517582111).jpg", "Bacilos curvos no muco superficial, corados em azul pelo Giemsa modificado", "Giemsa"),
            ("File:Helicobacter Pylori, Stomach Biopsy, Giemsa Stain (5435867593).jpg", "Biópsia gástrica: bacilos na superfície e nas fovéolas", "Giemsa"),
            ("File:Pylorigastritis.jpg", "Colonização da superfície do epitélio regenerativo", "Warthin-Starry"),
        ],
    },
    {
        "id": "mycobacterium-leprae",
        "name": "Mycobacterium leprae",
        "aka": ["Hanseníase", "Lepra", "Bacilo de Hansen"],
        "summary": "Bacilos álcool-ácido resistentes em globias dentro de macrófagos espumosos (Virchow) no polo virchowiano; granulomas em torno de nervos e raros bacilos no tuberculoide.",
        "description": "## Morfologia\n- **Polo virchowiano (LL)**: derme cheia de **macrófagos espumosos (células de Virchow)** sob uma **faixa de Grenz** subepidérmica; **bacilos numerosos, em globias**, no **Fite-Faraco** (o Ziehl comum descora o M. leprae).\n- **Polo tuberculoide (TT)**: granulomas epitelioides bem formados, **alongados ao redor de nervos e anexos**, poucos ou nenhum bacilo.\n- Formas dimorfas no meio do espectro. **Nervo** com inflamação e destruição é a pista.\n- Hanseníase histoide: nódulos fusocelulares com muitos bacilos.\n\n## Diferenciais\n- Sarcoidose, tuberculose cutânea, leishmaniose: pense em hanseníase sempre que houver granuloma perineural ou infiltrado espumoso — e peça o Fite.\n- Xantoma: espumosos sem bacilos.\n\n## Contexto\n- Brasil é o segundo país em casos; lesões hipocrômicas com perda de sensibilidade, espessamento de nervos.",
        "traits": ["baar", "bacilo", "granuloma", "intracelular"],
        "sites": ["pele", "nervo", "nasofaringe", "olho"],
        "clinical": ["cronico", "imunocompetente", "zona-rural"],
        "photos": [
            ("File:Leprosy - Lepromatous (LL) Wade Fite stain.jpg", "Hanseníase virchowiana: numerosos bacilos álcool-ácido resistentes", "Fite-Faraco (Wade-Fite)"),
            ("File:Leprosy Wade Fite stain 100x.jpg", "Bacilos em globias dentro de macrófagos", "Fite-Faraco (Wade-Fite)"),
            ("File:Lepromatous leprosy histoid leprosy Wellcome W0043391.jpg", "Hanseníase histoide: macrófagos sob a faixa de Grenz repletos de BAAR", "Fite-Faraco (Wade-Fite)"),
            ("File:Lepromatous leprosy.jpg", "HE: epiderme atrófica, faixa de Grenz e macrófagos espumosos (células de Virchow)", "HE"),
        ],
    },
    {
        "id": "actinomyces",
        "name": "Actinomyces",
        "aka": ["Actinomicose", "Grânulos de enxofre"],
        "summary": "Colônias basofílicas de filamentos ramificados (grânulos de enxofre) com borda eosinofílica de Splendore-Hoeppli, dentro de abscessos.",
        "description": "## Morfologia\n- **Grânulos de enxofre**: colônias de **50 a 300 µm**, basofílicas, com **filamentos finos ramificados** que se irradiam para a periferia, onde ganham um manto eosinofílico (**Splendore-Hoeppli**).\n- Cercadas por **neutrófilos**, abscessos e fibrose; fístulas.\n- **Gram-positivos**, Grocott positivo, **não são álcool-ácido resistentes** (diferença de Nocardia).\n\n## Diferenciais\n- Nocardia: filamentos soltos, sem colônia, fracamente ácido-resistentes (Fite).\n- Botriomicose: colônias de cocos (Staphylococcus) com o mesmo manto eosinofílico — o Gram mostra cocos, não filamentos.\n- Micetoma: grão maior, na pele do pé, com hifas (eumicetoma) ou filamentos (actinomicetoma).\n- Colônias em criptas amigdalianas e no apêndice são comensais: só diagnostique actinomicose com invasão e supuração.\n\n## Contexto\n- Cervicofacial (pós-extração dentária), torácica, abdominal (apêndice, ceco), pélvica em usuária de **DIU**.",
        "traits": ["filamentoso", "grao", "splendore", "bacilo", "grocott", "citologia"],
        "sites": ["mucosa-oral", "pulmao", "intestino", "apendice", "genital", "colo-uterino"],
        "clinical": ["diu", "cronico", "imunocompetente"],
        "photos": [
            ("File:Actinomyces - very high mag.jpg", "Grânulo de enxofre na mandíbula: filamentos em paliçada na periferia", "HE"),
            ("File:Actinomyces - high mag.jpg", "Colônia com borda eosinofílica (Splendore-Hoeppli)", "HE"),
            ("File:Actinomycosis (5287905500).jpg", "Colônia de Actinomyces dentro de abscesso pulmonar", "HE"),
        ],
    },
    {
        "id": "nocardia",
        "name": "Nocardia",
        "aka": ["Nocardiose"],
        "summary": "Filamentos finos (1 µm), ramificados e fragmentados, soltos em abscessos; Gram-positivos, Grocott-positivos e fracamente ácido-resistentes no Fite.",
        "description": "## Morfologia\n- Filamentos **finos (~1 µm), ramificados em ângulo reto, em contas**, soltos no pus — **não formam colônias** como Actinomyces.\n- Quase invisíveis no HE; **Gram** e **Grocott** mostram; **Fite-Faraco** (ácido-resistência fraca) confirma.\n- Abscessos com necrose supurativa e tecido de granulação; pouca reação granulomatosa.\n\n## Diferenciais\n- Actinomyces: colônias com Splendore-Hoeppli, Fite negativo.\n- Mycobacterium: bacilos curtos, sem ramificação verdadeira, Ziehl forte.\n- Micetoma por Nocardia brasiliensis: grãos na pele do pé.\n\n## Contexto\n- Pulmão e cérebro em transplantados, corticoterapia, aids; nocardiose cutânea após inoculação em imunocompetente.",
        "traits": ["filamentoso", "bacilo", "baar", "grocott"],
        "sites": ["pulmao", "snc", "pele", "partes-moles"],
        "clinical": ["transplante", "corticoide", "imunossuprimido", "trauma", "imunocompetente"],
        "photos": [
            ("File:Nocardiosis - Gram stain Case 149 (5286067518).jpg", "Filamentos finos, ramificados, Gram-positivos; sem colônias, ao contrário de Actinomyces", "Gram"),
            ("File:Nocardiosis Case 149 (5285470445).jpg", "Microabscesso cercado por tecido de granulação e fibrose — o padrão da nocardiose", "HE"),
        ],
    },
    {
        "id": "cmv",
        "name": "Citomegalovírus (CMV)",
        "aka": ["Inclusão em olho de coruja", "Citomegalia"],
        "summary": "Célula aumentada (citomegálica) com inclusão intranuclear grande, basofílica ou anfofílica, cercada de halo, e grânulos citoplasmáticos; endotélio, epitélio e estroma.",
        "description": "## Morfologia\n- Célula **2 a 4 vezes maior** que as vizinhas, com **inclusão intranuclear** única, grande, com **halo claro** (olho de coruja) e, com frequência, **inclusões citoplasmáticas granulares** basofílicas.\n- Infecta **células endoteliais, estromais e epiteliais** — procure na base das úlceras e nos vasos, não na superfície.\n- Inflamação variável; úlceras no tubo digestivo, pneumonite intersticial, hepatite, retinite.\n- **Imuno-histoquímica** para os casos com poucas células.\n\n## Diferenciais\n- Herpes: multinucleação, moldagem, inclusões em células escamosas superficiais.\n- Adenovírus: inclusão que apaga o núcleo (smudge cell), sem citomegalia.\n- Células de reparo ou de Reed-Sternberg: nucléolo, não inclusão com halo.\n\n## Contexto\n- Transplante, HIV com CD4 baixo, doença inflamatória intestinal em corticoide, infecção congênita.",
        "traits": ["inclusao-nuclear", "inclusao-citoplasmatica", "ihq"],
        "sites": ["intestino", "esofago", "pulmao", "placenta", "snc", "figado", "olho", "rim"],
        "clinical": ["hiv", "transplante", "imunossuprimido", "corticoide", "agudo"],
        "photos": [
            ("File:Cytomegalovirus 01.jpg", "Pneumócito citomegálico com inclusão intranuclear e halo", "HE"),
            ("File:Cytomegalovirus infection - Case 301 (35104826390).jpg", "Pneumócitos infectados: inclusão nuclear basofílica com halo e grânulos citoplasmáticos", "HE"),
            ("File:CMV encephalitis owl eye inclusions HE stain.jpg", "Encefalite congênita: células em olho de coruja", "HE"),
        ],
    },
    {
        "id": "hsv",
        "name": "Herpes simples (HSV 1 e 2)",
        "aka": ["Herpes", "Inclusão de Cowdry A", "Varicela-zóster (mesma morfologia)"],
        "summary": "Células escamosas multinucleadas com moldagem nuclear, cromatina marginada e núcleos em vidro fosco; inclusões eosinofílicas de Cowdry A.",
        "description": "## Morfologia\n- Os **3 M**: **multinucleação**, **moldagem** dos núcleos uns contra os outros e **marginação** da cromatina, com núcleos em **vidro fosco**.\n- **Inclusões intranucleares eosinofílicas** (Cowdry tipo A) com halo, em fase posterior.\n- Vesícula intraepidérmica por degeneração balonizante; na esofagite, as células infectadas ficam na **borda da úlcera**, no epitélio escamoso.\n- Varicela-zóster tem morfologia idêntica; separa-se por imuno-histoquímica ou clínica.\n\n## Diferenciais\n- CMV: uma célula grande com uma inclusão, no estroma e no endotélio.\n- Células gigantes de reparo ou pênfigo: sem cromatina marginada nem moldagem.\n\n## Contexto\n- Esofagite em imunossuprimido (e ocasionalmente em imunocompetente), herpes genital e labial, hepatite fulminante, encefalite temporal.",
        "traits": ["inclusao-nuclear", "multinucleacao", "ihq", "citologia"],
        "sites": ["esofago", "pele", "mucosa-oral", "genital", "colo-uterino", "figado", "snc"],
        "clinical": ["imunossuprimido", "hiv", "imunocompetente", "ist", "agudo"],
        "photos": [
            ("File:Herpes esophagitis - very high mag.jpg", "Os 3 M: marginação da cromatina, multinucleação e moldagem nuclear", "HE"),
            ("File:Herpes simplex infection Case 160 (5442479825).jpg", "Células multinucleadas com inclusões eosinofílicas de Cowdry tipo A", "HE"),
            ("File:Herpetic Esophagitis (49860361728).jpg", "Esofagite herpética em paciente sem imunossupressão conhecida", "HE"),
        ],
    },
    {
        "id": "hpv",
        "name": "Papilomavírus humano (HPV)",
        "aka": ["Coilócito", "Condiloma acuminado", "LSIL", "Verruga"],
        "summary": "Coilócitos: células escamosas maduras com halo perinuclear amplo e bem delimitado, núcleo aumentado, hipercromático e enrugado, às vezes binucleado.",
        "description": "## Morfologia\n- **Coilócito**: célula escamosa intermediária ou superficial com **cavidade perinuclear** ampla de borda nítida, citoplasma periférico denso, **núcleo aumentado, hipercromático, de contorno irregular (passa)**, com frequência **binucleação**.\n- Condiloma: papilomatose, acantose, paraceratose e coilocitose nas camadas altas.\n- Verruga vulgar: hiperceratose com paraceratose em colunas e grânulos de querato-hialina grosseiros.\n- Imuno-histoquímica para **p16** marca em bloco as lesões de alto grau (HPV de alto risco).\n\n## Diferenciais\n- Halo de glicogênio (célula navicular): borda difusa, núcleo normal.\n- Atrofia e reparo: sem hipercromasia com halo.\n\n## Contexto\n- IST mais prevalente; rastreio com Papanicolaou; HPV 16 e 18 e o carcinoma do colo, ânus, orofaringe.",
        "traits": ["coilocito", "citologia", "ihq", "multinucleacao"],
        "sites": ["colo-uterino", "genital", "anus", "pele", "mucosa-oral"],
        "clinical": ["ist", "hiv", "imunocompetente", "cronico"],
        "photos": [
            ("File:HPV-Infected Squamous Cell (Koilocyte) of the Cervix (44001403165).jpg", "Coilócito em citologia cervical: halo perinuclear amplo e núcleo aumentado, hipercromático", "Papanicolaou"),
            ("File:Condyloma acuminatum - very high mag.jpg", "Condiloma acuminado: coilócitos nas camadas superiores", "HE"),
            ("File:Condyloma acuminatum - high mag.jpg", "Condiloma: papilomatose com coilocitose", "HE"),
        ],
    },
    {
        "id": "molluscum",
        "name": "Molusco contagioso (poxvírus)",
        "aka": ["Corpos de Henderson-Paterson", "Corpos de molusco"],
        "summary": "Lóbulos epidérmicos invertidos, em cratera, cheios de queratinócitos com inclusões citoplasmáticas eosinofílicas enormes (corpos de Henderson-Paterson).",
        "description": "## Morfologia\n- Lesão **crateriforme** com lóbulos de epiderme hiperplásica voltados para a derme.\n- **Corpos de Henderson-Paterson**: inclusões **citoplasmáticas** eosinofílicas de até 35 µm que comprimem o núcleo para a periferia; ficam basofílicas nas camadas superiores e são eliminadas pelo poro central.\n- Inflamação escassa, exceto na lesão em regressão (infiltrado denso, às vezes granulomatoso).\n\n## Diferenciais\n- Verruga: inclusões intranucleares e grânulos de querato-hialina, sem corpos de molusco.\n- Cisto epidérmico rompido e criptococose cutânea (pápula umbilicada em HIV): morfologia diferente.\n\n## Contexto\n- Crianças (tronco, face), adultos por contato sexual (genital), lesões grandes e numerosas em HIV.",
        "traits": ["inclusao-citoplasmatica"],
        "sites": ["pele", "genital"],
        "clinical": ["crianca", "hiv", "ist", "imunocompetente"],
        "photos": [
            ("File:Molluscum contagiosum, very high mag.jpg", "Lesão crateriforme com inclusões citoplasmáticas eosinofílicas (corpos de Henderson-Paterson)", "HE"),
            ("File:Low magnification micrograph of a molluscum contagiosum lesion.jpg", "Lóbulos epidérmicos invertidos, em pequeno aumento", "HE"),
            ("File:Molluscum Contagiosum 1.jpg", "Biópsia de pele das costas de uma menina de 13 anos", "HE"),
        ],
    },
    {
        "id": "giardia",
        "name": "Giardia lamblia (G. duodenalis)",
        "aka": ["Giardíase"],
        "summary": "Trofozoítos piriformes, em pera ou em foice, na luz entre as vilosidades duodenais, sem invadir; a mucosa pode ser normal.",
        "description": "## Morfologia\n- **Trofozoítos** de **10 a 15 µm**, **piriformes** de frente (dois núcleos, \"cara de coruja\") e **em foice ou meia-lua** de perfil, soltos na luz, entre as vilosidades e nas criptas.\n- **Não invadem**: a mucosa pode ser normal ou ter atrofia vilositária parcial e linfocitose intraepitelial discreta.\n- Giemsa e imuno-histoquímica ajudam quando são poucos.\n\n## Diferenciais\n- Muco e debris celulares: o trofozoíto tem contorno definido e núcleos pareados.\n- Doença celíaca: mesma atrofia, sem organismos.\n\n## Contexto\n- Água contaminada, creches; deficiência de IgA e imunodeficiência comum variável prolongam a infecção.",
        "traits": ["trofozoito", "giemsa", "citologia"],
        "sites": ["intestino"],
        "clinical": ["agua", "crianca", "imunossuprimido", "imunocompetente"],
        "photos": [
            ("File:Giardiasis duodenum high.jpg", "Trofozoítos piriformes e em foice na luz, entre as vilosidades — sem invadir", "HE"),
            ("File:Giardiasis duodenum low.jpg", "Biópsia duodenal: organismos na superfície da mucosa", "HE"),
        ],
    },
    {
        "id": "demodex",
        "name": "Demodex folliculorum / brevis",
        "aka": ["Demodicose", "Ácaro do folículo"],
        "summary": "Ácaros alongados, de 0,1–0,4 mm, com exoesqueleto refringente e pernas curtas, dentro do infundíbulo folicular e das glândulas sebáceas.",
        "description": "## Morfologia\n- Ácaro **alongado, em charuto**, com cutícula eosinofílica refringente, estriações e **quatro pares de pernas curtas** na porção anterior; vários por folículo.\n- D. folliculorum no **infundíbulo**, D. brevis na **glândula sebácea**.\n- Achado incidental na maioria das biópsias faciais; inflamação perifolicular e granulomas quando o folículo rompe (demodicose, rosácea).\n\n## Diferenciais\n- Sarcoptes: na camada córnea, não no folículo, corpo arredondado.\n- Fragmento de pelo em corte: sem estrutura interna nem pernas.\n\n## Contexto\n- Face de adultos; blefarite; formas inflamatórias em imunossuprimidos.",
        "traits": ["artropode"],
        "sites": ["pele"],
        "clinical": ["imunocompetente", "cronico"],
        "photos": [
            ("File:Demodex folliculorum - Skin (52260322640).jpg", "Ácaros dentro do folículo piloso (legendas do autor)", "HE"),
            ("File:Demodex, HE 3.JPG", "Demodex no infundíbulo folicular", "HE"),
            ("File:Demodex Infestation - Skin (50196389113).jpg", "Vários ácaros num folículo", "HE"),
        ],
    },
    {
        "id": "sarcoptes",
        "name": "Sarcoptes scabiei",
        "aka": ["Escabiose", "Sarna"],
        "summary": "Ácaro arredondado (0,3–0,4 mm), ovos e cíbalas (fezes) dentro de túneis na camada córnea, com espongiose e eosinófilos na derme.",
        "description": "## Morfologia\n- **Túnel na camada córnea** com o **ácaro** (corpo arredondado com cutícula estriada, espinhos dorsais, pernas curtas), **ovos** ovais e **cíbalas** marrons.\n- Espongiose, exocitose de eosinófilos e infiltrado dérmico perivascular rico em eosinófilos.\n- **Sarna crostosa (norueguesa)**: hiperceratose maciça com centenas de ácaros — imunossuprimido, idoso institucionalizado.\n- \"Pink pigtails\": fragmentos espiralados de cutícula na camada córnea, pista quando o ácaro não aparece.\n\n## Diferenciais\n- Demodex: dentro do folículo.\n- Dermatite eosinofílica sem ácaro: pense em escabiose e corte mais níveis.\n\n## Contexto\n- Prurido noturno, espaços interdigitais, punhos, genitália; contato domiciliar.",
        "traits": ["artropode", "ovo"],
        "sites": ["pele"],
        "clinical": ["imunocompetente", "imunossuprimido", "crianca", "cronico"],
        "photos": [
            ("File:Skin - Scabies (49415528603).jpg", "Ácaro no interior da camada córnea", "HE"),
            ("File:Sarcoptes scabiei - Scabies - Skin (51944966705).png", "Túnel na camada córnea com ácaro e ovos", "HE"),
            ("File:Scabies - Skin (50839107751).jpg", "Fêmea com ovos na camada córnea", "HE"),
        ],
    },
    {
        "id": "tunga",
        "name": "Tunga penetrans",
        "aka": ["Bicho-de-pé", "Tungíase"],
        "summary": "Pulga fêmea encravada na epiderme do pé: cavidade com exoesqueleto quitinoso, ovos, traqueias e intestino, cercada de hiperplasia epidérmica e inflamação.",
        "description": "## Morfologia\n- Fêmea grávida (**até 1 cm**) dentro de uma cavidade na epiderme/derme superficial, com **cutícula quitinosa eosinofílica espessa**, **ovos** ovais de ~600 µm, **anéis traqueais** e intestino.\n- Hiperplasia pseudoepiteliomatosa ao redor, infiltrado misto com eosinófilos, infecção bacteriana secundária.\n- Fragmentos de cutícula e ovos são a assinatura quando a pulga foi parcialmente removida.\n\n## Diferenciais\n- Miíase: larva maior, com espinhos cuticulares e musculatura, sem ovos.\n- Cisto epidérmico: sem estruturas do artrópode.\n\n## Contexto\n- Praia, chiqueiro, solo arenoso; pés descalços; periungueal.",
        "traits": ["artropode", "ovo"],
        "sites": ["pele"],
        "clinical": ["areia", "zona-rural", "imunocompetente", "animais"],
        "photos": [
            ("File:Tungiasis - Tunga penetrans - Skin (51217862287).jpg", "Pulga fêmea encravada na epiderme: exoesqueleto, ovos e traqueias", "HE"),
            ("File:Tungiasis - Tunga penetrans - Skin (51912582184).jpg", "Tungíase: lesão clínica e histologia com os ovos", "HE"),
            ("File:Tungiasis - Skin (52114946071).jpg", "Cavidade epidérmica ocupada pela pulga", "HE"),
        ],
    },
    {
        "id": "malassezia",
        "name": "Malassezia (M. furfur, M. globosa)",
        "aka": ["Pitiríase versicolor", "Tinea versicolor", "Espaguete com almôndegas"],
        "summary": "Leveduras redondas em cachos e hifas curtas, grossas e curvas, restritas à camada córnea: \"espaguete com almôndegas\"; sem invasão nem inflamação.",
        "description": "## Morfologia\n- **Leveduras** de 3 a 8 µm, em **cachos**, e **hifas curtas, curvas, septadas**, todas dentro da **camada córnea** — \"espaguete com almôndegas\".\n- Epiderme e derme quase normais; hiperceratose discreta.\n- Visíveis no HE, óbvias no PAS.\n- Foliculite por Malassezia: leveduras (sem hifas) dentro do folículo dilatado com inflamação.\n\n## Diferenciais\n- Dermatófitos: hifas longas e artroconídios, sem leveduras em cacho.\n- Candida: pseudo-hifas e neutrófilos.\n\n## Contexto\n- Máculas hipo ou hipercrômicas no tronco em clima quente; comensal da pele oleosa.",
        "traits": ["brotamento", "hifa-verdadeira", "pas", "grocott"],
        "sites": ["pele"],
        "clinical": ["imunocompetente", "cronico"],
        "photos": [
            ("File:Malassezia furfur in skin scale from a patient with tinea versicolor PHIL 3938 lores.jpg", "Escamas com KOH: leveduras e hifas curtas — 'espaguete com almôndegas'", "KOH (exame direto)"),
        ],
    },
    {
        "id": "tropheryma",
        "name": "Tropheryma whipplei",
        "aka": ["Doença de Whipple"],
        "summary": "Lâmina própria do intestino delgado ocupada por macrófagos espumosos com material PAS-positivo diastase-resistente granular; vacúolos lipídicos e linfáticos dilatados.",
        "description": "## Morfologia\n- Vilosidades alargadas por **macrófagos espumosos** cheios de bacilos degenerados: material **PAS-positivo, diastase-resistente**, granular ou em foice.\n- **Vacúolos lipídicos** extracelulares e linfáticos dilatados na lâmina própria.\n- **Ziehl-Neelsen negativo** — diferencia de Mycobacterium avium, que dá os mesmos macrófagos PAS-positivos mas é BAAR-positivo.\n- Imuno-histoquímica e PCR confirmam.\n\n## Diferenciais\n- Mycobacterium avium-intracellulare (HIV): Ziehl positivo.\n- Histoplasmose, Rhodococcus, malacoplaquia: PAS positivo também — o contexto e as colorações especiais separam.\n\n## Contexto\n- Homem branco de meia-idade, artralgia migratória de anos, diarreia, emagrecimento; endocardite e neurológico.",
        "traits": ["intracelular", "bacilo", "pas"],
        "sites": ["intestino", "linfonodo", "snc", "coracao"],
        "clinical": ["cronico", "imunocompetente"],
        "photos": [
            ("File:Whipple's disease - PAS stain.jpg", "Lâmina própria duodenal ocupada por macrófagos PAS-positivos", "PAS"),
            ("File:Whipples Disease, PAS (6881958781).jpg", "Macrófagos espumosos PAS-positivos nas vilosidades", "PAS"),
        ],
    },
    {
        "id": "treponema",
        "name": "Treponema pallidum",
        "aka": ["Sífilis", "Cancro duro", "Lues"],
        "summary": "Espiroquetas finas e espiraladas, invisíveis no HE, evidenciadas por imuno-histoquímica ou Warthin-Starry; endarterite com plasmócitos é a pista.",
        "description": "## Morfologia\n- Espiroqueta de **6 a 15 µm**, espirais regulares, **não se vê no HE**: peça **imuno-histoquímica anti-T. pallidum** (sensível e limpa) ou **Warthin-Starry**.\n- Distribuição: **epiderme (camadas baixas), ao redor de vasos e anexos** na sífilis secundária; no cancro, na base da úlcera.\n- Padrão histológico sugestivo: **plasmócitos** abundantes, **endarterite** com endotélio túrgido, infiltrado liquenoide ou psoriasiforme, granulomas no terciário.\n\n## Diferenciais\n- Outras espiroquetas: Borrelia, treponemas comensais da boca (o anti-T. pallidum cruza com eles — cuidado na mucosa oral).\n- Fibras reticulínicas no Warthin-Starry imitam espiroquetas: a IHQ é melhor.\n\n## Contexto\n- Em ascensão; coinfecção com HIV; qualquer dermatose com plasmócitos merece a pergunta.",
        "traits": ["espiroqueta", "ihq", "warthin-starry"],
        "sites": ["pele", "mucosa-oral", "genital", "linfonodo", "placenta", "anus"],
        "clinical": ["ist", "hiv", "agudo", "cronico"],
        "photos": [
            ("File:Secondary syphilis spirochete epidermis.jpg", "Sífilis secundária: espiroquetas em vermelho na epiderme", "IHQ anti-T. pallidum"),
            ("File:Secondary syphilis spirochete eccrine ducts high power.jpg", "Espiroquetas ao redor dos ductos écrinos", "IHQ anti-T. pallidum"),
        ],
    },
    {
        "id": "alternaria",
        "name": "Alternaria (contaminante)",
        "aka": ["Conídios de Alternaria", "Fungo do ar"],
        "summary": "Macroconídios marrons, multicelulares, em forma de raquete de neve ou clava, com septos transversais e longitudinais; contaminante do ar em esfregaços.",
        "description": "## Morfologia\n- **Macroconídios** de **20 a 60 µm**, **marrons** (demáceos), em **raquete de neve** ou clava, com **septos transversais e longitudinais** (muriformes) e um bico apical.\n- Aparecem soltos, sem reação inflamatória, em esfregaços de Papanicolaou, lavados e lâminas que ficaram abertas.\n- Feo-hifomicose verdadeira por Alternaria existe (cisto subcutâneo em imunossuprimido): hifas pigmentadas dentro do tecido, com granuloma.\n\n## Diferenciais\n- Corpos escleróticos da cromoblastomicose: menores, redondos, dentro da derme com inflamação.\n- Pólen e outros conídios (Helminthosporium, Curvularia): formas diferentes, mesma lição — sem reação, é contaminante.\n\n## Contexto\n- Não laude como infecção: é o mais frequente contaminante fúngico da citologia.",
        "traits": ["esporo", "pigmentado", "citologia"],
        "sites": ["colo-uterino", "pulmao", "pele"],
        "clinical": ["contaminante", "imunossuprimido"],
        "photos": [
            ("File:Alternaria Spp. - Pap smear (52341524740).jpg", "Macroconídios marrons, multicelulares, em raquete de neve, em esfregaço de Papanicolaou", "Papanicolaou"),
        ],
    },
    {
        "id": "carrapato",
        "name": "Carrapato (Ixodes, Amblyomma, Rhipicephalus)",
        "aka": ["Picada de carrapato", "Ixodidae"],
        "summary": "Artrópode grande com hipostômio denteado enterrado na derme, cercado por cimento eosinofílico e infiltrado dérmico com eosinófilos.",
        "description": "## Morfologia\n- **Hipostômio** (peça bucal serrilhada) e quelíceras penetrando a epiderme, com um **cimento** eosinofílico amorfo ao redor; o corpo, quando presente, tem cutícula quitinosa, musculatura e intestino cheio de sangue.\n- Derme com infiltrado misto (eosinófilos, neutrófilos, linfócitos), edema, necrose focal; reação granulomatosa persistente quando as peças bucais ficam retidas (\"granuloma de carrapato\").\n- Pseudolinfoma na picada antiga.\n\n## Diferenciais\n- Outras picadas de artrópodes: sem as peças bucais no corte.\n- Tunga: cavidade epidérmica com ovos.\n\n## Contexto\n- Vetor de febre maculosa (Rickettsia rickettsii, Amblyomma sculptum no Brasil), borreliose e babesiose; zona rural, cavalos e capivaras.",
        "traits": ["artropode"],
        "sites": ["pele"],
        "clinical": ["zona-rural", "animais", "imunocompetente"],
        "photos": [
            ("File:Tick attached to skin (removed by shave biopsy) (51707551449).jpg", "Carrapato aderido à pele em biópsia por shaving: peças bucais na derme (composição do autor)", "HE"),
            ("File:Tick-Skin (51838764781).jpg", "Fêmea de Ixodes penetrando a pele, em biópsia por shaving"),
        ],
    },
    {
        "id": "miiase",
        "name": "Larva de mosca (miíase)",
        "aka": ["Berne", "Dermatobia hominis", "Cochliomyia hominivorax", "Bicheira"],
        "summary": "Larva no subcutâneo com cutícula espessa portando fileiras de espinhos, musculatura estriada e traqueias; cavidade com pus e eosinófilos.",
        "description": "## Morfologia\n- **Larva** de milímetros a 2 cm numa cavidade dérmica/subcutânea, com **cutícula** eosinofílica **espinhosa**, **musculatura estriada**, **traqueias** e tubo digestivo.\n- Reação inflamatória mista, rica em **eosinófilos**, abscesso e tecido de granulação; poro central de respiração na miíase furunculoide.\n\n## Diferenciais\n- Tunga: fêmea com ovos, na epiderme.\n- Cisticerco ou outro parasita: sem cutícula espinhosa nem traqueias.\n\n## Contexto\n- **Berne** (Dermatobia): nódulo furunculoide único, zona rural, gado. **Bicheira** (Cochliomyia): larvas múltiplas em feridas e cavidades, idosos e acamados.",
        "traits": ["artropode", "larva"],
        "sites": ["pele", "partes-moles"],
        "clinical": ["zona-rural", "animais", "trauma", "imunocompetente"],
        "photos": [
            ("File:Myiasis - Skin (51892436737).jpg", "Miíase: larva no tecido, com cutícula e espinhos (composição do autor)", "HE"),
        ],
    },
    {
        "id": "leishmania",
        "name": "Leishmania (amastigotas)",
        "aka": ["Leishmaniose", "Calazar", "Úlcera de Bauru", "Corpúsculos de Leishman-Donovan"],
        "summary": "Amastigotas de 2–4 µm dentro de macrófagos, cada uma com núcleo e um cinetoplasto em barra; Grocott negativo (diferencia de Histoplasma).",
        "description": "## Morfologia\n- **Amastigotas** redondas ou ovais de **2 a 4 µm**, no citoplasma de **macrófagos**, com **núcleo** e um **cinetoplasto** em barra ao lado — o cinetoplasto é o que Histoplasma não tem.\n- Sem cápsula nem halo verdadeiro; **Giemsa** mostra bem nos esfregaços (medula, aspirado de baço, imprint de pele).\n- **Grocott e PAS negativos** (o Histoplasma é positivo).\n- Pele: infiltrado dérmico difuso de macrófagos, plasmócitos e linfócitos, granulomas tuberculoides nas lesões antigas com poucos parasitas.\n\n## Diferenciais\n- Histoplasma: Grocott positivo, sem cinetoplasto.\n- Toxoplasma e Trypanosoma cruzi: veja os verbetes.\n- Hanseníase virchowiana: macrófagos espumosos com BAAR.\n\n## Contexto\n- Tegumentar (L. braziliensis, L. amazonensis) e visceral (L. infantum) endêmicas no Brasil; cão como reservatório urbano; reativação em HIV.",
        "traits": ["intracelular", "giemsa", "citologia", "granuloma"],
        "sites": ["pele", "mucosa-oral", "nasofaringe", "medula", "figado", "linfonodo"],
        "clinical": ["zona-rural", "hiv", "imunocompetente", "cronico", "animais"],
        "photos": [
            ("File:Висцеральный лейшманиоз. Внеклеточное и внутриклеточное расположение лейшманий. Костный мозг. Увеличение 1000.jpg", "Esfregaço de medula óssea, 1000×: amastigotas dentro e ao redor de um macrófago, cada uma com núcleo e cinetoplasto", "Esfregaço (Romanowsky)"),
        ],
    },
    {
        "id": "cromoblastomicose",
        "name": "Fungos da cromoblastomicose (Fonsecaea, Cladophialophora, Phialophora)",
        "aka": ["Cromoblastomicose", "Corpos escleróticos", "Células muriformes", "Corpos de Medlar"],
        "summary": "Corpos escleróticos: células fúngicas redondas, marrons, de parede espessa, com septos em dois planos (muriformes), no meio de granulomas e microabscessos na derme.",
        "description": "## Morfologia\n- **Corpos escleróticos (muriformes, de Medlar)**: células **redondas, de 5 a 12 µm, marrom-douradas**, parede espessa, divididas por **septos transversais e longitudinais** — não brotam.\n- Visíveis **no HE** pela pigmentação; ficam dentro de células gigantes e em microabscessos de neutrófilos.\n- Hiperplasia pseudoepiteliomatosa, eliminação transepidérmica; hifas pigmentadas curtas na superfície.\n\n## Diferenciais\n- Feo-hifomicose: hifas pigmentadas, sem corpos muriformes.\n- Esporotricose e outras micoses com hiperplasia pseudoepiteliomatosa: os corpos escleróticos definem.\n\n## Contexto\n- Trabalhador rural, membros inferiores, ferimento com madeira ou vegetal; lesões verrucosas de anos.",
        "traits": ["pigmentado", "granuloma", "pas", "grocott"],
        "sites": ["pele", "partes-moles"],
        "clinical": ["zona-rural", "trauma", "imunocompetente", "cronico"],
        "photos": [
            ("File:Chromoblastomycosis 40x.jpg", "Corpos escleróticos (muriformes) marrons na derme", "HE"),
            ("File:Chromoblastomycosis 20x.jpg", "Hiperplasia pseudoepiteliomatosa e infiltrado ao redor dos corpos escleróticos", "HE"),
            ("File:Sclerotic Bodies in a KOH Mount of a Skin Scraping from a Chromoblastomycosis Patient.jpg", "Corpos escleróticos em exame direto de raspado com KOH", "KOH (exame direto)"),
        ],
    },
    {
        "id": "lacazia",
        "name": "Lacazia loboi",
        "aka": ["Lobomicose", "Doença de Jorge Lobo", "Blastomicose queloidiana"],
        "summary": "Leveduras grandes (6–12 µm), uniformes, de parede espessa, em cadeias unidas por pontes tubulares, lotando histiócitos na derme sob uma faixa de Grenz.",
        "description": "## Morfologia\n- Leveduras **redondas, uniformes, de 6 a 12 µm**, parede espessa e refringente, em **cadeias** (rosário) conectadas por **pontes estreitas** — brotamento sequencial.\n- Derme preenchida por **histiócitos e células gigantes** repletos de leveduras, com **faixa de Grenz** e epiderme atrófica; fibrose queloidiana.\n- Grocott e PAS realçam; a parede birrefringe à luz polarizada.\n\n## Diferenciais\n- Paracoccidioides: tamanho variável, brotos múltiplos em roda de leme, acomete mucosa e pulmão.\n- Blastomyces: brotamento único de base larga.\n\n## Contexto\n- Amazônia (Brasil, Colômbia), ribeirinhos e golfinhos; nódulos queloidianos de crescimento lento por anos; não cultivável.",
        "traits": ["brotamento", "grocott", "pas", "intracelular"],
        "sites": ["pele"],
        "clinical": ["zona-rural", "cronico", "imunocompetente", "trauma"],
        "photos": [
            ("File:Lobomycosis.jpg", "Derme com faixa de Grenz e infiltrado histiocitário repleto de leveduras (canto inferior direito)", "HE"),
        ],
    },
    {
        "id": "micetoma",
        "name": "Micetoma (eumicetoma e actinomicetoma)",
        "aka": ["Pé de Madura", "Maduromicose", "Grãos de micetoma"],
        "summary": "Grãos de 0,2–3 mm dentro de microabscessos no subcutâneo do pé, com manto de Splendore-Hoeppli; hifas largas nos eumicetomas, filamentos finos nos actinomicetomas.",
        "description": "## Morfologia\n- **Grãos** (grânulos) de **0,2 a 3 mm** no centro de **microabscessos** de neutrófilos, cercados por tecido de granulação e fibrose; fístulas que drenam os grãos.\n- **Eumicetoma** (fungos: Madurella, Scedosporium): grão de **hifas largas (2–6 µm)** com clamidoconídios na periferia; **grãos pretos** em Madurella.\n- **Actinomicetoma** (Nocardia brasiliensis, Actinomadura, Streptomyces): grão de **filamentos finos (~1 µm)**, borda em franja.\n- **Splendore-Hoeppli** ao redor de ambos. Grocott e Gram separam os dois.\n\n## Diferenciais\n- Actinomicose: grãos menores, sem a topografia do pé, sem fístulas cutâneas múltiplas.\n- Botriomicose: cocos.\n\n## Contexto\n- Ferimento com espinho ou madeira no pé, zona rural, semiárido; tumefação com fístulas de anos. O tipo (fúngico ou bacteriano) decide o tratamento.",
        "traits": ["grao", "splendore", "hifa-verdadeira", "filamentoso", "grocott", "pigmentado"],
        "sites": ["pele", "partes-moles", "osso"],
        "clinical": ["zona-rural", "trauma", "cronico", "imunocompetente"],
        "photos": [
            ("File:Actinomycotic Mycetoma, Foot (2111203060).jpg", "Actinomicetoma do pé: microabscessos, cada um com o seu grão", "HE"),
            ("File:Actinomycotic Mycetoma, Foot (2111203428).jpg", "Grão de actinomicetoma com manto de Splendore-Hoeppli", "HE"),
            ("File:Eumycotic Mycetoma, GMS over H&E (10191064806).jpg", "Eumicetoma: grão de hifas coradas pela prata", "Grocott sobre HE"),
        ],
    },
    {
        "id": "rhinosporidium",
        "name": "Rhinosporidium seeberi",
        "aka": ["Rinosporidiose"],
        "summary": "Esporângios enormes (100–350 µm) de parede espessa, cheios de endósporos, em pólipo vascularizado da mucosa nasal ou conjuntival.",
        "description": "## Morfologia\n- **Esporângios** de **100 a 350 µm** com parede espessa e **endósporos** de 5 a 10 µm (maiores perto do poro de liberação), em vários estágios de maturação.\n- Pólipo mucoso com estroma frouxo, vasos, infiltrado misto e reação de corpo estranho aos esporângios rompidos.\n- Parede PAS e Grocott positiva; a mucicarmina cora a parede interna.\n\n## Diferenciais\n- Coccidioides: esférulas muito menores (até 80 µm), pulmão, granuloma.\n- Cistos de glândula mucosa: sem endósporos.\n\n## Contexto\n- Banho em água parada; Índia, Sri Lanka e casos no Brasil; pólipo nasal sangrante ou conjuntival. Organismo não cultivável (Mesomycetozoa).",
        "traits": ["esferula", "esporo", "pas", "grocott"],
        "sites": ["nasofaringe", "olho", "genital"],
        "clinical": ["agua", "zona-rural", "cronico", "imunocompetente"],
        "photos": [
            ("File:Rhinosporidiosis spherules.jpg", "Pólipo nasal: esporângios de tamanhos variados com endósporos", "HE"),
            ("File:Rhinosporidiosis histology image.jpg", "Esporângio maduro de R. seeberi", "HE"),
        ],
    },
    {
        "id": "klebsiella-granulomatis",
        "name": "Klebsiella granulomatis",
        "aka": ["Donovanose", "Granuloma inguinal", "Corpos de Donovan", "Calymmatobacterium"],
        "summary": "Corpos de Donovan: bacilos encapsulados de 1–2 µm dentro de vacúolos no citoplasma de macrófagos grandes, em lesão genital ulcerada rica em plasmócitos.",
        "description": "## Morfologia\n- **Corpos de Donovan**: bacilos de **1 a 2 µm**, com cápsula que dá aspecto bipolar de \"alfinete de segurança\", dentro de **vacúolos citoplasmáticos** de **macrófagos grandes** (células de Pund).\n- Melhor no **Giemsa, Warthin-Starry** ou **imprint** da lesão do que no HE.\n- Úlcera com tecido de granulação, **plasmócitos** abundantes, microabscessos de neutrófilos e hiperplasia pseudoepiteliomatosa nas bordas.\n\n## Diferenciais\n- Leishmaniose: amastigotas com cinetoplasto, Giemsa.\n- Rinoscleroma: mesmas células espumosas com bacilos (Klebsiella rhinoscleromatis) — mas no nariz.\n- Carcinoma escamoso: a hiperplasia pseudoepiteliomatosa engana.\n\n## Contexto\n- IST rara, úlcera genital indolor, vegetante, sangrante; regiões tropicais.",
        "traits": ["intracelular", "bacilo", "giemsa", "warthin-starry", "citologia"],
        "sites": ["genital", "pele", "anus"],
        "clinical": ["ist", "cronico"],
        "photos": [
            ("File:Donovan bodies (Klebsiella granulomatis) PHIL18899.png", "Corpos de Donovan: bacilos encapsulados dentro de vacúolos de macrófagos"),
            ("File:Donovanosis granuloma inguinale skin lesion Wellcome W0044402.jpg", "Lesão de donovanose: infiltrado de macrófagos e plasmócitos", "HE"),
        ],
    },
    {
        "id": "dirofilaria",
        "name": "Dirofilaria immitis / repens",
        "aka": ["Dirofilariose pulmonar", "Nódulo pulmonar em moeda", "Verme do coração do cão"],
        "summary": "Nódulo pulmonar necrótico com o verme em corte dentro de uma artéria trombosada: cutícula espessa com cristas longitudinais e musculatura bem desenvolvida.",
        "description": "## Morfologia\n- **Nódulo** subpleural de 1 a 3 cm com **infarto/necrose coagulativa** central e, no meio, um vaso trombosado contendo o **verme** (100–300 µm de diâmetro).\n- Cutícula **espessa, multilaminada, com cristas longitudinais** externas; musculatura somática abundante; cordões laterais.\n- Granuloma, eosinófilos e fibrose ao redor; o verme costuma estar degenerado — corte vários níveis.\n- D. repens: nódulo subcutâneo ou conjuntival, verme vivo.\n\n## Diferenciais\n- Outros nematódeos em tecido: só a cutícula com cristas e o contexto vascular identificam.\n- Metástase ou granuloma infeccioso: a clínica é de nódulo em moeda assintomático.\n\n## Contexto\n- Mosquito transmite a partir do cão; o homem é hospedeiro acidental e o verme morre na artéria pulmonar.",
        "traits": ["verme", "granuloma"],
        "sites": ["pulmao", "pele", "olho"],
        "clinical": ["animais", "imunocompetente"],
        "photos": [
            ("File:Dirofilariasis Case 234.jpg", "Nódulo pulmonar necrótico com cortes do verme", "HE"),
        ],
    },
    {
        "id": "raiva",
        "name": "Vírus da raiva (corpúsculos de Negri)",
        "aka": ["Raiva", "Corpúsculos de Negri", "Encefalite rábica"],
        "summary": "Corpúsculos de Negri: inclusões citoplasmáticas eosinofílicas, redondas ou ovais, de 2–10 µm, em neurônios do hipocampo e células de Purkinje.",
        "description": "## Morfologia\n- **Corpúsculos de Negri**: inclusões **citoplasmáticas**, **eosinofílicas**, redondas ou ovais, de **2 a 10 µm**, às vezes com grânulos basofílicos internos, em **neurônios piramidais do hipocampo (corno de Amon)** e **células de Purkinje**.\n- Encefalite discreta para a gravidade clínica: manguitos perivasculares, nódulos microgliais (nódulos de Babes), neuronofagia.\n- Ausentes em até 30% dos casos; a **imunofluorescência/IHQ** para o antígeno rábico é o padrão.\n\n## Diferenciais\n- Inclusões neuronais de outras causas (lipofuscina, corpos de Lewy no tronco): distribuição e contexto.\n- Outras encefalites virais: sem inclusões citoplasmáticas eosinofílicas.\n\n## Contexto\n- Mordida de cão, morcego, gato; letal; diagnóstico post-mortem no SNC.",
        "traits": ["inclusao-citoplasmatica", "ihq"],
        "sites": ["snc"],
        "clinical": ["animais", "agudo"],
        "photos": [
            ("File:Histopathology of Negri bodies in rabies encephalitis.png", "Corpúsculos de Negri: inclusões citoplasmáticas eosinofílicas em neurônio (anotação do autor)", "HE"),
            ("File:Rabies negri bodies brain.jpg", "Corpúsculo de Negri em célula de Purkinje do cerebelo", "HE"),
            ("File:Rabies encephalitis Negri bodies PHIL 3377 lores.jpg", "Encefalite rábica com corpúsculos de Negri", "HE"),
        ],
    },
    {
        "id": "poliomavirus-bk",
        "name": "Poliomavírus BK",
        "aka": ["Nefropatia por BK", "Células decoy (chamariz)", "Cistite hemorrágica"],
        "summary": "Núcleos tubulares aumentados, em vidro fosco, com inclusão basofílica que ocupa o núcleo todo; na urina, células decoy que imitam carcinoma urotelial.",
        "description": "## Morfologia\n- Células tubulares (e uroteliais) com **núcleo aumentado, cromatina em vidro fosco** ou **inclusão basofílica homogênea** que apaga o núcleo, sem halo; descamação tubular, tubulite e nefrite intersticial.\n- **Imuno-histoquímica anti-SV40** (antígeno T grande, cruza com BK e JC) confirma.\n- **Células decoy** na citologia urinária: núcleo grande, cromatina homogênea e opaca, sem o pleomorfismo do carcinoma.\n\n## Diferenciais\n- Rejeição celular aguda: tubulite sem inclusões — o SV40 decide.\n- CMV: citomegalia com inclusão com halo e inclusões citoplasmáticas.\n- Carcinoma urotelial de alto grau na urina: cromatina grosseira e irregular.\n\n## Contexto\n- Rim transplantado (imunossupressão intensa); cistite hemorrágica em transplante de medula.",
        "traits": ["inclusao-nuclear", "ihq", "citologia"],
        "sites": ["rim", "trato-urinario"],
        "clinical": ["transplante", "imunossuprimido"],
        "photos": [
            ("File:Polyomavirus nephropathy - very high mag.jpg", "Nefropatia por BK pós-transplante: núcleos tubulares aumentados, em vidro fosco", "PAS"),
            ("File:Polyomavirus nephropathy - sv40 - very high mag.jpg", "Marcação nuclear pelo anticorpo anti-SV40 (reação cruzada com o BK)", "IHQ SV40"),
        ],
    },
    {
        "id": "virus-jc",
        "name": "Vírus JC (leucoencefalopatia multifocal progressiva)",
        "aka": ["LEMP", "PML", "Leucoencefalopatia multifocal progressiva"],
        "summary": "Desmielinização multifocal com oligodendrócitos de núcleo aumentado e inclusão em vidro fosco na borda das lesões, astrócitos bizarros e macrófagos espumosos.",
        "description": "## Morfologia\n- Focos de **desmielinização** na substância branca com **macrófagos espumosos**.\n- **Oligodendrócitos** na periferia com **núcleo aumentado, cromatina em vidro fosco, magenta/anfofílica** (inclusão viral).\n- **Astrócitos bizarros**, hipercromáticos, que imitam glioma.\n- **Imuno-histoquímica anti-SV40** marca os núcleos infectados.\n\n## Diferenciais\n- Glioma: os astrócitos atípicos da LEMP não formam massa e vêm com a desmielinização e os oligodendrócitos com inclusão.\n- Esclerose múltipla: sem inclusões.\n\n## Contexto\n- HIV com CD4 baixo, natalizumab, rituximab, transplante.",
        "traits": ["inclusao-nuclear", "ihq"],
        "sites": ["snc"],
        "clinical": ["hiv", "imunossuprimido", "corticoide"],
        "photos": [
            ("File:PML-HE brain biopsy.jpg", "Oligodendrócitos com núcleos aumentados e cromatina em vidro fosco magenta", "HE"),
            ("File:PML-SV40.jpg", "Inclusões marcadas pelo anti-SV40", "IHQ SV40"),
        ],
    },
    {
        "id": "trichomonas",
        "name": "Trichomonas vaginalis",
        "aka": ["Tricomoníase"],
        "summary": "Trofozoíto piriforme ou redondo, de 15–30 µm, cinza-esverdeado no Papanicolaou, com núcleo pequeno excêntrico e grânulos citoplasmáticos; os flagelos raramente se veem.",
        "description": "## Morfologia\n- Organismo **piriforme ou arredondado** de **15 a 30 µm**, citoplasma **cinza-esverdeado ou acinzentado** no Papanicolaou, **núcleo pequeno, pálido e excêntrico**, grânulos eosinofílicos finos; flagelos quase nunca visíveis.\n- Fundo com **neutrófilos**, halos perinucleares nas escamosas e **Leptothrix** (filamentos longos) frequentemente associado.\n- Não confundir com fragmentos citoplasmáticos, células parabasais degeneradas ou muco.\n\n## Diferenciais\n- Célula parabasal degenerada: núcleo maior e mais denso.\n- Citoplasma solto: sem núcleo.\n\n## Contexto\n- IST; corrimento amarelo-esverdeado bolhoso; achado incidental no rastreio.",
        "traits": ["trofozoito", "citologia"],
        "sites": ["colo-uterino", "genital", "trato-urinario"],
        "clinical": ["ist", "imunocompetente"],
        "photos": [
            ("File:Trichomonas pap test.jpg", "Papanicolaou: organismo piriforme acinzentado (canto superior direito) entre células escamosas", "Papanicolaou"),
        ],
    },
    {
        "id": "mycobacterium-tuberculosis",
        "name": "Mycobacterium tuberculosis",
        "aka": ["Tuberculose", "BAAR", "Bacilo de Koch", "Granuloma caseoso"],
        "summary": "Granulomas epitelioides com necrose caseosa e células gigantes de Langhans; bacilos álcool-ácido resistentes finos, curvos, em vermelho no Ziehl-Neelsen, poucos e na necrose.",
        "description": "## Morfologia\n- **Granuloma caseoso**: centro de **necrose granular eosinofílica** sem estrutura, margem de **células epitelioides** e **células gigantes de Langhans** (núcleos em ferradura), coroa de linfócitos.\n- Bacilos **finos (0,4 × 3 µm), curvos, em contas**, vermelhos no **Ziehl-Neelsen**, geralmente **poucos** e dentro da necrose ou nas células gigantes — procure com objetiva de imersão.\n- No imunossuprimido: necrose com neutrófilos e muitos bacilos, granuloma mal formado.\n- PCR no bloco quando o Ziehl é negativo.\n\n## Diferenciais\n- Micobactérias não tuberculosas e hanseníase: mesmo Ziehl, contexto diferente.\n- Sarcoidose: granulomas \"nus\", sem necrose, Ziehl negativo.\n- Fungos: Grocott — todo granuloma necrosante merece Ziehl e Grocott.\n\n## Contexto\n- Pulmão, linfonodo cervical (escrófula), pleura, intestino, epidídimo, osso, meninge; HIV, diabetes, imunobiológicos.",
        "traits": ["baar", "bacilo", "granuloma", "multinucleacao"],
        "sites": ["pulmao", "linfonodo", "pleura", "intestino", "osso", "snc", "trato-urinario", "genital", "placenta", "pele"],
        "clinical": ["hiv", "imunossuprimido", "corticoide", "diabetes", "imunocompetente", "cronico"],
        "photos": [
            ("File:Mycobacterium tuberculosis Ziehl-Neelsen stain.jpg", "Bacilos álcool-ácido resistentes em vermelho (trombo placentário)", "Ziehl-Neelsen"),
            ("File:Tuberculous lymph node with caseating granuloma 40X.jpg", "Granuloma caseoso em linfonodo: necrose granular eosinofílica margeada por células epitelioides", "HE"),
            ("File:Tuberculous lymph node with caseating granuloma 4X.jpg", "Linfonodo com granulomas caseosos, pequeno aumento", "HE"),
            ("File:Tuberculoid granuloma humpath 2.png", "Granuloma tuberculoide: células epitelioides, célula gigante de Langhans e necrose caseosa", "HE"),
        ],
    },
    {
        "id": "cysticercus",
        "name": "Cysticercus (Taenia solium)",
        "aka": ["Cisticercose", "Neurocisticercose", "Cisticerco"],
        "summary": "Cisto de 5–20 mm com parede fina e membranosa de três camadas e um escólex invaginado com ganchos e ventosas; calcifica quando morre.",
        "description": "## Morfologia\n- Vesícula de **5 a 20 mm** com **parede fina** de três camadas (cuticular eosinofílica ondulada, celular e reticular) e, no interior, o **escólex invaginado** com **quatro ventosas e rostelo com ganchos** birrefringentes; corpúsculos calcários no parênquima.\n- Cisto vivo: quase nenhuma inflamação. Cisto degenerado: inflamação granulomatosa densa com eosinófilos, depois fibrose e **calcificação**.\n- Forma racemosa (sem escólex) nas cisternas da base.\n\n## Diferenciais\n- Cisto hidático: membrana laminada acelular espessa.\n- Cisto simples ou abscesso: sem parede parasitária.\n\n## Contexto\n- Ingestão de ovos de T. solium (água, hortaliças, autoinfecção); epilepsia de início tardio; nódulos subcutâneos e musculares calcificados.",
        "traits": ["cisto", "verme"],
        "sites": ["snc", "musculo", "olho", "pele", "partes-moles"],
        "clinical": ["zona-rural", "agua", "alimento", "cronico"],
        "photos": [],
    },
    {
        "id": "sporothrix",
        "name": "Sporothrix schenckii / brasiliensis",
        "aka": ["Esporotricose", "Corpo asteroide", "Esporotricose zoonótica"],
        "summary": "Leveduras raras, ovais ou em charuto (2–6 µm), difíceis no HE; granulomas supurativos com hiperplasia pseudoepiteliomatosa e, às vezes, corpo asteroide.",
        "description": "## Morfologia\n- Leveduras **ovais ou em charuto, de 2 a 6 µm**, com brotamento, **escassas** — muitas vezes só o Grocott ou o PAS as encontra, e mesmo assim em poucos campos.\n- **Corpo asteroide**: levedura central com raios eosinofílicos de Splendore-Hoeppli — sugestivo, não exclusivo.\n- Padrão: **granulomas supurativos** (neutrófilos no centro, epitelioides e gigantes ao redor) na derme, com **hiperplasia pseudoepiteliomatosa**; linfangite nodular ascendente.\n- Na esporotricose por S. brasiliensis (transmitida por gatos) as leveduras costumam ser mais numerosas.\n\n## Diferenciais\n- Leishmaniose, cromoblastomicose, micobacteriose atípica e tuberculose cutânea: mesma reação — as colorações especiais decidem.\n- Histoplasma: intracelular e em maior número.\n\n## Contexto\n- Arranhadura ou mordida de **gato** (epidemia urbana no Rio de Janeiro e no Sul), espinho de roseira, jardinagem.",
        "traits": ["brotamento", "granuloma", "splendore", "pas", "grocott"],
        "sites": ["pele", "linfonodo", "partes-moles", "osso"],
        "clinical": ["animais", "trauma", "zona-rural", "imunocompetente", "cronico"],
        "photos": [],
    },
    {
        "id": "entamoeba",
        "name": "Entamoeba histolytica",
        "aka": ["Amebíase", "Colite amebiana", "Abscesso hepático amebiano"],
        "summary": "Trofozoítos de 15–40 µm com citoplasma espumoso, núcleo pequeno com cariossoma central e hemácias fagocitadas, na superfície de úlceras em botão de camisa no cólon.",
        "description": "## Morfologia\n- **Trofozoítos** grandes (**15 a 40 µm**), citoplasma **espumoso e PAS-positivo**, **núcleo pequeno redondo com cariossoma central** e cromatina periférica fina; **hemácias fagocitadas** confirmam E. histolytica.\n- Ficam no **exsudato de fibrina e muco na superfície** e no fundo das úlceras, não invadem a lâmina própria em profundidade.\n- Úlceras **em botão de camisa** (estreitas na mucosa, largas na submucosa) no ceco e reto; necrose com poucos neutrófilos.\n- Abscesso hepático: necrose \"em pasta de anchova\", trofozoítos na borda.\n\n## Diferenciais\n- Macrófagos: núcleo maior, sem cariossoma central; a ameba é maior e PAS forte.\n- Doença inflamatória intestinal: a amebíase é o grande mímico — procure os trofozoítos antes de fechar Crohn ou retocolite.\n\n## Contexto\n- Água e alimentos contaminados; disenteria; a Entamoeba dispar é idêntica e comensal.",
        "traits": ["trofozoito", "pas", "citologia"],
        "sites": ["intestino", "figado", "pele"],
        "clinical": ["agua", "viagem", "agudo", "imunocompetente"],
        "photos": [],
    },
    {
        "id": "cryptosporidium",
        "name": "Cryptosporidium",
        "aka": ["Criptosporidiose"],
        "summary": "Esferas basofílicas de 2–5 µm enfileiradas na borda em escova do enterócito, como se fossem \"bolhas\" na superfície; intracelulares mas extracitoplasmáticas.",
        "description": "## Morfologia\n- Corpúsculos **redondos, basofílicos, de 2 a 5 µm**, alinhados na **superfície apical** dos enterócitos e do epitélio das criptas — parecem sentados na borda em escova (na verdade estão dentro de um vacúolo parasitóforo, extracitoplasmático).\n- Atrofia vilositária leve, hiperplasia de criptas, inflamação discreta.\n- Giemsa e imuno-histoquímica ajudam; o HE bem cortado costuma bastar.\n\n## Diferenciais\n- Muco, debris ou cortes tangenciais da borda em escova: o Cryptosporidium tem tamanho uniforme e distribuição em fila.\n- Cystoisospora: intracelular, maior, dentro do citoplasma.\n- Microsporídios: menores (1–2 µm), supranucleares, precisam de Gram modificado ou tricrômico.\n\n## Contexto\n- Diarreia crônica em HIV/aids; surtos por água em imunocompetentes e crianças; vias biliares em imunossuprimidos.",
        "traits": ["intracelular", "giemsa", "ihq"],
        "sites": ["intestino", "figado", "estomago"],
        "clinical": ["hiv", "imunossuprimido", "agua", "crianca"],
        "photos": [],
    },
    {
        "id": "bartonella",
        "name": "Bartonella henselae / quintana",
        "aka": ["Angiomatose bacilar", "Doença da arranhadura do gato", "Peliose hepática bacilar"],
        "summary": "Proliferação vascular lobular com endotélio epitelioide, neutrófilos e agregados granulares roxos de bacilos, prateados no Warthin-Starry.",
        "description": "## Morfologia\n- **Angiomatose bacilar**: lóbulos de **capilares com células endoteliais epitelioides**, protuberantes, com **neutrófilos** e **leucocitoclasia** entre os vasos e **agregados granulares anfofílicos** de bactérias no interstício — que viram bacilos pretos no **Warthin-Starry**.\n- **Arranhadura do gato (linfonodo)**: granulomas com **microabscessos estrelados** (necrose supurativa central), histiócitos em paliçada; bacilos raros, Warthin-Starry ou IHQ.\n- Peliose bacilar no fígado e baço.\n\n## Diferenciais\n- Sarcoma de Kaposi: fusocelular, fendas vasculares, HHV-8 positivo, sem neutrófilos nem grânulos bacterianos.\n- Granuloma piogênico: sem os agregados bacterianos.\n- Linfadenites supurativas granulomatosas: linfogranuloma venéreo, tularemia, Yersinia.\n\n## Contexto\n- Angiomatose e peliose: HIV/aids. Arranhadura do gato: imunocompetente, criança, gato filhote.",
        "traits": ["bacilo", "warthin-starry", "granuloma", "ihq"],
        "sites": ["pele", "linfonodo", "figado", "osso"],
        "clinical": ["hiv", "imunossuprimido", "animais", "crianca", "imunocompetente"],
        "photos": [],
    },
    {
        "id": "dermatofitos",
        "name": "Dermatófitos (Trichophyton, Microsporum, Epidermophyton)",
        "aka": ["Tinha", "Onicomicose", "Tinea", "Dermatofitose"],
        "summary": "Hifas septadas e artroconídios só na camada córnea, na unha e na haste do pelo; paraceratose com neutrófilos e o \"sinal do sanduíche\".",
        "description": "## Morfologia\n- **Hifas septadas** finas e **artroconídios** (cadeias de esporos retangulares) dentro da **camada córnea**, da **lâmina ungueal** ou **ao redor e dentro da haste do pelo** (ecto e endótrix).\n- No HE quase não aparecem: pistas são **neutrófilos na camada córnea**, paraceratose e o **sinal do sanduíche** (hifas entre camada córnea compacta abaixo e ortoqueratose/paraceratose acima). **PAS** confirma.\n- Foliculite e reação granulomatosa quando o folículo rompe (granuloma de Majocchi).\n\n## Diferenciais\n- Candida: leveduras e pseudo-hifas.\n- Malassezia: leveduras em cacho com hifas curtas.\n- Bactérias e fibras na camada córnea: PAS negativas ou sem septos.\n\n## Contexto\n- Tinha do pé, corporal, capitis (Microsporum canis, gatos e cães), onicomicose; peça PAS em toda biópsia de dermatite sem diagnóstico.",
        "traits": ["hifa-verdadeira", "hifa-septada", "esporo", "pas", "grocott"],
        "sites": ["pele"],
        "clinical": ["imunocompetente", "cronico", "animais"],
        "photos": [],
    },
]
