/* ==========================================================================
   renalOncocytic.ts — Neoplasias oncocíticas e eosinofílicas do rim.

   O problema da bancada: um tumor renal "rosa" (citoplasma eosinofílico ou
   oncocítico) que não é obviamente um oncocitoma nem um cromófobo. A OMS
   2022 e a GUPS abriram esse grupo em entidades novas (LOT, EVT, ESC,
   SDH-deficiente, FH-deficiente, ALK, PRNRP, tubulocístico, folicular
   tireoide-símile, FLCN/BHD) e cada uma tem um perfil de CK7, CD117 e
   poucos outros marcadores que a separa das demais.

   As frequências ("típico", "comum", "possível", "raro", "nunca") seguem
   Trpkov, Siadat & Saleeb (Histopathology 2026), as atualizações da GUPS
   (Mod Pathol 2021), Amin et al. (Mod Pathol 2022), Hes & Trpkov (Mod
   Pathol 2022) e a OMS 2022, 5ª edição. Onde a literatura é escassa (TLFCK,
   SOX9, FOXI1 nas entidades mais novas) a opção fica como "possível", que
   é neutra na pontuação.
   ========================================================================== */

import type { Algorithm, Entity, Likelihood, Profile, Question } from '../types'

const T: Likelihood = 'tipico'
const C: Likelihood = 'comum'
const P: Likelihood = 'possivel'
const R: Likelihood = 'raro'
const N: Likelihood = 'nunca'

/* ---- Perguntas ---------------------------------------------------------------- */

const questions: Question[] = [
  /* Clínica e macroscopia */
  {
    id: 'contexto',
    group: 'clinica',
    title: 'Contexto clínico',
    hint: 'Marque o que se aplica. Síndromes e multifocalidade mudam muito a lista.',
    kind: 'multi',
    options: [
      { id: 'multifocal', label: 'Múltiplos ou bilaterais' },
      { id: 'tsc', label: 'Esclerose tuberosa (TSC)', hint: 'Angiomiolipomas, cistos, história familiar.' },
      { id: 'bhd', label: 'Birt-Hogg-Dubé ou oncocitose', hint: 'Fibrofoliculomas, cistos pulmonares, pneumotórax; múltiplos focos oncocíticos no rim.' },
      { id: 'hlrcc', label: 'Leiomiomatose cutânea ou uterina (HLRCC)', hint: 'Leiomiomas de pele, miomas uterinos precoces, carcinoma renal na família.' },
      { id: 'sdh-sindrome', label: 'Paraganglioma, feocromocitoma ou GIST (SDH)' },
      { id: 'drc-terminal', label: 'Doença renal terminal ou diálise' },
      { id: 'falciforme', label: 'Traço ou anemia falciforme' },
      { id: 'neoplasia-infancia', label: 'Neoplasia ou quimioterapia na infância' },
    ],
  },
  {
    id: 'idade',
    group: 'clinica',
    title: 'Idade',
    kind: 'single',
    options: [
      { id: 'jovem', label: 'Até 40 anos' },
      { id: 'adulto', label: '40 a 60 anos' },
      { id: 'idoso', label: 'Mais de 60 anos' },
    ],
  },
  {
    id: 'sexo',
    group: 'clinica',
    title: 'Sexo',
    kind: 'single',
    options: [
      { id: 'f', label: 'Feminino' },
      { id: 'm', label: 'Masculino' },
    ],
  },
  {
    id: 'tamanho',
    group: 'clinica',
    title: 'Tamanho do tumor',
    kind: 'single',
    options: [
      { id: 'pequeno', label: 'Até 1,5 cm' },
      { id: 'medio', label: '1,5 a 7 cm' },
      { id: 'grande', label: 'Mais de 7 cm' },
    ],
  },

  /* Morfologia */
  {
    id: 'arquitetura',
    group: 'morfologia',
    title: 'Arquitetura dominante',
    hint: 'O padrão que ocupa a maior parte do tumor. É a primeira divisão do algoritmo.',
    kind: 'single',
    options: [
      { id: 'solida', label: 'Sólida, ninhos ou lençóis' },
      { id: 'papilar', label: 'Papilar' },
      { id: 'tubulocistica', label: 'Tubulocística', hint: 'Túbulos e cistos de tamanhos variados com estroma mínimo; macroscopia em plástico-bolha.' },
      { id: 'solido-cistica', label: 'Sólida e cística (macrocistos)' },
      { id: 'folicular', label: 'Folicular, tireoide-símile' },
      { id: 'mosaico', label: 'Mosaico de células oncocíticas e claras', hint: 'Padrão em xadrez: grupos de células claras ou vacuoladas entremeados a células oncocíticas.' },
      { id: 'mista', label: 'Vários padrões misturados', hint: 'Papilar + tubular + sólido + cribriforme no mesmo tumor: pense em FH-deficiente e ALK.' },
    ],
  },
  {
    id: 'nucleo-grau',
    group: 'morfologia',
    title: 'Núcleo e nucléolo',
    kind: 'single',
    options: [
      { id: 'baixo', label: 'Baixo grau: nucléolo inconspícuo', hint: 'Equivalente a OMS/ISUP 1–2.' },
      { id: 'nucleolo', label: 'Nucléolo evidente, uniforme', hint: 'Equivalente a grau 3, sem pleomorfismo.' },
      { id: 'macronucleolo-halo', label: 'Macronucléolo eosinofílico com halo perinucleolar', hint: 'Inclusão tipo citomegalovírus; clássico, mas não exclusivo, do FH-deficiente.' },
      { id: 'alto', label: 'Alto grau: pleomorfismo, rabdoide ou sarcomatoide' },
    ],
  },
  {
    id: 'citoplasma',
    group: 'morfologia',
    title: 'Citoplasma',
    kind: 'multi',
    options: [
      { id: 'oncocitico-homogeneo', label: 'Oncocítico homogêneo, granular fino' },
      { id: 'vacuolos-grandes', label: 'Vacúolos intracitoplasmáticos grandes, bem definidos' },
      { id: 'vacuolos-flocosos', label: 'Vacúolos ou inclusões pálidas, flocosas', hint: 'Material pálido e floculento no citoplasma: mitocôndrias gigantes anormais do SDH-deficiente.' },
      { id: 'granulos-basofilicos', label: 'Grânulos basofílicos grosseiros (estipulação)', hint: 'Agregados de retículo endoplasmático rugoso; lembram corpos de leishmania.' },
      { id: 'palido-reticulado', label: 'Citoplasma pálido reticulado com membrana espessa', hint: 'A célula "em casca de planta" do cromófobo clássico.' },
      { id: 'claras-entremeadas', label: 'Células claras entremeadas' },
      { id: 'mucina', label: 'Mucina intracelular ou intersticial', hint: 'Em tumor eosinofílico com padrões variados, mucina pede ALK.' },
    ],
  },
  {
    id: 'nucleo',
    group: 'morfologia',
    title: 'Forma e posição dos núcleos',
    kind: 'multi',
    options: [
      { id: 'redondo-regular', label: 'Redondos e regulares, centrais' },
      { id: 'enrugado-halo', label: 'Enrugados (em passa) com halo perinuclear' },
      { id: 'polaridade-reversa', label: 'Polaridade reversa: núcleos apicais alinhados', hint: 'Núcleos junto à luz, longe da base da papila.' },
      { id: 'tachinha', label: 'Em tachinha (hobnail)' },
      { id: 'multinucleacao', label: 'Binucleação ou células gigantes multinucleadas' },
    ],
  },
  {
    id: 'achados',
    group: 'morfologia',
    title: 'Estroma e outros achados',
    kind: 'multi',
    options: [
      { id: 'edematoso-ilhas', label: 'Estroma edematoso com células soltas ou em cordões', hint: 'Áreas frouxas, hemorrágicas, com células "em barcos na baía": oncocitoma e LOT.' },
      { id: 'cicatriz-central', label: 'Cicatriz central estrelada' },
      { id: 'rede-vascular', label: 'Rede de vasos finos sinusoidais entre os ninhos' },
      { id: 'adiposo-vasos', label: 'Gordura madura e vasos de parede espessa ou displásicos', hint: 'Componente de angiomiolipoma, mesmo focal.' },
      { id: 'mastocitos', label: 'Mastócitos entremeados' },
      { id: 'tubulos-aprisionados', label: 'Túbulos aprisionados e microcistos' },
      { id: 'macrofagos-espumosos', label: 'Macrófagos espumosos' },
      { id: 'psamomas', label: 'Corpos psamomatosos ou microcalcificações' },
      { id: 'oxalato', label: 'Cristais de oxalato de cálcio' },
      { id: 'coloide', label: 'Coloide denso nos folículos' },
      { id: 'oncocitose-adjacente', label: 'Focos oncocíticos microscópicos no rim adjacente' },
    ],
  },
  {
    id: 'alto-grau',
    group: 'morfologia',
    title: 'Sinais de agressividade',
    kind: 'multi',
    options: [
      { id: 'necrose', label: 'Necrose coagulativa' },
      { id: 'mitoses', label: 'Mitoses fáceis ou atípicas' },
      { id: 'sarcomatoide', label: 'Sarcomatoide ou rabdoide' },
      { id: 'invasao-vascular', label: 'Invasão vascular ou extrarrenal' },
    ],
  },

  /* Imuno */
  { id: 'ck7', group: 'imuno', title: 'CK7', hint: 'A extensão importa mais que a intensidade.', kind: 'single', options: [{ id: 'negativa-isoladas', label: 'Negativa ou em células isoladas' }, { id: 'focal', label: 'Focal ou em grupos' }, { id: 'difusa', label: 'Difusa' }] },
  { id: 'cd117', group: 'imuno', title: 'CD117 (KIT)', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'ck20', group: 'imuno', title: 'CK20', kind: 'single', options: [{ id: 'positiva', label: 'Positiva (difusa ou focal)' }, { id: 'negativa', label: 'Negativa' }] },
  { id: 'catepsina-k', group: 'imuno', title: 'Catepsina K', kind: 'single', options: [{ id: 'difusa', label: 'Difusa' }, { id: 'focal', label: 'Focal' }, { id: 'negativa', label: 'Negativa' }] },
  { id: 'gata3', group: 'imuno', title: 'GATA3', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'vimentina', group: 'imuno', title: 'Vimentina', kind: 'single', options: [{ id: 'positiva', label: 'Positiva' }, { id: 'negativa', label: 'Negativa' }] },
  { id: 'caix', group: 'imuno', title: 'CA-IX', kind: 'single', options: [{ id: 'caixa-difusa', label: 'Membranosa difusa, em caixa' }, { id: 'negativa-focal', label: 'Negativa ou só perinecrótica' }] },
  { id: 'amacr', group: 'imuno', title: 'AMACR (P504S)', kind: 'single', options: [{ id: 'positiva', label: 'Positiva' }, { id: 'negativa', label: 'Negativa' }] },
  { id: 'cd10', group: 'imuno', title: 'CD10', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'sdhb', group: 'imuno', title: 'SDHB', hint: 'Perda é ausência total no tumor com controle interno (endotélio, estroma) positivo. Marcação citoplasmática difusa tênue ("blush") não é retenção.', kind: 'single', weight: 1.5, options: [{ id: 'retida', label: 'Retida (granular citoplasmática)' }, { id: 'perdida', label: 'Perdida' }] },
  { id: 'fh', group: 'imuno', title: 'FH (fumarato hidratase)', hint: 'Perda é específica, mas pouco sensível: alguns FH-deficientes retêm FH. Complete com 2SC.', kind: 'single', weight: 1.5, options: [{ id: 'retida', label: 'Retida' }, { id: 'perdida', label: 'Perdida' }] },
  { id: 'twosc', group: 'imuno', title: '2SC (S-2-succinocisteína)', hint: 'Positivo nuclear e citoplasmático. AKR1B10 é alternativa com sensibilidade equivalente.', kind: 'single', weight: 1.3, options: [{ id: 'positiva', label: 'Positiva' }, { id: 'negativa', label: 'Negativa' }] },
  { id: 'melanociticos', group: 'imuno', title: 'HMB-45 / Melan-A', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'pax8', group: 'imuno', title: 'PAX8', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'tfe3', group: 'imuno', title: 'TFE3 (imuno ou FISH)', hint: 'Só a marcação nuclear forte e difusa conta; FISH break-apart confirma.', kind: 'single', weight: 1.3, options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'tfeb', group: 'imuno', title: 'TFEB (imuno ou FISH)', kind: 'single', weight: 1.3, options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'alk', group: 'imuno', title: 'ALK', hint: 'Clones 5A4 ou D5F3.', kind: 'single', weight: 1.5, options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'ttf1', group: 'imuno', title: 'TTF-1 / tireoglobulina', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'l1cam', group: 'imuno', title: 'L1CAM', hint: 'Marcador de célula principal do néfron distal.', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'gpnmb', group: 'imuno', title: 'GPNMB', hint: 'Marca ativação de mTORC1 e da via MiT: positivo em LOT, EVT, ESC, FLCN, eAML, TFE3 e TFEB. Negativo em oncocitoma, cromófobo e células claras.', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'foxi1', group: 'imuno', title: 'FOXI1', hint: 'Marcador de célula intercalada: positivo em oncocitoma e cromófobo, negativo no LOT.', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },
  { id: 'panck', group: 'imuno', title: 'Pancitoqueratina (AE1/AE3, CAM5.2)', kind: 'single', options: [{ id: 'positiva', label: 'Positiva' }, { id: 'fraca-negativa', label: 'Fraca, focal ou negativa' }] },
  { id: 'sox9', group: 'imuno', title: 'SOX9', kind: 'single', options: [{ id: 'positivo', label: 'Positivo' }, { id: 'negativo', label: 'Negativo' }] },

  /* Molecular */
  {
    id: 'molecular',
    group: 'molecular',
    title: 'Achado molecular, se houver',
    hint: 'Sequenciamento, FISH ou cariótipo. Marque o que já veio.',
    kind: 'multi',
    options: [
      { id: 'mtor-tsc', label: 'Mutação em MTOR, TSC1 ou TSC2' },
      { id: 'flcn', label: 'Mutação em FLCN' },
      { id: 'sdhx', label: 'Mutação em SDHB, SDHA, SDHC ou SDHD' },
      { id: 'fh-mut', label: 'Inativação bialélica de FH' },
      { id: 'alk-fusao', label: 'Fusão de ALK' },
      { id: 'kras', label: 'Mutação em KRAS' },
      { id: 'ewsr1-patz1', label: 'Fusão EWSR1::PATZ1' },
      { id: 'tfe3-fusao', label: 'Fusão de TFE3 (Xp11.2)' },
      { id: 'tfeb-alt', label: 'Rearranjo ou amplificação de TFEB' },
      { id: 'vhl-3p', label: 'Mutação de VHL ou perda de 3p' },
      { id: 'perda-1-y', label: 'Perda de 1 e Y, ou rearranjo de CCND1' },
      { id: 'perdas-multiplas', label: 'Perdas múltiplas (1, 2, 6, 10, 13, 17, 21)' },
      { id: 'ganho-7-17', label: 'Trissomia de 7 e 17' },
    ],
  },
]

/* ---- Entidades ------------------------------------------------------------------- */

/** Imuno "clássica" negativa, para não repetir em todo verbete que não tem a alteração. */
const noDefiningLoss: Profile = {
  sdhb: { retida: T, perdida: N },
  fh: { retida: T, perdida: N },
  twosc: { negativa: T, positiva: N },
  tfe3: { negativo: T, positivo: N },
  tfeb: { negativo: T, positivo: N },
  alk: { negativo: T, positivo: N },
  ttf1: { negativo: T, positivo: N },
}

const merge = (...parts: Profile[]): Profile => Object.assign({}, ...parts)

const entities: Entity[] = [
  {
    id: 'ro',
    short: 'Oncocitoma',
    name: 'Oncocitoma renal',
    aka: ['RO', 'renal oncocytoma'],
    status: 'Entidade da OMS 2022',
    risk: 'benigno',
    frequency: 3,
    summary:
      'Tumor benigno castanho-mogno, com cicatriz central estrelada, feito de ninhos e ilhas de células oncocíticas uniformes num estroma frouxo ou hialinizado. CK7 só em células isoladas com CD117 positivo é o perfil; CK7 difusa afasta.',
    keys: [
      'Células oncocíticas redondas, de núcleo regular e nucléolo pequeno; sem membrana celular proeminente nem núcleo em passa.',
      'Ninhos e ilhas em estroma frouxo, edematoso ou hialinizado; cicatriz central no tumor maior.',
      'CK7 negativa ou em células isoladas; CD117 positivo; CK20, vimentina e CA-IX negativos.',
      'Perda de 1 e Y ou rearranjo de CCND1; FOXI1 positivo (célula intercalada).',
    ],
    ihc: 'CD117+, CK7 em células isoladas, FOXI1+, GATA3−, vimentina−, CA-IX−, CK20−, catepsina K−, GPNMB−.',
    molecular: 'Perda de 1 e Y, ou rearranjo de CCND1. Múltiplos na oncocitose e em Birt-Hogg-Dubé.',
    behavior: 'Benigno. Atipia degenerativa, invasão vascular e extensão à gordura não mudam o diagnóstico.',
    pitfalls: [
      'Mitoses ou necrose não são de oncocitoma: reconsidere cromófobo eosinofílico, SDH-deficiente ou FH-deficiente.',
      'CK7 difusa num tumor "de oncocitoma": LOT (CD117−) ou cromófobo (CD117+).',
      'Vacúolos grandes com nucléolo evidente: EVT, não oncocitoma.',
    ],
    profile: merge(noDefiningLoss, {
      contexto: { bhd: C, multifocal: P, tsc: P, 'drc-terminal': P, hlrcc: R, 'sdh-sindrome': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { idoso: T, adulto: C, jovem: R },
      sexo: { m: C, f: C },
      tamanho: { pequeno: P, medio: T, grande: C },
      arquitetura: { solida: T, mosaico: R, papilar: R, tubulocistica: R, 'solido-cistica': P, folicular: N, mista: P },
      'nucleo-grau': { baixo: T, nucleolo: P, 'macronucleolo-halo': R, alto: N },
      citoplasma: { 'oncocitico-homogeneo': T, 'vacuolos-grandes': R, 'vacuolos-flocosos': R, 'granulos-basofilicos': R, 'palido-reticulado': R, 'claras-entremeadas': R, mucina: N },
      nucleo: { 'redondo-regular': T, 'enrugado-halo': R, 'polaridade-reversa': N, tachinha: R, multinucleacao: R },
      achados: { 'edematoso-ilhas': T, 'cicatriz-central': C, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: P, 'tubulos-aprisionados': P, 'macrofagos-espumosos': R, psamomas: R, oxalato: R, coloide: N, 'oncocitose-adjacente': C },
      'alto-grau': { necrose: R, mitoses: R, sarcomatoide: N, 'invasao-vascular': P },
      ck7: { 'negativa-isoladas': T, focal: P, difusa: N },
      cd117: { positivo: T, negativo: R },
      ck20: { negativa: T, positiva: N },
      'catepsina-k': { negativa: T, focal: R, difusa: R },
      gata3: { negativo: T, positivo: R },
      vimentina: { negativa: T, positiva: R },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: T, positiva: R },
      cd10: { negativo: C, positivo: P },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      l1cam: { negativo: T, positivo: R },
      gpnmb: { negativo: C, positivo: R },
      foxi1: { positivo: T, negativo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      sox9: { negativo: T, positivo: R },
      molecular: { 'perda-1-y': T, 'mtor-tsc': R, flcn: R, sdhx: N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N, 'perdas-multiplas': R, 'ganho-7-17': N },
    }),
    sources: ['who2022', 'gups2021a', 'amin2022', 'hes2022'],
  },
  {
    id: 'chrcc-eos',
    short: 'Cromófobo eosinofílico',
    name: 'Carcinoma renal cromófobo, variante eosinofílica',
    aka: ['e-ChRCC', 'eosinophilic chromophobe RCC'],
    status: 'Entidade da OMS 2022',
    risk: 'baixo',
    frequency: 3,
    summary:
      'O cromófobo em que a célula pálida reticulada cedeu lugar à oncocítica: fica o núcleo enrugado em passa com halo perinuclear, a binucleação e a membrana celular evidente. CK7 difusa com CD117 positivo é o perfil, e separa do oncocitoma (CK7 isoladas) e do LOT (CD117−).',
    keys: [
      'Núcleos irregulares, enrugados ("em passa"), com halo perinuclear; binucleação frequente.',
      'Membranas celulares proeminentes; ao menos focos de citoplasma pálido reticulado.',
      'CK7 difusa, CD117 positivo, vimentina e CA-IX negativas; FOXI1 positivo.',
      'Perdas cromossômicas múltiplas (1, 2, 6, 10, 13, 17, 21).',
    ],
    ihc: 'CK7 difusa, CD117+, FOXI1+, GATA3−, vimentina−, CA-IX−, CK20−, catepsina K−, GPNMB−.',
    molecular: 'Perdas múltiplas de cromossomos inteiros; mutações em TP53 e PTEN nos agressivos.',
    behavior: 'Baixo risco; recorrência e metástase em torno de 5%, maiores com sarcomatoide e necrose. Graduação OMS/ISUP não se aplica.',
    pitfalls: [
      'A coloração de Hale (ferro coloidal) é difusa e reticular, mas pouco reprodutível; a imuno resolve melhor.',
      'Tumor "híbrido" oncocitoma-cromófobo em paciente com múltiplos tumores: pense em Birt-Hogg-Dubé (FLCN).',
    ],
    profile: merge(noDefiningLoss, {
      contexto: { bhd: C, multifocal: P, tsc: P, 'drc-terminal': P, hlrcc: R, 'sdh-sindrome': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { adulto: T, idoso: T, jovem: P },
      sexo: { m: C, f: C },
      tamanho: { pequeno: P, medio: T, grande: C },
      arquitetura: { solida: T, mosaico: P, papilar: R, tubulocistica: R, 'solido-cistica': R, folicular: N, mista: P },
      'nucleo-grau': { baixo: C, nucleolo: C, 'macronucleolo-halo': R, alto: R },
      citoplasma: { 'oncocitico-homogeneo': C, 'palido-reticulado': C, 'claras-entremeadas': P, 'vacuolos-grandes': R, 'vacuolos-flocosos': R, 'granulos-basofilicos': R, mucina: N },
      nucleo: { 'enrugado-halo': T, 'redondo-regular': P, multinucleacao: C, 'polaridade-reversa': N, tachinha: R },
      achados: { 'edematoso-ilhas': R, 'cicatriz-central': P, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: P, 'tubulos-aprisionados': R, 'macrofagos-espumosos': R, psamomas: R, oxalato: R, coloide: N, 'oncocitose-adjacente': P },
      'alto-grau': { necrose: P, mitoses: P, sarcomatoide: P, 'invasao-vascular': P },
      ck7: { difusa: T, focal: P, 'negativa-isoladas': R },
      cd117: { positivo: T, negativo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { negativo: T, positivo: R },
      vimentina: { negativa: T, positiva: R },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: T, positiva: R },
      cd10: { negativo: C, positivo: P },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      l1cam: { negativo: T, positivo: R },
      gpnmb: { negativo: C, positivo: R },
      foxi1: { positivo: T, negativo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      sox9: { negativo: T, positivo: R },
      molecular: { 'perdas-multiplas': T, flcn: R, 'mtor-tsc': R, 'perda-1-y': R, sdhx: N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['who2022', 'gups2021a', 'amin2022'],
  },
  {
    id: 'lot',
    short: 'LOT',
    name: 'Tumor oncocítico de baixo grau (LOT)',
    aka: ['LOT', 'low-grade oncocytic tumour', 'adenoma oncocítico de célula principal'],
    status: 'OMS 2022: "outros tumores oncocíticos do rim" (entidade emergente)',
    risk: 'benigno',
    frequency: 2,
    summary:
      'Tumor sólido de células oncocíticas de núcleo baixo grau, com áreas edematosas em que as células ficam soltas em cordões ("barcos na baía"), e o perfil que o define: CK7 difusa com CD117 negativo. Mais de 300 casos relatados, todos indolentes.',
    keys: [
      'Sólido e compacto, com áreas estromais frouxas ou edematosas contendo células isoladas e em cordões.',
      'Citoplasma oncocítico homogêneo; núcleos redondos a ovais, de baixo grau, com halos perinucleares focais ou extensos.',
      'CK7 difusa e CD117 negativo (ou fracamente positivo em raras células); GATA3 e L1CAM positivos; FOXI1 negativo.',
      'Via mTOR ativada: mutações em MTOR, TSC1, TSC2 ou RHEB em quase 90%; GPNMB positivo.',
    ],
    ihc: 'CK7 difusa, CD117−, GATA3+, L1CAM+, GPNMB+, FOXI1−, vimentina−, CA-IX−, CK20−, catepsina K−.',
    molecular: 'MTOR (50%), TSC1 (20%), TSC2 (9%), RHEB (8%); baixa carga mutacional; deleções em 19p13, 1p36 e 19q13.',
    behavior: 'Benigno em todas as séries; frequência de 4 a 6% entre os tumores oncocíticos. Múltiplos em esclerose tuberosa e em rim terminal.',
    pitfalls: [
      'Antes do nome, era laudado como oncocitoma ou cromófobo eosinofílico: a CK7 difusa afasta o primeiro, o CD117 negativo afasta o segundo.',
      'Áreas tubulares, tubulorreticulares ou raramente papilares podem existir e não afastam.',
    ],
    profile: merge(noDefiningLoss, {
      contexto: { tsc: C, 'drc-terminal': P, multifocal: P, bhd: R, hlrcc: R, 'sdh-sindrome': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { idoso: T, adulto: C, jovem: R },
      sexo: { f: C, m: P },
      tamanho: { medio: T, pequeno: C, grande: R },
      arquitetura: { solida: T, mosaico: R, papilar: R, tubulocistica: P, 'solido-cistica': R, folicular: N, mista: P },
      'nucleo-grau': { baixo: T, nucleolo: R, 'macronucleolo-halo': N, alto: N },
      citoplasma: { 'oncocitico-homogeneo': T, 'palido-reticulado': R, 'claras-entremeadas': R, 'vacuolos-grandes': R, 'vacuolos-flocosos': R, 'granulos-basofilicos': R, mucina: N },
      nucleo: { 'redondo-regular': T, 'enrugado-halo': P, 'polaridade-reversa': N, tachinha: R, multinucleacao: R },
      achados: { 'edematoso-ilhas': T, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: P, 'tubulos-aprisionados': R, 'macrofagos-espumosos': R, psamomas: R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: N, mitoses: R, sarcomatoide: N, 'invasao-vascular': R },
      ck7: { difusa: T, focal: R, 'negativa-isoladas': N },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { positivo: T, negativo: R },
      vimentina: { negativa: T, positiva: R },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: T, positiva: R },
      cd10: { negativo: C, positivo: P },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      l1cam: { positivo: T, negativo: R },
      gpnmb: { positivo: T, negativo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      sox9: { negativo: T, positivo: R },
      molecular: { 'mtor-tsc': T, 'perda-1-y': R, flcn: R, 'perdas-multiplas': R, sdhx: N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['trpkov2026', 'trpkov2019', 'amin2022', 'hes2022', 'who2022'],
  },
  {
    id: 'evt',
    short: 'EVT',
    name: 'Tumor eosinofílico vacuolado (EVT)',
    aka: ['EVT', 'HOT', 'high-grade oncocytic tumour', 'carcinoma esporádico com citoplasma eosinofílico e vacuolado'],
    status: 'OMS 2022: "outros tumores oncocíticos do rim" (entidade emergente)',
    risk: 'benigno',
    frequency: 2,
    summary:
      'Tumor sólido de células eosinofílicas com vacúolos intracitoplasmáticos grandes e nucléolos proeminentes "de alto grau", num tumor que se comporta de forma indolente. CD117 positivo com CK7 negativa (ou em raras células), catepsina K focal e CD10 positivo.',
    keys: [
      'Células eosinofílicas volumosas com vacúolos intracitoplasmáticos grandes e nítidos.',
      'Núcleos redondos a ovais com nucléolo proeminente, que às vezes lembra inclusão viral; sem pleomorfismo.',
      'Sólido, sem componente cístico; vasos de parede espessa na periferia.',
      'CD117+, CK7 negativa ou em raras células, catepsina K ao menos focal, CD10+, GPNMB+.',
    ],
    ihc: 'CD117+, CK7 em raras células, catepsina K focal, CD10+, CD56+, GPNMB+, vimentina variável; CK20 raras células.',
    molecular: 'MTOR (43%), TSC2 (43%), TSC1 (14%): ativação de mTORC1; perda do alelo selvagem no cromossomo 1 (MTOR), perdas em 19p, 16p11 e 7q31.',
    behavior: 'Indolente em todos os casos relatados, com um único relato de metástase linfonodal num adolescente. Cerca de 1% dos tumores oncocíticos.',
    pitfalls: ['Antes do nome, era laudado como "cromófobo-símile" ou oncocitoma com nucléolo: o vacúolo grande com CD117+/CK7− é a pista.'],
    profile: merge(noDefiningLoss, {
      contexto: { tsc: C, multifocal: P, bhd: R, hlrcc: R, 'sdh-sindrome': R, 'drc-terminal': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { adulto: T, idoso: C, jovem: P },
      sexo: { f: C, m: C },
      tamanho: { medio: T, pequeno: C, grande: R },
      arquitetura: { solida: T, mosaico: R, papilar: R, tubulocistica: R, 'solido-cistica': R, folicular: N, mista: P },
      'nucleo-grau': { nucleolo: T, baixo: P, 'macronucleolo-halo': P, alto: R },
      citoplasma: { 'vacuolos-grandes': T, 'oncocitico-homogeneo': C, 'palido-reticulado': R, 'claras-entremeadas': R, 'vacuolos-flocosos': P, 'granulos-basofilicos': R, mucina: N },
      nucleo: { 'redondo-regular': T, 'enrugado-halo': R, 'polaridade-reversa': N, tachinha: R, multinucleacao: R },
      achados: { 'edematoso-ilhas': R, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': P, mastocitos: P, 'tubulos-aprisionados': R, 'macrofagos-espumosos': R, psamomas: R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: R, mitoses: R, sarcomatoide: N, 'invasao-vascular': R },
      ck7: { 'negativa-isoladas': T, focal: P, difusa: N },
      cd117: { positivo: T, negativo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { focal: T, difusa: P, negativa: R },
      gata3: { negativo: T, positivo: R },
      vimentina: { negativa: C, positiva: P },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: T, positiva: R },
      cd10: { positivo: T, negativo: R },
      melanociticos: { negativo: T, positivo: R },
      pax8: { positivo: T, negativo: R },
      l1cam: { negativo: C, positivo: P },
      gpnmb: { positivo: T, negativo: R },
      foxi1: { negativo: C, positivo: P },
      panck: { positiva: T, 'fraca-negativa': R },
      sox9: { negativo: T, positivo: R },
      molecular: { 'mtor-tsc': T, 'perda-1-y': R, flcn: R, 'perdas-multiplas': R, sdhx: N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['trpkov2026', 'he2018', 'hes2022', 'who2022'],
  },
  {
    id: 'flcn',
    short: 'FLCN / BHD',
    name: 'Tumor FLCN-mutado / híbrido oncocítico-cromófobo (Birt-Hogg-Dubé)',
    aka: ['HOCT', 'hybrid oncocytic chromophobe tumour', 'tumor de BHD'],
    status: 'OMS 2022: tumores oncocíticos híbridos em síndromes hereditárias; "FLCN-mutado" é nome em proposição',
    risk: 'benigno',
    frequency: 1,
    summary:
      'Tumor de paciente com Birt-Hogg-Dubé (ou, mais raramente, esporádico com mutação somática de FLCN), feito de um mosaico em xadrez de células oncocíticas e grupos de células claras ou vacuoladas; a imuno é igualmente em mosaico, com CD117 nas oncocíticas e CK7 nas claras. Multifocal, bilateral, com oncocitose no rim adjacente.',
    keys: [
      'Padrão em mosaico ("xadrez"): células oncocíticas entremeadas a grupos de células claras ou com vacúolos citoplasmáticos.',
      'Imuno mutuamente exclusiva: CD117 (e FOXI1) nas células oncocíticas, CK7 (e L1CAM) nas células claras.',
      'Múltiplos tumores e focos microscópicos de oncocitose no parênquima adjacente.',
      'Catepsina K e SOX9 positivos; GPNMB difuso (ativação de TFEB pela perda de FLCN).',
    ],
    ihc: 'CD117+ em mosaico, CK7+ nas células claras, catepsina K+, SOX9+, GPNMB+.',
    molecular: 'Mutação germinativa (BHD) ou somática de FLCN. Os tumores "atípicos" FLCN-mutados têm morfologia variada, sem o mosaico, e podem ganhar TFEB.',
    behavior: 'Indolente nos típicos; os atípicos esporádicos FLCN-mutados podem ser agressivos.',
    pitfalls: ['Em paciente sem síndrome conhecida, múltiplos tumores híbridos pedem investigação de BHD.', 'Não é o "cromófobo associado a BHD": os tumores de BHD têm expressão e perfil mitocondrial diferentes do cromófobo esporádico.'],
    profile: merge(noDefiningLoss, {
      contexto: { bhd: T, multifocal: T, tsc: R, hlrcc: R, 'sdh-sindrome': R, 'drc-terminal': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { adulto: T, idoso: C, jovem: P },
      sexo: { f: C, m: C },
      tamanho: { medio: T, pequeno: C, grande: P },
      arquitetura: { mosaico: T, solida: C, papilar: R, tubulocistica: R, 'solido-cistica': R, folicular: N, mista: P },
      'nucleo-grau': { baixo: T, nucleolo: P, 'macronucleolo-halo': R, alto: R },
      citoplasma: { 'claras-entremeadas': T, 'oncocitico-homogeneo': C, 'vacuolos-grandes': C, 'palido-reticulado': P, 'vacuolos-flocosos': R, 'granulos-basofilicos': R, mucina: N },
      nucleo: { 'redondo-regular': T, 'enrugado-halo': P, 'polaridade-reversa': N, tachinha: R, multinucleacao: P },
      achados: { 'oncocitose-adjacente': T, 'edematoso-ilhas': P, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: P, 'tubulos-aprisionados': R, 'macrofagos-espumosos': R, psamomas: R, oxalato: R, coloide: N },
      'alto-grau': { necrose: R, mitoses: R, sarcomatoide: R, 'invasao-vascular': R },
      ck7: { focal: T, difusa: P, 'negativa-isoladas': P },
      cd117: { positivo: T, negativo: P },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { focal: C, difusa: P, negativa: P },
      gata3: { negativo: C, positivo: P },
      vimentina: { negativa: C, positiva: P },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: T, positiva: R },
      cd10: { negativo: C, positivo: P },
      melanociticos: { negativo: T, positivo: R },
      pax8: { positivo: T, negativo: R },
      gpnmb: { positivo: T, negativo: R },
      foxi1: { positivo: C, negativo: P },
      panck: { positiva: T, 'fraca-negativa': R },
      sox9: { positivo: T, negativo: R },
      molecular: { flcn: T, 'perda-1-y': R, 'perdas-multiplas': R, 'mtor-tsc': R, sdhx: N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': R, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['trpkov2026', 'hes2022', 'who2022'],
  },
  {
    id: 'sdh',
    short: 'SDH-deficiente',
    name: 'Carcinoma renal SDH-deficiente',
    aka: ['SDH-deficient RCC', 'carcinoma renal com deficiência de succinato desidrogenase'],
    status: 'Entidade molecularmente definida da OMS 2022',
    risk: 'baixo',
    frequency: 1,
    summary:
      'Carcinoma de paciente jovem, sólido, de células eosinofílicas monótonas com vacúolos ou inclusões citoplasmáticas pálidas e flocosas, mastócitos e túbulos aprisionados; a perda de SDHB na imuno define, e quase todos têm mutação germinativa de SDHB.',
    keys: [
      'Lençóis ou ninhos de células cuboides monótonas, eosinofílicas, com citoplasma flocoso e vacúolos pálidos (mitocôndrias gigantes).',
      'Túbulos aprisionados na periferia, microcistos, mastócitos entremeados.',
      'Perda completa de SDHB na imuno com controle interno retido; CD117 e CK7 negativos; GATA3 e L1CAM positivos.',
      'Mutação germinativa de SDHB (raramente SDHA, SDHC, SDHD) com segundo evento somático.',
    ],
    ihc: 'SDHB perdida, CD117−, CK7−, GATA3+, L1CAM+, pancitoqueratina fraca ou ausente.',
    molecular: 'Inativação bialélica de SDHB, SDHA, SDHC ou SDHD, quase sempre germinativa. Obriga aconselhamento genético.',
    behavior: 'Indolente no tipo usual; transformação de alto grau, necrose e sarcomatoide em uma parte dos casos, com cerca de 70% de comportamento agressivo nesses.',
    pitfalls: [
      'Marcação citoplasmática tênue e difusa ("blush") de SDHB não é retenção: compare com o controle interno.',
      'Os SDHA-deficientes têm morfologia variada (papilar, cribriforme, glóbulos hialinos) e perdem também SDHA.',
      'O "FH-deficiente oncocítico de baixo grau" imita este tumor: peça FH e 2SC junto.',
    ],
    profile: merge(noDefiningLoss, {
      sdhb: { perdida: T, retida: N },
      contexto: { 'sdh-sindrome': T, multifocal: C, tsc: R, bhd: R, hlrcc: R, 'drc-terminal': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { jovem: T, adulto: C, idoso: P },
      sexo: { m: C, f: C },
      tamanho: { medio: T, pequeno: P, grande: P },
      arquitetura: { solida: T, tubulocistica: R, papilar: R, 'solido-cistica': P, mosaico: R, folicular: N, mista: P },
      'nucleo-grau': { baixo: T, nucleolo: P, 'macronucleolo-halo': R, alto: P },
      citoplasma: { 'vacuolos-flocosos': T, 'oncocitico-homogeneo': C, 'vacuolos-grandes': P, 'palido-reticulado': R, 'claras-entremeadas': R, 'granulos-basofilicos': R, mucina: N },
      nucleo: { 'redondo-regular': T, 'enrugado-halo': R, 'polaridade-reversa': N, tachinha: R, multinucleacao: R },
      achados: { 'tubulos-aprisionados': T, mastocitos: C, 'edematoso-ilhas': R, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, 'macrofagos-espumosos': R, psamomas: R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: P, mitoses: P, sarcomatoide: P, 'invasao-vascular': P },
      ck7: { 'negativa-isoladas': T, focal: P, difusa: R },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { positivo: T, negativo: P },
      vimentina: { positiva: C, negativa: P },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: T, positiva: R },
      cd10: { negativo: C, positivo: P },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      l1cam: { positivo: C, negativo: P },
      panck: { 'fraca-negativa': C, positiva: P },
      molecular: { sdhx: T, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['trpkov2026', 'williamson2015', 'gups2021a', 'who2022'],
  },
  {
    id: 'esc',
    short: 'ESC',
    name: 'Carcinoma renal eosinofílico sólido e cístico (ESC)',
    aka: ['ESC RCC', 'eosinophilic solid and cystic RCC'],
    status: 'Entidade da OMS 2022 ("outros tumores renais")',
    risk: 'intermediario',
    frequency: 2,
    summary:
      'Quase sempre em mulher: áreas sólidas e macrocísticas de células eosinofílicas volumosas com grânulos citoplasmáticos basofílicos grosseiros, cistos revestidos por células em tachinha, e o perfil invertido em relação aos outros oncocíticos: CK20 positiva com CK7 negativa.',
    keys: [
      'Componente sólido e cístico (macrocistos), células eosinofílicas volumosas de citoplasma granular.',
      'Grânulos citoplasmáticos basofílicos a anfofílicos grosseiros (estipulação), às vezes como "corpos de leishmania".',
      'Cistos revestidos por células em tachinha; células gigantes multinucleadas e xantomatosas podem aparecer.',
      'CK20+ (difusa ou focal) com CK7−; catepsina K ao menos focal; GPNMB+; vimentina+; CD117, GATA3 e L1CAM negativos.',
    ],
    ihc: 'CK20+, CK7−, CD117−, catepsina K focal, GPNMB+, vimentina+, CD10 variável, melan-A em raras células, GATA3−.',
    molecular: 'Perda bialélica somática de TSC2 (mais) ou TSC1; germinativa nos casos de esclerose tuberosa.',
    behavior: 'Indolente na maioria; metástases em 5 a 10%, em tumores maiores.',
    pitfalls: ['O "carcinoma oncocitoide após neuroblastoma" e o "RCC xantomatoso de células gigantes com TSC2" são o mesmo espectro.', 'Cerca de 10 a 15% são CK20 negativos: GPNMB e catepsina K ajudam.'],
    profile: merge(noDefiningLoss, {
      tfeb: { negativo: T, positivo: R },
      contexto: { tsc: P, 'neoplasia-infancia': P, 'drc-terminal': P, multifocal: P, bhd: R, hlrcc: R, 'sdh-sindrome': R, falciforme: R },
      idade: { adulto: T, idoso: C, jovem: C },
      sexo: { f: T, m: R },
      tamanho: { medio: T, pequeno: P, grande: P },
      arquitetura: { 'solido-cistica': T, solida: C, papilar: R, tubulocistica: R, mosaico: R, folicular: N, mista: P },
      'nucleo-grau': { nucleolo: C, baixo: C, 'macronucleolo-halo': R, alto: R },
      citoplasma: { 'granulos-basofilicos': T, 'oncocitico-homogeneo': C, 'vacuolos-grandes': P, 'claras-entremeadas': P, 'vacuolos-flocosos': R, 'palido-reticulado': R, mucina: N },
      nucleo: { 'redondo-regular': C, tachinha: C, multinucleacao: P, 'enrugado-halo': R, 'polaridade-reversa': N },
      achados: { 'macrofagos-espumosos': P, mastocitos: P, 'edematoso-ilhas': R, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, 'tubulos-aprisionados': R, psamomas: R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: R, mitoses: R, sarcomatoide: R, 'invasao-vascular': R },
      ck7: { 'negativa-isoladas': T, focal: R, difusa: N },
      cd117: { negativo: T, positivo: R },
      ck20: { positiva: T, negativa: R },
      'catepsina-k': { focal: C, difusa: C, negativa: R },
      gata3: { negativo: T, positivo: R },
      vimentina: { positiva: T, negativa: R },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: C, positiva: P },
      melanociticos: { negativo: C, positivo: P },
      pax8: { positivo: T, negativo: R },
      l1cam: { negativo: T, positivo: R },
      gpnmb: { positivo: T, negativo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      molecular: { 'mtor-tsc': T, 'perda-1-y': N, flcn: N, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': R, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['trpkov2026', 'trpkov2016esc', 'gups2021b', 'who2022'],
  },
  {
    id: 'eaml',
    short: 'eAML / PEComa',
    name: 'Angiomiolipoma epitelioide / PEComa epitelioide',
    aka: ['eAML', 'ePEComa', 'epithelioid angiomyolipoma'],
    status: 'Entidade da OMS 2022 (tumores mesenquimais do rim)',
    risk: 'intermediario',
    frequency: 2,
    summary:
      'O grande imitador de carcinoma eosinofílico: lençóis de células epitelioides com citoplasma abundante, nucléolo, inclusões e células tipo gânglio, muitas vezes com atipia, mitoses e necrose. PAX8 negativo com catepsina K difusa e HMB-45/Melan-A positivos resolve.',
    keys: [
      'Mais de 80% de células epitelioides; crescimento carcinoma-símile; gordura e vasos displásicos ao menos focais.',
      'Células tipo gânglio, multinucleação, inclusões nucleares; pode ter pleomorfismo, mitoses e necrose.',
      'PAX8 e queratinas negativos; catepsina K e GPNMB difusos; HMB-45 e Melan-A positivos.',
      'Metástase em cerca de 5%: tamanho > 7 cm, necrose, mitoses ≥ 2/10 CGA, atípicas, invasão venosa; TP53, RB1, ATRX.',
    ],
    ihc: 'PAX8−, pancitoqueratina−, catepsina K+ difusa, GPNMB+, HMB-45+, Melan-A+, actina de músculo liso variável.',
    molecular: 'Inativação de TSC2 ou TSC1 (esclerose tuberosa em parte); raros PEComas com fusão de TFE3.',
    behavior: 'Maioria benigna; cerca de 5% metastatizam, com os fatores de risco acima.',
    pitfalls: ['Em biópsia, um "carcinoma eosinofílico de alto grau" PAX8 negativo é eAML até prova em contrário.', 'O PEComa com TFE3 rearranjado tem TFE3 nuclear forte e difuso e lembra o carcinoma TFE3.'],
    profile: merge(noDefiningLoss, {
      tfe3: { negativo: C, positivo: R },
      contexto: { tsc: C, multifocal: P, bhd: R, hlrcc: R, 'sdh-sindrome': R, 'drc-terminal': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { adulto: T, jovem: C, idoso: C },
      sexo: { f: C, m: P },
      tamanho: { grande: C, medio: C, pequeno: P },
      arquitetura: { solida: T, mosaico: R, papilar: R, tubulocistica: N, 'solido-cistica': R, folicular: N, mista: P },
      'nucleo-grau': { nucleolo: C, alto: C, baixo: P, 'macronucleolo-halo': P },
      citoplasma: { 'oncocitico-homogeneo': C, 'claras-entremeadas': C, 'vacuolos-grandes': P, 'palido-reticulado': P, 'granulos-basofilicos': R, 'vacuolos-flocosos': R, mucina: N },
      nucleo: { multinucleacao: C, 'redondo-regular': P, 'enrugado-halo': R, 'polaridade-reversa': N, tachinha: R },
      achados: { 'adiposo-vasos': T, 'rede-vascular': P, 'edematoso-ilhas': R, 'cicatriz-central': R, mastocitos: R, 'tubulos-aprisionados': R, 'macrofagos-espumosos': R, psamomas: R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: C, mitoses: C, sarcomatoide: P, 'invasao-vascular': C },
      ck7: { 'negativa-isoladas': T, focal: R, difusa: N },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: N },
      'catepsina-k': { difusa: T, focal: R, negativa: N },
      gata3: { negativo: T, positivo: R },
      vimentina: { positiva: C, negativa: P },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: T, positiva: R },
      cd10: { negativo: C, positivo: P },
      melanociticos: { positivo: T, negativo: R },
      pax8: { negativo: T, positivo: N },
      l1cam: { negativo: C, positivo: R },
      gpnmb: { positivo: T, negativo: R },
      foxi1: { negativo: T, positivo: N },
      panck: { 'fraca-negativa': T, positiva: R },
      molecular: { 'mtor-tsc': T, 'tfe3-fusao': R, 'perda-1-y': N, flcn: N, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfeb-alt': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['trpkov2026', 'who2022', 'gups2021a'],
  },
  {
    id: 'fh',
    short: 'FH-deficiente',
    name: 'Carcinoma renal FH-deficiente',
    aka: ['FH-deficient RCC', 'carcinoma associado à leiomiomatose hereditária (HLRCC)'],
    status: 'Entidade molecularmente definida da OMS 2022',
    risk: 'alto',
    frequency: 1,
    summary:
      'Carcinoma agressivo de paciente jovem, com papilas, túbulos, cistos e áreas sólidas misturados e o macronucléolo eosinofílico com halo perinucleolar; a perda de FH com 2SC positivo define, e obriga aconselhamento genético. Também imita os oncocíticos de baixo grau, inclusive o SDH-deficiente.',
    keys: [
      'Padrões arquiteturais múltiplos no mesmo tumor: papilar, tubulocístico, sólido, cribriforme, em peneira.',
      'Macronucléolo eosinofílico com halo perinucleolar (tipo inclusão viral), ao menos focal.',
      'FH perdida (específica) e 2SC positivo nuclear e citoplasmático (sensível); AKR1B10 alternativa.',
      'Variante "oncocítica de baixo grau": sólida, de núcleo baixo e vacúolos, imita SDH-deficiente, com o mesmo perfil molecular.',
    ],
    ihc: 'FH perdida, 2SC+, AKR1B10+, CK7 geralmente negativa, CD117−, vimentina+, AMACR variável.',
    molecular: 'Inativação bialélica de FH, germinativa (HLRCC) ou, mais raramente, somática.',
    behavior: 'Agressivo, com apresentação em estádio alto na maioria; terapia com bevacizumabe e erlotinibe mostra resposta. Rastreamento familiar obrigatório.',
    pitfalls: ['Antes era "papilar tipo 2", "tubulocístico com desdiferenciação" ou "ducto coletor".', 'Perda heterogênea ou retenção de FH em mutações missense: 2SC positivo fecha.', 'Todo "tubulocístico" com áreas pobremente diferenciadas é FH-deficiente até prova em contrário.'],
    profile: merge(noDefiningLoss, {
      fh: { perdida: T, retida: R },
      twosc: { positiva: T, negativa: R },
      contexto: { hlrcc: T, multifocal: P, tsc: R, bhd: R, 'sdh-sindrome': R, 'drc-terminal': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { jovem: T, adulto: C, idoso: P },
      sexo: { f: C, m: C },
      tamanho: { grande: C, medio: C, pequeno: P },
      arquitetura: { papilar: T, mista: T, tubulocistica: C, solida: C, 'solido-cistica': P, mosaico: R, folicular: R },
      'nucleo-grau': { 'macronucleolo-halo': T, nucleolo: C, baixo: P, alto: C },
      citoplasma: { 'oncocitico-homogeneo': C, 'vacuolos-flocosos': P, 'vacuolos-grandes': P, 'claras-entremeadas': P, mucina: P, 'granulos-basofilicos': R, 'palido-reticulado': R },
      nucleo: { 'redondo-regular': P, tachinha: P, multinucleacao: P, 'enrugado-halo': R, 'polaridade-reversa': R },
      achados: { psamomas: P, 'macrofagos-espumosos': P, 'edematoso-ilhas': R, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: R, 'tubulos-aprisionados': R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: C, mitoses: C, sarcomatoide: P, 'invasao-vascular': C },
      ck7: { 'negativa-isoladas': C, focal: P, difusa: R },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { negativo: T, positivo: R },
      vimentina: { positiva: C, negativa: P },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { positiva: C, negativa: P },
      cd10: { positivo: P, negativo: P },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      gpnmb: { negativo: C, positivo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      molecular: { 'fh-mut': T, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, sdhx: N, 'perdas-multiplas': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['trpkov2026', 'trpkov2016fh', 'gups2021a', 'who2022'],
  },
  {
    id: 'alk',
    short: 'ALK',
    name: 'Carcinoma renal ALK-rearranjado',
    aka: ['ALK-rearranged RCC', 'ALK-RCC'],
    status: 'Entidade molecularmente definida da OMS 2022',
    risk: 'intermediario',
    frequency: 1,
    summary:
      'Tumor de morfologia variada (sólido, papilar, tubulocístico, cribriforme, células em anel de sinete, "mucinoso tubular e fusocelular-símile") com um achado que chama: mucina intracelular ou intersticial num tumor eosinofílico. ALK positivo na imuno (5A4, D5F3) define; há inibidores de ALK com resposta.',
    keys: [
      'Múltiplos padrões de crescimento no mesmo tumor, com células eosinofílicas e mucina intra ou extracelular.',
      'ALK positivo na imuno; FISH break-apart ou sequenciamento confirmam a fusão (VCL, TPM3, EML4, STRN, HOOK1 e outros).',
      'Fusão VCL-ALK em crianças com traço falciforme (morfologia medular-símile, mas INI1 retido).',
      'PAX8 e vimentina positivos; FH e INI1 retidos.',
    ],
    ihc: 'ALK+, PAX8+, vimentina+, FH e INI1 retidos, CK7 variável, AMACR variável.',
    molecular: 'Fusões de ALK com VCL, TPM3, EML4, STRN, CLIP1, KIF5B, PLEKHA7, SLIT1, TPM1 ou NUMA1.',
    behavior: 'Maioria indolente; metástase em 20 a 30%, com resposta a inibidores de ALK.',
    pitfalls: ['Em todo tumor eosinofílico de padrões variados com mucina que não fecha, faça ALK: há tratamento alvo.'],
    profile: merge(noDefiningLoss, {
      alk: { positivo: T, negativo: N },
      contexto: { falciforme: C, 'neoplasia-infancia': R, multifocal: R, tsc: R, bhd: R, hlrcc: R, 'sdh-sindrome': R, 'drc-terminal': R },
      idade: { jovem: C, adulto: C, idoso: P },
      sexo: { f: C, m: C },
      tamanho: { medio: C, grande: P, pequeno: P },
      arquitetura: { mista: T, papilar: C, solida: C, tubulocistica: C, 'solido-cistica': P, mosaico: R, folicular: R },
      'nucleo-grau': { nucleolo: C, baixo: P, 'macronucleolo-halo': P, alto: P },
      citoplasma: { mucina: T, 'oncocitico-homogeneo': C, 'vacuolos-grandes': P, 'claras-entremeadas': P, 'granulos-basofilicos': R, 'palido-reticulado': R, 'vacuolos-flocosos': R },
      nucleo: { 'redondo-regular': P, tachinha: P, multinucleacao: P, 'enrugado-halo': R, 'polaridade-reversa': R },
      achados: { psamomas: P, 'macrofagos-espumosos': P, 'edematoso-ilhas': R, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: P, 'tubulos-aprisionados': R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: P, mitoses: P, sarcomatoide: P, 'invasao-vascular': P },
      ck7: { focal: C, difusa: P, 'negativa-isoladas': P },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: C, positiva: P },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { negativo: C, positivo: P },
      vimentina: { positiva: T, negativa: R },
      caix: { 'negativa-focal': T, 'caixa-difusa': R },
      amacr: { positiva: C, negativa: P },
      cd10: { positivo: C, negativo: P },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      molecular: { 'alk-fusao': T, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['trpkov2026', 'gups2021b', 'who2022'],
  },
  {
    id: 'prnrp',
    short: 'PRNRP',
    name: 'Neoplasia renal papilar de polaridade reversa (PRNRP)',
    aka: ['PRNRP', 'papillary renal neoplasm with reverse polarity', 'carcinoma papilar oncocítico de núcleo baixo'],
    status: 'OMS 2022: dentro do carcinoma papilar, como padrão distinto; a literatura a trata como entidade própria',
    risk: 'benigno',
    frequency: 2,
    summary:
      'Tumor papilar pequeno, não encapsulado, de papilas delicadas revestidas por uma camada única de células oncocíticas com núcleos de baixo grau alinhados no polo apical, longe da base ("polaridade reversa"). GATA3 positivo com AMACR e vimentina negativos é o perfil, e a mutação de KRAS é quase constante. Sem relato de comportamento maligno.',
    keys: [
      'Papilas finas, camada única de células oncocíticas, núcleos apicais alinhados (polaridade reversa), baixo grau (OMS 1–2).',
      'Em geral < 1,5 cm (muitas vezes abaixo do corte do adenoma papilar), frequentemente cístico; sem necrose nem macrófagos espumosos em quantidade.',
      'GATA3+, L1CAM+, CK7+, queratina de alto peso+; AMACR e vimentina negativos.',
      'Mutação de KRAS (códon 12) na maioria; ganhos de 7 e 17 e perda de Y raros.',
    ],
    ihc: 'GATA3+, CK7+, L1CAM+, 34βE12+, AMACR−, vimentina−, CD117−.',
    molecular: 'KRAS em 70 a 90%; sem os ganhos de 7 e 17 típicos do papilar.',
    behavior: 'Indolente: nenhuma metástase relatada em algumas centenas de casos.',
    pitfalls: ['O papilar eosinofílico convencional tem núcleos basais, nucléolo, AMACR difuso e vimentina positiva, e pode ser agressivo.'],
    profile: merge(noDefiningLoss, {
      contexto: { multifocal: P, tsc: R, bhd: R, hlrcc: R, 'sdh-sindrome': R, 'drc-terminal': P, falciforme: R, 'neoplasia-infancia': R },
      idade: { idoso: T, adulto: C, jovem: R },
      sexo: { f: C, m: C },
      tamanho: { pequeno: T, medio: C, grande: R },
      arquitetura: { papilar: T, solida: R, tubulocistica: R, 'solido-cistica': P, mosaico: N, folicular: N, mista: R },
      'nucleo-grau': { baixo: T, nucleolo: R, 'macronucleolo-halo': N, alto: N },
      citoplasma: { 'oncocitico-homogeneo': T, 'vacuolos-grandes': R, 'vacuolos-flocosos': R, 'granulos-basofilicos': R, 'palido-reticulado': R, 'claras-entremeadas': R, mucina: N },
      nucleo: { 'polaridade-reversa': T, 'redondo-regular': T, 'enrugado-halo': R, tachinha: R, multinucleacao: R },
      achados: { 'macrofagos-espumosos': R, psamomas: R, 'edematoso-ilhas': R, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: R, 'tubulos-aprisionados': R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: N, mitoses: N, sarcomatoide: N, 'invasao-vascular': R },
      ck7: { difusa: T, focal: P, 'negativa-isoladas': R },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { positivo: T, negativo: R },
      vimentina: { negativa: T, positiva: R },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: T, positiva: R },
      cd10: { negativo: C, positivo: P },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      l1cam: { positivo: T, negativo: R },
      gpnmb: { negativo: C, positivo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      molecular: { kras: T, 'ganho-7-17': R, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N },
    }),
    sources: ['trpkov2026', 'alobaidy2019', 'gups2021b', 'who2022'],
  },
  {
    id: 'tcrcc',
    short: 'Tubulocístico',
    name: 'Carcinoma renal tubulocístico',
    aka: ['TC-RCC', 'tubulocystic RCC'],
    status: 'Entidade da OMS 2022',
    risk: 'baixo',
    frequency: 1,
    summary:
      'Massa esponjosa em plástico-bolha, feita só de túbulos e cistos de tamanhos variados revestidos por uma camada única de células eosinofílicas cuboides ou em tachinha com nucléolo proeminente, em estroma fibroso escasso. Homem adulto, indolente, mas qualquer área sólida ou pobremente diferenciada obriga a excluir FH-deficiente.',
    keys: [
      'Morfologia tubulocística pura, com estroma fibroso ou hipocelular mínimo entre os túbulos.',
      'Camada única de células eosinofílicas achatadas, cuboides ou em tachinha, com nucléolo proeminente (grau 3) e projeções apicais.',
      'AMACR, vimentina, CK7 e CD10 positivos; FH retida e 2SC negativo.',
      'Não se gradua: considerado indolente; perdas de 9 e Y e ganho de 17.',
    ],
    ihc: 'AMACR+, vimentina+, CK7+, CD10+, FH retida, 2SC−, CD117−.',
    molecular: 'Perdas de 9 e Y, ganho de 17; mutações em KMT2C e KDM5C em alguns.',
    behavior: 'Indolente nos casos puros (2 de 31 progrediram na série seminal); forte associação com rim terminal.',
    pitfalls: ['Mais de 80% dos "tubulocísticos com focos pobremente diferenciados" são FH-deficientes.'],
    profile: merge(noDefiningLoss, {
      contexto: { 'drc-terminal': P, multifocal: R, tsc: R, bhd: R, hlrcc: R, 'sdh-sindrome': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { adulto: T, idoso: C, jovem: P },
      sexo: { m: T, f: P },
      tamanho: { medio: C, pequeno: C, grande: P },
      arquitetura: { tubulocistica: T, papilar: R, solida: N, 'solido-cistica': P, mosaico: N, folicular: R, mista: R },
      'nucleo-grau': { nucleolo: T, baixo: P, 'macronucleolo-halo': R, alto: R },
      citoplasma: { 'oncocitico-homogeneo': T, 'vacuolos-grandes': R, 'vacuolos-flocosos': R, 'granulos-basofilicos': R, 'palido-reticulado': R, 'claras-entremeadas': R, mucina: N },
      nucleo: { tachinha: T, 'redondo-regular': C, 'enrugado-halo': R, 'polaridade-reversa': R, multinucleacao: R },
      achados: { 'edematoso-ilhas': R, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: R, 'tubulos-aprisionados': R, 'macrofagos-espumosos': R, psamomas: R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: R, mitoses: R, sarcomatoide: R, 'invasao-vascular': R },
      ck7: { difusa: C, focal: C, 'negativa-isoladas': P },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { negativo: T, positivo: R },
      vimentina: { positiva: T, negativa: R },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { positiva: T, negativa: R },
      cd10: { positivo: T, negativo: R },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      gpnmb: { negativo: C, positivo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      molecular: { 'ganho-7-17': P, 'fh-mut': N, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, sdhx: N, 'perdas-multiplas': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N },
    }),
    sources: ['trpkov2026', 'gups2021a', 'who2022'],
  },
  {
    id: 'tlfck',
    short: 'TLFCK',
    name: 'Carcinoma folicular tireoide-símile do rim (TLFCK)',
    aka: ['TLFCK', 'thyroid-like follicular carcinoma of kidney'],
    status: 'Entidade emergente da OMS 2022',
    risk: 'intermediario',
    frequency: 1,
    summary:
      'Tumor raro (cerca de 60 casos) de folículos cheios de coloide denso, revestidos por células eosinofílicas de núcleo uniforme, indistinguível do carcinoma folicular de tireoide no HE. TTF-1 e tireoglobulina negativos com PAX8 positivo separam da metástase tireoidiana, que é o diferencial principal.',
    keys: [
      'Folículos em dorso-a-dorso com coloide denso; focos papilares, ramificação e microcalcificações possíveis.',
      'Células eosinofílicas de núcleo uniforme (OMS 2–3); sem as características nucleares do papilar de tireoide.',
      'TTF-1 e tireoglobulina negativos; PAX8 positivo (como a tireoide: não ajuda sozinho).',
      'Fusão EWSR1::PATZ1 em parte dos casos; sem alteração recorrente definida.',
    ],
    ihc: 'PAX8+, TTF-1−, tireoglobulina−, demais marcadores variáveis.',
    molecular: 'EWSR1::PATZ1 em 3 de 8 casos indolentes e em 1 sarcomatoide; sem perfil de cópias recorrente.',
    behavior: 'Indolente na maioria; metástases para linfonodo, pulmão, retroperitônio, crânio e meninges em alguns, e três casos sarcomatoides com mortes.',
    pitfalls: ['Exclua metástase de carcinoma folicular ou papilar de tireoide e a "lesão rim atrófico-símile" (benigna, com atrofia e inflamação).', 'Parte dos casos relatados pode ser papilar com áreas foliculares.'],
    profile: merge(noDefiningLoss, {
      contexto: { multifocal: R, tsc: R, bhd: R, hlrcc: R, 'sdh-sindrome': R, 'drc-terminal': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { adulto: C, jovem: C, idoso: C },
      sexo: { f: C, m: P },
      tamanho: { medio: C, pequeno: P, grande: P },
      arquitetura: { folicular: T, papilar: P, solida: R, tubulocistica: R, 'solido-cistica': R, mosaico: N, mista: R },
      'nucleo-grau': { baixo: T, nucleolo: P, 'macronucleolo-halo': R, alto: R },
      citoplasma: { 'oncocitico-homogeneo': T, 'vacuolos-grandes': R, 'vacuolos-flocosos': R, 'granulos-basofilicos': R, 'palido-reticulado': R, 'claras-entremeadas': R, mucina: N },
      nucleo: { 'redondo-regular': T, 'enrugado-halo': R, 'polaridade-reversa': R, tachinha: R, multinucleacao: R },
      achados: { coloide: T, psamomas: P, 'edematoso-ilhas': R, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: R, 'tubulos-aprisionados': R, 'macrofagos-espumosos': R, oxalato: R, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: R, mitoses: R, sarcomatoide: R, 'invasao-vascular': R },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: C, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      vimentina: { positiva: C, negativa: P },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { negativa: C, positiva: P },
      cd10: { negativo: C, positivo: P },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      gpnmb: { negativo: C, positivo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      molecular: { 'ewsr1-patz1': C, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['trpkov2026', 'gups2021b', 'who2022'],
  },
  {
    id: 'ccrcc-eos',
    short: 'Células claras eosinofílico',
    name: 'Carcinoma renal de células claras, variante eosinofílica',
    aka: ['ccRCC eosinofílico', 'granular cell RCC (termo antigo)'],
    status: 'Entidade da OMS 2022 (padrão eosinofílico, geralmente de alto grau)',
    risk: 'alto',
    frequency: 3,
    summary:
      'O carcinoma renal mais comum, quando o citoplasma vira eosinofílico por grau alto, necrose ou hemorragia: ninhos entre uma rede de vasos finos sinusoidais, células claras entremeadas, nucléolo evidente. CA-IX membranoso difuso "em caixa" com vimentina e CD10 positivos, e CK7 e CD117 negativos, resolve.',
    keys: [
      'Ninhos e lençóis separados por rede delicada de vasos sinusoidais; áreas claras entremeadas; hemorragia e necrose comuns.',
      'Nucléolo evidente (OMS/ISUP 3) na maioria dos eosinofílicos; pleomorfismo, rabdoide ou sarcomatoide nos de grau 4.',
      'CA-IX membranoso difuso "em caixa", vimentina+, CD10+, PAX8+; CK7 e CD117 negativos.',
      'Perda de 3p e mutação de VHL; PBRM1, SETD2, BAP1.',
    ],
    ihc: 'CA-IX+ difuso em caixa, vimentina+, CD10+, PAX8+, CK7−, CD117−, AMACR variável, catepsina K−, GPNMB−.',
    molecular: 'Perda de 3p e inativação de VHL em quase todos; sem fusões ou perdas definidoras das outras entidades.',
    behavior: 'Depende de estádio e grau; a variante eosinofílica costuma ser de grau alto.',
    pitfalls: ['CA-IX perinecrótico focal aparece em qualquer tumor com necrose: só o padrão difuso em caixa conta.'],
    profile: merge(noDefiningLoss, {
      contexto: { 'drc-terminal': P, multifocal: P, tsc: R, bhd: R, hlrcc: R, 'sdh-sindrome': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { adulto: T, idoso: T, jovem: P },
      sexo: { m: C, f: C },
      tamanho: { grande: C, medio: C, pequeno: P },
      arquitetura: { solida: T, 'solido-cistica': C, papilar: R, tubulocistica: R, mosaico: P, folicular: N, mista: P },
      'nucleo-grau': { nucleolo: T, alto: C, 'macronucleolo-halo': P, baixo: R },
      citoplasma: { 'claras-entremeadas': T, 'oncocitico-homogeneo': C, 'vacuolos-grandes': P, 'granulos-basofilicos': R, 'palido-reticulado': R, 'vacuolos-flocosos': R, mucina: N },
      nucleo: { 'redondo-regular': P, tachinha: P, multinucleacao: P, 'enrugado-halo': R, 'polaridade-reversa': N },
      achados: { 'rede-vascular': T, psamomas: R, 'macrofagos-espumosos': R, 'edematoso-ilhas': R, 'cicatriz-central': R, 'adiposo-vasos': R, mastocitos: R, 'tubulos-aprisionados': R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: C, mitoses: C, sarcomatoide: P, 'invasao-vascular': C },
      ck7: { 'negativa-isoladas': T, focal: P, difusa: R },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { negativo: T, positivo: R },
      vimentina: { positiva: T, negativa: R },
      caix: { 'caixa-difusa': T, 'negativa-focal': R },
      amacr: { negativa: C, positiva: P },
      cd10: { positivo: T, negativo: R },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      l1cam: { negativo: C, positivo: R },
      gpnmb: { negativo: T, positivo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      molecular: { 'vhl-3p': T, 'perda-1-y': N, flcn: N, 'mtor-tsc': R, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'ganho-7-17': N },
    }),
    sources: ['who2022', 'gups2021a', 'amin2022'],
  },
  {
    id: 'prcc-eos',
    short: 'Papilar eosinofílico',
    name: 'Carcinoma renal papilar com células eosinofílicas',
    aka: ['papilar "tipo 2" (termo abandonado)', 'papilar oncocítico', 'eosinophilic papillary RCC'],
    status: 'Entidade da OMS 2022 (os "tipos" 1 e 2 foram abandonados)',
    risk: 'intermediario',
    frequency: 3,
    summary:
      'Papilas com eixo fibrovascular cheio de macrófagos espumosos, revestidas por células eosinofílicas de nucléolo evidente, com núcleos basais ou pseudoestratificados; AMACR difuso com vimentina positiva e trissomias de 7 e 17. Antes de fechar, exclua FH-deficiente, PRNRP e TFE3, que já estiveram escondidos aqui.',
    keys: [
      'Papilas e túbulos com macrófagos espumosos, corpos psamomatosos e hemossiderina.',
      'Células eosinofílicas colunares, núcleos basais ou pseudoestratificados com nucléolo; grau variável.',
      'AMACR difuso e forte, vimentina+, CD10+, CK7 variável (menos que no papilar de células pequenas).',
      'Ganhos de 7 e 17, perda de Y; FH retida, 2SC negativo, TFE3 negativo, GATA3 negativo.',
    ],
    ihc: 'AMACR+ difuso, vimentina+, CD10+, CK7 variável, GATA3−, CD117−, FH retida.',
    molecular: 'Trissomias de 7 e 17 e perda de Y; MET em parte; sem fusões definidoras.',
    behavior: 'Depende de estádio e grau; os eosinofílicos de alto grau são mais agressivos que o papilar clássico de células pequenas.',
    pitfalls: ['Núcleos apicais, baixo grau e GATA3+: PRNRP, não papilar.', 'Macronucléolo com halo e padrões misturados: FH-deficiente até prova em contrário.', 'Queratina fraca com psamomas em jovem: TFE3.'],
    profile: merge(noDefiningLoss, {
      contexto: { 'drc-terminal': P, multifocal: P, tsc: R, bhd: R, hlrcc: R, 'sdh-sindrome': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { adulto: T, idoso: T, jovem: P },
      sexo: { m: T, f: P },
      tamanho: { medio: C, grande: C, pequeno: C },
      arquitetura: { papilar: T, solida: P, tubulocistica: P, 'solido-cistica': P, mosaico: R, folicular: R, mista: P },
      'nucleo-grau': { nucleolo: T, baixo: P, 'macronucleolo-halo': P, alto: P },
      citoplasma: { 'oncocitico-homogeneo': T, 'claras-entremeadas': P, 'vacuolos-grandes': R, 'granulos-basofilicos': R, 'palido-reticulado': R, 'vacuolos-flocosos': R, mucina: R },
      nucleo: { 'redondo-regular': P, 'polaridade-reversa': R, tachinha: P, 'enrugado-halo': R, multinucleacao: P },
      achados: { 'macrofagos-espumosos': T, psamomas: C, 'edematoso-ilhas': R, 'cicatriz-central': R, 'rede-vascular': R, 'adiposo-vasos': R, mastocitos: R, 'tubulos-aprisionados': R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: C, mitoses: P, sarcomatoide: P, 'invasao-vascular': P },
      ck7: { difusa: C, focal: C, 'negativa-isoladas': P },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { negativo: T, positivo: R },
      vimentina: { positiva: T, negativa: R },
      caix: { 'negativa-focal': T, 'caixa-difusa': N },
      amacr: { positiva: T, negativa: R },
      cd10: { positivo: T, negativo: R },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      l1cam: { negativo: C, positivo: P },
      gpnmb: { negativo: C, positivo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      molecular: { 'ganho-7-17': T, kras: R, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N },
    }),
    sources: ['who2022', 'gups2021a', 'trpkov2026'],
  },
  {
    id: 'tfe3',
    short: 'TFE3',
    name: 'Carcinoma renal TFE3-rearranjado',
    aka: ['Xp11.2 translocation RCC', 'MiT family translocation RCC'],
    status: 'Entidade molecularmente definida da OMS 2022',
    risk: 'alto',
    frequency: 1,
    summary:
      'Carcinoma de criança e adulto jovem, com papilas e ninhos de células volumosas de citoplasma claro ou eosinofílico e corpos psamomatosos frequentes; a queratina fraca ou ausente confunde, e o TFE3 nuclear forte (ou o FISH) resolve. Catepsina K e GPNMB positivos em parte, melanocíticos em alguns.',
    keys: [
      'Papilar e em ninhos, células volumosas de citoplasma claro e eosinofílico, psamomas abundantes.',
      'Queratinas fracas ou negativas, PAX8 positivo; TFE3 nuclear forte e difuso; FISH break-apart confirma.',
      'Catepsina K em cerca de metade, GPNMB positivo, Melan-A ou HMB-45 em parte.',
      'Quimioterapia na infância em alguns; fusões ASPSCR1, PRCC, SFPQ, NONO e outras.',
    ],
    ihc: 'TFE3 nuclear+, PAX8+, pancitoqueratina fraca ou negativa, catepsina K ~50%, GPNMB+, CD10+, CK7−.',
    molecular: 'Fusões de TFE3 (Xp11.2) com ASPSCR1, PRCC, SFPQ, NONO, RBM10, MED15 e outros.',
    behavior: 'Variável; em adulto, estádio alto e metástase linfonodal são frequentes.',
    pitfalls: ['A imuno de TFE3 só vale com marcação nuclear forte e difusa com controle negativo limpo; na dúvida, FISH.', 'O PEComa com TFE3 rearranjado é PAX8 negativo.'],
    profile: merge(noDefiningLoss, {
      tfe3: { positivo: T, negativo: N },
      contexto: { 'neoplasia-infancia': C, multifocal: R, tsc: R, bhd: R, hlrcc: R, 'sdh-sindrome': R, 'drc-terminal': R, falciforme: R },
      idade: { jovem: T, adulto: C, idoso: P },
      sexo: { f: C, m: P },
      tamanho: { medio: C, grande: C, pequeno: P },
      arquitetura: { papilar: T, solida: C, mista: C, 'solido-cistica': P, tubulocistica: R, mosaico: P, folicular: N },
      'nucleo-grau': { nucleolo: T, alto: P, baixo: P, 'macronucleolo-halo': P },
      citoplasma: { 'claras-entremeadas': T, 'oncocitico-homogeneo': C, 'vacuolos-grandes': P, 'granulos-basofilicos': R, 'palido-reticulado': R, 'vacuolos-flocosos': R, mucina: R },
      nucleo: { 'redondo-regular': P, tachinha: P, multinucleacao: P, 'polaridade-reversa': R, 'enrugado-halo': R },
      achados: { psamomas: T, 'macrofagos-espumosos': P, 'rede-vascular': R, 'edematoso-ilhas': R, 'cicatriz-central': R, 'adiposo-vasos': R, mastocitos: R, 'tubulos-aprisionados': R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: P, mitoses: P, sarcomatoide: R, 'invasao-vascular': C },
      ck7: { 'negativa-isoladas': T, focal: P, difusa: R },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { focal: C, difusa: P, negativa: P },
      gata3: { negativo: T, positivo: R },
      vimentina: { positiva: P, negativa: P },
      caix: { 'negativa-focal': T, 'caixa-difusa': R },
      amacr: { positiva: C, negativa: P },
      cd10: { positivo: C, negativo: P },
      melanociticos: { positivo: P, negativo: C },
      pax8: { positivo: T, negativo: R },
      gpnmb: { positivo: T, negativo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { 'fraca-negativa': C, positiva: C },
      molecular: { 'tfe3-fusao': T, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfeb-alt': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['who2022', 'gups2021a', 'akgul2026'],
  },
  {
    id: 'tfeb',
    short: 'TFEB',
    name: 'Carcinoma renal TFEB-alterado (rearranjado ou amplificado)',
    aka: ['t(6;11) RCC', 'TFEB-translocation RCC', 'TFEB-amplified RCC'],
    status: 'Entidade molecularmente definida da OMS 2022',
    risk: 'intermediario',
    frequency: 1,
    summary:
      'O rearranjado é o tumor bifásico de jovem: ninhos de células grandes eosinofílicas ou claras e grupos de células pequenas ao redor de material hialino, com melanocíticos e catepsina K difusos e queratinas fracas. O amplificado é de idoso, eosinofílico, oncocítico ou papilar, e agressivo. TFEB nuclear ou o FISH (break-apart e número de cópias) definem.',
    keys: [
      'Rearranjado: padrão bifásico com células pequenas em torno de membrana basal hialina; HMB-45, Melan-A e catepsina K difusos.',
      'Amplificado: paciente idoso, morfologia eosinofílica oncocítica ou papilar, alto grau, agressivo; marcadores melanocíticos variáveis.',
      'TFEB nuclear na imuno; FISH break-apart (rearranjo) ou amplificação.',
      'Queratinas fracas ou negativas; PAX8 positivo; GPNMB difuso.',
    ],
    ihc: 'TFEB nuclear+, catepsina K+ difusa, HMB-45+, Melan-A+, GPNMB+, PAX8+, pancitoqueratina fraca, CK7−.',
    molecular: 'Fusão MALAT1::TFEB (t(6;11)) ou amplificação de 6p21 (TFEB e VEGFA).',
    behavior: 'Rearranjado: indolente na maioria; amplificado: agressivo.',
    pitfalls: ['Imita o ESC (ambos GPNMB e catepsina K positivos): o ESC é CK20+ e TFEB negativo.', 'Marcadores melanocíticos positivos num tumor PAX8+ excluem eAML.'],
    profile: merge(noDefiningLoss, {
      tfeb: { positivo: T, negativo: N },
      contexto: { 'neoplasia-infancia': P, multifocal: R, tsc: R, bhd: R, hlrcc: R, 'sdh-sindrome': R, 'drc-terminal': R, falciforme: R },
      idade: { jovem: C, adulto: C, idoso: C },
      sexo: { f: C, m: C },
      tamanho: { medio: C, grande: C, pequeno: P },
      arquitetura: { solida: C, mista: C, papilar: P, 'solido-cistica': P, tubulocistica: R, mosaico: P, folicular: N },
      'nucleo-grau': { nucleolo: C, baixo: C, alto: P, 'macronucleolo-halo': P },
      citoplasma: { 'claras-entremeadas': C, 'oncocitico-homogeneo': C, 'vacuolos-grandes': P, 'granulos-basofilicos': R, 'palido-reticulado': R, 'vacuolos-flocosos': R, mucina: R },
      nucleo: { 'redondo-regular': C, tachinha: R, multinucleacao: P, 'polaridade-reversa': R, 'enrugado-halo': R },
      achados: { psamomas: P, 'rede-vascular': R, 'edematoso-ilhas': R, 'cicatriz-central': R, 'adiposo-vasos': R, mastocitos: R, 'tubulos-aprisionados': R, 'macrofagos-espumosos': R, oxalato: R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: P, mitoses: P, sarcomatoide: R, 'invasao-vascular': P },
      ck7: { 'negativa-isoladas': T, focal: P, difusa: R },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { difusa: T, focal: P, negativa: R },
      gata3: { negativo: T, positivo: R },
      vimentina: { positiva: P, negativa: P },
      caix: { 'negativa-focal': T, 'caixa-difusa': R },
      amacr: { positiva: P, negativa: P },
      cd10: { positivo: P, negativo: P },
      melanociticos: { positivo: T, negativo: R },
      pax8: { positivo: T, negativo: R },
      gpnmb: { positivo: T, negativo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { 'fraca-negativa': C, positiva: C },
      molecular: { 'tfeb-alt': T, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'vhl-3p': N, 'ganho-7-17': N },
    }),
    sources: ['who2022', 'gups2021a', 'akgul2026'],
  },
  {
    id: 'acd',
    short: 'Doença cística adquirida',
    name: 'Carcinoma renal associado à doença cística adquirida',
    aka: ['ACD-RCC', 'acquired cystic disease-associated RCC'],
    status: 'Entidade da OMS 2022',
    risk: 'baixo',
    frequency: 2,
    summary:
      'O carcinoma do rim terminal em diálise prolongada: células eosinofílicas volumosas de nucléolo evidente em arranjos sólidos, papilares, císticos e em peneira (cribriforme), com cristais de oxalato de cálcio entre as células, que são a assinatura. Frequentemente múltiplo e bilateral.',
    keys: [
      'Rim terminal com doença cística adquirida; tumor em cisto ou no parênquima, muitas vezes múltiplo.',
      'Padrões sólido, papilar, cístico, microcístico e em peneira (cribriforme); células eosinofílicas de nucléolo proeminente.',
      'Cristais de oxalato de cálcio intratumorais (birrefringentes).',
      'AMACR, CD10 e vimentina positivos; CK7 negativa; CA-IX e CD117 negativos.',
    ],
    ihc: 'AMACR+, CD10+, vimentina+, PAX8+, CK7−, CA-IX−, CD117−.',
    molecular: 'Ganhos de 3, 7, 16 e 17, perda de Y; sem alteração definidora.',
    behavior: 'Indolente na maioria; metástases em pequena parte, sobretudo com sarcomatoide ou rabdoide.',
    pitfalls: ['O rim terminal também abriga papilar, células claras, LOT e ESC: os cristais de oxalato é que apontam para cá.'],
    profile: merge(noDefiningLoss, {
      contexto: { 'drc-terminal': T, multifocal: C, tsc: R, bhd: R, hlrcc: R, 'sdh-sindrome': R, falciforme: R, 'neoplasia-infancia': R },
      idade: { adulto: T, idoso: C, jovem: P },
      sexo: { m: C, f: P },
      tamanho: { medio: C, pequeno: C, grande: P },
      arquitetura: { solida: C, papilar: C, 'solido-cistica': C, tubulocistica: P, mosaico: R, folicular: N, mista: C },
      'nucleo-grau': { nucleolo: T, baixo: P, 'macronucleolo-halo': P, alto: P },
      citoplasma: { 'oncocitico-homogeneo': T, 'vacuolos-grandes': P, 'claras-entremeadas': P, 'granulos-basofilicos': R, 'palido-reticulado': R, 'vacuolos-flocosos': R, mucina: N },
      nucleo: { 'redondo-regular': P, tachinha: P, multinucleacao: P, 'enrugado-halo': R, 'polaridade-reversa': R },
      achados: { oxalato: T, psamomas: P, 'macrofagos-espumosos': P, 'rede-vascular': R, 'edematoso-ilhas': R, 'cicatriz-central': R, 'adiposo-vasos': R, mastocitos: R, 'tubulos-aprisionados': R, coloide: N, 'oncocitose-adjacente': R },
      'alto-grau': { necrose: P, mitoses: P, sarcomatoide: P, 'invasao-vascular': P },
      ck7: { 'negativa-isoladas': T, focal: P, difusa: R },
      cd117: { negativo: T, positivo: R },
      ck20: { negativa: T, positiva: R },
      'catepsina-k': { negativa: T, focal: R, difusa: N },
      gata3: { negativo: T, positivo: R },
      vimentina: { positiva: T, negativa: R },
      caix: { 'negativa-focal': T, 'caixa-difusa': R },
      amacr: { positiva: T, negativa: R },
      cd10: { positivo: T, negativo: R },
      melanociticos: { negativo: T, positivo: N },
      pax8: { positivo: T, negativo: R },
      l1cam: { negativo: C, positivo: P },
      gpnmb: { negativo: C, positivo: R },
      foxi1: { negativo: T, positivo: R },
      panck: { positiva: T, 'fraca-negativa': R },
      molecular: { 'ganho-7-17': P, 'perda-1-y': N, flcn: N, 'mtor-tsc': N, sdhx: N, 'perdas-multiplas': N, 'fh-mut': N, 'alk-fusao': N, kras: N, 'ewsr1-patz1': N, 'tfe3-fusao': N, 'tfeb-alt': N, 'vhl-3p': N },
    }),
    sources: ['who2022', 'gups2021a'],
  },
]

/* ---- Esquema ------------------------------------------------------------------------ */

export const renalOncocytic: Algorithm = {
  id: 'oncociticos-renais',
  name: 'Neoplasias oncocíticas e eosinofílicas do rim',
  summary: 'Do oncocitoma e cromófobo às entidades novas da OMS 2022 (LOT, EVT, ESC, SDH, FH, ALK, PRNRP, FLCN): responda o que a lâmina e a imuno mostram e veja quem sobra.',
  scope:
    'Tumor renal de citoplasma eosinofílico ou oncocítico, de qualquer grau, que não é obviamente um oncocitoma nem um cromófobo clássico. Cobre os tumores sólidos e os papilares ou tubulocísticos, os benignos, os de risco intermediário e os agressivos, e os mimetizadores mesenquimais (angiomiolipoma epitelioide).',
  system: 'Rim',
  revised: 'Outubro de 2026',
  advice: [
    'Painel inicial: CK7 e CD117 (KIT). Nos oncocíticos sólidos de baixo grau, isso já separa oncocitoma (CK7 isoladas, CD117+), cromófobo eosinofílico (CK7 difusa, CD117+) e LOT (CK7 difusa, CD117−).',
    'Em todo tumor eosinofílico de difícil classificação, sobretudo em paciente jovem, acrescente SDHB e FH (com 2SC): as duas perdas definem entidades hereditárias e obrigam aconselhamento genético.',
    'PAX8 negativo num "carcinoma eosinofílico de alto grau" é angiomiolipoma epitelioide até prova em contrário: peça catepsina K e HMB-45/Melan-A.',
    'Padrões arquiteturais misturados com mucina pedem ALK; padrões misturados com macronucléolo e halo pedem FH e 2SC.',
    'GPNMB marca ativação de mTOR e da via MiT (LOT, EVT, ESC, FLCN, eAML, TFE3, TFEB) e é negativo em oncocitoma, cromófobo e células claras: útil como triagem, não como diagnóstico.',
  ],
  fallback:
    'Se nada fecha, a OMS 2022 admite "neoplasia oncocítica renal de baixo potencial maligno, não classificada" para o tumor de baixo grau esporádico, e "carcinoma renal não classificado" para o de alto grau. Antes de usar o escape, confira SDHB, FH e, se houver padrões variados, ALK e TFE3.',
  questions,
  entities,
  schema: [
    {
      id: 'arquitetura',
      title: 'Primeira divisão: como o tumor cresce',
      branches: [
        { id: 'solido-baixo', label: 'Sólido, oncocítico, de baixo grau', when: [{ question: 'arquitetura', options: ['solida'] }, { question: 'nucleo-grau', options: ['baixo'] }], leads: ['ro', 'chrcc-eos', 'lot', 'flcn', 'sdh'], note: 'CK7 e CD117 separam os três primeiros; SDHB para o último, principalmente em jovem.' },
        { id: 'solido-vacuolos', label: 'Sólido com vacúolos grandes e nucléolo evidente', when: [{ question: 'arquitetura', options: ['solida'] }, { question: 'citoplasma', options: ['vacuolos-grandes'] }], leads: ['evt', 'sdh', 'flcn'], note: 'CD117+ com CK7− e catepsina K focal: EVT. SDHB perdida: SDH-deficiente.' },
        { id: 'solido-cistico-granulos', label: 'Sólido e cístico com grânulos basofílicos, em mulher', when: [{ question: 'arquitetura', options: ['solido-cistica', 'solida'] }, { question: 'citoplasma', options: ['granulos-basofilicos'] }], leads: ['esc'], note: 'CK20+ com CK7− fecha; TFEB negativo afasta o mimetizador.' },
        { id: 'papilar-tubulo', label: 'Papilar ou tubulocístico', when: [{ question: 'arquitetura', options: ['papilar', 'tubulocistica'] }], leads: ['prnrp', 'prcc-eos', 'fh', 'tcrcc', 'alk', 'tfe3'], note: 'Núcleos apicais e GATA3+: PRNRP. Macronucléolo com halo: FH e 2SC. Mucina: ALK. Queratina fraca com psamomas: TFE3.' },
        { id: 'mosaico', label: 'Mosaico de células oncocíticas e claras', when: [{ question: 'arquitetura', options: ['mosaico'] }], leads: ['flcn', 'chrcc-eos', 'tfeb'], note: 'Múltiplos tumores e oncocitose adjacente: Birt-Hogg-Dubé (FLCN).' },
        { id: 'folicular', label: 'Folicular com coloide', when: [{ question: 'arquitetura', options: ['folicular'] }], leads: ['tlfck'], note: 'TTF-1 e tireoglobulina negativos excluem metástase de tireoide.' },
        { id: 'misto', label: 'Vários padrões misturados', when: [{ question: 'arquitetura', options: ['mista'] }], leads: ['fh', 'alk', 'acd', 'tfe3'], note: 'FH e 2SC primeiro; ALK se houver mucina; oxalato aponta para o rim terminal.' },
        { id: 'alto-grau', label: 'Pleomórfico, carcinoma-símile', when: [{ question: 'nucleo-grau', options: ['alto'] }], leads: ['eaml', 'ccrcc-eos', 'fh', 'sdh', 'tfeb'], note: 'PAX8 e catepsina K: eAML. CA-IX em caixa: células claras. FH e SDHB: os hereditários desdiferenciados.' },
      ],
    },
    {
      id: 'ck7-cd117',
      title: 'Oncocítico sólido: CK7 × CD117',
      branches: [
        { id: 'ro', label: 'CK7 negativa ou isolada, CD117 positivo', when: [{ question: 'ck7', options: ['negativa-isoladas'] }, { question: 'cd117', options: ['positivo'] }], leads: ['ro', 'evt'], note: 'Oncocitoma; se houver vacúolos e nucléolo, EVT (catepsina K focal, CD10+).' },
        { id: 'chrcc', label: 'CK7 difusa, CD117 positivo', when: [{ question: 'ck7', options: ['difusa'] }, { question: 'cd117', options: ['positivo'] }], leads: ['chrcc-eos'], note: 'Cromófobo eosinofílico: procure o núcleo em passa e a binucleação.' },
        { id: 'lot', label: 'CK7 difusa, CD117 negativo', when: [{ question: 'ck7', options: ['difusa'] }, { question: 'cd117', options: ['negativo'] }], leads: ['lot', 'prnrp'], note: 'LOT: confirme com GATA3+ e FOXI1−. Se for papilar com núcleos apicais, PRNRP.' },
        { id: 'duplo-negativo', label: 'CK7 negativa ou isolada, CD117 negativo', when: [{ question: 'ck7', options: ['negativa-isoladas'] }, { question: 'cd117', options: ['negativo'] }], leads: ['sdh', 'esc', 'eaml', 'fh', 'ccrcc-eos', 'tfe3', 'tfeb'], note: 'Peça SDHB, CK20, PAX8 com catepsina K, FH com 2SC e CA-IX.' },
        { id: 'mosaico-ihc', label: 'CK7 e CD117 em populações diferentes (mosaico)', when: [{ question: 'ck7', options: ['focal'] }, { question: 'cd117', options: ['positivo'] }], leads: ['flcn', 'chrcc-eos'], note: 'Imuno mutuamente exclusiva: tumor híbrido FLCN-mutado.' },
      ],
    },
    {
      id: 'definidores',
      title: 'Marcadores que definem a entidade',
      branches: [
        { id: 'sdhb', label: 'SDHB perdida', when: [{ question: 'sdhb', options: ['perdida'] }], leads: ['sdh'], note: 'Confirme o controle interno; encaminhe para aconselhamento genético.' },
        { id: 'fh', label: 'FH perdida ou 2SC positivo', when: [{ question: 'fh', options: ['perdida'] }], leads: ['fh'], note: 'Mesmo com morfologia de baixo grau: FH-deficiente.' },
        { id: 'twosc', label: '2SC positivo com FH retida', when: [{ question: 'twosc', options: ['positiva'] }, { question: 'fh', options: ['retida'] }], leads: ['fh'], note: 'Mutação missense com proteína não funcional: ainda é FH-deficiente.' },
        { id: 'alk', label: 'ALK positivo', when: [{ question: 'alk', options: ['positivo'] }], leads: ['alk'], note: 'Confirme com FISH ou sequenciamento; há inibidores de ALK.' },
        { id: 'tfe3', label: 'TFE3 nuclear', when: [{ question: 'tfe3', options: ['positivo'] }], leads: ['tfe3', 'eaml'], note: 'PAX8+ é carcinoma; PAX8− é PEComa com TFE3.' },
        { id: 'tfeb', label: 'TFEB nuclear', when: [{ question: 'tfeb', options: ['positivo'] }], leads: ['tfeb'], note: 'Rearranjo (jovem, bifásico) ou amplificação (idoso, agressivo).' },
        { id: 'pax8neg', label: 'PAX8 negativo com catepsina K difusa', when: [{ question: 'pax8', options: ['negativo'] }, { question: 'catepsina-k', options: ['difusa'] }], leads: ['eaml'], note: 'HMB-45 e Melan-A fecham o angiomiolipoma epitelioide.' },
        { id: 'caix', label: 'CA-IX membranoso difuso em caixa', when: [{ question: 'caix', options: ['caixa-difusa'] }], leads: ['ccrcc-eos'], note: 'Com vimentina e CD10 positivos: células claras eosinofílico.' },
        { id: 'ck20', label: 'CK20 positiva com CK7 negativa', when: [{ question: 'ck20', options: ['positiva'] }, { question: 'ck7', options: ['negativa-isoladas'] }], leads: ['esc'], note: 'Único oncocítico renal com esse perfil.' },
        { id: 'gata3-papilar', label: 'Papilar com GATA3 positivo e AMACR negativo', when: [{ question: 'arquitetura', options: ['papilar'] }, { question: 'gata3', options: ['positivo'] }, { question: 'amacr', options: ['negativa'] }], leads: ['prnrp'], note: 'KRAS mutado confirma, mas não é obrigatório.' },
        { id: 'ttf1neg', label: 'Folicular com TTF-1 e tireoglobulina negativos', when: [{ question: 'arquitetura', options: ['folicular'] }, { question: 'ttf1', options: ['negativo'] }], leads: ['tlfck'], note: 'PAX8 não ajuda: é positivo nos dois.' },
      ],
    },
  ],
  sources: [
    { id: 'trpkov2026', label: 'Trpkov K, Siadat F, Saleeb R. Recent developments in eosinophilic renal neoplasms: what’s new, true and important? Histopathology 2026;88:166–192.', url: 'https://doi.org/10.1111/his.70001' },
    { id: 'who2022', label: 'WHO Classification of Tumours Editorial Board. Urinary and male genital tumours. 5th ed. Lyon: IARC; 2022 (WHO classification of tumours series, vol. 8).' },
    { id: 'gups2021a', label: 'Trpkov K, Hes O, Williamson SR, et al. New developments in existing WHO entities and evolving molecular concepts: the Genitourinary Pathology Society (GUPS) update on renal neoplasia. Mod Pathol 2021;34:1392–1424.', url: 'https://doi.org/10.1038/s41379-021-00779-w' },
    { id: 'gups2021b', label: 'Trpkov K, Williamson SR, Gill AJ, et al. Novel, emerging and provisional renal entities: the Genitourinary Pathology Society (GUPS) update on renal neoplasia. Mod Pathol 2021;34:1167–1184.', url: 'https://doi.org/10.1038/s41379-021-00737-6' },
    { id: 'amin2022', label: 'Amin MB, McKenney JK, Martignoni G, Campbell SC, Pal S, Tickoo SK. Low grade oncocytic tumors of the kidney: a clinically relevant approach for the workup and accurate diagnosis. Mod Pathol 2022;35:1306–1316.', url: 'https://doi.org/10.1038/s41379-022-01108-5' },
    { id: 'hes2022', label: 'Hes O, Trpkov K. Do we need an updated classification of oncocytic renal tumors? Emergence of low-grade oncocytic tumor (LOT) and eosinophilic vacuolated tumor (EVT) as novel renal entities. Mod Pathol 2022;35:1140–1150.', url: 'https://doi.org/10.1038/s41379-022-01057-z' },
    { id: 'akgul2026', label: 'Akgul M, et al. Molecularly defined renal cell carcinomas: practical approaches for surgical pathologists. Histopathology 2026.', url: 'https://doi.org/10.1111/his.70039' },
    { id: 'trpkov2019', label: 'Trpkov K, Williamson SR, Gao Y, et al. Low-grade oncocytic tumour of kidney (CD117-negative, cytokeratin 7-positive): a distinct entity? Histopathology 2019;75:174–184.' },
    { id: 'he2018', label: 'He H, Trpkov K, Martinek P, et al. "High-grade oncocytic renal tumor": morphologic, immunohistochemical, and molecular genetic study of 14 cases. Virchows Arch 2018;473:725–738.' },
    { id: 'williamson2015', label: 'Williamson SR, Eble JN, Amin MB, et al. Succinate dehydrogenase-deficient renal cell carcinoma: detailed characterization of 11 tumors defining a unique subtype of renal cell carcinoma. Mod Pathol 2015;28:80–94.' },
    { id: 'trpkov2016fh', label: 'Trpkov K, Hes O, Agaimy A, et al. Fumarate hydratase-deficient renal cell carcinoma is strongly correlated with fumarate hydratase mutation and hereditary leiomyomatosis and renal cell carcinoma syndrome. Am J Surg Pathol 2016;40:865–875.' },
    { id: 'trpkov2016esc', label: 'Trpkov K, Hes O, Bonert M, et al. Eosinophilic, solid, and cystic renal cell carcinoma: clinicopathologic study of 16 unique, sporadic neoplasms occurring in women. Am J Surg Pathol 2016;40:60–71.' },
    { id: 'alobaidy2019', label: 'Al-Obaidy KI, Eble JN, Cheng L, et al. Papillary renal neoplasm with reverse polarity: a morphologic, immunohistochemical, and molecular study. Am J Surg Pathol 2019;43:1099–1111.' },
  ],
}
