/* ==========================================================================
   boneneural.ts — o resto da área de partes moles e osso: tumores de
   bainha neural, tumores de células pequenas e redondas (Ewing, CIC, BCOR,
   DSRCT, rabdoide), tumores neuroblásticos e paragangliomas, e os tumores
   ósseos (osteogênicos, condrogênicos, células gigantes, cordoma,
   adamantinoma).

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Soft Tissue and Bone, 2020; Goldblum, Folpe & Weiss;
   Hornick, Practical Soft Tissue Pathology; revisões de imuno-histoquímica
   em Am J Surg Pathol, Mod Pathol e Histopathology). As fontes estão como
   referência de texto: as séries originais não foram abertas uma a uma, e
   citar URL sem conferir já custou caro neste projeto.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Soft Tissue and Bone Tumours (2020)'
const WEISS = "Goldblum, Folpe & Weiss, Enzinger & Weiss's Soft Tissue Tumors, 7ª ed."
const HORNICK = 'Hornick, Practical Soft Tissue Pathology: A Diagnostic Approach, 2ª ed.'

export const boneneural: Tumor[] = [
  /* ---- Células pequenas e redondas ------------------------------------------ */
  {
    id: 'sarcoma-ewing',
    name: 'Sarcoma de Ewing',
    aka: ['Ewing sarcoma', 'PNET (nome antigo)', 'sarcoma de Ewing com fusão FET::ETS'],
    behavior: 'maligno',
    sites: [
      { site: 'osso', role: 'primario', freq: 3 },
      { site: 'partes-moles', role: 'primario', freq: 2 },
      { site: 'pleura', role: 'primario', freq: 1 },
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'medula-ossea', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas'],
    architecture: ['lencois', 'rosetas', 'ninhos'],
    features: ['necrose', 'mitoses-altas', 'glicogenio', 'corpos-apoptoticos'],
    ages: ['crianca', 'jovem'],
    summary: 'Lençóis monótonos de células pequenas redondas de cromatina fina, citoplasma escasso rico em glicogênio e membranas bem definidas, na diáfise de ossos longos ou na pelve de crianças e adolescentes.',
    criteria: [
      'População uniforme de células pequenas redondas, com cromatina finamente granular e nucléolo inconspícuo.',
      'CD99 membranoso forte e difuso mais NKX2.2 nuclear: a dupla que sustenta o diagnóstico.',
      'Confirmação molecular obrigatória: fusão de um gene FET (EWSR1, raramente FUS) com um gene ETS (FLI1 em 85%, ERG em 10%).',
      'Excluir os outros sarcomas de células redondas, que hoje são entidades próprias (CIC, BCOR) e respondem diferente à quimioterapia.',
    ],
    markers: [
      { marker: 'cd99', pct: [95, 100], pattern: 'M', note: 'membranoso forte e difuso; o padrão importa tanto quanto a positividade' },
      { marker: 'nkx22', pct: [90, 95], note: 'nuclear; também positiva em neuroendócrinos e no condrossarcoma mesenquimal' },
      { marker: 'fli1', pct: [70, 90], note: 'nuclear, refletindo a fusão mais comum; positiva também em vasculares e linfócitos' },
      { marker: 'erg', pct: [5, 15], note: 'nos casos com EWSR1::ERG' },
      { marker: 'ae1ae3', pct: [20, 30], note: 'focal em parte dos casos: não converta em carcinoma' },
      { marker: 'sinaptofisina', pct: [20, 40], note: 'focal; mais na antiga variante PNET' },
      { marker: 'cromogranina', pct: [0, 15] },
      { marker: 'insm1', pct: [20, 50], note: 'armadilha com carcinoma neuroendócrino' },
      { marker: 's100', pct: [10, 30] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'miogenina', pct: [0, 5], note: 'negativa: separa do rabdomiossarcoma' },
      { marker: 'myod1', pct: [0, 5] },
      { marker: 'cd45', pct: 0, note: 'negativo: separa do linfoma linfoblástico' },
      { marker: 'tdt', pct: [0, 5] },
      { marker: 'wt1', pct: [0, 10], note: 'negativo (C-terminal): separa do DSRCT' },
      { marker: 'bcor', pct: [0, 10], note: 'negativo: separa do sarcoma BCOR' },
      { marker: 'etv4', pct: [0, 10], note: 'negativo: separa do sarcoma CIC' },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Sarcoma CIC-rearranjado: CD99 focal, WT1 e ETV4/DUX4 positivos, mais pleomorfismo, adulto e partes moles.',
      'Sarcoma BCOR: BCOR e SATB2 positivos, CD99 fraco, células fusiformes em áreas.',
      'Rabdomiossarcoma alveolar: miogenina e MyoD1 difusas.',
      'Linfoma linfoblástico: CD45, TdT e CD99 (citoplasmático) positivos.',
      'Neuroblastoma: PHOX2B e TH positivos, CD99 negativo, criança pequena com neurópilo.',
      'Carcinoma de células de Merkel e pequenas células: CK20 em dot, TTF-1, INSM1 difusa.',
    ],
    pitfalls: ['CD99 é positivo em linfoblástico, sarcoma sinovial, TFS e outros: só vale com o padrão membranoso e um segundo marcador.', 'Queratina focal aparece em até 30% e já levou a diagnóstico de carcinoma indiferenciado.'],
    molecular: 'EWSR1::FLI1 por t(11;22) em cerca de 85%, EWSR1::ERG em 10%, outras fusões FET::ETS no restante.',
    sources: [WHO, WEISS, 'Yoshida et al., Am J Surg Pathol 2012 (NKX2.2 no sarcoma de Ewing)'],
  },
  {
    id: 'sarcoma-cic',
    name: 'Sarcoma com rearranjo de CIC',
    aka: ['CIC::DUX4 sarcoma', 'sarcoma CIC-rearranjado', 'Ewing-like sarcoma (nome antigo)'],
    behavior: 'maligno',
    sites: [
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'retroperitoneo', role: 'primario', freq: 1 },
      { site: 'encefalo', role: 'primario', freq: 1 },
      { site: 'osso', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'epitelioide', 'pleomorfico'],
    architecture: ['lencois', 'lobular'],
    features: ['necrose', 'mitoses-altas', 'estroma-mixoide', 'nucleolo'],
    ages: ['jovem', 'adulto'],
    summary: 'Sarcoma de células redondas e epitelioides mais pleomórfico e menos monótono que o Ewing, com nucléolo evidente, focos mixoides e necrose extensa, em partes moles profundas de adultos jovens.',
    criteria: [
      'Células redondas a epitelioides com algum pleomorfismo, nucléolo visível e citoplasma mais amplo que no Ewing.',
      'CD99 positivo apenas focal ou heterogêneo (não o padrão difuso membranoso do Ewing).',
      'WT1 (C-terminal) e ETV4 nucleares positivos; DUX4 confirma a fusão CIC::DUX4.',
      'Comportamento pior que o do Ewing e resposta ruim ao esquema de quimioterapia do Ewing: a distinção muda o tratamento.',
    ],
    markers: [
      { marker: 'etv4', pct: [85, 95], note: 'nuclear; muito útil junto com WT1' },
      { marker: 'dux4', pct: [90, 100], note: 'anticorpo contra a porção C-terminal de DUX4; praticamente definidor' },
      { marker: 'wt1', pct: [80, 95], note: 'C-terminal, nuclear' },
      { marker: 'cd99', pct: [50, 80], note: 'focal ou heterogêneo: raramente difuso e membranoso' },
      { marker: 'nkx22', pct: [0, 15], note: 'negativa, ao contrário do Ewing' },
      { marker: 'fli1', pct: [10, 30] },
      { marker: 'erg', pct: [10, 30] },
      { marker: 'ae1ae3', pct: [10, 30] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'miogenina', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 's100', pct: [0, 15] },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 'ki67', pct: [80, 100] },
      { marker: 'p53', pct: [20, 50] },
    ],
    mimics: [
      'Sarcoma de Ewing: CD99 difuso membranoso, NKX2.2 positiva, monotonia celular.',
      'Sarcoma BCOR: BCOR e CCNB3 positivos, fusocelular em áreas.',
      'Melanoma e carcinoma pouco diferenciado: SOX10 ou queratinas difusas.',
      'Rabdomiossarcoma: miogenina positiva.',
    ],
    molecular: 'CIC::DUX4 por t(4;19) ou t(10;19); variantes CIC::FOXO4 e CIC::NUTM1.',
    sources: [WHO, HORNICK, 'Le Guellec et al., Mod Pathol 2016 (ETV4 e WT1 nos sarcomas CIC)'],
  },
  {
    id: 'sarcoma-bcor',
    name: 'Sarcoma com alteração de BCOR',
    aka: ['BCOR::CCNB3 sarcoma', 'sarcoma com duplicação interna de BCOR', 'BCOR ITD'],
    behavior: 'maligno',
    sites: [
      { site: 'osso', role: 'primario', freq: 1 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'fusocelular'],
    architecture: ['lencois', 'fasciculos', 'hemangiopericitoma'],
    features: ['estroma-mixoide', 'mitoses-altas', 'necrose'],
    ages: ['crianca', 'jovem'],
    sex: 'm',
    summary: 'Sarcoma de células redondas e fusiformes com transição suave entre os dois padrões, rede capilar delicada e estroma mixoide ou colagenizado, em osso e partes moles de meninos e adolescentes.',
    criteria: [
      'Mistura de células pequenas redondas e fusiformes uniformes, com matriz mixoide e capilares delicados.',
      'BCOR nuclear difusa; CCNB3 nuclear nos casos com fusão BCOR::CCNB3.',
      'SATB2 positiva com frequência, sem significar linhagem osteoblástica.',
      'A duplicação interna em tandem de BCOR define a variante de lactentes (sarcoma indiferenciado de células redondas do lactente e nefroma mesoblástico-símile).',
    ],
    markers: [
      { marker: 'bcor', pct: [90, 100], note: 'nuclear difusa; também positiva em sarcoma do estroma endometrial de alto grau e sinovial' },
      { marker: 'ccnb3', pct: [85, 95], note: 'só nos casos com fusão BCOR::CCNB3' },
      { marker: 'satb2', pct: [70, 90], note: 'não indica osteossarcoma neste contexto' },
      { marker: 'cd99', pct: [30, 60], note: 'fraco e focal, nunca o padrão do Ewing' },
      { marker: 'ciclinad1', pct: [70, 95] },
      { marker: 'tle1', pct: [40, 70], note: 'armadilha com sarcoma sinovial' },
      { marker: 'nkx22', pct: [0, 10] },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'miogenina', pct: [0, 5] },
      { marker: 's100', pct: [0, 15] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ss18ssx', pct: [0, 5], note: 'negativo: separa do sarcoma sinovial' },
      { marker: 'ini1', pct: [0, 5] },
      { marker: 'ki67', pct: [60, 95] },
    ],
    mimics: [
      'Sarcoma de Ewing: CD99 difuso membranoso, NKX2.2, BCOR negativo.',
      'Sarcoma sinovial pouco diferenciado: TLE1 difusa e SS18-SSX positivo.',
      'Rabdomiossarcoma fusocelular: desmina e MyoD1 positivos.',
      'Sarcoma do estroma endometrial de alto grau (no útero): também BCOR positivo; o sítio decide.',
    ],
    molecular: 'BCOR::CCNB3 por inversão em Xp11.4 (a mais comum), BCOR ITD nos lactentes, BCOR::MAML3 e ZC3H7B::BCOR.',
    sources: [WHO, HORNICK, 'Kao et al., Am J Surg Pathol 2016 (BCOR e CCNB3 na imuno-histoquímica)'],
  },
  {
    id: 'dsrct',
    name: 'Tumor desmoplásico de células pequenas e redondas',
    aka: ['DSRCT', 'desmoplastic small round cell tumour'],
    behavior: 'maligno',
    sites: [
      { site: 'peritoneo', role: 'primario', freq: 2 },
      { site: 'retroperitoneo', role: 'primario', freq: 1 },
      { site: 'testiculo', role: 'primario', freq: 1 },
      { site: 'pleura', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas'],
    architecture: ['ninhos', 'lencois'],
    features: ['desmoplasia', 'necrose', 'mitoses-altas', 'corpos-apoptoticos'],
    ages: ['jovem'],
    sex: 'm',
    summary: 'Ninhos nítidos de células pequenas redondas mergulhados em estroma desmoplásico celular, com implantes peritoneais múltiplos em homens jovens; coexpressa queratina, desmina em dot e WT1.',
    criteria: [
      'Ninhos bem delimitados de células redondas em estroma desmoplásico exuberante, com necrose central frequente.',
      'Diferenciação polifenotípica: queratina ou EMA, desmina em dot paranuclear e WT1 (C-terminal) nuclear.',
      'Massa abdominal com implantes serosos múltiplos em homem jovem: o quadro clínico é quase patognomônico.',
      'Confirmação por EWSR1::WT1.',
    ],
    markers: [
      { marker: 'desmina', pct: [90, 100], pattern: 'dot', note: 'dot paranuclear; achado típico' },
      { marker: 'wt1', pct: [85, 95], note: 'anticorpo C-terminal; o N-terminal é negativo por causa da fusão' },
      { marker: 'ae1ae3', pct: [85, 95] },
      { marker: 'ema', pct: [70, 90] },
      { marker: 'cam52', pct: [70, 90] },
      { marker: 'sinaptofisina', pct: [20, 50] },
      { marker: 'cromogranina', pct: [10, 30] },
      { marker: 'nse', pct: [70, 90] },
      { marker: 'cd99', pct: [20, 40], note: 'pode confundir com Ewing' },
      { marker: 'miogenina', pct: [0, 5], note: 'negativa apesar da desmina: não é rabdomiossarcoma' },
      { marker: 'myod1', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'sall4', pct: [0, 10] },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 'ki67', pct: [70, 95] },
    ],
    mimics: [
      'Sarcoma de Ewing: CD99 difuso, sem desmina em dot nem WT1.',
      'Rabdomiossarcoma: miogenina e MyoD1 positivas.',
      'Mesotelioma desmoplásico: calretinina positiva, desmina sem dot.',
      'Carcinoma de pequenas células metastático: TTF-1 ou INSM1, sem desmina.',
      'Tumor de Wilms extrarrenal: WT1 positivo mas com blastema, epitélio e estroma.',
    ],
    molecular: 'Fusão EWSR1::WT1 por t(11;22)(p13;q12).',
    sources: [WHO, WEISS, HORNICK],
  },
  {
    id: 'tumor-rabdoide-extrarrenal',
    name: 'Tumor rabdoide maligno extrarrenal',
    aka: ['malignant rhabdoid tumour', 'tumor rabdoide de partes moles'],
    behavior: 'maligno',
    sites: [
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'figado', role: 'primario', freq: 1 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['rabdoide', 'epitelioide'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['crianca'],
    summary: 'Lençóis discoesos de células grandes com inclusão citoplasmática eosinofílica globular que desloca o núcleo, nucléolo muito proeminente e perda de INI1, em lactentes e crianças pequenas.',
    criteria: [
      'Morfologia rabdoide: inclusão eosinofílica paranuclear (filamentos intermediários) com núcleo excêntrico e nucléolo cherry-red.',
      'Perda completa da expressão nuclear de INI1 (SMARCB1) nas células tumorais, com controle interno positivo em linfócitos e endotélio.',
      'Coexpressão polifenotípica (queratina, EMA, vimentina) sem linhagem definida.',
      'Rastrear predisposição germinativa (síndrome de predisposição a tumor rabdoide) em toda criança pequena.',
    ],
    markers: [
      { marker: 'ini1', pct: [95, 100], note: 'PERDA nuclear; o marcador que define a entidade' },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [70, 90], note: 'muitas vezes em dot' },
      { marker: 'ema', pct: [70, 90] },
      { marker: 'cd99', pct: [20, 50] },
      { marker: 'sinaptofisina', pct: [10, 30] },
      { marker: 's100', pct: [0, 15] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'desmina', pct: [0, 15] },
      { marker: 'miogenina', pct: [0, 5] },
      { marker: 'cd34', pct: [0, 10], note: 'negativo: ajuda contra sarcoma epitelioide, que também perde INI1' },
      { marker: 'glipicano3', pct: [10, 30] },
      { marker: 'ki67', pct: [70, 100] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Sarcoma epitelioide proximal: também perde INI1, mas é de adulto jovem, pélvico e CD34 positivo.',
      'Carcinoma medular renal e carcinoma sinonasal SMARCB1-deficiente: mesma perda, sítios diferentes.',
      'Rabdomiossarcoma: miogenina positiva, INI1 retido.',
      'Melanoma rabdoide: SOX10 positivo.',
    ],
    pitfalls: ['Morfologia rabdoide aparece em muitos tumores (carcinoma, melanoma, sarcoma): só a perda de INI1 com controle interno fecha o diagnóstico.'],
    molecular: 'Inativação bialélica de SMARCB1 (22q11), germinativa em cerca de um terço das crianças.',
    sources: [WHO, HORNICK],
  },
  /* ---- Tumores neuroblásticos e paragânglios ---------------------------------- */
  {
    id: 'neuroblastoma',
    name: 'Neuroblastoma e ganglioneuroblastoma',
    aka: ['neuroblastoma', 'ganglioneuroblastoma', 'tumor neuroblástico periférico'],
    behavior: 'maligno',
    sites: [
      { site: 'adrenal', role: 'primario', freq: 3 },
      { site: 'retroperitoneo', role: 'primario', freq: 3 },
      { site: 'mediastino', role: 'primario', freq: 2 },
      { site: 'pescoco', role: 'primario', freq: 1 },
      { site: 'medula-ossea', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'olho-orbita', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino'],
    architecture: ['lencois', 'rosetas', 'nodular'],
    features: ['calcificacao', 'necrose', 'mitoses-altas', 'hemorragia'],
    ages: ['crianca'],
    summary: 'Células pequenas redondas com cromatina em sal e pimenta imersas em neurópilo fibrilar, com rosetas de Homer Wright e calcificações, na adrenal ou na cadeia simpática de crianças menores de 5 anos.',
    criteria: [
      'Neurópilo fibrilar entre as células: o achado que separa dos outros tumores de células redondas.',
      'Rosetas de Homer Wright e graus variáveis de diferenciação ganglionar (classificação de Shimada / INPC).',
      'PHOX2B nuclear e tirosina hidroxilase citoplasmática: os marcadores mais específicos de linhagem simpática.',
      'Avaliar amplificação de MYCN, que define o grupo de alto risco.',
    ],
    markers: [
      { marker: 'phox2b', pct: [90, 100], note: 'nuclear; muito específica para linhagem neuroblástica' },
      { marker: 'th', pct: [80, 95] },
      { marker: 'sinaptofisina', pct: [85, 100] },
      { marker: 'cromogranina', pct: [50, 80] },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'nse', pct: [90, 100] },
      { marker: 'cd56', pct: [85, 100] },
      { marker: 'nf', pct: [60, 90], note: 'no neurópilo e nas células em diferenciação' },
      { marker: 's100', pct: [40, 70], note: 'nas células de Schwann do estroma, não nos neuroblastos' },
      { marker: 'gata3', pct: [70, 90], note: 'positiva: não interprete como urotelial ou mamário' },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 'cd99', pct: [0, 15], note: 'negativo: separa do Ewing' },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'miogenina', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'myc', pct: [20, 40], note: 'expressão de MYCN nos casos amplificados (confirme por FISH)' },
      { marker: 'ki67', pct: [50, 95] },
      { marker: 'sox10', pct: [10, 30], note: 'só nas células sustentaculares, como o S100' },
      { marker: 'cd20', pct: 0 },
      { marker: 'cd34', pct: [0, 5] },
    ],
    mimics: [
      'Sarcoma de Ewing: CD99 membranoso difuso, sem neurópilo nem PHOX2B.',
      'Rabdomiossarcoma alveolar: miogenina positiva.',
      'Linfoma linfoblástico: TdT e CD45 positivos.',
      'Tumor de Wilms: blastema com epitélio e estroma, WT1 positivo.',
      'Meduloblastoma metastático: contexto de lesão cerebelar, PHOX2B negativo.',
    ],
    molecular: 'Amplificação de MYCN (alto risco), alterações de ALK (alvo terapêutico), ganho de 17q e deleções de 1p e 11q.',
    sources: [WHO, 'WHO Classification of Paediatric Tumours, 5ª ed. (2022)', HORNICK],
  },
  {
    id: 'ganglioneuroma',
    name: 'Ganglioneuroma',
    aka: ['ganglioneuroma maduro'],
    behavior: 'benigno',
    sites: [
      { site: 'retroperitoneo', role: 'primario', freq: 2 },
      { site: 'mediastino', role: 'primario', freq: 2 },
      { site: 'adrenal', role: 'primario', freq: 1 },
      { site: 'pescoco', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'neuroendocrino', 'gigantes'],
    architecture: ['fasciculos'],
    features: ['mitoses-raras', 'calcificacao'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Fascículos de células de Schwann maduras entremeados por células ganglionares grandes e maduras, sem neuroblastos nem neurópilo; massa paraespinhal bem delimitada.',
    criteria: [
      'Estroma schwanniano maduro predominante, com células ganglionares dispersas, muitas vezes binucleadas, cercadas por células satélites.',
      'Ausência completa de neuroblastos e de neurópilo (a presença deles leva a ganglioneuroblastoma).',
      'Amostragem ampla é obrigatória: focos de neuroblastoma podem estar em um só nódulo.',
    ],
    markers: [
      { marker: 's100', pct: [95, 100], note: 'no estroma schwanniano' },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'sinaptofisina', pct: [80, 95], note: 'nas células ganglionares' },
      { marker: 'cromogranina', pct: [70, 90] },
      { marker: 'nf', pct: [80, 95] },
      { marker: 'neun', pct: [60, 90], note: 'núcleos das células ganglionares' },
      { marker: 'phox2b', pct: [70, 95] },
      { marker: 'th', pct: [40, 80] },
      { marker: 'cd34', pct: [20, 50] },
      { marker: 'ki67', pct: [0, 5], note: 'índice baixíssimo: o oposto do neuroblastoma' },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'gata3', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Ganglioneuroblastoma: focos de neuroblastos com neurópilo; amostre todo o tumor.',
      'Schwannoma: sem células ganglionares.',
      'Neurofibroma plexiforme: sem células ganglionares, fundo mixoide.',
      'Paraganglioma gangliocítico (duodeno): três componentes, incluindo epitelial.',
    ],
    sources: [WHO, HORNICK],
  },
  {
    id: 'feocromocitoma-paraganglioma',
    name: 'Feocromocitoma e paraganglioma',
    aka: ['feocromocitoma', 'paraganglioma', 'tumor do corpo carotídeo', 'glomus jugulare'],
    behavior: 'maligno',
    sites: [
      { site: 'adrenal', role: 'primario', freq: 3 },
      { site: 'pescoco', role: 'primario', freq: 2 },
      { site: 'retroperitoneo', role: 'primario', freq: 2 },
      { site: 'bexiga', role: 'primario', freq: 1 },
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'orelha', role: 'primario', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'neuroendocrino', 'oncocitico', 'pleomorfico'],
    architecture: ['organoide', 'trabecular', 'ninhos'],
    features: ['hemorragia', 'hialinizacao', 'mitoses-raras', 'vasos-espessos'],
    ages: ['jovem', 'adulto'],
    summary: 'Ninhos organoides (zellballen) de células principais granulares basofílicas cercados por células sustentaculares e por rede capilar delicada; na adrenal (feocromocitoma) ou nos paragânglios extra-adrenais.',
    criteria: [
      'Arquitetura em zellballen com células principais poligonais de citoplasma granular e rede capilar rica.',
      'Cromogranina e sinaptofisina positivas com queratina NEGATIVA: a combinação que separa de carcinoma e de tumor neuroendócrino epitelial.',
      'Células sustentaculares S100 e SOX10 positivas na periferia dos ninhos.',
      'Todo caso merece investigação genética: até 40% têm mutação germinativa (SDHx, VHL, RET, NF1, MAX, TMEM127). A perda de SDHB aponta a via SDH.',
      'Não há critério morfológico seguro de malignidade: metástase define. Escores (PASS, GAPP) apenas estratificam risco.',
    ],
    markers: [
      { marker: 'cromogranina', pct: [90, 100] },
      { marker: 'sinaptofisina', pct: [95, 100] },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'gata3', pct: [85, 95], note: 'muito útil; não confunda com urotelial ou mamário' },
      { marker: 'th', pct: [70, 95] },
      { marker: 'phox2b', pct: [70, 90] },
      { marker: 'ae1ae3', pct: [0, 5], note: 'negativa: o achado mais útil contra tumor neuroendócrino epitelial' },
      { marker: 'cam52', pct: [0, 10] },
      { marker: 'ema', pct: [0, 5] },
      { marker: 's100', pct: [70, 90], note: 'nas células sustentaculares periféricas, não nas principais' },
      { marker: 'sox10', pct: [70, 90], note: 'idem' },
      { marker: 'sdhb', pct: [20, 40], note: 'PERDA citoplasmática nos tumores com mutação de SDHx (maior risco de metástase)' },
      { marker: 'inibina', pct: [0, 10], note: 'negativa: separa do adrenocortical' },
      { marker: 'sf1', pct: [0, 5], note: 'negativa: separa do adrenocortical' },
      { marker: 'melana', pct: [0, 10] },
      { marker: 'ttf1', pct: [0, 5] },
      { marker: 'cdx2', pct: [0, 5] },
      { marker: 'ki67', pct: [5, 25] },
      { marker: 'pax8', pct: 0, note: 'o negativo que separa de carcinoma renal quando a massa é adrenal ou retroperitoneal' },
      { marker: 'desmina', pct: 0 },
      { marker: 'cd34', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma adrenocortical: SF-1, inibina e Melan-A positivos, cromogranina negativa.',
      'Tumor neuroendócrino metastático: queratina positiva, GATA3 negativa.',
      'Carcinoma renal metastático: PAX8 e queratina positivos.',
      'Melanoma: SOX10 difuso nas células tumorais (e não só nas sustentaculares).',
      'Sarcoma alveolar de partes moles: TFE3 positivo, cromogranina negativa.',
    ],
    pitfalls: ['Queratina positiva praticamente exclui paraganglioma.', 'A perda de SDHB muda o seguimento da família inteira: vale pedir em todos.'],
    molecular: 'Três grupos: pseudo-hipóxia (SDHx, VHL, FH, EPAS1), sinalização de quinases (RET, NF1, MAX, TMEM127) e Wnt. Cerca de 40% têm mutação germinativa.',
    sources: [WHO, 'WHO Classification of Endocrine and Neuroendocrine Tumours, 5ª ed. (2022)'],
  },
  {
    id: 'mnti',
    name: 'Tumor neuroectodérmico melanótico da infância',
    aka: ['MNTI', 'progonoma melanótico', 'melanotic neuroectodermal tumour of infancy'],
    behavior: 'intermediario',
    sites: [
      { site: 'maxilares', role: 'primario', freq: 2 },
      { site: 'osso', role: 'primario', freq: 1 },
      { site: 'encefalo', role: 'primario', freq: 1 },
      { site: 'testiculo', role: 'primario', freq: 1 },
    ],
    cells: ['pequenas-redondas', 'epitelioide'],
    architecture: ['alveolar', 'ninhos'],
    features: ['melanina', 'mitoses-raras'],
    ages: ['crianca'],
    summary: 'Duas populações num estroma fibroso denso: células pequenas neuroblásticas em ninhos e células maiores epitelioides pigmentadas por melanina revestindo espaços alveolares; massa da maxila anterior no primeiro ano de vida.',
    criteria: [
      'Bifasia característica: células grandes epitelioides melanóticas em fendas alveolares e células pequenas neuroblásticas.',
      'Estroma fibroso colagenizado denso, com crescimento infiltrativo no osso.',
      'Imunofenótipo duplo: as células grandes expressam queratina e HMB-45; as pequenas, sinaptofisina e CD56.',
      'Idade abaixo de 1 ano na maxila anterior: o contexto pesa tanto quanto a imuno.',
    ],
    markers: [
      { marker: 'hmb45', pct: [85, 100], note: 'nas células grandes pigmentadas' },
      { marker: 'ae1ae3', pct: [80, 95], note: 'nas células grandes' },
      { marker: 'sinaptofisina', pct: [70, 90], note: 'nas células pequenas' },
      { marker: 'cd56', pct: [70, 90] },
      { marker: 'nse', pct: [70, 90] },
      { marker: 'cromogranina', pct: [20, 50] },
      { marker: 'melana', pct: [20, 50], note: 'bem menos sensível que HMB-45 aqui' },
      { marker: 's100', pct: [10, 40], note: 'em geral negativa: diferente do melanoma' },
      { marker: 'sox10', pct: [0, 20] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'miogenina', pct: [0, 5] },
      { marker: 'cd99', pct: [0, 20] },
      { marker: 'ini1', pct: [0, 5] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Melanoma: S100 e SOX10 difusos, sem a bifasia nem a idade.',
      'Rabdomiossarcoma alveolar da cabeça e pescoço: miogenina positiva.',
      'Neuroblastoma metastático: PHOX2B positivo, sem células epitelioides pigmentadas.',
      'Sarcoma de Ewing: CD99 difuso.',
    ],
    molecular: 'Sem alteração definidora estabelecida; relatadas alterações de BRAF e de CDKN2A numa minoria.',
    sources: [WHO, 'WHO Classification of Head and Neck Tumours, 5ª ed. (2022)'],
  },
  /* ---- Bainha neural ------------------------------------------------------------ */
  {
    id: 'schwannoma',
    name: 'Schwannoma',
    aka: ['neurilemoma', 'schwannoma vestibular', 'schwannoma celular', 'schwannoma antigo'],
    behavior: 'benigno',
    sites: [
      { site: 'nervo-periferico', role: 'primario', freq: 3 },
      { site: 'partes-moles', role: 'primario', freq: 2 },
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 2 },
      { site: 'retroperitoneo', role: 'primario', freq: 2 },
      { site: 'estomago', role: 'primario', freq: 1 },
      { site: 'pele', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular'],
    architecture: ['fasciculos', 'palicada', 'nodular'],
    features: ['vasos-espessos', 'hemorragia', 'estroma-mixoide', 'mitoses-raras'],
    ages: ['adulto'],
    summary: 'Tumor encapsulado de células de Schwann com alternância de áreas compactas (Antoni A, com corpos de Verocay) e frouxas (Antoni B), vasos hialinizados espessos e atipia degenerativa sem mitoses.',
    criteria: [
      'Cápsula (perineuro) e padrão Antoni A/B com corpos de Verocay.',
      'S100 e SOX10 fortes e difusos em praticamente todas as células: o padrão difuso é o que separa do neurofibroma e do MPNST.',
      'Vasos de parede hialinizada espessa com trombose e hemorragia.',
      'Atipia "antiga" degenerativa (núcleos grandes hipercromáticos sem mitoses) não é malignidade.',
    ],
    markers: [
      { marker: 's100', pct: [95, 100], note: 'difusa e forte' },
      { marker: 'sox10', pct: [95, 100] },
      { marker: 'colageno-iv', pct: [85, 100], note: 'membrana basal pericelular' },
      { marker: 'glut1', pct: [30, 70], note: 'na cápsula perineural' },
      { marker: 'cd34', pct: [30, 60], note: 'em células fibroblásticas do Antoni B, não difuso' },
      { marker: 'gfap', pct: [20, 50] },
      { marker: 'nf', pct: [0, 20], note: 'axônios ausentes dentro do tumor (ao contrário do neurofibroma)' },
      { marker: 'ema', pct: [10, 30], note: 'na cápsula perineural' },
      { marker: 'h3k27me3', pct: [0, 10], note: 'retido; a perda favorece MPNST' },
      { marker: 'ini1', pct: [0, 5] },
      { marker: 'melana', pct: [0, 10], note: 'positivo no schwannoma melanótico' },
      { marker: 'hmb45', pct: [0, 10], note: 'idem' },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'sma', pct: [0, 10] },
      { marker: 'cd117', pct: [0, 5], note: 'negativo: separa do GIST na parede gástrica' },
      { marker: 'dog1', pct: [0, 5] },
      { marker: 'ki67', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Neurofibroma: S100 em apenas parte das células, CD34 em rede, axônios presentes.',
      'MPNST: S100 focal, perda de H3K27me3, mitoses e necrose.',
      'GIST (estômago): KIT e DOG1 positivos, S100 negativo.',
      'Leiomioma: desmina e caldesmon positivos.',
      'Meningioma (intracraniano): EMA e SSTR2A positivos, SOX10 negativo.',
    ],
    molecular: 'Inativação de NF2 (22q12) na maioria; múltiplos na neurofibromatose tipo 2 e na schwannomatose (SMARCB1, LZTR1).',
    sources: [WHO, WEISS, HORNICK],
  },
  {
    id: 'neurofibroma',
    name: 'Neurofibroma',
    aka: ['neurofibroma cutâneo', 'neurofibroma plexiforme', 'neurofibroma difuso'],
    behavior: 'benigno',
    sites: [
      { site: 'pele', role: 'primario', freq: 3 },
      { site: 'nervo-periferico', role: 'primario', freq: 3 },
      { site: 'partes-moles', role: 'primario', freq: 2 },
      { site: 'retroperitoneo', role: 'primario', freq: 1 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'estreladas'],
    architecture: ['fasciculos', 'plexiforme', 'infiltrativo'],
    features: ['estroma-mixoide', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Proliferação frouxa e não encapsulada de células de Schwann, fibroblastos e células perineurais em estroma mixoide e colagenizado, com feixes de colágeno em "cenoura ralada" e mastócitos.',
    criteria: [
      'Mistura de tipos celulares (Schwann, perineural, fibroblasto) com axônios aprisionados dentro da lesão.',
      'S100 e SOX10 positivos em apenas parte das células, com CD34 em rede fina ("fingerprint").',
      'Padrão plexiforme (expansão multinodular de fascículos nervosos) é praticamente específico de neurofibromatose tipo 1 e pode virar MPNST.',
      'Atipia isolada não preocupa; celularidade alta, perda do CD34, mitoses e nódulo expansivo sugerem transformação.',
    ],
    markers: [
      { marker: 's100', pct: [70, 90], note: 'em subpopulação, nunca difusa como no schwannoma' },
      { marker: 'sox10', pct: [70, 90], note: 'idem' },
      { marker: 'cd34', pct: [70, 95], note: 'rede fibroblástica em "impressão digital"; perde-se na transformação maligna' },
      { marker: 'nf', pct: [70, 95], note: 'axônios dentro da lesão: achado que o separa do schwannoma' },
      { marker: 'ema', pct: [30, 60], note: 'células perineurais dispersas' },
      { marker: 'glut1', pct: [20, 50] },
      { marker: 'h3k27me3', pct: [0, 10], note: 'retido' },
      { marker: 'triptase', pct: [80, 95], note: 'mastócitos abundantes: achado clássico' },
      { marker: 'colageno-iv', pct: [60, 90] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'sma', pct: [0, 10] },
      { marker: 'ki67', pct: [0, 10], note: 'acima de 10% levanta suspeita de transformação' },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'p16', pct: [0, 20], note: 'a perda de p16/CDKN2A acompanha a progressão para MPNST' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Schwannoma: S100 difusa, encapsulado, Antoni A/B.',
      'MPNST: celularidade alta, mitoses, perda de H3K27me3 e de CD34.',
      'DFSP (na pele): CD34 difuso e denso, S100 negativo.',
      'Dermatofibroma: FXIIIa positivo, S100 negativo.',
    ],
    molecular: 'Inativação bialélica de NF1; os plexiformes são marcadores da neurofibromatose tipo 1.',
    sources: [WHO, WEISS, HORNICK],
  },
  {
    id: 'mpnst',
    name: 'Tumor maligno da bainha de nervo periférico',
    aka: ['MPNST', 'schwannoma maligno (nome antigo)', 'neurofibrossarcoma', 'malignant peripheral nerve sheath tumour'],
    behavior: 'maligno',
    sites: [
      { site: 'nervo-periferico', role: 'primario', freq: 2 },
      { site: 'partes-moles', role: 'primario', freq: 2 },
      { site: 'retroperitoneo', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular', 'pleomorfico', 'epitelioide'],
    architecture: ['fasciculos', 'hemangiopericitoma', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'perineural', 'estroma-mixoide'],
    ages: ['jovem', 'adulto'],
    summary: 'Sarcoma fusocelular de alto grau em fascículos densos alternando com áreas mixoides hipocelulares, com condensação perivascular das células e necrose geográfica, surgindo de nervo ou de neurofibroma plexiforme na neurofibromatose tipo 1.',
    criteria: [
      'Origem em nervo periférico, em neurofibroma preexistente ou em paciente com neurofibromatose tipo 1 (contexto vale muito).',
      'Células fusiformes com núcleo ondulado, alternância de celularidade ("marbleizado"), condensação perivascular, necrose.',
      'S100 e SOX10 focais (nunca difusos) e perda de H3K27me3 em cerca de dois terços dos de alto grau.',
      'A perda de H3K27me3 é forte evidência num sarcoma fusocelular, mas ocorre também em sarcomas radioinduzidos e em melanomas.',
    ],
    markers: [
      { marker: 'h3k27me3', pct: [50, 80], note: 'PERDA completa; muito útil, mas nem todo MPNST perde' },
      { marker: 's100', pct: [40, 60], note: 'focal e fraca; difusa e forte sugere schwannoma ou melanoma' },
      { marker: 'sox10', pct: [30, 60], note: 'idem' },
      { marker: 'cd34', pct: [10, 30], note: 'perda da rede do neurofibroma de origem' },
      { marker: 'p16', pct: [60, 85], note: 'PERDA por deleção de CDKN2A, marcador de progressão' },
      { marker: 'ema', pct: [10, 30], note: 'em áreas de diferenciação perineural' },
      { marker: 'glut1', pct: [10, 30] },
      { marker: 'tle1', pct: [20, 50], note: 'fraca: armadilha com sarcoma sinovial' },
      { marker: 'ss18ssx', pct: [0, 5], note: 'negativo: separa do sarcoma sinovial' },
      { marker: 'desmina', pct: [5, 20], note: 'positiva no tumor de Triton (diferenciação rabdomioblástica)' },
      { marker: 'miogenina', pct: [5, 15], note: 'idem' },
      { marker: 'ae1ae3', pct: [0, 15] },
      { marker: 'melana', pct: [0, 5], note: 'negativa: separa do melanoma fusocelular' },
      { marker: 'hmb45', pct: [0, 5] },
      { marker: 'stat6', pct: [0, 5] },
      { marker: 'ini1', pct: [5, 20], note: 'perda no MPNST epitelioide, que também é S100 difusa' },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'p53', pct: [40, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Schwannoma celular: S100 e SOX10 difusos, H3K27me3 retido, sem necrose.',
      'Sarcoma sinovial monofásico: SS18-SSX positivo, TLE1 difusa, EMA/queratina focais.',
      'Melanoma fusocelular ou desmoplásico: S100 e SOX10 difusos, história de melanoma.',
      'Leiomiossarcoma: desmina e caldesmon difusos.',
      'MPNST epitelioide: S100 forte difusa com perda de INI1, comportamento distinto.',
    ],
    pitfalls: ['A perda de H3K27me3 não é exclusiva: sarcomas pós-radioterapia e melanomas também perdem.', 'S100 difusa e forte deve fazer repensar o diagnóstico, salvo na variante epitelioide.'],
    molecular: 'Inativação de NF1, CDKN2A e do complexo PRC2 (EED, SUZ12), esta última responsável pela perda de H3K27me3.',
    sources: [WHO, WEISS, 'Röhrich et al. / Prieto-Granada et al., Am J Surg Pathol 2016 (H3K27me3 no MPNST)'],
  },
  {
    id: 'perineurioma',
    name: 'Perineurioma',
    aka: ['perineurioma de partes moles', 'perineurioma intraneural', 'perineurioma esclerosante'],
    behavior: 'benigno',
    sites: [
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'nervo-periferico', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular'],
    architecture: ['storiforme', 'fasciculos'],
    features: ['hialinizacao', 'estroma-mixoide', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Células fusiformes muito finas, com prolongamentos citoplasmáticos bipolares longos, em arranjo estoriforme frouxo ou em bulbo de cebola dentro do nervo; EMA positivo e S100 negativo.',
    criteria: [
      'Células delgadas com processos bipolares longos, em estroma colagenizado ou mixoide.',
      'EMA positiva (muitas vezes fraca, exige exame cuidadoso) com S100 e SOX10 NEGATIVOS: a inversão do padrão do schwannoma.',
      'GLUT1 e claudina-1 apoiam a linhagem perineural.',
      'Intraneural: proliferação concêntrica em bulbo de cebola ao redor de axônios, vista em nervo espessado.',
    ],
    markers: [
      { marker: 'ema', pct: [80, 95], note: 'muitas vezes fraca e delicada: procure em grande aumento' },
      { marker: 'glut1', pct: [60, 90] },
      { marker: 'nf-perineurio', pct: [60, 90], note: 'claudina-1' },
      { marker: 'colageno-iv', pct: [70, 95] },
      { marker: 's100', pct: [0, 5], note: 'negativa: o achado mais importante contra schwannoma e neurofibroma' },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd34', pct: [20, 50] },
      { marker: 'sma', pct: [0, 20] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'muc4', pct: [0, 10], note: 'negativa: separa do sarcoma fibromixoide de baixo grau' },
      { marker: 'stat6', pct: [0, 5] },
      { marker: 'ki67', pct: [0, 10] },
      { marker: 'h3k27me3', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Neurofibroma e schwannoma: S100 e SOX10 positivos.',
      'Sarcoma fibromixoide de baixo grau: MUC4 difusa.',
      'Fibromatose desmoide: β-catenina nuclear, EMA negativa.',
      'DFSP: CD34 difuso e denso, EMA negativa.',
      'Meningioma (extracraniano): EMA positiva também; localização e SSTR2A ajudam.',
    ],
    molecular: 'Deleções de 22q (NF2) no de partes moles; fusões de TRAF7 em parte dos esclerosantes.',
    sources: [WHO, WEISS, HORNICK],
  },
  {
    id: 'fibrossarcoma-infantil',
    name: 'Fibrossarcoma infantil',
    aka: ['fibrossarcoma congênito', 'infantile fibrosarcoma', 'sarcoma com fusão NTRK'],
    behavior: 'intermediario',
    sites: [
      { site: 'partes-moles', role: 'primario', freq: 2 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'pequenas-redondas'],
    architecture: ['fasciculos', 'hemangiopericitoma'],
    features: ['necrose', 'mitoses-altas', 'estroma-mixoide', 'linfoide'],
    ages: ['crianca'],
    summary: 'Fascículos densos em espinha de peixe de células fusiformes primitivas com mitoses numerosas, vasos ramificados e infiltrado linfoide, em lactentes; apesar do aspecto agressivo, raramente metastatiza.',
    criteria: [
      'Lactente (quase sempre no primeiro ano) com massa de crescimento rápido em membro ou tronco.',
      'Fascículos celulares primitivos com alto índice mitótico, necrose e vasos em galhada.',
      'Pan-TRK nuclear ou citoplasmática positiva aponta fusão de NTRK; confirmação por ETV6::NTRK3.',
      'O diagnóstico muda o tratamento: inibidores de TRK (larotrectinibe, entrectinibe) evitam cirurgia mutilante.',
    ],
    markers: [
      { marker: 'pan-trk', pct: [80, 95], note: 'sensível nas fusões de NTRK3; a intensidade varia' },
      { marker: 'sma', pct: [30, 70] },
      { marker: 'cd34', pct: [20, 50] },
      { marker: 'desmina', pct: [0, 15] },
      { marker: 'miogenina', pct: [0, 5] },
      { marker: 's100', pct: [0, 15] },
      { marker: 'sox10', pct: [0, 10] },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 'alk', pct: [0, 10], note: 'negativo: separa do tumor miofibroblástico inflamatório' },
      { marker: 'betacatenina', pct: [0, 15], note: 'nuclear negativa: separa da fibromatose' },
      { marker: 'ini1', pct: [0, 5] },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'bcor', pct: [0, 15], note: 'positivo na variante com BCOR ITD, que é morfologicamente idêntica' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Fibromatose infantil: menos celular, sem necrose, β-catenina em parte.',
      'Sarcoma indiferenciado com BCOR ITD: BCOR positivo, pan-TRK negativo.',
      'Rabdomiossarcoma fusocelular: desmina e MyoD1 positivos.',
      'Tumor miofibroblástico inflamatório: ALK positivo.',
    ],
    molecular: 'ETV6::NTRK3 por t(12;15) na maioria; outras fusões de NTRK1/2, BRAF e MET; BCOR ITD nos morfologicamente idênticos.',
    sources: [WHO, 'WHO Classification of Paediatric Tumours, 5ª ed. (2022)', HORNICK],
  },
  /* ---- Osso -------------------------------------------------------------------- */
  {
    id: 'osteossarcoma',
    name: 'Osteossarcoma convencional',
    aka: ['osteosarcoma', 'osteossarcoma osteoblástico, condroblástico e fibroblástico', 'osteossarcoma parosteal (variante)'],
    behavior: 'maligno',
    sites: [
      { site: 'osso', role: 'primario', freq: 3 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['osteoblastico', 'pleomorfico', 'fusocelular', 'cartilaginoso'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['osteoide', 'necrose', 'mitoses-altas', 'condroide'],
    ages: ['jovem', 'idoso'],
    summary: 'Células mesenquimais malignas produzindo osteoide entrelaçado diretamente pelas células tumorais, na metáfise do joelho de adolescentes (pico) ou em osso doente de idosos.',
    criteria: [
      'Produção de osteoide (matriz eosinofílica densa, irregular, "em renda") pelas células tumorais: o critério definidor.',
      'Atipia e mitoses no componente celular, com permeação das trabéculas ósseas.',
      'A imuno-histoquímica não faz o diagnóstico: SATB2 apenas apoia a linhagem osteoblástica e é positiva também em outros tumores.',
      'A variante parosteal é de baixo grau, cresce na superfície do fêmur distal e tem amplificação de MDM2/CDK4.',
    ],
    markers: [
      { marker: 'satb2', pct: [80, 95], note: 'apoia diferenciação osteoblástica; positiva também em colorretal e em sarcoma BCOR' },
      { marker: 'runx2', pct: [70, 90] },
      { marker: 'sma', pct: [20, 50] },
      { marker: 's100', pct: [20, 50], note: 'no componente condroblástico' },
      { marker: 'sox9', pct: [30, 60], note: 'no componente condroide' },
      { marker: 'ae1ae3', pct: [10, 30], note: 'focal: não converta em carcinoma sarcomatoide' },
      { marker: 'ema', pct: [5, 20] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'cd99', pct: [20, 50] },
      { marker: 'mdm2', pct: [10, 25], note: 'amplificado no parosteal e no osteossarcoma de baixo grau central; negativo no convencional' },
      { marker: 'cdk4', pct: [10, 25] },
      { marker: 'rb1', pct: [30, 60], note: 'perda frequente (via RB1)' },
      { marker: 'p53', pct: [50, 80] },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'h3g34', pct: [0, 5], note: 'negativo: separa do tumor de células gigantes com osso reativo' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Osteossarcoma de células gigantes vs tumor de células gigantes: H3.3 G34W positivo no segundo.',
      'Calo ósseo e miosite ossificante: zonalidade com maturação periférica, sem atipia.',
      'Condrossarcoma: sem osteoide produzido pelas células tumorais.',
      'Metástase de carcinoma com reação óssea: queratinas difusas.',
      'Osteossarcoma parosteal vs osteocondroma: MDM2 amplificado no primeiro.',
    ],
    pitfalls: ['Osteoide reativo ao redor de qualquer tumor engana: exija matriz produzida pelas células malignas.', 'Biópsia pequena de área condroblástica pode passar por condrossarcoma.'],
    molecular: 'Cariótipo caótico com cromotripsia, TP53 e RB1 alterados; amplificação de MDM2/CDK4 nas variantes de baixo grau.',
    sources: [WHO, 'Fletcher, Diagnostic Histopathology of Tumors, 5ª ed.'],
  },
  {
    id: 'osteoblastoma-osteoma-osteoide',
    name: 'Osteoma osteoide e osteoblastoma',
    aka: ['osteoid osteoma', 'osteoblastoma', 'osteoblastoma epitelioide'],
    behavior: 'benigno',
    sites: [
      { site: 'osso', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
      { site: 'maxilares', role: 'primario', freq: 1 },
    ],
    cells: ['osteoblastico', 'gigantes'],
    architecture: ['nodular'],
    features: ['osteoide', 'calcificacao', 'mitoses-raras', 'hemorragia'],
    ages: ['crianca', 'jovem'],
    summary: 'Nidus circunscrito de trabéculas de osteoide entrelaçado revestidas por osteoblastos regulares, com estroma frouxo muito vascularizado; dor noturna que cede com anti-inflamatório no osteoma osteoide.',
    criteria: [
      'Lesão nítida e circunscrita, com trabéculas anastomosadas revestidas por osteoblastos uniformes em fileira única.',
      'Estroma frouxo, ricamente vascularizado, com células gigantes osteoclásticas dispersas.',
      'Tamanho é o que separa: até 1,5 a 2 cm, osteoma osteoide; acima, osteoblastoma.',
      'Ausência de permeação das trabéculas hospedeiras e de atipia, o que o separa do osteossarcoma.',
    ],
    markers: [
      { marker: 'satb2', pct: [80, 95] },
      { marker: 'runx2', pct: [70, 90] },
      { marker: 'ki67', pct: [0, 10] },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'mdm2', pct: [0, 5] },
      { marker: 'h3g34', pct: [0, 5] },
      { marker: 'cd68', pct: [60, 90], note: 'nas células gigantes osteoclásticas' },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 's100', pct: [0, 10] },
      { marker: 'sma', pct: [0, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Osteossarcoma osteoblástico: permeação, atipia, mitoses atípicas e necrose.',
      'Displasia fibrosa: trabéculas em caracteres chineses sem revestimento osteoblástico, GNAS mutado.',
      'Fratura de estresse e calo: zonalidade e ausência de nidus.',
    ],
    molecular: 'Rearranjos de FOS e FOSB na maioria das duas lesões (o anticorpo FOSB ajuda quando disponível).',
    sources: [WHO, 'Fletcher, Diagnostic Histopathology of Tumors, 5ª ed.'],
  },
  {
    id: 'condrossarcoma',
    name: 'Condrossarcoma convencional (e encondroma)',
    aka: ['chondrosarcoma', 'encondroma', 'condrossarcoma central e periférico', 'condrossarcoma desdiferenciado'],
    behavior: 'maligno',
    sites: [
      { site: 'osso', role: 'primario', freq: 3 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'laringe', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['cartilaginoso'],
    architecture: ['lobular', 'infiltrativo'],
    features: ['condroide', 'calcificacao', 'estroma-mixoide', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Lóbulos de matriz hialina cartilaginosa com condrócitos em lacunas, permeando o osso medular e envolvendo trabéculas preexistentes; graduado pela celularidade e pela atipia nuclear.',
    criteria: [
      'Permeação da medula óssea com aprisionamento de trabéculas: o critério mais confiável de malignidade (o encondroma não permeia).',
      'Celularidade aumentada, binucleação, núcleos abertos e alterações mixoides da matriz.',
      'Grau 1 (hoje tumor cartilaginoso atípico nos ossos longos) não metastatiza; graus 2 e 3 sim.',
      'Correlação radiológica obrigatória: dor, tamanho acima de 5 cm, destruição cortical e localização axial pesam a favor de malignidade.',
      'Componente sarcomatoso de alto grau abrupto junto à cartilagem define o condrossarcoma desdiferenciado, de péssimo prognóstico.',
    ],
    markers: [
      { marker: 's100', pct: [85, 100], note: 'confirma linhagem condroide, não malignidade' },
      { marker: 'sox9', pct: [85, 100] },
      { marker: 'idh1', pct: [10, 25], note: 'o anticorpo VE1/R132H detecta só essa mutação; a maioria dos condrossarcomas tem IDH1 R132C, que exige sequenciamento' },
      { marker: 'ae1ae3', pct: [0, 10], note: 'negativa: separa de cordoma e de carcinoma metastático' },
      { marker: 'ema', pct: [0, 10] },
      { marker: 'braquiuria', pct: [0, 5], note: 'negativa: separa do cordoma condroide' },
      { marker: 'satb2', pct: [10, 30], note: 'ajuda pouco aqui' },
      { marker: 'h3k36m', pct: [0, 5], note: 'negativo: separa do condroblastoma' },
      { marker: 'mdm2', pct: [0, 15] },
      { marker: 'p16', pct: [30, 60] },
      { marker: 'p53', pct: [20, 50], note: 'mais nos graus altos e no desdiferenciado' },
      { marker: 'ki67', pct: [10, 50] },
      { marker: 'nkx22', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Encondroma: bem delimitado, sem permeação, hipocelular; a distinção é radiológica e arquitetural, não imuno-histoquímica.',
      'Cordoma: braquiúria e queratina positivas.',
      'Condrossarcoma mesenquimal: componente de células pequenas redondas com NKX2.2 e CD99.',
      'Osteossarcoma condroblástico: há osteoide produzido pelo tumor; jovem.',
      'Condroblastoma: H3.3 K36M positivo, epífise de jovem.',
    ],
    pitfalls: ['Nenhum marcador separa encondroma de condrossarcoma de baixo grau: sem a radiologia e a arquitetura o diagnóstico não se sustenta.'],
    molecular: 'Mutações de IDH1 (R132C mais comum) e IDH2 nos centrais; EXT1/EXT2 nos periféricos sobre osteocondroma; COL2A1 alterado.',
    sources: [WHO, 'Fletcher, Diagnostic Histopathology of Tumors, 5ª ed.'],
  },
  {
    id: 'condrossarcoma-mesenquimal',
    name: 'Condrossarcoma mesenquimal',
    aka: ['mesenchymal chondrosarcoma'],
    behavior: 'maligno',
    sites: [
      { site: 'osso', role: 'primario', freq: 1 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'meninges', role: 'primario', freq: 1 },
      { site: 'maxilares', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'cartilaginoso'],
    architecture: ['hemangiopericitoma', 'lencois', 'lobular'],
    features: ['condroide', 'calcificacao', 'mitoses-altas', 'necrose'],
    ages: ['jovem', 'adulto'],
    summary: 'Bifasia abrupta: lençóis de células pequenas redondas com vasos em galhada alternando com ilhotas de cartilagem hialina bem diferenciada, em jovens.',
    criteria: [
      'Duas fases nítidas: componente indiferenciado de células pequenas redondas e ilhotas de cartilagem madura.',
      'Vasos em galhada (hemangiopericitoma-símile) no componente de células redondas.',
      'S100 e SOX9 marcam a cartilagem; NKX2.2 e CD99 marcam as células redondas, o que pode confundir com Ewing.',
      'Fusão HEY1::NCOA2 confirma; a amostragem pode não pegar a cartilagem em biópsia pequena.',
    ],
    markers: [
      { marker: 's100', pct: [80, 95], note: 'no componente cartilaginoso, negativa nas células redondas' },
      { marker: 'sox9', pct: [80, 95] },
      { marker: 'nkx22', pct: [70, 95], note: 'no componente de células redondas: armadilha clássica com Ewing' },
      { marker: 'cd99', pct: [70, 90], note: 'idem' },
      { marker: 'fli1', pct: [10, 30] },
      { marker: 'desmina', pct: [10, 30] },
      { marker: 'miogenina', pct: [0, 5] },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 'satb2', pct: [20, 50] },
      { marker: 'braquiuria', pct: [0, 5] },
      { marker: 'bcor', pct: [0, 15] },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Sarcoma de Ewing: sem ilhotas de cartilagem; a fusão resolve (EWSR1::FLI1 vs HEY1::NCOA2).',
      'Condrossarcoma convencional de alto grau: sem componente de células pequenas redondas.',
      'Sarcoma sinovial pouco diferenciado: SS18-SSX positivo.',
      'Hemangiopericitoma/TFS: STAT6 positivo.',
    ],
    molecular: 'Fusão HEY1::NCOA2 (deleção intracromossômica em 8q) na maioria; IRF2BP2::CDX1 raramente.',
    sources: [WHO, HORNICK],
  },
  {
    id: 'condroblastoma',
    name: 'Condroblastoma',
    aka: ['chondroblastoma', 'tumor de Codman'],
    behavior: 'benigno',
    sites: [{ site: 'osso', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'cartilaginoso', 'gigantes'],
    architecture: ['lencois', 'nodular'],
    features: ['calcificacao', 'condroide', 'gigantes-osteoclasticas', 'mitoses-raras'],
    ages: ['crianca', 'jovem'],
    summary: 'Lesão epifisária de osso longo em adolescente, formada por condroblastos poligonais com núcleo sulcado, matriz condroide focal, calcificação em "tela de galinheiro" e células gigantes osteoclásticas.',
    criteria: [
      'Localização epifisária ou apofisária em esqueleto imaturo.',
      'Condroblastos mononucleares com núcleo sulcado e citoplasma nítido, com calcificação pericelular em rede.',
      'H3.3 K36M nuclear positiva: substituto da mutação de H3F3B, muito sensível e específico.',
      'Células gigantes osteoclásticas dispersas não fazem dele um tumor de células gigantes.',
    ],
    markers: [
      { marker: 'h3k36m', pct: [90, 100], note: 'nuclear nas células mononucleares; praticamente definidora' },
      { marker: 's100', pct: [70, 95] },
      { marker: 'sox9', pct: [70, 95] },
      { marker: 'dog1', pct: [60, 90], note: 'positivo em condroblastoma: armadilha se pensar em GIST fora de contexto' },
      { marker: 'ae1ae3', pct: [10, 30], note: 'focal descrita' },
      { marker: 'cd68', pct: [60, 90], note: 'nas células gigantes' },
      { marker: 'h3g34', pct: [0, 5], note: 'negativo: separa do tumor de células gigantes do osso' },
      { marker: 'satb2', pct: [20, 50] },
      { marker: 'p63', pct: [20, 50] },
      { marker: 'ki67', pct: [0, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor de células gigantes do osso: H3.3 G34W positivo, epífise mas em adulto com placa fechada.',
      'Cisto ósseo aneurismático: espaços hemorrágicos septados, USP6 rearranjado.',
      'Condrossarcoma de células claras: epifisário e maligno, células claras grandes, H3K36M negativo.',
    ],
    molecular: 'Mutação H3F3B K36M (raramente H3F3A) em mais de 90%.',
    sources: [WHO, 'Amary et al., J Pathol 2016 (H3F3 no condroblastoma e no tumor de células gigantes)'],
  },
  {
    id: 'tumor-celulas-gigantes-osso',
    name: 'Tumor de células gigantes do osso',
    aka: ['TCG ósseo', 'osteoclastoma', 'giant cell tumour of bone'],
    behavior: 'intermediario',
    sites: [
      { site: 'osso', role: 'primario', freq: 3 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['gigantes', 'fusocelular', 'epitelioide'],
    architecture: ['lencois'],
    features: ['gigantes-osteoclasticas', 'hemorragia', 'mitoses-moderadas', 'osteoide'],
    ages: ['jovem', 'adulto'],
    summary: 'Lençóis de células mononucleares ovoides misturadas a células gigantes osteoclásticas muito numerosas e uniformemente distribuídas, na epífise de osso longo com placa fechada.',
    criteria: [
      'Células gigantes osteoclásticas abundantes e regularmente distribuídas, com núcleos semelhantes aos das células mononucleares (as neoplásicas).',
      'Localização epifisária/metafisária subcondral em adulto jovem, com destruição cortical.',
      'H3.3 G34W nuclear nas células mononucleares: substituto da mutação de H3F3A, muito específico.',
      'Mitoses são comuns e não indicam malignidade; necrose, atipia e sarcoma associado indicam TCG maligno.',
      'Denosumabe altera a histologia (osso neoformado abundante, células gigantes ausentes) e pode imitar osteossarcoma.',
    ],
    markers: [
      { marker: 'h3g34', pct: [90, 100], note: 'G34W nas células mononucleares neoplásicas; negativo nas gigantes' },
      { marker: 'satb2', pct: [70, 90], note: 'nas mononucleares: não confunda com osteossarcoma' },
      { marker: 'cd68', pct: [85, 100], note: 'nas células gigantes e nos histiócitos' },
      { marker: 'catepsinak', pct: [80, 95], note: 'nas células gigantes osteoclásticas' },
      { marker: 'p63', pct: [50, 80] },
      { marker: 'runx2', pct: [50, 80] },
      { marker: 'h3k36m', pct: [0, 5], note: 'negativo: separa do condroblastoma' },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 's100', pct: [0, 15] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'p53', pct: [0, 20], note: 'aberrante no TCG maligno' },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor marrom do hiperparatireoidismo: dosar PTH e cálcio; histologia quase idêntica.',
      'Cisto ósseo aneurismático: espaços hemorrágicos com septos, USP6 rearranjado, H3.3 G34W negativo.',
      'Osteossarcoma rico em células gigantes: atipia nas mononucleares, osteoide maligno, G34W negativo.',
      'Condroblastoma: H3.3 K36M positivo, matriz condroide, adolescente.',
      'Tumor tenossinovial de células gigantes: extraósseo, desmina em células grandes, clusterina.',
    ],
    pitfalls: ['Após denosumabe o tumor vira osso neoformado com células fusiformes: já houve laudo de osteossarcoma por isso.'],
    molecular: 'Mutação H3F3A G34W (ou G34L/V) em mais de 90%; RANKL alto sustenta o tratamento com denosumabe.',
    sources: [WHO, 'Amary et al., Am J Surg Pathol 2017 (anticorpo H3.3 G34W)'],
  },
  {
    id: 'cisto-osseo-aneurismatico',
    name: 'Cisto ósseo aneurismático',
    aka: ['COA', 'aneurysmal bone cyst', 'cisto ósseo aneurismático sólido'],
    behavior: 'benigno',
    sites: [
      { site: 'osso', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'gigantes'],
    architecture: ['cistico', 'nodular'],
    features: ['hemorragia', 'gigantes-osteoclasticas', 'osteoide', 'mitoses-moderadas'],
    ages: ['crianca', 'jovem'],
    summary: 'Espaços císticos cheios de sangue separados por septos fibrosos com miofibroblastos, células gigantes osteoclásticas e osso reativo em faixa curvilínea; metáfise de osso longo ou elementos posteriores da coluna.',
    criteria: [
      'Espaços hemorrágicos sem revestimento endotelial, separados por septos fibrosos celulares.',
      'Osso reativo curvilíneo dentro dos septos, com células gigantes e hemossiderina.',
      'Rearranjo de USP6 nos primários: prova de neoplasia e separa dos secundários (que acompanham outro tumor).',
      'Excluir sempre osteossarcoma telangiectásico, que também é cístico e hemorrágico mas tem atipia acentuada.',
    ],
    markers: [
      { marker: 'satb2', pct: [50, 80], note: 'osso reativo nos septos' },
      { marker: 'cd68', pct: [70, 95], note: 'nas células gigantes' },
      { marker: 'sma', pct: [50, 80], note: 'miofibroblastos septais' },
      { marker: 'h3g34', pct: [0, 5], note: 'negativo: separa do tumor de células gigantes' },
      { marker: 'h3k36m', pct: [0, 5] },
      { marker: 'p53', pct: [0, 10], note: 'aberrante sugere osteossarcoma telangiectásico' },
      { marker: 'mdm2', pct: [0, 5] },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'cd31', pct: [0, 10], note: 'os espaços não têm revestimento endotelial' },
      { marker: 'erg', pct: [0, 10] },
      { marker: 'ki67', pct: [5, 30] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Osteossarcoma telangiectásico: atipia acentuada nos septos, osteoide maligno, p53 aberrante.',
      'Tumor de células gigantes com alteração cística secundária: H3.3 G34W positivo.',
      'Cisto ósseo simples: parede fina fibrosa, sem septos celulares.',
      'Malformação vascular intraóssea: CD31 e ERG revestindo os espaços.',
    ],
    molecular: 'Rearranjos de USP6 (17p13) com vários parceiros, presentes nos primários e ausentes nos secundários.',
    sources: [WHO, 'Oliveira et al., Am J Pathol 2004 (USP6 no cisto ósseo aneurismático)'],
  },
  {
    id: 'osteocondroma',
    name: 'Osteocondroma',
    aka: ['exostose osteocartilaginosa', 'osteochondroma', 'exostoses múltiplas hereditárias'],
    behavior: 'benigno',
    sites: [{ site: 'osso', role: 'primario', freq: 3 }],
    cells: ['cartilaginoso', 'osteoblastico'],
    architecture: ['lobular'],
    features: ['condroide', 'calcificacao', 'mitoses-raras'],
    ages: ['crianca', 'jovem'],
    summary: 'Excrescência óssea da superfície metafisária com continuidade de cortical e medular com o osso hospedeiro, coberta por capa cartilaginosa organizada como placa de crescimento.',
    criteria: [
      'Continuidade da medular e da cortical do osso com a lesão: critério radiológico definidor.',
      'Capa cartilaginosa com condrócitos em colunas, maturando em osso endocondral.',
      'Capa acima de 2 cm no adulto, dor nova e crescimento após o fechamento das placas levantam condrossarcoma secundário periférico.',
    ],
    markers: [
      { marker: 's100', pct: [90, 100], note: 'na capa cartilaginosa' },
      { marker: 'sox9', pct: [85, 100] },
      { marker: 'satb2', pct: [60, 90], note: 'no componente ósseo' },
      { marker: 'idh1', pct: [0, 5], note: 'negativo: os periféricos não têm mutação de IDH, ao contrário dos centrais' },
      { marker: 'mdm2', pct: [0, 5], note: 'negativo: separa do osteossarcoma parosteal' },
      { marker: 'p16', pct: [0, 20] },
      { marker: 'ki67', pct: [0, 5] },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'braquiuria', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Condrossarcoma periférico secundário: capa espessa e desorganizada, permeação, mitoses.',
      'Osteossarcoma parosteal: base séssil sem continuidade medular, MDM2 amplificado.',
      'Miosite ossificante e bursite: sem capa cartilaginosa organizada.',
    ],
    molecular: 'Inativação de EXT1 ou EXT2; germinativa nas exostoses múltiplas hereditárias, com risco maior de transformação.',
    sources: [WHO, 'Fletcher, Diagnostic Histopathology of Tumors, 5ª ed.'],
  },
  {
    id: 'cordoma',
    name: 'Cordoma',
    aka: ['chordoma', 'cordoma convencional', 'cordoma condroide', 'cordoma pouco diferenciado'],
    behavior: 'maligno',
    sites: [
      { site: 'osso', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 2 },
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'claras', 'oncocitico'],
    architecture: ['lobular', 'trabecular'],
    features: ['estroma-mixoide', 'hialinizacao', 'mitoses-raras', 'necrose'],
    ages: ['adulto', 'idoso'],
    summary: 'Cordões e lóbulos de células fisalíferas (vacuoladas, com aspecto de bolha) em matriz mixoide azulada, na linha média: clivus, coluna e sacro.',
    criteria: [
      'Células fisalíferas eosinofílicas e vacuoladas em cordões dentro de matriz mixoide, separadas por septos fibrosos.',
      'Localização estritamente na linha média do esqueleto axial.',
      'Braquiúria nuclear positiva com queratina e EMA: a tríade que define, já que nenhum outro tumor nessa topografia é braquiúria positivo.',
      'Variante pouco diferenciada: perda de INI1, células rabdoides, criança ou jovem, comportamento agressivo.',
    ],
    markers: [
      { marker: 'braquiuria', pct: [90, 100], note: 'nuclear; praticamente definidora' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'ck19', pct: [60, 90] },
      { marker: 'ema', pct: [80, 95] },
      { marker: 's100', pct: [80, 95], note: 'positiva: não confunda com condrossarcoma' },
      { marker: 'ini1', pct: [5, 15], note: 'perda na variante pouco diferenciada (SMARCB1-deficiente)' },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'cea', pct: [0, 20] },
      { marker: 'sox9', pct: [50, 80] },
      { marker: 'd240', pct: [20, 50] },
      { marker: 'pax8', pct: [0, 10], note: 'negativo: separa de carcinoma renal metastático' },
      { marker: 'ttf1', pct: [0, 5] },
      { marker: 'ki67', pct: [5, 30] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Condrossarcoma (inclusive do clivus): S100 positivo mas queratina e braquiúria negativas.',
      'Carcinoma metastático de células claras renal: PAX8 e CA-IX positivos, braquiúria negativa.',
      'Cordoma pouco diferenciado vs tumor rabdoide: ambos perdem INI1; braquiúria decide.',
      'Mixopapilar ependimoma (filum terminal): GFAP positivo, queratina negativa.',
      'Notocorda ectópica benigna (tumor de células notocordais benigno): intraósseo, sem matriz mixoide lobulada nem destruição.',
    ],
    molecular: 'Duplicação de TBXT (braquiúria) nos familiares; perdas de CDKN2A e de PTEN; SMARCB1 deletado nos pouco diferenciados.',
    sources: [WHO, HORNICK],
  },
  {
    id: 'adamantinoma',
    name: 'Adamantinoma do osso',
    aka: ['adamantinoma da tíbia', 'adamantinoma osteofibroso-símile'],
    behavior: 'maligno',
    sites: [{ site: 'osso', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'basaloide', 'fusocelular'],
    architecture: ['ninhos', 'trabecular', 'glandulas', 'palicada'],
    features: ['osteoide', 'desmoplasia', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Ninhos e cordões epiteliais basaloides, com paliçada periférica, imersos em estroma fibro-ósseo, na cortical anterior da tíbia (diáfise), em adultos jovens.',
    criteria: [
      'Componente epitelial verdadeiro (queratinas de alto e baixo peso, p63) dentro de estroma osteofibroso.',
      'Localização característica: diáfise da tíbia, e às vezes fíbula, com aspecto radiológico em bolhas de sabão.',
      'Padrões basaloide, tubular, fusocelular e escamoide; o epitélio pode ser escasso e exigir imuno.',
      'Displasia osteofibrosa e o adamantinoma osteofibroso-símile têm células epiteliais isoladas, detectáveis só por queratina: o espectro é contínuo.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [90, 100], note: 'fundamental para achar o componente epitelial escasso' },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'ck19', pct: [70, 95] },
      { marker: 'ck14', pct: [70, 90] },
      { marker: 'p63', pct: [70, 95] },
      { marker: 'ema', pct: [40, 70] },
      { marker: 'satb2', pct: [50, 80], note: 'no componente ósseo do estroma' },
      { marker: 'vimentina', pct: [80, 95], note: 'coexpressa com queratina no epitélio' },
      { marker: 'braquiuria', pct: [0, 5] },
      { marker: 's100', pct: [0, 15] },
      { marker: 'cd34', pct: [0, 15] },
      { marker: 'ttf1', pct: [0, 5], note: 'negativo: ajuda contra metástase pulmonar' },
      { marker: 'ki67', pct: [5, 25] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Displasia osteofibrosa: sem ninhos epiteliais (apenas células isoladas queratina positivas), criança, curso benigno.',
      'Carcinoma metastático para a tíbia: idade maior, TTF-1/CDX2/GATA3 conforme a origem, sem estroma osteofibroso.',
      'Sarcoma sinovial: SS18-SSX positivo.',
      'Osteossarcoma: osteoide maligno, sem epitélio verdadeiro.',
    ],
    molecular: 'Ganhos cromossômicos (7, 8, 12, 19, 21); sem fusão característica. Alterações de MDM2 ausentes.',
    sources: [WHO, 'Fletcher, Diagnostic Histopathology of Tumors, 5ª ed.'],
  },
]
