/* ==========================================================================
   breast.ts — mama.

   Duas perguntas dominam a imuno da mama: esta lesão é invasora ou in situ
   (mioepitélio presente ou ausente) e este carcinoma é de origem mamária
   (GATA3, TRPS1, mamaglobina, GCDFP-15). Os marcadores preditivos ER, PR,
   HER2 e Ki-67 entram aqui como parte do perfil, mas o laudo deles segue os
   guias ASCO/CAP, que esta ferramenta não substitui.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Breast Tumours, 2019; recomendações ASCO/CAP para ER/PR
   e HER2; revisões de imuno-histoquímica em Am J Surg Pathol, Mod Pathol e
   Histopathology; dados do TRPS1 publicados a partir de 2021). As fontes
   estão como referência de texto: as séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Breast Tumours (2019)'
const ROSEN = "Hoda et al., Rosen's Breast Pathology, 5ª ed."
const ASCOCAP = 'Recomendações ASCO/CAP para ER/PR (2020) e HER2 (2023) em carcinoma de mama'

export const breast: Tumor[] = [
  {
    id: 'carcinoma-mama-luminal',
    name: 'Carcinoma invasivo de tipo não especial, luminal (ER positivo)',
    aka: ['carcinoma ductal invasivo', 'carcinoma invasivo NST', 'invasive breast carcinoma of no special type', 'luminal A e B'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'pleura', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
      { site: 'pele', role: 'metastase', freq: 1 },
      { site: 'ovario', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide'],
    architecture: ['ninhos', 'glandulas', 'trabecular', 'infiltrativo', 'cribriforme'],
    features: ['desmoplasia', 'mitoses-moderadas', 'calcificacao', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma invasor sem padrão especial, em ninhos, cordões e túbulos dentro de estroma desmoplásico, com receptor de estrogênio positivo; o subtipo mais comum e o de melhor prognóstico entre os invasores.',
    criteria: [
      'Invasão do estroma comprovada pela ausência de camada mioepitelial ao redor dos ninhos (p63, calponina, miosina de cadeia pesada).',
      'Padrão que não preenche critério de nenhum tipo especial (mais de 90% do tumor sem padrão especial).',
      'Graduação de Nottingham obrigatória: formação tubular, pleomorfismo nuclear e contagem de mitoses.',
      'ER, PR, HER2 e Ki-67 em todo carcinoma invasor: definem tratamento, não diagnóstico.',
      'E-caderina de membrana preservada separa do lobular.',
    ],
    markers: [
      { marker: 'er', pct: [75, 85], note: 'por definição positivo neste subtipo; o corte é 1% pelos critérios ASCO/CAP' },
      { marker: 'pr', pct: [60, 75] },
      { marker: 'her2', pct: [10, 15], note: 'o "positivo" é 3+ ou 2+ com FISH amplificado' },
      { marker: 'gata3', pct: [90, 100], note: 'o melhor marcador de origem mamária nos ER positivos' },
      { marker: 'trps1', pct: [90, 100], note: 'sensível em todos os subtipos, inclusive no triplo-negativo' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ecaderina', pct: [90, 100], pattern: 'M', note: 'membranosa preservada: separa do lobular' },
      { marker: 'p120', pct: [95, 100], pattern: 'M', note: 'membranosa; citoplasmática no lobular' },
      { marker: 'gcdfp15', pct: [40, 60], note: 'específica mas pouco sensível' },
      { marker: 'mamaglobina', pct: [50, 70] },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'ttf1', pct: [0, 3], note: 'negativo: separa de adenocarcinoma pulmonar' },
      { marker: 'pax8', pct: [0, 5], note: 'negativo: separa de mülleriano e rim' },
      { marker: 'cdx2', pct: [0, 3] },
      { marker: 'sox10', pct: [5, 15], note: 'baixa nos ER positivos; alta no triplo-negativo' },
      { marker: 'p63', pct: [0, 5], note: 'ausência de mioepitélio: é isso que prova invasão' },
      { marker: 'calponina', pct: [0, 5] },
      { marker: 'p53', pct: [15, 30], note: 'aberrante sobretudo nos de grau 3' },
      { marker: 'ki67', pct: [30, 60], note: 'usado para separar luminal A de luminal B (corte em torno de 20%)' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma lobular invasivo: perda de E-caderina, p120 citoplasmática, fila indiana.',
      'Adenose esclerosante e cicatriz radial: mioepitélio preservado em p63 e calponina.',
      'Metástase para a mama (pulmão, ovário, melanoma): GATA3 e TRPS1 negativos, TTF-1 ou PAX8 ou SOX10 positivos conforme a origem.',
      'Carcinoma de origem mamária metastático em outro sítio: GATA3 e TRPS1 positivos resolvem.',
    ],
    pitfalls: ['GATA3 também é positivo em urotelial, paratireoide, tricoblastoma e paraganglioma: use com o contexto.', 'A perda de E-caderina não é exclusiva do lobular; leia junto com p120.'],
    molecular: 'PIK3CA mutado em cerca de 40% (alvo de alpelisibe), ESR1 nas recidivas sob hormonioterapia; assinaturas genômicas guiam a quimioterapia adjuvante.',
    sources: [WHO, ROSEN, ASCOCAP],
  },
  {
    id: 'carcinoma-mama-her2',
    name: 'Carcinoma de mama HER2-positivo',
    aka: ['carcinoma HER2 superexpresso', 'HER2-positive breast carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'encefalo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide', 'pleomorfico'],
    architecture: ['ninhos', 'lencois', 'cribriforme'],
    features: ['necrose', 'mitoses-altas', 'nucleolo', 'precursor', 'linfoide'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma de grau alto com células grandes, nucléolo evidente e infiltrado linfocitário, definido pela superexpressão de HER2 (3+ por imuno ou amplificação por FISH); pode ser ER positivo ou negativo.',
    criteria: [
      'HER2 3+ pela imuno (coloração membranosa completa e intensa em mais de 10% das células) ou 2+ com amplificação confirmada por hibridização.',
      'Frequentemente associado a carcinoma ductal in situ de alto grau com comedonecrose.',
      'Categoria HER2-low (1+ ou 2+ sem amplificação) não é HER2-positivo, mas hoje tem implicação terapêutica própria.',
      'Testar em todo carcinoma invasor e repetir na recidiva ou na metástase, porque o status pode mudar.',
    ],
    markers: [
      { marker: 'her2', pct: [95, 100], note: 'definidor: 3+ ou amplificado' },
      { marker: 'er', pct: [40, 60], note: 'metade é ER positiva (luminal B HER2-positivo)' },
      { marker: 'pr', pct: [30, 50] },
      { marker: 'gata3', pct: [85, 95] },
      { marker: 'trps1', pct: [85, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ecaderina', pct: [90, 100] },
      { marker: 'gcdfp15', pct: [30, 50] },
      { marker: 'mamaglobina', pct: [40, 60] },
      { marker: 'ar', pct: [50, 80] },
      { marker: 'sox10', pct: [5, 20] },
      { marker: 'ck56', pct: [5, 20] },
      { marker: 'ttf1', pct: [0, 3] },
      { marker: 'pax8', pct: [0, 5] },
      { marker: 'p53', pct: [40, 70] },
      { marker: 'ki67', pct: [60, 90] },
      { marker: 'pdl1', pct: [10, 30] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma gástrico ou esofágico HER2-positivo metastático: CDX2 positivo, GATA3 negativo.',
      'Carcinoma seroso do endométrio: HER2 também pode estar amplificado; PAX8 e WT1 separam.',
      'Carcinoma de ductos salivares: AR, HER2 e GATA3 positivos como na mama; a topografia decide.',
      'Doença de Paget do mamilo: mesma superexpressão, mas intraepidérmica.',
    ],
    pitfalls: ['O padrão de coloração do HER2 na mama é circunferencial completo; no estômago é lateral ou basolateral, e os critérios são outros.'],
    molecular: 'Amplificação de ERBB2 em 17q12; mutações de PIK3CA coexistem e pioram a resposta ao trastuzumabe.',
    sources: [WHO, ASCOCAP],
  },
  {
    id: 'carcinoma-mama-triplo-negativo',
    name: 'Carcinoma de mama triplo-negativo (basal-like)',
    aka: ['carcinoma triplo-negativo', 'basal-like breast carcinoma', 'carcinoma com características medulares'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'encefalo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'pleomorfico', 'escamoso'],
    architecture: ['lencois', 'ninhos', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'linfoide', 'nucleolo', 'desmoplasia'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Carcinoma de alto grau em lençóis sólidos com bordas expansivas, necrose central e infiltrado linfocitário denso, negativo para ER, PR e HER2; mais comum em mulheres jovens e em portadoras de BRCA1.',
    criteria: [
      'ER e PR abaixo de 1% e HER2 não superexpresso nem amplificado.',
      'Morfologia sólida de alto grau, muitas vezes com necrose geográfica e resposta linfocitária (as antigas "características medulares").',
      'SOX10 e TRPS1 sustentam a origem mamária quando GATA3 é fraco ou negativo: é a situação mais difícil da mama metastática.',
      'Avaliar linfócitos infiltrantes do tumor e PD-L1, que orientam a imunoterapia; considerar teste germinativo de BRCA.',
    ],
    markers: [
      { marker: 'er', pct: [0, 1], note: 'por definição negativo' },
      { marker: 'pr', pct: [0, 1] },
      { marker: 'her2', pct: [0, 2] },
      { marker: 'trps1', pct: [85, 95], note: 'o marcador mais útil de origem mamária aqui' },
      { marker: 'sox10', pct: [60, 80], note: 'alta neste subtipo; cuidado, também é positiva em melanoma e salivar' },
      { marker: 'gata3', pct: [40, 65], note: 'bem menos sensível que nos ER positivos' },
      { marker: 'ck56', pct: [60, 80] },
      { marker: 'ck14', pct: [50, 75] },
      { marker: 'ck903', pct: [60, 85] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'p63', pct: [10, 30], note: 'nas áreas escamosas ou metaplásicas, não como mioepitélio' },
      { marker: 'ar', pct: [10, 30], note: 'alto no subtipo apócrino molecular (LAR)' },
      { marker: 'gcdfp15', pct: [5, 20] },
      { marker: 'mamaglobina', pct: [10, 30] },
      { marker: 'ttf1', pct: [0, 3] },
      { marker: 'pax8', pct: [0, 5] },
      { marker: 'melana', pct: [0, 3], note: 'negativa: separa do melanoma, que também é SOX10 positivo' },
      { marker: 'hmb45', pct: [0, 2] },
      { marker: 'p53', pct: [70, 90] },
      { marker: 'ki67', pct: [80, 100] },
      { marker: 'pdl1', pct: [30, 50], note: 'avaliado por CPS ou IC conforme o ensaio' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Melanoma metastático: SOX10 positivo também; Melan-A, HMB-45 e queratinas resolvem.',
      'Carcinoma escamoso metastático: p40 difuso, TRPS1 negativo.',
      'Carcinoma salivar metastático (adenoide cístico, mioepitelial): SOX10 positivo; a topografia e MYB ajudam.',
      'Linfoma de grandes células: CD45 positivo, queratina negativa.',
      'Carcinoma seroso metastático: PAX8 e WT1 positivos.',
    ],
    pitfalls: ['SOX10 positivo numa mulher com nódulo faz pensar em melanoma: em mama triplo-negativa é esperado.'],
    molecular: 'TP53 na maioria, deficiência de recombinação homóloga (BRCA1/2 germinativa em até 15%), que abre indicação de platina e inibidores de PARP.',
    sources: [WHO, ROSEN, 'Ai et al., Mod Pathol 2021 (TRPS1 como marcador de carcinoma mamário)'],
  },
  {
    id: 'carcinoma-lobular-invasivo',
    name: 'Carcinoma lobular invasivo',
    aka: ['CLI', 'invasive lobular carcinoma', 'carcinoma lobular pleomórfico'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 3 },
      { site: 'estomago', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'ovario', role: 'metastase', freq: 2 },
      { site: 'utero', role: 'metastase', freq: 1 },
      { site: 'pele', role: 'metastase', freq: 1 },
      { site: 'medula-ossea', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'anel-sinete'],
    architecture: ['fila-indiana', 'infiltrativo', 'lobular'],
    features: ['mucina', 'mitoses-raras', 'desmoplasia', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Células pequenas discoesas infiltrando em fila indiana e em anéis concêntricos ao redor de ductos, com vacúolo intracitoplasmático; perde E-caderina e é notoriamente difícil de ver na mamografia e na peça.',
    criteria: [
      'Discoesão celular com padrão em fila indiana e crescimento em alvo ao redor de estruturas normais.',
      'Perda da expressão membranosa de E-caderina com redistribuição citoplasmática de p120 catenina.',
      'Neoplasia lobular in situ adjacente é comum e apoia o diagnóstico.',
      'A variante pleomórfica tem núcleos grandes e pior prognóstico, mas o mesmo padrão de E-caderina.',
      'Metastatiza para sítios peculiares: estômago (imita gástrico difuso), peritônio, ovário, útero e órbita.',
    ],
    markers: [
      { marker: 'ecaderina', pct: [5, 15], note: 'o "positivo" é a expressão membranosa; ela está PERDIDA em 85 a 95%' },
      { marker: 'p120', pct: [95, 100], pattern: 'C', note: 'citoplasmática difusa: confirma o lobular mesmo quando a E-caderina é ambígua' },
      { marker: 'er', pct: [90, 100], note: 'mais frequentemente positivo que no NST' },
      { marker: 'pr', pct: [70, 90] },
      { marker: 'her2', pct: [0, 5], note: 'raro no clássico; ocorre no pleomórfico' },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'trps1', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'gcdfp15', pct: [50, 70], note: 'mais positivo que no NST' },
      { marker: 'mamaglobina', pct: [50, 70] },
      { marker: 'nkx31', pct: [5, 15], note: 'positividade descrita: não conclua próstata num homem com nódulo mamário' },
      { marker: 'cdx2', pct: [0, 5], note: 'negativo: chave contra gástrico difuso metastático' },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'pax8', pct: [0, 5] },
      { marker: 'ttf1', pct: [0, 3] },
      { marker: 'ki67', pct: [10, 30], note: 'em geral baixo no clássico' },
      { marker: 'p53', pct: [10, 30], note: 'aberrante no pleomórfico' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma gástrico difuso de células em anel de sinete: também perde E-caderina; GATA3, TRPS1 e ER positivos apontam mama, CDX2 aponta estômago.',
      'Carcinoma NST: E-caderina membranosa preservada.',
      'Linfoma e melanoma (pela discoesão): CD45 ou SOX10.',
      'Carcinoma lobular in situ com extensão pagetoide: mioepitélio presente em p63.',
    ],
    pitfalls: ['E-caderina fraca ou aberrante não exclui NST nem confirma lobular: use p120 junto.', 'Uma metástase gástrica de lobular já foi operada como gástrico difuso primário: a imuno resolve.'],
    molecular: 'Inativação de CDH1 (E-caderina), quase definidora; mutações germinativas de CDH1 predispõem a lobular e a gástrico difuso.',
    sources: [WHO, ROSEN],
  },
  {
    id: 'proliferacoes-intraductais',
    name: 'Proliferações intraductais: hiperplasia usual, atípica e carcinoma ductal in situ',
    aka: ['HDU', 'HDA', 'CDIS', 'ductal carcinoma in situ', 'hiperplasia ductal usual'],
    behavior: 'intermediario',
    sites: [{ site: 'mama', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'glandular'],
    architecture: ['cribriforme', 'papilar', 'micropapilar', 'lencois', 'lobular'],
    features: ['calcificacao', 'necrose', 'mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Proliferação dentro do ducto: na hiperplasia usual as células são heterogêneas com fendas periféricas irregulares; no carcinoma in situ são monótonas com espaços rígidos e a camada mioepitelial permanece íntegra.',
    criteria: [
      'A camada mioepitelial está PRESENTE em todas: é isso que as separa do carcinoma invasor.',
      'Hiperplasia usual: população mista (epitelial e mioepitelial), fendas periféricas, CK5/6 em mosaico e ER heterogêneo.',
      'Hiperplasia atípica e carcinoma in situ: população monótona, espaços rígidos, CK5/6 negativa e ER difuso e forte.',
      'A distinção entre hiperplasia atípica e carcinoma in situ de baixo grau é quantitativa (extensão menor ou maior que 2 mm ou dois ductos).',
      'Graduar o carcinoma in situ pelo grau nuclear e registrar necrose comedoniana.',
    ],
    markers: [
      { marker: 'ck56', pct: [10, 25], note: 'o número vale para HDA/CDIS, que são NEGATIVOS; na hiperplasia usual o padrão é mosaico positivo' },
      { marker: 'ck14', pct: [10, 25], note: 'mesmo raciocínio do CK5/6' },
      { marker: 'er', pct: [85, 95], note: 'difuso e forte na HDA e no CDIS de baixo grau; heterogêneo na hiperplasia usual' },
      { marker: 'p63', pct: [95, 100], note: 'camada mioepitelial contínua: o achado que exclui invasão' },
      { marker: 'calponina', pct: [90, 100] },
      { marker: 'smmhc', pct: [90, 100], note: 'mais específica que a calponina, que marca miofibroblastos' },
      { marker: 'ck903', pct: [90, 100], note: 'realça mioepitélio e células basais' },
      { marker: 'colageno-iv', pct: [80, 95], note: 'membrana basal preservada' },
      { marker: 'her2', pct: [20, 40], note: 'amplificado com frequência no CDIS de alto grau' },
      { marker: 'pr', pct: [70, 90] },
      { marker: 'ecaderina', pct: [90, 100], note: 'perdida na neoplasia lobular in situ, que é o principal diferencial' },
      { marker: 'p120', pct: [95, 100] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'p53', pct: [10, 30], note: 'aberrante no CDIS de alto grau' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'trps1', pct: [90, 100] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma invasor: perda completa da camada mioepitelial em p63, calponina e miosina.',
      'Neoplasia lobular in situ: perda de E-caderina, células discoesas.',
      'Hiperplasia usual florida: CK5/6 em mosaico e ER heterogêneo.',
      'Adenose esclerosante e lesão esclerosante complexa: arquitetura distorcida mas mioepitélio preservado.',
      'Carcinoma papilar encapsulado: mioepitélio ausente na periferia da cápsula.',
    ],
    pitfalls: ['Calponina marca miofibroblastos do estroma e pode simular mioepitélio: prefira miosina de cadeia pesada ou p63.', 'O mioepitélio pode ser atenuado em ductos muito distendidos: use dois marcadores.'],
    sources: [WHO, ROSEN],
  },
  {
    id: 'carcinoma-mucinoso-mama',
    name: 'Carcinoma mucinoso da mama',
    aka: ['carcinoma coloide', 'mucinous carcinoma of the breast'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide'],
    architecture: ['ninhos', 'lobular'],
    features: ['mucina', 'mitoses-raras', 'calcificacao'],
    ages: ['idoso'],
    sex: 'f',
    summary: 'Ninhos e pequenos grupos de células tumorais brandas flutuando em lagos de mucina extracelular separados por septos fibrovasculares delicados; mulher mais velha, prognóstico bom quando puro.',
    criteria: [
      'Mais de 90% do tumor com mucina extracelular abundante (a forma mista tem pior prognóstico).',
      'Células de grau baixo a intermediário, em ninhos pequenos dentro dos lagos.',
      'ER positivo e HER2 negativo na quase totalidade.',
      'A variante com diferenciação neuroendócrina existe e não muda a conduta.',
    ],
    markers: [
      { marker: 'er', pct: [90, 100] },
      { marker: 'pr', pct: [70, 90] },
      { marker: 'her2', pct: [0, 5] },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'trps1', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ecaderina', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [30, 60], note: 'diferenciação neuroendócrina frequente no tipo B' },
      { marker: 'cromogranina', pct: [20, 50] },
      { marker: 'insm1', pct: [20, 50] },
      { marker: 'gcdfp15', pct: [40, 70] },
      { marker: 'mamaglobina', pct: [50, 80] },
      { marker: 'cdx2', pct: [0, 5], note: 'negativo: separa de metástase mucinosa gastrointestinal' },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'pax8', pct: [0, 5], note: 'negativo: separa de mucinoso ovariano' },
      { marker: 'p63', pct: [0, 5] },
      { marker: 'ki67', pct: [5, 25] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Cisto mucocele-símile: mucina extravasada sem células epiteliais flutuantes; procure atipia nos ductos.',
      'Metástase mucinosa gastrointestinal ou ovariana: CDX2, CK20, SATB2 ou PAX8 positivos.',
      'Carcinoma mucinoso cístico: entidade rara e distinta.',
    ],
    sources: [WHO, ROSEN],
  },
  {
    id: 'carcinoma-tubular-cribriforme',
    name: 'Carcinoma tubular e carcinoma cribriforme invasivo',
    aka: ['carcinoma tubular', 'invasive cribriform carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular'],
    architecture: ['glandulas', 'cribriforme', 'infiltrativo'],
    features: ['desmoplasia', 'calcificacao', 'mitoses-raras', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Túbulos angulados abertos, de camada única, com projeções apicais, dispersos ao acaso em estroma desmoplásico elástico; grau 1 por definição e prognóstico excelente.',
    criteria: [
      'Mais de 90% de túbulos angulados de camada única, com distribuição desordenada e infiltração da gordura.',
      'Ausência de camada mioepitelial nos túbulos: o que o separa da adenose esclerosante e da cicatriz radial.',
      'Núcleos de baixo grau com projeções citoplasmáticas apicais.',
      'ER e PR positivos, HER2 negativo, Ki-67 baixo.',
    ],
    markers: [
      { marker: 'er', pct: [95, 100] },
      { marker: 'pr', pct: [80, 95] },
      { marker: 'her2', pct: [0, 3] },
      { marker: 'p63', pct: [0, 5], note: 'ausência de mioepitélio: o critério de invasão' },
      { marker: 'calponina', pct: [0, 5] },
      { marker: 'smmhc', pct: [0, 5], note: 'na adenose esclerosante e na cicatriz radial estaria presente' },
      { marker: 'ck903', pct: [10, 30] },
      { marker: 'gata3', pct: [95, 100] },
      { marker: 'trps1', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ecaderina', pct: [90, 100] },
      { marker: 'colageno-iv', pct: [0, 20], note: 'membrana basal ausente ao redor dos túbulos invasores' },
      { marker: 'ki67', pct: [0, 15] },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenose esclerosante: lobulocêntrica, mioepitélio preservado.',
      'Cicatriz radial: centro fibroelastótico com ductos aprisionados, mioepitélio presente.',
      'Adenose microglandular: glândulas redondas com secreção, S100 positiva, ER negativa, sem mioepitélio.',
      'Carcinoma cribriforme in situ: mioepitélio ao redor dos espaços.',
    ],
    sources: [WHO, ROSEN],
  },
  {
    id: 'carcinoma-metaplasico',
    name: 'Carcinoma metaplásico da mama',
    aka: ['metaplastic breast carcinoma', 'carcinoma de células fusiformes', 'carcinoma com diferenciação matriz-produtora'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular', 'escamoso', 'pleomorfico', 'cartilaginoso', 'osteoblastico'],
    architecture: ['fasciculos', 'lencois', 'infiltrativo'],
    features: ['condroide', 'osteoide', 'necrose', 'mitoses-altas', 'desmoplasia'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma em que o epitélio se transforma em células fusiformes, escamosas ou em matriz condroide e óssea; quase sempre triplo-negativo, com prognóstico pior que o do triplo-negativo comum.',
    criteria: [
      'Componente mesenquimal ou escamoso predominante, com ou sem carcinoma convencional associado.',
      'Demonstração da natureza epitelial por queratinas de alto peso (CK5/6, CK14, 34βE12) e p63, que são mais sensíveis aqui que AE1/AE3.',
      'Excluir tumor filoide maligno (sem queratina e sem p63) e sarcoma primário.',
      'Quase sempre ER, PR e HER2 negativos; responde mal à quimioterapia convencional.',
    ],
    markers: [
      { marker: 'p63', pct: [70, 90], note: 'o marcador mais útil no componente fusocelular' },
      { marker: 'ck903', pct: [70, 90] },
      { marker: 'ck56', pct: [60, 85] },
      { marker: 'ck14', pct: [60, 85] },
      { marker: 'ae1ae3', pct: [50, 80], note: 'pode ser focal ou negativa: use painel amplo de queratinas' },
      { marker: 'trps1', pct: [70, 90], note: 'útil quando as queratinas falham' },
      { marker: 'sox10', pct: [50, 80], note: 'positiva: não confunda com melanoma' },
      { marker: 'gata3', pct: [20, 40], note: 'bem menos sensível aqui' },
      { marker: 'er', pct: [0, 10] },
      { marker: 'pr', pct: [0, 5] },
      { marker: 'her2', pct: [0, 5] },
      { marker: 'cd34', pct: [0, 10], note: 'negativo: separa do tumor filoide e do sarcoma' },
      { marker: 'melana', pct: [0, 3] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'betacatenina', pct: [20, 50], note: 'nuclear em parte; a via Wnt está ativada com frequência' },
      { marker: 'p53', pct: [50, 80] },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'pdl1', pct: [30, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor filoide maligno: CD34 pode ser positivo, queratinas e p63 negativos, componente epitelial benigno em fendas.',
      'Sarcoma primário de mama: queratinas e p63 negativos em painel amplo.',
      'Melanoma metastático: SOX10 positivo nos dois; Melan-A e HMB-45 resolvem.',
      'Fasciite nodular e cicatriz: sem atipia, queratinas negativas.',
    ],
    pitfalls: ['AE1/AE3 negativa não exclui: o carcinoma metaplásico exige CK5/6, CK14, 34βE12 e p63 antes de virar sarcoma.'],
    molecular: 'TP53, alterações da via PI3K/AKT e Wnt; carga mutacional alta em parte dos casos.',
    sources: [WHO, ROSEN],
  },
  {
    id: 'carcinoma-apocrino-mama',
    name: 'Carcinoma apócrino da mama',
    aka: ['apocrine carcinoma', 'carcinoma com diferenciação apócrina'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['oncocitico', 'epitelioide'],
    architecture: ['ninhos', 'lencois', 'glandulas'],
    features: ['nucleolo', 'mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Células grandes com citoplasma eosinofílico granular abundante, núcleo vesiculoso e nucléolo proeminente; fenótipo molecular apócrino: ER e PR negativos com receptor de androgênio positivo.',
    criteria: [
      'Diferenciação apócrina em mais de 90% do tumor: citoplasma granular eosinofílico com secreção por decapitação.',
      'Perfil ER e PR negativos com AR positivo (o chamado triplo-negativo apócrino molecular ou LAR).',
      'HER2 amplificado numa parcela relevante.',
      'GCDFP-15 muito positiva, o que é útil quando o tumor aparece como metástase.',
    ],
    markers: [
      { marker: 'ar', pct: [90, 100], note: 'o marcador que define o fenótipo apócrino' },
      { marker: 'gcdfp15', pct: [80, 95] },
      { marker: 'er', pct: [0, 10] },
      { marker: 'pr', pct: [0, 5] },
      { marker: 'her2', pct: [30, 50] },
      { marker: 'gata3', pct: [85, 100] },
      { marker: 'trps1', pct: [80, 95] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'mamaglobina', pct: [20, 50] },
      { marker: 'sox10', pct: [5, 20] },
      { marker: 'ck56', pct: [10, 30] },
      { marker: 'ttf1', pct: [0, 3] },
      { marker: 'pax8', pct: [0, 5] },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'p53', pct: [30, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma oncocítico e de células claras: sem secreção por decapitação nem AR difuso.',
      'Carcinoma de ductos salivares metastático: AR, HER2, GATA3 e GCDFP-15 positivos também; a topografia decide.',
      'Metaplasia apócrina atípica e cisto apócrino: sem invasão nem atipia acentuada.',
      'Melanoma: SOX10 e Melan-A.',
    ],
    molecular: 'PIK3CA e PTEN alterados; via do receptor de androgênio ativa, com ensaios de antiandrogênios.',
    sources: [WHO, ROSEN],
  },
  {
    id: 'carcinoma-micropapilar-mama',
    name: 'Carcinoma micropapilar invasivo da mama',
    aka: ['invasive micropapillary carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular'],
    architecture: ['micropapilar', 'ninhos'],
    features: ['desmoplasia', 'mitoses-moderadas', 'calcificacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Aglomerados ocos de células sem eixo fibrovascular, flutuando em lacunas estromais retraídas, com polaridade invertida; altíssima taxa de invasão linfática e de metástase nodal.',
    criteria: [
      'Ninhos micropapilares sem eixo conjuntivo, em espaços claros que imitam vasos.',
      'Polaridade invertida demonstrada pelo EMA na face externa (voltada para o estroma), que é o achado característico.',
      'Invasão linfovascular extensa e comprometimento nodal precoce: o estadiamento pesa mais que o grau.',
      'Em geral ER positivo; HER2 amplificado numa parte.',
    ],
    markers: [
      { marker: 'ema', pct: [90, 100], note: 'padrão invertido: marca a superfície voltada para o estroma' },
      { marker: 'er', pct: [80, 95] },
      { marker: 'pr', pct: [60, 80] },
      { marker: 'her2', pct: [15, 35] },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'trps1', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ecaderina', pct: [85, 100] },
      { marker: 'd240', pct: [0, 10], note: 'os espaços ao redor dos ninhos NÃO são vasos linfáticos: D2-40 negativo os delimita' },
      { marker: 'cd31', pct: [0, 10] },
      { marker: 'wt1', pct: [0, 10], note: 'negativo: separa do seroso micropapilar' },
      { marker: 'pax8', pct: [0, 5] },
      { marker: 'ttf1', pct: [0, 3] },
      { marker: 'ki67', pct: [30, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma seroso metastático micropapilar: PAX8 e WT1 positivos.',
      'Carcinoma urotelial micropapilar: GATA3 positivo também; uroplaquina e p63 separam.',
      'Retração artefactual em carcinoma NST: sem polaridade invertida no EMA.',
      'Invasão linfovascular verdadeira: D2-40 e CD31 marcam o revestimento.',
    ],
    pitfalls: ['As lacunas parecem vasos e inflam o estadiamento: use D2-40 antes de laudar invasão linfática extensa.'],
    sources: [WHO, ROSEN],
  },
  {
    id: 'carcinoma-papilar-mama',
    name: 'Carcinoma papilar da mama',
    aka: ['carcinoma papilar encapsulado', 'carcinoma papilar sólido', 'carcinoma papilar intraductal', 'papiloma (diferencial)'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide', 'neuroendocrino'],
    architecture: ['papilar', 'cistico', 'lencois'],
    features: ['hemorragia', 'calcificacao', 'mitoses-raras', 'precursor'],
    ages: ['idoso'],
    sex: 'f',
    summary: 'Lesão papilar com eixos fibrovasculares revestidos por epitélio monótono sem mioepitélio, dentro de um cisto com cápsula fibrosa; descarga papilar sanguinolenta em mulher mais velha.',
    criteria: [
      'Eixos fibrovasculares revestidos por população epitelial monótona, SEM camada mioepitelial sobre as papilas.',
      'Carcinoma papilar encapsulado: também sem mioepitélio na periferia da cápsula, o que o distingue do carcinoma in situ papilar.',
      'Carcinoma papilar sólido: nódulos expansivos com paliçada e frequente diferenciação neuroendócrina.',
      'O papiloma benigno mantém mioepitélio nas papilas e tem CK5/6 em mosaico.',
      'Em geral ER forte, HER2 negativo e comportamento indolente, tratado como in situ quando encapsulado e sem invasão franca.',
    ],
    markers: [
      { marker: 'p63', pct: [0, 10], note: 'mioepitélio AUSENTE nas papilas; presente no papiloma' },
      { marker: 'calponina', pct: [0, 10] },
      { marker: 'smmhc', pct: [0, 10] },
      { marker: 'ck903', pct: [5, 20], note: 'no papiloma realça células basais e o padrão em mosaico' },
      { marker: 'ck56', pct: [0, 15], note: 'negativa: no papiloma é mosaico positivo' },
      { marker: 'er', pct: [90, 100], note: 'difuso e forte; heterogêneo no papiloma' },
      { marker: 'pr', pct: [70, 90] },
      { marker: 'her2', pct: [0, 5] },
      { marker: 'sinaptofisina', pct: [40, 70], note: 'no tipo sólido, que é frequentemente neuroendócrino' },
      { marker: 'cromogranina', pct: [30, 60] },
      { marker: 'insm1', pct: [30, 60] },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'trps1', pct: [90, 100] },
      { marker: 'ecaderina', pct: [90, 100] },
      { marker: 'ki67', pct: [5, 25] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Papiloma intraductal: mioepitélio presente nas papilas, CK5/6 em mosaico, ER heterogêneo.',
      'Carcinoma papilar in situ: mioepitélio ausente nas papilas mas presente na periferia do ducto.',
      'Carcinoma micropapilar invasivo: ninhos sem eixo, polaridade invertida.',
      'Metástase de carcinoma papilar de tireoide: TTF-1 e tireoglobulina positivos.',
    ],
    sources: [WHO, ROSEN],
  },
  {
    id: 'paget-mamilo',
    name: 'Doença de Paget do mamilo',
    aka: ['mammary Paget disease', 'doença de Paget mamária'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 2 },
      { site: 'pele', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'claras'],
    architecture: ['ninhos', 'fila-indiana'],
    features: ['mucina', 'mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Células grandes de citoplasma pálido, isoladas e em pequenos grupos, dentro da epiderme do mamilo, com eczema e erosão clínicos; quase sempre há carcinoma ductal in situ ou invasor subjacente.',
    criteria: [
      'Células de Paget intraepidérmicas com núcleo grande, nucléolo evidente e citoplasma abundante pálido.',
      'CK7 e HER2 positivos com p63 e SOX10 negativos.',
      'Investigar sempre o parênquima subjacente: carcinoma in situ de alto grau ou invasor está presente em mais de 90%.',
      'Diferente da doença de Paget extramamária, aqui a superexpressão de HER2 é a regra.',
    ],
    markers: [
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'her2', pct: [80, 95], note: 'muito mais frequente que na forma extramamária' },
      { marker: 'gata3', pct: [85, 100] },
      { marker: 'trps1', pct: [80, 95] },
      { marker: 'ema', pct: [90, 100] },
      { marker: 'cea', pct: [50, 80] },
      { marker: 'gcdfp15', pct: [40, 70] },
      { marker: 'er', pct: [20, 40], note: 'menos frequente que no carcinoma invasor comum' },
      { marker: 'ar', pct: [40, 70] },
      { marker: 'p63', pct: [0, 5], note: 'negativo: separa da doença de Bowen' },
      { marker: 'p40', pct: [0, 3] },
      { marker: 'sox10', pct: [0, 10], note: 'negativo: separa do melanoma in situ' },
      { marker: 'melana', pct: [0, 5] },
      { marker: 's100', pct: [10, 30], note: 'pode ser fraca: não use isolada contra melanoma' },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'ki67', pct: [40, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Melanoma in situ do mamilo: SOX10 e Melan-A positivos, CK7 negativa.',
      'Doença de Bowen: p63 e p40 positivos, CK7 negativa.',
      'Células claras de Toker: benignas, CK7 positivas também, mas sem atipia.',
      'Eczema do mamilo: sem células atípicas intraepidérmicas.',
    ],
    sources: [WHO, ROSEN],
  },
  {
    id: 'fibroadenoma-filoide',
    name: 'Fibroadenoma e tumor filoide',
    aka: ['fibroadenoma', 'phyllodes tumour', 'tumor filoide benigno, borderline e maligno', 'cistossarcoma filoide (nome antigo)'],
    behavior: 'intermediario',
    sites: [
      { site: 'mama', role: 'primario', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular', 'glandular', 'bifasico'],
    architecture: ['lobular', 'fasciculos', 'cistico'],
    features: ['estroma-mixoide', 'hialinizacao', 'mitoses-raras', 'mitoses-moderadas'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Lesões fibroepiteliais bifásicas: o fibroadenoma tem estroma uniforme pobre em células, o filoide tem estroma mais celular condensado sob o epitélio, com arquitetura em folhas e fendas.',
    criteria: [
      'Bifasia com componente epitelial benigno e componente estromal neoplásico.',
      'Fibroadenoma: estroma hipocelular uniforme, sem condensação periductal, sem atipia, margens circunscritas.',
      'Filoide: celularidade estromal aumentada e heterogênea com condensação subepitelial, arquitetura em folhas.',
      'Graduação do filoide por celularidade, atipia, mitoses, bordas e crescimento estromal excessivo: benigno, borderline e maligno.',
      'No filoide maligno o componente estromal é sarcomatoso e pode perder o epitélio: procure-o antes de chamar de sarcoma.',
    ],
    markers: [
      { marker: 'cd34', pct: [60, 90], note: 'no estroma do fibroadenoma e do filoide benigno; perde-se nos malignos' },
      { marker: 'betacatenina', pct: [30, 60], pattern: 'N', note: 'nuclear no estroma, mais frequente nos filoides' },
      { marker: 'ki67', pct: [10, 40], note: 'no estroma; alto no borderline e no maligno' },
      { marker: 'p53', pct: [10, 40], note: 'aberrante no filoide maligno' },
      { marker: 'er', pct: [70, 95], note: 'no componente epitelial; o estroma é negativo' },
      { marker: 'pr', pct: [60, 90] },
      { marker: 'p63', pct: [80, 100], note: 'mioepitélio preservado no componente epitelial' },
      { marker: 'calponina', pct: [80, 100] },
      { marker: 'ck903', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [0, 10], note: 'estroma negativo: separa do carcinoma metaplásico fusocelular' },
      { marker: 'sma', pct: [30, 60] },
      { marker: 'desmina', pct: [10, 30] },
      { marker: 'stat6', pct: [0, 10], note: 'negativo: separa do tumor fibroso solitário' },
      { marker: 'mdm2', pct: [0, 15], note: 'amplificado em raros filoides malignos com desdiferenciação lipossarcomatosa' },
      { marker: 'ck7', pct: [85, 100], note: 'só o componente epitelial; o estroma é negativo' },
      { marker: 'gata3', pct: [80, 100], note: 'idem' },
      { marker: 'trps1', pct: [70, 95], note: 'epitélio; o estroma do filoide também pode marcar e confundir com metaplásico' },
      { marker: 'ecaderina', pct: [90, 100], note: 'epitélio' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma metaplásico fusocelular: queratinas e p63 positivos no componente fusocelular.',
      'Sarcoma primário de mama: sem componente epitelial em amostragem ampla.',
      'Hamartoma e hiperplasia estromal pseudoangiomatosa: sem arquitetura em folhas.',
      'Fibroadenoma celular juvenil: adolescente, estroma celular mas uniforme.',
    ],
    pitfalls: ['A biópsia por agulha não separa bem fibroadenoma de filoide benigno: o laudo honesto é "lesão fibroepitelial" com a recomendação de excisão quando há celularidade estromal.'],
    molecular: 'MED12 mutado nos dois; nos filoides de maior grau somam-se TERT promotor, TP53, RB1 e EGFR.',
    sources: [WHO, ROSEN],
  },
  {
    id: 'net-mama',
    name: 'Tumor neuroendócrino de mama',
    aka: ['carcinoma neuroendócrino de mama', 'neuroendocrine tumour of the breast'],
    behavior: 'maligno',
    sites: [
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['neuroendocrino', 'epitelioide', 'plasmocitoide', 'fusocelular'],
    architecture: ['ninhos', 'trabecular', 'organoide', 'lencois'],
    features: ['mitoses-raras', 'mitoses-moderadas', 'mucina'],
    ages: ['idoso'],
    sex: 'f',
    summary: 'Carcinoma de células uniformes plasmocitoides ou fusiformes em ninhos coesos com estroma delicado, expressando marcadores neuroendócrinos de forma difusa; é ER positivo, o que o separa de metástase.',
    criteria: [
      'Morfologia neuroendócrina com expressão difusa (mais de 90% das células) de sinaptofisina ou cromogranina: expressão focal em carcinoma comum não conta.',
      'ER positivo e GATA3 positivo: sustentam origem mamária.',
      'Excluir metástase de tumor neuroendócrino de pulmão ou de intestino, que é bem mais comum que o primário mamário.',
      'O carcinoma neuroendócrino de pequenas células e de grandes células da mama é entidade separada e agressiva.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [90, 100], note: 'difusa por definição' },
      { marker: 'cromogranina', pct: [50, 80] },
      { marker: 'insm1', pct: [70, 95] },
      { marker: 'er', pct: [85, 100], note: 'o argumento mais forte contra metástase de NET pulmonar ou intestinal' },
      { marker: 'pr', pct: [60, 85] },
      { marker: 'gata3', pct: [80, 95] },
      { marker: 'trps1', pct: [80, 95] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'mamaglobina', pct: [40, 70] },
      { marker: 'gcdfp15', pct: [30, 60] },
      { marker: 'ttf1', pct: [0, 5], note: 'negativo: separa de carcinoide pulmonar metastático' },
      { marker: 'cdx2', pct: [0, 5], note: 'negativo: separa de NET de intestino médio' },
      { marker: 'satb2', pct: [0, 5] },
      { marker: 'her2', pct: [0, 10] },
      { marker: 'ecaderina', pct: [70, 95] },
      { marker: 'ki67', pct: [20, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoide pulmonar metastático: TTF-1 positivo, ER negativo.',
      'NET de intestino médio metastático: CDX2 e serotonina positivos.',
      'Carcinoma lobular sólido: perda de E-caderina, marcadores neuroendócrinos negativos.',
      'Carcinoma papilar sólido: pode ser neuroendócrino também; a arquitetura papilar decide.',
      'Linfoma e plasmocitoma (pela citologia plasmocitoide): CD45, CD138, queratina.',
    ],
    pitfalls: ['Sinaptofisina focal aparece em muitos carcinomas mamários comuns e não faz o diagnóstico.'],
    sources: [WHO, ROSEN],
  },
  {
    id: 'adenomioepitelioma',
    name: 'Adenomioepitelioma e tumores mioepiteliais da mama',
    aka: ['adenomyoepithelioma', 'mioepitelioma de mama', 'adenomioepitelioma com carcinoma'],
    behavior: 'intermediario',
    sites: [{ site: 'mama', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'claras', 'fusocelular', 'bifasico'],
    architecture: ['lobular', 'glandulas', 'nodular'],
    features: ['hialinizacao', 'mitoses-raras', 'calcificacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Proliferação bifásica de glândulas revestidas por epitélio luminal e envolvidas por uma camada expandida de células mioepiteliais claras ou fusiformes, formando nódulo circunscrito.',
    criteria: [
      'Dupla população evidente: células luminais (queratina e ER) e mioepiteliais expandidas (p63, calponina, SOX10, S100).',
      'Arquitetura nodular ou lobulada, muitas vezes com hialinização central.',
      'Malignidade quando há atipia acentuada, necrose, mitoses numerosas e crescimento infiltrativo em qualquer um dos componentes.',
      'A variante ER negativa costuma ter mutações de HRAS com PIK3CA ou PIK3R1.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'marca a camada mioepitelial expandida: o achado central' },
      { marker: 'calponina', pct: [85, 100] },
      { marker: 'smmhc', pct: [80, 95] },
      { marker: 'sma', pct: [80, 95] },
      { marker: 's100', pct: [70, 90] },
      { marker: 'sox10', pct: [70, 95], note: 'positiva no componente mioepitelial' },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'ck56', pct: [70, 90] },
      { marker: 'ck7', pct: [80, 95], note: 'no componente luminal' },
      { marker: 'er', pct: [40, 70], note: 'no componente luminal; a variante ER negativa é mais agressiva' },
      { marker: 'gata3', pct: [70, 90] },
      { marker: 'her2', pct: [0, 10] },
      { marker: 'ki67', pct: [5, 30] },
      { marker: 'p53', pct: [10, 30], note: 'aberrante nas formas malignas' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Papiloma com hiperplasia mioepitelial: arquitetura papilar com eixos fibrovasculares.',
      'Carcinoma metaplásico de células claras: sem dupla população organizada.',
      'Adenose esclerosante: lobulocêntrica, sem nódulo expansivo.',
      'Tumor filoide: estroma fusocelular sem fenótipo mioepitelial (p63 e SOX10 negativos no estroma).',
    ],
    molecular: 'HRAS Q61 com PIK3CA ou PIK3R1 nas variantes ER negativas; PIK3CA isolada nas ER positivas.',
    sources: [WHO, ROSEN],
  },
  {
    id: 'adenose-microglandular',
    name: 'Adenose microglandular',
    aka: ['microglandular adenosis', 'adenose microglandular atípica'],
    behavior: 'intermediario',
    sites: [{ site: 'mama', role: 'primario', freq: 1 }],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'infiltrativo'],
    features: ['coloide', 'mitoses-raras'],
    ages: ['adulto'],
    sex: 'f',
    summary: 'Glândulas pequenas, redondas e uniformes, de camada única, com secreção eosinofílica densa na luz, infiltrando gordura e estroma sem camada mioepitelial; benigna na aparência mas precursora de carcinoma triplo-negativo.',
    criteria: [
      'Glândulas redondas abertas, não anguladas, de epitélio cuboidal único sem projeções apicais, com secreção colóide-símile.',
      'AUSÊNCIA de camada mioepitelial (p63 e calponina negativos), mas com membrana basal preservada em colágeno IV e laminina: é isso que a separa do carcinoma tubular.',
      'S100 difusamente positiva com ER, PR e HER2 negativos: perfil oposto ao do carcinoma tubular.',
      'Pode progredir para adenose microglandular atípica e para carcinoma triplo-negativo: excisão completa é a conduta.',
    ],
    markers: [
      { marker: 's100', pct: [95, 100], note: 'difusa e forte; o marcador que define a lesão' },
      { marker: 'er', pct: [0, 5], note: 'negativo: o oposto do carcinoma tubular' },
      { marker: 'pr', pct: [0, 5] },
      { marker: 'her2', pct: [0, 5] },
      { marker: 'p63', pct: [0, 5], note: 'mioepitélio ausente, o que assusta e simula invasão' },
      { marker: 'calponina', pct: [0, 5] },
      { marker: 'smmhc', pct: [0, 5] },
      { marker: 'colageno-iv', pct: [85, 100], note: 'membrana basal PRESENTE: o que a separa do carcinoma invasor' },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'gata3', pct: [10, 40], note: 'muitas vezes negativa, ao contrário do carcinoma mamário comum' },
      { marker: 'sox10', pct: [60, 90] },
      { marker: 'ck903', pct: [0, 20] },
      { marker: 'ki67', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma tubular: túbulos angulados, ER positivo, S100 negativa, sem membrana basal.',
      'Adenose esclerosante: mioepitélio presente, lobulocêntrica.',
      'Carcinoma secretor: também S100 positivo; tem ETV6::NTRK3 e secreção intracitoplasmática.',
      'Carcinoma triplo-negativo surgido em adenose microglandular: transição morfológica, Ki-67 e atipia maiores.',
    ],
    pitfalls: ['A ausência de mioepitélio leva a laudar carcinoma invasor: o colágeno IV preservado e o S100 difuso evitam o erro.'],
    sources: [WHO, ROSEN],
  },
  {
    id: 'pash',
    name: 'Hiperplasia estromal pseudoangiomatosa (PASH)',
    aka: ['PASH', 'pseudoangiomatous stromal hyperplasia'],
    behavior: 'benigno',
    sites: [{ site: 'mama', role: 'primario', freq: 2 }],
    cells: ['fusocelular'],
    architecture: ['fasciculos'],
    features: ['hialinizacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Rede de fendas anastomosadas em estroma colagenizado denso, revestidas por células miofibroblásticas fusiformes achatadas que imitam endotélio, sem hemácias dentro das fendas.',
    criteria: [
      'Fendas vazias, sem hemácias, num estroma colágeno denso, formando rede anastomosada.',
      'Células de revestimento miofibroblásticas: CD34 e actina positivas, com CD31 e ERG NEGATIVOS.',
      'Ausência de atipia, mitoses e infiltração de gordura de forma destrutiva.',
      'A forma tumoral faz massa; a forma incidental aparece em qualquer biópsia mamária.',
    ],
    markers: [
      { marker: 'cd34', pct: [85, 100], note: 'nas células que revestem as fendas' },
      { marker: 'sma', pct: [60, 90] },
      { marker: 'desmina', pct: [30, 70] },
      { marker: 'pr', pct: [60, 90], note: 'estroma PR positivo: base da relação com hormônios' },
      { marker: 'er', pct: [20, 50] },
      { marker: 'cd31', pct: [0, 5], note: 'NEGATIVO: o achado que exclui angiossarcoma' },
      { marker: 'erg', pct: [0, 5], note: 'idem; é o mais confiável' },
      { marker: 'd240', pct: [0, 15] },
      { marker: 'myc', pct: [0, 5], note: 'negativo: separa de angiossarcoma pós-radioterapia' },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'stat6', pct: [0, 5] },
      { marker: 'ki67', pct: [0, 5] },
      { marker: 'gata3', pct: 0, note: 'o negativo esperado: a lesão é estromal, não epitelial' },
      { marker: 'trps1', pct: 0 },
      { marker: 'ck7', pct: 0 },
      { marker: 'p63', pct: 0 },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Angiossarcoma de baixo grau: canais com hemácias, CD31 e ERG positivos, atipia endotelial.',
      'Tumor filoide: arquitetura em folhas com componente epitelial.',
      'Miofibroblastoma de mama: nódulo de células fusiformes em faixas de colágeno, CD34 e desmina positivos.',
      'Fibroadenoma com alterações estromais: bifasia evidente.',
    ],
    pitfalls: ['É o principal simulador benigno de angiossarcoma na mama: ERG negativo resolve em um anticorpo.'],
    sources: [WHO, ROSEN],
  },
  {
    id: 'lobular-in-situ',
    name: 'Carcinoma lobular in situ e hiperplasia lobular atípica',
    aka: ['CLIS', 'LCIS', 'neoplasia lobular', 'hiperplasia lobular atípica', 'HLA'],
    behavior: 'intermediario',
    sites: [{ site: 'mama', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'plasmocitoide'],
    architecture: ['lobular', 'fila-indiana'],
    features: ['precursor', 'mitoses-raras', 'calcificacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Proliferação de células pequenas, uniformes e discoesas que preenche e distende os ácinos de um lóbulo, muitas vezes com vacúolo intracitoplasmático e corpo de inclusão; a perda de E-caderina com p120 redistribuído para o citoplasma é o par que a define, e a distinção entre a forma clássica e as variantes pleomórfica e florida muda a conduta cirúrgica.',
    criteria: [
      'Células discoesas, pequenas e monótonas (tipo A) ou um pouco maiores com nucléolo (tipo B), preenchendo os ácinos.',
      'Distensão de mais da metade dos ácinos de um lóbulo define carcinoma lobular in situ; menos que isso é hiperplasia lobular atípica.',
      'Perda da E-caderina de membrana com p120 citoplasmático: é o critério imuno, e vale também para o componente que se espalha em pagetoide pelos ductos.',
      'Variante pleomórfica: atipia de alto grau, muitas vezes com necrose comedo e HER2 amplificado; variante florida: distensão maciça com necrose.',
      'O clássico é marcador de risco bilateral e não exige margem livre; as variantes pleomórfica e florida são tratadas como o carcinoma ductal in situ.',
    ],
    markers: [
      { marker: 'ecaderina', pct: [0, 10], note: 'o positivo aqui seria a marcação de membrana, que está perdida: é o critério definidor' },
      { marker: 'p120', pct: [95, 100], note: 'citoplasmático difuso, e não de membrana como no ductal' },
      { marker: 'ck903', pct: [80, 95], note: 'perinuclear em alça, achado clássico do lobular' },
      { marker: 'er', pct: [90, 100] },
      { marker: 'pr', pct: [80, 95] },
      { marker: 'gata3', pct: [95, 100] },
      { marker: 'trps1', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'p63', pct: [95, 100], note: 'mioepitélio preservado ao redor: é o que prova que a lesão é in situ' },
      { marker: 'calponina', pct: [95, 100] },
      { marker: 'smmhc', pct: [90, 100] },
      { marker: 'her2', pct: [0, 10], note: 'no clássico; na variante pleomórfica chega a cerca de um terço' },
      { marker: 'p53', pct: [0, 10], note: 'selvagem no clássico' },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma ductal in situ sólido de baixo grau: E-caderina de membrana preservada, células coesas.',
      'Hiperplasia usual florida: população heterogênea, CK5/6 em mosaico, E-caderina preservada.',
      'Carcinoma lobular invasivo: ausência de mioepitélio ao redor dos ninhos.',
      'Artefato de retração e ácinos com secreção: sem população monótona distendendo o lóbulo.',
      'Adenose com envolvimento por neoplasia lobular: mioepitélio presente, arquitetura lobulada mantida.',
    ],
    pitfalls: ['E-caderina fracamente positiva não exclui neoplasia lobular; interprete junto com o p120, que é o marcador mais confiável do par.'],
    molecular: 'Perda de CDH1 (16q22) com deleção de 16q; a variante pleomórfica acrescenta ERBB2 e TP53.',
    sources: [WHO, ROSEN],
  },
  {
    id: 'atipia-epitelial-plana',
    name: 'Atipia epitelial plana e lesões de células colunares',
    aka: ['FEA', 'flat epithelial atypia', 'alteração de células colunares', 'CCC', 'CCH'],
    behavior: 'intermediario',
    sites: [{ site: 'mama', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'glandular'],
    architecture: ['cistico', 'glandulas', 'lobular'],
    features: ['calcificacao', 'precursor', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Unidade ducto-lobular terminal com ácinos dilatados revestidos por uma a poucas camadas de células colunares com projeções apicais e secreção luminal densa, quase sempre com microcalcificações — é a lesão que traz a paciente da mamografia. Quando essas células ganham atipia citológica de baixo grau sem qualquer complexidade arquitetural, chama-se atipia epitelial plana.',
    criteria: [
      'Ácinos dilatados e arredondados revestidos por epitélio colunar com projeções apicais (snouts) e secreção luminal.',
      'Microcalcificações quase sempre presentes: é o que faz a lesão ser biopsiada.',
      'Atipia epitelial plana: atipia citológica monótona de baixo grau (núcleo redondo, nucléolo pequeno) em epitélio plano, com no máximo cinco camadas.',
      'Ausência de arquitetura complexa: qualquer ponte rígida, micropapila ou cribra leva ao diagnóstico de hiperplasia ductal atípica ou carcinoma ductal in situ.',
      'Faz parte da família de baixo grau da mama, junto com a hiperplasia ductal atípica, o carcinoma tubular e a neoplasia lobular, que costumam aparecer no mesmo espécime.',
    ],
    markers: [
      { marker: 'er', pct: [95, 100], note: 'forte e difuso em todas as células, diferente do padrão heterogêneo da hiperplasia usual' },
      { marker: 'pr', pct: [85, 100] },
      { marker: 'ck56', pct: [0, 10], note: 'o negativo é o achado: a hiperplasia usual é positiva em mosaico' },
      { marker: 'ck903', pct: [0, 15] },
      { marker: 'ck14', pct: [0, 10] },
      { marker: 'gata3', pct: [95, 100] },
      { marker: 'trps1', pct: [90, 100] },
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'ecaderina', pct: [90, 100] },
      { marker: 'p63', pct: [95, 100], note: 'mioepitélio preservado' },
      { marker: 'calponina', pct: [95, 100] },
      { marker: 'her2', pct: [0, 5] },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Alteração de células colunares sem atipia: mesma arquitetura, núcleo basal ordenado e sem nucléolo.',
      'Hiperplasia ductal usual: população heterogênea com CK5/6 em mosaico e ER heterogêneo.',
      'Hiperplasia ductal atípica e carcinoma ductal in situ de baixo grau: têm arquitetura complexa.',
      'Cisto com metaplasia apócrina: citoplasma granular eosinofílico, ER negativo, AR positivo.',
      'Adenose e adenose esclerosante: arquitetura lobulada com mioepitélio proeminente.',
    ],
    molecular: 'Perda de 16q, a mesma alteração da família de baixo grau da mama.',
    sources: [WHO, ROSEN],
  },
  {
    id: 'adenose-esclerosante',
    name: 'Adenose esclerosante e cicatriz radial',
    aka: ['adenose esclerosante', 'cicatriz radial', 'lesão esclerosante complexa', 'radial scar'],
    behavior: 'benigno',
    sites: [{ site: 'mama', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'glandular', 'fusocelular'],
    architecture: ['lobular', 'glandulas', 'infiltrativo', 'storiforme'],
    features: ['calcificacao', 'hialinizacao', 'mitoses-raras', 'desmoplasia'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Os dois mímicos clássicos de invasão na mama: a adenose esclerosante mantém a arquitetura lobulada mesmo comprimida e distorcida, e a cicatriz radial tem um centro fibroelastótico do qual irradiam ductos aprisionados, com aspecto estrelado na mamografia. Em ambos o mioepitélio está preservado, e é isso que resolve.',
    criteria: [
      'Adenose esclerosante: proliferação de ácinos comprimidos por estroma fibroso, com lobularidade preservada em pequeno aumento — o achado que decide.',
      'Cicatriz radial: núcleo central de colágeno e tecido elástico com ductos e lóbulos irradiando, muitas vezes com alterações de células colunares na periferia.',
      'Camada mioepitelial preservada ao redor dos ácinos, demonstrada por p63, calponina e miosina de cadeia pesada.',
      'Membrana basal preservada, o que separa da adenose microglandular, que não tem mioepitélio mas tem colágeno IV.',
      'Amostrar bem a periferia: hiperplasia ductal atípica, carcinoma ductal in situ e carcinoma tubular surgem na borda da cicatriz radial.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'mioepitélio preservado; pode ser descontínuo na adenose, então use um painel e não um marcador' },
      { marker: 'calponina', pct: [90, 100] },
      { marker: 'smmhc', pct: [85, 100], note: 'a mais específica do painel mioepitelial' },
      { marker: 'ck14', pct: [80, 95] },
      { marker: 'sma', pct: [85, 100], note: 'cuidado: também marca miofibroblastos do estroma' },
      { marker: 'colageno-iv', pct: [85, 100], note: 'membrana basal presente' },
      { marker: 'er', pct: [70, 95] },
      { marker: 'pr', pct: [60, 90] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'ck56', pct: [60, 90], note: 'em mosaico nas áreas de hiperplasia usual associada' },
      { marker: 'ecaderina', pct: [90, 100] },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma tubular: túbulos angulados de camada única, mioepitélio ausente, estroma desmoplásico, e surge justamente na borda da cicatriz radial.',
      'Adenose microglandular: túbulos redondos uniformes sem mioepitélio, mas com colágeno IV e S100 positivo.',
      'Carcinoma invasivo de baixo grau: perda de mioepitélio, infiltração desordenada.',
      'Adenose apócrina: metaplasia apócrina sobre adenose, com atipia que assusta.',
      'Adenose microglandular atípica e carcinoma sobre adenose microglandular: exigem o mesmo painel.',
    ],
    pitfalls: ['O painel mioepitelial pode ficar descontínuo na adenose esclerosante e em lesões esclerosantes em geral: ausência focal não é invasão.'],
    sources: [WHO, ROSEN],
  },
  {
    id: 'papiloma-intraductal',
    name: 'Papiloma intraductal da mama',
    aka: ['papiloma ductal', 'papilomatose', 'intraductal papilloma'],
    behavior: 'benigno',
    sites: [{ site: 'mama', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'glandular'],
    architecture: ['papilar', 'cistico'],
    features: ['hemorragia', 'calcificacao', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Lesão papilar dentro de um ducto, com eixos fibrovasculares verdadeiros revestidos por epitélio e mioepitélio, que se apresenta como descarga papilar sanguinolenta quando central; a pergunta prática é se há hiperplasia ductal atípica ou carcinoma ductal in situ sobreposto, e o par CK5/6 com ER responde.',
    criteria: [
      'Eixos fibrovasculares verdadeiros revestidos por dupla camada, com mioepitélio demonstrável ao longo das papilas.',
      'Papiloma central único (descarga papilar) contra papilomas periféricos múltiplos, que têm mais risco.',
      'Epitélio sobreposto: a hiperplasia usual é CK5/6 positiva em mosaico com ER heterogêneo; a proliferação atípica é CK5/6 negativa com ER forte e difuso.',
      'Extensão da atipia decide o nome: até 3 mm, papiloma com hiperplasia ductal atípica; acima disso, papiloma com carcinoma ductal in situ.',
      'Infarto e metaplasia escamosa pós-punção produzem atipia que não deve ser lida como carcinoma.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'mioepitélio ao longo das papilas; sua ausência define carcinoma papilar intraductal' },
      { marker: 'calponina', pct: [90, 100] },
      { marker: 'smmhc', pct: [85, 100] },
      { marker: 'ck56', pct: [70, 95], note: 'em mosaico no epitélio benigno; o negativo focal marca a área atípica' },
      { marker: 'ck14', pct: [70, 90] },
      { marker: 'ck903', pct: [70, 95] },
      { marker: 'er', pct: [60, 90], note: 'heterogêneo no benigno; forte e difuso na área atípica' },
      { marker: 'pr', pct: [50, 80] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'trps1', pct: [85, 100] },
      { marker: 'ecaderina', pct: [90, 100] },
      { marker: 'her2', pct: [0, 5] },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma papilar intraductal: mioepitélio ausente nas papilas, CK5/6 negativo, ER forte e difuso.',
      'Carcinoma papilar encapsulado: cápsula fibrosa sem mioepitélio na periferia.',
      'Papiloma com carcinoma ductal in situ: área de atipia acima de 3 mm dentro de um papiloma benigno.',
      'Papiloma esclerosado com epitélio aprisionado: imita invasão; o painel mioepitelial resolve.',
      'Hiperplasia papilar juvenil (doença fibrocística): múltipla, em jovem.',
    ],
    sources: [WHO, ROSEN],
  },
  {
    id: 'miofibroblastoma-mama',
    name: 'Miofibroblastoma mamário',
    aka: ['miofibroblastoma', 'mammary-type myofibroblastoma'],
    behavior: 'benigno',
    sites: [
      { site: 'mama', role: 'primario', freq: 2 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'vulva-vagina', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'epitelioide', 'adipocitico'],
    architecture: ['fasciculos', 'nodular'],
    features: ['hialinizacao', 'vacuolos-lipidicos', 'mitoses-raras', 'estroma-mixoide'],
    ages: ['adulto', 'idoso'],
    summary: 'Nódulo bem delimitado de células fusiformes brandas dispostas em fascículos curtos e desordenados, separados por feixes de colágeno hialino espesso, com gordura entremeada; coexpressa CD34, desmina e receptores hormonais, e a perda de RB1 o coloca na mesma família 13q14 do lipoma de células fusiformes e do angiofibroma celular.',
    criteria: [
      'Nódulo circunscrito, não encapsulado, de células fusiformes ou ovoides uniformes sem atipia.',
      'Fascículos curtos em arranjo desordenado, separados por bandas de colágeno hialino grosseiro.',
      'Coexpressão de CD34 com desmina, mais ER, PR e receptor de androgênio.',
      'Perda de RB1 por imuno, refletindo a deleção de 13q14 compartilhada com o lipoma de células fusiformes.',
      'Variantes epitelioide, mixoide, lipomatosa e de células claras não mudam o comportamento, que é benigno.',
    ],
    markers: [
      { marker: 'cd34', pct: [85, 100] },
      { marker: 'desmina', pct: [80, 95], note: 'a coexpressão com CD34 é o achado que define' },
      { marker: 'rb1', pct: [80, 95], note: 'o positivo é a perda; deleção de 13q14' },
      { marker: 'er', pct: [70, 95] },
      { marker: 'pr', pct: [70, 95] },
      { marker: 'ar', pct: [70, 95] },
      { marker: 'sma', pct: [20, 50], note: 'focal; a positividade difusa favorece músculo liso verdadeiro' },
      { marker: 'caldesmon', pct: [0, 20] },
      { marker: 'stat6', pct: [0, 5], note: 'o negativo que separa do tumor fibroso solitário, que também é CD34 positivo' },
      { marker: 'ae1ae3', pct: [0, 5], note: 'o negativo que exclui carcinoma metaplásico fusocelular' },
      { marker: 'p63', pct: [0, 5] },
      { marker: 's100', pct: [0, 15] },
      { marker: 'betacatenina', pct: [0, 10], pattern: 'N', note: 'o negativo que separa da fibromatose mamária' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor fibroso solitário: STAT6 nuclear, vasos em galhada, desmina negativa.',
      'Carcinoma metaplásico fusocelular: queratina e p63 positivos.',
      'Fibromatose mamária: β-catenina nuclear, margens infiltrativas.',
      'Lipoma de células fusiformes e angiofibroma celular: mesma família com perda de RB1; a distinção é de sítio e de proporção de gordura.',
      'Leiomioma: desmina e h-caldesmon difusos, CD34 negativo.',
    ],
    molecular: 'Deleção de 13q14 com perda de RB1 e FOXO1.',
    sources: [WHO, ROSEN, "Goldblum, Folpe & Weiss, Enzinger & Weiss's Soft Tissue Tumors, 7ª ed."],
  },
]
