/* ==========================================================================
   cns.ts — sistema nervoso central, hipófise e olho.

   Desde 2021 o diagnóstico aqui é integrado: a morfologia dá o nome, o
   molecular dá o tipo e o grau pode vir do molecular mesmo com histologia
   branda (TERT, EGFR, +7/-10 fazem glioblastoma sem necrose; CDKN2A faz
   grau 4 no astrocitoma IDH-mutante). Os substitutos imuno-histoquímicos
   — IDH1 R132H, ATRX, H3 K27M, H3K27me3, BRAF V600E, L1CAM — resolvem boa
   parte dos casos sem sequenciamento.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours of the Central Nervous System, 5ª ed., 2021; Louis et al., cIMPACT-NOW;
   Perry & Brat, Practical Surgical Neuropathology, 2ª ed.; séries de Acta
   Neuropathol e Brain Pathol). As fontes estão como referência de texto: as
   séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours of the Central Nervous System, 5ª ed. (2021)'
const PERRY = 'Perry & Brat, Practical Surgical Neuropathology, 2ª ed.'
const CIMPACT = 'cIMPACT-NOW, atualizações 1 a 7 (Acta Neuropathologica)'

export const cns: Tumor[] = [
  {
    id: 'glioblastoma',
    name: 'Glioblastoma, IDH-selvagem',
    aka: ['GBM', 'glioblastoma multiforme', 'glioblastoma IDH-wildtype'],
    behavior: 'maligno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 3 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'pleomorfico', 'gigantes', 'epitelioide', 'estreladas'],
    architecture: ['lencois', 'infiltrativo', 'palicada'],
    features: ['necrose', 'mitoses-altas', 'vasos-espessos', 'hemorragia', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    summary: 'Glioma difuso astrocitário de adulto, grau 4, com pleomorfismo, mitoses, proliferação microvascular em glomérulos e necrose em pseudopaliçada; IDH-selvagem, e desde 2021 basta TERT mutado, EGFR amplificado ou ganho do 7 com perda do 10 para o diagnóstico, mesmo sem necrose.',
    criteria: [
      'Glioma difuso astrocitário de adulto, IDH-selvagem e H3-selvagem.',
      'Pelo menos um destes: necrose, proliferação microvascular, mutação do promotor de TERT, amplificação de EGFR, ou ganho do cromossomo 7 com perda do 10.',
      'IDH1 R132H negativo por imuno; abaixo de 55 anos, sequenciar IDH1 e IDH2 antes de concluir IDH-selvagem.',
      'ATRX retido na maioria (a perda favorece astrocitoma IDH-mutante).',
      'Necrose em pseudopaliçada e glomérulos vasculares são clássicos mas não obrigatórios.',
    ],
    markers: [
      { marker: 'gfap', pct: [85, 100], note: 'pode ser focal nos de células pequenas e epitelioides' },
      { marker: 'olig2', pct: [80, 95] },
      { marker: 'idh1', pct: [0, 5], note: 'o negativo é critério; abaixo de 55 anos sequencie antes de concluir' },
      { marker: 'atrx', pct: [5, 15], note: 'o positivo é a perda; retido na maioria' },
      { marker: 'p53', pct: [30, 50] },
      { marker: 's100', pct: [85, 100] },
      { marker: 'h3k27m', pct: 0, note: 'positivo define glioma difuso de linha média' },
      { marker: 'brafv600e', pct: [0, 10], note: 'positivo nos epitelioides, que têm terapia-alvo' },
      { marker: 'ae1ae3', pct: [5, 20], note: 'reatividade cruzada do clone AE1/AE3; não conclua carcinoma' },
      { marker: 'ema', pct: [0, 10] },
      { marker: 'sox10', pct: [70, 95], note: 'glial; não confunda com melanoma' },
      { marker: 'cd34', pct: [10, 30] },
      { marker: 'neun', pct: [0, 5], note: 'só neurônios aprisionados' },
      { marker: 'ki67', pct: [15, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Astrocitoma IDH-mutante grau 4: IDH1 R132H positivo, ATRX perdido, paciente mais jovem.',
      'Metástase carcinomatosa: bem delimitada, queratina e marcador de sítio positivos, GFAP negativo.',
      'Linfoma primário do SNC: angiocêntrico, CD20 positivo, GFAP negativo.',
      'Gliose reativa e desmielinização: macrófagos CD68 positivos, sem atipia, vasos normais.',
      'Xantoastrocitoma pleomórfico anaplásico: fibras de Rosenthal, corpos granulares eosinofílicos, BRAF V600E, CD34.',
    ],
    pitfalls: ['AE1/AE3 dá reatividade cruzada em gliomas; use CAM5.2 ou marcadores de sítio antes de chamar de metástase.'],
    molecular: 'TERT promotor, EGFR amplificado, +7/-10, CDKN2A/B deletado; metilação de MGMT é preditiva de resposta à temozolomida.',
    sources: [WHO, CIMPACT, PERRY],
  },
  {
    id: 'astrocitoma-idh',
    name: 'Astrocitoma, IDH-mutante',
    aka: ['astrocitoma difuso IDH-mutante', 'astrocitoma anaplásico', 'IDH-mutant astrocytoma'],
    behavior: 'maligno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'estreladas', 'epitelioide'],
    architecture: ['infiltrativo', 'lencois'],
    features: ['estroma-mixoide', 'mitoses-raras', 'mitoses-moderadas', 'necrose'],
    ages: ['jovem', 'adulto'],
    summary: 'Glioma difuso de adulto jovem, IDH-mutante e sem codeleção 1p/19q, com astrócitos fibrilares ou gemistocíticos infiltrando difusamente; o grau (2, 3 ou 4) sai de mitoses, proliferação microvascular, necrose e, hoje, da deleção homozigótica de CDKN2A/B, que sozinha faz grau 4.',
    criteria: [
      'Mutação de IDH1 ou IDH2 demonstrada (imuno R132H ou sequenciamento).',
      'Ausência de codeleção 1p/19q: é o que o separa do oligodendroglioma.',
      'Perda nuclear de ATRX e p53 aberrante apoiam fortemente e dispensam o teste de 1p/19q na prática.',
      'Grau 2: sem mitoses significativas. Grau 3: mitoses. Grau 4: necrose, proliferação microvascular ou CDKN2A/B deletado homozigoticamente.',
      'Em paciente jovem com glioma difuso, a mutação IDH deve sempre ser procurada.',
    ],
    markers: [
      { marker: 'idh1', pct: [85, 95], note: 'clone H09 detecta só R132H; um sequenciamento negativo é necessário em jovens' },
      { marker: 'atrx', pct: [80, 95], note: 'o positivo é a perda; retido no oligodendroglioma' },
      { marker: 'p53', pct: [70, 90], note: 'aberrante; o oligodendroglioma é selvagem' },
      { marker: 'gfap', pct: [90, 100] },
      { marker: 'olig2', pct: [85, 100] },
      { marker: 's100', pct: [90, 100] },
      { marker: 'sox10', pct: [80, 95] },
      { marker: 'h3k27m', pct: 0 },
      { marker: 'neun', pct: [0, 5] },
      { marker: 'ema', pct: [0, 10] },
      { marker: 'ki67', pct: [2, 20], note: 'sobe com o grau' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Oligodendroglioma: ATRX retido, p53 selvagem, codeleção 1p/19q, halos perinucleares e vasos em tela de galinheiro.',
      'Glioblastoma IDH-selvagem: IDH1 negativo, ATRX retido, em paciente mais velho.',
      'Gliose reativa: astrócitos regularmente espaçados, sem atipia, vasos normais.',
      'Glioma difuso de linha média: H3 K27M positivo, H3K27me3 perdido.',
    ],
    molecular: 'IDH1/IDH2, ATRX, TP53; CDKN2A/B homozigótico define grau 4.',
    sources: [WHO, CIMPACT, PERRY],
  },
  {
    id: 'oligodendroglioma',
    name: 'Oligodendroglioma, IDH-mutante e com codeleção 1p/19q',
    aka: ['oligodendroglioma', 'oligodendroglioma anaplásico'],
    behavior: 'maligno',
    sites: [{ site: 'encefalo', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'claras', 'estreladas'],
    architecture: ['infiltrativo', 'lencois', 'nodular'],
    features: ['calcificacao', 'estroma-mixoide', 'mitoses-raras', 'mitoses-moderadas'],
    ages: ['adulto'],
    summary: 'Glioma difuso de células redondas monótonas com halo perinuclear em ovo frito (artefato de fixação) e rede vascular ramificada fina em tela de galinheiro, com calcificações e satelitose perineuronal; IDH-mutante com codeleção 1p/19q, e é o glioma de melhor resposta à quimioterapia.',
    criteria: [
      'Mutação de IDH1 ou IDH2 obrigatória.',
      'Codeleção completa de 1p e 19q obrigatória para o diagnóstico (perdas parciais não contam).',
      'ATRX retido e p53 selvagem: o par imuno que substitui, na prática, a triagem inicial.',
      'Grau 2 ou 3 por mitoses, proliferação microvascular e necrose.',
      'Halos perinucleares e tela de galinheiro são sugestivos mas não bastam sem o molecular.',
    ],
    markers: [
      { marker: 'idh1', pct: [85, 95] },
      { marker: 'atrx', pct: [0, 10], note: 'retido; a perda favorece astrocitoma' },
      { marker: 'p53', pct: [0, 15], note: 'selvagem' },
      { marker: 'olig2', pct: [90, 100] },
      { marker: 'gfap', pct: [40, 80], note: 'em células gliofibrilares e em astrócitos aprisionados' },
      { marker: 's100', pct: [90, 100] },
      { marker: 'sox10', pct: [85, 100] },
      { marker: 'neun', pct: [0, 5], note: 'o negativo que separa de neurocitoma' },
      { marker: 'sinaptofisina', pct: [10, 30], note: 'no neurópilo de fundo; não conclua neuronal' },
      { marker: 'ema', pct: [0, 5] },
      { marker: 'ki67', pct: [2, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Astrocitoma IDH-mutante com células claras: ATRX perdido, p53 aberrante.',
      'Neurocitoma central: NeuN e sinaptofisina positivos, intraventricular, OLIG2 negativo.',
      'Tumor neuroepitelial disembrioplásico: elementos glioneuronais específicos, em criança com epilepsia.',
      'Ependimoma de células claras: EMA em dot, L1CAM, pseudorrosetas perivasculares.',
      'Metástase de carcinoma de células claras: queratina e PAX8.',
    ],
    molecular: 'IDH1/IDH2 com codeleção 1p/19q; TERT promotor, CIC e FUBP1.',
    sources: [WHO, CIMPACT, PERRY],
  },
  {
    id: 'glioma-linha-media',
    name: 'Glioma difuso de linha média, H3 K27-alterado',
    aka: ['DMG', 'glioma pontino intrínseco difuso', 'DIPG', 'diffuse midline glioma'],
    behavior: 'maligno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 2 },
    ],
    cells: ['fusocelular', 'estreladas', 'pequenas-redondas', 'pleomorfico'],
    architecture: ['infiltrativo', 'lencois'],
    features: ['mitoses-altas', 'necrose', 'vasos-espessos'],
    ages: ['crianca', 'jovem'],
    summary: 'Glioma difuso da ponte, tálamo, medula ou outra estrutura de linha média, com histologia que pode ser branda mas comportamento de grau 4; a marcação nuclear de H3 K27M com perda global de H3K27me3 define a entidade, e o prognóstico é uniformemente ruim.',
    criteria: [
      'Localização em linha média: ponte, tálamo, medula espinhal, cerebelo, terceiro ventrículo.',
      'Glioma difuso, astrocitário na maioria.',
      'Alteração de H3 K27: mutação K27M em H3F3A ou HIST1H3B/C, superexpressão de EZHIP, ou mutação de EGFR na variante bitalâmica.',
      'Perda global de H3K27me3 nas células tumorais, com controle interno (endotélio) retido.',
      'Grau 4 por definição, independentemente de necrose ou mitoses.',
    ],
    markers: [
      { marker: 'h3k27m', pct: [80, 95], note: 'nuclear difuso; critério definidor quando presente' },
      { marker: 'h3k27me3', pct: [90, 100], note: 'o positivo é a perda; mais sensível, pois cobre também EZHIP e EGFR' },
      { marker: 'gfap', pct: [80, 95] },
      { marker: 'olig2', pct: [70, 95], note: 'pode ser negativo nas variantes espinhais' },
      { marker: 'atrx', pct: [40, 60], note: 'o positivo é a perda; frequente' },
      { marker: 'p53', pct: [50, 80] },
      { marker: 'idh1', pct: 0, note: 'o negativo é esperado' },
      { marker: 's100', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [10, 30] },
      { marker: 'neun', pct: [0, 5] },
      { marker: 'ki67', pct: [10, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Astrocitoma pilocítico do tronco: bifásico, fibras de Rosenthal, KIAA1549::BRAF, bom prognóstico.',
      'Ependimoma: pseudorrosetas, EMA em dot.',
      'Astrocitoma IDH-mutante: IDH1 positivo, fora da linha média.',
      'Meduloblastoma com extensão: no cerebelo, pequenas células, sinaptofisina difusa.',
    ],
    pitfalls: ['H3K27me3 perdido também ocorre em MPNST e em outras neoplasias; interprete no contexto de glioma de linha média.'],
    molecular: 'H3F3A K27M, HIST1H3B/C K27M, superexpressão de EZHIP, EGFR mutado (bitalâmico).',
    sources: [WHO, CIMPACT],
  },
  {
    id: 'astrocitoma-pilocitico',
    name: 'Astrocitoma pilocítico',
    aka: ['pilocytic astrocytoma', 'glioma de vias ópticas'],
    behavior: 'benigno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 3 },
      { site: 'olho-orbita', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'estreladas'],
    architecture: ['infiltrativo', 'nodular'],
    features: ['estroma-mixoide', 'calcificacao', 'vasos-espessos', 'mitoses-raras'],
    ages: ['crianca', 'jovem'],
    summary: 'Glioma bem delimitado do cerebelo, vias ópticas ou hipotálamo em criança, bifásico: áreas compactas de células piloides com fibras de Rosenthal alternando com áreas frouxas microcísticas com corpos granulares eosinofílicos; grau 1, curável por ressecção, com fusão KIAA1549::BRAF.',
    criteria: [
      'Padrão bifásico com áreas compactas piloides e áreas frouxas microcísticas.',
      'Fibras de Rosenthal e corpos granulares eosinofílicos (nem sempre os dois).',
      'Delimitação relativa, ao contrário dos gliomas difusos.',
      'Proliferação vascular glomeruloide, hialinização e degeneração nuclear são comuns e não indicam malignidade.',
      'Fusão KIAA1549::BRAF ou, no contexto de neurofibromatose tipo 1, o diagnóstico clínico.',
    ],
    markers: [
      { marker: 'gfap', pct: [95, 100] },
      { marker: 'olig2', pct: [70, 95] },
      { marker: 's100', pct: [95, 100] },
      { marker: 'sox10', pct: [80, 95] },
      { marker: 'idh1', pct: 0, note: 'o negativo que separa de astrocitoma difuso em adolescente' },
      { marker: 'atrx', pct: [0, 5], note: 'retido' },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'brafv600e', pct: [5, 15], note: 'na minoria extracerebelar; a maioria tem fusão, não mutação' },
      { marker: 'h3k27m', pct: 0 },
      { marker: 'cd34', pct: [10, 30] },
      { marker: 'neun', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Astrocitoma difuso: infiltrativo, sem bifasicidade, IDH pode ser mutante.',
      'Glioma difuso de linha média: H3 K27M, prognóstico ruim.',
      'Ganglioglioma: neurônios displásicos, CD34 em rede.',
      'Hemangioblastoma: inibina e células estromais vacuoladas, em adulto com von Hippel-Lindau.',
      'Gliose piloide reativa ao redor de craniofaringioma e hemangioblastoma: sem massa própria.',
    ],
    molecular: 'Fusão KIAA1549::BRAF (duplicação em tandem de 7q34); via MAPK; NF1 germinativo na neurofibromatose.',
    sources: [WHO, PERRY],
  },
  {
    id: 'ependimoma',
    name: 'Ependimoma',
    aka: ['ependimoma ZFTA supratentorial', 'ependimoma PFA e PFB', 'ependymoma'],
    behavior: 'maligno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 2 },
    ],
    cells: ['epitelioide', 'fusocelular', 'claras'],
    architecture: ['pseudopapilar', 'rosetas', 'lencois', 'papilar'],
    features: ['calcificacao', 'necrose', 'mitoses-moderadas', 'vasos-espessos'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Tumor glial com pseudorrosetas perivasculares — coroas de processos fibrilares convergindo para o vaso — e, menos vezes, rosetas ependimárias verdadeiras; classificado hoje por sítio e molecular (ZFTA e YAP1 supratentoriais, PFA e PFB na fossa posterior, MYCN na medula).',
    criteria: [
      'Pseudorrosetas perivasculares: o achado obrigatório e mais constante.',
      'EMA em padrão de dot paranuclear ou em anel na luz microrrosetária.',
      'Classificação por sítio anatômico somada ao molecular: supratentorial ZFTA ou YAP1, fossa posterior A ou B, espinhal MYCN-amplificado.',
      'Perda de H3K27me3 define o grupo PFA da fossa posterior, de pior prognóstico.',
      'L1CAM e ciclina D1 positivos apoiam o grupo ZFTA (antigo RELA).',
    ],
    markers: [
      { marker: 'ema', pct: [70, 95], pattern: 'dot', note: 'dot paranuclear ou anel microrrosetário; é o achado imuno' },
      { marker: 'gfap', pct: [90, 100] },
      { marker: 's100', pct: [90, 100] },
      { marker: 'olig2', pct: [0, 15], note: 'o negativo que separa dos gliomas difusos' },
      { marker: 'l1cam', pct: [60, 90], note: 'no grupo ZFTA supratentorial' },
      { marker: 'ciclinad1', pct: [50, 85], note: 'idem' },
      { marker: 'h3k27me3', pct: [50, 70], note: 'o positivo é a perda; define o grupo PFA' },
      { marker: 'ae1ae3', pct: [10, 30] },
      { marker: 'neun', pct: [0, 5] },
      { marker: 'sinaptofisina', pct: [10, 30] },
      { marker: 'idh1', pct: 0 },
      { marker: 'ki67', pct: [2, 25] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Astrocitoma pilocítico: bifásico, fibras de Rosenthal, sem pseudorrosetas verdadeiras.',
      'Oligodendroglioma de células claras: OLIG2 positivo, IDH e 1p/19q.',
      'Meduloblastoma: pequenas células, sinaptofisina difusa, no vermis.',
      'Papiloma de plexo coroide: papilas com eixo verdadeiro, queratina e transtirretina.',
      'Subependimoma: nódulos de núcleos em grupos com matriz fibrilar, indolente.',
    ],
    molecular: 'Fusões ZFTA (RELA) e YAP1 nos supratentoriais; metilação e perda de H3K27me3 no PFA; MYCN no espinhal.',
    sources: [WHO, PERRY],
  },
  {
    id: 'meduloblastoma',
    name: 'Meduloblastoma',
    aka: ['medulloblastoma', 'meduloblastoma WNT, SHH, grupo 3 e 4'],
    behavior: 'maligno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'metastase', freq: 2 },
      { site: 'meninges', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'blastematoso'],
    architecture: ['lencois', 'rosetas', 'nodular'],
    features: ['mitoses-altas', 'necrose', 'corpos-apoptoticos'],
    ages: ['crianca', 'jovem'],
    summary: 'Tumor embrionário do cerebelo em criança, feito de células pequenas azuis com moldagem nuclear e rosetas de Homer Wright; classificado em quatro grupos moleculares (WNT, SHH, grupo 3 e grupo 4) que têm prognósticos muito diferentes e são parcialmente identificáveis por imuno.',
    criteria: [
      'Localização cerebelar ou no quarto ventrículo, em criança ou adulto jovem.',
      'Células embrionárias pequenas com relação núcleo-citoplasma alta, moldagem e alto índice mitótico e apoptótico.',
      'Subtipagem histológica: clássico, desmoplásico/nodular, com nodularidade extensa, e de grandes células/anaplásico.',
      'Grupo molecular: β-catenina nuclear e YAP1 no WNT; GAB1, YAP1 e filamina A no SHH; os grupos 3 e 4 são negativos para os dois.',
      'Amplificação de MYC e MYCN devem ser avaliadas: mudam o risco.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [85, 100] },
      { marker: 'insm1', pct: [80, 95] },
      { marker: 'neun', pct: [30, 70], note: 'nas áreas nodulares diferenciadas' },
      { marker: 'betacatenina', pct: [10, 15], pattern: 'N', note: 'nuclear define o grupo WNT, que tem excelente prognóstico' },
      { marker: 'gfap', pct: [10, 40], note: 'só em astrócitos aprisionados; difusa fala contra' },
      { marker: 'olig2', pct: [10, 40] },
      { marker: 'p53', pct: [20, 40], note: 'aberrante no SHH é de alto risco' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define tumor teratoide rabdoide atípico' },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 'cd99', pct: [10, 30], note: 'não conclua Ewing' },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'crx', pct: [10, 30], note: 'positivo levanta pineoblastoma' },
      { marker: 'ki67', pct: [40, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor teratoide rabdoide atípico: INI1 perdido, em lactente, células rabdoides.',
      'Ependimoma anaplásico: pseudorrosetas, EMA em dot, OLIG2 negativo.',
      'Pineoblastoma: na região pineal, CRX positivo.',
      'Linfoma e sarcoma de Ewing intracraniano: CD45 ou CD99 difuso com fusão EWSR1.',
      'Glioblastoma de células pequenas: GFAP e OLIG2 difusos, em adulto.',
    ],
    molecular: 'CTNNB1 (WNT), PTCH1/SUFU/SMO (SHH), amplificação de MYC (grupo 3) e MYCN; TP53 germinativo em Li-Fraumeni.',
    sources: [WHO, PERRY],
  },
  {
    id: 'meningioma',
    name: 'Meningioma',
    aka: ['meningioma meningotelial', 'meningioma atípico', 'meningioma anaplásico'],
    behavior: 'intermediario',
    sites: [
      { site: 'meninges', role: 'primario', freq: 3 },
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 2 },
      { site: 'olho-orbita', role: 'primario', freq: 1 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
    ],
    cells: ['sincicial', 'epitelioide', 'fusocelular', 'claras'],
    architecture: ['lobular', 'fasciculos', 'storiforme'],
    features: ['psamomas', 'sulcos-inclusoes', 'calcificacao', 'hialinizacao', 'mitoses-raras', 'necrose'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Tumor das células aracnoides, em lóbulos e redemoinhos de células sinciciais com pseudoinclusões nucleares e corpos psamomatosos; EMA e SSTR2A positivos, e o grau depende de mitoses, invasão cerebral e critérios de atipia, com CDKN2A deletado e TERT mutado fazendo grau 3 por si sós.',
    criteria: [
      'Redemoinhos e lóbulos de células sinciciais de limites indistintos, com pseudoinclusões nucleares e psamomas.',
      'EMA e SSTR2A positivos; SSTR2A é o mais sensível, sobretudo nos de alto grau.',
      'Grau 2: 4 a 19 mitoses por 10 campos, invasão cerebral, ou três dos cinco critérios de atipia; subtipos cordoide e de células claras.',
      'Grau 3: 20 ou mais mitoses, anaplasia franca, subtipos papilar e rabdoide, ou CDKN2A/B deletado ou TERT promotor mutado.',
      'Invasão do osso não conta como invasão cerebral e não sobe o grau.',
    ],
    markers: [
      { marker: 'sstr2', pct: [90, 100], note: 'o mais sensível; útil quando o EMA falha no alto grau' },
      { marker: 'ema', pct: [70, 95], note: 'cai nos graus 2 e 3' },
      { marker: 'pr', pct: [60, 90], note: 'cai com o grau' },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 's100', pct: [20, 50], note: 'fraca; difusa forte favorece schwannoma' },
      { marker: 'sox10', pct: [0, 10], note: 'o negativo que separa de schwannoma' },
      { marker: 'gfap', pct: [0, 5] },
      { marker: 'stat6', pct: [0, 5], note: 'o negativo que separa de tumor fibroso solitário' },
      { marker: 'cd34', pct: [0, 15] },
      { marker: 'ae1ae3', pct: [10, 30], note: 'nos secretores e sinciciais' },
      { marker: 'cd99', pct: [50, 80] },
      { marker: 'braquiuria', pct: [0, 5], note: 'o negativo contra cordoma no subtipo cordoide' },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 'ki67', pct: [1, 20], note: 'acompanha o grau, mas não é critério formal' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor fibroso solitário: STAT6 nuclear, CD34, vasos em galhada.',
      'Schwannoma: SOX10 e S100 difusos, Antoni A e B, EMA negativo.',
      'Hemangiopericitoma (hoje tumor fibroso solitário): idem.',
      'Metástase carcinomatosa dural: queratina forte, marcador de sítio.',
      'Cordoma no clivo contra meningioma cordoide: braquiúria positiva no cordoma.',
    ],
    molecular: 'NF2 na maioria; TRAF7, KLF4, AKT1, SMO nos da base; CDKN2A/B e TERT nos de grau 3.',
    sources: [WHO, PERRY],
  },
  {
    id: 'neurocitoma-central',
    name: 'Neurocitoma central',
    aka: ['central neurocytoma', 'neurocitoma extraventricular'],
    behavior: 'benigno',
    sites: [{ site: 'encefalo', role: 'primario', freq: 1 }],
    cells: ['pequenas-redondas', 'epitelioide', 'claras'],
    architecture: ['lencois', 'rosetas'],
    features: ['calcificacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Tumor intraventricular de adulto jovem, aderido ao septo pelúcido, feito de células redondas uniformes com halo perinuclear, separadas por ilhas de neurópilo fibrilar anucleado; NeuN e sinaptofisina positivos com OLIG2 negativo, o que o separa do oligodendroglioma que ele copia.',
    criteria: [
      'Localização intraventricular (ventrículos laterais, próximo ao forame de Monro e ao septo pelúcido).',
      'Células redondas monótonas com halo perinuclear, em lençóis com ilhas de neurópilo fibrilar.',
      'Sinaptofisina forte no neurópilo e NeuN nuclear nas células tumorais.',
      'OLIG2 negativo: é o marcador que decide contra oligodendroglioma.',
      'Índice proliferativo acima de 2 a 3% define a variante atípica, de maior recidiva.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [95, 100], note: 'forte nas ilhas de neurópilo' },
      { marker: 'neun', pct: [80, 95] },
      { marker: 'olig2', pct: [0, 10], note: 'o negativo que separa de oligodendroglioma' },
      { marker: 'nse', pct: [80, 95] },
      { marker: 'gfap', pct: [10, 40], note: 'só astrócitos aprisionados' },
      { marker: 'idh1', pct: 0 },
      { marker: 'atrx', pct: [0, 5] },
      { marker: 'ema', pct: [0, 10], note: 'o negativo que separa de ependimoma' },
      { marker: 'cromogranina', pct: [0, 15] },
      { marker: 's100', pct: [20, 50] },
      { marker: 'ki67', pct: [1, 5], note: 'acima de 2 a 3% define a variante atípica' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Oligodendroglioma: OLIG2 positivo, IDH-mutante, codeleção 1p/19q, no parênquima.',
      'Ependimoma de células claras: EMA em dot, pseudorrosetas.',
      'Papiloma de plexo coroide: papilas, queratina, transtirretina.',
      'Subependimoma: nódulos de núcleos agrupados, mais velho.',
      'Meduloblastoma: em criança, no cerebelo, Ki-67 muito alto.',
    ],
    sources: [WHO, PERRY],
  },
  {
    id: 'ganglioglioma',
    name: 'Ganglioglioma',
    aka: ['ganglioglioma', 'gangliocitoma'],
    behavior: 'benigno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'gigantes', 'estreladas'],
    architecture: ['nodular', 'infiltrativo', 'cistico'],
    features: ['calcificacao', 'linfoide', 'mitoses-raras'],
    ages: ['crianca', 'jovem'],
    summary: 'Tumor glioneuronal do lobo temporal em criança ou jovem com epilepsia refratária, misturando neurônios displásicos binucleados a um componente glial neoplásico, com rede de CD34, agregados linfoides perivasculares e calcificações; grau 1, com BRAF V600E em cerca de metade.',
    criteria: [
      'Componente neuronal displásico: neurônios grandes, binucleados, mal orientados, com corpos de Nissl.',
      'Componente glial neoplásico (astrocitário ou piloide) verdadeiro, não apenas reativo.',
      'CD34 em rede ramificada ao redor das células, muito característico e ausente no córtex normal.',
      'Agregados linfoides perivasculares, calcificações e corpos granulares eosinofílicos apoiam.',
      'BRAF V600E apoia e abre terapia-alvo nos casos irressecáveis.',
    ],
    markers: [
      { marker: 'cd34', pct: [70, 90], note: 'rede ramificada; o achado mais útil' },
      { marker: 'brafv600e', pct: [40, 60] },
      { marker: 'neun', pct: [80, 95], note: 'neurônios displásicos' },
      { marker: 'sinaptofisina', pct: [90, 100] },
      { marker: 'nf', pct: [70, 95], note: 'aglomerados anômalos nos neurônios displásicos' },
      { marker: 'gfap', pct: [85, 100], note: 'componente glial' },
      { marker: 'olig2', pct: [20, 50] },
      { marker: 'idh1', pct: 0, note: 'o negativo que separa de glioma difuso' },
      { marker: 'atrx', pct: [0, 5] },
      { marker: 'h3k27m', pct: 0 },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor neuroepitelial disembrioplásico: elemento glioneuronal específico com neurônios flutuantes, sem neurônios displásicos.',
      'Glioma difuso com neurônios aprisionados: sem CD34 em rede, neurônios normais, IDH pode ser mutante.',
      'Xantoastrocitoma pleomórfico: células xantomatosas, fibras de reticulina pericelular, também CD34 e BRAF.',
      'Displasia cortical focal tipo IIb: sem componente glial neoplásico, balloon cells.',
    ],
    molecular: 'BRAF V600E; outras alterações da via MAPK.',
    sources: [WHO, PERRY],
  },
  {
    id: 'xantoastrocitoma-pleomorfico',
    name: 'Xantoastrocitoma pleomórfico',
    aka: ['PXA', 'pleomorphic xanthoastrocytoma'],
    behavior: 'intermediario',
    sites: [{ site: 'encefalo', role: 'primario', freq: 1 }],
    cells: ['pleomorfico', 'gigantes', 'fusocelular', 'histiocitoide'],
    architecture: ['lencois', 'fasciculos', 'nodular'],
    features: ['linfoide', 'vacuolos-lipidicos', 'calcificacao', 'mitoses-raras', 'necrose'],
    ages: ['crianca', 'jovem'],
    summary: 'Tumor superficial do lobo temporal com envolvimento das leptomeninges, em jovem com epilepsia, feito de células muito pleomórficas e xantomatosas com corpos granulares eosinofílicos, rede de reticulina pericelular e infiltrado linfoide; o pleomorfismo assusta mas o grau é 2, salvo se houver 5 ou mais mitoses.',
    criteria: [
      'Localização superficial com envolvimento leptomeníngeo, em jovem.',
      'Pleomorfismo acentuado com células gigantes multinucleadas e células xantomatosas vacuoladas.',
      'Corpos granulares eosinofílicos e rede de reticulina pericelular.',
      'Grau 3 quando há 5 ou mais mitoses por 10 campos de grande aumento; a necrose isolada não basta.',
      'BRAF V600E com deleção homozigótica de CDKN2A/B é o perfil molecular típico.',
    ],
    markers: [
      { marker: 'brafv600e', pct: [60, 80] },
      { marker: 'cd34', pct: [70, 90] },
      { marker: 'gfap', pct: [85, 100] },
      { marker: 'olig2', pct: [40, 80] },
      { marker: 's100', pct: [90, 100] },
      { marker: 'idh1', pct: 0, note: 'o negativo que separa de astrocitoma IDH-mutante' },
      { marker: 'atrx', pct: [0, 10], note: 'retido' },
      { marker: 'p53', pct: [10, 30] },
      { marker: 'neun', pct: [0, 10] },
      { marker: 'sinaptofisina', pct: [10, 40] },
      { marker: 'ki67', pct: [1, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Glioblastoma de células gigantes: em adulto, IDH-selvagem, sem reticulina pericelular nem CD34.',
      'Ganglioglioma: neurônios displásicos presentes.',
      'Astrocitoma pilocítico: bifásico, fibras de Rosenthal, KIAA1549::BRAF.',
      'Meningioma anaplásico: EMA e SSTR2A positivos, GFAP negativo.',
      'Melanoma metastático: SOX10 e HMB-45.',
    ],
    molecular: 'BRAF V600E com CDKN2A/B deletado homozigoticamente.',
    sources: [WHO, PERRY],
  },
  {
    id: 'craniofaringioma',
    name: 'Craniofaringioma',
    aka: ['craniofaringioma adamantinomatoso', 'craniofaringioma papilar'],
    behavior: 'benigno',
    sites: [
      { site: 'sela', role: 'primario', freq: 3 },
      { site: 'encefalo', role: 'primario', freq: 1 },
    ],
    cells: ['escamoso', 'epitelioide', 'basaloide'],
    architecture: ['ninhos', 'cistico', 'papilar', 'palicada'],
    features: ['queratinizacao', 'calcificacao', 'hialinizacao'],
    ages: ['crianca', 'adulto', 'idoso'],
    summary: 'Tumor selar e supraselar epitelial, em dois tipos que hoje são entidades separadas: o adamantinomatoso, de criança, com paliçada periférica, retículo estrelado, queratina úmida e calcificação, com β-catenina nuclear; e o papilar, de adulto, com papilas escamosas maduras e BRAF V600E.',
    criteria: [
      'Adamantinomatoso: cordões epiteliais com paliçada basal, retículo estrelado central, nódulos de queratina úmida e calcificação; cisto de óleo de motor.',
      'Papilar: epitélio escamoso maduro sem paliçada, sem queratina úmida e sem calcificação, revestindo eixos fibrovasculares.',
      'β-catenina nuclear e citoplasmática em ninhos (whorls) confirma o adamantinomatoso.',
      'BRAF V600E confirma o papilar e abre terapia-alvo.',
      'Gliose piloide intensa com fibras de Rosenthal na borda não deve ser lida como astrocitoma pilocítico.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [70, 95], pattern: 'N', note: 'em ninhos; define o adamantinomatoso' },
      { marker: 'brafv600e', pct: [20, 40], note: 'define o papilar; nos adamantinomatosos é negativo' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p63', pct: [85, 100] },
      { marker: 'p40', pct: [80, 95] },
      { marker: 'ck56', pct: [85, 100] },
      { marker: 'ck7', pct: [20, 50] },
      { marker: 'gfap', pct: [0, 10], note: 'só a gliose piloide de borda' },
      { marker: 'sinaptofisina', pct: [0, 5], note: 'o negativo que separa de adenoma hipofisário' },
      { marker: 'pit1', pct: 0 },
      { marker: 'tpit', pct: 0 },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Cisto da bolsa de Rathke: revestimento cuboide ciliado com células caliciformes, sem paliçada.',
      'Adenoma hipofisário: sinaptofisina e hormônios, sem epitélio escamoso.',
      'Cisto epidermoide: escamoso queratinizado laminado, sem paliçada nem calcificação.',
      'Carcinoma escamoso metastático: atipia, mitoses, invasão.',
      'Astrocitoma pilocítico: a gliose de borda do craniofaringioma engana em biópsia pequena.',
    ],
    molecular: 'CTNNB1 no adamantinomatoso; BRAF V600E no papilar.',
    sources: [WHO, PERRY],
  },
  {
    id: 'pitnet',
    name: 'Tumor neuroendócrino hipofisário (adenoma hipofisário)',
    aka: ['PitNET', 'adenoma hipofisário', 'pituitary adenoma'],
    behavior: 'benigno',
    sites: [{ site: 'sela', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'neuroendocrino', 'oncocitico', 'claras'],
    architecture: ['lencois', 'trabecular', 'ninhos', 'papilar'],
    features: ['hemorragia', 'amiloide', 'calcificacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Proliferação monomórfica de células adeno-hipofisárias que apaga a arquitetura acinar normal, o que se demonstra pela perda da trama de reticulina; a classificação atual é por linhagem, com os fatores de transcrição PIT1, TPIT e SF-1 acima dos hormônios.',
    criteria: [
      'Monomorfismo celular com perda do padrão acinar da hipófise normal, demonstrada pela reticulina.',
      'Classificação por fator de transcrição: PIT1 (somatotrófico, lactotrófico, tireotrófico), TPIT (corticotrófico), SF-1 (gonadotrófico).',
      'Hormônios (GH, prolactina, ACTH, FSH/LH, TSH) complementam, mas não substituem os fatores de transcrição.',
      'Invasão do seio cavernoso e subtipos de alto risco (Crooke, lactotrófico masculino, silencioso corticotrófico, PIT1 plurihormonal) devem ser relatados.',
      'Carcinoma hipofisário exige metástase, não basta invasão.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [95, 100] },
      { marker: 'cam52', pct: [80, 95], note: 'padrão fibroso em corpo perinuclear no lactotrófico esparsamente granulado' },
      { marker: 'pit1', pct: [40, 60], note: 'linhagem somatotrófica, lactotrófica e tireotrófica' },
      { marker: 'sf1', pct: [30, 50], note: 'linhagem gonadotrófica' },
      { marker: 'tpit', pct: [15, 25], note: 'linhagem corticotrófica' },
      { marker: 'gh', pct: [15, 30] },
      { marker: 'prl', pct: [25, 40] },
      { marker: 'acth', pct: [15, 25] },
      { marker: 'reticulina', pct: [90, 100], note: 'o positivo é a perda da trama acinar; critério estrutural' },
      { marker: 'cromogranina', pct: [50, 85] },
      { marker: 'ae1ae3', pct: [70, 95] },
      { marker: 'gata3', pct: [20, 50], note: 'nos tireotróficos e gonadotróficos' },
      { marker: 'ttf1', pct: [0, 10], note: 'positivo no tumor de células fusiformes da hipófise posterior' },
      { marker: 'ki67', pct: [1, 10], note: 'acima de 3% em tumor invasivo aponta comportamento agressivo' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Hiperplasia hipofisária: reticulina expandida mas preservada.',
      'Craniofaringioma: epitélio escamoso, sinaptofisina negativa.',
      'Metástase de carcinoma neuroendócrino: TTF-1 ou CDX2, sem fator de transcrição hipofisário.',
      'Tumor de células granulares, pituicitoma e oncocitoma selar: TTF-1 positivos, hormônios negativos.',
      'Hipofisite: infiltrado linfoplasmocitário, IgG4.',
    ],
    molecular: 'GNAS nos somatotróficos; USP8 nos corticotróficos; MEN1, AIP e SDH em formas familiares.',
    sources: [WHO, 'WHO Classification of Tumours, 5ª ed.: Endocrine and Neuroendocrine Tumours (2022)', PERRY],
  },
  {
    id: 'hemangioblastoma',
    name: 'Hemangioblastoma',
    aka: ['haemangioblastoma', 'hemangioblastoma cerebelar'],
    behavior: 'benigno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 2 },
      { site: 'olho-orbita', role: 'primario', freq: 1 },
    ],
    cells: ['claras', 'estreladas', 'vasoformativo'],
    architecture: ['lencois', 'nodular'],
    features: ['vacuolos-lipidicos', 'hemorragia', 'mitoses-raras'],
    ages: ['adulto'],
    summary: 'Nódulo mural muito vascularizado na parede de um cisto cerebelar, feito de células estromais grandes e vacuoladas pelo lipídio dentro de uma rede capilar densa; inibina e brachyury ajudam pouco, e o marcador prático é a inibina com PAX8 e CA-IX negativos, contra a metástase de carcinoma renal na von Hippel-Lindau.',
    criteria: [
      'Células estromais poligonais de citoplasma vacuolado e clarificado, entre capilares de paredes finas.',
      'Rede capilar densa demonstrável por CD31 e reticulina.',
      'Inibina α positiva nas células estromais.',
      'PAX8 e CA-IX difuso negativos: é o par que exclui metástase de carcinoma renal de células claras, que é o problema real na doença de von Hippel-Lindau.',
      'Associação com von Hippel-Lindau em cerca de um quarto: obriga rastreio.',
    ],
    markers: [
      { marker: 'inibina', pct: [80, 95], note: 'nas células estromais; o marcador prático' },
      { marker: 's100', pct: [70, 95] },
      { marker: 'd240', pct: [50, 80] },
      { marker: 'cd31', pct: [95, 100], note: 'só a rede capilar' },
      { marker: 'nse', pct: [70, 90] },
      { marker: 'pax8', pct: [0, 10], note: 'o negativo que exclui metástase de carcinoma renal' },
      { marker: 'ae1ae3', pct: [0, 10], note: 'idem' },
      { marker: 'ema', pct: [0, 10] },
      { marker: 'caix', pct: [10, 30], note: 'pode ser positiva; não use isolada' },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'gfap', pct: [10, 40], note: 'só astrócitos aprisionados na borda' },
      { marker: 'braquiuria', pct: [10, 30] },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de carcinoma renal de células claras: PAX8, queratina e EMA positivos, inibina negativa.',
      'Astrocitoma pilocítico: bifásico, fibras de Rosenthal, GFAP difuso.',
      'Meningioma angiomatoso: EMA e SSTR2A positivos.',
      'Angiolipoma e malformação vascular: sem células estromais.',
    ],
    molecular: 'VHL germinativo em cerca de 25%; VHL somático nos esporádicos.',
    sources: [WHO, PERRY],
  },
  {
    id: 'papiloma-plexo-coroide',
    name: 'Papiloma e carcinoma de plexo coroide',
    aka: ['choroid plexus papilloma', 'carcinoma de plexo coroide'],
    behavior: 'intermediario',
    sites: [{ site: 'encefalo', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'glandular', 'pleomorfico'],
    architecture: ['papilar', 'lencois'],
    features: ['calcificacao', 'psamomas', 'mitoses-raras', 'necrose'],
    ages: ['crianca', 'adulto'],
    summary: 'Tumor intraventricular com papilas de eixo fibrovascular revestidas por uma camada única de epitélio cuboide a colunar, muito parecido com plexo coroide normal; o carcinoma tem lençóis sólidos, atipia, necrose e mitoses, e em criança pequena obriga a pesquisar TP53 germinativo.',
    criteria: [
      'Papilas com eixo fibrovascular revestidas por camada única de células, sem estratificação no papiloma.',
      'Papiloma atípico: 2 ou mais mitoses por 10 campos, sem os outros critérios de carcinoma.',
      'Carcinoma: quatro ou mais de cinco critérios (mitoses altas, densidade celular, pleomorfismo, borramento da arquitetura papilar, necrose).',
      'Transtirretina e Kir7.1 apoiam a origem no plexo coroide.',
      'No carcinoma em criança: pesquisa de TP53 germinativo (Li-Fraumeni).',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'ck7', pct: [60, 90] },
      { marker: 's100', pct: [70, 95], note: 'cai no carcinoma' },
      { marker: 'gfap', pct: [20, 50], note: 'focal; cai no carcinoma' },
      { marker: 'ema', pct: [0, 15], note: 'o negativo que ajuda contra carcinoma metastático e ependimoma' },
      { marker: 'ck20', pct: [0, 15] },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define tumor teratoide rabdoide atípico' },
      { marker: 'p53', pct: [10, 50], note: 'aberrante no carcinoma, sobretudo em Li-Fraumeni' },
      { marker: 'sinaptofisina', pct: [0, 15] },
      { marker: 'ki67', pct: [1, 30], note: 'baixo no papiloma, alto no carcinoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Plexo coroide normal e hiperplasia: arquitetura em paralelepípedo regular, sem massa.',
      'Ependimoma papilar: EMA em dot, GFAP difuso.',
      'Tumor teratoide rabdoide atípico: INI1 perdido, células rabdoides.',
      'Carcinoma metastático papilar: EMA positivo, marcador de sítio, em adulto.',
      'Meningioma papilar: EMA e SSTR2A.',
    ],
    sources: [WHO, PERRY],
  },
  {
    id: 'retinoblastoma',
    name: 'Retinoblastoma',
    aka: ['retinoblastoma'],
    behavior: 'maligno',
    sites: [
      { site: 'olho-orbita', role: 'primario', freq: 3 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
      { site: 'medula-ossea', role: 'metastase', freq: 1 },
    ],
    cells: ['pequenas-redondas', 'blastematoso'],
    architecture: ['lencois', 'rosetas'],
    features: ['necrose', 'mitoses-altas', 'calcificacao', 'corpos-apoptoticos'],
    ages: ['crianca'],
    summary: 'Tumor retiniano do lactente e do pré-escolar, com leucocoria, feito de células pequenas azuis com rosetas de Flexner-Wintersteiner de luz verdadeira e fleurettes nos mais diferenciados, com calcificação em meio à necrose; a perda de RB1 é o evento definidor e obriga aconselhamento genético.',
    criteria: [
      'Idade pediátrica com massa retiniana e leucocoria ou estrabismo.',
      'Rosetas de Flexner-Wintersteiner (luz verdadeira com membrana limitante) e fleurettes.',
      'Calcificação distrófica em zonas de necrose, com basofilia vascular.',
      'Fatores de risco a relatar: invasão do nervo óptico além da lâmina crivosa, invasão coroidal maciça, invasão escleral e do segmento anterior.',
      'Perda de RB1 por imuno com controle interno retido; teste germinativo em todos os casos.',
    ],
    markers: [
      { marker: 'crx', pct: [90, 100], note: 'fotorreceptor; o marcador mais específico' },
      { marker: 'rb1', pct: [90, 100], note: 'o positivo é a perda; critério molecular' },
      { marker: 'sinaptofisina', pct: [80, 95] },
      { marker: 'nse', pct: [80, 95] },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'nf', pct: [40, 70] },
      { marker: 'gfap', pct: [0, 15], note: 'só glia retiniana reativa' },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 'cd99', pct: [0, 20] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [70, 100] },
      { marker: 'sox10', pct: [0, 5], note: 'o negativo que separa de melanoma uveal, o outro tumor intraocular' },
      { marker: 's100', pct: [0, 10] },
    ],
    mimics: [
      'Doença de Coats e retinopatia da prematuridade: sem massa celular, exsudato.',
      'Meduloepitelioma do corpo ciliar: túbulos e cordões de neuroepitélio primitivo, DICER1.',
      'Linfoma e leucemia com envolvimento ocular: CD45 positivo.',
      'Rabdomiossarcoma orbitário: desmina e miogenina.',
      'Neuroblastoma metastático: PHOX2B positivo, CRX pode ser positivo (cuidado).',
    ],
    molecular: 'Inativação bialélica de RB1; germinativa em cerca de 40%, com risco de segundo tumor e de pineoblastoma.',
    sources: [WHO, PERRY],
  },
  {
    id: 'melanoma-uveal',
    name: 'Melanoma uveal',
    aka: ['melanoma de coroide', 'uveal melanoma', 'melanoma de íris e corpo ciliar'],
    behavior: 'maligno',
    sites: [
      { site: 'olho-orbita', role: 'primario', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'pleomorfico'],
    architecture: ['lencois', 'fasciculos', 'nodular'],
    features: ['melanina', 'necrose', 'mitoses-moderadas', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    summary: 'O tumor intraocular maligno mais comum do adulto: massa em cogumelo da coroide, de células fusiformes ou epitelioides com pigmento variável; metastatiza quase só para o fígado, às vezes décadas depois, e a monossomia do 3 com perda de BAP1 define o grupo de alto risco.',
    criteria: [
      'Massa pigmentada ou amelanótica da úvea, com ruptura da membrana de Bruch dando a forma de cogumelo.',
      'Classificação celular de Callender: fusiforme, epitelioide ou misto, com o epitelioide sendo o pior.',
      'SOX10 e Melan-A positivos; HMB-45 e tirosinase completam.',
      'Perda nuclear de BAP1 e monossomia do 3 definem alto risco de metástase hepática.',
      'Ao contrário do cutâneo, BRAF é raro e GNAQ/GNA11 é a regra.',
    ],
    markers: [
      { marker: 'sox10', pct: [95, 100] },
      { marker: 'melana', pct: [85, 100] },
      { marker: 's100', pct: [90, 100] },
      { marker: 'hmb45', pct: [80, 95] },
      { marker: 'mitf', pct: [80, 95] },
      { marker: 'tirosinase', pct: [70, 90] },
      { marker: 'prame', pct: [30, 60], note: 'associada a pior prognóstico aqui' },
      { marker: 'bap1', pct: [40, 50], note: 'o positivo é a perda; marca o grupo de alto risco metastático' },
      { marker: 'brafv600e', pct: [0, 5], note: 'ao contrário do cutâneo' },
      { marker: 'ae1ae3', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [5, 30] },
    ],
    mimics: [
      'Nevo de coroide: pequeno, sem crescimento, sem líquido sub-retiniano, BAP1 retido.',
      'Metástase de carcinoma para a coroide: queratina e marcador de sítio positivos.',
      'Hiperplasia do epitélio pigmentar da retina: pigmento em células cuboides regulares.',
      'Hemangioma de coroide: CD31 e ERG.',
      'Linfoma intraocular: CD45 e CD20.',
    ],
    molecular: 'GNAQ ou GNA11 em quase todos; BAP1 (alto risco), SF3B1 e EIF1AX (risco intermediário e baixo).',
    sources: [WHO, PERRY],
  },
  {
    id: 'atrt',
    name: 'Tumor teratoide rabdoide atípico (ATRT)',
    aka: ['ATRT', 'atypical teratoid/rhabdoid tumour'],
    behavior: 'maligno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
      { site: 'meninges', role: 'metastase', freq: 2 },
    ],
    cells: ['rabdoide', 'pequenas-redondas', 'epitelioide', 'pleomorfico'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'nucleolo', 'hemorragia'],
    ages: ['crianca'],
    summary: 'Tumor embrionário do lactente, quase sempre abaixo de três anos, com células rabdoides de núcleo excêntrico e inclusão citoplasmática eosinofílica misturadas a um componente de células pequenas azuis; a perda de INI1 define, e é o diferencial obrigatório do meduloblastoma na fossa posterior.',
    criteria: [
      'Perda completa da expressão nuclear de INI1 (SMARCB1) nas células tumorais, com endotélio e linfócitos retidos como controle interno.',
      'Células rabdoides presentes, ainda que focais: em parte dos casos dominam as células embrionárias pequenas.',
      'Fenótipo polifenotípico: coexpressão de EMA, queratina, GFAP, sinaptofisina e músculo liso na mesma lesão.',
      'Uma minoria mantém INI1 e perde BRG1 (SMARCA4): avalie os dois quando a morfologia é sugestiva.',
      'Investigação germinativa obrigatória, pela síndrome de predisposição a tumor rabdoide, com risco de tumor rabdoide renal sincrônico.',
    ],
    markers: [
      { marker: 'ini1', pct: [95, 100], note: 'o positivo é a perda; critério definidor' },
      { marker: 'brg1', pct: [5, 15], note: 'o positivo é a perda; ocorre na minoria que mantém INI1' },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [50, 85], note: 'focal, no componente rabdoide' },
      { marker: 'gfap', pct: [40, 80], note: 'focal; a positividade difusa favorece glioma' },
      { marker: 'sinaptofisina', pct: [40, 75] },
      { marker: 'sma', pct: [30, 70], note: 'a coexpressão de queratina, GFAP e músculo liso é o padrão polifenotípico clássico' },
      { marker: 'desmina', pct: [10, 40] },
      { marker: 'miogenina', pct: [0, 10], note: 'o negativo que exclui rabdomiossarcoma' },
      { marker: 'betacatenina', pct: [0, 10], pattern: 'N', note: 'o negativo que ajuda contra meduloblastoma WNT' },
      { marker: 'olig2', pct: [0, 15] },
      { marker: 'crx', pct: [0, 10], note: 'o negativo que afasta pineoblastoma' },
      { marker: 'ki67', pct: [50, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Meduloblastoma: INI1 retido, β-catenina ou GAB1 conforme o grupo molecular.',
      'Tumor rabdoide do rim com metástase encefálica: mesma perda de INI1; a topografia e a imagem decidem.',
      'Carcinoma de plexo coroide: INI1 retido, queratina forte e difusa.',
      'Glioblastoma com células rabdoides: GFAP difuso, INI1 retido, em adulto.',
      'Tumor embrionário com rosetas multicamadas (ETMR): LIN28A positivo, INI1 retido.',
    ],
    molecular: 'Inativação bialélica de SMARCB1 (raramente SMARCA4); três grupos de metilação (TYR, SHH, MYC) com prognósticos distintos.',
    sources: [WHO, PERRY],
  },
  {
    id: 'subependimoma',
    name: 'Subependimoma',
    aka: ['subependymoma'],
    behavior: 'benigno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
    ],
    cells: ['estreladas', 'epitelioide'],
    architecture: ['nodular', 'lencois'],
    features: ['calcificacao', 'hemorragia', 'mitoses-raras', 'vasos-espessos'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Nódulo intraventricular de crescimento lento, quase sempre no quarto ventrículo ou nos laterais, com núcleos agrupados em ninhos dentro de uma matriz fibrilar densa e microcistos entre eles; grau 1, muitas vezes achado de autópsia, e a armadilha é ler o agrupamento nuclear como hipercelularidade.',
    criteria: [
      'Agrupamentos de núcleos uniformes separados por matriz fibrilar gliótica abundante, com microcistos.',
      'Localização intraventricular, bem delimitada, sem infiltração do parênquima.',
      'Mitoses ausentes ou raríssimas, sem necrose e sem proliferação microvascular.',
      'GFAP difuso; o EMA em dot pode aparecer nas formas mistas com ependimoma e não exclui o diagnóstico.',
      'Tumor misto subependimoma-ependimoma existe e deve ser relatado, porque o componente ependimário governa a conduta.',
    ],
    markers: [
      { marker: 'gfap', pct: [95, 100] },
      { marker: 's100', pct: [90, 100] },
      { marker: 'olig2', pct: [10, 40], note: 'focal; difuso favorece glioma difuso' },
      { marker: 'ema', pct: [10, 30], note: 'em dot nas áreas de diferenciação ependimária' },
      { marker: 'idh1', pct: 0 },
      { marker: 'atrx', pct: [0, 5], note: 'retido' },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'neun', pct: [0, 5] },
      { marker: 'sinaptofisina', pct: [10, 30], note: 'no neurópilo de fundo aprisionado' },
      { marker: 'l1cam', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 3], note: 'muito baixo; acima de 5% reveja o diagnóstico' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Ependimoma: pseudorrosetas perivasculares, EMA em dot difuso, Ki-67 maior.',
      'Astrocitoma pilocítico: bifásico com fibras de Rosenthal, em criança.',
      'Gliose reativa periventricular: sem nódulo, astrócitos regularmente espaçados.',
      'Neurocitoma central: NeuN e sinaptofisina positivos, OLIG2 negativo.',
      'Astrocitoma subependimário de células gigantes: células grandes ganglionares, TTF-1 positivo, em esclerose tuberosa.',
    ],
    sources: [WHO, PERRY],
  },
  {
    id: 'sega',
    name: 'Astrocitoma subependimário de células gigantes (SEGA)',
    aka: ['SEGA', 'subependymal giant cell astrocytoma'],
    behavior: 'benigno',
    sites: [{ site: 'encefalo', role: 'primario', freq: 2 }],
    cells: ['gigantes', 'epitelioide', 'fusocelular'],
    architecture: ['ninhos', 'lencois', 'pseudopapilar'],
    features: ['calcificacao', 'linfoide', 'mitoses-raras'],
    ages: ['crianca', 'jovem'],
    summary: 'Nódulo junto ao forame de Monro em paciente com esclerose tuberosa, causando hidrocefalia obstrutiva; feito de células grandes poligonais de citoplasma vítreo abundante, algumas francamente ganglionares, com agrupamento perivascular e mastócitos entremeados. Grau 1, e hoje tratável com inibidor de mTOR sem cirurgia.',
    criteria: [
      'Localização junto ao forame de Monro, com crescimento intraventricular.',
      'Células grandes poligonais a fusiformes com citoplasma eosinofílico vítreo, algumas com aspecto ganglionar e nucléolo proeminente.',
      'Fenótipo misto glioneuronal: GFAP e S100 com sinaptofisina, neurofilamento e TTF-1 positivos.',
      'Contexto de esclerose tuberosa em quase todos: procure túberes corticais, angiomiolipoma renal e rabdomioma cardíaco.',
      'Mitoses ocasionais, necrose e proliferação vascular podem ocorrer e não indicam malignidade.',
    ],
    markers: [
      { marker: 'ttf1', pct: [80, 100], note: 'positivo, como nos tumores da região selar e ventricular: não interprete como pulmão nem tireoide' },
      { marker: 'gfap', pct: [70, 95], note: 'variável de célula para célula' },
      { marker: 's100', pct: [90, 100] },
      { marker: 'sinaptofisina', pct: [60, 90] },
      { marker: 'nf', pct: [50, 85] },
      { marker: 'neun', pct: [10, 40] },
      { marker: 'olig2', pct: [10, 40] },
      { marker: 'catepsinak', pct: [40, 80], note: 'reflete a via mTOR, como no PEComa e no angiomiolipoma da mesma síndrome' },
      { marker: 'melana', pct: [0, 15] },
      { marker: 'hmb45', pct: [0, 10] },
      { marker: 'idh1', pct: 0 },
      { marker: 'brafv600e', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 8] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Subependimoma: núcleos pequenos agrupados em matriz fibrilar, sem células gigantes ganglionares.',
      'Ganglioglioma: neurônios displásicos com CD34 em rede, fora do ventrículo.',
      'Gemistocytic astrocytoma e glioblastoma de células gigantes: infiltrativo, IDH ou p53 alterados.',
      'Neurocitoma central: células pequenas uniformes, NeuN difuso.',
      'PEComa e melanoma: HMB-45 forte, TTF-1 negativo.',
    ],
    molecular: 'Inativação bialélica de TSC1 ou TSC2, com ativação de mTOR: base do tratamento com everolimo.',
    sources: [WHO, PERRY],
  },
  {
    id: 'dnt',
    name: 'Tumor neuroepitelial disembrioplásico (DNT)',
    aka: ['DNET', 'DNT', 'dysembryoplastic neuroepithelial tumour'],
    behavior: 'benigno',
    sites: [{ site: 'encefalo', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'claras', 'estreladas'],
    architecture: ['nodular', 'infiltrativo'],
    features: ['estroma-mixoide', 'calcificacao', 'mitoses-raras'],
    ages: ['crianca', 'jovem'],
    summary: 'Tumor cortical de criança ou adulto jovem com epilepsia parcial refratária desde cedo, feito de nódulos intracorticais com o elemento glioneuronal específico: colunas de células oligodendrócito-símiles alinhadas ao longo de axônios, com neurônios maduros flutuando em lagos de mucina entre elas.',
    criteria: [
      'Elemento glioneuronal específico: colunas perpendiculares ao córtex, com matriz mucoide e neurônios flutuantes — o achado que define.',
      'Arquitetura multinodular intracortical, com displasia cortical focal associada com frequência.',
      'Células oligodendrócito-símiles OLIG2 positivas, com NeuN marcando os neurônios flutuantes maduros, e não as células tumorais.',
      'CD34 em rede ausente, o que o separa do ganglioglioma.',
      'Grau 1 e curável por ressecção; a persistência da epilepsia costuma vir da displasia cortical vizinha, não do tumor.',
    ],
    markers: [
      { marker: 'olig2', pct: [85, 100], note: 'nas células oligodendrócito-símiles' },
      { marker: 'sinaptofisina', pct: [80, 95], note: 'na matriz mucoide entre as colunas' },
      { marker: 'neun', pct: [80, 95], note: 'nos neurônios flutuantes maduros, não nas células tumorais' },
      { marker: 's100', pct: [85, 100] },
      { marker: 'gfap', pct: [40, 75], note: 'nos astrócitos entre as colunas' },
      { marker: 'cd34', pct: [0, 15], note: 'o negativo que o separa do ganglioglioma, que tem rede ramificada' },
      { marker: 'idh1', pct: 0, note: 'o negativo que separa de oligodendroglioma em adolescente' },
      { marker: 'atrx', pct: [0, 5], note: 'retido' },
      { marker: 'brafv600e', pct: [10, 30] },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'h3k27m', pct: 0 },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Oligodendroglioma: IDH-mutante com codeleção 1p/19q, infiltrativo, em adulto.',
      'Ganglioglioma: neurônios displásicos e binucleados, CD34 em rede, BRAF V600E mais frequente.',
      'Glioma angiocêntrico: células bipolares perivasculares, MYB::QKI.',
      'PLNTY: CD34 difuso, calcificações, alterações de BRAF ou FGFR.',
      'Displasia cortical focal tipo II: balloon cells, sem elemento glioneuronal específico.',
    ],
    molecular: 'Alterações de FGFR1 (duplicação em tandem do domínio tirosina-quinase ou mutação) na maioria.',
    sources: [WHO, PERRY],
  },
  {
    id: 'glioma-h3g34',
    name: 'Glioma hemisférico difuso, H3 G34-mutante',
    aka: ['diffuse hemispheric glioma H3 G34-mutant', 'glioma H3.3 G34R/V'],
    behavior: 'maligno',
    sites: [{ site: 'encefalo', role: 'primario', freq: 1 }],
    cells: ['fusocelular', 'pequenas-redondas', 'pleomorfico', 'estreladas'],
    architecture: ['infiltrativo', 'lencois'],
    features: ['necrose', 'mitoses-altas', 'vasos-espessos'],
    ages: ['jovem', 'crianca'],
    summary: 'Glioma difuso hemisférico de adolescente e adulto jovem, entidade nova da 5ª edição, que pode ter morfologia de glioblastoma ou de tumor embrionário de células pequenas; a combinação de H3.3 G34R/V positivo com OLIG2 negativo e perda de ATRX é bastante característica, e o prognóstico é ruim.',
    criteria: [
      'Glioma difuso dos hemisférios cerebrais, em adolescente ou adulto jovem.',
      'Mutação de H3-3A no códon G34 (G34R ou G34V), detectável pelo anticorpo específico.',
      'OLIG2 negativo ou muito focal, o que é incomum num glioma e serve de pista.',
      'Perda de ATRX e p53 aberrante na maioria, com IDH selvagem.',
      'Grau 4 por definição; morfologia embrionária não muda a classificação nem o tratamento.',
    ],
    markers: [
      { marker: 'h3g34rv', pct: [90, 100], note: 'nuclear; critério definidor. É outro clone que o G34W do tumor de células gigantes do osso' },
      { marker: 'olig2', pct: [0, 15], note: 'o negativo é a pista: quase todo glioma é positivo' },
      { marker: 'atrx', pct: [80, 95], note: 'o positivo é a perda' },
      { marker: 'p53', pct: [80, 95] },
      { marker: 'gfap', pct: [50, 85] },
      { marker: 's100', pct: [80, 100] },
      { marker: 'idh1', pct: 0 },
      { marker: 'h3k27m', pct: 0, note: 'o negativo que separa do glioma difuso de linha média' },
      { marker: 'sinaptofisina', pct: [20, 50], note: 'nas formas com morfologia embrionária' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda indicaria ATRT' },
      { marker: 'ae1ae3', pct: [0, 15] },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Glioblastoma IDH-selvagem do adulto: OLIG2 positivo, H3 selvagem, em paciente mais velho.',
      'Glioma difuso de linha média H3 K27-alterado: H3 K27M positivo, em linha média.',
      'ATRT: INI1 perdido, em lactente.',
      'Meduloblastoma e outros embrionários: no cerebelo, sinaptofisina difusa.',
      'Astrocitoma IDH-mutante: IDH1 R132H positivo.',
    ],
    molecular: 'H3-3A G34R/V, com ATRX e TP53 alterados; perfil de metilação próprio.',
    sources: [WHO, CIMPACT],
  },
  {
    id: 'glioma-hemisferico-lactente',
    name: 'Glioma hemisférico do lactente',
    aka: ['infant-type hemispheric glioma', 'glioma do lactente com fusão de tirosina-quinase'],
    behavior: 'maligno',
    sites: [{ site: 'encefalo', role: 'primario', freq: 1 }],
    cells: ['fusocelular', 'pleomorfico', 'estreladas', 'epitelioide'],
    architecture: ['infiltrativo', 'lencois', 'fasciculos'],
    features: ['necrose', 'mitoses-altas', 'hemorragia'],
    ages: ['crianca'],
    summary: 'Glioma hemisférico volumoso do primeiro ano de vida, entidade nova da 5ª edição, com histologia de alto grau mas comportamento melhor que o esperado; define-se por fusão de uma tirosina-quinase — NTRK, ALK, ROS1 ou MET —, todas com inibidor disponível, o que faz do reconhecimento uma decisão terapêutica.',
    criteria: [
      'Glioma difuso hemisférico no primeiro ano de vida, muitas vezes congênito e de grande volume.',
      'Histologia de alto grau na maioria, com necrose e mitoses, mas com sobrevida melhor que a de outros gliomas de alto grau pediátricos.',
      'Fusão de receptor de tirosina-quinase: NTRK1/2/3, ALK, ROS1 ou MET.',
      'Triagem por imuno com pan-TRK, ALK e ROS1, e confirmação molecular obrigatória antes de indicar o inibidor.',
      'H3 e IDH selvagens, o que o separa dos gliomas pediátricos de alto grau definidos por histona.',
    ],
    markers: [
      { marker: 'pan-trk', pct: [40, 60], note: 'nos casos com fusão NTRK, que são cerca de metade' },
      { marker: 'alk', pct: [20, 40], note: 'nos casos com fusão ALK' },
      { marker: 'ros1', pct: [10, 25] },
      { marker: 'gfap', pct: [70, 95] },
      { marker: 'olig2', pct: [50, 85] },
      { marker: 's100', pct: [85, 100] },
      { marker: 'idh1', pct: 0 },
      { marker: 'h3k27m', pct: 0 },
      { marker: 'h3g34rv', pct: 0 },
      { marker: 'atrx', pct: [0, 15], note: 'retido na maioria' },
      { marker: 'p53', pct: [10, 30] },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Glioblastoma pediátrico H3-selvagem e IDH-selvagem: sem fusão de tirosina-quinase, pior prognóstico.',
      'ATRT: INI1 perdido.',
      'Sarcoma intracraniano DICER1: fusocelular com rabdomioblastos, DICER1 mutado.',
      'Fibrossarcoma infantil intracraniano: mesma fusão ETV6::NTRK3, mas mesenquimal e GFAP negativo.',
      'Tumor rabdoide e outros embrionários: LIN28A ou INI1 conforme a entidade.',
    ],
    molecular: 'Fusões de NTRK1/2/3, ALK, ROS1 ou MET; alvo de larotrectinibe, entrectinibe e congêneres.',
    sources: [WHO, CIMPACT],
  },
  {
    id: 'gliomas-pediatricos-baixo-grau',
    name: 'Gliomas difusos pediátricos de baixo grau',
    aka: ['PLNTY', 'astrocitoma difuso MYB/MYBL1-alterado', 'glioma angiocêntrico', 'glioma de baixo grau MAPK-alterado'],
    behavior: 'benigno',
    sites: [{ site: 'encefalo', role: 'primario', freq: 2 }],
    cells: ['estreladas', 'fusocelular', 'claras', 'epitelioide'],
    architecture: ['infiltrativo', 'pseudopapilar', 'nodular'],
    features: ['calcificacao', 'mitoses-raras', 'estroma-mixoide'],
    ages: ['crianca', 'jovem'],
    summary: 'Família criada na 5ª edição para os gliomas difusos de criança com epilepsia e curso indolente, que antes viravam "astrocitoma difuso grau 2" e recebiam tratamento a mais: astrocitoma MYB/MYBL1-alterado, glioma angiocêntrico (com suas células bipolares em manguito perivascular), PLNTY (com CD34 difuso e calcificações) e o glioma de baixo grau com alteração da via MAPK.',
    criteria: [
      'Glioma difuso de criança ou adolescente, com epilepsia de longa data e crescimento muito lento.',
      'Histologia branda: sem mitoses significativas, sem necrose e sem proliferação microvascular.',
      'PLNTY: componente oligodendrócito-símile com calcificações abundantes e CD34 difuso em rede, com alteração de BRAF ou fusão de FGFR2/FGFR3.',
      'Glioma angiocêntrico: células bipolares alongadas em manguitos perivasculares radiais, com EMA em dot, e fusão MYB::QKI.',
      'A classificação depende de metilação ou sequenciamento: a imuno sozinha não distingue os quatro tipos entre si.',
    ],
    markers: [
      { marker: 'cd34', pct: [40, 80], note: 'difuso em rede no PLNTY; ausente nos demais' },
      { marker: 'olig2', pct: [60, 95] },
      { marker: 'gfap', pct: [70, 95] },
      { marker: 's100', pct: [85, 100] },
      { marker: 'brafv600e', pct: [10, 35], note: 'em parte dos PLNTY e dos MAPK-alterados' },
      { marker: 'idh1', pct: 0, note: 'o negativo é essencial: em adolescente, um glioma difuso IDH-mutante é outra doença' },
      { marker: 'atrx', pct: [0, 10], note: 'retido' },
      { marker: 'p53', pct: [0, 15], note: 'selvagem' },
      { marker: 'h3k27m', pct: 0 },
      { marker: 'ema', pct: [10, 40], note: 'em dot no glioma angiocêntrico' },
      { marker: 'neun', pct: [0, 10] },
      { marker: 'sinaptofisina', pct: [10, 30] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Astrocitoma IDH-mutante: IDH1 R132H positivo, ATRX perdido, em adulto jovem.',
      'Oligodendroglioma: IDH-mutante com codeleção 1p/19q.',
      'DNT e ganglioglioma: elemento glioneuronal específico ou neurônios displásicos.',
      'Astrocitoma pilocítico: bifásico com fibras de Rosenthal, KIAA1549::BRAF.',
      'Ependimoma: pseudorrosetas com EMA em dot difuso.',
    ],
    molecular: 'MYB ou MYBL1 alterados; MYB::QKI no angiocêntrico; BRAF e fusões de FGFR2/FGFR3 no PLNTY; via MAPK no restante.',
    sources: [WHO, CIMPACT],
  },
  {
    id: 'astrocitoma-piloide-alto-grau',
    name: 'Astrocitoma de alto grau com características piloides',
    aka: ['HGAP', 'high-grade astrocytoma with piloid features'],
    behavior: 'maligno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 1 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'estreladas', 'pleomorfico'],
    architecture: ['lencois', 'infiltrativo', 'fasciculos'],
    features: ['necrose', 'mitoses-moderadas', 'vasos-espessos', 'hialinizacao'],
    ages: ['adulto'],
    summary: 'Entidade nova da 5ª edição, definida só por perfil de metilação: glioma da fossa posterior de adulto, com citologia piloide e fibras de Rosenthal como num astrocitoma pilocítico, mas com necrose, proliferação microvascular e comportamento agressivo. A perda de ATRX com alteração de NF1 e CDKN2A é o perfil frequente.',
    criteria: [
      'Morfologia astrocitária piloide, com células bipolares e fibras de Rosenthal ou corpos granulares eosinofílicos.',
      'Sinais de alto grau: proliferação microvascular, necrose ou índice mitótico elevado.',
      'Localização preferencial na fossa posterior de adulto, o que a distingue do astrocitoma pilocítico da criança.',
      'Diagnóstico definitivo só por perfil de metilação: a morfologia e a imuno apenas levantam a hipótese.',
      'Alterações frequentes de ATRX, NF1 e CDKN2A/B, com IDH e H3 selvagens.',
    ],
    markers: [
      { marker: 'atrx', pct: [40, 70], note: 'o positivo é a perda; frequente e útil para levantar a hipótese' },
      { marker: 'gfap', pct: [85, 100] },
      { marker: 'olig2', pct: [70, 95] },
      { marker: 's100', pct: [90, 100] },
      { marker: 'idh1', pct: 0, note: 'o negativo que separa do astrocitoma IDH-mutante' },
      { marker: 'h3k27m', pct: 0, note: 'o negativo que separa do glioma de linha média, que compartilha o sítio' },
      { marker: 'h3g34rv', pct: 0 },
      { marker: 'p53', pct: [20, 50] },
      { marker: 'brafv600e', pct: [0, 10], note: 'o negativo que ajuda contra xantoastrocitoma pleomórfico anaplásico' },
      { marker: 'cd34', pct: [0, 20] },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Astrocitoma pilocítico: em criança, sem necrose nem mitoses, KIAA1549::BRAF, excelente prognóstico.',
      'Glioblastoma IDH-selvagem: hemisférico, sem citologia piloide.',
      'Glioma difuso de linha média: H3 K27M positivo, também na fossa posterior.',
      'Xantoastrocitoma pleomórfico anaplásico: BRAF V600E com CD34 e reticulina pericelular.',
      'Astrocitoma IDH-mutante grau 4: IDH1 R132H positivo.',
    ],
    molecular: 'Definido por metilação; ATRX, NF1 e CDKN2A/B alterados, com IDH e H3 selvagens.',
    sources: [WHO, CIMPACT],
  },
  {
    id: 'tumores-parenquima-pineal',
    name: 'Tumores do parênquima pineal',
    aka: ['pineocitoma', 'pineoblastoma', 'PPTID', 'tumor do parênquima pineal de diferenciação intermediária'],
    behavior: 'maligno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 2 },
      { site: 'medula-espinhal', role: 'metastase', freq: 1 },
      { site: 'meninges', role: 'metastase', freq: 1 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino', 'epitelioide'],
    architecture: ['lencois', 'rosetas', 'lobular'],
    features: ['calcificacao', 'necrose', 'mitoses-altas', 'mitoses-raras'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'O espectro do parênquima pineal, do pineocitoma grau 1 do adulto — com rosetas pineocitomatosas grandes e anucleadas — até o pineoblastoma grau 4 do lactente, indistinguível de outros embrionários de células pequenas. O CRX é o marcador de linhagem, e em criança o pineoblastoma obriga a pesquisar DICER1 e RB1.',
    criteria: [
      'Localização na glândula pineal, com hidrocefalia e síndrome de Parinaud.',
      'Pineocitoma: lençóis de células maduras com rosetas pineocitomatosas grandes, sem mitoses nem necrose.',
      'Pineoblastoma: células pequenas azuis densamente agrupadas, com rosetas de Homer Wright ou de Flexner-Wintersteiner, alto índice mitótico e necrose.',
      'CRX positivo confirma a linhagem fotorreceptora e separa dos germinativos e dos gliomas da região.',
      'Em criança com pineoblastoma: investigar DICER1 e RB1 germinativos (retinoblastoma trilateral).',
    ],
    markers: [
      { marker: 'crx', pct: [85, 100], note: 'linhagem pineal e fotorreceptora; é o marcador que decide' },
      { marker: 'sinaptofisina', pct: [90, 100] },
      { marker: 'nse', pct: [85, 100] },
      { marker: 'nf', pct: [60, 90], note: 'nas rosetas do pineocitoma' },
      { marker: 'cromogranina', pct: [30, 70] },
      { marker: 'neun', pct: [20, 60] },
      { marker: 'gfap', pct: [10, 40], note: 'só astrócitos aprisionados; difuso favorece glioma da região' },
      { marker: 'oct4', pct: 0, note: 'o negativo que exclui germinoma da região pineal' },
      { marker: 'sall4', pct: [0, 5] },
      { marker: 'plap', pct: [0, 5] },
      { marker: 'ae1ae3', pct: [0, 15], note: 'positiva no tumor papilar da região pineal, que é outra entidade' },
      { marker: 'rb1', pct: [10, 40], note: 'o positivo é a perda; no pineoblastoma associado a retinoblastoma' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda indicaria ATRT' },
      { marker: 'ki67', pct: [1, 60], note: 'praticamente nulo no pineocitoma e muito alto no pineoblastoma: é o que gradua' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Germinoma da região pineal: OCT4, SALL4 e PLAP positivos, com estroma linfoide.',
      'Tumor papilar da região pineal: queratina e TTF-1 positivos, arquitetura papilar.',
      'ATRT: INI1 perdido.',
      'Meduloblastoma metastático e outros embrionários: CRX costuma ser negativo.',
      'Cisto pineal: parênquima normal com gliose, sem massa celular.',
    ],
    molecular: 'DICER1, DROSHA e DGCR8 em subgrupos do pineoblastoma; RB1 no associado a retinoblastoma; KBTBD4 no de diferenciação intermediária.',
    sources: [WHO, PERRY],
  },
  {
    id: 'tumores-embrionarios-snc',
    name: 'Outros tumores embrionários do SNC (ETMR e neuroblastoma FOXR2)',
    aka: ['ETMR', 'tumor embrionário com rosetas multicamadas', 'neuroblastoma do SNC FOXR2-ativado'],
    behavior: 'maligno',
    sites: [
      { site: 'encefalo', role: 'primario', freq: 1 },
      { site: 'meninges', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'blastematoso', 'neuroendocrino'],
    architecture: ['rosetas', 'lencois', 'nodular'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos', 'calcificacao'],
    ages: ['crianca'],
    summary: 'Dois embrionários do lactente e do pré-escolar que saíram da antiga vala comum do PNET. O tumor embrionário com rosetas multicamadas tem rosetas de várias camadas com luz verdadeira sobre um fundo neuropílico, e é LIN28A positivo com amplificação de C19MC. O neuroblastoma do SNC FOXR2-ativado é definido por metilação e expressa OLIG2 focal com sinaptofisina.',
    criteria: [
      'ETMR: rosetas multicamadas com luz central verdadeira e figuras de mitose junto à luz, em fundo de neurópilo frouxo.',
      'LIN28A citoplasmático forte no ETMR, com amplificação ou fusão de C19MC confirmando.',
      'Neuroblastoma do SNC FOXR2: células pequenas com diferenciação neuroblástica e neuropílica, definido por perfil de metilação e superexpressão de FOXR2.',
      'INI1 e BRG1 retidos nos dois, o que os separa do ATRT.',
      'O termo PNET do SNC foi abandonado: um embrionário sem classificação molecular deve ser laudado como "não classificado", e não como PNET.',
    ],
    markers: [
      { marker: 'lin28a', pct: [85, 100], note: 'citoplasmático forte no ETMR; também marca germinativos, então leia no contexto' },
      { marker: 'sinaptofisina', pct: [70, 95] },
      { marker: 'nse', pct: [70, 95] },
      { marker: 'olig2', pct: [20, 60], note: 'focal no neuroblastoma FOXR2 e nas rosetas do ETMR' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define ATRT' },
      { marker: 'brg1', pct: [0, 5], note: 'retido' },
      { marker: 'gfap', pct: [10, 40], note: 'nos astrócitos aprisionados e em focos de diferenciação' },
      { marker: 'nf', pct: [20, 60] },
      { marker: 'crx', pct: [0, 20], note: 'o negativo que ajuda contra pineoblastoma' },
      { marker: 'betacatenina', pct: [0, 10], pattern: 'N' },
      { marker: 'ae1ae3', pct: [0, 20] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'ki67', pct: [50, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Meduloblastoma: no cerebelo, com grupos moleculares próprios; LIN28A negativo.',
      'ATRT: INI1 perdido.',
      'Pineoblastoma: CRX positivo, na região pineal.',
      'Ependimoma anaplásico: pseudorrosetas perivasculares, EMA em dot.',
      'Meduloepitelioma: túbulos de neuroepitélio primitivo com membrana limitante, no corpo ciliar ou no SNC.',
    ],
    molecular: 'Amplificação ou fusão de C19MC no ETMR (e a variante DICER1-mutada); superexpressão de FOXR2 no neuroblastoma do SNC.',
    sources: [WHO, CIMPACT],
  },
  {
    id: 'tumores-selares-ttf1',
    name: 'Tumores da neuro-hipófise TTF-1 positivos',
    aka: ['pituicitoma', 'oncocitoma de células fusiformes', 'tumor de células granulares da neuro-hipófise', 'sellar TTF-1 family'],
    behavior: 'benigno',
    sites: [{ site: 'sela', role: 'primario', freq: 2 }],
    cells: ['fusocelular', 'oncocitico', 'histiocitoide', 'epitelioide'],
    architecture: ['fasciculos', 'lencois', 'storiforme'],
    features: ['mitoses-raras', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    summary: 'Três tumores da hipófise posterior que a 5ª edição reconheceu como uma família única, derivada do pituícito e unida pela expressão de TTF-1: o pituicitoma fusocelular, o oncocitoma de células fusiformes e o tumor de células granulares da sela. Todos imitam adenoma hipofisário na imagem, sangram muito na cirurgia, e nenhum expressa hormônios.',
    criteria: [
      'Massa selar ou supraselar em adulto, muitas vezes com hipopituitarismo e sem hipersecreção hormonal.',
      'TTF-1 nuclear positivo: é o marcador que une a família e a separa do adenoma hipofisário.',
      'Pituicitoma: fascículos de células fusiformes eosinofílicas; oncocitoma de células fusiformes: citoplasma oncocítico com mitocôndrias; tumor de células granulares: citoplasma granular PAS-diastase resistente.',
      'Sinaptofisina, cromogranina e hormônios hipofisários negativos, com fatores de transcrição PIT1, TPIT e SF-1 negativos.',
      'Comportamento benigno (grau 1), mas a ressecção é difícil pela vascularização.',
    ],
    markers: [
      { marker: 'ttf1', pct: [90, 100], note: 'o marcador que define a família; não interprete como pulmão nem tireoide' },
      { marker: 's100', pct: [80, 100] },
      { marker: 'gfap', pct: [30, 70], note: 'variável entre os três tipos' },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 'cd68', pct: [40, 80], note: 'forte no tumor de células granulares' },
      { marker: 'ema', pct: [10, 40], note: 'o negativo ou fraco ajuda contra meningioma' },
      { marker: 'sinaptofisina', pct: [0, 15], note: 'o negativo que separa do adenoma hipofisário' },
      { marker: 'cromogranina', pct: [0, 10] },
      { marker: 'pit1', pct: 0 },
      { marker: 'tpit', pct: 0 },
      { marker: 'sf1', pct: 0 },
      { marker: 'ae1ae3', pct: [0, 15] },
      { marker: 'sstr2', pct: [0, 20], note: 'o negativo ajuda contra meningioma' },
      { marker: 'sox10', pct: [10, 40] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma hipofisário (PitNET): sinaptofisina e fatores de transcrição positivos, TTF-1 negativo.',
      'Meningioma selar: EMA e SSTR2A positivos, TTF-1 negativo.',
      'Schwannoma: SOX10 e S100 fortes, TTF-1 negativo.',
      'Craniofaringioma: epitélio escamoso, β-catenina nuclear ou BRAF V600E.',
      'Metástase de carcinoma pulmonar ou tireoidiano: também TTF-1 positiva — é a armadilha desta família; procure queratina.',
    ],
    pitfalls: ['TTF-1 positivo numa massa selar não indica metástase pulmonar nem tireoidiana: peça queratina, tireoglobulina e napsina antes de concluir.'],
    sources: [WHO, PERRY],
  },
  {
    id: 'melanocitico-meningeo',
    name: 'Tumores melanocíticos meníngeos',
    aka: ['melanocitoma meníngeo', 'melanoma meníngeo primário', 'melanocitose difusa'],
    behavior: 'intermediario',
    sites: [
      { site: 'meninges', role: 'primario', freq: 1 },
      { site: 'medula-espinhal', role: 'primario', freq: 1 },
      { site: 'encefalo', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'pleomorfico'],
    architecture: ['ninhos', 'fasciculos', 'lencois'],
    features: ['melanina', 'necrose', 'nucleolo', 'mitoses-raras', 'mitoses-altas'],
    ages: ['adulto'],
    summary: 'Proliferação dos melanócitos leptomeníngeos, que vai do melanocitoma bem delimitado e indolente ao melanoma primário difuso; a lesão é quase sempre negra à macroscopia e o painel melanocítico é o mesmo do melanoma cutâneo, mas o molecular é o do melanoma uveal — GNAQ e GNA11, não BRAF.',
    criteria: [
      'Proliferação melanocítica nas leptomeninges, com pigmento abundante na maioria.',
      'Melanocitoma: células uniformes em ninhos e fascículos, mitoses raras, sem necrose nem invasão do parênquima.',
      'Melanoma: atipia acentuada, mitoses frequentes, necrose e invasão do parênquima cerebral ou medular.',
      'Exclusão obrigatória de melanoma metastático: a lesão primária é única e sem primário cutâneo, ocular ou mucoso conhecido.',
      'Melanocitose e melanomatose difusas ocorrem na melanose neurocutânea, associada a NRAS.',
    ],
    markers: [
      { marker: 'sox10', pct: [95, 100] },
      { marker: 's100', pct: [95, 100] },
      { marker: 'melana', pct: [85, 100] },
      { marker: 'hmb45', pct: [85, 100] },
      { marker: 'mitf', pct: [80, 95] },
      { marker: 'tirosinase', pct: [70, 95] },
      { marker: 'prame', pct: [20, 60], note: 'difuso favorece melanoma sobre melanocitoma' },
      { marker: 'bap1', pct: [10, 40], note: 'o positivo é a perda; marca comportamento agressivo, como no uveal' },
      { marker: 'brafv600e', pct: [0, 10], note: 'ao contrário do cutâneo: aqui a via é GNAQ e GNA11' },
      { marker: 'gfap', pct: 0, note: 'o negativo que exclui glioma melanótico' },
      { marker: 'ema', pct: [0, 10], note: 'o negativo que exclui meningioma melanótico' },
      { marker: 'sstr2', pct: [0, 15] },
      { marker: 'ae1ae3', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 40], note: 'baixo no melanocitoma e alto no melanoma: é o que mais ajuda a graduar' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Melanoma metastático: muito mais comum que o primário; exige rastreio de pele, olho e mucosas.',
      'Meningioma melanótico: EMA e SSTR2A positivos.',
      'Schwannoma melanótico: SOX10 positivo também, mas com colágeno IV pericelular, e o psamomatoso marca o complexo de Carney.',
      'Melanose neurocutânea: difusa, em criança com nevo congênito gigante.',
      'Hemorragia e hemossiderina: pigmento ferro positivo, sem células melanocíticas.',
    ],
    molecular: 'GNAQ e GNA11, como no melanoma uveal; NRAS na melanose neurocutânea; BAP1 nos agressivos.',
    sources: [WHO, PERRY],
  },
  {
    id: 'meduloepitelioma-ciliar',
    name: 'Meduloepitelioma do corpo ciliar',
    aka: ['meduloepitelioma', 'dictioma', 'medulloepithelioma'],
    behavior: 'maligno',
    sites: [{ site: 'olho-orbita', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'blastematoso', 'pequenas-redondas', 'cartilaginoso'],
    architecture: ['papilar', 'cistico', 'rosetas'],
    features: ['condroide', 'mitoses-altas', 'necrose'],
    ages: ['crianca'],
    summary: 'Tumor do corpo ciliar da criança pequena, feito de fitas e túbulos de neuroepitélio primitivo que reproduzem a retina embrionária, com membranas limitantes nas duas faces e espaços císticos com ácido hialurônico; a variante teratoide acrescenta cartilagem, músculo esquelético e cérebro, e marca a síndrome DICER1.',
    criteria: [
      'Localização no corpo ciliar, em criança abaixo de dez anos, com leucocoria ou glaucoma secundário.',
      'Fitas, túbulos e rosetas de neuroepitélio primitivo com membrana limitante interna e externa, lembrando o cálice óptico.',
      'Espaços císticos contendo material mucoide (ácido hialurônico), característicos.',
      'Variante teratoide: elementos heterólogos, cartilagem hialina sendo o mais comum.',
      'Pesquisa de DICER1 germinativo obrigatória: associa-se a blastoma pleuropulmonar e a Sertoli-Leydig ovariano.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [40, 80], note: 'no neuroepitélio em túbulos' },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 's100', pct: [50, 85] },
      { marker: 'sinaptofisina', pct: [30, 70] },
      { marker: 'nse', pct: [50, 85] },
      { marker: 'gfap', pct: [10, 40] },
      { marker: 'crx', pct: [10, 40], note: 'menos constante que no retinoblastoma' },
      { marker: 'rb1', pct: [0, 15], note: 'retido; a perda indicaria retinoblastoma' },
      { marker: 'desmina', pct: [10, 40], note: 'nos elementos heterólogos da variante teratoide' },
      { marker: 'miogenina', pct: [10, 30] },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 'cd99', pct: [10, 40] },
      { marker: 'ki67', pct: [30, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Retinoblastoma: perda de RB1, CRX difuso, na retina e não no corpo ciliar.',
      'Rabdomiossarcoma orbitário: desmina e miogenina difusos, sem neuroepitélio tubular.',
      'Glioneuroma e hiperplasia do epitélio ciliar: sem atipia nem mitoses.',
      'Tumor teratoide rabdoide: INI1 perdido.',
      'Meduloepitelioma do SNC: mesma morfologia, outro sítio.',
    ],
    molecular: 'Mutação de DICER1, somática ou germinativa (síndrome DICER1).',
    sources: [WHO, PERRY],
  },
]
