/* ==========================================================================
   gi.ts — tubo digestivo: estômago, intestino delgado e ampola, cólon e
   reto, apêndice e ânus. O esôfago está em `thorax.ts`, e fígado, vias
   biliares e pâncreas ficam em `hepatopancreatic.ts`.

   Aqui moram duas perguntas caras da rotina: de onde vem este
   adenocarcinoma metastático (CK7/CK20, CDX2, SATB2, TTF-1, PAX8, GATA3) e
   o que é este tumor mesenquimal da parede (KIT, DOG1, desmina, S100).
   Entram também os marcadores preditivos obrigatórios: MMR, HER2, PD-L1 e
   claudina 18.2.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Digestive System Tumours, 2019; WHO Endocrine and
   Neuroendocrine, 5ª ed., 2022; revisões de imuno-histoquímica em Arch
   Pathol Lab Med, Am J Surg Pathol e Mod Pathol). As fontes estão como
   referência de texto: as séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Digestive System Tumours (2019)'
const WHONE = 'WHO Classification of Endocrine and Neuroendocrine Tumours, 5ª ed. (2022)'
const ODZE = 'Odze & Goldblum, Surgical Pathology of the GI Tract, Liver, Biliary Tract and Pancreas, 4ª ed.'

export const gi: Tumor[] = [
  /* ---- Estômago ------------------------------------------------------------------ */
  {
    id: 'adenocarcinoma-gastrico-intestinal',
    name: 'Adenocarcinoma gástrico de tipo intestinal',
    aka: ['adenocarcinoma gástrico tubular e papilar', 'gastric adenocarcinoma, intestinal type'],
    behavior: 'maligno',
    sites: [
      { site: 'estomago', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'ovario', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'papilar', 'cribriforme', 'infiltrativo'],
    features: ['mucina', 'desmoplasia', 'necrose', 'mitoses-altas', 'precursor', 'linfoide'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Glândulas malignas bem formadas que infiltram a parede em massa expansiva, sobre mucosa com gastrite atrófica e metaplasia intestinal; ligado a Helicobacter pylori e a dieta.',
    criteria: [
      'Glândulas coesas malignas com margem expansiva, sobre mucosa com atrofia e metaplasia intestinal.',
      'Displasia adjacente apoia a origem gástrica primária.',
      'Painel preditivo obrigatório no avançado: HER2, MMR, PD-L1 e claudina 18.2; EBV define um subtipo com estroma linfoide e ótimo prognóstico.',
      'O subtipo com estroma linfoide (carcinoma linfoepitelioma-símile) é EBER positivo e tem PD-L1 alto.',
    ],
    markers: [
      { marker: 'ck7', pct: [40, 70], note: 'padrão misto é comum no estômago: não use CK7/CK20 sozinhos' },
      { marker: 'ck20', pct: [40, 70] },
      { marker: 'cdx2', pct: [60, 85], note: 'mais positivo no tipo intestinal que no difuso' },
      { marker: 'satb2', pct: [5, 20], note: 'em geral negativo: o argumento contra origem colorretal' },
      { marker: 'muc5ac', pct: [50, 80], note: 'mucina gástrica foveolar' },
      { marker: 'muc2', pct: [30, 60] },
      { marker: 'vilina', pct: [60, 85] },
      { marker: 'her2', pct: [10, 20], note: 'critérios gástricos: coloração lateral ou basolateral conta como positiva' },
      { marker: 'mlh1', pct: [8, 20], note: 'perda por hipermetilação no subtipo MSI; boa resposta a imunoterapia' },
      { marker: 'pms2', pct: [8, 20] },
      { marker: 'msh2', pct: [1, 4] },
      { marker: 'msh6', pct: [1, 5] },
      { marker: 'ebv', pct: [5, 10], note: 'EBER positivo no subtipo com estroma linfoide' },
      { marker: 'pdl1', pct: [30, 60], note: 'avaliado por CPS' },
      { marker: 'p53', pct: [50, 70] },
      { marker: 'ecaderina', pct: [80, 95], note: 'preservada: separa do tipo difuso' },
      { marker: 'ttf1', pct: [0, 5] },
      { marker: 'pax8', pct: [0, 5] },
      { marker: 'gata3', pct: [0, 5] },
      { marker: 'heppar1', pct: [0, 10], note: 'positivo na variante hepatoide' },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma colorretal metastático: SATB2 e CDX2 difusos, CK7 negativa.',
      'Adenocarcinoma pancreatobiliar: SMAD4 perdido em parte, CK17 e S100P positivos.',
      'Adenocarcinoma pulmonar mucinoso metastático: história e imagem; SATB2 negativo nos dois.',
      'Carcinoma hepatoide gástrico: AFP, glipicano-3 e SALL4 positivos.',
    ],
    pitfalls: ['O padrão CK7/CK20 do estômago é imprevisível: não force a origem só com esses dois.'],
    molecular: 'Quatro grupos do TCGA: EBV, MSI, estável genomicamente (difuso, CDH1 e RHOA) e instabilidade cromossômica (ERBB2, VEGFA).',
    sources: [WHO, ODZE],
  },
  {
    id: 'adenocarcinoma-gastrico-difuso',
    name: 'Adenocarcinoma gástrico de tipo difuso (células em anel de sinete)',
    aka: ['carcinoma de células em anel de sinete', 'linite plástica', 'poorly cohesive carcinoma', 'câncer gástrico difuso hereditário'],
    behavior: 'maligno',
    sites: [
      { site: 'estomago', role: 'primario', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 3 },
      { site: 'ovario', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'medula-ossea', role: 'metastase', freq: 1 },
    ],
    cells: ['anel-sinete', 'epitelioide'],
    architecture: ['fila-indiana', 'infiltrativo'],
    features: ['mucina', 'desmoplasia', 'mitoses-moderadas'],
    ages: ['jovem', 'adulto'],
    summary: 'Células discoesas com vacúolo de mucina que desloca o núcleo, infiltrando isoladamente a parede e provocando fibrose difusa (linite plástica); mais comum em jovens e associado a CDH1 germinativo.',
    criteria: [
      'Células isoladas ou em pequenos grupos, sem formação glandular, permeando a lâmina própria e a muscular.',
      'Vacúolo de mucina intracitoplasmática com núcleo em crescente periférico.',
      'Perda de E-caderina é comum, o que cria o problema com o lobular de mama metastático.',
      'Metástase ovariana bilateral (tumor de Krukenberg) é apresentação clássica.',
      'Investigar CDH1 germinativo em jovens e com história familiar (câncer gástrico difuso hereditário).',
    ],
    markers: [
      { marker: 'ck7', pct: [50, 80] },
      { marker: 'ck20', pct: [30, 60] },
      { marker: 'cdx2', pct: [30, 60], note: 'menos positivo que no tipo intestinal, mas é a chave contra mama' },
      { marker: 'muc5ac', pct: [70, 95] },
      { marker: 'muc2', pct: [30, 60] },
      { marker: 'ecaderina', pct: [20, 50], note: 'o "positivo" é a expressão preservada; está perdida na maioria' },
      { marker: 'gata3', pct: [0, 10], note: 'negativo: o melhor argumento contra carcinoma lobular de mama' },
      { marker: 'trps1', pct: [0, 10] },
      { marker: 'er', pct: [0, 10], note: 'cuidado: há relatos de ER positivo em gástrico difuso' },
      { marker: 'satb2', pct: [0, 15] },
      { marker: 'her2', pct: [3, 10], note: 'bem menos frequente que no tipo intestinal' },
      { marker: 'mlh1', pct: [2, 8] },
      { marker: 'pdl1', pct: [20, 40] },
      { marker: 'p53', pct: [30, 50] },
      { marker: 'pax8', pct: [0, 5], note: 'negativo: separa de mucinoso ovariano primário' },
      { marker: 'ki67', pct: [40, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma lobular de mama metastático: GATA3, TRPS1 e ER positivos, CDX2 negativo.',
      'Linfoma e melanoma (pela discoesão): CD45, SOX10, queratina.',
      'Histiócitos xantomatosos da mucosa gástrica: CD68 positivo, queratina negativa; armadilha clássica em biópsia.',
      'Carcinoma mucinoso ovariano ou apendicular metastático: PAX8 ou SATB2 e história.',
    ],
    pitfalls: ['Xantoma gástrico e macrófagos são o simulador benigno mais comum: peça queratina antes de laudar anel de sinete.'],
    molecular: 'CDH1 (germinativo na forma hereditária), RHOA e fusões de CLDN18::ARHGAP; estável genomicamente no TCGA.',
    sources: [WHO, ODZE],
  },
  {
    id: 'carcinoma-hepatoide-gastrico',
    name: 'Carcinoma hepatoide gástrico',
    aka: ['hepatoid adenocarcinoma', 'adenocarcinoma produtor de alfafetoproteína'],
    behavior: 'maligno',
    sites: [
      { site: 'estomago', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['hepatocitoide', 'glandular', 'oncocitico'],
    architecture: ['trabecular', 'lencois', 'glandulas'],
    features: ['necrose', 'mitoses-altas', 'globulos-hialinos'],
    ages: ['idoso'],
    sex: 'm',
    summary: 'Adenocarcinoma gástrico com áreas de células poligonais eosinofílicas em trabéculas, idênticas a hepatócitos, com AFP alta no soro e metástases hepáticas volumosas; prognóstico ruim.',
    criteria: [
      'Componente hepatoide: células poligonais grandes com citoplasma eosinofílico em padrão trabecular, muitas vezes com glóbulos hialinos PAS positivos.',
      'AFP, glipicano-3 e SALL4 positivos, com componente de adenocarcinoma gástrico convencional associado.',
      'A grande dificuldade é distinguir de carcinoma hepatocelular metastático ou de invasão direta.',
      'AFP sérica alta acompanha e serve de marcador de seguimento.',
    ],
    markers: [
      { marker: 'afp', pct: [60, 85] },
      { marker: 'glipicano3', pct: [70, 95] },
      { marker: 'sall4', pct: [70, 95], note: 'muito útil; o hepatocelular comum é SALL4 negativo' },
      { marker: 'heppar1', pct: [50, 80], note: 'positivo: por si só não distingue do hepatocelular' },
      { marker: 'arginase', pct: [20, 50], note: 'menos positivo que no hepatocelular verdadeiro' },
      { marker: 'ck19', pct: [60, 90], note: 'positiva: o hepatocelular comum costuma ser negativo' },
      { marker: 'ck7', pct: [40, 70] },
      { marker: 'ck20', pct: [30, 60] },
      { marker: 'cdx2', pct: [30, 60] },
      { marker: 'moc31', pct: [70, 95], note: 'positivo: no hepatocelular é negativo' },
      { marker: 'claudina4', pct: [70, 95] },
      { marker: 'cea', pct: [50, 80], note: 'padrão canalicular ausente, ao contrário do hepatocelular' },
      { marker: 'cd10', pct: [10, 30] },
      { marker: 'her2', pct: [10, 25] },
      { marker: 'p53', pct: [60, 85] },
      { marker: 'ki67', pct: [70, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma hepatocelular: MOC-31 e claudina-4 negativos, CEA canalicular, SALL4 negativo, CK19 negativa.',
      'Tumor do saco vitelino: OCT4 negativo nos dois, mas o contexto (idade, sítio) difere.',
      'Adenocarcinoma gástrico convencional com citoplasma eosinofílico: sem AFP nem glipicano-3.',
      'Metástase de carcinoma adrenocortical: SF-1 e inibina positivos.',
    ],
    pitfalls: ['HepPar-1 positivo não prova hepatocelular: no hepatoide também marca. Use MOC-31, claudina-4, SALL4 e CK19.'],
    sources: [WHO, ODZE],
  },
  /* ---- Intestino delgado, cólon e reto ------------------------------------------ */
  {
    id: 'adenocarcinoma-colorretal',
    name: 'Adenocarcinoma colorretal',
    aka: ['adenocarcinoma de cólon', 'carcinoma colorretal', 'colorectal adenocarcinoma', 'CRC'],
    behavior: 'maligno',
    sites: [
      { site: 'colon-reto', role: 'primario', freq: 3 },
      { site: 'apendice', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'ovario', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'cribriforme', 'infiltrativo'],
    features: ['necrose', 'desmoplasia', 'mucina', 'mitoses-altas', 'precursor', 'linfoide'],
    ages: ['adulto', 'idoso'],
    summary: 'Glândulas malignas alongadas com necrose "suja" na luz, sobre adenoma residual; CDX2, SATB2 e CK20 positivos com CK7 negativa é o perfil que o identifica em qualquer metástase.',
    criteria: [
      'Glândulas malignas com debris necróticos intraluminais ("necrose suja") e desmoplasia.',
      'Perfil CK20 positivo, CK7 negativo, CDX2 e SATB2 positivos; SATB2 é o mais específico para origem colorretal.',
      'Teste de MMR obrigatório em todos os casos: rastreia Lynch e define imunoterapia.',
      'Nos avançados, testar RAS e BRAF; a mutação de BRAF V600E com perda de MLH1 aponta via esporádica, não Lynch.',
      'Os tumores MMR deficientes tendem a ser do cólon direito, mucinosos ou medulares, com linfócitos intratumorais e perda de CDX2.',
    ],
    markers: [
      { marker: 'cdx2', pct: [85, 95], note: 'pode ser perdido nos pouco diferenciados e nos MMR deficientes' },
      { marker: 'satb2', pct: [85, 95], note: 'o mais específico para origem colorretal; útil quando CDX2 falha' },
      { marker: 'ck20', pct: [80, 95] },
      { marker: 'ck7', pct: [5, 20], note: 'negativa na maioria; a positividade não exclui' },
      { marker: 'vilina', pct: [85, 95] },
      { marker: 'muc2', pct: [60, 85] },
      { marker: 'betacatenina', pct: [70, 90], pattern: 'N', note: 'nuclear pela via APC/Wnt; ajuda contra adenocarcinoma de bexiga primário' },
      { marker: 'mlh1', pct: [10, 15], note: 'perda com PMS2: esporádica por hipermetilação (com BRAF V600E) ou Lynch' },
      { marker: 'pms2', pct: [10, 15] },
      { marker: 'msh2', pct: [1, 3], note: 'perda com MSH6 aponta Lynch' },
      { marker: 'msh6', pct: [1, 4] },
      { marker: 'brafv600e', pct: [8, 12], note: 'com perda de MLH1 favorece esporádico; isolada indica pior prognóstico' },
      { marker: 'p53', pct: [50, 70] },
      { marker: 'her2', pct: [3, 8], note: 'amplificado numa minoria; alvo terapêutico no RAS selvagem' },
      { marker: 'pdl1', pct: [5, 15] },
      { marker: 'ttf1', pct: [0, 5], note: 'negativo; cuidado com o clone SPT24, que pode marcar colorretal' },
      { marker: 'pax8', pct: [0, 10], note: 'o policlonal pode ser positivo: use o monoclonal' },
      { marker: 'gata3', pct: [0, 5] },
      { marker: 'ki67', pct: [70, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma de intestino delgado ou de ampola: SATB2 em geral negativo, CK7 positiva.',
      'Adenocarcinoma pulmonar mucinoso invasivo: CK20 e CDX2 podem ser positivos, mas SATB2 é negativo.',
      'Adenocarcinoma endometrioide ou mucinoso ovariano: PAX8 e ER positivos.',
      'Adenocarcinoma de bexiga e do úraco: β-catenina membranosa, sem componente colorretal.',
      'Carcinoma medular colorretal: perda de CDX2 e de MLH1, calretinina positiva.',
    ],
    pitfalls: ['CDX2 é positivo em muitos adenocarcinomas não colorretais (estômago, pâncreas, pulmão mucinoso, ovário mucinoso): SATB2 é o desempate.', 'SATB2 também é positivo em osteossarcoma e em sarcoma BCOR: o contexto importa.'],
    molecular: 'Via APC/KRAS/TP53 na maioria; via serrilhada com BRAF V600E e hipermetilação; MSI em 15% (Lynch em 3%).',
    sources: [WHO, ODZE],
  },
  {
    id: 'carcinoma-medular-colorretal',
    name: 'Carcinoma medular colorretal',
    aka: ['medullary carcinoma of the colon', 'carcinoma indiferenciado com estroma linfoide'],
    behavior: 'maligno',
    sites: [
      { site: 'colon-reto', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'sincicial'],
    architecture: ['lencois', 'nodular'],
    features: ['linfoide', 'necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['idoso'],
    sex: 'f',
    summary: 'Lençóis sinciciais de células grandes vesiculosas com nucléolo evidente e infiltrado linfocitário intratumoral intenso, no cólon direito de mulheres idosas; MMR deficiente e prognóstico melhor do que a morfologia sugere.',
    criteria: [
      'Crescimento sólido sincicial com bordas expansivas e linfócitos intratumorais abundantes.',
      'Deficiência de MMR (quase sempre perda de MLH1 e PMS2 por hipermetilação, com BRAF V600E).',
      'Perda frequente de CDX2, o que faz o tumor parecer não colorretal.',
      'Calretinina positiva numa parcela: mais um motivo de confusão com mesotelioma e com tumor indiferenciado.',
      'Apesar do aspecto indiferenciado, o prognóstico é melhor que o do adenocarcinoma pouco diferenciado comum.',
    ],
    markers: [
      { marker: 'mlh1', pct: [85, 100], note: 'PERDA quase constante, com PMS2' },
      { marker: 'pms2', pct: [85, 100] },
      { marker: 'cdx2', pct: [20, 50], note: 'perdido com frequência: engana quanto à origem' },
      { marker: 'satb2', pct: [40, 70] },
      { marker: 'ck20', pct: [20, 50] },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'calretinina', pct: [40, 70], note: 'positiva em boa parte: armadilha com mesotelioma' },
      { marker: 'ae1ae3', pct: [90, 100], note: 'confirma natureza epitelial contra linfoma' },
      { marker: 'cd45', pct: 0, note: 'negativo nas células tumorais; os linfócitos do fundo são positivos' },
      { marker: 'brafv600e', pct: [60, 85] },
      { marker: 'sinaptofisina', pct: [10, 30], note: 'focal: não faz carcinoma neuroendócrino' },
      { marker: 'cromogranina', pct: [0, 15] },
      { marker: 'insm1', pct: [0, 15], note: 'negativa: separa do carcinoma neuroendócrino de grandes células' },
      { marker: 'pdl1', pct: [40, 70] },
      { marker: 'p53', pct: [10, 30], note: 'em geral selvagem, ao contrário do adenocarcinoma comum' },
      { marker: 'ki67', pct: [70, 95] },
    ],
    mimics: [
      'Linfoma de grandes células: CD45 positivo, queratina negativa.',
      'Carcinoma neuroendócrino de grandes células: INSM1 e cromogranina difusas, p53 aberrante.',
      'Adenocarcinoma pouco diferenciado comum: sem infiltrado linfoide, MMR intacto, pior prognóstico.',
      'Metástase de carcinoma indiferenciado: CDX2 e SATB2 ajudam, mas podem faltar aqui.',
    ],
    sources: [WHO, ODZE],
  },
  {
    id: 'neoplasia-mucinosa-apendicular',
    name: 'Neoplasia mucinosa apendicular de baixo grau e adenocarcinoma mucinoso do apêndice',
    aka: ['LAMN', 'low-grade appendiceal mucinous neoplasm', 'pseudomixoma peritoneal'],
    behavior: 'maligno',
    sites: [
      { site: 'apendice', role: 'primario', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 3 },
      { site: 'ovario', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular'],
    architecture: ['lobular', 'infiltrativo'],
    features: ['mucina', 'calcificacao', 'mitoses-raras', 'desmoplasia'],
    ages: ['adulto', 'idoso'],
    summary: 'Epitélio mucinoso viloso ou plano de baixo grau que substitui a mucosa apendicular, com mucina dissecando a parede e atrofia da muscular; a disseminação peritoneal produz o pseudomixoma.',
    criteria: [
      'Epitélio mucinoso de baixo grau com perda da lâmina própria e da muscular da mucosa, e fibrose ou hialinização da parede.',
      'Empurra a parede em vez de infiltrar: sem invasão destrutiva, é neoplasia de baixo grau, não adenocarcinoma.',
      'O estadiamento depende de onde chegaram o epitélio e a mucina acelular: as duas coisas se registram separadamente.',
      'Pseudomixoma peritoneal: classificado em acelular, de baixo grau e de alto grau (com ou sem células em anel de sinete).',
      'Toda mucina ovariana bilateral com pseudomixoma exige examinar o apêndice: a origem quase sempre é apendicular.',
    ],
    markers: [
      { marker: 'ck20', pct: [90, 100] },
      { marker: 'cdx2', pct: [85, 100] },
      { marker: 'satb2', pct: [80, 95], note: 'positivo: prova origem apendicular ou colorretal num implante ovariano' },
      { marker: 'ck7', pct: [10, 40], note: 'pode ser positiva: não exclui origem apendicular' },
      { marker: 'muc2', pct: [85, 100] },
      { marker: 'muc5ac', pct: [70, 95] },
      { marker: 'pax8', pct: [0, 5], note: 'negativo: separa do mucinoso ovariano primário' },
      { marker: 'er', pct: [0, 5] },
      { marker: 'p53', pct: [10, 30], note: 'aberrante nos de alto grau' },
      { marker: 'mlh1', pct: [0, 5], note: 'MMR em geral intacto' },
      { marker: 'ecaderina', pct: [85, 100] },
      { marker: 'ki67', pct: [5, 30], note: 'baixo no LAMN, alto no adenocarcinoma mucinoso' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor mucinoso ovariano primário: PAX8 positivo em parte, SATB2 negativo, unilateral e grande.',
      'Mucocele por obstrução: epitélio sem atipia nem perda da lâmina própria.',
      'Adenocarcinoma mucinoso colorretal com extensão: topografia.',
      'Endometriose com metaplasia mucinosa: estroma endometrial CD10 positivo.',
    ],
    pitfalls: ['Mucina acelular e mucina com epitélio têm prognósticos muito diferentes: relate as duas separadamente.'],
    molecular: 'KRAS e GNAS mutados na maioria; TP53 nos de alto grau.',
    sources: [WHO, ODZE],
  },
  {
    id: 'adenocarcinoma-delgado-ampola',
    name: 'Adenocarcinoma de intestino delgado e da ampola',
    aka: ['adenocarcinoma duodenal', 'carcinoma ampular', 'ampullary carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'intestino-delgado', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'papilar', 'infiltrativo'],
    features: ['mucina', 'desmoplasia', 'mitoses-altas', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma do duodeno, jejuno, íleo ou da papila; na ampola, separar o subtipo intestinal do pancreatobiliar muda o prognóstico e a quimioterapia.',
    criteria: [
      'Glândulas malignas com adenoma ou displasia adjacente; na ampola, definir o epicentro (intra-ampular, periampular, ductal).',
      'Subtipo intestinal: epitélio colunar alto tipo colônico, CDX2, CK20 e MUC2 positivos, melhor prognóstico.',
      'Subtipo pancreatobiliar: glândulas pequenas em estroma desmoplásico denso, CK7, MUC1 e CK17 positivos, pior prognóstico.',
      'Testar MMR: adenocarcinoma de delgado tem taxa relevante de deficiência e associação com Lynch e com doença celíaca e Crohn.',
    ],
    markers: [
      { marker: 'ck7', pct: [50, 80], note: 'alta no subtipo pancreatobiliar' },
      { marker: 'ck20', pct: [40, 70], note: 'alta no subtipo intestinal' },
      { marker: 'cdx2', pct: [60, 85] },
      { marker: 'satb2', pct: [10, 30], note: 'em geral negativo: separa de colorretal' },
      { marker: 'muc2', pct: [40, 70], note: 'subtipo intestinal' },
      { marker: 'muc5ac', pct: [50, 80] },
      { marker: 'ck17', pct: [30, 60], note: 'subtipo pancreatobiliar' },
      { marker: 's100p', pct: [50, 80], note: 'mais no pancreatobiliar' },
      { marker: 'maspina', pct: [50, 80] },
      { marker: 'smad4', pct: [20, 40], note: 'perda favorece subtipo pancreatobiliar' },
      { marker: 'mlh1', pct: [8, 20] },
      { marker: 'pms2', pct: [8, 20] },
      { marker: 'msh2', pct: [3, 8], note: 'associação com Lynch' },
      { marker: 'her2', pct: [5, 15] },
      { marker: 'p53', pct: [40, 70] },
      { marker: 'ki67', pct: [60, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma colorretal metastático ou por extensão: SATB2 difuso.',
      'Adenocarcinoma pancreático invadindo o duodeno: SMAD4 perdido, topografia do epicentro.',
      'Adenocarcinoma gástrico por extensão: MUC5AC e a mucosa de origem.',
      'Adenoma com displasia de alto grau: sem invasão da submucosa.',
    ],
    sources: [WHO, ODZE],
  },
  /* ---- Neuroendócrinos do tubo digestivo ---------------------------------------- */
  {
    id: 'net-gastrico',
    name: 'Tumor neuroendócrino gástrico',
    aka: ['carcinoide gástrico', 'NET gástrico tipo 1, 2 e 3', 'gastric neuroendocrine tumour'],
    behavior: 'maligno',
    sites: [
      { site: 'estomago', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 1 },
    ],
    cells: ['neuroendocrino', 'epitelioide'],
    architecture: ['trabecular', 'ninhos', 'organoide'],
    features: ['mitoses-raras', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'Ninhos e trabéculas de células neuroendócrinas monótonas na mucosa e submucosa gástrica; o tipo 1, que é o mais comum, nasce da hiperplasia de células enterocromafins-símile na gastrite atrófica autoimune.',
    criteria: [
      'Arquitetura organoide com células uniformes e cromatina em sal e pimenta, positivas para cromogranina e sinaptofisina.',
      'Tipar é o que importa: tipo 1 (gastrite atrófica autoimune, hipergastrinemia, múltiplos, indolentes), tipo 2 (Zollinger-Ellison e MEN1) e tipo 3 (esporádico, solitário, gastrina normal, agressivo).',
      'Graduar por mitoses e Ki-67 (G1, G2, G3), separado do carcinoma neuroendócrino.',
      'A mucosa não tumoral responde a pergunta do tipo: atrofia corporal com metaplasia e hiperplasia de células enterocromafins-símile indica tipo 1.',
    ],
    markers: [
      { marker: 'cromogranina', pct: [90, 100] },
      { marker: 'sinaptofisina', pct: [95, 100] },
      { marker: 'insm1', pct: [90, 100] },
      { marker: 'cd56', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'sstr2', pct: [70, 95] },
      { marker: 'cdx2', pct: [10, 40] },
      { marker: 'satb2', pct: [0, 15] },
      { marker: 'ttf1', pct: [0, 10] },
      { marker: 'isl1', pct: [20, 50] },
      { marker: 'pdx1', pct: [40, 70] },
      { marker: 'serotonina', pct: [5, 20], note: 'baixa: as células são histaminérgicas (ECL), não serotoninérgicas' },
      { marker: 'ki67', pct: [10, 30], note: 'define o grau: menos de 3% é G1, 3 a 20% é G2, acima de 20% é G3' },
      { marker: 'p53', pct: [0, 10], note: 'selvagem: aberrante sugere carcinoma neuroendócrino' },
      { marker: 'rb1', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma neuroendócrino gástrico: Ki-67 muito alto, p53 aberrante, perda de RB1, necrose.',
      'Adenocarcinoma pouco diferenciado: marcadores neuroendócrinos negativos ou focais.',
      'Hiperplasia de células enterocromafins-símile: nódulos menores que 0,5 mm, sem invasão da submucosa.',
      'NET metastático de outro sítio: CDX2, SATB2, ISL1, TTF-1.',
    ],
    molecular: 'MEN1 nos tipos 2; os tipos 1 são hiperplásicos-neoplásicos secundários à hipergastrinemia.',
    sources: [WHONE, WHO],
  },
  {
    id: 'net-intestino-delgado',
    name: 'Tumor neuroendócrino de intestino delgado (íleo)',
    aka: ['carcinoide de intestino médio', 'midgut NET', 'tumor carcinoide ileal'],
    behavior: 'maligno',
    sites: [
      { site: 'intestino-delgado', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['neuroendocrino', 'epitelioide'],
    architecture: ['ninhos', 'organoide', 'trabecular'],
    features: ['desmoplasia', 'mitoses-raras', 'calcificacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Ninhos sólidos com paliçada periférica de células com grânulos argentafins, nasce na submucosa ileal, é multicêntrico e provoca reação desmoplásica mesentérica intensa com isquemia; causa a síndrome carcinoide quando metastatiza para o fígado.',
    criteria: [
      'Ninhos arredondados com paliçada periférica, células uniformes, cromatina fina e citoplasma eosinofílico granular.',
      'Serotonina e CDX2 positivos com SATB2 e TTF-1 negativos: o perfil de intestino médio.',
      'Massa mesentérica desmoplásica desproporcional ao tumor primário, muitas vezes maior que ele.',
      'Múltiplos tumores primários em até um terço: examinar todo o segmento ressecado.',
      'Grau por mitoses e Ki-67, com metástase hepática mesmo em G1.',
    ],
    markers: [
      { marker: 'cromogranina', pct: [95, 100], note: 'forte e difusa' },
      { marker: 'sinaptofisina', pct: [95, 100] },
      { marker: 'insm1', pct: [90, 100] },
      { marker: 'serotonina', pct: [85, 100], note: 'característica do intestino médio' },
      { marker: 'cdx2', pct: [70, 95] },
      { marker: 'satb2', pct: [0, 15], note: 'negativo: separa do NET retal' },
      { marker: 'ttf1', pct: [0, 5], note: 'negativo: separa do carcinoide pulmonar' },
      { marker: 'isl1', pct: [0, 20], note: 'negativo: separa do NET pancreático e retal' },
      { marker: 'pdx1', pct: [0, 20] },
      { marker: 'sstr2', pct: [85, 100], note: 'base do PET com peptídeo marcado e do tratamento com análogos' },
      { marker: 'ae1ae3', pct: [80, 95] },
      { marker: 'psap', pct: [10, 30] },
      { marker: 'ki67', pct: [5, 20], note: 'em geral menor que 3%: G1' },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'atrx', pct: [0, 5], note: 'retido; a perda é do NET pancreático' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'NET pancreático metastático no fígado: ISL1 e PDX1 positivos, serotonina negativa.',
      'Carcinoide pulmonar metastático: TTF-1 positivo em parte.',
      'NET retal: SATB2 e PSAP positivos, CDX2 negativo.',
      'Adenocarcinoma pouco diferenciado: queratina difusa, marcadores neuroendócrinos negativos.',
      'Paraganglioma gangliocítico duodenal: três componentes, S100 nas células sustentaculares.',
    ],
    pitfalls: ['Uma metástase hepática neuroendócrina sem primário conhecido se resolve com CDX2, SATB2, ISL1, TTF-1 e serotonina: o intestino médio é a origem mais comum.'],
    molecular: 'Perda de 18q, CDKN1B mutado numa minoria; sem KRAS nem TP53.',
    sources: [WHONE, WHO],
  },
  {
    id: 'net-apendice',
    name: 'Tumor neuroendócrino do apêndice',
    aka: ['carcinoide apendicular', 'appendiceal NET'],
    behavior: 'maligno',
    sites: [
      { site: 'apendice', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['neuroendocrino', 'epitelioide'],
    architecture: ['ninhos', 'organoide'],
    features: ['mitoses-raras', 'desmoplasia'],
    ages: ['jovem', 'adulto'],
    summary: 'Achado incidental na ponta do apêndice apendicectomizado: ninhos sólidos de células enterocromafins na submucosa e na muscular, quase sempre menores que 1 cm e curados pela própria apendicectomia.',
    criteria: [
      'Ninhos sólidos com células argentafins, muitas vezes envolvendo a serosa e o mesoapêndice sem que isso piore o prognóstico.',
      'Tamanho é o que decide a conduta: até 1 cm, apendicectomia basta; acima de 2 cm ou com invasão mesoapendicular acima de 3 mm, considerar colectomia direita.',
      'Distinguir do adenocarcinoma de células caliciformes, que é outra doença e bem mais agressivo.',
      'A invasão perineural e linfovascular é comum e isolada não muda a conduta.',
    ],
    markers: [
      { marker: 'cromogranina', pct: [90, 100] },
      { marker: 'sinaptofisina', pct: [95, 100] },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'serotonina', pct: [80, 95] },
      { marker: 'cdx2', pct: [50, 80] },
      { marker: 'satb2', pct: [20, 50] },
      { marker: 's100', pct: [30, 60], note: 'células sustentaculares em parte dos casos' },
      { marker: 'sstr2', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [70, 95], note: 'às vezes fraca' },
      { marker: 'ck20', pct: [10, 30] },
      { marker: 'muc2', pct: [0, 15], note: 'negativo: separa do adenocarcinoma de células caliciformes' },
      { marker: 'ki67', pct: [0, 10], note: 'quase sempre G1' },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma de células caliciformes: células caliciformes verdadeiras com mucina, MUC2 positivo, comportamento de adenocarcinoma.',
      'NET de intestino delgado: mesma citologia; a topografia decide.',
      'Hiperplasia neuroendócrina e neuroma apendicular: S100 difusa, sem ninhos epiteliais.',
    ],
    sources: [WHONE, WHO],
  },
  {
    id: 'net-reto',
    name: 'Tumor neuroendócrino do reto',
    aka: ['carcinoide retal', 'rectal NET', 'NET de intestino posterior'],
    behavior: 'maligno',
    sites: [
      { site: 'colon-reto', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 1 },
    ],
    cells: ['neuroendocrino', 'epitelioide'],
    architecture: ['trabecular', 'ninhos'],
    features: ['mitoses-raras'],
    ages: ['adulto'],
    summary: 'Nódulo submucoso amarelado achado na colonoscopia de rastreamento, com trabéculas e cordões de células uniformes; cromogranina costuma ser fraca, o que confunde, mas SATB2 e PSAP são positivos.',
    criteria: [
      'Trabéculas e fitas de células monótonas na submucosa, com cromogranina fraca ou focal.',
      'Perfil de intestino posterior: SATB2 e PSAP positivos, CDX2 em geral negativo, serotonina negativa.',
      'Sinaptofisina e INSM1 são os marcadores confiáveis aqui, já que a cromogranina falha.',
      'Tamanho menor que 1 cm, sem invasão da muscular própria, permite ressecção endoscópica.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [95, 100] },
      { marker: 'insm1', pct: [90, 100] },
      { marker: 'cromogranina', pct: [30, 60], note: 'fraca ou focal: sua negatividade NÃO exclui NET retal' },
      { marker: 'satb2', pct: [80, 95], note: 'característico do intestino posterior' },
      { marker: 'psap', pct: [70, 90], note: 'fosfatase ácida prostática positiva: armadilha com próstata' },
      { marker: 'isl1', pct: [70, 90] },
      { marker: 'cdx2', pct: [0, 20], note: 'em geral negativo, ao contrário do intestino médio' },
      { marker: 'serotonina', pct: [0, 15] },
      { marker: 'ttf1', pct: [0, 5] },
      { marker: 'nkx31', pct: [0, 10], note: 'negativo: o desempate contra adenocarcinoma prostático quando PSAP é positivo' },
      { marker: 'psa', pct: [0, 5] },
      { marker: 'sstr2', pct: [60, 90] },
      { marker: 'ae1ae3', pct: [70, 95] },
      { marker: 'ki67', pct: [0, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma prostático invadindo o reto: NKX3.1 e PSA positivos, marcadores neuroendócrinos negativos.',
      'NET de intestino médio metastático: CDX2 e serotonina positivos, SATB2 negativo.',
      'Adenocarcinoma colorretal: glândulas, CK20 e CDX2 difusos.',
      'Linfoma e melanoma: CD45 e SOX10.',
    ],
    pitfalls: ['Cromogranina negativa em nódulo submucoso retal não exclui NET: use sinaptofisina e INSM1.', 'PSAP positivo aqui não indica próstata.'],
    sources: [WHONE, WHO],
  },
  {
    id: 'adenocarcinoma-celulas-caliciformes',
    name: 'Adenocarcinoma de células caliciformes do apêndice',
    aka: ['goblet cell adenocarcinoma', 'carcinoide de células caliciformes (nome antigo)', 'GCA'],
    behavior: 'maligno',
    sites: [
      { site: 'apendice', role: 'primario', freq: 1 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'ovario', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['anel-sinete', 'glandular', 'neuroendocrino'],
    architecture: ['ninhos', 'infiltrativo', 'fila-indiana'],
    features: ['mucina', 'desmoplasia', 'mitoses-moderadas', 'perineural'],
    ages: ['adulto'],
    summary: 'Ninhos coesos de células caliciformes com mucina, infiltrando concentricamente a parede apendicular, com marcação neuroendócrina apenas focal; comporta-se como adenocarcinoma, não como carcinoide.',
    criteria: [
      'Aglomerados de células caliciformes verdadeiras, infiltrando a parede de forma concêntrica, muitas vezes sem lesão mucosa.',
      'Marcadores neuroendócrinos apenas dispersos e focais: não é um tumor neuroendócrino.',
      'Graduação em três níveis pela proporção de padrão tubular/caliciforme contra padrão desorganizado de células isoladas.',
      'Metástase ovariana bilateral é comum e imita tumor de Krukenberg.',
    ],
    markers: [
      { marker: 'ck20', pct: [80, 95] },
      { marker: 'cdx2', pct: [80, 95] },
      { marker: 'satb2', pct: [70, 90] },
      { marker: 'muc2', pct: [85, 100] },
      { marker: 'ck7', pct: [20, 50] },
      { marker: 'sinaptofisina', pct: [40, 70], note: 'focal e dispersa: não faz NET' },
      { marker: 'cromogranina', pct: [30, 60], note: 'idem' },
      { marker: 'insm1', pct: [10, 30] },
      { marker: 'ecaderina', pct: [70, 95] },
      { marker: 'pax8', pct: [0, 5], note: 'negativo: separa do mucinoso ovariano primário' },
      { marker: 'er', pct: [0, 5] },
      { marker: 'p53', pct: [20, 50], note: 'aberrante nos de alto grau' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'NET apendicular: ninhos sólidos sem células caliciformes, marcadores neuroendócrinos difusos.',
      'Adenocarcinoma mucinoso apendicular: epitélio mucinoso viloso, não ninhos de caliciformes.',
      'Tumor de Krukenberg gástrico: CDX2 e SATB2 negativos ou fracos, MUC5AC positivo.',
      'Adenocarcinoma de células em anel de sinete colorretal: SATB2 também positivo; a topografia decide.',
    ],
    pitfalls: ['O nome antigo "carcinoide" fez tratar o tumor como indolente por décadas: o comportamento é de adenocarcinoma.'],
    sources: [WHO, WHONE],
  },
  {
    id: 'carcinoma-neuroendocrino-gi',
    name: 'Carcinoma neuroendócrino do tubo digestivo',
    aka: ['NEC', 'carcinoma neuroendócrino de pequenas e de grandes células', 'MiNEN (quando misto)'],
    behavior: 'maligno',
    sites: [
      { site: 'colon-reto', role: 'primario', freq: 1 },
      { site: 'estomago', role: 'primario', freq: 1 },
      { site: 'esofago', role: 'primario', freq: 1 },
      { site: 'anus', role: 'primario', freq: 1 },
      { site: 'pancreas', role: 'primario', freq: 1 },
      { site: 'vias-biliares', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino', 'epitelioide'],
    architecture: ['lencois', 'ninhos', 'organoide'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma pouco diferenciado de pequenas ou grandes células com marcação neuroendócrina, mitoses acima de 20 por 2 mm² e Ki-67 muito alto; nada a ver com o NET bem diferenciado, apesar do nome parecido.',
    criteria: [
      'Citologia pouco diferenciada (pequenas ou grandes células) com necrose extensa.',
      'Ki-67 quase sempre acima de 55%, com p53 aberrante e perda de RB1: o oposto do NET G3, que mantém p53 e RB1.',
      'A distinção de NET G3 é fundamental: o carcinoma responde a platina, o NET G3 não.',
      'MiNEN quando há um componente adenocarcinomatoso de pelo menos 30%.',
      'Testar MMR: os NEC de cólon podem ser MMR deficientes.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [85, 100] },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'cromogranina', pct: [40, 70], note: 'fraca e focal, ao contrário do NET' },
      { marker: 'cd56', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [85, 100], note: 'em dot nas pequenas células' },
      { marker: 'ki67', pct: [95, 100], note: 'em geral acima de 55%; o argumento central contra NET G3' },
      { marker: 'p53', pct: [70, 90], note: 'aberrante; selvagem no NET G3' },
      { marker: 'rb1', pct: [70, 90], note: 'PERDA de expressão; retido no NET G3' },
      { marker: 'cdx2', pct: [30, 60] },
      { marker: 'satb2', pct: [20, 50] },
      { marker: 'ttf1', pct: [20, 50], note: 'positivo mesmo fora do pulmão: não prova origem pulmonar' },
      { marker: 'sstr2', pct: [10, 30], note: 'baixa: por isso o PET com peptídeo é pouco útil aqui' },
      { marker: 'mlh1', pct: [5, 20] },
      { marker: 'cd45', pct: 0 },
      { marker: 'pdl1', pct: [10, 30] },
    ],
    mimics: [
      'NET G3 bem diferenciado: arquitetura organoide, p53 selvagem, RB1 retido, SSTR2 positivo, Ki-67 em geral 20 a 55%.',
      'Carcinoma de pequenas células pulmonar metastático: TTF-1 positivo nos dois; a clínica decide.',
      'Linfoma: CD45 positivo.',
      'Adenocarcinoma pouco diferenciado: marcadores neuroendócrinos negativos ou focais.',
      'Melanoma: SOX10.',
    ],
    pitfalls: ['Não chame de carcinoma neuroendócrino só porque o Ki-67 é alto: a citologia pouco diferenciada é obrigatória.'],
    molecular: 'TP53 e RB1 inativados; APC e KRAS nos colorretais; o NET G3 tem MEN1, DAXX e ATRX.',
    sources: [WHONE, WHO],
  },
  /* ---- Ânus ---------------------------------------------------------------------- */
  {
    id: 'carcinoma-espinocelular-anal',
    name: 'Carcinoma espinocelular do canal anal',
    aka: ['anal squamous cell carcinoma', 'carcinoma basaloide anal'],
    behavior: 'maligno',
    sites: [
      { site: 'anus', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['escamoso', 'basaloide'],
    architecture: ['ninhos', 'infiltrativo'],
    features: ['queratinizacao', 'desmoplasia', 'necrose', 'mitoses-altas', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma escamoso da zona de transição anal, quase sempre associado a HPV de alto risco, com p16 em bloco; ligado a HIV, imunossupressão e sexo anal receptivo.',
    criteria: [
      'Ninhos de células escamosas atípicas, com ou sem queratinização, invadindo a partir da zona de transição.',
      'p16 em bloco (forte, difuso, nuclear e citoplasmático) como substituto de HPV de alto risco: presente em mais de 90%.',
      'Lesão intraepitelial escamosa de alto grau adjacente apoia a origem anal.',
      'Tratamento é quimiorradioterapia, não cirurgia: o diagnóstico correto evita amputação abdominoperineal.',
    ],
    markers: [
      { marker: 'p16', pct: [85, 95], note: 'em bloco; substituto de HPV de alto risco' },
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [85, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'ck20', pct: [0, 10], note: 'negativa: separa do adenocarcinoma e da doença de Paget secundária' },
      { marker: 'cdx2', pct: [0, 5] },
      { marker: 'p53', pct: [10, 30], note: 'selvagem na maioria dos HPV-associados' },
      { marker: 'pdl1', pct: [40, 60] },
      { marker: 'sox10', pct: [0, 3], note: 'negativo: separa do melanoma anorretal' },
      { marker: 'melana', pct: [0, 3] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [70, 95] },
    ],
    mimics: [
      'Melanoma anorretal: SOX10, S100 e Melan-A positivos, queratinas negativas.',
      'Adenocarcinoma retal baixo com diferenciação escamosa: CK20 e CDX2 positivos.',
      'Carcinoma basocelular da margem anal: BerEP4 positiva, p16 negativa.',
      'Doença de Paget perianal: CK7 e GCDFP-15 positivos, p63 negativo.',
      'Condiloma gigante: sem invasão destrutiva nem atipia de alto grau.',
    ],
    molecular: 'HPV 16 na maioria; PIK3CA e alterações da via PI3K. p53 mutado nos raros HPV-independentes.',
    sources: [WHO, ODZE],
  },
  {
    id: 'adenocarcinoma-anal',
    name: 'Adenocarcinoma de glândulas anais e fístula anal',
    aka: ['anal gland adenocarcinoma', 'adenocarcinoma associado a fístula anal'],
    behavior: 'maligno',
    sites: [
      { site: 'anus', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'anel-sinete'],
    architecture: ['glandulas', 'infiltrativo'],
    features: ['mucina', 'desmoplasia', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma que nasce das glândulas anais ou de uma fístula crônica, crescendo na profundidade da parede sem lesão mucosa; raro e muitas vezes diagnosticado tarde.',
    criteria: [
      'Tumor centrado na parede ou na fístula, sem displasia na mucosa retal sobrejacente.',
      'Perfil CK7 positivo com CK20 e CDX2 negativos, que o separa do adenocarcinoma retal que desceu.',
      'Doença de Crohn e fístula crônica são contexto frequente.',
      'A ausência de componente mucoso retal displásico é o argumento morfológico principal.',
    ],
    markers: [
      { marker: 'ck7', pct: [80, 95], note: 'positiva: o oposto do adenocarcinoma retal' },
      { marker: 'ck20', pct: [0, 20], note: 'negativa na maioria' },
      { marker: 'cdx2', pct: [0, 25] },
      { marker: 'satb2', pct: [0, 20] },
      { marker: 'muc5ac', pct: [40, 70] },
      { marker: 'muc2', pct: [20, 50] },
      { marker: 'p40', pct: [0, 10], note: 'negativo: separa do espinocelular' },
      { marker: 'p16', pct: [10, 30] },
      { marker: 'gcdfp15', pct: [0, 20], note: 'negativo: separa da doença de Paget perianal' },
      { marker: 'p53', pct: [40, 70] },
      { marker: 'ki67', pct: [50, 85] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma retal invadindo o canal anal: CK20, CDX2 e SATB2 positivos, com displasia mucosa.',
      'Doença de Paget perianal com adenocarcinoma subjacente: CK7 e GCDFP-15 positivos na epiderme.',
      'Fístula com metaplasia mucinosa: sem atipia nem invasão destrutiva.',
      'Adenocarcinoma de glândulas anexiais perianais: topografia cutânea.',
    ],
    sources: [WHO, ODZE],
  },
  /* ---- Mesenquimais da parede ---------------------------------------------------- */
  {
    id: 'gist',
    name: 'Tumor estromal gastrointestinal (GIST)',
    aka: ['GIST', 'gastrointestinal stromal tumour', 'tumor de células intersticiais de Cajal'],
    behavior: 'maligno',
    sites: [
      { site: 'estomago', role: 'primario', freq: 3 },
      { site: 'intestino-delgado', role: 'primario', freq: 2 },
      { site: 'colon-reto', role: 'primario', freq: 1 },
      { site: 'esofago', role: 'primario', freq: 1 },
      { site: 'peritoneo', role: 'primario', freq: 1 },
      { site: 'retroperitoneo', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 3 },
    ],
    cells: ['fusocelular', 'epitelioide'],
    architecture: ['fasciculos', 'lencois', 'nodular'],
    features: ['estroma-mixoide', 'hialinizacao', 'necrose', 'mitoses-moderadas', 'calcificacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor mesenquimal mais comum do tubo digestivo, centrado na muscular própria, fusocelular ou epitelioide, positivo para KIT e DOG1; o risco vem do tamanho, do sítio e das mitoses, não da morfologia.',
    criteria: [
      'Proliferação fusocelular (70%) ou epitelioide (20%) na parede, com vacúolos paranucleares no tipo gástrico.',
      'DOG1 ou KIT positivos: DOG1 pega também os KIT negativos com mutação de PDGFRA.',
      'Estratificação de risco obrigatória por tamanho, índice mitótico em 5 mm² e sítio (o gástrico é mais benigno que o do delgado).',
      'Mutação de KIT ou PDGFRA orienta o imatinibe; PDGFRA D842V é resistente.',
      'GIST KIT negativo, epitelioide e gástrico em jovem: pensar em deficiência de SDH e testar SDHB.',
    ],
    markers: [
      { marker: 'dog1', pct: [90, 98], note: 'positivo inclusive em boa parte dos KIT negativos' },
      { marker: 'cd117', pct: [90, 95], note: 'citoplasmático e membranoso; padrão em dot também conta' },
      { marker: 'cd34', pct: [60, 85], note: 'mais nos gástricos que nos do delgado' },
      { marker: 'sdhb', pct: [5, 10], note: 'PERDA no subgrupo SDH-deficiente (jovens, gástrico, epitelioide, multinodular)' },
      { marker: 'sma', pct: [20, 40], note: 'focal: não faz leiomioma' },
      { marker: 'desmina', pct: [0, 5], note: 'negativa: chave contra leiomioma e leiomiossarcoma' },
      { marker: 'caldesmon', pct: [40, 70], note: 'positivo também em GIST: não serve para separar de músculo liso' },
      { marker: 's100', pct: [0, 10], note: 'negativa: separa do schwannoma' },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'ae1ae3', pct: [0, 5] },
      { marker: 'nestina', pct: [80, 95] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'p53', pct: [10, 30] },
      { marker: 'alk', pct: [0, 5], note: 'negativo: separa do tumor miofibroblástico inflamatório' },
      { marker: 'betacatenina', pct: [0, 10], note: 'nuclear negativa: separa da fibromatose' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Leiomioma e leiomiossarcoma: desmina difusa, DOG1 e KIT negativos.',
      'Schwannoma gastrointestinal: S100 e SOX10 difusos, manguito linfoide periférico.',
      'Fibromatose intra-abdominal: β-catenina nuclear, KIT e DOG1 negativos.',
      'Tumor fibroide inflamatório: CD34 positivo mas DOG1 e KIT negativos, eosinófilos abundantes.',
      'Fibromixoma plexiforme: plexiforme, mixoide, SMA positivo, DOG1 negativo.',
    ],
    pitfalls: ['KIT marca mastócitos e células intersticiais de Cajal normais: o controle interno pode enganar em biópsia pequena.', 'GIST com resposta a imatinibe fica hialinizado e pode perder KIT.'],
    molecular: 'KIT (exon 11 mais comum) em 75%, PDGFRA em 10% (D842V resistente), e o grupo selvagem com SDH, NF1, BRAF e fusões de NTRK.',
    sources: [WHO, ODZE, 'Miettinen & Lasota, Arch Pathol Lab Med 2006 (estratificação de risco do GIST)'],
  },
  {
    id: 'leiomioma-gi',
    name: 'Leiomioma gastrointestinal',
    aka: ['leiomioma de esôfago', 'leiomioma da muscular da mucosa', 'gastrointestinal leiomyoma'],
    behavior: 'benigno',
    sites: [
      { site: 'esofago', role: 'primario', freq: 3 },
      { site: 'colon-reto', role: 'primario', freq: 2 },
      { site: 'estomago', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'mioide'],
    architecture: ['fasciculos'],
    features: ['hialinizacao', 'mitoses-raras', 'calcificacao'],
    ages: ['adulto'],
    summary: 'Nódulo de músculo liso maduro, o tumor mesenquimal mais comum do esôfago e da muscular da mucosa do cólon; brando, sem atipia, KIT e DOG1 negativos.',
    criteria: [
      'Fascículos entrelaçados de células fusiformes eosinofílicas com núcleo em charuto, sem atipia nem necrose.',
      'Desmina e h-caldesmon difusos com DOG1 e KIT negativos: o inverso do GIST.',
      'Localização típica: esôfago (parede) e muscular da mucosa do cólon e do reto (pólipos pequenos).',
      'Mitoses acima do mínimo, atipia ou necrose levam a leiomiossarcoma, que é raro no tubo digestivo.',
    ],
    markers: [
      { marker: 'desmina', pct: [90, 100], note: 'difusa: o achado central contra GIST' },
      { marker: 'sma', pct: [90, 100] },
      { marker: 'caldesmon', pct: [85, 100] },
      { marker: 'msa', pct: [85, 100] },
      { marker: 'cd117', pct: [0, 5], note: 'negativo (os mastócitos do estroma podem marcar)' },
      { marker: 'dog1', pct: [0, 5] },
      { marker: 'cd34', pct: [0, 15] },
      { marker: 's100', pct: [0, 5] },
      { marker: 'ae1ae3', pct: [0, 5] },
      { marker: 'ki67', pct: [0, 5] },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'er', pct: [10, 40], note: 'nos leiomiomas de mulheres' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'GIST: DOG1 e KIT positivos, desmina negativa.',
      'Schwannoma: S100 e SOX10 positivos.',
      'Leiomiossarcoma: atipia, mitoses, necrose.',
      'Fibromixoma plexiforme: arquitetura plexiforme mixoide.',
    ],
    sources: [WHO, ODZE],
  },
  {
    id: 'tumor-glomico-gastrico',
    name: 'Tumor glômico gástrico',
    aka: ['glomus tumour of the stomach'],
    behavior: 'benigno',
    sites: [{ site: 'estomago', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'mioide'],
    architecture: ['ninhos', 'nodular', 'lencois'],
    features: ['hialinizacao', 'hemorragia', 'mitoses-raras', 'vasos-espessos'],
    ages: ['adulto'],
    summary: 'Nódulo mural do antro formado por células redondas uniformes com núcleo central e limites nítidos, agrupadas ao redor de vasos dilatados; sangra e imita GIST na endoscopia.',
    criteria: [
      'Células perfeitamente redondas e monótonas ao redor de canais vasculares, com membrana basal pericelular.',
      'SMA e colágeno IV positivos com KIT, DOG1 e queratina negativos.',
      'Sinaptofisina pode ser positiva e criar confusão com tumor neuroendócrino: cromogranina negativa resolve.',
      'Malignidade é rara: exige atipia acentuada, mitoses atípicas ou tamanho grande com localização profunda.',
    ],
    markers: [
      { marker: 'sma', pct: [90, 100] },
      { marker: 'caldesmon', pct: [70, 95] },
      { marker: 'calponina', pct: [70, 95] },
      { marker: 'colageno-iv', pct: [85, 100], note: 'padrão pericelular característico' },
      { marker: 'sinaptofisina', pct: [20, 50], note: 'armadilha com NET' },
      { marker: 'cromogranina', pct: [0, 10], note: 'negativa: o desempate contra NET' },
      { marker: 'cd117', pct: [0, 5], note: 'negativo: separa do GIST' },
      { marker: 'dog1', pct: [0, 15] },
      { marker: 'cd34', pct: [10, 40] },
      { marker: 'ae1ae3', pct: [0, 5], note: 'negativa: separa do carcinoma' },
      { marker: 'desmina', pct: [0, 15] },
      { marker: 's100', pct: [0, 5] },
      { marker: 'ki67', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'GIST epitelioide: DOG1 e KIT positivos.',
      'Tumor neuroendócrino: cromogranina positiva, SMA negativa.',
      'Paraganglioma: cromogranina positiva, GATA3 positiva.',
      'Carcinoma pouco diferenciado: queratinas positivas.',
    ],
    molecular: 'Rearranjos de NOTCH2 (MIR143::NOTCH2) em parte dos casos.',
    sources: [WHO, ODZE],
  },
  {
    id: 'tumor-fibroide-inflamatorio',
    name: 'Tumor fibroide inflamatório',
    aka: ['pólipo de Vanek', 'inflammatory fibroid polyp'],
    behavior: 'benigno',
    sites: [
      { site: 'estomago', role: 'primario', freq: 2 },
      { site: 'intestino-delgado', role: 'primario', freq: 2 },
      { site: 'colon-reto', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'estreladas'],
    architecture: ['storiforme', 'infiltrativo'],
    features: ['eosinofilos', 'estroma-mixoide', 'vasos-espessos', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Lesão submucosa de células fusiformes brandas em estroma frouxo edemaciado, com eosinófilos abundantes e o padrão característico de células em casca de cebola ao redor dos vasos; causa intussuscepção no íleo.',
    criteria: [
      'Proliferação fusocelular branda na submucosa, com eosinófilos numerosos e vasos com manguito concêntrico de células.',
      'CD34 positivo com KIT e DOG1 negativos: o padrão que o separa do GIST.',
      'Mutação de PDGFRA (o mesmo gene do GIST, outro contexto).',
      'Ulceração da mucosa sobrejacente é comum e não indica malignidade.',
    ],
    markers: [
      { marker: 'cd34', pct: [70, 95], note: 'positivo, o que aproxima do GIST na leitura apressada' },
      { marker: 'cd117', pct: [0, 10], note: 'negativo: mastócitos e eosinófilos podem confundir' },
      { marker: 'dog1', pct: [0, 5] },
      { marker: 'sma', pct: [20, 50] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 's100', pct: [0, 10] },
      { marker: 'alk', pct: [0, 5], note: 'negativo: separa do tumor miofibroblástico inflamatório' },
      { marker: 'betacatenina', pct: [0, 10] },
      { marker: 'ae1ae3', pct: [0, 5] },
      { marker: 'stat6', pct: [0, 5] },
      { marker: 'ki67', pct: [0, 10] },
      { marker: 'igg4', pct: [10, 30], note: 'plasmócitos presentes, mas não é doença de IgG4' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'GIST: DOG1 e KIT positivos, sem eosinofilia.',
      'Tumor miofibroblástico inflamatório: ALK positivo.',
      'Fibromixoma plexiforme: plexiforme, SMA difuso, sem eosinófilos.',
      'Gastroenterite eosinofílica: infiltrado sem proliferação fusocelular nodular.',
    ],
    molecular: 'Mutações ativadoras de PDGFRA (exons 12, 14 e 18).',
    sources: [WHO, ODZE],
  },
  {
    id: 'fibromixoma-plexiforme',
    name: 'Fibromixoma plexiforme gástrico',
    aka: ['plexiform fibromyxoma', 'tumor fibromixoide plexiforme'],
    behavior: 'benigno',
    sites: [{ site: 'estomago', role: 'primario', freq: 1 }],
    cells: ['fusocelular', 'estreladas'],
    architecture: ['plexiforme', 'nodular', 'infiltrativo'],
    features: ['estroma-mixoide', 'mitoses-raras', 'vasos-espessos'],
    ages: ['adulto'],
    summary: 'Nódulos multilobulados plexiformes de células fusiformes brandas em matriz mixoide rica em capilares, atravessando a muscular própria do antro gástrico; benigno, mas imita GIST na imagem.',
    criteria: [
      'Arquitetura plexiforme multinodular atravessando a parede, com matriz mixoide e rede capilar delicada.',
      'Células fusiformes brandas sem atipia nem necrose, com mitoses raras.',
      'SMA positivo com KIT, DOG1, CD34 e S100 negativos: perfil de exclusão que descarta GIST e schwannoma.',
      'Curso benigno mesmo com extensão à serosa.',
    ],
    markers: [
      { marker: 'sma', pct: [80, 95] },
      { marker: 'caldesmon', pct: [30, 60] },
      { marker: 'desmina', pct: [10, 30] },
      { marker: 'cd117', pct: [0, 5], note: 'negativo: separa do GIST' },
      { marker: 'dog1', pct: [0, 5] },
      { marker: 'cd34', pct: [0, 20] },
      { marker: 's100', pct: [0, 5], note: 'negativa: separa do schwannoma e do neurofibroma' },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'ae1ae3', pct: [0, 5] },
      { marker: 'betacatenina', pct: [0, 10] },
      { marker: 'alk', pct: [0, 5] },
      { marker: 'ki67', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'GIST mixoide: DOG1 e KIT positivos.',
      'Tumor fibroide inflamatório: CD34 positivo com eosinófilos.',
      'Schwannoma: S100 e SOX10 positivos.',
      'Neurofibroma plexiforme: S100 positivo, associado a neurofibromatose tipo 1.',
    ],
    molecular: 'Rearranjos de GLI1 (MALAT1::GLI1) em parte dos casos.',
    sources: [WHO, ODZE],
  },
  {
    id: 'carcinoma-indiferenciado-swi-snf-gi',
    name: 'Carcinoma indiferenciado SWI/SNF-deficiente do tubo digestivo',
    aka: ['carcinoma rabdoide gastrointestinal', 'SMARCA4-deficient undifferentiated carcinoma', 'carcinoma indiferenciado com perda de ARID1A'],
    behavior: 'maligno',
    sites: [
      { site: 'estomago', role: 'primario', freq: 1 },
      { site: 'colon-reto', role: 'primario', freq: 1 },
      { site: 'intestino-delgado', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['rabdoide', 'epitelioide', 'pleomorfico'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['idoso'],
    summary: 'Carcinoma sem diferenciação glandular, em lençóis discoesos de células grandes rabdoides com nucléolo, que perde um componente do complexo SWI/SNF (SMARCA4, SMARCB1 ou ARID1A) e tem curso fulminante.',
    criteria: [
      'Morfologia indiferenciada ou rabdoide, com queratina muitas vezes apenas focal.',
      'Perda de expressão nuclear de BRG1 (SMARCA4), INI1 (SMARCB1) ou ARID1A, com controle interno positivo.',
      'Muitas vezes há um componente de adenocarcinoma convencional em outro bloco: procure antes de chamar de sarcoma.',
      'Associação frequente com deficiência de MMR quando a perda é de ARID1A.',
    ],
    markers: [
      { marker: 'brg1', pct: [40, 70], note: 'PERDA nuclear; a alteração mais comum neste grupo' },
      { marker: 'ini1', pct: [10, 30], note: 'PERDA numa minoria' },
      { marker: 'arid1a', pct: [30, 60], note: 'PERDA; associada a MMR deficiente' },
      { marker: 'ae1ae3', pct: [50, 80], note: 'focal e fraca: a negatividade não exclui carcinoma' },
      { marker: 'cam52', pct: [40, 70] },
      { marker: 'claudina4', pct: [30, 60] },
      { marker: 'cdx2', pct: [10, 30], note: 'em geral perdido' },
      { marker: 'satb2', pct: [10, 30] },
      { marker: 'ecaderina', pct: [20, 50] },
      { marker: 'mlh1', pct: [20, 50] },
      { marker: 'cd45', pct: 0, note: 'negativo: separa do linfoma' },
      { marker: 'sox10', pct: [0, 5], note: 'negativo: separa do melanoma' },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'p53', pct: [30, 60] },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Linfoma de grandes células: CD45 positivo.',
      'Melanoma metastático: SOX10 e Melan-A positivos.',
      'Sarcoma pleomórfico: queratinas negativas em painel amplo e SWI/SNF intacto.',
      'Carcinoma neuroendócrino de grandes células: INSM1 e sinaptofisina difusas.',
      'Adenocarcinoma pouco diferenciado convencional: SWI/SNF preservado.',
    ],
    pitfalls: ['Sem testar SWI/SNF, esses tumores viram "carcinoma indiferenciado" ou "sarcoma": a perda tem valor diagnóstico e abre discussão sobre imunoterapia.'],
    molecular: 'Inativação de SMARCA4, SMARCB1 ou ARID1A; carga mutacional alta quando há MSI.',
    sources: [WHO, ODZE],
  },
]
