/* ==========================================================================
   headneck.ts — cabeça e pescoço mucoso e odontogênico.

   Duas perguntas mandam aqui. A primeira é de etiologia: p16 em bloco na
   orofaringe (com HPV confirmado) e EBER na nasofaringe mudam estadiamento e
   prognóstico, não só a curiosidade. A segunda é a dos tumores sinonasais
   indiferenciados, um grupo que só se separa por marcador: SMARCB1, SMARCA4,
   NUT, IDH2, e o que sobra depois deles.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Head and Neck Tumours, 2022; Thompson & Bishop, Head and
   Neck Pathology, 3ª ed.; séries de Am J Surg Pathol e Head Neck Pathol).
   As fontes estão como referência de texto: as séries não foram abertas uma
   a uma, e o clone e a plataforma mudam os números.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Head and Neck Tumours (2022)'
const THOMPSON = 'Thompson & Bishop, Head and Neck Pathology, 3ª ed. (Elsevier)'
const BISHOP = 'Bishop, "Newly described tumor entities in sinonasal tract pathology", Head Neck Pathol'

export const headneck: Tumor[] = [
  {
    id: 'cec-oral',
    name: 'Carcinoma de células escamosas oral convencional',
    aka: ['carcinoma epidermoide oral', 'CEC de língua, assoalho e gengiva'],
    behavior: 'maligno',
    sites: [
      { site: 'boca', role: 'primario', freq: 3 },
      { site: 'laringe', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['escamoso', 'epitelioide'],
    architecture: ['ninhos', 'infiltrativo'],
    features: ['queratinizacao', 'desmoplasia', 'perineural', 'mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Ninhos infiltrativos de epitélio escamoso com queratinização e desmoplasia, em fumante e etilista, quase sempre com displasia na mucosa adjacente; a imuno serve para confirmar linhagem escamosa e para separar do HPV-associado da orofaringe.',
    criteria: [
      'Invasão do estroma por ninhos escamosos, com resposta desmoplásica ou inflamatória.',
      'Diferenciação escamosa: pontes intercelulares, queratinização ou p40 difuso.',
      'Profundidade de invasão medida a partir da membrana basal da mucosa adjacente normal: é ela, e não a espessura, que estadia o T na boca.',
      'Invasão perineural e linfovascular devem ser relatadas.',
      'Displasia ou carcinoma in situ adjacente apoia origem primária contra metástase.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck903', pct: [90, 100] },
      { marker: 'ck17', pct: [70, 90] },
      { marker: 'p16', pct: [5, 20], note: 'positividade em bloco é rara fora da orofaringe e não prova HPV na boca' },
      { marker: 'p53', pct: [50, 70], note: 'padrão aberrante frequente, ligado a TP53 mutado' },
      { marker: 'ck7', pct: [5, 15] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'cdx2', pct: 0 },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ebv', pct: [0, 5] },
      { marker: 'ki67', pct: [70, 90] },
    ],
    mimics: [
      'Carcinoma de orofaringe HPV-associado: não queratinizante, p16 em bloco, HPV confirmado.',
      'Carcinoma nasofaríngeo: sincicial, EBER positivo, sem queratinização.',
      'Hiperplasia pseudoepiteliomatosa: sem atipia, sem desmoplasia, base regular.',
      'Melanoma mucoso amelanótico: SOX10 e S100 positivos, queratina negativa.',
    ],
    pitfalls: [
      'Carcinoma escamoso pouco diferenciado pode perder queratinas de alto peso; p40 costuma resistir.',
      'p16 positivo focal ou citoplasmático não é "HPV positivo": só conta o padrão em bloco, nuclear e citoplasmático, em mais de 70% das células.',
    ],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'cec-orofaringe-hpv',
    name: 'Carcinoma de orofaringe HPV-associado',
    aka: ['carcinoma escamoso não queratinizante p16 positivo', 'HPV-associated oropharyngeal carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'boca', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['escamoso', 'basaloide', 'epitelioide'],
    architecture: ['ninhos', 'lencois'],
    features: ['linfoide', 'necrose', 'mitoses-altas', 'corpos-apoptoticos', 'cistico'],
    ages: ['jovem', 'adulto'],
    summary: 'Carcinoma de tonsila ou base de língua, não queratinizante, em ninhos lobulados dentro de tecido linfoide, que se apresenta como metástase cística no pescoço em adulto sem grande história de tabagismo; p16 em bloco com HPV de alto risco confirmado.',
    criteria: [
      'Localização orofaríngea: tonsila palatina, base de língua ou tecido linfoide de Waldeyer.',
      'p16 em bloco (nuclear e citoplasmático, forte, em mais de 70% das células) é o substituto aceito, mas exige contexto orofaríngeo.',
      'Confirmação por ISH de RNA de HPV de alto risco quando o p16 é o único dado e a decisão de estadiamento depende disso.',
      'Morfologia não queratinizante, com bordas de ninho lisas e apoptose abundante; a queratinização não exclui.',
      'Estadiamento próprio (AJCC 8ª ed.), diferente do HPV-negativo.',
    ],
    markers: [
      { marker: 'p16', pct: [95, 100], note: 'em bloco; é o critério de entrada' },
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p53', pct: [0, 10], note: 'padrão selvagem: TP53 íntegro, ao contrário do HPV-negativo' },
      { marker: 'rb1', pct: [70, 90], note: 'redução da expressão pela E7; pouco usada na prática' },
      { marker: 'ebv', pct: [0, 5] },
      { marker: 'ck7', pct: [5, 20] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'sinaptofisina', pct: [0, 5], note: 'quando difusa, pense em carcinoma neuroendócrino HPV-associado, que é agressivo' },
      { marker: 'ki67', pct: [80, 95] },
    ],
    mimics: [
      'Metástase cística no pescoço interpretada como cisto branquial: qualquer cisto cervical em adulto exige p16 e busca de primário na tonsila.',
      'Carcinoma nasofaríngeo: EBER positivo, p16 negativo.',
      'Carcinoma escamoso basaloide HPV-negativo: p53 aberrante, p16 negativo.',
    ],
    pitfalls: [
      'Carcinoma neuroendócrino de pequenas células HPV-associado é p16 em bloco e comporta-se como pequenas células: procure sinaptofisina e INSM1 antes de assumir escamoso.',
      'p16 em bloco fora da orofaringe (laringe, seios, boca) não autoriza o diagnóstico de HPV-associado.',
    ],
    molecular: 'HPV de alto risco transcricionalmente ativo (E6/E7), sobretudo genótipo 16.',
    sources: [WHO, THOMPSON, 'AJCC Cancer Staging Manual, 8ª ed., capítulo de orofaringe HPV-mediado'],
  },
  {
    id: 'carcinoma-nasofaringeo',
    name: 'Carcinoma nasofaríngeo',
    aka: ['carcinoma indiferenciado tipo nasofaríngeo', 'linfoepitelioma', 'nasopharyngeal carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['sincicial', 'epitelioide', 'escamoso'],
    architecture: ['lencois', 'ninhos'],
    features: ['linfoide', 'nucleolo', 'mitoses-altas'],
    ages: ['jovem', 'adulto'],
    summary: 'Lençóis de células sinciciais de limites indistintos, núcleo vesiculoso e nucléolo grande, afogados em linfócitos e plasmócitos; EBER positivo em praticamente todos os casos indiferenciados, e muitas vezes o primeiro material é um linfonodo cervical.',
    criteria: [
      'Célula sincicial com nucléolo eosinofílico proeminente, em fundo linfoplasmocitário denso.',
      'Confirmação de linhagem epitelial por pan-queratina ou p40, que desfaz a impressão de linfoma.',
      'EBER por hibridização in situ positivo no subtipo indiferenciado e no não queratinizante diferenciado.',
      'O subtipo queratinizante é o único que pode ser EBER negativo, e é o de pior resposta à radioterapia.',
      'Metástase cervical alta com este padrão obriga a biopsiar a nasofaringe.',
    ],
    markers: [
      { marker: 'ebv', pct: [95, 100], note: 'EBER-ISH; o LMP1 é bem menos sensível' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p40', pct: [85, 95] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'cam52', pct: [80, 95] },
      { marker: 'p16', pct: [10, 25], note: 'pode ser positivo sem HPV; não use aqui' },
      { marker: 'cd45', pct: 0, note: 'o negativo que exclui linfoma' },
      { marker: 'cd30', pct: [0, 5] },
      { marker: 'cd20', pct: 0 },
      { marker: 'cd3', pct: 0 },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'melana', pct: 0 },
      { marker: 'pdl1', pct: [60, 90], note: 'preditivo, não diagnóstico' },
      { marker: 'ki67', pct: [70, 95] },
    ],
    mimics: [
      'Linfoma difuso de grandes células B: CD45 e CD20 positivos, queratina negativa.',
      'Melanoma mucoso: SOX10 e S100 positivos.',
      'Carcinoma linfoepitelial de outros sítios (salivar, pulmão, estômago): mesma imuno, o sítio é que decide.',
      'Hiperplasia linfoide da nasofaringe: sem célula sincicial atípica, queratina só no epitélio de superfície.',
    ],
    pitfalls: ['A queratina pode ser fraca e focal no material esmagado de linfonodo; repita com CAM5.2 e p40 antes de assumir linfoma.'],
    molecular: 'Vírus Epstein-Barr clonal; DNA viral plasmático serve de seguimento.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'papiloma-invertido',
    name: 'Papiloma sinonasal invertido',
    aka: ['papiloma schneideriano invertido', 'inverted sinonasal papilloma'],
    behavior: 'benigno',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 3 }],
    cells: ['escamoso', 'epitelioide'],
    architecture: ['infiltrativo', 'ninhos', 'cistico'],
    features: ['mitoses-raras', 'eosinofilos'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Epitélio escamoso e respiratório espesso que cresce invertido para dentro do estroma em ninhos de contorno liso, com microcistos cheios de neutrófilos; unilateral, recorrente, e com risco de carcinoma escamoso ao longo do tempo.',
    criteria: [
      'Crescimento endofítico do epitélio para dentro do estroma, com membrana basal íntegra e contornos arredondados.',
      'Epitélio escamoso ou transicional espessado, com microabscessos intraepiteliais.',
      'Ausência de atipia significativa e de desmoplasia: a presença de qualquer uma delas obriga a procurar carcinoma.',
      'Unilateralidade; lesão bilateral favorece pólipo inflamatório.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ck7', pct: [40, 70], note: 'no componente respiratório de superfície' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p16', pct: [5, 15] },
      { marker: 'p53', pct: [0, 10], note: 'aberrante sugere transformação maligna' },
      { marker: 'ki67', pct: [10, 30], note: 'basal e parabasal; difuso e alto favorece carcinoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma escamoso bem diferenciado: atipia, desmoplasia, mitoses em camadas altas.',
      'Papiloma oncocítico: epitélio colunar multicamadas oncocítico, mesma arquitetura invertida.',
      'Pólipo inflamatório: sem espessamento epitelial, estroma edematoso com eosinófilos.',
    ],
    molecular: 'Mutações de EGFR (exon 20) na maioria; KRAS mutado aparece nos que carcinomatizam.',
    sources: [WHO, THOMPSON, BISHOP],
  },
  {
    id: 'adenocarcinoma-intestinal-sinonasal',
    name: 'Adenocarcinoma sinonasal de tipo intestinal',
    aka: ['ITAC', 'intestinal-type sinonasal adenocarcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'anel-sinete'],
    architecture: ['glandulas', 'papilar', 'cribriforme'],
    features: ['mucina', 'necrose', 'mitoses-altas', 'desmoplasia'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Adenocarcinoma do etmoide que reproduz mucosa intestinal, com caliciformes e até células de Paneth, em marceneiro ou trabalhador de couro exposto a pó de madeira; imunofenótipo indistinguível de metástase colorretal, de modo que a exclusão clínica é obrigatória.',
    criteria: [
      'Epitélio de tipo intestinal: colunar com caliciformes, borda em escova, às vezes muscular da mucosa rudimentar.',
      'Localização em etmoide ou fenda olfatória; história ocupacional de pó de madeira ou couro apoia.',
      'Exclusão de adenocarcinoma colorretal metastático por colonoscopia e imagem: a imuno não separa.',
      'Graduação por padrão (papilar, colônico, sólido, mucinoso, misto) tem valor prognóstico.',
    ],
    markers: [
      { marker: 'cdx2', pct: [90, 100] },
      { marker: 'ck20', pct: [85, 95] },
      { marker: 'vilina', pct: [80, 95] },
      { marker: 'muc2', pct: [70, 90] },
      { marker: 'ck7', pct: [40, 60], note: 'mais frequente que no colorretal verdadeiro, mas não confiável' },
      { marker: 'satb2', pct: [30, 60], note: 'não separa do colorretal metastático' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p53', pct: [40, 60] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'p40', pct: [0, 5] },
      { marker: 's100', pct: [0, 5] },
      { marker: 'ki67', pct: [50, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma colorretal metastático: imuno idêntica; só a clínica separa.',
      'Adenocarcinoma sinonasal de tipo não intestinal: túbulos uniformes, CK7 positivo, CDX2 e CK20 negativos.',
      'Adenocarcinoma de baixo grau de glândulas seromucinosas: bem delimitado, sem necrose.',
    ],
    pitfalls: ['CDX2 e CK20 positivos num tumor nasal não significam metástase: o primário sinonasal tem o mesmo perfil.'],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'snuc',
    name: 'Carcinoma sinonasal indiferenciado (SNUC)',
    aka: ['sinonasal undifferentiated carcinoma', 'SNUC IDH2-mutante'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'pequenas-redondas', 'pleomorfico'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma de células médias a grandes em lençóis, com necrose extensa, altíssimo índice mitótico e nenhuma diferenciação escamosa ou glandular; é diagnóstico de exclusão depois que SMARCB1, SMARCA4, NUT, EBER e HPV foram descartados, e a maioria carrega mutação de IDH2.',
    criteria: [
      'Carcinoma de alto grau sem diferenciação escamosa, glandular nem neuroendócrina evidente.',
      'Queratina positiva, que o separa de linfoma, melanoma, rabdomiossarcoma e neuroblastoma olfatório.',
      'INI1 e BRG1 retidos, NUT negativo, EBER negativo e HPV negativo: sem isso o diagnóstico não se sustenta.',
      'Sinaptofisina focal é aceita; positividade difusa com cromogranina reclassifica como carcinoma neuroendócrino.',
      'Mutação de IDH2 (R172) apoia fortemente e hoje define a maioria dos casos.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'ini1', pct: 0, note: 'retido por definição; a perda define outra entidade' },
      { marker: 'brg1', pct: 0, note: 'retido por definição' },
      { marker: 'nut', pct: 0 },
      { marker: 'ebv', pct: 0 },
      { marker: 'p16', pct: [10, 30], note: 'sem HPV; o p16 aqui é ruído' },
      { marker: 'p40', pct: [0, 10], note: 'focal no máximo; difuso é carcinoma escamoso' },
      { marker: 'sinaptofisina', pct: [20, 40], note: 'focal e aceita' },
      { marker: 'cromogranina', pct: [0, 10] },
      { marker: 'insm1', pct: [10, 30] },
      { marker: 's100', pct: [0, 10] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'desmina', pct: 0 },
      { marker: 'p53', pct: [30, 50] },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Carcinoma sinonasal SMARCB1-deficiente: INI1 perdido.',
      'Carcinoma NUT: NUT nuclear em pontilhado, diferenciação escamosa abrupta.',
      'Neuroblastoma olfatório de alto grau: S100 sustentacular, queratina negativa ou focal.',
      'Carcinoma neuroendócrino de pequenas células: sinaptofisina e INSM1 difusos.',
      'Melanoma mucoso e rabdomiossarcoma alveolar: SOX10 ou desmina/miogenina positivos.',
    ],
    molecular: 'Mutação de IDH2 R172 na maioria; o anticorpo IDH1 R132H não a detecta.',
    sources: [WHO, BISHOP, 'Dogan et al., Mod Pathol (2019), IDH2 em carcinomas sinonasais indiferenciados'],
  },
  {
    id: 'carcinoma-smarcb1-sinonasal',
    name: 'Carcinoma sinonasal SMARCB1-deficiente',
    aka: ['carcinoma sinonasal INI1-deficiente', 'SMARCB1-deficient sinonasal carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'rabdoide', 'basaloide', 'pequenas-redondas'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma sinonasal de células basaloides ou rabdoides monótonas em lençóis, morfologicamente parecido com SNUC, definido pela perda completa de INI1 no núcleo com controle interno preservado; curso agressivo e resposta pobre.',
    criteria: [
      'Perda total da expressão nuclear de INI1 (SMARCB1) nas células tumorais, com endotélio e linfócitos retidos como controle interno.',
      'Queratina positiva, o que o separa de tumor rabdoide extrarrenal e de sarcoma epitelioide.',
      'Morfologia basaloide ou rabdoide, às vezes com diferenciação glandular ou escamosa focal (variante adenocarcinoma-símile).',
      'NUT negativo: o carcinoma NUT também pode ser basaloide.',
    ],
    markers: [
      { marker: 'ini1', pct: [95, 100], note: 'o positivo aqui é a perda; é o critério definidor' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'p63', pct: [30, 60] },
      { marker: 'p40', pct: [10, 40], note: 'menos frequente que p63' },
      { marker: 'ck56', pct: [20, 50] },
      { marker: 'nut', pct: 0 },
      { marker: 'brg1', pct: 0, note: 'retido; a perda define o SMARCA4-deficiente' },
      { marker: 'sinaptofisina', pct: [10, 30], note: 'focal' },
      { marker: 'cromogranina', pct: [0, 10] },
      { marker: 's100', pct: [0, 15] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'ki67', pct: [60, 90] },
    ],
    mimics: [
      'SNUC: INI1 retido.',
      'Tumor rabdoide extrarrenal: INI1 também perdido, mas queratina fraca ou negativa e ocorre em criança.',
      'Carcinoma NUT: NUT positivo, INI1 retido.',
      'Melanoma mucoso: SOX10 positivo.',
    ],
    molecular: 'Inativação bialélica de SMARCB1 (deleção ou mutação).',
    sources: [WHO, BISHOP, 'Agaimy et al., Am J Surg Pathol, carcinomas sinonasais SMARCB1-deficientes'],
  },
  {
    id: 'carcinoma-nut',
    name: 'Carcinoma NUT',
    aka: ['carcinoma da linha média NUT', 'NUT carcinoma', 'NMC'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 1 },
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'primario', freq: 1 },
      { site: 'boca', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'basaloide', 'pequenas-redondas'],
    architecture: ['lencois', 'ninhos'],
    features: ['necrose', 'mitoses-altas', 'queratinizacao'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Carcinoma indiferenciado de células monótonas médias com queratinização abrupta no meio do lençol indiferenciado, em jovem, na linha média do corpo; o anticorpo NUT dá marcação nuclear em pontilhado e fecha o diagnóstico, cuja sobrevida mediana é de poucos meses.',
    criteria: [
      'Marcação nuclear de NUT em mais de 50% das células, tipicamente em pontilhado grosseiro.',
      'Morfologia de carcinoma indiferenciado com focos de queratinização abrupta (nem sempre presentes).',
      'Queratina positiva; confirmação molecular do rearranjo NUTM1 quando a imuno é duvidosa.',
      'Idade jovem e sítio de linha média apoiam, mas não são obrigatórios.',
    ],
    markers: [
      { marker: 'nut', pct: [95, 100], note: 'critério definidor; clone C52B1' },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'p63', pct: [80, 95] },
      { marker: 'p40', pct: [70, 90] },
      { marker: 'ck56', pct: [50, 80] },
      { marker: 'cd34', pct: [20, 50], note: 'positividade curiosa e clássica neste tumor' },
      { marker: 'ini1', pct: 0, note: 'retido' },
      { marker: 'p16', pct: [20, 40] },
      { marker: 'ebv', pct: 0 },
      { marker: 'sinaptofisina', pct: [10, 25] },
      { marker: 'cd45', pct: 0 },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Carcinoma escamoso pouco diferenciado: NUT negativo.',
      'SNUC e carcinoma SMARCB1-deficiente: NUT negativo, INI1 perdido no segundo.',
      'Tumores de células redondas (Ewing, rabdomiossarcoma): queratina negativa.',
    ],
    pitfalls: ['Marcação NUT fraca e difusa sem pontilhado pode ser inespecífica; exija o padrão pontilhado ou confirme por FISH.'],
    molecular: 'Fusão NUTM1, mais comum BRD4::NUTM1; também BRD3 e NSD3.',
    sources: [WHO, BISHOP, 'French, Annu Rev Pathol, carcinoma NUT'],
  },
  {
    id: 'neuroblastoma-olfatorio',
    name: 'Neuroblastoma olfatório',
    aka: ['estesioneuroblastoma', 'olfactory neuroblastoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'encefalo', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino'],
    architecture: ['ninhos', 'lencois', 'rosetas'],
    features: ['calcificacao', 'necrose', 'mitoses-raras', 'hemorragia'],
    ages: ['jovem', 'adulto', 'idoso'],
    summary: 'Tumor da fenda olfatória em lóbulos separados por estroma vascularizado, com células pequenas em fundo neurofibrilar, rosetas de Homer Wright e, no baixo grau, mitoses escassas; as células sustentaculares S100 positivas na periferia dos ninhos são a assinatura.',
    criteria: [
      'Localização na fenda olfatória ou lâmina cribriforme, com massa dando-se em ampulheta pela base do crânio.',
      'Arquitetura lobular com matriz neurofibrilar de fundo.',
      'Sinaptofisina e cromogranina positivas com queratina negativa ou apenas focal.',
      'Células sustentaculares S100 positivas dispostas na periferia dos lóbulos (perdem-se nos graus altos de Hyams).',
      'Graduação de Hyams (I a IV) por arquitetura, matriz, pleomorfismo, mitoses, necrose e rosetas.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [90, 100] },
      { marker: 'cromogranina', pct: [70, 90] },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 's100', pct: [80, 95], pattern: 'N', note: 'só nas sustentaculares periféricas; difusa nas células tumorais fala contra' },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'nse', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [0, 15], note: 'focal quando presente; difusa reclassifica como carcinoma neuroendócrino' },
      { marker: 'nkx22', pct: [20, 40], note: 'pode confundir com Ewing' },
      { marker: 'cd99', pct: [10, 30], note: 'raramente membranoso forte' },
      { marker: 'p40', pct: 0 },
      { marker: 'cd45', pct: 0 },
      { marker: 'desmina', pct: 0 },
      { marker: 'sox10', pct: [10, 30], note: 'nas sustentaculares' },
      { marker: 'ki67', pct: [10, 50], note: 'sobe com o grau de Hyams' },
    ],
    mimics: [
      'Carcinoma neuroendócrino sinonasal: queratina difusa, sem sustentaculares, mitoses e necrose muito maiores.',
      'Ewing sinonasal: CD99 membranoso difuso, NKX2.2, fusão EWSR1.',
      'Rabdomiossarcoma alveolar: desmina e miogenina.',
      'Melanoma mucoso: SOX10 e HMB-45 nas próprias células tumorais.',
      'Adenoma pituitário invasivo do seio esfenoidal: hormônios hipofisários, PIT1/TPIT/SF-1.',
    ],
    sources: [WHO, THOMPSON, 'Hyams, Tumors of the upper respiratory tract and ear (AFIP), graduação'],
  },
  {
    id: 'melanoma-mucoso',
    name: 'Melanoma mucoso de cabeça e pescoço',
    aka: ['melanoma sinonasal', 'melanoma oral', 'mucosal melanoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'fusocelular', 'pleomorfico', 'plasmocitoide', 'pequenas-redondas'],
    architecture: ['lencois', 'ninhos'],
    features: ['melanina', 'necrose', 'mitoses-altas', 'nucleolo', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Melanoma de mucosa nasal ou oral, com frequência amelanótico, que imita carcinoma, linfoma e sarcoma na mesma lâmina; prognóstico muito pior que o cutâneo, sem Breslow aplicável, e com perfil molecular distinto (KIT em vez de BRAF).',
    criteria: [
      'Proliferação melanocítica maligna na mucosa, com componente juncional ou melanose atípica adjacente quando presente.',
      'Confirmação por dois marcadores melanocíticos, sendo SOX10 ou S100 um deles.',
      'Exclusão de carcinoma (pan-queratina), linfoma (CD45) e sarcoma de células redondas.',
      'A pigmentação pode faltar em metade dos casos e não é critério.',
    ],
    markers: [
      { marker: 's100', pct: [90, 100] },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'melana', pct: [70, 90] },
      { marker: 'hmb45', pct: [70, 90] },
      { marker: 'mitf', pct: [70, 90] },
      { marker: 'tirosinase', pct: [60, 85] },
      { marker: 'prame', pct: [60, 85] },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [0, 5], note: 'positividade focal é armadilha descrita' },
      { marker: 'p40', pct: 0 },
      { marker: 'cd45', pct: 0 },
      { marker: 'sinaptofisina', pct: [0, 10] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'cd117', pct: [30, 60], note: 'reflete a frequência de alterações de KIT nos mucosos' },
      { marker: 'brafv600e', pct: [0, 10], note: 'bem menos frequente que no melanoma cutâneo' },
      { marker: 'ki67', pct: [50, 90] },
    ],
    mimics: [
      'SNUC e carcinoma indiferenciado: queratina positiva, SOX10 negativo.',
      'Neuroblastoma olfatório: S100 só sustentacular, sinaptofisina difusa.',
      'Plasmocitoma: CD138 e restrição de cadeia leve.',
      'Rabdomiossarcoma alveolar: desmina e miogenina.',
    ],
    pitfalls: ['O melanoma mucoso pode ser HMB-45 e Melan-A negativos quando fusocelular; SOX10 é o mais confiável.'],
    molecular: 'Mutação ou amplificação de KIT em parte; BRAF V600E é incomum, ao contrário do cutâneo.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'teratocarcinossarcoma-sinonasal',
    name: 'Teratocarcinossarcoma sinonasal',
    aka: ['sinonasal teratocarcinosarcoma', 'SNTCS'],
    behavior: 'maligno',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'fusocelular', 'blastematoso', 'escamoso', 'glandular'],
    architecture: ['ninhos', 'glandulas', 'fasciculos'],
    features: ['necrose', 'mitoses-altas', 'estriacoes', 'condroide', 'osteoide'],
    ages: ['adulto'],
    sex: 'm',
    summary: 'Tumor sinonasal raro que mistura, num só bloco, epitélio escamoso e glandular imaturo, estroma sarcomatoso, ilhas de cartilagem ou osso e, quase sempre, ninhos de células com citoplasma claro glicogenado de aspecto fetal; a mistura é o diagnóstico.',
    criteria: [
      'Presença simultânea de componente epitelial (escamoso e glandular), mesenquimal maligno e neuroepitelial imaturo.',
      'Ninhos de epitélio escamoso fetal com citoplasma claro rico em glicogênio são muito característicos.',
      'Ausência de teratoma maduro organoide e de germinativo (SALL4 e OCT4 negativos).',
      'Componente rabdomioblástico é comum e não exclui.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [90, 100], note: 'só no componente epitelial' },
      { marker: 'p40', pct: [70, 90], note: 'no componente escamoso' },
      { marker: 'sinaptofisina', pct: [60, 85], note: 'no componente neuroepitelial' },
      { marker: 'desmina', pct: [50, 80], note: 'no componente rabdomioblástico' },
      { marker: 'miogenina', pct: [40, 70] },
      { marker: 's100', pct: [40, 70], note: 'cartilagem e neural' },
      { marker: 'betacatenina', pct: [70, 95], note: 'nuclear no epitélio fetal e no estroma; reflete alteração de CTNNB1' },
      { marker: 'sall4', pct: [0, 20] },
      { marker: 'oct4', pct: 0 },
      { marker: 'afp', pct: [0, 20] },
      { marker: 'ini1', pct: 0, note: 'retido' },
      { marker: 'ki67', pct: [50, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Teratoma imaturo: organoide, sem componente carcinomatoso franco, em criança.',
      'Carcinossarcoma: sem componente neuroepitelial nem epitélio fetal.',
      'Rabdomiossarcoma: puro, sem epitélio maligno.',
    ],
    molecular: 'Alterações de CTNNB1 (β-catenina) na maioria dos casos estudados.',
    sources: [WHO, BISHOP],
  },
  {
    id: 'sarcoma-bifenotipico-sinonasal',
    name: 'Sarcoma bifenotípico sinonasal',
    aka: ['biphenotypic sinonasal sarcoma', 'sarcoma de baixo grau com diferenciação neural e miogênica'],
    behavior: 'intermediario',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 1 }],
    cells: ['fusocelular'],
    architecture: ['fasciculos', 'infiltrativo', 'hemangiopericitoma'],
    features: ['mitoses-raras', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Sarcoma sinonasal de baixo grau, em fascículos de células fusiformes monótonas que envolvem e arrastam consigo glândulas respiratórias de superfície hiperplásicas; o achado que o define é a coexpressão de S100 com actina de músculo liso, sem SOX10.',
    criteria: [
      'Proliferação fusocelular infiltrativa, monótona, com mitoses escassas e sem necrose.',
      'Glândulas respiratórias aprisionadas dentro do tumor, muitas vezes com metaplasia escamosa.',
      'Coexpressão de S100 (difusa) e marcador miogênico (SMA ou actina) nas mesmas células.',
      'SOX10 negativo: é o que o separa de schwannoma e de MPNST.',
      'Confirmação por fusão PAX3, mais comum PAX3::MAML3.',
    ],
    markers: [
      { marker: 's100', pct: [90, 100], note: 'difusa, ao contrário do padrão sustentacular' },
      { marker: 'sox10', pct: [0, 5], note: 'o negativo é critério' },
      { marker: 'sma', pct: [80, 95] },
      { marker: 'msa', pct: [60, 85] },
      { marker: 'calponina', pct: [50, 80] },
      { marker: 'betacatenina', pct: [50, 80], pattern: 'N' },
      { marker: 'desmina', pct: [10, 30] },
      { marker: 'miogenina', pct: [10, 30], note: 'focal, quando há diferenciação rabdomioblástica' },
      { marker: 'myod1', pct: [10, 30] },
      { marker: 'cd34', pct: [10, 30] },
      { marker: 'stat6', pct: 0 },
      { marker: 'ae1ae3', pct: [0, 5], note: 'só nas glândulas aprisionadas' },
      { marker: 'ki67', pct: [5, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor fibroso solitário: STAT6 nuclear, S100 negativo.',
      'Schwannoma celular: SOX10 positivo, SMA negativa.',
      'Fibrossarcoma e MPNST de baixo grau: sem coexpressão, H3K27me3 pode estar perdido no MPNST.',
      'Fasciite nodular: USP6, mais frouxa e com mitoses fáceis.',
    ],
    molecular: 'Fusão PAX3::MAML3 na maioria; também PAX3::NCOA1 e outros parceiros.',
    sources: [WHO, BISHOP, 'Lewis et al., Am J Surg Pathol (2012), sarcoma bifenotípico sinonasal'],
  },
  {
    id: 'angiofibroma-nasofaringeo',
    name: 'Angiofibroma nasofaríngeo juvenil',
    aka: ['angiofibroma juvenil', 'juvenile nasopharyngeal angiofibroma'],
    behavior: 'benigno',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 2 }],
    cells: ['fusocelular', 'estreladas', 'vasoformativo'],
    architecture: ['infiltrativo'],
    features: ['hemorragia', 'hialinizacao', 'mitoses-raras', 'vasos-espessos'],
    ages: ['crianca', 'jovem'],
    sex: 'm',
    summary: 'Massa vascular do teto da nasofaringe em adolescente do sexo masculino com epistaxe de repetição, feita de vasos em fenda sem camada muscular completa dentro de estroma fibroso com células estreladas; a β-catenina nuclear no estroma confirma quando o material é fragmentado.',
    criteria: [
      'Adolescente do sexo masculino com massa no forame esfenopalatino e epistaxe.',
      'Vasos de calibre variável, em fenda ou estrelados, com parede muscular ausente ou incompleta.',
      'Estroma fibroso com células estreladas e fusiformes, sem atipia nem mitoses.',
      'Biópsia é evitada pelo risco de sangramento; o diagnóstico costuma ser da peça pós-embolização.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [70, 95], pattern: 'N', note: 'nuclear nas células estromais, não nos vasos' },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'cd34', pct: [90, 100], note: 'só o endotélio' },
      { marker: 'cd31', pct: [90, 100], note: 'só o endotélio' },
      { marker: 'ar', pct: [50, 80], note: 'receptor de androgênio no estroma; explica a idade e o sexo' },
      { marker: 'sma', pct: [30, 60], note: 'parede vascular incompleta' },
      { marker: 's100', pct: [0, 5] },
      { marker: 'stat6', pct: 0 },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor fibroso solitário: STAT6 nuclear.',
      'Pólipo antrocoanal com estroma atípico: sem o padrão vascular, em outro sítio.',
      'Angiofibroma-símile pós-traumático: sem β-catenina nuclear, sem o contexto.',
    ],
    molecular: 'Mutações de CTNNB1 no estroma; associação com polipose adenomatosa familiar.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'ameloblastoma',
    name: 'Ameloblastoma',
    aka: ['ameloblastoma convencional', 'ameloblastoma sólido multicístico'],
    behavior: 'intermediario',
    sites: [{ site: 'maxilares', role: 'primario', freq: 3 }],
    cells: ['basaloide', 'epitelioide', 'escamoso'],
    architecture: ['ninhos', 'palicada', 'plexiforme', 'cistico'],
    features: ['mitoses-raras', 'estroma-mixoide'],
    ages: ['jovem', 'adulto'],
    summary: 'Tumor odontogênico epitelial da mandíbula posterior, em ilhas e cordões com camada basal colunar em paliçada de núcleos invertidos e polarização reversa, envolvendo um centro frouxo de retículo estrelado; localmente agressivo e recidivante, mas benigno.',
    criteria: [
      'Camada periférica de células colunares altas com núcleo polarizado para longe da membrana basal (polarização reversa) e vacuolização subnuclear.',
      'Centro de células frouxamente arranjadas, tipo retículo estrelado.',
      'Padrões folicular, plexiforme, acantomatoso, granular, desmoplásico ou basaloide, sem valor prognóstico entre si.',
      'Radiolucidez multiloculada em favo de mel na mandíbula posterior.',
      'BRAF V600E presente na maioria dos mandibulares e útil quando se cogita terapia-alvo.',
    ],
    markers: [
      { marker: 'brafv600e', pct: [60, 85], note: 'mais frequente nos mandibulares; os maxilares tendem a SMO mutado' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [70, 90] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'calretinina', pct: [50, 80], note: 'nas células do retículo estrelado' },
      { marker: 'ck14', pct: [70, 90] },
      { marker: 'betacatenina', pct: [10, 30], pattern: 'N' },
      { marker: 'berep4', pct: [40, 70] },
      { marker: 'ki67', pct: [2, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma ameloblástico: atipia, mitoses frequentes, necrose, Ki-67 alto.',
      'Cisto odontogênico ceratocístico: parede fina, camada basal em paliçada mas sem retículo estrelado, superfície paraqueratinizada corrugada.',
      'Fibroma ameloblástico: componente ectomesenquimal mixoide neoplásico junto, em paciente mais jovem.',
      'Carcinoma basocelular da pele invadindo a mandíbula: BerEP4 forte, contexto cutâneo.',
    ],
    molecular: 'BRAF V600E na maioria dos mandibulares; SMO mutado nos maxilares.',
    sources: [WHO, 'WHO Classification of Head and Neck Tumours, capítulo de tumores odontogênicos', THOMPSON],
  },
  {
    id: 'ceratocisto-odontogenico',
    name: 'Cisto odontogênico ceratocístico',
    aka: ['ceratocisto odontogênico', 'tumor odontogênico ceratocístico', 'odontogenic keratocyst'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 3 }],
    cells: ['escamoso', 'basaloide'],
    architecture: ['cistico', 'palicada'],
    features: ['queratinizacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Cisto do ramo e corpo posterior da mandíbula com revestimento escamoso fino e uniforme de cinco a oito camadas, camada basal cuboide ou colunar em paliçada e superfície paraqueratinizada corrugada, sem cristas epiteliais; recidiva com frequência e é o marcador do síndrome de Gorlin quando múltiplo.',
    criteria: [
      'Epitélio escamoso de espessura uniforme, cinco a oito camadas, sem cristas interpapilares.',
      'Camada basal em paliçada, com núcleos hipercromáticos alinhados.',
      'Superfície paraqueratinizada ondulada ou corrugada, com paraqueratina descamada na luz.',
      'Ausência de inflamação no revestimento típico: a inflamação apaga os critérios e simula cisto radicular.',
      'Múltiplos ceratocistos exigem investigar síndrome de Gorlin (PTCH1).',
    ],
    markers: [
      { marker: 'ck17', pct: [85, 100], note: 'clássica no ceratocisto, contra o cisto dentígero' },
      { marker: 'ck19', pct: [70, 90], note: 'restrita às camadas basais' },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck56', pct: [85, 100] },
      { marker: 'ki67', pct: [5, 20], note: 'nas camadas suprabasais, maior que nos outros cistos odontogênicos' },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'calretinina', pct: [0, 10], note: 'ajuda contra o ameloblastoma uniscístico, que é positivo' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Cisto dentígero: revestimento não queratinizado de duas a quatro camadas, sem paliçada.',
      'Cisto odontogênico ortoqueratinizado: ortoqueratina com camada granulosa, sem paliçada basal, recidiva pouco.',
      'Ameloblastoma unicístico: retículo estrelado e polarização reversa, calretinina positiva.',
      'Cisto radicular inflamado: epitélio hiperplásico irregular, arcadas, inflamação densa.',
    ],
    molecular: 'Mutação de PTCH1 (via hedgehog), somática ou germinativa na síndrome de Gorlin.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'mixoma-odontogenico',
    name: 'Mixoma odontogênico',
    aka: ['fibromixoma odontogênico', 'odontogenic myxoma'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 2 }],
    cells: ['estreladas', 'fusocelular'],
    architecture: ['infiltrativo'],
    features: ['estroma-mixoide', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Lesão intraóssea gelatinosa dos maxilares feita de células estreladas e fusiformes esparsas em matriz mixoide abundante, sem cápsula, permeando as trabéculas ósseas; a radiologia em bolhas de sabão e o sítio fazem metade do diagnóstico.',
    criteria: [
      'Matriz mixoide abundante, alcianofílica, com celularidade baixa e uniforme.',
      'Células estreladas ou fusiformes sem atipia significativa, mitoses raras.',
      'Localização intraóssea em maxila ou mandíbula, com permeação das trabéculas.',
      'Ilhas de epitélio odontogênico inativo podem aparecer e não são necessárias.',
      'Ausência de lipoblastos e de rede vascular plexiforme afasta mixoide de partes moles.',
    ],
    markers: [
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'sma', pct: [20, 50], note: 'focal, miofibroblástica' },
      { marker: 'calponina', pct: [20, 50] },
      { marker: 's100', pct: [0, 15], note: 'ao contrário do mixoma de partes moles, é fraca e focal' },
      { marker: 'cd34', pct: [10, 30] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'ae1ae3', pct: [0, 10], note: 'só nas ilhas odontogênicas aprisionadas' },
      { marker: 'mdm2', pct: 0, note: 'negativa; separa de lipossarcoma mixoide invadindo' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Papila dental ou folículo dentário hiperplásico: pequenos, associados a dente em formação, não permeiam osso.',
      'Fibroma condromixoide: matriz condroide lobulada com células gigantes na periferia.',
      'Mixofibrossarcoma: atipia, vasos curvilíneos, idoso, em partes moles.',
      'Mixoma de partes moles: fora do osso, S100 negativo, GNAS na síndrome de Mazabraud.',
    ],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'adenoma-orelha-media',
    name: 'Tumor neuroendócrino de orelha média',
    aka: ['adenoma de orelha média', 'middle ear neuroendocrine tumour', 'MeNET'],
    behavior: 'benigno',
    sites: [{ site: 'orelha', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'glandular', 'neuroendocrino'],
    architecture: ['glandulas', 'trabecular', 'ninhos', 'lencois'],
    features: ['mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Massa da caixa timpânica feita de glândulas pequenas e trabéculas de células cuboides monótonas com cromatina em sal e pimenta; coexpressa queratina e marcadores neuroendócrinos, e o erro comum é chamá-la de paraganglioma ou de adenocarcinoma.',
    criteria: [
      'Localização na orelha média, envolvendo os ossículos, sem destruição óssea agressiva.',
      'Padrão glandular e trabecular misto de células cuboides uniformes, sem atipia nem necrose.',
      'Coexpressão de queratina com sinaptofisina e cromogranina.',
      'CK7 e CK20 costumam marcar populações distintas dentro do mesmo tumor, achado bastante característico.',
      'Ausência de células sustentaculares S100 positivas, o que o separa do paraganglioma.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'ck7', pct: [70, 90], note: 'em parte das células' },
      { marker: 'ck20', pct: [50, 80], note: 'em população diferente da CK7; padrão bicelular típico' },
      { marker: 'sinaptofisina', pct: [85, 100] },
      { marker: 'cromogranina', pct: [80, 95] },
      { marker: 'insm1', pct: [80, 95] },
      { marker: 'cd56', pct: [70, 90] },
      { marker: 's100', pct: [0, 10], note: 'sem sustentaculares; o paraganglioma as tem' },
      { marker: 'gata3', pct: [10, 40], note: 'cuidado: positiva no paraganglioma' },
      { marker: 'th', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Paraganglioma jugulotimpânico: queratina negativa, sustentaculares S100 positivas, zellballen.',
      'Tumor papilar do saco endolinfático: papilas com eixo fibrovascular, coloide-símile, invasão do osso petroso.',
      'Adenocarcinoma metastático: atipia, necrose, Ki-67 alto.',
      'Colesteatoma: escamoso queratinizado, sem componente glandular.',
    ],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'papiloma-escamoso-hpv',
    name: 'Papiloma escamoso e papilomatose respiratória recorrente',
    aka: ['papiloma escamoso', 'papilomatose laríngea juvenil', 'recurrent respiratory papillomatosis'],
    behavior: 'benigno',
    sites: [
      { site: 'laringe', role: 'primario', freq: 3 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['escamoso'],
    architecture: ['papilar'],
    features: ['queratinizacao', 'mitoses-raras', 'precursor'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Papilas com eixo fibrovascular delicado revestidas por epitélio escamoso maduro com coilocitose, causadas por HPV de baixo risco (6 e 11); na criança a forma é multifocal e recidivante, adquirida no parto, e o risco real é a disseminação para a traqueia e o pulmão, não a transformação maligna.',
    criteria: [
      'Papilas exofíticas com eixo fibrovascular fino revestidas por epitélio escamoso de maturação preservada.',
      'Coilocitose e disceratose superficiais; a camada basal pode ser hiperplásica sem que isso seja displasia.',
      'HPV de baixo risco (6 e 11): p16 é negativo ou focal, e sua positividade em bloco deve fazer pensar em lesão de alto risco.',
      'Displasia deve ser graduada e relatada, mas é incomum; transformação maligna ocorre em menos de 5%, quase sempre com tabagismo ou radioterapia prévia.',
      'Forma juvenil: multifocal, agressiva localmente, com disseminação traqueobrônquica e nódulos pulmonares cavitados.',
    ],
    markers: [
      { marker: 'p16', pct: [0, 15], note: 'negativo ou focal: HPV de baixo risco não desliga o RB e não produz o padrão em bloco' },
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'ck7', pct: [10, 40], note: 'no epitélio respiratório de superfície remanescente' },
      { marker: 'p53', pct: [0, 10], note: 'selvagem; aberrante levanta displasia ou carcinoma' },
      { marker: 'ki67', pct: [10, 40], note: 'camadas basal e parabasal; em espessura total sugere displasia' },
      { marker: 'ebv', pct: 0 },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma verrucoso: base larga empurrada, queratinização maciça, sem coilocitose.',
      'Carcinoma escamoso papilar: atipia de espessura total nas papilas.',
      'Papiloma sinonasal invertido: crescimento endofítico, EGFR mutado, outro sítio.',
      'Hiperplasia pseudoepiteliomatosa e nódulo de corda vocal: sem eixo papilar verdadeiro.',
      'Condiloma e verruga vulgar oral: mesma família de HPV, morfologia sobreposta.',
    ],
    molecular: 'HPV 6 e 11 (baixo risco); a forma juvenil associa-se ao genótipo 11, que é o mais agressivo.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'hmsc',
    name: 'Carcinoma sinonasal multifenotípico HPV-relacionado',
    aka: ['HMSC', 'HPV-related multiphenotypic sinonasal carcinoma', 'carcinoma sinonasal adenoide cístico-símile HPV'],
    behavior: 'maligno',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 1 }],
    cells: ['basaloide', 'epitelioide', 'fusocelular'],
    architecture: ['cribriforme', 'trabecular', 'lencois'],
    features: ['hialinizacao', 'necrose', 'mitoses-altas', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma sinonasal que copia o adenoide cístico — bifásico, cribriforme, com material de membrana basal — mas é causado por HPV de alto risco, quase sempre o genótipo 33, e tem prognóstico muito melhor. A displasia escamosa de superfície sobre a lesão é uma pista que o adenoide cístico verdadeiro não dá.',
    criteria: [
      'Morfologia bifásica de tipo adenoide cístico, com células ductais e mioepiteliais abluminais em padrão cribriforme, tubular ou sólido.',
      'p16 em bloco com HPV de alto risco confirmado, tipicamente o genótipo 33 (e não o 16).',
      'Displasia escamosa ou carcinoma in situ na mucosa de superfície sobrejacente: achado presente em boa parte e ausente no adenoide cístico.',
      'MYB pode ser positivo e a fusão MYB::NFIB está ausente: a imuno de MYB sozinha não separa das duas entidades.',
      'Prognóstico bem melhor que o do adenoide cístico sinonasal, apesar da atipia e das mitoses.',
    ],
    markers: [
      { marker: 'p16', pct: [95, 100], note: 'em bloco; é o critério de entrada' },
      { marker: 'p63', pct: [90, 100], note: 'abluminal, em cesto' },
      { marker: 'p40', pct: [85, 100] },
      { marker: 's100', pct: [70, 95] },
      { marker: 'sox10', pct: [80, 100] },
      { marker: 'calponina', pct: [80, 95] },
      { marker: 'sma', pct: [50, 85] },
      { marker: 'cd117', pct: [70, 95], note: 'luminal, como no adenoide cístico: não separa' },
      { marker: 'myb', pct: [30, 60], note: 'pode marcar sem que haja fusão MYB::NFIB — a armadilha central deste verbete' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ebv', pct: 0 },
      { marker: 'p53', pct: [0, 15], note: 'selvagem' },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma adenoide cístico sinonasal: p16 negativo ou focal, fusão MYB::NFIB, invasão perineural, prognóstico pior.',
      'Carcinoma escamoso basaloide: monofásico, sem componente mioepitelial.',
      'Carcinoma sinonasal indiferenciado: sem bifasia, IDH2 mutado.',
      'Carcinoma mioepitelial: sem componente ductal.',
      'Carcinoma de orofaringe HPV-associado invadindo: contexto e sítio.',
    ],
    molecular: 'HPV de alto risco, com sobre-representação marcante do genótipo 33; sem fusão MYB::NFIB.',
    sources: [WHO, BISHOP],
  },
  {
    id: 'adenocarcinoma-sinonasal-nao-intestinal',
    name: 'Adenocarcinoma sinonasal não intestinal',
    aka: ['non-intestinal-type sinonasal adenocarcinoma', 'adenocarcinoma seromucinoso sinonasal'],
    behavior: 'maligno',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 2 }],
    cells: ['glandular', 'epitelioide', 'oncocitico'],
    architecture: ['glandulas', 'papilar', 'trabecular', 'infiltrativo'],
    features: ['mitoses-raras', 'mitoses-altas', 'necrose', 'desmoplasia'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma sinonasal que não reproduz mucosa intestinal: o de baixo grau forma túbulos e papilas uniformes justapostos, sem estroma entre eles, com curso indolente; o de alto grau é francamente atípico e agressivo. O perfil é o inverso do de tipo intestinal — CK7 positivo com CDX2 e CK20 negativos.',
    criteria: [
      'Proliferação glandular sem diferenciação intestinal: sem caliciformes, sem borda em escova, sem células de Paneth.',
      'Baixo grau: túbulos e papilas dorso a dorso, células cuboides ou colunares uniformes, mitoses raras e sem necrose.',
      'Alto grau: atipia acentuada, necrose, mitoses frequentes e infiltração destrutiva.',
      'CK7 positivo com CDX2, CK20 e vilina negativos, o que o separa do de tipo intestinal e da metástase colorretal.',
      'Exclusão de tumor de glândula salivar menor (adenoide cístico, polimorfo, secretor) por painel mioepitelial e anticorpos de fusão.',
    ],
    markers: [
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'cdx2', pct: [0, 10], note: 'o negativo que o separa do de tipo intestinal' },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'vilina', pct: [0, 15] },
      { marker: 'muc2', pct: [0, 10] },
      { marker: 's100', pct: [20, 50], note: 'nas formas seromucinosas com diferenciação salivar' },
      { marker: 'sox10', pct: [20, 50] },
      { marker: 'dog1', pct: [0, 15] },
      { marker: 'p63', pct: [10, 40], note: 'camada abluminal nas formas com componente mioepitelial' },
      { marker: 'ttf1', pct: 0 },
      { marker: 'p16', pct: [5, 20], note: 'o negativo que ajuda contra o multifenotípico HPV-relacionado' },
      { marker: 'p53', pct: [20, 50], note: 'aberrante no de alto grau' },
      { marker: 'ki67', pct: [5, 60], note: 'baixo no de baixo grau e alto no de alto grau: é o que mais separa os dois' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma sinonasal de tipo intestinal: CDX2 e CK20 difusos.',
      'Metástase de adenocarcinoma colorretal: CDX2 e SATB2, com história.',
      'Hamartoma adenomatoide epitelial respiratório: glândulas benignas com membrana basal espessa.',
      'Adenocarcinoma polimorfo e outros salivares menores: painel mioepitelial e p63 com p40 dissociados.',
      'Papiloma sinonasal com metaplasia glandular: sem invasão nem atipia.',
    ],
    sources: [WHO, BISHOP, THOMPSON],
  },
  {
    id: 'carcinoma-linfoepitelial',
    name: 'Carcinoma linfoepitelial (fora da nasofaringe)',
    aka: ['lymphoepithelial carcinoma', 'carcinoma linfoepitelial salivar', 'carcinoma tipo linfoepitelioma'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'laringe', role: 'primario', freq: 1 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
      { site: 'estomago', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
    ],
    cells: ['sincicial', 'epitelioide', 'linfoide-pequenas'],
    architecture: ['lencois', 'ninhos'],
    features: ['linfoide', 'nucleolo', 'mitoses-altas', 'necrose'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma indiferenciado com a mesma morfologia do nasofaríngeo — lençóis sinciciais de nucléolo grande afogados em linfócitos —, mas em outro sítio: parótida, laringe, seios, estômago ou pulmão. Associado a EBV nas populações de risco, sobretudo asiática e inuíte, e com prognóstico melhor que o do carcinoma convencional do mesmo órgão.',
    criteria: [
      'Células sinciciais grandes de limites indistintos e nucléolo eosinofílico proeminente, em fundo linfoplasmocitário denso.',
      'Confirmação de linhagem epitelial por pan-queratina e p40, que desfaz a impressão de linfoma.',
      'EBER por hibridização in situ positivo na maioria dos salivares e gástricos; nos pulmonares e laríngeos a associação é menos constante.',
      'Exclusão obrigatória de metástase de carcinoma nasofaríngeo: exige exame da nasofaringe antes de chamar de primário.',
      'O infiltrado linfoide é reativo e policlonal, e não deve ser confundido com componente linfomatoso.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p40', pct: [80, 95] },
      { marker: 'p63', pct: [85, 100] },
      { marker: 'ck56', pct: [75, 95] },
      { marker: 'cam52', pct: [80, 95] },
      { marker: 'ebv', pct: [60, 95], note: 'quase constante nos salivares e gástricos; menos nos pulmonares e laríngeos' },
      { marker: 'cd45', pct: 0, note: 'o negativo que exclui linfoma — o infiltrado de fundo é que marca' },
      { marker: 'cd20', pct: 0 },
      { marker: 'cd3', pct: 0 },
      { marker: 'cd30', pct: [0, 10] },
      { marker: 'ck7', pct: [20, 60] },
      { marker: 'p16', pct: [10, 30], note: 'pode marcar sem HPV' },
      { marker: 'pdl1', pct: [50, 90], note: 'preditivo, não diagnóstico' },
      { marker: 'sox10', pct: [0, 10], note: 'o negativo que exclui melanoma' },
      { marker: 'ki67', pct: [60, 95] },
    ],
    mimics: [
      'Carcinoma nasofaríngeo metastático ou por extensão: idêntico; a nasofaringe precisa ser examinada.',
      'Linfoma difuso de grandes células B: CD45 e CD20 positivos, queratina negativa.',
      'Lesão linfoepitelial benigna e sialadenite de Sjögren: sem atipia, ilhas epimioepiteliais.',
      'Melanoma mucoso: SOX10 positivo.',
      'Carcinoma mioepitelial rico em linfócitos: painel mioepitelial positivo.',
    ],
    molecular: 'Vírus Epstein-Barr clonal na maioria dos casos associados.',
    sources: [WHO, THOMPSON, 'Seethala & Griffith, capítulos de patologia de glândulas salivares, Surg Pathol Clin'],
  },
  {
    id: 'pindborg',
    name: 'Tumor odontogênico epitelial calcificante (Pindborg)',
    aka: ['tumor de Pindborg', 'calcifying epithelial odontogenic tumour', 'CEOT'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'escamoso', 'claras'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['amiloide', 'calcificacao', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto'],
    summary: 'Tumor odontogênico da mandíbula posterior, quase sempre associado a dente incluso, feito de lençóis de células epiteliais poligonais com pontes intercelulares nítidas e núcleos pleomórficos que não devem assustar, depositando material amiloide que calcifica em anéis concêntricos de Liesegang.',
    criteria: [
      'Ilhas e lençóis de células epiteliais poligonais com pontes intercelulares bem visíveis e limites celulares nítidos.',
      'Material amiloide eosinofílico entre e dentro das ilhas, vermelho Congo positivo com birrefringência verde-maçã.',
      'Calcificações concêntricas em anéis (Liesegang) sobre o amiloide.',
      'Pleomorfismo nuclear com núcleos gigantes e bizarros é característico e não indica malignidade: não há mitoses.',
      'Radiolucidez mista com focos radiopacos, associada a dente incluso; a variante de células claras recidiva mais.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ck14', pct: [85, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [80, 95] },
      { marker: 'ck19', pct: [70, 95], note: 'origem odontogênica' },
      { marker: 'ema', pct: [40, 80] },
      { marker: 'calretinina', pct: [0, 20], note: 'o negativo que ajuda contra ameloblastoma' },
      { marker: 'brafv600e', pct: [0, 10], note: 'o negativo que separa do ameloblastoma, que é BRAF mutado na maioria' },
      { marker: 'ki67', pct: [1, 5], note: 'muito baixo apesar do pleomorfismo: é o que tranquiliza' },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Ameloblastoma: paliçada com polarização reversa e retículo estrelado, calretinina positiva, BRAF V600E.',
      'Carcinoma escamoso intraósseo: mitoses, necrose, Ki-67 alto.',
      'Tumor odontogênico adenomatoide: estruturas em roseta e ductais, em canino de adolescente.',
      'Cisto odontogênico calcificante (tumor de Gorlin): células fantasmas com β-catenina nuclear.',
      'Amiloidose localizada dos maxilares: sem componente epitelial neoplásico.',
    ],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'tumor-odontogenico-adenomatoide',
    name: 'Tumor odontogênico adenomatoide',
    aka: ['AOT', 'adenomatoid odontogenic tumour', 'tumor dos dois terços'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'fusocelular', 'basaloide'],
    architecture: ['nodular', 'rosetas', 'glandulas', 'cistico'],
    features: ['calcificacao', 'hialinizacao', 'mitoses-raras'],
    ages: ['jovem'],
    sex: 'f',
    summary: 'Tumor encapsulado do canino superior não irrompido em adolescente do sexo feminino — a regra dos dois terços: dois terços em mulheres, dois terços na maxila, dois terços associados a canino incluso. Forma nódulos sólidos de células fusiformes com estruturas em roseta e pseudoductos que não são glândulas verdadeiras.',
    criteria: [
      'Cápsula fibrosa espessa e completa, com o tumor muitas vezes envolvendo a coroa de um dente incluso.',
      'Nódulos sólidos de células fusiformes ou poligonais em redemoinho, com estruturas em roseta.',
      'Estruturas ductais aparentes revestidas por células colunares — pseudoductos, sem secreção verdadeira.',
      'Material eosinofílico amorfo entre as células e calcificações distróficas.',
      'Comportamento benigno, curado pela enucleação; recidiva é excepcional, ao contrário do ameloblastoma.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck19', pct: [80, 100], note: 'epitélio odontogênico' },
      { marker: 'ck14', pct: [70, 95] },
      { marker: 'ck56', pct: [70, 95] },
      { marker: 'p63', pct: [80, 100] },
      { marker: 'betacatenina', pct: [50, 85], pattern: 'N', note: 'reflete mutação de CTNNB1, que é a alteração desta entidade' },
      { marker: 'ema', pct: [30, 70], note: 'nos pseudoductos' },
      { marker: 'calretinina', pct: [0, 20] },
      { marker: 'brafv600e', pct: [0, 5], note: 'o negativo que o separa do ameloblastoma' },
      { marker: 's100', pct: [0, 20] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Ameloblastoma: paliçada com polarização reversa, BRAF V600E, infiltrativo e sem cápsula.',
      'Tumor de Pindborg: amiloide com anéis de Liesegang e pleomorfismo nuclear.',
      'Cisto dentígero: revestimento fino sem nódulos sólidos.',
      'Fibroma ameloblástico: componente ectomesenquimal mixoide, em criança.',
      'Adenocarcinoma de glândula salivar menor: glândulas verdadeiras com secreção, invasivo.',
    ],
    molecular: 'Mutações de CTNNB1, com acúmulo nuclear de β-catenina.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'fibroma-ameloblastico-odontoma',
    name: 'Fibroma ameloblástico e odontoma',
    aka: ['fibroma ameloblástico', 'odontoma composto', 'odontoma complexo', 'fibro-odontoma ameloblástico'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 3 }],
    cells: ['basaloide', 'epitelioide', 'estreladas', 'fusocelular'],
    architecture: ['plexiforme', 'ninhos', 'nodular'],
    features: ['estroma-mixoide', 'calcificacao', 'mitoses-raras'],
    ages: ['crianca', 'jovem'],
    summary: 'Os dois odontogênicos mistos, em que epitélio e ectomesênquima são ambos neoplásicos. O odontoma é o mais comum de todos os tumores odontogênicos e na verdade é um hamartoma, com esmalte, dentina e polpa organizados em dentículos. O fibroma ameloblástico tem cordões de epitélio odontogênico num estroma mixoide tipo papila dental, sem tecido duro.',
    criteria: [
      'Fibroma ameloblástico: cordões e ilhas de epitélio odontogênico com paliçada periférica, dentro de ectomesênquima mixoide celular semelhante à papila dental, sem formação de esmalte ou dentina.',
      'Odontoma: tecidos dentais duros formados e organizados — composto quando há dentículos reconhecíveis, complexo quando a massa é desorganizada.',
      'Fibro-odontoma ameloblástico ocupa o meio do espectro, com matriz dura em formação.',
      'Idade abaixo de vinte anos na quase totalidade; acima disso, reveja o diagnóstico.',
      'Fibrossarcoma ameloblástico: o componente ectomesenquimal ganha atipia e mitoses, com o epitelial permanecendo benigno.',
    ],
    markers: [
      { marker: 'ck19', pct: [85, 100], note: 'componente epitelial odontogênico' },
      { marker: 'ae1ae3', pct: [90, 100], note: 'só o epitélio' },
      { marker: 'ck14', pct: [70, 95] },
      { marker: 'p63', pct: [85, 100] },
      { marker: 'calretinina', pct: [20, 60], note: 'no retículo estrelado, como no ameloblastoma' },
      { marker: 'brafv600e', pct: [40, 70], note: 'no fibroma ameloblástico, partilhando a via do ameloblastoma' },
      { marker: 'vimentina', pct: [95, 100], note: 'componente ectomesenquimal' },
      { marker: 'sma', pct: [10, 40] },
      { marker: 's100', pct: [10, 40] },
      { marker: 'betacatenina', pct: [10, 40], pattern: 'N' },
      { marker: 'ki67', pct: [1, 8], note: 'alto no componente estromal indica fibrossarcoma ameloblástico' },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Ameloblastoma: só componente epitelial neoplásico, o estroma é fibroso maduro e não papila dental.',
      'Papila e folículo dentais hiperplásicos: associados a dente em formação, sem massa.',
      'Mixoma odontogênico: sem componente epitelial significativo, permeia o osso.',
      'Fibrossarcoma ameloblástico: atipia e mitoses no estroma.',
      'Cisto odontogênico calcificante com odontoma: células fantasmas presentes.',
    ],
    molecular: 'BRAF V600E no fibroma ameloblástico, como no ameloblastoma.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'lesoes-fibro-osseas-maxilares',
    name: 'Lesões fibro-ósseas dos maxilares',
    aka: ['fibroma ossificante', 'displasia cemento-óssea', 'fibroma ossificante juvenil', 'fibro-osseous lesions'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 3 }],
    cells: ['fusocelular', 'osteoblastico', 'estreladas'],
    architecture: ['storiforme', 'nodular'],
    features: ['osteoide', 'calcificacao', 'hemorragia', 'mitoses-raras', 'gigantes-osteoclasticas'],
    ages: ['adulto', 'jovem'],
    sex: 'f',
    summary: 'Grupo em que morfologia sozinha não decide e a radiologia é parte do diagnóstico. O fibroma ossificante é delimitado e se destaca do osso hospedeiro, com trabéculas ricas em osteoblastos. A displasia cemento-óssea é periapical ou florida, multifocal, e não se opera. A displasia fibrosa se funde ao osso, sem borda osteoblástica.',
    criteria: [
      'Fibroma ossificante: lesão delimitada, destacável na cirurgia, com trabéculas ósseas e cementículos envoltos por osteoblastos proeminentes.',
      'Displasia cemento-óssea: periapical, focal ou florida, em região de dentes vitais, evoluindo de radiolúcida a radiopaca; conduta é não operar.',
      'Displasia fibrosa: funde-se ao osso hospedeiro sem borda osteoblástica, com trabéculas em letras chinesas e mutação de GNAS.',
      'Fibroma ossificante juvenil (trabecular e psamomatoide): em criança, agressivo localmente, com trabéculas imaturas ou corpos psamomatoides.',
      'Correlação com a imagem é obrigatória: as três lesões podem ser indistinguíveis num fragmento pequeno.',
    ],
    markers: [
      { marker: 'satb2', pct: [70, 95], note: 'linhagem osteoblástica; não separa das lesões entre si nem de osteossarcoma' },
      { marker: 'runx2', pct: [50, 85] },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'sma', pct: [20, 50] },
      { marker: 'cd68', pct: [40, 80], note: 'células gigantes osteoclásticas quando presentes' },
      { marker: 'mdm2', pct: [0, 10], note: 'o negativo que separa do osteossarcoma de baixo grau e do parosteal' },
      { marker: 'cdk4', pct: [0, 10] },
      { marker: 'h3g34', pct: 0, note: 'o negativo que exclui tumor de células gigantes' },
      { marker: 'brafv600e', pct: [0, 5] },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 8] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Displasia fibrosa: GNAS mutado, funde-se ao osso, não se destaca.',
      'Osteossarcoma de baixo grau dos maxilares: MDM2 e CDK4 amplificados, permeação.',
      'Granuloma central de células gigantes: células gigantes dominantes com hemorragia e hemossiderina.',
      'Osteoblastoma e cementoblastoma: ligado à raiz do dente, com borda osteoblástica exuberante.',
      'Osteomielite crônica esclerosante: inflamação com osso reativo, sem estroma fibroblástico celular.',
    ],
    molecular: 'GNAS na displasia fibrosa; mutações de SATB2 e outras no fibroma ossificante; CDC73 no fibroma ossificante do hiperparatireoidismo com tumor de mandíbula.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'granuloma-central-celulas-gigantes',
    name: 'Granuloma central de células gigantes',
    aka: ['lesão central de células gigantes', 'granuloma periférico de células gigantes', 'central giant cell granuloma'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 2 }],
    cells: ['fusocelular', 'gigantes', 'histiocitoide'],
    architecture: ['nodular', 'lencois'],
    features: ['gigantes-osteoclasticas', 'hemorragia', 'osteoide', 'mitoses-moderadas'],
    ages: ['crianca', 'jovem', 'adulto'],
    sex: 'f',
    summary: 'Lesão dos maxilares, anterior à mandíbula na maioria, feita de estroma fibroblástico celular com hemorragia, hemossiderina e células gigantes osteoclásticas agrupadas ao redor das áreas hemorrágicas — e não espalhadas por igual. Morfologicamente igual ao tumor marrom do hiperparatireoidismo, que precisa ser afastado por dosagem, não por lâmina.',
    criteria: [
      'Estroma de células fusiformes e ovoides com hemorragia, hemossiderina e osteoide reativo na periferia.',
      'Células gigantes osteoclásticas de distribuição irregular, concentradas nas áreas hemorrágicas.',
      'Dosagem de cálcio, fósforo e paratormônio obrigatória antes de fechar: o tumor marrom é indistinguível.',
      'H3.3 G34W negativo, o que o separa do tumor de células gigantes do osso, que é raro nos maxilares.',
      'Formas agressiva e não agressiva definidas por tamanho, dor, reabsorção radicular e recidiva.',
    ],
    markers: [
      { marker: 'cd68', pct: [90, 100], note: 'células gigantes e histiócitos' },
      { marker: 'cd163', pct: [70, 95] },
      { marker: 'h3g34', pct: 0, note: 'o negativo que separa do tumor de células gigantes do osso' },
      { marker: 'satb2', pct: [50, 85], note: 'estroma osteoblástico' },
      { marker: 'runx2', pct: [40, 80] },
      { marker: 'sma', pct: [20, 60], note: 'estroma miofibroblástico' },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'catepsinak', pct: [70, 95], note: 'nas células gigantes osteoclásticas' },
      { marker: 'pth', pct: 0, note: 'o negativo não exclui tumor marrom: a resposta está na dosagem sérica' },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'ki67', pct: [2, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor marrom do hiperparatireoidismo: morfologia idêntica; só a dosagem de PTH separa.',
      'Tumor de células gigantes do osso: H3.3 G34W positivo, epifisário, raro nos maxilares.',
      'Cisto ósseo aneurismático: septos com espaços hemorrágicos, USP6 rearranjado.',
      'Querubismo: bilateral e simétrico, em criança, com SH3BP2 mutado.',
      'Lesões fibro-ósseas com células gigantes: estroma fibro-ósseo dominante.',
    ],
    molecular: 'Mutações de TRPV4, KRAS e FGFR1 descritas; SH3BP2 no querubismo.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'reah',
    name: 'Hamartoma adenomatoide epitelial respiratório (REAH)',
    aka: ['REAH', 'respiratory epithelial adenomatoid hamartoma'],
    behavior: 'benigno',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 2 }],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'cistico'],
    features: ['hialinizacao', 'mitoses-raras', 'linfoide'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Proliferação de glândulas revestidas por epitélio respiratório ciliado, cada uma envolta por uma membrana basal hialina espessa e nítida, brotando do epitélio de superfície; nasce quase sempre na fenda olfatória e é o principal mímico benigno do adenocarcinoma sinonasal de baixo grau.',
    criteria: [
      'Glândulas de tamanho variado revestidas por epitélio respiratório ciliado, com células caliciformes, em continuidade com a superfície.',
      'Membrana basal hialina espessa envolvendo cada glândula: o achado que define e que o adenocarcinoma não tem.',
      'Estroma edematoso ou fibroso com infiltrado inflamatório, sem desmoplasia.',
      'Ausência de atipia, de complexidade arquitetural e de invasão.',
      'Localização na fenda olfatória, muitas vezes com alargamento dela na tomografia, em paciente com polipose.',
    ],
    markers: [
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ttf1', pct: [20, 60], note: 'epitélio respiratório; não interprete como pulmão' },
      { marker: 'colageno-iv', pct: [90, 100], note: 'realça a membrana basal espessa, que é o critério' },
      { marker: 'p63', pct: [70, 95], note: 'camada basal preservada em volta das glândulas' },
      { marker: 'p40', pct: [60, 90] },
      { marker: 'cdx2', pct: [0, 10] },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 's100', pct: [10, 40] },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma sinonasal não intestinal de baixo grau: glândulas dorso a dorso sem membrana basal, com atipia e sem camada basal.',
      'Pólipo inflamatório com glândulas seromucinosas hiperplásicas: glândulas menores, sem a bainha hialina.',
      'Papiloma sinonasal com metaplasia glandular: crescimento invertido do epitélio.',
      'Hamartoma seromucinoso: glândulas serosas pequenas, entidade próxima e às vezes combinada.',
    ],
    sources: [WHO, BISHOP, THOMPSON],
  },
  {
    id: 'carcinoma-neuroendocrino-laringe',
    name: 'Tumores neuroendócrinos da laringe',
    aka: ['carcinoide laríngeo', 'carcinoma neuroendócrino de laringe', 'carcinoma de pequenas células laríngeo'],
    behavior: 'maligno',
    sites: [
      { site: 'laringe', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['neuroendocrino', 'epitelioide', 'pequenas-redondas', 'oncocitico'],
    architecture: ['ninhos', 'trabecular', 'organoide', 'lencois'],
    features: ['necrose', 'mitoses-moderadas', 'mitoses-altas', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Grupo próprio da laringe supraglótica, do tumor neuroendócrino bem diferenciado ao carcinoma de pequenas células; o de grau intermediário é o mais comum e o mais confundido com carcinoma medular de tireoide, porque também pode expressar calcitonina — e a diferença está na tireoglobulina, no TTF-1 e na topografia.',
    criteria: [
      'Localização supraglótica, quase sempre na epiglote ou nas pregas ariepiglóticas.',
      'Graduação como no pulmão: bem diferenciado (típico e atípico) contra pouco diferenciado (grandes células e pequenas células), por mitoses e necrose.',
      'Sinaptofisina, cromogranina e INSM1 positivos, com queratina.',
      'Calcitonina pode ser positiva e simular carcinoma medular: tireoglobulina negativa e ausência de massa tireoidiana resolvem.',
      'O carcinoma de pequenas células laríngeo é tratado como o pulmonar, com quimiorradioterapia e não com laringectomia.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [85, 100] },
      { marker: 'cromogranina', pct: [70, 95], note: 'mais fraca nos pouco diferenciados' },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'calcitonina', pct: [20, 50], note: 'positiva em parte: é a armadilha com carcinoma medular de tireoide' },
      { marker: 'tireoglobulina', pct: 0, note: 'o negativo que resolve essa armadilha' },
      { marker: 'ttf1', pct: [10, 40], note: 'positivo em parte, sobretudo nos de pequenas células: não indica pulmão' },
      { marker: 'cea', pct: [40, 80] },
      { marker: 'p40', pct: [0, 15], note: 'o negativo que separa do carcinoma escamoso basaloide' },
      { marker: 'p16', pct: [10, 40] },
      { marker: 'rb1', pct: [30, 70], note: 'o positivo é a perda, nos pouco diferenciados' },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [5, 90], note: 'é o que gradua: baixo no bem diferenciado, acima de 60% no de pequenas células' },
    ],
    mimics: [
      'Carcinoma medular de tireoide com extensão laríngea: calcitonina e CEA positivos com massa tireoidiana.',
      'Paraganglioma laríngeo: queratina negativa, GATA3 positiva, sustentaculares S100.',
      'Carcinoma escamoso basaloide: p40 difuso, sem marcador neuroendócrino.',
      'Melanoma mucoso: SOX10 positivo.',
      'Adenocarcinoma de glândula salivar menor: sem marcador neuroendócrino difuso.',
    ],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'cec-basaloide-verrucoso',
    name: 'Variantes do carcinoma escamoso: basaloide e verrucoso',
    aka: ['carcinoma escamoso basaloide', 'carcinoma verrucoso', 'carcinoma de Ackerman'],
    behavior: 'maligno',
    sites: [
      { site: 'laringe', role: 'primario', freq: 2 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['escamoso', 'basaloide'],
    architecture: ['ninhos', 'palicada', 'lobular', 'infiltrativo'],
    features: ['necrose', 'queratinizacao', 'hialinizacao', 'mitoses-altas', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Duas variantes de prognóstico oposto que o verbete reúne porque são os extremos do mesmo tumor. O basaloide é agressivo: ninhos de células pequenas hipercromáticas com paliçada periférica, necrose comedo e material hialino. O verrucoso quase não metastatiza: papilas maciças de epitélio muito bem diferenciado com base larga e empurrada.',
    criteria: [
      'Basaloide: ninhos sólidos de células basaloides pequenas com paliçada periférica, necrose comedo e material de membrana basal, com componente escamoso convencional ou in situ associado.',
      'Verrucoso: epitélio escamoso muito bem diferenciado com queratinização maciça em igreja, base larga empurrada e ausência de atipia significativa.',
      'No verrucoso, qualquer foco de invasão franca ou atipia reclassifica como carcinoma escamoso convencional — o que muda inteiramente a conduta.',
      'p16 e HPV devem ser avaliados no basaloide de orofaringe: o HPV-positivo tem prognóstico bem melhor.',
      'A biópsia superficial do verrucoso é notoriamente insuficiente: exige a interface com o estroma.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'p16', pct: [20, 50], note: 'em bloco só nos basaloides de orofaringe; no verrucoso é negativo' },
      { marker: 'p53', pct: [30, 60], note: 'aberrante no basaloide HPV-negativo' },
      { marker: 'ck7', pct: [5, 20] },
      { marker: 'sinaptofisina', pct: [0, 10], note: 'o negativo que separa do carcinoma neuroendócrino de grandes células, que também é basaloide' },
      { marker: 'insm1', pct: [0, 10] },
      { marker: 'cd117', pct: [10, 40], note: 'pode marcar e sugerir adenoide cístico: falta a bifasia' },
      { marker: 'myb', pct: [0, 15], note: 'o negativo que ajuda contra adenoide cístico' },
      { marker: 's100', pct: [0, 10] },
      { marker: 'ki67', pct: [10, 90], note: 'muito alto no basaloide e baixo no verrucoso' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma adenoide cístico: bifásico com componente mioepitelial, MYB positivo.',
      'Carcinoma neuroendócrino de grandes células: sinaptofisina e INSM1 difusos.',
      'Carcinoma escamoso convencional: o verbete a que ambos pertencem.',
      'Papilomatose e hiperplasia verrucosa: sem invasão, HPV de baixo risco.',
      'Carcinoma NUT: NUT nuclear, também basaloide com queratinização abrupta.',
    ],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'tumor-saco-endolinfatico',
    name: 'Tumor do saco endolinfático',
    aka: ['endolymphatic sac tumour', 'adenocarcinoma papilar de baixo grau do osso temporal'],
    behavior: 'intermediario',
    sites: [{ site: 'orelha', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'claras', 'glandular'],
    architecture: ['papilar', 'folicular', 'cistico'],
    features: ['coloide', 'hemorragia', 'calcificacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Tumor destrutivo do osso petroso posterior com perda auditiva e vertigem, feito de papilas de eixo fibrovascular revestidas por uma camada única de células cuboides, com folículos cheios de material coloide-símile que imitam tireoide; um terço ocorre na doença de von Hippel-Lindau, muitas vezes bilateral.',
    criteria: [
      'Localização no saco endolinfático, com destruição do osso petroso posterior à imagem.',
      'Papilas com eixo fibrovascular delicado revestidas por camada única de células cuboides de citoplasma claro ou eosinofílico.',
      'Espaços foliculares com material coloide-símile: a razão pela qual imita carcinoma tireoidiano metastático.',
      'TTF-1 e tireoglobulina negativos, o que afasta tireoide — o passo obrigatório.',
      'Rastreio de von Hippel-Lindau, sobretudo se bilateral ou em jovem.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ck7', pct: [70, 95] },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'ttf1', pct: 0, note: 'o negativo obrigatório: sem ele o caso vira metástase de tireoide' },
      { marker: 'tireoglobulina', pct: 0 },
      { marker: 'pax8', pct: [10, 40], note: 'pode marcar e confundir com renal e tireoidiano' },
      { marker: 's100', pct: [20, 60] },
      { marker: 'gfap', pct: [10, 40] },
      { marker: 'sinaptofisina', pct: [10, 40] },
      { marker: 'caix', pct: [30, 70], note: 'reflete a via VHL, como no carcinoma renal de células claras' },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de carcinoma papilífero de tireoide: TTF-1 e tireoglobulina positivos.',
      'Metástase de carcinoma renal de células claras: PAX8 forte e CA-IX em caixa, também em von Hippel-Lindau.',
      'Paraganglioma jugulotimpânico: queratina negativa, GATA3 positiva.',
      'Tumor neuroendócrino de orelha média: glandular e trabecular, com sinaptofisina e cromogranina difusas.',
      'Plexo coroide ectópico e papiloma de plexo: transtirretina, no ângulo pontocerebelar.',
    ],
    molecular: 'Mutação de VHL, germinativa em cerca de um terço.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'cisto-odontogenico-calcificante',
    name: 'Cisto odontogênico calcificante e tumor dentinogênico de células fantasmas',
    aka: ['cisto de Gorlin', 'calcifying odontogenic cyst', 'tumor odontogênico de células fantasmas', 'dentinogenic ghost cell tumour'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 2 }],
    cells: ['basaloide', 'epitelioide', 'escamoso'],
    architecture: ['cistico', 'palicada', 'ninhos'],
    features: ['calcificacao', 'queratinizacao', 'mitoses-raras', 'hialinizacao'],
    ages: ['jovem', 'adulto'],
    summary: 'Lesão odontogênica revestida por epitélio com paliçada basal e retículo estrelado, como o ameloblastoma, mas com o achado que a define: células fantasmas — queratinócitos grandes eosinofílicos que perderam o núcleo e deixaram um vazio no lugar dele — que calcificam e induzem dentinoide. β-catenina nuclear reflete a alteração de CTNNB1.',
    criteria: [
      'Revestimento epitelial com camada basal colunar em paliçada de polarização reversa e retículo estrelado suprajacente.',
      'Células fantasmas: queratinócitos alargados eosinofílicos com o contorno nuclear vazio, que calcificam progressivamente.',
      'Material dentinoide justaepitelial, indutivo, em parte dos casos.',
      'β-catenina nuclear e citoplasmática, refletindo mutação de CTNNB1.',
      'A forma sólida neoplásica é o tumor dentinogênico de células fantasmas; o carcinoma odontogênico de células fantasmas é a contraparte maligna, com atipia e mitoses.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [80, 100], pattern: 'N', note: 'reflete CTNNB1 mutado; o ameloblastoma é negativo' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck19', pct: [80, 100] },
      { marker: 'ck14', pct: [70, 95] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [80, 95] },
      { marker: 'ck56', pct: [85, 100] },
      { marker: 'calretinina', pct: [20, 60], note: 'no retículo estrelado, como no ameloblastoma' },
      { marker: 'brafv600e', pct: [0, 10], note: 'o negativo que o separa do ameloblastoma, que é BRAF mutado' },
      { marker: 'ciclinad1', pct: [40, 80], note: 'acompanha a ativação de β-catenina' },
      { marker: 'p53', pct: [0, 10], note: 'aberrante no carcinoma de células fantasmas' },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Ameloblastoma: sem células fantasmas, BRAF V600E positivo, β-catenina negativa.',
      'Craniofaringioma adamantinomatoso: células fantasmas e β-catenina nuclear também, mas na região selar.',
      'Pilomatricoma: mesmas células fantasmas e mesma β-catenina, na pele.',
      'Odontoma e fibro-odontoma: tecidos dentais organizados sem revestimento cístico ameloblástico.',
      'Ceratocisto odontogênico: paraqueratina corrugada, sem células fantasmas nem calcificação.',
    ],
    molecular: 'CTNNB1 mutado, compartilhado com craniofaringioma adamantinomatoso e pilomatricoma.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'cementoblastoma',
    name: 'Cementoblastoma e osteoblastoma dos maxilares',
    aka: ['cementoblastoma', 'cementoblastoma benigno', 'osteoblastoma dos maxilares'],
    behavior: 'benigno',
    sites: [
      { site: 'maxilares', role: 'primario', freq: 2 },
      { site: 'osso', role: 'primario', freq: 1 },
    ],
    cells: ['osteoblastico', 'fusocelular', 'gigantes'],
    architecture: ['trabecular', 'nodular'],
    features: ['osteoide', 'calcificacao', 'gigantes-osteoclasticas', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Massa mineralizada fundida à raiz de um molar inferior, com trabéculas grosseiras de material cementoide revestidas por cementoblastos proeminentes e borda radiolucente de tecido não mineralizado; o cementoblastoma é o único tumor odontogênico verdadeiro de origem mesenquimal cementária, e a fusão com a raiz é o critério.',
    criteria: [
      'Massa mineralizada em continuidade direta com a raiz do dente, com reabsorção radicular e borda radiolucente.',
      'Trabéculas grosseiras de material cementoide e osteoide com linhas de reversão proeminentes, revestidas por cementoblastos volumosos.',
      'Borda periférica de tecido não mineralizado com trabéculas radiadas e células gigantes osteoclásticas.',
      'Pleomorfismo nuclear focal nos cementoblastos é comum e não indica malignidade, como no osteoblastoma.',
      'Ausência de fusão com a raiz sugere osteoblastoma ou displasia cemento-óssea.',
    ],
    markers: [
      { marker: 'satb2', pct: [80, 100], note: 'linhagem osteoblástica e cementoblástica' },
      { marker: 'runx2', pct: [70, 95] },
      { marker: 'cd68', pct: [50, 85], note: 'células gigantes osteoclásticas periféricas' },
      { marker: 'catepsinak', pct: [50, 85] },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'mdm2', pct: [0, 5], note: 'o negativo que separa do osteossarcoma de baixo grau dos maxilares' },
      { marker: 'cdk4', pct: [0, 5] },
      { marker: 'h3g34', pct: 0, note: 'o negativo que exclui tumor de células gigantes' },
      { marker: 'sma', pct: [10, 40] },
      { marker: 'ae1ae3', pct: 0, note: 'o negativo que exclui componente odontogênico epitelial' },
      { marker: 'ck19', pct: 0 },
      { marker: 'ki67', pct: [1, 8] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Osteossarcoma de baixo grau dos maxilares: MDM2 e CDK4 amplificados, permeação do osso.',
      'Displasia cemento-óssea periapical: não se funde à raiz, em dentes vitais, multifocal.',
      'Osteoblastoma e osteoma osteoide: não ligados à raiz, com nicho central no osteoide osteoide.',
      'Odontoma complexo: contém esmalte e dentina organizados.',
      'Hipercementose: espessamento regular do cemento sem massa nodular.',
    ],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'carcinoma-ceruminoso',
    name: 'Tumores ceruminosos da orelha externa',
    aka: ['adenoma ceruminoso', 'ceruminoma', 'adenocarcinoma ceruminoso', 'ceruminous adenoma'],
    behavior: 'intermediario',
    sites: [{ site: 'orelha', role: 'primario', freq: 2 }],
    cells: ['glandular', 'epitelioide', 'oncocitico'],
    architecture: ['glandulas', 'trabecular', 'cistico', 'infiltrativo'],
    features: ['mitoses-raras', 'hialinizacao', 'perineural'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumores das glândulas ceruminosas do conduto auditivo externo, com o padrão bifásico típico dos anexos: camada luminal cuboide com secreção por decapitação e grânulos de ceruminina amarelo-castanhos, sobre camada mioepitelial. O adenoma é circunscrito; o adenocarcinoma infiltra, e o adenoide cístico ceruminoso é a variante maligna mais comum.',
    criteria: [
      'Localização no terço externo cartilaginoso do conduto auditivo, onde estão as glândulas ceruminosas.',
      'Padrão bifásico com camada luminal de células cuboides ou colunares com decapitação e camada basal mioepitelial contínua no adenoma.',
      'Grânulos de ceruminina (lipofuscina) amarelo-castanhos no citoplasma luminal: achado característico.',
      'Adenocarcinoma: perda da camada mioepitelial contínua, infiltração, atipia e invasão perineural.',
      'Exclusão de metástase e de extensão de tumor de parótida, que é o diferencial prático.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100], note: 'luminal' },
      { marker: 'p63', pct: [70, 95], note: 'camada mioepitelial contínua no adenoma; descontínua ou ausente no carcinoma' },
      { marker: 'calponina', pct: [60, 90] },
      { marker: 's100', pct: [50, 85] },
      { marker: 'sox10', pct: [60, 90] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'cd117', pct: [30, 70], note: 'luminal, sobretudo na variante adenoide cística' },
      { marker: 'myb', pct: [20, 60], note: 'na variante adenoide cística ceruminosa' },
      { marker: 'gcdfp15', pct: [40, 80], note: 'diferenciação apócrina' },
      { marker: 'ttf1', pct: 0, note: 'o negativo que separa do tumor neuroendócrino de orelha média e do saco endolinfático' },
      { marker: 'sinaptofisina', pct: [0, 15] },
      { marker: 'ki67', pct: [1, 30], note: 'baixo no adenoma e alto no carcinoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor neuroendócrino de orelha média: sinaptofisina e cromogranina positivas, CK7 e CK20 em populações distintas.',
      'Tumor do saco endolinfático: papilar com coloide, no osso petroso.',
      'Metástase e extensão de tumor de parótida: a topografia e a imagem decidem.',
      'Ceruminoma inflamatório e hiperplasia ceruminosa: sem massa nem atipia.',
      'Carcinoma adenoide cístico de glândula salivar menor: histologia idêntica, outro sítio.',
    ],
    sources: [WHO, THOMPSON],
  },
]
