/* ==========================================================================
   headneck.ts — cabeça e pescoço mucoso e odontogênico.

   Duas perguntas mandam aqui. A primeira é de etiologia: p16 em bloco na
   orofaringe (com HPV confirmado) e EBER na nasofaringe mudam estadiamento e
   prognóstico, não só a curiosidade. A segunda é a dos tumores sinonasais
   indiferenciados, um grupo que só se separa por marcador: SMARCB1, SMARCA4,
   NUT, IDH2, e o que sobra depois deles.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Head and Neck Tumours, 2022; Thompson & Bishop, Head and
   Neck Pathology, 3ª ed.; séries de Am J Surg Pathol e Head Neck Pathol).
   As fontes estão como referência de texto: as séries não foram abertas uma
   a uma, e o clone e a plataforma mudam os números.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Head and Neck Tumours (2022)'
const THOMPSON = 'Thompson & Bishop, Head and Neck Pathology, 3ª ed. (Elsevier)'
const BISHOP = 'Bishop, "Newly described tumor entities in sinonasal tract pathology", Head Neck Pathol'

export const headneck: Tumor[] = [
  {
    id: 'cec-oral',
    name: 'Carcinoma de células escamosas oral convencional',
    aka: ['carcinoma epidermoide oral', 'CEC de língua, assoalho e gengiva'],
    behavior: 'maligno',
    sites: [
      { site: 'boca', role: 'primario', freq: 3 },
      { site: 'laringe', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['escamoso', 'epitelioide'],
    architecture: ['ninhos', 'infiltrativo'],
    features: ['queratinizacao', 'desmoplasia', 'perineural', 'mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Ninhos infiltrativos de epitélio escamoso com queratinização e desmoplasia, em fumante e etilista, quase sempre com displasia na mucosa adjacente; a imuno serve para confirmar linhagem escamosa e para separar do HPV-associado da orofaringe.',
    criteria: [
      'Invasão do estroma por ninhos escamosos, com resposta desmoplásica ou inflamatória.',
      'Diferenciação escamosa: pontes intercelulares, queratinização ou p40 difuso.',
      'Profundidade de invasão medida a partir da membrana basal da mucosa adjacente normal: é ela, e não a espessura, que estadia o T na boca.',
      'Invasão perineural e linfovascular devem ser relatadas.',
      'Displasia ou carcinoma in situ adjacente apoia origem primária contra metástase.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck903', pct: [90, 100] },
      { marker: 'ck17', pct: [70, 90] },
      { marker: 'p16', pct: [5, 20], note: 'positividade em bloco é rara fora da orofaringe e não prova HPV na boca' },
      { marker: 'p53', pct: [50, 70], note: 'padrão aberrante frequente, ligado a TP53 mutado' },
      { marker: 'ck7', pct: [5, 15] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'cdx2', pct: 0 },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ebv', pct: [0, 5] },
      { marker: 'ki67', pct: [70, 90] },
    ],
    mimics: [
      'Carcinoma de orofaringe HPV-associado: não queratinizante, p16 em bloco, HPV confirmado.',
      'Carcinoma nasofaríngeo: sincicial, EBER positivo, sem queratinização.',
      'Hiperplasia pseudoepiteliomatosa: sem atipia, sem desmoplasia, base regular.',
      'Melanoma mucoso amelanótico: SOX10 e S100 positivos, queratina negativa.',
    ],
    pitfalls: [
      'Carcinoma escamoso pouco diferenciado pode perder queratinas de alto peso; p40 costuma resistir.',
      'p16 positivo focal ou citoplasmático não é "HPV positivo": só conta o padrão em bloco, nuclear e citoplasmático, em mais de 70% das células.',
    ],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'cec-orofaringe-hpv',
    name: 'Carcinoma de orofaringe HPV-associado',
    aka: ['carcinoma escamoso não queratinizante p16 positivo', 'HPV-associated oropharyngeal carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'boca', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['escamoso', 'basaloide', 'epitelioide'],
    architecture: ['ninhos', 'lencois'],
    features: ['linfoide', 'necrose', 'mitoses-altas', 'corpos-apoptoticos', 'cistico'],
    ages: ['jovem', 'adulto'],
    summary: 'Carcinoma de tonsila ou base de língua, não queratinizante, em ninhos lobulados dentro de tecido linfoide, que se apresenta como metástase cística no pescoço em adulto sem grande história de tabagismo; p16 em bloco com HPV de alto risco confirmado.',
    criteria: [
      'Localização orofaríngea: tonsila palatina, base de língua ou tecido linfoide de Waldeyer.',
      'p16 em bloco (nuclear e citoplasmático, forte, em mais de 70% das células) é o substituto aceito, mas exige contexto orofaríngeo.',
      'Confirmação por ISH de RNA de HPV de alto risco quando o p16 é o único dado e a decisão de estadiamento depende disso.',
      'Morfologia não queratinizante, com bordas de ninho lisas e apoptose abundante; a queratinização não exclui.',
      'Estadiamento próprio (AJCC 8ª ed.), diferente do HPV-negativo.',
    ],
    markers: [
      { marker: 'p16', pct: [95, 100], note: 'em bloco; é o critério de entrada' },
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p53', pct: [0, 10], note: 'padrão selvagem: TP53 íntegro, ao contrário do HPV-negativo' },
      { marker: 'rb1', pct: [70, 90], note: 'redução da expressão pela E7; pouco usada na prática' },
      { marker: 'ebv', pct: [0, 5] },
      { marker: 'ck7', pct: [5, 20] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'sinaptofisina', pct: [0, 5], note: 'quando difusa, pense em carcinoma neuroendócrino HPV-associado, que é agressivo' },
      { marker: 'ki67', pct: [80, 95] },
    ],
    mimics: [
      'Metástase cística no pescoço interpretada como cisto branquial: qualquer cisto cervical em adulto exige p16 e busca de primário na tonsila.',
      'Carcinoma nasofaríngeo: EBER positivo, p16 negativo.',
      'Carcinoma escamoso basaloide HPV-negativo: p53 aberrante, p16 negativo.',
    ],
    pitfalls: [
      'Carcinoma neuroendócrino de pequenas células HPV-associado é p16 em bloco e comporta-se como pequenas células: procure sinaptofisina e INSM1 antes de assumir escamoso.',
      'p16 em bloco fora da orofaringe (laringe, seios, boca) não autoriza o diagnóstico de HPV-associado.',
    ],
    molecular: 'HPV de alto risco transcricionalmente ativo (E6/E7), sobretudo genótipo 16.',
    sources: [WHO, THOMPSON, 'AJCC Cancer Staging Manual, 8ª ed., capítulo de orofaringe HPV-mediado'],
  },
  {
    id: 'carcinoma-nasofaringeo',
    name: 'Carcinoma nasofaríngeo',
    aka: ['carcinoma indiferenciado tipo nasofaríngeo', 'linfoepitelioma', 'nasopharyngeal carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['sincicial', 'epitelioide', 'escamoso'],
    architecture: ['lencois', 'ninhos'],
    features: ['linfoide', 'nucleolo', 'mitoses-altas'],
    ages: ['jovem', 'adulto'],
    summary: 'Lençóis de células sinciciais de limites indistintos, núcleo vesiculoso e nucléolo grande, afogados em linfócitos e plasmócitos; EBER positivo em praticamente todos os casos indiferenciados, e muitas vezes o primeiro material é um linfonodo cervical.',
    criteria: [
      'Célula sincicial com nucléolo eosinofílico proeminente, em fundo linfoplasmocitário denso.',
      'Confirmação de linhagem epitelial por pan-queratina ou p40, que desfaz a impressão de linfoma.',
      'EBER por hibridização in situ positivo no subtipo indiferenciado e no não queratinizante diferenciado.',
      'O subtipo queratinizante é o único que pode ser EBER negativo, e é o de pior resposta à radioterapia.',
      'Metástase cervical alta com este padrão obriga a biopsiar a nasofaringe.',
    ],
    markers: [
      { marker: 'ebv', pct: [95, 100], note: 'EBER-ISH; o LMP1 é bem menos sensível' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p40', pct: [85, 95] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'cam52', pct: [80, 95] },
      { marker: 'p16', pct: [10, 25], note: 'pode ser positivo sem HPV; não use aqui' },
      { marker: 'cd45', pct: 0, note: 'o negativo que exclui linfoma' },
      { marker: 'cd30', pct: [0, 5] },
      { marker: 'cd20', pct: 0 },
      { marker: 'cd3', pct: 0 },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'melana', pct: 0 },
      { marker: 'pdl1', pct: [60, 90], note: 'preditivo, não diagnóstico' },
      { marker: 'ki67', pct: [70, 95] },
    ],
    mimics: [
      'Linfoma difuso de grandes células B: CD45 e CD20 positivos, queratina negativa.',
      'Melanoma mucoso: SOX10 e S100 positivos.',
      'Carcinoma linfoepitelial de outros sítios (salivar, pulmão, estômago): mesma imuno, o sítio é que decide.',
      'Hiperplasia linfoide da nasofaringe: sem célula sincicial atípica, queratina só no epitélio de superfície.',
    ],
    pitfalls: ['A queratina pode ser fraca e focal no material esmagado de linfonodo; repita com CAM5.2 e p40 antes de assumir linfoma.'],
    molecular: 'Vírus Epstein-Barr clonal; DNA viral plasmático serve de seguimento.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'papiloma-invertido',
    name: 'Papiloma sinonasal invertido',
    aka: ['papiloma schneideriano invertido', 'inverted sinonasal papilloma'],
    behavior: 'benigno',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 3 }],
    cells: ['escamoso', 'epitelioide'],
    architecture: ['infiltrativo', 'ninhos', 'cistico'],
    features: ['mitoses-raras', 'eosinofilos'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Epitélio escamoso e respiratório espesso que cresce invertido para dentro do estroma em ninhos de contorno liso, com microcistos cheios de neutrófilos; unilateral, recorrente, e com risco de carcinoma escamoso ao longo do tempo.',
    criteria: [
      'Crescimento endofítico do epitélio para dentro do estroma, com membrana basal íntegra e contornos arredondados.',
      'Epitélio escamoso ou transicional espessado, com microabscessos intraepiteliais.',
      'Ausência de atipia significativa e de desmoplasia: a presença de qualquer uma delas obriga a procurar carcinoma.',
      'Unilateralidade; lesão bilateral favorece pólipo inflamatório.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ck7', pct: [40, 70], note: 'no componente respiratório de superfície' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p16', pct: [5, 15] },
      { marker: 'p53', pct: [0, 10], note: 'aberrante sugere transformação maligna' },
      { marker: 'ki67', pct: [10, 30], note: 'basal e parabasal; difuso e alto favorece carcinoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma escamoso bem diferenciado: atipia, desmoplasia, mitoses em camadas altas.',
      'Papiloma oncocítico: epitélio colunar multicamadas oncocítico, mesma arquitetura invertida.',
      'Pólipo inflamatório: sem espessamento epitelial, estroma edematoso com eosinófilos.',
    ],
    molecular: 'Mutações de EGFR (exon 20) na maioria; KRAS mutado aparece nos que carcinomatizam.',
    sources: [WHO, THOMPSON, BISHOP],
  },
  {
    id: 'adenocarcinoma-intestinal-sinonasal',
    name: 'Adenocarcinoma sinonasal de tipo intestinal',
    aka: ['ITAC', 'intestinal-type sinonasal adenocarcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'anel-sinete'],
    architecture: ['glandulas', 'papilar', 'cribriforme'],
    features: ['mucina', 'necrose', 'mitoses-altas', 'desmoplasia'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Adenocarcinoma do etmoide que reproduz mucosa intestinal, com caliciformes e até células de Paneth, em marceneiro ou trabalhador de couro exposto a pó de madeira; imunofenótipo indistinguível de metástase colorretal, de modo que a exclusão clínica é obrigatória.',
    criteria: [
      'Epitélio de tipo intestinal: colunar com caliciformes, borda em escova, às vezes muscular da mucosa rudimentar.',
      'Localização em etmoide ou fenda olfatória; história ocupacional de pó de madeira ou couro apoia.',
      'Exclusão de adenocarcinoma colorretal metastático por colonoscopia e imagem: a imuno não separa.',
      'Graduação por padrão (papilar, colônico, sólido, mucinoso, misto) tem valor prognóstico.',
    ],
    markers: [
      { marker: 'cdx2', pct: [90, 100] },
      { marker: 'ck20', pct: [85, 95] },
      { marker: 'vilina', pct: [80, 95] },
      { marker: 'muc2', pct: [70, 90] },
      { marker: 'ck7', pct: [40, 60], note: 'mais frequente que no colorretal verdadeiro, mas não confiável' },
      { marker: 'satb2', pct: [30, 60], note: 'não separa do colorretal metastático' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p53', pct: [40, 60] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'p40', pct: [0, 5] },
      { marker: 's100', pct: [0, 5] },
      { marker: 'ki67', pct: [50, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma colorretal metastático: imuno idêntica; só a clínica separa.',
      'Adenocarcinoma sinonasal de tipo não intestinal: túbulos uniformes, CK7 positivo, CDX2 e CK20 negativos.',
      'Adenocarcinoma de baixo grau de glândulas seromucinosas: bem delimitado, sem necrose.',
    ],
    pitfalls: ['CDX2 e CK20 positivos num tumor nasal não significam metástase: o primário sinonasal tem o mesmo perfil.'],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'snuc',
    name: 'Carcinoma sinonasal indiferenciado (SNUC)',
    aka: ['sinonasal undifferentiated carcinoma', 'SNUC IDH2-mutante'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'pequenas-redondas', 'pleomorfico'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma de células médias a grandes em lençóis, com necrose extensa, altíssimo índice mitótico e nenhuma diferenciação escamosa ou glandular; é diagnóstico de exclusão depois que SMARCB1, SMARCA4, NUT, EBER e HPV foram descartados, e a maioria carrega mutação de IDH2.',
    criteria: [
      'Carcinoma de alto grau sem diferenciação escamosa, glandular nem neuroendócrina evidente.',
      'Queratina positiva, que o separa de linfoma, melanoma, rabdomiossarcoma e neuroblastoma olfatório.',
      'INI1 e BRG1 retidos, NUT negativo, EBER negativo e HPV negativo: sem isso o diagnóstico não se sustenta.',
      'Sinaptofisina focal é aceita; positividade difusa com cromogranina reclassifica como carcinoma neuroendócrino.',
      'Mutação de IDH2 (R172) apoia fortemente e hoje define a maioria dos casos.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'ini1', pct: 0, note: 'retido por definição; a perda define outra entidade' },
      { marker: 'brg1', pct: 0, note: 'retido por definição' },
      { marker: 'nut', pct: 0 },
      { marker: 'ebv', pct: 0 },
      { marker: 'p16', pct: [10, 30], note: 'sem HPV; o p16 aqui é ruído' },
      { marker: 'p40', pct: [0, 10], note: 'focal no máximo; difuso é carcinoma escamoso' },
      { marker: 'sinaptofisina', pct: [20, 40], note: 'focal e aceita' },
      { marker: 'cromogranina', pct: [0, 10] },
      { marker: 'insm1', pct: [10, 30] },
      { marker: 's100', pct: [0, 10] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'desmina', pct: 0 },
      { marker: 'p53', pct: [30, 50] },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Carcinoma sinonasal SMARCB1-deficiente: INI1 perdido.',
      'Carcinoma NUT: NUT nuclear em pontilhado, diferenciação escamosa abrupta.',
      'Neuroblastoma olfatório de alto grau: S100 sustentacular, queratina negativa ou focal.',
      'Carcinoma neuroendócrino de pequenas células: sinaptofisina e INSM1 difusos.',
      'Melanoma mucoso e rabdomiossarcoma alveolar: SOX10 ou desmina/miogenina positivos.',
    ],
    molecular: 'Mutação de IDH2 R172 na maioria; o anticorpo IDH1 R132H não a detecta.',
    sources: [WHO, BISHOP, 'Dogan et al., Mod Pathol (2019), IDH2 em carcinomas sinonasais indiferenciados'],
  },
  {
    id: 'carcinoma-smarcb1-sinonasal',
    name: 'Carcinoma sinonasal SMARCB1-deficiente',
    aka: ['carcinoma sinonasal INI1-deficiente', 'SMARCB1-deficient sinonasal carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'rabdoide', 'basaloide', 'pequenas-redondas'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma sinonasal de células basaloides ou rabdoides monótonas em lençóis, morfologicamente parecido com SNUC, definido pela perda completa de INI1 no núcleo com controle interno preservado; curso agressivo e resposta pobre.',
    criteria: [
      'Perda total da expressão nuclear de INI1 (SMARCB1) nas células tumorais, com endotélio e linfócitos retidos como controle interno.',
      'Queratina positiva, o que o separa de tumor rabdoide extrarrenal e de sarcoma epitelioide.',
      'Morfologia basaloide ou rabdoide, às vezes com diferenciação glandular ou escamosa focal (variante adenocarcinoma-símile).',
      'NUT negativo: o carcinoma NUT também pode ser basaloide.',
    ],
    markers: [
      { marker: 'ini1', pct: [95, 100], note: 'o positivo aqui é a perda; é o critério definidor' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'p63', pct: [30, 60] },
      { marker: 'p40', pct: [10, 40], note: 'menos frequente que p63' },
      { marker: 'ck56', pct: [20, 50] },
      { marker: 'nut', pct: 0 },
      { marker: 'brg1', pct: 0, note: 'retido; a perda define o SMARCA4-deficiente' },
      { marker: 'sinaptofisina', pct: [10, 30], note: 'focal' },
      { marker: 'cromogranina', pct: [0, 10] },
      { marker: 's100', pct: [0, 15] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'ki67', pct: [60, 90] },
    ],
    mimics: [
      'SNUC: INI1 retido.',
      'Tumor rabdoide extrarrenal: INI1 também perdido, mas queratina fraca ou negativa e ocorre em criança.',
      'Carcinoma NUT: NUT positivo, INI1 retido.',
      'Melanoma mucoso: SOX10 positivo.',
    ],
    molecular: 'Inativação bialélica de SMARCB1 (deleção ou mutação).',
    sources: [WHO, BISHOP, 'Agaimy et al., Am J Surg Pathol, carcinomas sinonasais SMARCB1-deficientes'],
  },
  {
    id: 'carcinoma-nut',
    name: 'Carcinoma NUT',
    aka: ['carcinoma da linha média NUT', 'NUT carcinoma', 'NMC'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 1 },
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'primario', freq: 1 },
      { site: 'boca', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'basaloide', 'pequenas-redondas'],
    architecture: ['lencois', 'ninhos'],
    features: ['necrose', 'mitoses-altas', 'queratinizacao'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Carcinoma indiferenciado de células monótonas médias com queratinização abrupta no meio do lençol indiferenciado, em jovem, na linha média do corpo; o anticorpo NUT dá marcação nuclear em pontilhado e fecha o diagnóstico, cuja sobrevida mediana é de poucos meses.',
    criteria: [
      'Marcação nuclear de NUT em mais de 50% das células, tipicamente em pontilhado grosseiro.',
      'Morfologia de carcinoma indiferenciado com focos de queratinização abrupta (nem sempre presentes).',
      'Queratina positiva; confirmação molecular do rearranjo NUTM1 quando a imuno é duvidosa.',
      'Idade jovem e sítio de linha média apoiam, mas não são obrigatórios.',
    ],
    markers: [
      { marker: 'nut', pct: [95, 100], note: 'critério definidor; clone C52B1' },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'p63', pct: [80, 95] },
      { marker: 'p40', pct: [70, 90] },
      { marker: 'ck56', pct: [50, 80] },
      { marker: 'cd34', pct: [20, 50], note: 'positividade curiosa e clássica neste tumor' },
      { marker: 'ini1', pct: 0, note: 'retido' },
      { marker: 'p16', pct: [20, 40] },
      { marker: 'ebv', pct: 0 },
      { marker: 'sinaptofisina', pct: [10, 25] },
      { marker: 'cd45', pct: 0 },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Carcinoma escamoso pouco diferenciado: NUT negativo.',
      'SNUC e carcinoma SMARCB1-deficiente: NUT negativo, INI1 perdido no segundo.',
      'Tumores de células redondas (Ewing, rabdomiossarcoma): queratina negativa.',
    ],
    pitfalls: ['Marcação NUT fraca e difusa sem pontilhado pode ser inespecífica; exija o padrão pontilhado ou confirme por FISH.'],
    molecular: 'Fusão NUTM1, mais comum BRD4::NUTM1; também BRD3 e NSD3.',
    sources: [WHO, BISHOP, 'French, Annu Rev Pathol, carcinoma NUT'],
  },
  {
    id: 'neuroblastoma-olfatorio',
    name: 'Neuroblastoma olfatório',
    aka: ['estesioneuroblastoma', 'olfactory neuroblastoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'encefalo', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino'],
    architecture: ['ninhos', 'lencois', 'rosetas'],
    features: ['calcificacao', 'necrose', 'mitoses-raras', 'hemorragia'],
    ages: ['jovem', 'adulto', 'idoso'],
    summary: 'Tumor da fenda olfatória em lóbulos separados por estroma vascularizado, com células pequenas em fundo neurofibrilar, rosetas de Homer Wright e, no baixo grau, mitoses escassas; as células sustentaculares S100 positivas na periferia dos ninhos são a assinatura.',
    criteria: [
      'Localização na fenda olfatória ou lâmina cribriforme, com massa dando-se em ampulheta pela base do crânio.',
      'Arquitetura lobular com matriz neurofibrilar de fundo.',
      'Sinaptofisina e cromogranina positivas com queratina negativa ou apenas focal.',
      'Células sustentaculares S100 positivas dispostas na periferia dos lóbulos (perdem-se nos graus altos de Hyams).',
      'Graduação de Hyams (I a IV) por arquitetura, matriz, pleomorfismo, mitoses, necrose e rosetas.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [90, 100] },
      { marker: 'cromogranina', pct: [70, 90] },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 's100', pct: [80, 95], pattern: 'N', note: 'só nas sustentaculares periféricas; difusa nas células tumorais fala contra' },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'nse', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [0, 15], note: 'focal quando presente; difusa reclassifica como carcinoma neuroendócrino' },
      { marker: 'nkx22', pct: [20, 40], note: 'pode confundir com Ewing' },
      { marker: 'cd99', pct: [10, 30], note: 'raramente membranoso forte' },
      { marker: 'p40', pct: 0 },
      { marker: 'cd45', pct: 0 },
      { marker: 'desmina', pct: 0 },
      { marker: 'sox10', pct: [10, 30], note: 'nas sustentaculares' },
      { marker: 'ki67', pct: [10, 50], note: 'sobe com o grau de Hyams' },
    ],
    mimics: [
      'Carcinoma neuroendócrino sinonasal: queratina difusa, sem sustentaculares, mitoses e necrose muito maiores.',
      'Ewing sinonasal: CD99 membranoso difuso, NKX2.2, fusão EWSR1.',
      'Rabdomiossarcoma alveolar: desmina e miogenina.',
      'Melanoma mucoso: SOX10 e HMB-45 nas próprias células tumorais.',
      'Adenoma pituitário invasivo do seio esfenoidal: hormônios hipofisários, PIT1/TPIT/SF-1.',
    ],
    sources: [WHO, THOMPSON, 'Hyams, Tumors of the upper respiratory tract and ear (AFIP), graduação'],
  },
  {
    id: 'melanoma-mucoso',
    name: 'Melanoma mucoso de cabeça e pescoço',
    aka: ['melanoma sinonasal', 'melanoma oral', 'mucosal melanoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'fusocelular', 'pleomorfico', 'plasmocitoide', 'pequenas-redondas'],
    architecture: ['lencois', 'ninhos'],
    features: ['melanina', 'necrose', 'mitoses-altas', 'nucleolo', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Melanoma de mucosa nasal ou oral, com frequência amelanótico, que imita carcinoma, linfoma e sarcoma na mesma lâmina; prognóstico muito pior que o cutâneo, sem Breslow aplicável, e com perfil molecular distinto (KIT em vez de BRAF).',
    criteria: [
      'Proliferação melanocítica maligna na mucosa, com componente juncional ou melanose atípica adjacente quando presente.',
      'Confirmação por dois marcadores melanocíticos, sendo SOX10 ou S100 um deles.',
      'Exclusão de carcinoma (pan-queratina), linfoma (CD45) e sarcoma de células redondas.',
      'A pigmentação pode faltar em metade dos casos e não é critério.',
    ],
    markers: [
      { marker: 's100', pct: [90, 100] },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'melana', pct: [70, 90] },
      { marker: 'hmb45', pct: [70, 90] },
      { marker: 'mitf', pct: [70, 90] },
      { marker: 'tirosinase', pct: [60, 85] },
      { marker: 'prame', pct: [60, 85] },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [0, 5], note: 'positividade focal é armadilha descrita' },
      { marker: 'p40', pct: 0 },
      { marker: 'cd45', pct: 0 },
      { marker: 'sinaptofisina', pct: [0, 10] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'cd117', pct: [30, 60], note: 'reflete a frequência de alterações de KIT nos mucosos' },
      { marker: 'brafv600e', pct: [0, 10], note: 'bem menos frequente que no melanoma cutâneo' },
      { marker: 'ki67', pct: [50, 90] },
    ],
    mimics: [
      'SNUC e carcinoma indiferenciado: queratina positiva, SOX10 negativo.',
      'Neuroblastoma olfatório: S100 só sustentacular, sinaptofisina difusa.',
      'Plasmocitoma: CD138 e restrição de cadeia leve.',
      'Rabdomiossarcoma alveolar: desmina e miogenina.',
    ],
    pitfalls: ['O melanoma mucoso pode ser HMB-45 e Melan-A negativos quando fusocelular; SOX10 é o mais confiável.'],
    molecular: 'Mutação ou amplificação de KIT em parte; BRAF V600E é incomum, ao contrário do cutâneo.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'teratocarcinossarcoma-sinonasal',
    name: 'Teratocarcinossarcoma sinonasal',
    aka: ['sinonasal teratocarcinosarcoma', 'SNTCS'],
    behavior: 'maligno',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'fusocelular', 'blastematoso', 'escamoso', 'glandular'],
    architecture: ['ninhos', 'glandulas', 'fasciculos'],
    features: ['necrose', 'mitoses-altas', 'estriacoes', 'condroide', 'osteoide'],
    ages: ['adulto'],
    sex: 'm',
    summary: 'Tumor sinonasal raro que mistura, num só bloco, epitélio escamoso e glandular imaturo, estroma sarcomatoso, ilhas de cartilagem ou osso e, quase sempre, ninhos de células com citoplasma claro glicogenado de aspecto fetal; a mistura é o diagnóstico.',
    criteria: [
      'Presença simultânea de componente epitelial (escamoso e glandular), mesenquimal maligno e neuroepitelial imaturo.',
      'Ninhos de epitélio escamoso fetal com citoplasma claro rico em glicogênio são muito característicos.',
      'Ausência de teratoma maduro organoide e de germinativo (SALL4 e OCT4 negativos).',
      'Componente rabdomioblástico é comum e não exclui.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [90, 100], note: 'só no componente epitelial' },
      { marker: 'p40', pct: [70, 90], note: 'no componente escamoso' },
      { marker: 'sinaptofisina', pct: [60, 85], note: 'no componente neuroepitelial' },
      { marker: 'desmina', pct: [50, 80], note: 'no componente rabdomioblástico' },
      { marker: 'miogenina', pct: [40, 70] },
      { marker: 's100', pct: [40, 70], note: 'cartilagem e neural' },
      { marker: 'betacatenina', pct: [70, 95], note: 'nuclear no epitélio fetal e no estroma; reflete alteração de CTNNB1' },
      { marker: 'sall4', pct: [0, 20] },
      { marker: 'oct4', pct: 0 },
      { marker: 'afp', pct: [0, 20] },
      { marker: 'ini1', pct: 0, note: 'retido' },
      { marker: 'ki67', pct: [50, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Teratoma imaturo: organoide, sem componente carcinomatoso franco, em criança.',
      'Carcinossarcoma: sem componente neuroepitelial nem epitélio fetal.',
      'Rabdomiossarcoma: puro, sem epitélio maligno.',
    ],
    molecular: 'Alterações de CTNNB1 (β-catenina) na maioria dos casos estudados.',
    sources: [WHO, BISHOP],
  },
  {
    id: 'sarcoma-bifenotipico-sinonasal',
    name: 'Sarcoma bifenotípico sinonasal',
    aka: ['biphenotypic sinonasal sarcoma', 'sarcoma de baixo grau com diferenciação neural e miogênica'],
    behavior: 'intermediario',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 1 }],
    cells: ['fusocelular'],
    architecture: ['fasciculos', 'infiltrativo', 'hemangiopericitoma'],
    features: ['mitoses-raras', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Sarcoma sinonasal de baixo grau, em fascículos de células fusiformes monótonas que envolvem e arrastam consigo glândulas respiratórias de superfície hiperplásicas; o achado que o define é a coexpressão de S100 com actina de músculo liso, sem SOX10.',
    criteria: [
      'Proliferação fusocelular infiltrativa, monótona, com mitoses escassas e sem necrose.',
      'Glândulas respiratórias aprisionadas dentro do tumor, muitas vezes com metaplasia escamosa.',
      'Coexpressão de S100 (difusa) e marcador miogênico (SMA ou actina) nas mesmas células.',
      'SOX10 negativo: é o que o separa de schwannoma e de MPNST.',
      'Confirmação por fusão PAX3, mais comum PAX3::MAML3.',
    ],
    markers: [
      { marker: 's100', pct: [90, 100], note: 'difusa, ao contrário do padrão sustentacular' },
      { marker: 'sox10', pct: [0, 5], note: 'o negativo é critério' },
      { marker: 'sma', pct: [80, 95] },
      { marker: 'msa', pct: [60, 85] },
      { marker: 'calponina', pct: [50, 80] },
      { marker: 'betacatenina', pct: [50, 80], pattern: 'N' },
      { marker: 'desmina', pct: [10, 30] },
      { marker: 'miogenina', pct: [10, 30], note: 'focal, quando há diferenciação rabdomioblástica' },
      { marker: 'myod1', pct: [10, 30] },
      { marker: 'cd34', pct: [10, 30] },
      { marker: 'stat6', pct: 0 },
      { marker: 'ae1ae3', pct: [0, 5], note: 'só nas glândulas aprisionadas' },
      { marker: 'ki67', pct: [5, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor fibroso solitário: STAT6 nuclear, S100 negativo.',
      'Schwannoma celular: SOX10 positivo, SMA negativa.',
      'Fibrossarcoma e MPNST de baixo grau: sem coexpressão, H3K27me3 pode estar perdido no MPNST.',
      'Fasciite nodular: USP6, mais frouxa e com mitoses fáceis.',
    ],
    molecular: 'Fusão PAX3::MAML3 na maioria; também PAX3::NCOA1 e outros parceiros.',
    sources: [WHO, BISHOP, 'Lewis et al., Am J Surg Pathol (2012), sarcoma bifenotípico sinonasal'],
  },
  {
    id: 'angiofibroma-nasofaringeo',
    name: 'Angiofibroma nasofaríngeo juvenil',
    aka: ['angiofibroma juvenil', 'juvenile nasopharyngeal angiofibroma'],
    behavior: 'benigno',
    sites: [{ site: 'nariz-seios', role: 'primario', freq: 2 }],
    cells: ['fusocelular', 'estreladas', 'vasoformativo'],
    architecture: ['infiltrativo'],
    features: ['hemorragia', 'hialinizacao', 'mitoses-raras', 'vasos-espessos'],
    ages: ['crianca', 'jovem'],
    sex: 'm',
    summary: 'Massa vascular do teto da nasofaringe em adolescente do sexo masculino com epistaxe de repetição, feita de vasos em fenda sem camada muscular completa dentro de estroma fibroso com células estreladas; a β-catenina nuclear no estroma confirma quando o material é fragmentado.',
    criteria: [
      'Adolescente do sexo masculino com massa no forame esfenopalatino e epistaxe.',
      'Vasos de calibre variável, em fenda ou estrelados, com parede muscular ausente ou incompleta.',
      'Estroma fibroso com células estreladas e fusiformes, sem atipia nem mitoses.',
      'Biópsia é evitada pelo risco de sangramento; o diagnóstico costuma ser da peça pós-embolização.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [70, 95], pattern: 'N', note: 'nuclear nas células estromais, não nos vasos' },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'cd34', pct: [90, 100], note: 'só o endotélio' },
      { marker: 'cd31', pct: [90, 100], note: 'só o endotélio' },
      { marker: 'ar', pct: [50, 80], note: 'receptor de androgênio no estroma; explica a idade e o sexo' },
      { marker: 'sma', pct: [30, 60], note: 'parede vascular incompleta' },
      { marker: 's100', pct: [0, 5] },
      { marker: 'stat6', pct: 0 },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor fibroso solitário: STAT6 nuclear.',
      'Pólipo antrocoanal com estroma atípico: sem o padrão vascular, em outro sítio.',
      'Angiofibroma-símile pós-traumático: sem β-catenina nuclear, sem o contexto.',
    ],
    molecular: 'Mutações de CTNNB1 no estroma; associação com polipose adenomatosa familiar.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'ameloblastoma',
    name: 'Ameloblastoma',
    aka: ['ameloblastoma convencional', 'ameloblastoma sólido multicístico'],
    behavior: 'intermediario',
    sites: [{ site: 'maxilares', role: 'primario', freq: 3 }],
    cells: ['basaloide', 'epitelioide', 'escamoso'],
    architecture: ['ninhos', 'palicada', 'plexiforme', 'cistico'],
    features: ['mitoses-raras', 'estroma-mixoide'],
    ages: ['jovem', 'adulto'],
    summary: 'Tumor odontogênico epitelial da mandíbula posterior, em ilhas e cordões com camada basal colunar em paliçada de núcleos invertidos e polarização reversa, envolvendo um centro frouxo de retículo estrelado; localmente agressivo e recidivante, mas benigno.',
    criteria: [
      'Camada periférica de células colunares altas com núcleo polarizado para longe da membrana basal (polarização reversa) e vacuolização subnuclear.',
      'Centro de células frouxamente arranjadas, tipo retículo estrelado.',
      'Padrões folicular, plexiforme, acantomatoso, granular, desmoplásico ou basaloide, sem valor prognóstico entre si.',
      'Radiolucidez multiloculada em favo de mel na mandíbula posterior.',
      'BRAF V600E presente na maioria dos mandibulares e útil quando se cogita terapia-alvo.',
    ],
    markers: [
      { marker: 'brafv600e', pct: [60, 85], note: 'mais frequente nos mandibulares; os maxilares tendem a SMO mutado' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [70, 90] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'calretinina', pct: [50, 80], note: 'nas células do retículo estrelado' },
      { marker: 'ck14', pct: [70, 90] },
      { marker: 'betacatenina', pct: [10, 30], pattern: 'N' },
      { marker: 'berep4', pct: [40, 70] },
      { marker: 'ki67', pct: [2, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma ameloblástico: atipia, mitoses frequentes, necrose, Ki-67 alto.',
      'Cisto odontogênico ceratocístico: parede fina, camada basal em paliçada mas sem retículo estrelado, superfície paraqueratinizada corrugada.',
      'Fibroma ameloblástico: componente ectomesenquimal mixoide neoplásico junto, em paciente mais jovem.',
      'Carcinoma basocelular da pele invadindo a mandíbula: BerEP4 forte, contexto cutâneo.',
    ],
    molecular: 'BRAF V600E na maioria dos mandibulares; SMO mutado nos maxilares.',
    sources: [WHO, 'WHO Classification of Head and Neck Tumours, capítulo de tumores odontogênicos', THOMPSON],
  },
  {
    id: 'ceratocisto-odontogenico',
    name: 'Cisto odontogênico ceratocístico',
    aka: ['ceratocisto odontogênico', 'tumor odontogênico ceratocístico', 'odontogenic keratocyst'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 3 }],
    cells: ['escamoso', 'basaloide'],
    architecture: ['cistico', 'palicada'],
    features: ['queratinizacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Cisto do ramo e corpo posterior da mandíbula com revestimento escamoso fino e uniforme de cinco a oito camadas, camada basal cuboide ou colunar em paliçada e superfície paraqueratinizada corrugada, sem cristas epiteliais; recidiva com frequência e é o marcador do síndrome de Gorlin quando múltiplo.',
    criteria: [
      'Epitélio escamoso de espessura uniforme, cinco a oito camadas, sem cristas interpapilares.',
      'Camada basal em paliçada, com núcleos hipercromáticos alinhados.',
      'Superfície paraqueratinizada ondulada ou corrugada, com paraqueratina descamada na luz.',
      'Ausência de inflamação no revestimento típico: a inflamação apaga os critérios e simula cisto radicular.',
      'Múltiplos ceratocistos exigem investigar síndrome de Gorlin (PTCH1).',
    ],
    markers: [
      { marker: 'ck17', pct: [85, 100], note: 'clássica no ceratocisto, contra o cisto dentígero' },
      { marker: 'ck19', pct: [70, 90], note: 'restrita às camadas basais' },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck56', pct: [85, 100] },
      { marker: 'ki67', pct: [5, 20], note: 'nas camadas suprabasais, maior que nos outros cistos odontogênicos' },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'calretinina', pct: [0, 10], note: 'ajuda contra o ameloblastoma uniscístico, que é positivo' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Cisto dentígero: revestimento não queratinizado de duas a quatro camadas, sem paliçada.',
      'Cisto odontogênico ortoqueratinizado: ortoqueratina com camada granulosa, sem paliçada basal, recidiva pouco.',
      'Ameloblastoma unicístico: retículo estrelado e polarização reversa, calretinina positiva.',
      'Cisto radicular inflamado: epitélio hiperplásico irregular, arcadas, inflamação densa.',
    ],
    molecular: 'Mutação de PTCH1 (via hedgehog), somática ou germinativa na síndrome de Gorlin.',
    sources: [WHO, THOMPSON],
  },
  {
    id: 'mixoma-odontogenico',
    name: 'Mixoma odontogênico',
    aka: ['fibromixoma odontogênico', 'odontogenic myxoma'],
    behavior: 'benigno',
    sites: [{ site: 'maxilares', role: 'primario', freq: 2 }],
    cells: ['estreladas', 'fusocelular'],
    architecture: ['infiltrativo'],
    features: ['estroma-mixoide', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Lesão intraóssea gelatinosa dos maxilares feita de células estreladas e fusiformes esparsas em matriz mixoide abundante, sem cápsula, permeando as trabéculas ósseas; a radiologia em bolhas de sabão e o sítio fazem metade do diagnóstico.',
    criteria: [
      'Matriz mixoide abundante, alcianofílica, com celularidade baixa e uniforme.',
      'Células estreladas ou fusiformes sem atipia significativa, mitoses raras.',
      'Localização intraóssea em maxila ou mandíbula, com permeação das trabéculas.',
      'Ilhas de epitélio odontogênico inativo podem aparecer e não são necessárias.',
      'Ausência de lipoblastos e de rede vascular plexiforme afasta mixoide de partes moles.',
    ],
    markers: [
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'sma', pct: [20, 50], note: 'focal, miofibroblástica' },
      { marker: 'calponina', pct: [20, 50] },
      { marker: 's100', pct: [0, 15], note: 'ao contrário do mixoma de partes moles, é fraca e focal' },
      { marker: 'cd34', pct: [10, 30] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'ae1ae3', pct: [0, 10], note: 'só nas ilhas odontogênicas aprisionadas' },
      { marker: 'mdm2', pct: 0, note: 'negativa; separa de lipossarcoma mixoide invadindo' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Papila dental ou folículo dentário hiperplásico: pequenos, associados a dente em formação, não permeiam osso.',
      'Fibroma condromixoide: matriz condroide lobulada com células gigantes na periferia.',
      'Mixofibrossarcoma: atipia, vasos curvilíneos, idoso, em partes moles.',
      'Mixoma de partes moles: fora do osso, S100 negativo, GNAS na síndrome de Mazabraud.',
    ],
    sources: [WHO, THOMPSON],
  },
  {
    id: 'adenoma-orelha-media',
    name: 'Tumor neuroendócrino de orelha média',
    aka: ['adenoma de orelha média', 'middle ear neuroendocrine tumour', 'MeNET'],
    behavior: 'benigno',
    sites: [{ site: 'orelha', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'glandular', 'neuroendocrino'],
    architecture: ['glandulas', 'trabecular', 'ninhos', 'lencois'],
    features: ['mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Massa da caixa timpânica feita de glândulas pequenas e trabéculas de células cuboides monótonas com cromatina em sal e pimenta; coexpressa queratina e marcadores neuroendócrinos, e o erro comum é chamá-la de paraganglioma ou de adenocarcinoma.',
    criteria: [
      'Localização na orelha média, envolvendo os ossículos, sem destruição óssea agressiva.',
      'Padrão glandular e trabecular misto de células cuboides uniformes, sem atipia nem necrose.',
      'Coexpressão de queratina com sinaptofisina e cromogranina.',
      'CK7 e CK20 costumam marcar populações distintas dentro do mesmo tumor, achado bastante característico.',
      'Ausência de células sustentaculares S100 positivas, o que o separa do paraganglioma.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'ck7', pct: [70, 90], note: 'em parte das células' },
      { marker: 'ck20', pct: [50, 80], note: 'em população diferente da CK7; padrão bicelular típico' },
      { marker: 'sinaptofisina', pct: [85, 100] },
      { marker: 'cromogranina', pct: [80, 95] },
      { marker: 'insm1', pct: [80, 95] },
      { marker: 'cd56', pct: [70, 90] },
      { marker: 's100', pct: [0, 10], note: 'sem sustentaculares; o paraganglioma as tem' },
      { marker: 'gata3', pct: [10, 40], note: 'cuidado: positiva no paraganglioma' },
      { marker: 'th', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Paraganglioma jugulotimpânico: queratina negativa, sustentaculares S100 positivas, zellballen.',
      'Tumor papilar do saco endolinfático: papilas com eixo fibrovascular, coloide-símile, invasão do osso petroso.',
      'Adenocarcinoma metastático: atipia, necrose, Ki-67 alto.',
      'Colesteatoma: escamoso queratinizado, sem componente glandular.',
    ],
    sources: [WHO, THOMPSON],
  },
]
