/* ==========================================================================
   hemato.ts — linfonodo, medula óssea, baço e linfomas extranodais.

   Aqui o painel nunca é de um marcador: primeiro linhagem (CD20 e PAX5
   contra CD3), depois maturidade (TdT), depois o subtipo por combinação
   (CD5 e CD23 na LLC, CD5 e ciclina D1 no manto, CD10 e BCL2 no folicular),
   e a clonalidade por cadeia leve ou por rearranjo quando a morfologia não
   basta. Vários destes diagnósticos exigem citometria, cariótipo ou FISH:
   a imuno sozinha classifica, mas não fecha tudo.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Haematolymphoid Tumours, 5ª ed., 2022; classificação de consenso ICC 2022;
   Jaffe, Hematopathology, 3ª ed.; Swerdlow e Campo em revisões de Blood e
   Am J Surg Pathol). As fontes estão como referência de texto: as séries não
   foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Haematolymphoid Tumours, 5ª ed. (2022)'
const ICC = 'International Consensus Classification of mature lymphoid neoplasms (Blood, 2022)'
const JAFFE = 'Jaffe, Arber, Campo, Harris & Quintanilla-Martinez, Hematopathology, 3ª ed.'

export const hemato: Tumor[] = [
  {
    id: 'dlbcl',
    name: 'Linfoma difuso de grandes células B',
    aka: ['DLBCL', 'linfoma de grandes células B', 'diffuse large B-cell lymphoma'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 3 },
      { site: 'estomago', role: 'primario', freq: 2 },
      { site: 'encefalo', role: 'primario', freq: 1 },
      { site: 'testiculo', role: 'primario', freq: 1 },
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'osso', role: 'primario', freq: 1 },
      { site: 'baco', role: 'metastase', freq: 2 },
      { site: 'medula-ossea', role: 'metastase', freq: 2 },
    ],
    cells: ['linfoide-grandes', 'pleomorfico'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    summary: 'Proliferação difusa de linfócitos B grandes que apaga a arquitetura do linfonodo, com núcleos do tamanho de um macrófago ou maiores; é o linfoma mais comum, curável em cerca de dois terços, e a subclassificação em centro germinativo e não centro germinativo (algoritmo de Hans) e a pesquisa de duplo rearranjo mudam o tratamento.',
    criteria: [
      'Células B grandes em padrão difuso, com apagamento da arquitetura nodal.',
      'CD20 ou outro marcador B (PAX5, CD79a) positivo; CD3 negativo.',
      'Algoritmo de Hans com CD10, BCL6 e MUM1 separa centro germinativo de não centro germinativo.',
      'MYC e BCL2 por imuno como triagem; se MYC acima de 40%, FISH para MYC, BCL2 e BCL6 (linfoma de alto grau com duplo rearranjo).',
      'EBER e HHV-8 nos casos com morfologia ou contexto sugestivos.',
    ],
    markers: [
      { marker: 'cd20', pct: [90, 100], note: 'perdido após rituximabe e nos plasmablásticos' },
      { marker: 'cd79a', pct: [90, 100] },
      { marker: 'pax5', pct: [90, 100] },
      { marker: 'cd45', pct: [90, 100] },
      { marker: 'cd19', pct: [90, 100] },
      { marker: 'bcl6', pct: [60, 85] },
      { marker: 'mum1', pct: [50, 75] },
      { marker: 'cd10', pct: [30, 50], note: 'centro germinativo pelo algoritmo de Hans' },
      { marker: 'bcl2', pct: [50, 80] },
      { marker: 'myc', pct: [30, 50], note: 'acima de 40% pede FISH; com BCL2, duplo expressor' },
      { marker: 'cd30', pct: [10, 25], note: 'positivo abre terapia com brentuximabe' },
      { marker: 'cd5', pct: [5, 10], note: 'aberrante; associado a pior prognóstico, e exige afastar manto blastoide' },
      { marker: 'ciclinad1', pct: [0, 5], note: 'o negativo que separa de manto pleomórfico' },
      { marker: 'tdt', pct: [0, 5], note: 'o negativo que separa de linfoblástico' },
      { marker: 'ebv', pct: [5, 15], note: 'define DLBCL EBV-positivo, mais comum em idoso' },
      { marker: 'cd3', pct: 0 },
      { marker: 'ae1ae3', pct: 0, note: 'o negativo que exclui carcinoma' },
      { marker: 'ki67', pct: [60, 90] },
    ],
    mimics: [
      'Carcinoma indiferenciado: queratina positiva, CD45 negativo.',
      'Melanoma: SOX10 e S100 positivos.',
      'Linfoma de Burkitt: Ki-67 próximo de 100%, BCL2 negativo, MYC rearranjado isolado.',
      'Linfoma de Hodgkin clássico: CD30 e CD15 positivos, CD45 negativo, PAX5 fraco, fundo inflamatório.',
      'Linfoma de manto blastoide: ciclina D1 e SOX11 positivos.',
      'Hiperplasia imunoblástica (mononucleose): policlonal, arquitetura preservada.',
    ],
    pitfalls: ['CD30 positivo com CD45 negativo pode confundir com Hodgkin; PAX5 forte e CD20 forte favorecem DLBCL.'],
    molecular: 'BCL2, BCL6 e MYC rearranjados; mutações de MYD88 L265P e CD79B nos extranodais imunoprivilegiados (SNC, testículo).',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'linfoma-folicular',
    name: 'Linfoma folicular',
    aka: ['follicular lymphoma', 'FL'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 3 },
      { site: 'medula-ossea', role: 'metastase', freq: 3 },
      { site: 'baco', role: 'metastase', freq: 2 },
      { site: 'intestino-delgado', role: 'primario', freq: 1 },
    ],
    cells: ['linfoide-pequenas', 'linfoide-grandes'],
    architecture: ['nodular', 'lencois'],
    features: ['mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Linfoma de células do centro germinativo que reproduz folículos, mas folículos que perderam a polaridade, o manto e os macrófagos de corpo tingível, e que expressam BCL2 — uma proteína que o centro germinativo normal não tem; indolente, recidivante, com risco de transformação para grandes células.',
    criteria: [
      'Padrão nodular com folículos dorso a dorso, sem zona do manto nítida e sem polaridade.',
      'Mistura de centrócitos (clivados pequenos) e centroblastos.',
      'CD10 e BCL6 positivos, com BCL2 positivo nos folículos neoplásicos (ausente na hiperplasia folicular reativa).',
      'Graduação 1-2 contra 3A pela contagem de centroblastos; o grau 3B com lençóis é tratado como agressivo.',
      'Padrão de crescimento difuso deve ser quantificado: reflete transformação.',
    ],
    markers: [
      { marker: 'bcl2', pct: [80, 90], note: 'o critério contra hiperplasia folicular; negativo em parte dos graus 3' },
      { marker: 'cd10', pct: [80, 95], note: 'mais forte no folículo que na área interfolicular' },
      { marker: 'bcl6', pct: [90, 100] },
      { marker: 'cd20', pct: [95, 100] },
      { marker: 'pax5', pct: [95, 100] },
      { marker: 'cd79a', pct: [95, 100] },
      { marker: 'cd21', pct: [85, 100], note: 'redes de dendríticas foliculares expandidas e irregulares' },
      { marker: 'cd23', pct: [60, 85], note: 'redes foliculares' },
      { marker: 'cd5', pct: [0, 5], note: 'o negativo que separa de LLC e de manto' },
      { marker: 'ciclinad1', pct: [0, 5] },
      { marker: 'mum1', pct: [10, 25], note: 'positivo no grau 3B e na variante testicular pediátrica' },
      { marker: 'cd3', pct: 0 },
      { marker: 'ki67', pct: [5, 30], note: 'baixo; alto sugere transformação ou variantes de alto grau' },
    ],
    mimics: [
      'Hiperplasia folicular reativa: BCL2 negativo nos centros germinativos, polaridade, macrófagos de corpo tingível, Ki-67 alto.',
      'Linfoma de manto padrão nodular: ciclina D1 e SOX11, CD5 positivo, CD10 negativo.',
      'Linfoma da zona marginal com colonização folicular: CD10 e BCL6 negativos nas células neoplásicas.',
      'Neoplasia folicular in situ: só alguns folículos com células BCL2 fortemente positivas, arquitetura preservada.',
      'Linfoma folicular pediátrico: BCL2 negativo, Ki-67 alto, localizado, excelente prognóstico.',
    ],
    molecular: 't(14;18) IGH::BCL2 em cerca de 85%; mutações de EZH2, CREBBP e KMT2D.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'linfoma-manto',
    name: 'Linfoma de células do manto',
    aka: ['mantle cell lymphoma', 'MCL'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 3 },
      { site: 'medula-ossea', role: 'metastase', freq: 3 },
      { site: 'baco', role: 'metastase', freq: 2 },
      { site: 'colon-reto', role: 'primario', freq: 1 },
      { site: 'intestino-delgado', role: 'primario', freq: 1 },
    ],
    cells: ['linfoide-pequenas', 'pequenas-redondas'],
    architecture: ['nodular', 'lencois', 'infiltrativo'],
    features: ['vasos-espessos', 'mitoses-moderadas', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Proliferação monótona de linfócitos B pequenos de contorno nuclear irregular, com vênulas hialinizadas e histiócitos epitelioides dispersos, expressando CD5 junto com ciclina D1 e SOX11; a polipose linfomatosa do intestino é uma apresentação clássica, e o curso é agressivo apesar do aspecto de célula pequena.',
    criteria: [
      'Células B pequenas a médias, monótonas, de núcleo irregular ou clivado, sem centroblastos.',
      'CD5 positivo com CD20 forte, CD23 negativo ou fraco e CD10 negativo.',
      'Ciclina D1 nuclear positiva: o critério definidor, reflexo de t(11;14).',
      'SOX11 positivo, inclusive nos raros ciclina D1 negativos.',
      'Variantes blastoide e pleomórfica têm Ki-67 alto e pior prognóstico; o Ki-67 deve ser relatado.',
    ],
    markers: [
      { marker: 'ciclinad1', pct: [95, 100], note: 'critério definidor; também marca endotélio e histiócitos como controle' },
      { marker: 'sox11', pct: [90, 100], note: 'útil nos ciclina D1 negativos' },
      { marker: 'cd5', pct: [85, 95] },
      { marker: 'cd20', pct: [95, 100], note: 'forte, ao contrário da LLC' },
      { marker: 'pax5', pct: [95, 100] },
      { marker: 'ighv', pct: [80, 95], note: 'IgD positivo, como na LLC' },
      { marker: 'cd23', pct: [5, 20], note: 'o negativo que separa da LLC' },
      { marker: 'cd10', pct: [0, 10] },
      { marker: 'bcl6', pct: [0, 10] },
      { marker: 'lef1', pct: [0, 10], note: 'o negativo que separa da LLC' },
      { marker: 'bcl2', pct: [85, 100] },
      { marker: 'cd43', pct: [70, 95] },
      { marker: 'tdt', pct: [0, 10], note: 'positivo na variante blastoide, o que confunde com linfoblástico' },
      { marker: 'cd3', pct: 0 },
      { marker: 'ki67', pct: [10, 60], note: 'acima de 30% é de pior prognóstico; relate sempre' },
    ],
    mimics: [
      'LLC/SLL: CD23 e LEF1 positivos, CD20 fraco, centros de proliferação.',
      'Linfoma folicular: CD10 e BCL6 positivos, CD5 negativo.',
      'Linfoma da zona marginal: CD5 e ciclina D1 negativos.',
      'Hiperplasia da zona do manto: ciclina D1 negativa, arquitetura preservada.',
      'Linfoma linfoblástico: TdT difuso, CD34, em paciente jovem.',
    ],
    molecular: 't(11;14) IGH::CCND1; TP53 mutado marca alto risco.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'llc-sll',
    name: 'Leucemia linfocítica crônica / linfoma linfocítico de pequenas células',
    aka: ['LLC', 'SLL', 'CLL/SLL', 'chronic lymphocytic leukaemia'],
    behavior: 'maligno',
    sites: [
      { site: 'medula-ossea', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'primario', freq: 3 },
      { site: 'baco', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['linfoide-pequenas'],
    architecture: ['lencois', 'nodular'],
    features: ['mitoses-raras', 'nucleolo'],
    ages: ['idoso', 'adulto'],
    summary: 'Proliferação de linfócitos B pequenos de cromatina em bloco, com centros de proliferação pálidos (pseudofolículos) contendo prolinfócitos e paraimunoblastos; o perfil CD5 com CD23 e LEF1 positivos e CD20 fraco é praticamente diagnóstico, e a transformação de Richter é a complicação a vigiar.',
    criteria: [
      'Linfócitos pequenos monótonos com cromatina grumosa, mais os centros de proliferação, que são específicos.',
      'CD5 e CD23 positivos com CD20 e imunoglobulina de superfície fracos e LEF1 positivo.',
      'Ciclina D1 negativa: afasta manto.',
      'LLC exige linfocitose B monoclonal maior que 5 mil por microlitro no sangue; abaixo disso e sem massa, é linfocitose monoclonal de células B.',
      'Transformação de Richter: lençóis de grandes células, Ki-67 alto, com piora clínica abrupta.',
    ],
    markers: [
      { marker: 'cd5', pct: [95, 100] },
      { marker: 'cd23', pct: [90, 100] },
      { marker: 'lef1', pct: [85, 100], note: 'muito útil contra manto e marginal' },
      { marker: 'cd20', pct: [90, 100], note: 'caracteristicamente fraco' },
      { marker: 'pax5', pct: [95, 100] },
      { marker: 'cd79a', pct: [85, 100] },
      { marker: 'cd43', pct: [80, 95] },
      { marker: 'ighv', pct: [70, 90], note: 'IgD positivo' },
      { marker: 'ciclinad1', pct: [0, 5], note: 'o negativo obrigatório contra manto' },
      { marker: 'sox11', pct: [0, 5] },
      { marker: 'cd10', pct: [0, 5] },
      { marker: 'bcl6', pct: [0, 10], note: 'positivo nos centros de proliferação' },
      { marker: 'bcl2', pct: [90, 100] },
      { marker: 'tdt', pct: 0 },
      { marker: 'ki67', pct: [1, 10], note: 'alto apenas nos centros de proliferação; difuso sugere Richter' },
    ],
    mimics: [
      'Linfoma de manto: ciclina D1 e SOX11, CD23 e LEF1 negativos.',
      'Linfoma da zona marginal: CD5 e CD23 negativos.',
      'Linfoma linfoplasmacítico: diferenciação plasmocitária, MYD88 L265P, CD5 negativo.',
      'Hiperplasia linfoide reativa: policlonal, arquitetura preservada.',
      'Transformação de Richter: lençóis de grandes células.',
    ],
    molecular: 'Deleção 13q14 (bom), trissomia 12, deleção 11q, deleção 17p com TP53 (mau); estado mutacional de IGHV é prognóstico.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'linfoma-malt',
    name: 'Linfoma da zona marginal extranodal (MALT)',
    aka: ['linfoma MALT', 'extranodal marginal zone lymphoma', 'MALToma'],
    behavior: 'maligno',
    sites: [
      { site: 'estomago', role: 'primario', freq: 3 },
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'tireoide', role: 'primario', freq: 2 },
      { site: 'olho-orbita', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'primario', freq: 2 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['linfoide-pequenas', 'plasmocitoide'],
    architecture: ['infiltrativo', 'nodular'],
    features: ['linfoide', 'plasmocitos', 'granulomas'],
    ages: ['adulto', 'idoso'],
    summary: 'Linfoma indolente que nasce em tecido linfoide adquirido por inflamação crônica — Helicobacter no estômago, Sjögren na parótida, Hashimoto na tireoide —, feito de células centrócito-símiles e monocitoides que invadem o epitélio formando lesões linfoepiteliais; o gástrico regride com erradicação do Helicobacter.',
    criteria: [
      'Infiltrado difuso ou perifolicular de células B pequenas monocitoides, centrócito-símiles ou plasmocitoides.',
      'Lesões linfoepiteliais: agregados de três ou mais células B dentro do epitélio glandular, realçados por queratina.',
      'CD20 positivo com CD5, CD10, CD23 e ciclina D1 negativos: é um diagnóstico por exclusão imuno.',
      'Clonalidade por restrição de cadeia leve nos plasmócitos ou por rearranjo de IGH.',
      'No estômago: pesquisa de Helicobacter e de t(11;18), que prevê não resposta à erradicação.',
    ],
    markers: [
      { marker: 'cd20', pct: [95, 100] },
      { marker: 'pax5', pct: [95, 100] },
      { marker: 'cd79a', pct: [95, 100] },
      { marker: 'bcl2', pct: [80, 95] },
      { marker: 'cd5', pct: [0, 10], note: 'o negativo esperado' },
      { marker: 'cd10', pct: [0, 5] },
      { marker: 'bcl6', pct: [0, 10] },
      { marker: 'cd23', pct: [5, 20] },
      { marker: 'ciclinad1', pct: [0, 5] },
      { marker: 'cd43', pct: [30, 60], note: 'coexpressão aberrante apoia clonalidade' },
      { marker: 'ighv', pct: [0, 15], note: 'IgD negativo, ao contrário de manto e LLC' },
      { marker: 'cd21', pct: [70, 95], note: 'redes foliculares residuais distorcidas' },
      { marker: 'kappa', pct: [50, 60], note: 'restrição de cadeia leve; use com lambda' },
      { marker: 'lambda', pct: [40, 50] },
      { marker: 'ae1ae3', pct: 0, note: 'usada para realçar as lesões linfoepiteliais' },
      { marker: 'ki67', pct: [5, 20] },
    ],
    mimics: [
      'Gastrite crônica com folículos e sialadenite linfoepitelial: policlonal, sem lesões linfoepiteliais destrutivas.',
      'Linfoma de manto: ciclina D1, CD5.',
      'Linfoma folicular: CD10 e BCL6.',
      'LLC/SLL: CD5, CD23 e LEF1.',
      'Transformação para DLBCL: lençóis de grandes células.',
    ],
    molecular: 't(11;18) API2::MALT1 (gástrico, não responde à erradicação), t(14;18) IGH::MALT1, t(1;14) BCL10.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'linfoma-burkitt',
    name: 'Linfoma de Burkitt',
    aka: ['Burkitt lymphoma', 'linfoma de Burkitt endêmico e esporádico'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 2 },
      { site: 'intestino-delgado', role: 'primario', freq: 2 },
      { site: 'maxilares', role: 'primario', freq: 2 },
      { site: 'ovario', role: 'primario', freq: 1 },
      { site: 'medula-ossea', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
    ],
    cells: ['linfoide-grandes', 'pequenas-redondas'],
    architecture: ['lencois'],
    features: ['corpos-apoptoticos', 'mitoses-altas', 'necrose'],
    ages: ['crianca', 'jovem'],
    summary: 'Linfoma de células B médias e monótonas em lençóis com aspecto de céu estrelado, dado pelos macrófagos de corpo tingível engolindo as células apoptóticas; Ki-67 próximo de 100%, MYC rearranjado isolado e BCL2 negativo, e é o tumor humano de crescimento mais rápido.',
    criteria: [
      'Células B médias monótonas com citoplasma basofílico e vacúolos lipídicos, núcleo com vários nucléolos pequenos.',
      'Padrão de céu estrelado por macrófagos de corpo tingível.',
      'Ki-67 próximo de 100%: abaixo de 90% deve fazer reconsiderar.',
      'CD10 e BCL6 positivos com BCL2 negativo ou fraco e TdT negativo.',
      'MYC rearranjado com parceiro IG e sem rearranjo de BCL2 ou BCL6: a presença destes reclassifica como linfoma de alto grau com duplo rearranjo.',
    ],
    markers: [
      { marker: 'ki67', pct: [95, 100], note: 'próximo de 100%; é critério prático' },
      { marker: 'myc', pct: [90, 100] },
      { marker: 'cd10', pct: [90, 100] },
      { marker: 'bcl6', pct: [90, 100] },
      { marker: 'cd20', pct: [95, 100] },
      { marker: 'pax5', pct: [95, 100] },
      { marker: 'bcl2', pct: [0, 10], note: 'o negativo é critério; positivo forte pede FISH para duplo rearranjo' },
      { marker: 'tdt', pct: 0, note: 'o negativo que separa de linfoblástico' },
      { marker: 'mum1', pct: [0, 15] },
      { marker: 'ciclinad1', pct: 0 },
      { marker: 'cd5', pct: 0 },
      { marker: 'ebv', pct: [20, 40], note: 'quase todos no endêmico africano; minoria no esporádico' },
      { marker: 'tcl1', pct: [70, 95] },
      { marker: 'cd3', pct: 0 },
      { marker: 'ae1ae3', pct: 0 },
    ],
    mimics: [
      'Linfoma de alto grau com rearranjo de MYC e BCL2: BCL2 forte, FISH duplo positivo.',
      'DLBCL: células maiores e mais pleomórficas, Ki-67 abaixo de 90%.',
      'Linfoma linfoblástico B: TdT e CD34 positivos, cromatina fina.',
      'Neuroblastoma e outros tumores de células redondas em criança: CD45 negativo.',
      'Hiperplasia com céu estrelado: policlonal, arquitetura preservada.',
    ],
    molecular: 't(8;14) IGH::MYC (ou variantes com IGK e IGL); mutações de TCF3 e ID3.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'hodgkin-classico',
    name: 'Linfoma de Hodgkin clássico',
    aka: ['Hodgkin clássico', 'esclerose nodular', 'celularidade mista', 'classic Hodgkin lymphoma'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 3 },
      { site: 'mediastino', role: 'primario', freq: 3 },
      { site: 'baco', role: 'metastase', freq: 2 },
      { site: 'medula-ossea', role: 'metastase', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 1 },
    ],
    cells: ['linfoide-grandes', 'gigantes', 'linfoide-pequenas'],
    architecture: ['nodular', 'infiltrativo'],
    features: ['reed-sternberg', 'eosinofilos', 'plasmocitos', 'necrose', 'nucleolo', 'linfoide'],
    ages: ['jovem', 'adulto'],
    summary: 'Poucas células neoplásicas grandes — as de Reed-Sternberg, binucleadas em olho de coruja, e suas variantes mononucleares — perdidas num fundo rico de linfócitos, eosinófilos, plasmócitos e histiócitos; CD30 e CD15 positivos com CD45 negativo e PAX5 fraco é a assinatura imuno.',
    criteria: [
      'Células de Reed-Sternberg ou variantes (lacunares na esclerose nodular) em fundo inflamatório apropriado.',
      'CD30 de membrana e Golgi em praticamente todas as células neoplásicas.',
      'CD45 negativo e CD20 negativo ou fraco e heterogêneo; PAX5 positivo mas caracteristicamente mais fraco que nos linfócitos B de fundo.',
      'Subtipo por arquitetura e fundo: esclerose nodular, celularidade mista, rico em linfócitos, depleção linfocitária.',
      'EBER positivo em parte, mais na celularidade mista e em imunossuprimidos.',
    ],
    markers: [
      { marker: 'cd30', pct: [95, 100], note: 'membrana e dot de Golgi; é o critério' },
      { marker: 'pax5', pct: [90, 100], note: 'fraco, mais fraco que os B de fundo: achado característico' },
      { marker: 'cd15', pct: [70, 85] },
      { marker: 'mum1', pct: [90, 100] },
      { marker: 'cd45', pct: [0, 10], note: 'o negativo que separa de DLBCL e de ALCL' },
      { marker: 'cd20', pct: [10, 30], note: 'fraco e heterogêneo quando presente' },
      { marker: 'bcl6', pct: [0, 20] },
      { marker: 'cd3', pct: 0 },
      { marker: 'alk', pct: 0, note: 'o negativo que separa de ALCL ALK-positivo' },
      { marker: 'ebv', pct: [30, 50], note: 'LMP1 e EBER; mais na celularidade mista' },
      { marker: 'pd1', pct: [0, 10], note: 'rosetas de PD-1 favorecem predomínio linfocitário nodular' },
      { marker: 'pdl1', pct: [80, 100], note: 'reflete amplificação de 9p24.1; base da imunoterapia' },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'ki67', pct: [70, 100], note: 'nas células neoplásicas' },
    ],
    mimics: [
      'Hodgkin de predomínio linfocitário nodular: CD20 forte, CD45 positivo, CD30 e CD15 negativos, rosetas de PD-1.',
      'Linfoma anaplásico de grandes células: CD30 forte com CD45 e marcadores T positivos, ALK possível.',
      'DLBCL rico em células T e histiócitos: CD20 forte e difuso nas grandes células.',
      'Mononucleose infecciosa: imunoblastos CD30 positivos mas CD45 positivo e arquitetura preservada.',
      'Carcinoma metastático: queratina positiva.',
    ],
    pitfalls: ['Imunoblastos reativos são CD30 positivos; o que decide é CD45 negativo com PAX5 fraco no contexto certo.'],
    molecular: 'Amplificação de 9p24.1 (PD-L1/PD-L2); EBV clonal em parte.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'hodgkin-nlphl',
    name: 'Linfoma de Hodgkin de predomínio linfocitário nodular',
    aka: ['NLPHL', 'nodular lymphocyte predominant Hodgkin lymphoma', 'linfoma de células B rico em nódulos'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 2 },
      { site: 'baco', role: 'metastase', freq: 1 },
    ],
    cells: ['linfoide-grandes', 'linfoide-pequenas'],
    architecture: ['nodular'],
    features: ['linfoide', 'mitoses-raras'],
    ages: ['adulto'],
    sex: 'm',
    summary: 'Nódulos grandes de linfócitos B pequenos contendo células LP ("pipoca"), grandes, de núcleo lobulado e nucléolo pequeno, que mantêm o fenótipo B completo — CD20 e CD45 positivos, CD30 e CD15 negativos — e são cercadas por rosetas de linfócitos T PD-1 positivos.',
    criteria: [
      'Arquitetura nodular com nódulos expandidos de células B pequenas e redes de dendríticas foliculares CD21 positivas.',
      'Células LP grandes de núcleo lobulado ("pipoca") com fenótipo B preservado.',
      'CD20, CD45, CD79a, BCL6 e OCT2 positivos; CD30 e CD15 negativos.',
      'Rosetas de células T PD-1 positivas ao redor das células LP.',
      'Padrões de crescimento (A a F) devem ser relatados: os variantes ricos em T predizem recidiva e transformação.',
    ],
    markers: [
      { marker: 'cd20', pct: [95, 100], note: 'forte e uniforme, ao contrário do Hodgkin clássico' },
      { marker: 'cd45', pct: [90, 100] },
      { marker: 'cd79a', pct: [90, 100] },
      { marker: 'pax5', pct: [95, 100], note: 'forte' },
      { marker: 'bcl6', pct: [85, 100] },
      { marker: 'pd1', pct: [85, 100], note: 'rosetas de células T ao redor das células LP; achado muito útil' },
      { marker: 'cd30', pct: [0, 10], note: 'o negativo que separa do clássico' },
      { marker: 'cd15', pct: [0, 5] },
      { marker: 'cd21', pct: [85, 100], note: 'redes de dendríticas expandidas nos nódulos' },
      { marker: 'mum1', pct: [10, 30] },
      { marker: 'ebv', pct: [0, 5], note: 'o negativo esperado' },
      { marker: 'bcl2', pct: [0, 20] },
      { marker: 'cd57', pct: [60, 90], note: 'rosetas, junto com PD-1' },
      { marker: 'ki67', pct: [10, 40] },
    ],
    mimics: [
      'Hodgkin clássico rico em linfócitos: CD30 e CD15 positivos, CD45 negativo.',
      'DLBCL rico em células T e histiócitos: difuso, sem nódulos B nem redes dendríticas, pior prognóstico.',
      'Hiperplasia folicular florida com transformação progressiva dos centros germinativos: sem células LP atípicas.',
    ],
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'linfoma-t-periferico',
    name: 'Linfoma T periférico, sem outra especificação',
    aka: ['PTCL-NOS', 'linfoma T periférico SOE', 'peripheral T-cell lymphoma'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 3 },
      { site: 'baco', role: 'metastase', freq: 2 },
      { site: 'medula-ossea', role: 'metastase', freq: 2 },
      { site: 'pele', role: 'metastase', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 1 },
    ],
    cells: ['linfoide-grandes', 'linfoide-pequenas', 'pleomorfico'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['eosinofilos', 'vasos-espessos', 'necrose', 'mitoses-altas'],
    ages: ['adulto', 'idoso'],
    summary: 'Categoria de exclusão dos linfomas de células T maduras que não se encaixam em entidade definida: infiltrado difuso pleomórfico de células T que apaga o linfonodo, com vênulas proeminentes e eosinófilos, e com perda aberrante de antígenos T (o achado imuno que prova neoplasia).',
    criteria: [
      'Infiltrado T difuso com apagamento arquitetural e atipia citológica.',
      'Perda aberrante de um ou mais antígenos pan-T (CD7 e CD5 são os mais perdidos): é o achado que apoia clonalidade.',
      'Exclusão das entidades definidas: angioimunoblástico (PD-1, CXCL13, CD10), ALCL (CD30 difuso, ALK), NK/T (EBER, CD56), ATLL (HTLV-1).',
      'Fenótipo CD4 ou CD8, com rearranjo clonal de TCR quando necessário.',
      'Subgrupos TBX21 e GATA3 têm valor prognóstico emergente.',
    ],
    markers: [
      { marker: 'cd3', pct: [85, 100] },
      { marker: 'cd2', pct: [80, 95] },
      { marker: 'cd5', pct: [50, 80], note: 'a perda é frequente e apoia neoplasia' },
      { marker: 'cd7', pct: [30, 60], note: 'o mais perdido dos pan-T' },
      { marker: 'cd4', pct: [60, 85] },
      { marker: 'cd8', pct: [10, 30] },
      { marker: 'cd30', pct: [20, 50], note: 'focal e variável; difuso e forte sugere ALCL' },
      { marker: 'alk', pct: 0 },
      { marker: 'pd1', pct: [10, 30], note: 'difuso sugere angioimunoblástico' },
      { marker: 'cxcl13', pct: [10, 30] },
      { marker: 'cd10', pct: [5, 20] },
      { marker: 'granzima', pct: [20, 50] },
      { marker: 'ebv', pct: [10, 25], note: 'nas células de fundo, não nas neoplásicas' },
      { marker: 'cd20', pct: [0, 10] },
      { marker: 'cd56', pct: [10, 30] },
      { marker: 'ki67', pct: [40, 90] },
    ],
    mimics: [
      'Linfoma T angioimunoblástico: PD-1, CXCL13, CD10 e ICOS positivos, redes dendríticas expandidas, EBV nos B.',
      'ALCL: CD30 forte e uniforme, EMA, ALK.',
      'Hiperplasia T reativa (paracortical): sem perda de antígenos, policlonal.',
      'Linfoma de Hodgkin: CD30 e CD15 com CD45 negativo.',
      'DLBCL rico em T: as grandes células são CD20 positivas.',
    ],
    molecular: 'Rearranjo clonal de TCR; mutações epigenéticas (TET2, DNMT3A) sobrepostas ao angioimunoblástico.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'linfoma-angioimunoblastico',
    name: 'Linfoma T angioimunoblástico',
    aka: ['AITL', 'linfoma de células T auxiliares foliculares, tipo angioimunoblástico'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 3 },
      { site: 'baco', role: 'metastase', freq: 2 },
      { site: 'medula-ossea', role: 'metastase', freq: 2 },
      { site: 'pele', role: 'metastase', freq: 2 },
    ],
    cells: ['linfoide-pequenas', 'claras', 'linfoide-grandes'],
    architecture: ['infiltrativo', 'lencois'],
    features: ['vasos-espessos', 'eosinofilos', 'plasmocitos'],
    ages: ['idoso', 'adulto'],
    summary: 'Linfoma de células T auxiliares foliculares em idoso com febre, exantema, hipergamaglobulinemia e linfadenopatia generalizada: linfonodo apagado com vênulas arborizadas proeminentes, redes de dendríticas foliculares expandidas para fora dos folículos, e células claras perivasculares PD-1 e CD10 positivas.',
    criteria: [
      'Vênulas de endotélio alto arborizadas e proeminentes, com fundo polimorfo rico em eosinófilos e plasmócitos.',
      'Redes de células dendríticas foliculares (CD21, CD23, CD35) expandidas e irregulares, sobretudo em volta das vênulas.',
      'Fenótipo de célula T auxiliar folicular: pelo menos dois entre PD-1, CXCL13, CD10, ICOS e BCL6.',
      'Células B EBV positivas dispersas, que podem originar DLBCL secundário.',
      'Rearranjo clonal de TCR; a expansão B clonal concomitante é comum e não muda o diagnóstico.',
    ],
    markers: [
      { marker: 'pd1', pct: [85, 100] },
      { marker: 'cxcl13', pct: [70, 95] },
      { marker: 'cd10', pct: [50, 80], note: 'em células T: achado muito característico' },
      { marker: 'bcl6', pct: [60, 90] },
      { marker: 'cd3', pct: [90, 100] },
      { marker: 'cd4', pct: [85, 100] },
      { marker: 'cd21', pct: [85, 100], note: 'redes expandidas; é o achado arquitetural chave' },
      { marker: 'cd23', pct: [70, 95] },
      { marker: 'cd35', pct: [70, 95] },
      { marker: 'ebv', pct: [80, 95], note: 'nas células B de fundo, não nas T neoplásicas' },
      { marker: 'cd7', pct: [30, 60], note: 'perda frequente' },
      { marker: 'cd20', pct: [0, 10], note: 'só nos imunoblastos B de fundo' },
      { marker: 'cd30', pct: [10, 40], note: 'nos imunoblastos' },
      { marker: 'alk', pct: 0 },
      { marker: 'ki67', pct: [20, 60] },
    ],
    mimics: [
      'Linfoma T periférico SOE: sem fenótipo de T auxiliar folicular nem redes dendríticas expandidas.',
      'Hiperplasia paracortical e reação a droga: arquitetura parcialmente preservada, sem clone.',
      'Linfoma de Hodgkin: as células grandes são CD30 e CD15 positivas com CD45 negativo.',
      'DLBCL EBV-positivo: as grandes células B dominam.',
      'Doença de Castleman: folículos regressivos, sem clone T.',
    ],
    molecular: 'TET2, DNMT3A, IDH2 R172 e RHOA G17V, esta última bastante específica.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'alcl',
    name: 'Linfoma anaplásico de grandes células',
    aka: ['ALCL', 'anaplastic large cell lymphoma', 'ALCL associado a implante mamário'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 3 },
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'partes-moles', role: 'metastase', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 1 },
      { site: 'medula-ossea', role: 'metastase', freq: 1 },
    ],
    cells: ['linfoide-grandes', 'pleomorfico', 'rabdoide'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Linfoma T de células grandes com as células em ferradura ou rim ("hallmark cells"), crescimento coesivo sinusal que imita carcinoma, CD30 forte e uniforme em todas as células, e frequente perda de antígenos T; o ALK positivo é de criança e bom prognóstico, o ALK negativo é de adulto e pior.',
    criteria: [
      'Células grandes com núcleo excêntrico em ferradura e região de Golgi eosinofílica (hallmark cells).',
      'CD30 forte e uniforme em membrana e Golgi em praticamente todas as células neoplásicas.',
      'Perda frequente de antígenos T; o fenótipo "nulo" ainda é um linfoma T por rearranjo de TCR.',
      'ALK por imuno separa os dois grupos; o padrão de marcação sugere o parceiro de fusão (nuclear e citoplasmático em NPM1::ALK).',
      'ALCL associado a implante mamário: confinado ao seroma e à cápsula, ALK negativo, bom prognóstico se ressecado em bloco.',
    ],
    markers: [
      { marker: 'cd30', pct: [95, 100], note: 'forte e uniforme, ao contrário do focal do PTCL' },
      { marker: 'alk', pct: [50, 60], note: 'define o subtipo ALK-positivo, de criança e melhor prognóstico' },
      { marker: 'ema', pct: [70, 95], note: 'positivo, ao contrário do Hodgkin' },
      { marker: 'cd3', pct: [20, 50], note: 'perdido com frequência' },
      { marker: 'cd2', pct: [50, 80] },
      { marker: 'cd4', pct: [60, 85] },
      { marker: 'cd5', pct: [20, 50] },
      { marker: 'granzima', pct: [70, 95], note: 'fenótipo citotóxico' },
      { marker: 'clusterina', pct: [60, 90] },
      { marker: 'cd45', pct: [50, 80], note: 'pode ser fraco; a negatividade não exclui' },
      { marker: 'cd15', pct: [10, 30] },
      { marker: 'pax5', pct: [0, 5], note: 'o negativo que separa do Hodgkin clássico' },
      { marker: 'cd20', pct: 0 },
      { marker: 'ae1ae3', pct: [0, 10], note: 'o negativo que exclui carcinoma, que ele imita' },
      { marker: 'ki67', pct: [70, 100] },
    ],
    mimics: [
      'Hodgkin clássico: PAX5 fraco positivo, EMA negativo, CD15 mais frequente, fundo inflamatório.',
      'Carcinoma metastático no seio subcapsular: queratina positiva, CD30 negativo.',
      'Melanoma: SOX10 e S100.',
      'Papulose linfomatoide e ALCL cutâneo primário: mesma imuno, mas curso indolente e sem ALK.',
      'Linfoma T periférico com CD30 focal: CD30 heterogêneo e fraco.',
    ],
    molecular: 'Fusões de ALK (NPM1::ALK a mais comum); DUSP22 (bom prognóstico) e TP63 (mau) nos ALK-negativos.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'micose-fungoide',
    name: 'Micose fungoide e síndrome de Sézary',
    aka: ['mycosis fungoides', 'linfoma cutâneo de células T', 'Sézary syndrome'],
    behavior: 'maligno',
    sites: [
      { site: 'pele', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'baco', role: 'metastase', freq: 1 },
    ],
    cells: ['linfoide-pequenas', 'pleomorfico'],
    architecture: ['infiltrativo'],
    features: ['linfoide', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'O linfoma cutâneo de células T mais comum: infiltrado em faixa na derme papilar de linfócitos T de núcleo cerebriforme que sobem para a epiderme isolados e em microabscessos de Pautrier, com halo claro ao redor; evolui de mácula a placa a tumor ao longo de anos, e a fase inicial é notoriamente difícil de provar.',
    criteria: [
      'Epidermotropismo desproporcional: linfócitos na epiderme sem espongiose, alinhados na basal, com halo perinuclear.',
      'Microabscessos de Pautrier são específicos mas pouco sensíveis.',
      'Linfócitos de núcleo cerebriforme, maiores que os da derme.',
      'Perda de CD7 e, menos, de CD5, com relação CD4/CD8 desviada.',
      'Rearranjo clonal de TCR na pele; na síndrome de Sézary, clone idêntico no sangue com contagem acima de mil células por microlitro.',
    ],
    markers: [
      { marker: 'cd3', pct: [95, 100] },
      { marker: 'cd4', pct: [85, 95] },
      { marker: 'cd8', pct: [5, 15], note: 'variantes CD8 positivas existem, sobretudo pediátricas' },
      { marker: 'cd7', pct: [20, 50], note: 'a perda é o achado clássico, mas ocorre também em dermatoses' },
      { marker: 'cd5', pct: [60, 90], note: 'perda menos frequente, porém mais específica' },
      { marker: 'cd2', pct: [80, 95] },
      { marker: 'cd30', pct: [10, 30], note: 'sobe na transformação de grandes células' },
      { marker: 'granzima', pct: [10, 30] },
      { marker: 'cd25', pct: [20, 50] },
      { marker: 'cd20', pct: 0 },
      { marker: 'tdt', pct: 0 },
      { marker: 'ki67', pct: [5, 30], note: 'alto na transformação' },
    ],
    mimics: [
      'Dermatite espongiótica e reação a droga: espongiose, sem linfócitos atípicos alinhados, CD7 pode faltar também.',
      'Parapsoríase de pequenas placas: sem clone dominante, sem atipia.',
      'Papulose linfomatoide: CD30 positivo, lesões que regridem sozinhas.',
      'Linfoma T subcutâneo paniculítico: no subcutâneo, CD8 e granzima positivos, halo em torno dos adipócitos.',
      'Linfoma cutâneo T CD8 agressivo epidermotrópico: CD8 positivo, curso fulminante.',
    ],
    pitfalls: ['A perda de CD7 sozinha não prova linfoma: dermatoses inflamatórias crônicas também a mostram.'],
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'linfoma-nk-t-nasal',
    name: 'Linfoma extranodal de células NK/T, tipo nasal',
    aka: ['linfoma NK/T nasal', 'granuloma letal da linha média', 'extranodal NK/T-cell lymphoma'],
    behavior: 'maligno',
    sites: [
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'boca', role: 'primario', freq: 1 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'intestino-delgado', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['linfoide-grandes', 'linfoide-pequenas', 'pleomorfico'],
    architecture: ['infiltrativo', 'lencois'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos', 'linfoide'],
    ages: ['adulto'],
    summary: 'Linfoma destrutivo da linha média facial, com perfuração do septo e necrose extensa por angiocentrismo e angiodestruição; as células invadem e destroem a parede vascular, e o diagnóstico depende do EBER positivo com CD56 e granzima, muitas vezes em material pequeno e muito necrótico.',
    criteria: [
      'Infiltrado angiocêntrico e angiodestrutivo com necrose isquêmica extensa.',
      'EBER por hibridização in situ positivo em praticamente todas as células neoplásicas: é obrigatório.',
      'CD56 positivo com CD3 citoplasmático (o CD3 de superfície é negativo) e marcadores citotóxicos.',
      'CD5 e CD4 negativos, CD30 variável.',
      'Amostragem generosa e repetida: a necrose extensa produz biópsias não diagnósticas com frequência.',
    ],
    markers: [
      { marker: 'ebv', pct: [95, 100], note: 'EBER; critério obrigatório' },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'cd3', pct: [85, 100], note: 'citoplasmático (clone policlonal); o de superfície é negativo' },
      { marker: 'granzima', pct: [90, 100] },
      { marker: 'cd2', pct: [80, 95] },
      { marker: 'cd5', pct: [0, 15], note: 'o negativo típico' },
      { marker: 'cd4', pct: [0, 15] },
      { marker: 'cd8', pct: [10, 30] },
      { marker: 'cd7', pct: [30, 60] },
      { marker: 'cd30', pct: [30, 60] },
      { marker: 'cd20', pct: 0 },
      { marker: 'pax5', pct: 0 },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'ki67', pct: [60, 95] },
    ],
    mimics: [
      'Granulomatose com poliangiite: vasculite com granulomas, ANCA, sem clone nem EBER.',
      'Carcinoma nasofaríngeo: queratina positiva, também EBER positivo — o par queratina/CD45 decide.',
      'Rinite necrosante por cocaína: necrose sem células atípicas.',
      'DLBCL EBV-positivo: CD20 e PAX5 positivos.',
      'Linfoma T periférico: EBER negativo nas células neoplásicas, CD5 positivo.',
    ],
    molecular: 'EBV clonal; mutações de JAK3, STAT3 e DDX3X; deleção 6q.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'linfoma-linfoblastico',
    name: 'Leucemia/linfoma linfoblástico B e T',
    aka: ['LLA', 'linfoma linfoblástico', 'lymphoblastic leukaemia/lymphoma'],
    behavior: 'maligno',
    sites: [
      { site: 'medula-ossea', role: 'primario', freq: 3 },
      { site: 'mediastino', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'primario', freq: 2 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
    ],
    cells: ['pequenas-redondas', 'blastematoso'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['mitoses-altas', 'corpos-apoptoticos', 'necrose'],
    ages: ['crianca', 'jovem'],
    summary: 'Proliferação de precursores linfoides imaturos: células médias de cromatina fina dispersa, nucléolo indistinto e citoplasma escasso, com mitoses e apoptose abundantes; TdT positivo é a chave, e o linfoblástico T costuma se apresentar como massa mediastinal em adolescente.',
    criteria: [
      'Blastos de cromatina fina e nucléolo inconspícuo, com moldagem e índice mitótico alto.',
      'TdT nuclear positivo (o marcador de imaturidade) e CD34 frequentemente positivo.',
      'Linhagem B: CD19, CD79a, PAX5, CD10 positivos, CD20 frequentemente fraco ou negativo.',
      'Linhagem T: CD3 citoplasmático, CD7, CD1a, com coexpressão de CD4 e CD8 frequente.',
      'Classificação por alterações genéticas definidoras é obrigatória (BCR::ABL1, KMT2A, hiperdiploidia, ETV6::RUNX1).',
    ],
    markers: [
      { marker: 'tdt', pct: [90, 100], note: 'o marcador de imaturidade; é a chave do diagnóstico' },
      { marker: 'cd34', pct: [60, 85] },
      { marker: 'cd99', pct: [70, 95], note: 'membranoso; cuidado para não concluir Ewing' },
      { marker: 'cd10', pct: [70, 90], note: 'no B comum' },
      { marker: 'cd79a', pct: [70, 90], note: 'linhagem B' },
      { marker: 'pax5', pct: [70, 90], note: 'linhagem B' },
      { marker: 'cd19', pct: [70, 90] },
      { marker: 'cd3', pct: [30, 50], note: 'citoplasmático na linhagem T' },
      { marker: 'cd7', pct: [30, 50] },
      { marker: 'cd1a', pct: [25, 45], note: 'timócito cortical; linhagem T' },
      { marker: 'cd20', pct: [20, 40], note: 'fraco ou negativo no B imaturo' },
      { marker: 'ciclinad1', pct: [0, 5], note: 'o negativo contra manto blastoide' },
      { marker: 'mpo', pct: [0, 10], note: 'positivo indica linhagem mieloide ou leucemia de linhagem ambígua' },
      { marker: 'desmina', pct: 0 },
      { marker: 'ki67', pct: [60, 95] },
    ],
    mimics: [
      'Linfoma de Burkitt: TdT negativo, Ki-67 próximo de 100%, CD20 forte.',
      'Sarcoma de Ewing: CD99 também positivo, mas TdT negativo, CD45 negativo e fusão EWSR1.',
      'Sarcoma mieloide: MPO, lisozima, CD33, TdT possível.',
      'Linfoma de manto blastoide: ciclina D1 e SOX11, em adulto.',
      'Hematogônias na medula: TdT positivo mas espectro maturativo completo na citometria.',
    ],
    molecular: 'BCR::ABL1, KMT2A rearranjado, ETV6::RUNX1, hiperdiploidia, BCR::ABL1-like; NOTCH1 nos T.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'mieloma',
    name: 'Mieloma de células plasmáticas e plasmocitoma',
    aka: ['mieloma múltiplo', 'plasmocitoma', 'plasma cell myeloma'],
    behavior: 'maligno',
    sites: [
      { site: 'medula-ossea', role: 'primario', freq: 3 },
      { site: 'osso', role: 'primario', freq: 3 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
      { site: 'partes-moles', role: 'metastase', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['plasmocitoide', 'epitelioide', 'pleomorfico'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['amiloide', 'mitoses-moderadas', 'globulos-hialinos'],
    ages: ['adulto', 'idoso'],
    summary: 'Proliferação clonal de plasmócitos na medula, com núcleo excêntrico em roda de carroça e halo perinuclear, causando lesões líticas, anemia, hipercalcemia e insuficiência renal; a restrição de cadeia leve prova a clonalidade, e a expressão aberrante de ciclina D1 ou de CD56 apoia neoplasia.',
    criteria: [
      'Plasmócitos clonais na medula, com restrição de cadeia leve kappa ou lambda demonstrada por imuno ou ISH.',
      'CD138 e MUM1 positivos com CD19 e CD20 negativos (o plasmócito normal é CD19 positivo).',
      'CD56 e ciclina D1 aberrantes apoiam clonalidade.',
      'Critérios de mieloma sintomático (CRAB) ou biomarcadores (mais de 60% de plasmócitos, relação de cadeias leves acima de 100, lesão em ressonância).',
      'Plasmocitoma solitário: lesão única sem envolvimento medular.',
    ],
    markers: [
      { marker: 'cd138', pct: [95, 100], note: 'também marca carcinomas: use em painel' },
      { marker: 'mum1', pct: [90, 100] },
      { marker: 'kappa', pct: [60, 70], note: 'restrição; kappa em cerca de dois terços' },
      { marker: 'lambda', pct: [30, 40] },
      { marker: 'cd79a', pct: [60, 85] },
      { marker: 'cd56', pct: [60, 80], note: 'aberrante; o plasmócito normal é negativo' },
      { marker: 'ciclinad1', pct: [30, 50], note: 'reflete t(11;14)' },
      { marker: 'cd20', pct: [10, 25], note: 'negativo na maioria; positivo com ciclina D1 na t(11;14)' },
      { marker: 'cd19', pct: [0, 10], note: 'o negativo que separa do plasmócito reativo' },
      { marker: 'cd45', pct: [10, 40], note: 'fraco ou negativo' },
      { marker: 'ae1ae3', pct: [5, 20], note: 'positividade focal descrita; não conclua carcinoma' },
      { marker: 'ema', pct: [30, 60], note: 'positivo: outra armadilha contra carcinoma' },
      { marker: 'pax5', pct: [0, 10] },
      { marker: 'ki67', pct: [10, 60] },
    ],
    mimics: [
      'Plasmocitose reativa: policlonal, CD19 positivo, CD56 negativo, distribuição perivascular.',
      'Carcinoma pouco diferenciado e melanoma: queratina ou SOX10 positivos; cuidado, CD138 e EMA podem marcar carcinoma.',
      'Linfoma plasmablástico: EBER positivo, MYC rearranjado, em imunossuprimido.',
      'Linfoma linfoplasmacítico: componente linfoide B, MYD88 L265P, CD19 positivo.',
      'Doença de cadeias leves e amiloidose: depósito sem massa plasmocitária significativa.',
    ],
    pitfalls: ['CD138 e EMA positivos com queratina focal levam mieloma anaplásico a ser lido como carcinoma; peça MUM1 e cadeias leves.'],
    molecular: 't(11;14) CCND1, t(4;14) FGFR3/NSD2, t(14;16) MAF, del(17p) e ganho de 1q: definem risco.',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'sarcoma-mieloide',
    name: 'Sarcoma mieloide',
    aka: ['cloroma', 'sarcoma granulocítico', 'myeloid sarcoma'],
    behavior: 'maligno',
    sites: [
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'primario', freq: 2 },
      { site: 'osso', role: 'primario', freq: 2 },
      { site: 'partes-moles', role: 'primario', freq: 2 },
      { site: 'intestino-delgado', role: 'primario', freq: 1 },
      { site: 'medula-ossea', role: 'metastase', freq: 3 },
    ],
    cells: ['pequenas-redondas', 'blastematoso', 'linfoide-grandes'],
    architecture: ['infiltrativo', 'lencois', 'fila-indiana'],
    features: ['mitoses-altas', 'necrose', 'eosinofilos'],
    ages: ['crianca', 'adulto', 'idoso'],
    summary: 'Massa extramedular de blastos mieloides que pode preceder, acompanhar ou anunciar recidiva de leucemia mieloide aguda; infiltra em fila indiana entre o colágeno com aspecto enganosamente linfomatoso, e o verde do corte fresco (cloroma) vem da mieloperoxidase.',
    criteria: [
      'Infiltrado de células blásticas médias a grandes em massa tumoral, fora da medula.',
      'Demonstração de linhagem mieloide: mieloperoxidase, lisozima, CD33, CD117 ou CD68 (KP1).',
      'Precursores eosinofílicos entremeados são uma pista clássica.',
      'Exclusão de linfoma por CD20, CD3 e TdT interpretados com cuidado (TdT pode ser positivo).',
      'Cariótipo e molecular para classificar a leucemia subjacente (NPM1, KMT2A, RUNX1::RUNX1T1).',
    ],
    markers: [
      { marker: 'mpo', pct: [70, 90], note: 'específica de linhagem mieloide; negativa nos monoblásticos' },
      { marker: 'cd33', pct: [80, 95] },
      { marker: 'cd68', pct: [70, 95], note: 'clone KP1; mais nos monoblásticos' },
      { marker: 'cd117', pct: [50, 80] },
      { marker: 'cd43', pct: [85, 100], note: 'positivo com CD20 negativo é uma pista precoce' },
      { marker: 'cd34', pct: [40, 70] },
      { marker: 'cd45', pct: [80, 95], note: 'costuma ser mais fraco que nos linfomas' },
      { marker: 'cd4', pct: [40, 70], note: 'nos monoblásticos' },
      { marker: 'tdt', pct: [20, 40], note: 'positivo em parte; não conclua linfoblástico' },
      { marker: 'erg', pct: [40, 70], note: 'positivo em parte; não conclua tumor vascular' },
      { marker: 'cd20', pct: 0 },
      { marker: 'cd3', pct: 0 },
      { marker: 'pax5', pct: [0, 10] },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'ki67', pct: [50, 90] },
    ],
    mimics: [
      'Linfoma difuso de grandes células B: CD20 e PAX5 positivos, MPO negativa.',
      'Linfoma linfoblástico: TdT difuso com CD79a ou CD3 citoplasmático, MPO negativa.',
      'Carcinoma pouco diferenciado: queratina positiva.',
      'Sarcoma de Ewing e outros de células redondas: CD45 negativo.',
      'Hematopoese extramedular: três linhagens presentes, megacariócitos, sem monomorfismo blástico.',
    ],
    pitfalls: ['A pista mais comum é negativa: um "linfoma" CD20 e CD3 negativos com CD43 positivo deve receber MPO e lisozima.'],
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'histiocitose-langerhans',
    name: 'Histiocitose de células de Langerhans',
    aka: ['LCH', 'granuloma eosinofílico', 'histiocitose X', "Langerhans cell histiocytosis"],
    behavior: 'intermediario',
    sites: [
      { site: 'osso', role: 'primario', freq: 3 },
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'primario', freq: 2 },
      { site: 'sela', role: 'primario', freq: 1 },
      { site: 'medula-ossea', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'histiocitoide', 'gigantes'],
    architecture: ['lencois', 'infiltrativo', 'nodular'],
    features: ['eosinofilos', 'sulcos-inclusoes', 'necrose', 'mitoses-moderadas'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Proliferação clonal de células de Langerhans — núcleo reniforme com sulco longitudinal profundo, citoplasma eosinofílico pálido — misturada a eosinófilos abundantes, muitas vezes numa lesão lítica de crânio ou fêmur; CD1a e langerina positivos, e a maioria tem BRAF V600E.',
    criteria: [
      'Células com núcleo reniforme ou em grão de café, com sulco nuclear longitudinal nítido e cromatina fina.',
      'Fundo com eosinófilos abundantes, às vezes formando abscessos eosinofílicos, com histiócitos e células gigantes.',
      'CD1a e langerina (CD207) positivos: os dois são exigidos na prática.',
      'S100 positivo, mas inespecífico isoladamente.',
      'BRAF V600E na maioria e ligação com a via MAPK; abre terapia-alvo nas formas multissistêmicas.',
    ],
    markers: [
      { marker: 'cd1a', pct: [95, 100], note: 'critério; membranoso' },
      { marker: 'langerina', pct: [90, 100], note: 'substituto dos grânulos de Birbeck' },
      { marker: 's100', pct: [90, 100] },
      { marker: 'brafv600e', pct: [50, 65] },
      { marker: 'ciclinad1', pct: [80, 95], note: 'positiva; útil e frequentemente esquecida' },
      { marker: 'cd68', pct: [50, 80] },
      { marker: 'cd163', pct: [10, 30], note: 'negativa, ao contrário do Rosai-Dorfman' },
      { marker: 'cd45', pct: [50, 80], note: 'fraco' },
      { marker: 'sox10', pct: [0, 10], note: 'o negativo que ajuda contra melanoma' },
      { marker: 'melana', pct: 0 },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'cd21', pct: [0, 5], note: 'o negativo contra sarcoma de células dendríticas foliculares' },
      { marker: 'ki67', pct: [5, 30] },
    ],
    mimics: [
      'Doença de Rosai-Dorfman: células grandes com emperipolese, S100 positivo mas CD1a negativo e CD163 positivo.',
      'Doença de Erdheim-Chester: histiócitos espumosos, CD68 e BRAF positivos, CD1a negativo.',
      'Sarcoma de células dendríticas: CD21, CD23 e CD35.',
      'Melanoma: SOX10 e HMB-45.',
      'Osteomielite eosinofílica e granuloma reparativo: sem células de Langerhans clonais.',
    ],
    molecular: 'BRAF V600E na maioria; MAP2K1 nos BRAF-negativos.',
    sources: [WHO, JAFFE],
  },
  {
    id: 'rosai-dorfman',
    name: 'Doença de Rosai-Dorfman',
    aka: ['histiocitose sinusal com linfadenopatia maciça', 'Rosai-Dorfman disease', 'RDD'],
    behavior: 'benigno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 3 },
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
      { site: 'osso', role: 'primario', freq: 1 },
      { site: 'meninges', role: 'primario', freq: 1 },
    ],
    cells: ['histiocitoide', 'epitelioide', 'plasmocitoide'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['emperipolese', 'plasmocitos', 'linfoide'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Expansão dos seios linfonodais por histiócitos grandes de citoplasma claro e abundante, com linfócitos e plasmócitos intactos dentro do citoplasma (emperipolese), num fundo rico em plasmócitos; S100 positivo com CD1a negativo, e o curso costuma ser autolimitado.',
    criteria: [
      'Histiócitos grandes de núcleo vesiculoso, nucléolo evidente e citoplasma pálido abundante.',
      'Emperipolese: linfócitos e plasmócitos íntegros dentro do citoplasma, com halo claro — é o achado definidor, realçado pelo S100.',
      'Expansão dos seios linfonodais, com plasmocitose policlonal na área interfolicular.',
      'S100 e CD163 positivos com CD1a e langerina negativos.',
      'Formas extranodais são frequentes e mais fibrosantes, com emperipolese mais discreta.',
    ],
    markers: [
      { marker: 's100', pct: [95, 100], note: 'realça a emperipolese' },
      { marker: 'cd163', pct: [90, 100] },
      { marker: 'cd68', pct: [90, 100] },
      { marker: 'cd1a', pct: [0, 5], note: 'o negativo que separa de Langerhans' },
      { marker: 'langerina', pct: [0, 5] },
      { marker: 'ciclinad1', pct: [40, 80] },
      { marker: 'igg4', pct: [30, 60], note: 'plasmócitos IgG4 podem estar aumentados e levar a erro' },
      { marker: 'sox10', pct: [0, 5], note: 'o negativo que exclui melanoma e schwannoma' },
      { marker: 'melana', pct: 0 },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'cd21', pct: [0, 5] },
      { marker: 'brafv600e', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 10] },
    ],
    mimics: [
      'Histiocitose de células de Langerhans: CD1a e langerina positivos, eosinófilos, sulco nuclear.',
      'Doença relacionada a IgG4: fibrose estoriforme, flebite obliterante, sem emperipolese verdadeira.',
      'Histiocitose sinusal reativa: histiócitos menores, sem emperipolese proeminente.',
      'Melanoma metastático nos seios: SOX10 e HMB-45.',
      'Linfoma com diferenciação histiocitóide: clonalidade.',
    ],
    molecular: 'Mutações da via MAPK (KRAS, MAP2K1) em parte dos casos, sugerindo natureza clonal.',
    sources: [WHO, JAFFE],
  },
  {
    id: 'mastocitose-sistemica',
    name: 'Mastocitose sistêmica',
    aka: ['systemic mastocytosis', 'mastocitose'],
    behavior: 'intermediario',
    sites: [
      { site: 'medula-ossea', role: 'primario', freq: 3 },
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'baco', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'intestino-delgado', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular', 'epitelioide', 'histiocitoide'],
    architecture: ['nodular', 'infiltrativo', 'lencois'],
    features: ['eosinofilos', 'hialinizacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Agregados de mastócitos anômalos, fusiformes em vez de redondos, ao redor de trabéculas ósseas e vasos na medula, com eosinófilos e fibrose em volta; triptase e CD117 provam a linhagem, e a coexpressão aberrante de CD25 com a mutação KIT D816V fecha o diagnóstico.',
    criteria: [
      'Critério maior: agregados densos multifocais de 15 ou mais mastócitos em medula ou outro órgão extracutâneo.',
      'Critérios menores: mais de 25% de mastócitos fusiformes ou atípicos, KIT D816V, coexpressão de CD25 ou CD2, triptase sérica acima de 20 ng/mL.',
      'Um critério maior mais um menor, ou três menores, fecham o diagnóstico.',
      'Triptase e CD117 identificam os mastócitos; CD25 é o marcador aberrante que prova neoplasia.',
      'Avaliar neoplasia hematológica associada, que domina o prognóstico.',
    ],
    markers: [
      { marker: 'triptase', pct: [95, 100], note: 'o marcador de linhagem mais específico' },
      { marker: 'cd117', pct: [95, 100] },
      { marker: 'cd25', pct: [85, 100], note: 'aberrante; o mastócito normal é negativo' },
      { marker: 'cd2', pct: [40, 70], note: 'aberrante, menos sensível que o CD25' },
      { marker: 'cd68', pct: [70, 95] },
      { marker: 'cd43', pct: [70, 95] },
      { marker: 'cd45', pct: [80, 95] },
      { marker: 'cd30', pct: [40, 70], note: 'nas formas avançadas' },
      { marker: 'mpo', pct: [0, 10], note: 'o negativo que separa de sarcoma mieloide' },
      { marker: 'cd1a', pct: 0 },
      { marker: 's100', pct: [0, 15] },
      { marker: 'ki67', pct: [1, 10] },
    ],
    mimics: [
      'Mastocitose reativa e mastócitos aumentados em outras doenças: dispersos, redondos, CD25 negativos.',
      'Sarcoma mieloide: MPO e CD33 positivos, triptase negativa.',
      'Linfoma de células T: triptase e CD117 negativos.',
      'Fibrose medular de outras causas: sem agregados de mastócitos.',
      'Tumor fibroso solitário e outros fusocelulares: CD117 e triptase negativos.',
    ],
    molecular: 'KIT D816V na grande maioria (resistente a imatinibe, sensível a midostaurina e avapritinibe).',
    sources: [WHO, ICC, JAFFE],
  },
  {
    id: 'sarcoma-dendriticas-foliculares',
    name: 'Sarcoma de células dendríticas foliculares',
    aka: ['follicular dendritic cell sarcoma', 'FDCS'],
    behavior: 'maligno',
    sites: [
      { site: 'linfonodo', role: 'primario', freq: 2 },
      { site: 'figado', role: 'primario', freq: 1 },
      { site: 'baco', role: 'primario', freq: 1 },
      { site: 'boca', role: 'primario', freq: 1 },
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'peritoneo', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'epitelioide', 'sincicial'],
    architecture: ['storiforme', 'fasciculos', 'lencois'],
    features: ['linfoide', 'necrose', 'mitoses-moderadas', 'nucleolo'],
    ages: ['adulto'],
    summary: 'Proliferação fusocelular em fascículos e redemoinhos estoriformes, de células de limites indistintos com nucléolo evidente, salpicada de pequenos linfócitos maduros por todo o tumor; CD21, CD23 e CD35 positivos, e a variante inflamatória do fígado e baço é EBV-dirigida.',
    criteria: [
      'Fascículos e redemoinhos de células fusiformes a ovoides com núcleos vesiculosos e limites mal definidos.',
      'Linfócitos pequenos maduros permeando difusamente o tumor: a pista morfológica mais útil.',
      'Pelo menos um marcador de célula dendrítica folicular positivo: CD21, CD23, CD35, clusterina ou CXCL13.',
      'Queratina, SOX10, CD45 e marcadores musculares negativos.',
      'Variante pseudotumor inflamatório-símile do fígado e baço: EBER positivo, curso mais indolente.',
    ],
    markers: [
      { marker: 'cd21', pct: [70, 95] },
      { marker: 'cd23', pct: [60, 90] },
      { marker: 'cd35', pct: [70, 95] },
      { marker: 'clusterina', pct: [80, 95], note: 'forte e difusa; muito útil' },
      { marker: 'cxcl13', pct: [60, 90] },
      { marker: 'd240', pct: [50, 80] },
      { marker: 'ema', pct: [30, 60] },
      { marker: 'ae1ae3', pct: [0, 10], note: 'o negativo que exclui carcinoma sarcomatoide' },
      { marker: 'sox10', pct: [0, 5], note: 'o negativo que exclui melanoma e schwannoma' },
      { marker: 's100', pct: [10, 30] },
      { marker: 'cd45', pct: [0, 15] },
      { marker: 'cd1a', pct: [0, 5], note: 'o negativo contra sarcoma de células de Langerhans' },
      { marker: 'stat6', pct: [0, 5], note: 'o negativo contra tumor fibroso solitário' },
      { marker: 'cd34', pct: [0, 15] },
      { marker: 'ebv', pct: [10, 30], note: 'positivo na variante inflamatória de fígado e baço' },
      { marker: 'ki67', pct: [10, 50] },
    ],
    mimics: [
      'Tumor fibroso solitário: STAT6 nuclear, CD34, vasos em galhada.',
      'Carcinoma sarcomatoide e metastático: queratina positiva.',
      'Sarcoma de células dendríticas interdigitantes: S100 forte, CD21 e CD35 negativos.',
      'Tumor miofibroblástico inflamatório: ALK positivo, SMA.',
      'Meningioma metastático ou ectópico: EMA e SSTR2A, CD21 negativo.',
    ],
    sources: [WHO, JAFFE],
  },
]
