/* ==========================================================================
   hepatopancreatic.ts — fígado, vias biliares e pâncreas.

   No fígado a imuno resolve três perguntas em sequência: é hepatocelular ou
   não (HepPar-1, arginase, CD10 canalicular), é benigno ou maligno (reticulina,
   glipicano-3, HSP70, glutamina sintetase), e qual o subtipo do adenoma
   (LFABP, SAA/CRP, β-catenina), que é o que decide ressecção ou seguimento.
   No pâncreas a pergunta é quase sempre "ducto reativo ou adenocarcinoma?", e
   aí entram SMAD4, maspina, S100P e IMP3, nunca isolados.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Digestive System Tumours, 2019; Odze & Goldblum, Surgical
   Pathology of the GI Tract, Liver, Biliary Tract and Pancreas, 4ª ed.;
   Bosman e Hruban nos capítulos de pâncreas; séries de Am J Surg Pathol,
   Mod Pathol e Hepatology). As fontes estão como referência de texto: as
   séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Digestive System Tumours (2019)'
const ODZE = 'Odze & Goldblum, Surgical Pathology of the GI Tract, Liver, Biliary Tract and Pancreas, 4ª ed.'
const HRUBAN = 'Hruban, Pitman & Klimstra, Tumors of the Pancreas (AFIP Atlas)'
const BIOULAC = 'Bioulac-Sage et al., classificação imuno-histoquímica dos adenomas hepatocelulares, Hepatology'

export const hepatopancreatic: Tumor[] = [
  {
    id: 'hepatocarcinoma',
    name: 'Carcinoma hepatocelular',
    aka: ['hepatocarcinoma', 'CHC', 'HCC', 'hepatocellular carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'adrenal', role: 'metastase', freq: 1 },
    ],
    cells: ['hepatocitoide', 'epitelioide', 'claras', 'oncocitico', 'pleomorfico'],
    architecture: ['trabecular', 'pseudopapilar', 'lencois', 'cistico'],
    features: ['globulos-hialinos', 'mitoses-moderadas', 'necrose', 'nucleolo', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Tumor de células hepatocitoides em trabéculas espessas revestidas por endotélio (capilarização sinusoidal), sem tratos portais dentro da lesão e com a trama de reticulina perdida; nasce quase sempre em fígado cirrótico ou com hepatite crônica, e o painel HSP70, glutamina sintetase e glipicano-3 resolve os casos bem diferenciados.',
    criteria: [
      'Arquitetura trabecular com trabéculas de três ou mais células e revestimento endotelial completo (CD34 difuso nos sinusoides).',
      'Perda ou fragmentação da trama de reticulina, que é o critério mais útil contra adenoma.',
      'Ausência de tratos portais no interior da lesão.',
      'Dois ou mais positivos entre HSP70, glutamina sintetase difusa e glipicano-3 apoiam malignidade em nódulo bem diferenciado.',
      'Invasão estromal ou vascular quando demonstrável fecha o diagnóstico.',
    ],
    markers: [
      { marker: 'arginase', pct: [85, 95], note: 'a mais sensível, inclusive nos pouco diferenciados' },
      { marker: 'heppar1', pct: [70, 90], note: 'a queda nos pouco diferenciados é grande: 83% nos moderados contra 46% nos pouco diferenciados, contra 86% da arginase', source: 'Yan et al., Am J Surg Pathol 34:1147 (2010), arginase-1 contra HepPar-1' },
      { marker: 'cd10', pct: [60, 80], pattern: 'M', note: 'padrão canalicular; é o padrão que conta' },
      { marker: 'cea', pct: [60, 85], pattern: 'M', note: 'CEA policlonal em padrão canalicular; o monoclonal é negativo' },
      { marker: 'glipicano3', pct: [70, 85], note: 'negativo em adenoma e em cirrose, o que o torna útil' },
      { marker: 'hsp70', pct: [60, 80] },
      { marker: 'gs', pct: [50, 75], note: 'o "positivo" é o padrão difuso e forte' },
      { marker: 'reticulina', pct: [85, 95], note: 'o "positivo" é a perda ou as trabéculas espessas' },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [50, 80], note: 'pode ser fraca; não estranhe' },
      { marker: 'afp', pct: [20, 50], note: 'pouco sensível apesar da fama' },
      { marker: 'ck7', pct: [10, 30], note: 'nos de tipo progenitor e no colangiolocelular' },
      { marker: 'ck19', pct: [10, 25], note: 'quando positiva, prognóstico pior' },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'moc31', pct: [0, 15], note: 'o negativo que separa de adenocarcinoma metastático' },
      { marker: 'berep4', pct: [0, 15] },
      { marker: 'cdx2', pct: 0 },
      { marker: 'ttf1', pct: [0, 10], note: 'clone SPT24 pode dar citoplasmática: não é pulmão' },
      { marker: 'sall4', pct: [0, 15], note: 'positivo na variante tipo saco vitelino, de pior prognóstico' },
      { marker: 'ki67', pct: [10, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma hepatocelular: reticulina preservada, glipicano-3 negativo, sem invasão.',
      'Nódulo displásico de alto grau em cirrose: sem perda de reticulina nem CD34 difuso.',
      'Colangiocarcinoma: CK7, CK19 e MOC-31 positivos, arginase negativa.',
      'Metástase de adenocarcinoma: MOC-31 e BerEP4 positivos.',
      'Metástase de carcinoma adrenocortical e de NET: inibina, SF-1 ou sinaptofisina.',
      'Metástase de carcinoma renal: PAX8 e CA-IX.',
    ],
    pitfalls: [
      'HepPar-1 marca também adenocarcinoma gástrico hepatoide, saco vitelino e alguns adenocarcinomas pulmonares.',
      'Glutamina sintetase perivenular é normal; só a difusa conta.',
    ],
    molecular: 'TERT promotor, CTNNB1, TP53; a via da β-catenina dá glutamina sintetase difusa.',
    sources: [WHO, ODZE],
  },
  {
    id: 'hcc-fibrolamelar',
    name: 'Carcinoma hepatocelular fibrolamelar',
    aka: ['fibrolamellar carcinoma', 'HCC fibrolamelar'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
    ],
    cells: ['hepatocitoide', 'oncocitico', 'epitelioide'],
    architecture: ['trabecular', 'lencois'],
    features: ['hialinizacao', 'globulos-hialinos', 'nucleolo', 'mitoses-raras'],
    ages: ['jovem'],
    summary: 'Tumor de adolescente ou adulto jovem com fígado normal, feito de hepatócitos grandes de citoplasma oncocítico e nucléolo enorme, separados em cordões por lamelas espessas de colágeno paralelo; a coexpressão de CK7 com CD68 e a fusão DNAJB1::PRKACA são a assinatura.',
    criteria: [
      'Células poligonais grandes, oncocíticas, com nucléolo eosinofílico muito proeminente.',
      'Bandas lamelares de colágeno denso dispostas em paralelo entre os cordões.',
      'Fígado de fundo normal, sem cirrose, em paciente jovem.',
      'Coexpressão de CK7 e CD68 (padrão granular lisossomal) apoia fortemente.',
      'Confirmação por DNAJB1::PRKACA (FISH ou RT-PCR) quando disponível.',
    ],
    markers: [
      { marker: 'dnajb1', pct: [90, 100], note: 'substituto da fusão DNAJB1::PRKACA; é o critério molecular' },
      { marker: 'ck7', pct: [85, 100], note: 'ao contrário do HCC convencional, que é negativo' },
      { marker: 'cd68', pct: [70, 90], note: 'granular, lisossomal; a combinação com CK7 é característica' },
      { marker: 'arginase', pct: [85, 100] },
      { marker: 'heppar1', pct: [80, 95] },
      { marker: 'cd10', pct: [60, 85], pattern: 'M', note: 'canalicular' },
      { marker: 'glipicano3', pct: [20, 50], note: 'bem menos que no convencional' },
      { marker: 'afp', pct: [0, 10], note: 'tipicamente normal; a AFP sérica não sobe' },
      { marker: 'ck19', pct: [20, 50] },
      { marker: 'ck20', pct: 0 },
      { marker: 'moc31', pct: [0, 10] },
      { marker: 'ki67', pct: [5, 25] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Hiperplasia nodular focal: cicatriz central estrelada, glutamina sintetase em mapa, sem atipia.',
      'HCC convencional esclerosante: em cirrótico, CK7 negativo, sem nucléolo tão proeminente.',
      'Colangiocarcinoma: glandular, arginase negativa.',
    ],
    molecular: 'Deleção de 400 kb em 19p13 gerando DNAJB1::PRKACA.',
    sources: [WHO, ODZE, 'Honeyman et al., Science (2014), DNAJB1-PRKACA no fibrolamelar'],
  },
  {
    id: 'adenoma-hepatocelular',
    name: 'Adenoma hepatocelular',
    aka: ['hepatocellular adenoma', 'adenoma hepático'],
    behavior: 'benigno',
    sites: [{ site: 'figado', role: 'primario', freq: 2 }],
    cells: ['hepatocitoide', 'claras'],
    architecture: ['trabecular', 'lencois'],
    features: ['mitoses-raras', 'hemorragia', 'vacuolos-lipidicos', 'vasos-espessos'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Proliferação de hepatócitos benignos em placas de uma a duas células, sem tratos portais, com arteríolas nuas isoladas no estroma; a subtipagem imuno-histoquímica (HNF1A-inativado, inflamatório, β-catenina ativado) é obrigatória porque só o subtipo β-catenina e o masculino têm risco real de transformação.',
    criteria: [
      'Hepatócitos benignos em placas de no máximo duas células, com reticulina preservada.',
      'Ausência de tratos portais e de ductos biliares; arteríolas isoladas sem veia acompanhante.',
      'Subtipagem obrigatória: LFABP (perda define HNF1A-inativado), SAA e CRP (inflamatório), glutamina sintetase difusa com β-catenina nuclear (β-catenina ativado).',
      'Ausência de atipia citológica, pseudoglândulas e invasão.',
      'Adenoma em homem ou com ativação de β-catenina deve ser ressecado pelo risco de carcinoma.',
    ],
    markers: [
      { marker: 'lfabp', pct: [30, 40], note: 'o positivo é a perda; define o subtipo HNF1A-inativado, que é esteatótico' },
      { marker: 'saa', pct: [30, 45], note: 'define o subtipo inflamatório, o mais comum' },
      { marker: 'gs', pct: [10, 20], note: 'o positivo é o padrão difuso; define o subtipo β-catenina ativado' },
      { marker: 'betacatenina', pct: [10, 20], pattern: 'N', note: 'nuclear focal, difícil de ver; a glutamina sintetase é o substituto prático' },
      { marker: 'arginase', pct: [95, 100] },
      { marker: 'heppar1', pct: [90, 100] },
      { marker: 'cd10', pct: [70, 90], pattern: 'M', note: 'canalicular preservado' },
      { marker: 'reticulina', pct: [0, 10], note: 'preservada; o positivo aqui seria perda, que não ocorre' },
      { marker: 'glipicano3', pct: [0, 10], note: 'o negativo que o separa do HCC' },
      { marker: 'hsp70', pct: [0, 15] },
      { marker: 'ck7', pct: [10, 40], note: 'ductulos periféricos no subtipo inflamatório' },
      { marker: 'cd34', pct: [10, 30], note: 'focal; difuso e completo favorece HCC' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Hiperplasia nodular focal: glutamina sintetase em mapa geográfico ao redor das veias, cicatriz central, ductulos CK7 positivos.',
      'Carcinoma hepatocelular bem diferenciado: perda de reticulina, glipicano-3, CD34 difuso.',
      'Fígado esteatótico não neoplásico: mantém tratos portais.',
    ],
    pitfalls: ['O padrão em mapa da glutamina sintetase (HNF) é facilmente lido como "difuso": compare com a distribuição perivenular.'],
    molecular: 'HNF1A bialélico, IL6ST/STAT3 (inflamatório), CTNNB1 exon 3 (maior risco), sonic hedgehog.',
    sources: [WHO, BIOULAC, ODZE],
  },
  {
    id: 'hiperplasia-nodular-focal',
    name: 'Hiperplasia nodular focal',
    aka: ['HNF', 'focal nodular hyperplasia', 'FNH'],
    behavior: 'benigno',
    sites: [{ site: 'figado', role: 'primario', freq: 2 }],
    cells: ['hepatocitoide'],
    architecture: ['nodular', 'trabecular'],
    features: ['hialinizacao', 'vasos-espessos', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Resposta hiperplásica a uma malformação arterial: nódulo com cicatriz central estrelada contendo artérias de parede espessa, septos fibrosos com ductulos e reação ductular na interface; a glutamina sintetase desenha um mapa geográfico perivenular que é praticamente patognomônico.',
    criteria: [
      'Nódulo com cicatriz central fibrosa contendo vasos arteriais malformados de parede espessa.',
      'Septos fibrosos irradiando da cicatriz, com reação ductular CK7 positiva na interface.',
      'Glutamina sintetase em padrão de mapa geográfico anastomosante ao redor das veias, com áreas negativas entre eles.',
      'Reticulina preservada, arquitetura lobular parcialmente mantida.',
      'Ausência de atipia; não é lesão pré-maligna e não exige ressecção.',
    ],
    markers: [
      { marker: 'gs', pct: [90, 100], note: 'padrão em mapa geográfico; é o achado que define' },
      { marker: 'ck7', pct: [85, 100], note: 'reação ductular nos septos; ausente no adenoma' },
      { marker: 'ck19', pct: [80, 95], note: 'idem' },
      { marker: 'arginase', pct: [95, 100] },
      { marker: 'heppar1', pct: [95, 100] },
      { marker: 'reticulina', pct: [0, 5], note: 'preservada' },
      { marker: 'glipicano3', pct: [0, 5] },
      { marker: 'hsp70', pct: [0, 10] },
      { marker: 'saa', pct: [10, 30], note: 'pode ser focalmente positiva e confundir com adenoma inflamatório' },
      { marker: 'lfabp', pct: [0, 5], note: 'retido' },
      { marker: 'betacatenina', pct: [0, 5], pattern: 'N' },
      { marker: 'cd34', pct: [10, 30], note: 'periseptal' },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma hepatocelular inflamatório: SAA difusa, sem mapa de glutamina sintetase, sem ductulos.',
      'Nódulo regenerativo cirrótico: fígado de fundo cirrótico difuso.',
      'HCC fibrolamelar: nucléolo enorme, CK7 e CD68 nas células tumorais, DNAJB1.',
    ],
    sources: [WHO, BIOULAC, ODZE],
  },
  {
    id: 'hepatoblastoma',
    name: 'Hepatoblastoma',
    aka: ['hepatoblastoma epitelial', 'hepatoblastoma misto epitelial e mesenquimal'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['hepatocitoide', 'blastematoso', 'epitelioide', 'pequenas-redondas'],
    architecture: ['trabecular', 'lencois', 'nodular'],
    features: ['osteoide', 'mitoses-altas', 'hemorragia', 'necrose'],
    ages: ['crianca'],
    summary: 'Tumor hepático maligno da primeira infância que recapitula o fígado em desenvolvimento: componente fetal de células pequenas com alternância clara e escura, componente embrionário mais primitivo em rosetas, e às vezes osteoide e outros tecidos mesenquimais; AFP sérica altíssima e β-catenina nuclear em quase todos.',
    criteria: [
      'Idade: quase sempre abaixo de três anos.',
      'Componente epitelial fetal (padrão claro e escuro alternante) com ou sem embrionário, macrotrabecular ou de células pequenas indiferenciadas.',
      'β-catenina nuclear e citoplasmática refletindo alteração de CTNNB1.',
      'Glipicano-3 e AFP positivos apoiam; AFP sérica muito elevada é regra (exceto no de células pequenas).',
      'INI1 deve ser avaliado no componente de células pequenas indiferenciadas: a perda reclassifica como tumor rabdoide.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [80, 95], pattern: 'N' },
      { marker: 'glipicano3', pct: [85, 100] },
      { marker: 'afp', pct: [80, 95] },
      { marker: 'arginase', pct: [70, 90] },
      { marker: 'heppar1', pct: [70, 90] },
      { marker: 'gs', pct: [70, 95], note: 'difusa, pela ativação de β-catenina' },
      { marker: 'sall4', pct: [40, 80], note: 'no componente embrionário' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define tumor rabdoide' },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'vimentina', pct: [30, 70], note: 'componente mesenquimal' },
      { marker: 'ki67', pct: [20, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma hepatocelular pediátrico: em criança mais velha, sem componente fetal organizado.',
      'Tumor rabdoide: INI1 perdido.',
      'Neuroblastoma metastático: sinaptofisina e PHOX2B positivos, arginase negativa.',
      'Nefroblastoma metastático: WT1 positivo.',
    ],
    molecular: 'CTNNB1 (deleções e mutações do exon 3); associação com polipose adenomatosa familiar e Beckwith-Wiedemann.',
    sources: [WHO, ODZE],
  },
  {
    id: 'colangiocarcinoma-intrahepatico',
    name: 'Colangiocarcinoma intra-hepático',
    aka: ['CCA intra-hepático', 'intrahepatic cholangiocarcinoma', 'colangiocarcinoma periférico'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'trabecular', 'infiltrativo', 'papilar'],
    features: ['desmoplasia', 'mucina', 'perineural', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma de pequenos ductos ou de grandes ductos no parênquima hepático, com glândulas irregulares em estroma desmoplásico denso e mucina; imunologicamente indistinguível de metástase pancreatobiliar, o que faz do afastamento clínico parte do diagnóstico.',
    criteria: [
      'Adenocarcinoma no fígado com CK7 e CK19 positivos e marcadores hepatocitários negativos.',
      'Estroma desmoplásico abundante, invasão perineural frequente.',
      'Exclusão de metástase de pâncreas, vias biliares, estômago e mama por imagem e clínica.',
      'Subtipo de pequenos ductos (periférico, ligado a hepatite crônica, IDH1/2 e FGFR2) contra grandes ductos (hilar, mucinoso, KRAS e TP53).',
      'Componente hepatocelular concomitante define carcinoma combinado.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'moc31', pct: [90, 100] },
      { marker: 'berep4', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck20', pct: [10, 35], note: 'quando forte com CDX2, pense em colorretal metastático' },
      { marker: 'cdx2', pct: [10, 35] },
      { marker: 'arginase', pct: [0, 5], note: 'o negativo que exclui hepatocelular' },
      { marker: 'heppar1', pct: [0, 5] },
      { marker: 'smad4', pct: [15, 30], note: 'o positivo é a perda; bem menos frequente que no pâncreas' },
      { marker: 'maspina', pct: [50, 80] },
      { marker: 's100p', pct: [40, 70] },
      { marker: 'imp3', pct: [60, 85] },
      { marker: 'sox9', pct: [70, 90] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'pax8', pct: [0, 10] },
      { marker: 'er', pct: 0 },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma pancreático metastático: SMAD4 perdido com mais frequência, mas a separação é clínica.',
      'Carcinoma hepatocelular pouco diferenciado: arginase e HepPar-1 positivos, MOC-31 negativo.',
      'Adenocarcinoma colorretal metastático: CDX2 e SATB2 fortes, CK7 negativo.',
      'Reação ductular e colangite: sem atipia, sem invasão perineural, p53 selvagem.',
    ],
    molecular: 'IDH1/IDH2 e fusões de FGFR2 no subtipo de pequenos ductos (alvos terapêuticos); KRAS e TP53 no de grandes ductos.',
    sources: [WHO, ODZE],
  },
  {
    id: 'adenocarcinoma-vesicula-biliar',
    name: 'Adenocarcinoma de vesícula e vias biliares extra-hepáticas',
    aka: ['carcinoma de vesícula biliar', 'colangiocarcinoma extra-hepático', 'tumor de Klatskin'],
    behavior: 'maligno',
    sites: [
      { site: 'vias-biliares', role: 'primario', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide', 'anel-sinete'],
    architecture: ['glandulas', 'papilar', 'infiltrativo'],
    features: ['desmoplasia', 'mucina', 'perineural', 'precursor', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Adenocarcinoma de tipo biliar que costuma ser achado na colecistectomia por litíase, com glândulas angulares infiltrando a parede num estroma desmoplásico e displasia biliar adjacente; perda de SMAD4 e p53 aberrante ajudam contra a atipia reativa da colecistite crônica.',
    criteria: [
      'Glândulas malignas infiltrando além da lâmina própria, com desmoplasia e disposição desordenada.',
      'Displasia biliar de alto grau ou neoplasia papilar intraductal adjacente apoia primário.',
      'Invasão perineural e perda de polaridade nuclear.',
      'Profundidade na parede e o envolvimento do leito hepático definem o T, que é o que mais pesa no prognóstico.',
      'Seios de Rokitansky-Aschoff não devem ser confundidos com invasão.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'muc5ac', pct: [70, 90] },
      { marker: 'moc31', pct: [90, 100] },
      { marker: 'ck20', pct: [20, 50] },
      { marker: 'cdx2', pct: [20, 50] },
      { marker: 'smad4', pct: [30, 50], note: 'o positivo é a perda' },
      { marker: 'p53', pct: [50, 70] },
      { marker: 'maspina', pct: [70, 90] },
      { marker: 's100p', pct: [60, 85] },
      { marker: 'imp3', pct: [60, 85] },
      { marker: 'ck17', pct: [50, 80] },
      { marker: 'arginase', pct: 0 },
      { marker: 'her2', pct: [10, 20], note: 'alvo terapêutico em parte dos de vesícula' },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Colecistite crônica com metaplasia e atipia reativa: p53 selvagem, SMAD4 retido, sem desmoplasia.',
      'Adenomiomatose e seios de Rokitansky-Aschoff: glândulas benignas com lâmina própria, sem desmoplasia.',
      'Adenocarcinoma pancreático invadindo: mesmo perfil, a topografia decide.',
      'Carcinoma hepatocelular invadindo a vesícula: arginase positiva.',
    ],
    molecular: 'TP53, KRAS, CDKN2A; ERBB2 amplificado em parte dos de vesícula.',
    sources: [WHO, ODZE],
  },
  {
    id: 'adenocarcinoma-ductal-pancreas',
    name: 'Adenocarcinoma ductal do pâncreas',
    aka: ['PDAC', 'adenocarcinoma pancreático', 'pancreatic ductal adenocarcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide', 'anel-sinete'],
    architecture: ['glandulas', 'infiltrativo', 'cribriforme'],
    features: ['desmoplasia', 'mucina', 'perineural', 'necrose', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma com glândulas de contorno angular e incompleto, perdidas num estroma desmoplásico desproporcionalmente abundante, ao lado de artérias musculares sem ducto acompanhante e invadindo nervos; a perda de SMAD4 em metade dos casos é o achado imuno mais útil contra pancreatite crônica.',
    criteria: [
      'Glândulas com luz incompleta, contorno angulado e variação nuclear de quatro para um dentro da mesma glândula.',
      'Glândulas isoladas junto a artérias musculares de médio calibre, ou dentro de gordura, ou dentro de nervo: critérios clássicos de invasão.',
      'Estroma desmoplásico desproporcional à quantidade de epitélio.',
      'Perda de SMAD4 ou p53 aberrante confirmam neoplasia quando a distinção com pancreatite é difícil.',
      'Maspina, S100P e IMP3 positivos com mesotelina reforçam malignidade; nenhum isolado basta.',
    ],
    markers: [
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [90, 100] },
      { marker: 'muc5ac', pct: [80, 95] },
      { marker: 'smad4', pct: [50, 60], note: 'o positivo é a perda; a perda confirma neoplasia, a retenção não exclui' },
      { marker: 'maspina', pct: [85, 100], note: 'pâncreas normal é negativo' },
      { marker: 's100p', pct: [85, 100] },
      { marker: 'imp3', pct: [80, 95] },
      { marker: 'mesotelina', pct: [70, 90] },
      { marker: 'p53', pct: [50, 75] },
      { marker: 'claudina4', pct: [85, 100] },
      { marker: 'moc31', pct: [90, 100] },
      { marker: 'ck17', pct: [50, 80] },
      { marker: 'ck20', pct: [20, 40] },
      { marker: 'cdx2', pct: [15, 35] },
      { marker: 'muc2', pct: [5, 20], note: 'difusa favorece IPMN intestinal ou colorretal' },
      { marker: 'tripsina', pct: [0, 5], note: 'o negativo que separa do acinar' },
      { marker: 'sinaptofisina', pct: [0, 10] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Pancreatite crônica e pancreatite autoimune: lobularidade preservada, SMAD4 retido, maspina negativa, IgG4 na autoimune.',
      'Carcinoma de células acinares: tripsina e BCL10 positivos, arquitetura sólida.',
      'NET pancreático: sinaptofisina e cromogranina difusos.',
      'Colangiocarcinoma distal e adenocarcinoma de ampola: mesmo perfil, a topografia decide.',
      'Metástase de adenocarcinoma pulmonar ou mamário: TTF-1 ou GATA3.',
    ],
    pitfalls: ['SMAD4 retido não afasta carcinoma: quase metade dos casos o mantém.'],
    molecular: 'KRAS quase constante, CDKN2A, TP53, SMAD4; germinativas de BRCA em parte, com implicação terapêutica.',
    sources: [WHO, HRUBAN, ODZE],
  },
  {
    id: 'ipmn',
    name: 'Neoplasia mucinosa papilar intraductal (IPMN)',
    aka: ['IPMN', 'neoplasia intraductal papilar mucinosa'],
    behavior: 'intermediario',
    sites: [{ site: 'pancreas', role: 'primario', freq: 2 }],
    cells: ['glandular', 'anel-sinete', 'oncocitico'],
    architecture: ['papilar', 'cistico', 'glandulas'],
    features: ['mucina', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Neoplasia cística que cresce dentro do ducto pancreático principal ou de ramos secundários, produzindo mucina que dilata o sistema ductal e sai pela papila; a subtipagem por mucinas (gástrico, intestinal, pancreatobiliar, oncocítico) e o grau de displasia definem o risco de carcinoma associado.',
    criteria: [
      'Lesão produtora de mucina com envolvimento do ducto, maior que 1 cm, visível macroscopicamente.',
      'Epitélio colunar mucinoso papilar, sem estroma de tipo ovariano (que definiria neoplasia cística mucinosa).',
      'Graduação em displasia de baixo grau e de alto grau, com amostragem generosa.',
      'Busca ativa de carcinoma invasor associado, que muda inteiramente o prognóstico.',
      'Subtipo por MUC1, MUC2, MUC5AC, MUC6 e CDX2: intestinal dá carcinoma coloide, pancreatobiliar dá ductal.',
    ],
    markers: [
      { marker: 'muc5ac', pct: [90, 100], note: 'positiva em todos os subtipos' },
      { marker: 'muc2', pct: [30, 50], note: 'define o subtipo intestinal, junto com CDX2' },
      { marker: 'cdx2', pct: [30, 50], note: 'subtipo intestinal' },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'ck20', pct: [30, 60], note: 'no subtipo intestinal' },
      { marker: 'smad4', pct: [0, 15], note: 'retido na displasia; a perda indica invasão' },
      { marker: 'p53', pct: [10, 40], note: 'aberrante acompanha displasia de alto grau' },
      { marker: 'er', pct: 0, note: 'o negativo estromal que separa da neoplasia cística mucinosa' },
      { marker: 'pr', pct: 0 },
      { marker: 'inibina', pct: 0 },
      { marker: 'ki67', pct: [5, 40], note: 'sobe com o grau de displasia' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Neoplasia cística mucinosa: estroma de tipo ovariano ER, PR e inibina positivo, em mulher, na cauda, sem comunicação ductal.',
      'Cisto de retenção e pseudocisto: sem epitélio neoplásico.',
      'Cistoadenoma seroso: epitélio cuboide claro glicogenado, inibina positiva, sem mucina.',
      'Neoplasia intraductal papilar oncocítica: oncocítica, fusões PRKACA/PRKACB, entidade à parte.',
    ],
    molecular: 'KRAS e GNAS (GNAS é bastante específica de IPMN), RNF43.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'neoplasia-cistica-mucinosa-pancreas',
    name: 'Neoplasia cística mucinosa do pâncreas',
    aka: ['MCN', 'cistoadenoma mucinoso pancreático', 'mucinous cystic neoplasm'],
    behavior: 'intermediario',
    sites: [{ site: 'pancreas', role: 'primario', freq: 2 }],
    cells: ['glandular', 'anel-sinete', 'fusocelular'],
    architecture: ['cistico', 'papilar'],
    features: ['mucina', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Cisto multiloculado do corpo ou cauda do pâncreas em mulher de meia-idade, revestido por epitélio colunar mucinoso e cercado por um estroma celular denso idêntico ao do ovário, que expressa receptores hormonais e inibina; não se comunica com o sistema ductal.',
    criteria: [
      'Estroma de tipo ovariano subepitelial: é o critério obrigatório e definidor.',
      'Epitélio colunar produtor de mucina revestindo cistos, com graduação de displasia.',
      'Ausência de comunicação com o ducto pancreático principal.',
      'Localização em corpo ou cauda, em mulher na quinta ou sexta década.',
      'Amostragem completa da parede para excluir carcinoma invasor.',
    ],
    markers: [
      { marker: 'er', pct: [80, 95], note: 'no estroma ovariano-símile; é o critério imuno' },
      { marker: 'pr', pct: [85, 100], note: 'idem' },
      { marker: 'inibina', pct: [60, 90], note: 'estroma' },
      { marker: 'sf1', pct: [50, 80], note: 'estroma' },
      { marker: 'calretinina', pct: [30, 60], note: 'estroma' },
      { marker: 'muc5ac', pct: [85, 100], note: 'epitélio' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'cdx2', pct: [10, 30] },
      { marker: 'smad4', pct: [0, 15], note: 'retido, salvo em carcinoma associado' },
      { marker: 'p53', pct: [5, 25] },
      { marker: 'ki67', pct: [2, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'IPMN de ramo secundário: comunica com ducto, sem estroma ovariano.',
      'Pseudocisto: parede inflamatória sem epitélio.',
      'Cistoadenoma seroso: epitélio claro glicogenado, sem mucina.',
      'Tumor sólido pseudopapilar cístico: β-catenina nuclear, CD10, perda de E-caderina.',
    ],
    molecular: 'KRAS e RNF43; GNAS ausente, o que ajuda contra IPMN.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'tumor-solido-pseudopapilar',
    name: 'Tumor sólido pseudopapilar do pâncreas',
    aka: ['tumor de Frantz', 'solid pseudopapillary neoplasm', 'SPN'],
    behavior: 'intermediario',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'claras'],
    architecture: ['pseudopapilar', 'lencois', 'cistico'],
    features: ['globulos-hialinos', 'hemorragia', 'hialinizacao', 'mitoses-raras', 'sulcos-inclusoes'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Neoplasia de mulher jovem, discoesa, que descola das paredes vasculares e forma pseudopapilas com eixo mixo-hialino, com glóbulos hialinos PAS positivos e núcleos com sulcos; a β-catenina nuclear com perda de E-caderina de membrana e CD10 forte é o perfil, e a queratina costuma ser negativa.',
    criteria: [
      'Células monótonas discoesas com pseudopapilas de eixo fibrovascular mixoide.',
      'Glóbulos hialinos intracitoplasmáticos e extracelulares, PAS-diastase resistentes.',
      'β-catenina nuclear e citoplasmática difusa (critério prático) com perda da E-caderina de membrana.',
      'Marcadores neuroendócrinos e acinares essencialmente negativos: sinaptofisina pode ser focal, cromogranina é negativa.',
      'Comportamento indolente, mas com potencial metastático em minoria.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [95, 100], pattern: 'N', note: 'o marcador definidor' },
      { marker: 'cd10', pct: [85, 100] },
      { marker: 'cd56', pct: [85, 100] },
      { marker: 'pr', pct: [80, 95] },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 'ciclinad1', pct: [70, 95] },
      { marker: 'ecaderina', pct: [0, 10], note: 'perda da membranosa; o anticorpo do domínio citoplasmático dá nuclear' },
      { marker: 'sinaptofisina', pct: [20, 50], note: 'focal; a difusa favorece NET' },
      { marker: 'cromogranina', pct: [0, 10], note: 'o negativo que separa do NET' },
      { marker: 'ae1ae3', pct: [10, 40], note: 'focal ou negativa, ao contrário dos carcinomas' },
      { marker: 'tripsina', pct: [0, 5] },
      { marker: 'bcl10', pct: [0, 5] },
      { marker: 'er', pct: [0, 15] },
      { marker: 'sox11', pct: [80, 100] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'ck7', pct: [0, 15], note: 'o negativo que ajuda contra adenocarcinoma ductal' },
      { marker: 'ck19', pct: [0, 15] },
      { marker: 'muc5ac', pct: 0 },
      { marker: 'cdx2', pct: 0 },
      { marker: 'p53', pct: [0, 10], note: 'selvagem' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'NET pancreático: cromogranina difusa, queratina forte, β-catenina de membrana.',
      'Carcinoma de células acinares: tripsina e BCL10 positivos, queratina forte.',
      'Pancreatoblastoma: corpúsculos escamoides, em criança, acinar mais escamoso.',
      'Neoplasia cística mucinosa: estroma ovariano, epitélio mucinoso.',
    ],
    pitfalls: ['Queratina negativa num tumor pancreático assusta, mas aqui é o esperado; não pense em sarcoma.'],
    molecular: 'Mutação de CTNNB1 exon 3 em praticamente todos.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'carcinoma-acinar-pancreas',
    name: 'Carcinoma de células acinares do pâncreas',
    aka: ['acinar cell carcinoma pancreático'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'oncocitico', 'glandular'],
    architecture: ['ninhos', 'trabecular', 'lencois', 'glandulas'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma celular e pouco estromal, em ninhos e ácinos de células com citoplasma granular eosinofílico apical e nucléolo único proeminente; produz enzimas pancreáticas, e uma minoria causa necrose gordurosa subcutânea e poliartralgia pela lipase circulante.',
    criteria: [
      'Arquitetura acinar ou sólida densamente celular, com pouquíssimo estroma, ao contrário do ductal.',
      'Citoplasma granular eosinofílico com grânulos de zimogênio PAS-diastase resistentes.',
      'Núcleo redondo e uniforme com nucléolo único central proeminente.',
      'Confirmação por tripsina, quimotripsina ou BCL10 (anticorpo contra carboxil-éster lipase).',
      'Componente neuroendócrino acima de 30% define carcinoma misto acinar-neuroendócrino.',
    ],
    markers: [
      { marker: 'tripsina', pct: [85, 100] },
      { marker: 'bcl10', pct: [85, 100], note: 'clone 331.1; muito útil e mais específico que a tripsina' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'ck7', pct: [20, 50], note: 'bem menos que no ductal' },
      { marker: 'ck19', pct: [20, 50] },
      { marker: 'muc5ac', pct: [0, 10] },
      { marker: 'sinaptofisina', pct: [20, 40], note: 'focal; acima de 30% das células define tumor misto' },
      { marker: 'cromogranina', pct: [10, 30] },
      { marker: 'betacatenina', pct: [5, 20], pattern: 'N' },
      { marker: 'smad4', pct: [0, 10], note: 'retido' },
      { marker: 'glipicano3', pct: [10, 30] },
      { marker: 'afp', pct: [10, 25], note: 'mais nos pancreatoblastomas e nos casos pediátricos' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'NET pancreático: cromogranina difusa, cromatina em sal e pimenta, tripsina negativa.',
      'Pancreatoblastoma: corpúsculos escamoides, em criança.',
      'Adenocarcinoma ductal sólido: muito estroma, maspina e S100P positivos.',
      'Tumor sólido pseudopapilar: β-catenina nuclear, queratina fraca.',
    ],
    molecular: 'Instabilidade cromossômica; fusões BRAF e RAF1 em parte (alvo terapêutico); germinativas de BRCA2 e reparo.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'pancreatoblastoma',
    name: 'Pancreatoblastoma',
    aka: ['pancreatoblastoma infantil'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'blastematoso', 'escamoso'],
    architecture: ['ninhos', 'lencois', 'lobular'],
    features: ['mitoses-altas', 'necrose'],
    ages: ['crianca'],
    summary: 'Tumor pancreático da infância com diferenciação acinar predominante e nódulos escamoides característicos — ilhas de células fusiformes e escamoides com β-catenina nuclear — separados por septos estromais celulares; AFP sérica elevada é comum.',
    criteria: [
      'Corpúsculos escamoides: são obrigatórios para o diagnóstico e concentram a β-catenina nuclear.',
      'Diferenciação acinar predominante, com tripsina e BCL10 positivos.',
      'Septos estromais celulares separando lóbulos, às vezes com osteoide.',
      'Idade pediátrica na maioria; casos adultos existem e são mais agressivos.',
      'Associação com Beckwith-Wiedemann e com polipose adenomatosa familiar.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [80, 95], pattern: 'N', note: 'concentrada nos corpúsculos escamoides' },
      { marker: 'tripsina', pct: [80, 95] },
      { marker: 'bcl10', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'sinaptofisina', pct: [30, 60], note: 'focal' },
      { marker: 'cromogranina', pct: [20, 50] },
      { marker: 'afp', pct: [30, 60] },
      { marker: 'glipicano3', pct: [30, 60] },
      { marker: 'ck7', pct: [20, 50] },
      { marker: 'p63', pct: [30, 60], note: 'nos corpúsculos escamoides' },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma de células acinares: sem corpúsculos escamoides, em adulto.',
      'Tumor sólido pseudopapilar: pseudopapilas, sem diferenciação acinar.',
      'Neuroblastoma e tumores de células redondas: tripsina negativa.',
    ],
    molecular: 'Alterações de CTNNB1 e perda de 11p (via APC/β-catenina).',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'net-pancreatico',
    name: 'Tumor neuroendócrino pancreático',
    aka: ['PanNET', 'insulinoma', 'glucagonoma', 'tumor de ilhotas'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['neuroendocrino', 'epitelioide', 'oncocitico', 'claras', 'plasmocitoide'],
    architecture: ['trabecular', 'ninhos', 'organoide', 'glandulas', 'lencois'],
    features: ['amiloide', 'hialinizacao', 'mitoses-raras', 'vasos-espessos', 'psamomas'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor bem diferenciado em ninhos, trabéculas e rosetas, com cromatina em sal e pimenta e estroma vascular delicado; o grau (G1, G2, G3) sai de Ki-67 e mitoses, e ISL1 com PDX1 ajudam a apontar o pâncreas como origem de uma metástase hepática.',
    criteria: [
      'Morfologia bem diferenciada: organoide, com cromatina granular fina e citoplasma anfofílico.',
      'Sinaptofisina e cromogranina difusas.',
      'Graduação obrigatória: G1 (Ki-67 < 3%), G2 (3 a 20%), G3 (> 20% com morfologia ainda bem diferenciada).',
      'Distinção de carcinoma neuroendócrino de alto grau: este é pouco diferenciado, com RB1 perdido e p53 aberrante.',
      'Funcionalidade é clínica e não histológica; o hormônio por imuno não define a síndrome.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [95, 100] },
      { marker: 'cromogranina', pct: [85, 100] },
      { marker: 'insm1', pct: [90, 100] },
      { marker: 'isl1', pct: [70, 90], note: 'aponta origem pancreática ou retal numa metástase' },
      { marker: 'pdx1', pct: [60, 85] },
      { marker: 'cd56', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'atrx', pct: [10, 25], note: 'o positivo é a perda; associada a pior prognóstico, com DAXX' },
      { marker: 'sstr2', pct: [70, 90], note: 'SSTR2A; preditivo de resposta a análogos de somatostatina' },
      { marker: 'insulina', pct: [30, 60], note: 'especifique o hormônio na nota do caso' },
      { marker: 'serotonina', pct: [5, 20], note: 'quando difusa, pense em NET de intestino médio' },
      { marker: 'cdx2', pct: [5, 20], note: 'positiva favorece intestino médio' },
      { marker: 'ttf1', pct: [0, 10], note: 'positiva favorece pulmão' },
      { marker: 'rb1', pct: [0, 5], note: 'retido; a perda indica carcinoma neuroendócrino de alto grau' },
      { marker: 'p53', pct: [0, 10], note: 'selvagem; aberrante indica alto grau pouco diferenciado' },
      { marker: 'ki67', pct: [1, 20], note: 'o número exato é que dá o grau; conte 500 células' },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'ck19', pct: [20, 50], note: 'quando positiva, prognóstico pior' },
      { marker: 'muc5ac', pct: [0, 10], note: 'o negativo que separa do adenocarcinoma ductal' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma neuroendócrino de alto grau: pouco diferenciado, RB1 perdido, p53 aberrante, Ki-67 muito alto.',
      'Tumor sólido pseudopapilar: β-catenina nuclear, cromogranina negativa.',
      'Carcinoma de células acinares: tripsina e BCL10.',
      'Metástase de NET de íleo: serotonina e CDX2 positivos.',
      'Paraganglioma peripancreático: queratina negativa, GATA3 e sustentaculares.',
    ],
    pitfalls: ['Ilhotas normais aprisionadas em pancreatite crônica podem simular NET pequeno; procure a distribuição lobular.'],
    molecular: 'MEN1, DAXX e ATRX (com telômeros alternativos), via mTOR; associação com NEM 1 e von Hippel-Lindau.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'cistoadenoma-seroso-pancreas',
    name: 'Cistoadenoma seroso do pâncreas',
    aka: ['neoplasia cística serosa', 'serous cystadenoma', 'cistoadenoma microcístico'],
    behavior: 'benigno',
    sites: [{ site: 'pancreas', role: 'primario', freq: 2 }],
    cells: ['claras', 'epitelioide'],
    architecture: ['cistico', 'lobular'],
    features: ['glicogenio', 'hialinizacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Massa multicística em favo de mel com cicatriz central estrelada, revestida por uma camada única de células cuboides pequenas de citoplasma claro cheio de glicogênio e núcleo redondo sem atipia; benigna, e a confusão perigosa é com a neoplasia mucinosa, que é operável.',
    criteria: [
      'Revestimento de camada única de células cuboides claras, ricas em glicogênio (PAS positivo, diastase-lábil).',
      'Ausência de mucina intracitoplasmática: é o ponto que decide.',
      'Arquitetura microcística em favo de mel, com septos finos e cicatriz central.',
      'Ausência de estroma de tipo ovariano.',
      'Inibina e MUC6 positivos apoiam; associação com von Hippel-Lindau.',
    ],
    markers: [
      { marker: 'inibina', pct: [70, 95], note: 'no epitélio; achado útil e contraintuitivo' },
      { marker: 'caix', pct: [60, 90], note: 'reflete a via VHL' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ck19', pct: [60, 85] },
      { marker: 'muc5ac', pct: [0, 10], note: 'o negativo que separa das mucinosas' },
      { marker: 'muc2', pct: [0, 5] },
      { marker: 'cdx2', pct: [0, 5] },
      { marker: 'er', pct: [0, 10], note: 'sem estroma ovariano' },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'pax8', pct: [0, 15] },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Neoplasia cística mucinosa e IPMN: mucina, estroma ovariano no primeiro.',
      'Metástase de carcinoma renal de células claras: PAX8 positivo, inibina negativa, vascularização delicada.',
      'Pseudocisto e cisto linfoepitelial: sem epitélio claro glicogenado.',
      'NET de células claras (VHL): sinaptofisina e cromogranina positivos.',
    ],
    molecular: 'Mutação de VHL somática; associação com a síndrome de von Hippel-Lindau.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'panin',
    name: 'Neoplasia intraepitelial pancreática (PanIN)',
    aka: ['PanIN', 'pancreatic intraepithelial neoplasia', 'displasia ductal pancreática'],
    behavior: 'intermediario',
    sites: [{ site: 'pancreas', role: 'primario', freq: 3 }],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'papilar'],
    features: ['precursor', 'mucina', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Lesão intraductal microscópica, por definição menor que 5 mm, em que o epitélio cúbico do ducto é substituído por epitélio colunar mucinoso, plano ou micropapilar; é o precursor do adenocarcinoma ductal, é achado comum no pâncreas de idoso e, isolada, não tem significado clínico.',
    criteria: [
      'Lesão intraductal menor que 5 mm: acima disso, e formando lesão cística visível, o diagnóstico é neoplasia mucinosa papilar intraductal.',
      'Epitélio colunar produtor de mucina substituindo o epitélio ductal cúbico normal.',
      'Graduação binária desde 2015: baixo grau (a antiga PanIN-1 e 2) e alto grau (a antiga PanIN-3), que equivale a carcinoma in situ.',
      'Alto grau: perda de polaridade, brotamento luminal, núcleos arredondados com nucléolo, mitoses atípicas.',
      'PanIN de baixo grau é frequente no pâncreas normal com a idade e não deve ser relatada como achado de risco.',
    ],
    markers: [
      { marker: 'muc5ac', pct: [90, 100], note: 'positiva já no baixo grau; o ducto normal é negativo' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'maspina', pct: [20, 60], note: 'sobe com o grau; o pâncreas normal é negativo' },
      { marker: 's100p', pct: [20, 60], note: 'idem' },
      { marker: 'imp3', pct: [10, 40] },
      { marker: 'smad4', pct: [0, 15], note: 'o positivo é a perda; ela só aparece no alto grau e no invasor, e por isso ajuda a datar a progressão' },
      { marker: 'p53', pct: [5, 30], note: 'aberrante só no alto grau' },
      { marker: 'muc2', pct: [0, 10], note: 'positiva favorece IPMN de tipo intestinal' },
      { marker: 'cdx2', pct: [0, 15] },
      { marker: 'muc6', pct: [20, 50] },
      { marker: 'ki67', pct: [2, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Ducto pancreático normal com metaplasia mucinosa: sem atipia, MUC5AC pode marcar.',
      'Pancreatite crônica com atipia reativa: lobularidade preservada, maspina e S100P negativas.',
      'IPMN: maior que 5 mm, visível macroscopicamente, com GNAS mutado.',
      'Adenocarcinoma ductal: glândulas fora do sistema ductal, no estroma e junto a artérias musculares.',
      'Lesão de células acinares com metaplasia: tripsina e BCL10 positivos.',
    ],
    pitfalls: ['Um carcinoma ductal bem diferenciado pode crescer dentro dos ductos e imitar PanIN de alto grau (cancerização ductal): procure invasão em volta antes de concluir.'],
    molecular: 'KRAS desde o baixo grau; CDKN2A na progressão; TP53 e SMAD4 no alto grau.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'carcinoma-combinado-hcc-cca',
    name: 'Carcinoma combinado hepatocelular-colangiocarcinoma',
    aka: ['carcinoma hepatocolangiocelular', 'combined hepatocellular-cholangiocarcinoma', 'cHCC-CCA'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
    ],
    cells: ['hepatocitoide', 'glandular', 'epitelioide'],
    architecture: ['trabecular', 'glandulas', 'infiltrativo'],
    features: ['desmoplasia', 'mucina', 'necrose', 'mitoses-altas', 'globulos-hialinos'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Tumor hepático com componente hepatocelular e componente colangiocelular no mesmo nódulo, cada um inequívoco; o prognóstico é pior que o do hepatocarcinoma puro, o transplante costuma ser contraindicado, e o catálogo até aqui obrigava a escolher um dos dois.',
    criteria: [
      'Componente hepatocelular inequívoco (trabéculas, bile, arginase ou HepPar-1) e componente colangiocelular inequívoco (glândulas com mucina, CK19 e CK7) no mesmo tumor.',
      'A demonstração é morfológica, apoiada por imuno: a expressão isolada de CK19 num hepatocarcinoma não basta para o diagnóstico.',
      'Os dois componentes podem estar separados, entremeados ou em transição gradual.',
      'Relatar a proporção de cada componente; a presença de qualquer colangiocelular já muda a conduta cirúrgica.',
      'A categoria antiga de subtipo com células-tronco foi retirada na 5ª edição.',
    ],
    markers: [
      { marker: 'arginase', pct: [70, 95], note: 'componente hepatocelular' },
      { marker: 'heppar1', pct: [60, 90] },
      { marker: 'cd10', pct: [40, 80], pattern: 'M', note: 'canalicular no componente hepatocelular' },
      { marker: 'glipicano3', pct: [40, 80] },
      { marker: 'ck19', pct: [70, 95], note: 'componente colangiocelular' },
      { marker: 'ck7', pct: [70, 95] },
      { marker: 'moc31', pct: [60, 90], note: 'positivo no colangiocelular e negativo no hepatocelular: útil para mostrar os dois' },
      { marker: 'berep4', pct: [50, 85] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'afp', pct: [20, 50] },
      { marker: 'sall4', pct: [10, 40] },
      { marker: 'cdx2', pct: [0, 20] },
      { marker: 'p53', pct: [30, 60] },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Hepatocarcinoma com expressão de CK19: só um componente morfológico, e a CK19 isolada não faz o diagnóstico.',
      'Colangiocarcinoma com aprisionamento de hepatócitos: os hepatócitos são nativos, não neoplásicos.',
      'Hepatocarcinoma com padrão pseudoglandular: as pseudoglândulas contêm bile, não mucina, e são MOC-31 negativas.',
      'Metástase de adenocarcinoma junto a hepatocarcinoma: dois tumores distintos.',
      'Colangiocarcinoma colangiolocelular: cordões finos em estroma fibroso, hoje classificado no colangiocarcinoma de pequenos ductos.',
    ],
    sources: [WHO, ODZE],
  },
  {
    id: 'ipnb',
    name: 'Neoplasia papilar intraductal biliar (IPNB)',
    aka: ['IPNB', 'intraductal papillary neoplasm of the bile duct', 'papilomatose biliar'],
    behavior: 'intermediario',
    sites: [
      { site: 'vias-biliares', role: 'primario', freq: 2 },
      { site: 'figado', role: 'primario', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide', 'oncocitico', 'anel-sinete'],
    architecture: ['papilar', 'cistico', 'glandulas'],
    features: ['mucina', 'mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Contraparte biliar do IPMN: proliferação papilar dentro dos ductos biliares, dilatando-os e às vezes produzindo mucina que sai pela papila. Subtipa-se pelas mesmas mucinas (gástrico, intestinal, pancreatobiliar, oncocítico), e a busca de carcinoma invasor associado é a parte que decide o prognóstico.',
    criteria: [
      'Proliferação papilar intraductal macroscopicamente visível, com eixos fibrovasculares.',
      'Dilatação do ducto acometido, com ou sem produção de mucina.',
      'Subtipagem por MUC1, MUC2, MUC5AC, MUC6 e CDX2, como no IPMN.',
      'Graduação em displasia de baixo e alto grau, com amostragem generosa.',
      'Busca ativa de carcinoma invasor associado: a presença dele governa o prognóstico.',
    ],
    markers: [
      { marker: 'muc5ac', pct: [70, 95] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'muc2', pct: [20, 50], note: 'subtipo intestinal' },
      { marker: 'cdx2', pct: [20, 50] },
      { marker: 'muc6', pct: [30, 60], note: 'subtipo pancreatobiliar e gástrico' },
      { marker: 'ck20', pct: [20, 50] },
      { marker: 's100p', pct: [50, 85] },
      { marker: 'maspina', pct: [40, 80] },
      { marker: 'smad4', pct: [0, 20], note: 'o positivo é a perda; indica invasão' },
      { marker: 'p53', pct: [10, 40], note: 'aberrante acompanha displasia de alto grau' },
      { marker: 'arginase', pct: 0, note: 'o negativo que separa de hepatocarcinoma com padrão pseudopapilar' },
      { marker: 'er', pct: 0, note: 'sem estroma ovariano, ao contrário da neoplasia mucinosa cística' },
      { marker: 'ki67', pct: [10, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Neoplasia mucinosa cística hepatobiliar: estroma de tipo ovariano ER e PR positivo, sem comunicação ductal, em mulher.',
      'Colangiocarcinoma papilar invasor: invasão além da parede do ducto.',
      'Colangite e reação ductular com hiperplasia papilar: sem atipia nem massa.',
      'Adenoma de ducto biliar: nódulo subcapsular sólido de pequenos ductos.',
      'IPMN pancreático com extensão: a topografia decide.',
    ],
    molecular: 'KRAS, GNAS, RNF43 e alterações de CTNNB1, conforme o subtipo.',
    sources: [WHO, ODZE],
  },
  {
    id: 'hemangioma-hepatico',
    name: 'Hemangioma hepático',
    aka: ['hemangioma cavernoso do fígado', 'hemangioma esclerosante hepático'],
    behavior: 'benigno',
    sites: [{ site: 'figado', role: 'primario', freq: 3 }],
    cells: ['vasoformativo', 'epitelioide'],
    architecture: ['cistico', 'nodular'],
    features: ['hemorragia', 'hialinizacao', 'calcificacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'O tumor hepático mais comum e o primeiro a excluir diante de qualquer nódulo: espaços vasculares grandes e cavernosos revestidos por endotélio achatado único, separados por septos fibrosos finos, com trombose e hialinização nas áreas antigas. O esclerosante, quase todo fibrosado, é o que engana na imagem e na biópsia.',
    criteria: [
      'Espaços vasculares dilatados e cavernosos revestidos por camada única de endotélio sem atipia.',
      'Septos fibrosos finos entre os espaços, com trombos organizados e calcificação nas lesões antigas.',
      'Ausência de canais anastomosantes dissecando o parênquima e de atipia endotelial.',
      'Variante esclerosante: colapso e fibrose extensos, com poucos espaços residuais; a imuno endotelial é o que revela a natureza.',
      'Hepatócitos aprisionados na periferia são normais e não devem ser lidos como componente neoplásico.',
    ],
    markers: [
      { marker: 'cd31', pct: [95, 100] },
      { marker: 'erg', pct: [95, 100] },
      { marker: 'cd34', pct: [85, 100] },
      { marker: 'fli1', pct: [90, 100] },
      { marker: 'd240', pct: [0, 20], note: 'o negativo que ajuda contra linfangioma e Kaposi' },
      { marker: 'hhv8', pct: 0, note: 'o negativo que exclui Kaposi' },
      { marker: 'glut1', pct: [0, 10], note: 'o negativo que separa do hemangioma infantil' },
      { marker: 'camta1', pct: [0, 5], note: 'o negativo que exclui hemangioendotelioma epitelioide' },
      { marker: 'myc', pct: [0, 5], note: 'o negativo que ajuda contra angiossarcoma pós-radiação' },
      { marker: 'arginase', pct: [0, 10], note: 'só os hepatócitos aprisionados' },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Angiossarcoma hepático: canais anastomosantes dissecando as trabéculas, atipia endotelial, MYC nos pós-radiação.',
      'Hemangioendotelioma epitelioide: CAMTA1 nuclear, estroma mixo-hialino, cordões de células epitelioides.',
      'Peliose hepática: espaços sem revestimento endotelial próprio.',
      'Hemangioendotelioma infantil hepático: GLUT1 positivo, em lactente, múltiplo.',
      'Cicatriz e nódulo esclerosado: sem endotélio revestindo espaços.',
    ],
    sources: [WHO, ODZE],
  },
  {
    id: 'carcinoma-celulas-gigantes-osteoclasticas-pancreas',
    name: 'Carcinoma indiferenciado com células gigantes osteoclásticas do pâncreas',
    aka: ['undifferentiated carcinoma with osteoclast-like giant cells', 'carcinoma anaplásico pancreático'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['pleomorfico', 'gigantes', 'fusocelular', 'epitelioide'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['gigantes-osteoclasticas', 'hemorragia', 'necrose', 'mitoses-altas', 'osteoide'],
    ages: ['adulto', 'idoso'],
    summary: 'Massa pancreática hemorrágica com lençóis de células mononucleares atípicas misturadas a células gigantes multinucleadas do tipo osteoclasto — e estas são reativas, não neoplásicas, o que é o ponto do verbete: chamar a lesão de sarcoma ou de tumor de células gigantes é o erro que ela provoca.',
    criteria: [
      'Duas populações: células mononucleares atípicas neoplásicas e células gigantes osteoclásticas multinucleadas reativas.',
      'As células gigantes são CD68 positivas e queratina negativa: são histiócitos recrutados, com núcleos brandos e uniformes.',
      'As células mononucleares mantêm queratina ao menos focal e carregam a mutação de KRAS.',
      'Componente de adenocarcinoma ductal convencional está presente em boa parte e apoia.',
      'Osteoide ou osso metaplásico pode ocorrer e não indica osteossarcoma.',
    ],
    markers: [
      { marker: 'cd68', pct: [90, 100], note: 'nas células gigantes, que são reativas' },
      { marker: 'cd163', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [40, 80], note: 'focal, só nas células mononucleares neoplásicas' },
      { marker: 'cam52', pct: [40, 80] },
      { marker: 'ck7', pct: [30, 70] },
      { marker: 'ck19', pct: [30, 70] },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 'p53', pct: [50, 80] },
      { marker: 'smad4', pct: [30, 60], note: 'o positivo é a perda; compartilhada com o adenocarcinoma ductal' },
      { marker: 'catepsinak', pct: [70, 95], note: 'nas células gigantes osteoclásticas' },
      { marker: 'h3g34', pct: 0, note: 'o negativo que exclui tumor de células gigantes do osso' },
      { marker: 'satb2', pct: [10, 40] },
      { marker: 'melana', pct: [0, 5], note: 'o negativo que exclui melanoma' },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma ductal pouco diferenciado: sem células gigantes osteoclásticas.',
      'Tumor de células gigantes de partes moles ou ósseo: H3.3 G34W, queratina negativa.',
      'Sarcoma pleomórfico: queratina negativa, KRAS selvagem.',
      'Pancreatite com reação de corpo estranho: sem células mononucleares atípicas.',
      'Melanoma metastático: SOX10 e HMB-45.',
    ],
    molecular: 'KRAS e TP53, como no adenocarcinoma ductal do qual deriva.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'adenoma-ducto-biliar',
    name: 'Adenoma de ducto biliar e hamartoma biliar',
    aka: ['adenoma de ducto biliar', 'complexo de von Meyenburg', 'hamartoma biliar', 'bile duct adenoma'],
    behavior: 'benigno',
    sites: [{ site: 'figado', role: 'primario', freq: 2 }],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'cistico', 'nodular'],
    features: ['hialinizacao', 'mitoses-raras', 'linfoide'],
    ages: ['adulto', 'idoso'],
    summary: 'Dois nódulos hepáticos benignos que o cirurgião encontra na superfície durante uma laparotomia e manda para congelação como suspeita de metástase. O adenoma de ducto biliar é um nódulo subcapsular sólido de ductos pequenos e uniformes; o complexo de von Meyenburg é um aglomerado de ductos dilatados irregulares com bile inspissada, em estroma fibroso.',
    criteria: [
      'Adenoma de ducto biliar: nódulo subcapsular de até 2 cm, com ductos pequenos, uniformes, revestidos por epitélio cuboide sem atipia, em estroma fibroso.',
      'Complexo de von Meyenburg: ductos dilatados de contorno irregular e ramificado com bile espessa na luz, envoltos por estroma fibroso denso, próximos a trato portal.',
      'Ausência de atipia, de mitoses, de desmoplasia infiltrativa e de invasão perineural.',
      'Ki-67 muito baixo e p53 selvagem, com maspina e S100P negativas, que é o oposto do colangiocarcinoma.',
      'Na congelação, o risco é de virar metástase de adenocarcinoma: o tamanho, a uniformidade e a localização subcapsular resolvem.',
    ],
    markers: [
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'maspina', pct: [0, 15], note: 'o negativo que ajuda contra colangiocarcinoma' },
      { marker: 's100p', pct: [0, 15] },
      { marker: 'imp3', pct: [0, 10] },
      { marker: 'smad4', pct: [0, 5], note: 'retido' },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'arginase', pct: [0, 10], note: 'só os hepatócitos vizinhos' },
      { marker: 'cdx2', pct: [0, 10] },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Colangiocarcinoma bem diferenciado: desmoplasia, invasão perineural, maspina e S100P positivas, Ki-67 alto.',
      'Metástase de adenocarcinoma pancreatobiliar: mesmo perfil do colangiocarcinoma.',
      'Reação ductular periportal: acompanha inflamação e fibrose, sem nódulo.',
      'Hamartoma biliar múltiplo na doença policística: contexto e distribuição.',
      'Neoplasia papilar intraductal biliar: papilas dentro de ducto dilatado.',
    ],
    sources: [WHO, ODZE],
  },
  {
    id: 'itpn-iopn',
    name: 'Neoplasias intraductais pancreáticas não IPMN: ITPN e IOPN',
    aka: ['ITPN', 'neoplasia intraductal tubulopapilar', 'IOPN', 'neoplasia intraductal papilar oncocítica'],
    behavior: 'intermediario',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 1 },
      { site: 'vias-biliares', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'oncocitico', 'glandular'],
    architecture: ['glandulas', 'papilar', 'cribriforme', 'cistico'],
    features: ['necrose', 'mitoses-moderadas', 'mucina', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Duas intraductais pancreáticas que não são IPMN e hoje têm nome próprio. A tubulopapilar é sólida e tubular dentro do ducto, sem mucina visível, com necrose comedo e MUC5AC negativa. A papilar oncocítica é papilar com células oncocíticas e luzes intraepiteliais, tem fusões de PRKACA ou PRKACB e é indolente mesmo quando invade.',
    criteria: [
      'Crescimento intraductal nodular e macroscopicamente visível, sem a mucina abundante do IPMN.',
      'ITPN: túbulos apertados e cribras com necrose comedo, MUC5AC negativa e MUC6 positiva, com displasia de alto grau por definição.',
      'IOPN: papilas arborescentes de células oncocíticas com luzes intraepiteliais em crivo, MUC6 e HepPar-1 positivas.',
      'Ausência de GNAS e de KRAS, que é o oposto do IPMN e ajuda a confirmar.',
      'Prognóstico melhor que o do adenocarcinoma ductal mesmo com invasão associada, sobretudo na IOPN.',
    ],
    markers: [
      { marker: 'muc6', pct: [80, 100], note: 'positiva nas duas: é o marcador que as agrupa' },
      { marker: 'muc5ac', pct: [0, 20], note: 'o negativo que as separa do IPMN' },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'heppar1', pct: [20, 60], note: 'na IOPN, pelo citoplasma oncocítico rico em mitocôndrias' },
      { marker: 'muc2', pct: [0, 15] },
      { marker: 'cdx2', pct: [0, 15] },
      { marker: 'smad4', pct: [0, 15], note: 'retido, ao contrário de metade dos adenocarcinomas ductais' },
      { marker: 'p53', pct: [10, 40] },
      { marker: 'maspina', pct: [40, 80] },
      { marker: 's100p', pct: [20, 60] },
      { marker: 'tripsina', pct: [0, 10], note: 'o negativo que separa do carcinoma de células acinares intraductal' },
      { marker: 'bcl10', pct: [0, 10] },
      { marker: 'ki67', pct: [10, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'IPMN: MUC5AC difusa, mucina abundante, GNAS mutado.',
      'Adenocarcinoma ductal com cancerização de ductos: glândulas infiltrativas em volta, SMAD4 muitas vezes perdido.',
      'Carcinoma de células acinares com crescimento intraductal: tripsina e BCL10 positivos.',
      'PanIN de alto grau: menor que 5 mm, sem massa.',
      'Neoplasia intraductal biliar: mesma família, outro sítio.',
    ],
    molecular: 'Fusões de PRKACA e PRKACB na IOPN; alterações de PIK3CA e da via MAPK na ITPN; sem KRAS nem GNAS.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'sarcoma-embrionario-figado',
    name: 'Sarcoma embrionário indiferenciado do fígado',
    aka: ['undifferentiated embryonal sarcoma of the liver', 'UESL'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['fusocelular', 'estreladas', 'pleomorfico', 'gigantes'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['globulos-hialinos', 'estroma-mixoide', 'necrose', 'mitoses-altas', 'hemorragia'],
    ages: ['crianca'],
    summary: 'Sarcoma hepático da criança em idade escolar, volumoso e parcialmente cístico, feito de células fusiformes e estreladas em matriz mixoide frouxa, com células gigantes bizarras e glóbulos hialinos eosinofílicos intracitoplasmáticos PAS-diastase resistentes — estes últimos são a marca reconhecível da lesão.',
    criteria: [
      'Idade entre 6 e 15 anos, com massa hepática grande, parcialmente cística e hemorrágica.',
      'Células fusiformes e estreladas indiferenciadas em estroma mixoide, com células gigantes multinucleadas bizarras.',
      'Glóbulos hialinos eosinofílicos intracitoplasmáticos e extracelulares, PAS-diastase resistentes.',
      'Ductos biliares e hepatócitos aprisionados na periferia, que não são neoplásicos.',
      'Imuno inespecífica: vimentina difusa, com queratina e desmina focais; o diagnóstico é morfológico e de exclusão.',
    ],
    markers: [
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'cd68', pct: [50, 85], note: 'marca os glóbulos hialinos e histiócitos, sem indicar linhagem' },
      { marker: 'ae1ae3', pct: [20, 50], note: 'focal; não faz do tumor um carcinoma' },
      { marker: 'desmina', pct: [20, 50], note: 'focal' },
      { marker: 'sma', pct: [20, 60] },
      { marker: 'miogenina', pct: [0, 15], note: 'o negativo que exclui rabdomiossarcoma embrionário' },
      { marker: 'myod1', pct: [0, 15] },
      { marker: 'arginase', pct: [0, 10], note: 'só os hepatócitos aprisionados' },
      { marker: 'glipicano3', pct: [0, 20], note: 'o negativo que ajuda contra hepatoblastoma' },
      { marker: 'betacatenina', pct: [0, 15], pattern: 'N' },
      { marker: 'ini1', pct: [0, 10], note: 'retido; a perda indicaria tumor rabdoide' },
      { marker: 'alk', pct: [0, 10] },
      { marker: 'ki67', pct: [30, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Rabdomiossarcoma embrionário do trato biliar: miogenina e MyoD1 positivos, botrioide.',
      'Hepatoblastoma: componente epitelial fetal, β-catenina nuclear, glipicano-3.',
      'Tumor rabdoide: INI1 perdido, em lactente.',
      'Hamartoma mesenquimal hepático: em lactente, cístico, sem atipia; é considerado precursor.',
      'Sarcoma pleomórfico indiferenciado do adulto: outra faixa etária.',
    ],
    sources: [WHO, ODZE],
  },
  {
    id: 'hemangioendotelioma-infantil-hepatico',
    name: 'Hemangioma hepático infantil',
    aka: ['hemangioendotelioma infantil hepático', 'hemangioma infantil do fígado', 'hepatic infantile haemangioma'],
    behavior: 'benigno',
    sites: [{ site: 'figado', role: 'primario', freq: 2 }],
    cells: ['vasoformativo', 'epitelioide'],
    architecture: ['nodular', 'lobular'],
    features: ['hemorragia', 'calcificacao', 'mitoses-moderadas'],
    ages: ['crianca'],
    summary: 'Lesão vascular do lactente, única ou multifocal, com canais capilares revestidos por endotélio plump em lóbulos que envolvem ductos biliares aprisionados; GLUT1 positivo é o que a separa das malformações e do angiossarcoma, e as formas multifocais e difusas podem causar insuficiência cardíaca e hipotireoidismo de consumo.',
    criteria: [
      'Lóbulos de capilares revestidos por endotélio proeminente, com ductos biliares aprisionados entre eles.',
      'GLUT1 positivo no endotélio: o marcador que define o hemangioma infantil e o separa das malformações vasculares.',
      'Fases proliferativa (celular, com mitoses) e involutiva (fibrogordurosa): a mitose na fase proliferativa não indica malignidade.',
      'Formas focal, multifocal e difusa, com consequências clínicas distintas (shunt, hipotireoidismo por deiodinase 3).',
      'Ausência de canais anastomosantes dissecantes e de atipia endotelial, que definiriam angiossarcoma.',
    ],
    markers: [
      { marker: 'glut1', pct: [90, 100], note: 'o marcador que define; ausente nas malformações vasculares' },
      { marker: 'cd31', pct: [95, 100] },
      { marker: 'erg', pct: [95, 100] },
      { marker: 'cd34', pct: [85, 100] },
      { marker: 'fli1', pct: [90, 100] },
      { marker: 'd240', pct: [10, 40] },
      { marker: 'myc', pct: [0, 5], note: 'o negativo que ajuda contra angiossarcoma' },
      { marker: 'camta1', pct: [0, 5] },
      { marker: 'hhv8', pct: 0 },
      { marker: 'arginase', pct: [0, 10], note: 'hepatócitos aprisionados' },
      { marker: 'ck19', pct: [0, 15], note: 'ductos biliares aprisionados' },
      { marker: 'ki67', pct: [5, 30], note: 'alto na fase proliferativa, sem significar malignidade' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Malformação vascular hepática: GLUT1 negativo, sem fase proliferativa.',
      'Angiossarcoma hepático infantil: atipia endotelial, canais dissecantes, multicamadas.',
      'Hemangioendotelioma kaposiforme: D2-40 positivo, GLUT1 negativo, com Kasabach-Merritt.',
      'Hemangioma cavernoso do adulto: espaços cavernosos grandes, GLUT1 negativo.',
      'Peliose e hamartoma mesenquimal: sem proliferação endotelial lobular.',
    ],
    sources: [WHO, ODZE],
  },
  {
    id: 'neoplasia-mucinosa-cistica-hepatobiliar',
    name: 'Neoplasia mucinosa cística hepatobiliar',
    aka: ['cistoadenoma biliar', 'mucinous cystic neoplasm of the liver', 'cistoadenocarcinoma biliar'],
    behavior: 'intermediario',
    sites: [
      { site: 'figado', role: 'primario', freq: 1 },
      { site: 'vias-biliares', role: 'primario', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide', 'fusocelular'],
    architecture: ['cistico', 'papilar'],
    features: ['mucina', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto'],
    sex: 'f',
    summary: 'Lesão cística multiloculada do fígado de mulher de meia-idade, revestida por epitélio colunar mucinoso e envolvida por um estroma celular de tipo ovariano que expressa ER, PR e inibina — exatamente como a contraparte pancreática. Não se comunica com o sistema biliar, o que a separa da neoplasia papilar intraductal.',
    criteria: [
      'Estroma de tipo ovariano subepitelial: é o critério obrigatório e definidor.',
      'Cistos revestidos por epitélio colunar mucinoso ou biliar, com graduação de displasia.',
      'Ausência de comunicação com o sistema ductal biliar.',
      'Predomínio feminino marcante, na quarta e quinta décadas.',
      'Amostragem completa da parede para excluir carcinoma invasor associado, que muda o prognóstico.',
    ],
    markers: [
      { marker: 'er', pct: [80, 95], note: 'estroma ovariano-símile' },
      { marker: 'pr', pct: [85, 100] },
      { marker: 'inibina', pct: [50, 85] },
      { marker: 'sf1', pct: [40, 80] },
      { marker: 'calretinina', pct: [30, 70] },
      { marker: 'ck7', pct: [90, 100], note: 'epitélio' },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'muc5ac', pct: [70, 95] },
      { marker: 'cd10', pct: [30, 70], note: 'estroma' },
      { marker: 'smad4', pct: [0, 15], note: 'retido, salvo em carcinoma associado' },
      { marker: 'p53', pct: [5, 25] },
      { marker: 'arginase', pct: 0 },
      { marker: 'ki67', pct: [2, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Neoplasia papilar intraductal biliar: comunica com o ducto, sem estroma ovariano.',
      'Cisto hepático simples e doença policística: revestimento único sem estroma celular.',
      'Cisto hidático: membrana laminada com escólices.',
      'Hamartoma biliar e doença de Caroli: ductos dilatados sem estroma ovariano.',
      'Neoplasia cística mucinosa pancreática: mesma lesão, outro órgão.',
    ],
    sources: [WHO, ODZE, HRUBAN],
  },
  {
    id: 'cisto-linfoepitelial-pancreas',
    name: 'Cisto linfoepitelial pancreático',
    aka: ['lymphoepithelial cyst of the pancreas'],
    behavior: 'benigno',
    sites: [{ site: 'pancreas', role: 'primario', freq: 1 }],
    cells: ['escamoso', 'linfoide-pequenas'],
    architecture: ['cistico'],
    features: ['queratinizacao', 'linfoide', 'granulomas', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Cisto peripancreático revestido por epitélio escamoso maduro queratinizado, cercado por tecido linfoide denso com centros germinativos; o conteúdo é queratina em flocos, o que na punção devolve material escamoso anucleado e levanta suspeita de neoplasia cística mucinosa ou de carcinoma escamoso.',
    criteria: [
      'Revestimento escamoso maduro, muitas vezes queratinizado, sem atipia.',
      'Manguito de tecido linfoide com centros germinativos ao redor do cisto.',
      'Conteúdo de queratina laminada; colesterol e reação de corpo estranho são frequentes.',
      'Ausência de epitélio mucinoso e de estroma ovariano, o que afasta a neoplasia cística mucinosa.',
      'Lesão benigna, sem potencial maligno: a ressecção só se justifica pela dúvida diagnóstica.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'cd45', pct: [90, 100], note: 'o manguito linfoide, policlonal' },
      { marker: 'cd20', pct: [80, 95], note: 'centros germinativos' },
      { marker: 'cd3', pct: [80, 95] },
      { marker: 'muc5ac', pct: [0, 10], note: 'o negativo que afasta neoplasia cística mucinosa' },
      { marker: 'er', pct: [0, 10], note: 'sem estroma ovariano' },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'ki67', pct: [1, 10] },
    ],
    mimics: [
      'Neoplasia cística mucinosa: epitélio mucinoso com estroma ovariano ER e PR positivo.',
      'Cisto epidermoide em baço acessório intrapancreático: tecido esplênico na parede, CD8 nos sinusoides.',
      'Carcinoma adenoescamoso cístico: atipia franca com invasão.',
      'Pseudocisto: parede inflamatória sem epitélio.',
      'Cisto dermoide e teratoma: anexos cutâneos presentes.',
    ],
    sources: [WHO, HRUBAN],
  },
  {
    id: 'carcinoma-adenoescamoso-pancreas',
    name: 'Carcinoma adenoescamoso do pâncreas',
    aka: ['adenosquamous carcinoma of the pancreas'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['escamoso', 'glandular', 'epitelioide'],
    architecture: ['ninhos', 'glandulas', 'infiltrativo'],
    features: ['queratinizacao', 'necrose', 'desmoplasia', 'mitoses-altas', 'mucina'],
    ages: ['adulto', 'idoso'],
    summary: 'Variante do adenocarcinoma ductal com pelo menos 30% de componente escamoso, mais necrótica e ainda mais agressiva que a forma comum; costuma ser maior ao diagnóstico, com sobrevida menor, e a necrose central extensa é o que chama atenção na macroscopia e na imagem.',
    criteria: [
      'Componente escamoso inequívoco em pelo menos 30% do tumor, com queratinização ou pontes intercelulares.',
      'Componente glandular de adenocarcinoma ductal convencional no restante.',
      'Necrose central extensa é achado frequente e característico.',
      'Exclusão de carcinoma escamoso metastático e de extensão de carcinoma esofágico ou gástrico.',
      'Prognóstico pior que o do adenocarcinoma ductal puro, com sobrevida mediana menor.',
    ],
    markers: [
      { marker: 'p40', pct: [90, 100], note: 'no componente escamoso' },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'ck7', pct: [70, 95], note: 'no componente glandular' },
      { marker: 'ck19', pct: [80, 100] },
      { marker: 'muc5ac', pct: [40, 80] },
      { marker: 'smad4', pct: [50, 70], note: 'o positivo é a perda; mais frequente que no ductal convencional' },
      { marker: 'maspina', pct: [80, 100] },
      { marker: 's100p', pct: [70, 95] },
      { marker: 'p53', pct: [60, 85] },
      { marker: 'ck17', pct: [60, 90] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma ductal com metaplasia escamosa focal: componente escamoso abaixo de 30%.',
      'Carcinoma escamoso metastático: sem componente glandular nem PanIN adjacente.',
      'Carcinoma indiferenciado com células gigantes osteoclásticas: células gigantes CD68 positivas.',
      'Carcinoma escamoso do esôfago distal invadindo: topografia e lesão precursora.',
      'Pancreatite com metaplasia escamosa ductal: sem atipia nem invasão.',
    ],
    molecular: 'KRAS, TP53, CDKN2A e SMAD4, com perda de SMAD4 mais frequente que no ductal convencional.',
    sources: [WHO, HRUBAN],
  },
]
