/* ==========================================================================
   hepatopancreatic.ts — fígado, vias biliares e pâncreas.

   No fígado a imuno resolve três perguntas em sequência: é hepatocelular ou
   não (HepPar-1, arginase, CD10 canalicular), é benigno ou maligno (reticulina,
   glipicano-3, HSP70, glutamina sintetase), e qual o subtipo do adenoma
   (LFABP, SAA/CRP, β-catenina), que é o que decide ressecção ou seguimento.
   No pâncreas a pergunta é quase sempre "ducto reativo ou adenocarcinoma?", e
   aí entram SMAD4, maspina, S100P e IMP3, nunca isolados.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Digestive System Tumours, 2019; Odze & Goldblum, Surgical
   Pathology of the GI Tract, Liver, Biliary Tract and Pancreas, 4ª ed.;
   Bosman e Hruban nos capítulos de pâncreas; séries de Am J Surg Pathol,
   Mod Pathol e Hepatology). As fontes estão como referência de texto: as
   séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Digestive System Tumours (2019)'
const ODZE = 'Odze & Goldblum, Surgical Pathology of the GI Tract, Liver, Biliary Tract and Pancreas, 4ª ed.'
const HRUBAN = 'Hruban, Pitman & Klimstra, Tumors of the Pancreas (AFIP Atlas)'
const BIOULAC = 'Bioulac-Sage et al., classificação imuno-histoquímica dos adenomas hepatocelulares, Hepatology'

export const hepatopancreatic: Tumor[] = [
  {
    id: 'hepatocarcinoma',
    name: 'Carcinoma hepatocelular',
    aka: ['hepatocarcinoma', 'CHC', 'HCC', 'hepatocellular carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'adrenal', role: 'metastase', freq: 1 },
    ],
    cells: ['hepatocitoide', 'epitelioide', 'claras', 'oncocitico', 'pleomorfico'],
    architecture: ['trabecular', 'pseudopapilar', 'lencois', 'cistico'],
    features: ['globulos-hialinos', 'mitoses-moderadas', 'necrose', 'nucleolo', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Tumor de células hepatocitoides em trabéculas espessas revestidas por endotélio (capilarização sinusoidal), sem tratos portais dentro da lesão e com a trama de reticulina perdida; nasce quase sempre em fígado cirrótico ou com hepatite crônica, e o painel HSP70, glutamina sintetase e glipicano-3 resolve os casos bem diferenciados.',
    criteria: [
      'Arquitetura trabecular com trabéculas de três ou mais células e revestimento endotelial completo (CD34 difuso nos sinusoides).',
      'Perda ou fragmentação da trama de reticulina, que é o critério mais útil contra adenoma.',
      'Ausência de tratos portais no interior da lesão.',
      'Dois ou mais positivos entre HSP70, glutamina sintetase difusa e glipicano-3 apoiam malignidade em nódulo bem diferenciado.',
      'Invasão estromal ou vascular quando demonstrável fecha o diagnóstico.',
    ],
    markers: [
      { marker: 'arginase', pct: [85, 95], note: 'a mais sensível, inclusive nos pouco diferenciados' },
      { marker: 'heppar1', pct: [70, 90], note: 'a queda nos pouco diferenciados é grande: 83% nos moderados contra 46% nos pouco diferenciados, contra 86% da arginase', source: 'Yan et al., Am J Surg Pathol 34:1147 (2010), arginase-1 contra HepPar-1' },
      { marker: 'cd10', pct: [60, 80], pattern: 'M', note: 'padrão canalicular; é o padrão que conta' },
      { marker: 'cea', pct: [60, 85], pattern: 'M', note: 'CEA policlonal em padrão canalicular; o monoclonal é negativo' },
      { marker: 'glipicano3', pct: [70, 85], note: 'negativo em adenoma e em cirrose, o que o torna útil' },
      { marker: 'hsp70', pct: [60, 80] },
      { marker: 'gs', pct: [50, 75], note: 'o "positivo" é o padrão difuso e forte' },
      { marker: 'reticulina', pct: [85, 95], note: 'o "positivo" é a perda ou as trabéculas espessas' },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [50, 80], note: 'pode ser fraca; não estranhe' },
      { marker: 'afp', pct: [20, 50], note: 'pouco sensível apesar da fama' },
      { marker: 'ck7', pct: [10, 30], note: 'nos de tipo progenitor e no colangiolocelular' },
      { marker: 'ck19', pct: [10, 25], note: 'quando positiva, prognóstico pior' },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'moc31', pct: [0, 15], note: 'o negativo que separa de adenocarcinoma metastático' },
      { marker: 'berep4', pct: [0, 15] },
      { marker: 'cdx2', pct: 0 },
      { marker: 'ttf1', pct: [0, 10], note: 'clone SPT24 pode dar citoplasmática: não é pulmão' },
      { marker: 'sall4', pct: [0, 15], note: 'positivo na variante tipo saco vitelino, de pior prognóstico' },
      { marker: 'ki67', pct: [10, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma hepatocelular: reticulina preservada, glipicano-3 negativo, sem invasão.',
      'Nódulo displásico de alto grau em cirrose: sem perda de reticulina nem CD34 difuso.',
      'Colangiocarcinoma: CK7, CK19 e MOC-31 positivos, arginase negativa.',
      'Metástase de adenocarcinoma: MOC-31 e BerEP4 positivos.',
      'Metástase de carcinoma adrenocortical e de NET: inibina, SF-1 ou sinaptofisina.',
      'Metástase de carcinoma renal: PAX8 e CA-IX.',
    ],
    pitfalls: [
      'HepPar-1 marca também adenocarcinoma gástrico hepatoide, saco vitelino e alguns adenocarcinomas pulmonares.',
      'Glutamina sintetase perivenular é normal; só a difusa conta.',
    ],
    molecular: 'TERT promotor, CTNNB1, TP53; a via da β-catenina dá glutamina sintetase difusa.',
    sources: [WHO, ODZE],
  },
  {
    id: 'hcc-fibrolamelar',
    name: 'Carcinoma hepatocelular fibrolamelar',
    aka: ['fibrolamellar carcinoma', 'HCC fibrolamelar'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
    ],
    cells: ['hepatocitoide', 'oncocitico', 'epitelioide'],
    architecture: ['trabecular', 'lencois'],
    features: ['hialinizacao', 'globulos-hialinos', 'nucleolo', 'mitoses-raras'],
    ages: ['jovem'],
    summary: 'Tumor de adolescente ou adulto jovem com fígado normal, feito de hepatócitos grandes de citoplasma oncocítico e nucléolo enorme, separados em cordões por lamelas espessas de colágeno paralelo; a coexpressão de CK7 com CD68 e a fusão DNAJB1::PRKACA são a assinatura.',
    criteria: [
      'Células poligonais grandes, oncocíticas, com nucléolo eosinofílico muito proeminente.',
      'Bandas lamelares de colágeno denso dispostas em paralelo entre os cordões.',
      'Fígado de fundo normal, sem cirrose, em paciente jovem.',
      'Coexpressão de CK7 e CD68 (padrão granular lisossomal) apoia fortemente.',
      'Confirmação por DNAJB1::PRKACA (FISH ou RT-PCR) quando disponível.',
    ],
    markers: [
      { marker: 'dnajb1', pct: [90, 100], note: 'substituto da fusão DNAJB1::PRKACA; é o critério molecular' },
      { marker: 'ck7', pct: [85, 100], note: 'ao contrário do HCC convencional, que é negativo' },
      { marker: 'cd68', pct: [70, 90], note: 'granular, lisossomal; a combinação com CK7 é característica' },
      { marker: 'arginase', pct: [85, 100] },
      { marker: 'heppar1', pct: [80, 95] },
      { marker: 'cd10', pct: [60, 85], pattern: 'M', note: 'canalicular' },
      { marker: 'glipicano3', pct: [20, 50], note: 'bem menos que no convencional' },
      { marker: 'afp', pct: [0, 10], note: 'tipicamente normal; a AFP sérica não sobe' },
      { marker: 'ck19', pct: [20, 50] },
      { marker: 'ck20', pct: 0 },
      { marker: 'moc31', pct: [0, 10] },
      { marker: 'ki67', pct: [5, 25] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Hiperplasia nodular focal: cicatriz central estrelada, glutamina sintetase em mapa, sem atipia.',
      'HCC convencional esclerosante: em cirrótico, CK7 negativo, sem nucléolo tão proeminente.',
      'Colangiocarcinoma: glandular, arginase negativa.',
    ],
    molecular: 'Deleção de 400 kb em 19p13 gerando DNAJB1::PRKACA.',
    sources: [WHO, ODZE, 'Honeyman et al., Science (2014), DNAJB1-PRKACA no fibrolamelar'],
  },
  {
    id: 'adenoma-hepatocelular',
    name: 'Adenoma hepatocelular',
    aka: ['hepatocellular adenoma', 'adenoma hepático'],
    behavior: 'benigno',
    sites: [{ site: 'figado', role: 'primario', freq: 2 }],
    cells: ['hepatocitoide', 'claras'],
    architecture: ['trabecular', 'lencois'],
    features: ['mitoses-raras', 'hemorragia', 'vacuolos-lipidicos', 'vasos-espessos'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Proliferação de hepatócitos benignos em placas de uma a duas células, sem tratos portais, com arteríolas nuas isoladas no estroma; a subtipagem imuno-histoquímica (HNF1A-inativado, inflamatório, β-catenina ativado) é obrigatória porque só o subtipo β-catenina e o masculino têm risco real de transformação.',
    criteria: [
      'Hepatócitos benignos em placas de no máximo duas células, com reticulina preservada.',
      'Ausência de tratos portais e de ductos biliares; arteríolas isoladas sem veia acompanhante.',
      'Subtipagem obrigatória: LFABP (perda define HNF1A-inativado), SAA e CRP (inflamatório), glutamina sintetase difusa com β-catenina nuclear (β-catenina ativado).',
      'Ausência de atipia citológica, pseudoglândulas e invasão.',
      'Adenoma em homem ou com ativação de β-catenina deve ser ressecado pelo risco de carcinoma.',
    ],
    markers: [
      { marker: 'lfabp', pct: [30, 40], note: 'o positivo é a perda; define o subtipo HNF1A-inativado, que é esteatótico' },
      { marker: 'saa', pct: [30, 45], note: 'define o subtipo inflamatório, o mais comum' },
      { marker: 'gs', pct: [10, 20], note: 'o positivo é o padrão difuso; define o subtipo β-catenina ativado' },
      { marker: 'betacatenina', pct: [10, 20], pattern: 'N', note: 'nuclear focal, difícil de ver; a glutamina sintetase é o substituto prático' },
      { marker: 'arginase', pct: [95, 100] },
      { marker: 'heppar1', pct: [90, 100] },
      { marker: 'cd10', pct: [70, 90], pattern: 'M', note: 'canalicular preservado' },
      { marker: 'reticulina', pct: [0, 10], note: 'preservada; o positivo aqui seria perda, que não ocorre' },
      { marker: 'glipicano3', pct: [0, 10], note: 'o negativo que o separa do HCC' },
      { marker: 'hsp70', pct: [0, 15] },
      { marker: 'ck7', pct: [10, 40], note: 'ductulos periféricos no subtipo inflamatório' },
      { marker: 'cd34', pct: [10, 30], note: 'focal; difuso e completo favorece HCC' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Hiperplasia nodular focal: glutamina sintetase em mapa geográfico ao redor das veias, cicatriz central, ductulos CK7 positivos.',
      'Carcinoma hepatocelular bem diferenciado: perda de reticulina, glipicano-3, CD34 difuso.',
      'Fígado esteatótico não neoplásico: mantém tratos portais.',
    ],
    pitfalls: ['O padrão em mapa da glutamina sintetase (HNF) é facilmente lido como "difuso": compare com a distribuição perivenular.'],
    molecular: 'HNF1A bialélico, IL6ST/STAT3 (inflamatório), CTNNB1 exon 3 (maior risco), sonic hedgehog.',
    sources: [WHO, BIOULAC, ODZE],
  },
  {
    id: 'hiperplasia-nodular-focal',
    name: 'Hiperplasia nodular focal',
    aka: ['HNF', 'focal nodular hyperplasia', 'FNH'],
    behavior: 'benigno',
    sites: [{ site: 'figado', role: 'primario', freq: 2 }],
    cells: ['hepatocitoide'],
    architecture: ['nodular', 'trabecular'],
    features: ['hialinizacao', 'vasos-espessos', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Resposta hiperplásica a uma malformação arterial: nódulo com cicatriz central estrelada contendo artérias de parede espessa, septos fibrosos com ductulos e reação ductular na interface; a glutamina sintetase desenha um mapa geográfico perivenular que é praticamente patognomônico.',
    criteria: [
      'Nódulo com cicatriz central fibrosa contendo vasos arteriais malformados de parede espessa.',
      'Septos fibrosos irradiando da cicatriz, com reação ductular CK7 positiva na interface.',
      'Glutamina sintetase em padrão de mapa geográfico anastomosante ao redor das veias, com áreas negativas entre eles.',
      'Reticulina preservada, arquitetura lobular parcialmente mantida.',
      'Ausência de atipia; não é lesão pré-maligna e não exige ressecção.',
    ],
    markers: [
      { marker: 'gs', pct: [90, 100], note: 'padrão em mapa geográfico; é o achado que define' },
      { marker: 'ck7', pct: [85, 100], note: 'reação ductular nos septos; ausente no adenoma' },
      { marker: 'ck19', pct: [80, 95], note: 'idem' },
      { marker: 'arginase', pct: [95, 100] },
      { marker: 'heppar1', pct: [95, 100] },
      { marker: 'reticulina', pct: [0, 5], note: 'preservada' },
      { marker: 'glipicano3', pct: [0, 5] },
      { marker: 'hsp70', pct: [0, 10] },
      { marker: 'saa', pct: [10, 30], note: 'pode ser focalmente positiva e confundir com adenoma inflamatório' },
      { marker: 'lfabp', pct: [0, 5], note: 'retido' },
      { marker: 'betacatenina', pct: [0, 5], pattern: 'N' },
      { marker: 'cd34', pct: [10, 30], note: 'periseptal' },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma hepatocelular inflamatório: SAA difusa, sem mapa de glutamina sintetase, sem ductulos.',
      'Nódulo regenerativo cirrótico: fígado de fundo cirrótico difuso.',
      'HCC fibrolamelar: nucléolo enorme, CK7 e CD68 nas células tumorais, DNAJB1.',
    ],
    sources: [WHO, BIOULAC, ODZE],
  },
  {
    id: 'hepatoblastoma',
    name: 'Hepatoblastoma',
    aka: ['hepatoblastoma epitelial', 'hepatoblastoma misto epitelial e mesenquimal'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['hepatocitoide', 'blastematoso', 'epitelioide', 'pequenas-redondas'],
    architecture: ['trabecular', 'lencois', 'nodular'],
    features: ['osteoide', 'mitoses-altas', 'hemorragia', 'necrose'],
    ages: ['crianca'],
    summary: 'Tumor hepático maligno da primeira infância que recapitula o fígado em desenvolvimento: componente fetal de células pequenas com alternância clara e escura, componente embrionário mais primitivo em rosetas, e às vezes osteoide e outros tecidos mesenquimais; AFP sérica altíssima e β-catenina nuclear em quase todos.',
    criteria: [
      'Idade: quase sempre abaixo de três anos.',
      'Componente epitelial fetal (padrão claro e escuro alternante) com ou sem embrionário, macrotrabecular ou de células pequenas indiferenciadas.',
      'β-catenina nuclear e citoplasmática refletindo alteração de CTNNB1.',
      'Glipicano-3 e AFP positivos apoiam; AFP sérica muito elevada é regra (exceto no de células pequenas).',
      'INI1 deve ser avaliado no componente de células pequenas indiferenciadas: a perda reclassifica como tumor rabdoide.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [80, 95], pattern: 'N' },
      { marker: 'glipicano3', pct: [85, 100] },
      { marker: 'afp', pct: [80, 95] },
      { marker: 'arginase', pct: [70, 90] },
      { marker: 'heppar1', pct: [70, 90] },
      { marker: 'gs', pct: [70, 95], note: 'difusa, pela ativação de β-catenina' },
      { marker: 'sall4', pct: [40, 80], note: 'no componente embrionário' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define tumor rabdoide' },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'vimentina', pct: [30, 70], note: 'componente mesenquimal' },
      { marker: 'ki67', pct: [20, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma hepatocelular pediátrico: em criança mais velha, sem componente fetal organizado.',
      'Tumor rabdoide: INI1 perdido.',
      'Neuroblastoma metastático: sinaptofisina e PHOX2B positivos, arginase negativa.',
      'Nefroblastoma metastático: WT1 positivo.',
    ],
    molecular: 'CTNNB1 (deleções e mutações do exon 3); associação com polipose adenomatosa familiar e Beckwith-Wiedemann.',
    sources: [WHO, ODZE],
  },
  {
    id: 'colangiocarcinoma-intrahepatico',
    name: 'Colangiocarcinoma intra-hepático',
    aka: ['CCA intra-hepático', 'intrahepatic cholangiocarcinoma', 'colangiocarcinoma periférico'],
    behavior: 'maligno',
    sites: [
      { site: 'figado', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'trabecular', 'infiltrativo', 'papilar'],
    features: ['desmoplasia', 'mucina', 'perineural', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma de pequenos ductos ou de grandes ductos no parênquima hepático, com glândulas irregulares em estroma desmoplásico denso e mucina; imunologicamente indistinguível de metástase pancreatobiliar, o que faz do afastamento clínico parte do diagnóstico.',
    criteria: [
      'Adenocarcinoma no fígado com CK7 e CK19 positivos e marcadores hepatocitários negativos.',
      'Estroma desmoplásico abundante, invasão perineural frequente.',
      'Exclusão de metástase de pâncreas, vias biliares, estômago e mama por imagem e clínica.',
      'Subtipo de pequenos ductos (periférico, ligado a hepatite crônica, IDH1/2 e FGFR2) contra grandes ductos (hilar, mucinoso, KRAS e TP53).',
      'Componente hepatocelular concomitante define carcinoma combinado.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'moc31', pct: [90, 100] },
      { marker: 'berep4', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck20', pct: [10, 35], note: 'quando forte com CDX2, pense em colorretal metastático' },
      { marker: 'cdx2', pct: [10, 35] },
      { marker: 'arginase', pct: [0, 5], note: 'o negativo que exclui hepatocelular' },
      { marker: 'heppar1', pct: [0, 5] },
      { marker: 'smad4', pct: [15, 30], note: 'o positivo é a perda; bem menos frequente que no pâncreas' },
      { marker: 'maspina', pct: [50, 80] },
      { marker: 's100p', pct: [40, 70] },
      { marker: 'imp3', pct: [60, 85] },
      { marker: 'sox9', pct: [70, 90] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'pax8', pct: [0, 10] },
      { marker: 'er', pct: 0 },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma pancreático metastático: SMAD4 perdido com mais frequência, mas a separação é clínica.',
      'Carcinoma hepatocelular pouco diferenciado: arginase e HepPar-1 positivos, MOC-31 negativo.',
      'Adenocarcinoma colorretal metastático: CDX2 e SATB2 fortes, CK7 negativo.',
      'Reação ductular e colangite: sem atipia, sem invasão perineural, p53 selvagem.',
    ],
    molecular: 'IDH1/IDH2 e fusões de FGFR2 no subtipo de pequenos ductos (alvos terapêuticos); KRAS e TP53 no de grandes ductos.',
    sources: [WHO, ODZE],
  },
  {
    id: 'adenocarcinoma-vesicula-biliar',
    name: 'Adenocarcinoma de vesícula e vias biliares extra-hepáticas',
    aka: ['carcinoma de vesícula biliar', 'colangiocarcinoma extra-hepático', 'tumor de Klatskin'],
    behavior: 'maligno',
    sites: [
      { site: 'vias-biliares', role: 'primario', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide', 'anel-sinete'],
    architecture: ['glandulas', 'papilar', 'infiltrativo'],
    features: ['desmoplasia', 'mucina', 'perineural', 'precursor', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Adenocarcinoma de tipo biliar que costuma ser achado na colecistectomia por litíase, com glândulas angulares infiltrando a parede num estroma desmoplásico e displasia biliar adjacente; perda de SMAD4 e p53 aberrante ajudam contra a atipia reativa da colecistite crônica.',
    criteria: [
      'Glândulas malignas infiltrando além da lâmina própria, com desmoplasia e disposição desordenada.',
      'Displasia biliar de alto grau ou neoplasia papilar intraductal adjacente apoia primário.',
      'Invasão perineural e perda de polaridade nuclear.',
      'Profundidade na parede e o envolvimento do leito hepático definem o T, que é o que mais pesa no prognóstico.',
      'Seios de Rokitansky-Aschoff não devem ser confundidos com invasão.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'muc5ac', pct: [70, 90] },
      { marker: 'moc31', pct: [90, 100] },
      { marker: 'ck20', pct: [20, 50] },
      { marker: 'cdx2', pct: [20, 50] },
      { marker: 'smad4', pct: [30, 50], note: 'o positivo é a perda' },
      { marker: 'p53', pct: [50, 70] },
      { marker: 'maspina', pct: [70, 90] },
      { marker: 's100p', pct: [60, 85] },
      { marker: 'imp3', pct: [60, 85] },
      { marker: 'ck17', pct: [50, 80] },
      { marker: 'arginase', pct: 0 },
      { marker: 'her2', pct: [10, 20], note: 'alvo terapêutico em parte dos de vesícula' },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Colecistite crônica com metaplasia e atipia reativa: p53 selvagem, SMAD4 retido, sem desmoplasia.',
      'Adenomiomatose e seios de Rokitansky-Aschoff: glândulas benignas com lâmina própria, sem desmoplasia.',
      'Adenocarcinoma pancreático invadindo: mesmo perfil, a topografia decide.',
      'Carcinoma hepatocelular invadindo a vesícula: arginase positiva.',
    ],
    molecular: 'TP53, KRAS, CDKN2A; ERBB2 amplificado em parte dos de vesícula.',
    sources: [WHO, ODZE],
  },
  {
    id: 'adenocarcinoma-ductal-pancreas',
    name: 'Adenocarcinoma ductal do pâncreas',
    aka: ['PDAC', 'adenocarcinoma pancreático', 'pancreatic ductal adenocarcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide', 'anel-sinete'],
    architecture: ['glandulas', 'infiltrativo', 'cribriforme'],
    features: ['desmoplasia', 'mucina', 'perineural', 'necrose', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma com glândulas de contorno angular e incompleto, perdidas num estroma desmoplásico desproporcionalmente abundante, ao lado de artérias musculares sem ducto acompanhante e invadindo nervos; a perda de SMAD4 em metade dos casos é o achado imuno mais útil contra pancreatite crônica.',
    criteria: [
      'Glândulas com luz incompleta, contorno angulado e variação nuclear de quatro para um dentro da mesma glândula.',
      'Glândulas isoladas junto a artérias musculares de médio calibre, ou dentro de gordura, ou dentro de nervo: critérios clássicos de invasão.',
      'Estroma desmoplásico desproporcional à quantidade de epitélio.',
      'Perda de SMAD4 ou p53 aberrante confirmam neoplasia quando a distinção com pancreatite é difícil.',
      'Maspina, S100P e IMP3 positivos com mesotelina reforçam malignidade; nenhum isolado basta.',
    ],
    markers: [
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [90, 100] },
      { marker: 'muc5ac', pct: [80, 95] },
      { marker: 'smad4', pct: [50, 60], note: 'o positivo é a perda; a perda confirma neoplasia, a retenção não exclui' },
      { marker: 'maspina', pct: [85, 100], note: 'pâncreas normal é negativo' },
      { marker: 's100p', pct: [85, 100] },
      { marker: 'imp3', pct: [80, 95] },
      { marker: 'mesotelina', pct: [70, 90] },
      { marker: 'p53', pct: [50, 75] },
      { marker: 'claudina4', pct: [85, 100] },
      { marker: 'moc31', pct: [90, 100] },
      { marker: 'ck17', pct: [50, 80] },
      { marker: 'ck20', pct: [20, 40] },
      { marker: 'cdx2', pct: [15, 35] },
      { marker: 'muc2', pct: [5, 20], note: 'difusa favorece IPMN intestinal ou colorretal' },
      { marker: 'tripsina', pct: [0, 5], note: 'o negativo que separa do acinar' },
      { marker: 'sinaptofisina', pct: [0, 10] },
      { marker: 'ttf1', pct: 0 },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Pancreatite crônica e pancreatite autoimune: lobularidade preservada, SMAD4 retido, maspina negativa, IgG4 na autoimune.',
      'Carcinoma de células acinares: tripsina e BCL10 positivos, arquitetura sólida.',
      'NET pancreático: sinaptofisina e cromogranina difusos.',
      'Colangiocarcinoma distal e adenocarcinoma de ampola: mesmo perfil, a topografia decide.',
      'Metástase de adenocarcinoma pulmonar ou mamário: TTF-1 ou GATA3.',
    ],
    pitfalls: ['SMAD4 retido não afasta carcinoma: quase metade dos casos o mantém.'],
    molecular: 'KRAS quase constante, CDKN2A, TP53, SMAD4; germinativas de BRCA em parte, com implicação terapêutica.',
    sources: [WHO, HRUBAN, ODZE],
  },
  {
    id: 'ipmn',
    name: 'Neoplasia mucinosa papilar intraductal (IPMN)',
    aka: ['IPMN', 'neoplasia intraductal papilar mucinosa'],
    behavior: 'intermediario',
    sites: [{ site: 'pancreas', role: 'primario', freq: 2 }],
    cells: ['glandular', 'anel-sinete', 'oncocitico'],
    architecture: ['papilar', 'cistico', 'glandulas'],
    features: ['mucina', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Neoplasia cística que cresce dentro do ducto pancreático principal ou de ramos secundários, produzindo mucina que dilata o sistema ductal e sai pela papila; a subtipagem por mucinas (gástrico, intestinal, pancreatobiliar, oncocítico) e o grau de displasia definem o risco de carcinoma associado.',
    criteria: [
      'Lesão produtora de mucina com envolvimento do ducto, maior que 1 cm, visível macroscopicamente.',
      'Epitélio colunar mucinoso papilar, sem estroma de tipo ovariano (que definiria neoplasia cística mucinosa).',
      'Graduação em displasia de baixo grau e de alto grau, com amostragem generosa.',
      'Busca ativa de carcinoma invasor associado, que muda inteiramente o prognóstico.',
      'Subtipo por MUC1, MUC2, MUC5AC, MUC6 e CDX2: intestinal dá carcinoma coloide, pancreatobiliar dá ductal.',
    ],
    markers: [
      { marker: 'muc5ac', pct: [90, 100], note: 'positiva em todos os subtipos' },
      { marker: 'muc2', pct: [30, 50], note: 'define o subtipo intestinal, junto com CDX2' },
      { marker: 'cdx2', pct: [30, 50], note: 'subtipo intestinal' },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'ck20', pct: [30, 60], note: 'no subtipo intestinal' },
      { marker: 'smad4', pct: [0, 15], note: 'retido na displasia; a perda indica invasão' },
      { marker: 'p53', pct: [10, 40], note: 'aberrante acompanha displasia de alto grau' },
      { marker: 'er', pct: 0, note: 'o negativo estromal que separa da neoplasia cística mucinosa' },
      { marker: 'pr', pct: 0 },
      { marker: 'inibina', pct: 0 },
      { marker: 'ki67', pct: [5, 40], note: 'sobe com o grau de displasia' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Neoplasia cística mucinosa: estroma de tipo ovariano ER, PR e inibina positivo, em mulher, na cauda, sem comunicação ductal.',
      'Cisto de retenção e pseudocisto: sem epitélio neoplásico.',
      'Cistoadenoma seroso: epitélio cuboide claro glicogenado, inibina positiva, sem mucina.',
      'Neoplasia intraductal papilar oncocítica: oncocítica, fusões PRKACA/PRKACB, entidade à parte.',
    ],
    molecular: 'KRAS e GNAS (GNAS é bastante específica de IPMN), RNF43.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'neoplasia-cistica-mucinosa-pancreas',
    name: 'Neoplasia cística mucinosa do pâncreas',
    aka: ['MCN', 'cistoadenoma mucinoso pancreático', 'mucinous cystic neoplasm'],
    behavior: 'intermediario',
    sites: [{ site: 'pancreas', role: 'primario', freq: 2 }],
    cells: ['glandular', 'anel-sinete', 'fusocelular'],
    architecture: ['cistico', 'papilar'],
    features: ['mucina', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Cisto multiloculado do corpo ou cauda do pâncreas em mulher de meia-idade, revestido por epitélio colunar mucinoso e cercado por um estroma celular denso idêntico ao do ovário, que expressa receptores hormonais e inibina; não se comunica com o sistema ductal.',
    criteria: [
      'Estroma de tipo ovariano subepitelial: é o critério obrigatório e definidor.',
      'Epitélio colunar produtor de mucina revestindo cistos, com graduação de displasia.',
      'Ausência de comunicação com o ducto pancreático principal.',
      'Localização em corpo ou cauda, em mulher na quinta ou sexta década.',
      'Amostragem completa da parede para excluir carcinoma invasor.',
    ],
    markers: [
      { marker: 'er', pct: [80, 95], note: 'no estroma ovariano-símile; é o critério imuno' },
      { marker: 'pr', pct: [85, 100], note: 'idem' },
      { marker: 'inibina', pct: [60, 90], note: 'estroma' },
      { marker: 'sf1', pct: [50, 80], note: 'estroma' },
      { marker: 'calretinina', pct: [30, 60], note: 'estroma' },
      { marker: 'muc5ac', pct: [85, 100], note: 'epitélio' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [85, 100] },
      { marker: 'cdx2', pct: [10, 30] },
      { marker: 'smad4', pct: [0, 15], note: 'retido, salvo em carcinoma associado' },
      { marker: 'p53', pct: [5, 25] },
      { marker: 'ki67', pct: [2, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'IPMN de ramo secundário: comunica com ducto, sem estroma ovariano.',
      'Pseudocisto: parede inflamatória sem epitélio.',
      'Cistoadenoma seroso: epitélio claro glicogenado, sem mucina.',
      'Tumor sólido pseudopapilar cístico: β-catenina nuclear, CD10, perda de E-caderina.',
    ],
    molecular: 'KRAS e RNF43; GNAS ausente, o que ajuda contra IPMN.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'tumor-solido-pseudopapilar',
    name: 'Tumor sólido pseudopapilar do pâncreas',
    aka: ['tumor de Frantz', 'solid pseudopapillary neoplasm', 'SPN'],
    behavior: 'intermediario',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'claras'],
    architecture: ['pseudopapilar', 'lencois', 'cistico'],
    features: ['globulos-hialinos', 'hemorragia', 'hialinizacao', 'mitoses-raras', 'sulcos-inclusoes'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Neoplasia de mulher jovem, discoesa, que descola das paredes vasculares e forma pseudopapilas com eixo mixo-hialino, com glóbulos hialinos PAS positivos e núcleos com sulcos; a β-catenina nuclear com perda de E-caderina de membrana e CD10 forte é o perfil, e a queratina costuma ser negativa.',
    criteria: [
      'Células monótonas discoesas com pseudopapilas de eixo fibrovascular mixoide.',
      'Glóbulos hialinos intracitoplasmáticos e extracelulares, PAS-diastase resistentes.',
      'β-catenina nuclear e citoplasmática difusa (critério prático) com perda da E-caderina de membrana.',
      'Marcadores neuroendócrinos e acinares essencialmente negativos: sinaptofisina pode ser focal, cromogranina é negativa.',
      'Comportamento indolente, mas com potencial metastático em minoria.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [95, 100], pattern: 'N', note: 'o marcador definidor' },
      { marker: 'cd10', pct: [85, 100] },
      { marker: 'cd56', pct: [85, 100] },
      { marker: 'pr', pct: [80, 95] },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 'ciclinad1', pct: [70, 95] },
      { marker: 'ecaderina', pct: [0, 10], note: 'perda da membranosa; o anticorpo do domínio citoplasmático dá nuclear' },
      { marker: 'sinaptofisina', pct: [20, 50], note: 'focal; a difusa favorece NET' },
      { marker: 'cromogranina', pct: [0, 10], note: 'o negativo que separa do NET' },
      { marker: 'ae1ae3', pct: [10, 40], note: 'focal ou negativa, ao contrário dos carcinomas' },
      { marker: 'tripsina', pct: [0, 5] },
      { marker: 'bcl10', pct: [0, 5] },
      { marker: 'er', pct: [0, 15] },
      { marker: 'sox11', pct: [80, 100] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'ck7', pct: [0, 15], note: 'o negativo que ajuda contra adenocarcinoma ductal' },
      { marker: 'ck19', pct: [0, 15] },
      { marker: 'muc5ac', pct: 0 },
      { marker: 'cdx2', pct: 0 },
      { marker: 'p53', pct: [0, 10], note: 'selvagem' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'NET pancreático: cromogranina difusa, queratina forte, β-catenina de membrana.',
      'Carcinoma de células acinares: tripsina e BCL10 positivos, queratina forte.',
      'Pancreatoblastoma: corpúsculos escamoides, em criança, acinar mais escamoso.',
      'Neoplasia cística mucinosa: estroma ovariano, epitélio mucinoso.',
    ],
    pitfalls: ['Queratina negativa num tumor pancreático assusta, mas aqui é o esperado; não pense em sarcoma.'],
    molecular: 'Mutação de CTNNB1 exon 3 em praticamente todos.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'carcinoma-acinar-pancreas',
    name: 'Carcinoma de células acinares do pâncreas',
    aka: ['acinar cell carcinoma pancreático'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'oncocitico', 'glandular'],
    architecture: ['ninhos', 'trabecular', 'lencois', 'glandulas'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma celular e pouco estromal, em ninhos e ácinos de células com citoplasma granular eosinofílico apical e nucléolo único proeminente; produz enzimas pancreáticas, e uma minoria causa necrose gordurosa subcutânea e poliartralgia pela lipase circulante.',
    criteria: [
      'Arquitetura acinar ou sólida densamente celular, com pouquíssimo estroma, ao contrário do ductal.',
      'Citoplasma granular eosinofílico com grânulos de zimogênio PAS-diastase resistentes.',
      'Núcleo redondo e uniforme com nucléolo único central proeminente.',
      'Confirmação por tripsina, quimotripsina ou BCL10 (anticorpo contra carboxil-éster lipase).',
      'Componente neuroendócrino acima de 30% define carcinoma misto acinar-neuroendócrino.',
    ],
    markers: [
      { marker: 'tripsina', pct: [85, 100] },
      { marker: 'bcl10', pct: [85, 100], note: 'clone 331.1; muito útil e mais específico que a tripsina' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'ck7', pct: [20, 50], note: 'bem menos que no ductal' },
      { marker: 'ck19', pct: [20, 50] },
      { marker: 'muc5ac', pct: [0, 10] },
      { marker: 'sinaptofisina', pct: [20, 40], note: 'focal; acima de 30% das células define tumor misto' },
      { marker: 'cromogranina', pct: [10, 30] },
      { marker: 'betacatenina', pct: [5, 20], pattern: 'N' },
      { marker: 'smad4', pct: [0, 10], note: 'retido' },
      { marker: 'glipicano3', pct: [10, 30] },
      { marker: 'afp', pct: [10, 25], note: 'mais nos pancreatoblastomas e nos casos pediátricos' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'NET pancreático: cromogranina difusa, cromatina em sal e pimenta, tripsina negativa.',
      'Pancreatoblastoma: corpúsculos escamoides, em criança.',
      'Adenocarcinoma ductal sólido: muito estroma, maspina e S100P positivos.',
      'Tumor sólido pseudopapilar: β-catenina nuclear, queratina fraca.',
    ],
    molecular: 'Instabilidade cromossômica; fusões BRAF e RAF1 em parte (alvo terapêutico); germinativas de BRCA2 e reparo.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'pancreatoblastoma',
    name: 'Pancreatoblastoma',
    aka: ['pancreatoblastoma infantil'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'blastematoso', 'escamoso'],
    architecture: ['ninhos', 'lencois', 'lobular'],
    features: ['mitoses-altas', 'necrose'],
    ages: ['crianca'],
    summary: 'Tumor pancreático da infância com diferenciação acinar predominante e nódulos escamoides característicos — ilhas de células fusiformes e escamoides com β-catenina nuclear — separados por septos estromais celulares; AFP sérica elevada é comum.',
    criteria: [
      'Corpúsculos escamoides: são obrigatórios para o diagnóstico e concentram a β-catenina nuclear.',
      'Diferenciação acinar predominante, com tripsina e BCL10 positivos.',
      'Septos estromais celulares separando lóbulos, às vezes com osteoide.',
      'Idade pediátrica na maioria; casos adultos existem e são mais agressivos.',
      'Associação com Beckwith-Wiedemann e com polipose adenomatosa familiar.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [80, 95], pattern: 'N', note: 'concentrada nos corpúsculos escamoides' },
      { marker: 'tripsina', pct: [80, 95] },
      { marker: 'bcl10', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'sinaptofisina', pct: [30, 60], note: 'focal' },
      { marker: 'cromogranina', pct: [20, 50] },
      { marker: 'afp', pct: [30, 60] },
      { marker: 'glipicano3', pct: [30, 60] },
      { marker: 'ck7', pct: [20, 50] },
      { marker: 'p63', pct: [30, 60], note: 'nos corpúsculos escamoides' },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma de células acinares: sem corpúsculos escamoides, em adulto.',
      'Tumor sólido pseudopapilar: pseudopapilas, sem diferenciação acinar.',
      'Neuroblastoma e tumores de células redondas: tripsina negativa.',
    ],
    molecular: 'Alterações de CTNNB1 e perda de 11p (via APC/β-catenina).',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'net-pancreatico',
    name: 'Tumor neuroendócrino pancreático',
    aka: ['PanNET', 'insulinoma', 'glucagonoma', 'tumor de ilhotas'],
    behavior: 'maligno',
    sites: [
      { site: 'pancreas', role: 'primario', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['neuroendocrino', 'epitelioide', 'oncocitico', 'claras', 'plasmocitoide'],
    architecture: ['trabecular', 'ninhos', 'organoide', 'glandulas', 'lencois'],
    features: ['amiloide', 'hialinizacao', 'mitoses-raras', 'vasos-espessos', 'psamomas'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor bem diferenciado em ninhos, trabéculas e rosetas, com cromatina em sal e pimenta e estroma vascular delicado; o grau (G1, G2, G3) sai de Ki-67 e mitoses, e ISL1 com PDX1 ajudam a apontar o pâncreas como origem de uma metástase hepática.',
    criteria: [
      'Morfologia bem diferenciada: organoide, com cromatina granular fina e citoplasma anfofílico.',
      'Sinaptofisina e cromogranina difusas.',
      'Graduação obrigatória: G1 (Ki-67 < 3%), G2 (3 a 20%), G3 (> 20% com morfologia ainda bem diferenciada).',
      'Distinção de carcinoma neuroendócrino de alto grau: este é pouco diferenciado, com RB1 perdido e p53 aberrante.',
      'Funcionalidade é clínica e não histológica; o hormônio por imuno não define a síndrome.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [95, 100] },
      { marker: 'cromogranina', pct: [85, 100] },
      { marker: 'insm1', pct: [90, 100] },
      { marker: 'isl1', pct: [70, 90], note: 'aponta origem pancreática ou retal numa metástase' },
      { marker: 'pdx1', pct: [60, 85] },
      { marker: 'cd56', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'atrx', pct: [10, 25], note: 'o positivo é a perda; associada a pior prognóstico, com DAXX' },
      { marker: 'sstr2', pct: [70, 90], note: 'SSTR2A; preditivo de resposta a análogos de somatostatina' },
      { marker: 'insulina', pct: [30, 60], note: 'especifique o hormônio na nota do caso' },
      { marker: 'serotonina', pct: [5, 20], note: 'quando difusa, pense em NET de intestino médio' },
      { marker: 'cdx2', pct: [5, 20], note: 'positiva favorece intestino médio' },
      { marker: 'ttf1', pct: [0, 10], note: 'positiva favorece pulmão' },
      { marker: 'rb1', pct: [0, 5], note: 'retido; a perda indica carcinoma neuroendócrino de alto grau' },
      { marker: 'p53', pct: [0, 10], note: 'selvagem; aberrante indica alto grau pouco diferenciado' },
      { marker: 'ki67', pct: [1, 20], note: 'o número exato é que dá o grau; conte 500 células' },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'ck19', pct: [20, 50], note: 'quando positiva, prognóstico pior' },
      { marker: 'muc5ac', pct: [0, 10], note: 'o negativo que separa do adenocarcinoma ductal' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma neuroendócrino de alto grau: pouco diferenciado, RB1 perdido, p53 aberrante, Ki-67 muito alto.',
      'Tumor sólido pseudopapilar: β-catenina nuclear, cromogranina negativa.',
      'Carcinoma de células acinares: tripsina e BCL10.',
      'Metástase de NET de íleo: serotonina e CDX2 positivos.',
      'Paraganglioma peripancreático: queratina negativa, GATA3 e sustentaculares.',
    ],
    pitfalls: ['Ilhotas normais aprisionadas em pancreatite crônica podem simular NET pequeno; procure a distribuição lobular.'],
    molecular: 'MEN1, DAXX e ATRX (com telômeros alternativos), via mTOR; associação com NEM 1 e von Hippel-Lindau.',
    sources: [WHO, HRUBAN],
  },
  {
    id: 'cistoadenoma-seroso-pancreas',
    name: 'Cistoadenoma seroso do pâncreas',
    aka: ['neoplasia cística serosa', 'serous cystadenoma', 'cistoadenoma microcístico'],
    behavior: 'benigno',
    sites: [{ site: 'pancreas', role: 'primario', freq: 2 }],
    cells: ['claras', 'epitelioide'],
    architecture: ['cistico', 'lobular'],
    features: ['glicogenio', 'hialinizacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Massa multicística em favo de mel com cicatriz central estrelada, revestida por uma camada única de células cuboides pequenas de citoplasma claro cheio de glicogênio e núcleo redondo sem atipia; benigna, e a confusão perigosa é com a neoplasia mucinosa, que é operável.',
    criteria: [
      'Revestimento de camada única de células cuboides claras, ricas em glicogênio (PAS positivo, diastase-lábil).',
      'Ausência de mucina intracitoplasmática: é o ponto que decide.',
      'Arquitetura microcística em favo de mel, com septos finos e cicatriz central.',
      'Ausência de estroma de tipo ovariano.',
      'Inibina e MUC6 positivos apoiam; associação com von Hippel-Lindau.',
    ],
    markers: [
      { marker: 'inibina', pct: [70, 95], note: 'no epitélio; achado útil e contraintuitivo' },
      { marker: 'caix', pct: [60, 90], note: 'reflete a via VHL' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ck19', pct: [60, 85] },
      { marker: 'muc5ac', pct: [0, 10], note: 'o negativo que separa das mucinosas' },
      { marker: 'muc2', pct: [0, 5] },
      { marker: 'cdx2', pct: [0, 5] },
      { marker: 'er', pct: [0, 10], note: 'sem estroma ovariano' },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'pax8', pct: [0, 15] },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Neoplasia cística mucinosa e IPMN: mucina, estroma ovariano no primeiro.',
      'Metástase de carcinoma renal de células claras: PAX8 positivo, inibina negativa, vascularização delicada.',
      'Pseudocisto e cisto linfoepitelial: sem epitélio claro glicogenado.',
      'NET de células claras (VHL): sinaptofisina e cromogranina positivos.',
    ],
    molecular: 'Mutação de VHL somática; associação com a síndrome de von Hippel-Lindau.',
    sources: [WHO, HRUBAN],
  },
]
