/* ==========================================================================
   kidneyurothelial.ts — rim, via urinária e adrenal.

   No rim quase tudo é PAX8 positivo, e o trabalho é separar os subtipos:
   CA-IX em caixa e CD10 nas células claras, AMACR e vimentina no papilar,
   CK7 difusa com CD117 no cromófobo, e as perdas (FH, SDHB, INI1) e ganhos
   (TFE3, TFEB) nos moleculares. Na via urinária, GATA3 com p63 e uroplaquina
   respondem "é urotelial?", e o resto do painel responde "de onde veio?".

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Urinary and Male Genital Tumours, 2022; Amin, Epstein &
   Reuter nos capítulos de rim e bexiga; recomendações ISUP; séries de Am J
   Surg Pathol e Mod Pathol). As fontes estão como referência de texto: as
   séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Urinary and Male Genital Tumours (2022)'
const AMIN = 'Amin, Epstein & Reuter, capítulos de patologia renal e vesical; Urologic Surgical Pathology, 4ª ed.'
const ISUP = 'Recomendações da International Society of Urological Pathology (ISUP) para imuno-histoquímica em tumores renais'

export const kidneyurothelial: Tumor[] = [
  {
    id: 'rcc-celulas-claras',
    name: 'Carcinoma renal de células claras',
    aka: ['RCC de células claras', 'clear cell renal cell carcinoma', 'ccRCC'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 2 },
      { site: 'adrenal', role: 'metastase', freq: 2 },
      { site: 'tireoide', role: 'metastase', freq: 1 },
      { site: 'pancreas', role: 'metastase', freq: 1 },
    ],
    cells: ['claras', 'epitelioide', 'oncocitico', 'rabdoide', 'fusocelular'],
    architecture: ['ninhos', 'alveolar', 'cistico', 'lencois'],
    features: ['hemorragia', 'necrose', 'glicogenio', 'nucleolo', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'O carcinoma renal mais comum: ninhos de células de citoplasma claro pelo glicogênio e lipídio, separados por uma rede capilar delicada em arcadas; CA-IX em padrão de caixa e CD10 com PAX8 fecham a origem, e a graduação é pelo nucléolo (ISUP/WHO).',
    criteria: [
      'Ninhos e alvéolos de células claras delimitados por rede capilar fina e regular.',
      'Graduação nucleolar da ISUP/WHO: grau 1 a 3 pelo nucléolo, grau 4 por sarcomatoide, rabdoide ou pleomorfismo extremo.',
      'Componente sarcomatoide ou rabdoide deve ser quantificado: muda o prognóstico e a terapia.',
      'CA-IX em padrão de caixa, difuso e membranoso, em quase todos.',
      'Necrose deve ser relatada: entra em modelos prognósticos.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100], note: 'o marcador de origem renal por excelência' },
      { marker: 'caix', pct: [90, 100], note: 'padrão em caixa difuso; nos outros RCC é só perinecrótico' },
      { marker: 'cd10', pct: [85, 95] },
      { marker: 'vimentina', pct: [85, 95] },
      { marker: 'ae1ae3', pct: [80, 95] },
      { marker: 'cam52', pct: [85, 95] },
      { marker: 'ck7', pct: [5, 20], note: 'o negativo que o separa do papilar e do cromófobo' },
      { marker: 'amacr', pct: [10, 30], note: 'fraca; difusa e forte favorece papilar' },
      { marker: 'cd117', pct: [0, 10], note: 'o negativo que separa de cromófobo e oncocitoma' },
      { marker: 'ema', pct: [70, 90] },
      { marker: 'pax2', pct: [70, 90] },
      { marker: 'bap1', pct: [10, 15], note: 'o positivo é a perda; associada a pior prognóstico' },
      { marker: 'tfe3', pct: [0, 5], note: 'forte nuclear indica RCC de translocação' },
      { marker: 'melana', pct: [0, 5], note: 'positivo levanta PEComa/angiomiolipoma epitelioide' },
      { marker: 'hmb45', pct: [0, 5] },
      { marker: 'ck20', pct: 0 },
      { marker: 'gata3', pct: [0, 5] },
      { marker: 'ki67', pct: [5, 30] },
    ],
    mimics: [
      'Angiomiolipoma epitelioide: HMB-45, Melan-A e catepsina K positivos, PAX8 negativo.',
      'Carcinoma adrenocortical: inibina, SF-1 e Melan-A positivos, PAX8 e CA-IX negativos.',
      'RCC de translocação TFE3: TFE3 nuclear forte, queratina fraca, em jovem.',
      'RCC papilar de células claras: CK7 difusa, CA-IX em taça invertida, CD10 negativo, indolente.',
      'Metástase de carcinoma de células claras ginecológico: ER, PR e HNF1β.',
    ],
    pitfalls: ['Numa metástase, PAX8 pode ser a única pista; lembre que ele também marca tireoide e mülleriano.'],
    molecular: 'Perda de 3p com VHL inativado; PBRM1, SETD2 e BAP1 na progressão.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-papilar',
    name: 'Carcinoma renal papilar',
    aka: ['RCC papilar', 'papillary renal cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'glandular', 'oncocitico', 'claras'],
    architecture: ['papilar', 'trabecular', 'cistico'],
    features: ['psamomas', 'hemorragia', 'necrose', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma renal com papilas de eixo fibrovascular repletas de macrófagos espumosos e hemossiderina, com ou sem corpos psamomatosos; CK7 e AMACR difusos com CA-IX ausente é o perfil, e o tipo 2 (nucléolo proeminente, citoplasma eosinofílico) é bem mais agressivo que o tipo 1.',
    criteria: [
      'Papilas verdadeiras ou túbulos papilíferos em mais de 75% do tumor.',
      'Macrófagos espumosos no eixo das papilas e depósito de hemossiderina são achados de apoio.',
      'CK7 e AMACR positivos, CA-IX negativo ou apenas perinecrótico.',
      'Graduação nucleolar da ISUP/WHO aplicada igualmente.',
      'FH e SDHB devem ser avaliados no papilar de tipo 2 de alto grau: a perda define entidades hereditárias distintas.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'amacr', pct: [85, 100], note: 'difusa e forte; é a marca do papilar' },
      { marker: 'ck7', pct: [70, 90], note: 'difusa no tipo 1, mais fraca e focal no tipo 2' },
      { marker: 'vimentina', pct: [70, 90] },
      { marker: 'cd10', pct: [60, 85] },
      { marker: 'caix', pct: [5, 20], note: 'só perinecrótico; difuso em caixa seria células claras' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ema', pct: [80, 95] },
      { marker: 'cd117', pct: [0, 10] },
      { marker: 'fh', pct: [0, 10], note: 'o positivo é a perda; define RCC FH-deficiente, não papilar' },
      { marker: 'sdhb', pct: [0, 5], note: 'retido' },
      { marker: 'tfe3', pct: [0, 10] },
      { marker: 'gata3', pct: [0, 10] },
      { marker: 'wt1', pct: [0, 10] },
      { marker: 'ki67', pct: [5, 30] },
    ],
    mimics: [
      'Adenoma papilar: até 15 mm, baixo grau, mesma imuno; só o tamanho separa.',
      'RCC FH-deficiente: nucléolo enorme com halo perinucleolar, FH perdido e 2SC positivo.',
      'Carcinoma de ductos coletores: infiltrativo, medular, desmoplasia, PAX8 positivo mas AMACR negativo.',
      'Carcinoma urotelial da pelve renal com padrão papilar: GATA3 e p63 positivos, PAX8 negativo.',
      'RCC de translocação: TFE3 nuclear.',
    ],
    molecular: 'Trissomias 7 e 17 com perda do Y no tipo 1; MET no hereditário; alterações heterogêneas no tipo 2.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-cromofobo',
    name: 'Carcinoma renal cromófobo',
    aka: ['RCC cromófobo', 'chromophobe renal cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'claras', 'oncocitico'],
    architecture: ['lencois', 'trabecular', 'ninhos'],
    features: ['mitoses-raras', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma de células grandes com membrana celular espessa em casca de planta, citoplasma pálido reticulado ou eosinofílico, núcleo enrugado em passa com halo perinuclear; CK7 difusa com CD117 positivo e vimentina negativa é o perfil, e o prognóstico é bem melhor que o das células claras.',
    criteria: [
      'Membranas celulares proeminentes e acentuadas, dando aspecto de mosaico vegetal.',
      'Núcleos irregulares e enrugados com halo perinuclear claro; binucleação frequente.',
      'CK7 difusa e CD117 positivo, com vimentina negativa e CA-IX negativo.',
      'Coloração de Hale (ferro coloidal) difusa citoplasmática, quando disponível.',
      'Graduação nucleolar da ISUP não se aplica: use o sistema específico de cromófobo ou apenas relate sarcomatoide e necrose.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100], note: 'difusa; no oncocitoma é apenas em células dispersas' },
      { marker: 'cd117', pct: [85, 100] },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ema', pct: [85, 100] },
      { marker: 'vimentina', pct: [0, 10], note: 'o negativo que o separa de células claras e papilar' },
      { marker: 'caix', pct: [0, 10] },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'amacr', pct: [10, 30] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'sdhb', pct: [0, 5], note: 'retido; a perda define RCC SDH-deficiente' },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'hmb45', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 10] },
    ],
    mimics: [
      'Oncocitoma renal: CK7 em células isoladas e esparsas, núcleo redondo e regular, cicatriz central.',
      'RCC de células claras variante eosinofílica: CA-IX em caixa, vimentina positiva.',
      'RCC SDH-deficiente: SDHB perdido, citoplasma com vacúolos eosinofílicos.',
      'Angiomiolipoma epitelioide: HMB-45 e catepsina K, PAX8 negativo.',
    ],
    pitfalls: ['A coexistência de oncocitoma e cromófobo (tumor híbrido) ocorre na síndrome de Birt-Hogg-Dubé.'],
    molecular: 'Perdas cromossômicas múltiplas (1, 2, 6, 10, 13, 17, 21); FLCN na síndrome de Birt-Hogg-Dubé.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'oncocitoma-renal',
    name: 'Oncocitoma renal',
    aka: ['renal oncocytoma'],
    behavior: 'benigno',
    sites: [{ site: 'rim', role: 'primario', freq: 2 }],
    cells: ['oncocitico', 'epitelioide'],
    architecture: ['ninhos', 'trabecular', 'lencois'],
    features: ['hialinizacao', 'estroma-mixoide', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor renal benigno castanho-mogno com cicatriz central estrelada, feito de ninhos de células oncocíticas redondas e uniformes, com núcleo central regular e nucléolo pequeno, num estroma hialinizado ou mixoide frouxo; a CK7 marca apenas células isoladas, o que é o melhor critério contra o cromófobo.',
    criteria: [
      'Células oncocíticas com núcleo redondo regular e nucléolo pequeno; sem membranas celulares proeminentes nem núcleos enrugados.',
      'Arquitetura em ninhos e ilhas dentro de estroma hialinizado ou mixoide.',
      'CK7 positiva apenas em células esparsas e isoladas (menos de 5%), nunca difusa.',
      'Ausência de necrose, de mitoses atípicas e de crescimento papilar.',
      'Extensão focal na gordura perirrenal e degeneração nuclear isolada são aceitas e não indicam malignidade.',
    ],
    markers: [
      { marker: 'ck7', pct: [5, 20], note: 'em células isoladas; o padrão difuso indicaria cromófobo' },
      { marker: 'cd117', pct: [85, 100] },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'vimentina', pct: [0, 10] },
      { marker: 'caix', pct: [0, 10] },
      { marker: 'cd10', pct: [20, 50] },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'sdhb', pct: [0, 5], note: 'retido' },
      { marker: 'sox9', pct: [0, 15] },
      { marker: 'ki67', pct: [1, 3] },
    ],
    mimics: [
      'RCC cromófobo eosinofílico: CK7 difusa, núcleo enrugado, halo perinuclear.',
      'RCC de células claras eosinofílico: CA-IX em caixa, vimentina positiva.',
      'RCC SDH-deficiente: SDHB perdido, em paciente jovem.',
      'Angiomiolipoma epitelioide oncocítico: HMB-45, catepsina K.',
      'Tumor oncocítico de baixo potencial (LOT): CK7 difusa com CD117 negativo.',
    ],
    molecular: 'Perda de 1 e do Y, ou rearranjo de CCND1; multifocalidade na oncocitose e em Birt-Hogg-Dubé.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-translocacao-tfe3',
    name: 'Carcinoma renal com rearranjo de TFE3',
    aka: ['RCC de translocação Xp11', 'TFE3-rearranged renal cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['claras', 'epitelioide', 'oncocitico'],
    architecture: ['papilar', 'alveolar', 'ninhos'],
    features: ['psamomas', 'hemorragia', 'necrose', 'nucleolo'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Carcinoma renal de criança e adulto jovem, com papilas revestidas por células volumosas de citoplasma claro ou eosinofílico e corpos psamomatosos frequentes; a queratina costuma ser fraca ou focal, o que confunde, e o TFE3 nuclear forte é o que resolve.',
    criteria: [
      'Marcação nuclear forte e difusa de TFE3 com controle interno negativo (o anticorpo é notoriamente sensível à fixação).',
      'Confirmação por FISH break-apart de TFE3 ou sequenciamento: recomendada porque a imuno dá falsos positivos e negativos.',
      'Morfologia papilar e alveolar com células volumosas claras e psamomas.',
      'Queratinas e EMA fracas ou focais, com PAX8 positivo.',
      'Positividade de Melan-A ou catepsina K sem HMB-45 forte é frequente e não indica PEComa.',
    ],
    markers: [
      { marker: 'tfe3', pct: [80, 95], note: 'nuclear forte; confirme por FISH quando a decisão depender disso' },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'catepsinak', pct: [50, 80], note: 'marca a via MiT; não significa PEComa' },
      { marker: 'melana', pct: [30, 60] },
      { marker: 'ae1ae3', pct: [30, 60], note: 'fraca ou focal, ao contrário dos outros RCC' },
      { marker: 'cam52', pct: [40, 70] },
      { marker: 'ema', pct: [30, 60] },
      { marker: 'cd10', pct: [70, 90] },
      { marker: 'amacr', pct: [50, 80] },
      { marker: 'ck7', pct: [5, 20] },
      { marker: 'caix', pct: [10, 30] },
      { marker: 'hmb45', pct: [10, 30] },
      { marker: 'tfeb', pct: [0, 5], note: 'positivo define o RCC t(6;11), entidade distinta' },
      { marker: 'ki67', pct: [10, 40] },
    ],
    mimics: [
      'RCC de células claras: CA-IX em caixa, queratina forte, TFE3 negativo.',
      'RCC papilar: CK7 e AMACR difusos, TFE3 negativo.',
      'Angiomiolipoma epitelioide: HMB-45 forte, PAX8 negativo.',
      'Sarcoma alveolar de partes moles: também TFE3 positivo, mas queratina e PAX8 negativos, fora do rim.',
    ],
    pitfalls: ['A imuno de TFE3 é temperamental: fraca difusa inespecífica é comum, e o falso negativo por fixação prolongada também.'],
    molecular: 'Fusões de TFE3 (Xp11.2) com ASPSCR1, PRCC, SFPQ, NONO e outros.',
    sources: [WHO, AMIN],
  },
  {
    id: 'rcc-fh-deficiente',
    name: 'Carcinoma renal FH-deficiente',
    aka: ['RCC associado a HLRCC', 'FH-deficient renal cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'oncocitico', 'claras'],
    architecture: ['papilar', 'cribriforme', 'cistico', 'trabecular'],
    features: ['nucleolo', 'necrose', 'mitoses-altas'],
    ages: ['jovem', 'adulto'],
    summary: 'Carcinoma renal agressivo de paciente jovem, com padrões misturados (papilar, cribriforme, cístico) e um detalhe que se reconhece de longe: nucléolo enorme eosinofílico rodeado por um halo claro, como em citomegalovírus; a perda de FH com 2SC positivo indica a síndrome de leiomiomatose hereditária.',
    criteria: [
      'Nucléolo muito proeminente com halo perinucleolar claro, em quase todas as células.',
      'Arquitetura mista, com componentes papilar, tubulocístico, cribriforme e sólido no mesmo tumor.',
      'Perda da expressão de FH nas células tumorais com controle interno retido.',
      '2SC (S-(2-succino)-cisteína) positiva, que é mais sensível que a perda de FH.',
      'Encaminhamento genético obrigatório: leiomiomatose cutânea e uterina hereditária com carcinoma renal.',
    ],
    markers: [
      { marker: 'fh', pct: [80, 95], note: 'o positivo é a perda; alguns casos mantêm FH com 2SC positivo' },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'amacr', pct: [40, 70] },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'cd10', pct: [40, 70] },
      { marker: 'caix', pct: [10, 30] },
      { marker: 'sdhb', pct: [0, 5], note: 'retido' },
      { marker: 'tfe3', pct: [0, 10] },
      { marker: 'ki67', pct: [20, 60] },
    ],
    mimics: [
      'RCC papilar de tipo 2: FH retido, sem halo perinucleolar.',
      'Carcinoma de ductos coletores: infiltrativo com desmoplasia, FH retido.',
      'RCC SDH-deficiente: SDHB perdido, vacúolos citoplasmáticos.',
      'RCC de translocação: TFE3 nuclear.',
    ],
    molecular: 'Mutação germinativa de FH (HLRCC) com perda somática do alelo restante.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-medular',
    name: 'Carcinoma medular renal',
    aka: ['carcinoma medular do rim', 'renal medullary carcinoma', 'RCC SMARCB1-deficiente'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'rabdoide', 'pleomorfico'],
    architecture: ['cribriforme', 'lencois', 'trabecular', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'desmoplasia', 'granulomas'],
    ages: ['jovem'],
    summary: 'Carcinoma da medular renal em jovem negro com traço falciforme, infiltrando de modo destrutivo em padrão cribriforme e reticular, com estroma desmoplásico e infiltrado neutrofílico; INI1 perdido, e a apresentação já é metastática na maioria.',
    criteria: [
      'Traço ou doença falciforme praticamente obrigatórios no contexto clínico.',
      'Origem centrada na medular renal, com crescimento infiltrativo destrutivo.',
      'Padrão reticular, cribriforme ou adenoide-cístico-símile com estroma desmoplásico e inflamação neutrofílica.',
      'Perda completa de INI1 (SMARCB1) nas células tumorais, com controle interno retido.',
      'Exclusão de carcinoma de ductos coletores, que mantém INI1.',
    ],
    markers: [
      { marker: 'ini1', pct: [90, 100], note: 'o positivo é a perda; critério definidor' },
      { marker: 'pax8', pct: [60, 85] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'oct4', pct: [30, 60], note: 'positividade descrita; não significa germinativo' },
      { marker: 'ck7', pct: [20, 50] },
      { marker: 'caix', pct: [10, 30] },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'p63', pct: [0, 15] },
      { marker: 'gata3', pct: [0, 15] },
      { marker: 'ki67', pct: [50, 90] },
    ],
    mimics: [
      'Carcinoma de ductos coletores: INI1 retido, paciente mais velho, sem falciforme.',
      'Carcinoma urotelial de alto grau da pelve: GATA3 e p63 positivos, INI1 retido.',
      'Tumor rabdoide do rim: em lactente, queratina fraca, também INI1 perdido.',
      'Carcinoma renal com padrão rabdoide: mantém INI1.',
    ],
    molecular: 'Inativação bialélica de SMARCB1, em geral por deleção.',
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-ductos-coletores',
    name: 'Carcinoma de ductos coletores',
    aka: ['carcinoma de Bellini', 'collecting duct carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide', 'anel-sinete'],
    architecture: ['glandulas', 'papilar', 'trabecular', 'infiltrativo'],
    features: ['desmoplasia', 'necrose', 'mitoses-altas', 'mucina'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma centrado na medular renal, com túbulos e papilas angulares infiltrando em meio a desmoplasia intensa e displasia dos ductos coletores adjacentes; é diagnóstico de exclusão, e o prognóstico é sombrio.',
    criteria: [
      'Centralização na medular renal com crescimento infiltrativo.',
      'Arquitetura tubular ou tubulopapilar com estroma desmoplásico proeminente.',
      'Atipia dos ductos coletores adjacentes ao tumor.',
      'Ausência de carcinoma urotelial concomitante e de outro subtipo de RCC.',
      'INI1 retido: a perda reclassifica como carcinoma medular.',
    ],
    markers: [
      { marker: 'pax8', pct: [70, 95] },
      { marker: 'ck7', pct: [70, 90] },
      { marker: 'ck19', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ema', pct: [85, 100] },
      { marker: 'd240', pct: [50, 80], note: 'positividade descrita; não é mesotelioma' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define carcinoma medular' },
      { marker: 'caix', pct: [10, 30] },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'amacr', pct: [10, 40] },
      { marker: 'gata3', pct: [0, 15], note: 'o negativo que ajuda contra urotelial' },
      { marker: 'p63', pct: [0, 10] },
      { marker: 'uroplaquina', pct: [0, 5] },
      { marker: 'ki67', pct: [30, 70] },
    ],
    mimics: [
      'Carcinoma urotelial da pelve renal invadindo o parênquima: GATA3, p63 e uroplaquina positivos.',
      'Carcinoma medular renal: INI1 perdido, jovem falciforme.',
      'RCC papilar de tipo 2: circunscrito, AMACR difuso, sem desmoplasia.',
      'Adenocarcinoma metastático: PAX8 negativo, perfil do sítio de origem.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'nefroblastoma',
    name: 'Nefroblastoma (tumor de Wilms)',
    aka: ['tumor de Wilms', 'Wilms tumour', 'nephroblastoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['blastematoso', 'pequenas-redondas', 'fusocelular', 'glandular'],
    architecture: ['nodular', 'glandulas', 'lencois', 'rosetas'],
    features: ['mitoses-altas', 'necrose', 'condroide', 'osteoide', 'estriacoes'],
    ages: ['crianca'],
    summary: 'Tumor renal da infância que recapitula o rim em desenvolvimento em três componentes — blastema azul denso, túbulos e glomeruloides epiteliais, e estroma —, e cujo prognóstico depende sobretudo de haver ou não anaplasia difusa, que é a definição de histologia desfavorável.',
    criteria: [
      'Padrão trifásico clássico: blastema, epitélio e estroma, em proporção variável (formas monofásicas existem).',
      'Anaplasia definida por núcleos três vezes maiores, hipercromasia e mitoses multipolares: focal ou difusa, e é o que define histologia desfavorável.',
      'WT1 nuclear no blastema e no epitélio precoce.',
      'Avaliação do leito e dos nódulos após quimioterapia pré-operatória segue o protocolo SIOP.',
      'Restos nefrogênicos no rim vizinho apoiam e indicam risco contralateral.',
    ],
    markers: [
      { marker: 'wt1', pct: [70, 95], note: 'nuclear; forte no blastema, fraco no estroma' },
      { marker: 'pax8', pct: [70, 90], note: 'componente epitelial' },
      { marker: 'pax2', pct: [70, 90] },
      { marker: 'ae1ae3', pct: [60, 85], note: 'só no componente epitelial' },
      { marker: 'cd56', pct: [70, 95] },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 'desmina', pct: [30, 60], note: 'componente estromal rabdomioblástico' },
      { marker: 'miogenina', pct: [20, 50] },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define tumor rabdoide do rim' },
      { marker: 'bcor', pct: [0, 10], note: 'positivo define sarcoma de células claras do rim' },
      { marker: 'cd99', pct: [10, 30], note: 'não confunda com Ewing' },
      { marker: 'sall4', pct: [10, 40] },
      { marker: 'p53', pct: [10, 30], note: 'aberrante acompanha anaplasia' },
      { marker: 'ki67', pct: [40, 90] },
    ],
    mimics: [
      'Sarcoma de células claras do rim: BCOR positivo, sem componente epitelial, metastatiza para osso.',
      'Tumor rabdoide do rim: INI1 perdido, em lactente.',
      'Neuroblastoma: PHOX2B e tirosina hidroxilase, WT1 negativo.',
      'Nefroma mesoblástico: em recém-nascido, fusocelular, ETV6::NTRK3 na variante celular.',
      'Sarcoma de Ewing renal: CD99 membranoso difuso, NKX2.2, fusão EWSR1.',
    ],
    molecular: 'WT1, CTNNB1, WTX; associação com WAGR, Denys-Drash e Beckwith-Wiedemann; TP53 na anaplasia.',
    sources: [WHO, AMIN],
  },
  {
    id: 'nefroma-mesoblastico',
    name: 'Nefroma mesoblástico congênito',
    aka: ['congenital mesoblastic nephroma', 'nefroma mesoblástico celular'],
    behavior: 'intermediario',
    sites: [{ site: 'rim', role: 'primario', freq: 2 }],
    cells: ['fusocelular', 'pequenas-redondas'],
    architecture: ['fasciculos', 'infiltrativo', 'lencois'],
    features: ['mitoses-moderadas', 'mitoses-altas', 'hemorragia', 'necrose'],
    ages: ['crianca'],
    summary: 'Tumor renal do recém-nascido e do lactente, fusocelular, que infiltra o parênquima em línguas e aprisiona glomérulos e túbulos; a variante clássica é fibromatose-símile e indolente, e a celular é densamente celular com fusão ETV6::NTRK3, idêntica à do fibrossarcoma infantil.',
    criteria: [
      'Idade abaixo de um ano, quase sempre nos primeiros três meses.',
      'Proliferação fusocelular infiltrativa com aprisionamento de estruturas renais nativas.',
      'Variante clássica: fascículos frouxos, baixa celularidade, mitoses escassas.',
      'Variante celular: densamente celular, mitoses numerosas, com ETV6::NTRK3.',
      'Ausência de blastema e de componente epitelial neoplásico, que definiriam nefroblastoma.',
    ],
    markers: [
      { marker: 'pan-trk', pct: [70, 95], note: 'na variante celular, reflete ETV6::NTRK3' },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'sma', pct: [40, 80], note: 'mais na variante clássica' },
      { marker: 'desmina', pct: [10, 40] },
      { marker: 'betacatenina', pct: [10, 30], pattern: 'N' },
      { marker: 'wt1', pct: [0, 15], note: 'o negativo que ajuda contra nefroblastoma estromal' },
      { marker: 'pax8', pct: [0, 10], note: 'só nos túbulos aprisionados' },
      { marker: 'ae1ae3', pct: [0, 10], note: 'idem' },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 's100', pct: [0, 15] },
      { marker: 'cd34', pct: [10, 30] },
      { marker: 'ki67', pct: [10, 50], note: 'alto na variante celular' },
    ],
    mimics: [
      'Nefroblastoma estromal predominante: tem blastema ou epitélio, WT1 positivo.',
      'Sarcoma de células claras do rim: BCOR positivo, células claras com rede vascular.',
      'Tumor rabdoide do rim: INI1 perdido.',
      'Fibrossarcoma infantil de partes moles: mesma fusão e mesma histologia, fora do rim.',
    ],
    molecular: 'ETV6::NTRK3 na variante celular; alterações de EGFR internal tandem duplication na clássica.',
    sources: [WHO, AMIN],
  },
  {
    id: 'sarcoma-celulas-claras-rim',
    name: 'Sarcoma de células claras do rim',
    aka: ['clear cell sarcoma of the kidney', 'CCSK'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
    ],
    cells: ['claras', 'epitelioide', 'fusocelular', 'estreladas'],
    architecture: ['ninhos', 'trabecular', 'lencois'],
    features: ['estroma-mixoide', 'mitoses-moderadas', 'hemorragia'],
    ages: ['crianca'],
    summary: 'Segundo tumor renal maligno mais comum da infância, feito de cordões de células pálidas de limites indistintos e cromatina fina, separados por uma rede regular de capilares arborizados; é chamado de tumor ósseo metastatizante da infância, e o BCOR nuclear é o marcador atual.',
    criteria: [
      'Cordões e ninhos de células com citoplasma pálido a claro e núcleos vesiculosos de cromatina fina, sem nucléolo.',
      'Rede vascular capilar arborizada e regular, característica, envolvendo os cordões.',
      'Ausência de blastema, de componente epitelial e de anaplasia clássica.',
      'BCOR nuclear difuso reflete a duplicação interna em tandem de BCOR.',
      'WT1 negativo e INI1 retido, o que o separa de nefroblastoma e de tumor rabdoide.',
    ],
    markers: [
      { marker: 'bcor', pct: [85, 100], note: 'nuclear difuso; substituto da BCOR-ITD' },
      { marker: 'ciclinad1', pct: [80, 95], note: 'muito útil e frequentemente esquecida' },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'wt1', pct: [0, 10], note: 'o negativo contra nefroblastoma' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define tumor rabdoide' },
      { marker: 'ae1ae3', pct: [0, 10], note: 'só nos túbulos aprisionados' },
      { marker: 'pax8', pct: [0, 10], note: 'idem' },
      { marker: 'desmina', pct: [0, 15] },
      { marker: 'cd34', pct: [0, 15] },
      { marker: 's100', pct: [0, 10] },
      { marker: 'sall4', pct: [0, 5] },
      { marker: 'ki67', pct: [10, 40] },
    ],
    mimics: [
      'Nefroblastoma blastematoso: WT1 positivo, blastema azul denso.',
      'Nefroma mesoblástico celular: pan-TRK, ETV6::NTRK3.',
      'Tumor rabdoide do rim: INI1 perdido.',
      'Sarcoma de Ewing renal: CD99 e NKX2.2.',
    ],
    molecular: 'Duplicação interna em tandem de BCOR na grande maioria; fusões YWHAE::NUTM2 numa minoria.',
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-urotelial-invasivo',
    name: 'Carcinoma urotelial invasivo',
    aka: ['carcinoma de células transicionais', 'urothelial carcinoma', 'CCT'],
    behavior: 'maligno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 3 },
      { site: 'rim', role: 'primario', freq: 2 },
      { site: 'penis', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'prostata', role: 'metastase', freq: 2 },
    ],
    cells: ['urotelial', 'epitelioide', 'pleomorfico', 'escamoso', 'anel-sinete', 'plasmocitoide', 'fusocelular'],
    architecture: ['ninhos', 'papilar', 'infiltrativo', 'micropapilar', 'lencois'],
    features: ['necrose', 'mitoses-altas', 'desmoplasia', 'precursor', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma com incrível capacidade de imitar outros tumores: além do padrão convencional em ninhos irregulares, tem variantes micropapilar, plasmocitoide, sarcomatoide, em ninhos e escamosa; GATA3 com p63, CK5/6, CK20 e uroplaquina formam o painel, e a resposta à imunoterapia depende do subtipo molecular.',
    criteria: [
      'Invasão além da membrana basal, com estadiamento pela profundidade: lâmina própria (T1) contra muscular própria (T2).',
      'A muscular própria deve ser identificada e mencionada; feixes de muscular da mucosa não valem.',
      'Graduação em baixo e alto grau pela desordem arquitetural e pela atipia nuclear.',
      'Variantes devem ser relatadas e quantificadas: micropapilar, plasmocitoide e sarcomatoide mudam a conduta.',
      'Carcinoma in situ adjacente apoia origem urotelial primária.',
    ],
    markers: [
      { marker: 'gata3', pct: [80, 95], note: 'cai bastante nos de alto grau e nas variantes' },
      { marker: 'p63', pct: [80, 95] },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'ck56', pct: [60, 85] },
      { marker: 'uroplaquina', pct: [50, 75], note: 'específica, pouco sensível; a positividade fecha o diagnóstico' },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck20', pct: [50, 70], note: 'com CK7 forma o perfil clássico CK7+/CK20+' },
      { marker: 's100p', pct: [70, 90] },
      { marker: 'p40', pct: [60, 85] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'her2', pct: [10, 20] },
      { marker: 'p53', pct: [50, 70] },
      { marker: 'ttf1', pct: [0, 5] },
      { marker: 'pax8', pct: [5, 20], note: 'pode ser fracamente positivo: não descarte urotelial por ele' },
      { marker: 'nkx31', pct: 0, note: 'o negativo que separa de prostático' },
      { marker: 'psa', pct: 0 },
      { marker: 'cdx2', pct: [5, 20] },
      { marker: 'ecaderina', pct: [70, 95], note: 'perdida na variante plasmocitoide' },
      { marker: 'ki67', pct: [30, 80] },
    ],
    mimics: [
      'Adenocarcinoma prostático pouco diferenciado: NKX3.1 e P501S positivos, GATA3 negativo.',
      'Carcinoma escamoso de bexiga: p40 difuso, GATA3 e CK7 muitas vezes negativos, sem CIS urotelial.',
      'Carcinoma renal invadindo a pelve: PAX8 forte, GATA3 negativo.',
      'Adenocarcinoma colorretal invadindo a bexiga: CDX2 e SATB2, CK7 negativo.',
      'Carcinoma mamário lobular metastático na variante plasmocitoide: GATA3 positivo nos dois; peça ER e mamoglobina.',
    ],
    pitfalls: [
      'GATA3 marca mama, paratireoide e paraganglioma: não é prova de urotélio sozinho.',
      'A variante plasmocitoide perde E-caderina e imita carcinoma lobular e linfoma.',
    ],
    molecular: 'FGFR3 nos de baixo grau papilares (alvo de erdafitinibe); TP53 e RB1 nos de alto grau.',
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-urotelial-papilar-nao-invasivo',
    name: 'Carcinoma urotelial papilar não invasivo e carcinoma in situ',
    aka: ['carcinoma papilar de baixo grau', 'CIS urotelial', 'non-invasive papillary urothelial carcinoma'],
    behavior: 'intermediario',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 3 },
      { site: 'rim', role: 'primario', freq: 1 },
    ],
    cells: ['urotelial', 'epitelioide'],
    architecture: ['papilar'],
    features: ['mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Lesão papilar revestida por urotélio espesso com perda de polaridade e atipia, sem invasão da lâmina própria; o carcinoma in situ é a contraparte plana, com células grandes desordenadas e hipercromáticas, e o trio CK20 de espessura total, p53 aberrante e CD44 basal ausente ajuda quando a atipia é reativa contra neoplásica.',
    criteria: [
      'Eixos fibrovasculares delicados revestidos por urotélio de espessura aumentada e desordenado.',
      'Graduação em baixo e alto grau; o papiloma e a neoplasia de baixo potencial ficam abaixo.',
      'Ausência de invasão da lâmina própria (o nível mais frequente de erro é o ninho tangencial).',
      'No CIS: atipia de células grandes em espessura total, com perda de coesão e mitoses altas na camada.',
      'Painel CK20 (espessura total), p53 (aberrante) e CD44 (perda da positividade basal) apoia CIS contra atipia reativa.',
    ],
    markers: [
      { marker: 'ck20', pct: [70, 90], note: 'em espessura total no CIS; no urotélio normal só nas células guarda-chuva' },
      { marker: 'p53', pct: [60, 85], note: 'aberrante no CIS e no alto grau; selvagem no reativo' },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'uroplaquina', pct: [40, 70] },
      { marker: 'ki67', pct: [20, 60], note: 'alto e em espessura total no CIS' },
      { marker: 'nkx31', pct: 0 },
      { marker: 'psa', pct: 0 },
      { marker: 'ttf1', pct: 0 },
    ],
    mimics: [
      'Atipia reativa e pós-quimioterapia intravesical: p53 selvagem, CK20 só nas guarda-chuva, inflamação.',
      'Papiloma urotelial: espessura normal, polaridade preservada, guarda-chuva mantidas.',
      'Displasia urotelial: atipia insuficiente para CIS.',
      'Metaplasia e adenoma nefrogênico: PAX8 positivo, GATA3 negativo.',
    ],
    molecular: 'FGFR3 e via RAS nos papilares de baixo grau; TP53 no CIS e nos de alto grau.',
    sources: [WHO, AMIN],
  },
  {
    id: 'cec-bexiga',
    name: 'Carcinoma de células escamosas da bexiga',
    aka: ['carcinoma escamoso vesical', 'squamous cell carcinoma of the bladder'],
    behavior: 'maligno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
    ],
    cells: ['escamoso', 'epitelioide'],
    architecture: ['ninhos', 'infiltrativo'],
    features: ['queratinizacao', 'necrose', 'desmoplasia', 'precursor', 'mitoses-altas'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma puro de diferenciação escamosa da bexiga, ligado a irritação crônica (cateter, litíase, esquistossomose), com queratinização e metaplasia escamosa com displasia na mucosa vizinha; o diagnóstico exige que não haja qualquer componente urotelial convencional ou in situ.',
    criteria: [
      'Diferenciação escamosa pura, com pontes intercelulares ou queratinização.',
      'Ausência absoluta de componente urotelial convencional e de carcinoma in situ urotelial.',
      'Metaplasia escamosa com displasia ou queratinizante adjacente apoia.',
      'Exclusão de extensão de carcinoma escamoso do colo uterino, da vagina ou do ânus.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ck903', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [30, 60], note: 'menos frequente que no urotelial' },
      { marker: 'ck20', pct: [0, 15], note: 'o negativo que ajuda contra urotelial com diferenciação escamosa' },
      { marker: 'gata3', pct: [20, 50], note: 'pode ser positivo; não resolve sozinho' },
      { marker: 'uroplaquina', pct: [0, 10] },
      { marker: 'p16', pct: [10, 30], note: 'em bloco levanta origem no colo uterino' },
      { marker: 'p53', pct: [50, 75] },
      { marker: 'ki67', pct: [50, 90] },
    ],
    mimics: [
      'Carcinoma urotelial com diferenciação escamosa: tem componente urotelial ou CIS, CK20 e uroplaquina podem ajudar.',
      'Carcinoma escamoso do colo uterino invadindo a bexiga: p16 em bloco, HPV.',
      'Metaplasia escamosa queratinizante extensa: sem invasão nem atipia franca.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'adenocarcinoma-bexiga',
    name: 'Adenocarcinoma de bexiga e do úraco',
    aka: ['adenocarcinoma vesical', 'adenocarcinoma uracal', 'bladder adenocarcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'anel-sinete', 'epitelioide'],
    architecture: ['glandulas', 'infiltrativo', 'cribriforme'],
    features: ['mucina', 'desmoplasia', 'necrose', 'mitoses-altas'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma primário da bexiga, entérico, mucinoso ou de células em anel de sinete, que pode nascer no domo a partir de remanescente uracal; imunologicamente é indistinguível do colorretal, e a separação depende da topografia, da ausência de tumor colônico e do achado de cistite glandular ou de úraco residual.',
    criteria: [
      'Adenocarcinoma puro, sem componente urotelial convencional nem CIS urotelial.',
      'Critérios de origem uracal: tumor centrado no domo ou na parede anterior, na muscular ou mais profundo, com epitélio uracal residual ou relação com a linha média.',
      'Exclusão clínica e endoscópica de adenocarcinoma colorretal ou de outro sítio.',
      'Cistite glandular ou metaplasia intestinal adjacente apoia primário vesical não uracal.',
    ],
    markers: [
      { marker: 'cdx2', pct: [80, 95], note: 'como no colorretal; não separa' },
      { marker: 'ck20', pct: [80, 95] },
      { marker: 'vilina', pct: [70, 90] },
      { marker: 'satb2', pct: [30, 60], note: 'positivo em parte; não exclui origem vesical' },
      { marker: 'ck7', pct: [40, 70], note: 'mais frequente que no colorretal, mas não decisivo' },
      { marker: 'muc2', pct: [60, 85] },
      { marker: 'betacatenina', pct: [10, 30], pattern: 'N', note: 'nuclear é mais do colorretal' },
      { marker: 'gata3', pct: [0, 15], note: 'o negativo esperado; não ajuda a provar origem vesical' },
      { marker: 'uroplaquina', pct: [0, 10] },
      { marker: 'p63', pct: [0, 10] },
      { marker: 'pax8', pct: [0, 10] },
      { marker: 'ki67', pct: [40, 80] },
    ],
    mimics: [
      'Adenocarcinoma colorretal invadindo a bexiga: imuno idêntica; a clínica decide.',
      'Adenocarcinoma prostático com padrão ductal: NKX3.1 e P501S positivos.',
      'Carcinoma urotelial com diferenciação glandular: componente urotelial presente.',
      'Cistite glandular com metaplasia intestinal: sem invasão nem atipia.',
      'Endometriose vesical: ER, PR e PAX8 positivos, estroma endometrial CD10 positivo.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-pequenas-celulas-bexiga',
    name: 'Carcinoma neuroendócrino de pequenas células da bexiga',
    aka: ['small cell carcinoma vesical', 'carcinoma neuroendócrino de bexiga'],
    behavior: 'maligno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino'],
    architecture: ['lencois', 'ninhos'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma de pequenas células idêntico ao pulmonar, com núcleo hipercromático sem nucléolo, moldagem, esmagamento e necrose maciça, que na bexiga vem acompanhado de carcinoma urotelial convencional ou in situ em cerca de metade dos casos; a quimioterapia é a do pulmão e não a do urotelial.',
    criteria: [
      'Citologia de pequenas células: núcleo hipercromático, nucléolo ausente, moldagem nuclear, citoplasma escasso, artefato de esmagamento.',
      'Índice mitótico muito alto e necrose geográfica.',
      'Marcador neuroendócrino positivo (sinaptofisina, INSM1) ou morfologia inequívoca com queratina em dot.',
      'Qualquer proporção do componente de pequenas células basta para classificar o tumor como tal.',
      'Componente urotelial associado deve ser relatado.',
    ],
    markers: [
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [80, 95] },
      { marker: 'cromogranina', pct: [40, 70], note: 'mais fraca e focal que a sinaptofisina' },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [80, 95], pattern: 'dot', note: 'padrão perinuclear em dot frequente' },
      { marker: 'ttf1', pct: [30, 60], note: 'positivo sem significar pulmão: erro clássico' },
      { marker: 'gata3', pct: [10, 40], note: 'costuma perder-se' },
      { marker: 'p63', pct: [10, 30] },
      { marker: 'uroplaquina', pct: [0, 10] },
      { marker: 'rb1', pct: [70, 90], note: 'o positivo é a perda; quase constante' },
      { marker: 'p53', pct: [60, 90] },
      { marker: 'ck20', pct: [5, 20] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Carcinoma urotelial de alto grau pouco diferenciado: nucléolo presente, GATA3 e p63 fortes, sem marcador neuroendócrino.',
      'Linfoma: CD45 positivo, queratina negativa.',
      'Carcinoma de pequenas células pulmonar metastático: TTF-1 positivo nos dois; a clínica decide.',
      'Carcinoma prostático neuroendócrino: NKX3.1 pode persistir, história de bloqueio androgênico.',
    ],
    pitfalls: ['TTF-1 positivo num tumor de bexiga não indica primário pulmonar: até 60% dos vesicais o expressam.'],
    sources: [WHO, AMIN],
  },
  {
    id: 'adenoma-nefrogenico',
    name: 'Adenoma nefrogênico',
    aka: ['metaplasia nefrogênica', 'nephrogenic adenoma'],
    behavior: 'benigno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 2 },
      { site: 'penis', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular', 'claras'],
    architecture: ['glandulas', 'papilar', 'cistico', 'infiltrativo'],
    features: ['tachinha', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Lesão reativa em urotélio lesado por cirurgia, cateter ou cálculo, formada por túbulos pequenos, papilas e microcistos revestidos por uma camada única de células cuboides em tachinha; o perigo é ser lida como adenocarcinoma ou como carcinoma prostático, e o PAX8 com NKX3.1 negativo resolve.',
    criteria: [
      'História de instrumentação, litíase, cateter ou transplante renal.',
      'Túbulos e microcistos revestidos por camada única de células cuboides, muitas em tachinha, com bainha de membrana basal espessa.',
      'Ausência de atipia significativa, de necrose e de mitoses atípicas.',
      'PAX8 e PAX2 positivos com NKX3.1, P501S e PSA negativos.',
      'Extensão para a muscular própria pode ocorrer e não indica malignidade.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100], note: 'origem em células tubulares renais descamadas' },
      { marker: 'pax2', pct: [85, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'amacr', pct: [50, 85], note: 'positivo, e é justamente o que leva ao erro com prostático' },
      { marker: 'nkx31', pct: 0, note: 'o negativo que afasta próstata' },
      { marker: 'psa', pct: 0 },
      { marker: 'p501s', pct: 0 },
      { marker: 'gata3', pct: [0, 15] },
      { marker: 'p63', pct: [0, 10], note: 'sem camada basal, ao contrário das glândulas prostáticas benignas' },
      { marker: 'ck903', pct: [0, 10] },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 5] },
    ],
    mimics: [
      'Adenocarcinoma prostático: NKX3.1, P501S e PSA positivos, PAX8 negativo.',
      'Adenocarcinoma vesical: atipia, desmoplasia, CDX2.',
      'Carcinoma renal de células claras invadindo: PAX8 positivo nos dois; a massa renal decide.',
      'Cistite cística e glandular: sem padrão tubular difuso nem células em tachinha.',
    ],
    pitfalls: ['AMACR positivo com aspecto infiltrativo em biópsia de bexiga leva a diagnóstico errado de adenocarcinoma prostático; peça NKX3.1 e PAX8.'],
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-adrenocortical',
    name: 'Carcinoma e adenoma adrenocortical',
    aka: ['carcinoma do córtex adrenal', 'adrenocortical carcinoma', 'adenoma adrenocortical'],
    behavior: 'maligno',
    sites: [
      { site: 'adrenal', role: 'primario', freq: 3 },
      { site: 'retroperitoneo', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['claras', 'oncocitico', 'epitelioide', 'pleomorfico'],
    architecture: ['ninhos', 'trabecular', 'lencois', 'alveolar'],
    features: ['necrose', 'mitoses-altas', 'hemorragia', 'vacuolos-lipidicos'],
    ages: ['crianca', 'adulto', 'idoso'],
    summary: 'Tumor do córtex adrenal, de células claras lipídicas a compactas eosinofílicas, cuja malignidade não se decide por uma característica isolada mas pelo escore de Weiss; queratina fraca ou negativa com SF-1, inibina e Melan-A positivos é o perfil que o separa de carcinoma renal e de feocromocitoma.',
    criteria: [
      'Escore de Weiss (3 ou mais dos nove critérios) define carcinoma: alto grau nuclear, mitoses acima de 5 por 50 campos, mitoses atípicas, células claras em menos de 25%, arquitetura difusa, necrose, invasão venosa, sinusoidal e capsular.',
      'SF-1 nuclear é o marcador mais específico de linhagem adrenocortical.',
      'Queratina fraca ou negativa com vimentina forte é o padrão, e não deve levar a diagnóstico de sarcoma.',
      'Escore de Weiss não se aplica a variantes oncocítica (critérios de Lin-Weiss-Bisceglia), mixoide e pediátrica.',
      'Ki-67 acima de 5% apoia malignidade e orienta prognóstico.',
    ],
    markers: [
      { marker: 'sf1', pct: [90, 100], note: 'o marcador de linhagem mais específico' },
      { marker: 'inibina', pct: [80, 95] },
      { marker: 'melana', pct: [70, 95], note: 'clone A103; não indica melanoma' },
      { marker: 'calretinina', pct: [70, 90] },
      { marker: 'sinaptofisina', pct: [60, 85], note: 'positiva: não conclua neuroendócrino' },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [20, 50], note: 'fraca ou focal; a negatividade é esperada' },
      { marker: 'ema', pct: [0, 15] },
      { marker: 'pax8', pct: [0, 10], note: 'o negativo que separa de carcinoma renal' },
      { marker: 'caix', pct: [0, 10] },
      { marker: 'cromogranina', pct: [0, 10], note: 'o negativo que separa de feocromocitoma' },
      { marker: 'gata3', pct: [0, 10] },
      { marker: 'heppar1', pct: [0, 15] },
      { marker: 'p53', pct: [20, 50], note: 'mais frequente no carcinoma; germinativa em Li-Fraumeni' },
      { marker: 'betacatenina', pct: [20, 50], pattern: 'N' },
      { marker: 'ki67', pct: [1, 40], note: 'abaixo de 5% favorece adenoma; acima de 20% indica alto risco' },
    ],
    mimics: [
      'Carcinoma renal de células claras invadindo a adrenal: PAX8 e CA-IX positivos, queratina forte.',
      'Feocromocitoma: cromogranina e GATA3 positivos, SF-1 negativo, sustentaculares S100.',
      'Carcinoma hepatocelular: arginase e HepPar-1.',
      'Melanoma metastático: SOX10 e HMB-45 positivos, SF-1 negativo.',
      'Adenoma adrenocortical: Weiss abaixo de 3, Ki-67 baixo, sem necrose nem invasão.',
    ],
    pitfalls: ['Melan-A e sinaptofisina positivos com queratina negativa podem sugerir melanoma ou paraganglioma; SF-1 resolve.'],
    molecular: 'TP53 (Li-Fraumeni), CTNNB1, ZNRF3; perda de heterozigose em 11p15 (Beckwith-Wiedemann).',
    sources: [WHO, 'WHO Classification of Tumours, 5ª ed.: Endocrine and Neuroendocrine Tumours (2022)', AMIN],
  },
]
