/* ==========================================================================
   kidneyurothelial.ts — rim, via urinária e adrenal.

   No rim quase tudo é PAX8 positivo, e o trabalho é separar os subtipos:
   CA-IX em caixa e CD10 nas células claras, AMACR e vimentina no papilar,
   CK7 difusa com CD117 no cromófobo, e as perdas (FH, SDHB, INI1) e ganhos
   (TFE3, TFEB) nos moleculares. Na via urinária, GATA3 com p63 e uroplaquina
   respondem "é urotelial?", e o resto do painel responde "de onde veio?".

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Urinary and Male Genital Tumours, 2022; Amin, Epstein &
   Reuter nos capítulos de rim e bexiga; recomendações ISUP; séries de Am J
   Surg Pathol e Mod Pathol). As fontes estão como referência de texto: as
   séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Urinary and Male Genital Tumours (2022)'
const AMIN = 'Amin, Epstein & Reuter, capítulos de patologia renal e vesical; Urologic Surgical Pathology, 4ª ed.'
const ISUP = 'Recomendações da International Society of Urological Pathology (ISUP) para imuno-histoquímica em tumores renais'

export const kidneyurothelial: Tumor[] = [
  {
    id: 'rcc-celulas-claras',
    name: 'Carcinoma renal de células claras',
    aka: ['RCC de células claras', 'clear cell renal cell carcinoma', 'ccRCC'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 2 },
      { site: 'adrenal', role: 'metastase', freq: 2 },
      { site: 'tireoide', role: 'metastase', freq: 1 },
      { site: 'pancreas', role: 'metastase', freq: 1 },
    ],
    cells: ['claras', 'epitelioide', 'oncocitico', 'rabdoide', 'fusocelular'],
    architecture: ['ninhos', 'alveolar', 'cistico', 'lencois'],
    features: ['hemorragia', 'necrose', 'glicogenio', 'nucleolo', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'O carcinoma renal mais comum: ninhos de células de citoplasma claro pelo glicogênio e lipídio, separados por uma rede capilar delicada em arcadas; CA-IX em padrão de caixa e CD10 com PAX8 fecham a origem, e a graduação é pelo nucléolo (ISUP/WHO).',
    criteria: [
      'Ninhos e alvéolos de células claras delimitados por rede capilar fina e regular.',
      'Graduação nucleolar da ISUP/WHO: grau 1 a 3 pelo nucléolo, grau 4 por sarcomatoide, rabdoide ou pleomorfismo extremo.',
      'Componente sarcomatoide ou rabdoide deve ser quantificado: muda o prognóstico e a terapia.',
      'CA-IX em padrão de caixa, difuso e membranoso, em quase todos.',
      'Necrose deve ser relatada: entra em modelos prognósticos.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100], note: 'o marcador de origem renal por excelência' },
      { marker: 'caix', pct: [85, 95], note: 'padrão em caixa difuso; nos outros RCC é só perinecrótico', source: 'Séries de imuno-histoquímica em RCC: positividade de 88% (68/77) no de células claras' },
      { marker: 'cd10', pct: [85, 95] },
      { marker: 'vimentina', pct: [85, 95] },
      { marker: 'ae1ae3', pct: [80, 95] },
      { marker: 'cam52', pct: [85, 95] },
      { marker: 'ck7', pct: [5, 20], note: 'o negativo que o separa do papilar e do cromófobo' },
      { marker: 'amacr', pct: [10, 30], note: 'fraca; difusa e forte favorece papilar' },
      { marker: 'cd117', pct: [0, 10], note: 'o negativo que separa de cromófobo e oncocitoma' },
      { marker: 'ema', pct: [70, 90] },
      { marker: 'pax2', pct: [70, 90] },
      { marker: 'bap1', pct: [10, 15], note: 'o positivo é a perda; associada a pior prognóstico' },
      { marker: 'tfe3', pct: [0, 5], note: 'forte nuclear indica RCC de translocação' },
      { marker: 'melana', pct: [0, 5], note: 'positivo levanta PEComa/angiomiolipoma epitelioide' },
      { marker: 'hmb45', pct: [0, 5] },
      { marker: 'ck20', pct: 0 },
      { marker: 'gata3', pct: [0, 5] },
      { marker: 'ki67', pct: [5, 30] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Angiomiolipoma epitelioide: HMB-45, Melan-A e catepsina K positivos, PAX8 negativo.',
      'Carcinoma adrenocortical: inibina, SF-1 e Melan-A positivos, PAX8 e CA-IX negativos.',
      'RCC de translocação TFE3: TFE3 nuclear forte, queratina fraca, em jovem.',
      'RCC papilar de células claras: CK7 difusa, CA-IX em taça invertida, CD10 negativo, indolente.',
      'Metástase de carcinoma de células claras ginecológico: ER, PR e HNF1β.',
    ],
    pitfalls: ['Numa metástase, PAX8 pode ser a única pista; lembre que ele também marca tireoide e mülleriano.'],
    molecular: 'Perda de 3p com VHL inativado; PBRM1, SETD2 e BAP1 na progressão.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-papilar',
    name: 'Carcinoma renal papilar',
    aka: ['RCC papilar', 'papillary renal cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'glandular', 'oncocitico', 'claras'],
    architecture: ['papilar', 'trabecular', 'cistico'],
    features: ['psamomas', 'hemorragia', 'necrose', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma renal com papilas de eixo fibrovascular repletas de macrófagos espumosos e hemossiderina, com ou sem corpos psamomatosos; CK7 e AMACR difusos com CA-IX ausente é o perfil, e o tipo 2 (nucléolo proeminente, citoplasma eosinofílico) é bem mais agressivo que o tipo 1.',
    criteria: [
      'Papilas verdadeiras ou túbulos papilíferos em mais de 75% do tumor.',
      'Macrófagos espumosos no eixo das papilas e depósito de hemossiderina são achados de apoio.',
      'CK7 e AMACR positivos, CA-IX negativo ou apenas perinecrótico.',
      'Graduação nucleolar da ISUP/WHO aplicada igualmente.',
      'FH e SDHB devem ser avaliados no papilar de tipo 2 de alto grau: a perda define entidades hereditárias distintas.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'amacr', pct: [85, 100], note: 'difusa e forte; é a marca do papilar' },
      { marker: 'ck7', pct: [70, 90], note: 'difusa no tipo 1, mais fraca e focal no tipo 2' },
      { marker: 'vimentina', pct: [70, 90] },
      { marker: 'cd10', pct: [60, 85] },
      { marker: 'caix', pct: [5, 20], note: 'só perinecrótico; difuso em caixa seria células claras' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ema', pct: [80, 95] },
      { marker: 'cd117', pct: [0, 10] },
      { marker: 'fh', pct: [0, 10], note: 'o positivo é a perda; define RCC FH-deficiente, não papilar' },
      { marker: 'sdhb', pct: [0, 5], note: 'retido' },
      { marker: 'tfe3', pct: [0, 10] },
      { marker: 'gata3', pct: [0, 10] },
      { marker: 'wt1', pct: [0, 10] },
      { marker: 'ki67', pct: [5, 30] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma papilar: até 15 mm, baixo grau, mesma imuno; só o tamanho separa.',
      'RCC FH-deficiente: nucléolo enorme com halo perinucleolar, FH perdido e 2SC positivo.',
      'Carcinoma de ductos coletores: infiltrativo, medular, desmoplasia, PAX8 positivo mas AMACR negativo.',
      'Carcinoma urotelial da pelve renal com padrão papilar: GATA3 e p63 positivos, PAX8 negativo.',
      'RCC de translocação: TFE3 nuclear.',
    ],
    molecular: 'Trissomias 7 e 17 com perda do Y no tipo 1; MET no hereditário; alterações heterogêneas no tipo 2.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-cromofobo',
    name: 'Carcinoma renal cromófobo',
    aka: ['RCC cromófobo', 'chromophobe renal cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'claras', 'oncocitico'],
    architecture: ['lencois', 'trabecular', 'ninhos'],
    features: ['mitoses-raras', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma de células grandes com membrana celular espessa em casca de planta, citoplasma pálido reticulado ou eosinofílico, núcleo enrugado em passa com halo perinuclear; CK7 difusa com CD117 positivo e vimentina negativa é o perfil, e o prognóstico é bem melhor que o das células claras.',
    criteria: [
      'Membranas celulares proeminentes e acentuadas, dando aspecto de mosaico vegetal.',
      'Núcleos irregulares e enrugados com halo perinuclear claro; binucleação frequente.',
      'CK7 difusa e CD117 positivo, com vimentina negativa e CA-IX negativo.',
      'Coloração de Hale (ferro coloidal) difusa citoplasmática, quando disponível.',
      'Graduação nucleolar da ISUP não se aplica: use o sistema específico de cromófobo ou apenas relate sarcomatoide e necrose.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100], note: 'difusa; no oncocitoma é apenas em células dispersas' },
      { marker: 'cd117', pct: [85, 100] },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ema', pct: [85, 100] },
      { marker: 'vimentina', pct: [0, 10], note: 'o negativo que o separa de células claras e papilar' },
      { marker: 'caix', pct: [0, 10] },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'amacr', pct: [10, 30] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'sdhb', pct: [0, 5], note: 'retido; a perda define RCC SDH-deficiente' },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'hmb45', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Oncocitoma renal: CK7 em células isoladas e esparsas, núcleo redondo e regular, cicatriz central.',
      'RCC de células claras variante eosinofílica: CA-IX em caixa, vimentina positiva.',
      'RCC SDH-deficiente: SDHB perdido, citoplasma com vacúolos eosinofílicos.',
      'Angiomiolipoma epitelioide: HMB-45 e catepsina K, PAX8 negativo.',
    ],
    pitfalls: ['A coexistência de oncocitoma e cromófobo (tumor híbrido) ocorre na síndrome de Birt-Hogg-Dubé.'],
    molecular: 'Perdas cromossômicas múltiplas (1, 2, 6, 10, 13, 17, 21); FLCN na síndrome de Birt-Hogg-Dubé.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'oncocitoma-renal',
    name: 'Oncocitoma renal',
    aka: ['renal oncocytoma'],
    behavior: 'benigno',
    sites: [{ site: 'rim', role: 'primario', freq: 2 }],
    cells: ['oncocitico', 'epitelioide'],
    architecture: ['ninhos', 'trabecular', 'lencois'],
    features: ['hialinizacao', 'estroma-mixoide', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor renal benigno castanho-mogno com cicatriz central estrelada, feito de ninhos de células oncocíticas redondas e uniformes, com núcleo central regular e nucléolo pequeno, num estroma hialinizado ou mixoide frouxo; a CK7 marca apenas células isoladas, o que é o melhor critério contra o cromófobo.',
    criteria: [
      'Células oncocíticas com núcleo redondo regular e nucléolo pequeno; sem membranas celulares proeminentes nem núcleos enrugados.',
      'Arquitetura em ninhos e ilhas dentro de estroma hialinizado ou mixoide.',
      'CK7 positiva apenas em células esparsas e isoladas (menos de 5%), nunca difusa.',
      'Ausência de necrose, de mitoses atípicas e de crescimento papilar.',
      'Extensão focal na gordura perirrenal e degeneração nuclear isolada são aceitas e não indicam malignidade.',
    ],
    markers: [
      { marker: 'ck7', pct: [5, 20], note: 'em células isoladas; o padrão difuso indicaria cromófobo' },
      { marker: 'cd117', pct: [85, 100] },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'vimentina', pct: [0, 10] },
      { marker: 'caix', pct: [0, 10] },
      { marker: 'cd10', pct: [20, 50] },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'sdhb', pct: [0, 5], note: 'retido' },
      { marker: 'sox9', pct: [0, 15] },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'RCC cromófobo eosinofílico: CK7 difusa, núcleo enrugado, halo perinuclear.',
      'RCC de células claras eosinofílico: CA-IX em caixa, vimentina positiva.',
      'RCC SDH-deficiente: SDHB perdido, em paciente jovem.',
      'Angiomiolipoma epitelioide oncocítico: HMB-45, catepsina K.',
      'Tumor oncocítico de baixo potencial (LOT): CK7 difusa com CD117 negativo.',
    ],
    molecular: 'Perda de 1 e do Y, ou rearranjo de CCND1; multifocalidade na oncocitose e em Birt-Hogg-Dubé.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-translocacao-tfe3',
    name: 'Carcinoma renal com rearranjo de TFE3',
    aka: ['RCC de translocação Xp11', 'TFE3-rearranged renal cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['claras', 'epitelioide', 'oncocitico'],
    architecture: ['papilar', 'alveolar', 'ninhos'],
    features: ['psamomas', 'hemorragia', 'necrose', 'nucleolo'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Carcinoma renal de criança e adulto jovem, com papilas revestidas por células volumosas de citoplasma claro ou eosinofílico e corpos psamomatosos frequentes; a queratina costuma ser fraca ou focal, o que confunde, e o TFE3 nuclear forte é o que resolve.',
    criteria: [
      'Marcação nuclear forte e difusa de TFE3 com controle interno negativo (o anticorpo é notoriamente sensível à fixação).',
      'Confirmação por FISH break-apart de TFE3 ou sequenciamento: recomendada porque a imuno dá falsos positivos e negativos.',
      'Morfologia papilar e alveolar com células volumosas claras e psamomas.',
      'Queratinas e EMA fracas ou focais, com PAX8 positivo.',
      'Positividade de Melan-A ou catepsina K sem HMB-45 forte é frequente e não indica PEComa.',
    ],
    markers: [
      { marker: 'tfe3', pct: [80, 95], note: 'nuclear forte; confirme por FISH quando a decisão depender disso' },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'catepsinak', pct: [50, 80], note: 'marca a via MiT; não significa PEComa' },
      { marker: 'melana', pct: [30, 60] },
      { marker: 'ae1ae3', pct: [30, 60], note: 'fraca ou focal, ao contrário dos outros RCC' },
      { marker: 'cam52', pct: [40, 70] },
      { marker: 'ema', pct: [30, 60] },
      { marker: 'cd10', pct: [70, 90] },
      { marker: 'amacr', pct: [50, 80] },
      { marker: 'ck7', pct: [5, 20] },
      { marker: 'caix', pct: [10, 30] },
      { marker: 'hmb45', pct: [10, 30] },
      { marker: 'tfeb', pct: [0, 5], note: 'positivo define o RCC t(6;11), entidade distinta' },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'RCC de células claras: CA-IX em caixa, queratina forte, TFE3 negativo.',
      'RCC papilar: CK7 e AMACR difusos, TFE3 negativo.',
      'Angiomiolipoma epitelioide: HMB-45 forte, PAX8 negativo.',
      'Sarcoma alveolar de partes moles: também TFE3 positivo, mas queratina e PAX8 negativos, fora do rim.',
    ],
    pitfalls: ['A imuno de TFE3 é temperamental: fraca difusa inespecífica é comum, e o falso negativo por fixação prolongada também.'],
    molecular: 'Fusões de TFE3 (Xp11.2) com ASPSCR1, PRCC, SFPQ, NONO e outros.',
    sources: [WHO, AMIN],
  },
  {
    id: 'rcc-fh-deficiente',
    name: 'Carcinoma renal FH-deficiente',
    aka: ['RCC associado a HLRCC', 'FH-deficient renal cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'oncocitico', 'claras'],
    architecture: ['papilar', 'cribriforme', 'cistico', 'trabecular'],
    features: ['nucleolo', 'necrose', 'mitoses-altas'],
    ages: ['jovem', 'adulto'],
    summary: 'Carcinoma renal agressivo de paciente jovem, com padrões misturados (papilar, cribriforme, cístico) e um detalhe que se reconhece de longe: nucléolo enorme eosinofílico rodeado por um halo claro, como em citomegalovírus; a perda de FH com 2SC positivo indica a síndrome de leiomiomatose hereditária.',
    criteria: [
      'Nucléolo muito proeminente com halo perinucleolar claro, em quase todas as células.',
      'Arquitetura mista, com componentes papilar, tubulocístico, cribriforme e sólido no mesmo tumor.',
      'Perda da expressão de FH nas células tumorais com controle interno retido.',
      '2SC (S-(2-succino)-cisteína) positiva, que é mais sensível que a perda de FH.',
      'Encaminhamento genético obrigatório: leiomiomatose cutânea e uterina hereditária com carcinoma renal.',
    ],
    markers: [
      { marker: 'fh', pct: [80, 95], note: 'o positivo é a perda; alguns casos mantêm FH com 2SC positivo' },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'amacr', pct: [40, 70] },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'cd10', pct: [40, 70] },
      { marker: 'caix', pct: [10, 30] },
      { marker: 'sdhb', pct: [0, 5], note: 'retido' },
      { marker: 'tfe3', pct: [0, 10] },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'RCC papilar de tipo 2: FH retido, sem halo perinucleolar.',
      'Carcinoma de ductos coletores: infiltrativo com desmoplasia, FH retido.',
      'RCC SDH-deficiente: SDHB perdido, vacúolos citoplasmáticos.',
      'RCC de translocação: TFE3 nuclear.',
    ],
    molecular: 'Mutação germinativa de FH (HLRCC) com perda somática do alelo restante.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-medular',
    name: 'Carcinoma medular renal',
    aka: ['carcinoma medular do rim', 'renal medullary carcinoma', 'RCC SMARCB1-deficiente'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'rabdoide', 'pleomorfico'],
    architecture: ['cribriforme', 'lencois', 'trabecular', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'desmoplasia', 'granulomas'],
    ages: ['jovem'],
    summary: 'Carcinoma da medular renal em jovem negro com traço falciforme, infiltrando de modo destrutivo em padrão cribriforme e reticular, com estroma desmoplásico e infiltrado neutrofílico; INI1 perdido, e a apresentação já é metastática na maioria.',
    criteria: [
      'Traço ou doença falciforme praticamente obrigatórios no contexto clínico.',
      'Origem centrada na medular renal, com crescimento infiltrativo destrutivo.',
      'Padrão reticular, cribriforme ou adenoide-cístico-símile com estroma desmoplásico e inflamação neutrofílica.',
      'Perda completa de INI1 (SMARCB1) nas células tumorais, com controle interno retido.',
      'Exclusão de carcinoma de ductos coletores, que mantém INI1.',
    ],
    markers: [
      { marker: 'ini1', pct: [90, 100], note: 'o positivo é a perda; critério definidor' },
      { marker: 'pax8', pct: [60, 85] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'oct4', pct: [30, 60], note: 'positividade descrita; não significa germinativo' },
      { marker: 'ck7', pct: [20, 50] },
      { marker: 'caix', pct: [10, 30] },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'p63', pct: [0, 15] },
      { marker: 'gata3', pct: [0, 15] },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma de ductos coletores: INI1 retido, paciente mais velho, sem falciforme.',
      'Carcinoma urotelial de alto grau da pelve: GATA3 e p63 positivos, INI1 retido.',
      'Tumor rabdoide do rim: em lactente, queratina fraca, também INI1 perdido.',
      'Carcinoma renal com padrão rabdoide: mantém INI1.',
    ],
    molecular: 'Inativação bialélica de SMARCB1, em geral por deleção.',
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-ductos-coletores',
    name: 'Carcinoma de ductos coletores',
    aka: ['carcinoma de Bellini', 'collecting duct carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide', 'anel-sinete'],
    architecture: ['glandulas', 'papilar', 'trabecular', 'infiltrativo'],
    features: ['desmoplasia', 'necrose', 'mitoses-altas', 'mucina'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma centrado na medular renal, com túbulos e papilas angulares infiltrando em meio a desmoplasia intensa e displasia dos ductos coletores adjacentes; é diagnóstico de exclusão, e o prognóstico é sombrio.',
    criteria: [
      'Centralização na medular renal com crescimento infiltrativo.',
      'Arquitetura tubular ou tubulopapilar com estroma desmoplásico proeminente.',
      'Atipia dos ductos coletores adjacentes ao tumor.',
      'Ausência de carcinoma urotelial concomitante e de outro subtipo de RCC.',
      'INI1 retido: a perda reclassifica como carcinoma medular.',
    ],
    markers: [
      { marker: 'pax8', pct: [70, 95] },
      { marker: 'ck7', pct: [70, 90] },
      { marker: 'ck19', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ema', pct: [85, 100] },
      { marker: 'd240', pct: [50, 80], note: 'positividade descrita; não é mesotelioma' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define carcinoma medular' },
      { marker: 'caix', pct: [10, 30] },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'amacr', pct: [10, 40] },
      { marker: 'gata3', pct: [0, 15], note: 'o negativo que ajuda contra urotelial' },
      { marker: 'p63', pct: [0, 10] },
      { marker: 'uroplaquina', pct: [0, 5] },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma urotelial da pelve renal invadindo o parênquima: GATA3, p63 e uroplaquina positivos.',
      'Carcinoma medular renal: INI1 perdido, jovem falciforme.',
      'RCC papilar de tipo 2: circunscrito, AMACR difuso, sem desmoplasia.',
      'Adenocarcinoma metastático: PAX8 negativo, perfil do sítio de origem.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'nefroblastoma',
    name: 'Nefroblastoma (tumor de Wilms)',
    aka: ['tumor de Wilms', 'Wilms tumour', 'nephroblastoma'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['blastematoso', 'pequenas-redondas', 'fusocelular', 'glandular'],
    architecture: ['nodular', 'glandulas', 'lencois', 'rosetas'],
    features: ['mitoses-altas', 'necrose', 'condroide', 'osteoide', 'estriacoes'],
    ages: ['crianca'],
    summary: 'Tumor renal da infância que recapitula o rim em desenvolvimento em três componentes — blastema azul denso, túbulos e glomeruloides epiteliais, e estroma —, e cujo prognóstico depende sobretudo de haver ou não anaplasia difusa, que é a definição de histologia desfavorável.',
    criteria: [
      'Padrão trifásico clássico: blastema, epitélio e estroma, em proporção variável (formas monofásicas existem).',
      'Anaplasia definida por núcleos três vezes maiores, hipercromasia e mitoses multipolares: focal ou difusa, e é o que define histologia desfavorável.',
      'WT1 nuclear no blastema e no epitélio precoce.',
      'Avaliação do leito e dos nódulos após quimioterapia pré-operatória segue o protocolo SIOP.',
      'Restos nefrogênicos no rim vizinho apoiam e indicam risco contralateral.',
    ],
    markers: [
      { marker: 'wt1', pct: [70, 95], note: 'nuclear; forte no blastema, fraco no estroma' },
      { marker: 'pax8', pct: [70, 90], note: 'componente epitelial' },
      { marker: 'pax2', pct: [70, 90] },
      { marker: 'ae1ae3', pct: [60, 85], note: 'só no componente epitelial' },
      { marker: 'cd56', pct: [70, 95] },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 'desmina', pct: [30, 60], note: 'componente estromal rabdomioblástico' },
      { marker: 'miogenina', pct: [20, 50] },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define tumor rabdoide do rim' },
      { marker: 'bcor', pct: [0, 10], note: 'positivo define sarcoma de células claras do rim' },
      { marker: 'cd99', pct: [10, 30], note: 'não confunda com Ewing' },
      { marker: 'sall4', pct: [10, 40] },
      { marker: 'p53', pct: [10, 30], note: 'aberrante acompanha anaplasia' },
      { marker: 'ki67', pct: [40, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Sarcoma de células claras do rim: BCOR positivo, sem componente epitelial, metastatiza para osso.',
      'Tumor rabdoide do rim: INI1 perdido, em lactente.',
      'Neuroblastoma: PHOX2B e tirosina hidroxilase, WT1 negativo.',
      'Nefroma mesoblástico: em recém-nascido, fusocelular, ETV6::NTRK3 na variante celular.',
      'Sarcoma de Ewing renal: CD99 membranoso difuso, NKX2.2, fusão EWSR1.',
    ],
    molecular: 'WT1, CTNNB1, WTX; associação com WAGR, Denys-Drash e Beckwith-Wiedemann; TP53 na anaplasia.',
    sources: [WHO, AMIN],
  },
  {
    id: 'nefroma-mesoblastico',
    name: 'Nefroma mesoblástico congênito',
    aka: ['congenital mesoblastic nephroma', 'nefroma mesoblástico celular'],
    behavior: 'intermediario',
    sites: [{ site: 'rim', role: 'primario', freq: 2 }],
    cells: ['fusocelular', 'pequenas-redondas'],
    architecture: ['fasciculos', 'infiltrativo', 'lencois'],
    features: ['mitoses-moderadas', 'mitoses-altas', 'hemorragia', 'necrose'],
    ages: ['crianca'],
    summary: 'Tumor renal do recém-nascido e do lactente, fusocelular, que infiltra o parênquima em línguas e aprisiona glomérulos e túbulos; a variante clássica é fibromatose-símile e indolente, e a celular é densamente celular com fusão ETV6::NTRK3, idêntica à do fibrossarcoma infantil.',
    criteria: [
      'Idade abaixo de um ano, quase sempre nos primeiros três meses.',
      'Proliferação fusocelular infiltrativa com aprisionamento de estruturas renais nativas.',
      'Variante clássica: fascículos frouxos, baixa celularidade, mitoses escassas.',
      'Variante celular: densamente celular, mitoses numerosas, com ETV6::NTRK3.',
      'Ausência de blastema e de componente epitelial neoplásico, que definiriam nefroblastoma.',
    ],
    markers: [
      { marker: 'pan-trk', pct: [70, 95], note: 'na variante celular, reflete ETV6::NTRK3' },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'sma', pct: [40, 80], note: 'mais na variante clássica' },
      { marker: 'desmina', pct: [10, 40] },
      { marker: 'betacatenina', pct: [10, 30], pattern: 'N' },
      { marker: 'wt1', pct: [0, 15], note: 'o negativo que ajuda contra nefroblastoma estromal' },
      { marker: 'pax8', pct: [0, 10], note: 'só nos túbulos aprisionados' },
      { marker: 'ae1ae3', pct: [0, 10], note: 'idem' },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 's100', pct: [0, 15] },
      { marker: 'cd34', pct: [10, 30] },
      { marker: 'ki67', pct: [10, 50], note: 'alto na variante celular' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Nefroblastoma estromal predominante: tem blastema ou epitélio, WT1 positivo.',
      'Sarcoma de células claras do rim: BCOR positivo, células claras com rede vascular.',
      'Tumor rabdoide do rim: INI1 perdido.',
      'Fibrossarcoma infantil de partes moles: mesma fusão e mesma histologia, fora do rim.',
    ],
    molecular: 'ETV6::NTRK3 na variante celular; alterações de EGFR internal tandem duplication na clássica.',
    sources: [WHO, AMIN],
  },
  {
    id: 'sarcoma-celulas-claras-rim',
    name: 'Sarcoma de células claras do rim',
    aka: ['clear cell sarcoma of the kidney', 'CCSK'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
    ],
    cells: ['claras', 'epitelioide', 'fusocelular', 'estreladas'],
    architecture: ['ninhos', 'trabecular', 'lencois'],
    features: ['estroma-mixoide', 'mitoses-moderadas', 'hemorragia'],
    ages: ['crianca'],
    summary: 'Segundo tumor renal maligno mais comum da infância, feito de cordões de células pálidas de limites indistintos e cromatina fina, separados por uma rede regular de capilares arborizados; é chamado de tumor ósseo metastatizante da infância, e o BCOR nuclear é o marcador atual.',
    criteria: [
      'Cordões e ninhos de células com citoplasma pálido a claro e núcleos vesiculosos de cromatina fina, sem nucléolo.',
      'Rede vascular capilar arborizada e regular, característica, envolvendo os cordões.',
      'Ausência de blastema, de componente epitelial e de anaplasia clássica.',
      'BCOR nuclear difuso reflete a duplicação interna em tandem de BCOR.',
      'WT1 negativo e INI1 retido, o que o separa de nefroblastoma e de tumor rabdoide.',
    ],
    markers: [
      { marker: 'bcor', pct: [85, 100], note: 'nuclear difuso; substituto da BCOR-ITD' },
      { marker: 'ciclinad1', pct: [80, 95], note: 'muito útil e frequentemente esquecida' },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'wt1', pct: [0, 10], note: 'o negativo contra nefroblastoma' },
      { marker: 'ini1', pct: [0, 5], note: 'retido; a perda define tumor rabdoide' },
      { marker: 'ae1ae3', pct: [0, 10], note: 'só nos túbulos aprisionados' },
      { marker: 'pax8', pct: [0, 10], note: 'idem' },
      { marker: 'desmina', pct: [0, 15] },
      { marker: 'cd34', pct: [0, 15] },
      { marker: 's100', pct: [0, 10] },
      { marker: 'sall4', pct: [0, 5] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Nefroblastoma blastematoso: WT1 positivo, blastema azul denso.',
      'Nefroma mesoblástico celular: pan-TRK, ETV6::NTRK3.',
      'Tumor rabdoide do rim: INI1 perdido.',
      'Sarcoma de Ewing renal: CD99 e NKX2.2.',
    ],
    molecular: 'Duplicação interna em tandem de BCOR na grande maioria; fusões YWHAE::NUTM2 numa minoria.',
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-urotelial-invasivo',
    name: 'Carcinoma urotelial invasivo',
    aka: ['carcinoma de células transicionais', 'urothelial carcinoma', 'CCT'],
    behavior: 'maligno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 3 },
      { site: 'rim', role: 'primario', freq: 2 },
      { site: 'penis', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'prostata', role: 'metastase', freq: 2 },
    ],
    cells: ['urotelial', 'epitelioide', 'pleomorfico', 'escamoso', 'anel-sinete', 'plasmocitoide', 'fusocelular'],
    architecture: ['ninhos', 'papilar', 'infiltrativo', 'micropapilar', 'lencois'],
    features: ['necrose', 'mitoses-altas', 'desmoplasia', 'precursor', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma com incrível capacidade de imitar outros tumores: além do padrão convencional em ninhos irregulares, tem variantes micropapilar, plasmocitoide, sarcomatoide, em ninhos e escamosa; GATA3 com p63, CK5/6, CK20 e uroplaquina formam o painel, e a resposta à imunoterapia depende do subtipo molecular.',
    criteria: [
      'Invasão além da membrana basal, com estadiamento pela profundidade: lâmina própria (T1) contra muscular própria (T2).',
      'A muscular própria deve ser identificada e mencionada; feixes de muscular da mucosa não valem.',
      'Graduação em baixo e alto grau pela desordem arquitetural e pela atipia nuclear.',
      'Variantes devem ser relatadas e quantificadas: micropapilar, plasmocitoide e sarcomatoide mudam a conduta.',
      'Carcinoma in situ adjacente apoia origem urotelial primária.',
    ],
    markers: [
      { marker: 'gata3', pct: [80, 95], note: 'cai bastante nos de alto grau e nas variantes' },
      { marker: 'p63', pct: [80, 95] },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'ck56', pct: [60, 85] },
      { marker: 'uroplaquina', pct: [50, 75], note: 'específica, pouco sensível; a positividade fecha o diagnóstico' },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck20', pct: [50, 70], note: 'com CK7 forma o perfil clássico CK7+/CK20+' },
      { marker: 's100p', pct: [70, 90] },
      { marker: 'p40', pct: [60, 85] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'her2', pct: [10, 20] },
      { marker: 'p53', pct: [50, 70] },
      { marker: 'ttf1', pct: [0, 5] },
      { marker: 'pax8', pct: [5, 20], note: 'pode ser fracamente positivo: não descarte urotelial por ele' },
      { marker: 'nkx31', pct: 0, note: 'o negativo que separa de prostático' },
      { marker: 'psa', pct: 0 },
      { marker: 'cdx2', pct: [5, 20] },
      { marker: 'ecaderina', pct: [70, 95], note: 'perdida na variante plasmocitoide' },
      { marker: 'ki67', pct: [30, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma prostático pouco diferenciado: NKX3.1 e P501S positivos, GATA3 negativo.',
      'Carcinoma escamoso de bexiga: p40 difuso, GATA3 e CK7 muitas vezes negativos, sem CIS urotelial.',
      'Carcinoma renal invadindo a pelve: PAX8 forte, GATA3 negativo.',
      'Adenocarcinoma colorretal invadindo a bexiga: CDX2 e SATB2, CK7 negativo.',
      'Carcinoma mamário lobular metastático na variante plasmocitoide: GATA3 positivo nos dois; peça ER e mamoglobina.',
    ],
    pitfalls: [
      'GATA3 marca mama, paratireoide e paraganglioma: não é prova de urotélio sozinho.',
      'A variante plasmocitoide perde E-caderina e imita carcinoma lobular e linfoma.',
    ],
    molecular: 'FGFR3 nos de baixo grau papilares (alvo de erdafitinibe); TP53 e RB1 nos de alto grau.',
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-urotelial-papilar-nao-invasivo',
    name: 'Carcinoma urotelial papilar não invasivo e carcinoma in situ',
    aka: ['carcinoma papilar de baixo grau', 'CIS urotelial', 'non-invasive papillary urothelial carcinoma'],
    behavior: 'intermediario',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 3 },
      { site: 'rim', role: 'primario', freq: 1 },
    ],
    cells: ['urotelial', 'epitelioide'],
    architecture: ['papilar'],
    features: ['mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Lesão papilar revestida por urotélio espesso com perda de polaridade e atipia, sem invasão da lâmina própria; o carcinoma in situ é a contraparte plana, com células grandes desordenadas e hipercromáticas, e o trio CK20 de espessura total, p53 aberrante e CD44 basal ausente ajuda quando a atipia é reativa contra neoplásica.',
    criteria: [
      'Eixos fibrovasculares delicados revestidos por urotélio de espessura aumentada e desordenado.',
      'Graduação em baixo e alto grau; o papiloma e a neoplasia de baixo potencial ficam abaixo.',
      'Ausência de invasão da lâmina própria (o nível mais frequente de erro é o ninho tangencial).',
      'No CIS: atipia de células grandes em espessura total, com perda de coesão e mitoses altas na camada.',
      'Painel CK20 (espessura total), p53 (aberrante) e CD44 (perda da positividade basal) apoia CIS contra atipia reativa.',
    ],
    markers: [
      { marker: 'ck20', pct: [70, 90], note: 'em espessura total no CIS; no urotélio normal só nas células guarda-chuva' },
      { marker: 'p53', pct: [60, 85], note: 'aberrante no CIS e no alto grau; selvagem no reativo' },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'uroplaquina', pct: [40, 70] },
      { marker: 'ki67', pct: [20, 60], note: 'alto e em espessura total no CIS' },
      { marker: 'nkx31', pct: 0 },
      { marker: 'psa', pct: 0 },
      { marker: 'ttf1', pct: 0 },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Atipia reativa e pós-quimioterapia intravesical: p53 selvagem, CK20 só nas guarda-chuva, inflamação.',
      'Papiloma urotelial: espessura normal, polaridade preservada, guarda-chuva mantidas.',
      'Displasia urotelial: atipia insuficiente para CIS.',
      'Metaplasia e adenoma nefrogênico: PAX8 positivo, GATA3 negativo.',
    ],
    molecular: 'FGFR3 e via RAS nos papilares de baixo grau; TP53 no CIS e nos de alto grau.',
    sources: [WHO, AMIN],
  },
  {
    id: 'cec-bexiga',
    name: 'Carcinoma de células escamosas da bexiga',
    aka: ['carcinoma escamoso vesical', 'squamous cell carcinoma of the bladder'],
    behavior: 'maligno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
    ],
    cells: ['escamoso', 'epitelioide'],
    architecture: ['ninhos', 'infiltrativo'],
    features: ['queratinizacao', 'necrose', 'desmoplasia', 'precursor', 'mitoses-altas'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma puro de diferenciação escamosa da bexiga, ligado a irritação crônica (cateter, litíase, esquistossomose), com queratinização e metaplasia escamosa com displasia na mucosa vizinha; o diagnóstico exige que não haja qualquer componente urotelial convencional ou in situ.',
    criteria: [
      'Diferenciação escamosa pura, com pontes intercelulares ou queratinização.',
      'Ausência absoluta de componente urotelial convencional e de carcinoma in situ urotelial.',
      'Metaplasia escamosa com displasia ou queratinizante adjacente apoia.',
      'Exclusão de extensão de carcinoma escamoso do colo uterino, da vagina ou do ânus.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ck903', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [30, 60], note: 'menos frequente que no urotelial' },
      { marker: 'ck20', pct: [0, 15], note: 'o negativo que ajuda contra urotelial com diferenciação escamosa' },
      { marker: 'gata3', pct: [20, 50], note: 'pode ser positivo; não resolve sozinho' },
      { marker: 'uroplaquina', pct: [0, 10] },
      { marker: 'p16', pct: [10, 30], note: 'em bloco levanta origem no colo uterino' },
      { marker: 'p53', pct: [50, 75] },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma urotelial com diferenciação escamosa: tem componente urotelial ou CIS, CK20 e uroplaquina podem ajudar.',
      'Carcinoma escamoso do colo uterino invadindo a bexiga: p16 em bloco, HPV.',
      'Metaplasia escamosa queratinizante extensa: sem invasão nem atipia franca.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'adenocarcinoma-bexiga',
    name: 'Adenocarcinoma de bexiga e do úraco',
    aka: ['adenocarcinoma vesical', 'adenocarcinoma uracal', 'bladder adenocarcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'anel-sinete', 'epitelioide'],
    architecture: ['glandulas', 'infiltrativo', 'cribriforme'],
    features: ['mucina', 'desmoplasia', 'necrose', 'mitoses-altas'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenocarcinoma primário da bexiga, entérico, mucinoso ou de células em anel de sinete, que pode nascer no domo a partir de remanescente uracal; imunologicamente é indistinguível do colorretal, e a separação depende da topografia, da ausência de tumor colônico e do achado de cistite glandular ou de úraco residual.',
    criteria: [
      'Adenocarcinoma puro, sem componente urotelial convencional nem CIS urotelial.',
      'Critérios de origem uracal: tumor centrado no domo ou na parede anterior, na muscular ou mais profundo, com epitélio uracal residual ou relação com a linha média.',
      'Exclusão clínica e endoscópica de adenocarcinoma colorretal ou de outro sítio.',
      'Cistite glandular ou metaplasia intestinal adjacente apoia primário vesical não uracal.',
    ],
    markers: [
      { marker: 'cdx2', pct: [80, 95], note: 'como no colorretal; não separa' },
      { marker: 'ck20', pct: [80, 95] },
      { marker: 'vilina', pct: [70, 90] },
      { marker: 'satb2', pct: [30, 60], note: 'positivo em parte; não exclui origem vesical' },
      { marker: 'ck7', pct: [40, 70], note: 'mais frequente que no colorretal, mas não decisivo' },
      { marker: 'muc2', pct: [60, 85] },
      { marker: 'betacatenina', pct: [10, 30], pattern: 'N', note: 'nuclear é mais do colorretal' },
      { marker: 'gata3', pct: [0, 15], note: 'o negativo esperado; não ajuda a provar origem vesical' },
      { marker: 'uroplaquina', pct: [0, 10] },
      { marker: 'p63', pct: [0, 10] },
      { marker: 'pax8', pct: [0, 10] },
      { marker: 'ki67', pct: [40, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma colorretal invadindo a bexiga: imuno idêntica; a clínica decide.',
      'Adenocarcinoma prostático com padrão ductal: NKX3.1 e P501S positivos.',
      'Carcinoma urotelial com diferenciação glandular: componente urotelial presente.',
      'Cistite glandular com metaplasia intestinal: sem invasão nem atipia.',
      'Endometriose vesical: ER, PR e PAX8 positivos, estroma endometrial CD10 positivo.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-pequenas-celulas-bexiga',
    name: 'Carcinoma neuroendócrino de pequenas células da bexiga',
    aka: ['small cell carcinoma vesical', 'carcinoma neuroendócrino de bexiga'],
    behavior: 'maligno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino'],
    architecture: ['lencois', 'ninhos'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma de pequenas células idêntico ao pulmonar, com núcleo hipercromático sem nucléolo, moldagem, esmagamento e necrose maciça, que na bexiga vem acompanhado de carcinoma urotelial convencional ou in situ em cerca de metade dos casos; a quimioterapia é a do pulmão e não a do urotelial.',
    criteria: [
      'Citologia de pequenas células: núcleo hipercromático, nucléolo ausente, moldagem nuclear, citoplasma escasso, artefato de esmagamento.',
      'Índice mitótico muito alto e necrose geográfica.',
      'Marcador neuroendócrino positivo (sinaptofisina, INSM1) ou morfologia inequívoca com queratina em dot.',
      'Qualquer proporção do componente de pequenas células basta para classificar o tumor como tal.',
      'Componente urotelial associado deve ser relatado.',
    ],
    markers: [
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [80, 95] },
      { marker: 'cromogranina', pct: [40, 70], note: 'mais fraca e focal que a sinaptofisina' },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [80, 95], pattern: 'dot', note: 'padrão perinuclear em dot frequente' },
      { marker: 'ttf1', pct: [30, 60], note: 'positivo sem significar pulmão: erro clássico' },
      { marker: 'gata3', pct: [10, 40], note: 'costuma perder-se' },
      { marker: 'p63', pct: [10, 30] },
      { marker: 'uroplaquina', pct: [0, 10] },
      { marker: 'rb1', pct: [70, 90], note: 'o positivo é a perda; quase constante' },
      { marker: 'p53', pct: [60, 90] },
      { marker: 'ck20', pct: [5, 20] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Carcinoma urotelial de alto grau pouco diferenciado: nucléolo presente, GATA3 e p63 fortes, sem marcador neuroendócrino.',
      'Linfoma: CD45 positivo, queratina negativa.',
      'Carcinoma de pequenas células pulmonar metastático: TTF-1 positivo nos dois; a clínica decide.',
      'Carcinoma prostático neuroendócrino: NKX3.1 pode persistir, história de bloqueio androgênico.',
    ],
    pitfalls: ['TTF-1 positivo num tumor de bexiga não indica primário pulmonar: até 60% dos vesicais o expressam.'],
    sources: [WHO, AMIN],
  },
  {
    id: 'adenoma-nefrogenico',
    name: 'Adenoma nefrogênico',
    aka: ['metaplasia nefrogênica', 'nephrogenic adenoma'],
    behavior: 'benigno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 2 },
      { site: 'penis', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular', 'claras'],
    architecture: ['glandulas', 'papilar', 'cistico', 'infiltrativo'],
    features: ['tachinha', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Lesão reativa em urotélio lesado por cirurgia, cateter ou cálculo, formada por túbulos pequenos, papilas e microcistos revestidos por uma camada única de células cuboides em tachinha; o perigo é ser lida como adenocarcinoma ou como carcinoma prostático, e o PAX8 com NKX3.1 negativo resolve.',
    criteria: [
      'História de instrumentação, litíase, cateter ou transplante renal.',
      'Túbulos e microcistos revestidos por camada única de células cuboides, muitas em tachinha, com bainha de membrana basal espessa.',
      'Ausência de atipia significativa, de necrose e de mitoses atípicas.',
      'PAX8 e PAX2 positivos com NKX3.1, P501S e PSA negativos.',
      'Extensão para a muscular própria pode ocorrer e não indica malignidade.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100], note: 'origem em células tubulares renais descamadas' },
      { marker: 'pax2', pct: [85, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'amacr', pct: [50, 85], note: 'positivo, e é justamente o que leva ao erro com prostático' },
      { marker: 'nkx31', pct: 0, note: 'o negativo que afasta próstata' },
      { marker: 'psa', pct: 0 },
      { marker: 'p501s', pct: 0 },
      { marker: 'gata3', pct: [0, 15] },
      { marker: 'p63', pct: [0, 10], note: 'sem camada basal, ao contrário das glândulas prostáticas benignas' },
      { marker: 'ck903', pct: [0, 10] },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma prostático: NKX3.1, P501S e PSA positivos, PAX8 negativo.',
      'Adenocarcinoma vesical: atipia, desmoplasia, CDX2.',
      'Carcinoma renal de células claras invadindo: PAX8 positivo nos dois; a massa renal decide.',
      'Cistite cística e glandular: sem padrão tubular difuso nem células em tachinha.',
    ],
    pitfalls: ['AMACR positivo com aspecto infiltrativo em biópsia de bexiga leva a diagnóstico errado de adenocarcinoma prostático; peça NKX3.1 e PAX8.'],
    sources: [WHO, AMIN],
  },
  {
    id: 'carcinoma-adrenocortical',
    name: 'Carcinoma e adenoma adrenocortical',
    aka: ['carcinoma do córtex adrenal', 'adrenocortical carcinoma', 'adenoma adrenocortical'],
    behavior: 'maligno',
    sites: [
      { site: 'adrenal', role: 'primario', freq: 3 },
      { site: 'retroperitoneo', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['claras', 'oncocitico', 'epitelioide', 'pleomorfico'],
    architecture: ['ninhos', 'trabecular', 'lencois', 'alveolar'],
    features: ['necrose', 'mitoses-altas', 'hemorragia', 'vacuolos-lipidicos'],
    ages: ['crianca', 'adulto', 'idoso'],
    summary: 'Tumor do córtex adrenal, de células claras lipídicas a compactas eosinofílicas, cuja malignidade não se decide por uma característica isolada mas pelo escore de Weiss; queratina fraca ou negativa com SF-1, inibina e Melan-A positivos é o perfil que o separa de carcinoma renal e de feocromocitoma.',
    criteria: [
      'Escore de Weiss (3 ou mais dos nove critérios) define carcinoma: alto grau nuclear, mitoses acima de 5 por 50 campos, mitoses atípicas, células claras em menos de 25%, arquitetura difusa, necrose, invasão venosa, sinusoidal e capsular.',
      'SF-1 nuclear é o marcador mais específico de linhagem adrenocortical.',
      'Queratina fraca ou negativa com vimentina forte é o padrão, e não deve levar a diagnóstico de sarcoma.',
      'Escore de Weiss não se aplica a variantes oncocítica (critérios de Lin-Weiss-Bisceglia), mixoide e pediátrica.',
      'Ki-67 acima de 5% apoia malignidade e orienta prognóstico.',
    ],
    markers: [
      { marker: 'sf1', pct: [90, 100], note: 'o marcador de linhagem mais específico' },
      { marker: 'inibina', pct: [80, 95] },
      { marker: 'melana', pct: [70, 95], note: 'clone A103; não indica melanoma' },
      { marker: 'calretinina', pct: [70, 90] },
      { marker: 'sinaptofisina', pct: [60, 85], note: 'positiva: não conclua neuroendócrino' },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [20, 50], note: 'fraca ou focal; a negatividade é esperada' },
      { marker: 'ema', pct: [0, 15] },
      { marker: 'pax8', pct: [0, 10], note: 'o negativo que separa de carcinoma renal' },
      { marker: 'caix', pct: [0, 10] },
      { marker: 'cromogranina', pct: [0, 10], note: 'o negativo que separa de feocromocitoma' },
      { marker: 'gata3', pct: [0, 10] },
      { marker: 'heppar1', pct: [0, 15] },
      { marker: 'p53', pct: [20, 50], note: 'mais frequente no carcinoma; germinativa em Li-Fraumeni' },
      { marker: 'betacatenina', pct: [20, 50], pattern: 'N' },
      { marker: 'ki67', pct: [1, 40], note: 'abaixo de 5% favorece adenoma; acima de 20% indica alto risco' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma renal de células claras invadindo a adrenal: PAX8 e CA-IX positivos, queratina forte.',
      'Feocromocitoma: cromogranina e GATA3 positivos, SF-1 negativo, sustentaculares S100.',
      'Carcinoma hepatocelular: arginase e HepPar-1.',
      'Melanoma metastático: SOX10 e HMB-45 positivos, SF-1 negativo.',
      'Adenoma adrenocortical: Weiss abaixo de 3, Ki-67 baixo, sem necrose nem invasão.',
    ],
    pitfalls: ['Melan-A e sinaptofisina positivos com queratina negativa podem sugerir melanoma ou paraganglioma; SF-1 resolve.'],
    molecular: 'TP53 (Li-Fraumeni), CTNNB1, ZNRF3; perda de heterozigose em 11p15 (Beckwith-Wiedemann).',
    sources: [WHO, 'WHO Classification of Tumours, 5ª ed.: Endocrine and Neuroendocrine Tumours (2022)', AMIN],
  },
  {
    id: 'tumor-papilar-celulas-claras-renal',
    name: 'Tumor renal papilar de células claras',
    aka: ['carcinoma renal papilar de células claras', 'clear cell papillary renal cell tumour', 'CCPRCT'],
    behavior: 'benigno',
    sites: [{ site: 'rim', role: 'primario', freq: 2 }],
    cells: ['claras', 'epitelioide'],
    architecture: ['papilar', 'glandulas', 'cistico', 'trabecular'],
    features: ['mitoses-raras', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor renal pequeno e circunscrito, comum em rim de doença renal crônica e em transplantado, com túbulos e papilas revestidos por células claras cujos núcleos se alinham longe da membrana basal, numa fileira média; foi reclassificado como benigno na 5ª edição, e nenhum caso metastático bem documentado existe.',
    criteria: [
      'Núcleos alinhados numa fileira afastada da membrana basal (polarização apical), o achado mais característico.',
      'Túbulos, papilas e cistos revestidos por células claras de baixo grau nucleolar, com estroma fibromuscular.',
      'CK7 difusa e forte com CA-IX em padrão de taça invertida (poupando a superfície apical) e CD10 negativo.',
      'Ausência de alteração de VHL e de perda de 3p, o que o separa do carcinoma de células claras.',
      'Lesão benigna: o nome perdeu o "carcinoma" em 2022, e o laudo não deve sugerir seguimento oncológico.',
    ],
    markers: [
      { marker: 'ck7', pct: [95, 100], note: 'difusa e forte; no de células claras é focal ou negativa' },
      { marker: 'caix', pct: [90, 100], note: 'padrão em taça invertida, poupando o polo apical: é o que o separa do padrão em caixa' },
      { marker: 'cd10', pct: [0, 15], note: 'o negativo que separa do carcinoma de células claras' },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ema', pct: [80, 95] },
      { marker: 'ck903', pct: [70, 95] },
      { marker: 'amacr', pct: [0, 15], note: 'o negativo que separa do papilar' },
      { marker: 'vimentina', pct: [40, 80] },
      { marker: 'cd117', pct: [0, 10] },
      { marker: 'tfe3', pct: [0, 5] },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma renal de células claras: CA-IX em caixa difuso, CD10 positivo, CK7 negativo, com perda de 3p.',
      'Carcinoma renal papilar: AMACR difuso, macrófagos espumosos, CA-IX negativo.',
      'Carcinoma renal com rearranjo de TFE3: TFE3 nuclear, queratina fraca.',
      'Carcinoma renal ELOC-mutado: CK7 positivo também, mas com bandas fibromusculares espessas.',
      'Adenoma papilar: até 15 mm, sem células claras.',
    ],
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'mtscc',
    name: 'Carcinoma renal mucinoso tubular e de células fusiformes',
    aka: ['MTSCC', 'mucinous tubular and spindle cell carcinoma'],
    behavior: 'maligno',
    sites: [{ site: 'rim', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'fusocelular', 'glandular'],
    architecture: ['glandulas', 'trabecular', 'fasciculos'],
    features: ['estroma-mixoide', 'mucina', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma renal de baixo grau feito de túbulos alongados que se fundem em cordões fusocelulares dentro de estroma mixoide azulado; a fusocelularidade assusta e leva a pensar em sarcomatoide, mas o prognóstico é bom e o perfil imuno se sobrepõe ao do papilar.',
    criteria: [
      'Três elementos: túbulos alongados e estreitos, áreas fusocelulares em transição com eles, e estroma mixoide.',
      'Baixo grau nucleolar uniforme, sem necrose nem mitoses frequentes.',
      'CK7 e AMACR positivos, como no papilar: a imuno não separa e a morfologia é que decide.',
      'Ausência de ganho de 7 e 17, com perdas múltiplas de outros cromossomos: o oposto do papilar.',
      'Variantes mucina-pobre e com componente de alto grau existem e mudam o prognóstico.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'amacr', pct: [70, 95], note: 'positiva como no papilar; não separa' },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ema', pct: [80, 95] },
      { marker: 'vimentina', pct: [70, 95] },
      { marker: 'cd10', pct: [10, 40], note: 'fraca ou negativa, ao contrário do papilar' },
      { marker: 'caix', pct: [0, 20] },
      { marker: 'cd117', pct: [0, 10] },
      { marker: 'desmina', pct: [0, 10], note: 'o negativo que exclui componente sarcomatoide verdadeiro' },
      { marker: 'sma', pct: [0, 20] },
      { marker: 'tfe3', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma renal papilar tipo 1 com padrão sólido: mesma imuno, mas com trissomias 7 e 17 e macrófagos espumosos.',
      'Carcinoma renal sarcomatoide: atipia acentuada, necrose, alto índice mitótico.',
      'Nefroma mesoblástico e outros fusocelulares: queratina negativa.',
      'Carcinoma de ductos coletores: infiltrativo com desmoplasia e alto grau.',
      'Leiomioma renal: desmina e h-caldesmon difusos.',
    ],
    molecular: 'Perdas de múltiplos cromossomos (1, 4, 6, 8, 9, 13, 14, 15, 22) e alterações da via Hippo; sem ganho de 7 e 17.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-tubulocistico',
    name: 'Carcinoma renal tubulocístico',
    aka: ['tubulocystic renal cell carcinoma'],
    behavior: 'maligno',
    sites: [{ site: 'rim', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'oncocitico'],
    architecture: ['cistico', 'glandulas'],
    features: ['tachinha', 'nucleolo', 'mitoses-raras'],
    ages: ['adulto'],
    sex: 'm',
    summary: 'Massa esponjosa em favo de mel, feita só de túbulos e cistos de tamanhos variados revestidos por uma camada única de células com citoplasma eosinofílico e núcleo em tachinha de nucléolo proeminente; o alto grau nucleolar contrasta com o comportamento indolente, o que é a armadilha do verbete.',
    criteria: [
      'Arquitetura exclusivamente tubulocística, com septos fibrosos finos e aspecto macroscópico em bolha de sabão.',
      'Camada única de células eosinofílicas em tachinha, com nucléolo proeminente (grau 3 nucleolar) que não indica agressividade aqui.',
      'Ausência de componente sólido: qualquer área sólida ou papilar significativa exclui o diagnóstico.',
      'FH deve ser avaliado: o carcinoma FH-deficiente tem áreas tubulocísticas e é muito mais agressivo.',
      'Comportamento indolente, com metástase em menos de 10%.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'amacr', pct: [80, 100] },
      { marker: 'ck7', pct: [30, 60], note: 'variável, menos que no papilar' },
      { marker: 'cd10', pct: [60, 90] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'fh', pct: [0, 10], note: 'retido; a perda define o carcinoma FH-deficiente, que imita este e é agressivo' },
      { marker: 'caix', pct: [0, 20] },
      { marker: 'cd117', pct: [0, 10] },
      { marker: 'vimentina', pct: [50, 85] },
      { marker: 'tfe3', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma renal FH-deficiente: perda de FH com 2SC positivo, nucléolo com halo perinucleolar, agressivo.',
      'Carcinoma renal papilar com padrão cístico: papilas verdadeiras com macrófagos espumosos.',
      'Rim multicístico e doença cística adquirida: revestimento sem atipia.',
      'Carcinoma de ductos coletores: infiltrativo com desmoplasia.',
      'Nefroma cístico e tumor misto epitelial e estromal: estroma ovariano-símile ER e PR positivo.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'esc-rcc',
    name: 'Carcinoma renal eosinofílico sólido e cístico',
    aka: ['ESC RCC', 'eosinophilic solid and cystic renal cell carcinoma'],
    behavior: 'maligno',
    sites: [{ site: 'rim', role: 'primario', freq: 1 }],
    cells: ['oncocitico', 'epitelioide'],
    architecture: ['cistico', 'lencois', 'nodular'],
    features: ['mitoses-raras', 'hemorragia'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Entidade nova da 5ª edição: áreas sólidas e císticas de células eosinofílicas volumosas com grânulos citoplasmáticos basofílicos grosseiros (agregados de retículo endoplasmático), quase sempre em mulher; o perfil CK20 positivo com CK7 negativo é o inverso do restante dos oncocíticos renais.',
    criteria: [
      'Mistura de áreas sólidas e macrocísticas, com células eosinofílicas de citoplasma volumoso.',
      'Grânulos ou pontilhado citoplasmático basofílico grosseiro, característico e visível no hematoxilina-eosina.',
      'CK20 positivo (focal ou difuso) com CK7 negativo ou muito focal: o padrão que define.',
      'Ausência de perda de SDHB e de FH, e ausência de rearranjo de TFE3 e TFEB.',
      'Esporádico na maioria, mas multifocal e bilateral na esclerose tuberosa: investigar quando múltiplo ou em jovem.',
    ],
    markers: [
      { marker: 'ck20', pct: [80, 100], note: 'o achado que define; é o único tumor renal oncocítico com esse padrão' },
      { marker: 'ck7', pct: [0, 20], note: 'negativa ou muito focal, ao contrário do cromófobo' },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'cd117', pct: [0, 20], note: 'o negativo que ajuda contra oncocitoma e cromófobo' },
      { marker: 'caix', pct: [0, 15] },
      { marker: 'cd10', pct: [30, 70] },
      { marker: 'vimentina', pct: [40, 80] },
      { marker: 'sdhb', pct: [0, 5], note: 'retido' },
      { marker: 'fh', pct: [0, 5], note: 'retido' },
      { marker: 'melana', pct: [0, 10], note: 'o negativo que separa do PEComa epitelioide' },
      { marker: 'hmb45', pct: [0, 10] },
      { marker: 'tfe3', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Oncocitoma renal: CK7 em células isoladas, CD117 positivo, CK20 negativo.',
      'Carcinoma renal cromófobo eosinofílico: CK7 difusa, CD117 positivo.',
      'PEComa epitelioide (angiomiolipoma): HMB-45, Melan-A e catepsina K, PAX8 negativo.',
      'Carcinoma renal SDH-deficiente: perda de SDHB, com vacúolos citoplasmáticos.',
      'Tumor eosinofílico vacuolado (EVT): entidade emergente, CD117 positivo com CK7 negativo.',
    ],
    molecular: 'Mutações bialélicas de TSC1 ou TSC2, com ativação de mTOR.',
    sources: [WHO, AMIN, 'Trpkov et al., séries que definiram o carcinoma renal eosinofílico sólido e cístico, Am J Surg Pathol e Mod Pathol'],
  },
  {
    id: 'rcc-sdh-deficiente',
    name: 'Carcinoma renal SDH-deficiente',
    aka: ['succinate dehydrogenase-deficient renal cell carcinoma', 'RCC SDHB-deficiente'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['oncocitico', 'epitelioide', 'claras'],
    architecture: ['lencois', 'ninhos', 'cistico'],
    features: ['mitoses-raras', 'vacuolos-lipidicos', 'linfoide'],
    ages: ['jovem', 'adulto'],
    summary: 'Carcinoma renal de paciente jovem, com células eosinofílicas contendo inclusões ou vacúolos citoplasmáticos pálidos de aspecto flocoso, e mastócitos entremeados; a perda de SDHB por imuno define a entidade e obriga aconselhamento genético, porque quase todos têm mutação germinativa.',
    criteria: [
      'Perda completa da marcação citoplasmática de SDHB com controle interno (endotélio e mastócitos) preservado: é o critério definidor.',
      'Células eosinofílicas com vacúolos ou inclusões citoplasmáticas pálidas e flocosas.',
      'Idade jovem (média na quarta década), com multifocalidade e bilateralidade frequentes.',
      'Encaminhamento genético obrigatório: mutação germinativa de SDHB, SDHC ou SDHA em quase todos, com risco de paraganglioma e de GIST.',
      'Transformação de alto grau e componente sarcomatoide pioram muito o prognóstico, que de resto é bom.',
    ],
    markers: [
      { marker: 'sdhb', pct: [95, 100], note: 'o positivo é a perda; critério definidor, com controle interno obrigatório' },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [70, 95], note: 'pode ser fraca' },
      { marker: 'cam52', pct: [70, 95] },
      { marker: 'ck7', pct: [0, 20], note: 'o negativo que ajuda contra cromófobo' },
      { marker: 'cd117', pct: [0, 20], note: 'idem contra oncocitoma' },
      { marker: 'caix', pct: [0, 15] },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'fh', pct: [0, 5], note: 'retido' },
      { marker: 'vimentina', pct: [30, 70] },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'triptase', pct: [70, 95], note: 'mastócitos entremeados, achado de apoio descrito' },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Oncocitoma renal: SDHB retido, CD117 positivo, cicatriz central.',
      'Carcinoma renal cromófobo eosinofílico: SDHB retido, CK7 difusa.',
      'Carcinoma renal eosinofílico sólido e cístico: CK20 positivo, SDHB retido.',
      'Carcinoma renal FH-deficiente: perda de FH, nucléolo com halo.',
      'PEComa epitelioide: HMB-45 e catepsina K.',
    ],
    molecular: 'Mutação germinativa de SDHB (a mais comum), SDHC ou SDHA com perda do alelo restante.',
    sources: [WHO, AMIN, ISUP],
  },
  {
    id: 'rcc-tfeb',
    name: 'Carcinoma renal TFEB-alterado',
    aka: ['RCC t(6;11)', 'TFEB-rearranged renal cell carcinoma', 'RCC TFEB-amplificado'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'claras', 'oncocitico'],
    architecture: ['ninhos', 'alveolar', 'lencois'],
    features: ['calcificacao', 'psamomas', 'hemorragia', 'mitoses-raras'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Carcinoma renal com população bifásica característica: células epitelioides maiores em ninhos e, agrupadas ao redor de material de membrana basal hialino, células menores de citoplasma escasso. A forma rearranjada é indolente e ocorre em jovem; a amplificada é de idoso e agressiva, e as duas se reconhecem por TFEB e catepsina K.',
    criteria: [
      'Padrão bifásico com rosetas de células pequenas em torno de material basal hialino, quando presente, é praticamente diagnóstico.',
      'TFEB nuclear positivo, com catepsina K positiva na maioria — a combinação de catepsina K com melanocíticos numa lesão renal aponta a família MiT.',
      'Separar rearranjo (jovem, indolente, TFEB forte) de amplificação (idoso, alto grau, agressivo): a distinção é molecular e muda o prognóstico radicalmente.',
      'Queratinas e EMA fracas ou focais, como nos demais tumores da família MiT.',
      'Melan-A e HMB-45 positivos sem que isso signifique PEComa: PAX8 positivo resolve.',
    ],
    markers: [
      { marker: 'tfeb', pct: [85, 100], note: 'nuclear; critério definidor, mas confirme por FISH na forma amplificada' },
      { marker: 'catepsinak', pct: [80, 100], note: 'família MiT; junto com PAX8 separa de PEComa' },
      { marker: 'melana', pct: [60, 90], note: 'positivo sem indicar melanoma nem PEComa' },
      { marker: 'hmb45', pct: [40, 75] },
      { marker: 'pax8', pct: [80, 100], note: 'o positivo que separa do PEComa' },
      { marker: 'ae1ae3', pct: [20, 50], note: 'fraca ou focal' },
      { marker: 'ema', pct: [20, 50] },
      { marker: 'cd10', pct: [50, 85] },
      { marker: 'ck7', pct: [0, 20] },
      { marker: 'caix', pct: [10, 40] },
      { marker: 'tfe3', pct: [0, 10], note: 'o negativo que separa do RCC de translocação Xp11' },
      { marker: 'cd117', pct: [0, 10] },
      { marker: 'ki67', pct: [2, 30], note: 'alto na forma amplificada' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma renal com rearranjo de TFE3: TFE3 nuclear, TFEB negativo.',
      'PEComa epitelioide renal: PAX8 negativo, HMB-45 forte e difuso.',
      'Carcinoma renal de células claras: CA-IX em caixa, queratina forte.',
      'Oncocitoma: CD117 positivo, catepsina K pode marcar e confundir.',
      'Carcinoma renal eosinofílico sólido e cístico: CK20 positivo.',
    ],
    molecular: 'Rearranjo de TFEB (t(6;11) MALAT1::TFEB) na forma indolente; amplificação de TFEB na forma agressiva.',
    sources: [WHO, AMIN],
  },
  {
    id: 'rcc-alk',
    name: 'Carcinoma renal com rearranjo de ALK',
    aka: ['ALK-rearranged renal cell carcinoma', 'RCC ALK'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'rabdoide', 'anel-sinete', 'oncocitico'],
    architecture: ['papilar', 'trabecular', 'lencois', 'glandulas'],
    features: ['mucina', 'estroma-mixoide', 'necrose', 'mitoses-moderadas'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Entidade nova da 5ª edição, morfologicamente camaleônica: pode ser papilar, mucinosa com células em anel de sinete, rabdoide ou medular-símile. A pista é a ALK positiva por imuno, e o valor do verbete é terapêutico — estes tumores respondem a inibidor de ALK.',
    criteria: [
      'Marcação de ALK por imuno-histoquímica, citoplasmática, com confirmação por FISH ou sequenciamento.',
      'Morfologia variável, sem padrão obrigatório: papilar, sólida, mucinosa com anel de sinete, rabdoide.',
      'Estroma mixoide com mucina intracelular e extracelular em parte dos casos, sobretudo nos com parceiro VCL.',
      'Em criança e adolescente, o parceiro VCL associa-se a traço falciforme e imita carcinoma medular renal — mas INI1 está retido.',
      'Reconhecer importa pela terapia: é o único carcinoma renal com alvo de ALK estabelecido.',
    ],
    markers: [
      { marker: 'alk', pct: [95, 100], note: 'critério definidor; confirme a fusão antes de indicar o inibidor' },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'ck7', pct: [40, 80] },
      { marker: 'cam52', pct: [80, 100] },
      { marker: 'ini1', pct: [0, 5], note: 'retido: é o que o separa do carcinoma medular renal, que ele imita em jovem falciforme' },
      { marker: 'amacr', pct: [30, 70] },
      { marker: 'cd10', pct: [30, 70] },
      { marker: 'caix', pct: [0, 20] },
      { marker: 'tfe3', pct: [0, 10] },
      { marker: 'vimentina', pct: [60, 95] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma medular renal: INI1 perdido, em jovem com traço falciforme.',
      'Carcinoma renal papilar: ALK negativo, trissomias 7 e 17.',
      'Carcinoma renal mucinoso tubular e de células fusiformes: ALK negativo.',
      'Carcinoma de ductos coletores: infiltrativo, ALK negativo.',
      'Metástase de adenocarcinoma com anel de sinete: PAX8 negativo, CDX2 ou GATA3 conforme a origem.',
    ],
    molecular: 'Fusões de ALK, com parceiros VCL (pediátrico, falciforme), TPM3, EML4, STRN e outros.',
    sources: [WHO, AMIN],
  },
  {
    id: 'rcc-eloc',
    name: 'Carcinoma renal ELOC-mutado',
    aka: ['TCEB1-mutated renal cell carcinoma', 'RCC ELOC', 'RCC com bandas fibromusculares'],
    behavior: 'maligno',
    sites: [{ site: 'rim', role: 'primario', freq: 1 }],
    cells: ['claras', 'epitelioide'],
    architecture: ['ninhos', 'trabecular', 'alveolar', 'papilar'],
    features: ['hialinizacao', 'mitoses-raras', 'vasos-espessos'],
    ages: ['adulto', 'idoso'],
    summary: 'Entidade nova da 5ª edição: células claras em ninhos e trabéculas atravessados por bandas fibromusculares espessas e proeminentes, o que dá um aspecto lobulado inconfundível. Diferente do carcinoma de células claras clássico por ser CK7 positivo e por não ter alteração de VHL.',
    criteria: [
      'Bandas fibromusculares espessas dividindo o tumor em lóbulos: o achado arquitetural que chama a atenção.',
      'Células claras de grau nucleolar baixo a intermediário em ninhos e trabéculas.',
      'CK7 positiva, difusa ou em parte significativa, com CA-IX em caixa também positiva: a combinação é que separa do de células claras clássico.',
      'Mutação de ELOC (antigo TCEB1) com monossomia de 8, e sem alteração de VHL nem perda de 3p.',
      'Comportamento indolente na maioria das séries publicadas.',
    ],
    markers: [
      { marker: 'ck7', pct: [80, 100], note: 'positiva, ao contrário do carcinoma de células claras clássico' },
      { marker: 'caix', pct: [85, 100], note: 'em caixa, como no de células claras: por isso a CK7 é o desempate' },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'cd10', pct: [40, 80] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'vimentina', pct: [60, 95] },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'amacr', pct: [0, 20] },
      { marker: 'cd117', pct: [0, 10] },
      { marker: 'tfe3', pct: [0, 5] },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma renal de células claras: CK7 negativa ou focal, com perda de 3p e VHL alterado.',
      'Tumor renal papilar de células claras: CA-IX em taça invertida, CD10 negativo, benigno.',
      'Carcinoma renal cromófobo: CD117 positivo, CA-IX negativa.',
      'Carcinoma renal de translocação: TFE3 ou TFEB nuclear.',
    ],
    molecular: 'Mutação de ELOC (TCEB1) com monossomia de 8; VHL e 3p íntegros.',
    sources: [WHO, AMIN],
  },
  {
    id: 'lot-evt',
    name: 'Tumor oncocítico de baixo grau e tumor eosinofílico vacuolado',
    aka: ['LOT', 'low-grade oncocytic tumour', 'EVT', 'eosinophilic vacuolated tumour'],
    behavior: 'benigno',
    sites: [{ site: 'rim', role: 'primario', freq: 1 }],
    cells: ['oncocitico', 'epitelioide'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['estroma-mixoide', 'mitoses-raras', 'linfoide', 'vacuolos-lipidicos'],
    ages: ['adulto', 'idoso'],
    summary: 'Dois tumores emergentes que resolvem boa parte do grupo oncocítico antes chamado de indefinido. O de baixo grau tem células eosinofílicas com halos perinucleares e o perfil invertido CK7 positivo com CD117 negativo. O eosinofílico vacuolado tem vacúolos citoplasmáticos grandes e nucléolo proeminente, com CD117 positivo e CK7 apenas focal.',
    criteria: [
      'Tumor oncocítico de baixo grau: lençóis de células eosinofílicas com halos perinucleares e áreas de estroma frouxo edematoso, com agregados linfoides.',
      'CK7 difusa e forte com CD117 negativo: a combinação invertida que o define e o separa de oncocitoma e cromófobo.',
      'Tumor eosinofílico vacuolado: células grandes com vacúolos citoplasmáticos proeminentes e nucléolo evidente, CD117 positivo com CK7 focal.',
      'Ambos com perda de SDHB e de FH excluídas, e sem rearranjo da família MiT.',
      'Comportamento benigno nas séries publicadas; são categorias emergentes, e o laudo deve dizer isso.',
    ],
    markers: [
      { marker: 'ck7', pct: [60, 90], note: 'difusa no de baixo grau; focal no eosinofílico vacuolado' },
      { marker: 'cd117', pct: [20, 50], note: 'negativo no de baixo grau, positivo no eosinofílico vacuolado: o par com CK7 é o que separa' },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'catepsinak', pct: [30, 70], note: 'positiva no eosinofílico vacuolado, refletindo a via mTOR' },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'sdhb', pct: [0, 5], note: 'retido' },
      { marker: 'fh', pct: [0, 5], note: 'retido' },
      { marker: 'caix', pct: [0, 15] },
      { marker: 'ck20', pct: [0, 20], note: 'o negativo que ajuda contra o eosinofílico sólido e cístico' },
      { marker: 'vimentina', pct: [10, 50] },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'tfe3', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Oncocitoma renal: CK7 em células isoladas com CD117 positivo.',
      'Carcinoma renal cromófobo eosinofílico: CK7 difusa com CD117 positivo, núcleo enrugado.',
      'Carcinoma renal eosinofílico sólido e cístico: CK20 positivo.',
      'Carcinoma renal SDH-deficiente: perda de SDHB.',
      'PEComa epitelioide: HMB-45 e Melan-A, PAX8 negativo.',
    ],
    molecular: 'Alterações da via mTOR (TSC1, TSC2, MTOR) em ambos; ausência das perdas cromossômicas do cromófobo.',
    sources: [WHO, AMIN, 'Trpkov et al., propostas de LOT e EVT como entidades emergentes, Mod Pathol'],
  },
  {
    id: 'tumor-rabdoide-rim',
    name: 'Tumor rabdoide do rim',
    aka: ['rhabdoid tumour of the kidney', 'tumor rabdoide renal maligno'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'encefalo', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['rabdoide', 'epitelioide', 'pleomorfico'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'nucleolo', 'hemorragia'],
    ages: ['crianca'],
    summary: 'Tumor renal do lactente, altamente agressivo, feito de lençóis de células discoesas com núcleo excêntrico de nucléolo enorme e inclusão citoplasmática eosinofílica globular; a perda de INI1 define, e a associação com tumor rabdoide teratoide atípico do sistema nervoso obriga a investigar a linha germinativa.',
    criteria: [
      'Células rabdoides com inclusão citoplasmática eosinofílica que desloca o núcleo, e nucléolo muito proeminente.',
      'Perda completa de INI1 (SMARCB1) com controle interno retido: é o critério definidor.',
      'Idade quase sempre abaixo de dois anos, com invasão renal extensa ao diagnóstico.',
      'Ausência de blastema, de componente epitelial organizado e de BCOR, o que o separa de nefroblastoma e de sarcoma de células claras.',
      'Pesquisa germinativa de SMARCB1 obrigatória, pelo risco de tumor rabdoide sincrônico do sistema nervoso.',
    ],
    markers: [
      { marker: 'ini1', pct: [95, 100], note: 'o positivo é a perda; critério definidor' },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 'ema', pct: [60, 90] },
      { marker: 'ae1ae3', pct: [40, 80], note: 'focal; mais fraca que num carcinoma' },
      { marker: 'cam52', pct: [40, 80] },
      { marker: 'pax8', pct: [0, 20], note: 'o negativo que ajuda contra carcinoma renal, apesar do sítio' },
      { marker: 'wt1', pct: [0, 10], note: 'o negativo que separa do nefroblastoma' },
      { marker: 'bcor', pct: [0, 10], note: 'o negativo que separa do sarcoma de células claras do rim' },
      { marker: 'desmina', pct: [0, 15], note: 'o negativo que exclui rabdomiossarcoma' },
      { marker: 'miogenina', pct: [0, 5] },
      { marker: 'sinaptofisina', pct: [0, 20] },
      { marker: 'cd99', pct: [10, 30] },
      { marker: 'ki67', pct: [50, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Nefroblastoma com células rabdoides: INI1 retido, WT1 positivo, blastema presente.',
      'Sarcoma de células claras do rim: BCOR positivo, INI1 retido.',
      'Carcinoma medular renal: também INI1 perdido, mas em adolescente falciforme e com fenótipo epitelial franco.',
      'Nefroma mesoblástico celular: pan-TRK, ETV6::NTRK3.',
      'Neuroblastoma invadindo o rim: PHOX2B e tirosina hidroxilase.',
    ],
    molecular: 'Inativação bialélica de SMARCB1, germinativa em parte considerável (síndrome de predisposição a tumor rabdoide).',
    sources: [WHO, AMIN],
  },
  {
    id: 'papiloma-urotelial',
    name: 'Papiloma urotelial e neoplasia urotelial papilar de baixo potencial maligno',
    aka: ['papiloma urotelial', 'PUNLMP', 'papiloma invertido urotelial'],
    behavior: 'benigno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 2 },
      { site: 'rim', role: 'primario', freq: 1 },
    ],
    cells: ['urotelial', 'epitelioide'],
    architecture: ['papilar'],
    features: ['mitoses-raras'],
    ages: ['jovem', 'adulto', 'idoso'],
    summary: 'O extremo benigno da via papilar da bexiga: o papiloma tem eixos fibrovasculares delicados revestidos por urotélio de espessura e polaridade completamente normais, com células guarda-chuva preservadas; a neoplasia de baixo potencial maligno tem urotélio mais espesso, ainda ordenado e sem atipia, e recidiva sem progredir na quase totalidade.',
    criteria: [
      'Papiloma: urotélio de espessura normal (até sete camadas), polaridade preservada, células guarda-chuva presentes, sem atipia e sem mitoses acima da basal.',
      'Neoplasia papilar de baixo potencial maligno: urotélio espessado com polaridade ainda preservada, núcleos aumentados mas uniformes, mitoses raras e basais.',
      'Ausência de desordem arquitetural e de pleomorfismo, que definiriam carcinoma papilar de baixo grau.',
      'CK20 restrita às células guarda-chuva, p53 selvagem e CD44 basal preservado: o padrão oposto ao do carcinoma in situ.',
      'Papiloma invertido: crescimento endofítico em cordões anastomosantes com paliçada periférica, sem atipia, entidade benigna à parte.',
    ],
    markers: [
      { marker: 'ck20', pct: [5, 20], note: 'só nas células guarda-chuva; em espessura total indicaria carcinoma in situ' },
      { marker: 'p53', pct: [0, 10], note: 'selvagem' },
      { marker: 'gata3', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'uroplaquina', pct: [50, 85], note: 'nas guarda-chuva, preservadas' },
      { marker: 'ki67', pct: [1, 10], note: 'basal; alto e em espessura total favorece carcinoma' },
      { marker: 'nkx31', pct: 0 },
      { marker: 'psa', pct: 0 },
      { marker: 'pax8', pct: [0, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma urotelial papilar não invasivo de baixo grau: desordem arquitetural com variação nuclear.',
      'Hiperplasia urotelial papilar: sem eixo fibrovascular verdadeiro.',
      'Pólipo fibroepitelial: eixo estromal grosso com urotélio normal.',
      'Cistite polipoide e papilar: edema de lâmina própria com inflamação, base larga.',
      'Adenoma nefrogênico papilar: PAX8 positivo, GATA3 negativo.',
    ],
    molecular: 'FGFR3 mutado na maioria, como nos papilares de baixo grau; TP53 íntegro.',
    sources: [WHO, AMIN],
  },
  {
    id: 'adenoma-metanefrico',
    name: 'Adenoma metanéfrico',
    aka: ['metanephric adenoma'],
    behavior: 'benigno',
    sites: [{ site: 'rim', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'pequenas-redondas', 'blastematoso'],
    architecture: ['glandulas', 'papilar', 'rosetas'],
    features: ['psamomas', 'calcificacao', 'mitoses-raras', 'estroma-mixoide'],
    ages: ['adulto'],
    sex: 'f',
    summary: 'Nódulo renal bem delimitado feito de túbulos pequenos, apertados e uniformes, revestidos por células cuboides de citoplasma escasso e núcleo bland, muitas vezes com corpos psamomatosos e papilas glomeruloides; imita nefroblastoma epitelial e carcinoma papilar, e o BRAF V600E com WT1 positivo e AMACR negativo é o que resolve.',
    criteria: [
      'Túbulos pequenos, uniformes e densamente agrupados, de células cuboides sem atipia e com nucléolo inconspícuo.',
      'Corpos psamomatosos frequentes; estroma escasso, às vezes edematoso ou hialinizado.',
      'WT1 positivo com CK7 e AMACR negativos: o perfil que o separa do carcinoma papilar.',
      'Ausência de blastema e de componente estromal neoplásico, o que o separa do nefroblastoma.',
      'BRAF V600E presente na grande maioria e útil quando a biópsia é pequena.',
    ],
    markers: [
      { marker: 'brafv600e', pct: [85, 100], note: 'clone VE1; presente na grande maioria e muito útil aqui' },
      { marker: 'wt1', pct: [85, 100], note: 'nuclear; o carcinoma papilar é negativo' },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'pax2', pct: [80, 95] },
      { marker: 'cd57', pct: [70, 95], note: 'positivo, achado de apoio clássico' },
      { marker: 'ck7', pct: [0, 15], note: 'o negativo que separa do papilar' },
      { marker: 'amacr', pct: [0, 15], note: 'idem' },
      { marker: 'ae1ae3', pct: [70, 95] },
      { marker: 'ema', pct: [0, 20] },
      { marker: 'cd10', pct: [0, 20] },
      { marker: 'caix', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma renal papilar tipo 1 sólido: CK7 e AMACR positivos, WT1 negativo.',
      'Nefroblastoma epitelial: blastema presente, mitoses, em criança.',
      'Nefroma metanéfrico e tumor estromal metanéfrico: componente estromal dominante.',
      'Carcinoma de ductos coletores: infiltrativo com desmoplasia e alto grau.',
      'Adenoma papilar: papilas com macrófagos espumosos, CK7 positivo.',
    ],
    molecular: 'BRAF V600E na grande maioria.',
    sources: [WHO, AMIN],
  },
  {
    id: 'tumor-misto-epitelial-estromal-renal',
    name: 'Tumor misto epitelial e estromal do rim e nefroma cístico',
    aka: ['MEST', 'mixed epithelial and stromal tumour', 'nefroma cístico do adulto'],
    behavior: 'benigno',
    sites: [{ site: 'rim', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'fusocelular', 'glandular'],
    architecture: ['cistico', 'glandulas', 'fasciculos'],
    features: ['hialinizacao', 'mitoses-raras', 'tachinha'],
    ages: ['adulto'],
    sex: 'f',
    summary: 'Massa renal cística e sólida de mulher na perimenopausa, muitas vezes com história de reposição hormonal: cistos e túbulos revestidos por epitélio cuboide ou em tachinha, dentro de um estroma fusocelular que expressa receptores hormonais e lembra estroma ovariano. Nefroma cístico e MEST são hoje o mesmo espectro.',
    criteria: [
      'Componente epitelial (cistos e túbulos com revestimento cuboide, colunar ou em tachinha) com componente estromal fusocelular, os dois neoplásicos.',
      'Estroma com ER e PR positivos, às vezes com aspecto ovariano-símile.',
      'Predomínio feminino acentuado, na quinta e sexta décadas.',
      'Ausência de blastema e de elementos imaturos, que definiriam nefroblastoma cístico parcialmente diferenciado, da criança.',
      'Benigno; os raros casos com sarcoma sobre MEST são exceção e exigem atipia franca.',
    ],
    markers: [
      { marker: 'er', pct: [80, 95], note: 'no estroma; é o achado que define o espectro' },
      { marker: 'pr', pct: [85, 100] },
      { marker: 'cd10', pct: [50, 85], note: 'estroma' },
      { marker: 'inibina', pct: [20, 50] },
      { marker: 'calretinina', pct: [20, 50] },
      { marker: 'pax8', pct: [85, 100], note: 'componente epitelial' },
      { marker: 'ck7', pct: [70, 95], note: 'componente epitelial' },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'sma', pct: [40, 80], note: 'estroma' },
      { marker: 'desmina', pct: [30, 70] },
      { marker: 'wt1', pct: [30, 70], note: 'estroma' },
      { marker: 'caix', pct: [0, 15] },
      { marker: 'melana', pct: [0, 10], note: 'o negativo que afasta angiomiolipoma epitelioide' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Nefroblastoma cístico parcialmente diferenciado: blastema nos septos, em criança.',
      'Carcinoma renal multilocular cístico de baixo potencial: septos com células claras, CA-IX positivo.',
      'Angiomiolipoma com epitélio aprisionado: HMB-45 e Melan-A.',
      'Carcinoma renal tubulocístico: sem componente estromal celular.',
      'Rim policístico e cistos simples: revestimento único sem estroma celular.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'rcc-doenca-cistica-adquirida',
    name: 'Carcinoma renal associado a doença cística adquirida',
    aka: ['acquired cystic disease-associated renal cell carcinoma', 'RCC de doença cística adquirida'],
    behavior: 'maligno',
    sites: [
      { site: 'rim', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['oncocitico', 'epitelioide', 'claras'],
    architecture: ['cribriforme', 'papilar', 'cistico', 'lencois'],
    features: ['calcificacao', 'hemorragia', 'nucleolo', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma que surge no rim em diálise prolongada, com arquitetura em crivo e buracos que lembram um queijo suíço, células eosinofílicas de nucléolo proeminente e, o achado que o define, cristais intratumorais de oxalato de cálcio birrefringentes sob luz polarizada. É o carcinoma renal mais comum da doença cística adquirida.',
    criteria: [
      'Contexto de doença renal crônica em diálise prolongada com rins císticos adquiridos.',
      'Arquitetura cribriforme com microcistos intracitoplasmáticos e interceluares, dando aspecto de peneira.',
      'Cristais de oxalato de cálcio dentro do tumor, birrefringentes à luz polarizada: achado característico e quase específico.',
      'Células eosinofílicas de grau nucleolar alto com nucléolo proeminente, apesar do comportamento em geral indolente.',
      'AMACR positivo com CK7 negativo, o que ajuda contra o papilar.',
    ],
    markers: [
      { marker: 'amacr', pct: [85, 100] },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ck7', pct: [0, 20], note: 'o negativo que o separa do papilar, que é CK7 difuso' },
      { marker: 'cd10', pct: [60, 90] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'caix', pct: [0, 20] },
      { marker: 'cd117', pct: [0, 15] },
      { marker: 'vimentina', pct: [40, 80] },
      { marker: 'ck20', pct: [0, 15], note: 'o negativo que ajuda contra o eosinofílico sólido e cístico' },
      { marker: 'sdhb', pct: [0, 5], note: 'retido' },
      { marker: 'fh', pct: [0, 5], note: 'retido' },
      { marker: 'tfe3', pct: [0, 10] },
      { marker: 'ki67', pct: [2, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma renal papilar tipo 2: CK7 positivo, sem cristais de oxalato.',
      'Carcinoma renal de células claras eosinofílico: CA-IX em caixa.',
      'Carcinoma renal eosinofílico sólido e cístico: CK20 positivo, TSC alterado.',
      'Cistos da doença adquirida com atipia reativa: sem massa nem arquitetura cribriforme.',
      'Carcinoma renal papilar de células claras: CK7 difusa com CA-IX em taça.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'mielolipoma',
    name: 'Mielolipoma adrenal',
    aka: ['mielolipoma', 'adrenal myelolipoma'],
    behavior: 'benigno',
    sites: [
      { site: 'adrenal', role: 'primario', freq: 2 },
      { site: 'retroperitoneo', role: 'primario', freq: 1 },
    ],
    cells: ['adipocitico', 'blastematoso', 'gigantes'],
    architecture: ['nodular', 'lobular'],
    features: ['vacuolos-lipidicos', 'hemorragia', 'calcificacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Lesão adrenal benigna comum, achada por imagem, feita de tecido adiposo maduro misturado a hematopoese trilinear ativa — com megacariócitos, precursores eritroides e granulocíticos —, sem estroma medular organizado nem trabéculas ósseas. A densidade gordurosa na tomografia é praticamente diagnóstica.',
    criteria: [
      'Mistura de tecido adiposo maduro com elementos hematopoéticos das três linhagens, incluindo megacariócitos.',
      'Ausência de atipia adipocitária e de lipoblastos.',
      'Ausência de trabéculas ósseas e de arquitetura medular organizada, o que a separa de tecido medular ósseo heterotópico.',
      'Córtex adrenal residual comprimido na periferia, confirmando a topografia.',
      'Associação com hiperplasia adrenal congênita e com estímulo crônico por ACTH em parte dos casos.',
    ],
    markers: [
      { marker: 'cd61', pct: [90, 100], note: 'revela os megacariócitos, que provam a hematopoese trilinear' },
      { marker: 'mpo', pct: [85, 100], note: 'série granulocítica' },
      { marker: 'cd34', pct: [10, 40], note: 'precursores esparsos; abundante levantaria neoplasia mieloide' },
      { marker: 's100', pct: [85, 100], note: 'componente adiposo' },
      { marker: 'cd45', pct: [70, 95], note: 'células hematopoéticas' },
      { marker: 'sf1', pct: [0, 20], note: 'só o córtex adrenal residual comprimido' },
      { marker: 'inibina', pct: [0, 20] },
      { marker: 'melana', pct: [0, 15] },
      { marker: 'mdm2', pct: [0, 5], note: 'o negativo que exclui lipossarcoma retroperitoneal' },
      { marker: 'cdk4', pct: [0, 5] },
      { marker: 'hmb45', pct: [0, 5], note: 'o negativo que exclui angiomiolipoma' },
      { marker: 'reticulina', pct: [0, 20] },
      { marker: 'ki67', pct: [1, 10] },
    ],
    mimics: [
      'Lipossarcoma bem diferenciado retroperitoneal: MDM2 e CDK4 amplificados, atipia estromal.',
      'Angiomiolipoma: HMB-45 e Melan-A positivos, vasos de parede espessa.',
      'Hematopoese extramedular adrenal: sem componente adiposo dominante, em contexto de anemia crônica.',
      'Sarcoma mieloide adrenal: lençóis de blastos, MPO com CD34 e CD117 difusos.',
      'Lipoma e adenoma adrenocortical rico em lipídio: SF-1 e inibina positivos nas células neoplásicas.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'tumor-celulas-justaglomerulares',
    name: 'Tumor de células justaglomerulares',
    aka: ['reninoma', 'juxtaglomerular cell tumour'],
    behavior: 'benigno',
    sites: [{ site: 'rim', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'fusocelular'],
    architecture: ['lencois', 'hemangiopericitoma', 'trabecular'],
    features: ['hialinizacao', 'mitoses-raras', 'hemorragia'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Tumor renal raro de mulher jovem com hipertensão grave refratária, hipocalemia e renina alta: lençóis de células poligonais monótonas com rede vascular hemangiopericitoide, que produzem renina. A hipertensão desaparece após a nefrectomia parcial, e por isso o reconhecimento vale mais que a raridade.',
    criteria: [
      'Quadro clínico de hipertensão grave em jovem com hiperaldosteronismo secundário: renina e aldosterona altas com potássio baixo.',
      'Lençóis de células poligonais ou fusiformes uniformes com citoplasma eosinofílico e rede vascular hemangiopericitoide.',
      'Positividade para renina por imuno e grânulos romboides à microscopia eletrônica.',
      'CD34 positivo com actina de músculo liso, refletindo a origem no aparelho justaglomerular (pericito modificado).',
      'Ausência de atipia, necrose e mitoses; benigno, curado pela ressecção.',
    ],
    markers: [
      { marker: 'cd34', pct: [80, 100], note: 'positivo nas células tumorais, e não só no endotélio' },
      { marker: 'sma', pct: [70, 95] },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 'calponina', pct: [50, 85] },
      { marker: 'pax8', pct: [0, 15], note: 'o negativo que separa dos carcinomas renais' },
      { marker: 'ae1ae3', pct: [0, 15] },
      { marker: 'caix', pct: [0, 10] },
      { marker: 'cd10', pct: [0, 20] },
      { marker: 'cromogranina', pct: [0, 20] },
      { marker: 'sinaptofisina', pct: [10, 40], note: 'positiva em parte; não conclua neuroendócrino' },
      { marker: 'stat6', pct: [0, 5], note: 'o negativo que separa do tumor fibroso solitário, que compartilha os vasos' },
      { marker: 'melana', pct: [0, 5], note: 'o negativo que exclui PEComa' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor fibroso solitário renal: STAT6 nuclear com CD34.',
      'Glomangioma e tumor glômico renal: colágeno IV pericelular, SMA forte.',
      'Carcinoma renal de células claras: PAX8 e CA-IX positivos.',
      'PEComa e angiomiolipoma epitelioide: HMB-45 e Melan-A.',
      'Hemangioblastoma renal e tumor neuroendócrino: inibina ou cromogranina difusas.',
    ],
    sources: [WHO, AMIN],
  },
  {
    id: 'cistite-cistica-glandular',
    name: 'Cistite cística e glandular e outros mímicos benignos da bexiga',
    aka: ['cistite cística', 'cistite glandular', 'ninhos de von Brunn', 'metaplasia intestinal da bexiga'],
    behavior: 'benigno',
    sites: [
      { site: 'bexiga', role: 'primario', freq: 3 },
      { site: 'rim', role: 'primario', freq: 1 },
    ],
    cells: ['urotelial', 'glandular', 'epitelioide'],
    architecture: ['ninhos', 'cistico', 'glandulas'],
    features: ['mucina', 'mitoses-raras', 'linfoide'],
    ages: ['adulto', 'idoso'],
    summary: 'O espectro reativo da bexiga que imita adenocarcinoma e carcinoma urotelial em ninhos: ninhos de von Brunn invaginados, que se cistificam (cistite cística) e ganham epitélio colunar mucinoso (cistite glandular), com metaplasia intestinal nas formas crônicas. A arquitetura regular e a base linear são o que separam do carcinoma.',
    criteria: [
      'Ninhos de von Brunn regulares, arredondados e alinhados numa base linear na lâmina própria, sem ultrapassá-la.',
      'Cistite cística: ninhos com luz central; cistite glandular: revestimento colunar mucinoso, com ou sem metaplasia intestinal.',
      'Ausência de atipia citológica, de mitoses e de desmoplasia.',
      'Metaplasia intestinal extensa não é considerada lesão pré-maligna isolada, ao contrário do que já se pensou.',
      'Distinção do carcinoma urotelial variante em ninhos: este tem ninhos irregulares, confluentes, de profundidade variável, com atipia na base.',
    ],
    markers: [
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'p63', pct: [85, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ck20', pct: [10, 40], note: 'restrita às células superficiais e ao epitélio glandular; em espessura total indicaria neoplasia' },
      { marker: 'p53', pct: [0, 10], note: 'selvagem; aberrante favorece carcinoma' },
      { marker: 'ki67', pct: [1, 10], note: 'baixo; alto e difuso favorece carcinoma variante em ninhos' },
      { marker: 'cdx2', pct: [20, 60], note: 'nas áreas de metaplasia intestinal; não indica adenocarcinoma' },
      { marker: 'muc2', pct: [20, 60] },
      { marker: 'satb2', pct: [10, 40], note: 'positivo na metaplasia intestinal: não conclua origem colorretal' },
      { marker: 'uroplaquina', pct: [40, 80] },
      { marker: 'pax8', pct: [0, 15], note: 'positivo indicaria adenoma nefrogênico' },
      { marker: 'nkx31', pct: 0 },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma urotelial variante em ninhos: ninhos irregulares e confluentes com profundidade variável e atipia na base — o mímico maligno mais perigoso.',
      'Adenocarcinoma de bexiga: glândulas infiltrativas com desmoplasia e atipia.',
      'Adenoma nefrogênico: PAX8 positivo, células em tachinha.',
      'Malacoplaquia: corpos de Michaelis-Gutmann, CD68.',
      'Metaplasia escamosa e leucoplasia: epitélio escamoso queratinizado.',
    ],
    sources: [WHO, AMIN],
  },
]
