/* ==========================================================================
   ovary.ts — ovário, tuba uterina e peritônio ginecológico.

   Quase todo carcinoma daqui é PAX8 positivo; o trabalho é o subtipo, porque
   cada um tem terapia diferente. Seroso de alto grau: p53 aberrante, WT1
   positivo, p16 em bloco. Seroso de baixo grau: p53 selvagem, WT1 positivo.
   Endometrioide: WT1 negativo, ER positivo, às vezes β-catenina nuclear.
   Células claras: HNF1β e napsina, ER negativo. Mucinoso: CK7/CK20 e CDX2,
   e a primeira pergunta é sempre se não é metástase gastrointestinal.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Female Genital Tumours, 2020; Nucci & Oliva, Gynecologic
   Pathology; Kurman, Blaustein's Pathology of the Female Genital Tract, 7ª ed.;
   séries de Am J Surg Pathol e Mod Pathol). As fontes estão como referência de
   texto: as séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Female Genital Tumours (2020)'
const NUCCI = 'Nucci & Oliva, Gynecologic Pathology (série Foundations in Diagnostic Pathology)'
const BLAUSTEIN = "Kurman et al., Blaustein's Pathology of the Female Genital Tract, 7ª ed."

export const ovary: Tumor[] = [
  {
    id: 'seroso-alto-grau',
    name: 'Carcinoma seroso de alto grau',
    aka: ['HGSC', 'high-grade serous carcinoma', 'carcinoma seroso tubo-ovariano'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 3 },
      { site: 'tuba', role: 'primario', freq: 3 },
      { site: 'peritoneo', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'pleura', role: 'metastase', freq: 2 },
      { site: 'utero', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'glandular', 'pleomorfico', 'claras'],
    architecture: ['papilar', 'micropapilar', 'cribriforme', 'lencois', 'glandulas'],
    features: ['psamomas', 'necrose', 'mitoses-altas', 'desmoplasia', 'nucleolo', 'tachinha'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'O carcinoma ovariano mais comum e o mais letal: papilas e fendas revestidas por células muito atípicas, com pleomorfismo de três para um, mitoses numerosas e necrose; nasce na fímbria tubária a partir do STIC, e p53 aberrante com WT1 positivo é o par que o define.',
    criteria: [
      'Atipia nuclear acentuada com variação de três vezes no tamanho nuclear e nucléolos evidentes.',
      'Mais de 12 mitoses por 10 campos de grande aumento.',
      'Padrão p53 aberrante (difuso forte, nulo ou citoplasmático) em praticamente todos.',
      'WT1 nuclear positivo apoia origem tubo-ovariana e separa do endometrial seroso (que é WT1 negativo na maioria).',
      'Exame completo das fímbrias (protocolo SEE-FIM) para achar o STIC e atribuir o sítio primário.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'p53', pct: [95, 100], note: 'aberrante; o padrão selvagem praticamente exclui o diagnóstico, mas cerca de 4% têm TP53 mutado com imuno selvagem', source: 'Köbel et al., J Pathol Clin Res 2:247 (2016), p53 otimizado como preditor de TP53 mutado' },
      { marker: 'wt1', pct: [80, 95] },
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'p16', pct: [70, 90], note: 'em bloco, sem HPV' },
      { marker: 'er', pct: [70, 85], note: 'positivo, mas não indica resposta hormonal como na mama' },
      { marker: 'pr', pct: [30, 50] },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'cdx2', pct: [0, 5] },
      { marker: 'napsina', pct: [0, 5], note: 'o negativo que separa de células claras' },
      { marker: 'hnf1b', pct: [5, 20] },
      { marker: 'gata3', pct: [0, 10] },
      { marker: 'ttf1', pct: [0, 5] },
      { marker: 'calretinina', pct: [10, 30], note: 'não confunda com mesotelioma' },
      { marker: 'berep4', pct: [90, 100], note: 'positivo contra mesotelioma' },
      { marker: 'moc31', pct: [90, 100] },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma seroso de baixo grau: p53 selvagem, atipia uniforme, poucas mitoses.',
      'Mesotelioma peritoneal: calretinina e D2-40 positivos, BerEP4 e MOC-31 negativos, BAP1 pode ser perdido.',
      'Carcinoma endometrial seroso: WT1 costuma ser negativo; a distinção é clínico-patológica.',
      'Carcinoma de células claras: HNF1β e napsina positivos, ER negativo, p53 selvagem.',
      'Metástase de adenocarcinoma pancreatobiliar ou mamário: CK7 positivo nos dois; peça PAX8 e GATA3.',
    ],
    pitfalls: ['Padrão p53 "nulo" (ausência completa com controle interno positivo) é aberrante, não negativo.'],
    molecular: 'TP53 em quase 100%; BRCA1/2 germinativas ou somáticas em cerca de 20%, com indicação de inibidor de PARP.',
    sources: [WHO, NUCCI, BLAUSTEIN],
  },
  {
    id: 'seroso-baixo-grau',
    name: 'Carcinoma seroso de baixo grau',
    aka: ['LGSC', 'low-grade serous carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 2 },
      { site: 'peritoneo', role: 'primario', freq: 2 },
      { site: 'tuba', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'glandular'],
    architecture: ['papilar', 'micropapilar', 'cribriforme', 'infiltrativo'],
    features: ['psamomas', 'desmoplasia', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Carcinoma de células uniformes com atipia leve e mitoses escassas, invadindo em ninhos pequenos e micropapilas rodeados por fendas retráteis, com psamomas abundantes; surge de tumor seroso borderline, responde mal à quimioterapia e tem via MAPK ativada.',
    criteria: [
      'Uniformidade nuclear com variação de no máximo três vezes e nucléolo pequeno.',
      'Menos de 12 mitoses por 10 campos de grande aumento.',
      'Invasão destrutiva em micropapilas, ninhos e papilas com fendas retráteis.',
      'p53 selvagem: é o critério imuno que o separa do alto grau.',
      'Componente de tumor seroso borderline adjacente é frequente e apoia.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'wt1', pct: [85, 100] },
      { marker: 'p53', pct: [0, 10], note: 'selvagem; é o critério contra o alto grau' },
      { marker: 'er', pct: [80, 95] },
      { marker: 'pr', pct: [50, 80] },
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'p16', pct: [10, 30], note: 'focal, não em bloco' },
      { marker: 'brafv600e', pct: [5, 20], note: 'reflete BRAF mutado, mais comum nos borderline' },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'cdx2', pct: [0, 5] },
      { marker: 'napsina', pct: [0, 5] },
      { marker: 'calretinina', pct: [5, 20] },
      { marker: 'ki67', pct: [2, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma seroso de alto grau: p53 aberrante, atipia marcada, Ki-67 alto.',
      'Tumor seroso borderline com implantes não invasivos: sem invasão destrutiva.',
      'Endossalpingiose: glândulas benignas ciliadas sem atipia.',
      'Mesotelioma bem diferenciado papilar: calretinina e D2-40 positivos.',
    ],
    molecular: 'KRAS, BRAF e NRAS (via MAPK); TP53 íntegro.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'borderline-seroso',
    name: 'Tumor seroso borderline',
    aka: ['tumor seroso de baixo potencial de malignidade', 'serous borderline tumour', 'SBT'],
    behavior: 'intermediario',
    sites: [
      { site: 'ovario', role: 'primario', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular'],
    architecture: ['papilar', 'micropapilar', 'cistico'],
    features: ['psamomas', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Tumor cístico com papilas hierárquicas ramificadas revestidas por epitélio estratificado com tufos e células descamando, atipia leve a moderada e nenhuma invasão estromal destrutiva; bilateral em um terço, e o que muda o prognóstico são os implantes peritoneais invasivos, hoje chamados de carcinoma seroso de baixo grau.',
    criteria: [
      'Proliferação epitelial acima de 10% da lesão, com estratificação, tufos e destacamento celular.',
      'Ausência de invasão estromal destrutiva (microinvasão até 5 mm é permitida).',
      'Papilas com ramificação hierárquica; o padrão micropapilar não hierárquico acima de 5 mm define a variante micropapilar.',
      'Avaliação obrigatória do peritônio: implantes invasivos são reclassificados como carcinoma seroso de baixo grau.',
      'Amostragem generosa: um bloco por centímetro no mínimo, para não perder carcinoma.',
    ],
    markers: [
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'wt1', pct: [85, 100] },
      { marker: 'er', pct: [80, 95] },
      { marker: 'pr', pct: [50, 80] },
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'p16', pct: [5, 20] },
      { marker: 'brafv600e', pct: [20, 40], note: 'mais frequente que no carcinoma de baixo grau' },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'cdx2', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Cistoadenoma seroso com proliferação focal: menos de 10% de proliferação.',
      'Carcinoma seroso de baixo grau: invasão destrutiva.',
      'Carcinoma seroso de alto grau: p53 aberrante, atipia acentuada.',
      'Endossalpingiose e cistos de inclusão: sem proliferação.',
    ],
    molecular: 'BRAF V600E e KRAS; TP53 íntegro. BRAF mutado associa-se a comportamento mais indolente.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'endometrioide-ovario',
    name: 'Carcinoma endometrioide do ovário',
    aka: ['ovarian endometrioid carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide', 'escamoso'],
    architecture: ['glandulas', 'cribriforme', 'lencois', 'papilar'],
    features: ['precursor', 'mitoses-moderadas', 'desmoplasia', 'queratinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma de glândulas confluentes semelhantes ao endométrio, muitas vezes com diferenciação escamosa e com endometriose ou endometrioma ao lado; é frequentemente sincrônico com carcinoma endometrial, e nesse caso as duas lesões costumam ser clonalmente relacionadas mas de curso indolente.',
    criteria: [
      'Glândulas confluentes de tipo endometrial, com ou sem morulas escamosas.',
      'Endometriose ou tumor endometrioide borderline adjacente apoia primário ovariano.',
      'WT1 negativo com ER positivo: é o par que o separa do seroso.',
      'Graduação FIGO pelo componente sólido e pela atipia nuclear.',
      'Instabilidade de microssatélites e β-catenina nuclear devem ser avaliadas: definem subgrupos prognósticos e o rastreio de Lynch.',
    ],
    markers: [
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'er', pct: [75, 95] },
      { marker: 'pr', pct: [60, 85] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'wt1', pct: [0, 15], note: 'o negativo que separa do seroso' },
      { marker: 'betacatenina', pct: [30, 50], pattern: 'N', note: 'reflete CTNNB1; associada a bom prognóstico' },
      { marker: 'vimentina', pct: [70, 90], note: 'positiva, ao contrário do colorretal' },
      { marker: 'p53', pct: [10, 25], note: 'aberrante em minoria, de pior prognóstico' },
      { marker: 'napsina', pct: [0, 15] },
      { marker: 'hnf1b', pct: [10, 30] },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'cdx2', pct: [5, 25], note: 'positivo nas morulas escamosas; não conclua colorretal' },
      { marker: 'satb2', pct: [0, 10] },
      { marker: 'mlh1', pct: [10, 20], note: 'o positivo é a perda; rastreio de Lynch obrigatório' },
      { marker: 'pms2', pct: [10, 20] },
      { marker: 'arid1a', pct: [20, 30], note: 'o positivo é a perda' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de adenocarcinoma colorretal: CK20, CDX2 e SATB2 positivos, ER e PAX8 negativos, vimentina negativa.',
      'Carcinoma seroso de alto grau: WT1 e p53 aberrante.',
      'Tumor de Sertoli-Leydig: inibina, SF-1 e calretinina positivos, EMA negativo.',
      'Carcinoma de células claras: HNF1β e napsina, ER negativo.',
      'Tumor endometrioide borderline: sem invasão destrutiva.',
    ],
    molecular: 'CTNNB1, PTEN, ARID1A, PIK3CA; MSI com perda de MMR em parte (rastreio de Lynch).',
    sources: [WHO, NUCCI],
  },
  {
    id: 'celulas-claras-ovario',
    name: 'Carcinoma de células claras do ovário',
    aka: ['ovarian clear cell carcinoma', 'OCCC'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['claras', 'epitelioide', 'oncocitico'],
    architecture: ['papilar', 'glandulas', 'cistico', 'trabecular'],
    features: ['tachinha', 'hialinizacao', 'glicogenio', 'mitoses-raras', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma de células claras ou em tachinha, em papilas com eixo hialinizado, túbulos e cistos, quase sempre sobre endometriose; tem poucas mitoses apesar de ser agressivo, resiste à quimioterapia com platina e associa-se a trombose e a hipercalcemia paraneoplásica.',
    criteria: [
      'Células com citoplasma claro glicogenado ou eosinofílico, núcleo em tachinha protruindo na luz.',
      'Padrões papilar (com eixo hialinizado característico), tubulocístico e sólido.',
      'HNF1β nuclear e napsina A positivas com ER, PR e WT1 negativos.',
      'p53 selvagem na maioria; o padrão aberrante deve fazer reconsiderar seroso de alto grau.',
      'Endometriose ou carcinoma de células claras borderline adjacente apoia.',
    ],
    markers: [
      { marker: 'hnf1b', pct: [85, 100] },
      { marker: 'napsina', pct: [75, 95], note: 'mais específica que o HNF1β' },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'er', pct: [0, 15], note: 'o negativo que separa de endometrioide e seroso' },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'wt1', pct: [0, 10] },
      { marker: 'p53', pct: [10, 20], note: 'selvagem na maioria' },
      { marker: 'arid1a', pct: [45, 60], note: 'o positivo é a perda; reflete ARID1A mutado' },
      { marker: 'amacr', pct: [50, 80] },
      { marker: 'caix', pct: [10, 40], note: 'não é em caixa difuso como no renal' },
      { marker: 'cd10', pct: [10, 30] },
      { marker: 'sall4', pct: [0, 10], note: 'o negativo contra tumor do saco vitelino' },
      { marker: 'glipicano3', pct: [10, 30], note: 'pode confundir com saco vitelino' },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor do saco vitelino: SALL4 e AFP positivos, ER e PAX8 negativos, em jovem.',
      'Carcinoma renal de células claras metastático: CA-IX em caixa, CD10, napsina negativa.',
      'Carcinoma seroso de alto grau com células claras: p53 aberrante, WT1 positivo.',
      'Reação de Arias-Stella e alterações gravídicas: sem massa, contexto.',
      'Disgerminoma: OCT4 e SALL4 positivos.',
    ],
    molecular: 'ARID1A e PIK3CA; associação forte com endometriose.',
    sources: [WHO, NUCCI, BLAUSTEIN],
  },
  {
    id: 'mucinoso-ovario',
    name: 'Carcinoma e tumor mucinoso do ovário',
    aka: ['cistoadenocarcinoma mucinoso', 'tumor mucinoso borderline', 'ovarian mucinous tumour'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'anel-sinete'],
    architecture: ['cistico', 'glandulas', 'papilar', 'cribriforme'],
    features: ['mucina', 'necrose', 'mitoses-moderadas'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Tumor cístico multiloculado grande e unilateral, revestido por epitélio mucinoso de tipo gástrico-intestinal, com gradação de benigno a borderline a carcinoma dentro do mesmo tumor; a primeira obrigação diante de um mucinoso ovariano é excluir metástase de apêndice, cólon, pâncreas ou estômago.',
    criteria: [
      'Amostragem generosa (um a dois blocos por centímetro): o gradiente benigno-borderline-carcinoma é regra.',
      'Invasão expansiva (confluente, acima de 5 mm) ou infiltrativa define carcinoma; a infiltrativa é pior.',
      'Características de primário: unilateral, maior que 10 cm, superfície lisa, com componente borderline ou benigno.',
      'Características de metástase: bilateral, menor que 10 cm, nodular, implantes de superfície, invasão vascular.',
      'CK7 difusa com CK20 e CDX2 focais favorece primário; o inverso favorece origem intestinal baixa.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100], note: 'difusa; o padrão CK7+/CK20 focal favorece primário ovariano' },
      { marker: 'ck20', pct: [40, 70], note: 'focal e irregular no primário; difusa favorece metástase' },
      { marker: 'cdx2', pct: [30, 60], note: 'focal no primário' },
      { marker: 'satb2', pct: [0, 15], note: 'difusa indica origem colorretal ou apendicular' },
      { marker: 'pax8', pct: [20, 50], note: 'menos que nos outros ovarianos; a negatividade não exclui' },
      { marker: 'muc5ac', pct: [80, 95] },
      { marker: 'muc2', pct: [30, 60] },
      { marker: 'er', pct: [0, 15], note: 'negativo, ao contrário dos outros carcinomas ovarianos' },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'wt1', pct: [0, 10] },
      { marker: 'p53', pct: [30, 60], note: 'aberrante no carcinoma' },
      { marker: 'her2', pct: [15, 30], note: 'amplificado em parte dos carcinomas mucinosos' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de adenocarcinoma colorretal ou apendicular: SATB2 e CK20 difusos, CK7 negativo, bilateral.',
      'Metástase de adenocarcinoma pancreatobiliar: CK7 e CK17 positivos, SMAD4 pode estar perdido.',
      'Tumor de Krukenberg: células em anel de sinete difusas com estroma reativo, bilateral.',
      'Teratoma maduro com componente mucinoso: outros tecidos presentes.',
      'Pseudomixoma peritoneal de origem apendicular: sempre procure o apêndice.',
    ],
    pitfalls: ['Um tumor mucinoso "primário" ovariano bilateral é metástase até prova em contrário.'],
    molecular: 'KRAS, TP53, CDKN2A; amplificação de ERBB2 em parte.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'tumor-brenner',
    name: 'Tumor de Brenner',
    aka: ['Brenner tumour', 'tumor de células transicionais do ovário'],
    behavior: 'benigno',
    sites: [{ site: 'ovario', role: 'primario', freq: 2 }],
    cells: ['urotelial', 'epitelioide', 'fusocelular'],
    architecture: ['ninhos', 'cistico'],
    features: ['calcificacao', 'hialinizacao', 'sulcos-inclusoes', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Ninhos bem delimitados de epitélio de tipo urotelial, com núcleos ovais de sulco longitudinal em grão de café, dentro de estroma fibroso denso frequentemente calcificado; quase sempre achado incidental e benigno, e a variante maligna é rara.',
    criteria: [
      'Ninhos sólidos ou císticos de células transicionais com núcleos de sulco longitudinal.',
      'Estroma fibromatoso denso, com calcificações grosseiras frequentes.',
      'Imunofenótipo urotelial: GATA3, p63 e uroplaquina positivos, com WT1 negativo.',
      'Borderline: proliferação papilar intracística sem invasão estromal.',
      'Maligno: invasão estromal destrutiva, atipia acentuada, com Brenner benigno ou borderline adjacente.',
    ],
    markers: [
      { marker: 'gata3', pct: [85, 100] },
      { marker: 'p63', pct: [85, 100] },
      { marker: 'p40', pct: [70, 95] },
      { marker: 'uroplaquina', pct: [40, 70] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'wt1', pct: [0, 15], note: 'o negativo que separa do seroso' },
      { marker: 'pax8', pct: [10, 40], note: 'pode ser negativo; não estranhe' },
      { marker: 'er', pct: [10, 40] },
      { marker: 'calretinina', pct: [20, 50] },
      { marker: 'inibina', pct: [10, 40], note: 'no estroma' },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma urotelial metastático: atipia, invasão, história vesical.',
      'Tumor de células transicionais seroso (hoje considerado seroso de alto grau): WT1 e p53 aberrante.',
      'Tumor de Walthard: ninhos benignos na paratuba, sem massa.',
      'Fibroma com ninhos epiteliais aprisionados: estroma dominante.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'teratoma-maduro-ovario',
    name: 'Teratoma maduro cístico do ovário',
    aka: ['cisto dermoide', 'mature cystic teratoma'],
    behavior: 'benigno',
    sites: [{ site: 'ovario', role: 'primario', freq: 3 }],
    cells: ['escamoso', 'glandular', 'cartilaginoso', 'epitelioide', 'fusocelular'],
    architecture: ['cistico', 'glandulas', 'nodular'],
    features: ['queratinizacao', 'condroide', 'calcificacao', 'mucina', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'A neoplasia ovariana mais comum na mulher jovem: cisto único cheio de sebo e pelos, revestido por epidermes com anexos, e com tecidos das três camadas germinativas no nódulo de Rokitansky; benigno, com risco pequeno de transformação escamosa em mulher mais velha.',
    criteria: [
      'Tecidos maduros de duas ou três camadas germinativas, organoides, sem atipia.',
      'Nódulo de Rokitansky é o ponto a amostrar: é onde ficam os tecidos variados e onde surge a transformação maligna.',
      'Ausência de tecido imaturo: qualquer tubo neuroepitelial imaturo graduá-o como teratoma imaturo.',
      'Ausência de GCNIS e de i(12p): ao contrário do testículo, aqui é benigno.',
      'Struma ovarii quando o tecido tireoidiano é dominante.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [90, 100], note: 'componentes epiteliais' },
      { marker: 'p40', pct: [80, 100], note: 'componente escamoso' },
      { marker: 's100', pct: [50, 90], note: 'neural e cartilagem' },
      { marker: 'gfap', pct: [40, 80], note: 'glia' },
      { marker: 'ttf1', pct: [30, 70], note: 'tireoide e respiratório' },
      { marker: 'tireoglobulina', pct: [20, 60], note: 'positiva quando há struma' },
      { marker: 'cdx2', pct: [30, 60], note: 'componente entérico' },
      { marker: 'sall4', pct: [0, 10], note: 'o negativo esperado no maduro' },
      { marker: 'oct4', pct: 0 },
      { marker: 'glipicano3', pct: [0, 5] },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'er', pct: [0, 10], note: 'o negativo que separa dos tumores epiteliais de superfície' },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'wt1', pct: [0, 10] },
      { marker: 'pax8', pct: [10, 40], note: 'só nos componentes tireoidiano e respiratório' },
      { marker: 'ck7', pct: [30, 70], note: 'componentes glandulares' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Teratoma imaturo: tubos neuroepiteliais primitivos, SALL4 positivo, em jovem.',
      'Transformação em carcinoma escamoso: atipia, invasão, p53 aberrante, em mulher mais velha.',
      'Struma ovarii e carcinoide estrumal: TTF-1 e tireoglobulina positivos.',
      'Endometrioma: revestimento endometrial, hemossiderina, sem anexos cutâneos.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'granulosa-adulto',
    name: 'Tumor de células da granulosa do tipo adulto',
    aka: ['adult granulosa cell tumour', 'AGCT'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'pequenas-redondas'],
    architecture: ['folicular', 'trabecular', 'lencois', 'ninhos', 'fasciculos'],
    features: ['call-exner', 'sulcos-inclusoes', 'hemorragia', 'mitoses-raras', 'vacuolos-lipidicos'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Tumor de cordão sexual com células pálidas de núcleo angulado e sulco longitudinal em grão de café, dispostas em microfolículos com corpos de Call-Exner; produz estrogênio (sangramento pós-menopausa, hiperplasia endometrial), recidiva tarde, e a mutação FOXL2 C134W está em quase todos.',
    criteria: [
      'Núcleos pálidos, angulados, com sulco longitudinal nítido, sem atipia significativa.',
      'Padrões microfolicular (com corpos de Call-Exner), macrofolicular, trabecular, insular, difuso e sarcomatoide.',
      'Inibina, calretinina, FOXL2 e SF-1 positivos com EMA negativo.',
      'Avaliação do endométrio: hiperplasia ou carcinoma endometrioide concomitantes são frequentes.',
      'Mutação FOXL2 C134W confirma nos casos difusos ou sarcomatoides que imitam outros tumores.',
    ],
    markers: [
      { marker: 'foxl2', pct: [85, 100] },
      { marker: 'inibina', pct: [85, 100] },
      { marker: 'calretinina', pct: [80, 95] },
      { marker: 'sf1', pct: [90, 100] },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'wt1', pct: [80, 95] },
      { marker: 'ema', pct: [0, 10], note: 'o negativo que separa de carcinoma endometrioide' },
      { marker: 'ae1ae3', pct: [30, 60], note: 'fraca, em dot' },
      { marker: 'ck7', pct: [0, 15] },
      { marker: 'pax8', pct: [0, 15] },
      { marker: 'er', pct: [30, 70] },
      { marker: 'pr', pct: [70, 95] },
      { marker: 'sall4', pct: [0, 5] },
      { marker: 'p53', pct: [0, 10], note: 'selvagem; aberrante indica transformação' },
      { marker: 'ki67', pct: [2, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma endometrioide com padrão de cordão sexual: EMA e CK7 positivos, inibina negativa.',
      'Tumor de células da granulosa juvenil: núcleos redondos sem sulco, luteinizado, em criança.',
      'Carcinoide insular: cromogranina e sinaptofisina difusos.',
      'Carcinoma de pequenas células hipercalcêmico: BRG1 perdido, em jovem, com hipercalcemia.',
      'Tumor de Sertoli-Leydig: túbulos de Sertoli com células de Leydig no estroma.',
    ],
    molecular: 'FOXL2 C134W em mais de 90%; a ausência deve fazer reconsiderar o diagnóstico.',
    sources: [WHO, NUCCI, BLAUSTEIN],
  },
  {
    id: 'granulosa-juvenil',
    name: 'Tumor de células da granulosa do tipo juvenil',
    aka: ['juvenile granulosa cell tumour', 'JGCT'],
    behavior: 'intermediario',
    sites: [
      { site: 'ovario', role: 'primario', freq: 1 },
      { site: 'testiculo', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'claras', 'oncocitico'],
    architecture: ['folicular', 'lencois', 'nodular'],
    features: ['mitoses-altas', 'estroma-mixoide', 'hemorragia'],
    ages: ['crianca', 'jovem'],
    summary: 'Tumor de criança e adolescente que causa pseudopuberdade precoce isossexual, com folículos irregulares de tamanhos variados cheios de secreção basofílica, revestidos por células luteinizadas de citoplasma abundante e núcleo redondo sem sulco; mitoses são numerosas e não indicam malignidade.',
    criteria: [
      'Folículos de forma e tamanho irregulares, com conteúdo mucinoso basofílico.',
      'Células com citoplasma eosinofílico ou vacuolado (luteinização) e núcleos redondos hipercromáticos sem sulco.',
      'Mitoses frequentes e atipia focal são esperadas e não indicam malignidade.',
      'Inibina, calretinina, SF-1 e FOXL2 positivos.',
      'Quase sempre estádio I e curável; recidivas, quando ocorrem, são precoces (ao contrário do tipo adulto).',
    ],
    markers: [
      { marker: 'inibina', pct: [85, 100] },
      { marker: 'calretinina', pct: [80, 95] },
      { marker: 'sf1', pct: [85, 100] },
      { marker: 'foxl2', pct: [60, 90], note: 'a proteína marca, mas a mutação C134W está ausente' },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'wt1', pct: [70, 95] },
      { marker: 'ema', pct: [0, 10] },
      { marker: 'ae1ae3', pct: [20, 50] },
      { marker: 'sall4', pct: [0, 5], note: 'o negativo que separa de germinativo' },
      { marker: 'oct4', pct: 0 },
      { marker: 'brg1', pct: [0, 5], note: 'retido; a perda define carcinoma de pequenas células hipercalcêmico' },
      { marker: 'pr', pct: [60, 90] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma de pequenas células do ovário de tipo hipercalcêmico: BRG1 perdido, hipercalcemia, agressivo.',
      'Tumor de células da granulosa do adulto: sulcos nucleares, Call-Exner, FOXL2 mutado.',
      'Tumor do saco vitelino: SALL4, AFP e glipicano-3.',
      'Luteoma da gravidez: sem massa neoplásica verdadeira, contexto gestacional.',
    ],
    molecular: 'GNAS e AKT1 (duplicações em tandem); sem FOXL2 C134W.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'sertoli-leydig',
    name: 'Tumor de Sertoli-Leydig',
    aka: ['androblastoma', 'Sertoli-Leydig cell tumour', 'SLCT'],
    behavior: 'intermediario',
    sites: [{ site: 'ovario', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'fusocelular', 'oncocitico'],
    architecture: ['glandulas', 'trabecular', 'lobular', 'fasciculos'],
    features: ['estroma-mixoide', 'mitoses-moderadas', 'condroide'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Tumor de cordão sexual de mulher jovem com virilização, feito de túbulos de Sertoli imersos em estroma fibroso com ninhos de células de Leydig eosinofílicas; a graduação por diferenciação governa o prognóstico, e os pouco diferenciados com elementos heterólogos carregam mutação de DICER1, que exige rastreio familiar.',
    criteria: [
      'Túbulos ou cordões de células de Sertoli com células de Leydig no estroma entre eles.',
      'Graduação em bem, moderadamente e pouco diferenciado (sarcomatoide), que é o principal fator prognóstico.',
      'Elementos heterólogos (epitélio mucinoso intestinal, cartilagem, músculo esquelético) ocorrem nos moderados e pouco diferenciados.',
      'Inibina, calretinina, SF-1, FOXL2 e WT1 positivos com EMA negativo.',
      'Pesquisa de DICER1 nos moderados e pouco diferenciados, com encaminhamento genético.',
    ],
    markers: [
      { marker: 'inibina', pct: [85, 100] },
      { marker: 'calretinina', pct: [70, 95] },
      { marker: 'sf1', pct: [90, 100] },
      { marker: 'foxl2', pct: [60, 90] },
      { marker: 'wt1', pct: [70, 95] },
      { marker: 'cd56', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [40, 80], note: 'nos túbulos de Sertoli' },
      { marker: 'ema', pct: [0, 10], note: 'o negativo contra carcinoma endometrioide' },
      { marker: 'ck7', pct: [0, 20] },
      { marker: 'pax8', pct: [0, 15] },
      { marker: 'er', pct: [10, 40] },
      { marker: 'ar', pct: [50, 90] },
      { marker: 'sall4', pct: [0, 10] },
      { marker: 'ki67', pct: [5, 30] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma endometrioide de padrão sertoliforme: EMA e CK7 positivos, inibina negativa.',
      'Tumor de células da granulosa: sulcos nucleares, Call-Exner, FOXL2 mutado.',
      'Carcinoide trabecular: cromogranina e sinaptofisina.',
      'Tumor de Wolff (tumor do ligamento largo): CD10 e calretinina, sem células de Leydig.',
    ],
    molecular: 'DICER1 (hotspot do domínio RNase IIIb) nos moderados e pouco diferenciados; FOXL2 C134W nos de tipo retiforme raro.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'fibroma-tecoma',
    name: 'Fibroma e tecoma do ovário',
    aka: ['fibroma ovariano', 'tecoma', 'fibrotecoma', 'fibrothecoma'],
    behavior: 'benigno',
    sites: [{ site: 'ovario', role: 'primario', freq: 3 }],
    cells: ['fusocelular', 'epitelioide', 'claras'],
    architecture: ['fasciculos', 'storiforme', 'nodular'],
    features: ['hialinizacao', 'vacuolos-lipidicos', 'calcificacao', 'mitoses-raras', 'estroma-mixoide'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Massa sólida branca e firme feita de células fusiformes em fascículos entrelaçados com colágeno, no fibroma, ou de células pálidas ricas em lipídio produtoras de estrogênio, no tecoma; é a causa da síndrome de Meigs, e o fibroma celular com mais mitoses entra na categoria de baixo potencial.',
    criteria: [
      'Fibroma: células fusiformes uniformes em fascículos, colágeno abundante, até 3 mitoses por 10 campos.',
      'Fibroma celular: densamente celular com 4 ou mais mitoses; considerado de potencial maligno incerto.',
      'Tecoma: células pálidas ovaladas com citoplasma lipídico, hialinização em placas, com efeito estrogênico clínico.',
      'Inibina, calretinina e SF-1 positivos, o que confirma linhagem estromal ovariana.',
      'Fibromas múltiplos e bilaterais em jovem levantam síndrome de Gorlin.',
    ],
    markers: [
      { marker: 'inibina', pct: [50, 85], note: 'mais forte no tecoma que no fibroma' },
      { marker: 'calretinina', pct: [50, 85] },
      { marker: 'sf1', pct: [70, 95] },
      { marker: 'foxl2', pct: [60, 90] },
      { marker: 'wt1', pct: [60, 90] },
      { marker: 'cd56', pct: [50, 85] },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'sma', pct: [20, 50] },
      { marker: 'desmina', pct: [10, 40], note: 'difusa favorece leiomioma' },
      { marker: 'caldesmon', pct: [0, 20], note: 'positivo favorece leiomioma' },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'er', pct: [30, 70] },
      { marker: 'pr', pct: [50, 90] },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'ck7', pct: 0, note: 'o negativo que separa dos carcinomas de superfície' },
      { marker: 'pax8', pct: [0, 15] },
      { marker: 'p53', pct: [0, 10], note: 'selvagem' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Leiomioma ovariano: desmina e h-caldesmon difusos, inibina negativa.',
      'Tumor estromal esclerosante: pseudolobular com vasos hemangiopericitoides, em jovem.',
      'Fibrossarcoma ovariano: atipia acentuada, mais de 4 mitoses com atipia, necrose.',
      'Tumor de Brenner com estroma dominante: ninhos epiteliais GATA3 positivos.',
      'Metástase de GIST ou de tumor fusocelular: DOG1, CD117.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'sccoht',
    name: 'Carcinoma de pequenas células do ovário de tipo hipercalcêmico',
    aka: ['SCCOHT', 'small cell carcinoma of the ovary, hypercalcaemic type', 'tumor rabdoide ovariano'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 1 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'rabdoide', 'epitelioide'],
    architecture: ['lencois', 'folicular', 'ninhos'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos'],
    ages: ['crianca', 'jovem'],
    sex: 'f',
    summary: 'Tumor de mulher jovem com hipercalcemia paraneoplásica, feito de lençóis de células pequenas com espaços foliculares e, em parte dos casos, células rabdoides grandes; a perda de BRG1 (SMARCA4) define a entidade, e o prognóstico é sombrio.',
    criteria: [
      'Idade jovem (média de 24 anos) com hipercalcemia em cerca de dois terços.',
      'Lençóis difusos de células pequenas com espaços foliculares contendo material eosinofílico.',
      'Perda completa de BRG1 (SMARCA4) nas células tumorais com controle interno retido: é o critério definidor.',
      'Componente rabdoide ou de células grandes em parte dos casos.',
      'Encaminhamento genético: mutação germinativa de SMARCA4 em porção significativa (síndrome de predisposição a tumor rabdoide).',
    ],
    markers: [
      { marker: 'brg1', pct: [90, 100], note: 'o positivo é a perda; critério definidor' },
      { marker: 'ini1', pct: [0, 10], note: 'retido na maioria' },
      { marker: 'ae1ae3', pct: [70, 95], note: 'focal ou em dot' },
      { marker: 'ema', pct: [40, 70] },
      { marker: 'wt1', pct: [40, 80] },
      { marker: 'p53', pct: [10, 30], note: 'selvagem na maioria' },
      { marker: 'inibina', pct: [0, 15], note: 'o negativo que separa de granulosa juvenil' },
      { marker: 'calretinina', pct: [10, 40] },
      { marker: 'sf1', pct: [0, 20] },
      { marker: 'foxl2', pct: [0, 15] },
      { marker: 'sall4', pct: [0, 15] },
      { marker: 'oct4', pct: [0, 5] },
      { marker: 'sinaptofisina', pct: [10, 40], note: 'focal; não é neuroendócrino verdadeiro' },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [70, 100] },
    ],
    mimics: [
      'Tumor de células da granulosa juvenil: inibina e SF-1 positivos, BRG1 retido, bom prognóstico.',
      'Disgerminoma: OCT4 e SALL4 positivos.',
      'Linfoma: CD45 positivo.',
      'Carcinoma neuroendócrino de pequenas células pulmonar-símile: TTF-1, sinaptofisina difusa, BRG1 retido.',
      'Tumor desmoplásico de pequenas células redondas: desmina em dot, WT1 C-terminal.',
    ],
    molecular: 'Inativação bialélica de SMARCA4; germinativa em parte considerável dos casos.',
    sources: [WHO, NUCCI, 'Witkowski et al., Nat Genet (2014), SMARCA4 no SCCOHT'],
  },
  {
    id: 'stic',
    name: 'Carcinoma intraepitelial tubário seroso (STIC)',
    aka: ['STIC', 'serous tubal intraepithelial carcinoma'],
    behavior: 'intermediario',
    sites: [{ site: 'tuba', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'glandular'],
    architecture: ['infiltrativo'],
    features: ['mitoses-altas', 'nucleolo', 'tachinha', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Lesão plana ou levemente elevada na fímbria, com epitélio estratificado de células atípicas de núcleo grande e nucléolo, perda de cílios e perda da polaridade, sem invasão; é a precursora do carcinoma seroso de alto grau, e o diagnóstico exige p53 aberrante com Ki-67 elevado.',
    criteria: [
      'Localização na fímbria, examinada pelo protocolo SEE-FIM com corte seriado.',
      'Atipia nuclear inequívoca em epitélio estratificado, com perda de células ciliadas.',
      'p53 aberrante (difuso ou nulo) com Ki-67 acima de 10% na mesma área: os dois são exigidos.',
      'Ausência de invasão do estroma da prega.',
      'Encaminhamento para teste de BRCA na paciente e na família.',
    ],
    markers: [
      { marker: 'p53', pct: [90, 100], note: 'aberrante; exigido para o diagnóstico' },
      { marker: 'ki67', pct: [85, 100], note: 'acima de 10%, em contiguidade com a área p53 aberrante' },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'wt1', pct: [85, 100] },
      { marker: 'p16', pct: [70, 90] },
      { marker: 'er', pct: [60, 90] },
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'bcl2', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Lesão p53 signature: p53 aberrante mas sem atipia e com Ki-67 baixo.',
      'Atipia tubária reativa: p53 selvagem, cílios preservados, inflamação.',
      'Metaplasia transicional da fímbria: sem atipia.',
      'Carcinoma seroso invasor: invasão do estroma da prega.',
    ],
    sources: [WHO, NUCCI, 'Vang et al., recomendações para diagnóstico de STIC, Int J Gynecol Pathol'],
  },
  {
    id: 'krukenberg',
    name: 'Tumor de Krukenberg (metástase ovariana de carcinoma em anel de sinete)',
    aka: ['Krukenberg tumour', 'metástase ovariana gástrica'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 3 },
    ],
    cells: ['anel-sinete', 'glandular', 'fusocelular'],
    architecture: ['infiltrativo', 'lencois', 'fila-indiana'],
    features: ['mucina', 'desmoplasia', 'estroma-mixoide', 'mitoses-moderadas'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Metástase ovariana, quase sempre bilateral, de carcinoma com células em anel de sinete — estômago em primeiro lugar, depois mama lobular, apêndice e cólon —, com células isoladas dispersas num estroma ovariano celular e edemaciado que às vezes é luteinizado e produz hormônio.',
    criteria: [
      'Bilateralidade e envolvimento nodular multifocal com preservação do contorno ovariano.',
      'Células em anel de sinete isoladas ou em pequenos grupos, dentro de estroma ovariano reativo e celular.',
      'Invasão vascular no hilo e implantes de superfície apoiam metástase.',
      'Painel de origem: CK7 e CK20, CDX2, SATB2, GATA3, ER e PAX8.',
      'PAX8 negativo com CDX2 ou GATA3 positivos praticamente sela metástase.',
    ],
    markers: [
      { marker: 'pax8', pct: [0, 10], note: 'o negativo que afasta primário ovariano' },
      { marker: 'ck7', pct: [60, 90], note: 'positiva no gástrico e no mamário' },
      { marker: 'ck20', pct: [30, 60], note: 'positiva no gástrico e no colorretal' },
      { marker: 'cdx2', pct: [50, 80] },
      { marker: 'satb2', pct: [20, 50], note: 'difusa indica origem colorretal ou apendicular' },
      { marker: 'gata3', pct: [10, 30], note: 'positiva se a origem for mama lobular' },
      { marker: 'ecaderina', pct: [20, 50], note: 'perdida quando a origem é gástrico difuso ou lobular de mama' },
      { marker: 'er', pct: [10, 30], note: 'positiva na origem mamária' },
      { marker: 'wt1', pct: [0, 10] },
      { marker: 'muc5ac', pct: [50, 80] },
      { marker: 'muc2', pct: [30, 60] },
      { marker: 'inibina', pct: [0, 20], note: 'só no estroma luteinizado, não no tumor' },
      { marker: 'ki67', pct: [30, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma mucinoso primário ovariano: unilateral, grande, com componente borderline, PAX8 pode ser positivo.',
      'Tumor de células da granulosa com estroma luteinizado: inibina nas células tumorais.',
      'Carcinoma de células claras com células em anel de sinete: HNF1β e napsina.',
      'Adenocarcinoma endometrioide com muco: ER e PAX8 positivos.',
    ],
    pitfalls: ['O estroma ovariano luteinizado é inibina positivo e pode dar a falsa impressão de tumor de cordão sexual.'],
    sources: [WHO, NUCCI, BLAUSTEIN],
  },
  {
    id: 'teratoma-imaturo',
    name: 'Teratoma imaturo',
    aka: ['immature teratoma', 'teratoma imaturo do ovário'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['blastematoso', 'pequenas-redondas', 'estreladas', 'glandular', 'cartilaginoso'],
    architecture: ['rosetas', 'nodular', 'cistico'],
    features: ['mitoses-altas', 'condroide', 'necrose'],
    ages: ['crianca', 'jovem'],
    sex: 'f',
    summary: 'Teratoma com tecido embrionário imaturo, quase sempre neuroepitélio na forma de túbulos e rosetas primitivas com mitoses; a graduação conta quanto neuroepitélio há por lâmina e é o que decide quimioterapia, o que faz da amostragem generosa parte do diagnóstico.',
    criteria: [
      'Presença de tecido imaturo, na prática neuroepitélio primitivo em túbulos e rosetas com mitoses e apoptose.',
      'Graduação pelo neuroepitélio: grau 1 até um campo de pequeno aumento por lâmina, grau 2 até três, grau 3 acima disso.',
      'Amostragem generosa e dirigida às áreas sólidas e carnosas: o grau muda a conduta.',
      'Implantes peritoneais devem ser graduados à parte; gliomatose peritoneal (implantes de glia madura) não é doença maligna.',
      'Excluir componente de outro germinativo (saco vitelino, carcinoma embrionário), que muda o tratamento.',
    ],
    markers: [
      { marker: 'sall4', pct: [60, 90], note: 'no neuroepitélio imaturo; o teratoma maduro é negativo' },
      { marker: 'lin28a', pct: [50, 85] },
      { marker: 'sinaptofisina', pct: [70, 95], note: 'neuroepitélio' },
      { marker: 'gfap', pct: [60, 90], note: 'glia madura e implantes de gliomatose' },
      { marker: 's100', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [80, 100], note: 'componentes epiteliais' },
      { marker: 'cd99', pct: [20, 50] },
      { marker: 'oct4', pct: [0, 10], note: 'o negativo que separa de disgerminoma e carcinoma embrionário' },
      { marker: 'glipicano3', pct: [10, 40], note: 'difuso favorece componente de saco vitelino' },
      { marker: 'afp', pct: [10, 40] },
      { marker: 'ttf1', pct: [20, 50], note: 'componentes respiratório e tireoidiano' },
      { marker: 'cdx2', pct: [20, 50] },
      { marker: 'ki67', pct: [30, 80], note: 'concentrado no neuroepitélio imaturo' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Teratoma maduro: sem neuroepitélio imaturo, SALL4 negativo, benigno.',
      'Tumor do saco vitelino: glipicano-3 e AFP difusos, corpos de Schiller-Duval.',
      'Carcinoide e struma ovarii: componentes maduros dominantes.',
      'Gliomatose peritoneal: glia madura GFAP positiva, sem atipia nem mitoses.',
      'Tumor neuroectodérmico primitivo sobre teratoma: lençóis puros de células pequenas.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'mucinoso-borderline',
    name: 'Tumor mucinoso borderline do ovário',
    aka: ['tumor mucinoso de baixo potencial de malignidade', 'mucinous borderline tumour'],
    behavior: 'intermediario',
    sites: [{ site: 'ovario', role: 'primario', freq: 2 }],
    cells: ['glandular', 'anel-sinete'],
    architecture: ['cistico', 'glandulas', 'papilar'],
    features: ['mucina', 'mitoses-moderadas'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Cisto mucinoso grande e unilateral com proliferação epitelial de tipo gástrico-intestinal em mais de 10% da lesão, com estratificação e tufos, mas sem invasão estromal; a amostragem é o ponto crítico, porque carcinoma focal dentro de um tumor borderline é comum e muda tudo.',
    criteria: [
      'Proliferação epitelial mucinosa em mais de 10% do tumor, com estratificação de até três camadas, tufos e atipia leve a moderada.',
      'Ausência de invasão estromal: invasão expansiva confluente acima de 5 mm define carcinoma.',
      'Amostragem de um a dois blocos por centímetro, dirigida às áreas sólidas e papilares.',
      'Carcinoma intraepitelial (atipia de alto grau sem invasão) deve ser relatado à parte.',
      'Unilateralidade e tamanho grande apoiam primário; bilateral e pequeno levanta metástase.',
    ],
    markers: [
      { marker: 'ck7', pct: [85, 100], note: 'difusa; o padrão CK7 difusa com CK20 focal favorece primário' },
      { marker: 'ck20', pct: [30, 60], note: 'focal e irregular' },
      { marker: 'cdx2', pct: [20, 50], note: 'focal' },
      { marker: 'satb2', pct: [0, 15], note: 'difusa indicaria origem colorretal ou apendicular' },
      { marker: 'muc5ac', pct: [85, 100] },
      { marker: 'muc2', pct: [30, 60] },
      { marker: 'pax8', pct: [20, 50] },
      { marker: 'er', pct: [0, 15], note: 'negativo, ao contrário dos outros borderline ovarianos' },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'wt1', pct: [0, 10], note: 'o negativo que separa do seroso borderline' },
      { marker: 'p53', pct: [5, 25], note: 'aberrante levanta carcinoma intraepitelial' },
      { marker: 'p16', pct: [0, 20] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Cistadenoma mucinoso: proliferação em menos de 10%.',
      'Carcinoma mucinoso: invasão expansiva confluente ou infiltrativa.',
      'Metástase de apêndice ou cólon: bilateral, pequena, SATB2 e CK20 difusos.',
      'Teratoma maduro com componente mucinoso: outros tecidos presentes.',
      'Tumor de Brenner com componente mucinoso: ninhos transicionais GATA3 positivos.',
    ],
    molecular: 'KRAS na maioria; CDKN2A e TP53 na progressão para carcinoma.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'cistadenoma-ovario',
    name: 'Cistadenoma seroso e mucinoso do ovário',
    aka: ['cistadenoma seroso', 'cistadenoma mucinoso', 'cistadenofibroma'],
    behavior: 'benigno',
    sites: [{ site: 'ovario', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'glandular'],
    architecture: ['cistico', 'papilar'],
    features: ['mucina', 'psamomas', 'hialinizacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto', 'idoso'],
    sex: 'f',
    summary: 'O extremo benigno das duas vias epiteliais mais comuns do ovário: o seroso é revestido por epitélio tubário ciliado de camada única, e o mucinoso por epitélio colunar gástrico-intestinal alto com núcleos basais ordenados. O cistadenofibroma acrescenta estroma fibroso denso e papilas rombas.',
    criteria: [
      'Revestimento de camada única sem estratificação significativa nem tufos.',
      'Proliferação epitelial em menos de 10% da lesão: acima disso, o diagnóstico é borderline.',
      'Ausência de atipia relevante, de mitoses e de invasão do estroma.',
      'Cistadenofibroma: componente estromal fibroso proeminente com papilas de eixo largo.',
      'Amostragem proporcional ao tamanho: o borderline e o carcinoma costumam ser focais dentro de um cisto benigno.',
    ],
    markers: [
      { marker: 'pax8', pct: [85, 100], note: 'no seroso; o mucinoso marca bem menos' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'er', pct: [70, 95], note: 'no seroso; o mucinoso é negativo' },
      { marker: 'pr', pct: [50, 85] },
      { marker: 'wt1', pct: [70, 95], note: 'no seroso' },
      { marker: 'muc5ac', pct: [30, 60], note: 'no mucinoso' },
      { marker: 'ck20', pct: [10, 40], note: 'focal no mucinoso' },
      { marker: 'cdx2', pct: [10, 40] },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'p16', pct: [0, 15], note: 'focal' },
      { marker: 'calretinina', pct: [0, 20], note: 'o negativo que ajuda contra cisto de inclusão mesotelial' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor borderline: proliferação acima de 10% com tufos e estratificação.',
      'Cisto de inclusão e endossalpingiose: microscópicos, sem massa.',
      'Cisto de inclusão peritoneal mesotelial: calretinina e WT1 positivos com D2-40.',
      'Cisto folicular e corpo lúteo: revestimento de granulosa e teca luteinizada, inibina positiva.',
      'Endometrioma: revestimento endometrial com estroma CD10 positivo e hemossiderina.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'struma-ovarii',
    name: 'Struma ovarii e carcinoide estrumal',
    aka: ['struma ovarii', 'carcinoide estrumal', 'teratoma monodérmico tireoidiano'],
    behavior: 'benigno',
    sites: [{ site: 'ovario', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'glandular', 'neuroendocrino', 'oncocitico'],
    architecture: ['folicular', 'trabecular', 'ninhos', 'cistico'],
    features: ['coloide', 'mitoses-raras', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Teratoma monodérmico em que o tecido tireoidiano ocupa mais da metade da lesão, com folículos cheios de coloide idênticos aos da tireoide; pode causar tireotoxicose e, quando se mistura a um carcinoide, forma o carcinoide estrumal. A armadilha é ler TTF-1 e tireoglobulina positivos num tumor ovariano como metástase.',
    criteria: [
      'Tecido tireoidiano ocupando mais de 50% do tumor, com folículos e coloide.',
      'TTF-1 e tireoglobulina positivos confirmam, mas não indicam metástase: é tecido maduro de teratoma.',
      'Carcinoide estrumal: componente neuroendócrino trabecular íntimo com o tecido tireoidiano, com sinaptofisina e cromogranina.',
      'Struma maligno: carcinoma papilífero ou folicular surgindo no tecido tireoidiano, com os mesmos critérios da tireoide.',
      'Struma peritoneal (implantes de tecido tireoidiano maduro) é benigno, ao contrário do que o nome sugere.',
    ],
    markers: [
      { marker: 'ttf1', pct: [90, 100], note: 'num tumor ovariano, não conclua metástase de tireoide' },
      { marker: 'tireoglobulina', pct: [90, 100] },
      { marker: 'pax8', pct: [85, 100], note: 'positivo por dois motivos aqui: mülleriano e tireoidiano' },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [20, 60], note: 'no componente de carcinoide estrumal' },
      { marker: 'cromogranina', pct: [20, 55] },
      { marker: 'insm1', pct: [20, 55] },
      { marker: 'brafv600e', pct: [0, 10], note: 'positivo indica carcinoma papilífero sobre o struma' },
      { marker: 'er', pct: [0, 20] },
      { marker: 'wt1', pct: [0, 15] },
      { marker: 'inibina', pct: [0, 15], note: 'o negativo que afasta cordão sexual' },
      { marker: 'calretinina', pct: [0, 20] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase ovariana de carcinoma de tireoide: excepcional; a presença de teratoma ao redor resolve.',
      'Tumor de células da granulosa com padrão folicular: inibina e FOXL2 positivos, TTF-1 negativo.',
      'Carcinoma de células claras com padrão tubulocístico: HNF1β e napsina.',
      'Tumor de Sertoli: inibina e SF-1 positivos.',
      'Carcinoide insular puro: sem tecido tireoidiano.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'carcinossarcoma-ovario',
    name: 'Carcinossarcoma do ovário',
    aka: ['tumor mülleriano misto maligno ovariano', 'ovarian carcinosarcoma'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 1 },
      { site: 'peritoneo', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'fusocelular', 'pleomorfico', 'cartilaginoso'],
    architecture: ['papilar', 'lencois', 'fasciculos', 'glandulas'],
    features: ['necrose', 'mitoses-altas', 'condroide', 'osteoide', 'estriacoes'],
    ages: ['idoso'],
    sex: 'f',
    summary: 'Contraparte ovariana do carcinossarcoma uterino: carcinoma de alto grau, quase sempre seroso, com componente sarcomatoso e às vezes elementos heterólogos. É entendido hoje como carcinoma com transdiferenciação, é estadiado e tratado como carcinoma, e tem prognóstico pior que o do seroso de alto grau puro.',
    criteria: [
      'Componente carcinomatoso de alto grau (seroso na maioria) e componente sarcomatoso, ambos malignos.',
      'Elementos heterólogos (condrossarcoma, rabdomiossarcoma, osteossarcoma) definem a variante heteróloga.',
      'PAX8 e queratina positivos no componente epitelial, e frequentemente também no sarcomatoso.',
      'p53 aberrante nos dois componentes, o que apoia a clonalidade comum.',
      'Estadiamento e tratamento de carcinoma ovariano, não de sarcoma.',
    ],
    markers: [
      { marker: 'p53', pct: [75, 95], note: 'aberrante nos dois componentes' },
      { marker: 'pax8', pct: [60, 90] },
      { marker: 'ae1ae3', pct: [90, 100], note: 'no epitelial; focal no sarcomatoso' },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'wt1', pct: [50, 85], note: 'quando o carcinoma é seroso' },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'er', pct: [20, 50] },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 'desmina', pct: [20, 50], note: 'componente rabdomioblástico' },
      { marker: 'miogenina', pct: [20, 50] },
      { marker: 's100', pct: [20, 50], note: 'cartilagem' },
      { marker: 'p16', pct: [50, 80] },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma seroso de alto grau com áreas sólidas fusocelulares: sem sarcoma verdadeiro.',
      'Sarcoma ovariano puro: sem componente carcinomatoso, PAX8 e queratina negativos.',
      'Tumor de células da granulosa sarcomatoide: inibina e FOXL2.',
      'Teratoma imaturo com malignidade somática: em jovem, com componentes teratomatosos.',
      'Metástase de carcinossarcoma uterino: a mais comum das duas situações.',
    ],
    molecular: 'TP53 quase constante; perfil sobreposto ao do seroso de alto grau, com BRCA em parte.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'tumor-celulas-esteroides',
    name: 'Tumor de células esteroides do ovário',
    aka: ['steroid cell tumour', 'tumor de células lipídicas', 'luteoma estromal'],
    behavior: 'intermediario',
    sites: [{ site: 'ovario', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'oncocitico', 'claras'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['vacuolos-lipidicos', 'mitoses-raras', 'hemorragia', 'cristais-reinke'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Tumor de células poligonais grandes com citoplasma eosinofílico ou vacuolado por lipídio, em lençóis sem arquitetura definida, quase sempre com virilização por produção de androgênio; quando há cristais de Reinke o nome é tumor de células de Leydig, e a malignidade se define por tamanho, mitoses, necrose e hemorragia.',
    criteria: [
      'Células poligonais grandes com citoplasma eosinofílico granular ou vacuolado rico em lipídio, em lençóis difusos.',
      'Ausência de arquitetura de cordão sexual organizada (sem túbulos, sem Call-Exner).',
      'Cristais de Reinke, quando presentes, classificam como tumor de células de Leydig.',
      'Critérios de malignidade: maior que 7 cm, 2 ou mais mitoses por 10 campos, necrose, hemorragia e atipia acentuada.',
      'Perfil esteroidogênico: inibina, calretinina, SF-1 e Melan-A positivos com queratina fraca ou negativa.',
    ],
    markers: [
      { marker: 'inibina', pct: [85, 100] },
      { marker: 'calretinina', pct: [80, 95] },
      { marker: 'sf1', pct: [85, 100] },
      { marker: 'melana', pct: [70, 95], note: 'clone A103; não indica melanoma' },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [10, 40], note: 'fraca ou negativa, como no adrenocortical' },
      { marker: 'ema', pct: [0, 10], note: 'o negativo que ajuda contra carcinoma' },
      { marker: 'sinaptofisina', pct: [30, 70], note: 'positiva; não conclua neuroendócrino' },
      { marker: 'cromogranina', pct: [0, 15] },
      { marker: 'pax8', pct: [0, 15], note: 'o negativo que separa de carcinoma ovariano e renal' },
      { marker: 'caix', pct: [0, 10] },
      { marker: 'hmb45', pct: [0, 10], note: 'o negativo que separa de PEComa' },
      { marker: 'foxl2', pct: [20, 60] },
      { marker: 'ki67', pct: [1, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de carcinoma renal de células claras: PAX8 e CA-IX positivos, queratina forte.',
      'Carcinoma adrenocortical metastático: imuno praticamente idêntica; a massa adrenal decide.',
      'Luteoma da gravidez e hiperplasia estromal luteinizada: contexto gestacional, múltiplos e bilaterais.',
      'Tumor de células da granulosa luteinizado: FOXL2 mutado, Call-Exner.',
      'Carcinoma de células claras: HNF1β e napsina, queratina forte.',
    ],
    sources: [WHO, NUCCI, BLAUSTEIN],
  },
  {
    id: 'tumor-seromucinoso',
    name: 'Tumor seromucinoso do ovário',
    aka: ['seromucinous tumour', 'tumor mülleriano misto borderline', 'endocervical-like mucinous borderline'],
    behavior: 'intermediario',
    sites: [{ site: 'ovario', role: 'primario', freq: 1 }],
    cells: ['glandular', 'epitelioide', 'escamoso'],
    architecture: ['papilar', 'cistico'],
    features: ['mucina', 'eosinofilos', 'mitoses-raras', 'precursor'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Tumor associado a endometriose, com papilas hierárquicas revestidas por uma mistura de epitélio endocervical mucinoso, seroso ciliado, escamoso e eosinofílico indiferenciado, com neutrófilos no estroma das papilas; ao contrário do mucinoso intestinal, é ER e PR positivo e frequentemente bilateral.',
    criteria: [
      'Mistura de pelo menos dois tipos de epitélio mülleriano, com predomínio de endocervical mucinoso e seroso.',
      'Papilas hierárquicas com estroma edematoso e infiltrado neutrofílico, achado característico.',
      'ER e PR positivos com CK7 difusa, o oposto do mucinoso de tipo intestinal.',
      'Associação frequente com endometriose e com endometriose atípica.',
      'Graduação em benigno, borderline e carcinoma pelos mesmos critérios de proliferação e invasão dos demais epiteliais.',
    ],
    markers: [
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'er', pct: [70, 95], note: 'positivo, ao contrário do mucinoso intestinal' },
      { marker: 'pr', pct: [60, 90] },
      { marker: 'pax8', pct: [80, 95] },
      { marker: 'muc5ac', pct: [60, 90] },
      { marker: 'ck20', pct: [0, 20] },
      { marker: 'cdx2', pct: [0, 20] },
      { marker: 'satb2', pct: [0, 10] },
      { marker: 'wt1', pct: [10, 40] },
      { marker: 'p53', pct: [0, 15], note: 'selvagem' },
      { marker: 'arid1a', pct: [10, 40], note: 'o positivo é a perda; reflete a origem em endometriose' },
      { marker: 'napsina', pct: [0, 15] },
      { marker: 'ki67', pct: [5, 25] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor mucinoso de tipo intestinal: ER negativo, CK20 e CDX2 mais expressos, unilateral e grande.',
      'Tumor seroso borderline: epitélio tubário puro, WT1 forte.',
      'Tumor endometrioide borderline: glândulas endometrioides com morulas escamosas.',
      'Metástase de adenocarcinoma endocervical: p16 em bloco com HPV.',
      'Endometriose com metaplasia mucinosa: sem proliferação epitelial significativa.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'tumor-estromal-esclerosante',
    name: 'Tumor estromal esclerosante',
    aka: ['sclerosing stromal tumour', 'tumor estromal esclerosante do ovário'],
    behavior: 'benigno',
    sites: [{ site: 'ovario', role: 'primario', freq: 1 }],
    cells: ['fusocelular', 'epitelioide', 'claras'],
    architecture: ['nodular', 'hemangiopericitoma', 'lobular'],
    features: ['hialinizacao', 'vacuolos-lipidicos', 'estroma-mixoide', 'mitoses-raras'],
    ages: ['jovem'],
    sex: 'f',
    summary: 'Tumor de cordão sexual e estroma de mulher jovem, com arquitetura pseudolobular inconfundível: nódulos celulares ricamente vascularizados, com vasos hemangiopericitoides, separados por áreas hipocelulares esclerosadas. Dentro dos nódulos há células vacuoladas luteinizadas que lembram lipoblastos ou anel de sinete.',
    criteria: [
      'Pseudolobulação: alternância de nódulos celulares com áreas escleróticas hipocelulares, visível em pequeno aumento.',
      'Vascularização proeminente com vasos em galhada dentro dos nódulos.',
      'Duas populações celulares: fusiformes fibroblásticas e redondas vacuoladas luteinizadas.',
      'Ausência de atipia, de necrose e de mitoses significativas: é benigno e a ooforectomia é curativa.',
      'Idade jovem, quase sempre na segunda e terceira décadas, com irregularidade menstrual.',
    ],
    markers: [
      { marker: 'inibina', pct: [70, 95] },
      { marker: 'calretinina', pct: [70, 95] },
      { marker: 'sf1', pct: [80, 100] },
      { marker: 'foxl2', pct: [60, 90], note: 'a proteína marca, mas a mutação C134W está ausente' },
      { marker: 'wt1', pct: [60, 90] },
      { marker: 'cd56', pct: [50, 85] },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'sma', pct: [40, 80] },
      { marker: 'desmina', pct: [20, 50] },
      { marker: 'er', pct: [20, 60] },
      { marker: 'pr', pct: [40, 80] },
      { marker: 'ae1ae3', pct: [0, 10], note: 'o negativo que exclui carcinoma com anel de sinete' },
      { marker: 'ecaderina', pct: [0, 15] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor de Krukenberg: queratina positiva com anel de sinete verdadeiro, bilateral.',
      'Fibroma e tecoma: sem pseudolobulação nem rede vascular hemangiopericitoide.',
      'Tumor de células da granulosa: FOXL2 mutado, Call-Exner, sulcos nucleares.',
      'Tumor estromal microcístico: β-catenina nuclear, CD10 positivo, inibina negativa.',
      'Luteoma e hiperplasia estromal: difusos, sem nódulos.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'sctat',
    name: 'Tumor de cordão sexual com túbulos anulares (SCTAT)',
    aka: ['SCTAT', 'sex cord tumour with annular tubules'],
    behavior: 'intermediario',
    sites: [{ site: 'ovario', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'fusocelular'],
    architecture: ['rosetas', 'ninhos', 'nodular'],
    features: ['hialinizacao', 'calcificacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Tumor de cordão sexual com arquitetura única: túbulos simples ou complexos enrolados em anel ao redor de nódulos hialinos, com os núcleos dispostos na periferia e ao redor dos glóbulos centrais. Um terço ocorre na síndrome de Peutz-Jeghers, e nesses é multifocal, bilateral, calcificado e benigno.',
    criteria: [
      'Túbulos anulares: anéis de células com núcleos periféricos e antipodais ao redor de glóbulos hialinos de membrana basal.',
      'Nódulos arredondados bem delimitados, às vezes com calcificação.',
      'Associação com Peutz-Jeghers em cerca de um terço: nesses, lesão pequena, múltipla, bilateral, calcificada e benigna.',
      'Forma esporádica: unilateral, grande, com potencial maligno em cerca de 20%.',
      'Produção de estrogênio e, nos de Peutz-Jeghers, também de progesterona, com adenoma maligno do colo associado.',
    ],
    markers: [
      { marker: 'inibina', pct: [80, 100] },
      { marker: 'calretinina', pct: [70, 95] },
      { marker: 'sf1', pct: [85, 100] },
      { marker: 'foxl2', pct: [60, 90] },
      { marker: 'wt1', pct: [70, 95] },
      { marker: 'cd56', pct: [70, 95] },
      { marker: 'colageno-iv', pct: [85, 100], note: 'realça os glóbulos hialinos centrais, que são membrana basal' },
      { marker: 'ae1ae3', pct: [20, 60], note: 'fraca' },
      { marker: 'ema', pct: [0, 10], note: 'o negativo que separa de carcinoma' },
      { marker: 'er', pct: [10, 50] },
      { marker: 'pr', pct: [40, 80] },
      { marker: 'sall4', pct: [0, 5], note: 'o negativo que exclui gonadoblastoma, que também tem glóbulos hialinos' },
      { marker: 'oct4', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Gonadoblastoma: glóbulos hialinos semelhantes, mas com células germinativas OCT4 e SALL4 positivas.',
      'Tumor de células da granulosa: Call-Exner e sulcos nucleares, sem túbulos anulares.',
      'Tumor de Sertoli: túbulos ocos ou sólidos simples.',
      'Carcinoide insular e trabecular: cromogranina e sinaptofisina difusas.',
      'Adenocarcinoma endometrioide com padrão de cordão sexual: EMA e CK7 positivos.',
    ],
    molecular: 'STK11 na síndrome de Peutz-Jeghers.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'gonadoblastoma',
    name: 'Gonadoblastoma',
    aka: ['gonadoblastoma', 'neoplasia de células germinativas in situ em gônada disgenética'],
    behavior: 'intermediario',
    sites: [
      { site: 'ovario', role: 'primario', freq: 1 },
      { site: 'testiculo', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'pequenas-redondas', 'claras'],
    architecture: ['ninhos', 'rosetas', 'nodular'],
    features: ['hialinizacao', 'calcificacao', 'mitoses-moderadas'],
    ages: ['crianca', 'jovem'],
    summary: 'Tumor de gônada disgenética em paciente com cromossomo Y, feito de ninhos que misturam duas populações: células germinativas grandes tipo seminoma e células de cordão sexual pequenas que as circundam e formam rosetas ao redor de glóbulos hialinos. É o precursor do disgerminoma, e a gonadectomia profilática é a razão de reconhecê-lo.',
    criteria: [
      'Ninhos bifásicos: células germinativas OCT4 e SALL4 positivas envolvidas por células de cordão sexual inibina e SF-1 positivas.',
      'Glóbulos hialinos de membrana basal dentro dos ninhos, com calcificação frequente.',
      'Contexto de disgenesia gonadal com material do cromossomo Y: cariótipo obrigatório.',
      'Crescimento das células germinativas para fora dos ninhos indica disgerminoma invasor sobreposto, que ocorre em cerca de metade.',
      'A gônada contralateral também é de risco: a conduta é gonadectomia bilateral.',
    ],
    markers: [
      { marker: 'oct4', pct: [90, 100], note: 'nas células germinativas' },
      { marker: 'sall4', pct: [90, 100] },
      { marker: 'plap', pct: [70, 95] },
      { marker: 'cd117', pct: [70, 95] },
      { marker: 'd240', pct: [60, 90] },
      { marker: 'inibina', pct: [70, 95], note: 'nas células de cordão sexual que envolvem os ninhos' },
      { marker: 'sf1', pct: [80, 100] },
      { marker: 'calretinina', pct: [50, 85] },
      { marker: 'foxl2', pct: [40, 80] },
      { marker: 'colageno-iv', pct: [85, 100], note: 'glóbulos hialinos' },
      { marker: 'sox9', pct: [50, 85], note: 'células de Sertoli' },
      { marker: 'ae1ae3', pct: [0, 20] },
      { marker: 'ki67', pct: [10, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor de cordão sexual com túbulos anulares: glóbulos hialinos também, mas sem células germinativas OCT4 positivas.',
      'Disgerminoma e seminoma: população germinativa pura, sem ninhos bifásicos.',
      'Neoplasia de células germinativas in situ: intratubular, sem componente de cordão sexual organizado em ninhos.',
      'Tumor misto de células germinativas e cordão sexual não classificado: sem a arquitetura em ninhos e sem cromossomo Y.',
    ],
    sources: [WHO, NUCCI, 'Ulbright, Young & Amin, capítulos de tumores testiculares; Am J Surg Pathol'],
  },
  {
    id: 'fatwo',
    name: 'Tumor de provável origem wolffiana (FATWO)',
    aka: ['FATWO', 'tumor wolffiano', 'female adnexal tumour of probable Wolffian origin'],
    behavior: 'intermediario',
    sites: [
      { site: 'tuba', role: 'primario', freq: 1 },
      { site: 'ovario', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'claras'],
    architecture: ['glandulas', 'trabecular', 'cistico', 'lencois'],
    features: ['hialinizacao', 'mitoses-raras'],
    ages: ['adulto'],
    sex: 'f',
    summary: 'Tumor do ligamento largo ou do mesossalpinge, derivado de remanescentes do ducto mesonéfrico, com padrão sólido e tubular misturado a túbulos pequenos em favo de mel cheios de material eosinofílico; CD10 e calretinina positivos com EMA negativo, e o comportamento é indolente com recidivas tardias.',
    criteria: [
      'Localização no ligamento largo, mesossalpinge ou hilo ovariano, ligada anatomicamente aos remanescentes wolffianos.',
      'Padrões sólido, tubular retiforme e sieve-like (em peneira), com túbulos pequenos cheios de material eosinofílico.',
      'CD10 e calretinina positivos com EMA negativo: é o par que separa de carcinoma.',
      'Ausência de células de Leydig e de cristais de Reinke, o que o separa do Sertoli-Leydig.',
      'Comportamento indolente, mas com recidiva tardia em cerca de 10%: exige seguimento longo.',
    ],
    markers: [
      { marker: 'cd10', pct: [70, 95] },
      { marker: 'calretinina', pct: [60, 90] },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'cam52', pct: [80, 95] },
      { marker: 'ema', pct: [0, 15], note: 'o negativo que separa de carcinoma, e é o achado prático' },
      { marker: 'inibina', pct: [30, 70], note: 'positivo em parte: não separa bem do cordão sexual' },
      { marker: 'sf1', pct: [20, 60] },
      { marker: 'wt1', pct: [40, 80] },
      { marker: 'ck7', pct: [10, 40], note: 'caracteristicamente fraca ou negativa' },
      { marker: 'pax8', pct: [10, 40] },
      { marker: 'er', pct: [10, 40] },
      { marker: 'pr', pct: [30, 70] },
      { marker: 'gata3', pct: [20, 60], note: 'linhagem mesonéfrica, como no adenocarcinoma mesonéfrico' },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor de Sertoli-Leydig: células de Leydig no estroma, inibina forte.',
      'Carcinoma endometrioide de padrão sertoliforme: EMA e CK7 positivos.',
      'Adenocarcinoma mesonéfrico do colo: mesma linhagem, outro sítio, GATA3 e TTF-1.',
      'Tumor adenomatoide: canais com vacúolos, calretinina e WT1, benigno.',
      'Carcinoma de células claras: HNF1β e napsina.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'borderline-endometrioide-claras',
    name: 'Tumores borderline endometrioide e de células claras',
    aka: ['tumor endometrioide borderline', 'adenofibroma endometrioide', 'clear cell borderline tumour'],
    behavior: 'intermediario',
    sites: [{ site: 'ovario', role: 'primario', freq: 1 }],
    cells: ['glandular', 'epitelioide', 'claras', 'escamoso'],
    architecture: ['glandulas', 'cribriforme', 'cistico'],
    features: ['precursor', 'hialinizacao', 'tachinha', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Os degraus intermediários das duas vias ligadas à endometriose: glândulas endometrioides ou túbulos de células claras com atipia e proliferação dentro de um fundo adenofibromatoso, sem invasão estromal. Reconhecê-los completa o espectro dos dois carcinomas que já estão no catálogo.',
    criteria: [
      'Proliferação epitelial atípica dentro de um adenofibroma, sem invasão estromal destrutiva.',
      'Endometrioide: glândulas com atipia e arquitetura complexa, muitas vezes com morulas escamosas.',
      'Células claras: túbulos e cistos revestidos por células claras ou em tachinha com atipia, em estroma fibroso denso.',
      'Endometriose ou endometriose atípica adjacente é frequente e apoia.',
      'Microinvasão de até 5 mm é aceita; acima disso o diagnóstico é carcinoma.',
    ],
    markers: [
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'er', pct: [50, 90], note: 'positivo no endometrioide; negativo no de células claras' },
      { marker: 'pr', pct: [40, 80] },
      { marker: 'hnf1b', pct: [30, 70], note: 'no componente de células claras' },
      { marker: 'napsina', pct: [20, 60], note: 'idem' },
      { marker: 'wt1', pct: [0, 15], note: 'o negativo que separa dos serosos' },
      { marker: 'p53', pct: [0, 15], note: 'selvagem' },
      { marker: 'betacatenina', pct: [20, 50], pattern: 'N', note: 'no endometrioide' },
      { marker: 'arid1a', pct: [20, 50], note: 'o positivo é a perda; reflete a origem em endometriose' },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'cdx2', pct: [0, 20], note: 'nas morulas escamosas' },
      { marker: 'ki67', pct: [5, 25] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma endometrioide e de células claras: invasão estromal acima de 5 mm.',
      'Endometriose e endometriose atípica: sem proliferação epitelial complexa.',
      'Tumor seromucinoso borderline: epitélio misto com neutrófilos.',
      'Tumor de Brenner: ninhos transicionais GATA3 positivos.',
      'Adenofibroma sem atipia: benigno puro.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'fibrossarcoma-ovariano',
    name: 'Fibrossarcoma do ovário',
    aka: ['ovarian fibrosarcoma', 'fibroma celular de potencial maligno incerto'],
    behavior: 'maligno',
    sites: [
      { site: 'ovario', role: 'primario', freq: 1 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular'],
    architecture: ['fasciculos', 'storiforme'],
    features: ['necrose', 'mitoses-altas', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'A contraparte maligna do fibroma: proliferação fusocelular densa em fascículos, com atipia moderada a acentuada, 4 ou mais mitoses por 10 campos e muitas vezes necrose. Mantém o perfil de estroma ovariano — inibina, calretinina e SF-1 — e é isso que o separa dos sarcomas metastáticos.',
    criteria: [
      'Proliferação fusocelular densamente celular em fascículos entrelaçados.',
      'Quatro ou mais mitoses por 10 campos de grande aumento com atipia moderada a acentuada.',
      'Necrose e hemorragia frequentes; margens infiltrativas.',
      'Fibroma celular com 4 ou mais mitoses mas sem atipia é categoria intermediária, de potencial maligno incerto.',
      'Perfil de estroma ovariano preservado, o que o separa de leiomiossarcoma e de sarcoma metastático.',
    ],
    markers: [
      { marker: 'inibina', pct: [40, 80], note: 'mais fraco que no fibroma, mas costuma persistir' },
      { marker: 'calretinina', pct: [40, 80] },
      { marker: 'sf1', pct: [60, 90] },
      { marker: 'foxl2', pct: [40, 80] },
      { marker: 'wt1', pct: [50, 85] },
      { marker: 'cd56', pct: [40, 80] },
      { marker: 'vimentina', pct: [95, 100] },
      { marker: 'sma', pct: [20, 50] },
      { marker: 'desmina', pct: [0, 20], note: 'difusa favorece leiomiossarcoma' },
      { marker: 'caldesmon', pct: [0, 15] },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 'p53', pct: [20, 50] },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Fibroma e fibroma celular: sem atipia, mitoses abaixo do limiar.',
      'Leiomiossarcoma ovariano: desmina e h-caldesmon difusos.',
      'Sarcoma do estroma endometrial metastático: CD10 difuso, fusão JAZF1.',
      'Tumor de células da granulosa sarcomatoide: FOXL2 C134W mutado.',
      'Carcinossarcoma: componente carcinomatoso presente.',
    ],
    sources: [WHO, NUCCI],
  },
]
