/* ==========================================================================
   prostatetestis.ts — próstata, testículo e pênis.

   Na próstata a imuno tem duas funções e só duas: mostrar que não há camada
   basal (p63 e CK903 negativos onde as glândulas benignas seriam positivas) e
   apoiar neoplasia com AMACR. Nunca se gradua por imuno, e nunca se diagnostica
   câncer só porque o AMACR marcou. No testículo o painel é de linhagem:
   OCT4 separa seminoma e carcinoma embrionário do resto, SOX2 e CD30 apontam o
   embrionário, SOX17 e glipicano-3 o saco vitelino, e SALL4 cobre quase todos.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Urinary and Male Genital Tumours, 2022; Epstein, Prostate
   Biopsy Interpretation; Ulbright nos capítulos de testículo; recomendações
   ISUP de graduação). As fontes estão como referência de texto: as séries não
   foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Urinary and Male Genital Tumours (2022)'
const EPSTEIN = "Epstein & Netto, Biopsy Interpretation of the Prostate, 6ª ed."
const ULBRIGHT = 'Ulbright, Young & Amin, capítulos de tumores testiculares; Am J Surg Pathol'
const ISUP = 'ISUP/WHO 2014 e 2019: graduação de Gleason e grupos de grau'
const CUBILLA = 'Cubilla & Velazquez, capítulos de patologia peniana; Am J Surg Pathol'

export const prostatetestis: Tumor[] = [
  {
    id: 'adenocarcinoma-prostatico',
    name: 'Adenocarcinoma prostático acinar',
    aka: ['carcinoma de próstata', 'prostatic acinar adenocarcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'prostata', role: 'primario', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'bexiga', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide', 'claras'],
    architecture: ['glandulas', 'cribriforme', 'fila-indiana', 'lencois', 'infiltrativo'],
    features: ['nucleolo', 'perineural', 'mitoses-raras', 'necrose'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Glândulas pequenas infiltrando entre as glândulas benignas, sem camada basal, com nucléolo proeminente, citoplasma anfofílico e limites nítidos; o diagnóstico é morfológico, a imuno só confirma a ausência de basais, e o grupo de grau de Gleason é o que governa a conduta.',
    criteria: [
      'Arquitetura infiltrativa: glândulas pequenas entre glândulas maiores benignas, ou glândulas fundidas, cribriformes ou células isoladas.',
      'Ausência de camada de células basais, demonstrada por p63 e CK903 negativos nas glândulas suspeitas com controle interno positivo.',
      'Núcleo aumentado com nucléolo proeminente; nucleomegalia isolada não basta.',
      'Graduação de Gleason e grupo de grau da ISUP/WHO (1 a 5), com porcentagem do padrão 4 relatada.',
      'Invasão perineural e cribriforme ou intraductal devem ser relatados: pesam na conduta.',
    ],
    markers: [
      { marker: 'nkx31', pct: [90, 100], note: 'o mais específico de próstata; persiste melhor que o PSA no alto grau' },
      { marker: 'psa', pct: [85, 95], note: 'cai muito no alto grau e após bloqueio androgênico' },
      { marker: 'p501s', pct: [85, 95], note: 'granular perinuclear' },
      { marker: 'psap', pct: [80, 95] },
      { marker: 'psma', pct: [80, 95] },
      { marker: 'ar', pct: [90, 100] },
      { marker: 'amacr', pct: [80, 95], note: 'apoia, mas marca também adenose e adenoma nefrogênico' },
      { marker: 'p63', pct: [0, 5], note: 'a ausência é o critério; deve haver controle interno positivo' },
      { marker: 'ck903', pct: [0, 5], note: 'idem' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'gata3', pct: [0, 10], note: 'o negativo que separa de urotelial' },
      { marker: 'erg', pct: [35, 50], note: 'nuclear; reflete a fusão TMPRSS2::ERG e prova neoplasia quando positivo. A frequência varia com a população: cerca de 50% em europeus e bem menos em homens de ascendência africana', source: 'Coortes em microarranjo com ERG por imuno em torno de 34%; meta-análise de diferenças raciais em Am J Epidemiol 186:1352 (2017)' },
      { marker: 'pten', pct: [20, 40], note: 'o positivo é a perda; associada a pior prognóstico' },
      { marker: 'p53', pct: [10, 30] },
      { marker: 'ki67', pct: [2, 20] },
    ],
    mimics: [
      'Adenose (hiperplasia adenomatosa atípica): camada basal fragmentada mas presente, AMACR fraco.',
      'Atrofia parcial: citoplasma escasso, basais presentes, AMACR pode ser positivo.',
      'Adenoma nefrogênico em bexiga e uretra prostática: PAX8 positivo, NKX3.1 negativo.',
      'Carcinoma urotelial invadindo a próstata: GATA3 e p63 positivos, NKX3.1 negativo.',
      'Vesícula seminal e ducto ejaculatório: pigmento lipofuscínico, atipia degenerativa, PAX8 positivo, NKX3.1 negativo.',
    ],
    pitfalls: [
      'p63 e CK903 negativos num foco minúsculo podem ser falsos negativos por corte perdido; exija controle interno.',
      'AMACR positivo não faz diagnóstico: adenose, atrofia parcial e PIN de alto grau também marcam.',
    ],
    molecular: 'Fusão TMPRSS2::ERG em cerca de metade; perda de PTEN; SPOP; germinativas de BRCA2 com implicação terapêutica.',
    sources: [WHO, EPSTEIN, ISUP],
  },
  {
    id: 'adenocarcinoma-ductal-prostata',
    name: 'Adenocarcinoma ductal da próstata',
    aka: ['carcinoma ductal prostático', 'ductal adenocarcinoma of the prostate'],
    behavior: 'maligno',
    sites: [
      { site: 'prostata', role: 'primario', freq: 1 },
      { site: 'bexiga', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'epitelioide'],
    architecture: ['papilar', 'cribriforme', 'glandulas'],
    features: ['necrose', 'nucleolo', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Variante com papilas e cribras revestidas por epitélio colunar alto pseudoestratificado, muitas vezes centrada na uretra prostática e vista na ressecção como lesão polipoide sangrante; é graduada como Gleason 4 e tem prognóstico pior que o acinar de grau equivalente.',
    criteria: [
      'Epitélio colunar alto pseudoestratificado, com núcleos alongados, revestindo papilas com eixo fibrovascular ou cribras.',
      'Graduação como padrão 4 de Gleason; com necrose comedo, padrão 5.',
      'Marcadores prostáticos positivos confirmam a origem quando a lesão é uretral.',
      'Distinção de carcinoma intraductal: este mantém camada basal detectável por p63 e CK903.',
    ],
    markers: [
      { marker: 'nkx31', pct: [85, 100] },
      { marker: 'psa', pct: [80, 95] },
      { marker: 'p501s', pct: [80, 95] },
      { marker: 'ar', pct: [85, 100] },
      { marker: 'amacr', pct: [70, 90] },
      { marker: 'p63', pct: [0, 10], note: 'ausente no invasor; presente no intraductal' },
      { marker: 'ck903', pct: [0, 10] },
      { marker: 'ck7', pct: [30, 60], note: 'mais frequente que no acinar' },
      { marker: 'gata3', pct: [0, 10] },
      { marker: 'cdx2', pct: [0, 10], note: 'o negativo contra adenocarcinoma colorretal invadindo' },
      { marker: 'satb2', pct: [0, 10] },
      { marker: 'pten', pct: [30, 60], note: 'o positivo é a perda' },
      { marker: 'ki67', pct: [10, 40] },
    ],
    mimics: [
      'Carcinoma intraductal da próstata: camada basal presente (p63 e CK903 positivos em periferia).',
      'Carcinoma urotelial papilar de alto grau da uretra prostática: GATA3 e p63 positivos.',
      'Adenocarcinoma colorretal invadindo: CDX2 e SATB2 positivos.',
      'Pólipo uretral prostático benigno: sem atipia, camada basal presente.',
    ],
    sources: [WHO, EPSTEIN],
  },
  {
    id: 'pin-alto-grau',
    name: 'Neoplasia intraepitelial prostática de alto grau (PIN)',
    aka: ['HGPIN', 'high-grade prostatic intraepithelial neoplasia'],
    behavior: 'intermediario',
    sites: [{ site: 'prostata', role: 'primario', freq: 3 }],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'papilar', 'cribriforme'],
    features: ['nucleolo', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Glândulas prostáticas de arquitetura preservada e tamanho normal revestidas por células atípicas com núcleo aumentado e nucléolo proeminente, em padrão tufado, micropapilar, plano ou cribriforme, com camada basal ainda presente; é a lesão precursora, não é câncer, e sozinha não indica nova biópsia imediata.',
    criteria: [
      'Glândulas de calibre normal ou grande, com arquitetura benigna, revestidas por epitélio atípico.',
      'Nucleomegalia com nucléolo proeminente visível em pequeno aumento.',
      'Camada basal presente, ainda que descontínua: p63 e CK903 positivos.',
      'Padrões tufado (o mais comum), micropapilar, plano e cribriforme.',
      'PIN cribriforme extenso ou com necrose deve ser reavaliado como possível carcinoma intraductal.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'presente, ainda que descontínua: é o que separa de carcinoma' },
      { marker: 'ck903', pct: [90, 100] },
      { marker: 'amacr', pct: [50, 80], note: 'positivo; não use para diferenciar de carcinoma' },
      { marker: 'nkx31', pct: [95, 100] },
      { marker: 'psa', pct: [90, 100] },
      { marker: 'ar', pct: [95, 100] },
      { marker: 'erg', pct: [10, 20] },
      { marker: 'pten', pct: [0, 10], note: 'retido; a perda favorece carcinoma intraductal' },
      { marker: 'ki67', pct: [2, 10] },
    ],
    mimics: [
      'Carcinoma intraductal: glândulas maiores, atipia mais acentuada, necrose, PTEN perdido, ERG positivo.',
      'Adenocarcinoma cribriforme invasor: sem camada basal.',
      'Metaplasia de células transicionais e hiperplasia de células basais: sem nucléolo proeminente.',
      'Alterações por radioterapia ou bloqueio androgênico: atipia degenerativa, citoplasma vacuolizado.',
    ],
    sources: [WHO, EPSTEIN],
  },
  {
    id: 'adenose-prostatica',
    name: 'Adenose (hiperplasia adenomatosa atípica) da próstata',
    aka: ['hiperplasia adenomatosa atípica', 'adenosis', 'AAH'],
    behavior: 'benigno',
    sites: [{ site: 'prostata', role: 'primario', freq: 2 }],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'lobular'],
    features: ['mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Nódulo de glândulas pequenas e agrupadas na zona de transição, que imita carcinoma de baixo grau pelo tamanho e pela quantidade, mas mantém arranjo lobular, transição com glândulas maiores e camada basal fragmentada; nucléolo é pequeno e o citoplasma é pálido como o das glândulas vizinhas.',
    criteria: [
      'Agrupamento lobular e circunscrito de glândulas pequenas, em geral na zona de transição.',
      'Transição gradual entre glândulas pequenas e glândulas benignas maiores dentro do mesmo nódulo.',
      'Camada basal presente, ainda que fragmentada e descontínua, em pelo menos parte das glândulas.',
      'Citoplasma pálido idêntico ao das glândulas benignas vizinhas, nucléolo pequeno.',
      'Corpora amylacea e cristaloides podem estar presentes e não ajudam a separar.',
    ],
    markers: [
      { marker: 'p63', pct: [70, 95], note: 'fragmentada; a positividade em parte das glândulas é o critério' },
      { marker: 'ck903', pct: [70, 95] },
      { marker: 'amacr', pct: [10, 30], note: 'pode ser positivo e induzir ao erro; costuma ser fraco' },
      { marker: 'nkx31', pct: [95, 100] },
      { marker: 'psa', pct: [95, 100] },
      { marker: 'erg', pct: [0, 5], note: 'o negativo; positividade indicaria carcinoma' },
      { marker: 'ki67', pct: [1, 3] },
    ],
    mimics: [
      'Adenocarcinoma de grupo de grau 1: sem basais em nenhuma glândula, nucléolo proeminente, infiltrativo.',
      'Atrofia parcial: citoplasma escasso e luz irregular.',
      'Hiperplasia de células basais: camada basal espessa e sólida.',
    ],
    sources: [WHO, EPSTEIN],
  },
  {
    id: 'carcinoma-neuroendocrino-prostata',
    name: 'Carcinoma neuroendócrino da próstata',
    aka: ['carcinoma de pequenas células prostático', 'NEPC', 'carcinoma neuroendócrino de tratamento'],
    behavior: 'maligno',
    sites: [
      { site: 'prostata', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino', 'pleomorfico'],
    architecture: ['lencois', 'ninhos'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma de pequenas células da próstata, que surge de novo ou, mais frequentemente, como escape ao bloqueio androgênico prolongado em paciente com PSA baixo e doença visceral progressiva; perde AR, NKX3.1 e PSA, adquire marcadores neuroendócrinos, e perde RB1 e TP53.',
    criteria: [
      'Morfologia de pequenas células ou de carcinoma neuroendócrino de grandes células.',
      'Marcadores neuroendócrinos positivos com perda ou grande redução de AR, NKX3.1 e PSA.',
      'Contexto clínico de progressão sob bloqueio androgênico com PSA desproporcionalmente baixo.',
      'Perda de RB1 e p53 aberrante apoiam.',
      'Componente adenocarcinomatoso convencional associado deve ser relatado.',
    ],
    markers: [
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [80, 95] },
      { marker: 'cromogranina', pct: [40, 70] },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [80, 95], pattern: 'dot' },
      { marker: 'nkx31', pct: [10, 40], note: 'pode persistir e é a única pista de origem prostática' },
      { marker: 'psa', pct: [5, 25], note: 'em geral perdido' },
      { marker: 'ar', pct: [10, 30] },
      { marker: 'rb1', pct: [70, 90], note: 'o positivo é a perda' },
      { marker: 'p53', pct: [60, 90] },
      { marker: 'ttf1', pct: [30, 60], note: 'positivo sem significar pulmão' },
      { marker: 'gata3', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [70, 100] },
    ],
    mimics: [
      'Adenocarcinoma prostático de grupo de grau 5: NKX3.1 e PSA fortes, sem marcador neuroendócrino difuso.',
      'Carcinoma de pequenas células de bexiga ou pulmonar: NKX3.1 negativo, contexto clínico.',
      'Linfoma: CD45 positivo.',
      'Carcinoma urotelial de alto grau: GATA3 e p63.',
    ],
    molecular: 'Perda de RB1 e TP53; amplificação de MYCN e AURKA em parte.',
    sources: [WHO, EPSTEIN],
  },
  {
    id: 'seminoma',
    name: 'Seminoma',
    aka: ['seminoma clássico', 'disgerminoma (ovário)', 'germinoma (SNC)'],
    behavior: 'maligno',
    sites: [
      { site: 'testiculo', role: 'primario', freq: 3 },
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'retroperitoneo', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'claras', 'linfoide-grandes'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['linfoide', 'granulomas', 'glicogenio', 'nucleolo', 'mitoses-moderadas'],
    ages: ['jovem', 'adulto'],
    sex: 'm',
    summary: 'Lençóis de células grandes uniformes com citoplasma claro glicogenado, membrana nítida e nucléolo central proeminente, divididos por septos fibrosos com infiltrado linfocitário e às vezes granulomas; OCT4 e SALL4 positivos com CD30 negativo, e a neoplasia germinativa in situ nos túbulos adjacentes.',
    criteria: [
      'Células monótonas grandes com citoplasma claro e limites celulares bem definidos.',
      'Septos fibrosos com linfócitos T; granulomas em parte dos casos.',
      'OCT4 e SALL4 nucleares positivos, CD117 e D2-40 positivos, CD30 negativo.',
      'Neoplasia de células germinativas in situ (GCNIS) nos túbulos vizinhos apoia fortemente.',
      'Células sinciciotrofoblásticas isoladas com β-hCG podem existir e não fazem coriocarcinoma.',
    ],
    markers: [
      { marker: 'oct4', pct: [95, 100] },
      { marker: 'sall4', pct: [95, 100] },
      { marker: 'plap', pct: [85, 95] },
      { marker: 'cd117', pct: [85, 95] },
      { marker: 'd240', pct: [85, 95] },
      { marker: 'sox17', pct: [90, 100], note: 'positivo aqui e negativo no carcinoma embrionário' },
      { marker: 'sox2', pct: [0, 5], note: 'o negativo que separa do carcinoma embrionário' },
      { marker: 'cd30', pct: [0, 5], note: 'idem' },
      { marker: 'ae1ae3', pct: [10, 30], note: 'fraca ou em dot; forte e difusa favorece embrionário' },
      { marker: 'afp', pct: 0, note: 'positivo indicaria componente de saco vitelino' },
      { marker: 'glipicano3', pct: [0, 10] },
      { marker: 'hcg', pct: [10, 25], note: 'só em células sinciciotrofoblásticas isoladas' },
      { marker: 'prame', pct: [80, 95] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [50, 90] },
    ],
    mimics: [
      'Carcinoma embrionário: CD30 e SOX2 positivos, queratina forte, pleomorfismo maior.',
      'Linfoma testicular: CD45 e CD20 positivos, em homem mais velho, bilateral, sem GCNIS.',
      'Tumor espermatocítico: três populações celulares, sem GCNIS, OCT4 negativo, em idoso.',
      'Orquite granulomatosa: sem células neoplásicas.',
      'Metástase de melanoma: SOX10 e HMB-45.',
    ],
    pitfalls: ['O seminoma pode dar queratina focal em dot; isso não o torna carcinoma embrionário.'],
    molecular: 'Isocromossomo 12p em praticamente todos os germinativos pós-puberais; KIT mutado em parte.',
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'carcinoma-embrionario',
    name: 'Carcinoma embrionário',
    aka: ['embryonal carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'testiculo', role: 'primario', freq: 3 },
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'retroperitoneo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'pleomorfico', 'glandular'],
    architecture: ['lencois', 'papilar', 'glandulas', 'ninhos'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['jovem', 'adulto'],
    sex: 'm',
    summary: 'O componente mais primitivo e mais agressivo dos tumores germinativos mistos: lençóis e papilas de células grandes, muito pleomórficas, de núcleos sobrepostos e limites indistintos, com necrose e mitoses abundantes; CD30 e SOX2 positivos com queratina forte é o perfil.',
    criteria: [
      'Células grandes pleomórficas com núcleos vesiculosos sobrepostos e limites celulares mal definidos (ao contrário do seminoma).',
      'Padrões sólido, papilar, glandular e embrionoide, com necrose frequente.',
      'CD30 de membrana e SOX2 nuclear positivos, com OCT4 e SALL4 também positivos.',
      'SOX17 negativo: é o que o separa do seminoma junto com CD30.',
      'Quase sempre parte de tumor germinativo misto; a proporção deve ser estimada.',
    ],
    markers: [
      { marker: 'cd30', pct: [85, 100], note: 'pode ser perdido após quimioterapia' },
      { marker: 'sox2', pct: [85, 100] },
      { marker: 'oct4', pct: [95, 100] },
      { marker: 'sall4', pct: [95, 100] },
      { marker: 'ae1ae3', pct: [90, 100], note: 'forte e difusa, ao contrário do seminoma' },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'sox17', pct: [0, 10], note: 'o negativo que separa do seminoma' },
      { marker: 'cd117', pct: [10, 30] },
      { marker: 'd240', pct: [10, 30] },
      { marker: 'lin28a', pct: [80, 95] },
      { marker: 'glipicano3', pct: [10, 30], note: 'difuso favorece saco vitelino' },
      { marker: 'afp', pct: [10, 25], note: 'focal; difuso favorece saco vitelino' },
      { marker: 'hcg', pct: [5, 20] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Seminoma: CD30 e SOX2 negativos, SOX17 positivo, células uniformes.',
      'Tumor do saco vitelino sólido: glipicano-3 e AFP difusos, SOX17 positivo, CD30 negativo.',
      'Carcinoma metastático pouco diferenciado: OCT4 e SALL4 negativos.',
      'Linfoma de grandes células: CD45 positivo (CD30 pode marcar nos dois).',
    ],
    molecular: 'Isocromossomo 12p.',
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'tumor-saco-vitelino',
    name: 'Tumor do saco vitelino',
    aka: ['tumor do seio endodérmico', 'yolk sac tumour'],
    behavior: 'maligno',
    sites: [
      { site: 'testiculo', role: 'primario', freq: 3 },
      { site: 'ovario', role: 'primario', freq: 2 },
      { site: 'retroperitoneo', role: 'metastase', freq: 2 },
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'claras', 'glandular', 'estreladas'],
    architecture: ['pseudopapilar', 'glandulas', 'lencois', 'cistico', 'papilar'],
    features: ['schiller-duval', 'globulos-hialinos', 'estroma-mixoide', 'mitoses-altas'],
    ages: ['crianca', 'jovem'],
    summary: 'Tumor germinativo de arquitetura camaleônica — reticular microcística, endodérmica, papilar, sólida, hepatoide, glandular — cujos dois achados clássicos são os corpos de Schiller-Duval (glomeruloides com vaso central) e os glóbulos hialinos; AFP sérica e tecidual elevadas, e OCT4 negativo.',
    criteria: [
      'Padrão reticular microcístico frouxo é o mais comum; corpos de Schiller-Duval são específicos mas presentes em minoria.',
      'Glóbulos hialinos eosinofílicos PAS-diastase resistentes, intra e extracelulares.',
      'AFP e glipicano-3 positivos com OCT4 negativo e CD30 negativo.',
      'SALL4 e SOX17 positivos; LIN28A também.',
      'Em criança abaixo de cinco anos costuma ser puro e não ter GCNIS associada.',
    ],
    markers: [
      { marker: 'glipicano3', pct: [90, 100], note: 'mais sensível que a AFP' },
      { marker: 'afp', pct: [60, 90], note: 'irregular e focal, apesar da AFP sérica alta' },
      { marker: 'sall4', pct: [95, 100] },
      { marker: 'sox17', pct: [85, 100] },
      { marker: 'lin28a', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'oct4', pct: [0, 5], note: 'o negativo que separa de seminoma e carcinoma embrionário' },
      { marker: 'cd30', pct: [0, 5] },
      { marker: 'sox2', pct: [0, 10] },
      { marker: 'hnf1b', pct: [50, 80], note: 'cuidado: também positivo em carcinoma de células claras mülleriano' },
      { marker: 'cd117', pct: [10, 30] },
      { marker: 'heppar1', pct: [20, 50], note: 'na variante hepatoide' },
      { marker: 'ck7', pct: [10, 40] },
      { marker: 'er', pct: 0 },
      { marker: 'ki67', pct: [50, 90] },
    ],
    mimics: [
      'Carcinoma embrionário: CD30, SOX2 e OCT4 positivos.',
      'Carcinoma de células claras ovariano ou endometrial: PAX8 e ER, SALL4 negativo, em mulher mais velha.',
      'Carcinoma hepatocelular na variante hepatoide: arginase positiva, SALL4 negativo.',
      'Teratoma imaturo com glândulas: sem glipicano-3 difuso.',
    ],
    pitfalls: ['SALL4 marca também hepatoide gástrico, alguns Wilms e carcinomas; use em painel.'],
    molecular: 'Isocromossomo 12p nos pós-puberais; os pré-puberais têm perfil distinto, sem i(12p).',
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'coriocarcinoma',
    name: 'Coriocarcinoma',
    aka: ['choriocarcinoma', 'coriocarcinoma gestacional e não gestacional'],
    behavior: 'maligno',
    sites: [
      { site: 'testiculo', role: 'primario', freq: 1 },
      { site: 'utero', role: 'primario', freq: 2 },
      { site: 'placenta', role: 'primario', freq: 2 },
      { site: 'ovario', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'encefalo', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
    ],
    cells: ['trofoblastico', 'sincicial', 'pleomorfico', 'epitelioide'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['hemorragia', 'necrose', 'mitoses-altas'],
    ages: ['jovem', 'adulto'],
    summary: 'Massa hemorrágica e necrótica em que sobrevive apenas uma orla periférica de tumor bifásico: citotrofoblasto mononucleado claro em cachos, revestido por sinciciotrofoblasto multinucleado eosinofílico; β-hCG sérica altíssima, metástase pulmonar precoce e sangramento como forma de apresentação.',
    criteria: [
      'Padrão bifásico ou trifásico: citotrofoblasto, trofoblasto intermediário e sinciciotrofoblasto, em arranjo plexiforme.',
      'Hemorragia e necrose maciças com tumor viável só na periferia: amostre a borda.',
      'β-hCG forte no sinciciotrofoblasto.',
      'Ausência de vilosidades coriônicas (a presença delas indica mola ou gestação).',
      'Distinção entre gestacional e não gestacional (germinativo) tem impacto terapêutico e pode exigir genotipagem.',
    ],
    markers: [
      { marker: 'hcg', pct: [95, 100], note: 'no sinciciotrofoblasto; é o marcador definidor' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'gata3', pct: [85, 100], note: 'trofoblasto em geral' },
      { marker: 'p63', pct: [50, 80], note: 'citotrofoblasto' },
      { marker: 'inibina', pct: [70, 95] },
      { marker: 'hpl', pct: [30, 70], note: 'mais no trofoblasto intermediário' },
      { marker: 'sall4', pct: [10, 40], note: 'nos de origem germinativa' },
      { marker: 'oct4', pct: [0, 5] },
      { marker: 'cd30', pct: [0, 5] },
      { marker: 'glipicano3', pct: [70, 95] },
      { marker: 'afp', pct: [0, 10] },
      { marker: 'p16', pct: [40, 80] },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Tumor trofoblástico do sítio placentário: monofásico, hPL difuso, hCG focal, Ki-67 mais baixo.',
      'Tumor trofoblástico epitelioide: nódulos com necrose geográfica, p63 difuso, hCG focal.',
      'Carcinoma pouco diferenciado com células gigantes: hCG negativo, GATA3 conforme origem.',
      'Nódulo de sítio placentário: Ki-67 baixo, sem atipia.',
    ],
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'teratoma-pos-puberal',
    name: 'Teratoma pós-puberal',
    aka: ['teratoma maduro e imaturo do testículo', 'postpubertal-type teratoma'],
    behavior: 'maligno',
    sites: [
      { site: 'testiculo', role: 'primario', freq: 3 },
      { site: 'retroperitoneo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'escamoso', 'cartilaginoso', 'fusocelular', 'epitelioide'],
    architecture: ['cistico', 'glandulas', 'nodular'],
    features: ['queratinizacao', 'condroide', 'mucina', 'calcificacao'],
    ages: ['jovem', 'adulto'],
    sex: 'm',
    summary: 'Mistura desorganizada de tecidos das três camadas germinativas no testículo pós-puberal; ao contrário do ovário, aqui o teratoma nunca é benigno — metastatiza mesmo quando totalmente maduro, é quimiorresistente, e pode dar origem a malignidade de tipo somático.',
    criteria: [
      'Tecidos maduros ou imaturos de mais de uma camada germinativa, desorganizados, com atipia citológica frequente.',
      'GCNIS nos túbulos adjacentes e isocromossomo 12p: é isso que o define como pós-puberal e maligno.',
      'A imaturidade não muda o estadiamento nem o prognóstico no testículo, ao contrário do ovário.',
      'Pesquisa de malignidade de tipo somático (sarcoma, adenocarcinoma, PNET) dentro do teratoma, que muda a conduta.',
      'Massa residual pós-quimioterapia frequentemente é teratoma puro e deve ser ressecada.',
    ],
    markers: [
      { marker: 'sall4', pct: [20, 50], note: 'muito menos que nos outros germinativos; pode ser negativo' },
      { marker: 'oct4', pct: [0, 5] },
      { marker: 'cd30', pct: [0, 5] },
      { marker: 'glipicano3', pct: [0, 20] },
      { marker: 'ae1ae3', pct: [80, 100], note: 'nos componentes epiteliais' },
      { marker: 'cdx2', pct: [30, 60], note: 'componente entérico' },
      { marker: 'ttf1', pct: [20, 50], note: 'componente respiratório' },
      { marker: 's100', pct: [40, 80], note: 'cartilagem e neural' },
      { marker: 'gfap', pct: [20, 60], note: 'componente glial' },
      { marker: 'sinaptofisina', pct: [20, 50] },
      { marker: 'afp', pct: [0, 20] },
      { marker: 'ki67', pct: [10, 50] },
    ],
    mimics: [
      'Teratoma pré-puberal: organoide, sem GCNIS, sem i(12p), benigno.',
      'Cisto epidermoide do testículo: lesão única escamosa sem outros tecidos, benigno.',
      'Malignidade de tipo somático dentro do teratoma: sarcoma ou carcinoma expansivo puro.',
    ],
    molecular: 'Isocromossomo 12p.',
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'gcnis',
    name: 'Neoplasia de células germinativas in situ (GCNIS)',
    aka: ['GCNIS', 'neoplasia intratubular de células germinativas', 'carcinoma in situ testicular'],
    behavior: 'intermediario',
    sites: [{ site: 'testiculo', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'claras'],
    architecture: ['infiltrativo'],
    features: ['glicogenio', 'nucleolo', 'mitoses-moderadas'],
    ages: ['jovem', 'adulto'],
    sex: 'm',
    summary: 'Células germinativas atípicas grandes, de citoplasma claro glicogenado e nucléolo proeminente, alinhadas ao longo da membrana basal de túbulos com espermatogênese ausente e membrana basal espessada; é o precursor de todos os germinativos pós-puberais e está presente ao redor deles.',
    criteria: [
      'Células grandes atípicas na periferia dos túbulos seminíferos, substituindo a espermatogênese.',
      'Membrana basal tubular espessada, atrofia dos túbulos acometidos.',
      'OCT4, PLAP e SALL4 positivos, com CD117 e D2-40 também positivos.',
      'Distinção de células germinativas imaturas retidas em criança e em disgenesia gonadal exige cautela: elas também podem ser OCT4 positivas.',
      'Presença de GCNIS apoia origem germinativa numa massa metastática de origem indeterminada.',
    ],
    markers: [
      { marker: 'oct4', pct: [95, 100] },
      { marker: 'sall4', pct: [95, 100] },
      { marker: 'plap', pct: [90, 100] },
      { marker: 'cd117', pct: [85, 100] },
      { marker: 'd240', pct: [85, 100] },
      { marker: 'sox17', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [0, 15] },
      { marker: 'cd30', pct: [0, 5] },
      { marker: 'sox2', pct: [0, 5] },
      { marker: 'prame', pct: [80, 95] },
      { marker: 'ki67', pct: [40, 80] },
    ],
    mimics: [
      'Células de Sertoli reativas e túbulos atróficos: OCT4 negativo, SOX9 e inibina positivos.',
      'Espermatogônias normais: distribuídas regularmente, OCT4 negativo.',
      'Extensão intratubular de seminoma: preenche a luz tubular.',
    ],
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'tumor-espermatocitico',
    name: 'Tumor espermatocítico',
    aka: ['seminoma espermatocítico', 'spermatocytic tumour'],
    behavior: 'intermediario',
    sites: [{ site: 'testiculo', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'pequenas-redondas', 'gigantes'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['mitoses-moderadas', 'hemorragia'],
    ages: ['idoso', 'adulto'],
    sex: 'm',
    summary: 'Tumor de homem mais velho, exclusivo do testículo, com três populações celulares na mesma lâmina — pequenas linfócito-símiles, intermediárias e gigantes com cromatina em fios de espirema —, sem infiltrado linfoide, sem GCNIS e sem relação com os outros germinativos; comporta-se de modo benigno salvo se houver sarcoma.',
    criteria: [
      'Três populações celulares: pequena (6 a 8 µm), intermediária (15 a 20 µm) e gigante mononucleada ou binucleada.',
      'Cromatina filamentosa em espirema nas células intermediárias e grandes.',
      'Ausência de estroma linfoide, de granulomas e de GCNIS.',
      'OCT4, SALL4 e PLAP negativos ou apenas focais: o perfil imuno é o oposto do seminoma.',
      'Componente sarcomatoso, quando presente, muda o prognóstico radicalmente.',
    ],
    markers: [
      { marker: 'oct4', pct: [0, 5], note: 'o negativo que o separa do seminoma' },
      { marker: 'plap', pct: [0, 20], note: 'focal quando presente' },
      { marker: 'sall4', pct: [30, 70], note: 'pode ser positivo; não exclui' },
      { marker: 'cd117', pct: [50, 85] },
      { marker: 'd240', pct: [0, 15] },
      { marker: 'ae1ae3', pct: [0, 15] },
      { marker: 'cd30', pct: [0, 5] },
      { marker: 'afp', pct: 0 },
      { marker: 'hcg', pct: 0 },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [20, 60] },
    ],
    mimics: [
      'Seminoma clássico: OCT4 positivo, população única, estroma linfoide, GCNIS.',
      'Linfoma: CD45 positivo, intersticial.',
      'Tumor de células germinativas misto: outros componentes presentes.',
    ],
    molecular: 'Ganho do cromossomo 9; sem isocromossomo 12p, ao contrário dos demais germinativos.',
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'tumor-leydig',
    name: 'Tumor de células de Leydig',
    aka: ['Leydig cell tumour', 'tumor de células intersticiais'],
    behavior: 'intermediario',
    sites: [
      { site: 'testiculo', role: 'primario', freq: 2 },
      { site: 'ovario', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'oncocitico', 'claras'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['cristais-reinke', 'vacuolos-lipidicos', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Nódulo bem delimitado castanho-amarelado de células poligonais com citoplasma eosinofílico abundante, lipídio e, em cerca de um terço, cristais de Reinke em bastonete; costuma se manifestar por ginecomastia ou puberdade precoce, e a malignidade é rara e definida por tamanho, atipia, necrose e invasão.',
    criteria: [
      'Células poligonais com citoplasma eosinofílico granular abundante, núcleo redondo com nucléolo pequeno.',
      'Cristais de Reinke, quando presentes, são patognomônicos (presentes em cerca de um terço).',
      'Inibina, calretinina, SF-1 e Melan-A positivos com queratina negativa ou fraca.',
      'Critérios de malignidade: maior que 5 cm, atipia acentuada, mais de 3 mitoses por 10 campos, necrose, invasão vascular ou margem infiltrativa.',
      'Distinção do nódulo de células de Leydig hiperplásico e do tumor de restos adrenais em hiperplasia adrenal congênita.',
    ],
    markers: [
      { marker: 'inibina', pct: [85, 100] },
      { marker: 'calretinina', pct: [80, 95] },
      { marker: 'sf1', pct: [85, 100] },
      { marker: 'melana', pct: [70, 90], note: 'clone A103' },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [10, 40], note: 'fraca ou negativa' },
      { marker: 'sall4', pct: [0, 5], note: 'o negativo que separa de germinativo' },
      { marker: 'oct4', pct: [0, 5] },
      { marker: 'plap', pct: [0, 10] },
      { marker: 'sinaptofisina', pct: [30, 70], note: 'não conclua neuroendócrino' },
      { marker: 'cromogranina', pct: [0, 15] },
      { marker: 'ar', pct: [50, 90] },
      { marker: 'ki67', pct: [1, 10] },
    ],
    mimics: [
      'Tumor de restos adrenais testiculares: múltiplos, bilaterais, em hiperplasia adrenal congênita; imuno sobreposta.',
      'Seminoma: OCT4 e SALL4 positivos.',
      'Tumor de células de Sertoli: SOX9 e queratina mais fortes, arquitetura tubular.',
      'Malacoplaquia e orquite: corpos de Michaelis-Gutmann, CD68.',
    ],
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'tumor-sertoli',
    name: 'Tumor de células de Sertoli',
    aka: ['Sertoli cell tumour', 'tumor de células de Sertoli de células grandes calcificante'],
    behavior: 'intermediario',
    sites: [
      { site: 'testiculo', role: 'primario', freq: 1 },
      { site: 'ovario', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'claras', 'oncocitico', 'fusocelular'],
    architecture: ['glandulas', 'ninhos', 'trabecular', 'lencois'],
    features: ['hialinizacao', 'calcificacao', 'mitoses-raras', 'vacuolos-lipidicos'],
    ages: ['jovem', 'adulto'],
    summary: 'Tumor de cordão sexual com túbulos ocos ou sólidos e cordões de células colunares pálidas ou vacuoladas dentro de estroma hialinizado; a variante de células grandes calcificante ocorre em jovens e faz parte do complexo de Carney, e a malignidade é definida por tamanho, mitoses, necrose e invasão.',
    criteria: [
      'Túbulos, cordões e ninhos de células com citoplasma pálido a vacuolado, em estroma hialinizado.',
      'Inibina, calretinina, SF-1 e WT1 positivos; SOX9 e queratina também.',
      'Variante de células grandes calcificante: calcificações grosseiras laminadas, células grandes eosinofílicas, associação com complexo de Carney (PRKAR1A).',
      'Critérios de malignidade: maior que 5 cm, mitoses acima de 5 por 10 campos, necrose, atipia acentuada, invasão vascular.',
      'Distinção de hiperplasia de células de Sertoli e de adenoma tubular em criptorquidia.',
    ],
    markers: [
      { marker: 'inibina', pct: [60, 90] },
      { marker: 'calretinina', pct: [50, 85] },
      { marker: 'sf1', pct: [85, 100] },
      { marker: 'wt1', pct: [70, 95] },
      { marker: 'foxl2', pct: [50, 85] },
      { marker: 'sox9', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [60, 90], note: 'mais forte que no Leydig' },
      { marker: 'ema', pct: [0, 15], note: 'o negativo que ajuda contra carcinoma metastático' },
      { marker: 'betacatenina', pct: [30, 70], pattern: 'N', note: 'nuclear no subtipo CTNNB1-mutado' },
      { marker: 'sall4', pct: [0, 5] },
      { marker: 'oct4', pct: [0, 5] },
      { marker: 'melana', pct: [10, 40] },
      { marker: 'ki67', pct: [1, 10] },
    ],
    mimics: [
      'Seminoma com padrão tubular: OCT4 e SALL4 positivos.',
      'Tumor de células de Leydig: sem túbulos, cristais de Reinke, queratina fraca.',
      'Metástase de adenocarcinoma prostático: NKX3.1 e EMA positivos, inibina negativa.',
      'Adenoma da rete testis e hiperplasia de Sertoli: sem massa, arquitetura preservada.',
    ],
    molecular: 'CTNNB1 em parte dos esclerosantes; PRKAR1A no complexo de Carney (variante calcificante).',
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'tumor-adenomatoide',
    name: 'Tumor adenomatoide',
    aka: ['adenomatoid tumour', 'mesotelioma adenomatoide benigno'],
    behavior: 'benigno',
    sites: [
      { site: 'testiculo', role: 'primario', freq: 2 },
      { site: 'utero', role: 'primario', freq: 2 },
      { site: 'tuba', role: 'primario', freq: 2 },
      { site: 'adrenal', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'claras'],
    architecture: ['glandulas', 'cistico', 'trabecular', 'infiltrativo'],
    features: ['hialinizacao', 'mitoses-raras', 'linfoide'],
    ages: ['jovem', 'adulto'],
    summary: 'Nódulo pequeno e firme do epidídimo ou do miométrio, feito de canais, fendas e túbulos revestidos por células mesoteliais achatadas ou cuboides com vacúolos citoplasmáticos que dão aspecto de anel de sinete, dentro de estroma fibroso ou muscular; benigno, e o erro perigoso é chamar de adenocarcinoma.',
    criteria: [
      'Canais anastomosantes e vacúolos intracitoplasmáticos grandes que deslocam o núcleo.',
      'Imunofenótipo mesotelial: calretinina, WT1, D2-40 e CK5/6 positivos.',
      'Ausência de atipia, de necrose e de mitoses significativas.',
      'Aspecto pseudoinfiltrativo entre fibras musculares é esperado e não indica malignidade.',
      'MOC-31, BerEP4 e CEA negativos afastam adenocarcinoma.',
    ],
    markers: [
      { marker: 'calretinina', pct: [90, 100] },
      { marker: 'wt1', pct: [85, 100] },
      { marker: 'd240', pct: [85, 100] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'moc31', pct: [0, 10], note: 'o negativo que afasta adenocarcinoma' },
      { marker: 'berep4', pct: [0, 10] },
      { marker: 'cea', pct: [0, 5] },
      { marker: 'cd31', pct: [0, 5], note: 'o negativo que afasta tumor vascular' },
      { marker: 'erg', pct: [0, 5] },
      { marker: 'desmina', pct: [10, 40] },
      { marker: 'ki67', pct: [1, 3] },
    ],
    mimics: [
      'Adenocarcinoma metastático com anel de sinete: MOC-31 e BerEP4 positivos, atipia.',
      'Mesotelioma maligno da túnica vaginal: atipia, invasão franca, massa maior, BAP1 pode ser perdido.',
      'Linfangioma e hemangioma: CD31 e ERG positivos.',
      'Leiomioma com degeneração: desmina difusa, calretinina negativa.',
    ],
    molecular: 'Mutação de TRAF7 na maioria.',
    sources: [WHO, ULBRIGHT],
  },
  {
    id: 'cec-peniano',
    name: 'Carcinoma de células escamosas do pênis',
    aka: ['carcinoma peniano', 'penile squamous cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'penis', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['escamoso', 'basaloide', 'epitelioide'],
    architecture: ['ninhos', 'infiltrativo', 'papilar'],
    features: ['queratinizacao', 'desmoplasia', 'perineural', 'precursor', 'mitoses-altas'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma escamoso da glande e do prepúcio, separado em dois grupos com prognóstico e precursor distintos: os associados ao HPV (basaloide e condilomatoso, p16 em bloco) e os não associados (queratinizante usual, verrucoso, papilar, sobre líquen escleroso).',
    criteria: [
      'Invasão do estroma por epitélio escamoso maligno, com medida da profundidade e do nível anatômico (lâmina própria, corpo esponjoso, corpo cavernoso).',
      'Classificação em HPV-associado e não associado, com p16 em bloco como substituto aceito.',
      'Neoplasia intraepitelial peniana adjacente (diferenciada nos HPV-negativos, basaloide ou verrucosa nos HPV-positivos).',
      'Invasão perineural e linfovascular e o grau são os principais preditores de metástase inguinal.',
      'O verrucoso puro não metastatiza e tem base expansiva empurrada.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p16', pct: [30, 50], note: 'em bloco nos HPV-associados (basaloide e condilomatoso)' },
      { marker: 'p53', pct: [40, 65], note: 'aberrante nos HPV-negativos, sobre líquen escleroso' },
      { marker: 'ck7', pct: [5, 20] },
      { marker: 'gata3', pct: [20, 50], note: 'pode ser positivo; não use contra urotelial isoladamente' },
      { marker: 'uroplaquina', pct: [0, 10] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [50, 90] },
    ],
    mimics: [
      'Carcinoma urotelial da uretra com diferenciação escamosa: GATA3 e uroplaquina, CIS urotelial.',
      'Doença de Paget extramamária do pênis: CK7 e GATA3 positivos, p40 negativo.',
      'Melanoma amelanótico: SOX10 positivo.',
      'Condiloma acuminado gigante: sem invasão destrutiva, coilocitose.',
      'Pseudohiperplasia epitelial em líquen escleroso: sem atipia, sem desmoplasia.',
    ],
    molecular: 'HPV de alto risco (16 e 6/11 nos condilomatosos) em cerca de metade; TP53 e CDKN2A nos HPV-negativos.',
    sources: [WHO, CUBILLA],
  },
]
