/* ==========================================================================
   salivarythyroid.ts — glândulas salivares, tireoide e paratireoide.

   Nas salivares a imuno raramente faz o diagnóstico sozinha: a arquitetura e
   o padrão bifásico (ductal mais mioepitelial) fazem, e os anticorpos de
   fusão (PLAG1, MYB, NR4A3, pan-TRK) confirmam. Na tireoide a pergunta é
   outra: primeiro se é folicular ou medular (tireoglobulina contra
   calcitonina), depois se o pouco diferenciado ou o anaplásico ainda guarda
   linhagem tireoidiana (PAX8 sobrevive quando TTF-1 e tireoglobulina somem).

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Head and Neck Tumours, 2022, capítulos de salivares e de
   tireoide; Seethala, Salivary Gland Cytopathology and Surgical Pathology;
   séries de Am J Surg Pathol, Head Neck Pathol e Thyroid). As fontes estão
   como referência de texto: as séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Head and Neck Tumours (2022)'
const SEETHALA = 'Seethala & Griffith, capítulos de patologia de glândulas salivares, Surg Pathol Clin'
const LIVOLSI = "LiVolsi & Baloch, capítulos de patologia da tireoide; Rosai and Ackerman's Surgical Pathology, tireoide"

export const salivarythyroid: Tumor[] = [
  {
    id: 'adenoma-pleomorfico',
    name: 'Adenoma pleomórfico',
    aka: ['tumor misto benigno', 'pleomorphic adenoma'],
    behavior: 'benigno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 3 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'glandular', 'estreladas', 'plasmocitoide'],
    architecture: ['glandulas', 'ninhos', 'trabecular'],
    features: ['condroide', 'estroma-mixoide', 'hialinizacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'O tumor salivar mais comum: ductos verdadeiros de duas camadas mergulhados em estroma mixocondroide que nasce das próprias células mioepiteliais, com transição gradual entre epitélio, mioepitélio e matriz; a cápsula é fina e incompleta, e é por isso que a enucleação recidiva.',
    criteria: [
      'Três componentes obrigatórios em proporção variável: epitélio ductal, mioepitélio e estroma mixoide ou condroide.',
      'Transição suave entre as células mioepiteliais e a matriz, sem limite abrupto.',
      'Ductos de duas camadas: luminal com queratinas de baixo peso, abluminal mioepitelial com p63, calponina e S100.',
      'Ausência de invasão franca, necrose e mitoses atípicas; a presença delas levanta carcinoma ex-adenoma pleomórfico.',
      'PLAG1 nuclear confirma em material escasso ou em padrão celular atípico.',
    ],
    markers: [
      { marker: 'plag1', pct: [80, 95], note: 'reflete o rearranjo de PLAG1; HMGA2 cobre parte dos restantes' },
      { marker: 'hmga2', pct: [15, 35] },
      { marker: 's100', pct: [85, 100], note: 'mioepitélio e estroma condroide' },
      { marker: 'p63', pct: [85, 100], note: 'mioepitélio' },
      { marker: 'p40', pct: [70, 90] },
      { marker: 'calponina', pct: [80, 95] },
      { marker: 'sma', pct: [60, 85] },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'gfap', pct: [50, 80], note: 'clássica no componente condromixoide' },
      { marker: 'ae1ae3', pct: [95, 100], note: 'luminal' },
      { marker: 'ck7', pct: [85, 100], note: 'luminal' },
      { marker: 'ck14', pct: [70, 90] },
      { marker: 'ema', pct: [70, 90], note: 'luminal' },
      { marker: 'myb', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 5], note: 'acima de 10% levanta carcinoma ex-adenoma pleomórfico' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma adenoide cístico: cribriforme com pseudocistos de membrana basal, MYB positivo, invasão perineural, sem estroma condroide verdadeiro.',
      'Adenocarcinoma polimorfo: palato, padrões variados com fila indiana e alvo, infiltrativo.',
      'Mioepitelioma: mesma família, sem componente ductal significativo.',
      'Carcinoma ex-adenoma pleomórfico: componente maligno com necrose, atipia e invasão, sobre o nódulo hialinizado antigo.',
    ],
    pitfalls: ['Implantes por ruptura capsular durante a cirurgia produzem "recidiva multinodular" que não é malignidade.'],
    molecular: 'Rearranjo de PLAG1 (8q12) na maioria; HMGA2 (12q14) numa minoria.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'tumor-warthin',
    name: 'Tumor de Warthin',
    aka: ['cistadenoma papilífero linfomatoso', "Warthin's tumour"],
    behavior: 'benigno',
    sites: [{ site: 'salivares', role: 'primario', freq: 3 }],
    cells: ['oncocitico', 'glandular', 'linfoide-pequenas'],
    architecture: ['papilar', 'cistico'],
    features: ['linfoide', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Nódulo cístico da cauda da parótida em fumante, com papilas revestidas por duas camadas de oncócitos altos de núcleo alinhado, sobre um estroma linfoide com centros germinativos; é bilateral ou multifocal em até um décimo dos casos.',
    criteria: [
      'Revestimento oncocítico bicamada: colunares luminais altos e camada basal de células menores, com núcleos alinhados em duas fileiras.',
      'Estroma linfoide organizado, com centros germinativos.',
      'Arquitetura papilar e cística.',
      'Ausência de atipia, necrose tumoral e mitoses; infarto após punção pode simular carcinoma escamoso.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'p63', pct: [80, 95], note: 'camada basal' },
      { marker: 'cd45', pct: [95, 100], note: 'só o estroma linfoide, que é policlonal' },
      { marker: 'cd20', pct: [90, 100], note: 'folículos' },
      { marker: 'cd3', pct: [90, 100], note: 'zona interfolicular' },
      { marker: 'sox10', pct: [10, 40] },
      { marker: 's100', pct: [10, 30] },
      { marker: 'dog1', pct: [0, 10] },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 5], note: 'alto só nos centros germinativos' },
    ],
    mimics: [
      'Carcinoma mucoepidermoide com estroma linfoide: células mucosas e intermediárias, MAML2 rearranjado.',
      'Cisto linfoepitelial: revestimento escamoso, sem oncócitos bicamada, associado a HIV.',
      'Oncocitoma: sem estroma linfoide, sem papilas císticas.',
      'Metástase linfonodal intraparotídea: atipia, arquitetura destrutiva.',
    ],
    pitfalls: ['Infarto pós-punção causa metaplasia escamosa atípica e pode ser lido como carcinoma escamoso ou mucoepidermoide.'],
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-mucoepidermoide',
    name: 'Carcinoma mucoepidermoide',
    aka: ['CME', 'mucoepidermoid carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 3 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'escamoso', 'anel-sinete', 'claras'],
    architecture: ['cistico', 'ninhos', 'lencois'],
    features: ['mucina', 'linfoide', 'mitoses-raras', 'necrose'],
    ages: ['jovem', 'adulto'],
    summary: 'O carcinoma salivar mais comum e o mais comum na criança: mistura de células mucosas, intermediárias e epidermoides em proporções variáveis, com cistos cheios de mucina nos de baixo grau e lençóis sólidos nos de alto grau; a fusão CRTC1::MAML2 confirma e traz bom prognóstico.',
    criteria: [
      'Presença simultânea de células mucosas (mucicarmim ou PAS-diastase positivas), intermediárias e epidermoides.',
      'Ausência de queratinização franca com pérolas: se houver, pense em carcinoma escamoso.',
      'Graduação por sistema de pontos (componente cístico, invasão perineural, necrose, mitoses, anaplasia).',
      'Rearranjo de MAML2 confirma em casos sólidos e de alto grau e afasta carcinoma escamoso.',
      'p63 e p40 marcam as intermediárias e epidermoides; as mucosas são negativas.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'intermediárias e epidermoides' },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'muc5ac', pct: [70, 90], note: 'células mucosas' },
      { marker: 'ck14', pct: [60, 85] },
      { marker: 's100', pct: [5, 20], note: 'fraca; difusa favorece secretor' },
      { marker: 'sox10', pct: [5, 25], note: 'baixa, ao contrário do acinar e do secretor' },
      { marker: 'dog1', pct: [0, 10], note: 'negativa; separa do acinar' },
      { marker: 'mamaglobina', pct: [0, 15], note: 'negativa; o secretor é difusamente positivo' },
      { marker: 'pan-trk', pct: [0, 5] },
      { marker: 'ki67', pct: [5, 40], note: 'sobe com o grau' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma escamoso: queratinização, sem células mucosas, sem MAML2.',
      'Cistadenoma e metaplasia mucosa: sem componente intermediário sólido nem invasão.',
      'Carcinoma secretor: SOX10, S100 e mamaglobina difusos, ETV6::NTRK3.',
      'Carcinoma de células claras hialinizante: monomórfico, EWSR1::ATF1, sem células mucosas.',
    ],
    molecular: 'Fusão CRTC1::MAML2 (ou CRTC3::MAML2) na maioria dos de baixo e grau intermediário.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-adenoide-cistico',
    name: 'Carcinoma adenoide cístico',
    aka: ['CAC', 'adenoid cystic carcinoma', 'cilindroma (uso antigo)'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 3 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['basaloide', 'epitelioide'],
    architecture: ['cribriforme', 'trabecular', 'lencois', 'glandulas'],
    features: ['hialinizacao', 'perineural', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Proliferação bifásica de células basaloides de núcleo anguloso e citoplasma escasso, formando cribras cheias de material de membrana basal e mucina azul, com invasão perineural quase obrigatória; cresce devagar por décadas e mata por recidiva local e metástase pulmonar tardia.',
    criteria: [
      'Padrão cribriforme, tubular ou sólido, com predomínio de células mioepiteliais abluminais e ductos verdadeiros mínimos.',
      'Pseudocistos preenchidos por material de membrana basal (eosinofílico hialino) e mucina basofílica.',
      'Invasão perineural presente na grande maioria e altamente sugestiva.',
      'Componente sólido acima de 30% define o alto grau e piora muito o prognóstico.',
      'MYB nuclear ou rearranjo MYB::NFIB apoiam quando a morfologia é limítrofe.',
    ],
    markers: [
      { marker: 'myb', pct: [70, 90], note: 'reflete a fusão MYB::NFIB ou MYBL1. Fortemente dependente do clone e do ponto de corte: as séries vão de 26 a 97%, então valide o seu anticorpo antes de confiar num negativo' },
      { marker: 'cd117', pct: [85, 100], note: 'luminal; sensível mas nada específica' },
      { marker: 'p63', pct: [90, 100], note: 'abluminal, padrão em cesto ao redor das cribras' },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 's100', pct: [70, 90] },
      { marker: 'calponina', pct: [85, 100] },
      { marker: 'sma', pct: [60, 85] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'plag1', pct: [0, 10], note: 'negativa; separa do adenoma pleomórfico celular' },
      { marker: 'er', pct: [0, 10] },
      { marker: 'ki67', pct: [5, 30], note: 'acima de 20% acompanha transformação de alto grau' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma pleomórfico celular: PLAG1 positivo, estroma condroide, sem invasão perineural.',
      'Adenocarcinoma polimorfo: mais no palato, células monótonas com núcleo vesiculoso, padrões de fila indiana e alvo, PRKD1 mutado.',
      'Carcinoma basaloide escamoso: sem padrão bifásico, p16 possível, necrose comedo.',
      'Adenocarcinoma cribriforme de língua e salivares menores: nuclear claro, mais nodular.',
    ],
    pitfalls: ['CD117 positivo não é específico: marca também o adenoma pleomórfico e o carcinoma epitelial-mioepitelial.'],
    molecular: 'Fusão MYB::NFIB na maioria; MYBL1::NFIB em parte.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-acinar-salivar',
    name: 'Carcinoma de células acinares salivar',
    aka: ['acinic cell carcinoma', 'carcinoma de células acinares de parótida'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'oncocitico', 'claras', 'glandular'],
    architecture: ['lencois', 'micropapilar', 'cistico', 'folicular'],
    features: ['linfoide', 'mitoses-raras', 'hemorragia'],
    ages: ['jovem', 'adulto'],
    summary: 'Carcinoma de parótida feito de células serosas com grânulos de zimogênio basofílicos, muitas vezes em lençóis sólidos sem atipia, que pode simular parênquima normal na biópsia; DOG1 com padrão apical em membrana e NR4A3 nuclear são os dois marcadores úteis.',
    criteria: [
      'Diferenciação acinar serosa: grânulos de zimogênio PAS-diastase resistentes, mesmo que focais.',
      'Padrões sólido, microcístico, papilar-cístico e folicular, isolados ou misturados.',
      'DOG1 com marcação apical e membranosa, e não citoplasmática difusa.',
      'NR4A3 nuclear confirma; o subtipo esclerosante rico em microcistos é o que mais confunde.',
      'Transformação de alto grau é definida por necrose, anaplasia e Ki-67 alto sobre o componente clássico.',
    ],
    markers: [
      { marker: 'dog1', pct: [85, 100], note: 'apical e membranoso; é o padrão que conta' },
      { marker: 'nr4a3', pct: [80, 95], note: 'substituto do rearranjo de NR4A3' },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'ck7', pct: [50, 80], note: 'menos constante que nos outros salivares' },
      { marker: 's100', pct: [10, 40], note: 'fraca; difusa e forte favorece secretor' },
      { marker: 'mamaglobina', pct: [0, 15], note: 'negativa; separa do secretor' },
      { marker: 'p63', pct: [0, 10], note: 'sem componente mioepitelial' },
      { marker: 'p40', pct: [0, 5] },
      { marker: 'ttf1', pct: [0, 10], note: 'cuidado com o padrão folicular, que imita tireoide' },
      { marker: 'tireoglobulina', pct: 0 },
      { marker: 'ki67', pct: [1, 10], note: 'alto na transformação de alto grau' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma secretor: mamaglobina, S100 e SOX10 difusos, ETV6::NTRK3, DOG1 negativo.',
      'Parênquima salivar normal em biópsia: mantém lóbulos e ductos, tem cápsula e ácinos organizados.',
      'Oncocitoma e carcinoma oncocítico: sem grânulos de zimogênio, DOG1 negativo.',
      'Metástase de carcinoma folicular de tireoide: tireoglobulina e TTF-1 positivos.',
    ],
    molecular: 'Rearranjo de NR4A3 (t(4;9), enhancer hijacking) na quase totalidade.',
    sources: [WHO, SEETHALA, 'Haller et al., Nat Commun (2019), NR4A3 no carcinoma de células acinares'],
  },
  {
    id: 'carcinoma-secretor',
    name: 'Carcinoma secretor',
    aka: ['carcinoma secretor análogo ao mamário', 'MASC', 'secretory carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'boca', role: 'primario', freq: 1 },
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular', 'oncocitico'],
    architecture: ['cistico', 'papilar', 'lencois', 'folicular'],
    features: ['mucina', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Carcinoma de baixo grau com microcistos e folículos cheios de secreção eosinofílica densa, células de citoplasma vacuolizado abundante e núcleo vesiculoso com nucléolo central; a tríade S100, mamaglobina e SOX10 com DOG1 negativo aponta a fusão ETV6::NTRK3, que é alvo terapêutico.',
    criteria: [
      'Microcistos, túbulos e folículos com material secretor eosinofílico intraluminal, PAS-diastase resistente e mucicarmim positivo.',
      'Ausência de grânulos de zimogênio basofílicos (que definiriam acinar).',
      'Coexpressão difusa de S100, mamaglobina e SOX10, com DOG1 negativo.',
      'Confirmação por ETV6::NTRK3 (FISH ou sequenciamento) quando se cogita terapia com inibidor de TRK.',
      'Transformação de alto grau existe e muda a conduta.',
    ],
    markers: [
      { marker: 's100', pct: [95, 100], note: 'difusa e forte; é a marca' },
      { marker: 'mamaglobina', pct: [90, 100] },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'gcdfp15', pct: [40, 70] },
      { marker: 'pan-trk', pct: [80, 95], note: 'nuclear e citoplasmática; reflete a fusão NTRK3' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'dog1', pct: [0, 10], note: 'o negativo que separa do acinar' },
      { marker: 'p63', pct: [0, 10] },
      { marker: 'p40', pct: [0, 5] },
      { marker: 'nr4a3', pct: 0 },
      { marker: 'er', pct: [0, 10] },
      { marker: 'trps1', pct: [30, 70], note: 'não prova origem mamária aqui' },
      { marker: 'ki67', pct: [2, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma de células acinares: DOG1 apical, NR4A3, grânulos de zimogênio, mamaglobina negativa.',
      'Carcinoma mucoepidermoide de baixo grau: p63 e p40 difusos, células intermediárias, MAML2.',
      'Adenocarcinoma polimorfo: palato, fila indiana, PRKD1.',
      'Metástase de carcinoma mamário: a imuno é a mesma; o contexto clínico decide.',
    ],
    molecular: 'Fusão ETV6::NTRK3 na maioria; variantes ETV6::RET e outras existem.',
    sources: [WHO, SEETHALA, 'Skálová et al., Am J Surg Pathol (2010), carcinoma secretor análogo ao mamário'],
  },
  {
    id: 'adenocarcinoma-polimorfo',
    name: 'Adenocarcinoma polimorfo',
    aka: ['adenocarcinoma polimorfo de baixo grau', 'polymorphous adenocarcinoma', 'PAC'],
    behavior: 'maligno',
    sites: [
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'salivares', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular', 'basaloide'],
    architecture: ['glandulas', 'cribriforme', 'papilar', 'trabecular', 'fila-indiana', 'infiltrativo'],
    features: ['perineural', 'hialinizacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma de glândula salivar menor do palato com células uniformes de núcleo vesiculoso pálido e citoplasma escasso, que adota muitos padrões arquiteturais dentro do mesmo tumor, com crescimento em fila indiana e em alvo concêntrico ao redor de nervos e vasos.',
    criteria: [
      'Uniformidade citológica com diversidade arquitetural: o contrário do adenoide cístico.',
      'Núcleos vesiculosos, pálidos, sobrepostos, lembrando carcinoma papilífero de tireoide.',
      'Crescimento infiltrativo em fila indiana e padrão de alvo perineural.',
      'Sítio: glândula salivar menor, sobretudo palato duro-mole.',
      'A variante cribriforme (de língua) tem mais metástase nodal e núcleo mais claro.',
    ],
    markers: [
      { marker: 's100', pct: [90, 100], note: 'difusa e forte' },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ema', pct: [70, 90] },
      { marker: 'bcl2', pct: [70, 90] },
      { marker: 'p63', pct: [50, 80], note: 'positivo, mas p40 negativo: a dissociação é típica' },
      { marker: 'p40', pct: [0, 15], note: 'o negativo que separa do adenoide cístico' },
      { marker: 'calponina', pct: [10, 40] },
      { marker: 'myb', pct: [10, 30] },
      { marker: 'cd117', pct: [10, 40] },
      { marker: 'mamaglobina', pct: [20, 50] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma adenoide cístico: p40 positivo, células anguladas hipercromáticas, MYB.',
      'Adenoma pleomórfico: PLAG1, estroma condroide, sem invasão.',
      'Carcinoma papilífero de tireoide metastático: TTF-1 e tireoglobulina.',
      'Carcinoma mioepitelial: sem componente ductal, p40 difuso.',
    ],
    pitfalls: ['A dissociação p63 positivo com p40 negativo é um dos poucos lugares da patologia em que ela é diagnóstica.'],
    molecular: 'Mutação PRKD1 E710D no clássico; fusões PRKD1/2/3 na variante cribriforme.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-ductos-salivares',
    name: 'Carcinoma de ductos salivares',
    aka: ['salivary duct carcinoma', 'SDC'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'glandular', 'pleomorfico', 'oncocitico'],
    architecture: ['cribriforme', 'papilar', 'ninhos', 'glandulas'],
    features: ['necrose', 'mitoses-altas', 'desmoplasia', 'perineural', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma salivar de alto grau que reproduz o carcinoma ductal da mama, com cribras e necrose comedo dentro dos ductos e invasão desmoplásica em volta; quase sempre receptor de androgênio positivo, e uma parte é HER2 amplificada, o que abre tratamento alvo.',
    criteria: [
      'Morfologia de carcinoma ductal mamário de alto grau: cribriforme, papilar e sólido com necrose comedo.',
      'Receptor de androgênio nuclear difuso na grande maioria.',
      'ER e PR negativos (a positividade de ER sugere metástase mamária).',
      'HER2 e AR devem ser testados em todo caso: definem terapia.',
      'Pode surgir sobre adenoma pleomórfico (carcinoma ex-adenoma pleomórfico de tipo ductal).',
    ],
    markers: [
      { marker: 'ar', pct: [70, 95], note: 'difuso e nuclear; critério de apoio' },
      { marker: 'gcdfp15', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'her2', pct: [20, 45], note: 'o "positivo" é 3+ ou amplificado; define terapia anti-HER2' },
      { marker: 'ema', pct: [90, 100] },
      { marker: 'er', pct: [0, 10], note: 'o negativo que afasta metástase mamária' },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'gata3', pct: [60, 90], note: 'positivo; não use para dizer que é mama' },
      { marker: 'trps1', pct: [20, 50] },
      { marker: 'p63', pct: [0, 15], note: 'só mioepitélio residual no componente in situ' },
      { marker: 'sox10', pct: [0, 15], note: 'negativo, ao contrário da maioria dos salivares' },
      { marker: 's100', pct: [0, 15] },
      { marker: 'p53', pct: [50, 75] },
      { marker: 'ki67', pct: [40, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de carcinoma mamário: ER frequentemente positivo, história de mama.',
      'Carcinoma mucoepidermoide de alto grau: p63 e p40 difusos, células mucosas, MAML2.',
      'Carcinoma oncocítico: sem necrose comedo nem AR difuso.',
      'Carcinoma de células escamosas metastático na parótida: p40 difuso, sem AR.',
    ],
    pitfalls: ['SOX10 negativo num carcinoma de parótida é achado útil: quase todos os outros salivares são positivos.'],
    molecular: 'Amplificação de HER2 em parte; mutações de PIK3CA, HRAS e TP53; perda de PTEN.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-epitelial-mioepitelial',
    name: 'Carcinoma epitelial-mioepitelial',
    aka: ['epithelial-myoepithelial carcinoma', 'EMC'],
    behavior: 'maligno',
    sites: [{ site: 'salivares', role: 'primario', freq: 1 }],
    cells: ['claras', 'epitelioide', 'glandular'],
    architecture: ['glandulas', 'ninhos', 'lobular'],
    features: ['hialinizacao', 'mitoses-raras', 'perineural'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor bifásico de arquitetura tubular em que cada ducto tem uma camada luminal eosinofílica e uma camada externa nítida de células mioepiteliais de citoplasma claro, separadas por membrana basal espessa; baixo grau, com recidivas locais.',
    criteria: [
      'Padrão bifásico com camada mioepitelial externa de células claras bem evidente ao redor de ductos luminais.',
      'Membrana basal espessa em torno dos ninhos, marcada por colágeno IV ou PAS.',
      'Confirmação imuno-histoquímica das duas camadas: queratinas luminais mais p63, calponina e SMA abluminais.',
      'Crescimento lobulado com invasão, sem cápsula íntegra.',
      'Transformação de alto grau (dediferenciação) é rara e piora muito o prognóstico.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'camada mioepitelial' },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'calponina', pct: [90, 100] },
      { marker: 'sma', pct: [80, 95] },
      { marker: 's100', pct: [85, 100], note: 'mioepitélio' },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100], note: 'luminal' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ema', pct: [80, 95], note: 'luminal' },
      { marker: 'colageno-iv', pct: [85, 100], note: 'membrana basal espessa em volta dos ninhos' },
      { marker: 'cd117', pct: [50, 80], note: 'luminal; não é específica' },
      { marker: 'caix', pct: [0, 15], note: 'ajuda contra metástase de RCC de células claras' },
      { marker: 'pax8', pct: [0, 10] },
      { marker: 'ki67', pct: [2, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de carcinoma renal de células claras: PAX8 e CA-IX positivos, sem camada mioepitelial.',
      'Carcinoma de células claras hialinizante: monofásico, p63 positivo mas sem camada luminal, EWSR1::ATF1.',
      'Mioepitelioma de células claras: sem componente ductal.',
      'Carcinoma mucoepidermoide de células claras: células mucosas, MAML2.',
    ],
    molecular: 'Mutações de HRAS (Q61) na maioria.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-mioepitelial',
    name: 'Carcinoma mioepitelial',
    aka: ['mioepitelioma maligno', 'myoepithelial carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 1 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'boca', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'plasmocitoide', 'claras'],
    architecture: ['lobular', 'lencois', 'ninhos'],
    features: ['estroma-mixoide', 'necrose', 'mitoses-moderadas', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Proliferação puramente mioepitelial, sem ductos verdadeiros, com células epitelioides, plasmocitoides, claras ou fusiformes em nódulos com centro mixoide e periferia celular; o diagnóstico exige provar a linhagem mioepitelial e demonstrar invasão.',
    criteria: [
      'Ausência de diferenciação ductal verdadeira: só células mioepiteliais.',
      'Prova de linhagem: queratina (ou EMA) positiva junto com p63, calponina, SMA ou S100.',
      'Invasão destrutiva, necrose ou atipia acentuada separam do mioepitelioma benigno.',
      'Padrão de nódulos multilobulados com zonação mixoide central é característico.',
      'Muitos surgem sobre adenoma pleomórfico prévio.',
    ],
    markers: [
      { marker: 'p63', pct: [80, 95] },
      { marker: 'p40', pct: [50, 80] },
      { marker: 's100', pct: [85, 100] },
      { marker: 'sox10', pct: [85, 100] },
      { marker: 'calponina', pct: [70, 90] },
      { marker: 'sma', pct: [50, 80] },
      { marker: 'ae1ae3', pct: [80, 95] },
      { marker: 'ema', pct: [60, 85] },
      { marker: 'gfap', pct: [20, 50] },
      { marker: 'plag1', pct: [30, 60], note: 'quando nasce de adenoma pleomórfico' },
      { marker: 'ini1', pct: [10, 40], note: 'o positivo é a perda; ocorre em parte dos mioepiteliais de partes moles' },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Mioepitelioma benigno: sem invasão, sem necrose, Ki-67 baixo.',
      'Carcinoma epitelial-mioepitelial: tem camada luminal ductal.',
      'Melanoma: SOX10 e S100 positivos também, mas HMB-45 e Melan-A positivos e queratina negativa.',
      'Sarcoma mixoide (condrossarcoma mixoide extraesquelético): queratina e p63 negativos.',
    ],
    pitfalls: ['SOX10 e S100 positivos com queratina fraca podem levar a melanoma; peça HMB-45 e Melan-A.'],
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-ex-adenoma-pleomorfico',
    name: 'Carcinoma ex-adenoma pleomórfico',
    aka: ['carcinoma em adenoma pleomórfico', 'carcinoma ex-pleomorphic adenoma'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'glandular', 'pleomorfico'],
    architecture: ['ninhos', 'cribriforme', 'lencois'],
    features: ['necrose', 'mitoses-altas', 'hialinizacao', 'desmoplasia', 'perineural', 'calcificacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma que surge dentro de um adenoma pleomórfico, muitas vezes de longa data: o resíduo benigno aparece como área hialinizada e calcificada na periferia, e o componente maligno é em geral um carcinoma de ductos salivares ou um adenocarcinoma de alto grau.',
    criteria: [
      'Demonstração do adenoma pleomórfico residual (áreas condromixoides ou nódulo hialinizado cicatricial).',
      'Componente carcinomatoso identificado e tipado (ductos salivares na maioria).',
      'Classificação pela extensão da invasão além da cápsula do adenoma: intracapsular, minimamente invasivo (até 4 a 6 mm) ou francamente invasivo, que muda o prognóstico radicalmente.',
      'PLAG1 positivo nos dois componentes apoia a origem comum.',
    ],
    markers: [
      { marker: 'plag1', pct: [60, 90], note: 'persiste no componente maligno e confirma a origem' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ar', pct: [50, 80], note: 'quando o componente maligno é de ductos salivares' },
      { marker: 'her2', pct: [20, 45] },
      { marker: 'gcdfp15', pct: [50, 80] },
      { marker: 'p63', pct: [30, 70], note: 'no resíduo benigno e no componente mioepitelial' },
      { marker: 's100', pct: [40, 70], note: 'no resíduo benigno' },
      { marker: 'sox10', pct: [30, 70] },
      { marker: 'p53', pct: [50, 75], note: 'no componente maligno' },
      { marker: 'ki67', pct: [30, 80], note: 'a diferença entre os dois componentes é o achado útil' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma pleomórfico celular ou atípico: sem invasão, Ki-67 baixo, p53 selvagem.',
      'Carcinoma de ductos salivares de novo: sem resíduo de adenoma pleomórfico.',
      'Adenoma pleomórfico metastatizante: histologia benigna nos dois sítios.',
    ],
    molecular: 'Rearranjo de PLAG1 herdado do adenoma, somado a TP53, HER2 e outras alterações.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'papilifero-tireoide',
    name: 'Carcinoma papilífero de tireoide',
    aka: ['CPT', 'papillary thyroid carcinoma', 'variante folicular invasiva'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular', 'oncocitico'],
    architecture: ['papilar', 'folicular', 'trabecular', 'infiltrativo'],
    features: ['sulcos-inclusoes', 'psamomas', 'desmoplasia', 'mitoses-raras'],
    ages: ['jovem', 'adulto', 'idoso'],
    sex: 'f',
    summary: 'O carcinoma de tireoide mais comum: o diagnóstico é feito pelo núcleo, não pela papila — aumentado, oval, sobreposto, com cromatina clara em vidro fosco, sulcos longitudinais e pseudoinclusões; corpos psamomatosos e desmoplasia apoiam, e a metástase nodal cervical é regra e não muda muito o prognóstico.',
    criteria: [
      'Núcleos papilíferos: aumento e alongamento, sobreposição, cromatina clara marginada, membrana nuclear irregular, sulcos e pseudoinclusões.',
      'Escore nuclear de três pontos (tamanho/forma, membrana, cromatina) aplicado sistematicamente.',
      'Papilas verdadeiras com eixo fibrovascular, quando presentes; a variante folicular não as tem.',
      'Corpos psamomatosos são altamente específicos, mas pouco sensíveis.',
      'Invasão capsular ou vascular é necessária nas lesões foliculares encapsuladas com núcleo papilífero (senão, NIFTP).',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'tireoglobulina', pct: [90, 100], note: 'pode ser fraca nos pouco diferenciados' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [85, 100], note: 'forte e difusa; no folicular benigno é focal' },
      { marker: 'hbme1', pct: [80, 95] },
      { marker: 'galectina3', pct: [80, 95] },
      { marker: 'brafv600e', pct: [50, 80], note: 'clone VE1; quase todos os clássicos, poucos dos foliculares' },
      { marker: 'ck20', pct: 0 },
      { marker: 'calcitonina', pct: 0, note: 'o negativo que afasta medular' },
      { marker: 'cea', pct: [0, 10] },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'NIFTP: encapsulado, núcleo papilífero, sem invasão, sem papilas verdadeiras, sem psamomas.',
      'Adenoma folicular com alterações reativas: núcleo sem cromatina clara nem sulcos, CK19 focal.',
      'Carcinoma medular: calcitonina e CEA positivos, tireoglobulina negativa.',
      'Adenocarcinoma polimorfo salivar metastático: TTF-1 negativo.',
      'Hiperplasia papilar de doença de Graves: sem atipia nuclear, difusa.',
    ],
    pitfalls: ['HBME-1 e galectina-3 marcam algumas lesões benignas; nunca diagnostique por eles sem o núcleo.'],
    molecular: 'BRAF V600E na maioria dos clássicos; fusões RET/PTC e NTRK; RAS nas variantes foliculares.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'nift-p',
    name: 'Neoplasia folicular tireoidiana não invasiva com núcleos de tipo papilífero (NIFTP)',
    aka: ['NIFTP', 'variante folicular encapsulada não invasiva'],
    behavior: 'intermediario',
    sites: [{ site: 'tireoide', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'glandular'],
    architecture: ['folicular', 'cistico'],
    features: ['sulcos-inclusoes', 'mitoses-raras', 'coloide'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Nódulo encapsulado ou bem delimitado, inteiramente folicular, cujos núcleos têm alterações de tipo papilífero mas sem qualquer invasão capsular ou vascular; foi retirado da categoria de carcinoma justamente porque não recidiva nem metastatiza quando os critérios são cumpridos com rigor.',
    criteria: [
      'Encapsulado ou claramente delimitado.',
      'Padrão folicular em mais de 99% (sem papilas verdadeiras).',
      'Escore nuclear papilífero de 2 a 3 pontos.',
      'Ausência absoluta de invasão capsular e vascular, examinando toda a cápsula.',
      'Ausência de corpos psamomatosos, necrose tumoral e mais de 3 mitoses por 10 campos de grande aumento.',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'tireoglobulina', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [30, 60], note: 'em geral focal, ao contrário do papilífero clássico' },
      { marker: 'hbme1', pct: [50, 80] },
      { marker: 'galectina3', pct: [30, 60] },
      { marker: 'brafv600e', pct: [0, 5], note: 'praticamente ausente; se positivo, reveja o diagnóstico' },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Variante folicular invasiva do papilífero: qualquer invasão capsular ou vascular a exclui.',
      'Adenoma folicular: sem alterações nucleares papilíferas.',
      'Carcinoma folicular: invasão, sem núcleo papilífero.',
    ],
    pitfalls: ['O diagnóstico exige a cápsula inteira submetida; em punção ou fragmento não se pode fazer NIFTP.'],
    molecular: 'Mutações de RAS na maioria; BRAF V600E praticamente ausente.',
    sources: [WHO, 'Nikiforov et al., JAMA Oncol (2016), proposta do NIFTP', LIVOLSI],
  },
  {
    id: 'carcinoma-folicular-tireoide',
    name: 'Carcinoma folicular de tireoide',
    aka: ['follicular thyroid carcinoma', 'carcinoma folicular minimamente invasivo'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular'],
    architecture: ['folicular', 'trabecular'],
    features: ['coloide', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Neoplasia folicular encapsulada sem núcleos papilíferos cujo diagnóstico depende exclusivamente da demonstração de invasão capsular transfixante ou invasão vascular na cápsula ou fora dela; metastatiza por via hematogênica para osso e pulmão, às vezes antes de o nódulo dar sintoma.',
    criteria: [
      'Padrão folicular puro, sem alterações nucleares de tipo papilífero.',
      'Invasão capsular de espessura total, com tumor atravessando toda a cápsula.',
      'Ou invasão vascular: ninhos tumorais aderidos à parede de vaso dentro ou além da cápsula, cobertos por endotélio, com trombo.',
      'Classificação em minimamente invasivo, encapsulado angioinvasivo (menos ou mais de 4 focos) e amplamente invasivo, com prognósticos distintos.',
      'Amostragem da cápsula inteira é obrigatória.',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'tireoglobulina', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'cd31', pct: [0, 5], note: 'usada para provar que o foco está dentro de vaso' },
      { marker: 'erg', pct: [0, 5], note: 'idem, no endotélio que reveste o êmbolo' },
      { marker: 'ck19', pct: [10, 40], note: 'focal' },
      { marker: 'hbme1', pct: [40, 70] },
      { marker: 'galectina3', pct: [40, 70] },
      { marker: 'brafv600e', pct: [0, 5] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma folicular: sem invasão, mesma citologia.',
      'Carcinoma papilífero variante folicular: núcleos papilíferos.',
      'Carcinoma oncocítico: células oncocíticas em mais de 75%, perfil molecular distinto.',
      'Metástase de carcinoma renal ou de NET no nódulo tireoidiano: tireoglobulina negativa.',
    ],
    pitfalls: ['Artefato de punção prévia produz pseudoinvasão capsular com hemossiderina e fibrose linear; procure o trajeto.'],
    molecular: 'Mutações de RAS e fusão PAX8::PPARG.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'carcinoma-oncocitico-tireoide',
    name: 'Carcinoma oncocítico de tireoide',
    aka: ['carcinoma de células de Hürthle', 'Hürthle cell carcinoma', 'oncocytic carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['oncocitico', 'epitelioide'],
    architecture: ['folicular', 'trabecular', 'lencois'],
    features: ['nucleolo', 'mitoses-raras', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    summary: 'Neoplasia de células oncocíticas em mais de três quartos do tumor, com citoplasma granular eosinofílico abundante e nucléolo proeminente, definida como maligna pelos mesmos critérios de invasão do folicular; capta pouco iodo, o que muda o tratamento.',
    criteria: [
      'Mais de 75% de células oncocíticas (citoplasma granular eosinofílico por acúmulo de mitocôndrias).',
      'Invasão capsular transfixante ou invasão vascular, como no folicular.',
      'Ausência de núcleos de tipo papilífero (senão é variante oncocítica do papilífero).',
      'Necrose tumoral e mitoses numerosas indicam alto grau e mudam o prognóstico.',
    ],
    markers: [
      { marker: 'ttf1', pct: [90, 100] },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'tireoglobulina', pct: [70, 95], note: 'costuma ser mais fraca que no folicular clássico' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [30, 70] },
      { marker: 'hbme1', pct: [40, 70] },
      { marker: 'galectina3', pct: [50, 80] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'cromogranina', pct: [0, 10], note: 'o negativo que separa de paraganglioma e medular' },
      { marker: 'pth', pct: 0, note: 'afasta paratireoide oncocítica' },
      { marker: 'gata3', pct: [0, 10], note: 'idem' },
      { marker: 'brafv600e', pct: [0, 5] },
      { marker: 'ki67', pct: [2, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma oncocítico: sem invasão.',
      'Adenoma ou carcinoma de paratireoide oncocítico: PTH e GATA3 positivos, TTF-1 negativo.',
      'Carcinoma medular: calcitonina positiva.',
      'Metástase de carcinoma renal oncocítico e de HCC: PAX8 no renal, HepPar-1 e arginase no hepático.',
    ],
    molecular: 'Alterações mitocondriais de DNA e perdas cromossômicas amplas; RAS menos frequente que no folicular.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'carcinoma-medular-tireoide',
    name: 'Carcinoma medular de tireoide',
    aka: ['CMT', 'medullary thyroid carcinoma', 'carcinoma de células C'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['neuroendocrino', 'fusocelular', 'plasmocitoide', 'epitelioide', 'oncocitico'],
    architecture: ['ninhos', 'lencois', 'trabecular', 'organoide'],
    features: ['amiloide', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor das células C parafoliculares, em ninhos de células fusiformes ou plasmocitoides com cromatina em sal e pimenta, frequentemente com estroma amiloide; calcitonina positiva e tireoglobulina negativa, e um quarto dos casos é hereditário (RET germinativo, NEM 2).',
    criteria: [
      'Calcitonina positiva nas células tumorais (pode ser focal ou fraca nos pouco diferenciados).',
      'Tireoglobulina negativa, com o parênquima vizinho servindo de controle positivo.',
      'Marcadores neuroendócrinos positivos: sinaptofisina, cromogranina, INSM1.',
      'Amiloide estromal (vermelho Congo) quando presente, mas não obrigatório.',
      'Calcitonina sérica e CEA elevados; pesquisa de RET germinativo em todo caso.',
    ],
    markers: [
      { marker: 'calcitonina', pct: [85, 100], note: 'o critério; pode faltar em variantes pouco diferenciadas' },
      { marker: 'tireoglobulina', pct: 0, note: 'o negativo obrigatório' },
      { marker: 'cea', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [90, 100] },
      { marker: 'cromogranina', pct: [85, 100] },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'ttf1', pct: [70, 95], note: 'positivo: não use TTF-1 para separar de folicular' },
      { marker: 'pax8', pct: [10, 40], note: 'clone monoclonal costuma ser negativo' },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'ck7', pct: [10, 40] },
      { marker: 'ck20', pct: 0 },
      { marker: 'gata3', pct: [10, 40] },
      { marker: 's100', pct: [10, 30], note: 'sustentaculares periféricas em alguns' },
      { marker: 'ki67', pct: [2, 20], note: 'acima de 5% acompanha alto grau' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma folicular ou papilífero de padrão sólido: tireoglobulina positiva, calcitonina negativa.',
      'Paraganglioma cervical: queratina negativa, GATA3 positiva, sustentaculares.',
      'Metástase de NET de outro sítio: calcitonina negativa, CDX2 ou ilhotas conforme a origem.',
      'Hialinizante trabecular: MIB-1 de membrana, PAX8 positivo, calcitonina negativa.',
    ],
    pitfalls: ['TTF-1 positivo é a regra no medular e leva a erro quem o usa como prova de origem folicular.'],
    molecular: 'RET mutado (germinativo nas NEM 2A/2B, somático em metade dos esporádicos); RAS nos RET-negativos.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'carcinoma-pouco-diferenciado-tireoide',
    name: 'Carcinoma pouco diferenciado de tireoide',
    aka: ['carcinoma insular', 'poorly differentiated thyroid carcinoma', 'critérios de Turim'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'pequenas-redondas'],
    architecture: ['ninhos', 'trabecular', 'lencois'],
    features: ['necrose', 'mitoses-moderadas', 'mitoses-altas'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma de origem folicular com crescimento sólido, insular ou trabecular, sem núcleos papilíferos, e com pelo menos um de três sinais de agressividade: mitoses frequentes, necrose tumoral ou núcleo convoluto; ocupa o espaço entre o diferenciado e o anaplásico.',
    criteria: [
      'Padrão sólido, insular ou trabecular predominante.',
      'Ausência de núcleos de tipo papilífero convencionais.',
      'Pelo menos um dos três: núcleos convolutos, 3 ou mais mitoses por 2 mm², ou necrose tumoral.',
      'Manutenção de diferenciação folicular demonstrável por TTF-1 e PAX8, com tireoglobulina ao menos focal.',
      'Ausência de anaplasia franca e de perda total de diferenciação (que definiria anaplásico).',
    ],
    markers: [
      { marker: 'ttf1', pct: [80, 95] },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'tireoglobulina', pct: [50, 85], note: 'focal e fraca, muitas vezes só perinuclear' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'p53', pct: [20, 40], note: 'aumenta na progressão para anaplásico' },
      { marker: 'sinaptofisina', pct: [0, 15] },
      { marker: 'ki67', pct: [10, 30] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma anaplásico: perda de TTF-1 e tireoglobulina, anaplasia franca, p53 aberrante.',
      'Carcinoma medular: calcitonina positiva.',
      'Carcinoma folicular sólido sem sinais de Turim: sem necrose nem mitoses.',
      'Metástase de carcinoma neuroendócrino: PAX8 e TTF-1 conforme o sítio, sinaptofisina difusa.',
    ],
    molecular: 'RAS e BRAF somados a TERT promotor, TP53 e alterações de PIK3CA.',
    sources: [WHO, 'Volante et al., Am J Surg Pathol (2007), proposta de Turim', LIVOLSI],
  },
  {
    id: 'carcinoma-anaplasico-tireoide',
    name: 'Carcinoma anaplásico de tireoide',
    aka: ['carcinoma indiferenciado de tireoide', 'anaplastic thyroid carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 2 },
      { site: 'pescoco', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
    ],
    cells: ['pleomorfico', 'fusocelular', 'epitelioide', 'gigantes', 'rabdoide'],
    architecture: ['lencois', 'fasciculos', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'hemorragia', 'desmoplasia'],
    ages: ['idoso'],
    summary: 'Massa cervical que cresce em semanas em paciente idoso, feita de células fusiformes, pleomórficas e gigantes com necrose ampla, mitoses atípicas e invasão de tudo em volta; perde TTF-1 e tireoglobulina, e o PAX8 é quase sempre o único resquício de linhagem tireoidiana.',
    criteria: [
      'Carcinoma indiferenciado com anaplasia franca: pleomorfismo extremo, mitoses atípicas, necrose.',
      'Origem tireoidiana demonstrada por PAX8, por componente diferenciado residual ou pela topografia.',
      'Exclusão de sarcoma (queratina ou PAX8 positivos), melanoma (SOX10), linfoma (CD45) e metástase.',
      'Pesquisa de BRAF V600E obrigatória: define terapia com dabrafenibe e trametinibe.',
      'Estadiamento sempre T4 e estádio IV.',
    ],
    markers: [
      { marker: 'pax8', pct: [50, 80], note: 'o mais persistente; clone policlonal é mais sensível' },
      { marker: 'ae1ae3', pct: [50, 80], note: 'pode ser focal ou negativa nos fusocelulares' },
      { marker: 'ttf1', pct: [10, 30], note: 'perdido na maioria' },
      { marker: 'tireoglobulina', pct: [0, 15], note: 'só em resíduo diferenciado aprisionado' },
      { marker: 'p53', pct: [60, 90] },
      { marker: 'brafv600e', pct: [30, 45], note: 'nos que vêm de papilífero; define terapia-alvo' },
      { marker: 'pdl1', pct: [20, 60] },
      { marker: 'vimentina', pct: [80, 100] },
      { marker: 'cd45', pct: 0 },
      { marker: 'sox10', pct: [0, 10] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'ki67', pct: [50, 95] },
    ],
    mimics: [
      'Sarcoma de alto grau da região cervical: PAX8 e queratina negativas.',
      'Linfoma difuso de grandes células B da tireoide: CD45 e CD20 positivos, em tireoidite de Hashimoto.',
      'Melanoma metastático: SOX10 positivo.',
      'Carcinoma escamoso de laringe invadindo a tireoide: p40 difuso, PAX8 negativo.',
      'Tireoidite de Riedel: fibrose densa sem atipia, IgG4.',
    ],
    molecular: 'TP53 e TERT promotor quase constantes, sobre BRAF ou RAS herdados do tumor diferenciado precursor.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'adenoma-paratireoide',
    name: 'Adenoma e carcinoma de paratireoide',
    aka: ['adenoma paratireóideo', 'parathyroid adenoma', 'parathyroid carcinoma'],
    behavior: 'intermediario',
    sites: [
      { site: 'paratireoide', role: 'primario', freq: 3 },
      { site: 'pescoco', role: 'primario', freq: 2 },
      { site: 'mediastino', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'claras', 'oncocitico'],
    architecture: ['ninhos', 'trabecular', 'folicular', 'lencois'],
    features: ['mitoses-raras', 'hemorragia', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Nódulo hipercelular de células principais com borda de tecido paratireóideo normal comprimido e sem adipócitos no interior, em paciente com hipercalcemia e PTH alto; o carcinoma se define por invasão franca ou metástase, e a perda de parafibromina aponta a via HRPT2.',
    criteria: [
      'Hipercelularidade com perda do estroma adiposo intralesional e borda de glândula normal comprimida.',
      'Confirmação de linhagem por PTH e GATA3, com TTF-1 e tireoglobulina negativos.',
      'Carcinoma exige invasão capsular transmural com reação desmoplásica, invasão vascular ou perineural, invasão de estruturas vizinhas ou metástase.',
      'Bandas fibrosas espessas, necrose e mitoses frequentes apoiam carcinoma mas isoladamente não bastam.',
      'Perda de parafibromina indica carcinoma ou síndrome hiperparatireoidismo-tumor de mandíbula.',
    ],
    markers: [
      { marker: 'pth', pct: [90, 100], note: 'o marcador definidor' },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [50, 80] },
      { marker: 'cromogranina', pct: [70, 95] },
      { marker: 'ttf1', pct: 0, note: 'o negativo que separa da tireoide' },
      { marker: 'tireoglobulina', pct: 0 },
      { marker: 'pax8', pct: [0, 20], note: 'clone monoclonal negativo; policlonal pode marcar' },
      { marker: 'ck7', pct: [10, 40] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'ciclinad1', pct: [30, 70], note: 'superexpressa em parte dos adenomas' },
      { marker: 'rb1', pct: [10, 40], note: 'perda descrita em parte dos carcinomas' },
      { marker: 'ki67', pct: [1, 10], note: 'acima de 5% favorece carcinoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Nódulo tireoidiano de células claras: TTF-1 e tireoglobulina positivos.',
      'Hiperplasia paratireóidea: múltiplas glândulas aumentadas, sem borda normal comprimida.',
      'Paratireoide normal: adipócitos intralesionais preservados.',
      'Metástase de carcinoma renal de células claras: PAX8 e CA-IX positivos, PTH negativo.',
    ],
    molecular: 'Ciclina D1 (CCND1) e MEN1 nos adenomas; CDC73 (HRPT2) com perda de parafibromina nos carcinomas.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'adenoma-folicular-tireoide',
    name: 'Adenoma folicular de tireoide',
    aka: ['adenoma folicular', 'follicular adenoma', 'adenoma oncocítico'],
    behavior: 'benigno',
    sites: [{ site: 'tireoide', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'glandular', 'oncocitico'],
    architecture: ['folicular', 'trabecular', 'lencois'],
    features: ['coloide', 'mitoses-raras', 'hialinizacao', 'hemorragia'],
    ages: ['jovem', 'adulto', 'idoso'],
    sex: 'f',
    summary: 'Nódulo folicular encapsulado, único, com arquitetura diferente do parênquima vizinho comprimido, sem núcleos de tipo papilífero e sem qualquer invasão capsular ou vascular; é a lesão tireoidiana neoplásica mais comum e a base contra a qual todo o resto do diferencial folicular é lido.',
    criteria: [
      'Cápsula fibrosa completa, com parênquima tireoidiano normal comprimido por fora dela.',
      'Arquitetura folicular (normofolicular, microfolicular, macrofolicular, trabecular ou sólida) distinta do fundo.',
      'Ausência de núcleos de tipo papilífero: se presentes e sem invasão, o diagnóstico é NIFTP.',
      'Ausência absoluta de invasão capsular transfixante e de invasão vascular, com a cápsula inteira submetida.',
      'Variante oncocítica quando mais de 75% das células são oncocíticas; variantes com atipia nuclear focal entram nas categorias de potencial incerto.',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'tireoglobulina', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [10, 30], note: 'focal e fraca; forte e difusa favorece papilífero' },
      { marker: 'hbme1', pct: [10, 30], note: 'pode ser focalmente positivo: não use isolado para chamar de carcinoma' },
      { marker: 'galectina3', pct: [10, 35], note: 'idem' },
      { marker: 'brafv600e', pct: [0, 5] },
      { marker: 'calcitonina', pct: 0, note: 'o negativo que afasta medular' },
      { marker: 'cromogranina', pct: [0, 5] },
      { marker: 'pth', pct: 0, note: 'o negativo que afasta paratireoide, sobretudo na variante oncocítica' },
      { marker: 'gata3', pct: [0, 5] },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma folicular: invasão capsular transfixante ou vascular; a citologia é idêntica.',
      'NIFTP: mesma arquitetura encapsulada, mas com núcleos de tipo papilífero.',
      'Nódulo hiperplásico da tireoide multinodular: sem cápsula completa, múltiplo, com o mesmo padrão do fundo.',
      'Adenoma de paratireoide intratireoidiano: PTH e GATA3 positivos, TTF-1 negativo.',
      'Metástase de carcinoma renal de células claras: PAX8 positivo nos dois, tireoglobulina negativa.',
    ],
    molecular: 'Mutações de RAS e fusão PAX8::PPARG podem estar presentes; a molecular não separa adenoma de carcinoma folicular.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'carcinoma-celulas-claras-hialinizante',
    name: 'Carcinoma de células claras hialinizante',
    aka: ['carcinoma de células claras hialinizante', 'hyalinizing clear cell carcinoma', 'HCCC'],
    behavior: 'maligno',
    sites: [
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'salivares', role: 'primario', freq: 1 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
    ],
    cells: ['claras', 'epitelioide', 'escamoso'],
    architecture: ['ninhos', 'trabecular', 'fila-indiana', 'infiltrativo'],
    features: ['hialinizacao', 'mitoses-raras', 'perineural'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma de glândula salivar menor, quase sempre do palato ou da base da língua, com cordões e ninhos de células claras monótonas dentro de um estroma densamente hialinizado; é monofásico, sem camada mioepitelial abluminal, e a fusão EWSR1::ATF1 é o que o separa do epitelial-mioepitelial e do mucoepidermoide de células claras.',
    criteria: [
      'Cordões, ninhos e trabéculas de células poligonais com citoplasma claro glicogenado, sem atipia significativa.',
      'Estroma hialinizado denso, característico e frequentemente predominante.',
      'Proliferação monofásica: p63 positivo em todas as células, sem camada luminal ductal distinta.',
      'Ausência de células mucosas verdadeiras e de componente mioepitelial abluminal organizado.',
      'Confirmação por EWSR1::ATF1 (ou EWSR1::CREM), a mesma família de fusões do sarcoma de células claras e do fibro-histiocitoma angiomatoide.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'difuso em todas as células, e não só numa camada abluminal' },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ema', pct: [70, 95] },
      { marker: 's100', pct: [0, 20], note: 'o negativo que ajuda contra mioepitelial e epitelial-mioepitelial' },
      { marker: 'sox10', pct: [0, 25] },
      { marker: 'calponina', pct: [0, 20], note: 'o negativo que exclui componente mioepitelial verdadeiro' },
      { marker: 'sma', pct: [0, 15] },
      { marker: 'dog1', pct: [0, 10] },
      { marker: 'pax8', pct: [0, 10], note: 'o negativo que afasta metástase de carcinoma renal de células claras' },
      { marker: 'caix', pct: [0, 15] },
      { marker: 'melana', pct: [0, 5], note: 'o negativo que exclui melanoma e PEComa de células claras' },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma epitelial-mioepitelial: bifásico, com camada luminal ductal e mioepitélio claro abluminal.',
      'Carcinoma mucoepidermoide de células claras: células mucosas presentes, fusão MAML2.',
      'Metástase de carcinoma renal de células claras: PAX8 e CA-IX positivos, rede capilar delicada.',
      'Mioepitelioma e carcinoma mioepitelial de células claras: S100, SOX10 e calponina positivos.',
      'Odontogênico de células claras (carcinoma odontogênico de células claras): mesma fusão EWSR1::ATF1, mas intraósseo nos maxilares.',
    ],
    molecular: 'Fusão EWSR1::ATF1 na maioria; EWSR1::CREM numa minoria.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'oncocitoma-salivar',
    name: 'Oncocitoma salivar e oncocitose',
    aka: ['oncocitoma de parótida', 'adenoma oncocítico', 'oncocitose multifocal nodular'],
    behavior: 'benigno',
    sites: [{ site: 'salivares', role: 'primario', freq: 2 }],
    cells: ['oncocitico', 'epitelioide'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['mitoses-raras', 'hialinizacao'],
    ages: ['idoso', 'adulto'],
    summary: 'Nódulo encapsulado de parótida feito só de oncócitos poligonais com citoplasma granular eosinofílico intenso e núcleo redondo central, sem estroma linfoide e sem grânulos de zimogênio; a oncocitose multifocal nodular é a contraparte não encapsulada e multifocal, e a variante de células claras é a que mais confunde com carcinoma renal metastático.',
    criteria: [
      'Proliferação pura de oncócitos, encapsulada, sem componente mucoso, escamoso, acinar nem linfoide.',
      'Núcleos redondos e uniformes com nucléolo pequeno, sem atipia e sem mitoses.',
      'Ausência de grânulos de zimogênio (que definiriam acinar) e de estroma linfoide (que definiria Warthin).',
      'DOG1 e NR4A3 negativos, o que o separa do carcinoma de células acinares oncocítico.',
      'Oncocitose multifocal nodular: nódulos múltiplos não encapsulados no parênquima, sem significado maligno, mas que na congelação simula invasão.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'ck7', pct: [70, 95] },
      { marker: 'p63', pct: [40, 80], note: 'camada basal periférica dos ninhos, descontínua' },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'dog1', pct: [0, 10], note: 'o negativo que separa do carcinoma de células acinares' },
      { marker: 'nr4a3', pct: [0, 5] },
      { marker: 'sox10', pct: [30, 70] },
      { marker: 's100', pct: [10, 40] },
      { marker: 'plag1', pct: [0, 10], note: 'o negativo que separa do adenoma pleomórfico oncocítico' },
      { marker: 'pax8', pct: [0, 10], note: 'o negativo que afasta metástase renal, sobretudo na variante de células claras' },
      { marker: 'caix', pct: [0, 15] },
      { marker: 'ar', pct: [0, 20], note: 'o negativo que ajuda contra carcinoma de ductos salivares oncocítico' },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor de Warthin: estroma linfoide com centros germinativos e revestimento bicamada papilar.',
      'Carcinoma de células acinares oncocítico: DOG1 apical e NR4A3 nuclear.',
      'Carcinoma oncocítico: invasão, atipia, necrose e Ki-67 alto.',
      'Metástase de carcinoma renal de células claras ou oncocitoma renal: PAX8 positivo.',
      'Adenoma pleomórfico oncocítico: PLAG1 positivo, com estroma condromixoide.',
    ],
    sources: [WHO, SEETHALA],
  },
  {
    id: 'adenoma-celulas-basais',
    name: 'Adenoma de células basais',
    aka: ['basal cell adenoma', 'adenoma monomórfico', 'adenoma de células basais membranoso'],
    behavior: 'benigno',
    sites: [{ site: 'salivares', role: 'primario', freq: 2 }],
    cells: ['basaloide', 'epitelioide'],
    architecture: ['ninhos', 'trabecular', 'glandulas', 'palicada'],
    features: ['hialinizacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Adenoma de parótida bem encapsulado, feito de células basaloides em ninhos com paliçada periférica e material de membrana basal entre eles, sem o estroma condromixoide do adenoma pleomórfico; a variante membranosa, com bainhas hialinas grossas em quebra-cabeça, é multifocal, recidiva e associa-se ao cilindroma cutâneo.',
    criteria: [
      'Proliferação basaloide encapsulada com paliçada periférica nítida e dupla população (basaloide escura periférica e mais pálida central).',
      'Ausência de estroma condromixoide: é o que o separa do adenoma pleomórfico.',
      'Padrões sólido, trabecular, tubular e membranoso; o membranoso tem bainhas hialinas espessas e é o único que recidiva.',
      'β-catenina nuclear reflete mutação de CTNNB1 e apoia o diagnóstico nos padrões sólido e trabecular.',
      'Ausência de invasão: o carcinoma de células basais tem a mesma citologia e se define por infiltração, invasão perineural ou vascular.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [60, 90], pattern: 'N', note: 'reflete CTNNB1 mutado; o carcinoma adenoide cístico é negativo' },
      { marker: 'p63', pct: [90, 100], note: 'células basaloides periféricas' },
      { marker: 'p40', pct: [80, 95] },
      { marker: 'calponina', pct: [70, 95], note: 'componente mioepitelial abluminal' },
      { marker: 'sma', pct: [50, 85] },
      { marker: 's100', pct: [50, 85] },
      { marker: 'sox10', pct: [80, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [80, 95], note: 'luminal' },
      { marker: 'colageno-iv', pct: [80, 100], note: 'bainhas de membrana basal, espessas na variante membranosa' },
      { marker: 'cd117', pct: [40, 80], note: 'luminal; positivo também no adenoide cístico, então não separa' },
      { marker: 'myb', pct: [0, 20], note: 'o negativo que ajuda contra adenoide cístico' },
      { marker: 'plag1', pct: [0, 15], note: 'o negativo que separa do adenoma pleomórfico' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma adenoide cístico: cribriforme com pseudocistos, invasão perineural, MYB positivo, β-catenina negativa.',
      'Adenoma pleomórfico celular: estroma condromixoide, PLAG1 positivo.',
      'Carcinoma de células basais: mesma citologia com invasão franca.',
      'Carcinoma basaloide escamoso: sem componente mioepitelial, p53 aberrante.',
      'Cilindroma e espiradenoma cutâneos da pele sobrejacente: CYLD, com a mesma arquitetura membranosa.',
    ],
    molecular: 'CTNNB1 nos padrões sólido e trabecular; CYLD na variante membranosa, ligada à síndrome de Brooke-Spiegler.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'mioepitelioma',
    name: 'Mioepitelioma',
    aka: ['mioepitelioma benigno', 'myoepithelioma', 'adenoma mioepitelial'],
    behavior: 'benigno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'boca', role: 'primario', freq: 1 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'plasmocitoide', 'epitelioide', 'claras'],
    architecture: ['lencois', 'fasciculos', 'nodular'],
    features: ['estroma-mixoide', 'hialinizacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Tumor composto exclusivamente por células mioepiteliais — fusiformes, plasmocitoides (hialinas), epitelioides ou claras — sem qualquer formação ductal verdadeira; é o extremo da mesma família do adenoma pleomórfico, compartilha o rearranjo de PLAG1, e a contraparte maligna se define por invasão e atipia, não por imuno.',
    criteria: [
      'Proliferação exclusivamente mioepitelial, com no máximo ductos muito esparsos (menos de 5% da lesão).',
      'Quatro morfologias possíveis, isoladas ou combinadas: fusocelular, plasmocitoide, epitelioide e de células claras.',
      'Prova de linhagem: queratina ou EMA positivos junto com pelo menos um entre p63, calponina, SMA e S100.',
      'Ausência de estroma condromixoide abundante, que definiria adenoma pleomórfico.',
      'Encapsulado e sem invasão: atipia acentuada, necrose ou infiltração definem carcinoma mioepitelial.',
    ],
    markers: [
      { marker: 's100', pct: [85, 100] },
      { marker: 'sox10', pct: [85, 100] },
      { marker: 'p63', pct: [70, 95] },
      { marker: 'p40', pct: [40, 75], note: 'menos constante que o p63 nesta linhagem' },
      { marker: 'calponina', pct: [70, 95] },
      { marker: 'sma', pct: [40, 75], note: 'costuma faltar na variante plasmocitoide' },
      { marker: 'ae1ae3', pct: [70, 95] },
      { marker: 'ck7', pct: [40, 80] },
      { marker: 'ema', pct: [40, 75] },
      { marker: 'gfap', pct: [20, 50] },
      { marker: 'plag1', pct: [40, 75], note: 'compartilhado com o adenoma pleomórfico, do qual é parente próximo' },
      { marker: 'ini1', pct: [0, 10], note: 'retido; a perda ocorre em parte dos mioepiteliais de partes moles' },
      { marker: 'desmina', pct: [0, 10], note: 'o negativo que separa de tumor de músculo liso' },
      { marker: 'ki67', pct: [1, 5], note: 'acima de 10% com atipia favorece carcinoma mioepitelial' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma mioepitelial: invasão destrutiva, necrose, atipia e Ki-67 alto.',
      'Adenoma pleomórfico: componente ductal e estroma condromixoide presentes.',
      'Melanoma: SOX10 e S100 positivos nos dois; HMB-45 e Melan-A resolvem.',
      'Schwannoma: SOX10 e S100 positivos, mas queratina e p63 negativos.',
      'Plasmocitoma da variante plasmocitoide: CD138 com restrição de cadeia leve.',
    ],
    pitfalls: ['A variante plasmocitoide é queratina fraca e SMA negativa: sem p63 e S100 no painel, o caso pode virar plasmocitoma ou melanoma.'],
    molecular: 'Rearranjo de PLAG1 em parte; EWSR1 nas variantes de células claras.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-intraductal-salivar',
    name: 'Carcinoma intraductal salivar',
    aka: ['intraductal carcinoma of salivary gland', 'carcinoma intraductal de baixo grau', 'antigo carcinoma cribriforme de ducto intercalado'],
    behavior: 'intermediario',
    sites: [{ site: 'salivares', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'glandular', 'oncocitico'],
    architecture: ['cribriforme', 'papilar', 'cistico', 'glandulas'],
    features: ['mitoses-raras', 'hemorragia', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Proliferação epitelial confinada ao sistema ductal da parótida, com mioepitélio preservado ao redor de cada estrutura — o equivalente salivar do carcinoma ductal in situ da mama. O subtipo de ducto intercalado é S100 e mamaglobina positivo e indolente; o apócrino é AR positivo e parente do carcinoma de ductos salivares.',
    criteria: [
      'Camada mioepitelial preservada ao redor de todos os ninhos, demonstrada por p63, calponina e miosina de cadeia pesada: é o critério que define.',
      'Arquitetura cribriforme, papilar ou sólida dentro de ductos dilatados, com atipia de baixo a intermediário grau.',
      'Subtipo de ducto intercalado: S100, SOX10 e mamaglobina positivos, com AR negativo; fusões de NCOA4::RET.',
      'Subtipo apócrino: AR e GCDFP-15 positivos com S100 negativo; alterações de PIK3CA e HRAS.',
      'A perda focal do mioepitélio indica invasão e reclassifica como carcinoma invasor, mudando a conduta.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'mioepitélio preservado: sem ele, o diagnóstico é carcinoma invasor' },
      { marker: 'calponina', pct: [85, 100] },
      { marker: 'smmhc', pct: [80, 95] },
      { marker: 's100', pct: [70, 95], note: 'no subtipo de ducto intercalado, que é o mais comum' },
      { marker: 'mamaglobina', pct: [60, 90] },
      { marker: 'sox10', pct: [80, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ar', pct: [10, 40], note: 'positivo só no subtipo apócrino, que é parente do carcinoma de ductos salivares' },
      { marker: 'gcdfp15', pct: [20, 50] },
      { marker: 'her2', pct: [0, 15] },
      { marker: 'dog1', pct: [0, 10], note: 'o negativo que separa do carcinoma de células acinares' },
      { marker: 'nr4a3', pct: [0, 5] },
      { marker: 'pan-trk', pct: [0, 15], note: 'o negativo que ajuda contra carcinoma secretor' },
      { marker: 'ki67', pct: [2, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma secretor: microcistos com secreção, mamaglobina e S100 difusos, mas sem mioepitélio ao redor e com ETV6::NTRK3.',
      'Carcinoma de ductos salivares: invasor, AR difuso, HER2 amplificado, sem mioepitélio.',
      'Carcinoma de células acinares: DOG1 apical, NR4A3 nuclear.',
      'Cistadenoma e sialadenoma papilífero: sem atipia.',
      'Adenoma pleomórfico com proliferação intraductal: PLAG1 positivo, estroma condromixoide.',
    ],
    molecular: 'Fusões de RET (NCOA4::RET, TRIM27::RET) no subtipo de ducto intercalado; PIK3CA e HRAS no apócrino.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'adenocarcinoma-microsecretor',
    name: 'Adenocarcinoma microsecretor',
    aka: ['microsecretory adenocarcinoma', 'MSA'],
    behavior: 'maligno',
    sites: [
      { site: 'boca', role: 'primario', freq: 1 },
      { site: 'salivares', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular', 'claras'],
    architecture: ['glandulas', 'trabecular', 'infiltrativo'],
    features: ['estroma-mixoide', 'mucina', 'mitoses-raras'],
    ages: ['adulto'],
    summary: 'Entidade nova da 5ª edição, quase sempre do palato: microcistos e túbulos uniformes revestidos por células achatadas ou cuboides, com secreção basofílica luminal, num estroma fibromixoide azulado. Indolente apesar das margens infiltrativas, e definido pela fusão SS18::MEF2C — a mesma família SS18 do sarcoma sinovial, em contexto completamente diferente.',
    criteria: [
      'Microcistos e túbulos pequenos e monótonos com secreção basofílica ou eosinofílica intraluminal.',
      'Células achatadas a cuboides de baixo grau, com citoplasma escasso e núcleos uniformes.',
      'Estroma fibromixoide abundante, azulado, entre as estruturas.',
      'Coexpressão de S100 e p63 com SOX10, num tumor sem camada mioepitelial organizada.',
      'Confirmação por fusão SS18::MEF2C; o anticorpo SS18-SSX é negativo, e não deve ser usado para excluir.',
    ],
    markers: [
      { marker: 's100', pct: [90, 100] },
      { marker: 'p63', pct: [85, 100], note: 'a coexpressão com S100 é o achado prático' },
      { marker: 'sox10', pct: [80, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ck7', pct: [20, 60], note: 'caracteristicamente fraca ou negativa, ao contrário dos outros salivares' },
      { marker: 'p40', pct: [0, 25], note: 'dissociação com o p63, como no adenocarcinoma polimorfo' },
      { marker: 'sma', pct: [0, 20] },
      { marker: 'calponina', pct: [0, 30] },
      { marker: 'ss18ssx', pct: 0, note: 'negativo: a fusão é SS18::MEF2C e o anticorpo de sarcoma sinovial não a detecta' },
      { marker: 'mamaglobina', pct: [0, 20], note: 'o negativo que ajuda contra carcinoma secretor' },
      { marker: 'pan-trk', pct: [0, 10] },
      { marker: 'dog1', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma secretor: mamaglobina difusa, ETV6::NTRK3, pan-TRK positivo.',
      'Adenocarcinoma polimorfo: mesma dissociação p63 positivo com p40 negativo, mas com padrões arquiteturais variados e fila indiana.',
      'Carcinoma mucoepidermoide de baixo grau: células mucosas e intermediárias, MAML2.',
      'Adenocarcinoma de tipo não especial: sem o perfil S100 com p63.',
      'Sialadenite esclerosante com metaplasia: sem infiltração nem monotonia.',
    ],
    molecular: 'Fusão SS18::MEF2C, característica e definidora.',
    sources: [WHO, SEETHALA, 'Bishop, novas entidades em patologia de cabeça e pescoço, Head Neck Pathol'],
  },
  {
    id: 'adenoma-policistico-esclerosante',
    name: 'Adenoma policístico esclerosante',
    aka: ['sclerosing polycystic adenoma', 'adenose policística esclerosante', 'SPA'],
    behavior: 'benigno',
    sites: [{ site: 'salivares', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'oncocitico', 'glandular', 'claras'],
    architecture: ['cistico', 'lobular', 'glandulas'],
    features: ['hialinizacao', 'linfoide', 'mitoses-raras', 'precursor'],
    ages: ['adulto'],
    summary: 'Lesão de parótida bem delimitada que reproduz a alteração fibrocística da mama: lóbulos de ácinos e ductos dilatados dentro de esclerose densa, com metaplasia apócrina, células acinares de grânulos eosinofílicos grandes e focos de atipia ductal que lembram hiperplasia atípica. Reclassificado como neoplasia na 5ª edição, por ser clonal.',
    criteria: [
      'Lesão delimitada com arquitetura lobular preservada, em estroma densamente esclerótico.',
      'Ductos dilatados e cistos com epitélio variado: apócrino, mucoso, escamoso, oncocítico e vacuolado, na mesma lesão.',
      'Células acinares com grânulos citoplasmáticos eosinofílicos grandes e brilhantes, muito característicos.',
      'Focos de atipia ductal de tipo mamário, até carcinoma in situ, que não mudam o prognóstico benigno.',
      'Mioepitélio preservado ao redor dos ductos, o que separa de carcinoma invasor.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'mioepitélio preservado, o que exclui invasão' },
      { marker: 'calponina', pct: [85, 100] },
      { marker: 'smmhc', pct: [70, 95] },
      { marker: 's100', pct: [60, 90] },
      { marker: 'sox10', pct: [70, 95] },
      { marker: 'gcdfp15', pct: [60, 90], note: 'metaplasia apócrina' },
      { marker: 'ar', pct: [50, 85] },
      { marker: 'mamaglobina', pct: [30, 70] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'er', pct: [10, 40] },
      { marker: 'dog1', pct: [20, 60], note: 'nas células acinares residuais' },
      { marker: 'nr4a3', pct: [0, 5], note: 'o negativo que separa do carcinoma de células acinares' },
      { marker: 'ki67', pct: [1, 8] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma de células acinares: DOG1 apical difuso e NR4A3 nuclear, sem arquitetura lobular esclerótica.',
      'Sialadenite crônica esclerosante (tumor de Küttner): sem cistos revestidos por epitélio variado, IgG4.',
      'Carcinoma intraductal salivar: atipia difusa e monótona, não focal.',
      'Adenoma pleomórfico esclerosado: PLAG1 positivo, estroma condromixoide residual.',
      'Alteração fibrocística de tecido mamário ectópico: mesma morfologia, outro tecido.',
    ],
    molecular: 'Alterações da via PI3K (PIK3CA, PTEN, AKT1), com clonalidade demonstrada — a razão de ter sido reclassificado como neoplasia.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'tumor-trabecular-hialinizante',
    name: 'Tumor trabecular hialinizante',
    aka: ['hyalinizing trabecular tumour', 'HTT', 'adenoma trabecular hialinizante'],
    behavior: 'benigno',
    sites: [{ site: 'tireoide', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'fusocelular', 'oncocitico'],
    architecture: ['trabecular', 'ninhos'],
    features: ['hialinizacao', 'sulcos-inclusoes', 'calcificacao', 'psamomas', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Nódulo tireoidiano encapsulado com trabéculas de células alongadas envoltas por material hialino abundante, cujos núcleos têm sulcos e pseudoinclusões idênticos aos do carcinoma papilífero — o que faz dele um dos falsos positivos mais clássicos da punção. O MIB-1 com marcação de membrana é o achado que resolve.',
    criteria: [
      'Arquitetura trabecular com material hialino intercelular e perivascular abundante.',
      'Células alongadas com sulcos nucleares e pseudoinclusões, que imitam o carcinoma papilífero.',
      'Ki-67 (clone MIB-1) com marcação de membrana e citoplasma, e não nuclear: artefato de fixação característico e praticamente diagnóstico.',
      'Encapsulado, sem invasão capsular nem vascular; BRAF V600E negativo.',
      'Fusão PAX8::GLIS3 ou PAX8::GLIS1 confirma quando disponível.',
    ],
    markers: [
      { marker: 'ki67', pct: [85, 100], note: 'o padrão de membrana com o clone MIB-1 é o achado; lido como proliferação, vira falso alarme' },
      { marker: 'ttf1', pct: [90, 100] },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'tireoglobulina', pct: [80, 100] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck19', pct: [0, 20], note: 'o negativo que ajuda contra papilífero' },
      { marker: 'hbme1', pct: [0, 20] },
      { marker: 'galectina3', pct: [10, 40] },
      { marker: 'brafv600e', pct: [0, 5], note: 'o negativo que o separa do papilífero' },
      { marker: 'calcitonina', pct: 0, note: 'o negativo que afasta medular, que o hialino também imita' },
      { marker: 'cromogranina', pct: [0, 10] },
      { marker: 'cea', pct: [0, 10] },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma papilífero de tireoide: CK19 forte, BRAF V600E, Ki-67 nuclear.',
      'Carcinoma medular: calcitonina e CEA positivos, amiloide congo positivo.',
      'Paraganglioma intratireoidiano: queratina negativa, GATA3 positiva.',
      'Adenoma folicular com hialinização: sem trabéculas nem sulcos nucleares.',
      'Tumor hialinizante trabecular com invasão: existe, é raríssimo, e aí o nome muda.',
    ],
    pitfalls: ['Na punção, os sulcos e as pseudoinclusões levam a diagnóstico de papilífero: é uma das causas mais citadas de tireoidectomia desnecessária.'],
    molecular: 'Fusão PAX8::GLIS3 (ou GLIS1), específica desta entidade.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'neoplasias-foliculares-umb',
    name: 'Neoplasias foliculares de potencial maligno incerto',
    aka: ['FT-UMP', 'WDT-UMP', 'tumor folicular de potencial maligno incerto', 'tumor bem diferenciado de potencial maligno incerto'],
    behavior: 'intermediario',
    sites: [{ site: 'tireoide', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'glandular', 'oncocitico'],
    architecture: ['folicular', 'trabecular'],
    features: ['coloide', 'mitoses-raras', 'sulcos-inclusoes', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Categorias formais da OMS para o nódulo folicular encapsulado em que a invasão é duvidosa. Sem alterações nucleares papilíferas, chama-se FT-UMP; com elas, WDT-UMP. Existem para o patologista dizer honestamente que não sabe, em vez de forçar adenoma ou carcinoma — e quase todos se comportam de modo benigno.',
    criteria: [
      'Nódulo folicular encapsulado ou bem delimitado, com a cápsula inteira submetida.',
      'Invasão capsular ou vascular questionável e não inequívoca: é o critério de entrada.',
      'FT-UMP: sem alterações nucleares de tipo papilífero. WDT-UMP: com alterações nucleares papilíferas bem desenvolvidas.',
      'Ausência de necrose tumoral e de índice mitótico elevado, que levariam a carcinoma pouco diferenciado.',
      'O laudo deve dizer explicitamente que a categoria existe porque a invasão é duvidosa, e recomendar seguimento e não tratamento oncológico.',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'tireoglobulina', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'cd31', pct: [0, 5], note: 'usada para decidir se o foco duvidoso está mesmo dentro de um vaso' },
      { marker: 'erg', pct: [0, 5], note: 'idem; o endotélio precisa revestir o êmbolo' },
      { marker: 'ck19', pct: [20, 50] },
      { marker: 'hbme1', pct: [30, 60] },
      { marker: 'galectina3', pct: [30, 60] },
      { marker: 'brafv600e', pct: [0, 10] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'p53', pct: [0, 10], note: 'selvagem' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma folicular e NIFTP: sem qualquer suspeita de invasão.',
      'Carcinoma folicular: invasão capsular transfixante ou vascular inequívoca.',
      'Carcinoma papilífero variante folicular invasiva: invasão com núcleos papilíferos.',
      'Pseudoinvasão por punção prévia: trajeto com hemossiderina e fibrose linear.',
    ],
    pitfalls: ['A categoria não deve virar depósito de casos mal amostrados: antes de usá-la, confirme que toda a cápsula foi examinada.'],
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'castle',
    name: 'Carcinoma tímico-símile da tireoide (CASTLE)',
    aka: ['CASTLE', 'carcinoma mostrando diferenciação tímica', 'thymic-like carcinoma of the thyroid'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 1 },
      { site: 'pescoco', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'escamoso', 'sincicial'],
    architecture: ['lobular', 'ninhos', 'trabecular'],
    features: ['linfoide', 'hialinizacao', 'necrose', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma da tireoide ou da região peritireoidiana que reproduz o carcinoma tímico: lóbulos de células epiteliais com bordas expansivas, separados por septos fibrosos com linfócitos e plasmócitos. O CD5 positivo com TTF-1 e tireoglobulina negativos é o que o separa do carcinoma anaplásico e do escamoso, e o prognóstico é muito melhor que o de ambos.',
    criteria: [
      'Arquitetura lobular com septos fibrosos e infiltrado linfoplasmocitário, lembrando timo.',
      'CD5 e CD117 positivos nas células epiteliais: é o par que define.',
      'TTF-1 e tireoglobulina negativos, o que afasta origem folicular e o carcinoma anaplásico.',
      'Ausência de massa mediastinal: um carcinoma tímico que invade o pescoço é o principal diferencial.',
      'Prognóstico bem melhor que o do anaplásico e do escamoso da tireoide, que é a razão prática de reconhecer.',
    ],
    markers: [
      { marker: 'cd5', pct: [80, 100], note: 'nas células epiteliais, e não só nos linfócitos: é o critério' },
      { marker: 'cd117', pct: [80, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [80, 95] },
      { marker: 'ck56', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ttf1', pct: [0, 10], note: 'o negativo obrigatório' },
      { marker: 'tireoglobulina', pct: 0 },
      { marker: 'pax8', pct: [10, 40], note: 'o clone policlonal pode marcar, porque reconhece PAX8 tímico' },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'cd45', pct: 0, note: 'só os linfócitos dos septos' },
      { marker: 'ebv', pct: [0, 15] },
      { marker: 'p53', pct: [10, 40] },
      { marker: 'ki67', pct: [10, 40] },
    ],
    mimics: [
      'Carcinoma anaplásico de tireoide: PAX8 positivo, p53 aberrante, curso fulminante.',
      'Carcinoma escamoso da tireoide, primário ou por invasão da laringe: CD5 negativo.',
      'Carcinoma tímico com invasão cervical: histologia idêntica; a topografia e a imagem decidem.',
      'Timo ectópico e tumor ectópico do timo hamartomatoso: sem atipia.',
      'Carcinoma linfoepitelial: EBER positivo, CD5 negativo.',
    ],
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'hiperplasia-paratireoide',
    name: 'Hiperplasia de paratireoide',
    aka: ['hiperplasia paratireóidea primária e secundária', 'parathyroid hyperplasia'],
    behavior: 'benigno',
    sites: [
      { site: 'paratireoide', role: 'primario', freq: 3 },
      { site: 'pescoco', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'claras', 'oncocitico'],
    architecture: ['nodular', 'lencois', 'trabecular'],
    features: ['mitoses-raras', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    summary: 'Aumento de todas as quatro glândulas por proliferação de células principais, com perda do estroma adiposo; a distinção do adenoma é cirúrgica e não histológica, porque uma glândula hiperplásica isolada é idêntica a um adenoma — o que o patologista pode fazer é comparar com a segunda glândula biopsiada.',
    criteria: [
      'Hipercelularidade com redução do estroma adiposo, em múltiplas glândulas.',
      'Ausência de borda de paratireoide normal comprimida, que é o achado a favor de adenoma.',
      'Comparação com uma segunda glândula é a informação decisiva: se também é hipercelular, o quadro é de hiperplasia.',
      'Contexto clínico separa primária (esporádica ou NEM) de secundária (doença renal crônica) e terciária.',
      'Nodularidade e clonalidade em nódulos dominantes da hiperplasia secundária são comuns e não indicam adenoma.',
    ],
    markers: [
      { marker: 'pth', pct: [95, 100] },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'cromogranina', pct: [70, 95] },
      { marker: 'sinaptofisina', pct: [40, 80] },
      { marker: 'ttf1', pct: 0, note: 'o negativo que separa da tireoide' },
      { marker: 'tireoglobulina', pct: 0 },
      { marker: 'pax8', pct: [0, 20] },
      { marker: 'ciclinad1', pct: [10, 40], note: 'menos que no adenoma, mas não separa' },
      { marker: 'ki67', pct: [1, 3], note: 'baixo; acima de 5% favorece carcinoma' },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma de paratireoide: glândula única com borda de tecido normal comprimido, as demais normais.',
      'Carcinoma de paratireoide: invasão transcapsular com desmoplasia, invasão vascular, perda de parafibromina.',
      'Nódulo tireoidiano de células claras: TTF-1 e tireoglobulina positivos.',
      'Paratireoide normal: adipócitos intralesionais preservados.',
      'Paratiromatose: ninhos dispersos no pescoço após cirurgia prévia.',
    ],
    molecular: 'Policlonal na secundária, com nódulos clonais na evolução; MEN1 e CDC73 nas formas sindrômicas.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'sialoblastoma',
    name: 'Sialoblastoma',
    aka: ['sialoblastoma', 'adenoma basaloide congênito', 'embrioma salivar'],
    behavior: 'intermediario',
    sites: [{ site: 'salivares', role: 'primario', freq: 1 }],
    cells: ['basaloide', 'epitelioide', 'blastematoso'],
    architecture: ['ninhos', 'nodular', 'glandulas'],
    features: ['mitoses-moderadas', 'necrose', 'hialinizacao'],
    ages: ['crianca'],
    summary: 'Tumor congênito ou do primeiro ano de vida, quase sempre da parótida, que reproduz o estágio embrionário da glândula: ninhos sólidos de células basaloides primitivas com camada periférica em paliçada, envoltos por estroma imaturo, com ductos rudimentares no centro dos ninhos. O comportamento vai do benigno ao localmente agressivo.',
    criteria: [
      'Idade congênita ou no primeiro ano de vida, com massa parotídea ou submandibular.',
      'Ninhos sólidos de células basaloides primitivas com paliçada periférica, separados por estroma mesenquimal imaturo.',
      'Estruturas ductais rudimentares dentro dos ninhos, com camada luminal e mioepitelial demonstráveis.',
      'Achados de agressividade a relatar: necrose, invasão perineural e vascular, atipia acentuada e mitoses numerosas.',
      'Exclusão de outros tumores basaloides da criança: adenoma de células basais e carcinoma adenoide cístico praticamente não ocorrem nessa idade.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ck7', pct: [70, 95], note: 'luminal' },
      { marker: 'p63', pct: [85, 100], note: 'camada basaloide periférica' },
      { marker: 'calponina', pct: [60, 90] },
      { marker: 's100', pct: [50, 85] },
      { marker: 'sox10', pct: [70, 95] },
      { marker: 'sma', pct: [40, 80] },
      { marker: 'ema', pct: [40, 80], note: 'luminal' },
      { marker: 'cd117', pct: [30, 70] },
      { marker: 'betacatenina', pct: [20, 60], pattern: 'N' },
      { marker: 'plag1', pct: [0, 20], note: 'o negativo que ajuda contra adenoma pleomórfico' },
      { marker: 'myb', pct: [0, 20], note: 'o negativo que ajuda contra adenoide cístico' },
      { marker: 'ki67', pct: [10, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma de células basais e carcinoma de células basais: em adulto, com β-catenina nuclear no membranoso.',
      'Carcinoma adenoide cístico: MYB positivo, cribriforme com pseudocistos.',
      'Hamartoma e tecido salivar imaturo residual: arquitetura lobular organizada, sem massa.',
      'Rabdomiossarcoma embrionário parotídeo: desmina e miogenina positivos.',
      'Neuroblastoma metastático: PHOX2B e sinaptofisina.',
    ],
    sources: [WHO, SEETHALA],
  },
  {
    id: 'adenomas-ducto-salivar',
    name: 'Queratocistoma e adenomas de ducto estriado e intercalado',
    aka: ['keratocystoma', 'striated duct adenoma', 'intercalated duct adenoma', 'hiperplasia de ducto intercalado'],
    behavior: 'benigno',
    sites: [{ site: 'salivares', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'escamoso', 'oncocitico', 'glandular'],
    architecture: ['cistico', 'glandulas', 'nodular', 'lobular'],
    features: ['queratinizacao', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto'],
    summary: 'Três entidades benignas novas na 5ª edição, todas raras e todas com o mesmo papel prático: impedir que uma lesão benigna vire carcinoma no laudo. O queratocistoma tem cistos escamosos queratinizados sem atipia; os adenomas de ducto estriado e intercalado reproduzem cada segmento ductal, e o de ducto intercalado pode dar origem a adenoma de células basais.',
    criteria: [
      'Queratocistoma: cistos multiloculados revestidos por epitélio escamoso estratificado queratinizado, com ninhos sólidos escamosos, sem atipia, sem células mucosas e sem MAML2.',
      'Adenoma de ducto estriado: nódulo circunscrito de ductos revestidos por células colunares eosinofílicas com estriações basais, idênticas ao ducto estriado normal.',
      'Adenoma de ducto intercalado: nódulo de ductos pequenos com camada luminal cuboide e mioepitélio preservado, semelhante ao ducto intercalado.',
      'Hiperplasia de ducto intercalado é a contraparte não nodular e multifocal, e associa-se a adenoma de células basais e a carcinoma epitelial-mioepitelial.',
      'Todos exigem mioepitélio preservado e ausência de invasão; a demonstração disso é o que separa de carcinoma.',
    ],
    markers: [
      { marker: 'p63', pct: [85, 100], note: 'mioepitélio preservado nos adenomas; camada basal no queratocistoma' },
      { marker: 'calponina', pct: [70, 95] },
      { marker: 'smmhc', pct: [60, 90] },
      { marker: 'ck7', pct: [70, 95], note: 'luminal nos adenomas ductais' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck56', pct: [80, 100], note: 'epitélio escamoso do queratocistoma' },
      { marker: 'p40', pct: [80, 95] },
      { marker: 's100', pct: [40, 80] },
      { marker: 'sox10', pct: [60, 90] },
      { marker: 'dog1', pct: [0, 20], note: 'o negativo que separa do carcinoma de células acinares' },
      { marker: 'muc5ac', pct: [0, 15], note: 'o negativo que separa do carcinoma mucoepidermoide' },
      { marker: 'plag1', pct: [0, 15] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma mucoepidermoide de baixo grau: células mucosas e intermediárias com rearranjo de MAML2.',
      'Carcinoma escamoso metastático e cisto epidermoide: atipia ou ausência de camada basal organizada.',
      'Adenoma de células basais: paliçada periférica com β-catenina nuclear.',
      'Carcinoma epitelial-mioepitelial: bifásico com mioepitélio claro e invasão.',
      'Cistadenoma e cisto linfoepitelial: revestimento único sem ninhos sólidos.',
    ],
    sources: [WHO, SEETHALA],
  },
  {
    id: 'teratoma-tireoide',
    name: 'Teratoma da tireoide e do pescoço',
    aka: ['teratoma cervical', 'teratoma tireoidiano', 'teratoma maligno da tireoide'],
    behavior: 'intermediario',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 1 },
      { site: 'pescoco', role: 'primario', freq: 1 },
    ],
    cells: ['blastematoso', 'estreladas', 'glandular', 'escamoso', 'cartilaginoso'],
    architecture: ['nodular', 'rosetas', 'cistico'],
    features: ['condroide', 'mitoses-altas', 'necrose', 'calcificacao'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Teratoma cervical com epicentro na tireoide, que no recém-nascido é volumoso e maduro, causando obstrução de via aérea, e no adulto é quase sempre imaturo e maligno, com neuroepitélio primitivo dominante. A regra etária é o inverso da intuição: benigno no recém-nascido, maligno no adulto.',
    criteria: [
      'Massa cervical com epicentro na tireoide, contendo tecidos das três camadas germinativas.',
      'No recém-nascido e no lactente: quase sempre maduro ou imaturo de baixo grau, e benigno.',
      'No adulto: quase sempre imaturo de alto grau com neuroepitélio primitivo dominante, e agressivo.',
      'Graduação pelo componente neuroepitelial imaturo, como nos teratomas ovarianos.',
      'Exclusão de tumor germinativo metastático e de teratoma mediastinal com extensão cervical.',
    ],
    markers: [
      { marker: 'sall4', pct: [40, 80], note: 'no neuroepitélio imaturo; ausente no maduro' },
      { marker: 'lin28a', pct: [30, 70] },
      { marker: 'sinaptofisina', pct: [60, 90], note: 'neuroepitélio' },
      { marker: 'gfap', pct: [40, 80], note: 'glia' },
      { marker: 's100', pct: [60, 90] },
      { marker: 'ae1ae3', pct: [80, 100], note: 'componentes epiteliais' },
      { marker: 'ttf1', pct: [30, 70], note: 'tireoide residual e componente respiratório' },
      { marker: 'tireoglobulina', pct: [20, 60], note: 'tireoide residual aprisionada, e não o tumor' },
      { marker: 'oct4', pct: [0, 10], note: 'o negativo que exclui germinoma e carcinoma embrionário' },
      { marker: 'glipicano3', pct: [0, 30], note: 'difuso indicaria componente de saco vitelino' },
      { marker: 'desmina', pct: [20, 60] },
      { marker: 'cd99', pct: [20, 50] },
      { marker: 'ki67', pct: [20, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Bócio multinodular e nódulo coloide: sem tecidos de outras camadas germinativas.',
      'Carcinoma anaplásico e carcinossarcoma da tireoide: PAX8 positivo, sem componentes teratomatosos organizados.',
      'Teratoma mediastinal com extensão cervical: epicentro no mediastino.',
      'Tumor germinativo metastático: OCT4 e SALL4 difusos.',
      'Neuroblastoma cervical: PHOX2B e tirosina hidroxilase, sem outros tecidos.',
    ],
    sources: [WHO, LIVOLSI],
  },
]
