/* ==========================================================================
   salivarythyroid.ts — glândulas salivares, tireoide e paratireoide.

   Nas salivares a imuno raramente faz o diagnóstico sozinha: a arquitetura e
   o padrão bifásico (ductal mais mioepitelial) fazem, e os anticorpos de
   fusão (PLAG1, MYB, NR4A3, pan-TRK) confirmam. Na tireoide a pergunta é
   outra: primeiro se é folicular ou medular (tireoglobulina contra
   calcitonina), depois se o pouco diferenciado ou o anaplásico ainda guarda
   linhagem tireoidiana (PAX8 sobrevive quando TTF-1 e tireoglobulina somem).

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Head and Neck Tumours, 2022, capítulos de salivares e de
   tireoide; Seethala, Salivary Gland Cytopathology and Surgical Pathology;
   séries de Am J Surg Pathol, Head Neck Pathol e Thyroid). As fontes estão
   como referência de texto: as séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Head and Neck Tumours (2022)'
const SEETHALA = 'Seethala & Griffith, capítulos de patologia de glândulas salivares, Surg Pathol Clin'
const LIVOLSI = "LiVolsi & Baloch, capítulos de patologia da tireoide; Rosai and Ackerman's Surgical Pathology, tireoide"

export const salivarythyroid: Tumor[] = [
  {
    id: 'adenoma-pleomorfico',
    name: 'Adenoma pleomórfico',
    aka: ['tumor misto benigno', 'pleomorphic adenoma'],
    behavior: 'benigno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 3 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'nariz-seios', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'glandular', 'estreladas', 'plasmocitoide'],
    architecture: ['glandulas', 'ninhos', 'trabecular'],
    features: ['condroide', 'estroma-mixoide', 'hialinizacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'O tumor salivar mais comum: ductos verdadeiros de duas camadas mergulhados em estroma mixocondroide que nasce das próprias células mioepiteliais, com transição gradual entre epitélio, mioepitélio e matriz; a cápsula é fina e incompleta, e é por isso que a enucleação recidiva.',
    criteria: [
      'Três componentes obrigatórios em proporção variável: epitélio ductal, mioepitélio e estroma mixoide ou condroide.',
      'Transição suave entre as células mioepiteliais e a matriz, sem limite abrupto.',
      'Ductos de duas camadas: luminal com queratinas de baixo peso, abluminal mioepitelial com p63, calponina e S100.',
      'Ausência de invasão franca, necrose e mitoses atípicas; a presença delas levanta carcinoma ex-adenoma pleomórfico.',
      'PLAG1 nuclear confirma em material escasso ou em padrão celular atípico.',
    ],
    markers: [
      { marker: 'plag1', pct: [80, 95], note: 'reflete o rearranjo de PLAG1; HMGA2 cobre parte dos restantes' },
      { marker: 'hmga2', pct: [15, 35] },
      { marker: 's100', pct: [85, 100], note: 'mioepitélio e estroma condroide' },
      { marker: 'p63', pct: [85, 100], note: 'mioepitélio' },
      { marker: 'p40', pct: [70, 90] },
      { marker: 'calponina', pct: [80, 95] },
      { marker: 'sma', pct: [60, 85] },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'gfap', pct: [50, 80], note: 'clássica no componente condromixoide' },
      { marker: 'ae1ae3', pct: [95, 100], note: 'luminal' },
      { marker: 'ck7', pct: [85, 100], note: 'luminal' },
      { marker: 'ck14', pct: [70, 90] },
      { marker: 'ema', pct: [70, 90], note: 'luminal' },
      { marker: 'myb', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 5], note: 'acima de 10% levanta carcinoma ex-adenoma pleomórfico' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma adenoide cístico: cribriforme com pseudocistos de membrana basal, MYB positivo, invasão perineural, sem estroma condroide verdadeiro.',
      'Adenocarcinoma polimorfo: palato, padrões variados com fila indiana e alvo, infiltrativo.',
      'Mioepitelioma: mesma família, sem componente ductal significativo.',
      'Carcinoma ex-adenoma pleomórfico: componente maligno com necrose, atipia e invasão, sobre o nódulo hialinizado antigo.',
    ],
    pitfalls: ['Implantes por ruptura capsular durante a cirurgia produzem "recidiva multinodular" que não é malignidade.'],
    molecular: 'Rearranjo de PLAG1 (8q12) na maioria; HMGA2 (12q14) numa minoria.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'tumor-warthin',
    name: 'Tumor de Warthin',
    aka: ['cistadenoma papilífero linfomatoso', "Warthin's tumour"],
    behavior: 'benigno',
    sites: [{ site: 'salivares', role: 'primario', freq: 3 }],
    cells: ['oncocitico', 'glandular', 'linfoide-pequenas'],
    architecture: ['papilar', 'cistico'],
    features: ['linfoide', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Nódulo cístico da cauda da parótida em fumante, com papilas revestidas por duas camadas de oncócitos altos de núcleo alinhado, sobre um estroma linfoide com centros germinativos; é bilateral ou multifocal em até um décimo dos casos.',
    criteria: [
      'Revestimento oncocítico bicamada: colunares luminais altos e camada basal de células menores, com núcleos alinhados em duas fileiras.',
      'Estroma linfoide organizado, com centros germinativos.',
      'Arquitetura papilar e cística.',
      'Ausência de atipia, necrose tumoral e mitoses; infarto após punção pode simular carcinoma escamoso.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'p63', pct: [80, 95], note: 'camada basal' },
      { marker: 'cd45', pct: [95, 100], note: 'só o estroma linfoide, que é policlonal' },
      { marker: 'cd20', pct: [90, 100], note: 'folículos' },
      { marker: 'cd3', pct: [90, 100], note: 'zona interfolicular' },
      { marker: 'sox10', pct: [10, 40] },
      { marker: 's100', pct: [10, 30] },
      { marker: 'dog1', pct: [0, 10] },
      { marker: 'p53', pct: [0, 5] },
      { marker: 'ki67', pct: [1, 5], note: 'alto só nos centros germinativos' },
    ],
    mimics: [
      'Carcinoma mucoepidermoide com estroma linfoide: células mucosas e intermediárias, MAML2 rearranjado.',
      'Cisto linfoepitelial: revestimento escamoso, sem oncócitos bicamada, associado a HIV.',
      'Oncocitoma: sem estroma linfoide, sem papilas císticas.',
      'Metástase linfonodal intraparotídea: atipia, arquitetura destrutiva.',
    ],
    pitfalls: ['Infarto pós-punção causa metaplasia escamosa atípica e pode ser lido como carcinoma escamoso ou mucoepidermoide.'],
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-mucoepidermoide',
    name: 'Carcinoma mucoepidermoide',
    aka: ['CME', 'mucoepidermoid carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 3 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'escamoso', 'anel-sinete', 'claras'],
    architecture: ['cistico', 'ninhos', 'lencois'],
    features: ['mucina', 'linfoide', 'mitoses-raras', 'necrose'],
    ages: ['jovem', 'adulto'],
    summary: 'O carcinoma salivar mais comum e o mais comum na criança: mistura de células mucosas, intermediárias e epidermoides em proporções variáveis, com cistos cheios de mucina nos de baixo grau e lençóis sólidos nos de alto grau; a fusão CRTC1::MAML2 confirma e traz bom prognóstico.',
    criteria: [
      'Presença simultânea de células mucosas (mucicarmim ou PAS-diastase positivas), intermediárias e epidermoides.',
      'Ausência de queratinização franca com pérolas: se houver, pense em carcinoma escamoso.',
      'Graduação por sistema de pontos (componente cístico, invasão perineural, necrose, mitoses, anaplasia).',
      'Rearranjo de MAML2 confirma em casos sólidos e de alto grau e afasta carcinoma escamoso.',
      'p63 e p40 marcam as intermediárias e epidermoides; as mucosas são negativas.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'intermediárias e epidermoides' },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'muc5ac', pct: [70, 90], note: 'células mucosas' },
      { marker: 'ck14', pct: [60, 85] },
      { marker: 's100', pct: [5, 20], note: 'fraca; difusa favorece secretor' },
      { marker: 'sox10', pct: [5, 25], note: 'baixa, ao contrário do acinar e do secretor' },
      { marker: 'dog1', pct: [0, 10], note: 'negativa; separa do acinar' },
      { marker: 'mamaglobina', pct: [0, 15], note: 'negativa; o secretor é difusamente positivo' },
      { marker: 'pan-trk', pct: [0, 5] },
      { marker: 'ki67', pct: [5, 40], note: 'sobe com o grau' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma escamoso: queratinização, sem células mucosas, sem MAML2.',
      'Cistadenoma e metaplasia mucosa: sem componente intermediário sólido nem invasão.',
      'Carcinoma secretor: SOX10, S100 e mamaglobina difusos, ETV6::NTRK3.',
      'Carcinoma de células claras hialinizante: monomórfico, EWSR1::ATF1, sem células mucosas.',
    ],
    molecular: 'Fusão CRTC1::MAML2 (ou CRTC3::MAML2) na maioria dos de baixo e grau intermediário.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-adenoide-cistico',
    name: 'Carcinoma adenoide cístico',
    aka: ['CAC', 'adenoid cystic carcinoma', 'cilindroma (uso antigo)'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 3 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'nariz-seios', role: 'primario', freq: 2 },
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['basaloide', 'epitelioide'],
    architecture: ['cribriforme', 'trabecular', 'lencois', 'glandulas'],
    features: ['hialinizacao', 'perineural', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Proliferação bifásica de células basaloides de núcleo anguloso e citoplasma escasso, formando cribras cheias de material de membrana basal e mucina azul, com invasão perineural quase obrigatória; cresce devagar por décadas e mata por recidiva local e metástase pulmonar tardia.',
    criteria: [
      'Padrão cribriforme, tubular ou sólido, com predomínio de células mioepiteliais abluminais e ductos verdadeiros mínimos.',
      'Pseudocistos preenchidos por material de membrana basal (eosinofílico hialino) e mucina basofílica.',
      'Invasão perineural presente na grande maioria e altamente sugestiva.',
      'Componente sólido acima de 30% define o alto grau e piora muito o prognóstico.',
      'MYB nuclear ou rearranjo MYB::NFIB apoiam quando a morfologia é limítrofe.',
    ],
    markers: [
      { marker: 'myb', pct: [70, 90], note: 'reflete a fusão MYB::NFIB ou MYBL1. Fortemente dependente do clone e do ponto de corte: as séries vão de 26 a 97%, então valide o seu anticorpo antes de confiar num negativo' },
      { marker: 'cd117', pct: [85, 100], note: 'luminal; sensível mas nada específica' },
      { marker: 'p63', pct: [90, 100], note: 'abluminal, padrão em cesto ao redor das cribras' },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 's100', pct: [70, 90] },
      { marker: 'calponina', pct: [85, 100] },
      { marker: 'sma', pct: [60, 85] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'plag1', pct: [0, 10], note: 'negativa; separa do adenoma pleomórfico celular' },
      { marker: 'er', pct: [0, 10] },
      { marker: 'ki67', pct: [5, 30], note: 'acima de 20% acompanha transformação de alto grau' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma pleomórfico celular: PLAG1 positivo, estroma condroide, sem invasão perineural.',
      'Adenocarcinoma polimorfo: mais no palato, células monótonas com núcleo vesiculoso, padrões de fila indiana e alvo, PRKD1 mutado.',
      'Carcinoma basaloide escamoso: sem padrão bifásico, p16 possível, necrose comedo.',
      'Adenocarcinoma cribriforme de língua e salivares menores: nuclear claro, mais nodular.',
    ],
    pitfalls: ['CD117 positivo não é específico: marca também o adenoma pleomórfico e o carcinoma epitelial-mioepitelial.'],
    molecular: 'Fusão MYB::NFIB na maioria; MYBL1::NFIB em parte.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-acinar-salivar',
    name: 'Carcinoma de células acinares salivar',
    aka: ['acinic cell carcinoma', 'carcinoma de células acinares de parótida'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'oncocitico', 'claras', 'glandular'],
    architecture: ['lencois', 'micropapilar', 'cistico', 'folicular'],
    features: ['linfoide', 'mitoses-raras', 'hemorragia'],
    ages: ['jovem', 'adulto'],
    summary: 'Carcinoma de parótida feito de células serosas com grânulos de zimogênio basofílicos, muitas vezes em lençóis sólidos sem atipia, que pode simular parênquima normal na biópsia; DOG1 com padrão apical em membrana e NR4A3 nuclear são os dois marcadores úteis.',
    criteria: [
      'Diferenciação acinar serosa: grânulos de zimogênio PAS-diastase resistentes, mesmo que focais.',
      'Padrões sólido, microcístico, papilar-cístico e folicular, isolados ou misturados.',
      'DOG1 com marcação apical e membranosa, e não citoplasmática difusa.',
      'NR4A3 nuclear confirma; o subtipo esclerosante rico em microcistos é o que mais confunde.',
      'Transformação de alto grau é definida por necrose, anaplasia e Ki-67 alto sobre o componente clássico.',
    ],
    markers: [
      { marker: 'dog1', pct: [85, 100], note: 'apical e membranoso; é o padrão que conta' },
      { marker: 'nr4a3', pct: [80, 95], note: 'substituto do rearranjo de NR4A3' },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'ck7', pct: [50, 80], note: 'menos constante que nos outros salivares' },
      { marker: 's100', pct: [10, 40], note: 'fraca; difusa e forte favorece secretor' },
      { marker: 'mamaglobina', pct: [0, 15], note: 'negativa; separa do secretor' },
      { marker: 'p63', pct: [0, 10], note: 'sem componente mioepitelial' },
      { marker: 'p40', pct: [0, 5] },
      { marker: 'ttf1', pct: [0, 10], note: 'cuidado com o padrão folicular, que imita tireoide' },
      { marker: 'tireoglobulina', pct: 0 },
      { marker: 'ki67', pct: [1, 10], note: 'alto na transformação de alto grau' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma secretor: mamaglobina, S100 e SOX10 difusos, ETV6::NTRK3, DOG1 negativo.',
      'Parênquima salivar normal em biópsia: mantém lóbulos e ductos, tem cápsula e ácinos organizados.',
      'Oncocitoma e carcinoma oncocítico: sem grânulos de zimogênio, DOG1 negativo.',
      'Metástase de carcinoma folicular de tireoide: tireoglobulina e TTF-1 positivos.',
    ],
    molecular: 'Rearranjo de NR4A3 (t(4;9), enhancer hijacking) na quase totalidade.',
    sources: [WHO, SEETHALA, 'Haller et al., Nat Commun (2019), NR4A3 no carcinoma de células acinares'],
  },
  {
    id: 'carcinoma-secretor',
    name: 'Carcinoma secretor',
    aka: ['carcinoma secretor análogo ao mamário', 'MASC', 'secretory carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'boca', role: 'primario', freq: 1 },
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular', 'oncocitico'],
    architecture: ['cistico', 'papilar', 'lencois', 'folicular'],
    features: ['mucina', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Carcinoma de baixo grau com microcistos e folículos cheios de secreção eosinofílica densa, células de citoplasma vacuolizado abundante e núcleo vesiculoso com nucléolo central; a tríade S100, mamaglobina e SOX10 com DOG1 negativo aponta a fusão ETV6::NTRK3, que é alvo terapêutico.',
    criteria: [
      'Microcistos, túbulos e folículos com material secretor eosinofílico intraluminal, PAS-diastase resistente e mucicarmim positivo.',
      'Ausência de grânulos de zimogênio basofílicos (que definiriam acinar).',
      'Coexpressão difusa de S100, mamaglobina e SOX10, com DOG1 negativo.',
      'Confirmação por ETV6::NTRK3 (FISH ou sequenciamento) quando se cogita terapia com inibidor de TRK.',
      'Transformação de alto grau existe e muda a conduta.',
    ],
    markers: [
      { marker: 's100', pct: [95, 100], note: 'difusa e forte; é a marca' },
      { marker: 'mamaglobina', pct: [90, 100] },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'gcdfp15', pct: [40, 70] },
      { marker: 'pan-trk', pct: [80, 95], note: 'nuclear e citoplasmática; reflete a fusão NTRK3' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'dog1', pct: [0, 10], note: 'o negativo que separa do acinar' },
      { marker: 'p63', pct: [0, 10] },
      { marker: 'p40', pct: [0, 5] },
      { marker: 'nr4a3', pct: 0 },
      { marker: 'er', pct: [0, 10] },
      { marker: 'trps1', pct: [30, 70], note: 'não prova origem mamária aqui' },
      { marker: 'ki67', pct: [2, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma de células acinares: DOG1 apical, NR4A3, grânulos de zimogênio, mamaglobina negativa.',
      'Carcinoma mucoepidermoide de baixo grau: p63 e p40 difusos, células intermediárias, MAML2.',
      'Adenocarcinoma polimorfo: palato, fila indiana, PRKD1.',
      'Metástase de carcinoma mamário: a imuno é a mesma; o contexto clínico decide.',
    ],
    molecular: 'Fusão ETV6::NTRK3 na maioria; variantes ETV6::RET e outras existem.',
    sources: [WHO, SEETHALA, 'Skálová et al., Am J Surg Pathol (2010), carcinoma secretor análogo ao mamário'],
  },
  {
    id: 'adenocarcinoma-polimorfo',
    name: 'Adenocarcinoma polimorfo',
    aka: ['adenocarcinoma polimorfo de baixo grau', 'polymorphous adenocarcinoma', 'PAC'],
    behavior: 'maligno',
    sites: [
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'salivares', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular', 'basaloide'],
    architecture: ['glandulas', 'cribriforme', 'papilar', 'trabecular', 'fila-indiana', 'infiltrativo'],
    features: ['perineural', 'hialinizacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma de glândula salivar menor do palato com células uniformes de núcleo vesiculoso pálido e citoplasma escasso, que adota muitos padrões arquiteturais dentro do mesmo tumor, com crescimento em fila indiana e em alvo concêntrico ao redor de nervos e vasos.',
    criteria: [
      'Uniformidade citológica com diversidade arquitetural: o contrário do adenoide cístico.',
      'Núcleos vesiculosos, pálidos, sobrepostos, lembrando carcinoma papilífero de tireoide.',
      'Crescimento infiltrativo em fila indiana e padrão de alvo perineural.',
      'Sítio: glândula salivar menor, sobretudo palato duro-mole.',
      'A variante cribriforme (de língua) tem mais metástase nodal e núcleo mais claro.',
    ],
    markers: [
      { marker: 's100', pct: [90, 100], note: 'difusa e forte' },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ema', pct: [70, 90] },
      { marker: 'bcl2', pct: [70, 90] },
      { marker: 'p63', pct: [50, 80], note: 'positivo, mas p40 negativo: a dissociação é típica' },
      { marker: 'p40', pct: [0, 15], note: 'o negativo que separa do adenoide cístico' },
      { marker: 'calponina', pct: [10, 40] },
      { marker: 'myb', pct: [10, 30] },
      { marker: 'cd117', pct: [10, 40] },
      { marker: 'mamaglobina', pct: [20, 50] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma adenoide cístico: p40 positivo, células anguladas hipercromáticas, MYB.',
      'Adenoma pleomórfico: PLAG1, estroma condroide, sem invasão.',
      'Carcinoma papilífero de tireoide metastático: TTF-1 e tireoglobulina.',
      'Carcinoma mioepitelial: sem componente ductal, p40 difuso.',
    ],
    pitfalls: ['A dissociação p63 positivo com p40 negativo é um dos poucos lugares da patologia em que ela é diagnóstica.'],
    molecular: 'Mutação PRKD1 E710D no clássico; fusões PRKD1/2/3 na variante cribriforme.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-ductos-salivares',
    name: 'Carcinoma de ductos salivares',
    aka: ['salivary duct carcinoma', 'SDC'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'glandular', 'pleomorfico', 'oncocitico'],
    architecture: ['cribriforme', 'papilar', 'ninhos', 'glandulas'],
    features: ['necrose', 'mitoses-altas', 'desmoplasia', 'perineural', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Carcinoma salivar de alto grau que reproduz o carcinoma ductal da mama, com cribras e necrose comedo dentro dos ductos e invasão desmoplásica em volta; quase sempre receptor de androgênio positivo, e uma parte é HER2 amplificada, o que abre tratamento alvo.',
    criteria: [
      'Morfologia de carcinoma ductal mamário de alto grau: cribriforme, papilar e sólido com necrose comedo.',
      'Receptor de androgênio nuclear difuso na grande maioria.',
      'ER e PR negativos (a positividade de ER sugere metástase mamária).',
      'HER2 e AR devem ser testados em todo caso: definem terapia.',
      'Pode surgir sobre adenoma pleomórfico (carcinoma ex-adenoma pleomórfico de tipo ductal).',
    ],
    markers: [
      { marker: 'ar', pct: [70, 95], note: 'difuso e nuclear; critério de apoio' },
      { marker: 'gcdfp15', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'her2', pct: [20, 45], note: 'o "positivo" é 3+ ou amplificado; define terapia anti-HER2' },
      { marker: 'ema', pct: [90, 100] },
      { marker: 'er', pct: [0, 10], note: 'o negativo que afasta metástase mamária' },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'gata3', pct: [60, 90], note: 'positivo; não use para dizer que é mama' },
      { marker: 'trps1', pct: [20, 50] },
      { marker: 'p63', pct: [0, 15], note: 'só mioepitélio residual no componente in situ' },
      { marker: 'sox10', pct: [0, 15], note: 'negativo, ao contrário da maioria dos salivares' },
      { marker: 's100', pct: [0, 15] },
      { marker: 'p53', pct: [50, 75] },
      { marker: 'ki67', pct: [40, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de carcinoma mamário: ER frequentemente positivo, história de mama.',
      'Carcinoma mucoepidermoide de alto grau: p63 e p40 difusos, células mucosas, MAML2.',
      'Carcinoma oncocítico: sem necrose comedo nem AR difuso.',
      'Carcinoma de células escamosas metastático na parótida: p40 difuso, sem AR.',
    ],
    pitfalls: ['SOX10 negativo num carcinoma de parótida é achado útil: quase todos os outros salivares são positivos.'],
    molecular: 'Amplificação de HER2 em parte; mutações de PIK3CA, HRAS e TP53; perda de PTEN.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-epitelial-mioepitelial',
    name: 'Carcinoma epitelial-mioepitelial',
    aka: ['epithelial-myoepithelial carcinoma', 'EMC'],
    behavior: 'maligno',
    sites: [{ site: 'salivares', role: 'primario', freq: 1 }],
    cells: ['claras', 'epitelioide', 'glandular'],
    architecture: ['glandulas', 'ninhos', 'lobular'],
    features: ['hialinizacao', 'mitoses-raras', 'perineural'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor bifásico de arquitetura tubular em que cada ducto tem uma camada luminal eosinofílica e uma camada externa nítida de células mioepiteliais de citoplasma claro, separadas por membrana basal espessa; baixo grau, com recidivas locais.',
    criteria: [
      'Padrão bifásico com camada mioepitelial externa de células claras bem evidente ao redor de ductos luminais.',
      'Membrana basal espessa em torno dos ninhos, marcada por colágeno IV ou PAS.',
      'Confirmação imuno-histoquímica das duas camadas: queratinas luminais mais p63, calponina e SMA abluminais.',
      'Crescimento lobulado com invasão, sem cápsula íntegra.',
      'Transformação de alto grau (dediferenciação) é rara e piora muito o prognóstico.',
    ],
    markers: [
      { marker: 'p63', pct: [90, 100], note: 'camada mioepitelial' },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'calponina', pct: [90, 100] },
      { marker: 'sma', pct: [80, 95] },
      { marker: 's100', pct: [85, 100], note: 'mioepitélio' },
      { marker: 'sox10', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100], note: 'luminal' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ema', pct: [80, 95], note: 'luminal' },
      { marker: 'colageno-iv', pct: [85, 100], note: 'membrana basal espessa em volta dos ninhos' },
      { marker: 'cd117', pct: [50, 80], note: 'luminal; não é específica' },
      { marker: 'caix', pct: [0, 15], note: 'ajuda contra metástase de RCC de células claras' },
      { marker: 'pax8', pct: [0, 10] },
      { marker: 'ki67', pct: [2, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de carcinoma renal de células claras: PAX8 e CA-IX positivos, sem camada mioepitelial.',
      'Carcinoma de células claras hialinizante: monofásico, p63 positivo mas sem camada luminal, EWSR1::ATF1.',
      'Mioepitelioma de células claras: sem componente ductal.',
      'Carcinoma mucoepidermoide de células claras: células mucosas, MAML2.',
    ],
    molecular: 'Mutações de HRAS (Q61) na maioria.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-mioepitelial',
    name: 'Carcinoma mioepitelial',
    aka: ['mioepitelioma maligno', 'myoepithelial carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 1 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
      { site: 'boca', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'plasmocitoide', 'claras'],
    architecture: ['lobular', 'lencois', 'ninhos'],
    features: ['estroma-mixoide', 'necrose', 'mitoses-moderadas', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Proliferação puramente mioepitelial, sem ductos verdadeiros, com células epitelioides, plasmocitoides, claras ou fusiformes em nódulos com centro mixoide e periferia celular; o diagnóstico exige provar a linhagem mioepitelial e demonstrar invasão.',
    criteria: [
      'Ausência de diferenciação ductal verdadeira: só células mioepiteliais.',
      'Prova de linhagem: queratina (ou EMA) positiva junto com p63, calponina, SMA ou S100.',
      'Invasão destrutiva, necrose ou atipia acentuada separam do mioepitelioma benigno.',
      'Padrão de nódulos multilobulados com zonação mixoide central é característico.',
      'Muitos surgem sobre adenoma pleomórfico prévio.',
    ],
    markers: [
      { marker: 'p63', pct: [80, 95] },
      { marker: 'p40', pct: [50, 80] },
      { marker: 's100', pct: [85, 100] },
      { marker: 'sox10', pct: [85, 100] },
      { marker: 'calponina', pct: [70, 90] },
      { marker: 'sma', pct: [50, 80] },
      { marker: 'ae1ae3', pct: [80, 95] },
      { marker: 'ema', pct: [60, 85] },
      { marker: 'gfap', pct: [20, 50] },
      { marker: 'plag1', pct: [30, 60], note: 'quando nasce de adenoma pleomórfico' },
      { marker: 'ini1', pct: [10, 40], note: 'o positivo é a perda; ocorre em parte dos mioepiteliais de partes moles' },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Mioepitelioma benigno: sem invasão, sem necrose, Ki-67 baixo.',
      'Carcinoma epitelial-mioepitelial: tem camada luminal ductal.',
      'Melanoma: SOX10 e S100 positivos também, mas HMB-45 e Melan-A positivos e queratina negativa.',
      'Sarcoma mixoide (condrossarcoma mixoide extraesquelético): queratina e p63 negativos.',
    ],
    pitfalls: ['SOX10 e S100 positivos com queratina fraca podem levar a melanoma; peça HMB-45 e Melan-A.'],
    sources: [WHO, SEETHALA],
  },
  {
    id: 'carcinoma-ex-adenoma-pleomorfico',
    name: 'Carcinoma ex-adenoma pleomórfico',
    aka: ['carcinoma em adenoma pleomórfico', 'carcinoma ex-pleomorphic adenoma'],
    behavior: 'maligno',
    sites: [
      { site: 'salivares', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'glandular', 'pleomorfico'],
    architecture: ['ninhos', 'cribriforme', 'lencois'],
    features: ['necrose', 'mitoses-altas', 'hialinizacao', 'desmoplasia', 'perineural', 'calcificacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma que surge dentro de um adenoma pleomórfico, muitas vezes de longa data: o resíduo benigno aparece como área hialinizada e calcificada na periferia, e o componente maligno é em geral um carcinoma de ductos salivares ou um adenocarcinoma de alto grau.',
    criteria: [
      'Demonstração do adenoma pleomórfico residual (áreas condromixoides ou nódulo hialinizado cicatricial).',
      'Componente carcinomatoso identificado e tipado (ductos salivares na maioria).',
      'Classificação pela extensão da invasão além da cápsula do adenoma: intracapsular, minimamente invasivo (até 4 a 6 mm) ou francamente invasivo, que muda o prognóstico radicalmente.',
      'PLAG1 positivo nos dois componentes apoia a origem comum.',
    ],
    markers: [
      { marker: 'plag1', pct: [60, 90], note: 'persiste no componente maligno e confirma a origem' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ar', pct: [50, 80], note: 'quando o componente maligno é de ductos salivares' },
      { marker: 'her2', pct: [20, 45] },
      { marker: 'gcdfp15', pct: [50, 80] },
      { marker: 'p63', pct: [30, 70], note: 'no resíduo benigno e no componente mioepitelial' },
      { marker: 's100', pct: [40, 70], note: 'no resíduo benigno' },
      { marker: 'sox10', pct: [30, 70] },
      { marker: 'p53', pct: [50, 75], note: 'no componente maligno' },
      { marker: 'ki67', pct: [30, 80], note: 'a diferença entre os dois componentes é o achado útil' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma pleomórfico celular ou atípico: sem invasão, Ki-67 baixo, p53 selvagem.',
      'Carcinoma de ductos salivares de novo: sem resíduo de adenoma pleomórfico.',
      'Adenoma pleomórfico metastatizante: histologia benigna nos dois sítios.',
    ],
    molecular: 'Rearranjo de PLAG1 herdado do adenoma, somado a TP53, HER2 e outras alterações.',
    sources: [WHO, SEETHALA],
  },
  {
    id: 'papilifero-tireoide',
    name: 'Carcinoma papilífero de tireoide',
    aka: ['CPT', 'papillary thyroid carcinoma', 'variante folicular invasiva'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular', 'oncocitico'],
    architecture: ['papilar', 'folicular', 'trabecular', 'infiltrativo'],
    features: ['sulcos-inclusoes', 'psamomas', 'desmoplasia', 'mitoses-raras'],
    ages: ['jovem', 'adulto', 'idoso'],
    sex: 'f',
    summary: 'O carcinoma de tireoide mais comum: o diagnóstico é feito pelo núcleo, não pela papila — aumentado, oval, sobreposto, com cromatina clara em vidro fosco, sulcos longitudinais e pseudoinclusões; corpos psamomatosos e desmoplasia apoiam, e a metástase nodal cervical é regra e não muda muito o prognóstico.',
    criteria: [
      'Núcleos papilíferos: aumento e alongamento, sobreposição, cromatina clara marginada, membrana nuclear irregular, sulcos e pseudoinclusões.',
      'Escore nuclear de três pontos (tamanho/forma, membrana, cromatina) aplicado sistematicamente.',
      'Papilas verdadeiras com eixo fibrovascular, quando presentes; a variante folicular não as tem.',
      'Corpos psamomatosos são altamente específicos, mas pouco sensíveis.',
      'Invasão capsular ou vascular é necessária nas lesões foliculares encapsuladas com núcleo papilífero (senão, NIFTP).',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'tireoglobulina', pct: [90, 100], note: 'pode ser fraca nos pouco diferenciados' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [85, 100], note: 'forte e difusa; no folicular benigno é focal' },
      { marker: 'hbme1', pct: [80, 95] },
      { marker: 'galectina3', pct: [80, 95] },
      { marker: 'brafv600e', pct: [50, 80], note: 'clone VE1; quase todos os clássicos, poucos dos foliculares' },
      { marker: 'ck20', pct: 0 },
      { marker: 'calcitonina', pct: 0, note: 'o negativo que afasta medular' },
      { marker: 'cea', pct: [0, 10] },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'NIFTP: encapsulado, núcleo papilífero, sem invasão, sem papilas verdadeiras, sem psamomas.',
      'Adenoma folicular com alterações reativas: núcleo sem cromatina clara nem sulcos, CK19 focal.',
      'Carcinoma medular: calcitonina e CEA positivos, tireoglobulina negativa.',
      'Adenocarcinoma polimorfo salivar metastático: TTF-1 negativo.',
      'Hiperplasia papilar de doença de Graves: sem atipia nuclear, difusa.',
    ],
    pitfalls: ['HBME-1 e galectina-3 marcam algumas lesões benignas; nunca diagnostique por eles sem o núcleo.'],
    molecular: 'BRAF V600E na maioria dos clássicos; fusões RET/PTC e NTRK; RAS nas variantes foliculares.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'nift-p',
    name: 'Neoplasia folicular tireoidiana não invasiva com núcleos de tipo papilífero (NIFTP)',
    aka: ['NIFTP', 'variante folicular encapsulada não invasiva'],
    behavior: 'intermediario',
    sites: [{ site: 'tireoide', role: 'primario', freq: 2 }],
    cells: ['epitelioide', 'glandular'],
    architecture: ['folicular', 'cistico'],
    features: ['sulcos-inclusoes', 'mitoses-raras', 'coloide'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Nódulo encapsulado ou bem delimitado, inteiramente folicular, cujos núcleos têm alterações de tipo papilífero mas sem qualquer invasão capsular ou vascular; foi retirado da categoria de carcinoma justamente porque não recidiva nem metastatiza quando os critérios são cumpridos com rigor.',
    criteria: [
      'Encapsulado ou claramente delimitado.',
      'Padrão folicular em mais de 99% (sem papilas verdadeiras).',
      'Escore nuclear papilífero de 2 a 3 pontos.',
      'Ausência absoluta de invasão capsular e vascular, examinando toda a cápsula.',
      'Ausência de corpos psamomatosos, necrose tumoral e mais de 3 mitoses por 10 campos de grande aumento.',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'tireoglobulina', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [30, 60], note: 'em geral focal, ao contrário do papilífero clássico' },
      { marker: 'hbme1', pct: [50, 80] },
      { marker: 'galectina3', pct: [30, 60] },
      { marker: 'brafv600e', pct: [0, 5], note: 'praticamente ausente; se positivo, reveja o diagnóstico' },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Variante folicular invasiva do papilífero: qualquer invasão capsular ou vascular a exclui.',
      'Adenoma folicular: sem alterações nucleares papilíferas.',
      'Carcinoma folicular: invasão, sem núcleo papilífero.',
    ],
    pitfalls: ['O diagnóstico exige a cápsula inteira submetida; em punção ou fragmento não se pode fazer NIFTP.'],
    molecular: 'Mutações de RAS na maioria; BRAF V600E praticamente ausente.',
    sources: [WHO, 'Nikiforov et al., JAMA Oncol (2016), proposta do NIFTP', LIVOLSI],
  },
  {
    id: 'carcinoma-folicular-tireoide',
    name: 'Carcinoma folicular de tireoide',
    aka: ['follicular thyroid carcinoma', 'carcinoma folicular minimamente invasivo'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'glandular'],
    architecture: ['folicular', 'trabecular'],
    features: ['coloide', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Neoplasia folicular encapsulada sem núcleos papilíferos cujo diagnóstico depende exclusivamente da demonstração de invasão capsular transfixante ou invasão vascular na cápsula ou fora dela; metastatiza por via hematogênica para osso e pulmão, às vezes antes de o nódulo dar sintoma.',
    criteria: [
      'Padrão folicular puro, sem alterações nucleares de tipo papilífero.',
      'Invasão capsular de espessura total, com tumor atravessando toda a cápsula.',
      'Ou invasão vascular: ninhos tumorais aderidos à parede de vaso dentro ou além da cápsula, cobertos por endotélio, com trombo.',
      'Classificação em minimamente invasivo, encapsulado angioinvasivo (menos ou mais de 4 focos) e amplamente invasivo, com prognósticos distintos.',
      'Amostragem da cápsula inteira é obrigatória.',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'tireoglobulina', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'cd31', pct: [0, 5], note: 'usada para provar que o foco está dentro de vaso' },
      { marker: 'erg', pct: [0, 5], note: 'idem, no endotélio que reveste o êmbolo' },
      { marker: 'ck19', pct: [10, 40], note: 'focal' },
      { marker: 'hbme1', pct: [40, 70] },
      { marker: 'galectina3', pct: [40, 70] },
      { marker: 'brafv600e', pct: [0, 5] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma folicular: sem invasão, mesma citologia.',
      'Carcinoma papilífero variante folicular: núcleos papilíferos.',
      'Carcinoma oncocítico: células oncocíticas em mais de 75%, perfil molecular distinto.',
      'Metástase de carcinoma renal ou de NET no nódulo tireoidiano: tireoglobulina negativa.',
    ],
    pitfalls: ['Artefato de punção prévia produz pseudoinvasão capsular com hemossiderina e fibrose linear; procure o trajeto.'],
    molecular: 'Mutações de RAS e fusão PAX8::PPARG.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'carcinoma-oncocitico-tireoide',
    name: 'Carcinoma oncocítico de tireoide',
    aka: ['carcinoma de células de Hürthle', 'Hürthle cell carcinoma', 'oncocytic carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['oncocitico', 'epitelioide'],
    architecture: ['folicular', 'trabecular', 'lencois'],
    features: ['nucleolo', 'mitoses-raras', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    summary: 'Neoplasia de células oncocíticas em mais de três quartos do tumor, com citoplasma granular eosinofílico abundante e nucléolo proeminente, definida como maligna pelos mesmos critérios de invasão do folicular; capta pouco iodo, o que muda o tratamento.',
    criteria: [
      'Mais de 75% de células oncocíticas (citoplasma granular eosinofílico por acúmulo de mitocôndrias).',
      'Invasão capsular transfixante ou invasão vascular, como no folicular.',
      'Ausência de núcleos de tipo papilífero (senão é variante oncocítica do papilífero).',
      'Necrose tumoral e mitoses numerosas indicam alto grau e mudam o prognóstico.',
    ],
    markers: [
      { marker: 'ttf1', pct: [90, 100] },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'tireoglobulina', pct: [70, 95], note: 'costuma ser mais fraca que no folicular clássico' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [30, 70] },
      { marker: 'hbme1', pct: [40, 70] },
      { marker: 'galectina3', pct: [50, 80] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'cromogranina', pct: [0, 10], note: 'o negativo que separa de paraganglioma e medular' },
      { marker: 'pth', pct: 0, note: 'afasta paratireoide oncocítica' },
      { marker: 'gata3', pct: [0, 10], note: 'idem' },
      { marker: 'brafv600e', pct: [0, 5] },
      { marker: 'ki67', pct: [2, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenoma oncocítico: sem invasão.',
      'Adenoma ou carcinoma de paratireoide oncocítico: PTH e GATA3 positivos, TTF-1 negativo.',
      'Carcinoma medular: calcitonina positiva.',
      'Metástase de carcinoma renal oncocítico e de HCC: PAX8 no renal, HepPar-1 e arginase no hepático.',
    ],
    molecular: 'Alterações mitocondriais de DNA e perdas cromossômicas amplas; RAS menos frequente que no folicular.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'carcinoma-medular-tireoide',
    name: 'Carcinoma medular de tireoide',
    aka: ['CMT', 'medullary thyroid carcinoma', 'carcinoma de células C'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
    ],
    cells: ['neuroendocrino', 'fusocelular', 'plasmocitoide', 'epitelioide', 'oncocitico'],
    architecture: ['ninhos', 'lencois', 'trabecular', 'organoide'],
    features: ['amiloide', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor das células C parafoliculares, em ninhos de células fusiformes ou plasmocitoides com cromatina em sal e pimenta, frequentemente com estroma amiloide; calcitonina positiva e tireoglobulina negativa, e um quarto dos casos é hereditário (RET germinativo, NEM 2).',
    criteria: [
      'Calcitonina positiva nas células tumorais (pode ser focal ou fraca nos pouco diferenciados).',
      'Tireoglobulina negativa, com o parênquima vizinho servindo de controle positivo.',
      'Marcadores neuroendócrinos positivos: sinaptofisina, cromogranina, INSM1.',
      'Amiloide estromal (vermelho Congo) quando presente, mas não obrigatório.',
      'Calcitonina sérica e CEA elevados; pesquisa de RET germinativo em todo caso.',
    ],
    markers: [
      { marker: 'calcitonina', pct: [85, 100], note: 'o critério; pode faltar em variantes pouco diferenciadas' },
      { marker: 'tireoglobulina', pct: 0, note: 'o negativo obrigatório' },
      { marker: 'cea', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [90, 100] },
      { marker: 'cromogranina', pct: [85, 100] },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'ttf1', pct: [70, 95], note: 'positivo: não use TTF-1 para separar de folicular' },
      { marker: 'pax8', pct: [10, 40], note: 'clone monoclonal costuma ser negativo' },
      { marker: 'ae1ae3', pct: [85, 100] },
      { marker: 'ck7', pct: [10, 40] },
      { marker: 'ck20', pct: 0 },
      { marker: 'gata3', pct: [10, 40] },
      { marker: 's100', pct: [10, 30], note: 'sustentaculares periféricas em alguns' },
      { marker: 'ki67', pct: [2, 20], note: 'acima de 5% acompanha alto grau' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma folicular ou papilífero de padrão sólido: tireoglobulina positiva, calcitonina negativa.',
      'Paraganglioma cervical: queratina negativa, GATA3 positiva, sustentaculares.',
      'Metástase de NET de outro sítio: calcitonina negativa, CDX2 ou ilhotas conforme a origem.',
      'Hialinizante trabecular: MIB-1 de membrana, PAX8 positivo, calcitonina negativa.',
    ],
    pitfalls: ['TTF-1 positivo é a regra no medular e leva a erro quem o usa como prova de origem folicular.'],
    molecular: 'RET mutado (germinativo nas NEM 2A/2B, somático em metade dos esporádicos); RAS nos RET-negativos.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'carcinoma-pouco-diferenciado-tireoide',
    name: 'Carcinoma pouco diferenciado de tireoide',
    aka: ['carcinoma insular', 'poorly differentiated thyroid carcinoma', 'critérios de Turim'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'pequenas-redondas'],
    architecture: ['ninhos', 'trabecular', 'lencois'],
    features: ['necrose', 'mitoses-moderadas', 'mitoses-altas'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma de origem folicular com crescimento sólido, insular ou trabecular, sem núcleos papilíferos, e com pelo menos um de três sinais de agressividade: mitoses frequentes, necrose tumoral ou núcleo convoluto; ocupa o espaço entre o diferenciado e o anaplásico.',
    criteria: [
      'Padrão sólido, insular ou trabecular predominante.',
      'Ausência de núcleos de tipo papilífero convencionais.',
      'Pelo menos um dos três: núcleos convolutos, 3 ou mais mitoses por 2 mm², ou necrose tumoral.',
      'Manutenção de diferenciação folicular demonstrável por TTF-1 e PAX8, com tireoglobulina ao menos focal.',
      'Ausência de anaplasia franca e de perda total de diferenciação (que definiria anaplásico).',
    ],
    markers: [
      { marker: 'ttf1', pct: [80, 95] },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'tireoglobulina', pct: [50, 85], note: 'focal e fraca, muitas vezes só perinuclear' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'p53', pct: [20, 40], note: 'aumenta na progressão para anaplásico' },
      { marker: 'sinaptofisina', pct: [0, 15] },
      { marker: 'ki67', pct: [10, 30] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma anaplásico: perda de TTF-1 e tireoglobulina, anaplasia franca, p53 aberrante.',
      'Carcinoma medular: calcitonina positiva.',
      'Carcinoma folicular sólido sem sinais de Turim: sem necrose nem mitoses.',
      'Metástase de carcinoma neuroendócrino: PAX8 e TTF-1 conforme o sítio, sinaptofisina difusa.',
    ],
    molecular: 'RAS e BRAF somados a TERT promotor, TP53 e alterações de PIK3CA.',
    sources: [WHO, 'Volante et al., Am J Surg Pathol (2007), proposta de Turim', LIVOLSI],
  },
  {
    id: 'carcinoma-anaplasico-tireoide',
    name: 'Carcinoma anaplásico de tireoide',
    aka: ['carcinoma indiferenciado de tireoide', 'anaplastic thyroid carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'tireoide', role: 'primario', freq: 2 },
      { site: 'pescoco', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
    ],
    cells: ['pleomorfico', 'fusocelular', 'epitelioide', 'gigantes', 'rabdoide'],
    architecture: ['lencois', 'fasciculos', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'hemorragia', 'desmoplasia'],
    ages: ['idoso'],
    summary: 'Massa cervical que cresce em semanas em paciente idoso, feita de células fusiformes, pleomórficas e gigantes com necrose ampla, mitoses atípicas e invasão de tudo em volta; perde TTF-1 e tireoglobulina, e o PAX8 é quase sempre o único resquício de linhagem tireoidiana.',
    criteria: [
      'Carcinoma indiferenciado com anaplasia franca: pleomorfismo extremo, mitoses atípicas, necrose.',
      'Origem tireoidiana demonstrada por PAX8, por componente diferenciado residual ou pela topografia.',
      'Exclusão de sarcoma (queratina ou PAX8 positivos), melanoma (SOX10), linfoma (CD45) e metástase.',
      'Pesquisa de BRAF V600E obrigatória: define terapia com dabrafenibe e trametinibe.',
      'Estadiamento sempre T4 e estádio IV.',
    ],
    markers: [
      { marker: 'pax8', pct: [50, 80], note: 'o mais persistente; clone policlonal é mais sensível' },
      { marker: 'ae1ae3', pct: [50, 80], note: 'pode ser focal ou negativa nos fusocelulares' },
      { marker: 'ttf1', pct: [10, 30], note: 'perdido na maioria' },
      { marker: 'tireoglobulina', pct: [0, 15], note: 'só em resíduo diferenciado aprisionado' },
      { marker: 'p53', pct: [60, 90] },
      { marker: 'brafv600e', pct: [30, 45], note: 'nos que vêm de papilífero; define terapia-alvo' },
      { marker: 'pdl1', pct: [20, 60] },
      { marker: 'vimentina', pct: [80, 100] },
      { marker: 'cd45', pct: 0 },
      { marker: 'sox10', pct: [0, 10] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'ki67', pct: [50, 95] },
    ],
    mimics: [
      'Sarcoma de alto grau da região cervical: PAX8 e queratina negativas.',
      'Linfoma difuso de grandes células B da tireoide: CD45 e CD20 positivos, em tireoidite de Hashimoto.',
      'Melanoma metastático: SOX10 positivo.',
      'Carcinoma escamoso de laringe invadindo a tireoide: p40 difuso, PAX8 negativo.',
      'Tireoidite de Riedel: fibrose densa sem atipia, IgG4.',
    ],
    molecular: 'TP53 e TERT promotor quase constantes, sobre BRAF ou RAS herdados do tumor diferenciado precursor.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'adenoma-paratireoide',
    name: 'Adenoma e carcinoma de paratireoide',
    aka: ['adenoma paratireóideo', 'parathyroid adenoma', 'parathyroid carcinoma'],
    behavior: 'intermediario',
    sites: [
      { site: 'paratireoide', role: 'primario', freq: 3 },
      { site: 'pescoco', role: 'primario', freq: 2 },
      { site: 'mediastino', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'claras', 'oncocitico'],
    architecture: ['ninhos', 'trabecular', 'folicular', 'lencois'],
    features: ['mitoses-raras', 'hemorragia', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    summary: 'Nódulo hipercelular de células principais com borda de tecido paratireóideo normal comprimido e sem adipócitos no interior, em paciente com hipercalcemia e PTH alto; o carcinoma se define por invasão franca ou metástase, e a perda de parafibromina aponta a via HRPT2.',
    criteria: [
      'Hipercelularidade com perda do estroma adiposo intralesional e borda de glândula normal comprimida.',
      'Confirmação de linhagem por PTH e GATA3, com TTF-1 e tireoglobulina negativos.',
      'Carcinoma exige invasão capsular transmural com reação desmoplásica, invasão vascular ou perineural, invasão de estruturas vizinhas ou metástase.',
      'Bandas fibrosas espessas, necrose e mitoses frequentes apoiam carcinoma mas isoladamente não bastam.',
      'Perda de parafibromina indica carcinoma ou síndrome hiperparatireoidismo-tumor de mandíbula.',
    ],
    markers: [
      { marker: 'pth', pct: [90, 100], note: 'o marcador definidor' },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cam52', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [50, 80] },
      { marker: 'cromogranina', pct: [70, 95] },
      { marker: 'ttf1', pct: 0, note: 'o negativo que separa da tireoide' },
      { marker: 'tireoglobulina', pct: 0 },
      { marker: 'pax8', pct: [0, 20], note: 'clone monoclonal negativo; policlonal pode marcar' },
      { marker: 'ck7', pct: [10, 40] },
      { marker: 'calcitonina', pct: 0 },
      { marker: 'ciclinad1', pct: [30, 70], note: 'superexpressa em parte dos adenomas' },
      { marker: 'rb1', pct: [10, 40], note: 'perda descrita em parte dos carcinomas' },
      { marker: 'ki67', pct: [1, 10], note: 'acima de 5% favorece carcinoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Nódulo tireoidiano de células claras: TTF-1 e tireoglobulina positivos.',
      'Hiperplasia paratireóidea: múltiplas glândulas aumentadas, sem borda normal comprimida.',
      'Paratireoide normal: adipócitos intralesionais preservados.',
      'Metástase de carcinoma renal de células claras: PAX8 e CA-IX positivos, PTH negativo.',
    ],
    molecular: 'Ciclina D1 (CCND1) e MEN1 nos adenomas; CDC73 (HRPT2) com perda de parafibromina nos carcinomas.',
    sources: [WHO, LIVOLSI],
  },
  {
    id: 'adenoma-folicular-tireoide',
    name: 'Adenoma folicular de tireoide',
    aka: ['adenoma folicular', 'follicular adenoma', 'adenoma oncocítico'],
    behavior: 'benigno',
    sites: [{ site: 'tireoide', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'glandular', 'oncocitico'],
    architecture: ['folicular', 'trabecular', 'lencois'],
    features: ['coloide', 'mitoses-raras', 'hialinizacao', 'hemorragia'],
    ages: ['jovem', 'adulto', 'idoso'],
    sex: 'f',
    summary: 'Nódulo folicular encapsulado, único, com arquitetura diferente do parênquima vizinho comprimido, sem núcleos de tipo papilífero e sem qualquer invasão capsular ou vascular; é a lesão tireoidiana neoplásica mais comum e a base contra a qual todo o resto do diferencial folicular é lido.',
    criteria: [
      'Cápsula fibrosa completa, com parênquima tireoidiano normal comprimido por fora dela.',
      'Arquitetura folicular (normofolicular, microfolicular, macrofolicular, trabecular ou sólida) distinta do fundo.',
      'Ausência de núcleos de tipo papilífero: se presentes e sem invasão, o diagnóstico é NIFTP.',
      'Ausência absoluta de invasão capsular transfixante e de invasão vascular, com a cápsula inteira submetida.',
      'Variante oncocítica quando mais de 75% das células são oncocíticas; variantes com atipia nuclear focal entram nas categorias de potencial incerto.',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'pax8', pct: [95, 100] },
      { marker: 'tireoglobulina', pct: [95, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ck19', pct: [10, 30], note: 'focal e fraca; forte e difusa favorece papilífero' },
      { marker: 'hbme1', pct: [10, 30], note: 'pode ser focalmente positivo: não use isolado para chamar de carcinoma' },
      { marker: 'galectina3', pct: [10, 35], note: 'idem' },
      { marker: 'brafv600e', pct: [0, 5] },
      { marker: 'calcitonina', pct: 0, note: 'o negativo que afasta medular' },
      { marker: 'cromogranina', pct: [0, 5] },
      { marker: 'pth', pct: 0, note: 'o negativo que afasta paratireoide, sobretudo na variante oncocítica' },
      { marker: 'gata3', pct: [0, 5] },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'ki67', pct: [1, 3] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma folicular: invasão capsular transfixante ou vascular; a citologia é idêntica.',
      'NIFTP: mesma arquitetura encapsulada, mas com núcleos de tipo papilífero.',
      'Nódulo hiperplásico da tireoide multinodular: sem cápsula completa, múltiplo, com o mesmo padrão do fundo.',
      'Adenoma de paratireoide intratireoidiano: PTH e GATA3 positivos, TTF-1 negativo.',
      'Metástase de carcinoma renal de células claras: PAX8 positivo nos dois, tireoglobulina negativa.',
    ],
    molecular: 'Mutações de RAS e fusão PAX8::PPARG podem estar presentes; a molecular não separa adenoma de carcinoma folicular.',
    sources: [WHO, LIVOLSI],
  },
]
