/* ==========================================================================
   skin.ts — tumores da pele e dos anexos cutâneos.

   As porcentagens são faixas de séries e revisões clássicas de imuno-
   histoquímica dermatopatológica (WHO Skin Tumours 4ª/5ª ed., Wick, Plaza &
   Prieto, revisões do Arch Pathol Lab Med e do Am J Dermatopathol). Cada
   faixa é a leitura corrente da literatura, não um número de um único
   estudo: o que separa "bate" de "bate por exceção" é a ordem de grandeza,
   não a casa decimal. Quando uma faixa ainda não foi conferida contra a
   série original, está dita em `note`.
   ========================================================================== */

import type { Tumor } from '../types'

export const skin: Tumor[] = [
  {
    id: 'carcinoma-basocelular',
    name: 'Carcinoma basocelular',
    aka: ['CBC', 'basalioma', 'basal cell carcinoma', 'BCC'],
    behavior: 'maligno',
    sites: [{ site: 'pele', role: 'primario', freq: 3 }],
    cells: ['basaloide', 'epitelioide'],
    architecture: ['ninhos', 'palicada', 'infiltrativo', 'trabecular'],
    features: ['estroma-mixoide', 'mitoses-moderadas', 'corpos-apoptoticos', 'desmoplasia'],
    ages: ['adulto', 'idoso'],
    summary: 'Ninhos de células basaloides com paliçada periférica, fendas de retração e estroma mixoide, em pele fotoexposta. O tumor maligno mais comum do ser humano.',
    criteria: [
      'Células basaloides monomorfas com escasso citoplasma, paliçada na periferia dos ninhos.',
      'Fenda de retração entre o ninho e o estroma mixoide peritumoral.',
      'Conexão com a epiderme ou com o folículo, em pele fotoexposta.',
      'BerEP4 positivo com EMA negativo separa do carcinoma espinocelular; PHLDA1 negativo separa do tricoepitelioma.',
    ],
    markers: [
      { marker: 'berep4', pct: [90, 100] },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'ck56', pct: [70, 90] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'cd10', pct: [70, 90], note: 'positivo no epitélio tumoral; no tricoepitelioma marca o estroma' },
      { marker: 'betacatenina', pct: [30, 60], note: 'nuclear focal em parte dos casos' },
      { marker: 'ema', pct: [0, 10], note: 'positiva só no componente escamoso ou sebáceo' },
      { marker: 'phlda1', pct: [0, 10], note: 'negativa; difusa no tricoepitelioma' },
      { marker: 'ck20', pct: [0, 10], note: 'sem células de Merkel colonizando, ao contrário do tricoepitelioma' },
      { marker: 'ck7', pct: [0, 10] },
      { marker: 'adipofilina', pct: [0, 10], note: 'positiva se houver diferenciação sebácea' },
      { marker: 'ar', pct: [10, 30] },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd34', pct: [0, 10], note: 'negativo no tumor; o estroma do tricoepitelioma é CD34 positivo' },
      { marker: 'ki67', pct: [20, 50], note: 'índice geralmente 10 a 30%' },
      { marker: 'bcl2', pct: [80, 95], note: 'difuso; no tricoepitelioma fica restrito à camada periférica' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tricoepitelioma/tricoblastoma: PHLDA1 difusa, estroma CD34 positivo, CD10 no estroma e não no epitélio, células de Merkel CK20 positivas.',
      'Carcinoma espinocelular basaloide: BerEP4 negativo, EMA positiva, queratinização e atipia maiores.',
      'Carcinoma de células de Merkel: CK20 em dot, sinaptofisina e INSM1 positivos.',
      'Carcinoma sebáceo: adipofilina e AR positivos, vacúolos lipídicos com endentação nuclear.',
    ],
    pitfalls: ['BerEP4 também é positiva em anexiais benignos e em adenocarcinomas metastáticos: use com EMA e com a morfologia.', 'A paliçada e a fenda de retração podem faltar no padrão infiltrativo e morfeiforme.'],
    molecular: 'Ativação da via Hedgehog: mutação de PTCH1 na maioria, SMO em parte (alvo de vismodegibe); assinatura de UV.',
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK482439/', 'https://dermnetnz.org/topics/basal-cell-carcinoma-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)'],
  },
  {
    id: 'carcinoma-espinocelular-cutaneo',
    name: 'Carcinoma espinocelular cutâneo',
    aka: ['CEC cutâneo', 'carcinoma escamocelular', 'cutaneous squamous cell carcinoma', 'cSCC'],
    behavior: 'maligno',
    sites: [
      { site: 'pele', role: 'primario', freq: 3 },
      { site: 'penis', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['escamoso', 'epitelioide', 'pleomorfico'],
    architecture: ['ninhos', 'infiltrativo', 'lencois'],
    features: ['queratinizacao', 'mitoses-altas', 'desmoplasia', 'perineural', 'precursor', 'necrose'],
    ages: ['adulto', 'idoso'],
    summary: 'Ninhos e cordões infiltrativos de células escamosas atípicas com pontes intercelulares e queratinização, surgindo em queratose actínica ou doença de Bowen em pele fotoexposta.',
    criteria: [
      'Células escamosas com citoplasma eosinofílico, pontes intercelulares e graus variáveis de queratinização.',
      'Invasão da derme além da membrana basal (o que o separa da doença de Bowen).',
      'Queratose actínica ou carcinoma in situ adjacente apoia a origem cutânea primária.',
      'O queratoacantoma é a variante cratiforme de crescimento rápido, com lábio epitelial e queratina central: o diagnóstico é morfológico, não imuno-histoquímico.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'p40', pct: [90, 100] },
      { marker: 'ck56', pct: [85, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'ck17', pct: [70, 90] },
      { marker: 'ema', pct: [80, 95] },
      { marker: 'ck7', pct: [0, 15] },
      { marker: 'berep4', pct: [0, 10], note: 'negativa; distingue do carcinoma basocelular' },
      { marker: 'p16', pct: [10, 30], note: 'em bloco apenas nos raros casos HPV-associados (periungueal, genital)' },
      { marker: 'p53', pct: [50, 80], note: 'padrão aberrante frequente pela assinatura UV' },
      { marker: 'ki67', pct: [70, 95], note: 'índice alto e desorganizado, não só basal' },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd10', pct: [20, 50], note: 'pode ser positivo nas variantes pouco diferenciadas: não use sozinho contra o fibroxantoma atípico' },
      { marker: 'cd34', pct: [0, 5] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Fibroxantoma atípico: queratinas e p63/p40 negativos, CD10 positivo.',
      'Melanoma desmoplásico ou de células fusiformes: S100 e SOX10 positivos, queratinas negativas.',
      'Carcinoma basocelular: BerEP4 positiva, EMA negativa.',
      'Metástase cutânea de carcinoma escamoso de pulmão ou cabeça e pescoço: correlação clínica; TTF-1 e p16 ajudam pouco, a história é o que decide.',
    ],
    pitfalls: ['O CEC sarcomatoide pode perder todas as queratinas comuns: use um coquetel amplo mais p63/p40 antes de chamar de sarcoma.', 'Ki-67 e p53 não separam queratoacantoma de CEC bem diferenciado.'],
    molecular: 'Carga mutacional altíssima com assinatura UV: TP53, CDKN2A, NOTCH1/2, TERT promotor.',
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK441939/', 'https://dermnetnz.org/topics/squamous-cell-carcinoma-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)'],
  },
  {
    id: 'doenca-de-bowen',
    name: 'Doença de Bowen (carcinoma espinocelular in situ)',
    aka: ['CEC in situ', 'Bowen disease', 'eritroplasia de Queyrat no pênis'],
    behavior: 'maligno',
    sites: [
      { site: 'pele', role: 'primario', freq: 3 },
      { site: 'penis', role: 'primario', freq: 2 },
      { site: 'vulva-vagina', role: 'primario', freq: 2 },
    ],
    cells: ['escamoso', 'pleomorfico'],
    architecture: ['lencois'],
    features: ['queratinizacao', 'mitoses-altas', 'corpos-apoptoticos', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Atipia escamosa de espessura total da epiderme, com desordem arquitetural, mitoses em todos os níveis e paraqueratose, sem invasão da derme.',
    criteria: [
      'Atipia citológica em toda a espessura da epiderme, com perda da maturação.',
      'Mitoses acima da camada basal, disqueratose e células multinucleadas.',
      'Membrana basal íntegra: nenhuma invasão dérmica.',
      'Anexos frequentemente colonizados pelo epitélio atípico (não confundir com invasão).',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'p40', pct: [90, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'ck7', pct: [0, 15], note: 'em geral negativa: chave contra a doença de Paget extramamária' },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'gcdfp15', pct: [0, 5] },
      { marker: 'her2', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5], note: 'negativo: separa do melanoma in situ' },
      { marker: 's100', pct: [0, 10], note: 'células de Langerhans dispersas podem confundir' },
      { marker: 'melana', pct: [0, 5], note: 'melanócitos intraepidérmicos residuais podem simular melanoma in situ' },
      { marker: 'p16', pct: [20, 50], note: 'em bloco nas lesões HPV-associadas (genital, periungueal)' },
      { marker: 'p53', pct: [50, 80] },
      { marker: 'ki67', pct: [80, 100], note: 'positividade em toda a espessura' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Doença de Paget extramamária: CK7 e GCDFP-15 positivos, p63/p40 negativos.',
      'Melanoma in situ: SOX10, S100 e Melan-A positivos, queratinas negativas.',
      'Queratose actínica: atipia limitada ao terço inferior, poupando os anexos.',
    ],
    pitfalls: ['A colonização de folículos é regra e não deve ser lida como invasão.', 'Melan-A em corte de pele fotoexposta superestima melanócitos: não diagnostique melanoma in situ com Melan-A isolado.'],
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
  {
    id: 'carcinoma-merkel',
    name: 'Carcinoma de células de Merkel',
    aka: ['carcinoma neuroendócrino primário cutâneo', 'Merkel cell carcinoma', 'MCC'],
    behavior: 'maligno',
    sites: [
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['mitoses-altas', 'necrose', 'corpos-apoptoticos'],
    ages: ['idoso'],
    summary: 'Tumor dérmico de células pequenas azuis com cromatina fina em sal e pimenta, citoplasma escasso, mitoses e apoptose abundantes, em pele fotoexposta de idosos e imunossuprimidos.',
    criteria: [
      'Células pequenas redondas uniformes, cromatina fina, nucléolo inconspícuo, citoplasma escasso, moldagem nuclear.',
      'Queratina (CK20 ou pan-queratina) em dot paranuclear mais pelo menos um marcador neuroendócrino.',
      'Exclusão de carcinoma de pequenas células metastático: TTF-1 negativo e CK20 positiva favorecem Merkel.',
    ],
    markers: [
      { marker: 'ck20', pct: [85, 95], pattern: 'dot' },
      { marker: 'ae1ae3', pct: [90, 100], pattern: 'dot' },
      { marker: 'cam52', pct: [90, 100], pattern: 'dot' },
      { marker: 'insm1', pct: [90, 100] },
      { marker: 'sinaptofisina', pct: [80, 95] },
      { marker: 'cromogranina', pct: [55, 80], note: 'frequentemente focal' },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'nf', pct: [70, 90], pattern: 'dot' },
      { marker: 'sox2', pct: [80, 95] },
      { marker: 'pax5', pct: [70, 90], note: 'armadilha: não chamar de linfoma' },
      { marker: 'tdt', pct: [30, 70], note: 'armadilha com linfoblástico' },
      { marker: 'ttf1', pct: [0, 5], note: 'raros casos positivos com o clone SPT24' },
      { marker: 'ck7', pct: [5, 20] },
      { marker: 'cd45', pct: 0 },
      { marker: 'cd99', pct: [30, 50], note: 'citoplasmática ou membranosa focal' },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'p63', pct: [30, 60], note: 'associada a pior prognóstico' },
      { marker: 'ki67', pct: [90, 100], note: 'índice em geral acima de 50%' },
    ],
    mimics: [
      'Carcinoma de pequenas células pulmonar metastático: TTF-1 positivo, CK20 negativa, sem dot de neurofilamento.',
      'Linfoma (PAX5 e TdT confundem): CD45 e CD20/CD3 positivos, queratina negativa.',
      'Melanoma de células pequenas: SOX10 e S100 positivos, queratina negativa.',
      'Sarcoma de Ewing: CD99 membranoso forte, NKX2.2, queratina em geral negativa.',
    ],
    pitfalls: ['PAX5 e TdT positivos numa fração dos casos: nunca diagnosticar linfoma sem CD45.', 'CK20 negativa em cerca de 10%, sobretudo nos casos poliomavírus-negativos e com assinatura UV.'],
    molecular: 'Poliomavírus de Merkel integrado em cerca de 80% dos casos, ou assinatura UV com mutações de TP53 e RB1 nos vírus-negativos.',
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK482329/', 'https://dermnetnz.org/topics/merkel-cell-carcinoma-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)'],
  },
  {
    id: 'melanoma-convencional',
    name: 'Melanoma cutâneo convencional',
    aka: ['melanoma extensivo superficial', 'melanoma nodular', 'lentigo maligno melanoma', 'cutaneous melanoma'],
    behavior: 'maligno',
    sites: [
      { site: 'pele', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 2 },
      { site: 'intestino-delgado', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
      { site: 'mama', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'fusocelular', 'pleomorfico', 'rabdoide', 'claras'],
    architecture: ['ninhos', 'lencois', 'infiltrativo'],
    features: ['melanina', 'mitoses-altas', 'nucleolo', 'necrose', 'precursor', 'linfoide'],
    ages: ['jovem', 'adulto', 'idoso'],
    summary: 'Proliferação melanocítica assimétrica com disseminação pagetoide, ninhos confluentes irregulares, ausência de maturação em profundidade e mitoses dérmicas.',
    criteria: [
      'Assimetria, má delimitação lateral e melanócitos isolados predominando sobre ninhos na junção.',
      'Disseminação pagetoide acima da junção e extensão anexial irregular.',
      'Falta de maturação do componente dérmico com mitoses dérmicas, sobretudo profundas.',
      'PRAME difusa e perda do gradiente de HMB-45 apoiam malignidade quando a morfologia é ambígua.',
    ],
    markers: [
      { marker: 'sox10', pct: [95, 100] },
      { marker: 's100', pct: [95, 100] },
      { marker: 'melana', pct: [85, 95] },
      { marker: 'hmb45', pct: [70, 90], note: 'sem gradiente de maturação, ao contrário do nevo' },
      { marker: 'mitf', pct: [80, 95] },
      { marker: 'tirosinase', pct: [70, 90] },
      { marker: 'prame', pct: [80, 95], note: 'difusa (> 75% das células) na maioria; nevos são negativos ou focais' },
      { marker: 'p16', pct: [40, 70], note: 'o "positivo" aqui é a PERDA de expressão; nevos mantêm p16' },
      { marker: 'ki67', pct: [70, 90], note: 'índice dérmico alto e disperso em profundidade' },
      { marker: 'brafv600e', pct: [40, 50], note: 'VE1 positiva reflete BRAF V600E, mais comum nos de tronco de jovens' },
      { marker: 'ae1ae3', pct: [0, 5], note: 'raríssimos melanomas expressam queratina: armadilha grave' },
      { marker: 'ema', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'cd68', pct: [5, 20], note: 'reatividade cruzada em melanoma: não chame de histiocitose' },
      { marker: 'cd117', pct: [20, 50], note: 'mais frequente nos acrais e mucosos' },
      { marker: 'bap1', pct: [5, 15], note: 'perda nos melanomas da família BAP1 e no uveal' },
      { marker: 'pdl1', pct: [30, 50], note: 'preditivo de resposta, não diagnóstico' },
    ],
    mimics: [
      'Nevo melanocítico: maturação, HMB-45 em gradiente, PRAME negativa ou focal, Ki-67 dérmico baixo.',
      'Carcinoma espinocelular ou basocelular pigmentado: queratinas e p63/p40 positivos.',
      'Linfoma: CD45 positivo, SOX10 negativo.',
      'Sarcoma de células claras: morfologicamente idêntico e SOX10/HMB-45 positivo; separa-se por EWSR1::ATF1 e por ser de partes moles profundas.',
    ],
    pitfalls: ['Melanomas desdiferenciados perdem SOX10, S100 e Melan-A: se a lesão é dérmica, pleomórfica e "nula", pense em melanoma desdiferenciado ou fibroxantoma atípico.', 'PRAME também é positiva em CEC, sarcoma sinovial e seminoma: só vale dentro do contexto melanocítico.'],
    molecular: 'BRAF V600 em cerca de metade, NRAS em 15 a 20%, NF1 nos de pele danificada por sol; TERT promotor quase universal.',
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK470409/', 'https://dermnetnz.org/topics/melanoma-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)'],
  },
  {
    id: 'melanoma-desmoplasico',
    name: 'Melanoma desmoplásico',
    aka: ['desmoplastic melanoma', 'melanoma neurotrópico'],
    behavior: 'maligno',
    sites: [
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular'],
    architecture: ['fasciculos', 'infiltrativo'],
    features: ['desmoplasia', 'perineural', 'linfoide', 'mitoses-moderadas'],
    ages: ['idoso'],
    summary: 'Proliferação fusocelular amelanótica em estroma colagenizado, com agregados linfoides dispersos e neurotropismo, em cabeça e pescoço de idosos, muitas vezes sob um lentigo maligno.',
    criteria: [
      'Células fusiformes atípicas dispersas em estroma desmoplásico, com agregados linfoides nodulares.',
      'S100 e SOX10 positivos difusos com Melan-A e HMB-45 negativos: a combinação que define o padrão.',
      'Neurotropismo frequente; componente de lentigo maligno na epiderme suprajacente em parte dos casos.',
      'Exclusão de cicatriz, fibroxantoma atípico e neurofibroma antes de assumir o diagnóstico.',
    ],
    markers: [
      { marker: 's100', pct: [95, 100] },
      { marker: 'sox10', pct: [95, 100] },
      { marker: 'melana', pct: [0, 15], note: 'quase sempre negativo: a grande diferença para o melanoma convencional' },
      { marker: 'hmb45', pct: [0, 10], note: 'negativo no componente desmoplásico; pode marcar o componente juncional' },
      { marker: 'mitf', pct: [10, 40] },
      { marker: 'prame', pct: [20, 40], note: 'bem menos sensível que no melanoma convencional' },
      { marker: 'p53', pct: [50, 80] },
      { marker: 'ki67', pct: [30, 60] },
      { marker: 'ae1ae3', pct: [0, 5] },
      { marker: 'p63', pct: [0, 10] },
      { marker: 'cd34', pct: [0, 10], note: 'negativo: ajuda contra neurofibroma e DFSP' },
      { marker: 'sma', pct: [5, 20], note: 'miofibroblastos aprisionados podem confundir' },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'brafv600e', pct: [0, 10], note: 'BRAF é raro neste subtipo, ao contrário do convencional' },
      { marker: 'pdl1', pct: [40, 70], note: 'carga mutacional alta; boa resposta a imunoterapia' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Cicatriz: fusocelulares S100 positivas isoladas podem existir; a densidade e a atipia decidem, com SOX10 mais confiável que S100.',
      'Neurofibroma: S100 positivo mas CD34 em rede positiva, sem atipia nem mitoses.',
      'Fibroxantoma atípico: S100 e SOX10 negativos, CD10 positivo.',
      'CEC sarcomatoide: queratinas ou p63/p40 positivos ao menos focalmente.',
    ],
    pitfalls: ['Pedir só Melan-A e HMB-45 numa lesão fusocelular deixa passar o melanoma desmoplásico: SOX10 é obrigatório.', 'Células de Schwann e dendríticas dérmicas são S100 positivas: use SOX10 e a densidade celular.'],
    molecular: 'Carga mutacional muito alta com assinatura UV, NF1 frequente; BRAF V600 raro.',
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.', 'Revisões de PRAME e SOX10 em melanoma desmoplásico (Am J Surg Pathol, 2018-2021)'],
  },
  {
    id: 'nevo-melanocitico',
    name: 'Nevo melanocítico (comum e de Spitz)',
    aka: ['nevo nevocelular', 'nevo composto', 'nevo intradérmico', 'nevo de Spitz', 'melanocytic nevus'],
    behavior: 'benigno',
    sites: [{ site: 'pele', role: 'primario', freq: 3 }],
    cells: ['epitelioide', 'fusocelular'],
    architecture: ['ninhos'],
    features: ['melanina', 'mitoses-raras'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Proliferação melanocítica simétrica e bem delimitada, com ninhos regulares na junção e maturação progressiva em profundidade; no Spitz, células epitelioides grandes com corpos de Kamino e fendas peri-ninho.',
    criteria: [
      'Simetria, boa delimitação lateral e ninhos de tamanho regular, sem confluência desordenada.',
      'Maturação: células menores e ninhos menores em profundidade, sem mitoses profundas.',
      'No nevo de Spitz, células epitelioides e fusiformes grandes, hipertrofia epidérmica, corpos de Kamino e fendas de retração ao redor dos ninhos juncionais.',
      'PRAME negativa ou focal e p16 preservada apoiam benignidade quando a morfologia é limítrofe.',
    ],
    markers: [
      { marker: 'sox10', pct: [95, 100] },
      { marker: 's100', pct: [95, 100] },
      { marker: 'melana', pct: [90, 100] },
      { marker: 'hmb45', pct: [60, 85], note: 'padrão em gradiente: positiva na junção e nas células superficiais, negativa em profundidade' },
      { marker: 'prame', pct: [0, 10], note: 'difusa em menos de 5% dos nevos; o Spitz pode ter positividade focal' },
      { marker: 'p16', pct: [5, 20], note: 'o "positivo" é a perda; nevos habitualmente retêm p16' },
      { marker: 'ki67', pct: [0, 10], note: 'índice dérmico abaixo de 2%, com mitoses superficiais raras' },
      { marker: 'mitf', pct: [90, 100] },
      { marker: 'brafv600e', pct: [50, 80], note: 'nevos adquiridos comuns; o Spitz clássico é HRAS ou fusões, BRAF negativo' },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'alk', pct: [0, 10], note: 'positiva nos nevos de Spitz com fusão ALK (padrão plexiforme fusocelular)' },
      { marker: 'pan-trk', pct: [0, 10], note: 'positiva nos Spitz com fusão NTRK' },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'cd34', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Melanoma: assimetria, ausência de maturação, mitoses profundas, PRAME difusa, perda de p16.',
      'Nevo displásico: ponte entre cristas, fibroplasia lamelar e atipia arquitetural, com PRAME em geral negativa.',
      'Melanoma spitzoide: Ki-67 dérmico alto, PRAME difusa, mitoses profundas e atípicas.',
    ],
    pitfalls: ['Nevo de Spitz pode ter mitoses e Ki-67 não desprezível na juventude: idade e morfologia mandam.', 'HMB-45 difusa em profundidade é sinal de alerta, mas o nevo azul é difusamente positivo por natureza.'],
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.', 'Lezcano et al., Am J Surg Pathol 2018 (PRAME em lesões melanocíticas)'],
  },
  {
    id: 'nevo-azul',
    name: 'Nevo azul e melanocitoma dérmico',
    aka: ['blue naevus', 'nevo azul celular', 'melanocitoma pigmentado epitelioide'],
    behavior: 'benigno',
    sites: [{ site: 'pele', role: 'primario', freq: 2 }],
    cells: ['fusocelular', 'epitelioide'],
    architecture: ['fasciculos', 'infiltrativo'],
    features: ['melanina', 'hialinizacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Melanócitos dendríticos fortemente pigmentados entre feixes colágenos espessados da derme reticular, com melanófagos, sem componente juncional.',
    criteria: [
      'Melanócitos fusiformes e dendríticos muito pigmentados, dispersos em estroma esclerótico, sem ninhos juncionais.',
      'A variante celular forma nódulos de células fusiformes pouco pigmentadas com bordas em "haltere" no subcutâneo.',
      'Ausência de atipia acentuada, necrose e mitoses atípicas, que sugeririam melanoma de nevo azul.',
    ],
    markers: [
      { marker: 'sox10', pct: [95, 100] },
      { marker: 's100', pct: [95, 100] },
      { marker: 'melana', pct: [85, 95] },
      { marker: 'hmb45', pct: [90, 100], note: 'difusa por natureza, sem gradiente: não interprete como melanoma' },
      { marker: 'mitf', pct: [90, 100] },
      { marker: 'prame', pct: [0, 15] },
      { marker: 'ki67', pct: [0, 10] },
      { marker: 'bap1', pct: [0, 10], note: 'perda nos melanocitomas BAP1-inativados (com nevo tipo Spitz epitelioide)' },
      { marker: 'p16', pct: [0, 15] },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'cd34', pct: [0, 5] },
      { marker: 'sma', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Melanoma metastático pigmentado: nódulo expansivo com atipia, mitoses e necrose.',
      'Dermatofibroma pigmentado ou hemossiderótico: SOX10 negativo, FXIIIa positivo.',
      'Melanoma de nevo azul: nódulo celular com atipia, mitoses e perda de BAP1 em parte.',
    ],
    molecular: 'Mutações de GNAQ ou GNA11, as mesmas do melanoma uveal.',
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
  {
    id: 'carcinoma-sebaceo',
    name: 'Carcinoma sebáceo',
    aka: ['sebaceous carcinoma', 'carcinoma de glândula de Meibômio'],
    behavior: 'maligno',
    sites: [
      { site: 'olho-orbita', role: 'primario', freq: 2 },
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'basaloide', 'claras', 'pleomorfico'],
    architecture: ['lencois', 'ninhos', 'infiltrativo'],
    features: ['vacuolos-lipidicos', 'mitoses-altas', 'necrose'],
    ages: ['adulto', 'idoso'],
    summary: 'Lóbulos infiltrativos de células basaloides atípicas com focos de citoplasma vacuolizado por lipídio, que endenta o núcleo; na pálpebra, disseminação pagetoide na conjuntiva.',
    criteria: [
      'Diferenciação sebácea: citoplasma multivacuolado com endentação nuclear (não confundir com células claras por glicogênio).',
      'Atipia, mitoses numerosas e necrose comedoniana, com infiltração.',
      'Adipofilina ou perilipina confirmam lipídio quando a morfologia é sutil; AR e EMA apoiam a linhagem sebácea.',
      'Investigar síndrome de Muir-Torre com MMR quando extraocular ou múltiplo.',
    ],
    markers: [
      { marker: 'adipofilina', pct: [85, 100], note: 'padrão vesicular em membrana de gotícula; o mais útil' },
      { marker: 'ema', pct: [85, 100] },
      { marker: 'ar', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [30, 60] },
      { marker: 'berep4', pct: [40, 70], note: 'positiva em parte: não use isolada contra o basocelular' },
      { marker: 'p63', pct: [80, 100] },
      { marker: 'p40', pct: [60, 90] },
      { marker: 'ck903', pct: [70, 90] },
      { marker: 'mlh1', pct: [10, 30], note: 'perda em parte dos casos de Muir-Torre' },
      { marker: 'msh2', pct: [20, 40], note: 'a perda mais comum em Muir-Torre' },
      { marker: 'msh6', pct: [20, 40] },
      { marker: 'p53', pct: [50, 80] },
      { marker: 'ki67', pct: [70, 95] },
      { marker: 'melana', pct: [0, 5], note: 'o clone A103 pode marcar sebáceo: armadilha clássica com melanoma' },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 's100', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma basocelular com diferenciação sebácea: BerEP4 difusa, EMA negativa nas áreas basaloides.',
      'Carcinoma espinocelular de células claras: adipofilina negativa, sem endentação nuclear.',
      'Doença de Paget e melanoma in situ na pálpebra: CK7/GCDFP-15 e SOX10 resolvem.',
      'Hiperplasia sebácea e sebaceoma: lóbulos organizados com camada basaloide periférica fina, sem atipia.',
    ],
    pitfalls: ['O clone A103 de Melan-A marca células sebáceas e adrenocorticais: nunca diagnostique melanoma com A103 isolado.', 'Adipofilina precisa de fixação adequada; tecido processado em álcool pode dissolver o lipídio.'],
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Plaza & Prieto, Applied Immunohistochemistry in Dermatopathology', 'Plaza et al., Am J Dermatopathol (adipofilina no carcinoma sebáceo)'],
  },
  {
    id: 'poroma-porocarcinoma',
    name: 'Poroma e porocarcinoma',
    aka: ['hidroacantoma simples', 'poroma écrino', 'poroid hidradenoma', 'porocarcinoma'],
    behavior: 'intermediario',
    sites: [{ site: 'pele', role: 'primario', freq: 2 }],
    cells: ['basaloide', 'epitelioide', 'claras'],
    architecture: ['ninhos', 'lobular', 'cistico'],
    features: ['glicogenio', 'necrose', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'Lóbulos de células poroides pequenas e monótonas conectados à epiderme, com ductos intratumorais revestidos por cutícula eosinofílica; o porocarcinoma acrescenta atipia, mitoses e infiltração.',
    criteria: [
      'Células poroides uniformes, cuboidais, com pontes intercelulares e ductos intraepiteliais revestidos por cutícula.',
      'Conexão ampla com a epiderme, com bordas bem delimitadas no poroma.',
      'No porocarcinoma: atipia citológica, mitoses atípicas, necrose, infiltração e invasão linfovascular; muitas vezes com poroma residual.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ema', pct: [85, 100], note: 'realça os ductos intratumorais' },
      { marker: 'cea', pct: [80, 95], note: 'luz ductal; confirma a diferenciação ductal' },
      { marker: 'ck7', pct: [50, 80], note: 'sobretudo nas células ductais' },
      { marker: 'p63', pct: [85, 100] },
      { marker: 'ck903', pct: [70, 90] },
      { marker: 'berep4', pct: [20, 50] },
      { marker: 'cd117', pct: [30, 60] },
      { marker: 'p53', pct: [30, 70], note: 'aberrante sobretudo no porocarcinoma' },
      { marker: 'ki67', pct: [40, 80], note: 'alto no porocarcinoma, baixo no poroma' },
      { marker: 's100', pct: [0, 15] },
      { marker: 'sox10', pct: [0, 20] },
      { marker: 'gcdfp15', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma basocelular: paliçada periférica e fenda de retração, BerEP4 difusa, sem ductos com cutícula.',
      'Doença de Bowen: atipia de espessura total sem ductos nem células poroides.',
      'Hidradenoma: lóbulos maiores com células claras e escamoides, sem conexão epidérmica ampla.',
    ],
    molecular: 'Fusões YAP1::MAML2 e YAP1::NUTM1 na maioria dos poromas e porocarcinomas.',
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.', 'Sekine et al., J Clin Invest 2019 (fusões de YAP1 em poroma e porocarcinoma)'],
  },
  {
    id: 'hidradenoma',
    name: 'Hidradenoma e hidradenocarcinoma',
    aka: ['hidradenoma nodular', 'acrospiroma écrino', 'hidradenoma de células claras', 'clear cell hidradenoma'],
    behavior: 'intermediario',
    sites: [{ site: 'pele', role: 'primario', freq: 2 }],
    cells: ['claras', 'epitelioide', 'basaloide', 'oncocitico'],
    architecture: ['lobular', 'cistico', 'ninhos'],
    features: ['glicogenio', 'hialinizacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Nódulo dérmico circunscrito de lóbulos sólidos e císticos, com mistura de células claras ricas em glicogênio, poligonais eosinofílicas e escamoides, com estroma hialinizado.',
    criteria: [
      'Nódulo bem delimitado, sem conexão epidérmica ampla, com áreas sólidas e cavidades císticas.',
      'Duas ou mais populações: células claras glicogenadas, poligonais eosinofílicas e escamoides, com ductos dispersos.',
      'Hidradenocarcinoma: infiltração, atipia acentuada, mitoses atípicas, necrose e invasão vascular.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ema', pct: [80, 95], note: 'realça luzes ductais' },
      { marker: 'cea', pct: [60, 85], pattern: 'M', note: 'luminal' },
      { marker: 'ck7', pct: [60, 90] },
      { marker: 'p63', pct: [70, 95], note: 'camada periférica preservada no benigno' },
      { marker: 'sma', pct: [30, 60], note: 'mioepitélio periférico' },
      { marker: 'calponina', pct: [30, 60] },
      { marker: 's100', pct: [30, 70] },
      { marker: 'sox10', pct: [40, 80] },
      { marker: 'gcdfp15', pct: [20, 50] },
      { marker: 'er', pct: [10, 40] },
      { marker: 'caix', pct: [0, 15], note: 'negativa: ajuda contra carcinoma renal de células claras metastático' },
      { marker: 'pax8', pct: [0, 5], note: 'negativa: chave contra metástase renal' },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'p53', pct: [20, 60], note: 'aberrante mais no hidradenocarcinoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma renal de células claras metastático: PAX8 e CA-IX positivos, queratina fraca, rede vascular delicada.',
      'Carcinoma sebáceo: adipofilina positiva, vacúolos com endentação nuclear.',
      'Poroma: células poroides pequenas com conexão epidérmica ampla.',
      'Melanoma de células claras (balloon cell): SOX10 positivo, queratina negativa.',
    ],
    molecular: 'Fusão CRTC1::MAML2 em parte dos hidradenomas de células claras, a mesma do carcinoma mucoepidermoide.',
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
  {
    id: 'espiradenoma-cilindroma',
    name: 'Espiradenoma e cilindroma',
    aka: ['espiradenoma écrino', 'cilindroma dérmico', 'tumor em turbante', 'spiradenocilindroma'],
    behavior: 'benigno',
    sites: [{ site: 'pele', role: 'primario', freq: 2 }],
    cells: ['basaloide', 'epitelioide'],
    architecture: ['nodular', 'trabecular', 'lobular'],
    features: ['hialinizacao', 'linfoide', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Nódulos dérmicos azuis de duas populações basaloides: no espiradenoma, nódulos sólidos com linfócitos intratumorais; no cilindroma, peças de quebra-cabeça cercadas por membrana basal hialina espessa.',
    criteria: [
      'Duas populações celulares: células pequenas basaloides de núcleo escuro na periferia e células maiores pálidas no centro, com ductos dispersos.',
      'Cilindroma: nódulos justapostos em mosaico com bainha hialina PAS positiva e gotas de membrana basal intratumorais.',
      'Espiradenoma: nódulos sólidos bem circunscritos com linfócitos entremeados e vasos dilatados.',
      'Lesões múltiplas sugerem síndrome de Brooke-Spiegler (CYLD).',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ema', pct: [70, 95], note: 'nos ductos' },
      { marker: 'cea', pct: [60, 85], note: 'luminal' },
      { marker: 'ck7', pct: [60, 90], note: 'células luminais' },
      { marker: 'p63', pct: [85, 100], note: 'camada basaloide periférica; sua perda em foco sugere transformação maligna' },
      { marker: 'sma', pct: [60, 90], note: 'células mioepiteliais periféricas' },
      { marker: 'calponina', pct: [60, 90] },
      { marker: 's100', pct: [40, 80] },
      { marker: 'sox10', pct: [60, 90] },
      { marker: 'colageno-iv', pct: [85, 100], note: 'realça a bainha hialina do cilindroma' },
      { marker: 'cd117', pct: [40, 70] },
      { marker: 'ki67', pct: [0, 15] },
      { marker: 'p53', pct: [0, 20], note: 'aberrante nos raros espiradenocarcinomas' },
      { marker: 'berep4', pct: [30, 60] },
      { marker: 'myb', pct: [20, 50], note: 'positivo em parte dos cilindromas, como no adenoide cístico' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma adenoide cístico cutâneo: infiltrativo, perineural, MYB positivo, sem a bainha hialina em mosaico.',
      'Carcinoma basocelular: paliçada e fenda de retração, BerEP4 difusa, sem ductos com CEA.',
      'Espiradenocarcinoma: perda abrupta da dupla população e do p63 periférico, com atipia e mitoses.',
    ],
    molecular: 'Inativação de CYLD, esporádica ou germinativa (Brooke-Spiegler); fusões MYB em parte dos cilindromas.',
    sources: ['https://dermnetnz.org/topics/cylindroma-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
  {
    id: 'tricoepitelioma',
    name: 'Tricoepitelioma e tricoblastoma',
    aka: ['trichoepithelioma', 'tricoblastoma', 'tricoepitelioma desmoplásico'],
    behavior: 'benigno',
    sites: [{ site: 'pele', role: 'primario', freq: 2 }],
    cells: ['basaloide'],
    architecture: ['ninhos', 'palicada', 'lobular'],
    features: ['queratinizacao', 'calcificacao', 'mitoses-raras', 'corpos-apoptoticos'],
    ages: ['jovem', 'adulto'],
    summary: 'Lóbulos basaloides com diferenciação folicular, cistos córneos, corpos papilares mesenquimais e estroma fibroso próprio, sem fenda entre epitélio e estroma.',
    criteria: [
      'Diferenciação folicular: cistos infundibulares, corpos papilares mesenquimais e aposição íntima epitélio-estroma.',
      'Estroma fibrocelular próprio que acompanha os lóbulos, com fenda entre estroma e derme (o oposto do basocelular).',
      'PHLDA1 difusa e células de Merkel CK20 positivas dentro dos lóbulos.',
      'Mitoses e apoptose podem ser numerosas sem significar malignidade.',
    ],
    markers: [
      { marker: 'phlda1', pct: [85, 100], note: 'difusa; negativa no carcinoma basocelular' },
      { marker: 'ck20', pct: [70, 90], pattern: 'dot', note: 'células de Merkel colonizando os lóbulos' },
      { marker: 'cd34', pct: [70, 90], note: 'no estroma peritumoral; ausente no basocelular' },
      { marker: 'cd10', pct: [70, 90], note: 'no estroma, não no epitélio: o oposto do basocelular' },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'berep4', pct: [70, 95], note: 'positiva também aqui: não separa do basocelular' },
      { marker: 'bcl2', pct: [30, 60], note: 'restrita à camada periférica, ao contrário do basocelular difuso' },
      { marker: 'ema', pct: [0, 10] },
      { marker: 'ki67', pct: [20, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma basocelular: PHLDA1 negativa, CD10 epitelial, estroma CD34 negativo, fenda epitélio-estroma, bcl-2 difusa.',
      'Tricoepitelioma desmoplásico vs carcinoma anexial microcístico: o microcístico infiltra a hipoderme com perineural e ductos CEA positivos.',
      'Carcinoma basocelular infiltrativo: atipia, mitoses atípicas e estroma mixoide, sem corpos papilares.',
    ],
    pitfalls: ['Nenhum marcador isolado separa tricoepitelioma de basocelular com certeza: use PHLDA1, CD10, CD34 e CK20 em painel, sempre com a arquitetura.'],
    sources: ['https://dermnetnz.org/topics/trichoepithelioma-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Sellheyer et al. (PHLDA1 no tricoepitelioma vs carcinoma basocelular)'],
  },
  {
    id: 'pilomatricoma',
    name: 'Pilomatricoma',
    aka: ['epitelioma calcificante de Malherbe', 'pilomatrixoma'],
    behavior: 'benigno',
    sites: [{ site: 'pele', role: 'primario', freq: 3 }],
    cells: ['basaloide', 'gigantes'],
    architecture: ['lobular', 'ninhos'],
    features: ['calcificacao', 'queratinizacao', 'gigantes-osteoclasticas', 'mitoses-altas'],
    ages: ['crianca', 'jovem'],
    summary: 'Nódulo subcutâneo firme com ilhas de células basaloides matriciais que transitam para células fantasma anucleadas, com calcificação e reação gigantocelular de corpo estranho.',
    criteria: [
      'Células basaloides matriciais periféricas com núcleo vesiculoso e nucléolo, muitas mitoses (não é malignidade).',
      'Transição abrupta para células fantasma (sombra) eosinofílicas anucleadas.',
      'Calcificação distrófica, ossificação e granuloma de corpo estranho ao redor da queratina.',
      'β-catenina nuclear confirma a ativação de CTNNB1.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [85, 100], pattern: 'N', note: 'nuclear nas células basaloides, reflexo da mutação de CTNNB1' },
      { marker: 'ae1ae3', pct: [90, 100] },
      { marker: 'ck903', pct: [80, 95] },
      { marker: 'p63', pct: [80, 100] },
      { marker: 'ck56', pct: [70, 90] },
      { marker: 'cd10', pct: [40, 70] },
      { marker: 'cd68', pct: [60, 90], note: 'nas células gigantes de corpo estranho, não nas tumorais' },
      { marker: 'ki67', pct: [70, 95], note: 'alto na camada matricial: não indica malignidade' },
      { marker: 'berep4', pct: [20, 50] },
      { marker: 'ema', pct: [0, 15] },
      { marker: 's100', pct: [0, 10] },
      { marker: 'p53', pct: [10, 30], note: 'aberrante no raro pilomatrixocarcinoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Pilomatrixocarcinoma: infiltração, atipia acentuada, necrose e mitoses atípicas com invasão vascular.',
      'Carcinoma basocelular com diferenciação matricial: paliçada e estroma mixoide, sem lençóis de células fantasma.',
      'Cisto epidermoide roto: sem células basaloides matriciais nem β-catenina nuclear.',
    ],
    molecular: 'Mutação ativadora de CTNNB1 (β-catenina) em quase todos os casos.',
    sources: ['https://dermnetnz.org/topics/pilomatricoma-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
  {
    id: 'siringoma',
    name: 'Siringoma',
    aka: ['syringoma', 'siringoma de células claras'],
    behavior: 'benigno',
    sites: [
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'olho-orbita', role: 'primario', freq: 2 },
    ],
    cells: ['epitelioide', 'claras'],
    architecture: ['glandulas', 'infiltrativo'],
    features: ['desmoplasia', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Pequenos ductos e cordões em vírgula ("girino") de duas camadas de células cuboidais, em estroma esclerótico da derme superficial, tipicamente em pálpebras.',
    criteria: [
      'Ductos pequenos revestidos por duas camadas de células cuboidais brandas, com cordões sólidos em vírgula.',
      'Confinamento à derme superficial e média, sem invasão profunda nem perineural.',
      'Estroma esclerótico; a variante de células claras associa-se a diabetes.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ema', pct: [85, 100], note: 'luminal' },
      { marker: 'cea', pct: [70, 95], note: 'luminal' },
      { marker: 'ck7', pct: [70, 95] },
      { marker: 'p63', pct: [85, 100], note: 'camada externa preservada' },
      { marker: 'sma', pct: [50, 80] },
      { marker: 'calponina', pct: [50, 80] },
      { marker: 's100', pct: [20, 50] },
      { marker: 'sox10', pct: [40, 80] },
      { marker: 'er', pct: [30, 70] },
      { marker: 'pr', pct: [30, 70] },
      { marker: 'ki67', pct: [0, 10] },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma anexial microcístico: infiltra fundo e músculo, com invasão perineural e perda focal da camada mioepitelial.',
      'Carcinoma basocelular morfeiforme: BerEP4 positiva, sem ductos CEA positivos com duas camadas.',
      'Tricoepitelioma desmoplásico: cistos córneos e corpos papilares, sem ductos verdadeiros.',
    ],
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
  {
    id: 'carcinoma-anexial-microcistico',
    name: 'Carcinoma anexial microcístico',
    aka: ['microcystic adnexal carcinoma', 'MAC', 'carcinoma siringomatoso esclerosante'],
    behavior: 'maligno',
    sites: [{ site: 'pele', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'basaloide'],
    architecture: ['glandulas', 'infiltrativo', 'cistico'],
    features: ['desmoplasia', 'perineural', 'queratinizacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Tumor profundamente infiltrativo da face com cistos córneos superficiais, cordões e ductos siringomatosos em estroma esclerótico, com invasão perineural proeminente e citologia branda.',
    criteria: [
      'Zonalidade: cistos córneos em cima, cordões e ductos pequenos no fundo, invadindo hipoderme e músculo.',
      'Invasão perineural frequente com atipia citológica mínima e poucas mitoses.',
      'Bordas infiltrativas muito além do clínico: exige margens amplas ou Mohs.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'ema', pct: [70, 95], note: 'luminal' },
      { marker: 'cea', pct: [60, 90], note: 'luminal; confirma ductos verdadeiros' },
      { marker: 'ck7', pct: [40, 80] },
      { marker: 'p63', pct: [80, 100], note: 'pode ser descontínua, ao contrário do siringoma' },
      { marker: 'berep4', pct: [0, 20], note: 'em geral negativa: ajuda contra o basocelular morfeiforme' },
      { marker: 'cd34', pct: [0, 10], note: 'estroma negativo, ao contrário do tricoepitelioma desmoplásico' },
      { marker: 'sma', pct: [20, 50] },
      { marker: 'ki67', pct: [10, 30] },
      { marker: 'p53', pct: [20, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Siringoma: superficial, sem perineural, sem invasão de músculo.',
      'Tricoepitelioma desmoplásico: estroma CD34 positivo, corpos papilares, sem perineural.',
      'Carcinoma basocelular morfeiforme: BerEP4 positiva, sem ductos CEA positivos.',
      'Metástase de carcinoma mamário ou de células escamosas: história clínica, GATA3/ER.',
    ],
    pitfalls: ['A citologia branda engana em biópsia superficial: sem o fundo da lesão o diagnóstico passa por siringoma.'],
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
  {
    id: 'paget-extramamaria',
    name: 'Doença de Paget extramamária',
    aka: ['extramammary Paget disease', 'EMPD'],
    behavior: 'maligno',
    sites: [
      { site: 'vulva-vagina', role: 'primario', freq: 2 },
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'anus', role: 'primario', freq: 1 },
      { site: 'penis', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'anel-sinete', 'claras'],
    architecture: ['ninhos', 'fila-indiana'],
    features: ['mucina', 'mitoses-moderadas'],
    ages: ['idoso'],
    summary: 'Células grandes de citoplasma pálido e mucinoso, isoladas e em pequenos ninhos, dentro da epiderme de área apócrina (vulva, escroto, perianal), muitas vezes com anel de queratinócitos comprimidos.',
    criteria: [
      'Células de Paget intraepidérmicas com citoplasma abundante pálido, nucléolo evidente, mucina intracitoplasmática.',
      'CK7 positiva quase sempre, com p63/p40 e SOX10 negativos.',
      'Separar primária (GCDFP-15 e GATA3 positivos, CK20 negativa) de secundária a carcinoma colorretal ou urotelial (CK20 e CDX2 ou uroplaquina positivos).',
      'Avaliar carcinoma invasivo subjacente e, na forma secundária, investigar o tumor de base.',
    ],
    markers: [
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'cea', pct: [70, 95] },
      { marker: 'ema', pct: [85, 100] },
      { marker: 'gcdfp15', pct: [60, 85], note: 'apoia a forma primária apócrina' },
      { marker: 'gata3', pct: [80, 95] },
      { marker: 'her2', pct: [20, 40], note: 'superexpressão em parte; alvo terapêutico' },
      { marker: 'ar', pct: [50, 80] },
      { marker: 'mamaglobina', pct: [20, 50] },
      { marker: 'ck20', pct: [10, 25], note: 'positiva sobretudo na forma secundária a carcinoma colorretal ou urotelial' },
      { marker: 'cdx2', pct: [5, 20], note: 'positivo na secundária de origem colorretal' },
      { marker: 'uroplaquina', pct: [5, 15], note: 'positiva na secundária de origem urotelial' },
      { marker: 'p63', pct: [0, 10], note: 'negativa: separa da doença de Bowen' },
      { marker: 'p40', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 10], note: 'negativa: separa do melanoma in situ' },
      { marker: 's100', pct: [10, 30], note: 'pode ser fracamente positiva: não use isolada contra melanoma' },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'ki67', pct: [50, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Doença de Bowen pagetoide: p63/p40 e CK5/6 positivos, CK7 negativa.',
      'Melanoma in situ pagetoide: SOX10 e Melan-A positivos, CK7 negativa.',
      'Carcinoma sebáceo pagetoide na pálpebra: adipofilina e AR positivos.',
    ],
    pitfalls: ['Células claras benignas de Toker no mamilo e na vulva também são CK7 positivas: a atipia e a mucina decidem.'],
    sources: ['https://dermnetnz.org/topics/extramammary-paget-disease-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Plaza & Prieto, Applied Immunohistochemistry in Dermatopathology'],
  },
  {
    id: 'dermatofibroma',
    name: 'Dermatofibroma (histiocitoma fibroso benigno)',
    aka: ['histiocitoma fibroso benigno', 'dermatofibroma', 'benign fibrous histiocytoma'],
    behavior: 'benigno',
    sites: [{ site: 'pele', role: 'primario', freq: 3 }],
    cells: ['fusocelular', 'histiocitoide', 'gigantes'],
    architecture: ['storiforme', 'infiltrativo'],
    features: ['hialinizacao', 'hemorragia', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Proliferação dérmica de fibroblastos e histiócitos em arranjo estoriforme frouxo, aprisionando feixes colágenos espessos na periferia, com hiperplasia epidérmica e hiperpigmentação basal.',
    criteria: [
      'Colágeno "em halter" aprisionado nas bordas da lesão.',
      'Hiperplasia epidérmica com hiperpigmentação da camada basal sobre a lesão.',
      'Zona de Grenz frequente; celularidade mista com siderófagos e células de Touton na variante aneurismática.',
      'FXIIIa positivo com CD34 negativo no centro da lesão.',
    ],
    markers: [
      { marker: 'fxiiia', pct: [80, 95] },
      { marker: 'cd68', pct: [60, 90] },
      { marker: 'cd163', pct: [50, 80] },
      { marker: 'cd34', pct: [0, 20], note: 'negativo no centro; pode ser positivo na periferia (armadilha com DFSP)' },
      { marker: 'sma', pct: [30, 70], note: 'miofibroblastos' },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'ki67', pct: [0, 15] },
      { marker: 'cd10', pct: [40, 80], note: 'positivo: não separa de fibroxantoma atípico' },
      { marker: 'erg', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Dermatofibrossarcoma protuberans: CD34 difuso, FXIIIa negativo, infiltração em favo de mel no subcutâneo, sem colágeno aprisionado nem hiperplasia epidérmica.',
      'Fibroxantoma atípico: pleomorfismo acentuado e mitoses atípicas em pele muito fotoexposta de idoso.',
      'Melanoma desmoplásico: SOX10 positivo.',
    ],
    pitfalls: ['Variantes celulares e atípicas recidivam e podem preocupar; o padrão CD34/FXIIIa pode ser ambíguo na periferia.'],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK470538/', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
  {
    id: 'dfsp',
    name: 'Dermatofibrossarcoma protuberans',
    aka: ['DFSP', 'dermatofibrosarcoma protuberans', 'tumor de Bednar (variante pigmentada)'],
    behavior: 'intermediario',
    sites: [
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'partes-moles', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular'],
    architecture: ['storiforme', 'infiltrativo', 'fasciculos'],
    features: ['mitoses-raras', 'mitoses-moderadas'],
    ages: ['jovem', 'adulto'],
    summary: 'Proliferação fusocelular monótona em arranjo estoriforme apertado que infiltra o subcutâneo em favo de mel, envolvendo os septos e poupando os adipócitos.',
    criteria: [
      'Células fusiformes uniformes em estoriforme denso, com infiltração em favo de mel na gordura.',
      'CD34 difuso com FXIIIa negativo.',
      'Ausência do colágeno aprisionado e da hiperplasia epidérmica do dermatofibroma.',
      'Fibrossarcomatoso: fascículos em espinha de peixe, perda de CD34, mitoses e Ki-67 mais altos, maior risco de metástase.',
    ],
    markers: [
      { marker: 'cd34', pct: [85, 95], note: 'difuso; perde-se nas áreas fibrossarcomatosas' },
      { marker: 'fxiiia', pct: [0, 15], note: 'negativo, ao contrário do dermatofibroma' },
      { marker: 'cd68', pct: [0, 20] },
      { marker: 'sma', pct: [0, 20] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 's100', pct: [0, 5], note: 'positivo só na melanina do tumor de Bednar (células pigmentadas)' },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'ema', pct: [0, 5] },
      { marker: 'stat6', pct: [0, 5], note: 'negativo: separa do tumor fibroso solitário' },
      { marker: 'ki67', pct: [10, 30] },
      { marker: 'nestina', pct: [70, 95], note: 'positiva; proposta como auxiliar quando CD34 é fraco' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Dermatofibroma: FXIIIa positivo, CD34 negativo no centro, colágeno aprisionado.',
      'Tumor fibroso solitário: STAT6 nuclear positivo, vasos em galhada.',
      'Neurofibroma difuso: S100 e SOX10 positivos.',
      'Fibrossarcoma cutâneo: sempre procurar componente DFSP residual e testar COL1A1::PDGFB.',
    ],
    molecular: 'Fusão COL1A1::PDGFB por t(17;22), quase sempre como cromossomo em anel; base do tratamento com imatinibe.',
    sources: ['https://dermnetnz.org/topics/dermatofibrosarcoma-protuberans-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Goldblum, Folpe & Weiss, Enzinger & Weiss\'s Soft Tissue Tumors, 7ª ed.'],
  },
  {
    id: 'fibroxantoma-atipico',
    name: 'Fibroxantoma atípico e sarcoma dérmico pleomórfico',
    aka: ['AFX', 'atypical fibroxanthoma', 'pleomorphic dermal sarcoma', 'PDS'],
    behavior: 'intermediario',
    sites: [{ site: 'pele', role: 'primario', freq: 1 }],
    cells: ['pleomorfico', 'fusocelular', 'gigantes', 'epitelioide'],
    architecture: ['lencois', 'fasciculos'],
    features: ['mitoses-altas', 'necrose', 'hemorragia'],
    ages: ['idoso'],
    summary: 'Nódulo exofítico ulcerado em couro cabeludo ou face de idoso, formado por células pleomórficas, fusiformes e gigantes bizarras com mitoses atípicas; é um diagnóstico de exclusão imuno-histoquímica.',
    criteria: [
      'Proliferação dérmica pleomórfica de alto grau em pele muito fotoexposta, bem delimitada.',
      'Exclusão obrigatória de carcinoma (queratinas, p63/p40), melanoma (S100, SOX10), leiomiossarcoma (desmina, caldesmon) e angiossarcoma (CD31, ERG).',
      'Fibroxantoma atípico: confinado à derme, sem necrose, sem invasão de subcutâneo profundo, sem invasão linfovascular ou perineural.',
      'Sarcoma dérmico pleomórfico: qualquer um desses critérios adversos presente; risco real de recidiva e metástase.',
    ],
    markers: [
      { marker: 'cd10', pct: [80, 95], note: 'sensível, nada específico' },
      { marker: 'cd68', pct: [50, 80] },
      { marker: 'cd99', pct: [40, 70] },
      { marker: 'sma', pct: [30, 60], note: 'focal; não confundir com leiomiossarcoma' },
      { marker: 'ae1ae3', pct: [0, 10], note: 'focal fraca possível: repita com painel amplo antes de excluir carcinoma' },
      { marker: 'p63', pct: [10, 30], note: 'positividade focal descrita: não basta para chamar de carcinoma' },
      { marker: 'p40', pct: [0, 5], note: 'negativa: mais confiável que p63 aqui' },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'caldesmon', pct: [0, 5] },
      { marker: 'cd31', pct: [0, 10], note: 'macrófagos podem marcar: use ERG' },
      { marker: 'erg', pct: [0, 5] },
      { marker: 'cd34', pct: [0, 10] },
      { marker: 'p53', pct: [70, 95], note: 'aberrante na maioria, por assinatura UV' },
      { marker: 'ki67', pct: [70, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma espinocelular sarcomatoide: queratinas ou p40 positivos ao menos focalmente.',
      'Melanoma desdiferenciado: pode perder SOX10; procure componente in situ e história de melanoma.',
      'Leiomiossarcoma cutâneo: desmina e h-caldesmon positivos difusos.',
      'Angiossarcoma: CD31 e ERG positivos, canais vasculares dissecando o colágeno.',
    ],
    pitfalls: ['É diagnóstico de exclusão: laudar sem o painel completo é o erro clássico.', 'CD10 positivo não confirma nada: CEC e dermatofibroma também marcam.'],
    molecular: 'Assinatura UV com TP53 mutado e alta carga mutacional; sem alteração definidora.',
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Goldblum, Folpe & Weiss, Enzinger & Weiss\'s Soft Tissue Tumors, 7ª ed.', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
  {
    id: 'angiossarcoma-cutaneo',
    name: 'Angiossarcoma cutâneo',
    aka: ['angiossarcoma de cabeça e pescoço', 'angiossarcoma pós-radioterapia', 'síndrome de Stewart-Treves', 'cutaneous angiosarcoma'],
    behavior: 'maligno',
    sites: [
      { site: 'pele', role: 'primario', freq: 1 },
      { site: 'mama', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['vasoformativo', 'epitelioide', 'fusocelular', 'pleomorfico'],
    architecture: ['infiltrativo', 'lencois'],
    features: ['hemorragia', 'mitoses-altas', 'necrose', 'tachinha'],
    ages: ['idoso'],
    summary: 'Canais vasculares anastomosados irregulares que dissecam o colágeno dérmico, revestidos por células endoteliais atípicas em tachinha, com áreas sólidas epitelioides ou fusocelulares.',
    criteria: [
      'Canais vasculares infiltrativos, anastomosados, dissecando feixes de colágeno, com endotélio atípico e multicamadas.',
      'Confirmação endotelial por CD31 e ERG (mais específicos que CD34 e fator VIII).',
      'No pós-radioterapia de mama, amplificação de MYC comprovada por imuno-histoquímica ou FISH.',
      'Exclusão de hemangioma atípico pós-radiação (lesão pequena, sem atipia, MYC negativa).',
    ],
    markers: [
      { marker: 'erg', pct: [90, 100] },
      { marker: 'cd31', pct: [85, 100] },
      { marker: 'cd34', pct: [50, 80], note: 'menos sensível, sobretudo nos pouco diferenciados' },
      { marker: 'fli1', pct: [80, 95] },
      { marker: 'd240', pct: [40, 70], note: 'diferenciação linfática em parte' },
      { marker: 'fviii', pct: [40, 70] },
      { marker: 'myc', pct: [90, 100], note: 'nos pós-radioterapia e no linfedema; negativo nos primários esporádicos' },
      { marker: 'ae1ae3', pct: [20, 40], note: 'positiva nas variantes epitelioides: armadilha com carcinoma' },
      { marker: 'ema', pct: [10, 30] },
      { marker: 'ki67', pct: [70, 95] },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'hhv8', pct: [0, 5], note: 'negativo: separa do sarcoma de Kaposi' },
      { marker: 'camta1', pct: [0, 5], note: 'negativo: separa do hemangioendotelioma epitelioide' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Sarcoma de Kaposi: HHV-8 nuclear positivo, fendas com hemácias e glóbulos hialinos.',
      'Hemangioma atípico pós-radiação: pequeno, sem atipia nem mitoses, MYC negativo.',
      'Carcinoma pouco diferenciado: queratinas difusas e ERG negativo.',
      'Hemangioendotelioma epitelioide: CAMTA1 nuclear positivo, estroma mixo-hialino.',
    ],
    pitfalls: ['O angiossarcoma epitelioide expressa queratina em até 1/3: sem ERG/CD31 vira carcinoma metastático.', 'CD31 marca macrófagos; ERG é mais limpo.'],
    molecular: 'Amplificação de MYC nos secundários a radioterapia e linfedema; alterações de KDR e PLCG1 nos primários.',
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Goldblum, Folpe & Weiss, Enzinger & Weiss\'s Soft Tissue Tumors, 7ª ed.'],
  },
  {
    id: 'sarcoma-kaposi',
    name: 'Sarcoma de Kaposi',
    aka: ['Kaposi sarcoma', 'sarcoma de Kaposi clássico, endêmico, epidêmico e iatrogênico'],
    behavior: 'maligno',
    sites: [
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'boca', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'primario', freq: 1 },
      { site: 'colon-reto', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'vasoformativo'],
    architecture: ['fasciculos', 'infiltrativo'],
    features: ['hemorragia', 'globulos-hialinos', 'plasmocitos', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    summary: 'Fascículos de células fusiformes brandas com fendas vasculares contendo hemácias, glóbulos hialinos eosinofílicos, hemossiderina e plasmócitos, em pele de pacientes com HIV, imunossupressão ou origem mediterrânea.',
    criteria: [
      'Células fusiformes formando fendas vasculares mal definidas cheias de hemácias, com o "sinal do promontório" ao redor de vasos preexistentes.',
      'Glóbulos hialinos intracitoplasmáticos e hemossiderina.',
      'HHV-8 (LANA-1) nuclear positivo: obrigatório e praticamente definidor.',
    ],
    markers: [
      { marker: 'hhv8', pct: [95, 100], note: 'LANA-1 nuclear puntiforme; definidor' },
      { marker: 'erg', pct: [90, 100] },
      { marker: 'cd31', pct: [90, 100] },
      { marker: 'cd34', pct: [85, 100] },
      { marker: 'd240', pct: [80, 95], note: 'diferenciação linfática típica' },
      { marker: 'fli1', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [0, 5] },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'sma', pct: [0, 15] },
      { marker: 'ki67', pct: [20, 50] },
      { marker: 'myc', pct: [0, 10], note: 'negativo, ao contrário do angiossarcoma pós-radioterapia' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Angiossarcoma: HHV-8 negativo, atipia muito maior, canais anastomosados.',
      'Hemangioendotelioma kaposiforme: criança, nódulos com microtrombos, HHV-8 negativo.',
      'Fibrossarcoma ou DFSP: CD31, ERG e HHV-8 negativos.',
      'Angiomatose bacilar: aglomerados bacilares com Warthin-Starry, neutrófilos, HHV-8 negativo.',
    ],
    molecular: 'Infecção por herpesvírus humano 8 (HHV-8 / KSHV) em todas as formas.',
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK534839/', 'https://dermnetnz.org/topics/kaposi-sarcoma-pathology', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)'],
  },
  {
    id: 'hemangioma-cutaneo',
    name: 'Hemangioma cutâneo e granuloma piogênico',
    aka: ['hemangioma capilar lobular', 'granuloma piogênico', 'hemangioma infantil', 'hemangioma cavernoso'],
    behavior: 'benigno',
    sites: [{ site: 'pele', role: 'primario', freq: 3 }],
    cells: ['vasoformativo', 'epitelioide'],
    architecture: ['lobular', 'nodular'],
    features: ['hemorragia', 'mitoses-raras'],
    ages: ['crianca', 'jovem', 'adulto'],
    summary: 'Proliferação vascular benigna em lóbulos bem delimitados de capilares com endotélio brando; o granuloma piogênico é o hemangioma capilar lobular polipoide, ulcerado e com colarete epidérmico.',
    criteria: [
      'Arquitetura lobular de capilares com endotélio regular, sem atipia, necrose nem canais anastomosados dissecantes.',
      'Granuloma piogênico: lesão polipoide com colarete epidérmico, edema, ulceração e infiltrado neutrofílico.',
      'Hemangioma infantil: GLUT1 positivo (o congênito e os outros hemangiomas são negativos).',
    ],
    markers: [
      { marker: 'cd31', pct: [95, 100] },
      { marker: 'erg', pct: [95, 100] },
      { marker: 'cd34', pct: [90, 100] },
      { marker: 'glut1', pct: [30, 60], note: 'positivo no hemangioma infantil, negativo nos demais e nas malformações' },
      { marker: 'fviii', pct: [70, 95] },
      { marker: 'd240', pct: [0, 20], note: 'positivo se houver componente linfático' },
      { marker: 'hhv8', pct: [0, 2], note: 'negativo: separa do sarcoma de Kaposi' },
      { marker: 'myc', pct: [0, 5] },
      { marker: 'sma', pct: [60, 90], note: 'pericitos ao redor dos capilares, arranjo organizado' },
      { marker: 'ki67', pct: [0, 20], note: 'alto na fase proliferativa do hemangioma infantil' },
      { marker: 'fosb', pct: [0, 10], note: 'positivo no hemangioma epitelioide (fusão FOS/FOSB)' },
      { marker: 'ae1ae3', pct: 0 },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Sarcoma de Kaposi em fase inicial: HHV-8 positivo, fendas dissecantes, plasmócitos.',
      'Angiossarcoma bem diferenciado: infiltração dissecante do colágeno com atipia endotelial.',
      'Malformação vascular: canais de parede irregular, sem lobulação nem fase proliferativa, GLUT1 negativo.',
    ],
    sources: ['https://www.ncbi.nlm.nih.gov/books/NBK556077/', 'WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Goldblum, Folpe & Weiss, Enzinger & Weiss\'s Soft Tissue Tumors, 7ª ed.'],
  },
  {
    id: 'leiomioma-cutaneo',
    name: 'Leiomioma cutâneo (piloleiomioma)',
    aka: ['piloleiomioma', 'angioleiomioma', 'leiomioma genital', 'cutaneous leiomyoma'],
    behavior: 'benigno',
    sites: [
      { site: 'pele', role: 'primario', freq: 2 },
      { site: 'vulva-vagina', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'mioide'],
    architecture: ['fasciculos', 'infiltrativo'],
    features: ['hialinizacao', 'mitoses-raras'],
    ages: ['jovem', 'adulto'],
    summary: 'Fascículos entrelaçados de células fusiformes com citoplasma eosinofílico fibrilar e núcleo em charuto de pontas rombas, sem atipia nem mitoses, na derme, doloroso à palpação.',
    criteria: [
      'Células fusiformes com citoplasma eosinofílico brilhante e núcleo alongado de extremidades rombas, em fascículos que se cruzam em ângulo reto.',
      'Sem atipia, necrose ou mitoses relevantes (mais de 1 a 2 por 10 campos de grande aumento levanta dúvida).',
      'Leiomiomas múltiplos: investigar leiomiomatose hereditária e câncer renal (HLRCC) com FH e 2SC.',
    ],
    markers: [
      { marker: 'sma', pct: [95, 100] },
      { marker: 'desmina', pct: [85, 100] },
      { marker: 'caldesmon', pct: [85, 100] },
      { marker: 'calponina', pct: [80, 95] },
      { marker: 'msa', pct: [85, 100] },
      { marker: 'er', pct: [20, 60], note: 'mais nos genitais' },
      { marker: 'pr', pct: [20, 60] },
      { marker: 'fh', pct: [5, 20], note: 'perda nos leiomiomas de HLRCC, com núcleos de nucléolo proeminente em halo' },
      { marker: 'ki67', pct: [0, 10] },
      { marker: 'p53', pct: [0, 10] },
      { marker: 's100', pct: [0, 5] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd34', pct: [0, 15] },
      { marker: 'ae1ae3', pct: [0, 5] },
      { marker: 'hmb45', pct: [0, 5], note: 'negativo: separa do PEComa' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Leiomiossarcoma cutâneo: atipia, mitoses (acima de 1 por 10 campos na pele já preocupa), necrose, Ki-67 alto.',
      'Dermatofibroma: FXIIIa positivo, desmina negativa.',
      'Neurofibroma e schwannoma: S100 e SOX10 positivos.',
      'PEComa cutâneo: HMB-45 e Melan-A positivos.',
    ],
    molecular: 'Perda bialélica de FH nos casos sindrômicos (HLRCC); esporádicos sem alteração definidora.',
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Goldblum, Folpe & Weiss, Enzinger & Weiss\'s Soft Tissue Tumors, 7ª ed.'],
  },
  {
    id: 'ceratose-actinica',
    name: 'Ceratose actínica',
    aka: ['queratose actínica', 'queratose solar', 'actinic keratosis'],
    behavior: 'intermediario',
    sites: [{ site: 'pele', role: 'primario', freq: 3 }],
    cells: ['escamoso', 'basaloide'],
    features: ['queratinizacao', 'precursor', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Atipia dos queratinócitos da camada basal e parabasal em pele fotoexposta, com paraceratose alternando com ortoceratose sobre os óstios foliculares (o sinal de bandeira) e elastose solar embaixo; é a lesão precursora do carcinoma escamoso e o diagnóstico dermatopatológico mais frequente.',
    criteria: [
      'Atipia limitada ao terço inferior da epiderme, com perda da maturação ordenada acima dela.',
      'Paraceratose alternando com ortoceratose, poupando os óstios folicular e sudoríparo.',
      'Elastose solar na derme papilar.',
      'Atipia de espessura total define carcinoma in situ (doença de Bowen), e invasão do estroma define carcinoma invasor.',
      'Variantes hipertrófica, atrófica, bowenoide, liquenoide, acantolítica e pigmentada não mudam a conduta.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p53', pct: [40, 70], note: 'padrão aberrante já no precursor, por dano actínico de TP53' },
      { marker: 'ki67', pct: [10, 30], note: 'basal e parabasal; espessura total favorece doença de Bowen' },
      { marker: 'p16', pct: [5, 20], note: 'focal; em bloco levanta lesão HPV-associada' },
      { marker: 'berep4', pct: [0, 10], note: 'o negativo que separa do carcinoma basocelular' },
      { marker: 'sox10', pct: [0, 5], note: 'marca só os melanócitos intraepidérmicos, não os queratinócitos' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Doença de Bowen: atipia de espessura total, Ki-67 em toda a altura.',
      'Carcinoma escamoso invasor: ninhos abaixo da membrana basal com desmoplasia.',
      'Carcinoma basocelular superficial: BerEP4 positivo, paliçada periférica, fenda de retração.',
      'Lentigo maligno: proliferação melanocítica, SOX10 e Melan-A nas células atípicas.',
      'Dermatite liquenoide e lúpus: atipia ausente, infiltrado em faixa.',
    ],
    sources: ['WHO Classification of Tumours, 4ª ed.: Skin Tumours (2018)', 'Calonje et al., McKee’s Pathology of the Skin, 5ª ed.'],
  },
]
