/* ==========================================================================
   thorax.ts — pulmão, pleura, mediastino, coração e esôfago.

   É o bloco que mais aparece na rotina de imuno-histoquímica: separar
   adenocarcinoma de carcinoma espinocelular no pulmão, decidir se um
   adenocarcinoma pulmonar é primário ou metástase, e resolver mesotelioma
   contra adenocarcinoma na pleura.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Thoracic Tumours, 2021; recomendações da IASLC e do
   International Mesothelioma Interest Group; revisões de imuno-histoquímica
   em Arch Pathol Lab Med, Mod Pathol e Am J Surg Pathol; guias do NordiQC
   sobre clones). As fontes estão como referência de texto: as séries não
   foram abertas uma a uma nesta rodada.

   Um aviso que vale para todo o arquivo: **o clone de TTF-1 muda o
   resultado**. O 8G7G3/1 é mais específico; o SPT24 é mais sensível e marca
   com alguma frequência tumores extrapulmonares (colorretal, ginecológico,
   pequenas células de qualquer sítio). As faixas aqui assumem 8G7G3/1,
   salvo quando a nota diz o contrário.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Thoracic Tumours (2021)'
const IASLC = 'IASLC Atlas of Diagnostic Immunohistochemistry (2020)'
const IMIG = 'Guidelines for Pathologic Diagnosis of Malignant Mesothelioma, Arch Pathol Lab Med (consenso IMIG, atualização 2018)'

export const thorax: Tumor[] = [
  /* ---- Pulmão ------------------------------------------------------------------ */
  {
    id: 'adenocarcinoma-pulmonar',
    name: 'Adenocarcinoma pulmonar',
    aka: ['adenocarcinoma de pulmão não mucinoso', 'lung adenocarcinoma', 'adenocarcinoma acinar, lepídico, papilar, micropapilar e sólido'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'encefalo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 3 },
      { site: 'adrenal', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'pleura', role: 'metastase', freq: 2 },
      { site: 'pele', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide', 'claras'],
    architecture: ['glandulas', 'papilar', 'micropapilar', 'lencois', 'lobular'],
    features: ['mucina', 'desmoplasia', 'necrose', 'mitoses-moderadas', 'psamomas'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma com formação glandular, papilar ou lepídica, ou sólido com mucina, positivo para TTF-1 e napsina A; o tumor pulmonar mais comum e o mais frequente em não fumantes.',
    criteria: [
      'Diferenciação glandular morfológica (acinar, lepídica, papilar, micropapilar) ou padrão sólido com mucina intracitoplasmática.',
      'TTF-1 positivo apoia origem pulmonar; napsina A confirma e é mais específica para o adenocarcinoma.',
      'p40 negativo: em biópsia pequena, o par TTF-1 mais p40 resolve a maioria dos casos com dois anticorpos.',
      'Sempre correlacionar com a clínica: TTF-1 positivo não exclui metástase de tireoide (tireoglobulina e PAX8 separam).',
      'Testar EGFR, ALK, ROS1, BRAF, KRAS G12C e PD-L1 nos avançados: o resultado muda o tratamento de primeira linha.',
    ],
    markers: [
      { marker: 'ttf1', pct: [65, 85], note: 'clone 8G7G3/1 (65 a 82% nas séries comparativas); o SPT24 sobe para cerca de 85%, com menos especificidade', source: 'Comparison of Three Different TTF-1 Clones in Resected Primary Lung Cancer, Am J Clin Pathol 150:533 (2018)' },
      { marker: 'napsina', pct: [70, 85], note: 'mais específica que TTF-1 para adenocarcinoma pulmonar' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'cam52', pct: [90, 100] },
      { marker: 'p40', pct: [0, 5], note: 'negativo: o achado que separa do carcinoma espinocelular' },
      { marker: 'p63', pct: [10, 30], note: 'menos específica que p40: pode ser positiva aqui' },
      { marker: 'ck56', pct: [5, 20] },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'cdx2', pct: [0, 10], note: 'positivo sobretudo no mucinoso invasivo' },
      { marker: 'satb2', pct: [0, 5], note: 'negativo: separa de metástase colorretal' },
      { marker: 'gata3', pct: [0, 10], note: 'negativo: separa de mama e urotélio' },
      { marker: 'er', pct: [0, 10] },
      { marker: 'pax8', pct: [0, 5], note: 'negativo: separa de tireoide, rim e mülleriano' },
      { marker: 'calretinina', pct: [5, 20], note: 'focal possível: não basta para mesotelioma' },
      { marker: 'wt1', pct: [0, 5], note: 'negativo: chave contra mesotelioma e seroso' },
      { marker: 'claudina4', pct: [90, 100], note: 'positiva: separa de mesotelioma' },
      { marker: 'moc31', pct: [85, 100] },
      { marker: 'berep4', pct: [85, 100] },
      { marker: 'alk', pct: [4, 7], note: 'positiva reflete rearranjo; confirmar por FISH ou NGS' },
      { marker: 'ros1', pct: [1, 3], note: 'triagem: todo positivo exige confirmação molecular' },
      { marker: 'pdl1', pct: [25, 35], note: 'preditivo, não diagnóstico (TPS ≥ 50%)' },
      { marker: 'p53', pct: [40, 60] },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma espinocelular pulmonar: p40 e CK5/6 positivos, TTF-1 negativo.',
      'Mesotelioma epitelioide: calretinina, WT1 e D2-40 positivos, claudina-4 e MOC-31 negativos.',
      'Metástase de mama: GATA3, ER e TRPS1 positivos, TTF-1 negativo.',
      'Metástase colorretal: CDX2, SATB2 e CK20 positivos, CK7 e TTF-1 negativos.',
      'Carcinoma de tireoide metastático: TTF-1 positivo também, mas com tireoglobulina e PAX8.',
    ],
    pitfalls: ['TTF-1 pelo clone SPT24 marca tumores extrapulmonares: sempre saber qual clone o laboratório usa.', 'Napsina A também é positiva em carcinoma renal de células claras e em carcinoma de células claras ginecológico.'],
    molecular: 'EGFR (mais frequente em não fumantes), KRAS (incluindo G12C), ALK, ROS1, BRAF V600E, MET exon 14, RET, NTRK e HER2.',
    sources: [WHO, IASLC, 'Yatabe et al., J Thorac Oncol 2019 (recomendações da IASLC sobre TTF-1 e clones)'],
  },
  {
    id: 'adenocarcinoma-mucinoso-invasivo',
    name: 'Adenocarcinoma mucinoso invasivo do pulmão',
    aka: ['carcinoma bronquioloalveolar mucinoso (nome antigo)', 'invasive mucinous adenocarcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'anel-sinete'],
    architecture: ['lobular', 'glandulas', 'infiltrativo'],
    features: ['mucina', 'mitoses-raras', 'desmoplasia'],
    ages: ['adulto', 'idoso'],
    summary: 'Células colunares altas com mucina apical abundante e núcleo basal pequeno, crescendo de forma lepídica e com frequência multifocal ou pneumônica; TTF-1 quase sempre negativo, o que engana.',
    criteria: [
      'Células colunares mucinosas (tipo gástrico ou caliciforme) com atipia leve, crescimento lepídico e mucina nos alvéolos.',
      'Apresentação em consolidação pneumônica ou nódulos múltiplos bilaterais, o que já sugere a variante.',
      'TTF-1 e napsina A negativos na maioria: a origem pulmonar se sustenta na radiologia e na exclusão de primário gastrointestinal ou pancreático.',
      'Quase sempre KRAS mutado; fusões de NRG1 num subgrupo.',
    ],
    markers: [
      { marker: 'ttf1', pct: [15, 30], note: 'negativo na maioria: a grande diferença para o adenocarcinoma pulmonar comum' },
      { marker: 'napsina', pct: [10, 30] },
      { marker: 'ck7', pct: [85, 100] },
      { marker: 'ck20', pct: [40, 70], note: 'positivo com frequência: armadilha com metástase gastrointestinal' },
      { marker: 'cdx2', pct: [30, 60], note: 'idem' },
      { marker: 'muc5ac', pct: [80, 95], note: 'mucina gástrica foveolar' },
      { marker: 'muc2', pct: [20, 50] },
      { marker: 'satb2', pct: [0, 10], note: 'negativo: o melhor argumento contra metástase colorretal' },
      { marker: 'p40', pct: [0, 5] },
      { marker: 'claudina4', pct: [90, 100] },
      { marker: 'moc31', pct: [85, 100] },
      { marker: 'pax8', pct: [0, 10], note: 'negativo: separa de mucinoso ovariano' },
      { marker: 'er', pct: [0, 5] },
      { marker: 'calretinina', pct: [0, 10] },
      { marker: 'p53', pct: [20, 40] },
      { marker: 'ki67', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de adenocarcinoma pancreático ou biliar: quadro clínico e imagem; SMAD4 perdido favorece pâncreas.',
      'Metástase colorretal: SATB2 e CDX2 difusos, CK7 em geral negativa.',
      'Metástase de mucinoso ovariano ou apendicular: PAX8 e história clínica.',
      'Adenocarcinoma pulmonar comum: TTF-1 e napsina positivas.',
    ],
    pitfalls: ['Chamar de metástase gastrointestinal por causa de CK20 e CDX2 positivos com TTF-1 negativo é o erro clássico: SATB2 negativo e a imagem salvam.'],
    molecular: 'KRAS mutado em cerca de 60 a 90%; fusões de NRG1 (CD74::NRG1) num subgrupo tratável.',
    sources: [WHO, IASLC],
  },
  {
    id: 'carcinoma-espinocelular-pulmonar',
    name: 'Carcinoma espinocelular pulmonar',
    aka: ['CEC de pulmão', 'lung squamous cell carcinoma', 'carcinoma escamoso pulmonar'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'adrenal', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 2 },
    ],
    cells: ['escamoso', 'epitelioide', 'basaloide'],
    architecture: ['ninhos', 'lencois', 'infiltrativo'],
    features: ['queratinizacao', 'necrose', 'mitoses-altas', 'desmoplasia', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma central de fumantes, com queratinização e pontes intercelulares, p40 e CK5/6 positivos e TTF-1 negativo; a variante basaloide é sólida e sem queratina evidente.',
    criteria: [
      'Queratinização, pérolas córneas ou pontes intercelulares na morfologia.',
      'Nos pouco diferenciados, p40 difuso mais CK5/6, com TTF-1 e napsina negativos, basta para classificar em biópsia pequena.',
      'Displasia escamosa ou carcinoma in situ brônquico adjacente apoia a origem pulmonar.',
      'A origem pulmonar primária contra metástase de cabeça e pescoço é decidida pela clínica: não existe marcador confiável.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100], note: 'o marcador de escolha; mais específico que p63' },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'ck56', pct: [85, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [30, 60], note: 'pode ser positiva: não use sozinha contra adenocarcinoma' },
      { marker: 'ttf1', pct: [0, 5], note: 'negativo; positividade obriga a rever o diagnóstico' },
      { marker: 'napsina', pct: [0, 3] },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'ck17', pct: [70, 90] },
      { marker: 'sox2', pct: [70, 95], note: 'amplificação de SOX2 é comum' },
      { marker: 'p16', pct: [10, 30], note: 'em bloco sugere origem orofaríngea HPV-associada metastática' },
      { marker: 'calretinina', pct: [10, 30], note: 'armadilha com mesotelioma, que também é CK5/6 positivo' },
      { marker: 'wt1', pct: [0, 5], note: 'negativo: separa do mesotelioma' },
      { marker: 'claudina4', pct: [85, 100] },
      { marker: 'moc31', pct: [70, 95] },
      { marker: 'gata3', pct: [10, 30], note: 'positividade focal descrita: não conclua urotelial' },
      { marker: 'p53', pct: [60, 85] },
      { marker: 'pdl1', pct: [25, 40] },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma sólido: TTF-1 e napsina positivas, p40 negativo.',
      'Mesotelioma epitelioide: calretinina, WT1 e D2-40 positivos, claudina-4 negativa.',
      'Carcinoma espinocelular metastático de cabeça e pescoço: p16 em bloco nos HPV-associados; o resto é clínica.',
      'Carcinoma NUT: NUT nuclear positiva, jovem, curso fulminante.',
      'Timoma tipo B3 e carcinoma tímico: CD5 e CD117 positivos, localização mediastinal.',
    ],
    pitfalls: ['Mesotelioma e CEC compartilham CK5/6 e p63: sem calretinina, WT1 e claudina-4 o erro é fácil na pleura.'],
    molecular: 'Sem alvos consagrados na maioria; amplificação de FGFR1, mutações de PIK3CA e NFE2L2. Testar PD-L1.',
    sources: [WHO, IASLC],
  },
  {
    id: 'carcinoma-pequenas-celulas',
    name: 'Carcinoma de pequenas células',
    aka: ['CPPC', 'small cell carcinoma', 'oat cell carcinoma', 'carcinoma de pequenas células extrapulmonar'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 3 },
      { site: 'bexiga', role: 'primario', freq: 1 },
      { site: 'colo', role: 'primario', freq: 1 },
      { site: 'prostata', role: 'primario', freq: 1 },
      { site: 'esofago', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'encefalo', role: 'metastase', freq: 3 },
      { site: 'osso', role: 'metastase', freq: 2 },
      { site: 'medula-ossea', role: 'metastase', freq: 2 },
      { site: 'adrenal', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino'],
    architecture: ['lencois', 'ninhos', 'trabecular', 'rosetas'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos'],
    ages: ['adulto', 'idoso'],
    summary: 'Células pequenas com citoplasma escasso, cromatina finamente granular sem nucléolo, moldagem nuclear e artefato de esmagamento, com necrose extensa e índice mitótico altíssimo.',
    criteria: [
      'Citologia definidora: tamanho pequeno, relação núcleo/citoplasma altíssima, cromatina fina, nucléolo ausente ou inconspícuo, moldagem.',
      'Mais de 10 mitoses por 2 mm² (em geral muito mais) com necrose geográfica.',
      'Queratina em dot paranuclear e pelo menos um marcador neuroendócrino; cerca de 10% são totalmente negativos para marcadores neuroendócrinos e o diagnóstico segue morfológico.',
      'Ki-67 muito alto (em geral acima de 70%) separa do carcinoide, sobretudo em biópsia esmagada.',
    ],
    markers: [
      { marker: 'insm1', pct: [85, 95], note: 'nuclear; o marcador neuroendócrino mais útil hoje' },
      { marker: 'sinaptofisina', pct: [80, 95] },
      { marker: 'cd56', pct: [85, 95] },
      { marker: 'cromogranina', pct: [40, 60], note: 'fraca e focal: sua negatividade não exclui' },
      { marker: 'ae1ae3', pct: [85, 95], pattern: 'dot', note: 'dot paranuclear típico; negativa em uma minoria' },
      { marker: 'cam52', pct: [85, 95], pattern: 'dot' },
      { marker: 'ttf1', pct: [80, 90], note: 'positivo também nos extrapulmonares: NÃO prova origem pulmonar' },
      { marker: 'ki67', pct: [95, 100], note: 'índice em geral acima de 70%; essencial contra carcinoide' },
      { marker: 'rb1', pct: [85, 95], note: 'PERDA de expressão, junto com p53 aberrante' },
      { marker: 'p53', pct: [80, 95] },
      { marker: 'p40', pct: [0, 5], note: 'negativo: separa do espinocelular basaloide' },
      { marker: 'p63', pct: [10, 30] },
      { marker: 'ck20', pct: [0, 5], note: 'negativa: separa do carcinoma de células de Merkel' },
      { marker: 'cd45', pct: 0, note: 'negativo: separa do linfoma, que é a armadilha em biópsia esmagada' },
      { marker: 'cd99', pct: [10, 30] },
      { marker: 'desmina', pct: [0, 5] },
      { marker: 'nkx31', pct: [0, 10], note: 'positivo aponta origem prostática' },
      { marker: 'pdl1', pct: [10, 25] },
    ],
    mimics: [
      'Linfoma: CD45 positivo, queratina negativa; a armadilha clássica na biópsia esmagada.',
      'Carcinoma de células de Merkel: CK20 em dot, TTF-1 negativo.',
      'Carcinoide atípico: Ki-67 abaixo de 30%, cromatina grosseira, nucléolo, sem necrose geográfica.',
      'Carcinoma espinocelular basaloide: p40 difuso.',
      'Sarcoma de Ewing: CD99 membranoso, NKX2.2, queratina em geral negativa.',
    ],
    pitfalls: ['TTF-1 é positivo em pequenas células de qualquer sítio: não use para provar origem pulmonar.', 'Em biópsia esmagada, peça CD45 antes de assumir carcinoma.'],
    molecular: 'Inativação de TP53 e RB1 em praticamente todos; amplificação de MYC em parte. Subtipos por ASCL1, NEUROD1, POU2F3 e YAP1.',
    sources: [WHO, IASLC],
  },
  {
    id: 'carcinoma-neuroendocrino-grandes-celulas',
    name: 'Carcinoma neuroendócrino de grandes células',
    aka: ['LCNEC', 'large cell neuroendocrine carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
    ],
    cells: ['epitelioide', 'neuroendocrino', 'pleomorfico'],
    architecture: ['organoide', 'trabecular', 'rosetas', 'palicada'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma de células grandes com arquitetura neuroendócrina (organoide, trabecular, paliçada periférica, rosetas), nucléolo evidente, necrose extensa e mais de 10 mitoses por 2 mm², com marcador neuroendócrino positivo.',
    criteria: [
      'Morfologia neuroendócrina reconhecível em pequeno aumento mais citologia de células grandes com nucléolo.',
      'Mais de 10 mitoses por 2 mm² e necrose (em geral extensa).',
      'Confirmação obrigatória por pelo menos um marcador neuroendócrino: sem ele, o tumor é carcinoma de grandes células.',
      'A distinção do carcinoma de pequenas células é citológica (tamanho, nucléolo, cromatina), não imuno-histoquímica.',
    ],
    markers: [
      { marker: 'insm1', pct: [80, 95] },
      { marker: 'sinaptofisina', pct: [75, 90] },
      { marker: 'cromogranina', pct: [50, 75] },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [90, 100], note: 'difusa, sem o padrão em dot das pequenas células' },
      { marker: 'ttf1', pct: [40, 60], note: 'menos frequente que nas pequenas células' },
      { marker: 'napsina', pct: [0, 10] },
      { marker: 'p40', pct: [0, 5], note: 'negativo: separa do espinocelular' },
      { marker: 'ck7', pct: [50, 80] },
      { marker: 'ki67', pct: [85, 100], note: 'em geral 40 a 80%: alto, mas às vezes menor que nas pequenas células' },
      { marker: 'rb1', pct: [40, 70], note: 'perda no subgrupo de tipo pequenas células' },
      { marker: 'p53', pct: [60, 85] },
      { marker: 'sstr2', pct: [20, 50] },
      { marker: 'cd45', pct: 0 },
      { marker: 'pdl1', pct: [10, 30] },
    ],
    mimics: [
      'Carcinoma de pequenas células: células menores, sem nucléolo, cromatina fina, queratina em dot.',
      'Carcinoide atípico: Ki-67 e mitoses bem menores, sem necrose geográfica.',
      'Adenocarcinoma sólido com marcador neuroendócrino focal: sem arquitetura neuroendócrina, não é LCNEC.',
      'Carcinoma de grandes células: nenhum marcador neuroendócrino positivo.',
    ],
    pitfalls: ['Positividade neuroendócrina focal em adenocarcinoma comum não faz LCNEC: a arquitetura tem de estar lá.'],
    molecular: 'Dois grupos: tipo pequenas células (TP53 e RB1) e tipo não pequenas células (STK11, KEAP1, KRAS).',
    sources: [WHO, IASLC],
  },
  {
    id: 'carcinoide-pulmonar',
    name: 'Tumor carcinoide pulmonar (típico e atípico)',
    aka: ['tumor neuroendócrino pulmonar', 'carcinoide típico', 'carcinoide atípico', 'pulmonary carcinoid'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['neuroendocrino', 'epitelioide', 'oncocitico', 'fusocelular'],
    architecture: ['organoide', 'trabecular', 'ninhos', 'rosetas'],
    features: ['mitoses-raras', 'mitoses-moderadas', 'vasos-espessos', 'necrose'],
    ages: ['jovem', 'adulto'],
    summary: 'Ninhos e trabéculas de células uniformes com cromatina em sal e pimenta e citoplasma eosinofílico, em estroma ricamente vascularizado; típico quando tem menos de 2 mitoses por 2 mm² e nenhuma necrose.',
    criteria: [
      'Arquitetura organoide com células monótonas, cromatina granular fina e nucléolo inconspícuo.',
      'Carcinoide típico: menos de 2 mitoses por 2 mm² e ausência de necrose.',
      'Carcinoide atípico: 2 a 10 mitoses por 2 mm² ou necrose pontual.',
      'Contar mitoses em 2 mm² e avaliar necrose é o que define o grau: a imuno confirma a linhagem, não o grau.',
      'Cuidado com o esmagamento da biópsia brônquica, que simula carcinoma de pequenas células.',
    ],
    markers: [
      { marker: 'cromogranina', pct: [90, 100], note: 'forte e difusa, ao contrário das pequenas células' },
      { marker: 'sinaptofisina', pct: [95, 100] },
      { marker: 'insm1', pct: [90, 100] },
      { marker: 'cd56', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [80, 95] },
      { marker: 'ttf1', pct: [30, 50], note: 'mais nos periféricos; a negatividade não exclui origem pulmonar' },
      { marker: 'cdx2', pct: [0, 15], note: 'positivo aponta origem em intestino médio' },
      { marker: 'satb2', pct: [0, 10], note: 'positivo aponta origem retal' },
      { marker: 'isl1', pct: [10, 40], note: 'positivo aponta origem pancreática ou retal' },
      { marker: 'sstr2', pct: [70, 95], note: 'base da cintilografia e do tratamento com análogos de somatostatina' },
      { marker: 'ki67', pct: [10, 30], note: 'em geral abaixo de 5% no típico e 5 a 20% no atípico; não substitui a contagem de mitoses' },
      { marker: 'rb1', pct: [0, 10], note: 'retido, ao contrário das pequenas células' },
      { marker: 'p53', pct: [0, 15], note: 'selvagem: a aberração sugere carcinoma neuroendócrino' },
      { marker: 'serotonina', pct: [20, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma de pequenas células: Ki-67 acima de 70%, p53 aberrante, perda de RB1, necrose extensa.',
      'LCNEC: mitoses acima de 10 por 2 mm².',
      'NET metastático de outro sítio: CDX2, SATB2, ISL1 e a clínica.',
      'Paraganglioma: queratina negativa, GATA3 positiva.',
      'Tumorlet e hiperplasia de células neuroendócrinas: menor que 5 mm.',
    ],
    pitfalls: ['O grau é morfológico: Ki-67 ajuda contra pequenas células, mas não define típico contra atípico.'],
    molecular: 'Mutações de MEN1, ARID1A e EIF1AX; TP53 e RB1 preservados. Associação com MEN1 nos multifocais.',
    sources: [WHO, IASLC, 'WHO Classification of Endocrine and Neuroendocrine Tumours, 5ª ed. (2022)'],
  },
  {
    id: 'carcinoma-sarcomatoide-pulmonar',
    name: 'Carcinoma pleomórfico e sarcomatoide do pulmão',
    aka: ['carcinoma pleomórfico', 'carcinoma de células fusiformes e gigantes', 'carcinossarcoma pulmonar'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 1 },
      { site: 'pleura', role: 'metastase', freq: 1 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['pleomorfico', 'fusocelular', 'gigantes', 'epitelioide'],
    architecture: ['lencois', 'fasciculos', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'hemorragia', 'desmoplasia'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma pouco diferenciado com pelo menos 10% de componente fusocelular ou de células gigantes, muitas vezes com adenocarcinoma ou espinocelular associado; grande, periférico, em fumantes pesados.',
    criteria: [
      'Componente sarcomatoide (fusiforme ou de células gigantes) de pelo menos 10% do tumor.',
      'Demonstração de linhagem epitelial: queratina ou TTF-1 ao menos focais, ou um componente carcinomatoso convencional.',
      'Carcinossarcoma quando há elemento heterólogo verdadeiro (osso, cartilagem, músculo esquelético).',
      'Excluir sarcoma primário, mesotelioma sarcomatoide e metástase de melanoma.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [70, 90], note: 'pode ser focal: use painel amplo de queratinas' },
      { marker: 'cam52', pct: [60, 85] },
      { marker: 'ttf1', pct: [30, 60] },
      { marker: 'napsina', pct: [10, 30] },
      { marker: 'p40', pct: [10, 30], note: 'no componente espinocelular' },
      { marker: 'ck7', pct: [50, 80] },
      { marker: 'vimentina', pct: [80, 95], note: 'coexpressa com queratina' },
      { marker: 'calretinina', pct: [10, 30], note: 'armadilha com mesotelioma sarcomatoide' },
      { marker: 'd240', pct: [10, 30] },
      { marker: 'bap1', pct: [0, 10], note: 'retido: a perda favorece mesotelioma' },
      { marker: 'mtap', pct: [10, 30] },
      { marker: 's100', pct: [0, 10] },
      { marker: 'sox10', pct: [0, 5], note: 'negativo: separa de melanoma' },
      { marker: 'desmina', pct: [0, 15] },
      { marker: 'mdm2', pct: [0, 10] },
      { marker: 'pdl1', pct: [50, 80], note: 'expressão alta frequente; pode responder a imunoterapia' },
      { marker: 'p53', pct: [60, 85] },
      { marker: 'ki67', pct: [70, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Mesotelioma sarcomatoide: perda de BAP1 ou de MTAP, crescimento em casca pleural, calretinina e D2-40.',
      'Sarcoma primário ou metastático: queratinas negativas em painel amplo.',
      'Melanoma sarcomatoide: SOX10 positivo.',
      'Carcinoma metastático sarcomatoide renal: PAX8 positivo.',
    ],
    molecular: 'MET exon 14 skipping em cerca de 20 a 30% (alvo terapêutico), KRAS e TP53 frequentes.',
    sources: [WHO, IASLC],
  },
  {
    id: 'tumor-toracico-smarca4',
    name: 'Tumor torácico indiferenciado SMARCA4-deficiente',
    aka: ['SMARCA4-deficient undifferentiated tumour', 'SMARCA4-UT', 'sarcoma torácico SMARCA4-deficiente'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 1 },
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'pleura', role: 'primario', freq: 1 },
    ],
    cells: ['epitelioide', 'rabdoide', 'pleomorfico'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'nucleolo'],
    ages: ['adulto'],
    sex: 'm',
    summary: 'Lençóis discoesos de células epitelioides grandes com morfologia rabdoide, nucléolo proeminente e necrose, em homens fumantes de meia-idade, com massa torácica volumosa e curso muito agressivo.',
    criteria: [
      'Morfologia indiferenciada epitelioide/rabdoide, sem diferenciação glandular ou escamosa.',
      'Perda completa de BRG1 (SMARCA4) nuclear, muitas vezes com perda também de BRM (SMARCA2).',
      'Expressão de queratina apenas focal, com CD34, SOX2 e SALL4 frequentemente positivos.',
      'Excluir carcinoma pulmonar SMARCA4-deficiente (que mantém morfologia de adenocarcinoma) e tumor rabdoide.',
    ],
    markers: [
      { marker: 'brg1', pct: [95, 100], note: 'PERDA nuclear completa; é o que define a entidade' },
      { marker: 'ini1', pct: [0, 10], note: 'retido, ao contrário do tumor rabdoide' },
      { marker: 'ae1ae3', pct: [30, 60], note: 'focal e fraca' },
      { marker: 'cd34', pct: [50, 70], note: 'positivo com frequência: achado útil' },
      { marker: 'sox2', pct: [50, 80] },
      { marker: 'sall4', pct: [40, 70], note: 'armadilha com tumor de células germinativas no mediastino' },
      { marker: 'ttf1', pct: [0, 10] },
      { marker: 'p40', pct: [0, 5] },
      { marker: 'claudina4', pct: [10, 30] },
      { marker: 'oct4', pct: [0, 10], note: 'negativo: separa de carcinoma embrionário e seminoma' },
      { marker: 'cd117', pct: [10, 30] },
      { marker: 'calretinina', pct: [10, 30] },
      { marker: 'cd45', pct: 0 },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'ki67', pct: [70, 100] },
    ],
    mimics: [
      'Carcinoma de grandes células e sarcomatoide: BRG1 retido.',
      'Tumor de células germinativas mediastinal: OCT4 e CD30 positivos, SALL4 também positivo (armadilha).',
      'Mesotelioma epitelioide: calretinina e WT1 difusos, BRG1 retido.',
      'Melanoma e linfoma: SOX10 ou CD45.',
      'Tumor rabdoide: perda de INI1, não de BRG1, e em criança.',
    ],
    molecular: 'Inativação bialélica de SMARCA4; carga mutacional alta com assinatura de tabaco. Pode responder a imunoterapia.',
    sources: [WHO, 'Rekhtman et al., Mod Pathol 2020 (tumores torácicos SMARCA4-deficientes)'],
  },
  {
    id: 'blastoma-pleuropulmonar',
    name: 'Blastoma pleuropulmonar',
    aka: ['PPB', 'pleuropulmonary blastoma', 'tumor DICER1 pulmonar'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 1 },
      { site: 'pleura', role: 'primario', freq: 1 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['blastematoso', 'fusocelular', 'pequenas-redondas', 'cartilaginoso'],
    architecture: ['cistico', 'lencois', 'nodular'],
    features: ['estroma-mixoide', 'necrose', 'mitoses-altas', 'condroide'],
    ages: ['crianca'],
    summary: 'Tumor de criança pequena, puramente cístico (tipo I) a sólido (tipo III), com camada cambial subepitelial de células blastematosas primitivas sob epitélio respiratório benigno e focos de rabdomioblastos e cartilagem.',
    criteria: [
      'Criança menor de 6 anos com lesão cística ou sólida pulmonar/pleural.',
      'Componente mesenquimal maligno primitivo sob epitélio respiratório NÃO neoplásico: a chave é que o epitélio é benigno.',
      'Rabdomioblastos (desmina e miogenina) e nódulos de cartilagem displásica.',
      'Mutação de DICER1, germinativa em cerca de dois terços: investigar a família (nódulos tireoidianos, Sertoli-Leydig, nefroma cístico).',
    ],
    markers: [
      { marker: 'desmina', pct: [60, 90], note: 'nos rabdomioblastos' },
      { marker: 'miogenina', pct: [50, 80] },
      { marker: 'myod1', pct: [50, 80] },
      { marker: 's100', pct: [40, 70], note: 'na cartilagem' },
      { marker: 'sox9', pct: [40, 70] },
      { marker: 'ae1ae3', pct: [20, 50], note: 'apenas no epitélio benigno aprisionado, não no componente maligno' },
      { marker: 'ttf1', pct: [10, 40], note: 'idem: marca o epitélio residual' },
      { marker: 'cd34', pct: [20, 50] },
      { marker: 'wt1', pct: [10, 40] },
      { marker: 'p53', pct: [30, 60], note: 'aberrante nos tipos II e III' },
      { marker: 'ini1', pct: [0, 5] },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'betacatenina', pct: [0, 15], note: 'nuclear negativa: separa do blastoma pulmonar do adulto' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Malformação adenomatoide cística congênita: sem camada cambial nem atipia.',
      'Blastoma pulmonar do adulto: epitélio maligno com β-catenina nuclear.',
      'Rabdomiossarcoma embrionário: sem os componentes cartilaginoso e cístico característicos.',
      'Sarcoma sinovial pulmonar: SS18-SSX positivo, adulto.',
    ],
    molecular: 'Mutações de DICER1 (germinativa em 66%), com perda da função do domínio RNase IIIb.',
    sources: [WHO, 'WHO Classification of Paediatric Tumours, 5ª ed. (2022)'],
  },
  {
    id: 'blastoma-pulmonar-adulto',
    name: 'Adenocarcinoma fetal e blastoma pulmonar do adulto',
    aka: ['fetal adenocarcinoma', 'blastoma pulmonar bifásico', 'adenocarcinoma fetal de baixo grau'],
    behavior: 'maligno',
    sites: [
      { site: 'pulmao', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'blastematoso', 'fusocelular'],
    architecture: ['glandulas', 'trabecular'],
    features: ['glicogenio', 'mitoses-moderadas', 'necrose'],
    ages: ['jovem', 'adulto'],
    summary: 'Glândulas tubulares de células colunares ricas em glicogênio que lembram o pulmão fetal pseudoglandular, com mórulas escamoides; no blastoma, essas glândulas convivem com estroma blastematoso maligno.',
    criteria: [
      'Glândulas complexas ramificadas de epitélio colunar com vacúolos subnucleares e supranucleares de glicogênio.',
      'Mórulas escamoides (redondelas de células escamoides), que concentram a β-catenina nuclear.',
      'Adenocarcinoma fetal de baixo grau: só o componente epitelial, com estroma benigno. Blastoma: estroma primitivo maligno associado.',
      'β-catenina nuclear e citoplasmática reflete mutação de CTNNB1: separa do adenocarcinoma convencional.',
    ],
    markers: [
      { marker: 'betacatenina', pct: [80, 95], pattern: 'N', note: 'nuclear, concentrada nas mórulas; muito característica' },
      { marker: 'ttf1', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [90, 100], note: 'no componente epitelial' },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'sinaptofisina', pct: [50, 80], note: 'nas mórulas e em células neuroendócrinas dispersas' },
      { marker: 'cromogranina', pct: [30, 60] },
      { marker: 'napsina', pct: [30, 60] },
      { marker: 'p40', pct: [0, 10], note: 'negativo apesar das mórulas escamoides' },
      { marker: 'vimentina', pct: [50, 80], note: 'no estroma do blastoma' },
      { marker: 'desmina', pct: [10, 30], note: 'em focos heterólogos do blastoma' },
      { marker: 'sall4', pct: [10, 40] },
      { marker: 'afp', pct: [10, 30] },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'p53', pct: [20, 50], note: 'mais no blastoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma pulmonar convencional: β-catenina só membranosa, sem mórulas.',
      'Blastoma pleuropulmonar: criança, epitélio benigno, DICER1.',
      'Carcinossarcoma pulmonar: componentes malignos convencionais, sem padrão fetal.',
      'Metástase de adenocarcinoma endometrioide com mórulas: PAX8 e ER positivos.',
    ],
    molecular: 'Mutação de CTNNB1 (β-catenina) na maioria dos de baixo grau; o blastoma e o fetal de alto grau têm alterações adicionais.',
    sources: [WHO, IASLC],
  },
  /* ---- Pleura ------------------------------------------------------------------- */
  {
    id: 'mesotelioma-epitelioide',
    name: 'Mesotelioma epitelioide',
    aka: ['mesotelioma maligno epitelioide', 'epithelioid mesothelioma', 'mesotelioma peritoneal'],
    behavior: 'maligno',
    sites: [
      { site: 'pleura', role: 'primario', freq: 3 },
      { site: 'peritoneo', role: 'primario', freq: 2 },
      { site: 'coracao', role: 'primario', freq: 1 },
      { site: 'testiculo', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'oncocitico', 'claras'],
    architecture: ['papilar', 'trabecular', 'lencois', 'glandulas', 'micropapilar'],
    features: ['desmoplasia', 'psamomas', 'mitoses-moderadas', 'necrose'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Proliferação de células epitelioides poligonais com citoplasma eosinofílico denso e nucléolo, em padrão tubulopapilar ou sólido, invadindo a gordura e formando casca pleural; história de asbesto.',
    criteria: [
      'Invasão verdadeira do estroma (gordura, músculo, parênquima) é o que separa de hiperplasia mesotelial reativa.',
      'Dois marcadores mesoteliais positivos (calretinina, WT1, D2-40, CK5/6) e dois epiteliais negativos (claudina-4, MOC-31, BerEP4, TTF-1, CEA).',
      'Perda de BAP1 nuclear ou perda de MTAP (substituto da deleção de CDKN2A) comprovam malignidade em amostra difícil, inclusive em líquido.',
      'Nenhuma das duas perdas exclui malignidade: a ausência delas não torna a lesão benigna.',
    ],
    markers: [
      { marker: 'calretinina', pct: [85, 100] },
      { marker: 'wt1', pct: [70, 95], note: 'nuclear' },
      { marker: 'd240', pct: [80, 95] },
      { marker: 'ck56', pct: [75, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'mesotelina', pct: [80, 95] },
      { marker: 'hbme1', pct: [80, 95] },
      { marker: 'claudina4', pct: [0, 5], note: 'negativa: um dos melhores marcadores contra adenocarcinoma' },
      { marker: 'moc31', pct: [0, 10] },
      { marker: 'berep4', pct: [0, 10] },
      { marker: 'cea', pct: [0, 5], note: 'negativo: clássico contra adenocarcinoma' },
      { marker: 'ttf1', pct: [0, 3] },
      { marker: 'napsina', pct: [0, 3] },
      { marker: 'bap1', pct: [50, 70], note: 'PERDA nuclear; prova malignidade, mas a retenção não exclui' },
      { marker: 'mtap', pct: [50, 70], note: 'PERDA citoplasmática, substituta da deleção de CDKN2A' },
      { marker: 'p16', pct: [40, 70] },
      { marker: 'gata3', pct: [10, 30], note: 'positiva em parte: armadilha com mama e urotélio' },
      { marker: 'pax8', pct: [0, 10], note: 'negativo: separa do seroso ovariano, que também é WT1 positivo' },
      { marker: 'er', pct: [0, 10], note: 'idem' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma pulmonar invadindo a pleura: claudina-4, MOC-31, TTF-1 e napsina positivos.',
      'Carcinoma seroso ovariano ou peritoneal: WT1 positivo também, mas com PAX8, ER e p53 aberrante.',
      'Hiperplasia mesotelial reativa: sem invasão, BAP1 e MTAP retidos.',
      'Carcinoma de mama metastático: GATA3, ER e TRPS1.',
      'Carcinoma renal metastático: PAX8 e CA-IX.',
    ],
    pitfalls: ['WT1 positivo não distingue mesotelioma de seroso: PAX8 é o desempate.', 'Calretinina é positiva em alguns carcinomas escamosos e de mama triplo-negativos.'],
    molecular: 'Inativação de BAP1, CDKN2A e NF2; BAP1 germinativa na síndrome de predisposição.',
    sources: [WHO, IMIG, 'Husain et al., Arch Pathol Lab Med 2018 (diretrizes para o diagnóstico de mesotelioma)'],
  },
  {
    id: 'mesotelioma-sarcomatoide',
    name: 'Mesotelioma sarcomatoide e desmoplásico',
    aka: ['sarcomatoid mesothelioma', 'mesotelioma desmoplásico'],
    behavior: 'maligno',
    sites: [
      { site: 'pleura', role: 'primario', freq: 2 },
      { site: 'peritoneo', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular', 'pleomorfico'],
    architecture: ['fasciculos', 'storiforme', 'infiltrativo'],
    features: ['desmoplasia', 'necrose', 'mitoses-altas'],
    ages: ['idoso'],
    sex: 'm',
    summary: 'Proliferação fusocelular atípica em fascículos ou em estroma densamente colagenizado (variante desmoplásica), formando casca pleural e invadindo a parede torácica; imunofenótipo pobre e prognóstico péssimo.',
    criteria: [
      'Células fusiformes atípicas com queratina positiva ao menos focal: a queratina é o achado mais importante, já que os marcadores mesoteliais falham.',
      'Invasão da gordura, do músculo ou do parênquima, ou necrose, na variante desmoplásica (que é 50% ou mais de colágeno paucicelular).',
      'Calretinina, WT1 e D2-40 são muito menos sensíveis que na forma epitelioide.',
      'Perda de BAP1 ou de MTAP ajuda, mas é menos frequente aqui do que no epitelioide.',
      'Distinguir de pleurite fibrosa organizada: a fibrose reativa tem zonalidade e vasos perpendiculares à superfície, sem invasão.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [70, 90], note: 'pode ser focal; a negatividade completa não exclui' },
      { marker: 'cam52', pct: [60, 85] },
      { marker: 'calretinina', pct: [30, 60], note: 'bem menos sensível que no epitelioide' },
      { marker: 'd240', pct: [30, 60] },
      { marker: 'wt1', pct: [10, 30] },
      { marker: 'ck56', pct: [20, 50] },
      { marker: 'gata3', pct: [50, 80], note: 'positiva com frequência: útil contra carcinoma sarcomatoide pulmonar, que costuma ser negativo' },
      { marker: 'bap1', pct: [15, 35], note: 'perda menos frequente que no epitelioide' },
      { marker: 'mtap', pct: [50, 80], note: 'perda frequente (deleção de CDKN2A é quase universal no sarcomatoide)' },
      { marker: 'claudina4', pct: [0, 10] },
      { marker: 'moc31', pct: [0, 10] },
      { marker: 'ttf1', pct: [0, 5] },
      { marker: 'p40', pct: [0, 10] },
      { marker: 's100', pct: [0, 10] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'desmina', pct: [0, 15], note: 'positiva na hiperplasia mesotelial reativa, não no mesotelioma' },
      { marker: 'stat6', pct: [0, 5], note: 'negativo: separa do tumor fibroso solitário' },
      { marker: 'mdm2', pct: [0, 10] },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Pleurite fibrosa organizada: zonalidade, sem invasão, MTAP e BAP1 retidos.',
      'Carcinoma sarcomatoide pulmonar invadindo a pleura: TTF-1 ou p40 focais, GATA3 negativa.',
      'Tumor fibroso solitário: STAT6 e CD34 positivos, queratina negativa.',
      'Sarcoma sinovial pleural: SS18-SSX positivo.',
      'Melanoma e sarcoma: SOX10, ou queratina negativa em painel amplo.',
    ],
    pitfalls: ['Desmina positiva favorece hiperplasia mesotelial reativa, não mesotelioma: é o inverso do que a intuição sugere.'],
    molecular: 'Deleção de CDKN2A em quase todos, BAP1 e NF2 alterados; TP53 frequente.',
    sources: [WHO, IMIG],
  },
  /* ---- Mediastino --------------------------------------------------------------- */
  {
    id: 'timoma',
    name: 'Timoma',
    aka: ['timoma tipo A, AB, B1, B2 e B3', 'thymoma'],
    behavior: 'intermediario',
    sites: [
      { site: 'mediastino', role: 'primario', freq: 3 },
      { site: 'pleura', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'fusocelular', 'linfoide-pequenas'],
    architecture: ['lobular', 'lencois', 'fasciculos'],
    features: ['linfoide', 'hialinizacao', 'mitoses-raras'],
    ages: ['adulto', 'idoso'],
    summary: 'Neoplasia epitelial tímica organotípica, com lóbulos separados por septos fibrosos e mistura de células epiteliais brandas com timócitos imaturos; associada a miastenia gravis.',
    criteria: [
      'Arquitetura organotípica: lóbulos com septos fibrosos, espaços perivasculares e, nos tipos B, timócitos TdT positivos abundantes.',
      'Células epiteliais sem atipia significativa (o que separa do carcinoma tímico).',
      'Tipos: A (fusocelular, pobre em linfócitos), AB (misto), B1 (rico em linfócitos, lembra timo normal), B2 (epiteliais dispersas em fundo linfocitário), B3 (epiteliais predominantes, atipia leve).',
      'Estadiamento de Masaoka-Koga pela invasão da cápsula e dos órgãos vizinhos: é o que dá o prognóstico, mais que o tipo.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [95, 100], note: 'realça a rede epitelial, essencial nos tipos ricos em linfócitos' },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'pax8', pct: [70, 90], note: 'com anticorpo policlonal (reação cruzada com PAX5/PAX2); o monoclonal é negativo' },
      { marker: 'tdt', pct: [70, 95], note: 'nos timócitos imaturos, não nas células epiteliais; quase ausente no tipo A e no B3' },
      { marker: 'cd1a', pct: [70, 90], note: 'idem' },
      { marker: 'cd99', pct: [70, 90], note: 'idem' },
      { marker: 'cd5', pct: [0, 10], note: 'NEGATIVO nas células epiteliais: a chave contra o carcinoma tímico (marca os timócitos, cuidado)' },
      { marker: 'cd117', pct: [0, 10], note: 'negativo nas epiteliais: idem' },
      { marker: 'glut1', pct: [0, 20] },
      { marker: 'ttf1', pct: [0, 5] },
      { marker: 'calretinina', pct: [20, 50] },
      { marker: 'cd20', pct: [20, 50], note: 'positivo nas células epiteliais do tipo A e AB: achado curioso e útil' },
      { marker: 'ki67', pct: [0, 20], note: 'alto nos timócitos, baixo nas epiteliais' },
    ],
    mimics: [
      'Carcinoma tímico: CD5 e CD117 positivos nas epiteliais, atipia franca, sem timócitos TdT.',
      'Linfoma linfoblástico T: TdT positivo em lençol difuso sem rede epitelial de queratina.',
      'Linfoma de Hodgkin e linfoma B mediastinal: CD30, CD20, sem rede epitelial.',
      'Tumor de células germinativas: OCT4, SALL4, CD30.',
      'Hiperplasia tímica: arquitetura tímica normal preservada, com corpúsculos de Hassall.',
    ],
    pitfalls: ['TdT positivo assusta e faz pensar em linfoma linfoblástico: a rede de queratina resolve.', 'PAX8 positivo no timoma é artefato de clone policlonal, não indica tireoide nem rim.'],
    molecular: 'GTF2I mutado nos tipos A e AB (bom prognóstico); alterações de TP53 e CDKN2A nos tipos B3 e no carcinoma.',
    sources: [WHO, IASLC],
  },
  {
    id: 'carcinoma-timico',
    name: 'Carcinoma tímico',
    aka: ['thymic carcinoma', 'carcinoma escamoso tímico'],
    behavior: 'maligno',
    sites: [
      { site: 'mediastino', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'pleura', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['escamoso', 'epitelioide', 'basaloide'],
    architecture: ['ninhos', 'lencois', 'infiltrativo'],
    features: ['desmoplasia', 'queratinizacao', 'necrose', 'mitoses-altas'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma mediastinal com atipia franca, estroma desmoplásico e ausência de arquitetura organotípica tímica; o tipo escamoso é o mais comum e expressa CD5 e CD117.',
    criteria: [
      'Atipia citológica evidente com desmoplasia e crescimento infiltrativo, sem lóbulos nem espaços perivasculares.',
      'Ausência de timócitos imaturos TdT positivos (ao contrário do timoma B).',
      'CD5 e CD117 positivos nas células epiteliais tumorais: a combinação mais útil, sobretudo contra carcinoma escamoso pulmonar metastático.',
      'Excluir metástase antes de assumir primário tímico: é diagnóstico de exclusão em massa mediastinal.',
    ],
    markers: [
      { marker: 'cd5', pct: [70, 90], note: 'nas células epiteliais tumorais; raro em carcinoma escamoso pulmonar' },
      { marker: 'cd117', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'p40', pct: [85, 100] },
      { marker: 'ck56', pct: [80, 95] },
      { marker: 'pax8', pct: [50, 80], note: 'policlonal; o monoclonal é negativo' },
      { marker: 'glut1', pct: [70, 90], note: 'positiva, ao contrário do timoma' },
      { marker: 'tdt', pct: [0, 10], note: 'ausência de timócitos imaturos: separa do timoma B3' },
      { marker: 'cd1a', pct: [0, 10] },
      { marker: 'ttf1', pct: [0, 5], note: 'negativo: ajuda contra adenocarcinoma pulmonar' },
      { marker: 'calretinina', pct: [10, 30] },
      { marker: 'cd30', pct: [0, 10], note: 'negativo: separa de carcinoma embrionário' },
      { marker: 'oct4', pct: [0, 5] },
      { marker: 'sall4', pct: [0, 15] },
      { marker: 'mtap', pct: [40, 70], note: 'perda descrita por deleção de CDKN2A' },
      { marker: 'p53', pct: [50, 80] },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'pdl1', pct: [50, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Timoma B3: sem atipia franca, CD5 e CD117 negativos nas epiteliais, GLUT1 negativa.',
      'Carcinoma escamoso pulmonar metastático: CD5 e CD117 em geral negativos.',
      'Carcinoma NUT: NUT nuclear positiva, jovem.',
      'Seminoma mediastinal: OCT4, PLAP e CD117 positivos mas queratina fraca e CD5 negativo.',
      'Linfoma B mediastinal primário: CD20 e CD30 fraco, queratina negativa.',
    ],
    pitfalls: ['CD117 sozinho não serve: seminoma também é positivo. Use com CD5, OCT4 e p40.'],
    molecular: 'Deleção de CDKN2A, mutações de TP53; GTF2I ausente (ao contrário do timoma A).',
    sources: [WHO, IASLC],
  },
  {
    id: 'tumor-neuroendocrino-timico',
    name: 'Tumor neuroendócrino tímico',
    aka: ['carcinoide tímico', 'thymic neuroendocrine tumour', 'carcinoma neuroendócrino tímico'],
    behavior: 'maligno',
    sites: [
      { site: 'mediastino', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
      { site: 'figado', role: 'metastase', freq: 1 },
    ],
    cells: ['neuroendocrino', 'epitelioide', 'oncocitico'],
    architecture: ['organoide', 'trabecular', 'rosetas'],
    features: ['necrose', 'calcificacao', 'mitoses-moderadas', 'mitoses-altas'],
    ages: ['adulto'],
    sex: 'm',
    summary: 'Ninhos e trabéculas de células neuroendócrinas no mediastino anterior, com necrose central em comedo e calcificação; comporta-se pior que o carcinoide pulmonar de mesmo grau e associa-se a MEN1 e a síndrome de Cushing por ACTH.',
    criteria: [
      'Arquitetura organoide com marcadores neuroendócrinos positivos em massa do mediastino anterior.',
      'Graduação por mitoses e necrose, como no pulmão, mas com comportamento mais agressivo em cada grau.',
      'Investigar MEN1 (até 25% dos casos) e produção ectópica de ACTH.',
      'Excluir paraganglioma mediastinal (queratina negativa) e metástase de NET de outro sítio.',
    ],
    markers: [
      { marker: 'sinaptofisina', pct: [90, 100] },
      { marker: 'cromogranina', pct: [80, 95] },
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'ae1ae3', pct: [90, 100], note: 'positiva: separa do paraganglioma' },
      { marker: 'ttf1', pct: [0, 15], note: 'em geral negativo: ajuda contra carcinoide pulmonar' },
      { marker: 'cdx2', pct: [0, 10] },
      { marker: 'pax8', pct: [20, 50], note: 'policlonal' },
      { marker: 'sstr2', pct: [60, 90] },
      { marker: 'acth', pct: [20, 40], note: 'nos casos com síndrome de Cushing' },
      { marker: 'cd5', pct: [0, 15] },
      { marker: 'cd117', pct: [10, 30] },
      { marker: 'gata3', pct: [0, 15], note: 'negativa: separa do paraganglioma' },
      { marker: 'tdt', pct: [0, 5] },
      { marker: 'ki67', pct: [30, 70] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Paraganglioma mediastinal: queratina negativa, GATA3 positiva, células sustentaculares S100.',
      'Carcinoide pulmonar metastático: TTF-1 mais provável, imagem.',
      'Timoma B3 e carcinoma tímico: p40 positivo, marcadores neuroendócrinos negativos.',
      'Carcinoma de pequenas células metastático: citologia e Ki-67 muito alto.',
    ],
    molecular: 'MEN1 alterado em parte; cariótipo com perdas em 3p e 11q.',
    sources: [WHO, 'WHO Classification of Endocrine and Neuroendocrine Tumours, 5ª ed. (2022)'],
  },
  /* ---- Coração ------------------------------------------------------------------ */
  {
    id: 'mixoma-cardiaco',
    name: 'Mixoma cardíaco',
    aka: ['cardiac myxoma', 'mixoma atrial', 'complexo de Carney'],
    behavior: 'benigno',
    sites: [{ site: 'coracao', role: 'primario', freq: 3 }],
    cells: ['estreladas', 'fusocelular'],
    architecture: ['trabecular', 'nodular'],
    features: ['estroma-mixoide', 'hemorragia', 'calcificacao', 'mitoses-raras'],
    ages: ['adulto'],
    summary: 'Massa gelatinosa polipoide do átrio esquerdo, presa ao septo interatrial, formada por células estreladas e fusiformes (lepídicas) isoladas ou em cordões e anéis perivasculares, em matriz mixoide com hemorragia e hemossiderina.',
    criteria: [
      'Células mixoides estreladas e fusiformes, isoladas ou em cordões e estruturas em anel ao redor de capilares.',
      'Matriz mixoide abundante com hemorragia, hemossiderina, corpos de Gamna-Gandy e trombos de superfície.',
      'Localização: átrio esquerdo, fossa oval, em mais de 75% dos casos.',
      'Mixomas múltiplos, ventriculares ou em jovem: investigar complexo de Carney (PRKAR1A), com lentigos e tumores endócrinos.',
    ],
    markers: [
      { marker: 'calretinina', pct: [80, 95], note: 'nas células mixoides; o marcador mais útil' },
      { marker: 'cd31', pct: [40, 70], note: 'em parte das células, apoiando origem endotelial primitiva' },
      { marker: 'erg', pct: [30, 60] },
      { marker: 'cd34', pct: [40, 70] },
      { marker: 'vimentina', pct: [90, 100] },
      { marker: 's100', pct: [20, 50] },
      { marker: 'ae1ae3', pct: [0, 15], note: 'focal possível nas células glandulares entremeadas' },
      { marker: 'sma', pct: [10, 40] },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'd240', pct: [10, 40] },
      { marker: 'ki67', pct: [0, 5] },
      { marker: 'mdm2', pct: [0, 5], note: 'negativo: separa de sarcoma intimal mixoide' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Trombo organizado: laminação, sem células mixoides calretinina positivas.',
      'Sarcoma intimal ou mixofibrossarcoma cardíaco: atipia, mitoses, MDM2 amplificado.',
      'Fibroelastoma papilar: eixo colagenoso avascular revestido por endotélio, na valva.',
      'Fibrose endocárdica e organização de trombo mural: sem células mixoides calretinina positivas.',
    ],
    molecular: 'Mutação de PRKAR1A nos casos sindrômicos (complexo de Carney) e em parte dos esporádicos.',
    sources: [WHO, 'Fletcher, Diagnostic Histopathology of Tumors, 5ª ed.'],
  },
  {
    id: 'sarcoma-cardiaco',
    name: 'Sarcoma cardíaco primário',
    aka: ['angiossarcoma cardíaco', 'sarcoma intimal', 'cardiac sarcoma'],
    behavior: 'maligno',
    sites: [
      { site: 'coracao', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['pleomorfico', 'fusocelular', 'vasoformativo', 'epitelioide'],
    architecture: ['infiltrativo', 'lencois', 'fasciculos'],
    features: ['hemorragia', 'necrose', 'mitoses-altas', 'estroma-mixoide'],
    ages: ['adulto'],
    summary: 'Sarcoma de alto grau infiltrando o miocárdio: angiossarcoma no átrio direito (canais vasculares atípicos e hemorragia) ou sarcoma intimal na artéria pulmonar e no átrio esquerdo, com amplificação de MDM2.',
    criteria: [
      'Massa infiltrativa mural, e não polipoide pediculada como o mixoma.',
      'Angiossarcoma: átrio direito, canais anastomosados atípicos, CD31 e ERG positivos.',
      'Sarcoma intimal: crescimento intraluminal na artéria pulmonar ou no átrio esquerdo, fusocelular pleomórfico, MDM2 e CDK4 amplificados.',
      'Excluir metástase e invasão direta (bem mais comuns que o sarcoma primário) e mixoma com alterações degenerativas.',
    ],
    markers: [
      { marker: 'erg', pct: [40, 70], note: 'no angiossarcoma' },
      { marker: 'cd31', pct: [40, 70], note: 'idem' },
      { marker: 'cd34', pct: [30, 60] },
      { marker: 'mdm2', pct: [30, 60], note: 'amplificado no sarcoma intimal; confirme por FISH' },
      { marker: 'cdk4', pct: [30, 60] },
      { marker: 'ae1ae3', pct: [10, 30], note: 'focal no angiossarcoma epitelioide: armadilha com carcinoma' },
      { marker: 'calretinina', pct: [10, 30], note: 'negativa nas células tumorais; positiva no mixoma' },
      { marker: 'desmina', pct: [10, 30], note: 'no leiomiossarcoma e no rabdomiossarcoma cardíacos' },
      { marker: 'sma', pct: [20, 50] },
      { marker: 'myc', pct: [10, 30], note: 'amplificado em angiossarcomas secundários a radioterapia' },
      { marker: 's100', pct: [0, 15] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'p53', pct: [50, 80] },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Mixoma cardíaco: polipoide, calretinina positiva, sem atipia.',
      'Metástase ou invasão direta de carcinoma: queratinas difusas.',
      'Linfoma cardíaco primário: CD45 e CD20 positivos.',
      'Trombo organizado com atipia reativa: sem mitoses atípicas nem infiltração mural.',
    ],
    molecular: 'Sarcoma intimal: amplificação de MDM2, CDK4 e PDGFRA. Angiossarcoma: alterações de KDR e POT1 (esta última familiar).',
    sources: [WHO, 'Fletcher, Diagnostic Histopathology of Tumors, 5ª ed.'],
  },
  /* ---- Esôfago ------------------------------------------------------------------- */
  {
    id: 'adenocarcinoma-esofagico',
    name: 'Adenocarcinoma do esôfago e da junção esofagogástrica',
    aka: ['adenocarcinoma de Barrett', 'oesophageal adenocarcinoma', 'adenocarcinoma da JEG'],
    behavior: 'maligno',
    sites: [
      { site: 'esofago', role: 'primario', freq: 3 },
      { site: 'estomago', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'anel-sinete', 'epitelioide'],
    architecture: ['glandulas', 'cribriforme', 'infiltrativo', 'fila-indiana'],
    features: ['mucina', 'desmoplasia', 'necrose', 'mitoses-altas', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'm',
    summary: 'Adenocarcinoma do terço distal do esôfago e da junção, quase sempre sobre esôfago de Barrett, com displasia adjacente; homens, obesidade e refluxo crônico.',
    criteria: [
      'Glândulas malignas infiltrando a parede, com displasia em Barrett adjacente quando amostrada.',
      'Metaplasia intestinal (células caliciformes) no epitélio colunar adjacente apoia a origem no Barrett.',
      'Imuno não é necessária para o diagnóstico, mas HER2, PD-L1, MMR e claudina 18.2 são obrigatórios nos avançados, porque definem o tratamento.',
      'Distinguir do adenocarcinoma gástrico proximal é convencional (regra de Siewert), não imuno-histoquímico.',
    ],
    markers: [
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ck20', pct: [40, 70], note: 'padrão misto CK7+/CK20+ é típico do Barrett' },
      { marker: 'cdx2', pct: [60, 85] },
      { marker: 'satb2', pct: [10, 30], note: 'em geral negativo: ajuda contra metástase colorretal' },
      { marker: 'muc5ac', pct: [50, 80] },
      { marker: 'muc2', pct: [40, 70] },
      { marker: 'her2', pct: [15, 25], note: 'superexpressão 3+; critérios próprios do trato gastrointestinal (positividade lateral, não circunferencial)' },
      { marker: 'p53', pct: [60, 85], note: 'aberrante já na displasia: útil para confirmar displasia em Barrett' },
      { marker: 'mlh1', pct: [3, 10], note: 'perda menos comum que no estômago distal' },
      { marker: 'pms2', pct: [3, 10] },
      { marker: 'pdl1', pct: [30, 50], note: 'avaliado por CPS' },
      { marker: 'ttf1', pct: [0, 5], note: 'negativo: separa de adenocarcinoma pulmonar invadindo' },
      { marker: 'p40', pct: [0, 5] },
      { marker: 'gata3', pct: [0, 10] },
      { marker: 'ecaderina', pct: [70, 95], note: 'perda nos componentes de anel de sinete' },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma gástrico proximal: distinção topográfica, não imuno-histoquímica.',
      'Adenocarcinoma pulmonar invadindo o esôfago: TTF-1 e napsina positivas.',
      'Carcinoma espinocelular basaloide com padrão pseudoglandular: p40 positivo.',
      'Metástase colorretal: SATB2 difuso, CK7 negativa.',
    ],
    molecular: 'TP53 quase universal, amplificações de ERBB2, VEGFA, GATA6 e CCNE1; instabilidade cromossômica (subtipo CIN do TCGA).',
    sources: [WHO, 'WHO Classification of Tumours, 5ª ed.: Digestive System Tumours (2019)'],
  },
  {
    id: 'carcinoma-espinocelular-esofagico',
    name: 'Carcinoma espinocelular do esôfago',
    aka: ['CEC de esôfago', 'oesophageal squamous cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'esofago', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['escamoso', 'basaloide', 'fusocelular'],
    architecture: ['ninhos', 'infiltrativo', 'lencois'],
    features: ['queratinizacao', 'desmoplasia', 'necrose', 'mitoses-altas', 'precursor'],
    ages: ['adulto', 'idoso'],
    summary: 'Carcinoma escamoso do terço médio e superior do esôfago, ligado a álcool, tabaco e bebidas muito quentes, com displasia escamosa adjacente; o tipo mais comum no mundo.',
    criteria: [
      'Ninhos de células escamosas atípicas com queratinização ou pontes intercelulares, invadindo a parede.',
      'Displasia escamosa ou carcinoma in situ na mucosa adjacente apoia a origem esofágica.',
      'p40 e CK5/6 confirmam a linhagem escamosa nos pouco diferenciados.',
      'p16 em bloco é raro aqui: ao contrário da orofaringe, o HPV tem pouco papel no esôfago.',
    ],
    markers: [
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [90, 100] },
      { marker: 'ck56', pct: [85, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [10, 30] },
      { marker: 'ck20', pct: [0, 5] },
      { marker: 'cdx2', pct: [0, 5], note: 'negativo: separa do adenocarcinoma' },
      { marker: 'ttf1', pct: [0, 3] },
      { marker: 'p16', pct: [5, 20], note: 'em bloco é raro; HPV tem papel pequeno no esôfago' },
      { marker: 'p53', pct: [60, 90] },
      { marker: 'her2', pct: [0, 5], note: 'não se testa neste tipo' },
      { marker: 'pdl1', pct: [30, 50], note: 'avaliado por CPS; define imunoterapia' },
      { marker: 'ecaderina', pct: [80, 95] },
      { marker: 'sox2', pct: [70, 95] },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma pouco diferenciado: CDX2 e CK7 positivos, p40 negativo.',
      'Carcinoma de pequenas células esofágico: INSM1 e sinaptofisina positivos, p40 negativo.',
      'Melanoma mucoso: SOX10 e S100 positivos.',
      'Carcinoma espinocelular pulmonar invadindo: topografia e imagem; não há marcador que separe.',
    ],
    molecular: 'TP53, CDKN2A, NOTCH1 e amplificação de CCND1 e SOX2; distinto do adenocarcinoma no perfil do TCGA.',
    sources: [WHO, 'WHO Classification of Tumours, 5ª ed.: Digestive System Tumours (2019)'],
  },
  {
    id: 'adenocarcinoma-in-situ-pulmao',
    name: 'Adenocarcinoma in situ, minimamente invasivo e hiperplasia adenomatosa atípica',
    aka: ['AIS', 'MIA', 'hiperplasia adenomatosa atípica', 'AAH', 'lesões pré-invasoras glandulares do pulmão'],
    behavior: 'intermediario',
    sites: [{ site: 'pulmao', role: 'primario', freq: 3 }],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas'],
    features: ['mitoses-raras', 'precursor', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    summary: 'O espectro pré-invasor glandular do pulmão, definido por tamanho e por quanto há de invasão: hiperplasia adenomatosa atípica até 5 mm, adenocarcinoma in situ até 3 cm puramente lepídico, e minimamente invasivo até 3 cm com no máximo 5 mm de invasão. Sobrevida de praticamente 100% quando ressecados, o que torna a medida da invasão a informação central do laudo.',
    criteria: [
      'Crescimento lepídico: células tumorais revestindo as paredes alveolares preservadas, sem destruí-las.',
      'Hiperplasia adenomatosa atípica: foco de até 5 mm, células cuboides ou colunares baixas com lacunas entre si.',
      'Adenocarcinoma in situ: até 3 cm, puramente lepídico, sem invasão, sem necrose e sem invasão linfovascular ou pleural.',
      'Minimamente invasivo: até 3 cm com foco invasor de até 5 mm, medido no maior foco isolado e não pela soma.',
      'A classificação exige a lesão inteira submetida: não se faz AIS nem MIA em biópsia, em citologia, nem quando há múltiplos nódulos.',
    ],
    markers: [
      { marker: 'ttf1', pct: [95, 100] },
      { marker: 'napsina', pct: [85, 100] },
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'p40', pct: 0, note: 'o negativo esperado; a lesão é glandular' },
      { marker: 'p63', pct: [0, 10] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'p53', pct: [0, 10], note: 'selvagem; aberrante deve fazer procurar invasão' },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cdx2', pct: [0, 5] },
      { marker: 'muc5ac', pct: [10, 40], note: 'na variante mucinosa da AAH e do AIS, que é menos comum' },
      { marker: 'alk', pct: [0, 5], note: 'as alterações acionáveis aparecem no invasor, não aqui' },
      { marker: 'cromogranina', pct: 0 },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma invasivo de padrão lepídico predominante: tem foco invasor acima de 5 mm.',
      'Hiperplasia reativa de pneumócitos tipo II: contexto de dano alveolar difuso, atipia com inflamação, sem nódulo.',
      'Adenoma bronquiolar (tumor papilar muconodular ciliado): duas camadas, com células basais p40 positivas contínuas.',
      'Metástase de adenocarcinoma com crescimento lepídico: TTF-1 negativo, marcador do sítio de origem.',
      'Fibrose com epitélio aprisionado: arquitetura colapsada, sem monotonia celular.',
    ],
    sources: [WHO, IASLC],
  },
]
