/* ==========================================================================
   uterus.ts — corpo uterino, colo, vulva e doença trofoblástica.

   No endométrio a imuno hoje serve para classificar em grupos moleculares
   (POLE, MMR-deficiente, p53 aberrante, sem perfil específico), e é isso que
   guia terapia. Nos mesenquimais a pergunta é sempre a mesma: músculo liso
   (desmina, h-caldesmon) contra estroma endometrial (CD10, ciclina D1, BCOR),
   e depois grau. No colo, p16 em bloco separa o que é HPV do que não é, e o
   que não é (gástrico-tipo) tem prognóstico pior.

   As porcentagens são faixas da literatura corrente (WHO Classification of
   Tumours, 5ª ed., Female Genital Tumours, 2020; Nucci & Oliva, Gynecologic
   Pathology; classificação molecular ProMisE e TCGA; critérios de Stanford
   para tumores de músculo liso; séries de Am J Surg Pathol e Mod Pathol). As
   fontes estão como referência de texto: as séries não foram abertas uma a uma.
   ========================================================================== */

import type { Tumor } from '../types'

const WHO = 'WHO Classification of Tumours, 5ª ed.: Female Genital Tumours (2020)'
const NUCCI = 'Nucci & Oliva, Gynecologic Pathology (série Foundations in Diagnostic Pathology)'
const PROMISE = 'Talhouk et al., classificação molecular ProMisE do carcinoma endometrial; TCGA (Nature, 2013)'
const STANFORD = 'Bell, Kempson & Hendrickson, critérios de Stanford para tumores uterinos de músculo liso'

export const uterus: Tumor[] = [
  {
    id: 'endometrioide-endometrio',
    name: 'Carcinoma endometrioide do endométrio',
    aka: ['adenocarcinoma endometrioide', 'endometrioid endometrial carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'ovario', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide', 'escamoso', 'claras'],
    architecture: ['glandulas', 'cribriforme', 'papilar', 'lencois', 'infiltrativo'],
    features: ['desmoplasia', 'mitoses-moderadas', 'precursor', 'queratinizacao', 'necrose'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'O carcinoma uterino mais comum, ligado a excesso de estrogênio e obesidade: glândulas confluentes com estratificação e perda do estroma entre elas, muitas vezes com morulas escamosas e hiperplasia atípica ao lado; a classificação molecular em quatro grupos hoje pesa mais que o grau.',
    criteria: [
      'Padrão glandular confluente, cribriforme ou papilar viloglandular, com perda do estroma interglandular ou desmoplasia.',
      'Graduação FIGO pelo componente sólido não escamoso (1: até 5%, 2: 6 a 50%, 3: mais de 50%), com subida de grau por atipia nuclear grave.',
      'Classificação molecular em quatro grupos: POLE ultramutado, MMR-deficiente, p53 aberrante e sem perfil específico.',
      'Rastreio universal de MMR por imuno, com MLH1 metilado quando MLH1 e PMS2 estão perdidos.',
      'Invasão miometrial medida em profundidade relativa; padrão MELF deve ser relatado.',
    ],
    markers: [
      { marker: 'er', pct: [80, 95] },
      { marker: 'pr', pct: [70, 90] },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'vimentina', pct: [80, 95], note: 'positiva, ao contrário do endocervical e do colorretal' },
      { marker: 'wt1', pct: [0, 15], note: 'o negativo que separa do seroso ovariano' },
      { marker: 'p53', pct: [10, 20], note: 'aberrante define o grupo de pior prognóstico' },
      { marker: 'p16', pct: [10, 30], note: 'focal e em mosaico; em bloco sugere seroso ou endocervical' },
      { marker: 'betacatenina', pct: [20, 40], pattern: 'N' },
      { marker: 'pten', pct: [40, 70], note: 'o positivo é a perda; é a alteração mais precoce' },
      { marker: 'arid1a', pct: [25, 40], note: 'o positivo é a perda' },
      { marker: 'mlh1', pct: [20, 30], note: 'o positivo é a perda; com PMS2, quase sempre por metilação' },
      { marker: 'pms2', pct: [20, 30] },
      { marker: 'msh2', pct: [2, 5] },
      { marker: 'msh6', pct: [3, 8] },
      { marker: 'napsina', pct: [0, 10], note: 'o negativo contra células claras' },
      { marker: 'hnf1b', pct: [5, 20] },
      { marker: 'cdx2', pct: [10, 30], note: 'nas morulas escamosas; não indica colorretal' },
      { marker: 'ck20', pct: [0, 10] },
      { marker: 'l1cam', pct: [10, 25], note: 'positivo marca risco alto' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Hiperplasia atípica (EIN): sem invasão estromal, sem confluência glandular franca.',
      'Adenocarcinoma endocervical HPV-associado: p16 em bloco, ER e vimentina negativos ou fracos.',
      'Carcinoma seroso endometrial: p53 aberrante, atipia extrema, papilas com células destacando.',
      'Metástase de adenocarcinoma colorretal: CDX2 e SATB2 difusos, CK7 e ER negativos.',
      'Adenomiose com alteração reativa: glândulas com estroma endometrial CD10 positivo ao redor.',
    ],
    molecular: 'PTEN, PIK3CA, ARID1A, CTNNB1; grupos TCGA/ProMisE governam prognóstico e imunoterapia.',
    sources: [WHO, NUCCI, PROMISE],
  },
  {
    id: 'hiperplasia-atipica-ein',
    name: 'Hiperplasia endometrial atípica (neoplasia intraepitelial endometrial)',
    aka: ['EIN', 'hiperplasia complexa atípica', 'atypical hyperplasia'],
    behavior: 'intermediario',
    sites: [{ site: 'utero', role: 'primario', freq: 3 }],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'cribriforme'],
    features: ['mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Lesão precursora do carcinoma endometrioide: área de glândulas apinhadas em que o volume glandular supera o estromal, com citologia diferente do endométrio de fundo, medindo mais de 1 mm; cerca de um terço já tem carcinoma na histerectomia.',
    criteria: [
      'Apinhamento glandular com relação glândula-estroma maior que 1 (o volume glandular supera o estromal).',
      'Alteração citológica da área lesional em relação às glândulas de fundo (núcleo arredondado, nucléolo, perda de polaridade).',
      'Dimensão maior que 1 mm.',
      'Exclusão de mímicos: pólipo, endométrio secretor, alterações por progestágeno e reparo.',
      'Exclusão de carcinoma: confluência glandular, cribras extensas ou desmoplasia levam ao diagnóstico de carcinoma.',
    ],
    markers: [
      { marker: 'pten', pct: [40, 70], note: 'o positivo é a perda; perda em clone contíguo apoia EIN' },
      { marker: 'pax2', pct: [60, 80], note: 'o positivo é a perda; muito útil na distinção com hiperplasia benigna' },
      { marker: 'betacatenina', pct: [20, 40], pattern: 'N' },
      { marker: 'er', pct: [85, 100] },
      { marker: 'pr', pct: [80, 95] },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'p53', pct: [0, 10], note: 'selvagem; aberrante levanta carcinoma intraepitelial seroso' },
      { marker: 'p16', pct: [5, 20] },
      { marker: 'mlh1', pct: [10, 25], note: 'o positivo é a perda; pode preceder o carcinoma' },
      { marker: 'ki67', pct: [10, 30] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Hiperplasia sem atipia: PAX2 e PTEN retidos, citologia igual à do fundo.',
      'Endométrio secretor e alterações por progestágeno: vacúolos, estroma decidualizado.',
      'Metaplasia (eosinofílica, ciliada, mucinosa): sem apinhamento verdadeiro.',
      'Carcinoma endometrioide grau 1: confluência, cribras ou desmoplasia.',
      'Carcinoma intraepitelial seroso: p53 aberrante, atipia extrema em epitélio atrófico.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'seroso-endometrial',
    name: 'Carcinoma seroso do endométrio',
    aka: ['uterine serous carcinoma', 'carcinoma papilífero seroso uterino'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 3 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'ovario', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'glandular', 'pleomorfico', 'claras'],
    architecture: ['papilar', 'glandulas', 'lencois', 'micropapilar'],
    features: ['psamomas', 'necrose', 'mitoses-altas', 'nucleolo', 'tachinha'],
    ages: ['idoso'],
    sex: 'f',
    summary: 'Carcinoma de mulher idosa magra com endométrio atrófico, em papilas curtas e glândulas com células muito atípicas que se destacam para a luz; p53 aberrante e p16 em bloco com ER fraco, dissemina para o peritônio mesmo sem invasão miometrial, e tem o pior prognóstico dos tipos histológicos.',
    criteria: [
      'Atipia nuclear extrema com nucléolos macronucleolares e variação nuclear acentuada.',
      'Papilas curtas e fendas com destacamento celular; a arquitetura pode ser glandular e enganar.',
      'p53 aberrante em quase todos, com Ki-67 alto e p16 em bloco.',
      'Carcinoma intraepitelial seroso no endométrio atrófico é a lesão precursora.',
      'Estadiamento peritoneal completo: dissemina sem invasão miometrial.',
    ],
    markers: [
      { marker: 'p53', pct: [85, 100], note: 'aberrante; é o critério imuno principal' },
      { marker: 'p16', pct: [80, 95], note: 'em bloco, sem HPV' },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'er', pct: [30, 60], note: 'mais fraco e focal que no endometrioide' },
      { marker: 'pr', pct: [10, 40] },
      { marker: 'wt1', pct: [10, 30], note: 'costuma ser negativo, ao contrário do seroso ovariano' },
      { marker: 'ki67', pct: [70, 95] },
      { marker: 'her2', pct: [25, 35], note: 'amplificado em parte: alvo terapêutico validado aqui' },
      { marker: 'pten', pct: [0, 15], note: 'retido, ao contrário do endometrioide' },
      { marker: 'napsina', pct: [0, 10] },
      { marker: 'hnf1b', pct: [10, 30] },
      { marker: 'mlh1', pct: [0, 10] },
      { marker: 'l1cam', pct: [70, 90], note: 'alto neste tipo' },
      { marker: 'vimentina', pct: [30, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma endometrioide grau 3: p53 selvagem na maioria, ER e PR fortes, PTEN perdido.',
      'Carcinoma de células claras: HNF1β e napsina positivos, p53 muitas vezes selvagem.',
      'Carcinoma seroso ovariano ou tubário com envolvimento uterino: WT1 positivo.',
      'Alteração de Arias-Stella e atipia reativa: p53 selvagem, Ki-67 baixo, contexto.',
      'Carcinossarcoma: componente sarcomatoso presente.',
    ],
    pitfalls: ['Carcinoma seroso pode ser puramente glandular e ser lido como endometrioide grau 1; a atipia é que denuncia.'],
    molecular: 'TP53 em quase 100%; amplificação de ERBB2 e de CCNE1; PPP2R1A.',
    sources: [WHO, NUCCI, PROMISE],
  },
  {
    id: 'celulas-claras-endometrio',
    name: 'Carcinoma de células claras do endométrio',
    aka: ['uterine clear cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['claras', 'epitelioide', 'oncocitico'],
    architecture: ['papilar', 'glandulas', 'trabecular', 'cistico'],
    features: ['tachinha', 'hialinizacao', 'glicogenio', 'mitoses-moderadas'],
    ages: ['idoso'],
    sex: 'f',
    summary: 'Carcinoma de células claras ou eosinofílicas em tachinha, com papilas de eixo hialinizado e túbulos, em mulher idosa; ER e PR negativos com napsina e HNF1β positivos, e o p53 costuma ser selvagem, o que o separa do seroso.',
    criteria: [
      'Células com citoplasma claro glicogenado ou eosinofílico, núcleo protruindo na luz (tachinha).',
      'Padrões papilar com eixo hialinizado, tubulocístico e sólido.',
      'Napsina A e HNF1β positivos com ER e PR negativos.',
      'p53 selvagem na maioria; aberrante em minoria, que se comporta pior.',
      'Exclusão de alterações claras reativas e de reação de Arias-Stella.',
    ],
    markers: [
      { marker: 'napsina', pct: [70, 95] },
      { marker: 'hnf1b', pct: [80, 95] },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'er', pct: [0, 20], note: 'o negativo que separa do endometrioide com células claras' },
      { marker: 'pr', pct: [0, 15] },
      { marker: 'p53', pct: [20, 40], note: 'selvagem na maioria' },
      { marker: 'p16', pct: [20, 50], note: 'focal, não em bloco' },
      { marker: 'wt1', pct: [0, 10] },
      { marker: 'amacr', pct: [50, 80] },
      { marker: 'arid1a', pct: [20, 40], note: 'o positivo é a perda' },
      { marker: 'sall4', pct: [0, 10], note: 'o negativo contra saco vitelino' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma seroso com células claras: p53 aberrante, ER pode ser positivo.',
      'Carcinoma endometrioide com alteração secretora: ER e PR positivos, napsina negativa.',
      'Reação de Arias-Stella: contexto gestacional, sem massa, Ki-67 baixo.',
      'Tumor do saco vitelino: SALL4, AFP e glipicano-3, em jovem.',
      'Metástase de carcinoma renal de células claras: CA-IX em caixa, CD10, napsina negativa.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'carcinossarcoma-uterino',
    name: 'Carcinossarcoma uterino',
    aka: ['tumor mülleriano misto maligno', 'MMMT', 'uterine carcinosarcoma'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 2 },
      { site: 'ovario', role: 'primario', freq: 1 },
      { site: 'peritoneo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'fusocelular', 'pleomorfico', 'glandular', 'cartilaginoso'],
    architecture: ['glandulas', 'fasciculos', 'lencois', 'papilar'],
    features: ['necrose', 'mitoses-altas', 'condroide', 'osteoide', 'estriacoes', 'desmoplasia'],
    ages: ['idoso'],
    sex: 'f',
    summary: 'Tumor bifásico com carcinoma (seroso ou endometrioide de alto grau) e sarcoma no mesmo bloco, muitas vezes com elementos heterólogos como cartilagem e rabdomioblastos; é hoje entendido como carcinoma com transdiferenciação sarcomatosa, e é estadiado e tratado como carcinoma.',
    criteria: [
      'Componente carcinomatoso e componente sarcomatoso, ambos malignos, com transição entre eles.',
      'Elementos heterólogos (condrossarcoma, rabdomiossarcoma, osteossarcoma) definem a variante heteróloga.',
      'Queratina e PAX8 positivos no componente epitelial e frequentemente também no sarcomatoso.',
      'p53 aberrante na maioria, nos dois componentes: apoia a clonalidade comum.',
      'Estadiamento como carcinoma endometrial, não como sarcoma.',
    ],
    markers: [
      { marker: 'p53', pct: [70, 95], note: 'aberrante nos dois componentes' },
      { marker: 'pax8', pct: [60, 90], note: 'pode persistir no componente sarcomatoso' },
      { marker: 'ae1ae3', pct: [90, 100], note: 'no epitelial; focal no sarcomatoso' },
      { marker: 'ck7', pct: [80, 95] },
      { marker: 'ema', pct: [70, 95] },
      { marker: 'er', pct: [20, 50] },
      { marker: 'pr', pct: [10, 40] },
      { marker: 'p16', pct: [50, 80] },
      { marker: 'vimentina', pct: [85, 100] },
      { marker: 'desmina', pct: [20, 50], note: 'no componente rabdomioblástico' },
      { marker: 'miogenina', pct: [20, 50] },
      { marker: 's100', pct: [20, 50], note: 'cartilagem' },
      { marker: 'cd10', pct: [20, 50] },
      { marker: 'mlh1', pct: [5, 15], note: 'o positivo é a perda' },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma endometrioide com metaplasia fusocelular: componente fusiforme é queratina positivo e não atípico o bastante.',
      'Leiomiossarcoma: sem componente carcinomatoso, desmina e h-caldesmon difusos.',
      'Adenossarcoma: componente epitelial é benigno.',
      'Sarcoma do estroma endometrial de alto grau: sem carcinoma, BCOR ou ciclina D1.',
      'Rabdomiossarcoma uterino puro: sem carcinoma.',
    ],
    molecular: 'TP53 quase constante; PIK3CA, FBXW7, PPP2R1A; perfil sobreposto ao do seroso.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'carcinoma-desdiferenciado-endometrio',
    name: 'Carcinoma indiferenciado e desdiferenciado do endométrio',
    aka: ['undifferentiated endometrial carcinoma', 'dedifferentiated carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['epitelioide', 'pleomorfico', 'rabdoide', 'linfoide-grandes'],
    architecture: ['lencois'],
    features: ['necrose', 'mitoses-altas', 'linfoide'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Lençóis monótonos de células discoesas de médio tamanho, sem qualquer formação glandular, que parecem linfoma ou sarcoma e expressam queratina apenas focalmente; quando há carcinoma endometrioide grau 1 ou 2 ao lado, chama-se desdiferenciado, e a perda de SMARCA4, SMARCB1 ou ARID1A é frequente.',
    criteria: [
      'Componente indiferenciado: lençóis sólidos discoesos sem glândulas, sem diferenciação escamosa nem neuroendócrina.',
      'Queratina e EMA apenas focais (menos de 10% das células) e ER/PR negativos.',
      'Desdiferenciado: componente endometrioide grau 1 ou 2 justaposto, com transição abrupta.',
      'Perda de SMARCA4 (BRG1), SMARCB1 (INI1) ou ARID1A em parte considerável.',
      'Rastreio de MMR obrigatório: a perda é frequente e abre imunoterapia.',
    ],
    markers: [
      { marker: 'ae1ae3', pct: [50, 80], note: 'focal, em células isoladas' },
      { marker: 'ema', pct: [30, 60], note: 'focal' },
      { marker: 'er', pct: [0, 20], note: 'o negativo é esperado no componente indiferenciado' },
      { marker: 'pr', pct: [0, 15] },
      { marker: 'pax8', pct: [10, 40], note: 'muitas vezes perdido: não use para excluir' },
      { marker: 'brg1', pct: [20, 40], note: 'o positivo é a perda' },
      { marker: 'ini1', pct: [10, 25], note: 'o positivo é a perda' },
      { marker: 'arid1a', pct: [40, 70], note: 'o positivo é a perda' },
      { marker: 'mlh1', pct: [40, 60], note: 'o positivo é a perda; MMR-deficiente é comum aqui' },
      { marker: 'pms2', pct: [40, 60] },
      { marker: 'p53', pct: [20, 50] },
      { marker: 'cd45', pct: 0, note: 'o negativo que exclui linfoma' },
      { marker: 'sinaptofisina', pct: [10, 30], note: 'focal; difusa reclassifica como neuroendócrino' },
      { marker: 'desmina', pct: [0, 10] },
      { marker: 'ki67', pct: [60, 95] },
    ],
    mimics: [
      'Carcinoma endometrioide grau 3: forma glândulas, ER e queratina difusos.',
      'Linfoma difuso de grandes células B: CD45 e CD20 positivos.',
      'Sarcoma do estroma endometrial de alto grau: CD10, ciclina D1 ou BCOR, queratina negativa.',
      'Carcinoma neuroendócrino de grandes células: sinaptofisina e INSM1 difusos.',
      'Rabdomiossarcoma: desmina e miogenina.',
    ],
    molecular: 'SMARCA4, SMARCB1 e ARID1A; MMR-deficiente frequente; subgrupo POLE existe e tem bom prognóstico.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'leiomioma-uterino',
    name: 'Leiomioma uterino',
    aka: ['mioma', 'uterine leiomyoma', 'leiomioma celular'],
    behavior: 'benigno',
    sites: [{ site: 'utero', role: 'primario', freq: 3 }],
    cells: ['fusocelular', 'mioide'],
    architecture: ['fasciculos'],
    features: ['hialinizacao', 'calcificacao', 'mitoses-raras', 'estroma-mixoide', 'vasos-espessos'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'O tumor mais comum do útero: nódulo branco e firme de fascículos entrelaçados de células fusiformes de citoplasma eosinofílico fibrilar e núcleo em charuto, com limites nítidos e sem necrose de coagulação tumoral; a variante FH-deficiente merece reconhecimento porque aponta síndrome hereditária.',
    criteria: [
      'Fascículos entrelaçados de músculo liso com núcleos em charuto de extremidades rombas.',
      'Ausência dos três critérios de malignidade (atipia difusa, necrose de coagulação tumoral, mitoses acima do limiar).',
      'Variantes com limiares próprios: mitoticamente ativo, celular, bizarro (atipia simplástica), mixoide e epitelioide.',
      'Leiomioma FH-deficiente: núcleos com nucléolo e halo perinucleolar, glóbulos eosinofílicos, alvéolos de edema; perda de FH e 2SC positivo.',
      'Necrose hialina (infarto) não é necrose de coagulação tumoral e não conta.',
    ],
    markers: [
      { marker: 'desmina', pct: [90, 100] },
      { marker: 'caldesmon', pct: [85, 100] },
      { marker: 'sma', pct: [90, 100] },
      { marker: 'smmhc', pct: [80, 95] },
      { marker: 'er', pct: [80, 95] },
      { marker: 'pr', pct: [85, 100] },
      { marker: 'cd10', pct: [10, 30], note: 'pode ser positivo; não use isolado contra estroma endometrial' },
      { marker: 'fh', pct: [1, 3], note: 'o positivo é a perda; define a variante FH-deficiente' },
      { marker: 'p16', pct: [10, 30], note: 'difuso favorece leiomiossarcoma' },
      { marker: 'p53', pct: [0, 10], note: 'aberrante favorece leiomiossarcoma' },
      { marker: 'hmb45', pct: [0, 5], note: 'o negativo que separa de PEComa' },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'ciclinad1', pct: [0, 15] },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Leiomiossarcoma: dois ou mais dos três critérios, p16 e p53 alterados, Ki-67 alto.',
      'Sarcoma do estroma endometrial de baixo grau: CD10 difuso, desmina e h-caldesmon negativos, invasão em língua.',
      'PEComa uterino: HMB-45 e Melan-A positivos, células claras ou epitelioides.',
      'Adenomiose com hiperplasia muscular: glândulas endometriais dentro.',
      'Tumor de músculo liso de potencial maligno incerto (STUMP): critérios limítrofes.',
    ],
    pitfalls: ['Atipia simplástica (bizarra) isolada, sem mitoses nem necrose tumoral, é benigna: não chame de sarcoma.'],
    molecular: 'MED12 na maioria; rearranjo de HMGA2; FH na variante deficiente (leiomiomatose hereditária).',
    sources: [WHO, STANFORD, NUCCI],
  },
  {
    id: 'leiomiossarcoma-uterino',
    name: 'Leiomiossarcoma uterino',
    aka: ['uterine leiomyosarcoma', 'LMS uterino'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 3 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'osso', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular', 'pleomorfico', 'epitelioide', 'mioide'],
    architecture: ['fasciculos', 'lencois'],
    features: ['necrose', 'mitoses-altas', 'hemorragia'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Sarcoma de músculo liso do útero, diagnosticado pelos critérios de Stanford: atipia nuclear difusa, necrose de coagulação tumoral e índice mitótico elevado, dos quais dois bastam; metastatiza por via hematogênica para o pulmão e não se beneficia de linfadenectomia.',
    criteria: [
      'No tipo fusocelular convencional: dois de três entre atipia difusa moderada a grave, necrose de coagulação tumoral e 10 ou mais mitoses por 10 campos de grande aumento.',
      'Necrose de coagulação tumoral: transição abrupta entre tumor viável e necrótico, sem zona de granulação.',
      'Limiares mais baixos nas variantes epitelioide e mixoide (4 ou mais mitoses já contam).',
      'Margem infiltrativa e invasão vascular apoiam.',
      'Confirmação de linhagem muscular por desmina e h-caldesmon, que podem enfraquecer nos pouco diferenciados.',
    ],
    markers: [
      { marker: 'desmina', pct: [70, 95], note: 'pode cair nos de alto grau' },
      { marker: 'caldesmon', pct: [70, 90] },
      { marker: 'sma', pct: [80, 95] },
      { marker: 'smmhc', pct: [50, 80] },
      { marker: 'p16', pct: [60, 90], note: 'difuso e forte, ao contrário do leiomioma' },
      { marker: 'p53', pct: [40, 60], note: 'aberrante em cerca de metade' },
      { marker: 'er', pct: [30, 60], note: 'cai em relação ao leiomioma' },
      { marker: 'pr', pct: [30, 60] },
      { marker: 'cd10', pct: [20, 50], note: 'pode ser positivo e confundir com estroma endometrial' },
      { marker: 'rb1', pct: [30, 60], note: 'o positivo é a perda' },
      { marker: 'hmb45', pct: [0, 10], note: 'o negativo que separa de PEComa' },
      { marker: 'melana', pct: [0, 5] },
      { marker: 'ae1ae3', pct: [10, 40], note: 'focal; não conclua carcinossarcoma' },
      { marker: 'ki67', pct: [30, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Leiomioma com atipia bizarra: sem necrose tumoral, mitoses baixas, p16 e p53 normais.',
      'STUMP: critérios ambíguos ou limítrofes.',
      'Sarcoma do estroma endometrial de alto grau: ciclina D1 ou BCOR difusos, desmina negativa.',
      'PEComa: HMB-45, Melan-A e catepsina K.',
      'Carcinossarcoma: componente carcinomatoso presente, PAX8 e queratina difusos.',
    ],
    molecular: 'Cariótipo complexo; TP53, RB1, ATRX, MED12; sem alteração definidora.',
    sources: [WHO, STANFORD, NUCCI],
  },
  {
    id: 'stump-uterino',
    name: 'Tumor uterino de músculo liso de potencial maligno incerto (STUMP)',
    aka: ['STUMP', 'smooth muscle tumour of uncertain malignant potential'],
    behavior: 'intermediario',
    sites: [{ site: 'utero', role: 'primario', freq: 1 }],
    cells: ['fusocelular', 'mioide', 'epitelioide'],
    architecture: ['fasciculos'],
    features: ['mitoses-moderadas', 'necrose', 'hialinizacao'],
    ages: ['adulto'],
    sex: 'f',
    summary: 'Categoria de exclusão para o tumor de músculo liso que preenche apenas um dos critérios de Stanford ou os preenche de modo ambíguo — por exemplo, necrose duvidosa com atipia leve, ou atipia difusa com mitoses no limiar; a maioria se comporta bem, mas exige seguimento.',
    criteria: [
      'Combinações que não alcançam o limiar de leiomiossarcoma nem se enquadram em leiomioma ou suas variantes.',
      'Necrose de coagulação tumoral duvidosa, ou necrose com atipia leve e mitoses baixas.',
      'Atipia difusa com índice mitótico entre 6 e 9 por 10 campos e sem necrose.',
      'Amostragem generosa é obrigatória antes de usar a categoria: um bloco por centímetro.',
      'Perda de FH deve ser afastada: o leiomioma FH-deficiente imita atipia preocupante.',
    ],
    markers: [
      { marker: 'desmina', pct: [85, 100] },
      { marker: 'caldesmon', pct: [80, 95] },
      { marker: 'sma', pct: [90, 100] },
      { marker: 'p16', pct: [30, 60], note: 'difuso desloca para leiomiossarcoma' },
      { marker: 'p53', pct: [10, 30], note: 'aberrante desloca para leiomiossarcoma' },
      { marker: 'er', pct: [60, 90] },
      { marker: 'pr', pct: [60, 90] },
      { marker: 'fh', pct: [5, 15], note: 'o positivo é a perda; reclassifica como leiomioma FH-deficiente' },
      { marker: 'hmb45', pct: [0, 5] },
      { marker: 'ki67', pct: [5, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Leiomiossarcoma: dois ou mais critérios de Stanford.',
      'Leiomioma mitoticamente ativo: mitoses altas sem atipia nem necrose, em mulher jovem ou grávida.',
      'Leiomioma FH-deficiente: perda de FH, morfologia alarmante mas benigna.',
      'Leiomioma com infarto hialino: necrose com zona de granulação.',
    ],
    sources: [WHO, STANFORD],
  },
  {
    id: 'ess-baixo-grau',
    name: 'Sarcoma do estroma endometrial de baixo grau',
    aka: ['LG-ESS', 'low-grade endometrial stromal sarcoma'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 2 },
      { site: 'ovario', role: 'metastase', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular', 'pequenas-redondas', 'estreladas'],
    architecture: ['lencois', 'infiltrativo', 'nodular'],
    features: ['vasos-espessos', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto'],
    sex: 'f',
    summary: 'Proliferação de células pequenas e uniformes idênticas ao estroma endometrial proliferativo, com arteríolas espiraladas em toda a lesão, infiltrando o miométrio em línguas permeativas e invadindo vasos; indolente mas recidivante tardiamente, e responde a bloqueio hormonal.',
    criteria: [
      'Células uniformes pequenas, semelhantes ao estroma endometrial proliferativo, com citoplasma escasso.',
      'Arteríolas espiraladas de pequeno calibre distribuídas regularmente.',
      'Infiltração miometrial em línguas irregulares e invasão linfovascular: é isso que separa do nódulo estromal, que é circunscrito.',
      'CD10 difuso com ER e PR positivos; desmina e h-caldesmon negativos ou focais.',
      'Mitoses escassas e ausência de necrose; atipia mínima.',
    ],
    markers: [
      { marker: 'cd10', pct: [85, 100], note: 'difuso; mas não é específico' },
      { marker: 'er', pct: [80, 95] },
      { marker: 'pr', pct: [85, 100], note: 'base do tratamento hormonal' },
      { marker: 'wt1', pct: [50, 80] },
      { marker: 'caldesmon', pct: [0, 20], note: 'o negativo que separa de músculo liso' },
      { marker: 'desmina', pct: [10, 30], note: 'focal, nas áreas de diferenciação muscular' },
      { marker: 'sma', pct: [20, 50] },
      { marker: 'ciclinad1', pct: [0, 20], note: 'difusa e forte indica alto grau YWHAE' },
      { marker: 'bcor', pct: [0, 15] },
      { marker: 'cd117', pct: [0, 10] },
      { marker: 'betacatenina', pct: [40, 70], pattern: 'N', note: 'reflete a fusão JAZF1 em parte' },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'ki67', pct: [1, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Nódulo estromal endometrial: circunscrito, sem permeação nem invasão vascular.',
      'Leiomioma celular: desmina e h-caldesmon difusos, vasos de parede espessa.',
      'Sarcoma do estroma de alto grau: atipia, mitoses altas, ciclina D1 ou BCOR.',
      'Adenossarcoma: componente epitelial benigno com projeções em folha.',
      'Endometriose e adenomiose: glândulas presentes.',
    ],
    molecular: 'Fusões JAZF1::SUZ12 (a mais comum), PHF1 e outras da via do complexo repressor polycomb.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'ess-alto-grau',
    name: 'Sarcoma do estroma endometrial de alto grau',
    aka: ['HG-ESS', 'sarcoma do estroma YWHAE', 'sarcoma do estroma BCOR'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 1 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['pequenas-redondas', 'fusocelular', 'epitelioide'],
    architecture: ['ninhos', 'lencois', 'fasciculos', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'estroma-mixoide'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Sarcoma estromal com atipia e mitoses altas, em dois grupos moleculares: o YWHAE::NUTM2, com componente redondo ciclina D1 difuso e componente fusocelular de baixo grau, e o BCOR (fusão ou duplicação interna), mixoide e fusocelular; ambos perdem ER, PR e CD10 em relação ao baixo grau.',
    criteria: [
      'Atipia nuclear de alto grau com mitoses numerosas (frequentemente acima de 10 por 10 campos) e necrose.',
      'Perda ou redução de CD10, ER e PR em relação ao sarcoma de baixo grau.',
      'Ciclina D1 nuclear difusa (acima de 70% das células) no grupo YWHAE.',
      'BCOR nuclear no grupo BCOR, muitas vezes com estroma mixoide e colágeno.',
      'Ausência de componente epitelial maligno, o que o separa do carcinossarcoma.',
    ],
    markers: [
      { marker: 'ciclinad1', pct: [80, 100], note: 'difusa e forte no grupo YWHAE; é o marcador prático' },
      { marker: 'bcor', pct: [60, 90], note: 'no grupo BCOR' },
      { marker: 'cd117', pct: [50, 80], note: 'positiva no componente redondo do YWHAE; não é GIST' },
      { marker: 'cd10', pct: [20, 50], note: 'reduzido ou perdido no componente de alto grau' },
      { marker: 'er', pct: [10, 30] },
      { marker: 'pr', pct: [10, 40] },
      { marker: 'caldesmon', pct: [0, 20] },
      { marker: 'desmina', pct: [10, 30] },
      { marker: 'ae1ae3', pct: [0, 20], note: 'o negativo que separa de carcinossarcoma' },
      { marker: 'pax8', pct: [0, 15] },
      { marker: 'p53', pct: [10, 30] },
      { marker: 'dog1', pct: [0, 10], note: 'negativa apesar do CD117 positivo' },
      { marker: 'ki67', pct: [30, 80] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Sarcoma do estroma de baixo grau: CD10, ER e PR fortes, ciclina D1 focal.',
      'Leiomiossarcoma: desmina e h-caldesmon difusos.',
      'Carcinossarcoma: componente carcinomatoso, PAX8 e queratina.',
      'Rabdomiossarcoma uterino: miogenina e MyoD1.',
      'Sarcoma indiferenciado uterino: sem fusão e sem marcador definidor.',
    ],
    molecular: 'YWHAE::NUTM2A/B; fusões e duplicação interna em tandem de BCOR; ZC3H7B::BCOR.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'adenossarcoma-uterino',
    name: 'Adenossarcoma uterino',
    aka: ['müllerian adenosarcoma', 'adenossarcoma mülleriano'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 1 },
      { site: 'colo', role: 'primario', freq: 1 },
      { site: 'ovario', role: 'primario', freq: 1 },
    ],
    cells: ['fusocelular', 'glandular', 'estreladas'],
    architecture: ['papilar', 'cistico', 'glandulas'],
    features: ['mitoses-moderadas', 'estroma-mixoide', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Tumor bifásico com epitélio benigno e estroma maligno de baixo grau: as glândulas se tornam fendas em folha de samambaia comprimidas pelo estroma, que forma manguitos hipercelulares periglandulares; o que piora o prognóstico é o crescimento sarcomatoso excessivo e a invasão miometrial profunda.',
    criteria: [
      'Componente epitelial benigno (glandular mülleriano) com componente estromal maligno.',
      'Arquitetura em folha de samambaia com projeções polipoides intraglandulares.',
      'Manguito estromal periglandular hipercelular, com atipia e mitoses acima de 2 por 10 campos.',
      'Crescimento sarcomatoso excessivo (mais de 25% de estroma puro de alto grau) muda o prognóstico radicalmente.',
      'Elementos heterólogos e invasão miometrial devem ser relatados.',
    ],
    markers: [
      { marker: 'cd10', pct: [70, 95], note: 'no estroma neoplásico' },
      { marker: 'er', pct: [60, 90], note: 'no estroma' },
      { marker: 'pr', pct: [60, 90] },
      { marker: 'wt1', pct: [50, 80] },
      { marker: 'ki67', pct: [10, 40], note: 'concentrado no manguito periglandular' },
      { marker: 'ae1ae3', pct: [0, 10], note: 'só o epitélio benigno' },
      { marker: 'pax8', pct: [0, 15], note: 'só o epitélio' },
      { marker: 'desmina', pct: [10, 40] },
      { marker: 'caldesmon', pct: [0, 20] },
      { marker: 'miogenina', pct: [5, 25], note: 'nos elementos heterólogos rabdomioblásticos' },
      { marker: 'p53', pct: [10, 30], note: 'aberrante no crescimento sarcomatoso excessivo' },
      { marker: 'ciclinad1', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Pólipo endometrial: sem manguito hipercelular, sem atipia estromal, mitoses raras.',
      'Carcinossarcoma: componente epitelial é maligno.',
      'Sarcoma do estroma endometrial: sem componente epitelial organizado.',
      'Adenofibroma: estroma sem atipia nem mitoses (categoria hoje muito restrita).',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'mola-hidatiforme',
    name: 'Mola hidatiforme completa e parcial',
    aka: ['gestação molar', 'hydatidiform mole'],
    behavior: 'intermediario',
    sites: [
      { site: 'placenta', role: 'primario', freq: 3 },
      { site: 'utero', role: 'primario', freq: 3 },
    ],
    cells: ['trofoblastico', 'estreladas'],
    architecture: ['papilar', 'cistico'],
    features: ['hemorragia', 'mitoses-moderadas', 'corpos-apoptoticos'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Gestação anômala com vilosidades hidrópicas e hiperplasia trofoblástica: na completa, ausência total de feto, vilos com cisternas e hiperplasia circunferencial, e p57 perdido por não haver genoma materno; na parcial, dois populações de vilos, inclusões estromais e p57 retido.',
    criteria: [
      'Completa: vilos aumentados com cisterna central, hiperplasia trofoblástica circunferencial, estroma hipercelular com cariorrexe, ausência de tecido fetal.',
      'Parcial: duas populações de vilos (normais e hidrópicos), contornos recortados com inclusões pseudoinclusivas, hiperplasia focal, tecido fetal presente.',
      'p57 (KIP2) é o marcador que decide: perdido no citotrofoblasto viloso e no estroma da completa (genoma androgenético), retido na parcial e na não molar.',
      'Genotipagem por STR separa parcial (triploide diândrica) de aborto hidrópico e de mola completa.',
      'Seguimento com β-hCG seriada é obrigatório pelo risco de neoplasia trofoblástica gestacional.',
    ],
    markers: [
      { marker: 'p57', pct: [5, 15], note: 'o rótulo positivo é "retido": na mola completa está perdido, na parcial retido' },
      { marker: 'hcg', pct: [90, 100], note: 'sinciciotrofoblasto' },
      { marker: 'gata3', pct: [90, 100], note: 'trofoblasto' },
      { marker: 'p63', pct: [60, 90], note: 'citotrofoblasto e trofoblasto viloso' },
      { marker: 'hpl', pct: [40, 70], note: 'trofoblasto intermediário' },
      { marker: 'inibina', pct: [60, 90] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ki67', pct: [40, 80], note: 'alto no trofoblasto da completa' },
      { marker: 'ck7', pct: [85, 100], note: 'trofoblasto' },
      { marker: 'er', pct: 0, note: 'o negativo que separa das lesões endometriais' },
      { marker: 'pr', pct: 0 },
      { marker: 'p53', pct: [0, 10], note: 'selvagem' },
      { marker: 'pax8', pct: [0, 15] },
      { marker: 'p16', pct: [30, 70], note: 'positivo sem HPV; não interprete como colo' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Aborto hidrópico não molar: p57 retido, sem hiperplasia trofoblástica, vilos com contorno liso.',
      'Mola parcial: p57 retido, triploide, tecido fetal.',
      'Coriocarcinoma: sem vilosidades, bifásico, hemorrágico.',
      'Mola invasora: vilos molares dentro do miométrio.',
    ],
    pitfalls: ['p57 retido não exclui mola parcial nem molar precoce; a genotipagem é o padrão quando a decisão importa.'],
    molecular: 'Completa: androgenética diploide (46,XX na maioria). Parcial: triploide diândrica (69,XXY).',
    sources: [WHO, NUCCI],
  },
  {
    id: 'tumor-trofoblastico-sitio-placentario',
    name: 'Tumor trofoblástico do sítio placentário e epitelioide',
    aka: ['PSTT', 'ETT', 'placental site trophoblastic tumour', 'epithelioid trophoblastic tumour'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 1 },
      { site: 'colo', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
    ],
    cells: ['trofoblastico', 'epitelioide', 'pleomorfico'],
    architecture: ['infiltrativo', 'ninhos', 'nodular'],
    features: ['necrose', 'hialinizacao', 'mitoses-moderadas', 'hemorragia'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Tumores do trofoblasto intermediário, monofásicos: o do sítio placentário infiltra o miométrio dissecando as fibras musculares e substituindo a parede dos vasos, com hPL difuso; o epitelioide forma nódulos expansivos com necrose geográfica e material hialino, imita carcinoma escamoso e é p63 positivo.',
    criteria: [
      'Proliferação monofásica de trofoblasto intermediário, sem o padrão bifásico do coriocarcinoma.',
      'PSTT: infiltração dissecante entre fibras musculares, substituição fibrinoide da parede vascular, hPL difuso com hCG focal.',
      'ETT: nódulos expansivos com necrose geográfica e material hialino eosinofílico, p63 difuso, imitando carcinoma escamoso do colo.',
      'β-hCG sérica baixa ou moderadamente elevada, desproporcional ao volume tumoral (ao contrário do coriocarcinoma).',
      'Ki-67 elevado (acima de 10%) separa do nódulo de sítio placentário e do sítio placentário exagerado.',
    ],
    markers: [
      { marker: 'hpl', pct: [80, 95], note: 'difuso no PSTT; focal no ETT' },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'inibina', pct: [80, 95] },
      { marker: 'p63', pct: [80, 95], note: 'difuso no ETT; negativo no PSTT: é o que os separa' },
      { marker: 'hcg', pct: [20, 50], note: 'focal, em células sinciciais dispersas' },
      { marker: 'ema', pct: [50, 80] },
      { marker: 'p16', pct: [50, 80], note: 'positivo sem HPV: cuidado ao diferenciar do CEC do colo' },
      { marker: 'sall4', pct: [0, 10] },
      { marker: 'oct4', pct: [0, 5] },
      { marker: 'ki67', pct: [10, 50], note: 'acima de 10% separa das lesões trofoblásticas não neoplásicas' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Sítio placentário exagerado: Ki-67 abaixo de 1%, sem massa.',
      'Nódulo de sítio placentário: circunscrito, hialinizado, Ki-67 baixo, p63 positivo.',
      'Coriocarcinoma: bifásico, hCG difuso e sérico altíssimo.',
      'Carcinoma escamoso do colo: p16 em bloco com HPV, GATA3 e inibina negativos.',
      'Carcinoma epitelioide de músculo liso: desmina positiva.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'cec-colo',
    name: 'Carcinoma de células escamosas do colo uterino',
    aka: ['carcinoma escamoso cervical', 'cervical squamous cell carcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'colo', role: 'primario', freq: 3 },
      { site: 'vulva-vagina', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'bexiga', role: 'metastase', freq: 1 },
    ],
    cells: ['escamoso', 'basaloide', 'epitelioide'],
    architecture: ['ninhos', 'infiltrativo'],
    features: ['queratinizacao', 'desmoplasia', 'precursor', 'necrose', 'mitoses-altas', 'perineural'],
    ages: ['jovem', 'adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma escamoso associado a HPV de alto risco, com ninhos infiltrativos saindo de lesão intraepitelial de alto grau na zona de transformação; p16 em bloco é praticamente universal, e a profundidade e a extensão horizontal definem os subestádios do IA.',
    criteria: [
      'Invasão do estroma a partir de lesão intraepitelial escamosa de alto grau, com desmoplasia ou resposta inflamatória.',
      'Medida da profundidade de invasão e da extensão horizontal: define IA1, IA2 e IB.',
      'p16 em bloco confirma associação a HPV de alto risco.',
      'Invasão linfovascular deve ser relatada: pesa na conduta.',
      'Os raros HPV-independentes existem e têm pior prognóstico: p16 negativo com p53 aberrante.',
    ],
    markers: [
      { marker: 'p16', pct: [90, 100], note: 'em bloco; praticamente definidor no colo' },
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck7', pct: [30, 60] },
      { marker: 'p53', pct: [5, 20], note: 'selvagem; aberrante levanta HPV-independente' },
      { marker: 'er', pct: [0, 15] },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'pax8', pct: [10, 40] },
      { marker: 'gata3', pct: [10, 40], note: 'pode ser positivo; não use contra urotelial isoladamente' },
      { marker: 'ki67', pct: [60, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Lesão intraepitelial de alto grau com extensão glandular: sem invasão do estroma.',
      'Carcinoma escamoso do canal anal ou vaginal: mesma imuno; a topografia decide.',
      'Tumor trofoblástico epitelioide: GATA3, inibina e hPL positivos, p16 sem HPV.',
      'Metaplasia escamosa imatura e atrofia: p16 focal, Ki-67 baixo.',
      'Carcinoma neuroendócrino de pequenas células do colo: sinaptofisina e INSM1, também p16 em bloco.',
    ],
    molecular: 'HPV de alto risco (16 e 18 na maioria) com integração e expressão de E6/E7.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'adenocarcinoma-endocervical-hpv',
    name: 'Adenocarcinoma endocervical HPV-associado',
    aka: ['adenocarcinoma endocervical usual', 'HPV-associated endocervical adenocarcinoma', 'sistema de Silva'],
    behavior: 'maligno',
    sites: [
      { site: 'colo', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 2 },
      { site: 'ovario', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'cribriforme', 'papilar', 'infiltrativo'],
    features: ['mitoses-altas', 'corpos-apoptoticos', 'desmoplasia', 'precursor', 'mucina'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Adenocarcinoma de epitélio colunar pseudoestratificado em que as mitoses ficam na superfície apical e os corpos apoptóticos na base — o par que se enxerga em pequeno aumento e diz "HPV"; p16 em bloco com ER negativo, e o padrão de invasão de Silva define a necessidade de linfadenectomia.',
    criteria: [
      'Mitoses apicais e corpos apoptóticos basais no epitélio colunar: o achado de triagem.',
      'p16 em bloco com confirmação de HPV de alto risco quando necessário.',
      'Classificação do padrão de invasão pelo sistema de Silva (A, B, C), que estratifica o risco nodal.',
      'Adenocarcinoma in situ adjacente apoia primário endocervical.',
      'ER e PR negativos ou fracos, com vimentina negativa: separa do endometrioide do corpo.',
    ],
    markers: [
      { marker: 'p16', pct: [90, 100], note: 'em bloco; é o critério de entrada' },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'pax8', pct: [80, 95] },
      { marker: 'er', pct: [0, 20], note: 'o negativo que separa do endometrioide do corpo' },
      { marker: 'pr', pct: [0, 15] },
      { marker: 'vimentina', pct: [0, 20], note: 'negativa, ao contrário do endometrioide' },
      { marker: 'cea', pct: [60, 90], note: 'positivo, ao contrário do endocervical benigno' },
      { marker: 'p53', pct: [5, 25], note: 'selvagem na maioria' },
      { marker: 'cdx2', pct: [10, 40], note: 'pode ser positivo; não conclua colorretal' },
      { marker: 'ck20', pct: [0, 15] },
      { marker: 'satb2', pct: [0, 10] },
      { marker: 'muc6', pct: [0, 15], note: 'difusa favorece o tipo gástrico HPV-independente' },
      { marker: 'ki67', pct: [50, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma endometrioide do corpo: ER, PR e vimentina positivos, p16 focal.',
      'Adenocarcinoma gástrico-tipo: p16 negativo ou focal, citoplasma volumoso claro, pior prognóstico.',
      'Hiperplasia microglandular e reação de Arias-Stella: sem atipia, Ki-67 baixo.',
      'Metástase de adenocarcinoma colorretal: SATB2 e CK20, CK7 negativo.',
      'Endometriose cervical e endocervicose: sem atipia.',
    ],
    molecular: 'HPV de alto risco, com o genótipo 18 sobre-representado nos adenocarcinomas.',
    sources: [WHO, NUCCI, 'Roma et al., sistema de padrão de invasão de Silva, Am J Surg Pathol'],
  },
  {
    id: 'adenocarcinoma-gastrico-tipo-colo',
    name: 'Adenocarcinoma endocervical de tipo gástrico',
    aka: ['adenoma malignum', 'desvio mínimo', 'gastric-type endocervical adenocarcinoma'],
    behavior: 'maligno',
    sites: [
      { site: 'colo', role: 'primario', freq: 1 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
      { site: 'ovario', role: 'metastase', freq: 2 },
    ],
    cells: ['glandular', 'claras', 'anel-sinete'],
    architecture: ['glandulas', 'infiltrativo', 'cistico'],
    features: ['mucina', 'desmoplasia', 'mitoses-moderadas', 'perineural'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Adenocarcinoma cervical HPV-independente de células com citoplasma volumoso claro ou pálido e membranas nítidas, com atipia às vezes mínima (o antigo adenoma malignum), que infiltra profundamente com glândulas de aparência enganosamente benigna; pior prognóstico que o HPV-associado e associado à síndrome de Peutz-Jeghers.',
    criteria: [
      'Células colunares com citoplasma abundante claro ou eosinofílico pálido e limites celulares nítidos (fenótipo gástrico ou pilórico).',
      'p16 negativo ou apenas focal em mosaico, com HPV negativo.',
      'Infiltração profunda da parede cervical com glândulas irregulares e angulares, mesmo quando a atipia é mínima.',
      'MUC6 e HIK1083 positivos apoiam o fenótipo gástrico.',
      'Investigação de síndrome de Peutz-Jeghers (STK11) quando há lesão lobular glandular endocervical associada.',
    ],
    markers: [
      { marker: 'p16', pct: [10, 30], note: 'focal em mosaico; nunca em bloco' },
      { marker: 'muc6', pct: [70, 95], note: 'fenótipo gástrico' },
      { marker: 'muc5ac', pct: [70, 95] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'pax8', pct: [50, 80], note: 'menos que no HPV-associado' },
      { marker: 'er', pct: [0, 15] },
      { marker: 'pr', pct: [0, 10] },
      { marker: 'p53', pct: [40, 65], note: 'aberrante em boa parte, ao contrário do HPV-associado' },
      { marker: 'cea', pct: [70, 95] },
      { marker: 'cdx2', pct: [20, 50] },
      { marker: 'ck20', pct: [10, 40] },
      { marker: 'smad4', pct: [10, 30], note: 'o positivo é a perda' },
      { marker: 'hnf1b', pct: [40, 80], note: 'pode confundir com carcinoma de células claras' },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma endocervical HPV-associado: p16 em bloco, mitoses apicais.',
      'Hiperplasia lobular glandular endocervical: lobular, sem invasão profunda nem desmoplasia.',
      'Metástase de adenocarcinoma pancreatobiliar ou gástrico: mesmo perfil; a clínica decide.',
      'Carcinoma de células claras: HNF1β e napsina, padrão tubulocístico com tachinha.',
      'Adenocarcinoma mesonéfrico: GATA3 e TTF-1 positivos, túbulos com material eosinofílico.',
    ],
    pitfalls: ['A atipia pode ser tão discreta que a biópsia superficial passa por benigna; a profundidade da invasão é o sinal.'],
    molecular: 'HPV-independente; TP53, STK11 (Peutz-Jeghers), CDKN2A, ERBB2 amplificado em parte.',
    sources: [WHO, NUCCI, 'Kojima et al., Am J Surg Pathol (2007), adenocarcinoma cervical de tipo gástrico'],
  },
  {
    id: 'sil-colo',
    name: 'Lesão intraepitelial escamosa do colo uterino (LSIL e HSIL)',
    aka: ['NIC 1', 'NIC 2', 'NIC 3', 'displasia cervical', 'LSIL', 'HSIL', 'sistema LAST'],
    behavior: 'intermediario',
    sites: [
      { site: 'colo', role: 'primario', freq: 3 },
      { site: 'vulva-vagina', role: 'primario', freq: 2 },
      { site: 'anus', role: 'primario', freq: 2 },
    ],
    cells: ['escamoso', 'basaloide'],
    features: ['precursor', 'mitoses-moderadas', 'mitoses-altas'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'A lesão precursora do carcinoma escamoso do colo, dividida em dois graus pelo sistema LAST: a de baixo grau é efeito citopático viral produtivo, com coilocitose e maturação preservada; a de alto grau tem atipia que alcança o terço médio e superior, com mitoses em camadas altas. É a pergunta mais frequente da patologia ginecológica, e o p16 é o que resolve o caso limítrofe.',
    criteria: [
      'Baixo grau (NIC 1): coilócitos com halo perinuclear e núcleo atípico, maturação preservada, atipia restrita ao terço inferior.',
      'Alto grau (NIC 2 e 3): perda de maturação com atipia no terço médio e superior, mitoses acima da camada basal, relação núcleo-citoplasma alta.',
      'p16 em bloco (forte, contínuo, nuclear e citoplasmático, do terço basal para cima) sustenta o alto grau; focal ou em mosaico é compatível com baixo grau.',
      'O p16 só deve ser usado em quatro situações definidas pelo LAST, entre elas a morfologia limítrofe de NIC 2 e a dúvida com metaplasia imatura ou atrofia.',
      'Ki-67 em terço médio e superior acompanha o p16 em bloco; sozinho não define.',
    ],
    markers: [
      { marker: 'p16', pct: [80, 95], note: 'em bloco na de alto grau; na de baixo grau é focal ou negativo em cerca de dois terços' },
      { marker: 'ki67', pct: [70, 95], note: 'em terço médio e superior na de alto grau' },
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'p53', pct: [0, 10], note: 'selvagem; aberrante levanta a via HPV-independente, sobretudo na vulva' },
      { marker: 'ck7', pct: [20, 50], note: 'positiva na lesão da zona de transformação, o que se associa a persistência' },
      { marker: 'er', pct: [0, 15] },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metaplasia escamosa imatura: p16 focal, Ki-67 baixo, sem atipia real.',
      'Atrofia pós-menopausa: espessura reduzida, núcleos uniformes, p16 negativo.',
      'Alteração reparativa e cervicite: nucléolo proeminente com inflamação, maturação preservada.',
      'Carcinoma escamoso invasor: ninhos além da membrana basal com desmoplasia.',
      'Neoplasia intraepitelial vulvar diferenciada: p16 negativo com p53 aberrante, sobre líquen escleroso.',
    ],
    pitfalls: ['p16 em bloco não diz que a lesão é invasora nem substitui a procura de invasão; e p16 negativo numa lesão de alto grau morfológica deve fazer pensar na via HPV-independente.'],
    molecular: 'HPV de alto risco: infecção produtiva no baixo grau, transformante com integração no alto grau.',
    sources: [WHO, NUCCI, 'Darragh et al., projeto LAST: terminologia de dois graus para lesões escamosas associadas a HPV, Arch Pathol Lab Med (2012)'],
  },
  {
    id: 'ais-endocervical',
    name: 'Adenocarcinoma in situ endocervical',
    aka: ['AIS endocervical', 'adenocarcinoma in situ do colo', 'neoplasia glandular intraepitelial cervical'],
    behavior: 'intermediario',
    sites: [{ site: 'colo', role: 'primario', freq: 3 }],
    cells: ['glandular', 'epitelioide'],
    architecture: ['glandulas', 'cribriforme', 'papilar'],
    features: ['precursor', 'mitoses-altas', 'corpos-apoptoticos', 'mucina'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Epitélio glandular endocervical substituído por células colunares pseudoestratificadas, hipercromáticas e com mucina reduzida, mantendo o contorno das glândulas normais; as mitoses ficam na superfície apical e os corpos apoptóticos na base, o par que se enxerga em pequeno aumento e denuncia HPV.',
    criteria: [
      'Substituição do epitélio glandular normal mantendo a arquitetura e a distribuição das glândulas endocervicais.',
      'Mitoses apicais e corpos apoptóticos basais: o achado de triagem em pequeno aumento.',
      'Pseudoestratificação nuclear com hipercromasia e depleção de mucina.',
      'Ausência de invasão estromal: nem desmoplasia, nem glândulas fora do campo das criptas normais, nem crescimento confluente.',
      'p16 em bloco confirma a via HPV-associada; o estado da margem do cone é a informação que governa a conduta.',
    ],
    markers: [
      { marker: 'p16', pct: [90, 100], note: 'em bloco; é o critério de apoio principal' },
      { marker: 'ki67', pct: [60, 90], note: 'alto e difuso, contra o baixo da metaplasia tubária' },
      { marker: 'ck7', pct: [95, 100] },
      { marker: 'cea', pct: [50, 80], note: 'positivo, ao contrário do epitélio endocervical normal' },
      { marker: 'pax8', pct: [80, 95] },
      { marker: 'er', pct: [0, 20], note: 'o negativo que ajuda contra origem endometrial' },
      { marker: 'pr', pct: [0, 15] },
      { marker: 'vimentina', pct: [0, 15] },
      { marker: 'p53', pct: [0, 15], note: 'selvagem; aberrante levanta a via gástrica HPV-independente' },
      { marker: 'cdx2', pct: [10, 40] },
      { marker: 'p63', pct: [0, 10], note: 'ausência de camada basal, ao contrário da metaplasia escamosa' },
      { marker: 'bcl2', pct: [10, 40] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metaplasia tubária e tuboendometrioide: cílios presentes, p16 focal, Ki-67 baixo.',
      'Endometriose e endocervicose cervicais: estroma endometrial CD10 positivo, sem atipia.',
      'Hiperplasia microglandular: arquitetura em favo com neutrófilos, em uso de progestágeno.',
      'Reação de Arias-Stella: citoplasma vacuolado com núcleo hipercromático, na gestação.',
      'Adenocarcinoma invasor: desmoplasia, glândulas confluentes ou além do campo das criptas normais.',
      'Adenocarcinoma de tipo gástrico in situ: p16 negativo, citoplasma volumoso claro.',
    ],
    molecular: 'HPV de alto risco, com genótipo 18 sobre-representado nas lesões glandulares.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'nodulo-estromal-endometrial',
    name: 'Nódulo estromal endometrial',
    aka: ['endometrial stromal nodule', 'nódulo estromal'],
    behavior: 'benigno',
    sites: [{ site: 'utero', role: 'primario', freq: 2 }],
    cells: ['fusocelular', 'pequenas-redondas', 'estreladas'],
    architecture: ['nodular', 'lencois'],
    features: ['vasos-espessos', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto'],
    sex: 'f',
    summary: 'Nódulo único e bem delimitado de células idênticas ao estroma endometrial proliferativo, com as mesmas arteríolas espiraladas do sarcoma de baixo grau — e a única diferença entre os dois é a margem: aqui ela é expansiva, com no máximo três projeções de até 3 mm, e não há invasão vascular.',
    criteria: [
      'Margem expansiva e circunscrita, avaliada em toda a interface com o miométrio.',
      'No máximo três protrusões irregulares, nenhuma com mais de 3 mm: acima disso, o diagnóstico é sarcoma do estroma de baixo grau.',
      'Ausência absoluta de invasão linfovascular.',
      'Células uniformes com arteríolas espiraladas regularmente distribuídas, como no estroma proliferativo.',
      'A avaliação exige a peça inteira: o diagnóstico não pode ser feito em curetagem nem em biópsia por agulha.',
    ],
    markers: [
      { marker: 'cd10', pct: [85, 100] },
      { marker: 'er', pct: [80, 95] },
      { marker: 'pr', pct: [85, 100] },
      { marker: 'wt1', pct: [50, 80] },
      { marker: 'caldesmon', pct: [0, 20], note: 'o negativo que separa de músculo liso' },
      { marker: 'desmina', pct: [10, 30], note: 'focal, em áreas de diferenciação muscular' },
      { marker: 'sma', pct: [20, 50] },
      { marker: 'ciclinad1', pct: [0, 20], note: 'o negativo que afasta o sarcoma do estroma de alto grau YWHAE' },
      { marker: 'bcor', pct: [0, 10] },
      { marker: 'betacatenina', pct: [30, 60], pattern: 'N' },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'ae1ae3', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Sarcoma do estroma endometrial de baixo grau: permeação em língua e invasão vascular; imuno idêntica.',
      'Leiomioma celular: desmina e h-caldesmon difusos, vasos de parede espessa em fenda.',
      'Tumor uterino tipo cordão sexual: inibina, calretinina e queratina positivas.',
      'Adenomiose com estroma predominante: glândulas endometriais dentro.',
      'Tumor de músculo liso com mudança mixoide: h-caldesmon positivo.',
    ],
    pitfalls: ['A imuno não separa nódulo estromal de sarcoma de baixo grau: os dois são CD10, ER e PR positivos. Só a margem decide, e só na peça.'],
    molecular: 'Fusões JAZF1::SUZ12, as mesmas do sarcoma do estroma de baixo grau.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'polipo-endometrial',
    name: 'Pólipo endometrial e hiperplasia sem atipia',
    aka: ['pólipo endometrial', 'hiperplasia endometrial simples e complexa sem atipia'],
    behavior: 'benigno',
    sites: [{ site: 'utero', role: 'primario', freq: 3 }],
    cells: ['glandular', 'epitelioide', 'fusocelular'],
    architecture: ['glandulas', 'cistico'],
    features: ['vasos-espessos', 'mitoses-raras', 'hialinizacao'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'As duas lesões que dominam a curetagem por sangramento anormal: o pólipo tem estroma fibroso denso, vasos de parede espessa e glândulas irregulares muitas vezes dilatadas, com epitélio de superfície em três lados; a hiperplasia sem atipia tem glândulas apinhadas com contorno irregular, mas citologia igual à do endométrio proliferativo.',
    criteria: [
      'Pólipo: estroma fibroso ou fibromuscular denso, vasos de parede espessa de calibre grande e glândulas desalinhadas em relação à superfície.',
      'Hiperplasia sem atipia: relação glândula-estroma aumentada em campo amplo, mas com citologia idêntica à das glândulas de fundo.',
      'A ausência de alteração citológica é o que a separa da hiperplasia atípica: PAX2 e PTEN retidos ajudam quando a morfologia é limítrofe.',
      'Hiperplasia sem atipia responde a progestágeno e tem risco baixo de progressão; a atípica é lesão neoplásica.',
      'Metaplasias (ciliada, eosinofílica, mucinosa, papilar) são frequentes nos dois e não devem ser lidas como atipia.',
    ],
    markers: [
      { marker: 'pax2', pct: [0, 20], note: 'retido; o positivo aqui seria a perda, que marca a hiperplasia atípica' },
      { marker: 'pten', pct: [5, 20], note: 'o positivo é a perda; glândulas PTEN-nulas existem no endométrio normal e sozinhas não fazem diagnóstico' },
      { marker: 'er', pct: [90, 100] },
      { marker: 'pr', pct: [90, 100] },
      { marker: 'pax8', pct: [90, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'vimentina', pct: [80, 95] },
      { marker: 'cd10', pct: [80, 95], note: 'estroma endometrial; útil para reconhecer o estroma do pólipo' },
      { marker: 'p53', pct: [0, 5], note: 'selvagem' },
      { marker: 'p16', pct: [0, 15] },
      { marker: 'betacatenina', pct: [0, 15], pattern: 'N' },
      { marker: 'mlh1', pct: [0, 5], note: 'retido' },
      { marker: 'ki67', pct: [5, 20] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Hiperplasia atípica (EIN): alteração citológica em relação ao fundo, com perda de PAX2 ou PTEN em clone contíguo.',
      'Adenocarcinoma endometrioide grau 1: confluência glandular, cribras ou desmoplasia.',
      'Endométrio secretor e alterações por progestágeno: vacúolos, estroma decidualizado.',
      'Adenossarcoma: manguito estromal hipercelular periglandular com mitoses.',
      'Endométrio disfuncional com colapso estromal: aglomerados que imitam apinhamento.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'carcinoma-neuroendocrino-colo',
    name: 'Carcinoma neuroendócrino do colo uterino',
    aka: ['carcinoma de pequenas células do colo', 'carcinoma neuroendócrino de grandes células cervical'],
    behavior: 'maligno',
    sites: [
      { site: 'colo', role: 'primario', freq: 2 },
      { site: 'linfonodo', role: 'metastase', freq: 3 },
      { site: 'figado', role: 'metastase', freq: 2 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'encefalo', role: 'metastase', freq: 1 },
    ],
    cells: ['pequenas-redondas', 'neuroendocrino', 'pleomorfico'],
    architecture: ['lencois', 'ninhos', 'trabecular'],
    features: ['necrose', 'mitoses-altas', 'corpos-apoptoticos', 'precursor'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Carcinoma neuroendócrino de alto grau do colo, quase sempre HPV-associado (genótipo 18 sobre-representado), com conduta e prognóstico completamente distintos do escamoso: dissemina cedo, é tratado com quimioterapia de pequenas células e não com cirurgia radical, e qualquer proporção do componente já classifica o tumor.',
    criteria: [
      'Morfologia de pequenas células (moldagem, cromatina hipercromática, esmagamento) ou de grandes células neuroendócrinas (nucléolo, palissada periférica, necrose).',
      'Marcador neuroendócrino positivo: INSM1, sinaptofisina ou cromogranina — o INSM1 é o mais sensível.',
      'Qualquer proporção do componente neuroendócrino define o tumor e a conduta, mesmo com carcinoma escamoso ou adenocarcinoma associado.',
      'p16 em bloco com HPV de alto risco na maioria, o que não muda o prognóstico ruim.',
      'TTF-1 pode ser positivo sem indicar pulmão, e é armadilha frequente numa metástase.',
    ],
    markers: [
      { marker: 'insm1', pct: [85, 100] },
      { marker: 'sinaptofisina', pct: [75, 95] },
      { marker: 'cromogranina', pct: [40, 75], note: 'mais fraca e focal que a sinaptofisina' },
      { marker: 'cd56', pct: [80, 95] },
      { marker: 'p16', pct: [85, 100], note: 'em bloco; HPV 18 sobre-representado' },
      { marker: 'ae1ae3', pct: [80, 95], pattern: 'dot' },
      { marker: 'ttf1', pct: [30, 60], note: 'positivo sem indicar pulmão: erro clássico numa metástase' },
      { marker: 'p40', pct: [0, 15], note: 'o negativo que separa do escamoso basaloide' },
      { marker: 'rb1', pct: [60, 90], note: 'o positivo é a perda' },
      { marker: 'p53', pct: [30, 60] },
      { marker: 'er', pct: [0, 15] },
      { marker: 'pax8', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
      { marker: 'ki67', pct: [80, 100] },
    ],
    mimics: [
      'Carcinoma escamoso basaloide: p40 difuso, sem marcador neuroendócrino.',
      'Lesão intraepitelial de alto grau com extensão glandular: sem invasão nem diferenciação neuroendócrina.',
      'Linfoma: CD45 positivo.',
      'Metástase de carcinoma de pequenas células pulmonar: p16 sem HPV, história.',
      'Adenocarcinoma endocervical pouco diferenciado: sem marcador neuroendócrino difuso.',
    ],
    molecular: 'HPV de alto risco (18 e 16); perda de RB1 e TP53 na progressão.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'adenocarcinoma-mesonefrico',
    name: 'Adenocarcinoma mesonéfrico e mesonéfrico-símile',
    aka: ['mesonephric adenocarcinoma', 'mesonephric-like adenocarcinoma', 'adenocarcinoma de ducto de Gartner'],
    behavior: 'maligno',
    sites: [
      { site: 'colo', role: 'primario', freq: 1 },
      { site: 'utero', role: 'primario', freq: 1 },
      { site: 'ovario', role: 'primario', freq: 1 },
    ],
    cells: ['glandular', 'epitelioide', 'fusocelular'],
    architecture: ['glandulas', 'papilar', 'trabecular', 'cistico'],
    features: ['hialinizacao', 'mitoses-moderadas', 'coloide'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Adenocarcinoma de linhagem wolffiana, com túbulos pequenos cheios de material eosinofílico denso que imita coloide, misturados a padrões ductal, papilar, retiforme e fusocelular na mesma lesão; o perfil GATA3 e TTF-1 positivos com ER negativo é contraintuitivo num tumor ginecológico e é a razão do verbete.',
    criteria: [
      'Múltiplos padrões arquiteturais no mesmo tumor, com túbulos pequenos contendo secreção eosinofílica densa.',
      'Perfil imuno: GATA3 e CD10 (luminal) positivos com ER e PR negativos, e TTF-1 positivo em parte.',
      'Mesonéfrico verdadeiro: no colo, com hiperplasia de remanescentes mesonéfricos adjacente.',
      'Mesonéfrico-símile: no endométrio ou no ovário, sem remanescentes, provavelmente de origem mülleriana com diferenciação wolffiana.',
      'Mutação de KRAS quase constante, com ausência de alterações de PTEN e de instabilidade de microssatélites.',
    ],
    markers: [
      { marker: 'gata3', pct: [70, 95], note: 'positivo num adenocarcinoma ginecológico: é o achado que denuncia' },
      { marker: 'cd10', pct: [70, 95], pattern: 'M', note: 'padrão luminal' },
      { marker: 'ttf1', pct: [40, 75], note: 'positivo sem indicar pulmão nem tireoide; costuma ser recíproco ao GATA3' },
      { marker: 'er', pct: [0, 15], note: 'o negativo que o separa do endometrioide' },
      { marker: 'pr', pct: [0, 15] },
      { marker: 'pax8', pct: [80, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'calretinina', pct: [20, 60] },
      { marker: 'p16', pct: [10, 40], note: 'focal, não em bloco: o negativo afasta o HPV-associado' },
      { marker: 'p53', pct: [10, 40] },
      { marker: 'napsina', pct: [0, 20], note: 'o negativo que ajuda contra células claras' },
      { marker: 'hnf1b', pct: [20, 60] },
      { marker: 'wt1', pct: [0, 20] },
      { marker: 'ki67', pct: [20, 60] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinoma endometrioide: ER e PR positivos, vimentina positiva.',
      'Carcinoma de células claras: napsina e HNF1β fortes, tachinha.',
      'Adenocarcinoma endocervical HPV-associado: p16 em bloco.',
      'Hiperplasia de remanescentes mesonéfricos: lobular, sem atipia nem invasão.',
      'Tumor wolffiano do ligamento largo (FATWO): EMA negativo, no anexo.',
    ],
    molecular: 'KRAS em quase todos; também PIK3CA e ARID1A; sem PTEN nem MSI.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'carcinoma-mucinoso-endometrio',
    name: 'Carcinoma mucinoso do endométrio',
    aka: ['adenocarcinoma mucinoso endometrial', 'carcinoma endometrial de tipo mucinoso'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 1 },
      { site: 'linfonodo', role: 'metastase', freq: 1 },
    ],
    cells: ['glandular', 'anel-sinete', 'epitelioide'],
    architecture: ['glandulas', 'papilar', 'cribriforme'],
    features: ['mucina', 'mitoses-moderadas', 'precursor'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Carcinoma endometrial em que mais da metade das células tem mucina intracitoplasmática abundante; quase sempre de baixo grau e bom prognóstico, seu problema é o diferencial com o adenocarcinoma endocervical, porque a distinção muda o estadiamento — e o par ER com vimentina contra p16 em bloco é o que resolve.',
    criteria: [
      'Mais de 50% das células com mucina intracitoplasmática, confirmada por PAS-diastase ou mucicarmim.',
      'Arquitetura glandular, cribriforme ou vilo-glandular, quase sempre de baixo grau.',
      'ER, PR e vimentina positivos com p16 focal: o perfil endometrial.',
      'Exclusão obrigatória de adenocarcinoma endocervical, que é p16 em bloco com ER negativo.',
      'A variante microglandular-símile imita a hiperplasia microglandular do colo em curetagem.',
    ],
    markers: [
      { marker: 'er', pct: [70, 95] },
      { marker: 'pr', pct: [60, 90] },
      { marker: 'vimentina', pct: [60, 90], note: 'positiva, ao contrário do endocervical' },
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'p16', pct: [10, 30], note: 'focal; em bloco indica origem endocervical' },
      { marker: 'muc5ac', pct: [60, 90] },
      { marker: 'cea', pct: [10, 40], note: 'difuso favorece endocervical' },
      { marker: 'cdx2', pct: [10, 40] },
      { marker: 'ck20', pct: [0, 20] },
      { marker: 'satb2', pct: [0, 10], note: 'o negativo que afasta colorretal' },
      { marker: 'p53', pct: [5, 25], note: 'selvagem na maioria' },
      { marker: 'mlh1', pct: [10, 30], note: 'o positivo é a perda; rastreio de Lynch como nos demais endometriais' },
      { marker: 'ki67', pct: [15, 50] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Adenocarcinoma endocervical HPV-associado: p16 em bloco, ER e vimentina negativos.',
      'Metaplasia mucinosa e lesões mucinosas atípicas do endométrio: sem invasão nem complexidade.',
      'Hiperplasia microglandular do colo: em uso de progestágeno, sem atipia.',
      'Adenocarcinoma colorretal invadindo: CDX2 e SATB2, CK7 negativo.',
      'Carcinoma endometrioide com diferenciação mucinosa focal: menos de 50% de mucina.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'vin',
    name: 'Neoplasia intraepitelial vulvar (VIN)',
    aka: ['VIN', 'HSIL vulvar', 'VIN diferenciada', 'dVIN', 'doença de Bowen vulvar'],
    behavior: 'intermediario',
    sites: [{ site: 'vulva-vagina', role: 'primario', freq: 3 }],
    cells: ['escamoso', 'basaloide'],
    architecture: ['infiltrativo'],
    features: ['precursor', 'queratinizacao', 'mitoses-moderadas'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Duas doenças com o mesmo nome e vias opostas. A HSIL vulvar é HPV-associada, de mulher mais jovem, basaloide ou condilomatosa, com p16 em bloco. A VIN diferenciada é HPV-independente, sobre líquen escleroso em mulher idosa, com atipia restrita à camada basal e p53 aberrante — e é ela que progride rápido para carcinoma.',
    criteria: [
      'HSIL vulvar (HPV-associada): atipia de espessura total ou dos dois terços inferiores, com mitoses altas e p16 em bloco.',
      'VIN diferenciada: atipia basal e parabasal apenas, com maturação superficial preservada, queratinócitos eosinofílicos alargados e pontes intercelulares proeminentes.',
      'p53 aberrante (difuso basal, nulo ou citoplasmático) na VIN diferenciada, com p16 negativo.',
      'Líquen escleroso ou hiperplasia de células escamosas adjacente apoia a VIN diferenciada.',
      'A VIN diferenciada é sutil, muitas vezes subdiagnosticada como dermatose, e tem risco de progressão bem maior que a HSIL.',
    ],
    markers: [
      { marker: 'p16', pct: [40, 70], note: 'em bloco na HPV-associada; negativo na diferenciada' },
      { marker: 'p53', pct: [30, 60], note: 'aberrante na diferenciada; selvagem na HPV-associada — os dois são recíprocos' },
      { marker: 'ki67', pct: [60, 90], note: 'em terço médio e superior na HPV-associada; basal e parabasal na diferenciada' },
      { marker: 'p40', pct: [95, 100] },
      { marker: 'p63', pct: [95, 100] },
      { marker: 'ck56', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'ck903', pct: [85, 100] },
      { marker: 'ck7', pct: [10, 40], note: 'positiva na doença de Paget, que é o diferencial intraepitelial' },
      { marker: 'gata3', pct: [20, 50] },
      { marker: 'sox10', pct: [0, 5], note: 'o negativo que separa de melanoma in situ' },
      { marker: 'cea', pct: [0, 15], note: 'positivo na doença de Paget' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Líquen escleroso e líquen simples crônico: sem atipia basal, p53 selvagem.',
      'Doença de Paget extramamária: células grandes pálidas CK7 e CEA positivas, p40 negativo.',
      'Melanoma in situ: SOX10 e Melan-A positivos.',
      'Candidíase e dermatite com atipia reativa: maturação preservada, sem clone.',
      'Carcinoma escamoso invasor: ninhos abaixo da membrana basal.',
    ],
    molecular: 'HPV de alto risco na HSIL; TP53 na VIN diferenciada, sobre líquen escleroso.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'utrosct',
    name: 'Tumor uterino de tipo cordão sexual (UTROSCT)',
    aka: ['UTROSCT', 'uterine tumour resembling ovarian sex cord tumour'],
    behavior: 'intermediario',
    sites: [{ site: 'utero', role: 'primario', freq: 1 }],
    cells: ['epitelioide', 'fusocelular'],
    architecture: ['trabecular', 'glandulas', 'rosetas', 'ninhos'],
    features: ['hialinizacao', 'mitoses-raras', 'vacuolos-lipidicos'],
    ages: ['adulto', 'idoso'],
    sex: 'f',
    summary: 'Nódulo uterino que reproduz tumor de cordão sexual do ovário — cordões, trabéculas, túbulos e ninhos retiformes —, com coexpressão desconcertante de queratina, inibina, calretinina e CD10 na mesma célula. Comportamento em geral indolente, com recidivas e metástases tardias numa minoria.',
    criteria: [
      'Padrões de cordão sexual (trabecular, tubular, retiforme, glomeruloide) sem componente de estroma endometrial reconhecível.',
      'Coexpressão de pelo menos dois marcadores de cordão sexual (inibina, calretinina, FOXL2, SF-1, CD56) com queratina.',
      'Ausência do padrão permeativo em língua do sarcoma do estroma endometrial.',
      'Fusões de NCOA1/2/3 com ESR1 ou GREB1 na maioria; as com GREB1 são mais agressivas.',
      'Comportamento incerto: relate como potencial maligno indeterminado e indique seguimento.',
    ],
    markers: [
      { marker: 'inibina', pct: [50, 85] },
      { marker: 'calretinina', pct: [60, 90] },
      { marker: 'foxl2', pct: [50, 85] },
      { marker: 'sf1', pct: [50, 85] },
      { marker: 'cd56', pct: [70, 95] },
      { marker: 'ae1ae3', pct: [70, 95], note: 'a coexpressão com inibina e calretinina é o achado que define' },
      { marker: 'cam52', pct: [60, 90] },
      { marker: 'cd10', pct: [50, 85] },
      { marker: 'er', pct: [60, 90] },
      { marker: 'pr', pct: [70, 95] },
      { marker: 'desmina', pct: [30, 70] },
      { marker: 'caldesmon', pct: [10, 40] },
      { marker: 'wt1', pct: [50, 85] },
      { marker: 'ki67', pct: [1, 15] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Sarcoma do estroma endometrial com diferenciação de cordão sexual: permeação em língua, fusão JAZF1.',
      'Carcinoma endometrioide com padrão sertoliforme: EMA positivo, inibina negativa.',
      'Tumor de músculo liso epitelioide: desmina e h-caldesmon difusos.',
      'Nódulo estromal endometrial: CD10 difuso sem marcadores de cordão sexual.',
      'Metástase de tumor de cordão sexual ovariano: história e massa anexial.',
    ],
    molecular: 'Fusões ESR1::NCOA2/3 e GREB1::NCOA1/2, estas últimas de comportamento pior.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'sarcoma-uterino-indiferenciado',
    name: 'Sarcoma uterino indiferenciado',
    aka: ['undifferentiated uterine sarcoma', 'sarcoma endometrial indiferenciado'],
    behavior: 'maligno',
    sites: [
      { site: 'utero', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 2 },
    ],
    cells: ['pleomorfico', 'fusocelular', 'pequenas-redondas'],
    architecture: ['lencois', 'infiltrativo'],
    features: ['necrose', 'mitoses-altas', 'hemorragia'],
    ages: ['idoso'],
    sex: 'f',
    summary: 'Sarcoma de alto grau do útero sem qualquer linhagem demonstrável: não é músculo liso, não é estroma endometrial, não tem fusão conhecida e não tem componente epitelial. É diagnóstico de exclusão, feito depois de afastar carcinossarcoma, leiomiossarcoma e o sarcoma do estroma de alto grau, e o prognóstico é sombrio.',
    criteria: [
      'Proliferação de alto grau com pleomorfismo acentuado, necrose e índice mitótico elevado.',
      'Ausência de diferenciação demonstrável: queratina e PAX8 negativos, desmina e h-caldesmon negativos, CD10 fraco ou ausente.',
      'Ciclina D1 e BCOR negativos ou não difusos, o que afasta o sarcoma do estroma de alto grau.',
      'Amostragem generosa para excluir componente carcinomatoso, que definiria carcinossarcoma.',
      'Diagnóstico de exclusão: sempre relate quais entidades foram afastadas e como.',
    ],
    markers: [
      { marker: 'cd10', pct: [20, 50], note: 'fraco e focal quando presente' },
      { marker: 'ae1ae3', pct: [0, 20], note: 'o negativo que exclui carcinossarcoma' },
      { marker: 'pax8', pct: [0, 15] },
      { marker: 'desmina', pct: [0, 20], note: 'o negativo que exclui leiomiossarcoma' },
      { marker: 'caldesmon', pct: [0, 15] },
      { marker: 'ciclinad1', pct: [10, 40], note: 'difusa e forte indicaria sarcoma do estroma de alto grau YWHAE' },
      { marker: 'bcor', pct: [0, 25] },
      { marker: 'er', pct: [0, 25] },
      { marker: 'pr', pct: [0, 25] },
      { marker: 'p53', pct: [40, 80] },
      { marker: 'miogenina', pct: [0, 10], note: 'o negativo que exclui rabdomiossarcoma' },
      { marker: 'sox10', pct: [0, 5] },
      { marker: 'ini1', pct: [0, 15], note: 'retido; a perda indicaria tumor rabdoide' },
      { marker: 'ki67', pct: [50, 95] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Carcinossarcoma: componente carcinomatoso presente, PAX8 e queratina positivos.',
      'Leiomiossarcoma: desmina e h-caldesmon difusos.',
      'Sarcoma do estroma de alto grau: ciclina D1 ou BCOR difusos, com fusão.',
      'Rabdomiossarcoma uterino: miogenina e MyoD1.',
      'Carcinoma indiferenciado do endométrio: queratina focal com perda de SMARCA4 ou SMARCB1.',
    ],
    sources: [WHO, NUCCI],
  },
  {
    id: 'leiomiomatose-intravenosa',
    name: 'Leiomiomatose intravenosa e leiomioma metastatizante benigno',
    aka: ['leiomiomatose intravenosa', 'benign metastasizing leiomyoma', 'leiomiomatose peritoneal disseminada'],
    behavior: 'intermediario',
    sites: [
      { site: 'utero', role: 'primario', freq: 1 },
      { site: 'pulmao', role: 'metastase', freq: 2 },
      { site: 'peritoneo', role: 'metastase', freq: 1 },
      { site: 'coracao', role: 'metastase', freq: 1 },
    ],
    cells: ['fusocelular', 'mioide'],
    architecture: ['fasciculos', 'nodular'],
    features: ['hialinizacao', 'mitoses-raras', 'vasos-espessos'],
    ages: ['adulto'],
    sex: 'f',
    summary: 'Tumores de músculo liso com histologia inteiramente benigna e comportamento que assusta: a leiomiomatose intravenosa cresce dentro das veias uterinas e pode alcançar a veia cava e o átrio direito; o leiomioma metastatizante benigno aparece como nódulos pulmonares múltiplos anos após uma miomectomia.',
    criteria: [
      'Histologia de leiomioma benigno: sem atipia, sem necrose de coagulação tumoral e com mitoses raras.',
      'Leiomiomatose intravenosa: cordões tumorais dentro de espaços vasculares revestidos por endotélio, demonstrável com CD31 ou ERG.',
      'Leiomioma metastatizante: nódulos pulmonares múltiplos, ER e PR positivos, com história de leiomioma uterino.',
      'Exclusão de leiomiossarcoma de baixo grau com invasão vascular: exige amostragem generosa do tumor uterino.',
      'Comportamento benigno mas com morbidade real: a extensão cardíaca exige cirurgia de grande porte.',
    ],
    markers: [
      { marker: 'desmina', pct: [90, 100] },
      { marker: 'caldesmon', pct: [85, 100] },
      { marker: 'sma', pct: [90, 100] },
      { marker: 'er', pct: [80, 95], note: 'positivo também nos nódulos pulmonares: é o que prova a origem uterina' },
      { marker: 'pr', pct: [85, 100] },
      { marker: 'cd31', pct: [0, 5], note: 'usada para provar que o cordão está dentro de um vaso revestido' },
      { marker: 'erg', pct: [0, 5], note: 'idem' },
      { marker: 'p16', pct: [0, 20], note: 'difuso favorece leiomiossarcoma' },
      { marker: 'p53', pct: [0, 10], note: 'selvagem' },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'hmb45', pct: [0, 5], note: 'o negativo que exclui linfangioleiomiomatose, que também dá nódulos pulmonares' },
      { marker: 'ttf1', pct: 0, note: 'o negativo que afasta origem pulmonar primária' },
      { marker: 'ki67', pct: [1, 5] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Leiomiossarcoma com invasão vascular: atipia, necrose tumoral, p16 e p53 alterados.',
      'Linfangioleiomiomatose: HMB-45 e Melan-A positivos, cistos pulmonares, esclerose tuberosa.',
      'Leiomioma com extensão para o miométrio em fenda: sem revestimento endotelial ao redor.',
      'Hamartoma pulmonar e outros nódulos: ER e PR negativos.',
      'Leiomiomatose peritoneal disseminada: nódulos peritoneais múltiplos, em gestante ou usuária de anticoncepcional.',
    ],
    molecular: 'Alterações de HMGA2 e deleções cromossômicas; as metastatizantes são clonalmente relacionadas ao leiomioma uterino.',
    sources: [WHO, NUCCI, STANFORD],
  },
  {
    id: 'rabdomiossarcoma-colo',
    name: 'Rabdomiossarcoma embrionário botrioide do colo e da vagina',
    aka: ['sarcoma botrioide', 'botryoid rhabdomyosarcoma', 'rabdomiossarcoma cervical DICER1'],
    behavior: 'maligno',
    sites: [
      { site: 'colo', role: 'primario', freq: 1 },
      { site: 'vulva-vagina', role: 'primario', freq: 1 },
      { site: 'utero', role: 'primario', freq: 1 },
    ],
    cells: ['pequenas-redondas', 'fusocelular', 'estreladas'],
    architecture: ['nodular', 'infiltrativo'],
    features: ['estroma-mixoide', 'estriacoes', 'condroide', 'mitoses-altas'],
    ages: ['crianca', 'jovem'],
    sex: 'f',
    summary: 'Massa polipoide em cacho de uva que protrai pelo orifício vaginal ou cervical, com a camada cambial de Nicholson — uma faixa densa de células pequenas logo abaixo do epitélio — sobre um estroma mixoide hipocelular. No colo de adolescente, associa-se a DICER1 e pode ter ilhas de cartilagem.',
    criteria: [
      'Arquitetura polipoide multinodular com estroma mixoide e camada cambial subepitelial densa.',
      'Rabdomioblastos com citoplasma eosinofílico e, às vezes, estriações cruzadas.',
      'Desmina, miogenina e MyoD1 positivos confirmam a linhagem esquelética.',
      'Cartilagem hialina no colo aponta DICER1, e obriga rastreio de blastoma pleuropulmonar e de Sertoli-Leydig.',
      'Ausência de rearranjo de FOXO1, o que o separa do rabdomiossarcoma alveolar.',
    ],
    markers: [
      { marker: 'desmina', pct: [90, 100] },
      { marker: 'miogenina', pct: [80, 100], note: 'focal e heterogênea, ao contrário da difusa do alveolar' },
      { marker: 'myod1', pct: [85, 100] },
      { marker: 'msa', pct: [70, 95] },
      { marker: 'sma', pct: [20, 50] },
      { marker: 's100', pct: [20, 50], note: 'nas ilhas de cartilagem da variante DICER1' },
      { marker: 'caldesmon', pct: [0, 15], note: 'o negativo que separa de tumor de músculo liso' },
      { marker: 'ae1ae3', pct: [0, 10], note: 'só o epitélio de superfície aprisionado' },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'er', pct: [0, 15] },
      { marker: 'cd99', pct: [10, 40] },
      { marker: 'ini1', pct: [0, 5], note: 'retido' },
      { marker: 'ki67', pct: [40, 90] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Pólipo fibroepitelial vaginal: células estromais multinucleadas sem camada cambial, desmina focal, benigno.',
      'Adenossarcoma: componente epitelial benigno com manguito periglandular.',
      'Rabdomiossarcoma alveolar: miogenina difusa e forte, fusão FOXO1.',
      'Sarcoma do estroma endometrial: CD10 difuso, sem marcadores musculares esqueléticos.',
      'Carcinoma neuroendócrino de pequenas células: sinaptofisina e INSM1.',
    ],
    molecular: 'DICER1 nos cervicais; sem fusão FOXO1; alterações de RAS em parte.',
    sources: [WHO, NUCCI],
  },
  {
    id: 'nodulo-sitio-placentario',
    name: 'Nódulo de sítio placentário e sítio placentário exagerado',
    aka: ['nódulo de sítio placentário', 'placental site nodule', 'exaggerated placental site', 'APSN'],
    behavior: 'benigno',
    sites: [
      { site: 'utero', role: 'primario', freq: 2 },
      { site: 'colo', role: 'primario', freq: 1 },
    ],
    cells: ['trofoblastico', 'epitelioide'],
    architecture: ['nodular', 'infiltrativo'],
    features: ['hialinizacao', 'mitoses-raras', 'necrose'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Os dois resíduos trofoblásticos não neoplásicos, e os principais mímicos dos tumores trofoblásticos. O nódulo de sítio placentário é um nódulo pequeno, bem delimitado e hialinizado, achado incidental em curetagem. O sítio placentário exagerado é a infiltração fisiológica do miométrio por trofoblasto intermediário, sem massa.',
    criteria: [
      'Nódulo de sítio placentário: nódulo circunscrito de até alguns milímetros, com trofoblasto intermediário degenerado em matriz hialina densa.',
      'Ki-67 abaixo de 5% no nódulo e abaixo de 1% no sítio placentário exagerado: é o critério que separa dos tumores.',
      'Sítio placentário exagerado: células trofoblásticas intermediárias infiltrando o miométrio sem formar massa, com células multinucleadas.',
      'Nódulo atípico de sítio placentário: tamanho ou celularidade intermediários, com Ki-67 entre 5 e 10%, e exige seguimento.',
      'β-hCG sérica normal ou muito baixa, ao contrário dos tumores trofoblásticos.',
    ],
    markers: [
      { marker: 'ki67', pct: [0, 10], note: 'abaixo de 5%: é o que separa do tumor trofoblástico epitelioide e do de sítio placentário' },
      { marker: 'p63', pct: [70, 95], note: 'positivo no nódulo, como no tumor trofoblástico epitelioide' },
      { marker: 'hpl', pct: [30, 70], note: 'difuso no sítio placentário exagerado; focal no nódulo' },
      { marker: 'gata3', pct: [90, 100] },
      { marker: 'ae1ae3', pct: [95, 100] },
      { marker: 'inibina', pct: [70, 95] },
      { marker: 'hcg', pct: [10, 40], note: 'focal, em células sinciciais' },
      { marker: 'p16', pct: [40, 80] },
      { marker: 'ck7', pct: [80, 100] },
      { marker: 'ema', pct: [40, 80] },
      { marker: 'sall4', pct: [0, 5] },
      { marker: 'p53', pct: [0, 10] },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Tumor trofoblástico epitelioide: massa maior, necrose geográfica, Ki-67 acima de 10%.',
      'Tumor trofoblástico do sítio placentário: infiltração dissecante com substituição da parede vascular, hPL difuso.',
      'Carcinoma escamoso do colo: p16 em bloco com HPV, GATA3 e inibina negativos.',
      'Carcinoma epidermoide queratinizante e metaplasia escamosa cervical: sem GATA3 nem hPL.',
      'Restos coriônicos e gestação recente: vilosidades presentes.',
    ],
    pitfalls: ['O nódulo de sítio placentário é p63 positivo como o tumor trofoblástico epitelioide: o Ki-67 é que decide, e sem ele o caso vira neoplasia.'],
    sources: [WHO, NUCCI],
  },
  {
    id: 'adenose-vaginal',
    name: 'Adenose vaginal e carcinoma de células claras vaginal',
    aka: ['adenose vaginal', 'carcinoma de células claras da vagina', 'exposição a dietilestilbestrol'],
    behavior: 'intermediario',
    sites: [{ site: 'vulva-vagina', role: 'primario', freq: 1 }],
    cells: ['glandular', 'claras', 'epitelioide'],
    architecture: ['glandulas', 'papilar', 'cistico', 'trabecular'],
    features: ['tachinha', 'mucina', 'precursor', 'hialinizacao'],
    ages: ['jovem', 'adulto'],
    sex: 'f',
    summary: 'Presença de epitélio glandular mülleriano na vagina, que deveria ser só escamosa; historicamente ligada à exposição intrauterina ao dietilestilbestrol, é a lesão de base sobre a qual surge o carcinoma de células claras vaginal em mulher jovem — hoje raro, mas o verbete permanece porque a adenose também ocorre sem o antecedente.',
    criteria: [
      'Glândulas ou epitélio colunar mucinoso de tipo endocervical, ou tuboendometrioide, na parede vaginal.',
      'Adenose atípica: atipia nuclear com tachinha, considerada precursora do carcinoma de células claras.',
      'Carcinoma de células claras: padrões tubulocístico, papilar e sólido com células em tachinha e estroma hialinizado.',
      'Napsina A e HNF1β positivos com ER negativo no carcinoma, como nos de células claras de outros sítios müllerianos.',
      'História de exposição a dietilestilbestrol apoia, mas a ausência dela não exclui.',
    ],
    markers: [
      { marker: 'pax8', pct: [85, 100] },
      { marker: 'ck7', pct: [90, 100] },
      { marker: 'hnf1b', pct: [70, 95], note: 'no carcinoma de células claras' },
      { marker: 'napsina', pct: [60, 90] },
      { marker: 'er', pct: [10, 50], note: 'positivo na adenose, negativo no carcinoma de células claras' },
      { marker: 'pr', pct: [10, 50] },
      { marker: 'p16', pct: [10, 40], note: 'focal; em bloco indicaria origem HPV' },
      { marker: 'p53', pct: [10, 30], note: 'selvagem na maioria' },
      { marker: 'amacr', pct: [40, 80] },
      { marker: 'caix', pct: [10, 40], note: 'o negativo em caixa ajuda contra metástase renal' },
      { marker: 'cd10', pct: [10, 40] },
      { marker: 'wt1', pct: [0, 15] },
      { marker: 'ki67', pct: [2, 50], note: 'baixo na adenose e alto no carcinoma' },
      { marker: 'cd45', pct: 0 },
    ],
    mimics: [
      'Metástase de carcinoma de células claras do endométrio ou do ovário: imuno idêntica, e a clínica decide.',
      'Adenocarcinoma endocervical estendendo-se à vagina: p16 em bloco.',
      'Metástase de carcinoma renal de células claras: CA-IX em caixa, CD10 forte.',
      'Reação de Arias-Stella em adenose: contexto gestacional, Ki-67 baixo.',
      'Endometriose vaginal: estroma endometrial CD10 positivo.',
    ],
    sources: [WHO, NUCCI],
  },
]
