/* ==========================================================================
   content/adnexal.ts — foliculites e perifoliculites, acne e rosácea,
   hidradenite, alopecias cicatriciais e não cicatriciais, e as doenças
   das glândulas écrinas.
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'
const SPERLING = 'Sperling: An Atlas of Hair Pathology with Clinical Correlations, 2ª ed. (2012)'

export const adnexal: Diagnosis[] = [
  {
    id: 'bacterial-folliculitis',
    name: 'Foliculite bacteriana / furúnculo',
    patterns: ['folliculitis', 'neutrophilic'],
    clinical: ['follicular', 'pustule', 'acute', 'trunk', 'scalp', 'legs', 'pain', 'diabetes', 'immunosuppression', 'nodule'],
    histology: ['folliculitis-neutrophilic', 'follicular-rupture', 'bacteria', 'neutrophils-dermis', 'subcorneal-pustule', 'foreign-body-giant-cells'],
    hallmarks: ['folliculitis-neutrophilic'],
    frequency: 3,
    summary: 'Pústulas centradas em pelos ou nódulo flutuante doloroso; neutrófilos no infundíbulo e ao redor dele, com ruptura e abscesso dérmico (furúnculo), cocos ao Gram.',
    clues: ['Pústula folicular com neutrófilos dentro do canal; ruptura leva a reação de corpo estranho à queratina e ao pelo.', 'Pseudofoliculite da barba: pelo encravado com reação granulomatosa, sem bactéria.'],
    mimics: ['Foliculite por Malassezia: leveduras no infundíbulo dilatado (PAS).', 'Foliculite eosinofílica: eosinófilos.', 'Foliculite herpética: multinucleação no epitélio folicular.', 'Foliculite por Demodex: ácaros em número.', 'Acne: comedão, sebáceas.'],
    next: ['Gram e PAS; cultura se recorrente.'],
    sources: [WEEDON],
  },
  {
    id: 'malassezia-folliculitis',
    name: 'Foliculite por Malassezia',
    aka: ['Foliculite pitirospórica'],
    patterns: ['folliculitis'],
    clinical: ['follicular', 'trunk', 'young-adult', 'itch', 'chronic', 'immunosuppression', 'papule', 'pustule'],
    histology: ['folliculitis-neutrophilic', 'hyphae', 'pas-positive', 'follicular-rupture', 'follicular-plug', 'lymphocytic-superficial'],
    hallmarks: ['hyphae', 'pas-positive'],
    frequency: 2,
    summary: 'Pápulo-pústulas foliculares monomórficas pruriginosas em dorso e tórax que não respondem a antibiótico; infundíbulo dilatado cheio de queratina com leveduras redondas em brotamento (PAS), com inflamação neutrofílica e ruptura.',
    clues: ['Muitas leveduras (não hifas) dentro do folículo dilatado, além do que se vê em pele normal.', 'Comum após antibiótico, corticoide ou em imunossuprimido.'],
    mimics: ['Acne: comedões e sebáceas, poucas leveduras.', 'Foliculite bacteriana: cocos.', 'Foliculite eosinofílica: eosinófilos.'],
    next: ['PAS.'],
    sources: [WEEDON],
  },
  {
    id: 'eosinophilic-folliculitis',
    name: 'Foliculite pustulosa eosinofílica',
    aka: ['Doença de Ofuji', 'Foliculite eosinofílica associada ao HIV'],
    patterns: ['folliculitis'],
    clinical: ['immunosuppression', 'itch', 'follicular', 'face', 'trunk', 'annular', 'chronic', 'relapsing', 'child', 'papule', 'pustule'],
    histology: ['eosinophils', 'eosinophilic-spongiosis', 'folliculitis-lymphocytic', 'sebaceous-loss', 'flame-figures', 'superficial-and-deep'],
    hallmarks: ['eosinophils', 'eosinophilic-spongiosis'],
    against: ['bacteria', 'hyphae', 'mite'],
    frequency: 1,
    summary: 'Pápulas foliculares muito pruriginosas em face e tronco superior de paciente com HIV avançado, ou placas anulares de pústulas em japonês (Ofuji); espongiose eosinofílica do infundíbulo e da glândula sebácea, com eosinófilos perifoliculares, sem organismos.',
    clues: ['Eosinófilos dentro do epitélio folicular e na sebácea ("sebaceíte eosinofílica").', 'Excluir Demodex, escabiose e fungos.'],
    mimics: ['Escabiose: ácaro, também eosinófilos em HIV.', 'Foliculite por Demodex: ácaros.', 'Picada: cunha não folicular.', 'Erupção papular pruriginosa do HIV: reação a picada exagerada, não folicular.'],
    next: ['PAS, pesquisa de ácaro; CD4 e carga viral.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'acne-vulgaris',
    name: 'Acne vulgar',
    patterns: ['folliculitis'],
    clinical: ['young-adult', 'face', 'trunk', 'seborrheic', 'papule', 'pustule', 'nodule', 'chronic', 'atrophy'],
    histology: ['follicular-plug', 'folliculitis-neutrophilic', 'follicular-rupture', 'foreign-body-giant-cells', 'sclerosis', 'neutrophils-dermis'],
    hallmarks: ['follicular-plug', 'follicular-rupture'],
    frequency: 3,
    summary: 'Comedões, pápulas, pústulas e nódulos em face e dorso de adolescente; infundíbulo dilatado por queratina (comedão) que rompe e provoca abscesso e granuloma de corpo estranho ao redor de queratina e pelo, evoluindo para cicatriz.',
    clues: ['O comedão é a lesão primária; tudo o mais é ruptura e reação à queratina.', 'Raramente biopsiado; a biópsia serve para excluir foliculite infecciosa ou rosácea granulomatosa.'],
    mimics: ['Rosácea: sem comedões, Demodex, vasos ectásicos.', 'Foliculite por Malassezia: leveduras.', 'Acne induzida (corticoide, EGFR): monomórfica, sem comedões.'],
    sources: [WEEDON],
  },
  {
    id: 'rosacea',
    name: 'Rosácea',
    patterns: ['folliculitis', 'perivascular-superficial'],
    clinical: ['face', 'female', 'telangiectasia', 'papule', 'pustule', 'chronic', 'relapsing', 'sun', 'photosensitive'],
    histology: ['dilated-vessels', 'periadnexal', 'folliculitis-lymphocytic', 'demodex', 'solar-elastosis', 'papillary-edema', 'sarcoidal-granuloma', 'folliculitis-neutrophilic', 'sclerosis'],
    hallmarks: ['dilated-vessels', 'demodex', 'periadnexal'],
    against: ['follicular-plug', 'vacuolar', 'bmz-thickening', 'mucin'],
    frequency: 3,
    summary: 'Eritema centrofacial com telangiectasias, pápulas e pústulas sem comedões; vasos ectásicos na derme superior com edema, infiltrado linfocitário perivascular e perifolicular, Demodex nos infundíbulos e elastose solar; granulomas na forma granulomatosa, fibrose e hiperplasia sebácea no rinofima.',
    clues: ['Telangiectasias + infiltrado perifolicular + Demodex numa pele solar de face: rosácea, não lúpus.', 'Sem interface, sem tampões, sem espessamento da basal.'],
    mimics: ['Lúpus discoide / agudo: interface, mucina, membrana basal.', 'Dermatite seborreica: espongiose e paraceratose folicular.', 'Acne: comedões.', 'Sarcoidose: granulomas nus difusos.', 'Dermatite perioral: forma periorificial da mesma doença.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'hidradenitis-suppurativa',
    name: 'Hidradenite supurativa',
    aka: ['Acne inversa', 'Celulite dissecante do couro cabeludo (mesma família)'],
    patterns: ['folliculitis', 'neutrophilic'],
    clinical: ['flexural', 'genital', 'nodule', 'subcutaneous-nodule', 'pain', 'chronic', 'relapsing', 'ulcer', 'family', 'young-adult', 'ibd'],
    histology: ['follicular-plug', 'follicular-rupture', 'neutrophils-dermis', 'foreign-body-giant-cells', 'sclerosis', 'lymphoid-follicles', 'plasma-cells', 'fat-necrosis'],
    hallmarks: ['follicular-rupture', 'sclerosis'],
    frequency: 2,
    summary: 'Nódulos, abscessos, fístulas e cicatrizes em axilas, virilhas e nádegas; oclusão e dilatação do infundíbulo com ruptura, abscessos e trajetos sinusais revestidos por epitélio escamoso na derme profunda e subcutâneo, com fibrose densa; as glândulas apócrinas são acometidas por vizinhança.',
    clues: ['Trajetos epitelizados com queratina e pelo livre, cercados de abscesso e fibrose, atingindo o subcutâneo.', 'Carcinoma espinocelular pode surgir em fístulas de décadas.'],
    mimics: ['Furunculose: sem fístulas nem cicatriz.', 'Doença de Crohn cutânea: granulomas não caseosos e úlceras "em faca"; podem coexistir.', 'Cisto epidérmico roto: solitário.', 'Actinomicose / micetoma: grãos.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'folliculitis-decalvans',
    name: 'Foliculite decalvante',
    patterns: ['alopecia', 'folliculitis', 'neutrophilic'],
    clinical: ['scalp', 'hair-loss', 'pustule', 'follicular', 'chronic', 'male', 'pain', 'atrophy'],
    histology: ['folliculitis-neutrophilic', 'follicular-rupture', 'plasma-cells', 'sclerosis', 'foreign-body-giant-cells', 'perifollicular-fibrosis', 'bacteria', 'neutrophils-dermis'],
    hallmarks: ['folliculitis-neutrophilic', 'follicular-rupture'],
    frequency: 1,
    summary: 'Placa de alopecia cicatricial no vértice com pústulas e "pelos em tufo" (politriquia); foliculite neutrofílica que rompe e destrói o folículo, com infiltrado misto rico em plasmócitos, fibrose e vários pelos saindo de um mesmo óstio.',
    clues: ['Vários pelos compartilhando um infundíbulo dilatado, com abscessos e plasmócitos, em couro cabeludo cicatricial.', 'Staphylococcus aureus quase sempre na cultura.'],
    mimics: ['Líquen planopilar: linfocitário, sem pústulas.', 'Celulite dissecante: nódulos flutuantes e fístulas profundas.', 'Tinha capitis inflamatória (kerion): fungos na haste.', 'Acne queloidiana da nuca: nuca, queloide.'],
    next: ['PAS e cultura.'],
    sources: [WEEDON, SPERLING],
  },
  {
    id: 'lichen-planopilaris',
    name: 'Líquen planopilar / alopecia frontal fibrosante',
    aka: ['LPP', 'Síndrome de Graham-Little', 'AFF'],
    patterns: ['alopecia', 'interface-lichenoid', 'folliculitis'],
    clinical: ['scalp', 'hair-loss', 'female', 'atrophy', 'follicular', 'chronic', 'itch', 'pain', 'elderly', 'face'],
    histology: ['folliculitis-lymphocytic', 'perifollicular-fibrosis', 'vacuolar', 'necrotic-keratinocytes', 'sebaceous-loss', 'follicular-plug', 'thick-collagen', 'wedge-hypergranulosis'],
    hallmarks: ['folliculitis-lymphocytic', 'perifollicular-fibrosis'],
    against: ['mucin', 'bmz-thickening', 'periadnexal', 'folliculitis-neutrophilic'],
    frequency: 2,
    summary: 'Alopecia cicatricial em placas com eritema e hiperceratose perifolicular na borda (LPP), ou recuo em faixa da linha frontal com perda das sobrancelhas em mulher pós-menopausa (AFF); infiltrado liquenoide limitado ao istmo e infundíbulo com dano vacuolar do epitélio folicular, fibrose lamelar concêntrica e perda precoce das sebáceas; a epiderme interfolicular é poupada.',
    clues: [
      'A interface é folicular, no nível do istmo (bulge), e a epiderme entre folículos está normal; fendas artefatuais entre folículo e fibrose ("efeito de retração").',
      'Fibrose perifolicular concêntrica em "cebola" e fusão de folículos em unidades compostas nas fases finais.',
      'AFF: mesmo quadro com folículos velos e intermediários acometidos, pouca inflamação.',
    ],
    mimics: [
      'Lúpus discoide: interface também na epiderme interfolicular, mucina, membrana basal espessa, infiltrado periécrino profundo, banda lúpica.',
      'Alopecia cicatricial centrífuga central: fibrose perifolicular com descamação prematura da bainha interna, pouca interface, mulheres negras no vértice.',
      'Foliculite decalvante: neutrófilos, plasmócitos, tufos.',
      'Pseudopelade de Brocq: estágio final "queimado" de qualquer uma.',
    ],
    next: ['Cortes transversais para contar folículos; PAS e mucina para excluir lúpus; IF se houver dúvida.'],
    sources: [WEEDON, SPERLING],
  },
  {
    id: 'ccca',
    name: 'Alopecia cicatricial centrífuga central',
    aka: ['CCCA', 'Alopecia por pente quente', 'Síndrome da degeneração folicular'],
    patterns: ['alopecia'],
    clinical: ['scalp', 'hair-loss', 'female', 'chronic', 'asymptomatic', 'atrophy', 'itch'],
    histology: ['perifollicular-fibrosis', 'folliculitis-lymphocytic', 'sebaceous-loss', 'follicular-rupture', 'thick-collagen', 'foreign-body-giant-cells'],
    hallmarks: ['perifollicular-fibrosis', 'sebaceous-loss'],
    against: ['vacuolar', 'mucin', 'folliculitis-neutrophilic'],
    frequency: 2,
    summary: 'Alopecia cicatricial que começa no vértice e se expande centrifugamente em mulheres negras; descamação prematura da bainha radicular interna, fibrose lamelar perifolicular com inflamação linfocitária discreta, perda de sebáceas e folículos "nus" que rompem no final.',
    clues: ['Descamação prematura da bainha interna abaixo do istmo é o sinal precoce em cortes transversais.', 'Menos interface que no líquen planopilar; sobreposição frequente.'],
    mimics: ['Líquen planopilar: interface liquenoide folicular clara.', 'Alopecia por tração: miniaturização com fibrose, distribuição marginal.', 'Foliculite decalvante: neutrófilos.'],
    next: ['Cortes transversais.'],
    sources: [SPERLING, WEEDON],
  },
  {
    id: 'alopecia-areata',
    name: 'Alopecia areata',
    patterns: ['alopecia'],
    clinical: ['hair-loss', 'scalp', 'acute', 'relapsing', 'child', 'young-adult', 'thyroid', 'atopy', 'nails', 'autoimmune', 'asymptomatic'],
    histology: ['peribulbar-lymphocytes', 'catagen-telogen', 'follicular-miniaturization', 'pigment-incontinence', 'eosinophils', 'hair-shaft-damage'],
    hallmarks: ['peribulbar-lymphocytes', 'catagen-telogen'],
    against: ['perifollicular-fibrosis', 'sebaceous-loss', 'folliculitis-neutrophilic'],
    frequency: 3,
    summary: 'Placas redondas de alopecia não cicatricial com pelos em ponto de exclamação; linfócitos peribulbares em "enxame de abelhas" ao redor dos bulbos anágenos (fase aguda), depois catágenos e telógenos em excesso com folículos miniaturizados e incontinência pigmentar no trajeto fibroso (fase crônica).',
    clues: [
      'O infiltrado é peri e intrabulbar, profundo, e o folículo acima está normal; sebáceas preservadas.',
      'Na fase crônica pode não haver infiltrado: contar folículos em transversal (anágeno/telógeno invertido, muitos velos, trajetos fibrosos com pigmento e eosinófilos).',
    ],
    mimics: ['Eflúvio telógeno: sem inflamação, sem miniaturização, telógenos aumentados mas folículos normais em número.', 'Alopecia androgenética: miniaturização sem inflamação bulbar, padrão.', 'Tricotilomania: hastes distorcidas, tricomalácia, cilindros pigmentares, sem linfócitos.', 'Sífilis secundária: plasmócitos, sorologia.'],
    next: ['Cortes transversais para razão anágeno/telógeno e terminal/velo.'],
    sources: [SPERLING, WEEDON],
  },
  {
    id: 'androgenetic-alopecia',
    name: 'Alopecia androgenética',
    aka: ['Alopecia de padrão', 'Calvície'],
    patterns: ['alopecia', 'invisible'],
    clinical: ['hair-loss', 'scalp', 'chronic', 'male', 'female', 'family', 'asymptomatic'],
    histology: ['follicular-miniaturization', 'sparse-infiltrate', 'catagen-telogen', 'solar-elastosis'],
    hallmarks: ['follicular-miniaturization'],
    against: ['peribulbar-lymphocytes', 'perifollicular-fibrosis', 'sebaceous-loss'],
    frequency: 3,
    summary: 'Rarefação do vértice e recuo temporal no homem, ou alargamento da risca na mulher; miniaturização progressiva dos folículos (razão terminal:velo abaixo de 4:1 em cortes transversais) com número total preservado, trajetos fibrosos e infiltrado perifolicular discreto, sem cicatriz.',
    clues: ['Muitos velos e folículos de calibre variado na mesma unidade, sebáceas preservadas.', 'Inflamação perifolicular leve é comum e não muda o diagnóstico.'],
    mimics: ['Alopecia areata crônica: mais telógenos, pigmento nos trajetos fibrosos, infiltrado bulbar.', 'Eflúvio telógeno: sem miniaturização.', 'Alopecia frontal fibrosante: fibrose perifolicular e perda de sebáceas.'],
    next: ['Cortes transversais no nível do istmo.'],
    sources: [SPERLING],
  },
  {
    id: 'telogen-effluvium',
    name: 'Eflúvio telógeno',
    patterns: ['alopecia', 'invisible'],
    clinical: ['hair-loss', 'scalp', 'acute', 'subacute', 'female', 'pregnancy', 'drug', 'fever', 'thyroid', 'generalized'],
    histology: ['catagen-telogen', 'sparse-infiltrate'],
    hallmarks: ['catagen-telogen'],
    against: ['follicular-miniaturization', 'peribulbar-lymphocytes', 'perifollicular-fibrosis'],
    frequency: 3,
    summary: 'Queda difusa 2 a 3 meses após parto, cirurgia, febre, dieta ou novo fármaco; couro cabeludo histologicamente normal exceto pela proporção de telógenos acima de 20% em cortes transversais, sem miniaturização nem inflamação.',
    clues: ['Lâmina normal com telógenos aumentados; a biópsia serve para excluir areata difusa e androgenética.', 'Teste de tração positivo.'],
    mimics: ['Alopecia areata difusa: infiltrado bulbar, pigmento em trajetos.', 'Alopecia androgenética: miniaturização.', 'Eflúvio anágeno: quimioterapia, hastes afiladas.'],
    next: ['Ferritina, TSH, vitamina D e história de 3 meses antes.'],
    sources: [SPERLING],
  },
  {
    id: 'trichotillomania',
    name: 'Tricotilomania / alopecia por tração',
    patterns: ['alopecia'],
    clinical: ['hair-loss', 'scalp', 'child', 'young-adult', 'female', 'chronic', 'asymptomatic'],
    histology: ['hair-shaft-damage', 'catagen-telogen', 'rbc-extravasation', 'sparse-infiltrate', 'follicular-miniaturization', 'perifollicular-fibrosis'],
    hallmarks: ['hair-shaft-damage'],
    against: ['peribulbar-lymphocytes', 'sebaceous-loss'],
    frequency: 2,
    summary: 'Placa de alopecia com pelos quebrados de tamanhos diferentes e formato bizarro; folículos vazios com hastes distorcidas e fragmentadas (tricomalácia), cilindros pigmentares no canal, hemorragia peribulbar e muitos catágenos, sem inflamação; a tração crônica leva a miniaturização e fibrose nas margens.',
    clues: ['Tricomalácia e cilindros de pigmento sem infiltrado linfocitário são a assinatura do trauma.', 'Alopecia por tração: margem frontotemporal, "sinal da franja".'],
    mimics: ['Alopecia areata: linfócitos peribulbares, ponto de exclamação.', 'Tinha capitis: fungos na haste.', 'Alopecia androgenética: miniaturização sem trauma.'],
    sources: [SPERLING, WEEDON],
  },
  {
    id: 'tinea-capitis',
    name: 'Tinha do couro cabeludo',
    aka: ['Tinea capitis', 'Kerion'],
    patterns: ['alopecia', 'folliculitis'],
    clinical: ['child', 'scalp', 'hair-loss', 'scaly-plaque', 'pustule', 'nodule', 'acute', 'subacute', 'travel'],
    histology: ['fungal-hair', 'pas-positive', 'folliculitis-neutrophilic', 'follicular-rupture', 'suppurative-granuloma', 'hyphae', 'neutrophils-dermis'],
    hallmarks: ['fungal-hair', 'pas-positive'],
    frequency: 2,
    summary: 'Placas descamativas com pelos tonsurados ou placa inflamatória boggy (kerion) em criança; esporos dentro (endótrix) ou ao redor (ectótrix) da haste ao PAS, com foliculite neutrofílica, ruptura e granuloma supurativo.',
    clues: ['Os fungos estão na haste, não só na córnea: cortar folículos.', 'Kerion pode não mostrar fungo pela inflamação intensa; cultura.'],
    mimics: ['Foliculite decalvante: sem fungo, tufos.', 'Dermatite seborreica: sem alopecia franca.', 'Alopecia areata: sem inflamação neutrofílica.', 'Tricotilomania: hastes quebradas sem fungo.'],
    next: ['PAS; cultura e lâmpada de Wood.'],
    sources: [WEEDON],
  },
  {
    id: 'demodicosis',
    name: 'Demodicidose',
    aka: ['Foliculite por Demodex', 'Pitiríase folliculorum'],
    patterns: ['folliculitis'],
    clinical: ['face', 'follicular', 'papule', 'pustule', 'itch', 'immunosuppression', 'elderly', 'chronic'],
    histology: ['demodex', 'folliculitis-lymphocytic', 'folliculitis-neutrophilic', 'follicular-rupture', 'sarcoidal-granuloma', 'periadnexal'],
    hallmarks: ['demodex'],
    frequency: 2,
    summary: 'Pápulo-pústulas foliculares faciais com descamação "em lixa" que respondem a ivermectina; múltiplos Demodex por folículo com infundíbulo dilatado, foliculite linfocitária ou neutrofílica e granulomas quando o ácaro sai do folículo.',
    clues: ['Mais de um ácaro por folículo, ou ácaros com inflamação ao redor; um Demodex isolado é achado normal.', 'Comum em rosácea, HIV e crianças com leucemia.'],
    mimics: ['Rosácea: mesmo espectro.', 'Foliculite bacteriana: cocos.', 'Foliculite eosinofílica: eosinófilos, HIV.'],
    sources: [WEEDON],
  },
  {
    id: 'neutrophilic-eccrine-hidradenitis',
    name: 'Hidradenite écrina neutrofílica / hidradenite palmoplantar idiopática',
    patterns: ['neutrophilic'],
    clinical: ['malignancy', 'drug', 'acute', 'papule', 'nodule', 'acral', 'child', 'fever', 'pain', 'trunk'],
    histology: ['eccrine-neutrophils', 'syringometaplasia', 'neutrophils-dermis', 'papillary-edema', 'periadnexal'],
    hallmarks: ['eccrine-neutrophils'],
    frequency: 1,
    summary: 'Placas eritematosas dolorosas dias após quimioterapia (citarabina) ou nódulos plantares em criança após exercício e calçado úmido; neutrófilos ao redor e dentro do enovelado écrino com necrose do epitélio glandular, muitas vezes com metaplasia siringoescamosa.',
    clues: ['O alvo é a glândula écrina, não o folículo nem os vasos; procurar necrose das células secretoras.', 'Metaplasia escamosa do ducto (siringometaplasia) aparece na fase de reparo.'],
    mimics: ['Sweet: infiltrado difuso não centrado na écrina.', 'Celulite: bactérias, cultura.', 'Bolha de coma: necrose écrina sem neutrófilos.', 'Eritema nodoso plantar: paniculite.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'follicular-mucinosis',
    name: 'Mucinose folicular / alopecia mucinosa',
    patterns: ['folliculitis', 'deposition'],
    clinical: ['face', 'scalp', 'hair-loss', 'papule', 'follicular', 'chronic', 'young-adult', 'elderly', 'itch'],
    histology: ['follicular-mucinosis', 'folliculitis-lymphocytic', 'eosinophils', 'periadnexal', 'atypical-lymphocytes', 'epidermotropism'],
    hallmarks: ['follicular-mucinosis'],
    frequency: 1,
    summary: 'Placas de pápulas foliculares com alopecia na face e couro cabeludo; acúmulo de mucina entre as células da bainha externa e da sebácea, que ficam dissociadas em "rede", com linfócitos e eosinófilos perifoliculares.',
    clues: ['Mucina dentro do epitélio folicular (alcian blue); a forma idiopática de jovens é localizada e regride.', 'Em adultos com lesões múltiplas e linfócitos atípicos no folículo, é micose fungoide foliculotrópica até prova em contrário.'],
    mimics: ['Micose fungoide foliculotrópica: atipia, clone, perda de CD7; a mucinose é secundária.', 'Lúpus discoide: interface epidérmica, membrana basal.', 'Foliculite eosinofílica: sem mucina.'],
    next: ['Alcian blue; IHQ e rearranjo do TCR em adultos ou lesões múltiplas.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'keratosis-pilaris-group',
    name: 'Ceratose pilar e pseudofoliculite',
    aka: ['Ceratose folicular', 'Pseudofoliculite da barba'],
    patterns: ['folliculitis', 'invisible'],
    clinical: ['extensor', 'follicular', 'papule', 'atopy', 'child', 'young-adult', 'chronic', 'asymptomatic', 'face'],
    histology: ['follicular-plug', 'sparse-infiltrate', 'follicular-rupture', 'foreign-body-giant-cells', 'hypergranulosis'],
    hallmarks: ['follicular-plug'],
    against: ['bacteria', 'hyphae', 'eosinophils'],
    frequency: 3,
    summary: 'Pápulas foliculares ásperas em braços e coxas (ceratose pilar) ou pápulas na área da barba raspada (pseudofoliculite); infundíbulo dilatado por rolha de queratina que às vezes contém o pelo enrolado, com pouca ou nenhuma inflamação, ou pelo encravado com reação granulomatosa.',
    clues: ['Rolha córnea infundibular sem infecção; na pseudofoliculite, o pelo reentra na derme e gera granuloma de corpo estranho.', 'Biopsiada raramente; serve para excluir foliculite infecciosa e líquen espinuloso.'],
    mimics: ['Foliculite bacteriana / Malassezia: organismos.', 'PRP: tampões foliculares com tabuleiro na epiderme interfolicular.', 'Líquen espinuloso: mesma histologia em placa agrupada.'],
    sources: [WEEDON],
  },
]
