/* ==========================================================================
   content/blistering.ts — vesículas, bolhas e pústulas: acantolíticas
   (pênfigos, Hailey-Hailey, Darier, Grover), subepidérmicas (penfigoides,
   IgA linear, dermatite herpetiforme, EBA, lúpus bolhoso, porfiria),
   virais, bacterianas e as pustuloses estéreis (PEGA, Sneddon-Wilkinson,
   neonatais).
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const ACKERMAN = 'Ackerman: Histologic Diagnosis of Inflammatory Skin Diseases, 3ª ed. (2005)'
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'

export const blistering: Diagnosis[] = [
  {
    id: 'pemphigus-vulgaris',
    name: 'Pênfigo vulgar',
    patterns: ['intraepidermal-blister'],
    clinical: ['mucosa', 'flaccid-bulla', 'pain', 'trunk', 'scalp', 'subacute', 'drug', 'elderly', 'young-adult'],
    histology: ['suprabasal-cleft', 'acantholysis', 'dif-intercellular', 'eosinophilic-spongiosis', 'eosinophils', 'lymphocytic-superficial', 'periadnexal'],
    hallmarks: ['suprabasal-cleft', 'dif-intercellular'],
    against: ['dyskeratosis', 'subepidermal-cell-poor', 'dif-linear-bmz', 'necrotic-keratinocytes'],
    frequency: 2,
    summary: 'Erosões orais dolorosas e bolhas flácidas que se rompem; fenda suprabasal com a fileira basal presa à derme ("lápides") e células acantolíticas soltas na cavidade, estendendo-se à bainha folicular, com IgG intercelular na IF.',
    clues: [
      'Acantólise suprabasal que segue o folículo piloso, deixando a basal em lápide e a papila dérmica "nua" projetada na bolha.',
      'Lesão precoce ou perilesional: espongiose eosinofílica sem fenda ainda.',
      'IF direta com IgG e C3 em rede intercelular; anti-desmogleína 3 (e 1 na forma mucocutânea).',
    ],
    mimics: [
      'Hailey-Hailey: acantólise em toda a espessura ("muro em ruínas"), IF negativa, dobras.',
      'Darier: disceratose (corpos redondos e grãos), IF negativa, áreas seborreicas.',
      'Pênfigo paraneoplásico: acantólise mais interface e queratinócitos necróticos, IF também na ZMB, neoplasia.',
      'Pênfigo foliáceo: fenda subcórnea ou na granulosa.',
      'Herpes: balonização e multinucleação, acantólise secundária.',
    ],
    next: ['IF direta perilesional; ELISA anti-Dsg1/Dsg3.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'pemphigus-foliaceus',
    name: 'Pênfigo foliáceo (incluindo fogo selvagem)',
    aka: ['Pênfigo endêmico brasileiro', 'Pênfigo eritematoso (Senear-Usher)'],
    patterns: ['intraepidermal-blister'],
    clinical: ['seborrheic', 'trunk', 'face', 'scaly-plaque', 'flaccid-bulla', 'pain', 'travel', 'young-adult', 'drug', 'erythroderma', 'insect'],
    histology: ['subcorneal-pustule', 'acantholysis', 'intraepidermal-blister', 'dif-intercellular', 'eosinophilic-spongiosis', 'neutrophils-dermis', 'eosinophils', 'dyskeratosis'],
    hallmarks: ['acantholysis', 'dif-intercellular'],
    against: ['suprabasal-cleft', 'mucosa', 'hyphae', 'bacteria'],
    frequency: 2,
    summary: 'Erosões crostosas e escamosas em áreas seborreicas sem lesão oral, endêmico em áreas rurais do Brasil (fogo selvagem); fenda subcórnea ou na camada granulosa com células acantolíticas, muitas vezes só crosta com queratinócitos soltos, e IgG intercelular superficial na IF.',
    clues: [
      'A bolha é tão alta que quase sempre já rompeu: procurar acantólise na granulosa sob a crosta e disceratose focal.',
      'Neutrófilos e eosinófilos na fenda são comuns; sem fungos nem bactérias.',
      'IF direta e anti-Dsg1 fecham; forma eritematosa tem também banda lúpica.',
    ],
    mimics: [
      'Impetigo bolhoso / SSSS: mesma altura de fenda, mas com cocos (Gram) ou toxina; IF negativa.',
      'Pustulose subcórnea / pênfigo IgA: neutrófilos predominam, IgA na IF.',
      'Dermatite seborreica: sem acantólise.',
      'Pênfigo vulgar: suprabasal, mucosa.',
    ],
    next: ['IF direta e ELISA anti-Dsg1; Gram na dúvida.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'paraneoplastic-pemphigus',
    name: 'Pênfigo paraneoplásico',
    aka: ['Síndrome multiorgânica autoimune paraneoplásica'],
    patterns: ['intraepidermal-blister', 'interface-lichenoid'],
    clinical: ['mucosa', 'malignancy', 'flaccid-bulla', 'target', 'violaceous', 'pain', 'acral', 'subacute'],
    histology: ['acantholysis', 'suprabasal-cleft', 'vacuolar', 'necrotic-keratinocytes', 'band-like', 'dif-intercellular', 'dif-linear-bmz'],
    hallmarks: ['acantholysis', 'necrotic-keratinocytes'],
    frequency: 1,
    summary: 'Estomatite intratável com lesões polimorfas (bolhas, alvos, líquen plano) em paciente com linfoma, LLC ou Castleman; acantólise suprabasal somada a dermatite de interface liquenoide com queratinócitos necróticos, e IF com IgG intercelular e na ZMB.',
    clues: ['Acantólise + interface no mesmo corte é a combinação-chave.', 'IF indireta em bexiga de rato positiva; anti-plaquinas e anti-Dsg.'],
    mimics: ['Pênfigo vulgar: sem interface.', 'Eritema multiforme / NET: sem acantólise, sem IF.', 'Líquen plano erosivo: sem acantólise, sem IgG intercelular.', 'GVHD: contexto de transplante.'],
    next: ['IF direta e indireta (bexiga de rato), imunoprecipitação; rastreio de neoplasia linfoide e Castleman.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'iga-pemphigus',
    name: 'Pênfigo por IgA',
    aka: ['Dermatose pustulosa intraepidérmica IgA', 'Tipo pustulose subcórnea'],
    patterns: ['intraepidermal-blister', 'neutrophilic'],
    clinical: ['pustule', 'flexural', 'trunk', 'annular', 'chronic', 'itch', 'malignancy'],
    histology: ['subcorneal-pustule', 'intraepidermal-blister', 'acantholysis', 'exocytosis-neutrophils', 'neutrophils-dermis'],
    hallmarks: ['subcorneal-pustule'],
    frequency: 1,
    summary: 'Pústulas flácidas em arranjo anular nas dobras e tronco; pústulas subcórneas ou intraepidérmicas com neutrófilos e acantólise discreta, e IgA intercelular na IF direta.',
    clues: ['Igual à pustulose subcórnea de Sneddon-Wilkinson, mas com IgA intercelular; anti-desmocolina 1.', 'Gamopatia IgA associada.'],
    mimics: ['Pustulose subcórnea: IF negativa.', 'Psoríase pustulosa: pústula espongiforme, acantose.', 'Pênfigo foliáceo: IgG, eosinófilos.', 'Candidíase / impetigo: organismos.'],
    next: ['IF direta com IgA; eletroforese de proteínas.'],
    sources: [WEEDON],
  },
  {
    id: 'hailey-hailey',
    name: 'Doença de Hailey-Hailey',
    aka: ['Pênfigo familiar benigno crônico'],
    patterns: ['intraepidermal-blister'],
    clinical: ['flexural', 'family', 'chronic', 'relapsing', 'flaccid-bulla', 'pain', 'young-adult', 'itch'],
    histology: ['acantholysis', 'suprabasal-cleft', 'dif-negative', 'crust', 'dyskeratosis', 'acanthosis-irregular', 'lymphocytic-superficial', 'neutrophils-dermis'],
    hallmarks: ['acantholysis', 'dif-negative'],
    against: ['dif-intercellular', 'mucosa'],
    frequency: 2,
    summary: 'Placas erosivas e fissuradas em axilas, virilhas e pescoço desde a juventude, com história familiar (ATP2C1); acantólise que atinge toda a espessura da epiderme ("muro de tijolos em ruínas") com cristas alongadas, disceratose escassa e IF negativa.',
    clues: ['Acantólise ampla e incompleta, com células ainda parcialmente aderidas, sobre epiderme acantótica; pouca disceratose.', 'Frequentemente sobreinfectada por bactérias e Candida.'],
    mimics: ['Pênfigo vulgar: acantólise limitada à suprabasal, IF positiva.', 'Darier: mais disceratose (corpos redondos e grãos), áreas seborreicas.', 'Grover: focos minúsculos, tronco de idoso.', 'Intertrigo / candidíase: sem acantólise verdadeira.'],
    next: ['IF direta negativa confirma; PAS e Gram para sobreinfecção.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'darier-disease',
    name: 'Doença de Darier',
    aka: ['Ceratose folicular', 'Disceratose folicular'],
    patterns: ['intraepidermal-blister'],
    clinical: ['seborrheic', 'family', 'chronic', 'papule', 'nails', 'young-adult', 'photosensitive', 'linear', 'hyperpigmented'],
    histology: ['dyskeratosis', 'acantholysis', 'suprabasal-cleft', 'parakeratosis-confluent', 'papillomatosis', 'dif-negative', 'acanthosis-irregular'],
    hallmarks: ['dyskeratosis', 'suprabasal-cleft'],
    against: ['dif-intercellular'],
    frequency: 2,
    summary: 'Pápulas ceratósicas gordurosas e malcheirosas em áreas seborreicas, com unhas em V e fendas na palma (ATP2A1); fendas suprabasais com disceratose acantolítica (corpos redondos na granulosa, grãos na córnea) sob coluna de paraceratose.',
    clues: ['Corpos redondos (célula com núcleo picnótico e halo claro) e grãos são a marca da disceratose acantolítica; vilos de papila dérmica projetados na fenda.', 'Forma segmentar linear por mosaico.'],
    mimics: ['Hailey-Hailey: pouca disceratose, acantólise mais extensa, dobras.', 'Grover: idêntico em foco minúsculo e transitório.', 'Disceratoma verrucoso: lesão única em taça.', 'Pênfigo vulgar: sem disceratose, IF positiva.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'grover-disease',
    name: 'Doença de Grover',
    aka: ['Dermatose acantolítica transitória'],
    patterns: ['intraepidermal-blister', 'spongiotic'],
    clinical: ['elderly', 'male', 'trunk', 'papule', 'itch', 'acute', 'relapsing', 'sun', 'immunosuppression'],
    histology: ['acantholysis', 'dyskeratosis', 'suprabasal-cleft', 'spongiosis', 'eosinophils', 'lymphocytic-superficial', 'dif-negative'],
    hallmarks: ['acantholysis'],
    frequency: 3,
    summary: 'Pápulas pruriginosas no tronco de homem idoso após calor, suor ou internação; focos minúsculos (um ou dois cristas) de acantólise com padrão de Darier, Hailey-Hailey, pênfigo ou espongiótico, num mesmo caso.',
    clues: ['A lesão é muito pequena: procurar o foco acantolítico em cortes seriados quando a suspeita clínica for boa.', 'Eosinófilos e espongiose ao redor; IF negativa.'],
    mimics: ['Darier: lesões extensas, história familiar, unhas.', 'Pênfigo: IF positiva.', 'Foliculite / picada: sem acantólise.', 'Dermatite espongiótica: sem foco acantolítico.'],
    next: ['Cortes seriados; IF se houver dúvida com pênfigo.'],
    sources: [WEEDON],
  },
  {
    id: 'bullous-pemphigoid',
    name: 'Penfigoide bolhoso',
    patterns: ['subepidermal-blister', 'spongiotic'],
    clinical: ['elderly', 'bulla', 'itch', 'wheal', 'flexural', 'trunk', 'drug', 'chronic', 'subacute'],
    histology: ['subepidermal-eos', 'eosinophilic-spongiosis', 'eosinophils', 'dif-linear-bmz', 'papillary-edema', 'lymphocytic-superficial', 'subepidermal-cell-poor'],
    hallmarks: ['subepidermal-eos', 'dif-linear-bmz'],
    against: ['acantholysis', 'dif-granular-iga', 'dif-intercellular', 'necrotic-keratinocytes'],
    frequency: 3,
    summary: 'Bolhas tensas sobre base urticariforme em idoso muito pruriginoso; bolha subepidérmica com teto viável e eosinófilos na cavidade e na derme, precedida por espongiose eosinofílica, e IgG/C3 linear na ZMB (lado epidérmico no salt-split).',
    clues: [
      'Fase pré-bolhosa: espongiose eosinofílica e eosinófilos alinhados na junção ("eosinófilos em fila na ZMB") sem bolha.',
      'Teto da bolha íntegro com a basal presa (ao contrário do pênfigo).',
      'Gliptinas, anti-PD-1 e diuréticos de alça induzem penfigoide.',
    ],
    mimics: [
      'Epidermólise bolhosa adquirida: cavidade pobre em células ou com neutrófilos, cicatriz e milia, IgG no assoalho (salt-split).',
      'Penfigoide de membranas mucosas: mucosa, cicatriz, mesma IF.',
      'Dermatite herpetiforme / IgA linear: neutrófilos, IgA.',
      'Eritema multiforme bolhoso: necrose de queratinócitos, sem eosinófilos, IF negativa.',
      'Picada bolhosa: cunha eosinofílica, IF negativa.',
      'Penfigoide gestacional: gestante, C3 linear.',
    ],
    next: ['IF direta perilesional; salt-split e ELISA anti-BP180/BP230.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'pemphigoid-gestationis',
    name: 'Penfigoide gestacional',
    aka: ['Herpes gestationis'],
    patterns: ['subepidermal-blister', 'spongiotic'],
    clinical: ['pregnancy', 'itch', 'wheal', 'bulla', 'trunk', 'acute', 'subacute'],
    histology: ['subepidermal-eos', 'eosinophilic-spongiosis', 'papillary-edema', 'eosinophils', 'dif-linear-bmz', 'necrotic-keratinocytes'],
    hallmarks: ['dif-linear-bmz', 'subepidermal-eos'],
    frequency: 1,
    summary: 'Placas urticariformes que começam ao redor do umbigo no segundo ou terceiro trimestre e viram bolhas; edema papilar em "gota" com eosinófilos e bolha subepidérmica, e C3 linear (com ou sem IgG) na ZMB.',
    clues: ['Edema papilar exuberante com eosinófilos na junção; necrose de basais focal.', 'Umbigo acometido, ao contrário da erupção polimórfica da gestação.'],
    mimics: ['Erupção polimórfica da gestação: IF negativa, estrias, poupa umbigo.', 'Penfigoide bolhoso: sem gestação.', 'Urticária: sem eosinófilos na junção.'],
    next: ['IF direta (C3 linear) e ELISA anti-BP180.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'mucous-membrane-pemphigoid',
    name: 'Penfigoide de membranas mucosas',
    aka: ['Penfigoide cicatricial'],
    patterns: ['subepidermal-blister', 'fibrosing'],
    clinical: ['mucosa', 'elderly', 'chronic', 'atrophy', 'scalp', 'flaccid-bulla', 'pain'],
    histology: ['subepidermal-cell-poor', 'dif-linear-bmz', 'sclerosis', 'plasma-cells', 'lymphocytic-superficial', 'subepidermal-neut', 'dif-linear-iga'],
    hallmarks: ['dif-linear-bmz', 'subepidermal-cell-poor'],
    frequency: 1,
    summary: 'Gengivite descamativa, conjuntivite cicatricial e erosões que cicatrizam com sinéquias (Brunsting-Perry no couro cabeludo); bolha subepidérmica pobre em células ou com neutrófilos e fibrose da lâmina própria, com IgG/IgA/C3 lineares.',
    clues: ['Bolha subepidérmica com fibrose subjacente em mucosa ou cabeça: cicatriz é o critério.', 'Anti-laminina 332: rastreio de neoplasia.'],
    mimics: ['Penfigoide bolhoso: eosinófilos, sem cicatriz.', 'Líquen plano erosivo: interface liquenoide, sem IgG linear.', 'Epidermólise bolhosa adquirida: assoalho no salt-split.', 'Pênfigo vulgar: acantólise.'],
    next: ['IF direta de mucosa (biópsia perilesional); IF indireta em salt-split; ELISA BP180, laminina 332.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'linear-iga-dermatosis',
    name: 'Dermatose por IgA linear',
    aka: ['Doença bolhosa crônica da infância'],
    patterns: ['subepidermal-blister', 'neutrophilic'],
    clinical: ['child', 'bulla', 'annular', 'genital', 'flexural', 'drug', 'acute', 'itch', 'mucosa'],
    histology: ['subepidermal-neut', 'dif-linear-iga', 'neutrophils-dermis', 'papillary-edema', 'eosinophils'],
    hallmarks: ['dif-linear-iga', 'subepidermal-neut'],
    against: ['dif-granular-iga', 'acantholysis'],
    frequency: 1,
    summary: 'Bolhas tensas em "colar de pérolas" ao redor de lesões antigas no períneo e dobras de pré-escolar, ou em adulto após vancomicina; bolha subepidérmica com neutrófilos (às vezes em microabscessos papilares) e IgA linear na ZMB.',
    clues: ['Neutrófilos na junção e na cavidade com IgA linear (não granular): separa da dermatite herpetiforme.', 'Vancomicina é o fármaco clássico.'],
    mimics: ['Dermatite herpetiforme: IgA granular nas papilas, glúten.', 'Penfigoide bolhoso: eosinófilos, IgG.', 'Epidermólise bolhosa adquirida com neutrófilos: IgG no assoalho.', 'Impetigo bolhoso: subcórnea, cocos.'],
    next: ['IF direta com IgA linear; revisar vancomicina e outros fármacos.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'dermatitis-herpetiformis',
    name: 'Dermatite herpetiforme',
    aka: ['Doença de Duhring'],
    patterns: ['subepidermal-blister', 'neutrophilic'],
    clinical: ['extensor', 'itch', 'vesicle', 'papule', 'young-adult', 'chronic', 'relapsing', 'lichenified', 'ibd'],
    histology: ['subepidermal-neut', 'dif-granular-iga', 'neutrophils-dermis', 'papillary-edema', 'crust', 'eosinophils'],
    hallmarks: ['subepidermal-neut', 'dif-granular-iga'],
    against: ['dif-linear-iga', 'dif-linear-bmz', 'acantholysis'],
    frequency: 2,
    summary: 'Pápulo-vesículas agrupadas que coçam a ponto de nunca serem vistas inteiras, em cotovelos, joelhos, nádegas e couro cabeludo, com enteropatia ao glúten; microabscessos de neutrófilos nas pontas das papilas dérmicas com fenda subepidérmica multiloculada, e IgA granular nas papilas.',
    clues: ['Neutrófilos "empilhados" no ápice das papilas, formando fendas nas pontas antes de a bolha confluir.', 'Biópsia perilesional (não da vesícula) para a IF; anti-transglutaminase tecidual.'],
    mimics: ['IgA linear: IgA linear na ZMB.', 'Penfigoide bolhoso: eosinófilos.', 'Lúpus bolhoso: mesma histologia com banda lúpica e lúpus sistêmico.', 'Escabiose escoriada: ácaro, eosinófilos.'],
    next: ['IF direta perilesional (IgA granular); anti-tTG e anti-endomísio; dieta sem glúten.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'epidermolysis-bullosa-acquisita',
    name: 'Epidermólise bolhosa adquirida',
    patterns: ['subepidermal-blister'],
    clinical: ['trauma', 'extensor', 'hands', 'acral', 'bulla', 'atrophy', 'chronic', 'ibd', 'mucosa', 'elderly'],
    histology: ['subepidermal-cell-poor', 'dif-linear-bmz', 'subepidermal-neut', 'sclerosis', 'sparse-infiltrate'],
    hallmarks: ['subepidermal-cell-poor', 'dif-linear-bmz'],
    frequency: 1,
    summary: 'Bolhas por trauma em dorso das mãos, cotovelos e pés que deixam cicatriz e milia (forma mecanobolhosa), ou quadro tipo penfigoide inflamatório; bolha subepidérmica pobre em células e IgG linear na ZMB que fica no assoalho no salt-split.',
    clues: ['Bolha "vazia" com pouca inflamação e fibrose dérmica: pensar em EBA e porfiria.', 'Anti-colágeno VII; salt-split com IgG no assoalho separa de penfigoide.'],
    mimics: ['Penfigoide bolhoso: eosinófilos, teto no salt-split.', 'Porfiria cutânea tardia: festonamento, IF vascular, urina.', 'Penfigoide de membranas mucosas anti-laminina 332: também assoalho; mucosa predominante.', 'Lúpus bolhoso: anti-colágeno VII também, com lúpus sistêmico.'],
    next: ['IF direta e salt-split; ELISA anti-colágeno VII.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'bullous-lupus',
    name: 'Lúpus eritematoso sistêmico bolhoso',
    patterns: ['subepidermal-blister', 'neutrophilic'],
    clinical: ['autoimmune', 'female', 'young-adult', 'bulla', 'photoexposed', 'acute', 'fever', 'renal'],
    histology: ['subepidermal-neut', 'dif-lupus-band', 'dif-linear-bmz', 'neutrophils-dermis', 'mucin', 'lcv', 'vacuolar'],
    hallmarks: ['subepidermal-neut', 'dif-lupus-band'],
    frequency: 1,
    summary: 'Bolhas tensas de aparecimento súbito em paciente com lúpus sistêmico ativo; bolha subepidérmica com neutrófilos nas papilas idêntica à dermatite herpetiforme, com mucina, vasculite ocasional e IF com IgG, IgA, IgM e C3 na ZMB.',
    clues: ['Dermatite herpetiforme "que não é": mucina dérmica, banda lúpica com múltiplos imunorreagentes e anti-colágeno VII.', 'Responde a dapsona.'],
    mimics: ['Dermatite herpetiforme: IgA granular isolada, sem lúpus.', 'IgA linear: só IgA.', 'EBA: sem lúpus sistêmico.', 'Sweet: sem bolha subepidérmica verdadeira.'],
    next: ['IF direta, FAN, anti-dsDNA e função renal.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'porphyria-cutanea-tarda',
    name: 'Porfiria cutânea tardia / pseudoporfiria',
    patterns: ['subepidermal-blister', 'deposition'],
    clinical: ['hands', 'photoexposed', 'bulla', 'atrophy', 'liver', 'renal', 'drug', 'male', 'chronic', 'sun', 'photosensitive'],
    histology: ['subepidermal-cell-poor', 'festooning', 'bmz-thickening', 'solar-elastosis', 'sparse-infiltrate', 'sclerosis'],
    hallmarks: ['festooning', 'subepidermal-cell-poor'],
    against: ['eosinophils', 'neutrophils-dermis', 'dif-granular-iga'],
    frequency: 1,
    summary: 'Bolhas e erosões que deixam milia e cicatriz no dorso das mãos, com fragilidade e hipertricose malar, em hepatopata ou etilista (PCT) ou em dialítico ou usuário de AINE (pseudoporfiria); bolha subepidérmica sem inflamação com papilas dérmicas que se projetam no assoalho (festonamento), paredes vasculares hialinas PAS+ e corpos em lagarta no teto.',
    clues: ['Bolha "vazia" com festonamento das papilas e vasos de parede espessa hialina; a IF mostra IgG e C3 nas paredes vasculares e na ZMB.', 'Pseudoporfiria é idêntica: separa pela porfirina urinária.'],
    mimics: ['EBA: IgG linear na ZMB sem depósito vascular, sem festonamento típico.', 'Penfigoide bolhoso: eosinófilos.', 'Bolha diabética: acral, sem festonamento.', 'Bolha por fricção / coma: história.'],
    next: ['Porfirinas urinárias e plasmáticas; ferritina, hepatite C, HIV; revisar naproxeno, furosemida, tetraciclinas e diálise.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'herpes-simplex-zoster',
    name: 'Herpes simples / varicela-zóster',
    patterns: ['intraepidermal-blister', 'interface-vacuolar'],
    clinical: ['vesicle', 'acute', 'pain', 'dermatomal', 'mucosa', 'genital', 'relapsing', 'immunosuppression', 'ulcer', 'elderly'],
    histology: ['ballooning', 'viral-inclusions', 'acantholysis', 'intraepidermal-blister', 'necrotic-keratinocytes', 'neutrophils-dermis', 'lymphocytic-vasculitis', 'folliculitis-lymphocytic', 'superficial-and-deep'],
    hallmarks: ['ballooning', 'viral-inclusions'],
    frequency: 3,
    summary: 'Vesículas agrupadas sobre eritema, recorrentes (simples) ou em dermatômero doloroso (zóster); degeneração balonizante e reticular com queratinócitos multinucleados de núcleos moldados em vidro fosco (Cowdry A), acantólise secundária e necrose, muitas vezes no folículo.',
    clues: [
      'Os três M: multinucleação, moldagem nuclear e margeamento da cromatina; procurar na borda da vesícula ou no epitélio folicular quando a vesícula já rompeu.',
      'Zóster tem infiltrado mais profundo com vasculite linfocitária e neurite; lesões antigas ficam só com foliculite.',
      'Úlcera crônica em imunossuprimido pode ser herpes sem vesícula: IHQ HSV/VZV.',
    ],
    mimics: ['Pênfigo vulgar: acantólise sem multinucleação, IF.', 'Enteroviroses (mão-pé-boca): balonização sem multinucleação, sem inclusões.', 'Eritema multiforme: sem balonização.', 'Impetigo: subcórnea, cocos.'],
    next: ['IHQ para HSV-1/2 e VZV, ou PCR; Tzanck à beira do leito.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'hand-foot-mouth',
    name: 'Doença mão-pé-boca e outras enteroviroses',
    aka: ['Coxsackie'],
    patterns: ['intraepidermal-blister', 'interface-vacuolar'],
    clinical: ['child', 'acute', 'acral', 'mucosa', 'vesicle', 'fever', 'infection', 'genital'],
    histology: ['ballooning', 'intraepidermal-blister', 'necrotic-keratinocytes', 'vacuolar', 'spongiosis', 'papillary-edema', 'lymphocytic-superficial'],
    hallmarks: ['ballooning'],
    against: ['viral-inclusions', 'eosinophils'],
    frequency: 2,
    summary: 'Vesículas ovais em palmas, plantas e boca de criança com febre; vesícula intraepidérmica por degeneração reticular e balonizante sem multinucleação nem inclusões, com necrose de queratinócitos e edema papilar.',
    clues: ['Balonização sem os três M do herpes; infiltrado linfocitário perivascular com exocitose.', 'Coxsackie A6: forma atípica extensa no adulto, com eczema herpético-símile e onicomadese.'],
    mimics: ['Herpes: multinucleação e inclusões; IHQ.', 'Eritema multiforme: sem vesícula intraepidérmica reticular.', 'Eczema disidrótico: espongiose, sem necrose.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'impetigo',
    name: 'Impetigo / impetigo bolhoso',
    patterns: ['intraepidermal-blister', 'neutrophilic'],
    clinical: ['child', 'acute', 'face', 'flaccid-bulla', 'pustule', 'infection', 'atopy'],
    histology: ['subcorneal-pustule', 'bacteria', 'crust', 'exocytosis-neutrophils', 'acantholysis', 'neutrophils-dermis', 'spongiosis'],
    hallmarks: ['subcorneal-pustule', 'bacteria'],
    against: ['dif-intercellular', 'eosinophils'],
    frequency: 3,
    summary: 'Crostas melicéricas periorais ou bolhas flácidas em criança; pústula subcórnea com neutrófilos e cocos Gram-positivos, crosta de serosidade, neutrófilos e bactérias, e acantólise superficial na forma bolhosa (toxina esfoliativa).',
    clues: ['Cocos visíveis na crosta e na pústula ao Gram; acantólise da granulosa idêntica à do pênfigo foliáceo mas com bactérias e IF negativa.', 'Impetiginização secundária de eczema, escabiose e herpes é mais comum que o impetigo primário.'],
    mimics: ['Pênfigo foliáceo: IF positiva, sem bactérias.', 'Pustulose subcórnea: sem bactérias, crônica.', 'SSSS: fenda na granulosa sem bactérias na pele (toxina a distância).', 'Candidíase: leveduras.'],
    next: ['Gram e cultura.'],
    sources: [WEEDON],
  },
  {
    id: 'sssss',
    name: 'Síndrome da pele escaldada estafilocócica',
    aka: ['SSSS', 'Doença de Ritter'],
    patterns: ['intraepidermal-blister'],
    clinical: ['child', 'acute', 'fever', 'flaccid-bulla', 'generalized', 'flexural', 'face', 'pain', 'renal', 'infection'],
    histology: ['intraepidermal-blister', 'acantholysis', 'sparse-infiltrate', 'subcorneal-pustule'],
    hallmarks: ['intraepidermal-blister'],
    against: ['full-thickness-necrosis', 'necrotic-keratinocytes', 'bacteria', 'eosinophils'],
    frequency: 1,
    summary: 'Eritema doloroso e descolamento superficial em lactente febril, poupando mucosas (toxina esfoliativa a distância); fenda na camada granulosa com células acantolíticas escassas e quase nenhuma inflamação, sem bactérias na pele e sem necrose.',
    clues: ['Fenda alta, teto fino de córnea e granulosa, epiderme abaixo viável: congelação do teto separa de NET em minutos.', 'Sem bactérias na lesão: o foco é a distância (nariz, umbigo, conjuntiva).'],
    mimics: ['NET: necrose de espessura total, mucosas acometidas, fármaco, adulto.', 'Impetigo bolhoso: bactérias na lesão, localizado.', 'Pênfigo foliáceo: IF positiva.', 'Queimadura: história.'],
    next: ['Congelação do teto da bolha; cultura de nariz, conjuntiva e umbigo.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'agep',
    name: 'Pustulose exantemática generalizada aguda',
    aka: ['PEGA', 'AGEP'],
    patterns: ['intraepidermal-blister', 'neutrophilic'],
    clinical: ['drug', 'acute', 'fever', 'pustule', 'flexural', 'face', 'generalized', 'trunk'],
    histology: ['subcorneal-pustule', 'kogoj', 'papillary-edema', 'eosinophils', 'necrotic-keratinocytes', 'neutrophils-dermis', 'lcv', 'spongiosis'],
    hallmarks: ['subcorneal-pustule', 'eosinophils'],
    against: ['acanthosis-regular', 'hyphae', 'bacteria', 'acantholysis'],
    frequency: 2,
    summary: 'Centenas de pústulas estéreis não foliculares sobre eritema edematoso das dobras, 1 a 3 dias após antibiótico (betalactâmico, macrolídeo) ou antimalárico, com febre e neutrofilia; pústulas subcórneas e intraepidérmicas com edema papilar, eosinófilos e queratinócitos necróticos, sem acantose psoriasiforme.',
    clues: ['Pústula subcórnea com eosinófilos e necrose de queratinócitos, sem a epiderme psoriasiforme: fármaco.', 'Edema papilar marcado e vasculite leucocitoclástica focal ocorrem.'],
    mimics: ['Psoríase pustulosa generalizada: acantose psoriasiforme, sem eosinófilos, história de psoríase, curso mais longo.', 'Pustulose subcórnea: crônica, sem eosinófilos.', 'Candidíase / impetigo: organismos.', 'DRESS pustuloso: início mais tardio, hepatite.'],
    next: ['Cronologia do fármaco (horas a poucos dias); PAS e Gram negativos.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'subcorneal-pustular-dermatosis',
    name: 'Pustulose subcórnea (Sneddon-Wilkinson)',
    patterns: ['intraepidermal-blister', 'neutrophilic'],
    clinical: ['flexural', 'trunk', 'pustule', 'annular', 'chronic', 'relapsing', 'female', 'malignancy'],
    histology: ['subcorneal-pustule', 'neutrophils-dermis', 'exocytosis-neutrophils', 'dif-negative', 'sparse-infiltrate'],
    hallmarks: ['subcorneal-pustule', 'dif-negative'],
    against: ['kogoj', 'acanthosis-regular', 'eosinophils', 'hyphae', 'bacteria', 'dif-intercellular'],
    frequency: 1,
    summary: 'Pústulas flácidas com nível líquido ("hipópio") em arranjo anular nas dobras e tronco de mulher de meia-idade, em surtos; pústula subcórnea "descolada" sobre epiderme quase normal, sem espongiforme, sem acantólise significativa e IF negativa.',
    clues: ['A pústula parece ter sido colocada em cima de uma epiderme sadia; poucos neutrófilos na espinhosa.', 'Gamopatia IgA em parte dos casos; responde a dapsona.'],
    mimics: ['Pênfigo IgA: idêntico com IgA intercelular.', 'Psoríase pustulosa: espongiforme e psoriasiforme.', 'PEGA: agudo, eosinófilos, fármaco.', 'Pênfigo foliáceo: acantólise, IgG.', 'Impetigo / candidíase: organismos.'],
    next: ['IF direta; eletroforese de proteínas.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'neonatal-pustuloses',
    name: 'Pustuloses neonatais benignas (eritema tóxico, melanose pustulosa transitória, acropustulose infantil)',
    patterns: ['intraepidermal-blister', 'folliculitis'],
    clinical: ['child', 'acute', 'pustule', 'trunk', 'acral', 'asymptomatic', 'relapsing'],
    histology: ['subcorneal-pustule', 'folliculitis-neutrophilic', 'eosinophils', 'neutrophils-dermis', 'intraepidermal-blister'],
    against: ['bacteria', 'hyphae', 'ballooning', 'mite'],
    frequency: 2,
    summary: 'Pústulas em recém-nascido ou lactente sadio; eritema tóxico dá pústula folicular cheia de eosinófilos, melanose pustulosa transitória dá pústula subcórnea de neutrófilos com mácula pigmentada residual, e acropustulose infantil dá pústulas acrais recorrentes de neutrófilos (às vezes pós-escabiose).',
    clues: ['O tipo de célula (eosinófilo x neutrófilo) e o centro folicular ou não separam as três; o Tzanck faz o mesmo sem biópsia.', 'Todas são estéreis: Gram, PAS e pesquisa de ácaro negativos.'],
    mimics: ['Impetigo / candidíase neonatal: organismos.', 'Herpes neonatal: multinucleação, emergência.', 'Escabiose: ácaro; a acropustulose pode seguir escabiose tratada.', 'Foliculite pustulosa eosinofílica infantil: couro cabeludo, eosinofilia, recorrente.'],
    next: ['Tzanck com Gram e KOH.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'bullosis-diabeticorum',
    name: 'Bolha diabética e bolhas por fricção, coma ou edema',
    aka: ['Bullosis diabeticorum', 'Bolha de coma', 'Bolha de edema'],
    patterns: ['subepidermal-blister', 'intraepidermal-blister'],
    clinical: ['diabetes', 'acral', 'legs', 'bulla', 'acute', 'asymptomatic', 'trauma', 'renal', 'elderly'],
    histology: ['subepidermal-cell-poor', 'intraepidermal-blister', 'sparse-infiltrate', 'dif-negative', 'eccrine-neutrophils', 'papillary-edema'],
    hallmarks: ['subepidermal-cell-poor', 'dif-negative'],
    against: ['eosinophils', 'festooning', 'dif-linear-bmz'],
    frequency: 2,
    summary: 'Bolha tensa grande e indolor de aparecimento súbito em pé ou perna de diabético, ou em área de pressão após coma ou intoxicação; bolha subepidérmica (ou intraepidérmica alta) sem inflamação e sem festonamento, IF negativa; a bolha de coma tem necrose de glândulas écrinas.',
    clues: ['Bolha "vazia" com IF negativa em diabético: exclusão de porfiria (festonamento, IF vascular) e EBA.', 'Necrose de glândula sudorípara é a marca da bolha de coma ou de pressão.'],
    mimics: ['Porfiria / pseudoporfiria: festonamento, vasos hialinos, IF vascular.', 'EBA: IgG linear.', 'Penfigoide: eosinófilos.', 'Bolha por trauma térmico: necrose epidérmica.'],
    next: ['IF direta negativa; porfirinas se houver dúvida.'],
    sources: [WEEDON],
  },
]
