/* ==========================================================================
   content/deposition.ts — dermatoses "invisíveis" e de depósito: as que
   parecem pele normal em pequeno aumento (vitiligo, pitiríase versicolor,
   amiloidose macular, pigmentações) e as de depósito (amiloide, cálcio,
   urato, mucina reticular, perfurantes).
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const ACKERMAN = 'Ackerman: Histologic Diagnosis of Inflammatory Skin Diseases, 3ª ed. (2005)'
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'

export const deposition: Diagnosis[] = [
  {
    id: 'vitiligo',
    name: 'Vitiligo',
    patterns: ['invisible', 'interface-vacuolar'],
    clinical: ['hypopigmented', 'macule', 'acral', 'face', 'genital', 'chronic', 'thyroid', 'autoimmune', 'asymptomatic', 'linear', 'family'],
    histology: ['sparse-infiltrate', 'vacuolar', 'lymphocytic-superficial', 'pigment-incontinence'],
    against: ['hyphae', 'atrophy-epidermis', 'band-like', 'homogenized-papillary'],
    frequency: 3,
    summary: 'Máculas acrômicas de bordas nítidas em face, mãos e genitais; epiderme sem melanócitos e sem melanina no centro, com linfócitos na junção e vacuolização de basais na borda ativa. A lâmina de HE parece normal: pedir Melan-A ou SOX10 e Fontana-Masson e comparar com a borda.',
    clues: ['Ausência de melanócitos na basal confirmada por IHQ; a borda inflamatória tem linfócitos CD8+ na junção.', 'Comparar com pele pigmentada adjacente na mesma lâmina sempre que possível.'],
    mimics: ['Pitiríase versicolor: leveduras e hifas curtas na córnea, melanócitos presentes.', 'Líquen escleroso: homogeneização papilar e atrofia.', 'Hipopigmentação pós-inflamatória: melanócitos presentes, menos melanina.', 'Micose fungoide hipopigmentada: epidermotropismo e atipia, CD8+.', 'Hanseníase indeterminada: infiltrado perineural discreto; Fite.'],
    next: ['Melan-A ou SOX10 e Fontana-Masson; PAS para excluir versicolor.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'pityriasis-versicolor',
    name: 'Pitiríase versicolor',
    aka: ['Tinea versicolor'],
    patterns: ['invisible'],
    clinical: ['trunk', 'hypopigmented', 'hyperpigmented', 'macule', 'young-adult', 'chronic', 'relapsing', 'asymptomatic', 'scaly-plaque'],
    histology: ['hyphae', 'pas-positive', 'sparse-infiltrate', 'orthokeratosis-compact'],
    hallmarks: ['hyphae', 'pas-positive'],
    frequency: 3,
    summary: 'Manchas descamativas hipo ou hipercrômicas confluentes no tronco superior; córnea com leveduras redondas e hifas curtas e tortuosas ("espaguete com almôndegas") sem inflamação, visíveis ao HE e óbvias ao PAS.',
    clues: ['Epiderme e derme normais: se a biópsia de mancha do tronco parecer normal, olhar a córnea com PAS.', 'Foliculite por Malassezia é a forma folicular do mesmo organismo.'],
    mimics: ['Vitiligo: sem organismo, sem melanócitos.', 'Dermatofitose: hifas longas septadas com inflamação.', 'Papilomatose confluente e reticulada: papilomatose, sem fungo.', 'Hipopigmentação pós-inflamatória: sem fungo.'],
    next: ['PAS.'],
    sources: [WEEDON],
  },
  {
    id: 'postinflammatory-pigmentation',
    name: 'Hiper e hipopigmentação pós-inflamatória / melasma',
    patterns: ['invisible'],
    clinical: ['hyperpigmented', 'hypopigmented', 'macule', 'face', 'chronic', 'asymptomatic', 'female', 'sun', 'pregnancy', 'drug'],
    histology: ['pigment-incontinence', 'sparse-infiltrate', 'solar-elastosis', 'mast-cells'],
    hallmarks: ['pigment-incontinence'],
    against: ['vacuolar', 'necrotic-keratinocytes', 'hyphae', 'amyloid'],
    frequency: 3,
    summary: 'Manchas acastanhadas que seguem uma dermatose prévia (ou o melasma centrofacial na gestação e no anticoncepcional); epiderme com melanina basal aumentada ou diminuída e melanófagos na derme papilar, sem inflamação ativa. Pigmentação por fármaco (minociclina, amiodarona, antimaláricos) mostra pigmento marrom-acinzentado em macrófagos dérmicos.',
    clues: ['Melanófagos sem dano de interface ativo; no melasma há elastose e mastócitos aumentados.', 'Minociclina: pigmento que cora com Perls (tipo I) ou Fontana (tipo II); antimaláricos: pigmento amarelo-marrom que cora com ambos.'],
    mimics: ['Eritema discrômico perstante: interface ativa contínua.', 'Amiloidose macular: material hialino nas papilas, vermelho Congo.', 'Erupção fixa por fármaco: interface com necrose e eosinófilos na fase ativa.', 'Ocronose exógena: fibras "em banana" ocre por hidroquinona.'],
    next: ['Fontana-Masson e Perls quando a origem do pigmento for dúvida.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'cutaneous-amyloidosis',
    name: 'Amiloidose cutânea (macular, liquenoide, nodular)',
    aka: ['Líquen amiloide', 'Amiloidose macular', 'Amiloidose nodular'],
    patterns: ['deposition', 'invisible', 'psoriasiform'],
    clinical: ['itch', 'hyperpigmented', 'papule', 'extensor', 'legs', 'trunk', 'chronic', 'nodule', 'malignancy', 'asymptomatic', 'lichenified'],
    histology: ['amyloid', 'pigment-incontinence', 'acanthosis-irregular', 'hypergranulosis', 'sparse-infiltrate', 'plasma-cells', 'diffuse-dermal-infiltrate'],
    hallmarks: ['amyloid'],
    frequency: 2,
    summary: 'Manchas ondulantes acastanhadas interescapulares (macular) ou pápulas pruriginosas pré-tibiais (liquenoide), ambas por queratina derivada da coçadura; ou nódulo céreo com amiloide AL (nodular, com plasmócitos e risco de mieloma). Glóbulos eosinofílicos homogêneos nas papilas dérmicas com melanófagos, ou massas amorfas que ocupam a derme e vasos.',
    clues: ['Glóbulos hialinos róseos "em grumos" nas papilas, com pigmento: fáceis de perder se não procurados; vermelho Congo com birrefringência verde ou cristal violeta; IHQ para queratina marca o amiloide macular e liquenoide.', 'Nodular: amiloide em toda a derme e em vasos e anexos, com plasmócitos; investigar amiloidose sistêmica AL.'],
    mimics: ['Hialinose (lipoidoproteinose): material hialino ao redor de vasos e anexos, PAS+, Congo negativo.', 'Milium coloide: papilas com material fissurado, fotoexposta, Congo fraco.', 'Líquen simples crônico: sem glóbulos.', 'Hiperpigmentação pós-inflamatória: só melanófagos.'],
    next: ['Vermelho Congo ou tioflavina T; nodular: eletroforese e imunofixação, gordura abdominal.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'colloid-milium',
    name: 'Milium coloide',
    patterns: ['deposition'],
    clinical: ['photoexposed', 'face', 'hands', 'papule', 'elderly', 'chronic', 'asymptomatic', 'sun', 'contact'],
    histology: ['amyloid', 'solar-elastosis', 'sparse-infiltrate', 'atrophy-epidermis'],
    hallmarks: ['amyloid', 'solar-elastosis'],
    frequency: 1,
    summary: 'Pápulas amareladas translúcidas em face e dorso das mãos de trabalhador ao ar livre; papilas dérmicas expandidas por material eosinofílico homogêneo e fissurado, separado da epiderme por zona de Grenz fina e da elastose solar abaixo.',
    clues: ['Material coloide fendido em blocos nas papilas, sem plasmócitos, com elastose solar intensa por baixo.', 'Vermelho Congo fraco ou negativo; forma juvenil familiar tem depósito derivado de queratina.'],
    mimics: ['Amiloidose nodular: Congo forte, plasmócitos, vasos acometidos.', 'Lipoidoproteinose: perivascular e perianexial, PAS+.', 'Ceratose actínica hipertrófica com elastose: atipia epidérmica.'],
    sources: [WEEDON],
  },
  {
    id: 'reticular-erythematous-mucinosis',
    name: 'Mucinose eritematosa reticular',
    aka: ['REM', 'Mucinose em placa'],
    patterns: ['deposition', 'perivascular-deep'],
    clinical: ['trunk', 'female', 'young-adult', 'macule', 'annular', 'chronic', 'photosensitive', 'asymptomatic'],
    histology: ['mucin', 'lymphocytic-superficial', 'superficial-and-deep', 'periadnexal', 'sparse-infiltrate'],
    hallmarks: ['mucin'],
    against: ['vacuolar', 'atrophy-epidermis'],
    frequency: 1,
    summary: 'Eritema reticulado no centro do tórax ou dorso de mulher jovem, piorado pelo sol; mucina na derme superior e média com infiltrado linfocitário perivascular e perifolicular discreto, sem alteração epidérmica. Provável espectro do lúpus túmido.',
    clues: ['Mucina abundante com pouca inflamação em pele de tronco central: alcian blue.', 'Responde a antimaláricos.'],
    mimics: ['Lúpus túmido: infiltrado mais denso e profundo; talvez a mesma doença.', 'Mixedema pré-tibial: pernas, tireoide.', 'Granuloma anular intersticial: histiócitos.', 'Eritema anular centrífugo: sem mucina.'],
    next: ['Alcian blue; FAN.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'perforating-dermatoses',
    name: 'Dermatoses perforantes (colagenose perforante reativa, elastose perfurante serpiginosa, Kyrle)',
    aka: ['Dermatose perforante adquirida'],
    patterns: ['deposition', 'psoriasiform'],
    clinical: ['renal', 'diabetes', 'itch', 'papule', 'extensor', 'legs', 'chronic', 'annular', 'child', 'drug', 'family'],
    histology: ['transepidermal-elimination', 'acanthosis-irregular', 'crust', 'necrobiosis', 'elastophagocytosis', 'neutrophils-dermis', 'foreign-body-giant-cells', 'follicular-plug'],
    hallmarks: ['transepidermal-elimination'],
    frequency: 2,
    summary: 'Pápulas umbilicadas com rolha ceratósica central em pernas e extensores de diabético renal pruriginoso (forma adquirida), ou pápulas em arco no pescoço de jovem (elastose serpiginosa, ligada a penicilamina e Down); canal epidérmico em taça cheio de queratina, colágeno degenerado ou fibras elásticas em eliminação transepidérmica, com neutrófilos e reação granulomatosa.',
    clues: ['Identificar o que está sendo eliminado: colágeno (tricrômico) na colagenose reativa, elástica (orceína) na serpiginosa, queratina e restos na de Kyrle.', 'Coçadura crônica é o gatilho na forma adquirida; muitas vezes coexiste prurigo nodular.'],
    mimics: ['Prurigo nodular: hiperplasia sem canal de eliminação.', 'Foliculite perfurante: centrada em folículo com pelo enrolado.', 'Granuloma anular perforante: paliçada com mucina eliminada.', 'Ceratoacantoma: cratera com lábios e atipia.'],
    next: ['Tricrômico e orceína no material eliminado; creatinina e glicemia.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'calcinosis-cutis',
    name: 'Calcinose cutânea',
    aka: ['Calcinose distrófica / metastática / idiopática', 'Nódulo calcificado subepidérmico'],
    patterns: ['deposition'],
    clinical: ['nodule', 'papule', 'autoimmune', 'renal', 'trauma', 'child', 'chronic', 'ulcer', 'acral', 'asymptomatic'],
    histology: ['calcification', 'foreign-body-giant-cells', 'sclerosis', 'transepidermal-elimination', 'sparse-infiltrate'],
    hallmarks: ['calcification'],
    frequency: 2,
    summary: 'Nódulos duros que eliminam material gessado, em dermatomiosite, esclerose sistêmica ou cicatrizes (distrófica), em doença renal com produto cálcio-fósforo alto (metastática), no escroto ou como nódulo solitário de criança (idiopática); depósitos basofílicos granulares ou em massas na derme e subcutâneo, com reação de células gigantes e fibrose.',
    clues: ['Cálcio basofílico ao HE, negro ao von Kossa; procurar a lesão de base (cisto, pilomatricoma, colagenose, veias) ao redor.', 'Osteoma cutâneo tem osso lamelar com osteócitos, não só cálcio.'],
    mimics: ['Calcifilaxia: cálcio na parede de arteríolas com trombose e necrose.', 'Gota: urato em agulhas com material amorfo e células gigantes; fixar em álcool para preservar cristais.', 'Pilomatricoma: células fantasma basaloides ao redor.', 'Osteoma cutâneo: osso.'],
    next: ['von Kossa; cálcio, fósforo, PTH e a doença de base.'],
    sources: [WEEDON],
  },
  {
    id: 'gout',
    name: 'Tofo gotoso',
    patterns: ['deposition', 'granulomatous'],
    clinical: ['nodule', 'male', 'elderly', 'acral', 'extensor', 'arthralgia', 'renal', 'chronic', 'ulcer', 'drug'],
    histology: ['foreign-body-giant-cells', 'palisaded-granuloma', 'needle-clefts', 'sclerosis', 'calcification'],
    hallmarks: ['needle-clefts', 'palisaded-granuloma'],
    against: ['mucin'],
    frequency: 2,
    summary: 'Nódulos brancacentos sobre hélices, cotovelos e dedos de homem com gota, que drenam material giz; massas amorfas eosinofílicas ou acastanhadas com fendas em agulha radiais (cristais dissolvidos pela formalina), cercadas por paliçada de histiócitos e células gigantes e fibrose.',
    clues: ['Material amorfo com agulhas "fantasma" e paliçada: em tecido fixado em álcool, cristais birrefringentes negativos à luz polarizada.', 'Diferencial mais comum: nódulo reumatoide e granuloma anular profundo.'],
    mimics: ['Nódulo reumatoide: fibrina sem agulhas.', 'Granuloma anular subcutâneo: mucina.', 'Calcinose: basofílica, von Kossa.', 'Xantoma: histiócitos espumosos.'],
    next: ['Fixação em álcool absoluto para polarizar; ácido úrico sérico.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'ichthyosis-xerosis',
    name: 'Ictiose vulgar e xerose / eczema asteatósico',
    aka: ['Ictiose vulgar', 'Eczema craquelé'],
    patterns: ['invisible', 'spongiotic'],
    clinical: ['extensor', 'legs', 'scaly-plaque', 'itch', 'chronic', 'elderly', 'atopy', 'family', 'child', 'asymptomatic'],
    histology: ['orthokeratosis-compact', 'hypogranulosis', 'sparse-infiltrate', 'spongiosis', 'parakeratosis-focal', 'lymphocytic-superficial'],
    hallmarks: ['hypogranulosis', 'orthokeratosis-compact'],
    against: ['neutrophils-corneum', 'eosinophils', 'band-like'],
    frequency: 3,
    summary: 'Escamas finas aderentes em extensores desde a infância com hiperlinearidade palmar (ictiose vulgar, filagrina) ou pele seca com fissuras em "leito de rio" nas pernas de idoso no inverno (eczema asteatósico); hiperceratose ortoceratósica compacta com camada granulosa reduzida ou ausente e epiderme por outro lado normal, mais espongiose leve na forma eczematosa.',
    clues: ['Ortoceratose sem granulosa em lâmina "normal": ictiose vulgar; a ictiose ligada ao X tem granulosa normal.', 'O eczema asteatósico acrescenta espongiose discreta e infiltrado escasso.'],
    mimics: ['Ictiose adquirida: mesma lâmina em adulto com linfoma, HIV ou fármaco.', 'Dermatite atópica crônica: acantose, fibrose papilar.', 'Pitiríase versicolor: fungo.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'invisible-dermatosis-pitfalls',
    name: 'Lâmina "normal": lista de verificação',
    aka: ['Dermatose invisível'],
    patterns: ['invisible'],
    clinical: ['itch', 'macule', 'asymptomatic', 'generalized', 'chronic'],
    histology: ['sparse-infiltrate', 'mast-cells', 'hyphae', 'pigment-incontinence', 'amyloid', 'orthokeratosis-compact', 'hypogranulosis', 'mucin', 'epidermotropism'],
    frequency: 2,
    summary: 'Biópsia de lesão clínica real com histologia aparentemente normal: percorrer a lista antes de assinar "sem alterações significativas". Córnea: fungo (versicolor), ácaro, ortoceratose sem granulosa (ictiose). Epiderme: melanócitos ausentes (vitiligo), linfócitos alinhados (micose fungoide), acantólise focal (Grover). Derme: melanófagos (pigmentação), mastócitos (urticária pigmentosa), mucina (mucinose), amiloide nas papilas, eosinófilos intersticiais (urticária, picada), hemossiderina (púrpura pigmentar), elastose ou fibras elásticas ausentes (anetodermia), colágeno em excesso (colagenoma). Anexos: telógenos (eflúvio), miniaturização.',
    clues: ['PAS, Giemsa ou CD117, alcian blue, vermelho Congo, Fontana-Masson, Melan-A e orceína cobrem quase tudo.', 'Sempre perguntar de que lesão veio a biópsia e comparar com a pele normal adjacente.'],
    mimics: ['Pele normal biopsiada fora da lesão: pedir nova amostra.', 'Artefato de tratamento: corticoide tópico apaga a inflamação mas não os fungos nem os melanócitos.'],
    next: ['Colorações especiais dirigidas pela hipótese clínica.'],
    sources: [ACKERMAN, WEEDON],
  },
]
