/* ==========================================================================
   content/fibrosing.ts — dermatoses esclerosantes e fibrosantes: morfeia e
   esclerose sistêmica, fasciíte eosinofílica, fibrose nefrogênica, GVHD
   esclerodermoide, escleredema, mucinoses esclerosantes, queloide,
   radiodermite e lipodermatoesclerose.
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const ACKERMAN = 'Ackerman: Histologic Diagnosis of Inflammatory Skin Diseases, 3ª ed. (2005)'
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'

export const fibrosing: Diagnosis[] = [
  {
    id: 'morphea',
    name: 'Morfeia',
    aka: ['Esclerodermia localizada', 'Morfeia em placa / linear / generalizada / profunda'],
    patterns: ['fibrosing', 'perivascular-deep'],
    clinical: ['sclerosis', 'trunk', 'linear', 'child', 'female', 'chronic', 'hyperpigmented', 'atrophy', 'asymptomatic'],
    histology: ['thick-collagen', 'sclerosis', 'plasma-cells', 'superficial-and-deep', 'septal-fibrosis', 'periadnexal', 'lymphoid-follicles', 'atrophy-epidermis', 'sebaceous-loss'],
    hallmarks: ['thick-collagen', 'plasma-cells'],
    against: ['mucin', 'homogenized-papillary', 'eosinophils'],
    frequency: 2,
    summary: 'Placa endurecida marfim com halo lilás, ou faixa linear em membro de criança; fase inflamatória com infiltrado linfoplasmocitário na derme profunda e nos septos, seguida de colágeno espessado, hialinizado e compactado ("borda em faca") que engole as glândulas écrinas e substitui a gordura periécrina, com perda de anexos.',
    clues: [
      'Écrinas "aprisionadas" no colágeno denso, sem o coxim de gordura ao redor, e feixes colágenos horizontais espessos até o subcutâneo: a biópsia precisa ir fundo.',
      'Plasmócitos na borda inflamatória (alcian negativo, ao contrário do lúpus túmido).',
      'Quadrado da biópsia com borda reta ("sinal do punch quadrado") reflete a rigidez.',
    ],
    mimics: [
      'Esclerose sistêmica: idêntica na lâmina; separa-se por esclerodactilia, Raynaud, anticorpos.',
      'Líquen escleroso: homogeneização papilar com atrofia epidérmica; coexistem.',
      'Fasciíte eosinofílica: fáscia espessada com eosinófilos, pele poupada na superfície.',
      'Fibrose nefrogênica: fibroblastos CD34+ em abundância, diálise.',
      'GVHD esclerodermoide: transplante, interface prévia.',
      'Cicatriz / queloide: história, colágeno em nódulos.',
      'Radiodermite crônica: fibroblastos atípicos, vasos ectásicos.',
    ],
    next: ['Biópsia profunda (até fáscia se morfeia profunda); FAN e anti-Scl-70 conforme clínica.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'systemic-sclerosis',
    name: 'Esclerose sistêmica',
    aka: ['Esclerodermia sistêmica'],
    patterns: ['fibrosing'],
    clinical: ['sclerosis', 'acral', 'hands', 'face', 'female', 'chronic', 'telangiectasia', 'ulcer', 'autoimmune', 'cold', 'hypopigmented'],
    histology: ['thick-collagen', 'sclerosis', 'sebaceous-loss', 'sparse-infiltrate', 'calcification', 'atrophy-epidermis', 'dilated-vessels', 'septal-fibrosis'],
    hallmarks: ['thick-collagen', 'sebaceous-loss'],
    frequency: 1,
    summary: 'Esclerodactilia com Raynaud, telangiectasias e calcinose; derme de colágeno hialinizado e compacto com perda de anexos e de gordura subcutânea, pouca inflamação, vasos de parede espessa e lúmen estreito.',
    clues: ['Igual à morfeia tardia; o que diferencia é sistêmico.', 'Calcinose e "sal e pimenta" (despigmentação com pigmento perifolicular) são pistas clínicas.'],
    mimics: ['Morfeia: localizada, sem Raynaud.', 'Escleredema: mucina entre feixes separados.', 'Escleromixedema: mucina com proliferação de fibroblastos e paraproteína.', 'Fibrose nefrogênica: CD34+, diálise.'],
    next: ['FAN, anti-centrômero, anti-Scl-70, anti-RNA pol III; capilaroscopia.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'eosinophilic-fasciitis',
    name: 'Fasciíte eosinofílica',
    aka: ['Síndrome de Shulman'],
    patterns: ['fibrosing', 'panniculitis-septal'],
    clinical: ['sclerosis', 'legs', 'extensor', 'acute', 'subacute', 'pain', 'trauma', 'male', 'young-adult'],
    histology: ['sclerosis', 'eosinophils', 'plasma-cells', 'septal-fibrosis', 'lymphoid-follicles', 'thick-collagen'],
    hallmarks: ['sclerosis', 'eosinophils'],
    frequency: 1,
    summary: 'Endurecimento doloroso e simétrico dos membros com "sinal do sulco" sobre as veias após exercício intenso, poupando mãos e pés, com eosinofilia; fáscia espessada e hialinizada com infiltrado linfoplasmocitário e eosinófilos que se estende aos septos do subcutâneo e ao músculo.',
    clues: ['A biópsia precisa incluir fáscia (incisional até o músculo); a derme pode estar normal ou pouco fibrosada.', 'Eosinófilos podem faltar na fáscia mesmo com eosinofilia periférica.'],
    mimics: ['Morfeia profunda: mesmo espectro; sem eosinofilia.', 'Esclerose sistêmica: Raynaud, mãos acometidas.', 'Síndrome eosinofilia-mialgia / óleo tóxico: história de exposição.'],
    next: ['Biópsia em bloco pele-fáscia-músculo; hemograma e ressonância.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'nephrogenic-systemic-fibrosis',
    name: 'Fibrose sistêmica nefrogênica',
    patterns: ['fibrosing'],
    clinical: ['renal', 'legs', 'sclerosis', 'subacute', 'chronic', 'pain', 'hyperpigmented', 'drug'],
    histology: ['thick-collagen', 'sclerosis', 'mucin', 'septal-fibrosis', 'calcification', 'sparse-infiltrate', 'foreign-body-giant-cells'],
    hallmarks: ['thick-collagen', 'septal-fibrosis'],
    frequency: 1,
    summary: 'Placas endurecidas e hiperpigmentadas em pernas e antebraços de paciente renal crônico exposto a gadolínio, poupando a face; proliferação de fibroblastos fusiformes CD34+ e procolágeno I+ entre feixes de colágeno espessados, com fibras elásticas preservadas, estendendo-se aos septos, com mucina e às vezes corpos ósseos ou calcificação.',
    clues: ['Celularidade fibroblástica alta (CD34+) sem inflamação, que invade o subcutâneo em septos largos: morfeia é pobre em células.', 'Corpos "lolipop" de colágeno calcificado ou osso metaplásico ocorrem.'],
    mimics: ['Morfeia / esclerose sistêmica: hipocelular, CD34 reduzido.', 'Escleromixedema: paraproteína, sem doença renal, face acometida.', 'Escleredema: mucina sem fibroblastos aumentados.'],
    next: ['CD34; história de gadolínio e função renal.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'sclerodermoid-gvhd',
    name: 'Doença do enxerto contra hospedeiro crônica esclerodermoide',
    patterns: ['fibrosing', 'interface-vacuolar'],
    clinical: ['transplant', 'sclerosis', 'chronic', 'hyperpigmented', 'hypopigmented', 'atrophy', 'trunk', 'generalized'],
    histology: ['thick-collagen', 'sclerosis', 'atrophy-epidermis', 'vacuolar', 'sebaceous-loss', 'homogenized-papillary', 'pigment-incontinence', 'sparse-infiltrate', 'septal-fibrosis'],
    hallmarks: ['thick-collagen', 'vacuolar'],
    frequency: 1,
    summary: 'Esclerose cutânea progressiva meses a anos após transplante de medula, com contraturas e poiquilodermia; esclerose dérmica com atrofia epidérmica, interface vacuolar residual e perda de anexos, às vezes com padrão de líquen escleroso superficial ou fasciíte.',
    clues: ['Esclerose + interface (ainda que discreta) + transplante.', 'Formas de líquen escleroso-símile, morfeia-símile e fasciíte-símile podem coexistir no mesmo paciente.'],
    mimics: ['Morfeia: sem interface, sem transplante.', 'Líquen escleroso: sem transplante.', 'Esclerose sistêmica: Raynaud e anticorpos.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'scleredema',
    name: 'Escleredema',
    aka: ['Escleredema de Buschke', 'Escleredema diabeticorum'],
    patterns: ['fibrosing', 'deposition'],
    clinical: ['trunk', 'sclerosis', 'diabetes', 'infection', 'malignancy', 'chronic', 'male', 'asymptomatic', 'child'],
    histology: ['thick-collagen', 'mucin', 'sparse-infiltrate', 'sebaceous-loss'],
    hallmarks: ['thick-collagen', 'mucin'],
    against: ['plasma-cells', 'eosinophils', 'homogenized-papillary'],
    frequency: 1,
    summary: 'Endurecimento lenhoso da nuca e dorso superior em diabético obeso, após infecção estreptocócica em criança, ou com gamopatia; derme reticular muito espessada por feixes de colágeno grossos separados por espaços claros que contêm mucina (alcian blue), sem inflamação e sem aumento de fibroblastos.',
    clues: ['Feixes colágenos "afastados" por fendas de mucina numa derme três vezes mais espessa; anexos preservados mas afastados.', 'A mucina pode ser escassa: comparar com pele normal e usar fixação sem excesso.'],
    mimics: ['Escleromixedema: pápulas, muita mucina com fibroblastos aumentados, paraproteína.', 'Morfeia: colágeno compactado sem fendas, plasmócitos.', 'Esclerose sistêmica: sem mucina.'],
    next: ['Alcian blue ou coloide-ferro; glicemia e eletroforese de proteínas.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'scleromyxedema',
    name: 'Escleromixedema / líquen mixedematoso',
    aka: ['Mucinose papular'],
    patterns: ['deposition', 'fibrosing'],
    clinical: ['papule', 'face', 'hands', 'sclerosis', 'chronic', 'malignancy', 'elderly', 'linear'],
    histology: ['mucin', 'thick-collagen', 'sparse-infiltrate', 'sclerosis'],
    hallmarks: ['mucin'],
    frequency: 1,
    summary: 'Pápulas céreas alinhadas em face, orelhas e mãos com endurecimento difuso e paraproteína IgG lambda; mucina abundante na derme superior e média com proliferação de fibroblastos e colágeno irregular (tríade), com anexos preservados.',
    clues: ['Mucina + fibroblastos aumentados + fibrose na derme papilar e reticular superior; o líquen mixedematoso localizado tem só mucina e fibroblastos sem esclerose nem paraproteína.', 'Glabela com sulcos (fácies leonina) e sinal do "donut" nas articulações.'],
    mimics: ['Escleredema: feixes afastados sem fibroblastos aumentados.', 'Mixedema pré-tibial: mucina sem fibrose, tireoidopatia.', 'Fibrose nefrogênica: renal.', 'Granuloma anular intersticial: histiócitos.'],
    next: ['Eletroforese e imunofixação; TSH para separar do mixedema.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'pretibial-myxedema',
    name: 'Mixedema pré-tibial',
    aka: ['Dermopatia tireoidiana'],
    patterns: ['deposition'],
    clinical: ['legs', 'thyroid', 'nodule', 'sclerosis', 'chronic', 'asymptomatic', 'female'],
    histology: ['mucin', 'sparse-infiltrate', 'thick-collagen', 'mast-cells'],
    hallmarks: ['mucin'],
    against: ['plasma-cells', 'necrobiosis'],
    frequency: 1,
    summary: 'Placas e nódulos em casca de laranja na região pré-tibial de paciente com doença de Graves (oftalmopatia); mucina abundante em toda a derme reticular separando feixes de colágeno afinados, sem aumento de fibroblastos e sem inflamação, com epiderme às vezes hiperceratótica.',
    clues: ['Mucina por toda a derme reticular com pouca celularidade e zona de Grenz poupada.', 'Aparece anos após o tratamento do hipertireoidismo; TRAb alto.'],
    mimics: ['Escleromixedema: fibroblastos aumentados, paraproteína.', 'Mucinose focal / cisto mixoide: lesão única.', 'Lipodermatoesclerose: paniculite, estase.', 'Necrobiose lipoídica: histiócitos e necrobiose.'],
    next: ['Alcian blue; TSH e TRAb.'],
    sources: [WEEDON],
  },
  {
    id: 'keloid-hypertrophic-scar',
    name: 'Queloide e cicatriz hipertrófica',
    patterns: ['fibrosing'],
    clinical: ['trauma', 'nodule', 'chronic', 'itch', 'pain', 'young-adult', 'trunk', 'family'],
    histology: ['sclerosis', 'thick-collagen', 'sparse-infiltrate', 'sebaceous-loss', 'dilated-vessels', 'mast-cells'],
    hallmarks: ['sclerosis'],
    frequency: 3,
    summary: 'Nódulo firme que cresce além dos limites da ferida (queloide) ou fica restrito a ela e regride (hipertrófica), em tórax, ombros e lóbulos de orelha; feixes de colágeno hialinizados, grossos, vítreos e desorganizados no queloide, ou nódulos fibroblásticos com vasos verticais na cicatriz hipertrófica, sem anexos.',
    clues: ['Colágeno "queloidal": feixes largos, eosinofílicos e brilhantes, em arranjo caótico, com fibroblastos escassos.', 'Cicatriz hipertrófica: fibroblastos em nódulos e vasos perpendiculares à epiderme, colágeno fino.'],
    mimics: ['Dermatofibroma: histiócitos, hiperplasia epidérmica, "aprisiona" colágeno na periferia.', 'Dermatofibrossarcoma protuberans: CD34+, infiltra gordura em favo de mel.', 'Morfeia: colágeno compactado com anexos aprisionados, sem colágeno queloidal.', 'Colagenoma / fibroma: colágeno normal em excesso.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'radiation-dermatitis',
    name: 'Radiodermite',
    patterns: ['fibrosing', 'interface-vacuolar'],
    clinical: ['malignancy', 'atrophy', 'telangiectasia', 'sclerosis', 'ulcer', 'chronic', 'acute', 'hyperpigmented', 'hypopigmented'],
    histology: ['sclerosis', 'dilated-vessels', 'atrophy-epidermis', 'vacuolar', 'necrotic-keratinocytes', 'sebaceous-loss', 'thrombi', 'thick-collagen'],
    hallmarks: ['sclerosis', 'dilated-vessels'],
    frequency: 2,
    summary: 'Eritema e descamação no campo irradiado (aguda) ou placa atrófica, esclerosada e telangiectásica que ulcera anos depois (crônica); interface com queratinócitos necróticos e edema na fase aguda; esclerose dérmica com fibroblastos estrelados atípicos, vasos ectásicos de parede hialina e perda de anexos na crônica.',
    clues: ['Fibroblastos grandes, hipercromáticos e bizarros ("fibroblastos de radiação") em derme esclerótica com telangiectasias: história de radioterapia fecha.', 'Ulceração crônica com pouca inflamação e endarterite obliterante.'],
    mimics: ['Morfeia: sem atipia fibroblástica, sem telangiectasias.', 'Angiossarcoma pós-radioterapia: proliferação vascular atípica, MYC+; sempre examinar os vasos.', 'Líquen escleroso: homogeneização papilar.', 'Carcinoma sobre radiodermite: atipia epitelial.'],
    next: ['Marcar campo de radioterapia e data; MYC ou ERG se vasos suspeitos.'],
    sources: [WEEDON],
  },
  {
    id: 'lipodermatosclerosis',
    name: 'Lipodermatoesclerose',
    aka: ['Paniculite esclerosante', 'Hipodermite'],
    patterns: ['panniculitis-lobular', 'fibrosing'],
    clinical: ['legs', 'venous', 'elderly', 'female', 'sclerosis', 'pain', 'chronic', 'hyperpigmented', 'ulcer', 'acute'],
    histology: ['lipomembranous', 'septal-fibrosis', 'fat-necrosis', 'sclerosis', 'rbc-extravasation', 'dilated-vessels', 'lobular-panniculitis', 'sparse-infiltrate'],
    hallmarks: ['lipomembranous', 'septal-fibrosis'],
    frequency: 3,
    summary: 'Endurecimento em "garrafa invertida" do terço inferior da perna com hiperpigmentação e estase; paniculite lobular pouco inflamatória com necrose gordurosa isquêmica, alteração lipomembranosa (membranas eosinofílicas festonadas e pseudocistos), septos fibrosados e derme com estase.',
    clues: ['Alteração lipomembranosa: membranas PAS+ pregueadas revestindo cistos na gordura, com lóbulos atróficos entre septos largos.', 'Biópsia dessas pernas cicatriza mal: biopsiar só se for imprescindível, e então em cunha.'],
    mimics: ['Eritema nodoso: septal com Miescher, sem lipomembranosa, agudo.', 'Morfeia profunda: derme esclerosada, sem estase.', 'Paniculite lúpica: necrose hialina, linfócitos, plasmócitos.', 'Celulite: neutrófilos e febre; frequentemente confundida na fase aguda.'],
    sources: [WEEDON, MCKEE],
  },
]
