/* ==========================================================================
   content/interface.ts — dermatites de interface: as vacuolares (eritema
   multiforme, fármacos, GVHD, lúpus, dermatomiosite, pitiríase liquenoide)
   e as liquenoides (líquen plano e variantes, líquen estriado, nítido,
   ceratose liquenoide, líquen escleroso, eritema discrômico).
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const ACKERMAN = 'Ackerman: Histologic Diagnosis of Inflammatory Skin Diseases, 3ª ed. (2005)'
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'

export const interfaceDermatitis: Diagnosis[] = [
  {
    id: 'erythema-multiforme',
    name: 'Eritema multiforme',
    patterns: ['interface-vacuolar', 'subepidermal-blister'],
    clinical: ['young-adult', 'acute', 'target', 'acral', 'extensor', 'mucosa', 'infection', 'relapsing'],
    histology: ['vacuolar', 'necrotic-keratinocytes', 'lymphocytic-superficial', 'papillary-edema', 'subepidermal-cell-poor', 'exocytosis-neutrophils', 'pigment-incontinence'],
    hallmarks: ['necrotic-keratinocytes', 'vacuolar'],
    against: ['eosinophils', 'parakeratosis-confluent', 'plasma-cells'],
    frequency: 2,
    summary: 'Alvos típicos acrais após herpes simples; interface vacuolar com queratinócitos necróticos em todos os níveis, infiltrado linfocitário superficial e córnea normal (lesão de poucos dias).',
    clues: [
      'Camada córnea em cesto com epiderme lesada por baixo: a lesão é aguda.',
      'Necrose de queratinócitos isolados e em grupos, com linfócitos "satélites"; bolha subepidérmica quando a necrose confluir.',
      'Eosinófilos escassos ou ausentes favorecem herpes sobre fármaco.',
    ],
    mimics: [
      'Erupção fixa por fármaco: mesma histologia com eosinófilos, neutrófilos, melanófagos abundantes e infiltrado mais profundo; lesão recorrente no mesmo lugar.',
      'Síndrome de Stevens-Johnson / NET: necrose confluente de espessura total, infiltrado escasso; separação clínica pela extensão.',
      'GVHD aguda: mesma imagem em transplantado; a cronologia decide.',
      'Lúpus subagudo: mucina, membrana basal espessa, infiltrado periadnexal.',
      'Pitiríase liquenoide aguda: paraceratose, hemácias extravasadas, infiltrado em cunha.',
    ],
    next: ['Perguntar por herpes labial 1 a 3 semanas antes.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'sjs-ten',
    name: 'Síndrome de Stevens-Johnson / necrólise epidérmica tóxica',
    aka: ['SJS', 'NET', 'Lyell'],
    patterns: ['interface-vacuolar', 'subepidermal-blister'],
    clinical: ['drug', 'acute', 'fever', 'mucosa', 'flaccid-bulla', 'target', 'generalized', 'pain', 'immunosuppression'],
    histology: ['full-thickness-necrosis', 'necrotic-keratinocytes', 'vacuolar', 'subepidermal-cell-poor', 'sparse-infiltrate', 'eosinophils'],
    hallmarks: ['full-thickness-necrosis'],
    against: ['acantholysis', 'subcorneal-pustule', 'neutrophils-corneum'],
    frequency: 1,
    summary: 'Descolamento epidérmico doloroso com mucosite dias a semanas após anticonvulsivante, alopurinol, sulfa ou AINE; necrose epidérmica de espessura total sobre derme quase sem inflamação.',
    clues: [
      'Epiderme inteira necrótica e eosinofílica destacada da derme, que fica com infiltrado escasso: "muita necrose, pouca inflamação".',
      'Lesões precoces mostram interface vacuolar com queratinócitos necróticos dispersos, iguais ao eritema multiforme.',
      'A biópsia de congelação do teto da bolha separa de SSSS em horas.',
    ],
    mimics: [
      'Síndrome da pele escaldada estafilocócica: fenda subcórnea / na granulosa, epiderme viável abaixo.',
      'Eritema multiforme major: necrose menos confluente e clínica de alvos típicos.',
      'GVHD aguda grau IV: idêntica; contexto de transplante.',
      'Pênfigo paraneoplásico: acantólise suprabasal somada à interface.',
      'Queimadura / reação fototóxica: distribuição e história.',
    ],
    next: ['Congelação do teto da bolha para excluir SSSS; suspender o fármaco suspeito.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'fixed-drug-eruption',
    name: 'Erupção fixa por fármaco',
    patterns: ['interface-vacuolar', 'interface-lichenoid'],
    clinical: ['drug', 'acute', 'relapsing', 'hyperpigmented', 'genital', 'mucosa', 'acral', 'bulla', 'annular'],
    histology: ['vacuolar', 'necrotic-keratinocytes', 'pigment-incontinence', 'eosinophils', 'neutrophils-dermis', 'superficial-and-deep', 'subepidermal-cell-poor', 'lymphocytic-superficial'],
    hallmarks: ['pigment-incontinence', 'necrotic-keratinocytes'],
    frequency: 2,
    summary: 'Placa violácea que reaparece sempre no mesmo lugar (lábio, genital, mãos) a cada dose do fármaco e deixa mancha acinzentada; interface com necrose de queratinócitos, infiltrado misto com eosinófilos e neutrófilos, e muitos melanófagos.',
    clues: [
      'A tríade: dano de interface, infiltrado mais profundo e misto que o do eritema multiforme, e melanófagos abundantes (marca das recorrências).',
      'Forma bolhosa generalizada imita NET, mas com infiltrado mais rico e melanófagos.',
    ],
    mimics: [
      'Eritema multiforme: superficial, sem eosinófilos, sem melanófagos.',
      'Líquen plano: infiltrado em faixa puro, hipergranulose, sem eosinófilos.',
      'Eritema discrômico perstante: interface sutil e melanófagos sem necrose ativa.',
      'Herpes simples recorrente: balonização e multinucleação.',
    ],
    next: ['Perguntar por AINE, sulfa, paracetamol, tetraciclinas e a mesma localização em surtos prévios.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'morbilliform-drug-eruption',
    name: 'Erupção medicamentosa morbiliforme',
    aka: ['Exantema por fármaco', 'Erupção maculopapular'],
    patterns: ['perivascular-superficial', 'interface-vacuolar'],
    clinical: ['drug', 'acute', 'generalized', 'trunk', 'macule', 'papule', 'itch', 'subacute'],
    histology: ['lymphocytic-superficial', 'vacuolar', 'eosinophils', 'necrotic-keratinocytes', 'papillary-edema', 'spongiosis', 'sparse-infiltrate'],
    hallmarks: ['eosinophils', 'vacuolar'],
    against: ['band-like', 'plasma-cells', 'atypical-lymphocytes'],
    frequency: 3,
    summary: 'Exantema simétrico 7 a 14 dias após antibiótico ou anticonvulsivante; infiltrado perivascular superficial com eosinófilos e dano vacuolar sutil com um ou outro queratinócito necrótico.',
    clues: ['Pouco em cada compartimento: leve espongiose, leve interface, leve infiltrado, mas eosinófilos.', 'DRESS: mesma histologia com edema, infiltrado mais denso e linfócitos atípicos; febre, eosinofilia e hepatite.'],
    mimics: [
      'Exantema viral: sem eosinófilos, geralmente; criança, pródromo.',
      'GVHD aguda: satélites necróticos, poucos eosinófilos, transplante.',
      'Urticária: sem interface e sem espongiose, edema e neutrófilos intravasculares.',
      'Sífilis secundária: plasmócitos.',
    ],
    next: ['Hemograma com eosinófilos e transaminases se houver febre (DRESS).'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'viral-exanthem',
    name: 'Exantema viral',
    patterns: ['perivascular-superficial', 'interface-vacuolar'],
    clinical: ['child', 'acute', 'fever', 'generalized', 'macule', 'infection', 'trunk'],
    histology: ['lymphocytic-superficial', 'sparse-infiltrate', 'vacuolar', 'spongiosis', 'papillary-edema', 'rbc-extravasation', 'necrotic-keratinocytes'],
    against: ['eosinophils', 'band-like'],
    frequency: 2,
    summary: 'Exantema morbiliforme febril de criança; infiltrado linfocitário perivascular escasso com espongiose e interface mínimas, sem eosinófilos.',
    clues: ['Histologia mínima e inespecífica; a ausência de eosinófilos ajuda contra fármaco.', 'Sarampo pode ter células gigantes multinucleadas na epiderme (Warthin-Finkeldey).'],
    mimics: ['Erupção morbiliforme por fármaco: eosinófilos.', 'GVHD aguda: satélites necróticos.', 'Urticária: edema sem dano epidérmico.'],
    sources: [WEEDON],
  },
  {
    id: 'acute-gvhd',
    name: 'Doença do enxerto contra hospedeiro aguda',
    aka: ['GVHD aguda'],
    patterns: ['interface-vacuolar'],
    clinical: ['transplant', 'acute', 'acral', 'generalized', 'macule', 'flaccid-bulla', 'fever'],
    histology: ['vacuolar', 'satellite-necrosis', 'necrotic-keratinocytes', 'sparse-infiltrate', 'periadnexal', 'lymphocytic-superficial', 'subepidermal-cell-poor', 'full-thickness-necrosis'],
    hallmarks: ['satellite-necrosis', 'vacuolar'],
    against: ['eosinophils', 'band-like', 'plasma-cells'],
    frequency: 2,
    summary: 'Exantema que começa em palmas, plantas e orelhas 2 a 6 semanas após transplante de medula; interface vacuolar com queratinócitos necróticos rodeados de linfócitos (satelitose) e infiltrado escasso, estendendo-se ao folículo.',
    clues: [
      'Necrose de célula satélite e dano vacuolar que envolve o infundíbulo folicular e o acrossiríngio.',
      'Graus de Lerner: 1 vacuolar, 2 disceratose, 3 fenda subepidérmica, 4 perda da epiderme.',
      'Eosinófilos não excluem GVHD, mas em número significativo favorecem fármaco.',
    ],
    mimics: [
      'Erupção morbiliforme por fármaco: eosinófilos, sem satelitose franca; cronologia sobreposta é comum.',
      'Exantema viral / recuperação de quimioterapia: interface sutil sem satélites; nos primeiros 3 semanas pós-condicionamento, o achado é inespecífico.',
      'Eritema multiforme / NET: mesma imagem, sem transplante.',
    ],
    next: ['Correlacionar com diarreia, bilirrubinas e o dia pós-transplante.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'chronic-lichenoid-gvhd',
    name: 'Doença do enxerto contra hospedeiro crônica (liquenoide)',
    patterns: ['interface-lichenoid', 'interface-vacuolar'],
    clinical: ['transplant', 'chronic', 'violaceous', 'mucosa', 'nails', 'acral', 'hyperpigmented'],
    histology: ['band-like', 'vacuolar', 'necrotic-keratinocytes', 'hypergranulosis', 'acanthosis-irregular', 'pigment-incontinence', 'periadnexal', 'satellite-necrosis'],
    hallmarks: ['band-like', 'satellite-necrosis'],
    frequency: 2,
    summary: 'Pápulas violáceas e lesões orais semelhantes a líquen plano meses após o transplante; dermatite liquenoide com satelitose e acometimento anexial, evoluindo para a forma esclerodermoide.',
    clues: ['Igual ao líquen plano, mas com satélites necróticos, acometimento de folículos e ductos e menos hipergranulose em cunha.', 'A forma esclerodermoide vem depois, com esclerose dérmica e perda de anexos.'],
    mimics: ['Líquen plano: sem satelitose, sem anexos, sem transplante.', 'Erupção liquenoide por fármaco: eosinófilos, paraceratose.', 'Lúpus: mucina, banda lúpica.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'discoid-lupus',
    name: 'Lúpus eritematoso discoide',
    aka: ['Lúpus cutâneo crônico'],
    patterns: ['interface-vacuolar', 'interface-lichenoid', 'perivascular-deep'],
    clinical: ['female', 'photoexposed', 'face', 'scalp', 'chronic', 'atrophy', 'hair-loss', 'hyperpigmented', 'hypopigmented', 'telangiectasia', 'photosensitive', 'autoimmune'],
    histology: ['vacuolar', 'bmz-thickening', 'follicular-plug', 'periadnexal', 'superficial-and-deep', 'mucin', 'pigment-incontinence', 'atrophy-epidermis', 'orthokeratosis-compact', 'dif-lupus-band', 'necrotic-keratinocytes', 'band-like', 'sebaceous-loss'],
    hallmarks: ['bmz-thickening', 'follicular-plug', 'periadnexal', 'mucin'],
    against: ['eosinophils', 'wedge-hypergranulosis', 'saw-tooth', 'neutrophils-corneum'],
    frequency: 3,
    summary: 'Placas discoides cicatriciais em face e couro cabeludo; interface vacuolar com membrana basal espessada, tampões foliculares, infiltrado linfocitário superficial, profundo e periadnexal, e mucina intersticial.',
    clues: [
      'Membrana basal espessada (PAS) e tampões foliculares com interface folicular são as marcas do discoide.',
      'Infiltrado periadnexal e periécrino profundo com mucina reticular no colágeno.',
      'IF: banda granular de IgG/IgM/C3 na ZMB em pele lesada (banda lúpica).',
    ],
    mimics: [
      'Líquen plano: faixa que apaga a junção, hipergranulose em cunha, dente de serra, sem mucina nem periadnexal profundo.',
      'Líquen planopilar: no couro cabeludo, infiltrado só perifolicular no istmo, poupa a epiderme interfolicular; sem mucina.',
      'Dermatomiosite: indistinguível na pele; mais atrofia, menos periadnexal; clínica.',
      'Dermatite seborreica facial: espongiose, sem interface.',
      'Rosácea: sem interface, Demodex.',
    ],
    next: ['PAS para a membrana basal e coloide-ferro ou alcian para mucina; IF direta; FAN e avaliação sistêmica.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'subacute-cutaneous-lupus',
    name: 'Lúpus eritematoso cutâneo subagudo',
    aka: ['LECSA', 'SCLE'],
    patterns: ['interface-vacuolar'],
    clinical: ['female', 'photoexposed', 'trunk', 'annular', 'scaly-plaque', 'photosensitive', 'drug', 'autoimmune', 'subacute'],
    histology: ['vacuolar', 'necrotic-keratinocytes', 'atrophy-epidermis', 'mucin', 'lymphocytic-superficial', 'sparse-infiltrate', 'pigment-incontinence', 'dif-lupus-band', 'papillary-edema'],
    hallmarks: ['vacuolar', 'mucin'],
    against: ['follicular-plug', 'bmz-thickening', 'wedge-hypergranulosis', 'eosinophils'],
    frequency: 2,
    summary: 'Placas anulares ou psoriasiformes não cicatriciais em ombros, dorso e braços, anti-Ro positivas; interface vacuolar proeminente com atrofia epidérmica, mucina e infiltrado mais raso e mais escasso que no discoide.',
    clues: [
      'Mais dano de interface e menos infiltrado que o discoide; sem tampões e sem espessamento da basal.',
      'Fármacos (hidroclorotiazida, terbinafina, inibidores de bomba, anti-TNF) induzem a forma subaguda com frequência.',
      'IF pode mostrar depósitos granulares finos ao redor dos queratinócitos basais ("dust-like") além da banda.',
    ],
    mimics: [
      'Eritema multiforme: agudo, sem mucina.',
      'Dermatomiosite: idêntica; clínica e enzimas.',
      'Erupção liquenoide por fármaco: faixa densa com eosinófilos.',
      'Eritema anular centrífugo: sem interface.',
    ],
    next: ['Anti-Ro/SSA, FAN e lista de medicamentos.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'acute-cutaneous-lupus',
    name: 'Lúpus eritematoso cutâneo agudo',
    aka: ['Eritema malar'],
    patterns: ['interface-vacuolar', 'perivascular-superficial'],
    clinical: ['female', 'young-adult', 'face', 'photoexposed', 'acute', 'fever', 'arthralgia', 'autoimmune', 'photosensitive'],
    histology: ['vacuolar', 'sparse-infiltrate', 'mucin', 'papillary-edema', 'lymphocytic-superficial', 'dif-lupus-band', 'necrotic-keratinocytes', 'neutrophils-dermis'],
    hallmarks: ['vacuolar', 'mucin'],
    frequency: 2,
    summary: 'Eritema malar em asa de borboleta de lúpus sistêmico ativo; dano vacuolar discreto com edema, mucina e infiltrado escasso, às vezes com neutrófilos e poeira nuclear.',
    clues: ['Achados sutis: a mucina e o edema com pouca inflamação são a pista; IF positiva também em pele sã.', 'Neutrófilos e leucocitoclasia sem vasculite ocorrem no lúpus sistêmico agudo.'],
    mimics: ['Rosácea / dermatite seborreica: sem interface, sem mucina.', 'Dermatomiosite: idêntica; heliótropo e Gottron.', 'Erupção medicamentosa: eosinófilos.'],
    next: ['FAN, anti-dsDNA, complemento e urina.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'tumid-lupus',
    name: 'Lúpus eritematoso túmido',
    aka: ['Lúpus túmido'],
    patterns: ['perivascular-deep', 'deposition'],
    clinical: ['face', 'trunk', 'photoexposed', 'photosensitive', 'papule', 'annular', 'chronic', 'relapsing', 'asymptomatic'],
    histology: ['superficial-and-deep', 'periadnexal', 'mucin', 'lymphocytic-superficial'],
    hallmarks: ['mucin', 'superficial-and-deep'],
    against: ['vacuolar', 'necrotic-keratinocytes', 'atrophy-epidermis', 'band-like'],
    frequency: 2,
    summary: 'Placas suculentas eritematosas sem escama ou atrofia em face e tronco, que somem sem cicatriz; infiltrado linfocitário superficial, profundo e periadnexal com mucina abundante, sem alteração epidérmica.',
    clues: ['Muita mucina intersticial e infiltrado "em manga" profundo, com epiderme normal e sem interface.', 'FAN em geral negativo; fotossensível.'],
    mimics: [
      'Infiltrado linfocitário de Jessner: provavelmente a mesma entidade; sem mucina.',
      'Mucinose eritematosa reticular (REM): tronco central, mesmo espectro.',
      'Eritema anular centrífugo profundo: sem mucina.',
      'Pseudolinfoma / linfoma B: folículos, células B, clone.',
      'Erupção polimorfa à luz: edema papilar, sem mucina.',
    ],
    next: ['Coloide-ferro ou alcian blue para a mucina.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'dermatomyositis',
    name: 'Dermatomiosite',
    patterns: ['interface-vacuolar'],
    clinical: ['female', 'photoexposed', 'face', 'hands', 'extensor', 'atrophy', 'telangiectasia', 'itch', 'malignancy', 'autoimmune', 'child', 'photosensitive'],
    histology: ['vacuolar', 'atrophy-epidermis', 'mucin', 'sparse-infiltrate', 'dilated-vessels', 'necrotic-keratinocytes', 'pigment-incontinence', 'lymphocytic-superficial', 'calcification'],
    hallmarks: ['vacuolar', 'mucin', 'atrophy-epidermis'],
    against: ['follicular-plug', 'bmz-thickening', 'periadnexal', 'band-like', 'eosinophils'],
    frequency: 2,
    summary: 'Heliótropo, pápulas de Gottron e poiquilodermia pruriginosa dos ombros; interface vacuolar com epiderme atrófica, mucina dérmica, vasos dilatados e infiltrado escasso, indistinguível do lúpus na lâmina.',
    clues: [
      'Interface "pobre" (pouco infiltrado, muita mucina, atrofia) em fotoexposta com prurido intenso.',
      'Pápulas de Gottron podem ter acantose em vez de atrofia.',
      'A lâmina não separa de lúpus: fraqueza proximal, CK, autoanticorpos (anti-MDA5, TIF1-γ) e rastreio de neoplasia fazem o resto.',
    ],
    mimics: ['Lúpus subagudo / agudo: idêntico; sorologia e clínica.', 'Erupção fototóxica: necrose de queratinócitos "queimados", sem mucina.', 'Micose fungoide poiquilodérmica: atipia e epidermotropismo.'],
    next: ['CK, aldolase, eletroneuromiografia e painel de anticorpos miosite-específicos; rastreio de neoplasia no adulto.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'pleva',
    name: 'Pitiríase liquenoide e varioliforme aguda',
    aka: ['PLEVA', 'Mucha-Habermann'],
    patterns: ['interface-vacuolar', 'interface-lichenoid', 'perivascular-deep'],
    clinical: ['child', 'young-adult', 'acute', 'relapsing', 'papule', 'trunk', 'vesicle', 'ulcer', 'atrophy'],
    histology: ['parakeratosis-confluent', 'necrotic-keratinocytes', 'vacuolar', 'rbc-extravasation', 'wedge-infiltrate', 'epidermotropism', 'lymphocytic-vasculitis', 'crust', 'superficial-and-deep', 'pale-upper-epidermis'],
    hallmarks: ['rbc-extravasation', 'necrotic-keratinocytes', 'wedge-infiltrate'],
    against: ['eosinophils', 'plasma-cells'],
    frequency: 2,
    summary: 'Surtos de pápulas necróticas e crostosas que deixam cicatrizes varioliformes; paraceratose confluente com escamo-crosta, interface com necrose de queratinócitos, hemácias extravasadas na epiderme e infiltrado em cunha com vasculite linfocitária.',
    clues: [
      'Hemácias dentro da epiderme e exocitose de linfócitos com necrose confluente sob crosta de paraceratose.',
      'Infiltrado em cunha com o vértice profundo; linfócitos CD8+ predominam.',
    ],
    mimics: [
      'Papulose linfomatoide: células grandes CD30+ atípicas; as duas podem coexistir.',
      'Eritema multiforme: córnea normal, sem hemácias.',
      'Vasculite leucocitoclástica: fibrina e neutrófilos na parede.',
      'Varicela: balonização e multinucleação.',
      'Erupção liquenoide por fármaco: eosinófilos.',
    ],
    next: ['CD30 quando houver células grandes; excluir sífilis se o paciente for adulto.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'plc',
    name: 'Pitiríase liquenoide crônica',
    aka: ['PLC'],
    patterns: ['interface-vacuolar', 'psoriasiform'],
    clinical: ['child', 'young-adult', 'chronic', 'relapsing', 'papule', 'scaly-plaque', 'trunk', 'hypopigmented', 'asymptomatic'],
    histology: ['parakeratosis-confluent', 'vacuolar', 'lymphocytic-superficial', 'rbc-extravasation', 'epidermotropism', 'necrotic-keratinocytes', 'pigment-incontinence', 'acanthosis-regular'],
    hallmarks: ['parakeratosis-confluent', 'rbc-extravasation'],
    against: ['eosinophils', 'atypical-lymphocytes', 'pautrier'],
    frequency: 2,
    summary: 'Pápulas pequenas com escama em "mica" que se destaca inteira, de evolução arrastada; paraceratose confluente aderida, interface leve com hemácias extravasadas e exocitose modesta.',
    clues: ['Escama paraceratósica compacta sobre epiderme com interface discreta; versão atenuada da PLEVA.', 'Hipopigmentação residual é comum em pele escura e imita micose fungoide hipopigmentada.'],
    mimics: [
      'Micose fungoide: atipia, alinhamento na basal, perda de CD7, clone.',
      'Pitiríase rósea: montículos focais, espongiose, curso curto.',
      'Psoríase gutata: neutrófilos na córnea.',
      'Sífilis secundária: plasmócitos, IHQ.',
    ],
    next: ['Seguimento; se persistir por anos com placas maiores, repetir biópsia com IHQ e clone.'],
    sources: [WEEDON],
  },
  {
    id: 'lichen-planus',
    name: 'Líquen plano',
    patterns: ['interface-lichenoid'],
    clinical: ['young-adult', 'itch', 'violaceous', 'papule', 'acral', 'flexural', 'mucosa', 'nails', 'linear', 'liver', 'chronic', 'subacute'],
    histology: ['band-like', 'vacuolar', 'necrotic-keratinocytes', 'wedge-hypergranulosis', 'saw-tooth', 'orthokeratosis-compact', 'max-joseph', 'pigment-incontinence', 'dif-cytoid', 'acanthosis-irregular'],
    hallmarks: ['band-like', 'wedge-hypergranulosis', 'saw-tooth', 'necrotic-keratinocytes'],
    against: ['parakeratosis-confluent', 'eosinophils', 'plasma-cells', 'mucin', 'periadnexal', 'superficial-and-deep'],
    frequency: 3,
    summary: 'Pápulas poligonais violáceas pruriginosas de punhos e tornozelos, com estrias de Wickham; infiltrado linfocitário em faixa que oculta a junção, hipergranulose em cunha, cristas em dente de serra, corpos de Civatte e ortoceratose.',
    clues: [
      'Faixa de linfócitos limitada à derme papilar, "abraçando" a epiderme, com ortoceratose (sem paraceratose) e hipergranulose em cunha.',
      'Corpos de Civatte na basal e na derme papilar; fendas de Max Joseph quando o dano é intenso.',
      'IF: corpos citoides com IgM e fibrinogênio irregular na ZMB, sem banda granular.',
    ],
    mimics: [
      'Erupção liquenoide por fármaco: eosinófilos, paraceratose focal, infiltrado que desce além da papilar, necrose em níveis altos.',
      'Lúpus discoide: membrana basal espessa, tampões, periadnexal, mucina.',
      'Ceratose liquenoide benigna: lesão solitária, ceratose seborreica ou lentigo ao lado.',
      'GVHD liquenoide: satelitose, anexos.',
      'Sífilis liquenoide: plasmócitos.',
      'Micose fungoide liquenoide: atipia, Pautrier.',
    ],
    next: ['Hepatite C quando houver lesão oral ou erosiva; revisar fármacos (antimaláricos, tiazídicos, ouro, inibidores de checkpoint).'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'hypertrophic-lichen-planus',
    name: 'Líquen plano hipertrófico',
    patterns: ['interface-lichenoid', 'psoriasiform'],
    clinical: ['legs', 'chronic', 'itch', 'lichenified', 'violaceous', 'extensor', 'elderly'],
    histology: ['acanthosis-irregular', 'hypergranulosis', 'orthokeratosis-compact', 'band-like', 'vacuolar', 'necrotic-keratinocytes', 'papillary-fibrosis', 'papillomatosis'],
    hallmarks: ['acanthosis-irregular', 'band-like'],
    frequency: 2,
    summary: 'Placas verrucosas espessas pré-tibiais que coçam por anos; hiperplasia epidérmica exuberante com o dano liquenoide concentrado na ponta das cristas, muitas vezes ao redor de folículos.',
    clues: ['O infiltrado liquenoide fica só na base das cristas alongadas; o resto lembra líquen simples.', 'Pode haver proliferação "pseudoepiteliomatosa" e carcinoma espinocelular secundário em lesões antigas.'],
    mimics: [
      'Líquen simples crônico / prurigo nodular: sem interface, sem Civatte.',
      'Carcinoma espinocelular: atipia, queratinização anômala, invasão; muito difícil em biópsia superficial.',
      'Ceratose actínica hipertrófica / líquen plano-like: atipia basal em pele solar.',
    ],
    next: ['Biópsia mais profunda se houver dúvida com carcinoma.'],
    sources: [WEEDON],
  },
  {
    id: 'lichenoid-drug-eruption',
    name: 'Erupção liquenoide por fármaco',
    aka: ['Líquen plano medicamentoso'],
    patterns: ['interface-lichenoid', 'interface-vacuolar'],
    clinical: ['drug', 'elderly', 'photoexposed', 'trunk', 'generalized', 'violaceous', 'scaly-plaque', 'subacute', 'itch'],
    histology: ['band-like', 'eosinophils', 'parakeratosis-focal', 'necrotic-keratinocytes', 'vacuolar', 'superficial-and-deep', 'plasma-cells', 'pigment-incontinence', 'hypogranulosis'],
    hallmarks: ['eosinophils', 'parakeratosis-focal'],
    frequency: 2,
    summary: 'Erupção liquenoide extensa e fotodistribuída de paciente idoso polimedicado (tiazídico, antimalárico, betabloqueador, anti-PD-1); líquen plano "sujo" com eosinófilos, paraceratose focal, hipogranulose e infiltrado que ultrapassa a papilar.',
    clues: [
      'Eosinófilos (e plasmócitos) numa faixa liquenoide são a pista principal; nenhum é obrigatório.',
      'Paraceratose e queratinócitos necróticos em níveis altos da epiderme, ao contrário do líquen plano clássico.',
      'Infiltrado mais profundo e perivascular, com menos hipergranulose.',
    ],
    mimics: ['Líquen plano: ortoceratose, faixa limpa, hipergranulose em cunha.', 'Lúpus subagudo: mucina, membrana basal.', 'Micose fungoide liquenoide: atipia, clone.', 'Dermatite actínica crônica: elastose, CD8.'],
    next: ['Cronologia dos fármacos, incluindo imunoterapia oncológica.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'lichen-striatus',
    name: 'Líquen estriado',
    patterns: ['interface-lichenoid', 'spongiotic'],
    clinical: ['child', 'linear', 'dermatomal', 'papule', 'hypopigmented', 'relapsing', 'asymptomatic', 'legs'],
    histology: ['band-like', 'vacuolar', 'necrotic-keratinocytes', 'spongiosis', 'periadnexal', 'parakeratosis-focal', 'pigment-incontinence', 'superficial-and-deep'],
    hallmarks: ['periadnexal', 'band-like'],
    frequency: 2,
    summary: 'Faixa de pápulas que segue Blaschko num membro de criança e some em meses deixando hipocromia; dermatite liquenoide com espongiose e infiltrado que desce ao redor de folículos e glândulas écrinas.',
    clues: ['Infiltrado liquenoide mais um infiltrado periécrino profundo: a combinação é a assinatura.', 'Espongiose e paraceratose focal separam de líquen plano.'],
    mimics: ['Líquen plano linear: sem espongiose, sem periécrino; adulto.', 'NEVIL: psoriasiforme com alternância de queratose, sem interface.', 'Líquen nítido: granuloma em garra numa única papila.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'lichen-nitidus',
    name: 'Líquen nítido',
    patterns: ['interface-lichenoid', 'granulomatous'],
    clinical: ['child', 'young-adult', 'papule', 'genital', 'trunk', 'extensor', 'asymptomatic', 'chronic', 'linear'],
    histology: ['band-like', 'vacuolar', 'atrophy-epidermis', 'parakeratosis-focal', 'sarcoidal-granuloma', 'foreign-body-giant-cells', 'pigment-incontinence'],
    hallmarks: ['band-like', 'sarcoidal-granuloma'],
    frequency: 2,
    summary: 'Pápulas brilhantes minúsculas e monomórficas em pênis, abdome e antebraços; infiltrado linfo-histiocitário compacto em uma ou duas papilas, "abraçado" por cristas alongadas laterais (garra segurando bola).',
    clues: ['Infiltrado bem circunscrito com histiócitos epitelioides e células gigantes, atrofia da epiderme sobre ele e paraceratose focal.', 'As cristas laterais alongadas em garra são o sinal clássico.'],
    mimics: ['Líquen plano: faixa contínua, hipergranulose, sem granuloma.', 'Sarcoidose papular: granulomas nus na derme sem confinamento à papila.', 'Líquen escrofuloso: perifolicular, tuberculose.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'benign-lichenoid-keratosis',
    name: 'Ceratose liquenoide benigna',
    aka: ['Ceratose tipo líquen plano', 'Lentigo com regressão liquenoide'],
    patterns: ['interface-lichenoid'],
    clinical: ['elderly', 'photoexposed', 'trunk', 'papule', 'asymptomatic', 'acute', 'subacute'],
    histology: ['band-like', 'vacuolar', 'necrotic-keratinocytes', 'parakeratosis-focal', 'pigment-incontinence', 'solar-elastosis', 'eosinophils', 'plasma-cells', 'papillomatosis'],
    hallmarks: ['band-like', 'solar-elastosis'],
    frequency: 3,
    summary: 'Lesão solitária rosada no tronco ou braço de adulto, biopsiada como carcinoma basocelular; reação liquenoide a lentigo solar ou ceratose seborreica em regressão, com paraceratose e restos da lesão original na borda.',
    clues: ['Procurar o lentigo ou a ceratose seborreica residual na periferia: papilomatose, pseudocistos, hiperpigmentação basal.', 'Faixa liquenoide "solitária" com eosinófilos ocasionais e elastose solar.'],
    mimics: ['Líquen plano: múltiplas lesões, hipergranulose em cunha, sem elastose.', 'Lúpus discoide: periadnexal, membrana basal.', 'Melanoma em regressão: melanócitos atípicos residuais, melanófagos em faixa; usar SOX10 se necessário.'],
    next: ['SOX10 / Melan-A se houver melanófagos densos e dúvida de regressão de melanoma.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'lichen-sclerosus',
    name: 'Líquen escleroso',
    aka: ['Líquen escleroso e atrófico', 'Craurose vulvar'],
    patterns: ['interface-lichenoid', 'fibrosing'],
    clinical: ['female', 'genital', 'itch', 'atrophy', 'hypopigmented', 'chronic', 'child', 'elderly', 'sclerosis', 'trunk'],
    histology: ['homogenized-papillary', 'atrophy-epidermis', 'vacuolar', 'band-like', 'orthokeratosis-compact', 'follicular-plug', 'papillary-edema', 'rbc-extravasation', 'elastophagocytosis', 'acanthosis-irregular'],
    hallmarks: ['homogenized-papillary', 'atrophy-epidermis'],
    against: ['wedge-hypergranulosis', 'saw-tooth', 'mucin'],
    frequency: 3,
    summary: 'Placas branco-porcelana atróficas na vulva ou glande (e pápulas no tronco) com prurido intenso; epiderme atrófica com ortoceratose compacta e tampões, homogeneização edemato-hialina da derme papilar e faixa de linfócitos empurrada para baixo dela.',
    clues: [
      'Colágeno papilar homogeneizado e pálido, com perda de fibras elásticas, separando a epiderme atrófica da faixa linfocitária.',
      'Lesão inicial só tem interface liquenoide com edema papilar; a esclerose vem depois.',
      'Vulva: pode coexistir hiperplasia (líquen simples sobreposto) e, raramente, VIN diferenciada e carcinoma.',
    ],
    mimics: [
      'Líquen plano genital: sem homogeneização, hipergranulose, cristas em dente de serra; erosivo na vulva.',
      'Morfeia: esclerose de toda a derme reticular, sem atrofia epidérmica; as duas coexistem.',
      'Vitiligo: sem atrofia, sem esclerose, perda de melanócitos.',
      'Radiodermite crônica: fibroblastos atípicos, vasos ectásicos, história.',
    ],
    next: ['Orceína para fibras elásticas se a homogeneização for duvidosa; atenção a atipia basal na vulva (p53).'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'erythema-dyschromicum-perstans',
    name: 'Eritema discrômico perstante',
    aka: ['Dermatose cinzenta', 'Ashy dermatosis', 'Líquen plano pigmentoso'],
    patterns: ['interface-vacuolar', 'invisible'],
    clinical: ['young-adult', 'trunk', 'hyperpigmented', 'macule', 'chronic', 'asymptomatic', 'face', 'flexural', 'photoexposed'],
    histology: ['pigment-incontinence', 'vacuolar', 'sparse-infiltrate', 'lymphocytic-superficial', 'necrotic-keratinocytes', 'band-like'],
    hallmarks: ['pigment-incontinence', 'vacuolar'],
    against: ['eosinophils', 'spongiosis'],
    frequency: 2,
    summary: 'Manchas cinza-azuladas no tronco e pescoço de adultos de pele parda; interface vacuolar sutil com melanófagos abundantes na derme papilar e infiltrado escasso. O líquen plano pigmentoso é o mesmo processo em fotoexpostas e dobras.',
    clues: ['Muito melanófago para tão pouca inflamação: dano de interface antigo e contínuo.', 'Sem espongiose e sem eosinófilos.'],
    mimics: ['Erupção fixa por fármaco: necrose ativa, eosinófilos, lesão única recorrente.', 'Hiperpigmentação pós-inflamatória: sem interface ativa; história de dermatose prévia.', 'Melasma: mais melanina epidérmica, sem melanófagos abundantes, face.'],
    sources: [WEEDON, BOLOGNIA],
  },
]
