/* ==========================================================================
   content/nodular.ts — padrões nodular e difuso: granulomatosos (sarcoidose,
   paliçada, corpo estranho, infecções granulomatosas), neutrofílicos
   (Sweet, pioderma, Behçet), eosinofílicos (Wells), mastócitos, linfoides
   e histiocitoses que se disfarçam de inflamação.
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const ACKERMAN = 'Ackerman: Histologic Diagnosis of Inflammatory Skin Diseases, 3ª ed. (2005)'
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'
const WHO_HEME = 'WHO Classification of Haematolymphoid Tumours, 5ª ed. (2024)'

export const nodular: Diagnosis[] = [
  {
    id: 'sarcoidosis',
    name: 'Sarcoidose',
    patterns: ['granulomatous', 'nodular-diffuse'],
    clinical: ['papule', 'nodule', 'face', 'chronic', 'annular', 'fever', 'arthralgia', 'trauma', 'female', 'asymptomatic'],
    histology: ['sarcoidal-granuloma', 'sparse-infiltrate', 'foreign-body-giant-cells', 'polarizable', 'superficial-and-deep', 'sclerosis'],
    hallmarks: ['sarcoidal-granuloma'],
    against: ['tuberculoid-granuloma', 'suppurative-granuloma', 'mucin', 'eosinophils', 'plasma-cells'],
    frequency: 2,
    summary: 'Pápulas e placas vermelho-acastanhadas em face e cicatrizes antigas, com doença pulmonar ou linfonodal; granulomas epitelioides compactos e bem delimitados com pouquíssimos linfócitos ao redor ("nus"), sem necrose caseosa.',
    clues: [
      'Granulomas nus e bem circunscritos distribuídos por toda a derme, com corpos asteroides ou de Schaumann ocasionais.',
      'Material polarizável dentro dos granulomas não exclui sarcoidose: até um quarto dos casos tem, e a sarcoidose adora cicatrizes e tatuagens.',
      'Diagnóstico de exclusão: colorações para fungos e micobactérias negativas e clínica sistêmica compatível.',
    ],
    mimics: [
      'Reação granulomatosa a corpo estranho: material no centro, células gigantes maiores, história de trauma; mas ver acima.',
      'Tuberculose / hanseníase tuberculoide: necrose caseosa, manguito linfocitário denso, nervos envolvidos (hanseníase).',
      'Rosácea granulomatosa: face, perifolicular, Demodex.',
      'Granuloma anular: paliçada com mucina ou histiócitos intersticiais.',
      'Líquen nítido: granuloma em uma papila com cristas em garra.',
    ],
    next: ['PAS/Grocott, Ziehl-Neelsen e Fite; luz polarizada; radiografia de tórax, ECA e cálcio.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'granuloma-annulare',
    name: 'Granuloma anular',
    patterns: ['granulomatous'],
    clinical: ['annular', 'hands', 'acral', 'extensor', 'child', 'young-adult', 'chronic', 'asymptomatic', 'diabetes', 'generalized', 'papule', 'subcutaneous-nodule'],
    histology: ['palisaded-granuloma', 'mucin', 'interstitial-histiocytes', 'necrobiosis', 'eosinophils', 'lymphocytic-superficial', 'foreign-body-giant-cells'],
    hallmarks: ['palisaded-granuloma', 'mucin', 'interstitial-histiocytes'],
    against: ['plasma-cells', 'sarcoidal-granuloma', 'sclerosis', 'foamy-histiocytes'],
    frequency: 3,
    summary: 'Anéis de pápulas lisas em dorso de mãos e pés de jovens; histiócitos em paliçada ao redor de colágeno degenerado com mucina (forma clássica) ou histiócitos espalhados entre feixes de colágeno (forma intersticial, a mais comum e a mais esquecida).',
    clues: [
      'Mucina no centro da paliçada (alcian blue / coloide-ferro) é o que separa de necrobiose lipoídica e nódulo reumatoide.',
      'Na forma intersticial, a derme parece "ocupada" por histiócitos entre feixes separados por mucina, sem paliçada; eosinófilos ajudam.',
      'Forma subcutânea em crianças (pseudo-reumatoide) e forma generalizada em diabéticos e HIV.',
    ],
    mimics: [
      'Necrobiose lipoídica: paliçada em camadas horizontais por toda a derme, com plasmócitos, sem mucina, pré-tibial.',
      'Nódulo reumatoide: necrose fibrinoide eosinofílica com fibrina, sem mucina, subcutâneo, artrite reumatoide.',
      'Dermatite granulomatosa intersticial: histiócitos em cordões com colágeno degenerado basofílico e neutrófilos; artrite.',
      'Xantogranuloma necrobiótico: paliçada com colesterol, plasmócitos, paraproteína, periorbitário.',
      'Sarcoidose: granulomas nus sem mucina.',
      'Eritema anular centrífugo: sem histiócitos.',
    ],
    next: ['Alcian blue ou coloide-ferro para a mucina; CD68 se a forma intersticial for duvidosa.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'necrobiosis-lipoidica',
    name: 'Necrobiose lipoídica',
    patterns: ['granulomatous', 'fibrosing'],
    clinical: ['legs', 'diabetes', 'female', 'atrophy', 'telangiectasia', 'chronic', 'ulcer', 'asymptomatic'],
    histology: ['palisaded-granuloma', 'necrobiosis', 'plasma-cells', 'sclerosis', 'foreign-body-giant-cells', 'thick-collagen', 'atrophy-epidermis', 'lymphoid-follicles', 'foamy-histiocytes'],
    hallmarks: ['necrobiosis', 'plasma-cells'],
    against: ['mucin'],
    frequency: 2,
    summary: 'Placas amarelo-acastanhadas atróficas e telangiectásicas pré-tibiais, muitas vezes em diabético; camadas horizontais alternadas de colágeno degenerado e paliçadas de histiócitos ocupando toda a derme até o subcutâneo ("bolo em camadas"), com plasmócitos e sem mucina.',
    clues: [
      'Em pequeno aumento, faixas horizontais de necrobiose alternando com inflamação por toda a espessura da derme, sem os limites nítidos do granuloma anular.',
      'Plasmócitos na profundidade e ao redor de vasos; agregados linfoides no subcutâneo.',
      'Perda de anexos e esclerose; a epiderme fica atrófica.',
    ],
    mimics: ['Granuloma anular: paliçadas focais com mucina, derme superficial e média, sem plasmócitos.', 'Xantogranuloma necrobiótico: fendas de colesterol, células gigantes bizarras, paraproteína.', 'Nódulo reumatoide: necrose fibrinoide subcutânea.', 'Sarcoidose: granulomas nus.'],
    next: ['Glicemia; alcian blue negativo ajuda contra granuloma anular.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'rheumatoid-nodule',
    name: 'Nódulo reumatoide',
    patterns: ['granulomatous', 'panniculitis-septal'],
    clinical: ['subcutaneous-nodule', 'extensor', 'autoimmune', 'arthralgia', 'chronic', 'asymptomatic', 'hands'],
    histology: ['palisaded-granuloma', 'necrobiosis', 'septal-panniculitis', 'sparse-infiltrate', 'plasma-cells'],
    hallmarks: ['palisaded-granuloma', 'necrobiosis'],
    against: ['mucin', 'foamy-histiocytes'],
    frequency: 2,
    summary: 'Nódulo subcutâneo firme sobre cotovelo ou dedos de paciente com artrite reumatoide soropositiva; grande área de necrose fibrinoide eosinofílica e homogênea cercada por paliçada de histiócitos, no subcutâneo ou derme profunda.',
    clues: ['Centro de fibrina vermelha, não de mucina azul; localização profunda.', 'Metotrexato acelera nódulos.'],
    mimics: ['Granuloma anular subcutâneo (pseudo-reumatoide): criança, mucina no centro, sem artrite.', 'Gota: cristais em agulha dissolvidos com material amorfo róseo; polarizar tecido sem descalcificação.', 'Epitelioma calcificante / cisto roto: queratina.'],
    next: ['Fator reumatoide e anti-CCP se ainda não houver diagnóstico.'],
    sources: [WEEDON],
  },
  {
    id: 'necrobiotic-xanthogranuloma',
    name: 'Xantogranuloma necrobiótico',
    patterns: ['granulomatous'],
    clinical: ['face', 'elderly', 'nodule', 'malignancy', 'chronic', 'ulcer', 'atrophy'],
    histology: ['palisaded-granuloma', 'necrobiosis', 'foamy-histiocytes', 'foreign-body-giant-cells', 'plasma-cells', 'lymphoid-follicles', 'needle-clefts'],
    hallmarks: ['foamy-histiocytes', 'necrobiosis'],
    frequency: 1,
    summary: 'Placas amareladas induradas periorbitárias que ulceram, com paraproteína IgG; necrobiose extensa em faixas com células gigantes de Touton e de corpo estranho bizarras, histiócitos espumosos, fendas de colesterol e agregados linfoplasmocitários.',
    clues: ['Necrobiose + células gigantes enormes + colesterol + plasmócitos, em paciente com gamopatia.', 'Estende-se ao subcutâneo.'],
    mimics: ['Necrobiose lipoídica: pernas, sem colesterol nem células tão bizarras.', 'Xantelasma: só histiócitos espumosos, sem necrobiose.', 'Xantogranuloma juvenil: criança, Touton sem necrobiose.'],
    next: ['Eletroforese e imunofixação de proteínas séricas.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'interstitial-granulomatous-dermatitis',
    name: 'Dermatite granulomatosa intersticial / reação granulomatosa intersticial a fármaco',
    aka: ['Sinal da corda (Ackerman)', 'Dermatite granulomatosa paliçádica e neutrofílica'],
    patterns: ['granulomatous'],
    clinical: ['arthralgia', 'autoimmune', 'drug', 'trunk', 'flexural', 'papule', 'annular', 'chronic', 'female'],
    histology: ['interstitial-histiocytes', 'necrobiosis', 'neutrophils-dermis', 'eosinophils', 'palisaded-granuloma', 'vacuolar', 'lymphocytic-superficial'],
    hallmarks: ['interstitial-histiocytes', 'necrobiosis'],
    against: ['mucin', 'sarcoidal-granuloma'],
    frequency: 1,
    summary: 'Placas e cordões lineares nas laterais do tronco de paciente com artrite ou lúpus, ou erupção após bloqueador de canal de cálcio, estatina ou anti-TNF; histiócitos intersticiais em cordões ao redor de pequenos focos de colágeno degenerado basofílico, com neutrófilos e poeira nuclear (autoimune) ou eosinófilos e interface (fármaco).',
    clues: ['Focos pequenos e múltiplos de colágeno degenerado "azulado" rodeados de histiócitos em roseta, sem mucina.', 'Na forma medicamentosa há dano vacuolar e eosinófilos; na autoimune, neutrófilos e às vezes LCV.'],
    mimics: ['Granuloma anular intersticial: mucina e eosinófilos, sem necrobiose basofílica.', 'Reação granulomatosa extravascular de vasculite ANCA: vasculite e clínica sistêmica.', 'Micose fungoide granulomatosa: atipia linfoide.'],
    next: ['Fator reumatoide, FAN e revisão de fármacos.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'foreign-body-granuloma',
    name: 'Reação granulomatosa a corpo estranho',
    aka: ['Granuloma de tatuagem', 'Granuloma de silicone / preenchedor', 'Granuloma de sutura'],
    patterns: ['granulomatous', 'nodular-diffuse'],
    clinical: ['trauma', 'nodule', 'chronic', 'face', 'asymptomatic', 'papule', 'hands'],
    histology: ['foreign-body-giant-cells', 'polarizable', 'sarcoidal-granuloma', 'suppurative-granuloma', 'sclerosis', 'foamy-histiocytes', 'lymphoid-follicles'],
    hallmarks: ['foreign-body-giant-cells', 'polarizable'],
    frequency: 3,
    summary: 'Nódulo em cicatriz, tatuagem, ponto de injeção ou preenchimento; células gigantes multinucleadas com material identificável no citoplasma ou no centro do granuloma, birrefringente (talco, sílica, sutura, espinho vegetal) ou não (ácido hialurônico, silicone, pigmento de tatuagem).',
    clues: [
      'Polarizar todo granuloma antes de assinar sarcoidose ou infecção.',
      'Silicone: vacúolos de tamanhos variados dentro de histiócitos e células gigantes ("queijo suíço"); ácido hialurônico: material basofílico amorfo; pigmento de tatuagem: grânulos pretos ou coloridos.',
      'Ruptura de cisto ou folículo é o corpo estranho mais comum: procurar queratina laminada.',
    ],
    mimics: ['Sarcoidose: granulomas nus sem material; mas a sarcoidose se instala em tatuagens e cicatrizes.', 'Infecção granulomatosa: necrose, colorações especiais.', 'Xantogranuloma: sem material.'],
    next: ['Luz polarizada; PAS/Grocott e Ziehl se houver supuração ou necrose.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'cutaneous-tuberculosis',
    name: 'Tuberculose cutânea',
    aka: ['Lúpus vulgar', 'Escrofuloderma', 'Tuberculose verrucosa', 'Tubercúlides'],
    patterns: ['granulomatous', 'nodular-diffuse'],
    clinical: ['face', 'chronic', 'nodule', 'ulcer', 'atrophy', 'immunosuppression', 'travel', 'fever', 'papule'],
    histology: ['tuberculoid-granuloma', 'sarcoidal-granuloma', 'suppurative-granuloma', 'afb-positive', 'plasma-cells', 'superficial-and-deep', 'acanthosis-irregular', 'lymphocytic-vasculitis'],
    hallmarks: ['tuberculoid-granuloma', 'afb-positive'],
    frequency: 1,
    summary: 'Placa de "geleia de maçã" em face (lúpus vulgar), nódulo fistulizante sobre linfonodo (escrofuloderma) ou placa verrucosa em mão; granulomas tuberculoides com necrose caseosa e manguito linfocitário denso, bacilos raros (lúpus vulgar) ou visíveis (escrofuloderma).',
    clues: ['Necrose caseosa central e coroa de linfócitos são o oposto do granuloma "nu" da sarcoidose.', 'Tubercúlides (papulonecrótica, eritema induratum, líquen escrofuloso) não têm bacilo: PCR e IGRA.'],
    mimics: ['Sarcoidose: sem necrose caseosa, poucos linfócitos.', 'Hanseníase tuberculoide: granulomas alongados seguindo nervos, com destruição do nervo (S100).', 'Micobacteriose atípica: granulomas supurativos, história de aquário ou procedimento.', 'Micoses profundas: PAS/Grocott.', 'Leishmaniose: amastigotas, plasmócitos.'],
    next: ['Ziehl-Neelsen (ou Fite), PCR para M. tuberculosis, cultura, IGRA e radiografia de tórax.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'atypical-mycobacteriosis',
    name: 'Micobacteriose atípica',
    aka: ['Granuloma de aquário (M. marinum)', 'M. abscessus / fortuitum / chelonae', 'Úlcera de Buruli'],
    patterns: ['granulomatous', 'neutrophilic'],
    clinical: ['trauma', 'hands', 'nodule', 'chronic', 'ulcer', 'linear', 'immunosuppression', 'pustule'],
    histology: ['suppurative-granuloma', 'afb-positive', 'tuberculoid-granuloma', 'neutrophils-dermis', 'acanthosis-irregular', 'fat-necrosis'],
    hallmarks: ['suppurative-granuloma'],
    frequency: 1,
    summary: 'Nódulos esporotricoides no braço após aquário ou piscina, ou abscessos após injeção, lipoaspiração, tatuagem ou mesoterapia; granulomas supurativos (centro de neutrófilos com histiócitos e células gigantes ao redor) com bacilos escassos.',
    clues: ['Granuloma supurativo em pele de mão ou em sítio de procedimento estético: cultura a 30 °C e a 37 °C.', 'Bacilos podem estar dentro de vacúolos lipídicos nas micobactérias de crescimento rápido.'],
    mimics: ['Esporotricose: idêntica; Grocott e cultura.', 'Tuberculose cutânea: caseificação.', 'Leishmaniose: amastigotas.', 'Foliculite / abscesso bacteriano: sem granuloma organizado, Gram.'],
    next: ['Fite, Grocott, PCR para micobactérias e cultura em meios e temperaturas apropriados.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'tuberculoid-leprosy',
    name: 'Hanseníase tuberculoide e dimorfa-tuberculoide',
    patterns: ['granulomatous'],
    clinical: ['annular', 'hypopigmented', 'macule', 'travel', 'chronic', 'asymptomatic', 'face', 'trunk'],
    histology: ['tuberculoid-granuloma', 'sarcoidal-granuloma', 'periadnexal', 'superficial-and-deep', 'afb-positive'],
    hallmarks: ['tuberculoid-granuloma', 'periadnexal'],
    frequency: 2,
    summary: 'Placa anular hipocrômica com anestesia e borda elevada; granulomas epitelioides alongados que seguem nervos e anexos, com manguito linfocitário, tocando a epiderme, e nervo dérmico infiltrado ou destruído; bacilos ausentes ou raros.',
    clues: [
      'Granuloma linear "em salsicha" ao longo de um nervo, e nervo com infiltrado dentro do perineuro, são a assinatura (S100 mostra o nervo fragmentado).',
      'A hipocromia com anestesia é o dado clínico decisivo; sem neurologia, não é hanseníase.',
      'Reação reversa (tipo 1): edema no granuloma e na derme, células gigantes de Langhans em placa que incha de repente.',
    ],
    mimics: ['Sarcoidose: sem nervos, sem anestesia.', 'Tuberculose: caseificação, sem nervos.', 'Granuloma anular: paliçada e mucina.', 'Lúpus vulgar: face, história.'],
    next: ['Fite-Faraco, S100 para os nervos, teste de sensibilidade na lesão; classificação operacional e notificação.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'lepromatous-leprosy',
    name: 'Hanseníase virchowiana e dimorfa-virchowiana',
    aka: ['Hanseníase lepromatosa'],
    patterns: ['nodular-diffuse', 'granulomatous'],
    clinical: ['nodule', 'papule', 'face', 'generalized', 'travel', 'chronic', 'asymptomatic', 'hair-loss'],
    histology: ['foamy-histiocytes', 'diffuse-dermal-infiltrate', 'afb-positive', 'plasma-cells', 'periadnexal', 'sparse-infiltrate'],
    hallmarks: ['foamy-histiocytes', 'afb-positive'],
    frequency: 2,
    summary: 'Nódulos e infiltração difusa da face (fácies leonina), madarose e perda de sensibilidade em luvas e botas; derme cheia de histiócitos espumosos (células de Virchow) separados da epiderme por zona de Grenz, com globias de bacilos ao Fite.',
    clues: [
      'Macrófagos espumosos difusos com faixa de Grenz e epiderme atrófica: pedir Fite-Faraco antes de pensar em xantoma.',
      'Bacilos abundantes em globias, também dentro de nervos, vasos e músculo eretor.',
      'Eritema nodoso hansênico (reação tipo 2): neutrófilos, vasculite e paniculite sobre a base virchowiana.',
    ],
    mimics: ['Xantoma / xantogranuloma: histiócitos espumosos sem bacilos, lipídios.', 'Leishmaniose difusa anérgica: amastigotas.', 'Histoplasmose / paracoccidioidomicose: Grocott.', 'Linfoma: atipia linfoide.'],
    next: ['Fite-Faraco (Ziehl comum pode falhar), baciloscopia de lóbulo de orelha; notificação.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'cutaneous-leishmaniasis',
    name: 'Leishmaniose tegumentar',
    patterns: ['nodular-diffuse', 'granulomatous'],
    clinical: ['travel', 'ulcer', 'nodule', 'photoexposed', 'chronic', 'insect', 'mucosa', 'face', 'legs'],
    histology: ['parasite', 'plasma-cells', 'diffuse-dermal-infiltrate', 'sarcoidal-granuloma', 'tuberculoid-granuloma', 'acanthosis-irregular', 'necrotic-keratinocytes', 'suppurative-granuloma'],
    hallmarks: ['parasite', 'plasma-cells'],
    frequency: 2,
    summary: 'Úlcera de bordas elevadas em área exposta após viagem a mata ou zona rural; infiltrado difuso linfo-histioplasmocitário com amastigotas dentro dos macrófagos (lesões recentes) ou granulomas tuberculoides com poucos parasitos (lesões antigas e mucosas).',
    clues: [
      'Amastigotas de 2 a 4 µm com núcleo e cinetoplasto em barra, arranjadas na periferia do vacúolo do macrófago ("mostrador de relógio"); Giemsa e IHQ anti-Leishmania ajudam.',
      'Plasmócitos abundantes com granulomas mal formados: se não achar o parasito, procurar PCR.',
      'Hiperplasia pseudoepiteliomatosa na borda da úlcera pode enganar como carcinoma.',
    ],
    mimics: ['Histoplasmose: leveduras de tamanho semelhante, PAS/Grocott positivas, sem cinetoplasto.', 'Esporotricose / paracoccidioidomicose: Grocott.', 'Tuberculose / micobacteriose: Fite.', 'Sarcoidose: sem plasmócitos.', 'Carcinoma espinocelular: atipia verdadeira.'],
    next: ['Giemsa, IHQ ou PCR; intradermorreação de Montenegro; exame de mucosa nasal.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'deep-fungal-infection',
    name: 'Micoses profundas (paracoccidioidomicose, esporotricose, cromoblastomicose, histoplasmose, criptococose)',
    patterns: ['granulomatous', 'nodular-diffuse', 'neutrophilic'],
    clinical: ['travel', 'nodule', 'ulcer', 'chronic', 'immunosuppression', 'trauma', 'legs', 'mucosa', 'face', 'linear'],
    histology: ['suppurative-granuloma', 'pas-positive', 'acanthosis-irregular', 'tuberculoid-granuloma', 'foreign-body-giant-cells', 'plasma-cells', 'neutrophils-dermis', 'mucin'],
    hallmarks: ['pas-positive', 'suppurative-granuloma'],
    frequency: 2,
    summary: 'Placa verrucosa, nódulo linfangítico ou úlcera crônica em trabalhador rural; hiperplasia pseudoepiteliomatosa com microabscessos intraepidérmicos e granulomas supurativos, e o fungo (leveduras em roda de leme, corpos muriformes, corpos asteroides, cápsula mucoide) ao PAS/Grocott.',
    clues: [
      'Hiperplasia pseudoepiteliomatosa + microabscessos de neutrófilos + granulomas = "PEH-abscesso-granuloma": micose profunda, micobactéria, leishmaniose ou halogenoderma até prova em contrário.',
      'Paracoccidioides: leveduras grandes com brotamento múltiplo (roda de leme); cromoblastomicose: corpos muriformes marrons ao HE; esporotricose: leveduras em charuto raras, corpo asteroide; criptococo: cápsula com halo, mucicarmim; histoplasma: leveduras pequenas intracelulares.',
    ],
    mimics: ['Carcinoma espinocelular: atipia com invasão; a PEH não tem.', 'Micobacteriose atípica: idêntica, Fite.', 'Leishmaniose: amastigotas com cinetoplasto.', 'Halogenoderma / pioderma vegetante: sem organismo.'],
    next: ['PAS, Grocott, mucicarmim (criptococo), Fontana-Masson (fungos demáceos); cultura para fungos.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'granulomatous-rosacea',
    name: 'Rosácea granulomatosa / dermatite perioral',
    aka: ['Lupus miliaris disseminatus faciei'],
    patterns: ['granulomatous', 'folliculitis'],
    clinical: ['face', 'papule', 'pustule', 'chronic', 'female', 'telangiectasia', 'drug'],
    histology: ['sarcoidal-granuloma', 'tuberculoid-granuloma', 'periadnexal', 'demodex', 'dilated-vessels', 'folliculitis-lymphocytic', 'follicular-rupture', 'solar-elastosis'],
    hallmarks: ['periadnexal', 'demodex'],
    frequency: 2,
    summary: 'Pápulas monomórficas avermelhadas periorificiais ou nas bochechas, muitas vezes após corticoide tópico; granulomas epitelioides perifoliculares pequenos, às vezes com necrose central (lúpus miliar), com Demodex e vasos ectásicos.',
    clues: ['Granulomas centrados em folículos numa pele com telangiectasias e elastose: rosácea antes de sarcoidose.', 'Demodex no infundíbulo em quantidade.'],
    mimics: ['Sarcoidose: granulomas nus sem centralização folicular.', 'Lúpus vulgar: caseificação, bacilos por PCR, destrói.', 'Lúpus discoide: interface e membrana basal.', 'Dermatite seborreica: espongiose.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'cutaneous-crohn',
    name: 'Doença de Crohn cutânea / granulomatose orofacial',
    aka: ['Crohn metastático', 'Queilite granulomatosa de Miescher', 'Melkersson-Rosenthal'],
    patterns: ['granulomatous'],
    clinical: ['ibd', 'genital', 'flexural', 'mucosa', 'face', 'ulcer', 'nodule', 'chronic', 'child'],
    histology: ['sarcoidal-granuloma', 'superficial-and-deep', 'plasma-cells', 'papillary-edema', 'lymphoid-follicles', 'periadnexal'],
    hallmarks: ['sarcoidal-granuloma'],
    frequency: 1,
    summary: 'Edema labial persistente ou úlceras lineares "em faca" em dobras e genitais; granulomas epitelioides não caseosos pequenos e dispersos, com edema, linfócitos e plasmócitos, sem organismo.',
    clues: ['Granulomas esparsos "dissolvidos" num estroma edematoso com plasmócitos; não é o granuloma compacto da sarcoidose.', 'A doença intestinal pode vir depois da pele.'],
    mimics: ['Sarcoidose: granulomas densos e nus.', 'Hidradenite supurativa: folículos rotos, fístulas.', 'Infecção granulomatosa: colorações.', 'Tuberculose orificial: caseificação, bacilos.'],
    next: ['Calprotectina fecal e colonoscopia se ainda sem diagnóstico intestinal.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'annular-elastolytic-granuloma',
    name: 'Granuloma anular elastolítico de células gigantes',
    aka: ['Granuloma actínico de O\'Brien'],
    patterns: ['granulomatous'],
    clinical: ['photoexposed', 'annular', 'elderly', 'face', 'hands', 'chronic', 'asymptomatic', 'atrophy'],
    histology: ['foreign-body-giant-cells', 'elastophagocytosis', 'solar-elastosis', 'sarcoidal-granuloma', 'interstitial-histiocytes'],
    hallmarks: ['elastophagocytosis', 'solar-elastosis'],
    against: ['mucin', 'necrobiosis'],
    frequency: 1,
    summary: 'Anéis com borda elevada e centro atrófico em pele fotoexposta de idoso; células gigantes multinucleadas engolindo fibras elásticas na borda da lesão, com desaparecimento da elastose solar no centro, sem mucina nem necrobiose.',
    clues: ['Elastofagocitose evidente e centro sem fibras elásticas (orceína): três zonas.', 'Pode ser variante de granuloma anular em pele solar.'],
    mimics: ['Granuloma anular: mucina, paliçada.', 'Sarcoidose: granulomas compactos sem elastofagocitose.', 'Necrobiose lipoídica: necrobiose em camadas, pernas.'],
    next: ['Orceína ou Verhoeff para fibras elásticas.'],
    sources: [WEEDON],
  },
  {
    id: 'xanthoma',
    name: 'Xantomas',
    aka: ['Xantelasma', 'Xantoma eruptivo / tuberoso / tendíneo / plano'],
    patterns: ['nodular-diffuse', 'deposition'],
    clinical: ['papule', 'nodule', 'extensor', 'face', 'diabetes', 'liver', 'malignancy', 'asymptomatic', 'acute', 'chronic'],
    histology: ['foamy-histiocytes', 'foreign-body-giant-cells', 'sparse-infiltrate', 'neutrophils-dermis', 'sclerosis'],
    hallmarks: ['foamy-histiocytes'],
    against: ['afb-positive', 'necrobiosis'],
    frequency: 2,
    summary: 'Pápulas amarelas em surto (eruptivo, triglicérides) ou placas e nódulos amarelos crônicos (xantelasma, tuberoso, tendíneo, plano da gamopatia); histiócitos espumosos em derme, com lipídio extracelular e neutrófilos nas lesões eruptivas iniciais.',
    clues: ['Células espumosas com citoplasma vacuolado e núcleo pequeno, células gigantes de Touton nas formas tuberosas.', 'Xantoma eruptivo recente tem lipídio extracelular e neutrófilos; o histiócito espumoso vem depois.'],
    mimics: ['Hanseníase virchowiana: Fite.', 'Xantogranuloma juvenil: criança, Touton com coroa e infiltrado misto com eosinófilos.', 'Xantogranuloma necrobiótico: necrobiose, colesterol.', 'Histiocitose / doença de Erdheim-Chester: BRAF, contexto.'],
    next: ['Perfil lipídico; eletroforese de proteínas para xantoma plano difuso.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'sweet-syndrome',
    name: 'Síndrome de Sweet',
    aka: ['Dermatose neutrofílica febril aguda'],
    patterns: ['neutrophilic', 'nodular-diffuse'],
    clinical: ['acute', 'fever', 'pain', 'papule', 'nodule', 'face', 'hands', 'infection', 'malignancy', 'drug', 'ibd', 'pregnancy', 'female'],
    histology: ['neutrophils-dermis', 'papillary-edema', 'diffuse-dermal-infiltrate', 'subepidermal-neut', 'eosinophils', 'interstitial-histiocytes'],
    hallmarks: ['neutrophils-dermis', 'papillary-edema'],
    against: ['lcv', 'thrombi', 'bacteria', 'sarcoidal-granuloma'],
    frequency: 2,
    summary: 'Placas suculentas dolorosas de início abrupto em face, pescoço e braços com febre e neutrofilia; edema papilar intenso (às vezes bolha) sobre infiltrado neutrofílico denso e difuso na derme superior, com leucocitoclasia sem vasculite primária.',
    clues: [
      'Neutrófilos maduros em profusão com poeira nuclear e edema, mas vasos com parede íntegra: se houver fibrina, é vasculite secundária "de vizinhança".',
      'Variante histiocitoide: células mononucleares mieloides imaturas (MPO+) que enganam como histiócitos; pesquisar mielodisplasia.',
      'Gatilhos: infecção respiratória, G-CSF, azacitidina, leucemia mieloide, doença inflamatória intestinal, gestação.',
    ],
    mimics: [
      'Vasculite leucocitoclástica: fibrina na parede como achado central, púrpura.',
      'Pioderma gangrenoso: úlcera com abscesso profundo; contínuo clínico com Sweet.',
      'Infecção / celulite: bactérias, cultura; sempre excluir antes de corticoide.',
      'Leucemia cutânea: blastos; MPO/CD34/CD117 na variante histiocitoide.',
      'Urticária neutrofílica: infiltrado escasso, sem edema maciço.',
    ],
    next: ['Gram e cultura; hemograma e, se histiocitoide, mielograma; MPO/CD68 na dúvida.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'pyoderma-gangrenosum',
    name: 'Pioderma gangrenoso',
    patterns: ['neutrophilic', 'nodular-diffuse'],
    clinical: ['ulcer', 'pain', 'legs', 'trauma', 'ibd', 'arthralgia', 'malignancy', 'acute', 'pustule'],
    histology: ['neutrophils-dermis', 'diffuse-dermal-infiltrate', 'folliculitis-neutrophilic', 'fat-necrosis', 'lcv', 'thrombi', 'lymphocytic-superficial'],
    hallmarks: ['neutrophils-dermis'],
    against: ['bacteria', 'pas-positive', 'afb-positive'],
    frequency: 2,
    summary: 'Úlcera dolorosa de borda violácea solapada que cresce após trauma (patergia), com doença intestinal ou artrite; abscesso neutrofílico dérmico e subcutâneo sob a borda, com vasculite secundária, sem organismos.',
    clues: [
      'A borda da úlcera é o lugar de biopsiar: infiltrado neutrofílico denso que desce ao subcutâneo; o centro só mostra necrose.',
      'É diagnóstico de exclusão: colorações e cultura negativas, e resposta a imunossupressão.',
      'Variante pustulosa, bolhosa (hematológica) e vegetante (superficial).',
    ],
    mimics: ['Infecção (bacteriana, micobactéria, fungo): cultura e colorações; nunca assinar pioderma sem excluir.', 'Sweet: sem úlcera, edema papilar.', 'Vasculite / vasculopatia: vasculite como achado central, trombos.', 'Úlcera factícia: forma geométrica, sem infiltrado profundo.', 'Calcifilaxia: cálcio vascular.'],
    next: ['Gram, PAS/Grocott, Fite e cultura da borda; rastreio de DII, artrite e gamopatia.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'behcet',
    name: 'Doença de Behçet',
    patterns: ['neutrophilic', 'vasculitis'],
    clinical: ['mucosa', 'genital', 'ulcer', 'pustule', 'subcutaneous-nodule', 'legs', 'arthralgia', 'trauma', 'young-adult', 'relapsing', 'travel'],
    histology: ['neutrophils-dermis', 'lcv', 'lymphocytic-vasculitis', 'folliculitis-neutrophilic', 'septal-panniculitis', 'thrombi', 'subcorneal-pustule'],
    frequency: 1,
    summary: 'Aftas orais e genitais recorrentes com pseudofoliculite, eritema nodoso-símile e patergia; dermatose neutrofílica com vasculite de vênulas (leucocitoclástica ou linfocitária) e tromboflebite.',
    clues: ['Lesão papulopustulosa com neutrófilos e vasculite (foliculite "que não é foliculite").', 'Nódulos das pernas: paniculite septal e lobular com vasculite, ao contrário do eritema nodoso.'],
    mimics: ['Foliculite bacteriana: sem vasculite, Gram.', 'Eritema nodoso: sem vasculite.', 'Sweet: sem vasculite primária.', 'Aftose complexa isolada: clínica.'],
    next: ['Teste de patergia; HLA-B51; exame oftalmológico.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'bowel-associated-dermatosis',
    name: 'Síndrome dermatose-artrite associada ao intestino / dermatose neutrofílica das mãos',
    aka: ['Bowel bypass syndrome', 'Neutrophilic dermatosis of the dorsal hands', 'Vasculite pustulosa das mãos'],
    patterns: ['neutrophilic'],
    clinical: ['hands', 'pustule', 'arthralgia', 'ibd', 'trauma', 'acute', 'relapsing', 'fever'],
    histology: ['neutrophils-dermis', 'papillary-edema', 'subcorneal-pustule', 'lcv', 'diffuse-dermal-infiltrate'],
    hallmarks: ['neutrophils-dermis'],
    frequency: 1,
    summary: 'Pápulas e pústulas hemorrágicas no dorso das mãos (com ou sem artrite e cirurgia bariátrica ou DII); infiltrado neutrofílico dérmico denso com edema, pústula e vasculite leucocitoclástica focal, no espectro do Sweet.',
    clues: ['Sweet localizado nas mãos, com mais vasculite do que o habitual.', 'Antibiótico melhora quando há alça cega.'],
    mimics: ['Sweet: mesma lâmina, distribuição diferente.', 'Vasculite leucocitoclástica: vasculite como achado central.', 'Infecção (gonococcemia, micobactéria): cultura.', 'Pioderma gangrenoso: úlcera.'],
    sources: [WEEDON],
  },
  {
    id: 'wells-syndrome',
    name: 'Síndrome de Wells',
    aka: ['Celulite eosinofílica'],
    patterns: ['nodular-diffuse', 'perivascular-deep'],
    clinical: ['acute', 'relapsing', 'itch', 'pain', 'legs', 'trunk', 'insect', 'drug', 'child'],
    histology: ['eosinophils', 'flame-figures', 'diffuse-dermal-infiltrate', 'papillary-edema', 'superficial-and-deep', 'foreign-body-giant-cells', 'eosinophilic-spongiosis'],
    hallmarks: ['flame-figures', 'eosinophils'],
    against: ['lcv', 'neutrophils-dermis'],
    frequency: 1,
    summary: 'Placas edematosas que parecem celulite mas não respondem a antibiótico, em surtos; eosinófilos difusos pela derme e subcutâneo com figuras em chama (colágeno recoberto de grânulos eosinofílicos) rodeadas de histiócitos e células gigantes nas lesões evoluídas.',
    clues: ['Figuras em chama são sugestivas, não específicas: aparecem em picadas, penfigoide, dermatite herpetiforme, foliculite eosinofílica e parasitoses.', 'Sem vasculite e sem organismos; eosinofilia periférica.'],
    mimics: ['Picada de artrópode: cunha, poucas figuras em chama, história.', 'Celulite bacteriana: neutrófilos, febre, cultura.', 'Urticária: infiltrado escasso.', 'Síndrome hipereosinofílica / linfoma T: atipia, contexto sistêmico.', 'Penfigoide bolhoso urticariforme: IF linear.'],
    next: ['Hemograma, parasitológico e revisão de fármacos.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'mastocytosis',
    name: 'Mastocitose cutânea',
    aka: ['Urticária pigmentosa', 'Mastocitoma', 'Telangiectasia macular eruptiva perstante'],
    patterns: ['invisible', 'nodular-diffuse', 'perivascular-superficial'],
    clinical: ['child', 'hyperpigmented', 'macule', 'papule', 'nodule', 'itch', 'trunk', 'wheal', 'chronic', 'relapsing'],
    histology: ['mast-cells', 'sparse-infiltrate', 'eosinophils', 'pigment-incontinence', 'diffuse-dermal-infiltrate', 'papillary-edema', 'dilated-vessels'],
    hallmarks: ['mast-cells'],
    frequency: 2,
    summary: 'Máculas acastanhadas que urticam à fricção (Darier) em criança, ou nódulo solitário; mastócitos em número aumentado ao redor de vasos e entre feixes de colágeno na derme papilar, com hiperpigmentação basal e eosinófilos, muitas vezes tão sutis que a lâmina parece normal.',
    clues: ['Células ovais ou fusiformes de núcleo central e citoplasma granular anfofílico "em ovo frito" em fila perivascular; Giemsa, triptase ou CD117 confirmam.', 'Mastocitoma e forma difusa: infiltrado denso de mastócitos por toda a derme.'],
    mimics: ['Urticária: sem aumento de mastócitos (comparar com pele normal).', 'Dermatose invisível / lâmina normal: pedir triptase se a clínica sugerir.', 'Histiocitose de Langerhans: CD1a, S100; criança.', 'Leucemia mastocítica / mastocitose sistêmica: CD25 e CD2 aberrantes, triptase sérica.'],
    next: ['Giemsa ou azul de toluidina, CD117 e triptase; CD25 se adulto (sistêmica); triptase sérica.'],
    sources: [WEEDON, WHO_HEME],
  },
  {
    id: 'cutaneous-lymphoid-hyperplasia',
    name: 'Hiperplasia linfoide cutânea (pseudolinfoma)',
    aka: ['Linfocitoma cutis', 'Pseudolinfoma B', 'Infiltrado linfocitário de Jessner'],
    patterns: ['nodular-diffuse', 'perivascular-deep'],
    clinical: ['face', 'nodule', 'papule', 'chronic', 'asymptomatic', 'insect', 'trauma', 'drug', 'young-adult', 'female'],
    histology: ['lymphoid-follicles', 'superficial-and-deep', 'plasma-cells', 'eosinophils', 'periadnexal', 'diffuse-dermal-infiltrate'],
    hallmarks: ['lymphoid-follicles'],
    against: ['atypical-lymphocytes', 'epidermotropism', 'mucin'],
    frequency: 2,
    summary: 'Nódulo ou placa avermelhada na face ou orelha, às vezes após picada, tatuagem ou vacina; infiltrado linfoide denso "de cima para baixo" com folículos reativos de centros germinativos polarizados, macrófagos de corpo tingível e mistura de células (plasmócitos, eosinófilos, histiócitos).',
    clues: ['Folículos com manto e centro germinativo bem formados, infiltrado mais denso na derme superior, zona de Grenz, células mistas.', 'Jessner: infiltrado linfocitário perivascular e periadnexal profundo sem folículos e sem mucina, na face.'],
    mimics: [
      'Linfoma B de centro folicular / zona marginal: folículos sem manto, "de baixo para cima", BCL2+ nos centros, restrição de cadeia leve, clone IgH.',
      'Lúpus túmido: mucina.',
      'Erupção polimorfa à luz: edema papilar.',
      'Borreliose: plasmócitos, sorologia; linfocitoma do lobo da orelha em criança.',
    ],
    next: ['IHQ CD20/CD3/CD10/BCL6/BCL2/kappa/lambda; clonalidade IgH quando a morfologia não fechar.'],
    sources: [WEEDON, WHO_HEME],
  },
  {
    id: 'langerhans-cell-histiocytosis',
    name: 'Histiocitose de células de Langerhans',
    patterns: ['nodular-diffuse', 'spongiotic'],
    clinical: ['child', 'seborrheic', 'flexural', 'scalp', 'papule', 'petechiae', 'ulcer', 'chronic', 'fever'],
    histology: ['diffuse-dermal-infiltrate', 'eosinophils', 'epidermotropism', 'rbc-extravasation', 'crust', 'papillary-edema'],
    frequency: 1,
    summary: 'Erupção "seborreica" petequial e crostosa em couro cabeludo e dobras de lactente que não melhora, ou pápulas ulceradas em adulto; células grandes de núcleo reniforme com sulco e citoplasma róseo preenchendo a derme papilar e invadindo a epiderme, com eosinófilos e hemácias extravasadas.',
    clues: ['Células de Langerhans com núcleo em feijão ou café e citoplasma abundante em faixa sob a epiderme: CD1a, langerina (CD207) e S100 positivos.', 'Dermatite seborreica com petéquias em bebê é histiocitose até prova em contrário.'],
    mimics: ['Dermatite seborreica: espongiose com paraceratose folicular, sem células grandes.', 'Escabiose: eosinófilos, ácaro.', 'Xantogranuloma juvenil: Touton, CD1a negativo.', 'Mastocitose: CD117.', 'Micose fungoide: CD3.'],
    next: ['CD1a, langerina, S100; BRAF V600E; investigação sistêmica (osso, hipófise, fígado).'],
    sources: [WEEDON, WHO_HEME],
  },
  {
    id: 'rosai-dorfman',
    name: 'Doença de Rosai-Dorfman cutânea',
    aka: ['Histiocitose sinusal com linfadenopatia maciça'],
    patterns: ['nodular-diffuse'],
    clinical: ['nodule', 'papule', 'face', 'trunk', 'chronic', 'asymptomatic', 'female'],
    histology: ['diffuse-dermal-infiltrate', 'plasma-cells', 'lymphoid-follicles', 'foamy-histiocytes', 'neutrophils-dermis', 'sclerosis'],
    frequency: 1,
    summary: 'Pápulas e nódulos vermelho-amarelados isolados sem linfadenopatia (forma cutânea pura); histiócitos enormes de citoplasma pálido com linfócitos e plasmócitos íntegros dentro (emperipolese), num fundo linfoplasmocitário com fibrose.',
    clues: ['Emperipolese em histiócitos S100+ e CD68+, CD1a negativos, com muitos plasmócitos ao redor.', 'Pode imitar xantoma ou pseudolinfoma em pequeno aumento.'],
    mimics: ['Histiocitose de Langerhans: CD1a+.', 'Xantogranuloma: sem emperipolese, S100 negativo.', 'Hanseníase virchowiana: Fite.', 'Pseudolinfoma: sem histiócitos gigantes.'],
    next: ['S100, CD68, CD1a.'],
    sources: [WEEDON, WHO_HEME],
  },
]
