/* ==========================================================================
   content/panniculitis.ts — paniculites septais e lobulares, com e sem
   vasculite, e os processos que se apresentam como nódulo subcutâneo
   inflamatório (calcifilaxia, linfoma paniculite-símile).
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const REQUENA = 'Requena & Sánchez Yus: Panniculitis, J Am Acad Dermatol 2001;45:163-183 e 325-361'
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'
const WHO_HEME = 'WHO Classification of Haematolymphoid Tumours, 5ª ed. (2024)'

export const panniculitis: Diagnosis[] = [
  {
    id: 'erythema-nodosum',
    name: 'Eritema nodoso',
    patterns: ['panniculitis-septal'],
    clinical: ['subcutaneous-nodule', 'legs', 'extensor', 'female', 'young-adult', 'acute', 'pain', 'fever', 'arthralgia', 'infection', 'drug', 'ibd', 'pregnancy'],
    histology: ['septal-panniculitis', 'miescher', 'neutrophils-dermis', 'foreign-body-giant-cells', 'septal-fibrosis', 'lymphoid-follicles', 'eosinophils', 'rbc-extravasation'],
    hallmarks: ['septal-panniculitis', 'miescher'],
    against: ['medium-vessel-vasculitis', 'fat-necrosis', 'lipomembranous', 'lcv', 'afb-positive'],
    frequency: 3,
    summary: 'Nódulos dolorosos, quentes e contusiformes nas faces anteriores das pernas, que não ulceram e regridem em semanas; paniculite septal sem vasculite: septos edemaciados e infiltrados (neutrófilos no início, linfócitos, histiócitos e células gigantes depois) com granulomas radiais de Miescher, e lóbulos poupados exceto na periferia.',
    clues: [
      'Granulomas de Miescher: pequenos agregados nodulares de histiócitos em torno de uma fenda central, nos septos ou na borda do lóbulo.',
      'Septos alargados com lóbulos íntegros; nas lesões velhas os septos fibrosam e o infiltrado invade a periferia do lóbulo, sem necrose gordurosa relevante.',
      'Gatilhos: estreptococo, sarcoidose (Löfgren), tuberculose, DII, fármacos, gestação, paracoccidioidomicose.',
    ],
    mimics: [
      'Eritema induratum / vasculite nodular: lobular com vasculite e necrose caseosa, panturrilha, ulcera.',
      'Poliarterite nodosa cutânea: arterite necrosante de vaso septal.',
      'Morfeia profunda / fasciíte: septos esclerosados com plasmócitos, sem Miescher.',
      'Paniculite infecciosa: neutrófilos lobulares com organismos.',
      'Tromboflebite superficial: veia com trombo.',
    ],
    next: ['Biópsia incisional profunda; radiografia de tórax, ASLO e IGRA conforme clínica.'],
    sources: [WEEDON, REQUENA],
  },
  {
    id: 'erythema-induratum',
    name: 'Eritema induratum de Bazin / vasculite nodular',
    patterns: ['panniculitis-lobular', 'vasculitis', 'granulomatous'],
    clinical: ['legs', 'subcutaneous-nodule', 'female', 'ulcer', 'chronic', 'relapsing', 'cold', 'travel', 'pain'],
    histology: ['lobular-panniculitis', 'medium-vessel-vasculitis', 'fat-necrosis', 'tuberculoid-granuloma', 'suppurative-granuloma', 'foreign-body-giant-cells', 'lcv', 'foamy-histiocytes'],
    hallmarks: ['lobular-panniculitis', 'medium-vessel-vasculitis'],
    against: ['miescher', 'afb-positive', 'lipomembranous'],
    frequency: 2,
    summary: 'Nódulos na face posterior das pernas de mulher, que ulceram e deixam cicatriz, em surtos no inverno; paniculite lobular ou mista com vasculite de vênulas ou artérias do septo, necrose gordurosa caseosa e granulomas, sem bacilos (tubercúlide) ou de outra causa (vasculite nodular).',
    clues: ['Lóbulo necrótico com granulomas e um vaso do septo lesado: a vasculite pode exigir cortes seriados.', 'PCR para M. tuberculosis positiva em boa parte; bacilos quase nunca são vistos.'],
    mimics: ['Eritema nodoso: septal, sem vasculite, sem necrose, anterior.', 'Poliarterite nodosa: arterite sem paniculite lobular difusa.', 'Paniculite lúpica: necrose hialina, linfócitos, plasmócitos.', 'Paniculite infecciosa: organismos.'],
    next: ['Ziehl, PCR para micobactérias, IGRA e radiografia de tórax.'],
    sources: [WEEDON, REQUENA],
  },
  {
    id: 'lupus-panniculitis',
    name: 'Paniculite lúpica',
    aka: ['Lúpus profundo'],
    patterns: ['panniculitis-lobular'],
    clinical: ['subcutaneous-nodule', 'face', 'trunk', 'extensor', 'female', 'chronic', 'atrophy', 'autoimmune', 'pain'],
    histology: ['lobular-panniculitis', 'hyaline-fat-necrosis', 'lymphoid-follicles', 'plasma-cells', 'mucin', 'vacuolar', 'calcification', 'periadnexal', 'dif-lupus-band'],
    hallmarks: ['hyaline-fat-necrosis', 'lymphoid-follicles'],
    against: ['neutrophils-dermis', 'medium-vessel-vasculitis', 'lipomembranous', 'rimming-lymphocytes'],
    frequency: 1,
    summary: 'Nódulos profundos em face, braços proximais, ombros e nádegas que deixam depressões lipoatróficas; paniculite lobular linfocitária com necrose hialina da gordura, agregados linfoides com centros germinativos, plasmócitos, mucina e, na metade dos casos, lúpus discoide na pele sobrejacente.',
    clues: ['Necrose hialina eosinofílica "vítrea" dos adipócitos com folículos linfoides e plasmócitos nos septos; calcificação em lesões velhas.', 'Diferencial mais difícil: linfoma T paniculite-símile. Procurar atipia, rimming, CD8 monótono, Ki-67 alto e clone.'],
    mimics: ['Linfoma T subcutâneo paniculite-símile: linfócitos atípicos CD8+ contornando adipócitos, cariorrexe, Ki-67 alto nos que contornam, sem folículos B nem plasmócitos, TCR clonal.', 'Morfeia profunda: septal fibrosante.', 'Eritema induratum: vasculite e granulomas.', 'Lipoatrofia por injeção: história de corticoide ou insulina.'],
    next: ['CD3/CD4/CD8/CD20/Ki-67/βF1 e rearranjo do TCR quando houver dúvida com linfoma; FAN.'],
    sources: [WEEDON, WHO_HEME],
  },
  {
    id: 'sptcl',
    name: 'Linfoma T subcutâneo paniculite-símile',
    aka: ['SPTCL'],
    patterns: ['panniculitis-lobular'],
    clinical: ['subcutaneous-nodule', 'legs', 'trunk', 'fever', 'young-adult', 'chronic', 'malignancy', 'female', 'autoimmune'],
    histology: ['lobular-panniculitis', 'rimming-lymphocytes', 'atypical-lymphocytes', 'fat-necrosis', 'foamy-histiocytes'],
    hallmarks: ['rimming-lymphocytes', 'atypical-lymphocytes'],
    against: ['lymphoid-follicles', 'plasma-cells', 'medium-vessel-vasculitis'],
    frequency: 1,
    summary: 'Nódulos subcutâneos múltiplos em pernas e tronco, às vezes com febre e citopenias (síndrome hemofagocítica), em paciente jovem com ou sem lúpus; linfócitos atípicos de tamanho variado que contornam adipócitos individuais ("rimming"), com cariorrexe, macrófagos com corpos apoptóticos ("bean-bag cells") e sem envolvimento da derme.',
    clues: ['Rimming de linfócitos CD8+ com Ki-67 alto restrito às células que contornam a gordura; βF1+, CD56 negativo, EBV negativo.', 'Ausência de plasmócitos e de folículos B, ao contrário da paniculite lúpica; as duas podem coexistir.'],
    mimics: ['Paniculite lúpica: folículos B, plasmócitos, necrose hialina, mucina, Ki-67 baixo.', 'Linfoma T γδ cutâneo: CD56+, γδ+, epidermotropismo, mais agressivo.', 'Paniculite histiocítica citofágica: hoje considerada a mesma entidade com hemofagocitose.'],
    next: ['IHQ CD3/CD4/CD8/CD56/βF1/TCRδ/Ki-67, EBER e rearranjo do TCR; ferritina e hemograma.'],
    sources: [WHO_HEME, WEEDON],
  },
  {
    id: 'pancreatic-panniculitis',
    name: 'Paniculite pancreática',
    patterns: ['panniculitis-lobular'],
    clinical: ['subcutaneous-nodule', 'legs', 'liver', 'malignancy', 'arthralgia', 'acute', 'ulcer', 'male', 'pain'],
    histology: ['lobular-panniculitis', 'saponification', 'fat-necrosis', 'calcification', 'neutrophils-dermis', 'foreign-body-giant-cells'],
    hallmarks: ['saponification'],
    frequency: 1,
    summary: 'Nódulos em pernas que drenam material oleoso, com artrite e pancreatite ou carcinoma acinar do pâncreas (lipase alta); necrose lobular com "adipócitos fantasma" (membranas sem núcleo) e saponificação basofílica granular por cálcio, com neutrófilos ao redor.',
    clues: ['Adipócitos fantasma e material basofílico calcificado dentro do lóbulo necrótico: quase patognomônico.', 'Tríade de Schmid: paniculite, artrite, eosinofilia; lipase e amilase.'],
    mimics: ['Necrose gordurosa traumática: sem saponificação difusa, história.', 'Deficiência de alfa-1 antitripsina: lóbulos "dissolvidos" com neutrófilos, sem fantasmas, sem cálcio.', 'Calcifilaxia: cálcio vascular, não nos adipócitos.'],
    next: ['Lipase e amilase séricas; imagem do pâncreas.'],
    sources: [WEEDON, REQUENA],
  },
  {
    id: 'alpha1-antitrypsin-panniculitis',
    name: 'Paniculite por deficiência de alfa-1 antitripsina',
    patterns: ['panniculitis-lobular', 'neutrophilic'],
    clinical: ['subcutaneous-nodule', 'trunk', 'legs', 'ulcer', 'trauma', 'young-adult', 'relapsing', 'family', 'liver'],
    histology: ['lobular-panniculitis', 'neutrophils-dermis', 'fat-necrosis', 'septal-panniculitis', 'diffuse-dermal-infiltrate'],
    hallmarks: ['neutrophils-dermis', 'fat-necrosis'],
    frequency: 1,
    summary: 'Nódulos que ulceram e drenam material oleoso após trauma em tronco e coxas de adulto jovem, com enfisema ou hepatopatia familiar; paniculite neutrofílica com necrose liquefativa que "dissolve" lóbulos e septos, deixando ilhas de gordura normal flutuando em neutrófilos, e infiltrado que invade a derme reticular.',
    clues: ['Necrose com neutrófilos que separa septos de lóbulos (splaying) e lóbulos normais lado a lado com lóbulos destruídos.', 'Dosagem e fenótipo de alfa-1 antitripsina (ZZ).'],
    mimics: ['Paniculite infecciosa: organismos, cultura.', 'Paniculite pancreática: fantasmas e cálcio.', 'Paniculite factícia: material estranho, polarização.', 'Pioderma gangrenoso: começa na derme.'],
    next: ['Alfa-1 antitripsina sérica e fenotipagem; Gram, PAS e cultura.'],
    sources: [WEEDON, REQUENA],
  },
  {
    id: 'neonatal-fat-necrosis',
    name: 'Necrose gordurosa subcutânea do recém-nascido / esclerema neonatal',
    patterns: ['panniculitis-lobular'],
    clinical: ['child', 'subcutaneous-nodule', 'trunk', 'extensor', 'acute', 'trauma', 'cold', 'asymptomatic', 'sclerosis'],
    histology: ['lobular-panniculitis', 'needle-clefts', 'fat-necrosis', 'foreign-body-giant-cells', 'calcification', 'eosinophils'],
    hallmarks: ['needle-clefts'],
    frequency: 1,
    summary: 'Nódulos endurecidos em dorso, nádegas e bochechas de recém-nascido a termo após parto difícil ou hipotermia terapêutica (necrose gordurosa, benigna, com risco de hipercalcemia) ou endurecimento difuso e frio em prematuro grave (esclerema, sem inflamação); fendas em agulha radiais dentro de adipócitos e células gigantes, com paniculite granulomatosa e calcificação na necrose gordurosa.',
    clues: ['Cristais em agulha em roseta dentro dos adipócitos e das células gigantes = gordura neonatal saturada cristalizada.', 'Esclerema: as mesmas agulhas com septos espessos e quase sem inflamação.'],
    mimics: ['Paniculite pós-esteroide: mesmas agulhas em criança após retirada de corticoide.', 'Paniculite pelo frio: sem cristais, ao redor de vasos.', 'Celulite: neutrófilos, febre.'],
    next: ['Cálcio sérico seriado por semanas.'],
    sources: [WEEDON, REQUENA],
  },
  {
    id: 'cold-panniculitis',
    name: 'Paniculite pelo frio',
    aka: ['Paniculite do picolé', 'Paniculite equestre'],
    patterns: ['panniculitis-lobular'],
    clinical: ['cold', 'child', 'face', 'legs', 'subcutaneous-nodule', 'acute', 'female', 'young-adult'],
    histology: ['lobular-panniculitis', 'lymphocytic-superficial', 'fat-necrosis', 'superficial-and-deep', 'papillary-edema'],
    frequency: 1,
    summary: 'Nódulos nas bochechas de lactente após picolé ou nas coxas de mulher jovem após cavalgar no frio; paniculite lobular linfo-histiocitária na junção dermo-hipodérmica com necrose gordurosa discreta e infiltrado perivascular na derme.',
    clues: ['Inflamação concentrada na interface derme-gordura, mais rica em linfócitos que em neutrófilos, sem cristais.', 'História de exposição ao frio 1 a 3 dias antes.'],
    mimics: ['Necrose gordurosa neonatal: cristais em agulha.', 'Perniose: derme, sem paniculite proeminente.', 'Eritema nodoso: septal.', 'Paniculite lúpica: necrose hialina e folículos.'],
    sources: [WEEDON, REQUENA],
  },
  {
    id: 'traumatic-factitial-panniculitis',
    name: 'Paniculite traumática, factícia e por injeção',
    aka: ['Lipogranuloma esclerosante', 'Paniculite por óleo / silicone', 'Necrose gordurosa traumática'],
    patterns: ['panniculitis-lobular', 'granulomatous'],
    clinical: ['trauma', 'subcutaneous-nodule', 'ulcer', 'legs', 'trunk', 'genital', 'chronic', 'female', 'asymptomatic'],
    histology: ['lobular-panniculitis', 'fat-necrosis', 'foreign-body-giant-cells', 'lipomembranous', 'polarizable', 'sclerosis', 'foamy-histiocytes', 'neutrophils-dermis', 'calcification'],
    hallmarks: ['foreign-body-giant-cells', 'fat-necrosis'],
    frequency: 2,
    summary: 'Nódulos endurecidos em sítio de injeção, trauma ou aplicação de substância; necrose gordurosa com lipófagos e células gigantes ao redor de vacúolos de tamanhos variados (óleo, silicone: "queijo suíço"), fibrose, hemossiderina e às vezes material estranho polarizável.',
    clues: ['Vacúolos de tamanhos discrepantes cercados por células gigantes e fibrose: substância injetada; polarizar sempre.', 'Necrose traumática da mama e de coxas: lipófagos, cistos oleosos e calcificação.'],
    mimics: ['Eritema nodoso: septal com Miescher.', 'Paniculite pancreática: fantasmas e saponificação.', 'Lipodermatoesclerose: estase, lipomembranosa.', 'Deficiência de alfa-1 antitripsina: neutrófilos difusos.'],
    next: ['Luz polarizada; perguntar por injeções, preenchimentos e automanipulação.'],
    sources: [WEEDON, REQUENA],
  },
  {
    id: 'infectious-panniculitis',
    name: 'Paniculite infecciosa',
    patterns: ['panniculitis-lobular', 'neutrophilic'],
    clinical: ['immunosuppression', 'subcutaneous-nodule', 'ulcer', 'fever', 'legs', 'trauma', 'acute', 'travel', 'pain'],
    histology: ['lobular-panniculitis', 'neutrophils-dermis', 'fat-necrosis', 'bacteria', 'pas-positive', 'afb-positive', 'suppurative-granuloma', 'rbc-extravasation', 'thrombi'],
    hallmarks: ['neutrophils-dermis', 'fat-necrosis'],
    frequency: 2,
    summary: 'Nódulos flutuantes ou úlceras em imunossuprimido, ou celulite profunda após trauma; paniculite mista neutrofílica com necrose, hemorragia e trombose vascular, e organismos ao Gram, PAS ou Ziehl (bactérias, micobactérias rápidas, fungos oportunistas, Nocardia).',
    clues: ['Neutrófilos por todo o lóbulo e septo com necrose e vasos trombosados: pedir todas as colorações e reservar tecido para cultura.', 'Micobactérias de crescimento rápido após injeção ou lipoaspiração.'],
    mimics: ['Deficiência de alfa-1 antitripsina: sem organismos, jovem, fenótipo ZZ.', 'Paniculite pancreática: fantasmas.', 'Pioderma gangrenoso: começa na derme, sem organismos.', 'Eritema nodoso: septal.'],
    next: ['Gram, PAS/Grocott, Ziehl/Fite; cultura para bactérias, micobactérias e fungos.'],
    sources: [WEEDON, REQUENA],
  },
  {
    id: 'calciphylaxis',
    name: 'Calcifilaxia',
    aka: ['Arteriolopatia urêmica calcificante'],
    patterns: ['vasculitis', 'panniculitis-lobular'],
    clinical: ['renal', 'diabetes', 'livedo', 'ulcer', 'pain', 'legs', 'trunk', 'acute', 'female', 'drug'],
    histology: ['calcification', 'thrombi', 'fat-necrosis', 'lobular-panniculitis', 'neutrophils-dermis', 'full-thickness-necrosis', 'septal-panniculitis'],
    hallmarks: ['calcification', 'thrombi'],
    frequency: 1,
    summary: 'Placas retiformes muito dolorosas que necrosam em áreas adiposas (coxas, abdome) de dialítico com hiperparatireoidismo ou em uso de varfarina; calcificação da média de arteríolas do subcutâneo com fibrose intimal e trombos, necrose isquêmica da gordura e da pele, com ou sem calcificação de adipócitos e fibras.',
    clues: ['Cálcio na parede de arteríolas pequenas do subcutâneo (von Kossa se discreto), com trombose e infarto: biópsia profunda incisional, evitando a lesão necrótica central.', 'Calcificação extravascular fina ("em rede") ao redor dos adipócitos é sinal precoce.'],
    mimics: ['Vasculopatia trombótica (varfarina, antifosfolípide): trombos sem cálcio.', 'Êmbolos de colesterol: fendas em agulha.', 'Paniculite pancreática: cálcio nos adipócitos, não nos vasos.', 'Úlcera arterial: aterosclerose de vaso grande.'],
    next: ['von Kossa ou alizarina; cálcio, fósforo, PTH; revisar varfarina.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'erythema-nodosum-leprosum',
    name: 'Eritema nodoso hansênico (reação tipo 2)',
    patterns: ['neutrophilic', 'panniculitis-lobular', 'vasculitis'],
    clinical: ['travel', 'fever', 'subcutaneous-nodule', 'nodule', 'pain', 'arthralgia', 'acute', 'relapsing', 'drug', 'generalized'],
    histology: ['neutrophils-dermis', 'foamy-histiocytes', 'afb-positive', 'lcv', 'lobular-panniculitis', 'papillary-edema', 'diffuse-dermal-infiltrate'],
    hallmarks: ['neutrophils-dermis', 'foamy-histiocytes'],
    frequency: 1,
    summary: 'Nódulos dolorosos disseminados com febre, neurite e artrite em paciente virchowiano, com frequência ao iniciar o tratamento; infiltrado neutrofílico difuso na derme e subcutâneo sobre o fundo de histiócitos espumosos com bacilos fragmentados, muitas vezes com vasculite leucocitoclástica.',
    clues: ['Neutrófilos abundantes em cima de células de Virchow: Fite mostra bacilos granulosos (mortos).', 'Não é eritema nodoso clássico: é lobular, neutrofílico e com vasculite.'],
    mimics: ['Sweet: sem histiócitos espumosos nem bacilos.', 'Eritema nodoso: septal.', 'Vasculite leucocitoclástica: sem fundo virchowiano.'],
    next: ['Fite-Faraco; notificar e classificar a reação.'],
    sources: [WEEDON, MCKEE],
  },
]
