/* ==========================================================================
   content/psoriasiform.ts — psoríase e o que a imita: PRP, líquen simples,
   sífilis secundária, micose fungoide, dermatoses nutricionais e as
   papilomatoses "invisíveis" que também são psoriasiformes.
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const ACKERMAN = 'Ackerman: Histologic Diagnosis of Inflammatory Skin Diseases, 3ª ed. (2005)'
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'
const WHO_HEME = 'WHO Classification of Haematolymphoid Tumours, 5ª ed. (2024)'

export const psoriasiform: Diagnosis[] = [
  {
    id: 'psoriasis-vulgaris',
    name: 'Psoríase vulgar',
    aka: ['Psoríase em placas'],
    patterns: ['psoriasiform'],
    clinical: ['chronic', 'scaly-plaque', 'extensor', 'scalp', 'nails', 'family', 'linear', 'young-adult'],
    histology: ['parakeratosis-confluent', 'neutrophils-corneum', 'hypogranulosis', 'acanthosis-regular', 'thin-suprapapillary', 'dilated-vessels', 'kogoj', 'lymphocytic-superficial', 'papillary-edema'],
    hallmarks: ['neutrophils-corneum', 'hypogranulosis', 'thin-suprapapillary'],
    against: ['eosinophils', 'spongiotic-vesicle', 'hyphae', 'plasma-cells'],
    frequency: 3,
    summary: 'Placas eritemato-escamosas de extensores e couro cabeludo; acantose psoriasiforme regular com paraceratose confluente, microabscessos de Munro, hipogranulose e capilares dilatados sob placas suprapapilares finas.',
    clues: [
      'Neutrófilos na paraceratose (Munro) e na camada espinhosa (Kogoj) são o dado mais específico.',
      'Hipogranulose sob a paraceratose; cristas alongadas de altura uniforme com placas suprapapilares afinadas.',
      'Lesão inicial (gutata) tem mais espongiose e menos acantose; a lesão tratada perde os neutrófilos.',
    ],
    mimics: [
      'Dermatofitose: também tem neutrófilos na córnea; PAS obrigatório na primeira biópsia.',
      'Dermatite seborreica: espongiose, paraceratose folicular, granulosa preservada.',
      'Líquen simples crônico: acantose irregular, hipergranulose, fibrose papilar vertical.',
      'Pitiríase rubra pilar: orto e paraceratose alternadas, tampões foliculares, sem neutrófilos.',
      'Sífilis secundária: plasmócitos, interface, IHQ Treponema.',
      'Erupção psoriasiforme por fármaco (betabloqueador, anti-TNF): eosinófilos, dano de interface.',
    ],
    next: ['PAS na primeira vez.', 'Se eosinófilos, revisar medicamentos.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'guttate-psoriasis',
    name: 'Psoríase gutata',
    patterns: ['psoriasiform', 'spongiotic'],
    clinical: ['child', 'young-adult', 'acute', 'infection', 'trunk', 'papule', 'scaly-plaque'],
    histology: ['parakeratosis-focal', 'neutrophils-corneum', 'spongiosis', 'lymphocytic-superficial', 'dilated-vessels', 'hypogranulosis', 'acanthosis-regular'],
    hallmarks: ['neutrophils-corneum'],
    against: ['eosinophils', 'plasma-cells'],
    frequency: 2,
    summary: 'Pápulas em gota após faringite estreptocócica; psoríase jovem com espongiose, montículos de paraceratose com neutrófilos e acantose ainda discreta.',
    clues: ['Montículos de paraceratose com neutrófilos sobre epiderme pouco espessada; muitas vezes só isso.', 'Mais espongiose que na placa madura.'],
    mimics: [
      'Pitiríase rósea: hemácias extravasadas, sem neutrófilos.',
      'Pitiríase liquenoide crônica: interface, paraceratose confluente sem neutrófilos.',
      'Sífilis secundária: plasmócitos, IHQ.',
      'Dermatite seborreica: paraceratose folicular.',
    ],
    next: ['ASLO e cultura de orofaringe fecham o gatilho.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'pustular-psoriasis',
    name: 'Psoríase pustulosa',
    aka: ['Von Zumbusch', 'Pustulose palmoplantar', 'Acrodermatite contínua de Hallopeau'],
    patterns: ['intraepidermal-blister', 'psoriasiform', 'neutrophilic'],
    clinical: ['pustule', 'acute', 'fever', 'acral', 'nails', 'drug', 'pregnancy', 'chronic'],
    histology: ['kogoj', 'subcorneal-pustule', 'parakeratosis-confluent', 'acanthosis-regular', 'exocytosis-neutrophils', 'neutrophils-corneum', 'hypogranulosis', 'dilated-vessels'],
    hallmarks: ['kogoj'],
    against: ['eosinophils', 'hyphae', 'acantholysis'],
    frequency: 2,
    summary: 'Pústulas estéreis sobre eritema, generalizadas com febre ou palmoplantares crônicas; pústula espongiforme de Kogoj grande e pústulas subcórneas sobre epiderme psoriasiforme.',
    clues: [
      'Pústula espongiforme (neutrófilos entre queratinócitos degenerados que ainda formam uma rede) é a chave.',
      'Generalizada: retirada de corticoide sistêmico, gestação (impetigo herpetiforme), mutação IL36RN.',
    ],
    mimics: [
      'PEGA (pustulose exantemática generalizada aguda): eosinófilos, necrose de queratinócitos, edema papilar; fármaco 1 a 3 dias antes.',
      'Pustulose subcórnea (Sneddon-Wilkinson): pústula subcórnea sem espongiforme, sem acantose psoriasiforme.',
      'Candidíase / tinha: PAS.',
      'Pênfigo IgA: acantólise discreta e IgA intercelular.',
      'Impetigo: cocos no Gram, crosta.',
    ],
    next: ['PAS e Gram na pústula.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'reactive-arthritis',
    name: 'Artrite reativa (queratoderma blenorrágico)',
    aka: ['Síndrome de Reiter'],
    patterns: ['psoriasiform', 'intraepidermal-blister'],
    clinical: ['male', 'young-adult', 'acral', 'arthralgia', 'infection', 'genital', 'pustule', 'scaly-plaque'],
    histology: ['kogoj', 'parakeratosis-confluent', 'acanthosis-regular', 'neutrophils-corneum', 'subcorneal-pustule', 'hypogranulosis'],
    against: ['eosinophils'],
    frequency: 1,
    summary: 'Pápulas hiperceratósicas e pustulosas em plantas com artrite, uretrite ou diarreia prévia; histologia indistinguível de psoríase pustulosa, com crosta muito espessa.',
    clues: ['Camada córnea hiperplásica com paraceratose maciça e pústulas espongiformes.', 'HLA-B27 e o quadro articular fazem o diagnóstico.'],
    mimics: ['Psoríase pustulosa palmoplantar: idêntica; clínica.', 'Tinha pedis: PAS.'],
    sources: [WEEDON],
  },
  {
    id: 'pityriasis-rubra-pilaris',
    name: 'Pitiríase rubra pilar',
    aka: ['PRP'],
    patterns: ['psoriasiform'],
    clinical: ['erythroderma', 'follicular', 'acral', 'scaly-plaque', 'chronic', 'subacute', 'child', 'elderly'],
    histology: ['alternating-keratosis', 'follicular-plug', 'acanthosis-regular', 'hypergranulosis', 'lymphocytic-superficial', 'acantholysis', 'sparse-infiltrate'],
    hallmarks: ['alternating-keratosis', 'follicular-plug'],
    against: ['neutrophils-corneum', 'hypogranulosis', 'eosinophils', 'thin-suprapapillary'],
    frequency: 1,
    summary: 'Eritrodermia laranja com ilhas de pele sã, pápulas foliculares e queratoderma cerosa; acantose psoriasiforme com orto e paraceratose alternadas nos dois eixos, granulosa preservada e tampões foliculares.',
    clues: [
      'Tabuleiro de xadrez: paraceratose alternando com ortoceratose tanto na vertical quanto na horizontal.',
      'Tampões foliculares com paraceratose nos ombros do folículo; acantólise focal ocorre.',
      'Placas suprapapilares espessas e granulosa mantida, ao contrário da psoríase.',
    ],
    mimics: [
      'Psoríase: neutrófilos na córnea, hipogranulose, placas finas.',
      'Dermatite seborreica: espongiose, sem tabuleiro.',
      'Eritrodermia de outra causa: MF, fármaco, atópica.',
    ],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'lichen-simplex-chronicus',
    name: 'Líquen simples crônico',
    aka: ['Neurodermite'],
    patterns: ['psoriasiform'],
    clinical: ['itch', 'chronic', 'lichenified', 'genital', 'legs', 'extensor', 'atopy'],
    histology: ['acanthosis-irregular', 'hypergranulosis', 'orthokeratosis-compact', 'papillary-fibrosis', 'lymphocytic-superficial', 'parakeratosis-focal', 'crust'],
    hallmarks: ['papillary-fibrosis', 'hypergranulosis'],
    against: ['neutrophils-corneum', 'hypogranulosis', 'thin-suprapapillary', 'atypical-lymphocytes'],
    frequency: 3,
    summary: 'Placa liquenificada de coçar habitual (nuca, pernas, escroto, vulva); acantose psoriasiforme irregular com hipergranulose, ortoceratose compacta e feixes colágenos verticais na derme papilar.',
    clues: [
      'Colágeno papilar em feixes verticais paralelos às cristas é a marca do atrito crônico.',
      'Hipergranulose e ortoceratose compacta, ao contrário da psoríase.',
      'Sempre secundário: procurar a dermatose de base (atopia, líquen escleroso, prurido sistêmico).',
    ],
    mimics: [
      'Psoríase: paraceratose com neutrófilos, hipogranulose.',
      'Prurigo nodular: mesmo processo em nódulo, com hiperplasia mais exuberante e proliferação neural.',
      'Líquen plano hipertrófico: interface na ponta das cristas e infiltrado em faixa.',
      'Micose fungoide: linfócitos atípicos alinhados na basal.',
    ],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'prurigo-nodularis',
    name: 'Prurigo nodular',
    patterns: ['psoriasiform'],
    clinical: ['itch', 'chronic', 'nodule', 'extensor', 'legs', 'lichenified', 'renal', 'liver', 'atopy', 'immunosuppression'],
    histology: ['acanthosis-irregular', 'hypergranulosis', 'orthokeratosis-compact', 'papillary-fibrosis', 'crust', 'lymphocytic-superficial', 'eosinophils', 'dilated-vessels'],
    hallmarks: ['acanthosis-irregular', 'papillary-fibrosis'],
    against: ['atypical-lymphocytes', 'neutrophils-corneum'],
    frequency: 3,
    summary: 'Nódulos escoriados em extensores por coçadura crônica; hiperplasia epidérmica pseudoepiteliomatosa em cúpula com fibrose papilar e, às vezes, nervos hipertrofiados.',
    clues: ['Hiperplasia irregular e compacta com ulceração central e crosta.', 'Procurar causa sistêmica do prurido (renal, hepática, HIV, linfoma).'],
    mimics: [
      'Carcinoma espinocelular: atipia e invasão; a hiperplasia do prurigo é regular na base.',
      'Ceratoacantoma: cratera de queratina com lábios.',
      'Líquen plano hipertrófico: interface na base das cristas.',
      'Colagenose perfurante reativa: canal com colágeno eliminado.',
    ],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'ilven',
    name: 'Nevo epidérmico verrucoso inflamatório linear',
    aka: ['NEVIL', 'ILVEN'],
    patterns: ['psoriasiform'],
    clinical: ['child', 'linear', 'itch', 'chronic', 'legs', 'dermatomal'],
    histology: ['alternating-keratosis', 'acanthosis-regular', 'hypogranulosis', 'hypergranulosis', 'lymphocytic-superficial', 'papillomatosis'],
    hallmarks: ['alternating-keratosis'],
    frequency: 1,
    summary: 'Placa linear pruriginosa que segue as linhas de Blaschko, resistente a tratamento; acantose psoriasiforme com alternância nítida de paraceratose sobre hipogranulose e ortoceratose sobre hipergranulose.',
    clues: ['A alternância horizontal orto/paraceratose com granulosa correspondente é o dado-chave.', 'Sem neutrófilos na córnea.'],
    mimics: ['Psoríase linear: neutrófilos, sem alternância.', 'Nevo epidérmico comum: papilomatose sem inflamação.', 'Líquen estriado: interface e infiltrado periécrino.'],
    sources: [WEEDON],
  },
  {
    id: 'nutritional-dermatosis',
    name: 'Dermatoses nutricionais e metabólicas (pelagra, acrodermatite enteropática, eritema necrolítico migratório)',
    aka: ['Deficiência de zinco', 'Glucagonoma', 'Pelagra'],
    patterns: ['psoriasiform'],
    clinical: ['flexural', 'genital', 'acral', 'photoexposed', 'annular', 'child', 'liver', 'malignancy', 'subacute'],
    histology: ['pale-upper-epidermis', 'parakeratosis-confluent', 'acanthosis-regular', 'necrotic-keratinocytes', 'exocytosis-neutrophils', 'subcorneal-pustule', 'hypogranulosis'],
    hallmarks: ['pale-upper-epidermis'],
    frequency: 1,
    summary: 'Placas eritemato-erosivas periorificiais, acrais ou fotoexpostas; epiderme psoriasiforme com palidez e necrose das camadas superiores, paraceratose confluente e neutrófilos, muitas vezes com fenda subcórnea.',
    clues: [
      'Palidez vacuolar da metade superior da epiderme com necrose e fenda subcórnea é o achado comum ao grupo.',
      'Eritema necrolítico migratório: glucagonoma, diabetes, perda de peso; pseudoglucagonoma em cirrose.',
      'Acrodermatite enteropática: lactente ao desmame, diarreia, alopecia.',
    ],
    mimics: [
      'Psoríase: sem palidez superior.',
      'Candidíase: pseudo-hifas.',
      'PEGA: eosinófilos, fármaco.',
    ],
    next: ['Zinco, glucagon, niacina e, se possível, imagem de pâncreas conforme o quadro.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'secondary-syphilis',
    name: 'Sífilis secundária',
    patterns: ['psoriasiform', 'interface-lichenoid', 'perivascular-deep', 'granulomatous'],
    clinical: ['young-adult', 'acral', 'trunk', 'generalized', 'scaly-plaque', 'papule', 'hair-loss', 'mucosa', 'fever', 'immunosuppression', 'asymptomatic'],
    histology: ['plasma-cells', 'spirochetes', 'acanthosis-regular', 'parakeratosis-confluent', 'vacuolar', 'superficial-and-deep', 'band-like', 'necrotic-keratinocytes', 'dilated-vessels', 'sarcoidal-granuloma', 'exocytosis-neutrophils'],
    hallmarks: ['plasma-cells', 'spirochetes'],
    frequency: 2,
    summary: 'A grande imitadora: pápulas palmoplantares, roséola, alopecia em clareiras; psoriasiforme com interface, plasmócitos, endotélio túrgido e infiltrado que pode ser liquenoide ou granulomatoso.',
    clues: [
      'Plasmócitos num infiltrado psoriasiforme-liquenoide e vasos com endotélio tumefeito.',
      'Neutrófilos na córnea e paraceratose podem levar erroneamente a psoríase.',
      'IHQ para Treponema mostra espiroquetas na junção e ao redor dos vasos; a ausência não exclui.',
    ],
    mimics: [
      'Psoríase: sem plasmócitos, sem interface.',
      'Pitiríase rósea / liquenoide: sem plasmócitos.',
      'Líquen plano: sem plasmócitos, sem endotélio túrgido.',
      'Micose fungoide: atipia com halo, clone.',
    ],
    next: ['IHQ anti-Treponema pallidum e sorologia (VDRL / FTA-ABS).'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'mycosis-fungoides',
    name: 'Micose fungoide (fase de mancha e placa)',
    aka: ['Linfoma cutâneo de células T'],
    patterns: ['psoriasiform', 'interface-lichenoid', 'invisible'],
    clinical: ['elderly', 'chronic', 'trunk', 'scaly-plaque', 'macule', 'hypopigmented', 'itch', 'atrophy', 'child'],
    histology: ['epidermotropism', 'pautrier', 'atypical-lymphocytes', 'band-like', 'papillary-fibrosis', 'acanthosis-regular', 'sparse-infiltrate', 'parakeratosis-focal'],
    hallmarks: ['epidermotropism', 'pautrier', 'atypical-lymphocytes'],
    against: ['spongiotic-vesicle', 'eosinophils', 'plasma-cells'],
    frequency: 2,
    summary: 'Manchas e placas "eczematosas" em áreas cobertas que duram anos; linfócitos com halo alinhados na basal e em ninhos (Pautrier) sem espongiose proporcional, sobre derme papilar fibrótica.',
    clues: [
      'Linfócitos na epiderme maiores que os da derme, com núcleo cerebriforme e halo claro, sem espongiose ao redor.',
      'Enfileiramento na basal ("colar de contas"), microabscessos de Pautrier e fibrose papilar em feixes grossos.',
      'Variante hipopigmentada em jovens e pardos; foliculotrópica na cabeça e pescoço com mucinose folicular.',
    ],
    mimics: [
      'Dermatite espongiótica crônica: linfócitos na epiderme sempre acompanhados de espongiose.',
      'Dermatite actínica crônica: CD8+, elastose, fotodistribuição.',
      'Erupção liquenoide por fármaco: eosinófilos, dano de interface verdadeiro.',
      'Parapsoríase de pequenas placas: pode ser a mesma doença "precoce"; sem atipia convincente.',
      'Pitiríase liquenoide: necrose de queratinócitos, hemácias extravasadas.',
    ],
    next: ['IHQ CD3/CD4/CD8/CD7/CD30 (perda de CD7, razão CD4:CD8 alterada) e rearranjo do TCR; biópsias múltiplas sem corticoide por 2 a 4 semanas.'],
    sources: [WHO_HEME, MCKEE],
  },
  {
    id: 'small-plaque-parapsoriasis',
    name: 'Parapsoríase de pequenas placas',
    aka: ['Dermatose digitada'],
    patterns: ['psoriasiform', 'spongiotic', 'invisible'],
    clinical: ['elderly', 'male', 'chronic', 'trunk', 'macule', 'scaly-plaque', 'asymptomatic'],
    histology: ['parakeratosis-focal', 'spongiosis', 'lymphocytic-superficial', 'sparse-infiltrate', 'epidermotropism'],
    against: ['atypical-lymphocytes', 'pautrier'],
    frequency: 2,
    summary: 'Placas ovais digitiformes no tronco, estáveis por décadas; histologia mínima com espongiose focal, paraceratose e exocitose de linfócitos pequenos sem atipia.',
    clues: ['Lâmina "quase normal": a suspeita vem da clínica.', 'Quando as placas passam de 5 cm ou têm atrofia, tratar como micose fungoide inicial.'],
    mimics: ['Micose fungoide: atipia, Pautrier, fibrose papilar, clone.', 'Dermatite espongiótica: mais espongiose e eosinófilos.'],
    next: ['Seguimento clínico com nova biópsia se as placas crescerem ou atrofiarem.'],
    sources: [WEEDON, WHO_HEME],
  },
  {
    id: 'psoriasiform-drug-eruption',
    name: 'Erupção psoriasiforme por fármaco',
    aka: ['Psoríase paradoxal por anti-TNF'],
    patterns: ['psoriasiform', 'spongiotic'],
    clinical: ['drug', 'subacute', 'scaly-plaque', 'acral', 'scalp', 'ibd', 'autoimmune'],
    histology: ['acanthosis-regular', 'parakeratosis-confluent', 'eosinophils', 'spongiosis', 'neutrophils-corneum', 'vacuolar', 'necrotic-keratinocytes', 'lymphocytic-superficial'],
    hallmarks: ['eosinophils'],
    frequency: 2,
    summary: 'Psoríase que aparece ou piora após betabloqueador, lítio, antimalárico, anti-TNF ou inibidor de checkpoint; psoriasiforme com eosinófilos, espongiose ou dano de interface que a psoríase clássica não tem.',
    clues: ['Eosinófilos e queratinócitos necróticos num quadro psoriasiforme são a pista para fármaco.', 'Anti-TNF: placas palmoplantares pustulosas e do couro cabeludo em paciente com Crohn ou artrite.'],
    mimics: ['Psoríase vulgar: sem eosinófilos e sem interface.', 'Dermatite seborreica: paraceratose folicular.', 'Sífilis: plasmócitos.'],
    next: ['Cronologia dos medicamentos, incluindo biológicos.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'confluent-reticulated-papillomatosis',
    name: 'Papilomatose confluente e reticulada / acantose nigricans',
    aka: ['Gougerot-Carteaud', 'Acanthosis nigricans'],
    patterns: ['invisible', 'psoriasiform'],
    clinical: ['young-adult', 'trunk', 'flexural', 'hyperpigmented', 'asymptomatic', 'chronic', 'diabetes', 'malignancy'],
    histology: ['papillomatosis', 'hypergranulosis', 'orthokeratosis-compact', 'sparse-infiltrate', 'acanthosis-irregular'],
    hallmarks: ['papillomatosis'],
    against: ['spongiosis', 'band-like'],
    frequency: 2,
    summary: 'Placas aveludadas hiperpigmentadas em dobras (acantose nigricans) ou pápulas reticuladas no tronco (Gougerot-Carteaud); papilomatose ondulada com hiperceratose e pouca ou nenhuma inflamação.',
    clues: ['Papilomatose em ondas com hiperceratose "em igreja" e hiperpigmentação basal; a derme é quase normal.', 'Acantose nigricans: obesidade e resistência insulínica; forma maligna de início súbito com mucosas.'],
    mimics: ['Pitiríase versicolor: leveduras e hifas curtas na córnea; PAS.', 'Ceratose seborreica: pseudocistos córneos.', 'Dermatite atópica liquenificada: espongiose e infiltrado.'],
    next: ['PAS para afastar pitiríase versicolor.'],
    sources: [WEEDON, BOLOGNIA],
  },
]
