/* ==========================================================================
   content/spongiotic.ts — dermatoses de padrão espongiótico: os eczemas e
   o que se disfarça de eczema (tinha, escabiose, picada, pitiríase rósea,
   micose fungoide inicial). A fonte é citada como texto: livro, edição.
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const ACKERMAN = 'Ackerman: Histologic Diagnosis of Inflammatory Skin Diseases, 3ª ed. (2005)'
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'

export const spongiotic: Diagnosis[] = [
  {
    id: 'atopic-dermatitis',
    name: 'Dermatite atópica',
    aka: ['Eczema atópico'],
    patterns: ['spongiotic', 'psoriasiform'],
    clinical: ['child', 'itch', 'chronic', 'flexural', 'lichenified', 'atopy', 'family', 'face'],
    histology: ['spongiosis', 'parakeratosis-focal', 'acanthosis-irregular', 'lymphocytic-superficial', 'eosinophils', 'papillary-fibrosis', 'hypergranulosis', 'crust'],
    against: ['hyphae', 'mite', 'atypical-lymphocytes', 'neutrophils-corneum'],
    frequency: 3,
    summary: 'Eczema crônico e pruriginoso de dobras; a histologia é a de qualquer dermatite espongiótica e a idade da lesão dita se domina a espongiose (aguda) ou a acantose com paraceratose (crônica).',
    clues: [
      'Lesão aguda: espongiose com vesículas e exocitose de linfócitos; crônica: acantose psoriasiforme irregular, hipergranulose e fibrose papilar vertical (liquenificação).',
      'Eosinófilos são poucos e não separam de dermatite de contato.',
      'Escoriação e crosta são comuns pelo prurido.',
    ],
    mimics: [
      'Dermatite de contato alérgica: idêntica na lâmina; separa-se por exposição, distribuição e teste de contato.',
      'Micose fungoide: linfócitos na epiderme sem espongiose proporcional, alinhados na basal e com halo; dermatite crônica "que não responde" merece imuno e clone.',
      'Escabiose: procurar túnel e ácaro na córnea; eosinófilos abundantes com infiltrado profundo.',
      'Psoríase: paraceratose confluente com neutrófilos, hipogranulose e placas suprapapilares finas.',
    ],
    next: ['PAS quando a placa for solitária ou anular.', 'Se a espongiose for mínima para o tanto de linfócito intraepidérmico, pensar em micose fungoide.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'allergic-contact-dermatitis',
    name: 'Dermatite de contato alérgica',
    patterns: ['spongiotic'],
    clinical: ['itch', 'acute', 'subacute', 'contact', 'linear', 'hands', 'face', 'vesicle'],
    histology: ['spongiosis', 'spongiotic-vesicle', 'langerhans-microabscess', 'eosinophils', 'lymphocytic-superficial', 'papillary-edema', 'parakeratosis-focal'],
    hallmarks: ['spongiotic-vesicle', 'langerhans-microabscess'],
    against: ['hyphae', 'neutrophils-corneum'],
    frequency: 3,
    summary: 'Hipersensibilidade tardia a um contactante: espongiose com vesículas, microabscessos de Langerhans e eosinófilos num sítio que denuncia a exposição.',
    clues: [
      'Microvesículas espongióticas com coleções de células de Langerhans são a pista mais específica, embora não exclusiva.',
      'Eosinófilos na derme e na epiderme favorecem alérgica sobre irritativa.',
      'Bordas geométricas ou lineares e localização (pálpebra, mãos, pescoço) contam mais que a lâmina.',
    ],
    mimics: [
      'Dermatite de contato irritativa: necrose de queratinócitos superficiais, neutrófilos, menos eosinófilos.',
      'Dermatite atópica: idêntica; separa-se pela clínica.',
      'Dermatofitose: hifas na córnea, muitas vezes com paraceratose "sanduíche".',
      'Reação id: eczema disseminado a distância de um foco (tinha pedis, estase).',
    ],
    next: ['Teste de contato quando a dermatite for recorrente ou ocupacional.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'irritant-contact-dermatitis',
    name: 'Dermatite de contato irritativa',
    patterns: ['spongiotic'],
    clinical: ['pain', 'acute', 'chronic', 'contact', 'hands', 'acral'],
    histology: ['spongiosis', 'pale-upper-epidermis', 'necrotic-keratinocytes', 'exocytosis-neutrophils', 'parakeratosis-focal', 'lymphocytic-superficial', 'crust'],
    hallmarks: ['pale-upper-epidermis'],
    against: ['eosinophils', 'langerhans-microabscess'],
    frequency: 3,
    summary: 'Dano direto por irritante (detergentes, solventes, umidade): espongiose com necrose de queratinócitos superficiais e neutrófilos, sem eosinófilos.',
    clues: [
      'Palidez ou necrose das camadas altas da epiderme com neutrófilos aponta para irritante forte.',
      'Forma crônica é uma dermatite espongiótica-psoriasiforme sem assinatura.',
      'Ardor supera prurido; começa nas mãos de quem lava muito.',
    ],
    mimics: [
      'Dermatite de contato alérgica: vesículas com Langerhans e eosinófilos.',
      'Psoríase palmar: paraceratose com neutrófilos e hipogranulose.',
      'Dermatofitose: hifas.',
    ],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'nummular-dermatitis',
    name: 'Dermatite numular',
    aka: ['Eczema discoide'],
    patterns: ['spongiotic', 'psoriasiform'],
    clinical: ['itch', 'chronic', 'legs', 'extensor', 'annular', 'elderly', 'scaly-plaque'],
    histology: ['spongiosis', 'acanthosis-irregular', 'parakeratosis-focal', 'crust', 'lymphocytic-superficial', 'eosinophils'],
    against: ['hyphae', 'neutrophils-corneum', 'atypical-lymphocytes'],
    frequency: 3,
    summary: 'Placas em moeda, exsudativas e pruriginosas, sobretudo nas pernas de adultos e idosos; dermatite espongiótica subaguda sem assinatura própria.',
    clues: ['Espongiose com acantose irregular e crostas de serosidade e neutrófilos.', 'A forma da lesão é o diagnóstico; a lâmina exclui tinha e psoríase.'],
    mimics: [
      'Dermatofitose: hifas na córnea, PAS.',
      'Psoríase: paraceratose confluente com neutrófilos e hipogranulose.',
      'Micose fungoide: epidermotropismo desproporcional à espongiose.',
      'Doença de Bowen: atipia de espessura total.',
    ],
    next: ['PAS em toda placa anular ou solitária.'],
    sources: [WEEDON],
  },
  {
    id: 'dyshidrotic-eczema',
    name: 'Eczema disidrótico',
    aka: ['Ponfólix', 'Disidrose'],
    patterns: ['spongiotic', 'intraepidermal-blister'],
    clinical: ['itch', 'acute', 'relapsing', 'acral', 'vesicle', 'young-adult'],
    histology: ['spongiotic-vesicle', 'spongiosis', 'orthokeratosis-compact', 'lymphocytic-superficial', 'eosinophils'],
    hallmarks: ['spongiotic-vesicle'],
    against: ['hyphae', 'neutrophils-corneum', 'kogoj'],
    frequency: 3,
    summary: 'Vesículas em "sagu" nas laterais dos dedos, palmas e plantas, em surtos; vesículas espongióticas sob a córnea espessa acral.',
    clues: ['Vesículas grandes porque a córnea acral não deixa romper.', 'Sem neutrófilos e sem hifas.'],
    mimics: [
      'Tinha pedis / manuum vesicobolhosa: PAS positivo; pode ser a causa de uma reação id nas mãos.',
      'Psoríase pustulosa palmoplantar: pústulas com neutrófilos, paraceratose.',
      'Dermatite de contato alérgica: pode ser indistinguível; depende da história.',
    ],
    next: ['PAS na vesícula e nos pés, se houver tinha pedis.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'stasis-dermatitis',
    name: 'Dermatite de estase',
    aka: ['Eczema gravitacional'],
    patterns: ['spongiotic'],
    clinical: ['legs', 'chronic', 'elderly', 'venous', 'hyperpigmented', 'itch'],
    histology: ['spongiosis', 'dilated-vessels', 'rbc-extravasation', 'lymphocytic-superficial', 'sclerosis', 'acanthosis-irregular', 'parakeratosis-focal'],
    hallmarks: ['dilated-vessels', 'rbc-extravasation'],
    frequency: 3,
    summary: 'Eczema das pernas com hipertensão venosa: espongiose sobre derme com lóbulos de vasos neoformados de parede espessa, hemossiderina e fibrose.',
    clues: [
      'Proliferação lobular de vênulas na derme papilar e reticular com hemossiderina é o dado que "assina".',
      'Fibrose dérmica e lipodermatosclerose na profundidade em casos antigos.',
    ],
    mimics: [
      'Sarcoma de Kaposi: fendas vasculares que dissecam colágeno, HHV-8.',
      'Acroangiodermatite (pseudo-Kaposi): é a mesma proliferação vascular da estase, exagerada.',
      'Dermatite de contato alérgica sobreposta: muito comum por tópicos; eosinófilos e vesículas.',
      'Púrpura pigmentar: sem espongiose, hemácias extravasadas em derme papilar.',
    ],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'seborrheic-dermatitis',
    name: 'Dermatite seborreica',
    patterns: ['spongiotic', 'psoriasiform'],
    clinical: ['seborrheic', 'scalp', 'face', 'chronic', 'scaly-plaque', 'immunosuppression', 'relapsing'],
    histology: ['parakeratosis-focal', 'spongiosis', 'acanthosis-regular', 'lymphocytic-superficial', 'neutrophils-corneum', 'crust'],
    hallmarks: ['parakeratosis-focal'],
    frequency: 3,
    summary: 'Descamação gordurosa em áreas seborreicas; espongiose leve com paraceratose em montículos ao redor dos óstios foliculares ("shoulder parakeratosis").',
    clues: [
      'Paraceratose e crostas de neutrófilos centradas nos óstios foliculares.',
      'Acantose psoriasiforme discreta com espongiose: o híbrido espongiótico-psoriasiforme.',
      'Formas extensas em HIV e em Parkinson.',
    ],
    mimics: [
      'Psoríase do couro cabeludo: paraceratose confluente, hipogranulose, sem espongiose.',
      'Tinha da face / capitis: PAS.',
      'Lúpus discoide na face: interface com tampões e membrana basal espessa.',
      'Rosácea: sem espongiose, infiltrado perivascular e perifolicular com Demodex.',
    ],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'id-reaction',
    name: 'Reação id (autoeczematização)',
    aka: ['Dermatofítide'],
    patterns: ['spongiotic'],
    clinical: ['itch', 'acute', 'generalized', 'papule', 'vesicle', 'acral', 'venous'],
    histology: ['spongiosis', 'spongiotic-vesicle', 'lymphocytic-superficial', 'eosinophils'],
    against: ['hyphae'],
    frequency: 2,
    summary: 'Erupção espongiótica simétrica e a distância, disparada por um foco primário (tinha pedis, estase, contato); a lâmina do id não tem organismo nem assinatura.',
    clues: ['Vesículas nas laterais dos dedos são a apresentação clássica da dermatofítide.', 'O diagnóstico está na dermatose primária, não nesta biópsia.'],
    mimics: [
      'Dermatofitose disseminada: PAS positivo na própria lesão.',
      'Eczema disidrótico: indistinguível; pergunte pelos pés.',
      'Erupção medicamentosa espongiótica: cronologia do fármaco.',
    ],
    next: ['Exame dos pés, dobras e pernas em busca do foco.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'pityriasis-rosea',
    name: 'Pitiríase rósea',
    patterns: ['spongiotic', 'perivascular-superficial'],
    clinical: ['young-adult', 'acute', 'subacute', 'trunk', 'scaly-plaque', 'annular', 'relapsing'],
    histology: ['parakeratosis-focal', 'spongiosis', 'rbc-extravasation', 'lymphocytic-superficial', 'acanthosis-irregular', 'necrotic-keratinocytes'],
    hallmarks: ['parakeratosis-focal', 'rbc-extravasation'],
    against: ['plasma-cells', 'hyphae'],
    frequency: 3,
    summary: 'Erupção autolimitada em "árvore de Natal" após placa-mãe; espongiose focal com montículos de paraceratose e hemácias extravasadas nas papilas e na epiderme.',
    clues: [
      'Montículos de paraceratose sobre focos de espongiose, com hemácias na papila e às vezes dentro da epiderme.',
      'Queratinócitos disceratóticos isolados podem aparecer e não afastam.',
    ],
    mimics: [
      'Sífilis secundária: plasmócitos, infiltrado liquenoide ou psoriasiforme, IHQ para Treponema.',
      'Dermatite espongiótica comum: sem hemácias extravasadas; a clínica separa.',
      'Pitiríase liquenoide crônica: mais interface e paraceratose confluente.',
      'Tinha corporis: PAS.',
    ],
    next: ['IHQ para Treponema pallidum ou sorologia quando houver plasmócitos, lesão palmoplantar ou paciente sexualmente ativo.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'dermatophytosis',
    name: 'Dermatofitose',
    aka: ['Tinha corporis / cruris / pedis', 'Tinea'],
    patterns: ['spongiotic', 'psoriasiform'],
    clinical: ['annular', 'itch', 'chronic', 'flexural', 'acral', 'scaly-plaque', 'immunosuppression', 'travel'],
    histology: ['hyphae', 'parakeratosis-focal', 'spongiosis', 'exocytosis-neutrophils', 'neutrophils-corneum', 'pas-positive', 'acanthosis-regular', 'lymphocytic-superficial'],
    hallmarks: ['hyphae', 'pas-positive'],
    frequency: 3,
    summary: 'Qualquer dermatite espongiótica ou psoriasiforme com neutrófilos na córnea pede PAS: as hifas ficam entre a ortoceratose de baixo e a paraceratose de cima ("sinal do sanduíche").',
    clues: [
      'Neutrófilos na córnea + paraceratose em montículos + espongiose leve = pedir PAS antes de assinar.',
      'Hifas septadas na córnea e nos pelos (tinha capitis, granuloma de Majocchi).',
      'Corticoide tópico "apaga" a inflamação (tinha incógnito) sem apagar as hifas.',
    ],
    mimics: [
      'Psoríase: também tem neutrófilos na córnea, sem hifas.',
      'Dermatite seborreica: sem hifas (mas Malassezia pode aparecer como leveduras).',
      'Candidíase: pseudo-hifas e leveduras, pústula subcórnea, dobras.',
      'Eritema anular centrífugo: sem hifas, infiltrado perivascular em manga.',
    ],
    next: ['PAS ou Grocott.', 'Se pústulas foliculares profundas, procurar hifas na haste (Majocchi).'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'candidiasis',
    name: 'Candidíase cutânea',
    aka: ['Intertrigo candidiásico'],
    patterns: ['spongiotic', 'intraepidermal-blister'],
    clinical: ['flexural', 'pustule', 'diabetes', 'immunosuppression', 'itch', 'pain'],
    histology: ['subcorneal-pustule', 'hyphae', 'pas-positive', 'spongiosis', 'exocytosis-neutrophils', 'parakeratosis-focal'],
    hallmarks: ['subcorneal-pustule', 'hyphae'],
    frequency: 3,
    summary: 'Intertrigo com pústulas-satélite; pústulas subcórneas com pseudo-hifas e leveduras na córnea.',
    clues: ['Pseudo-hifas e blastoconídios na córnea, muitas vezes dentro da pústula subcórnea.', 'Dobras úmidas, diabetes e antibiótico recente.'],
    mimics: [
      'Psoríase inversa: sem organismos, paraceratose confluente.',
      'Dermatofitose: hifas septadas verdadeiras, sem leveduras.',
      'Pustulose subcórnea / pênfigo IgA: sem fungos, IF.',
      'Eritrasma: bactérias filamentosas na córnea, sem inflamação.',
    ],
    next: ['PAS.'],
    sources: [WEEDON],
  },
  {
    id: 'scabies',
    name: 'Escabiose',
    aka: ['Sarna'],
    patterns: ['spongiotic', 'perivascular-deep'],
    clinical: ['itch', 'generalized', 'flexural', 'genital', 'acral', 'family', 'papule', 'child', 'elderly', 'immunosuppression'],
    histology: ['mite', 'spongiosis', 'eosinophils', 'superficial-and-deep', 'crust', 'wedge-infiltrate', 'spongiotic-vesicle'],
    hallmarks: ['mite'],
    frequency: 3,
    summary: 'Prurido noturno familiar; espongiose com eosinófilos abundantes e infiltrado superficial e profundo, e o ácaro (ou ovos, ou fezes) na córnea quando o corte pega o túnel.',
    clues: [
      'Eosinófilos em grande número com infiltrado profundo num "eczema" devem levantar escabiose e picada.',
      'Cortes seriados aumentam a chance de achar o túnel; a escabiose crostosa tem ácaros incontáveis.',
      'Nódulos escrotais e axilares persistentes podem ter infiltrado denso com atipia (pseudolinfoma).',
    ],
    mimics: [
      'Reação a picada de artrópode: idêntica sem o ácaro; a distribuição e o contexto separam.',
      'Dermatite atópica: menos eosinófilos, sem infiltrado profundo.',
      'Penfigoide bolhoso urticariforme: espongiose eosinofílica e IF linear.',
    ],
    next: ['Cortes seriados e exame direto (raspado) quando a suspeita clínica for forte.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'arthropod-bite',
    name: 'Reação a picada de artrópode',
    aka: ['Prurigo estrófulo', 'Urticária papular'],
    patterns: ['spongiotic', 'perivascular-deep'],
    clinical: ['itch', 'papule', 'insect', 'child', 'legs', 'acute', 'relapsing', 'vesicle'],
    histology: ['wedge-infiltrate', 'eosinophils', 'superficial-and-deep', 'spongiosis', 'spongiotic-vesicle', 'papillary-edema', 'crust', 'flame-figures'],
    hallmarks: ['wedge-infiltrate', 'eosinophils'],
    frequency: 3,
    summary: 'Pápulas e vesículas pruriginosas agrupadas; infiltrado em cunha superficial e profundo rico em eosinófilos, com espongiose ou vesícula no ápice e às vezes o ponto de picada.',
    clues: [
      'Infiltrado em cunha com o vértice para baixo, eosinófilos intersticiais até a derme profunda.',
      'Pode haver eosinófilos entre feixes de colágeno e figuras em chama nas lesões velhas.',
      'Leucemia linfoide crônica exagera a reação a picadas.',
    ],
    mimics: [
      'Escabiose: mesmo quadro com ácaro; procurar túnel.',
      'Síndrome de Wells: figuras em chama numerosas, placas grandes.',
      'Papulose linfomatoide: células grandes CD30+ atípicas.',
      'Penfigoide bolhoso: espongiose eosinofílica com IF linear.',
    ],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'polymorphic-eruption-pregnancy',
    name: 'Erupção polimórfica da gestação',
    aka: ['PUPPP', 'Pápulas e placas urticariformes pruriginosas da gestação'],
    patterns: ['spongiotic', 'perivascular-superficial'],
    clinical: ['pregnancy', 'itch', 'trunk', 'wheal', 'papule', 'acute'],
    histology: ['spongiosis', 'papillary-edema', 'eosinophils', 'lymphocytic-superficial', 'parakeratosis-focal', 'dif-negative'],
    against: ['dif-linear-bmz', 'subepidermal-eos'],
    frequency: 2,
    summary: 'Terceiro trimestre de primigesta, começa nas estrias abdominais e poupa o umbigo; dermatite espongiótica com edema papilar e eosinófilos, IF negativa.',
    clues: ['Sem assinatura histológica: o valor da biópsia é excluir penfigoide gestacional.', 'IF direta negativa é o dado decisivo.'],
    mimics: [
      'Penfigoide gestacional: espongiose eosinofílica, bolha subepidérmica, C3 linear na ZMB; começa periumbilical.',
      'Urticária: sem espongiose, sem paraceratose.',
      'Erupção medicamentosa: cronologia.',
    ],
    next: ['IF direta em pele perilesional.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'miliaria',
    name: 'Miliária',
    aka: ['Brotoeja'],
    patterns: ['spongiotic', 'intraepidermal-blister'],
    clinical: ['child', 'acute', 'trunk', 'vesicle', 'papule', 'fever'],
    histology: ['spongiotic-vesicle', 'subcorneal-pustule', 'spongiosis', 'periadnexal', 'sparse-infiltrate'],
    frequency: 2,
    summary: 'Obstrução do ducto écrino por calor e oclusão: vesícula subcórnea (cristalina) ou espongiótica intraepidérmica (rubra) centrada no acrossiríngio.',
    clues: ['A vesícula é centrada no ducto écrino, com o resto da epiderme normal.', 'Pode haver tampão de queratina ou bactérias no óstio.'],
    mimics: [
      'Foliculite: centrada no folículo, não no ducto.',
      'Candidíase: pseudo-hifas, dobras.',
      'Eritema tóxico neonatal: pústula folicular com eosinófilos.',
    ],
    sources: [WEEDON],
  },
  {
    id: 'chronic-actinic-dermatitis',
    name: 'Dermatite actínica crônica',
    aka: ['Reticuloide actínico'],
    patterns: ['spongiotic', 'psoriasiform', 'interface-lichenoid'],
    clinical: ['elderly', 'male', 'photoexposed', 'chronic', 'itch', 'lichenified', 'photosensitive', 'face', 'hands'],
    histology: ['spongiosis', 'acanthosis-irregular', 'lymphocytic-superficial', 'solar-elastosis', 'atypical-lymphocytes', 'epidermotropism', 'papillary-fibrosis', 'superficial-and-deep'],
    hallmarks: ['solar-elastosis'],
    frequency: 1,
    summary: 'Eczema liquenificado persistente em fotoexpostas de homens idosos, que pode ter linfócitos atípicos e simular micose fungoide; elastose solar e o padrão fotodistribuído são a chave.',
    clues: ['Dermatite espongiótica-psoriasiforme com elastose solar intensa e limite nítido pela roupa.', 'A forma reticuloide tem infiltrado denso com células cerebriformes CD8+.'],
    mimics: [
      'Micose fungoide: CD4 predomina e há clone; na dermatite actínica os linfócitos atípicos são CD8+.',
      'Fotoalergia: quadro agudo, com fármaco ou filtro solar.',
      'Dermatite de contato aerotransportada: pega pálpebras superiores e retroauricular, que o sol poupa.',
    ],
    next: ['Fototeste e teste de contato; IHQ CD4/CD8 quando houver atipia.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'spongiotic-drug-eruption',
    name: 'Erupção medicamentosa espongiótica',
    aka: ['Dermatite de contato sistêmica'],
    patterns: ['spongiotic', 'perivascular-superficial'],
    clinical: ['drug', 'acute', 'generalized', 'itch', 'flexural', 'elderly'],
    histology: ['spongiosis', 'eosinophils', 'lymphocytic-superficial', 'necrotic-keratinocytes', 'papillary-edema', 'vacuolar'],
    frequency: 2,
    summary: 'Eczema simétrico ou de dobras (síndrome do babuíno) iniciado após fármaco; espongiose com eosinófilos e, às vezes, dano vacuolar ou queratinócitos necróticos que denunciam a origem medicamentosa.',
    clues: ['Combinação de padrões (espongiose + interface + eosinófilos) num mesmo corte é a marca de fármaco.', 'Bloqueadores de canal de cálcio em idosos dão eczema crônico generalizado.'],
    mimics: [
      'Dermatite atópica do adulto: sem dano de interface, história longa.',
      'Reação id: foco primário identificável.',
      'Micose fungoide: epidermotropismo sem espongiose.',
    ],
    next: ['Revisar toda a lista de medicamentos com datas.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'gianotti-crosti',
    name: 'Síndrome de Gianotti-Crosti',
    aka: ['Acrodermatite papular da infância'],
    patterns: ['spongiotic', 'perivascular-deep'],
    clinical: ['child', 'acute', 'papule', 'extensor', 'face', 'infection', 'acral'],
    histology: ['spongiosis', 'superficial-and-deep', 'lymphocytic-superficial', 'papillary-edema', 'rbc-extravasation', 'lymphocytic-vasculitis'],
    frequency: 1,
    summary: 'Pápulas monomórficas em face, nádegas e extremidades de criança após infecção viral (EBV, hepatite B); espongiose focal com infiltrado superficial e profundo e edema papilar.',
    clues: ['Histologia inespecífica: a distribuição acral e a idade fazem o diagnóstico.', 'Pode haver vasculite linfocitária discreta.'],
    mimics: ['Líquen plano: interface liquenoide com hipergranulose.', 'Picadas de artrópode: eosinófilos e cunha.', 'Erupção medicamentosa: cronologia.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'erythema-annulare-centrifugum',
    name: 'Eritema anular centrífugo',
    patterns: ['perivascular-superficial', 'perivascular-deep', 'spongiotic'],
    clinical: ['annular', 'trunk', 'chronic', 'relapsing', 'asymptomatic', 'infection', 'malignancy'],
    histology: ['lymphocytic-superficial', 'superficial-and-deep', 'parakeratosis-focal', 'spongiosis', 'sparse-infiltrate'],
    hallmarks: ['lymphocytic-superficial'],
    against: ['hyphae', 'plasma-cells', 'mucin'],
    frequency: 2,
    summary: 'Anéis que crescem com descamação interna; infiltrado linfocitário perivascular denso e bem delimitado ("em manga de casaco"), superficial na forma descamativa e superficial e profundo na forma sem escama.',
    clues: ['Infiltrado perivascular compacto e nitidamente demarcado, com espongiose e paraceratose focal na variante superficial.', 'Reativo: tinha pedis, fármaco, neoplasia oculta.'],
    mimics: [
      'Tinha corporis: PAS.',
      'Lúpus túmido: mucina abundante, periadnexal.',
      'Eritema migratório (Lyme): plasmócitos, história de carrapato.',
      'Micose fungoide: epidermotropismo, atipia.',
      'Granuloma anular: histiócitos intersticiais e mucina.',
    ],
    next: ['PAS; procurar tinha nos pés.'],
    sources: [WEEDON, ACKERMAN],
  },
]
