/* ==========================================================================
   content/vascular.ts — urticária e urticariformes, vasculites de pequeno e
   médio vaso, vasculopatias oclusivas e as dermatoses perivasculares sem
   dano epidérmico (eritema migratório, perniose, erupção polimorfa à luz).
   ========================================================================== */

import type { Diagnosis } from '../types'

const WEEDON = "Weedon's Skin Pathology, 5ª ed. (Patterson, 2021)"
const MCKEE = "McKee's Pathology of the Skin, 5ª ed. (Calonje, Brenn, Lazar, Billings, 2020)"
const ACKERMAN = 'Ackerman: Histologic Diagnosis of Inflammatory Skin Diseases, 3ª ed. (2005)'
const BOLOGNIA = 'Bolognia: Dermatology, 5ª ed. (2024)'

export const vascular: Diagnosis[] = [
  {
    id: 'urticaria',
    name: 'Urticária',
    patterns: ['perivascular-superficial', 'invisible'],
    clinical: ['wheal', 'itch', 'lesion-24h', 'acute', 'chronic', 'generalized', 'drug', 'infection'],
    histology: ['papillary-edema', 'sparse-infiltrate', 'eosinophils', 'neutrophils-dermis', 'dilated-vessels', 'lymphocytic-superficial', 'mast-cells'],
    hallmarks: ['papillary-edema'],
    against: ['lcv', 'spongiosis', 'vacuolar', 'rbc-extravasation'],
    frequency: 3,
    summary: 'Urticas que migram e somem em menos de 24 h; edema dérmico com vasos dilatados, infiltrado perivascular e intersticial escasso de linfócitos, eosinófilos e neutrófilos, epiderme intacta.',
    clues: [
      'Neutrófilos e eosinófilos dentro das vênulas e espalhados entre feixes de colágeno afastados pelo edema.',
      'Lâmina "quase normal": a epiderme está intacta e não há vasculite.',
      'Lesão que dura mais de 24 h, dói ou deixa púrpura pede pensar em vasculite urticariforme.',
    ],
    mimics: [
      'Vasculite urticariforme: fibrina e leucocitoclasia na parede, hemácias extravasadas.',
      'Erupção medicamentosa morbiliforme: interface e espongiose.',
      'Síndrome de Sweet: infiltrado neutrofílico denso, edema maciço.',
      'Mastocitose: mastócitos em número maior; c-KIT / triptase.',
      'Penfigoide bolhoso pré-bolhoso: espongiose eosinofílica, IF linear.',
    ],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'urticarial-vasculitis',
    name: 'Vasculite urticariforme',
    patterns: ['vasculitis', 'perivascular-superficial'],
    clinical: ['wheal', 'pain', 'purpura', 'arthralgia', 'chronic', 'autoimmune', 'female', 'fever'],
    histology: ['lcv', 'papillary-edema', 'rbc-extravasation', 'neutrophils-dermis', 'eosinophils', 'dif-vascular-iga'],
    hallmarks: ['lcv'],
    frequency: 1,
    summary: 'Urticas que duram mais de 24 h, ardem e deixam púrpura ou pigmento; vasculite leucocitoclástica discreta (fibrina, poeira nuclear, hemácias) sobre o fundo edematoso de uma urticária.',
    clues: ['Procurar fibrina na parede e leucocitoclasia mesmo que sutis; a hemácia extravasada é o sinal de alerta.', 'Forma hipocomplementêmica associa-se a lúpus e doença sistêmica.'],
    mimics: ['Urticária: sem lesão vascular; neutrófilos sem poeira nuclear.', 'Vasculite leucocitoclástica clássica: púrpura palpável de pernas.', 'Sweet: infiltrado neutrofílico difuso muito mais denso.'],
    next: ['Complemento (C3, C4, C1q), FAN e urina.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'leukocytoclastic-vasculitis',
    name: 'Vasculite leucocitoclástica cutânea',
    aka: ['Vasculite de pequenos vasos', 'Vasculite por hipersensibilidade'],
    patterns: ['vasculitis'],
    clinical: ['purpura', 'legs', 'acute', 'drug', 'infection', 'arthralgia', 'malignancy', 'autoimmune', 'ulcer'],
    histology: ['lcv', 'rbc-extravasation', 'neutrophils-dermis', 'papillary-edema', 'thrombi', 'eosinophils', 'necrotic-keratinocytes', 'dif-vascular-iga'],
    hallmarks: ['lcv'],
    frequency: 3,
    summary: 'Púrpura palpável simétrica de pernas dias após infecção ou fármaco; vênulas pós-capilares com fibrina na parede, neutrófilos e poeira nuclear ao redor, hemácias extravasadas.',
    clues: [
      'A tríade fibrina na parede + leucocitoclasia + hemácias define; biopsiar lesão de 24 a 48 h.',
      'Lesão velha vira infiltrado linfocitário com hemossiderina e pode parecer púrpura pigmentar.',
      'Eosinófilos favorecem fármaco; IgA na parede favorece Henoch-Schönlein.',
    ],
    mimics: [
      'Vasculite por IgA: mesma lâmina, IgA na IF direta; criança com dor abdominal e nefrite.',
      'Vasculite séptica: trombos, cocos, neutrófilos dentro do vaso; hemocultura.',
      'Vasculite ANCA: acometimento de vaso médio, granulomas extravasculares (GPA) ou eosinófilos (EGPA).',
      'Púrpura pigmentar: sem fibrina, sem leucocitoclasia.',
      'Vasculopatia livedoide: trombos hialinos sem neutrófilos.',
    ],
    next: ['IF direta em lesão fresca (IgA); ANCA, crioglobulinas, hepatites, urina e hemocultura conforme o quadro.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'iga-vasculitis',
    name: 'Vasculite por IgA',
    aka: ['Púrpura de Henoch-Schönlein'],
    patterns: ['vasculitis'],
    clinical: ['child', 'purpura', 'legs', 'acute', 'infection', 'arthralgia', 'renal', 'pain', 'extensor'],
    histology: ['lcv', 'dif-vascular-iga', 'rbc-extravasation', 'neutrophils-dermis', 'papillary-edema'],
    hallmarks: ['lcv', 'dif-vascular-iga'],
    frequency: 2,
    summary: 'Púrpura palpável em nádegas e pernas de criança após infecção respiratória, com artralgia, dor abdominal e hematúria; vasculite leucocitoclástica com IgA granular na parede das vênulas.',
    clues: ['Histologia idêntica à LCV; só a IF direta com IgA separa.', 'Adultos têm mais nefrite: acompanhar a urina.'],
    mimics: ['Vasculite leucocitoclástica de outra causa: IF sem IgA (ou IgA discreta em lesão velha).', 'Púrpura trombocitopênica: hemorragia sem vasculite.'],
    next: ['IF direta em lesão de menos de 48 h; urina I e função renal.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'anca-vasculitis',
    name: 'Vasculite associada a ANCA (GPA, EGPA, PAM)',
    aka: ['Granulomatose com poliangiite', 'Granulomatose eosinofílica com poliangiite', 'Poliangiite microscópica'],
    patterns: ['vasculitis', 'granulomatous'],
    clinical: ['purpura', 'nodule', 'ulcer', 'fever', 'arthralgia', 'renal', 'legs', 'extensor', 'chronic'],
    histology: ['lcv', 'medium-vessel-vasculitis', 'palisaded-granuloma', 'eosinophils', 'flame-figures', 'necrotic-keratinocytes', 'neutrophils-dermis', 'rbc-extravasation'],
    frequency: 1,
    summary: 'Púrpura, nódulos ou úlceras com doença renal, pulmonar ou sinusal; vasculite de pequeno e médio vaso que na GPA vem com granulomas em paliçada ao redor de colágeno degenerado basofílico, e na EGPA com eosinófilos e figuras em chama.',
    clues: [
      'Granuloma em paliçada com centro basofílico de neutrófilos degenerados (GPA) ou eosinófilos (EGPA) sem vaso no centro: "granuloma extravascular".',
      'PAM: LCV pura, sem granulomas, com glomerulonefrite.',
    ],
    mimics: ['LCV comum: sem granulomas nem vaso médio.', 'Granuloma anular: sem vasculite, mucina.', 'Poliarterite nodosa cutânea: só vaso médio, ANCA negativo.'],
    next: ['c-ANCA/PR3 e p-ANCA/MPO, hemograma com eosinófilos, urina e imagem de tórax e seios.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'cutaneous-pan',
    name: 'Poliarterite nodosa cutânea',
    patterns: ['vasculitis', 'panniculitis-septal'],
    clinical: ['subcutaneous-nodule', 'livedo', 'legs', 'ulcer', 'pain', 'chronic', 'relapsing', 'infection', 'ibd'],
    histology: ['medium-vessel-vasculitis', 'septal-panniculitis', 'neutrophils-dermis', 'thrombi', 'rbc-extravasation', 'lcv'],
    hallmarks: ['medium-vessel-vasculitis'],
    frequency: 1,
    summary: 'Nódulos dolorosos com livedo racemoso nas pernas, sem doença sistêmica; arterite necrosante de uma artéria muscular no septo ou na junção dermo-hipodérmica, com fibrina, neutrófilos e destruição da lâmina elástica.',
    clues: [
      'O vaso doente é uma artéria de parede muscular no subcutâneo; a derme pode ter só LCV secundária.',
      'Biópsia deve ser profunda (punch grande ou incisional) e centrada no nódulo, não na livedo.',
      'Estreptococo, hepatite B e doença inflamatória intestinal como gatilhos.',
    ],
    mimics: ['Eritema nodoso: sem arterite; septos alargados com Miescher.', 'Eritema induratum: paniculite lobular com vasculite; tuberculose.', 'Tromboflebite superficial: veia com trombo, sem necrose fibrinoide.', 'Vasculite ANCA: pequeno e médio vaso, ANCA.'],
    next: ['Orceína para a lâmina elástica (artéria x veia); ANCA e sorologias.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'septic-vasculitis',
    name: 'Vasculite séptica / êmbolos sépticos',
    aka: ['Gonococcemia', 'Meningococcemia', 'Endocardite'],
    patterns: ['vasculitis'],
    clinical: ['fever', 'acute', 'purpura', 'pustule', 'acral', 'arthralgia', 'immunosuppression', 'petechiae'],
    histology: ['thrombi', 'lcv', 'bacteria', 'neutrophils-dermis', 'subcorneal-pustule', 'rbc-extravasation', 'papillary-edema'],
    hallmarks: ['thrombi', 'bacteria'],
    frequency: 1,
    summary: 'Pústulas hemorrágicas acrais em paciente febril; vasculite com trombos de fibrina e neutrófilos dentro do lúmen, pústula intraepidérmica e, às vezes, bactérias visíveis ao Gram.',
    clues: ['Trombos luminais com neutrófilos e vasculite ao mesmo tempo apontam para sepse, não para hipersensibilidade.', 'Pústula sobre púrpura é a marca clínica.'],
    mimics: ['LCV: sem trombos, sem pústula.', 'Púrpura fulminante / CIVD: trombos sem vasculite, hemorragia maciça.', 'Sweet: sem vasculite primária nem trombo.'],
    next: ['Gram, cultura da lesão e hemoculturas antes do antibiótico se possível.'],
    sources: [WEEDON],
  },
  {
    id: 'erythema-elevatum-diutinum',
    name: 'Eritema elevado diutino',
    patterns: ['vasculitis', 'neutrophilic', 'fibrosing'],
    clinical: ['extensor', 'hands', 'papule', 'nodule', 'chronic', 'arthralgia', 'immunosuppression', 'malignancy'],
    histology: ['lcv', 'neutrophils-dermis', 'sclerosis', 'foamy-histiocytes', 'diffuse-dermal-infiltrate'],
    hallmarks: ['lcv', 'sclerosis'],
    frequency: 1,
    summary: 'Pápulas e nódulos firmes vermelho-acastanhados sobre articulações de mãos e joelhos, persistentes por anos; vasculite leucocitoclástica crônica que vira fibrose concêntrica ao redor dos vasos com neutrófilos ainda presentes.',
    clues: ['LCV "velha" com fibrose lamelar e infiltrado neutrofílico difuso persistente.', 'Associada a gamopatia IgA, HIV e doença inflamatória intestinal.'],
    mimics: ['Granuloma facial: face, eosinófilos, zona de Grenz.', 'Sweet: sem vasculite primária, agudo.', 'Dermatofibroma / xantoma: sem vasculite.'],
    next: ['Eletroforese de proteínas e sorologia para HIV.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'granuloma-faciale',
    name: 'Granuloma facial',
    patterns: ['vasculitis', 'nodular-diffuse'],
    clinical: ['face', 'male', 'elderly', 'papule', 'nodule', 'chronic', 'asymptomatic', 'hyperpigmented'],
    histology: ['lcv', 'eosinophils', 'neutrophils-dermis', 'plasma-cells', 'diffuse-dermal-infiltrate', 'sclerosis', 'rbc-extravasation'],
    hallmarks: ['eosinophils', 'lcv'],
    frequency: 1,
    summary: 'Placa acastanhada solitária na face de homem de meia-idade, com óstios dilatados; infiltrado dérmico denso e misto rico em eosinófilos, separado da epiderme por zona de Grenz, com vasculite leucocitoclástica focal e fibrose perivascular.',
    clues: ['Zona de Grenz nítida com infiltrado misto (eosinófilos, neutrófilos, plasmócitos) e vasculite discreta.', 'Não é granulomatoso apesar do nome.'],
    mimics: ['Eritema elevado diutino: extensores, menos eosinófilos.', 'Sarcoidose: granulomas.', 'Linfoma B / pseudolinfoma: folículos, sem vasculite, sem eosinófilos tantos.', 'Sweet: sem Grenz, sem eosinófilos.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'cryoglobulinemic-vasculitis',
    name: 'Crioglobulinemia',
    patterns: ['vasculitis'],
    clinical: ['purpura', 'legs', 'cold', 'ulcer', 'livedo', 'acral', 'liver', 'malignancy', 'arthralgia', 'chronic'],
    histology: ['lcv', 'thrombi', 'rbc-extravasation', 'amyloid', 'neutrophils-dermis'],
    hallmarks: ['thrombi', 'lcv'],
    frequency: 1,
    summary: 'Púrpura de pernas, acrocianose e úlceras piores no frio; tipo I (monoclonal) dá trombos hialinos PAS-positivos sem inflamação, tipos II e III (mistas, hepatite C) dão vasculite leucocitoclástica.',
    clues: ['Material eosinofílico homogêneo PAS-positivo dentro do lúmen sem vasculite = crioglobulina monoclonal.', 'Vasculite leucocitoclástica com hepatite C ou gamopatia = mista.'],
    mimics: ['LCV comum: sem trombos.', 'Vasculopatia livedoide: trombos hialinos de fibrina e vasos com parede hialinizada, sem crioglobulina.', 'Púrpura fulminante: trombos com necrose extensa e sepse.'],
    next: ['Crioglobulinas (coleta aquecida), hepatite C, complemento e eletroforese.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'pigmented-purpuric-dermatosis',
    name: 'Dermatose purpúrica pigmentar',
    aka: ['Púrpura de Schamberg', 'Púrpura pigmentar crônica', 'Líquen aureus', 'Púrpura de Majocchi'],
    patterns: ['perivascular-superficial', 'interface-lichenoid'],
    clinical: ['legs', 'petechiae', 'chronic', 'asymptomatic', 'itch', 'hyperpigmented', 'annular', 'venous'],
    histology: ['rbc-extravasation', 'lymphocytic-superficial', 'sparse-infiltrate', 'band-like', 'spongiosis', 'dilated-vessels', 'pigment-incontinence'],
    hallmarks: ['rbc-extravasation'],
    against: ['lcv', 'thrombi', 'atypical-lymphocytes'],
    frequency: 3,
    summary: 'Máculas em pimenta-de-caiena nas pernas, assintomáticas ou levemente pruriginosas; hemácias extravasadas e hemossiderina ao redor de capilares da derme papilar com infiltrado linfocitário, sem fibrina nem leucocitoclasia.',
    clues: ['Capilarite: linfócitos ao redor de capilares dilatados com hemácias e hemossiderina, sem vasculite verdadeira.', 'Líquen aureus: infiltrado em faixa denso com hemossiderina abundante; lesão única dourada.'],
    mimics: [
      'Micose fungoide: variante purpúrica; se houver atipia e epidermotropismo, IHQ e clone.',
      'Vasculite leucocitoclástica velha: pode ser indistinguível; história de púrpura palpável.',
      'Dermatite de estase: espongiose, vasos neoformados lobulares na derme reticular.',
      'Púrpura por fármaco ou trombocitopenia: hemorragia sem inflamação.',
    ],
    next: ['Perls para hemossiderina; se lesões extensas e persistentes, IHQ CD4/CD8/CD7.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'livedoid-vasculopathy',
    name: 'Vasculopatia livedoide',
    aka: ['Atrofia branca', 'Livedo reticular com úlceras de verão'],
    patterns: ['vasculitis'],
    clinical: ['legs', 'acral', 'ulcer', 'atrophy', 'livedo', 'pain', 'chronic', 'relapsing', 'female', 'venous'],
    histology: ['thrombi', 'sclerosis', 'rbc-extravasation', 'sparse-infiltrate', 'dilated-vessels', 'atrophy-epidermis'],
    hallmarks: ['thrombi'],
    against: ['lcv', 'neutrophils-dermis'],
    frequency: 1,
    summary: 'Úlceras dolorosas em tornozelos que cicatrizam como atrofia branca estrelada; trombos de fibrina nos vasos da derme superficial com hialinização segmentar da parede e quase nenhuma inflamação.',
    clues: ['Vasos papilares com parede hialina e fibrina no lúmen, sem neutrófilos: "vasculopatia, não vasculite".', 'Investigar trombofilias, anticorpos antifosfolípides e insuficiência venosa.'],
    mimics: ['LCV: neutrófilos e poeira nuclear.', 'Crioglobulinemia tipo I: trombos PAS+ e proteína sérica.', 'Dermatite de estase ulcerada: proliferação vascular, hemossiderina, sem trombos hialinos.', 'Calcifilaxia: cálcio em vasos do subcutâneo.'],
    next: ['Painel de trombofilia e antifosfolípide; Doppler venoso.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'thrombotic-vasculopathy',
    name: 'Vasculopatia trombótica (púrpura fulminante, antifosfolípide, necrose por varfarina, heparina)',
    aka: ['CIVD', 'Síndrome antifosfolípide', 'Necrose cumarínica'],
    patterns: ['vasculitis'],
    clinical: ['acute', 'livedo', 'purpura', 'ulcer', 'fever', 'drug', 'autoimmune', 'malignancy', 'pain', 'petechiae'],
    histology: ['thrombi', 'rbc-extravasation', 'full-thickness-necrosis', 'sparse-infiltrate', 'fat-necrosis'],
    hallmarks: ['thrombi'],
    against: ['lcv'],
    frequency: 1,
    summary: 'Púrpura retiforme com necrose em paciente grave, anticoagulado ou com antifosfolípide; trombos de fibrina em vasos de todos os calibres sem inflamação da parede, com hemorragia e infarto da pele.',
    clues: ['Muitos vasos ocluídos e nenhum inflamado; necrose epidérmica e dérmica por isquemia.', 'Necrose por varfarina: dias 3 a 5, em mama, coxa e abdome; heparina: no sítio da injeção ou a distância.'],
    mimics: ['Vasculite séptica: trombos com neutrófilos e vasculite.', 'Calcifilaxia: cálcio na parede de arteríolas subcutâneas (von Kossa).', 'Êmbolos de colesterol: fendas em agulha no lúmen arteriolar.', 'Crioglobulinemia tipo I: trombos PAS+ e frio.'],
    next: ['Coagulograma, plaquetas, antifosfolípides, proteínas C e S; von Kossa se houver cálcio.'],
    sources: [WEEDON, MCKEE],
  },
  {
    id: 'cholesterol-emboli',
    name: 'Embolização por cristais de colesterol',
    patterns: ['vasculitis'],
    clinical: ['elderly', 'male', 'legs', 'acral', 'livedo', 'ulcer', 'trauma', 'pain', 'acute', 'renal'],
    histology: ['needle-clefts', 'thrombi', 'foreign-body-giant-cells', 'rbc-extravasation', 'fat-necrosis'],
    hallmarks: ['needle-clefts', 'thrombi'],
    frequency: 1,
    summary: 'Livedo e dedos azuis após cateterismo ou anticoagulação em ateromatoso; fendas em agulha (cristais dissolvidos) dentro de arteríolas da derme profunda e subcutâneo, com reação de células gigantes e fibrose intimal.',
    clues: ['Fendas biconvexas vazias no lúmen de arteríolas, às vezes só no subcutâneo: cortes seriados e biópsia profunda.', 'Pulsos preservados e eosinofilia periférica.'],
    mimics: ['Calcifilaxia: cálcio, não fendas.', 'Vasculopatia trombótica: fibrina sem fendas.', 'Paniculite com fendas em agulha (esclerema, necrose gordurosa neonatal): cristais nos adipócitos, não nos vasos.'],
    next: ['Cortes seriados profundos; eosinófilos no sangue e função renal.'],
    sources: [WEEDON],
  },
  {
    id: 'perniosis',
    name: 'Perniose',
    aka: ['Eritema pérnio', 'Frieiras', 'Lúpus pérnio-símile'],
    patterns: ['perivascular-deep', 'interface-vacuolar'],
    clinical: ['cold', 'acral', 'papule', 'nodule', 'itch', 'pain', 'female', 'young-adult', 'relapsing', 'autoimmune'],
    histology: ['superficial-and-deep', 'papillary-edema', 'lymphocytic-vasculitis', 'vacuolar', 'periadnexal', 'necrotic-keratinocytes', 'lymphocytic-superficial'],
    hallmarks: ['papillary-edema', 'lymphocytic-vasculitis'],
    frequency: 2,
    summary: 'Pápulas violáceas dolorosas em dedos, orelhas e calcanhares após frio úmido; edema papilar intenso com infiltrado linfocitário superficial e profundo que "envolve" vasos e glândulas écrinas, com interface discreta.',
    clues: ['Edema papilar exuberante e infiltrado linfocitário perivascular "em manguito" até o plexo profundo, com periécrino.', 'Lúpus-pérnio (chilblain lupus) tem a mesma imagem com mucina e banda lúpica; anticorpos e TREX1.'],
    mimics: ['Lúpus pérnio (chilblain lupus): mucina, IF positiva, membrana basal espessa.', 'Vasculite leucocitoclástica: neutrófilos, fibrina.', 'Crioglobulinemia: trombos.', 'Erupção polimorfa à luz: fotoexposta, sem frio.'],
    next: ['FAN, crioglobulinas e aglutininas frias quando persistente ou fora do inverno.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'polymorphous-light-eruption',
    name: 'Erupção polimorfa à luz',
    patterns: ['perivascular-deep', 'spongiotic'],
    clinical: ['photoexposed', 'sun', 'female', 'young-adult', 'papule', 'vesicle', 'itch', 'relapsing', 'acute', 'photosensitive'],
    histology: ['papillary-edema', 'superficial-and-deep', 'lymphocytic-superficial', 'spongiosis', 'periadnexal', 'eosinophils'],
    hallmarks: ['papillary-edema', 'superficial-and-deep'],
    against: ['mucin', 'vacuolar', 'bmz-thickening'],
    frequency: 2,
    summary: 'Pápulas e vesículas pruriginosas em V do decote e antebraços horas a dias após as primeiras exposições solares da estação; edema papilar marcado com infiltrado linfocitário perivascular superficial e profundo e espongiose variável.',
    clues: ['Edema papilar intenso é o achado mais constante; sem dano de interface ou mucina significativos.', 'Poupa a face habitualmente exposta ("hardening").'],
    mimics: ['Lúpus túmido: mucina abundante, sem edema tão marcado.', 'Lúpus subagudo: interface.', 'Picada de artrópode: eosinófilos em cunha.', 'Fotoalergia a fármaco: espongiose e eosinófilos, cronologia.', 'Prurigo actínico: queilite e conjuntivite, folículos linfoides; população indígena das Américas.'],
    sources: [WEEDON, ACKERMAN],
  },
  {
    id: 'erythema-migrans',
    name: 'Eritema migratório (borreliose de Lyme)',
    patterns: ['perivascular-deep', 'perivascular-superficial'],
    clinical: ['annular', 'insect', 'travel', 'trunk', 'acute', 'fever', 'asymptomatic'],
    histology: ['superficial-and-deep', 'plasma-cells', 'eosinophils', 'lymphocytic-superficial', 'sparse-infiltrate', 'periadnexal'],
    hallmarks: ['plasma-cells'],
    frequency: 1,
    summary: 'Anel que se expande a partir da picada de carrapato, com centro claro; infiltrado linfocitário perivascular superficial e profundo com plasmócitos e alguns eosinófilos, no centro (picada) e na borda.',
    clues: ['Plasmócitos num infiltrado perivascular "banal" de placa anular são a pista.', 'Sorologia é frequentemente negativa nas primeiras semanas.'],
    mimics: ['Eritema anular centrífugo: sem plasmócitos, infiltrado em manga.', 'Picada de artrópode: eosinófilos em cunha, sem expansão anular.', 'Tinha corporis: PAS.', 'Lúpus túmido: mucina.'],
    next: ['Sorologia em duas etapas; história de área endêmica.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'dress',
    name: 'DRESS (reação a fármaco com eosinofilia e sintomas sistêmicos)',
    aka: ['Síndrome de hipersensibilidade a fármaco'],
    patterns: ['perivascular-superficial', 'interface-vacuolar', 'spongiotic'],
    clinical: ['drug', 'fever', 'generalized', 'erythroderma', 'subacute', 'face', 'macule', 'papule', 'pustule'],
    histology: ['eosinophils', 'vacuolar', 'necrotic-keratinocytes', 'spongiosis', 'papillary-edema', 'atypical-lymphocytes', 'superficial-and-deep', 'lymphocytic-superficial'],
    hallmarks: ['eosinophils'],
    frequency: 1,
    summary: 'Exantema que vira eritrodermia com edema facial, febre, linfonodomegalia, eosinofilia e hepatite 2 a 8 semanas após anticonvulsivante, alopurinol ou sulfa; histologia de erupção medicamentosa "com tudo": interface, espongiose, eosinófilos e linfócitos atípicos.',
    clues: ['Mais de um padrão no mesmo corte, com eosinófilos e linfócitos ativados; a intensidade é maior que na erupção morbiliforme simples.', 'A lâmina não faz o diagnóstico: RegiSCAR faz.'],
    mimics: ['Erupção morbiliforme simples: sem sintomas sistêmicos.', 'Micose fungoide eritrodérmica: atipia com clone, sem fármaco.', 'PEGA: pústulas subcórneas, início em 1 a 3 dias.', 'Exantema viral (HHV-6 reativa no DRESS): confunde de propósito.'],
    next: ['Hemograma, transaminases, creatinina; suspender o fármaco.'],
    sources: [WEEDON, BOLOGNIA],
  },
  {
    id: 'degos-disease',
    name: 'Papulose atrófica maligna (Degos)',
    patterns: ['vasculitis', 'interface-vacuolar'],
    clinical: ['young-adult', 'trunk', 'papule', 'atrophy', 'chronic', 'pain', 'autoimmune'],
    histology: ['wedge-infiltrate', 'thrombi', 'mucin', 'atrophy-epidermis', 'vacuolar', 'sclerosis', 'sparse-infiltrate', 'lymphocytic-vasculitis'],
    hallmarks: ['wedge-infiltrate', 'thrombi', 'mucin'],
    frequency: 1,
    summary: 'Pápulas com centro branco-porcelana deprimido e halo eritematoso; infarto dérmico em cunha com epiderme atrófica, mucina e esclerose, causado por trombose de arteríola na ponta da cunha.',
    clues: ['Cunha de necrose isquêmica com vaso trombosado no vértice; mucina abundante e interface no ápice.', 'Forma sistêmica com perfuração intestinal e neurológica; forma cutânea benigna existe.'],
    mimics: ['Lúpus (variante "Degos-like"): banda lúpica e sorologia.', 'Vasculopatia livedoide: sem cunha nem mucina.', 'Pitiríase liquenoide: paraceratose, hemácias na epiderme.'],
    sources: [WEEDON, MCKEE],
  },
]
